### ISSUE TITLE
How to change increase playback speed with sound speed ?

### ISSUE THREAD

**Issue by gabong** [Bilibili/ijkplayer#1000]
How to change increase playback speed with sound speed ?

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/search?utf8=✓&q=setSpeed

**Comment by gabong** [comment]
Thank you

**Comment by MarcSteven** [comment]
@bbcallen  But in iOS, how to make this happen?  There is no method named set speed
