### ISSUE TITLE
软/硬解码来回切换不生效

### ISSUE THREAD

**Issue by zourb** [Bilibili/ijkplayer#1001]
在同一个Activity实例中，默认是硬解码，当点击按钮切换成软解码时候生效，并且CPU使用率有显著增高；再次点击按钮切换我硬解码时，CPU使用率依然很高，而且有明显卡顿的现象，感觉是从软解切换成硬解没有生效。切换过程的option log如下
I/IJKMEDIA: ===== options =====
I/IJKMEDIA: player-opts : overlay-format               = 842225234
I/IJKMEDIA: player-opts : framedrop                    = 12
I/IJKMEDIA: player-opts : mediacodec                   = 1
I/IJKMEDIA: format-opts : http-detect-range-support    = 0
I/IJKMEDIA: format-opts : user_agent                   = ijkplayer
I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
I/IJKMEDIA: ===================

I/IJKMEDIA: ===== options =====
I/IJKMEDIA: player-opts : overlay-format               = 842225234
I/IJKMEDIA: player-opts : framedrop                    = 12
I/IJKMEDIA: player-opts : mediacodec                   = 0
I/IJKMEDIA: format-opts : http-detect-range-support    = 0
I/IJKMEDIA: format-opts : user_agent                   = ijkplayer
I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
I/IJKMEDIA: ===================

I/IJKMEDIA: ===== options =====
I/IJKMEDIA: player-opts : overlay-format               = 842225234
I/IJKMEDIA: player-opts : framedrop                    = 12
I/IJKMEDIA: player-opts : mediacodec                   = 1
I/IJKMEDIA: format-opts : http-detect-range-support    = 0
I/IJKMEDIA: format-opts : user_agent                   = ijkplayer
I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
I/IJKMEDIA: ===================

**Comment by linwea** [comment]
软解硬解怎么切换？

**Comment by edwardZj** [comment]
修改settings里面的设置，然后重新setVideoPath
