### ISSUE TITLE
关于视频直播的视频流拉取问题

### ISSUE THREAD

**Issue by yinxianwu** [Bilibili/ijkplayer#1004]
我的英文比较差，如果用英文我怕描述不清晰，抱歉。
这样的一个问题，我用播放器做视频直播，当我进入一个房间的时候如果有人直播我就初始化播放器像这样{
    [IJKMediaModule sharedModule].appIdleTimerDisabled = YES;
    [IJKFFMoviePlayerController checkIfFFmpegVersionMatch:YES];
    IJKFFOptions * options = [IJKFFOptions optionsByDefault];
    [options setFormatOptionValue:@"ijktcphook" forKey:@"http-tcp-hook"];
    NSURL *theMovieURL = [NSURL URLWithString:self.videoUrl];
    self.player = [[IJKFFMoviePlayerController alloc] initWithContentURL:theMovieURL withOptions:options];
    self.player.scalingMode = IJKMPMovieScalingModeAspectFit;
    self.player.shouldAutoplay = YES;
    [self insertSubview:self.player.view belowSubview:self.loadingLabel];
    [self.player prepareToPlay];
} 
在直播过程中，如果我发现房间没人在了，那么我需要停止播放。当又有人直播的时候我就重新开始播放
然后我是这样处理的，停止播放 我就直接 [_player shutdown];
重新直播的话 我会把上面初始化所有步骤重新来一次。 我这样处理是否有问题；

**Comment by bbcallen** [comment]
Did you encounter any problem?

**Comment by yinxianwu** [comment]
之前的问题我使用了  [_player shutdown]; 然后立马重新设置播放器 导致之前的播放器没有关闭掉 会多开一个播放器

**Comment by bbcallen** [comment]
Do you mean previous player is not closed immediately or not closed forever (leak)?

**Comment by yinxianwu** [comment]
对啊，是不是不应该多次的shutdown init
我是否可以通过某一种方法可以dealloc 一个player 
因为我每次init 之前的来不及shutdown的话 播放器会存在多个

**Comment by bbcallen** [comment]
```
- (void)shutdown
{
    if (!_mediaPlayer)
        return;

    [self stopHudTimer];
    [self unregisterApplicationObservers];
    [self setScreenOn:NO];

    // modify the code, call shutdownWaitStop directly. 
    [self performSelectorInBackground:@selector(shutdownWaitStop:) withObject:self];
}
```

**Comment by yinxianwu** [comment]
ok 我试试 感谢

**Comment by yinxianwu** [comment]
因为shutdown 不会直接在主线程里面调用 所以存在一个时间的问题 需要我这边去处理

**Comment by blueseaguo** [comment]
@yinxianwu 这个你解决没有？？这创建多个view，感觉这样不是很好吧，能不能做到像avplayer那样，替换正在播放的那个

**Comment by yinxianwu** [comment]
@blueseaguo  我也想啊 不知道具体怎么处理

**Comment by yinxianwu** [comment]
@bbcallen  多次的这样shutdown init 是否有一种方法我直接可以设置url 当url更新的时候播放器重新播放

**Comment by bbcallen** [comment]
No.

**Comment by yinxianwu** [comment]
额 好吧 谢谢！
还有一个小问题，进入直播间播放视频流出现下面问题是什么原因呢（偶发），出现下面问题之后整个app就锁死。 @bbcallen 

aout_open_audio()
aout_pause_audio(0)
vtb fail!!! switch to ffmpeg decode!!!! 
ijkmp_get_msg: FFP_MSG_PREPARED
SDL_VoutFFmpeg_CreateOverlay(w=640, h=480, fmt=I420(0x30323449, dp=0x14747a620)
Video: first frame decoded
SDL_VoutFFmpeg_CreateOverlay(w=640, h=480, fmt=I420(0x30323449, dp=0x14747a620)
SDL_VoutFFmpeg_CreateOverlay(w=640, h=480, fmt=I420(0x30323449, dp=0x14747a620)
2016-03-12 14:51:46.228 FansClient[2745:1236222] OK use I420 GL renderer
2016-03-12 14:51:46.231 FansClient[2745:1236222] OK setup GL programm
2016-03-12 14:51:46.233 FansClient[2745:1236222] OK setup GL framebuffer 640:480
avcodec/Audio: first frame decoded

**Comment by bbcallen** [comment]
No idea without debug.

**Comment by zwy2937** [comment]
可以增加在shutdown真正结束后的回调吗

**Comment by zwy2937** [comment]
@bbcallen
