### ISSUE TITLE
是否可以设置大的缓冲区，在播放完一次后重新播放能直接从缓冲区获取数据

### ISSUE THREAD

**Issue by cwq** [Bilibili/ijkplayer#101]
Android中的mediaplayer是播放完后重新播放就不会重新从http获取的

**Comment by SevenJustin** [comment]
@bbcallen 可以说说在哪里设置缓存的地方吗，我现在需要知道如何能缓存视频后再播放就直接读取缓存！

**Comment by bbcallen** [comment]
No such option, for now.

**Comment by Stewarddeng** [comment]
well
