### ISSUE TITLE
compile ffmpeg show "you need the NDKr9 or later"

### ISSUE THREAD

**Issue by conhow** [Bilibili/ijkplayer#1012]
eg.sh all
====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a arm64 x86 x86_64
FF_ACT_ARCHS = armv5 armv7a arm64 x86 x86_64

====================
[*] check env armv5
====================
build on Linux x86_64
ANDROID_SDK=/home/wangjizhong/Downloads/Sdk/Sdk/
ANDROID_NDK=/home/wangjizhong/Downloads/android-ndk-r9d/

You need the NDKr9 or later

**Comment by MROU** [comment]
NDK  **# r10e**
Android Studio 1.4
Gradle 2.6

https://github.com/Bilibili/ijkplayer/blob/master/README.md   My Build Environment

**Comment by cjztool** [comment]
Maybe put a RELEASE.TXT file with content 'r10e' into your NDK dir can solve...
