### ISSUE TITLE
when i compile file "compile-ffmpeg.sh" ,it show error "No such file or directory".

### ISSUE THREAD

**Issue by conhow** [Bilibili/ijkplayer#1014]
wangjihzong@ubuntu:~/ijkplayer-android/android/contrib$ sh ./compile-ffmpeg.sh all
====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a arm64 x86 x86_64
FF_ACT_ARCHS = armv5 armv7a arm64 x86 x86_64

====================
[*] check env armv5
====================
build on Linux x86_64
ANDROID_SDK=/home/wangjihzong/Downloads/Sdk/Sdk
ANDROID_NDK=/home/wangjihzong/android-ndk-r10
NDKr10 detected

--------------------
[*] make NDK standalone toolchain
--------------------
Copying prebuilt binaries...
Copying sysroot headers and libraries...
Copying c++ runtime headers and libraries...
Copying files to: /home/wangjihzong/ijkplayer-android/android/contrib/build/ffmpeg-armv5/toolchain
Cleaning up...
Done.

--------------------
[*] check ffmpeg env
--------------------

--------------------
[*] configurate ffmpeg
--------------------
tools/do-compile-ffmpeg.sh: line 302: cd: /home/wangjihzong/ijkplayer-android/android/contrib/ffmpeg-armv5: No such file or directory

**Comment by CrazyDude1994** [comment]
Update your git to version 2.7.* You probably have 1.9.*

**Comment by conhow** [comment]
I have update the git version to 2.7.2 . then,it also have error.

root@ubuntu:/home/wangjihzong/ijkplayer-android/android/contrib# ./compile-ffmpeg.sh clean
====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a arm64 x86 x86_64
FF_ACT_ARCHS = FF_ACT_ARCHS_64

/home/wangjihzong/ijkplayer-android/android/contrib
root@ubuntu:/home/wangjihzong/ijkplayer-android/android/contrib# ./compile-ffmpeg.sh all
====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a arm64 x86 x86_64
FF_ACT_ARCHS = armv5 armv7a arm64 x86 x86_64

====================
[*] check env armv5
====================
build on Linux x86_64
ANDROID_SDK=/home/wangjihzong/Downloads/Sdk/Sdk
ANDROID_NDK=/home/wangjihzong/android-ndk-r10
NDKr10 detected

--------------------
[*] make NDK standalone toolchain
--------------------
Copying prebuilt binaries...
Copying sysroot headers and libraries...
Copying c++ runtime headers and libraries...
Copying files to: /home/wangjihzong/ijkplayer-android/android/contrib/build/ffmpeg-armv5/toolchain
Cleaning up...
Done.

--------------------
[*] check ffmpeg env
--------------------

--------------------
[*] configurate ffmpeg
--------------------
/home/wangjihzong/ijkplayer-android/android/contrib/build/ffmpeg-armv5/toolchain/bin//arm-linux-androideabi-gcc
tools/do-compile-ffmpeg.sh: line 307: ./configure: No such file or directory
root@ubuntu:/home/wangjihzong/ijkplayer-android/android/contrib# git --version
git version 2.7.2
root@ubuntu:/home/wangjihzong/ijkplayer-android/android/contrib#

**Comment by CrazyDude1994** [comment]
Have you launched ./init-android.sh before ffmpeg build?

**Comment by conhow** [comment]
when i launched ./compile-ffmpeg.sh, it show that:

link libswresample/arm/*.o
link libswscale/*.o

--------------------
[*] create files for shared ffmpeg
--------------------
====================
[*] check env arm64
====================
build on Linux x86_64
ANDROID_SDK=/home/wangjihzong/Downloads/Sdk/Sdk
ANDROID_NDK=/home/wangjihzong/android-ndk-r10
NDKr10 detected

--------------------
[*] make NDK standalone toolchain
--------------------
Invalid platform name: android-21
Please use --platform=<name> with one of: android-12 android-13 android-14 android-15 android-16 android-17 android-18 android-19 android-3 android-4 android-5 android-8 android-9

**Comment by conhow** [comment]
thank you very much!
