### ISSUE TITLE
请问IJKFFMoviePlayerController怎么静音 和非静音， 是在找不到怎么解决了

### ISSUE THREAD

**Issue by QLyuanqing** [Bilibili/ijkplayer#1015]
请问IJKFFMoviePlayerController怎么静音 和非静音， 是在找不到怎么解决了

**Comment by bbcallen** [comment]
There is no mute/unmute API in ijkplayer.

**Comment by youhui** [comment]
the same question, How to solve？

**Comment by bbcallen** [comment]
mute/unmute system volume.

**Comment by youhui** [comment]
yes , i found it, thank you.

**Comment by edwincen** [comment]
set muted in ffplay should solve the problem

**Comment by blakelzy** [comment]
How to set?

**Comment by xinzhengzhang** [comment]
`IJKMediaPlayback`

**Comment by ceekay1991** [comment]
IJKMediaPlayback playbackVolume 取值范围是多少啊？@xinzhengzhang

**Comment by fake-car** [comment]
@ceekay1991  请问playbackVolume取值范围是多少？

**Comment by Android4MediaPlayer** [comment]
0.0-1.0

**Comment by fake-car** [comment]
3q
