### ISSUE TITLE
when i compile file "compile-ffmpeg.sh" ,it show error "Invalid platform name: android-21".

### ISSUE THREAD

**Issue by conhow** [Bilibili/ijkplayer#1017]
I can compile "armv5 armv7a" .but ,when i compile "x86_64",it show that:

[*] create files for shared ffmpeg
--------------------
====================
[*] check env arm64
====================
build on Linux x86_64
ANDROID_SDK=/home/wangjihzong/Downloads/Sdk/Sdk
ANDROID_NDK=/home/wangjihzong/android-ndk-r10
NDKr10 detected

--------------------
[*] make NDK standalone toolchain
--------------------
Invalid platform name: android-21
Please use --platform=<name> with one of: android-12 android-13 android-14 android-15 android-16 android-17 android-18 android-19 android-3 android-4 android-5 android-8 android-9

**Comment by bbcallen** [comment]
The log has told you what is wrong.

**Comment by rooque** [comment]
You need to update your SDK.

**Comment by FrankLove** [comment]
@bbcallen 为什么ijkplayer编译不用ndkr9d的话就报错 "you need ndk r9 or later"，用r9d又报错"Invalid platform name: android-21"，到底要怎么整啊，请问你们项目组测试过没有呢？ndk r9d用了报这个错，不用报哪个错，真是无语啊~~
