### ISSUE TITLE
 Does this player support "rtsp"?

### ISSUE THREAD

**Issue by liuyuejinqiu** [Bilibili/ijkplayer#1018]
Does this player support "rtsp"?

**Comment by bbcallen** [comment]
I don't know.
I've never tested "rtsp" myself.

**Comment by liuyuejinqiu** [comment]
thank you !

**Comment by rooque** [comment]
Yes, ijkplayer support it! You just need to change 'module.sh' for your
needs.

**Comment by liuyuejinqiu** [comment]
thank you,what should I change about?@rooque

**Comment by addskya** [comment]
@liuyuejinqiu  Pls Visit: https://github.com/Bilibili/ijkplayer/issues/1108
