### ISSUE TITLE
selectTrack() error

### ISSUE THREAD

**Issue by duckula0718** [Bilibili/ijkplayer#1023]
I downloaded newest zipped master source code and compiled demo successfully. But, When I switch audio track with selectTrack(), it dosen't  work properly：
(1) When I call it with current track index as param, the program crashed.
(2) When I call it to switch audio track several times, it may dosen't  work at all, or even make the video to be mute.
Please help !

**Comment by a4tech** [comment]
I want to add to IjKFFMoviePlayer

2 options:

- Change Video mode - 16:9, 4:3, pillar etc
- Add Volume change
- Add setTrack if it detect

I think We need to code such methods for that.
Any example appreciate.

**Comment by bbcallen** [comment]
selectTrack() is an experimental feature, for now.

**Comment by linwea** [comment]
selectTrack() can use but have bug ,after use selectTrack image and sound not synchronous

**Comment by wqmijkplayer** [comment]
@bbcallen @linwea I have aslo this av sync issue in my project, Audio stamp is earlyer than Video stamp, Any suggestion about this issue？

**Comment by Peterede** [comment]
You could try a seekTo after changing the audio and this could help sync.

**Comment by Peterede** [comment]
The problem appears to be that this function is called directly on the native code instead of being handled like seekTo which is put into a message queue.  I have code from over a year ago which has worked that behaves like seekTo, I will migrate this to the latest code and share it.

**Comment by Peterede** [comment]
You can download the updated files from [https://drive.google.com/open?id=0B5bgWvRM9MhgZlBJT253eFRwLU0](url).

**Comment by duckula0718** [comment]
Thank you very very much for helping. I'll update it and try.
In the past weeks, We found another way to resolve the problem: We decode both audio track all the time, but only select one of them (accoding to the selected track index) to ouput. It works on our platfrom and the extra memory cost is acceptable.
However, we still looking forward to the "official" solution.



duckula0718@gmail.com
 
From: Peterede
Date: 2016-04-15 14:03
To: Bilibili/ijkplayer
CC: duckula0718
Subject: Re: [Bilibili/ijkplayer] selectTrack() error (#1023)
You can download the updated files from https://drive.google.com/open?id=0B5bgWvRM9MhgZlBJT253eFRwLU0.

**Comment by bbcallen** [comment]
Sorry, I would say, it's very unlikely in my recent plan.
