### ISSUE TITLE
Cannot play .mkv and .avi video files?

### ISSUE THREAD

**Issue by mianharisali** [Bilibili/ijkplayer#1024]
Cannot play .mkv and .avi video files?
i am using sample video player on android, any help?

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer#before-build
Try switch to config/module-default.sh

**Comment by mianharisali** [comment]
oh thanks , it worked :)

**Comment by SUSHILl-NICS** [comment]
please suggest me how i will use ijkplayer to play all kind of videos,currently i acan play only mp4 and flv in android
