### ISSUE TITLE
i want to modify the ijkplayer/ijkmedia source . 

### ISSUE THREAD

**Issue by conhow** [Bilibili/ijkplayer#1027]
我想修改ijkplayer 中，ijkmedia 里视频处理的内容，我想问下，使用什么编译工具，具体是什么步骤，再修改代码时能自动关联代码，进行修改，并进行生成so的。

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer#my-build-environment

**Comment by conhow** [comment]
但是，每次修改ijkplayer/ijkmedia 部分源码后，只能打包so进行调试。没有办法，直接 将ijkmedia导入工程里进行修改自动编译吗？
