### ISSUE TITLE
播放过程中自动播放结束[实际并不该播放结束]

### ISSUE THREAD

**Issue by var1993** [Bilibili/ijkplayer#1029]
50分钟26秒的视频，播放到十几分钟后自动播放结束，
log：

03-14 15:43:40.082 12554-12941/tv.danmaku.ijk.media.sample W/IJKMEDIA: No trailing CRLF found in HTTP header.
03-14 15:43:40.082 12554-12941/tv.danmaku.ijk.media.sample W/IJKMEDIA: Failed to open segment of playlist 0
03-14 15:43:40.082 12554-12941/tv.danmaku.ijk.media.sample I/IJKMEDIA: HLS request for url 'http://222.73.137.16/697AB11752137810D09B976F3E/030001100F56CB751CF8B204B921BFE8EE5F85-67D8-420C-7517-17F4DAEFC719.flv.ts?ts_start=90.58&ts_end=102.58&ts_seg_no=260&ts_keyframe=1', offset 0, playlist 0
03-14 15:43:40.082 12554-12941/tv.danmaku.ijk.media.sample W/IJKMEDIA: No trailing CRLF found in HTTP header.
03-14 15:43:40.082 12554-12941/tv.danmaku.ijk.media.sample W/IJKMEDIA: Failed to open segment of playlist 0
03-14 15:43:40.082 12554-12941/tv.danmaku.ijk.media.sample I/IJKMEDIA: HLS request for url 'http://222.73.137.16/697AB11752137810D09B976F3E/030001100F56CB751CF8B204B921BFE8EE5F85-67D8-420C-7517-17F4DAEFC719.flv.ts?ts_start=102.58&ts_end=114.58&ts_seg_no=261&ts_keyframe=1', offset 0, playlist 0
03-14 15:43:40.082 12554-12941/tv.danmaku.ijk.media.sample W/IJKMEDIA: No trailing CRLF found in HTTP header.
03-14 15:43:40.082 12554-12941/tv.danmaku.ijk.media.sample W/IJKMEDIA: Failed to open segment of playlist 0
03-14 15:43:40.082 12554-12941/tv.danmaku.ijk.media.sample I/IJKMEDIA: HLS request for url 'http://222.73.137.16/697AB11752137810D09B976F3E/030001100F56CB751CF8B204B921BFE8EE5F85-67D8-420C-7517-17F4DAEFC719.flv.ts?ts_start=114.58&ts_end=126.58&ts_seg_no=262&ts_keyframe=1', offset 0, playlist 0
03-14 15:43:40.082 12554-12941/tv.danmaku.ijk.media.sample W/IJKMEDIA: No trailing CRLF found in HTTP header.
03-14 15:43:40.082 12554-12941/tv.danmaku.ijk.media.sample W/IJKMEDIA: Failed to open segment of playlist 0
03-14 15:43:40.082 12554-12941/tv.danmaku.ijk.media.sample I/IJKMEDIA: HLS request for url 'http://222.73.137.16/697AB11752137810D09B976F3E/030001100F56CB751CF8B204B921BFE8EE5F85-67D8-420C-7517-17F4DAEFC719.flv.ts?ts_start=126.58&ts_end=138.58&ts_seg_no=263&ts_keyframe=1', offset 0, playlist 0
03-14 15:43:40.082 12554-12941/tv.danmaku.ijk.media.sample W/IJKMEDIA: No trailing CRLF found in HTTP header.
03-14 15:43:40.082 12554-12941/tv.danmaku.ijk.media.sample W/IJKMEDIA: Failed to open segment of playlist 0
03-14 15:43:40.082 12554-12941/tv.danmaku.ijk.media.sample I/IJKMEDIA: HLS request for url 'http://222.73.137.16/697AB11752137810D09B976F3E/030001100F56CB751CF8B204B921BFE8EE5F85-67D8-420C-7517-17F4DAEFC719.flv.ts?ts_start=138.58&ts_end=145.1&ts_seg_no=264&ts_keyframe=1', offset 0, playlist 0
03-14 15:43:40.082 12554-12941/tv.danmaku.ijk.media.sample W/IJKMEDIA: No trailing CRLF found in HTTP header.
03-14 15:43:40.082 12554-12941/tv.danmaku.ijk.media.sample W/IJKMEDIA: Failed to open segment of playlist 0
03-14 15:43:40.082 12554-12941/tv.danmaku.ijk.media.sample W/IJKMEDIA: PES packet size mismatch
03-14 15:43:40.082 12554-12941/tv.danmaku.ijk.media.sample D/IJKMEDIA: unknown SEI type 37
03-14 15:43:42.922 12554-13010/tv.danmaku.ijk.media.sample D/IJKMEDIA: Unknown NAL code: 0 (1424 bits)
03-14 15:43:48.622 12554-13003/tv.danmaku.ijk.media.sample D/IJKMEDIA: stereo with SCE
03-14 15:43:48.632 12554-13003/tv.danmaku.ijk.media.sample E/IJKMEDIA: Input buffer exhausted before END element found
03-14 15:43:48.922 12554-13010/tv.danmaku.ijk.media.sample D/IJKMEDIA: unknown SEI type 37
03-14 15:43:48.922 12554-13010/tv.danmaku.ijk.media.sample D/IJKMEDIA: Unknown NAL code: 0 (1424 bits)
03-14 15:43:48.962 12554-13010/tv.danmaku.ijk.media.sample D/IJKMEDIA: bytestream overread -8
03-14 15:43:48.962 12554-13010/tv.danmaku.ijk.media.sample E/IJKMEDIA: error while decoding MB 29 14, bytestream -8
03-14 15:43:48.972 12554-13010/tv.danmaku.ijk.media.sample I/IJKMEDIA: concealing 1880 DC, 1880 AC, 1880 MV errors in I frame
03-14 15:43:50.192 12554-12941/tv.danmaku.ijk.media.sample I/IJKMEDIA: ffp_toggle_buffering: completed: OK
03-14 15:43:50.192 12554-12939/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_COMPLETED
03-14 15:43:50.192 12554-12939/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_COMPLETED:
03-14 15:43:51.202 12554-12941/tv.danmaku.ijk.media.sample I/IJKMEDIA: ffp_toggle_buffering: eof

**Comment by bbcallen** [comment]
```
03-14 15:43:48.632 12554-13003/tv.danmaku.ijk.media.sample E/IJKMEDIA: Input buffer exhausted before END element found
03-14 15:43:48.922 12554-13010/tv.danmaku.ijk.media.sample D/IJKMEDIA: unknown SEI type 37
03-14 15:43:48.922 12554-13010/tv.danmaku.ijk.media.sample D/IJKMEDIA: Unknown NAL code: 0 (1424 bits)
03-14 15:43:48.962 12554-13010/tv.danmaku.ijk.media.sample D/IJKMEDIA: bytestream overread -8
```
Seems an FFmpeg issue.
Can you reproduce same problem with ffplay on PC?

**Comment by GrayLuo** [comment]
the same problem,
`IJK_GLES2_Renderer_TexCoords_cropRight2016-05-03 19:50:44.039 APP[1915:722404] FFP_MSG_VIDEO_RENDERING_START:
Sending bytes read report
Sending bytes read report
2016-05-03 19:51:34.900 APP[1915:722404] invalidateRenderBuffer
2016-05-03 19:51:34.901 APP[1915:722750] IJKSDLGLView: renderbufferStorage fromDrawable
Sending bytes read report
av_read_frame error: fffffffb(\377,\377,\377,\373): unknown
aout_pause_audio(1)
ffp_toggle_buffering: error: -5
av_read_frame error: fffffffb(\377,\377,\377,\373): unknown
2016-05-03 19:52:03.630 APP[1915:722404] FFP_MSG_ERROR: 0
IJK palyer state = 1, media state = 3

ffp_toggle_buffering: eof
`
then it wait here : 
`                    // infinite wait may block shutdown
                    while(!is->abort_request && !is->seek_req)
                        SDL_CondWaitTimeout(is->continue_read_thread, wait_mutex, 100);
`
Any suggestion?

**Comment by bbcallen** [comment]
No, I don't think there is anything more I can do.
You can dig into libavformat/mpegts.c or submit a issue at FFmpeg's trac site.

**Comment by GrayLuo** [comment]
av_read_frame error: fffffffb(\377,\377,\377,\373): unknown
aout_pause_audio(1)
ffp_toggle_buffering: error: -5
av_read_frame error: fffffffb(\377,\377,\377,\373): unknown
2016-05-04 13:34:43.910 APP[2149:808660] FFP_MSG_ERROR: 0
2016-05-04 13:34:43.911 APP[2149:808660] IJKMPMoviePlayBackStateDidChange 1: playing
2016-05-04 13:34:43.911 APP[2149:808660] playbackStateDidChange: **IJKMPMovieFinishReasonPlaybackError**: 1
ijkmp_stop()
ijkmp_stop()=0

How to reconnect the RTMP stream while got the error of  av_read_frame? How to recover？

**Comment by limbo0312** [comment]
同样遇到这个问题。长时间暂停之后，就进入这个waiting无法脱离了。

                    // infinite wait may block shutdown
                    while(!is->abort_request && !is->seek_req)
                        SDL_CondWaitTimeout(is->continue_read_thread, wait_mutex, 100);
