### ISSUE TITLE
Subtitle support?

### ISSUE THREAD

**Issue by mianharisali** [Bilibili/ijkplayer#1031]
Does this player support subtitles?
if yes , then any documentation?
i am using sample app in android.

**Comment by bbcallen** [comment]
No subtitle support, and I'm afraid it's very unlikely in my plan.

**Comment by mianharisali** [comment]
i hope you implement this feature , as many videos contain separate stream/track for subtitles.
and a good library should support that :)

**Comment by bbcallen** [comment]
Sorry, I have a full time job.
I don't have too much time to develop or maintain features not necessary to my employer.

Any how, pull request is welcome.

**Comment by mianharisali** [comment]
oh ok , btw i really appreciate your effort for this library , thumbs up (Y)
