### ISSUE TITLE
Android How to change ijkplayer to InternalMediaPlayer real time？

### ISSUE THREAD

**Issue by linwea** [Bilibili/ijkplayer#1032]
I am use surfaceView and MediaPlayer to play video，test use ijkplayer or InternalMediaPlayer both success too，I want to make a button switch between ijkplayer  and InternalMediaPlayer real time，
my method is  stop current MediaPlayer play and release it，reinit new MediaPlayer set datasource and prepareAsync. InternalMediaPlayer change ijkplayer is successful，but ijkplayer change to InternalMediaPlayer fail at prepareAsync when I setDislay() before prepareAsync,if I setDisplay() in onPrepare ,after MediaPlayer.start() logcat  without any message,but the video would not start.

**Comment by bbcallen** [comment]
Write your own wrapper.
InternalMediaPlayer is not designed for this.

**Comment by linwea** [comment]
I had use interface replace MediaPlayer,respectively including InternalMediaPlayer or  ijkplayer 2 new class implements this interface. 
I need to rewrite the setDisplay of InternalMediaPlayer?

**Comment by bbcallen** [comment]
It's more complicated.

You should follow the behavior described in Android's document
http://developer.android.com/intl/zh-cn/reference/android/media/MediaPlayer.html

Especially the "State Diagram" part.
