### ISSUE TITLE
编译通不过

### ISSUE THREAD

**Issue by jinch888d** [Bilibili/ijkplayer#1033]
使用mac系统Android ndk 10e/Android ndk 11都无法编译通过，执行到./compile-ffmpeg.sh all挂掉，找不到module-lite-hevc.sh

**Comment by jinch888d** [comment]
Mac OS X 10.10.5上面使用NKD R10d，NDK R11，NDK R10e，
git clone https://github.com/Bilibili/ijkplayer.git ijkplayer-android
cd ijkplayer-android
git checkout -B latest k0.4.5.1

./init-android.sh

cd android/contrib
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all

cd ..
./compile-ijk.sh all
按照顺序执行这几步，执行到./compile-ffmpeg.sh all，报出x86-64 need NDK r9 或者以上版本，将NDK替换成NDK R9d，执行这一步报出module-lite-hevc.sh，找不到文件

**Comment by jinch888d** [comment]
能不能给出正确的编译环境和编译工具以及步骤

**Comment by bbcallen** [comment]
Did you update your git client?

**Comment by bbcallen** [comment]
No, I can't. I'm not an expert of build tools.

**Comment by jinch888d** [comment]
执行到到config/module.sh的时候里面的module-lite-hevc.sh没法执行

**Comment by jinch888d** [comment]
请问你们编译的使用Android ijkplayer的时候使用的什么工具，不是Mac10.10.5，NDK使用的32位还是64位，编译之前要不要执行
cd config
rm module.sh
ln -s module-default.sh module.sh
cd android/contrib
# cd ios
sh compile-ffmpeg clean
这几步

**Comment by bbcallen** [comment]
I think they are already answered in README.

**Comment by reeonce** [comment]
for NDK r11, only gcc-4.9 is available. What I did was updating the `android/contrib/tools/do-compile-ffmpeg.sh` file with following changes.

```bash
-    9*|10*)
+    9*|10*|11*)

-        if test -d ${ANDROID_NDK}/toolchains/arm-linux-androideabi-4.8
+        if test -d ${ANDROID_NDK}/toolchains/arm-linux-androideabi-4.9


-FF_GCC_VER=4.8
+FF_GCC_VER=4.9

-        FF_MAKE_TOOLCHAIN_FLAGS="$FF_MAKE_TOOLCHAIN_FLAGS --system=darwin-x86_64"
+        # FF_MAKE_TOOLCHAIN_FLAGS="$FF_MAKE_TOOLCHAIN_FLAGS --system=darwin-x86_64"
```

For some `Application.mk`, updating `NDK_TOOLCHAIN_VERSION=4.8` to `NDK_TOOLCHAIN_VERSION=4.9` is required as well.

**Comment by loentar** [comment]
Toolchain autodetection for ndk11: https://gist.github.com/loentar/2be98bc2af8ee04f2268516ee1e7bc5c

**Comment by tianxiao875** [comment]
我是windows  编译的，最后提示IJk_NDK_REL=
You need the NKDr10e or later 怎么解决哇。我下载不到R11
