### ISSUE TITLE
视频黑屏，但是有声音

### ISSUE THREAD

**Issue by Catherine0728** [Bilibili/ijkplayer#1034]
我在重新加载了视频，然后出现黑屏，但是有声音的状态，是什么情况

**Comment by iamluodong** [comment]
一般情况下是缺少必要的解码器导致，比如ijk默认只带了h264解码code，但你的视频编码可能是mpeg2，or Rmvb?

**Comment by wuruize** [comment]
应该是和SDL渲染有关系。我们的播放器也是采用的SDL＋FFmpeg，部分机器也碰到了。

**Comment by Catherine0728** [comment]
你的意思是跟机型有关？@wurulze

**Comment by wuruize** [comment]
和系统版本，机型都有关系@Catherine0728
