### ISSUE TITLE
IjkMediaPlayer不能使用

### ISSUE THREAD

**Issue by jinch888d** [Bilibili/ijkplayer#1035]
IjkVideoView中使用IjkMediaPlayer几乎所有视频都不能播放，mp4格式有些有声音但是没有画面

03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer D/IJKMEDIA: ijkmp_set_data_source(url="http://192.168.0.176:8084/SSH/movies/ceshi.mkv")=0
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x80001d)
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer D/IJKMEDIA: ffpipeline_set_surface()
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x80001d)=void
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer D/IJKMEDIA: IjkMediaPlayer_prepareAsync
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer D/IJKMEDIA: ijkmp_prepare_async()
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer I/IJKMEDIA: ===== versions =====
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer I/IJKMEDIA: FFmpeg       : ff2.8--ijk0.4.1.1--dev0.3.3--rc4
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer I/IJKMEDIA: libavutil    : 54.31.100
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer I/IJKMEDIA: libavcodec   : 56.60.100
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer I/IJKMEDIA: libavformat  : 56.40.101
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer I/IJKMEDIA: libswscale   : 3.1.101
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer I/IJKMEDIA: libswresample: 1.2.101
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer I/IJKMEDIA: ===== options =====
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer I/IJKMEDIA: player-opts : mediacodec                   = 0
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer I/IJKMEDIA: player-opts : opensles                     = 0
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer I/IJKMEDIA: player-opts : overlay-format               = 842225234
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer I/IJKMEDIA: player-opts : framedrop                    = 1
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer I/IJKMEDIA: player-opts : start-on-prepared            = 0
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer I/IJKMEDIA: format-opts : ijkinject-opaque             = 491783422
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer I/IJKMEDIA: format-opts : http-detect-range-support    = 0
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer I/IJKMEDIA: format-opts : timeout                      = 10000000
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer I/IJKMEDIA: format-opts : reconnect                    = 1
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
03-15 13:36:20.318 23181-23181/tcking.github.com.giraffeplayer I/IJKMEDIA: ===================
03-15 13:36:20.328 23181-23181/tcking.github.com.giraffeplayer D/IJKMEDIA: ijkmp_prepare_async()=0
03-15 13:36:20.328 23181-26823/tcking.github.com.giraffeplayer I/IJKMEDIA: SDL_RunThread: [26823] ff_read
03-15 13:36:20.338 23181-26821/tcking.github.com.giraffeplayer I/IJKMEDIA: SDL_RunThread: [26821] ff_msg_loop
03-15 13:36:20.338 23181-26821/tcking.github.com.giraffeplayer D/IJKMEDIA: message_loop
03-15 13:36:20.338 23181-26821/tcking.github.com.giraffeplayer D/IJKMEDIA: FFP_MSG_FLUSH:
03-15 13:36:20.338 23181-26822/tcking.github.com.giraffeplayer I/IJKMEDIA: SDL_RunThread: [26822] ff_vout
03-15 13:36:22.408 23181-26823/tcking.github.com.giraffeplayer D/IJKMEDIA: Statistics: 1048576 bytes read, 0 seeks
03-15 13:36:22.418 23181-26823/tcking.github.com.giraffeplayer E/IJKMEDIA: http://192.168.0.176:8084/SSH/movies/ceshi.mkv: Invalid data found when processing input
03-15 13:36:22.418 23181-26821/tcking.github.com.giraffeplayer D/IJKMEDIA: FFP_MSG_ERROR: 0
03-15 13:36:22.418 23181-23181/tcking.github.com.giraffeplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
03-15 13:36:22.418 23181-23181/tcking.github.com.giraffeplayer D/IjkVideoView: Error: -10000,0
03-15 13:36:22.418 23181-26823/tcking.github.com.giraffeplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [26823]

**Comment by linwea** [comment]
If you prefer more codec/format
cd config
rm module.sh
ln -s module-default.sh module.sh
cd android/contrib
# cd ios
sh compile-ffmpeg clean

弄这个就好了

**Comment by jinch888d** [comment]
请问上面的几步在git checkout -B latest k0.4.5.1之前执行还是在./init-android.sh之前执行，ndk使用64位还是32位，必须是R10e吗？？？

**Comment by linwea** [comment]
我是第一次编译后发现很多解码不了黑屏，再进行上面几步的，执行之后就执行./init-android.sh

cd android/contrib
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all

cd ..
./compile-ijk.sh all

ndk是64位是r10e

**Comment by jinch888d** [comment]
我再github上面找了一个别人编译好的，什么都没有修改，IjkVideoView使用的Ijkmediaplayer，但是很多格式的视频都不能播放，mp4格式的部分可以播放，还有一部分有声音没有界面

**Comment by linwea** [comment]
github编译好那个版本好像很久了

**Comment by jinch888d** [comment]
github上面有个五六天前编译好的，但是使用ijkmediaplayer不能用，有bug

**Comment by bbcallen** [comment]
I don't maintain any binary not from me.
