### ISSUE TITLE
[iOS] class IJKFFMoviePlayerController delegate 

### ISSUE THREAD

**Issue by nyz110** [Bilibili/ijkplayer#1036]
@property (nonatomic, retain) id<IJKMediaUrlOpenDelegate> segmentOpenDelegate;
@property (nonatomic, retain) id<IJKMediaUrlOpenDelegate> tcpOpenDelegate;
@property (nonatomic, retain) id<IJKMediaUrlOpenDelegate> httpOpenDelegate;
@property (nonatomic, retain) id<IJKMediaUrlOpenDelegate> liveOpenDelegate;

may cause retain cycle above delegate property  ,should use weak replace

**Comment by bbcallen** [comment]
Thanks.
It has been fixed in my local dev branch, would be merged in several weeks.

**Comment by nyz110** [comment]
@bbcallen nice. because my project support for ios 7+.i add a static lib target to the

**Comment by bbcallen** [comment]
Check your "Deployment Target".
Framework can be used on ios7.

**Comment by bbcallen** [comment]
I think they are already being set nil here
https://github.com/Bilibili/ijkplayer/blob/fe0fb59d3d4c5dce9590111b18dc688167c01fba/ios/IJKMediaPlayer/IJKMediaPlayer/IJKFFMoviePlayerController.m#L480
