### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app-lib/tv.danmaku.ijk.media.sample-3/libijkplayer.so"

### ISSUE THREAD

**Issue by zhuowr2006** [Bilibili/ijkplayer#1037]
My ".so"  and put it in, so why would it look like?To solve the

**Comment by 18369188711why** [comment]
I have the same problem as you did,could you please tell me how do you solve the problem?

**Comment by dummas2008** [comment]
add ijkplayer proguard rule to fix this problem:
-dontwarn tv.danmaku.ijk.media.player.**
-keep class tv.danmaku.ijk.media.player.** { *; }
-keep interface tv.danmaku.ijk.media.player.* { *; }

**Comment by fukemy** [comment]
not working to me
