### ISSUE TITLE
iOS Connection always be closed,but I sure that stream is OK!

### ISSUE THREAD

**Issue by gaara0816** [Bilibili/ijkplayer#1039]
===== versions =====
[FFPlayer @ 0x3017a00] FFmpeg       : ff2.8--ijk0.4.4.1--dev0.3.3--rc7
[FFPlayer @ 0x3017a00] libavutil    : 54.31.100
[FFPlayer @ 0x3017a00] libavcodec   : 56.1.101
[FFPlayer @ 0x3017a00] libavformat  : 55.5.100
[FFPlayer @ 0x3017a00] libswscale   : 3.1.100
[FFPlayer @ 0x3017a00] libswresample: 1.1.100
===== options =====
[FFPlayer @ 0x3017a00] player-opts : videotoolbox-max-frame-width = 960
[FFPlayer @ 0x3017a00] player-opts : overlay-format               = fcc-_es2
[FFPlayer @ 0x3017a00] player-opts : framedrop                    = 0
[FFPlayer @ 0x3017a00] player-opts : max-fps                      = 30
[FFPlayer @ 0x3017a00] player-opts : video-pictq-size             = 3
[FFPlayer @ 0x3017a00] player-opts : videotoolbox                 = 0
[FFPlayer @ 0x3017a00] player-opts : start-on-prepared            = 1
[FFPlayer @ 0x3017a00] format-opts : ijkinject-opaque             = 166682928
[FFPlayer @ 0x3017a00] format-opts : user-agent                   = ijkplayer
[FFPlayer @ 0x3017a00] format-opts : auto_convert                 = 0
[FFPlayer @ 0x3017a00] format-opts : timeout                      = 30000000
[FFPlayer @ 0x3017a00] format-opts : reconnect                    = 1
[FFPlayer @ 0x3017a00] format-opts : safe                         = 0
===================
ijkmp_prepare_async()=0
2016-03-15 20:54:07.307 Dog[4748:1632114] invalidateRenderBuffer
2016-03-15 20:54:07.310 Dog[4748:1634472] IJKSDLGLView: setupDisplay not ready
2016-03-15 20:54:07.320 Dog[4748:1632114] invalidateRenderBuffer
2016-03-15 20:54:07.320 Dog[4748:1634472] IJKSDLGLView: setupDisplay not ready
[http @ 0x27be9f0] request: GET /fdog/56e0227075b62560ba002a62.flv HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=0-

Connection: close

Host: 100009e.live1-hdl.z1.pili.qiniucdn.com

Icy-MetaData: 1

[http @ 0x27be9f0] header='HTTP/1.1 200 OK '
[http @ 0x27be9f0] http_code=200
[http @ 0x27be9f0] header='Server: c4h-cdn-server/1.0.1.1'
[http @ 0x27be9f0] header='Date: Tue, 15 Mar 2016 12:54:08 GMT'
[http @ 0x27be9f0] header='Content-Type: video/x-flv'
[http @ 0x27be9f0] header='Transfer-Encoding: chunked'
[http @ 0x27be9f0] header='Connection: close'
[http @ 0x27be9f0] header='C4H-Cache:  sr006.ct-jsxz-03.c4hcdn.cn'
[http @ 0x27be9f0] header=''
[AVIOContext @ 0xaf737b0] Statistics: 13 bytes read, 0 seeks
http://100009e.live1-hdl.z1.pili.qiniucdn.com/fdog/56e0227075b62560ba002a62.flv: Operation timed out
2016-03-15 20:54:38.139 Dog[4748:1632114] FFP_MSG_ERROR: 0
2016-03-15 20:54:38.140 Dog[4748:1632114] IJKMPMoviePlayBackStateDidChange 2: paused
2016-03-15 20:54:38.140 Dog[4748:1632114] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1

**Comment by gaara0816** [comment]
stream is OK,I sure

**Comment by bbcallen** [comment]
Can't reproduce here.
Better check you local LAN traffic.

**Comment by gaara0816** [comment]
I sure that ,because  it's fine when i create a new Project what import your framework.

**Comment by gaara0816** [comment]
So I think is some config error?

**Comment by bbcallen** [comment]
```
[AVIOContext @ 0xaf737b0] Statistics: 13 bytes read, 0 seeks
http://100009e.live1-hdl.z1.pili.qiniucdn.com/fdog/56e0227075b62560ba002a62.flv: Operation timed out
2016-03-15 20:54:38.139 Dog[4748:1632114] FFP_MSG_ERROR: 0
2016-03-15 20:54:38.140 Dog[4748:1632114] IJKMPMoviePlayBackStateDidChange 2: paused
2016-03-15 20:54:38.140 Dog[4748:1632114] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1
```
This is not "paused", it is an error.

**Comment by gaara0816** [comment]
`[http @ 0x27be9f0] request: GET /fdog/56e0227075b62560ba002a62.flv HTTP/1.1

User-Agent: ijkplayer

Accept: /

Range: bytes=0-

Connection: close

Host: 100009e.live1-hdl.z1.pili.qiniucdn.com

Icy-MetaData: 1

[http @ 0x27be9f0] header='HTTP/1.1 200 OK '
[http @ 0x27be9f0] http_code=200
[http @ 0x27be9f0] header='Server: c4h-cdn-server/1.0.1.1'
[http @ 0x27be9f0] header='Date: Tue, 15 Mar 2016 12:54:08 GMT'
[http @ 0x27be9f0] header='Content-Type: video/x-flv'
[http @ 0x27be9f0] header='Transfer-Encoding: chunked'
[http @ 0x27be9f0] header='Connection: close'
[http @ 0x27be9f0] header='C4H-Cache: sr006.ct-jsxz-03.c4hcdn.cn'
[http @ 0x27be9f0] header=''`

`request: GET /fdog/56e0227075b62560ba002a62.flv HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=0-

Connection: close

Host: 100009e.live1-hdl.z1.pili.qiniucdn.com

Icy-MetaData: 1




Format flv probed with size=2048 and score=100
Option safe not found.
Before avformat_find_stream_info() pos: 13 bytes read:4103 seeks:0
All info found
rfps: 29.666667 0.014903
rfps: 29.750000 0.008133
rfps: 29.833333 0.003422
rfps: 29.916667 0.000770
rfps: 29.916667 0.000770
rfps: 30.000000 0.000176
rfps: 30.000000 0.000176
rfps: 60.000000 0.000704
rfps: 60.000000 0.000704`

you can see the deference,the error is Connection: close

**Comment by casscqt** [comment]
-(void)viewWillAppear:(BOOL)animated{
    if (![self.player isPlaying]) {
        [self.player prepareToPlay];
    }
}

**Comment by RinCelery** [comment]
it seems ijkplayer doesn't support for chunked ? i have met the same problem, when use ffmpeg it seems ok, while use vlc be bad. of course , i sure my stream is well
