### ISSUE TITLE
In the case of live, open hardware decoding, the memory and CPU consumption of large moment,

### ISSUE THREAD

**Issue by zhangcheng1989** [Bilibili/ijkplayer#1040]
In the case of live, open hardware decoding, the memory and CPU consumption of large moment,

**Comment by zhangcheng1989** [comment]
你好，长时间播放，在播放过程出现卡顿，就会出现整个播放画面停止不动，重新获取下播放流，就好了

**Comment by zhangcheng1989** [comment]
AVC: nal size 6193
missing picture in access unit with size 2049
av_read_frame error: ffffffc4(\377,\377,\377,\304): AVERROR(ETIMEDOUT)
ffp_toggle_buffering_l: end
aout_pause_audio(0)
2016-03-16 13:16:41.892 DYZB[3541:60b] FFP_MSG_BUFFERING_END:
2016-03-16 13:16:41.895 DYZB[3541:60b] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3
2016-03-16 13:16:41.896 DYZB[3541:60b] moviePlayBackStateDidChange 1: playing
AVC: nal size 6193
AVC: nal size 6193
no frame!
aout_pause_audio(1)
ffp_toggle_buffering: error: -60
av_read_frame error: ffffffc4(\377,\377,\377,\304): AVERROR(ETIMEDOUT)
2016-03-16 13:16:42.961 DYZB[3541:60b] FFP_MSG_ERROR: 0
2016-03-16 13:16:42.963 DYZB[3541:60b] moviePlayBackStateDidChange 1: playing
2016-03-16 13:16:42.964 DYZB[3541:60b] playbackStateDidChange: MPMovieFinishReasonPlaybackEnded: 0
ffp_toggle_buffering: eof

**Comment by bbcallen** [comment]
```
av_read_frame error: ffffffc4(\377,\377,\377,\304): AVERROR(TIME-OUT)
```

**Comment by zhangcheng1989** [comment]
@bbcallen    if (completed) {
                    av_log(ffp, AV_LOG_INFO, "ffp_toggle_buffering: eof\n");
                    SDL_LockMutex(wait_mutex);
                    // infinite wait may block shutdown
                    while(!is->abort_request && !is->seek_req)
                        SDL_CondWaitTimeout(is->continue_read_thread, wait_mutex, 100);
                    SDL_UnlockMutex(wait_mutex);
                    if (!is->abort_request)
                        continue;
可能是网络环境很，然后执行到这里，没有做任何处理吧，还有一个情况就是播放的时候卡顿情况很严重，我把你回复给其他的优化设置添加了，效果还是不明显

**Comment by zhangcheng1989** [comment]
如果是线程的话，我添加的弹幕都在执行，出现上面的错误，监听整个网络情况没有执行了，
