### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by jinch888d** [Bilibili/ijkplayer#1041]
编译出来的类库在AArch64 Processor rev 4 手机上面测试崩溃

**Comment by jinch888d** [comment]
03-17 15:54:29.823 21366-21533/? E/IJKMEDIA: Option ijkinject-opaque not found.
03-17 15:54:29.892 21366-21533/? E/IJKMEDIA: csd-0[38]: 00000001
03-17 15:54:29.892 21366-21533/? E/IJKMEDIA: csd-0[38]: 6764001f
03-17 15:54:29.892 21366-21533/? E/IJKMEDIA: csd-0[38]: acd94040
03-17 15:54:29.892 21366-21533/? E/IJKMEDIA: csd-0[38]: 049a1000
03-17 15:54:29.893 21366-21533/? E/IJKMEDIA: csd-0[38]: 00030010
03-17 15:54:29.893 21366-21533/? E/IJKMEDIA: csd-0[38]: 00000303
03-17 15:54:29.893 21366-21533/? E/IJKMEDIA: csd-0[38]: 28f18319
03-17 15:54:29.893 21366-21533/? E/IJKMEDIA: csd-0[38]: 60000000
03-17 15:54:29.893 21366-21533/? E/IJKMEDIA: csd-0[38]: 0168ebec
03-17 15:54:29.893 21366-21533/? E/IJKMEDIA: csd-0[38]: b22c0000
03-17 15:54:29.934 21366-21533/? E/IJKMEDIA: configure acodec:0x100bd6 format:0x200ba2: surface:0xb26
03-17 15:54:30.094 21366-21366/? E/loadHistory: 加载配置信息
03-17 15:54:30.094 21366-21366/? E/loadHistory播放的视频名称: 潮流教主粤语HDTV01.mkv
03-17 15:54:30.095 21366-21366/? E/loadHistory播放的视频: 104647
03-17 15:54:30.625 21366-21420/? A/libc: Fatal signal 7 (SIGBUS), code 1, fault addr 0x9c6f9b96 in tid 21420 (jk.media.sample)
03-17 15:54:31.665 847-919/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
03-17 15:54:31.667 847-912/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
03-17 15:54:31.691 358-1039/? E/OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
03-17 15:54:31.697 847-1006/? E/InputDispatcher: channel '1084ef29 tv.danmaku.ijk.media.sample/com.xigua.media.activity.FirstActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-17 15:54:31.697 847-1006/? E/InputDispatcher: channel '3f11cc3b tv.danmaku.ijk.media.sample/tcking.github.com.giraffeplayer.GiraffePlayerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-17 15:54:45.616 847-1020/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=69.19 rxSuccessRate=121.96 targetRoamBSSID=any RSSI=-39
03-17 15:55:02.635 847-1020/? E/WifiStateMachine: cancelDelayedScan -> 6321
03-17 15:55:02.638 847-1020/? E/native: do suspend true
03-17 15:55:05.622 847-1020/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=0.00 targetRoamBSSID=any RSSI=-43
03-17 15:55:05.623 847-1020/? E/WifiStateMachine: WifiStateMachine L2Connected CMD_START_SCAN source -2 6320, 6321 -> obsolete
03-17 15:55:44.126 26636-21812/? E/ProtoReq: [10876] a.a: want to send authenticated request, but no Google account on device


SurfaceView doesn't support rotation (0)!

**Comment by Android4MediaPlayer** [comment]
which devices?

**Comment by bbcallen** [comment]
Please find out the crash stack with ndk-stack.
