### ISSUE TITLE
X86、armeabi-V7a正常，V8a崩溃

### ISSUE THREAD

**Issue by jinch888d** [Bilibili/ijkplayer#1043]
loadLibraries error
                                                  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tv.danmaku.ijk.media.sample-1/base.apk"],nativeLibraryDirectories=[/data/app/tv.danmaku.ijk.media.sample-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"
                                                      at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                      at java.lang.System.loadLibrary(System.java:988)
                                                      at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:157)
                                                      at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:168)
                                                      at tcking.github.com.giraffeplayer.GiraffePlayer.<init>(GiraffePlayer.java:265)
                                                      at tcking.github.com.giraffeplayer.GiraffePlayerActivity.onCreate(GiraffePlayerActivity.java:32)
                                                      at android.app.Activity.performCreate(Activity.java:6142)
                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115)
                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2528)
                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2656)
                                                      at android.app.ActivityThread.access$800(ActivityThread.java:178)
                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1512)
                                                      at android.os.Handler.dispatchMessage(Handler.java:111)
                                                      at android.os.Looper.loop(Looper.java:194)
                                                      at android.app.ActivityThread.main(ActivityThread.java:5691)
                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
03-17 09:23:11.263 29876-29906/? E/GED: Failed to get GED Log Buf, err(0)
03-17 09:23:11.276 872-872/? E/WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 66 num clients 12
03-17 09:23:11.276 872-872/? E/WifiTrafficPoller:  packet count Tx=75968 Rx=144508
03-17 09:23:11.276 872-872/? E/WifiTrafficPoller: notifying of data activity 1
03-17 09:23:11.454 872-979/? E/WifiStateMachine:  ConnectedState (when=-5ms what=131155 arg1=41!CMD_RSSI_POLL 41 0 "360-8888" a4:56:02:13:5f:47 rssi=-50 f=2452 sc=60 link=135 tx=0.0, 0.0, 0.0  rx=2.8 bcn=0 [on:0 tx:0 rx:0 period:3005] from screen [on:0 period:-2111089187] gl hn u24 rssi=-45 ag=0 hr ticks 0,0,0 ls-=0 [56,56,56,56,61] brc=0 lrc=0
03-17 09:23:11.457 872-979/? E/WifiStateMachine:  L2ConnectedState (when=-8ms what=131155 arg1=41!CMD_RSSI_POLL 41 0 "360-8888" a4:56:02:13:5f:47 rssi=-50 f=2452 sc=60 link=135 tx=0.0, 0.0, 0.0  rx=2.8 bcn=0 [on:0 tx:0 rx:0 period:4] from screen [on:0 period:-2111089183] gl hn u24 rssi=-45 ag=0 hr ticks 0,0,0 ls-=0 [56,56,56,56,61] brc=0 lrc=0
03-17 09:23:11.457 872-979/? E/WifiStateMachine:  get link layer stats 0
03-17 09:23:11.475 872-979/? E/WifiConfigStore: updateConfiguration freq=2452 BSSID=a4:56:02:13:5f:47 RSSI=-49 "360-8888"WPA_PSK
03-17 09:23:12.278 872-872/? E/WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 66 num clients 12
03-17 09:23:12.279 872-872/? E/WifiTrafficPoller:  packet count Tx=75968 Rx=144509
03-17 09:23:13.280 872-872/? E/WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 66 num clients 12
03-17 09:23:13.281 872-872/? E/WifiTrafficPoller:  packet count Tx=75970 Rx=144510
03-17 09:23:13.281 872-872/? E/WifiTrafficPoller: notifying of data activity 3
03-17 09:23:13.793 872-996/? E/libPerfService: Could not open '/d/ged/hal/custom_boost_gpu_freq'
03-17 09:23:13.793 872-996/? E/libPerfService: error : 13, Permission denied
03-17 09:23:14.284 872-872/? E/WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 66 num clients 12
03-17 09:23:14.285 872-872/? E/WifiTrafficPoller:  packet count Tx=75970 Rx=144512
03-17 09:23:14.285 872-872/? E/WifiTrafficPoller: notifying of data activity 1
03-17 09:23:14.481 872-979/? E/WifiStateMachine:  ConnectedState (when=-4ms what=131155 arg1=41!CMD_RSSI_POLL 41 0 "360-8888" a4:56:02:13:5f:47 rssi=-51 f=2452 sc=60 link=135 tx=0.0, 0.0, 0.0  rx=2.9 bcn=0 [on:0 tx:0 rx:0 period:3004] from screen [on:0 period:-2111086159] gl hn u24 rssi=-46 ag=0 hr ticks 0,0,0 ls-=0 [56,56,56,56,61] brc=0 lrc=0
03-17 09:23:14.483 872-979/? E/WifiStateMachine:  L2ConnectedState (when=-7ms what=131155 arg1=41!CMD_RSSI_POLL 41 0 "360-8888" a4:56:02:13:5f:47 rssi=-51 f=2452 sc=60 link=135 tx=0.0, 0.0, 0.0  rx=2.9 bcn=0 [on:0 tx:0 rx:0 period:2] from screen [on:0 period:-2111086157] gl hn u24 rssi=-46 ag=0 hr ticks 0,0,0 ls-=0 [56,56,56,56,61] brc=0 lrc=0
03-17 09:23:14.483 872-979/? E/WifiStateMachine:  get link layer stats 0
03-17 09:23:14.510 872-979/? E/WifiConfigStore: updateConfiguration freq=2452 BSSID=a4:56:02:13:5f:47 RSSI=-50 "360-8888"WPA_PSK
03-17 09:23:15.295 872-872/? E/WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 66 num clients 12
03-17 09:23:15.296 872-872/? E/WifiTrafficPoller:  packet count Tx=75970 Rx=144512
03-17 09:23:15.296 872-872/? E/WifiTrafficPoller: notifying of data activity 0
03-17 09:23:16.299 872-872/? E/WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 66 num clients 12
03-17 09:23:16.300 872-872/? E/WifiTrafficPoller:  packet count Tx=75970 Rx=144513
03-17 09:23:16.300 872-872/? E/WifiTrafficPoller: notifying of data activity 1
03-17 09:23:17.302 872-872/? E/WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 66 num clients 12
03-17 09:23:17.303 872-872/? E/WifiTrafficPoller:  packet count Tx=75970 Rx=144516
03-17 09:23:17.519 872-979/? E/WifiStateMachine:  ConnectedState (when=-5ms what=131155 arg1=41!CMD_RSSI_POLL 41 0 "360-8888" a4:56:02:13:5f:47 rssi=-51 f=2452 sc=60 link=135 tx=1.0, 0.0, 0.0  rx=3.5 bcn=0 [on:0 tx:0 rx:0 period:2997] from screen [on:0 period:-2111083122] gl hn u24 rssi=-46 ag=0 hr ticks 0,0,0 ls-=0 [56,56,56,56,61] brc=0 lrc=0
03-17 09:23:17.521 872-979/? E/WifiStateMachine:  L2ConnectedState (when=-8ms what=131155 arg1=41!CMD_RSSI_POLL 41 0 "360-8888" a4:56:02:13:5f:47 rssi=-51 f=2452 sc=60 link=135 tx=1.0, 0.0, 0.0  rx=3.5 bcn=0 [on:0 tx:0 rx:0 period:3] from screen [on:0 period:-2111083119] gl hn u24 rssi=-46 ag=0 hr ticks 0,0,0 ls-=0 [56,56,56,56,61] brc=0 lrc=0
03-17 09:23:17.523 872-979/? E/WifiStateMachine:  get link layer stats 0
03-17 09:23:17.551 872-979/? E/WifiConfigStore: updateConfiguration freq=2452 BSSID=a4:56:02:13:5f:47 RSSI=-51 "360-8888"WPA_PSK
03-17 09:23:18.305 872-872/? E/WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 66 num clients 12
03-17 09:23:18.306 872-872/? E/WifiTrafficPoller:  packet count Tx=75970 Rx=144517
03-17 09:23:19.307 872-872/? E/WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 66 num clients 12
03-17 09:23:19.309 872-872/? E/WifiTrafficPoller:  packet count Tx=75970 Rx=144519
03-17 09:23:20.310 872-872/? E/WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 66 num clients 12
03-17 09:23:20.311 872-872/? E/WifiTrafficPoller:  packet count Tx=75970 Rx=144519
03-17 09:23:20.311 872-872/? E/WifiTrafficPoller: notifying of data activity 0
03-17 09:23:20.560 872-979/? E/WifiStateMachine:  ConnectedState (when=-5ms what=131155 arg1=41!CMD_RSSI_POLL 41 0 "360-8888" a4:56:02:13:5f:47 rssi=-52 f=2452 sc=60 link=135 tx=0.5, 0.0, 0.0  rx=3.7 bcn=0 [on:0 tx:0 rx:0 period:2991] from screen [on:0 period:-2111080080] gl hn u24 rssi=-47 ag=0 hr ticks 0,0,0 ls-=0 [56,56,56,56,61] brc=0 lrc=0
03-17 09:23:20.576 872-979/? E/WifiStateMachine:  L2ConnectedState (when=-20ms what=131155 arg1=41!CMD_RSSI_POLL 41 0 "360-8888" a4:56:02:13:5f:47 rssi=-52 f=2452 sc=60 link=135 tx=0.5, 0.0, 0.0  rx=3.7 bcn=0 [on:0 tx:0 rx:0 period:16] from screen [on:0 period:-2111080064] gl hn u24 rssi=-47 ag=0 hr ticks 0,0,0 ls-=0 [56,56,56,56,61] brc=0 lrc=0
03-17 09:23:20.577 872-979/? E/WifiStateMachine:  get link layer stats 0
03-17 09:23:20.596 872-979/? E/WifiConfigStore: updateConfiguration freq=2452 BSSID=a4:56:02:13:5f:47 RSSI=-49 "360-8888"WPA_PSK
01-01 00:00:00.000 0-0/? E/Internal: device '810EBLS26QS5' not found，
编译出来的类库在X86和V7a架构上面正常，在V8a架构上面，找不到类库

**Comment by bbcallen** [comment]
```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tv.danmaku.ijk.media.sample-1/base.apk"],nativeLibraryDirectories=[/data/app/tv.danmaku.ijk.media.sample-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"
```

**Comment by Android4MediaPlayer** [comment]
complier ffmpeg for arm64
