### ISSUE TITLE
最新版本，直播过程中会出现整个播放画面停止，请教如何解决

### ISSUE THREAD

**Issue by zhangcheng1989** [Bilibili/ijkplayer#1048]
最新版本，直播过程中会出现整个播放画面停止，缓存也不执行了，相当于整个播放器卡死了，日志也不输出了，请教如何解决

**Comment by Android4MediaPlayer** [comment]
more information

**Comment by zhangcheng1989** [comment]
@Android4MediaPlayer 应该是网络情况导致的，就是在网络情况很不稳定下，可能没有获取到流 ffp_statistic_l(ffp);
                if (completed) {
                    av_log(ffp, AV_LOG_INFO, "ffp_toggle_buffering: eof\n");
                    SDL_LockMutex(wait_mutex);
                    // infinite wait may block shutdown
                    while(!is->abort_request && !is->seek_req)
                        SDL_CondWaitTimeout(is->continue_read_thread, wait_mutex, 100);
                    SDL_UnlockMutex(wait_mutex);
                    if (!is->abort_request)
                        continue;
肯定是执行到这里了，没有任何处理，相当于整个播放画面卡死，连声音也没有

**Comment by zhangcheng1989** [comment]
@Android4MediaPlayer  同步线程导致的，改如何解决呢

**Comment by zhangcheng1989** [comment]
@Android4MediaPlayer 还有就是卡死后，没有任何日志输出

**Comment by zhangcheng1989** [comment]
@bbcallen  if (completed) {
                    av_log(ffp, AV_LOG_INFO, "ffp_toggle_buffering: eof\n");
                    ffp_notify_msg1(ffp, FFP_MSG_COMP);
                    SDL_LockMutex(wait_mutex);
                    // infinite wait may block shutdown
                    while(!is->abort_request && !is->seek_req)
                        SDL_CondWaitTimeout(is->continue_read_thread, wait_mutex, 100);
                    SDL_UnlockMutex(wait_mutex);
                    printf("SDL_UnlockMutex");
                    if (!is->abort_request)
                        continue;
debug在这里死循环了，
