### ISSUE TITLE
How to get a frame image?

### ISSUE THREAD

**Issue by vuzya** [Bilibili/ijkplayer#1049]
Hello. Would you suggest how can I get the currently displayed frame? Output is not so important - would it be byte array or file. I don't need some exact frame - it could be last keyframe, or frame "a second ago" - just need a snapshot of video stream "approximately now". Could you please suggest something?

**Comment by bbcallen** [comment]
No such API for android, yet.
thumbnailImageAtCurrentTime for iOS for last displayed frame.

**Comment by Feng-xp** [comment]
thumbnailImageAtCurrentTime 这个方法貌似截不到视频啊，模拟器可以截取，真机上截出来的图片是黑色的

**Comment by lovederh** [comment]
@Feng-xp Fen 您解决thumbnailImageAtCurrentTime这个截不到的问题了吗, 我的是空的图片

**Comment by Feng-xp** [comment]
太久了，没印象了

lovederh ***@***.***>于2021年8月16日 周一15:43写道：
