### ISSUE TITLE
android  怎么判断当前推流端已经停止发布直播

### ISSUE THREAD

**Issue by garrickjubiao** [Bilibili/ijkplayer#1051]
您好。 请问android ijkplayer的sdk，怎么判断推流端已经结束直播了。 有个场景： 当主播停止直播后，播放端需求弹出提示告诉用户直播已经结束。 但是，我不知道怎么判断是正常推流结束，还是播放端的其他异常引起的。 因为这两种情况都会走onError() 和 onComplete（）回调，而且传入的what extra字段值都一样。....我用的是IjkMediaPlayer+TextureView。

**Comment by bbcallen** [comment]
Ijkplayer can't do that.

**Comment by jyfree** [comment]
在onError() 和 onComplete（）方法。方法：1、重新获取直播地址，服务端控制是否有地址返回。
2、用户http请求该地址，若请求成功表示直播未结束，否则结束

**Comment by garrickjubiao** [comment]
Yeah , We just do it like your description @jyfree

**Comment by blueseaguo** [comment]
请问，给你个地址，怎么用ijk来判断是直播还是点播

**Comment by michalliu** [comment]
@blueseaguo m3u8里有X-EXT-ENDLIST
