### ISSUE TITLE
IOS下播放demo卡顿 Android下正常

### ISSUE THREAD

**Issue by iosnower** [Bilibili/ijkplayer#1052]
真机运行, 相同的网络环境下, 播放rtmp直播流.
android上运行k0.4.4.1 demo, 画面流畅.
ios上, 分别运行k0.4.4.1和k0.4.5.1的demo,画面卡顿, 经常会卡住一会儿

**Comment by tickhunter** [comment]
我也遇到这个问题了，ios走系统硬解码则ok，ijk内的ffmepg则不行，帧率低

**Comment by zhangcheng1989** [comment]
我也是遇到了，不知道咋解决啊

**Comment by bbcallen** [comment]
What device were you testing on?
It's a known issue that it doesn't work well on simulator.

**Comment by iosnower** [comment]
三星note4 系统Android 5.0.1
iphone5s 系统ios9.2

**Comment by Somepig** [comment]
@tickhunter IOS硬解码除了设置option还需要改别的东西吗   我这边硬解播不出来
