### ISSUE TITLE
急：请问如何使用2个ijkvideoview播放同一个视频

### ISSUE THREAD

**Issue by Millertoken** [Bilibili/ijkplayer#1055]
你好，我是做VR的，现在需要基于这个框架实现VR的2个画面播放同一个视频的效果。想法是获取到第一个播放view的画布或者图像帧，然后设置到第二个view里面，这样就不会出现视频不同步的情况。IOS的同事也是使用你们DEMO，IOS的同事成功了，他是监听有一个display(overlay)的方法，这个方法每画一帧就会调用，他再把overlay放到第二个view去画。但是android这边怎么都实现不了，不知道android是否也有每一帧画完都会回调的方法来实现这个功能。请问有什么办法么。英语不好，见谅。
麻烦帮我看看，急着要出版本，谢谢了。

**Comment by bbcallen** [comment]
How did you use with android ijkplayer?

**Comment by Millertoken** [comment]
@Override
    public void setDisplay(SurfaceHolder sh) {
        mSurfaceHolder = sh;
        Surface surface;
        if (sh != null) {
            surface = sh.getSurface();
        } else {
            surface = null;
        }
        _setVideoSurface(surface);
        updateSurfaceScreenOn();
        if (mIdIsPlayCallBack != null){
            mIdIsPlayCallBack.setdisplaycallback(sh);
        }
    }
我在 ijkplayer里面监听setDisPlay事件，然后把SurfaceHolder获取到，以为可以设置给另一个surfaceview，然后实现同步画面，但是失败了。SurfaceHolder的surface被设置到native去绘制了，没找到绘制每一帧时的回调，没办法获取到每一帧的数据（如果可以获取到数据，是否可以用另一个surfaceview 的canvas画出来。）。所以这个功能怎么都做不出来。

我看有些应用是用GLsurfaceview实现视频播放的，里面有一个ondrawframe()的回调，每一帧都会触发这个方法，然后通过native层的返回值在这个方法里面绘制。不知道ijk是否有类似的办法。

或者请问下是否有其他方式实现1个播放，另一个同步的双界面功能呢？

**Comment by bbcallen** [comment]
You should modify native-c code to implement such features.
Search ANativeWindow related code.
