### ISSUE TITLE
请问，如何在ijk中按照缓存顺序获得 m3u8地址

### ISSUE THREAD

**Issue by SteveFrank** [Bilibili/ijkplayer#1056]
请问如何在播放m3u8文件的同时，将m3u8解析后得到的地址列表按照缓存的时间打印到Anroid界面上，并且获得缓存的时候每一条 m3u8 到达的时间。

**Comment by bbcallen** [comment]
Modify FFmpeg, and export the callback functions.

**Comment by SteveFrank** [comment]
多谢作者，已经有思路了。
