### ISSUE TITLE
为啥不用libavutil\error.c的错误码

### ISSUE THREAD

**Issue by lyqaiym** [Bilibili/ijkplayer#1057]
ijkplayer\ff_ffplay.c的read_thread方法avformat_open_input打开视频返回-875574520
其实就是error.c中的HTTP_NOT_FOUND Server returned 404 Not Found但为啥播放器没有用到
last_error并没有和avformat_open_input结合起来啊

**Comment by lyqaiym** [comment]
就是视频打开的方法avformat_open_input返回错误，没用到代码里，last_error这变量还是0

**Comment by bbcallen** [comment]
So?
