### ISSUE TITLE
切换音轨时，视频会加速播放1秒后正常

### ISSUE THREAD

**Issue by wqmijkplayer** [Bilibili/ijkplayer#1059]
@bbcallen 切换音轨有这样一个问题，视频会加速播放1秒后正常

**Comment by bbcallen** [comment]
It's an experimental feature, for now.
That's to say I don't have any plan to fix bugs about it recently.

**Comment by m521521l** [comment]
有多音轨？？？

**Comment by xiongziliang** [comment]
解决方法：ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "min-frames", 2);
