### ISSUE TITLE
播放经常出现（-10000,0）错误，请问什么原因，部分手机经常出现，有些手机很少出现

### ISSUE THREAD

**Issue by zhangbl** [Bilibili/ijkplayer#1062]
播放经常出现（-10000,0）错误，请问什么原因，部分手机经常出现，有些手机很少出现

**Comment by zhangbl** [comment]
03-23 15:34:50.956: D/IJKMEDIA(22926): IjkMediaPlayer_setVideoSurface
03-23 15:34:50.956: D/IJKMEDIA(22926): ijkmp_set_android_surface(surface=0x3f400021)
03-23 15:34:50.956: D/IJKMEDIA(22926): ffpipeline_set_surface()
03-23 15:34:50.956: D/IJKMEDIA(22926): ijkmp_set_android_surface(surface=0x3f400021)=void
03-23 15:34:50.956: D/IJKMEDIA(22926): IjkMediaPlayer_setDataSourceAndHeaders
03-23 15:34:50.956: V/IJKMEDIA(22926): setDataSource: path http://replay.xiuimg.com/release/bo19_4776db3931c6b0b60d148dfdb230b218-1458697580_flv/bo19_4776db3931c6b0b60d148dfdb230b218-1458697580.mp4
03-23 15:34:50.956: D/IJKMEDIA(22926): ijkmp_set_data_source(url="http://replay.xiuimg.com/release/bo19_4776db3931c6b0b60d148dfdb230b218-1458697580_flv/bo19_4776db3931c6b0b60d148dfdb230b218-1458697580.mp4")
03-23 15:34:50.956: D/IJKMEDIA(22926): ijkmp_set_data_source(url="http://replay.xiuimg.com/release/bo19_4776db3931c6b0b60d148dfdb230b218-1458697580_flv/bo19_4776db3931c6b0b60d148dfdb230b218-1458697580.mp4")=0
03-23 15:34:50.956: D/IJKMEDIA(22926): IjkMediaPlayer_prepareAsync
03-23 15:34:50.956: D/IJKMEDIA(22926): ijkmp_prepare_async()
03-23 15:34:50.956: I/IJKMEDIA(22926): ===== versions =====
03-23 15:34:50.956: I/IJKMEDIA(22926): FFmpeg       : ff2.8--ijk0.4.1.1--dev0.3.3--rc4
03-23 15:34:50.956: I/IJKMEDIA(22926): SDL_RunThread: [23838] ff_msg_loop
03-23 15:34:50.956: I/IJKMEDIA(22926): libavutil    : 54.31.100
03-23 15:34:50.956: I/IJKMEDIA(22926): libavcodec   : 56.60.100
03-23 15:34:50.956: D/IJKMEDIA(22926): message_loop
03-23 15:34:50.956: I/IJKMEDIA(22926): libavformat  : 56.40.101
03-23 15:34:50.956: I/IJKMEDIA(22926): libswscale   : 3.1.101
03-23 15:34:50.956: I/IJKMEDIA(22926): libswresample: 1.2.101
03-23 15:34:50.956: I/IJKMEDIA(22926): ===== options =====
03-23 15:34:50.956: I/IJKMEDIA(22926): player-opts : overlay-format               = 842225234
03-23 15:34:50.956: I/IJKMEDIA(22926): player-opts : min-frames                   = 80
03-23 15:34:50.956: I/IJKMEDIA(22926): player-opts : packet-buffering             = 0
03-23 15:34:50.956: I/IJKMEDIA(22926): format-opts : ijkinject-opaque             = 490734422
03-23 15:34:50.956: I/IJKMEDIA(22926): format-opts : nobuffer                     = 1
03-23 15:34:50.956: I/IJKMEDIA(22926): ===================
03-23 15:34:50.956: D/IJKMEDIA(22926): FFP_MSG_FLUSH:
03-23 15:34:50.956: I/IJKMEDIA(22926): SDL_RunThread: [23839] ff_vout
03-23 15:34:50.956: D/IJKMEDIA(22926): ijkmp_prepare_async()=0
03-23 15:34:50.956: I/IJKMEDIA(22926): SDL_RunThread: [23840] ff_read
03-23 15:34:51.086: E/IJKMEDIA(22926): error reading header
03-23 15:34:51.086: E/IJKMEDIA(22926): http://replay.xiuimg.com/release/bo19_4776db3931c6b0b60d148dfdb230b218-1458697580_flv/bo19_4776db3931c6b0b60d148dfdb230b218-1458697580.mp4: Invalid data found when processing input
03-23 15:34:51.086: I/IJKMEDIA(22926): SDL_JNI_DetachThreadEnv: [23840]
03-23 15:34:51.086: D/IJKMEDIA(22926): FFP_MSG_ERROR: 0
03-23 15:34:51.106: E/tv.danmaku.ijk.media.player.IjkMediaPlayer(22926): Error (-10000,0)
03-23 15:34:51.106: I/System.out(22926): url===http://replay.xiuimg.com/release/bo19_4776db3931c6b0b60d148dfdb230b218-1458697580_flv/bo19_4776db3931c6b0b60d148dfdb230b218-1458697580.mp4
03-23 15:34:51.106: D/IJKMEDIA(22926): ijkmp_stop()
03-23 15:34:51.106: D/IJKMEDIA(22926): ijkmp_stop()=0
03-23 15:34:51.116: D/IJKMEDIA(22926): IjkMediaPlayer_release
03-23 15:34:51.116: D/IJKMEDIA(22926): ijkmp_set_android_surface(surface=0x0)
03-23 15:34:51.116: D/IJKMEDIA(22926): message_loop exit
03-23 15:34:51.116: I/IJKMEDIA(22926): SDL_JNI_DetachThreadEnv: [23838]
03-23 15:34:51.116: D/IJKMEDIA(22926): ffpipeline_set_surface()
03-23 15:34:51.116: D/IJKMEDIA(22926): ijkmp_set_android_surface(surface=0x0)=void
03-23 15:34:51.116: D/IJKMEDIA(22926): ijkmp_shutdown_l()
03-23 15:34:51.116: I/IJKMEDIA(22926): SDL_JNI_DetachThreadEnv: [23839]
03-23 15:34:51.116: D/IJKMEDIA(22926): ijkmp_shutdown_l()=void
03-23 15:34:51.116: D/IJKMEDIA(22926): ijkmp_dec_ref(): ref=0
03-23 15:34:51.116: D/IJKMEDIA(22926): ijkmp_shutdown_l()
03-23 15:34:51.116: D/IJKMEDIA(22926): ijkmp_shutdown_l()=void
03-23 15:34:51.116: D/IJKMEDIA(22926): IjkMediaPlayer_native_setup
03-23 15:34:51.116: I/IJKMEDIA(22926): av_version_info: ff2.8--ijk0.4.1.1--dev0.3.3--rc4
03-23 15:34:51.116: D/IJKMEDIA(22926): ffpipeline_create_from_android()
03-23 15:34:51.116: D/IJKMEDIA(22926): ijkmp_set_inject_opaque(0x1d500356)
03-23 15:34:51.116: D/IJKMEDIA(22926): ijkmp_set_inject_opaque()=void
03-23 15:34:51.116: D/IJKMEDIA(22926): ijkmp_android_set_mediacodec_select_callback()
03-23 15:34:51.116: D/IJKMEDIA(22926): ffpipeline_set_mediacodec_select_callback
03-23 15:34:51.116: D/IJKMEDIA(22926): ijkmp_android_set_mediacodec_select_callback()=void
03-23 15:34:51.116: D/IJKMEDIA(22926): IjkMediaPlayer_setOptionLong
03-23 15:34:51.116: D/IJKMEDIA(22926): IjkMediaPlayer_setOptionLong
03-23 15:34:51.116: D/IJKMEDIA(22926): IjkMediaPlayer_setOptionLong
03-23 15:34:51.116: D/IJKMEDIA(22926): IjkMediaPlayer_setOptionLong
03-23 15:34:51.116: W/tv.danmaku.ijk.media.player.IjkMediaPlayer(22926): setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
03-23 15:34:51.116: W/tv.danmaku.ijk.media.player.IjkMediaPlayer(22926): setScreenOnWhilePlaying(true) is ineffective for Surface
03-23 15:34:51.116: D/IJKMEDIA(22926): IjkMediaPlayer_setVideoSurface
03-23 15:34:51.116: D/IJKMEDIA(22926): ijkmp_set_android_surface(surface=0x48d00021)
03-23 15:34:51.116: D/IJKMEDIA(22926): ffpipeline_set_surface()
03-23 15:34:51.116: D/IJKMEDIA(22926): ijkmp_set_android_surface(surface=0x48d00021)=void
03-23 15:34:51.116: D/IJKMEDIA(22926): IjkMediaPlayer_setDataSourceAndHeaders
03-23 15:34:51.116: V/IJKMEDIA(22926): setDataSource: path http://replay.xiuimg.com/release/bo19_4776db3931c6b0b60d148dfdb230b218-1458697580_flv/bo19_4776db3931c6b0b60d148dfdb230b218-1458697580.mp4
03-23 15:34:51.116: D/IJKMEDIA(22926): ijkmp_set_data_source(url="http://replay.xiuimg.com/release/bo19_4776db3931c6b0b60d148dfdb230b218-1458697580_flv/bo19_4776db3931c6b0b60d148dfdb230b218-1458697580.mp4")
03-23 15:34:51.116: D/IJKMEDIA(22926): ijkmp_set_data_source(url="http://replay.xiuimg.com/release/bo19_4776db3931c6b0b60d148dfdb230b218-1458697580_flv/bo19_4776db3931c6b0b60d148dfdb230b218-1458697580.mp4")=0
03-23 15:34:51.116: D/IJKMEDIA(22926): IjkMediaPlayer_prepareAsync
03-23 15:34:51.116: D/IJKMEDIA(22926): ijkmp_prepare_async()
03-23 15:34:51.116: I/IJKMEDIA(22926): ===== versions =====
03-23 15:34:51.116: I/IJKMEDIA(22926): FFmpeg       : ff2.8--ijk0.4.1.1--dev0.3.3--rc4
03-23 15:34:51.116: I/IJKMEDIA(22926): libavutil    : 54.31.100
03-23 15:34:51.116: I/IJKMEDIA(22926): libavcodec   : 56.60.100
03-23 15:34:51.116: I/IJKMEDIA(22926): libavformat  : 56.40.101
03-23 15:34:51.116: I/IJKMEDIA(22926): libswscale   : 3.1.101
03-23 15:34:51.116: I/IJKMEDIA(22926): libswresample: 1.2.101
03-23 15:34:51.116: I/IJKMEDIA(22926): ===== options =====
03-23 15:34:51.116: I/IJKMEDIA(22926): player-opts : overlay-format               = 842225234
03-23 15:34:51.116: I/IJKMEDIA(22926): player-opts : min-frames                   = 80
03-23 15:34:51.116: I/IJKMEDIA(22926): player-opts : packet-buffering             = 0
03-23 15:34:51.116: I/IJKMEDIA(22926): format-opts : ijkinject-opaque             = 491782998
03-23 15:34:51.116: I/IJKMEDIA(22926): format-opts : nobuffer                     = 1
03-23 15:34:51.116: I/IJKMEDIA(22926): ===================
03-23 15:34:51.126: D/IJKMEDIA(22926): ijkmp_prepare_async()=0
03-23 15:34:51.126: I/IJKMEDIA(22926): SDL_RunThread: [23845] ff_msg_loop
03-23 15:34:51.126: D/IJKMEDIA(22926): message_loop
03-23 15:34:51.126: D/IJKMEDIA(22926): FFP_MSG_FLUSH:
03-23 15:34:51.126: I/IJKMEDIA(22926): SDL_RunThread: [23847] ff_read
03-23 15:34:51.126: I/IJKMEDIA(22926): SDL_RunThread: [23846] ff_vout
03-23 15:34:51.256: E/IJKMEDIA(22926): error reading header
03-23 15:34:51.256: E/IJKMEDIA(22926): http://replay.xiuimg.com/release/bo19_4776db3931c6b0b60d148dfdb230b218-1458697580_flv/bo19_4776db3931c6b0b60d148dfdb230b218-1458697580.mp4: Invalid data found when processing input
03-23 15:34:51.256: I/IJKMEDIA(22926): SDL_JNI_DetachThreadEnv: [23847]
03-23 15:34:51.256: D/IJKMEDIA(22926): FFP_MSG_ERROR: 0
03-23 15:34:51.256: E/tv.danmaku.ijk.media.player.IjkMediaPlayer(22926): Error (-10000,0)
03-23 15:34:51.516: D/dalvikvm(22926): GC_FOR_ALLOC freed 3017K, 14% free 20440K/23632K, paused 34ms, total 34ms
03-23 15:34:51.526: D/IJKMEDIA(22926): IjkMediaPlayer_native_finalize
03-23 15:34:51.526: D/IJKMEDIA(22926): IjkMediaPlayer_release
03-23 15:34:51.526: D/IJKMEDIA(22926): IjkMediaPlayer_native_finalize
03-23 15:34:51.526: D/IJKMEDIA(22926): IjkMediaPlayer_release
03-23 15:34:51.526: D/IJKMEDIA(22926): IjkMediaPlayer_native_finalize
03-23 15:34:51.526: D/IJKMEDIA(22926): IjkMediaPlayer_release
03-23 15:34:51.526: D/IJKMEDIA(22926): IjkMediaPlayer_native_finalize
03-23 15:34:51.526: D/IJKMEDIA(22926): IjkMediaPlayer_release

**Comment by zhangbl** [comment]
03-23 15:34:51.116: D/IJKMEDIA(22926): IjkMediaPlayer_prepareAsync
03-23 15:34:51.116: D/IJKMEDIA(22926): ijkmp_prepare_async()
03-23 15:34:51.116: I/IJKMEDIA(22926): ===== versions =====
03-23 15:34:51.116: I/IJKMEDIA(22926): FFmpeg       : ff2.8--ijk0.4.1.1--dev0.3.3--rc4
03-23 15:34:51.116: I/IJKMEDIA(22926): libavutil    : 54.31.100
03-23 15:34:51.116: I/IJKMEDIA(22926): libavcodec   : 56.60.100
03-23 15:34:51.116: I/IJKMEDIA(22926): libavformat  : 56.40.101
03-23 15:34:51.116: I/IJKMEDIA(22926): libswscale   : 3.1.101
03-23 15:34:51.116: I/IJKMEDIA(22926): libswresample: 1.2.101
03-23 15:34:51.116: I/IJKMEDIA(22926): ===== options =====
03-23 15:34:51.116: I/IJKMEDIA(22926): player-opts : overlay-format               = 842225234
03-23 15:34:51.116: I/IJKMEDIA(22926): player-opts : min-frames                   = 80
03-23 15:34:51.116: I/IJKMEDIA(22926): player-opts : packet-buffering             = 0
03-23 15:34:51.116: I/IJKMEDIA(22926): format-opts : ijkinject-opaque             = 491782998
03-23 15:34:51.116: I/IJKMEDIA(22926): format-opts : nobuffer                     = 1
03-23 15:34:51.116: I/IJKMEDIA(22926): ===================
03-23 15:34:51.126: D/IJKMEDIA(22926): ijkmp_prepare_async()=0
03-23 15:34:51.126: I/IJKMEDIA(22926): SDL_RunThread: [23845] ff_msg_loop
03-23 15:34:51.126: D/IJKMEDIA(22926): message_loop
03-23 15:34:51.126: D/IJKMEDIA(22926): FFP_MSG_FLUSH:
03-23 15:34:51.126: I/IJKMEDIA(22926): SDL_RunThread: [23847] ff_read
03-23 15:34:51.126: I/IJKMEDIA(22926): SDL_RunThread: [23846] ff_vout
03-23 15:34:51.256: E/IJKMEDIA(22926): error reading header
03-23 15:34:51.256: E/IJKMEDIA(22926): http://**********************bo19_4776db3931c6b0b60d148dfdb230b218-1458697580.mp4: Invalid data found when processing input
03-23 15:34:51.256: I/IJKMEDIA(22926): SDL_JNI_DetachThreadEnv: [23847]
03-23 15:34:51.256: D/IJKMEDIA(22926): FFP_MSG_ERROR: 0
03-23 15:34:51.256: E/tv.danmaku.ijk.media.player.IjkMediaPlayer(22926): Error (-10000,0)
03-23 15:34:51.516: D/dalvikvm(22926): GC_FOR_ALLOC freed 3017K, 14% free 20440K/23632K, paused 34ms, total 34ms
03-23 15:34:51.526: D/IJKMEDIA(22926): IjkMediaPlayer_native_finalize
03-23 15:34:51.526: D/IJKMEDIA(22926): IjkMediaPlayer_release
03-23 15:34:51.526: D/IJKMEDIA(22926): IjkMediaPlayer_native_finalize
03-23 15:34:51.526: D/IJKMEDIA(22926): IjkMediaPlayer_release
03-23 15:34:51.526: D/IJKMEDIA(22926): IjkMediaPlayer_native_finalize
03-23 15:34:51.526: D/IJKMEDIA(22926): IjkMediaPlayer_release

**Comment by bbcallen** [comment]
Why do you add "nobuffer = 1"

**Comment by hewking** [comment]
@你好 我也遇到这个问题tv.danmaku.ijk.media.player.IjkMediaPlayer(18164): Error (-10000,0)还有这个
 load_library(linker.cpp:761): library "libmaliinstr.so" not found  请问有啥解决的方法吗

**Comment by zhangli1845** [comment]
朋友这个问题解决了吗？我也遇到是同样的代码。只在某些手机上出问题
