### ISSUE TITLE
关于ijkplayer添加GPUImage 滤镜的问题

### ISSUE THREAD

**Issue by seu070507** [Bilibili/ijkplayer#1063]
@bbcallen 大神，请问ijkplayer 视频解码完成以后，渲染之前加上GPUimage的滤镜能否实现？
现在的渲染是在native层用NativeWindow做的。是否需要在java层重写onDrawFrame，然后调用GPUimage来做？如果这么做的话，可行性如何呢？

**Comment by bbcallen** [comment]
There is a GLES render, you can add your shader there.

**Comment by seu070507** [comment]
@bbcallen  
这个native层的render我看到了，如果这么做的话，要把GPUimage里面的shader提取出来，重新封装一下。 我是想复用GPUImage的java层代码。如果能够用GLSurfaceView的Render中的onDrawFrame就完美了。
不知道这种想法可不可行呢？

**Comment by bbcallen** [comment]
I don't know.
Not familiar with GPUimage.

**Comment by seu070507** [comment]
@bbcallen 大神，我有一种思路想向你求证一下：
我们知道ijk是用的egl在native层进行的渲染到窗口，如果我将texturesurface的texture id
传到native层，然后利用eglCreatePbufferSurface 这个函数把 解码出的数据渲染到 texture 纹理（而不是直接到window），
最后在java层把这个texture 纹理作为输入，给shader做效果，最后再渲染到窗口，不知道我这种思路有问题吗？

**Comment by bbcallen** [comment]
I don't know.
But seems you need to upload texture twice.

**Comment by seu070507** [comment]
@bbcallen 准备按以下方案来实施:
1 eglcontext的渲染操作放在java层做
2 native层的video_display2函数会循环调用java层的redraw接口去做渲染(EGL开始的初始化工作也可以在这里面去做).

谢谢,有新的进展.我再更新

**Comment by KarvenMa** [comment]
@seu070507 大神，你好，我们现在对视频渲染有些疑问想交流一下，方面留个联系方式。
我们的邮箱是 mj_623ok@126.com

**Comment by sugar0811** [comment]
@seu070507  您好，方便留个联系方式吗？ 我现在也需要在ijkplayer播放器上做实时视频渲染，交流一下。

**Comment by ChaseWang** [comment]
大家用中文问的问题 回答不能用中文吗 还是大神本身是个老外？ @bbcallen
