### ISSUE TITLE
[IJKFFMoviePlayerController setLogReport:NO]; is useless

### ISSUE THREAD

**Issue by xu01** [Bilibili/ijkplayer#1066]
[IJKFFMoviePlayerController setLogReport:NO];

but the logs on the console too.

**Comment by bbcallen** [comment]
Yes, I'm planning to remove this method.

**Comment by xu01** [comment]
@bbcallen  ok, is there any other way to set no report on Debug?

**Comment by bbcallen** [comment]
Not for now.
