### ISSUE TITLE
请问开源的IJK版本和bilibili 客户端使用的版本是同一个么，感觉bilibili版本加载速度要快很多呢？

### ISSUE THREAD

**Issue by Mongolian** [Bilibili/ijkplayer#1067]

**Comment by bbcallen** [comment]
Is there any difference for you, if I say yes or no?

**Comment by Mongolian** [comment]
没有不同，我在对比我们的播放体验和Bilibili客户端感觉有差距，想知道是我使用的方式有问题，还是本身底层库支持上面的不同， 是有不同么？

**Comment by bbcallen** [comment]
The traffic speed is mostly depending on the quality of video CDN, not player itself.
