### ISSUE TITLE
tools/do-compile-ffmpeg.sh: line 208: cd: /ijkplayer-ios/ios/ffmpeg-armv7: No such file or directory

### ISSUE THREAD

**Issue by rncl** [Bilibili/ijkplayer#1068]
Excute me, when I run "./compile-ffmpeg.sh all", it seems existing some error. May some steps I'm doing wrong, or "do-compile-ffmpeg.sh" might have little mistake?

**Comment by bbcallen** [comment]
Take a look at previous issues.
