### ISSUE TITLE
Use MediaController has some problems

### ISSUE THREAD

**Issue by liuyuejinqiu** [Bilibili/ijkplayer#1069]
播放m3u8网络视频文件时，当手拖动seekbar进行seek时，“播放器实际seek的点”和“拖动到达的最后的点”误差很大。直接点击seekbar到某一点，播放器seek的点比较准确，可是拖动seekbar时问题特别明显（ijkmediademo中的Sample中也存在这个问题），不知有什么好的解决方案

**Comment by FrankLove** [comment]
why can not understand this question?
一句话就是点击seekbar和拖动seekbar定位的视频位置点有很大的误差。建议打印下这两个值，然后在process的监听里面处理下看

**Comment by liuyuejinqiu** [comment]
03-24 15:43:46.027: D/PlayerActivity(10442): mMediaPlayer,progress:3422720
03-24 15:43:46.047: I/VideoPlayerActivity(10442): =====3626453
03-24 15:43:46.047: D/PlayerActivity(10442): mMediaPlayer,progress:3626453
03-24 15:43:46.067: I/VideoPlayerActivity(10442): =====3845466
03-24 15:43:46.067: D/PlayerActivity(10442): mMediaPlayer,progress:3845466
03-24 15:43:46.077: I/VideoPlayerActivity(10442): =====3996556
03-24 15:43:46.077: D/PlayerActivity(10442): mMediaPlayer,progress:3996556
03-24 15:43:46.097: I/VideoPlayerActivity(10442): =====4183894
03-24 15:43:46.097: D/PlayerActivity(10442): mMediaPlayer,progress:4183894
03-24 15:43:46.117: I/VideoPlayerActivity(10442): =====4308787
03-24 15:43:46.117: D/PlayerActivity(10442): mMediaPlayer,progress:4308787
03-24 15:43:46.127: I/VideoPlayerActivity(10442): =====4522145
03-24 15:43:46.127: D/PlayerActivity(10442): mMediaPlayer,progress:4522145
03-24 15:43:46.147: I/VideoPlayerActivity(10442): =====4636629
03-24 15:43:46.147: D/PlayerActivity(10442): mMediaPlayer,progress:4636629
03-24 15:43:46.167: I/VideoPlayerActivity(10442): =====4751114
03-24 15:43:46.167: D/PlayerActivity(10442): mMediaPlayer,progress:4751114
03-24 15:43:46.177: I/VideoPlayerActivity(10442): =====4823968
03-24 15:43:46.187: D/PlayerActivity(10442): mMediaPlayer,progress:4823968
03-24 15:43:46.197: I/VideoPlayerActivity(10442): =====4902026
03-24 15:43:46.197: D/PlayerActivity(10442): mMediaPlayer,progress:4902026
03-24 15:43:46.217: I/VideoPlayerActivity(10442): =====4943656
03-24 15:43:46.217: D/PlayerActivity(10442): mMediaPlayer,progress:4943656
03-24 15:43:46.237: I/VideoPlayerActivity(10442): =====4980083
03-24 15:43:46.247: D/PlayerActivity(10442): mMediaPlayer,progress:4980083
03-24 15:43:46.267: I/VideoPlayerActivity(10442): =====5026918
03-24 15:43:46.267: D/PlayerActivity(10442): mMediaPlayer,progress:5026918
03-24 15:43:46.297: I/VideoPlayerActivity(10442): =====5052937
**03-24 15:43:46.307: D/PlayerActivity(10442): mMediaPlayer,progress:5052937**
03-24 15:43:47.058: I/VideoPlayerActivity(10442): =====1125626
03-24 15:43:48.069: I/VideoPlayerActivity(10442): =====1124050
03-24 15:43:49.080: I/VideoPlayerActivity(10442): =====1125064


This line "03-24 15:43:46.307: D/PlayerActivity(10442): mMediaPlayer,progress:5052937"
这行log是在IjkVideoView的seekTo方法中打印出来的
 @Override
    public void seekTo(int msec) {
        if (isInPlaybackState()) {
            Log.d("PlayerActivity", "mMediaPlayer,progress:" + msec);
            mMediaPlayer.seekTo(msec);
            mSeekWhenPrepared = 0;
        } else {
            mSeekWhenPrepared = msec;
        }
    }
正常的情况下 播放器应当seek到5052937，可实际上是跳转到了1125626这个点


这个怎么处理一下比较好呢

**Comment by bbcallen** [comment]
What do you mean "直接点击seekbar到某一点，其准确度还可以"

**Comment by liuyuejinqiu** [comment]
两种操作seekbar的方式
1.当点击seekbar时，播放器同样会执行seekTo方法，这种情况下播放器seek的点是准确的。
2.当拖动seekbar时，有时就会出现以上的情况
