### ISSUE TITLE
ijkplayer可以实现进入后台后音频仍然继续播放吗？如何实现？

### ISSUE THREAD

**Issue by richardvip** [Bilibili/ijkplayer#1071]

**Comment by richardvip** [comment]
For iOS,Thanks.

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/ios/IJKMediaPlayer/IJKMediaPlayer/IJKFFMoviePlayerController.h#L85

**Comment by fenglinxiu** [comment]
Just set in your target setting. 
Capabilities-->Background Modes 
Then choose mode "audio,airplay,and picture in picture".
Done. So easy!
