### ISSUE TITLE
Android获取下载速率，播放时延

### ISSUE THREAD

**Issue by SteveFrank** [Bilibili/ijkplayer#1072]
hi , 
   请问，在Android环境下如何获取下载速率，以及用户在点击网络视频播放之后到真正视频播放时间的时间差可以进行计算吗？谢谢

**Comment by bbcallen** [comment]
No API for this on Android.
You can implement it by yourself as iOS does.
https://github.com/Bilibili/ijkplayer/blob/master/ios/IJKMediaPlayer/IJKMediaPlayer/IJKFFMoviePlayerController.m#L736

**Comment by SteveFrank** [comment]
多谢！
