### ISSUE TITLE
Please help.I can't understand.

### ISSUE THREAD

**Issue by xclidongbo** [Bilibili/ijkplayer#1077]
# import ios/IJKMediaPlayer for MediaPlayer.framework-like interface (recommended)
# open ios/IJKMediaDemo/IJKMediaDemo.xcodeproj with Xcode

What's the mean in Chinese?

**Comment by bbcallen** [comment]
导入 ios/IJKMediaPlayer 以获得类似 MediaPlayer.framework 的接口。
在 Xcode 中打开 ios/IJKMediaDemo/IJKMediaDemo.xcodeproj

**Comment by xclidongbo** [comment]
@bbcallen  非常感谢.Thanks a lot.
