### ISSUE TITLE
ijkplayer资源释放的消息回调

### ISSUE THREAD

**Issue by wbi1987** [Bilibili/ijkplayer#1078]
ijkplayer的资源释放好像是异步的，目前没有释放成功的回调消息，请问一下如果我要加这个回调消息，是不是在ff_ffplay.c文件中的stream_close()方法里面抛事件上来？我在这个方法的最后抛了一个释放成功的消息，请问在这里抛能保证资源已经完全释放成功了吗？代码如下：

static void stream_close(FFPlayer *ffp)
{
    VideoState *is = ffp->is;
    /* XXX: use a special url_shutdown call to abort parse cleanly */
    is->abort_request = 1;
    packet_queue_abort(&is->videoq);
    packet_queue_abort(&is->audioq);
    av_log(NULL, AV_LOG_DEBUG, "wait for read_tid\n");
    SDL_WaitThread(is->read_tid, NULL);

    /* close each stream */
    if (is->audio_stream >= 0)
        stream_component_close(ffp, is->audio_stream);
    if (is->video_stream >= 0)
        stream_component_close(ffp, is->video_stream);
#ifdef FFP_MERGE
    if (is->subtitle_stream >= 0)
        stream_component_close(ffp, is->subtitle_stream);
#endif

    avformat_close_input(&is->ic);

    av_log(NULL, AV_LOG_DEBUG, "wait for video_refresh_tid\n");
    SDL_WaitThread(is->video_refresh_tid, NULL);

    packet_queue_destroy(&is->videoq);
    packet_queue_destroy(&is->audioq);
#ifdef FFP_MERGE
    packet_queue_destroy(&is->subtitleq);
#endif

    /* free all pictures */
    frame_queue_destory(&is->pictq);
    frame_queue_destory(&is->sampq);
#ifdef FFP_MERGE
    frame_queue_destory(&is->subpq);
#endif
    SDL_DestroyCond(is->continue_read_thread);
    SDL_DestroyMutex(is->play_mutex);
#if !CONFIG_AVFILTER
    sws_freeContext(is->img_convert_ctx);
#endif
#ifdef FFP_MERGE
    sws_freeContext(is->sub_convert_ctx);
#endif
    av_free(is->filename);
    av_free(is);

   ffp_notify_msg1(ffp, FFP_MSG_RELEASE_SUCCESS);
}

**Comment by wbi1987** [comment]
这个地方发消息好像发不上去，请问一下在哪发送是正确的？

**Comment by bbcallen** [comment]
Messages are dispatched asynchronous.
It's very likely that the message loop is closed before the message could be handled.

Why don't you register your own callback directly?

**Comment by wbi1987** [comment]
我可以不用ijkplayer本身的消息机制，我自己写一个消息回调，我就是想确认一下在什么地方发这个消息能确保资源都释放成功了，感觉好像在ffp_destroy()里面比较合适！想确认一下，谢谢！

**Comment by bbcallen** [comment]
I don't know.
Maybe it's suitable for now.
But there is no guarantee that it will remain suitable in the future.

Since you've reached such level.
I think a simple breakpoint in IDE could tell you everything.

**Comment by zhangcheng1989** [comment]
@wbi1987 能分享下不，
