### ISSUE TITLE
Android: E/IJKMEDIA﹕ SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -22

### ISSUE THREAD

**Issue by michalliu** [Bilibili/ijkplayer#1079]
To reproduce.

    1. create two SurfaceTexture
    2. call setSurface between them

It seems the first surface texture is not released when the mediaplayer has switched to the second surface.

**Comment by michalliu** [comment]
It turns out i need to release the surface in java side. it needs to call "surface.release()". I created a new surface everytime without release them.

**Comment by qwuip789** [comment]
> It turns out i need to release the surface at java side. it needs to call "surface.release()". I created a new surface everytime without releasing them.

Where should I call surface.release() to ensure the Surface is properly released
