### ISSUE TITLE
how to build mips

### ISSUE THREAD

**Issue by aii1991** [Bilibili/ijkplayer#1080]
i need to compatible mips platform,can i tell me how to build mips

**Comment by lyqaiym** [comment]
我在android/contrib/tools的do-compile-ffmpeg.sh加上
elif [ "$FF_ARCH" = "mips" ]; then

    FF_BUILD_NAME=ffmpeg-mips
    FF_BUILD_NAME_OPENSSL=openssl-mips
    FF_SOURCE=$FF_BUILD_ROOT/$FF_BUILD_NAME

    FF_CROSS_PREFIX=mipsel-linux-android
    FF_TOOLCHAIN_NAME=${FF_CROSS_PREFIX}-${FF_GCC_64_VER}

    FF_CFG_FLAGS="$FF_CFG_FLAGS --arch=mips --cpu=mips32r2"

    FF_EXTRA_CFLAGS="$FF_EXTRA_CFLAGS"
    FF_EXTRA_LDFLAGS="$FF_EXTRA_LDFLAGS"

    FF_ASSEMBLER_SUB_DIRS="mips"
就能编译成功了，但是在虚拟机播放flv和hls都有bug，出现指针0

**Comment by bbcallen** [comment]
I don't know.
I don't have any mips devices.
