### ISSUE TITLE
Android集成问题

### ISSUE THREAD

**Issue by cenyuankeith** [Bilibili/ijkplayer#1081]
AS如果要使用 tv.danmaku.ijk.media:ijkplayer-arm64:0.4.5.1 需要将 minSdkVersion 设置成21以上才能run得起来，但如果将minSdkVersion 设置成21，编译的APK，低版本的手机又不能安装，如何解决这个问题？

**Comment by bbcallen** [comment]
Modify it to the number you need.

**Comment by garrickjubiao** [comment]
you dont need to set minSdVersion 21 。 you just add :
<uses-sdk tools:overrideLibrary="tv.danmaku.ijk.media.player_arm64"></uses-sdk> in your AndroidManifest.xml。

**Comment by likaiyuan559** [comment]
@garrickjubiao I'm sorry,can you specific?

**Comment by cenyuankeith** [comment]
@garrickjubiao @bbcallen Thanks
