### ISSUE TITLE
关于av_usleep问题

### ISSUE THREAD

**Issue by wqmijkplayer** [Bilibili/ijkplayer#1083]
@bbcallen 我现在遇到一个奇怪问题
我使用的是android版ijkplayer，ffplay_video_refresh_thread线程中使用av_usleep进行sleep 10ms，但是播放一会后，sleep的时间就会超过10ms，有时甚至sleep长达50ms。
网上查了一下，可能是线程调度的问题
请问，这大概是什么原因？十分感谢

**Comment by wqmijkplayer** [comment]
也就是从某个时刻开始，每次sleep的时间都达到40-50ms，这样视频显示将会卡顿

**Comment by bbcallen** [comment]
How did you profile it?

**Comment by SuperMan-Lfj** [comment]
我也发现这个问题了。安卓 上，后台之后，av_usleep就不会很准。目前不知道怎么解决。
