### ISSUE TITLE
can't stream https on ios

### ISSUE THREAD

**Issue by postolaki** [Bilibili/ijkplayer#1086]
i've compiled the project with openssl, Allow Arbitrary Loads is enabled

**Comment by Assylkhan** [comment]
+

**Comment by Assylkhan** [comment]
I've run following commands: ./init-ios.sh; ./compile-ffmpeg.sh clean; ./compile-ffmpeg.sh all; ./compile-openssl.sh clean; ./compile-openssl.sh all. But i get "https protocol not found, recompile FFmpeg with openssl, gnutls,
or securetransport enabled.".

**Comment by bbcallen** [comment]
You need to build OpenSSL first.

**Comment by Assylkhan** [comment]
You mean first "./compile-openssl.sh"? I've built but the same error.

**Comment by bbcallen** [comment]
OpenSSL should be built before FFmpeg, so FFmpeg could detect OpenSSL, and link it.
That's to say, after you build OpenSSL, run "sh compile-ffmpeg.sh clean", and rebuild FFmpeg.

**Comment by patzhangjiwang** [comment]
i have the same problem.
i build OpenSSL first, then build FFmpeg
also get "https protocol not found, recompile FFmpeg with openssl, gnutls,
or securetransport enabled.".

**Comment by patzhangjiwang** [comment]
solved

**Comment by loneystar1983** [comment]
patzhangjiwang how solved?

**Comment by Antony-Lee** [comment]
@patzhangjiwang 
Can you show the step you solved this problem?
I have the same problem here in ios.

**Comment by ttmdung203** [comment]
I solved it. 

1 ) ./init-ios-openssl.sh
2 ) ./init-ios.sh

then cd ios

3.1) ./compile-openssl.sh clean //if u did compiled before
3.2) ./compile-ffmpeg.sh clean //if u did compiled before
4.1) ./compile-openssl.sh all
4.2) ./compile-ffmpeg.sh all

Done 💃 
Hope it useful for u :)

**Comment by Antony-Lee** [comment]
Thanks!










在 2016-12-23 19:01:30，"ttmdung203" <notifications@github.com> 写道：


I solved it.

1 ) ./init-ios-openssl.sh
2 ) ./init-ios.sh

then cd ios

3.1) ./compile-openssl.sh clean //if u did compiled before
3.2) ./compile-ffmpeg.sh clean //if u did compiled before
4.1) ./compile-openssl.sh all
4.2) ./compile-ffmpeg.sh all

Done 💃
Hope it useful for u :)

**Comment by isurukej** [comment]
I got this error after did @ttmdung203 steps

 dyld: Library not loaded: @rpath/IJKMediaFrameworkWithSSL.framework/IJKMediaFrameworkWithSSL
  Referenced from: /var/containers/Bundle/Application/56D9872F-C86C-4961-A66F-C08718636D1F/IJKMediaDemo.app/IJKMediaDemo
  Reason: image not found

**Comment by JRJian** [comment]
First 
1 ) ./init-ios-openssl.sh
2 ) ./init-ios.sh

then cd ios

3.1) ./compile-openssl.sh clean //if u did compiled before
3.2) ./compile-ffmpeg.sh clean //if u did compiled before
4.1) ./compile-openssl.sh all
4.2) ./compile-ffmpeg.sh all

Open IJKMediaDemo
Select subproject IJKMediaPlayer.xcodeproj 
Select target IJKMediaFrameworkWithSSL 
Add the libcrypto.a and libssl.a in 【Build  Phases】-【Link Binary With Libraries】

Select main project IJKMediaDemo
Open IJKVideoViewController.h and replace #import <IJKMediaFramework/IJKMediaFrameworkL.h> with #import <IJKMediaFrameworkWithSSL/IJKMediaFrameworkWithSSL.h>

Allow ATS，search "IOS ATS" on search engine

Find a video url using Https protocol.

Build

**Comment by James-Geng** [comment]
How do you fix it? @isurukej

**Comment by James-Geng** [comment]
build settings -> linking ->runpath search path 

add:

@executable_path/Frameworks

**Comment by BigVeila** [comment]
> OpenSSL should be built before FFmpeg, so FFmpeg could detect OpenSSL, and link it. That's to say, after you build OpenSSL, run "sh compile-ffmpeg.sh clean", and rebuild FFmpeg.

Hello, I do build OpenSSL first but if I do that, after I build FFmpeg, all libs OpenSSL compile removed, like libcrypto.a
