### ISSUE TITLE
Reduce buffer/cache size?

### ISSUE THREAD

**Issue by mianharisali** [Bilibili/ijkplayer#1087]
is there any way to reduce the cache/buffer(audio and video) size on android?

when the it starts the video playback from a file , it buffers/cache some data in advance; I want to know how can we change its value?

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/ff_ffplay_options.h#L110
Take a look at these player options.
