### ISSUE TITLE
[iOS] Change Playback file on the fly cause crash

### ISSUE THREAD

**Issue by a4tech** [Bilibili/ijkplayer#1088]
Hello all,

I have a problem.

Situation:

1. I am playing a file.
2. I press custom button( it STOP playback by 

[self.player stop]

3. I replace automatically same file with different movie ( same location, same filename etc)

4.I make 

[self.player preparePlay]

It does not play from begenning and openning new file it just crash

ijkmp_stop()

ijkmp_stop()=0

ijkmp_set_data_source(url="/var/mobile/Containers/Data/Application/asdf-1D11-4550-ACC3-926EA2012348/Library/Caches/test.ts")

ijkmp_set_data_source(url="/var/mobile/Containers/Data/Application/asdf-1D11-4550-ACC3-926EA2012348/Library/Caches/test.ts")=-3

ijkmp_prepare_async()

Assertion failed: (!ffp->is), function ffp_prepare_async_l, file /Users/xxxx/Documents//ijkmedia/ijkplayer/ff_ffplay.c, line 3451.

Any idea how to reopen same file - without closing ViewController ?

When I make:

[self.player stop];

replace file

[self.player start];

Here is a log:

> 
> ijkmp_stop()
> ijkmp_stop()=0
> 
> ijkmp_start()
> ijkmp_start()=-3

**Comment by bbcallen** [comment]
It's not designed to be used like that.
Always create new player for a new URL

**Comment by a4tech** [comment]
Thanks for info.

The idea was to change movie list by swype gesture - left / right thats why I ask for that.

**Comment by a4tech** [comment]
Fixed on latest commits. Thanks for tip.

Now Android has that issue with Surface.

https://github.com/Bilibili/ijkplayer/issues/670#issuecomment-209056329
