### ISSUE TITLE
[iOS]视频暂停时，转屏后图片拉伸

### ISSUE THREAD

**Issue by KevinFengGit** [Bilibili/ijkplayer#1090]
视频播放使用IJKFFMoviePlayerController时，视屏处于播放状态时，转屏后图像可以自适应屏幕播放。但是视频处于暂停状态，转屏后图像被拉伸。（取消了强制横屏播放）

**Comment by bbcallen** [comment]
setContentMode or layoutSubviews after rotation as a workaround.
