### ISSUE TITLE
libijkffmpeg.so has text relocations

### ISSUE THREAD

**Issue by Dimezis** [Bilibili/ijkplayer#1092]
I am using x86 device with 6.0 Android version.
Unfortunately the app is crashing because of:

java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.eightbitlab.muster-1/lib/x86/libijkffmpeg.so: has text relocations

Any suggestions?

**Comment by rooque** [comment]
See https://github.com/Bilibili/ijkplayer/pull/953 ... Not a solution, but a workaround.
