### ISSUE TITLE
H.265, MediaCodec doest not work.

### ISSUE THREAD

**Issue by Lennith** [Bilibili/ijkplayer#1095]
When decoding a h265 mp4 file or flv file, mediaCodec will not be used, only avcodec supported.
PS: tested on snapdragon 820 , H265 HW supported.

**Comment by bbcallen** [comment]
It's disabled by default.
Did you enable it?

**Comment by Lennith** [comment]
How...

**Comment by Lennith** [comment]
solved. thx= =
