### ISSUE TITLE
android 版本编译后为什么没有生成三个ijkmediawidget、ijkmediaplayer、ijkdemo三个工程呢

### ISSUE THREAD

**Issue by FrankLove** [Bilibili/ijkplayer#1096]
android 版本编译后为什么没有生成三个ijkmediawidget、ijkmediaplayer、ijkdemo三个工程呢？现在编译生成的在eclipse使用需要导入所以工程，感觉很不方便，有什么办法可以让它生成这个三个工程呢

**Comment by bbcallen** [comment]
Because I don't like to
