### ISSUE TITLE
hi,sir,i have an error while i build:tools/do-compile-openssl.sh: line 167: cd: /Users/dengpan/ijkplayer-ios/ios/openssl-armv7: No such file or directory

### ISSUE THREAD

**Issue by beydeng** [Bilibili/ijkplayer#1097]

**Comment by bbcallen** [comment]
Did you run "sh init-iso.sh" successfully?

**Comment by beydeng** [comment]
yes 
== pull gas-preprocessor base ==
Fetching origin
/Users/dengpan/ijkplayer-ios
== pull ffmpeg base ==
Fetching origin
/Users/dengpan/ijkplayer-ios
== pull ffmpeg fork armv7 ==
Fetching origin
/Users/dengpan/ijkplayer-ios
Reset branch 'ijkplayer'
/Users/dengpan/ijkplayer-ios
== pull ffmpeg fork arm64 ==
Fetching origin
/Users/dengpan/ijkplayer-ios
Reset branch 'ijkplayer'
/Users/dengpan/ijkplayer-ios
== pull ffmpeg fork i386 ==
Fetching origin
/Users/dengpan/ijkplayer-ios
Reset branch 'ijkplayer'
/Users/dengpan/ijkplayer-ios
== pull ffmpeg fork x86_64 ==
Fetching origin
/Users/dengpan/ijkplayer-ios
Reset branch 'ijkplayer'
/Users/dengpan/ijkplayer-ios


it's successfully?

**Comment by beydeng** [comment]
@bbcallen  while i run compile-openssl.sh ,this error has occurred.

**Comment by bbcallen** [comment]
Did you run "sh init-ios-openssl.sh" successfully?

**Comment by beydeng** [comment]
@bbcallen No,while i run init-ios-openssl.sh,it will show me the error :tools/do-compile-openssl.sh: line 167: cd: /Users/dengpan/ijkplayer-ios/ios/openssl-armv7: No such file or directory

**Comment by bbcallen** [comment]
Log ?

**Comment by beydeng** [comment]
yes ,the terminal show me this one

**Comment by bbcallen** [comment]
I mean the full log.

**Comment by beydeng** [comment]
====================
[*] check xcode version
====================
FF_ALL_ARCHS = armv7 arm64 i386 x86_64
====================
[*] check host
====================
build_root: /Users/dengpan/ijkplayer-ios/ios
====================
[*] config arch armv7
====================
build_name: openssl-armv7
platform:   iPhoneOS
osversion:  -miphoneos-version-min=6.0
====================
[*] make ios toolchain openssl-armv7
====================
build_source: /Users/dengpan/ijkplayer-ios/ios/openssl-armv7
build_prefix: /Users/dengpan/ijkplayer-ios/ios/build/openssl-armv7/output
CROSS_TOP: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer
CROSS_SDK: iPhoneOS9.2.sdk
BUILD_TOOL: /Applications/Xcode.app/Contents/Developer
CC: xcrun -sdk iphoneos clang -arch armv7 -miphoneos-version-min=6.0

--------------------
[*] configurate openssl
--------------------
tools/do-compile-openssl.sh: line 167: cd: /Users/dengpan/ijkplayer-ios/ios/openssl-armv7: No such file or directory


thank you !! man!

**Comment by bbcallen** [comment]
I mean the full log of  "sh init-ios-openssl.sh"
