### ISSUE TITLE
play h263+amr_nb video very fast

### ISSUE THREAD

**Issue by wqmijkplayer** [Bilibili/ijkplayer#1098]
@bbcallen 
play a h263+amr_nb video in http://pan.baidu.com/s/1o7Lp7EM, 
audio clock is error and play very fast.
but play it in vlc is ok
Thanks

**Comment by bbcallen** [comment]
Reproduce in ffplay, too.
Better submit this issue to FFmpeg. I'm not familiar with h263+amr_nb
