### ISSUE TITLE
怎么确定一个是直播还是点播ijkplayer ，有没有这样的API

### ISSUE THREAD

**Issue by blueseaguo** [Bilibili/ijkplayer#1100]

**Comment by tanhx2008** [comment]
怎么可能有，只有应用层知道

**Comment by bbcallen** [comment]
Mostly, you can't get a valid duration from live stream.

**Comment by blueseaguo** [comment]
用hls协议的时候，duration为0 但是用rtmp协议的时候，duration是3600，这都区分不了是直播还是点播了
