### ISSUE TITLE
Too big delay on start playing

### ISSUE THREAD

**Issue by don11995** [Bilibili/ijkplayer#1106]
Hello! I'm trying to play simple video via http and there is too big delay on start of each video - about 4 seconds. I tried to reduce next variables:
`#define MAX_QUEUE_SIZE (1 * 1024 * 1024)
#ifdef FFP_MERGE
#define MIN_FRAMES 5
#endif
#define DEFAULT_MIN_FRAMES  5
#define MIN_MIN_FRAMES      5
#define MAX_MIN_FRAMES      5`

Also I tried to set player options in java:
`        mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
        mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "min-frames", 20);
        mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "start-on-prepared", 1);
        mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "fflags", "nobuffer");
        mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probsize", "4096");
        mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzeduration", "2000000");`

But there is always about 4 seconds on start. How can I set all buffers (preload, runtime) to about 100ms? Thanks.

**Comment by bbcallen** [comment]
Try these options
https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/ff_ffplay_options.h#L114

**Comment by don11995** [comment]
Ok, I tried this and this also not work. For testing I also switched to local server to nullify the network delay.

**Comment by bbcallen** [comment]
Then, there is nothing I can do, for now.

**Comment by don11995** [comment]
I found bug in your player: if I create mediaPlayer and then calling `mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "first-high-water-mark-ms", millis)`, after play clicked video plays for some seconds and then starts from the beginning and then playing normally. Aka seek to start of the buffer. For example, if I start video from 30-th second it plays for 3-4 seconds and then plays again from 30-th second.

**Comment by bbcallen** [comment]
I don't understand. Any source code or log?

**Comment by don11995** [comment]
Ok, I found where this delay happens: in `ff_ffplay.c->read_thread()` function `avformat_find_stream_info(ic, opts)`. This function runs about 4-5 seconds. To reduce delay I wrote next line before: `ic->max_analyze_duration2 = 500000`. This line forces to analyze only first 500ms of the stream for  stream info, by default ffmpeg has 5sec for analyze time. 
`mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzeduration", "2000000");` not working from Java Code.

**Comment by bbcallen** [comment]
Which version are you using?
It seems that max_analyze_duration2 field has been removed from FFmpeg n3.0

**Comment by don11995** [comment]
I'm using your last version - 0.4.5.1. I used Your intructions from respository.

**Comment by don11995** [comment]
If I correctly understood from API documentation, `max_analyze_duration2` renamed to `max_analyze_duration` in ffmpeg 3.0.
