### ISSUE TITLE
播放4K高清视频有明显的卡顿

### ISSUE THREAD

**Issue by Millertoken** [Bilibili/ijkplayer#1107]
你好，我发现播放4K视频的时候有明显的卡顿，但是原声的mediaplayer好像不会。是否和解码速度有关，有什么好的解决办法么？

**Comment by bbcallen** [comment]
Did you enable MediaCodec?

**Comment by 214557835** [comment]
And how to enable MediaCodec?

**Comment by bbcallen** [comment]
See the demo.
