### ISSUE TITLE
how to play RTSP urls on ios IJKPlayer?

### ISSUE THREAD

**Issue by leon790** [Bilibili/ijkplayer#1108]
i read anothers issues and they recomend to remove the timeout, then i try to do that but it doesnt work.

this is my error log...

av_version_info: ff3.0--ijk0.4.5.1--dev0.4.5--rc10
ijkmp_set_inject_opaque(0x15689830)
ijkmp_set_inject_opaque()=void
2016-03-29 16:28:08.619 IJKMediaDemo[493:207626] OK setup GL
ijkmp_ios_set_view(glView=0x156ac990)
ijkmp_ios_set_view(glView=0x156ac990)=void
2016-03-29 16:28:08.625 IJKMediaDemo[493:207626] invalidateRenderBuffer
2016-03-29 16:28:08.628 IJKMediaDemo[493:207899] IJKSDLGLView: setupDisplay not ready
ijkmp_set_data_source(url="rtsp://192.168.100.7:8554/l")
ijkmp_set_data_source(url="rtsp://192.168.100.7:8554/l")=0
ijkmp_prepare_async()
[FFPlayer @ 0x159f8200] remove 'timeout' option for rtmp.
===== versions =====
[FFPlayer @ 0x159f8200] FFmpeg       : ff3.0--ijk0.4.5.1--dev0.4.5--rc10
[FFPlayer @ 0x159f8200] libavutil    : 55.17.103
[FFPlayer @ 0x159f8200] libavcodec   : 57.24.102
[FFPlayer @ 0x159f8200] libavformat  : 57.25.100
[FFPlayer @ 0x159f8200] libswscale   : 4.0.100
[FFPlayer @ 0x159f8200] libswresample: 2.0.101
===== options =====
[FFPlayer @ 0x159f8200] player-opts : videotoolbox-max-frame-width = 960
[FFPlayer @ 0x159f8200] player-opts : overlay-format               = fcc-_es2
[FFPlayer @ 0x159f8200] player-opts : framedrop                    = 0
[FFPlayer @ 0x159f8200] player-opts : max-fps                      = 30
[FFPlayer @ 0x159f8200] player-opts : video-pictq-size             = 3
[FFPlayer @ 0x159f8200] player-opts : videotoolbox                 = 0
[FFPlayer @ 0x159f8200] player-opts : start-on-prepared            = 1
[FFPlayer @ 0x159f8200] format-opts : ijkinject-opaque             = 359176240
[FFPlayer @ 0x159f8200] format-opts : ijkapplication               = 358927904
[FFPlayer @ 0x159f8200] format-opts : user-agent                   = ijkplayer
[FFPlayer @ 0x159f8200] format-opts : auto_convert                 = 0
[FFPlayer @ 0x159f8200] format-opts : safe                         = 0
[FFPlayer @ 0x159f8200] format-opts : reconnect                    = 1
===================
ijkmp_prepare_async()=0
[FFPlayer @ 0x159f8200] remove 'timeout' option for rtmp.
rtsp://192.168.100.7:8554/l: Protocol not found
2016-03-29 16:28:08.659 IJKMediaDemo[493:207626] invalidateRenderBuffer
2016-03-29 16:28:08.660 IJKMediaDemo[493:207899] IJKSDLGLView: setupDisplay not ready
2016-03-29 16:28:08.675 IJKMediaDemo[493:207626] invalidateRenderBuffer
2016-03-29 16:28:08.676 IJKMediaDemo[493:207899] IJKSDLGLView: setupDisplay not ready
2016-03-29 16:28:08.687 IJKMediaDemo[493:207626] FFP_MSG_ERROR: 0
2016-03-29 16:28:08.688 IJKMediaDemo[493:207626] IJKMPMoviePlayBackStateDidChange 2: paused
2016-03-29 16:28:08.689 IJKMediaDemo[493:207626] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1

**Comment by bbcallen** [comment]
RTSP is disabled in default build.
You need to enable it in config/module-lite.sh

**Comment by leon790** [comment]
I already modify the "Config / module-lite.sh " file and put the following line "export "COMMON_FF_CFG_FLAGS =" $ COMMON_FF_CFG_FLAGS --enable - rtp protocol =" but I do not know how to activate it in Xcode or how to the use syntax @bbcallen

**Comment by leon790** [comment]
i already found the solution you have to edit "Config / module-lite.sh " then change line COMMON_FF_CFG_FLAGS =" $ COMMON_FF_CFG_FLAGS --disable - rtp protocol =" to --> COMMON_FF_CFG_FLAGS =" $ COMMON_FF_CFG_FLAGS --enable - rtp protocol ="
and put under that line this: export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=rtsp"

**Comment by wanglifeifei** [comment]
I have, as you suggest to change the “Config/module - lite. sh" configuration, then need to do? @leon790

**Comment by xy13663015647** [comment]
我按照上面提到的方法修改文件，但是我播rtsp流，真机播不了几秒就卡死了，播rtmp就没事，这是怎么回事？

**Comment by chenl326** [comment]
按照上面的配置改了文件 重新编译还是 报着个错  playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1

**Comment by yxnyxnyxnyxn** [comment]
@xy13663015647 请问用哪个demo播放的rtsp啊 我用的sample 没法输入url啊

**Comment by Coder-XL** [comment]
1、我用module-default.sh是可以播放RTSP，但是打的包快500M，太大了。
2、现在是采用修改module-lite.sh文件，
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=rtp"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=rtsp"
然后修改ff_ffplay.c文件，
修改：static int packet_queue_get_or_buffering(FFPlayer *ffp, PacketQueue *q, AVPacket *pkt, int *serial, int *finished)
{
assert(finished);
if (!ffp->packet_buffering)
return packet_queue_get(q, pkt, 1, serial);

while (1) {
    int new_packet = packet_queue_get(q, pkt, 0, serial);
    if (new_packet < 0)
        return -1;
    else if (new_packet == 0) {
        if (q->is_buffer_indicator && !*finished)
            ffp_toggle_buffering(ffp, 1);
        new_packet = packet_queue_get(q, pkt, 1, serial);
        if (new_packet < 0)
            return -1;
    }

    if (*finished == *serial) {
        av_packet_unref(pkt);
        continue;
    }
    else
        break;
}

return 1;
}

TO----->
static int packet_queue_get_or_buffering(FFPlayer *ffp, PacketQueue *q, AVPacket *pkt, int *serial, int finished)

{

while (1) {
    
    int new_packet = packet_queue_get(q, pkt, 1, serial);
    
    if (new_packet < 0)
    
    {
        
        new_packet = packet_queue_get(q, pkt, 0, serial);
        
        if(new_packet < 0)
        
        return -1;
        
    }
    else if (new_packet == 0) {
        
        if (!finished)
        
        ffp_toggle_buffering(ffp, 1);
        
        new_packet = packet_queue_get(q, pkt, 1, serial);
        
        if (new_packet < 0)
        
        return -1;
        
    }
    if (finished == *serial) {
        
        av_free_packet(pkt);
        
        continue;
        
    }
    else
    
    break;
    
}
return 1;
}

然后编译，打包播放不了，我从网上搜到的开源视频流地址：rtsp://218.204.223.237:554/live/1/66251FC11353191F/e7ooqwcfbqjoo80j.sdp

求大家指教！！！

**Comment by unigeniee** [comment]
@CoderXYLan Have you found out a way to resolve it?
