### ISSUE TITLE
IjkMediaPlayer_getMediaMeta 

### ISSUE THREAD

**Issue by RobinLW** [Bilibili/ijkplayer#1110]
_getMediaMeta can not get bitrate infomation.  
I changed below code 
 
    fillMetaInternal(env, jlocal_bundle, meta, IJKM_KEY_START_US, NULL );
    fillMetaInternal(env, jlocal_bundle, meta, IJKM_KEY_START_US, NULL );
    
to

    fillMetaInternal(env, jlocal_bundle, meta, IJKM_KEY_START_US, NULL );
    fillMetaInternal(env, jlocal_bundle, meta, IJKM_KEY_BITRATE, NULL );

and it work

**Comment by bbcallen** [comment]
Fixed: f005eb0b71f6d9c8d0384d2d4ca5ed557428293e
Thanks.

**Comment by RobinLW** [comment]
you are welcom
