### ISSUE TITLE
 duplicate symbol on fifo.o  when  work with Easymob SDK

### ISSUE THREAD

**Issue by gaara0816** [Bilibili/ijkplayer#1111]
duplicate symbol _av_fifo_alloc_array in:
    /Users/Demon/Desktop/VideoDemo/Pods/EaseMobSDKFull/EaseMobSDKFull/lib/libEaseMobClientSDK_x86_64.a(fifo.o)
    /Users/Demon/Desktop/VideoDemo/VideoDemo/IJKMediaFramework.framework/IJKMediaFramework(fifo.o)
duplicate symbol _av_fifo_grow in:
    /Users/Demon/Desktop/VideoDemo/Pods/EaseMobSDKFull/EaseMobSDKFull/lib/libEaseMobClientSDK_x86_64.a(fifo.o)
    /Users/Demon/Desktop/VideoDemo/VideoDemo/IJKMediaFramework.framework/IJKMediaFramework(fifo.o)
duplicate symbol _av_fifo_reset in:
    /Users/Demon/Desktop/VideoDemo/Pods/EaseMobSDKFull/EaseMobSDKFull/lib/libEaseMobClientSDK_x86_64.a(fifo.o)
    /Users/Demon/Desktop/VideoDemo/VideoDemo/IJKMediaFramework.framework/IJKMediaFramework(fifo.o)
duplicate symbol _av_fifo_freep in:
    /Users/Demon/Desktop/VideoDemo/Pods/EaseMobSDKFull/EaseMobSDKFull/lib/libEaseMobClientSDK_x86_64.a(fifo.o)
    /Users/Demon/Desktop/VideoDemo/VideoDemo/IJKMediaFramework.framework/IJKMediaFramework(fifo.o)
duplicate symbol _av_fifo_drain in:
    /Users/Demon/Desktop/VideoDemo/Pods/EaseMobSDKFull/EaseMobSDKFull/lib/libEaseMobClientSDK_x86_64.a(fifo.o)
    /Users/Demon/Desktop/VideoDemo/VideoDemo/IJKMediaFramework.framework/IJKMediaFramework(fifo.o)
duplicate symbol _av_fifo_size in:
    /Users/Demon/Desktop/VideoDemo/Pods/EaseMobSDKFull/EaseMobSDKFull/lib/libEaseMobClientSDK_x86_64.a(fifo.o)
    /Users/Demon/Desktop/VideoDemo/VideoDemo/IJKMediaFramework.framework/IJKMediaFramework(fifo.o)
duplicate symbol _av_fifo_generic_write in:
    /Users/Demon/Desktop/VideoDemo/Pods/EaseMobSDKFull/EaseMobSDKFull/lib/libEaseMobClientSDK_x86_64.a(fifo.o)
    /Users/Demon/Desktop/VideoDemo/VideoDemo/IJKMediaFramework.framework/IJKMediaFramework(fifo.o)
duplicate symbol _av_fifo_free in:
    /Users/Demon/Desktop/VideoDemo/Pods/EaseMobSDKFull/EaseMobSDKFull/lib/libEaseMobClientSDK_x86_64.a(fifo.o)
    /Users/Demon/Desktop/VideoDemo/VideoDemo/IJKMediaFramework.framework/IJKMediaFramework(fifo.o)
duplicate symbol _av_fifo_space in:
    /Users/Demon/Desktop/VideoDemo/Pods/EaseMobSDKFull/EaseMobSDKFull/lib/libEaseMobClientSDK_x86_64.a(fifo.o)
    /Users/Demon/Desktop/VideoDemo/VideoDemo/IJKMediaFramework.framework/IJKMediaFramework(fifo.o)
duplicate symbol _av_fifo_generic_read in:
    /Users/Demon/Desktop/VideoDemo/Pods/EaseMobSDKFull/EaseMobSDKFull/lib/libEaseMobClientSDK_x86_64.a(fifo.o)
    /Users/Demon/Desktop/VideoDemo/VideoDemo/IJKMediaFramework.framework/IJKMediaFramework(fifo.o)
duplicate symbol _av_fifo_alloc in:
    /Users/Demon/Desktop/VideoDemo/Pods/EaseMobSDKFull/EaseMobSDKFull/lib/libEaseMobClientSDK_x86_64.a(fifo.o)
    /Users/Demon/Desktop/VideoDemo/VideoDemo/IJKMediaFramework.framework/IJKMediaFramework(fifo.o)
duplicate symbol _av_fifo_realloc2 in:
    /Users/Demon/Desktop/VideoDemo/Pods/EaseMobSDKFull/EaseMobSDKFull/lib/libEaseMobClientSDK_x86_64.a(fifo.o)
    /Users/Demon/Desktop/VideoDemo/VideoDemo/IJKMediaFramework.framework/IJKMediaFramework(fifo.o)
ld: 12 duplicate symbols for architecture x86_64

**Comment by gaara0816** [comment]
duplicate symbol _OBJC_IVAR_$_IJKVideoViewController._player in:
    /Users/delphi/Library/Developer/Xcode/DerivedData/Dog-bujnijzyajzvthgoluordznrcatu/Build/Intermediates/Dog.build/Debug-iphoneos/Dog.build/Objects-normal/armv7/IJKMoviePlayerViewController-8D68C81513ACBB87.o
duplicate symbol _OBJC_CLASS_$_IJKVideoViewController in:
    /Users/delphi/Library/Developer/Xcode/DerivedData/Dog-bujnijzyajzvthgoluordznrcatu/Build/Intermediates/Dog.build/Debug-iphoneos/Dog.build/Objects-normal/armv7/IJKMoviePlayerViewController-8D68C81513ACBB87.o
duplicate symbol _OBJC_METACLASS_$_IJKVideoViewController in:
    /Users/delphi/Library/Developer/Xcode/DerivedData/Dog-bujnijzyajzvthgoluordznrcatu/Build/Intermediates/Dog.build/Debug-iphoneos/Dog.build/Objects-normal/armv7/IJKMoviePlayerViewController-8D68C81513ACBB87.o
duplicate symbol _OBJC_IVAR_$_IJKVideoViewController._url in:
    /Users/delphi/Library/Developer/Xcode/DerivedData/Dog-bujnijzyajzvthgoluordznrcatu/Build/Intermediates/Dog.build/Debug-iphoneos/Dog.build/Objects-normal/armv7/IJKMoviePlayerViewController-8D68C81513ACBB87.o
duplicate symbol _OBJC_IVAR_$_IJKVideoViewController._mediaControl in:
    /Users/delphi/Library/Developer/Xcode/DerivedData/Dog-bujnijzyajzvthgoluordznrcatu/Build/Intermediates/Dog.build/Debug-iphoneos/Dog.build/Objects-normal/armv7/IJKMoviePlayerViewController-8D68C81513ACBB87.o
ld: 5 duplicate symbols for architecture armv7

**Comment by bbcallen** [comment]
Can't see "fifo.o" in log.

**Comment by gaara0816** [comment]
sorry，i copy the other
