### ISSUE TITLE
 IjkVideoView nested inside the ScrollView

### ISSUE THREAD

**Issue by MROU** [Bilibili/ijkplayer#1121]
The IjkVideoView nested inside the ScrollView, 
 when the scrollview issliding,AndroidMediaController not slide, 
resulting in  AndroidMediaController  and  IjkVideoView  separated

**Comment by bbcallen** [comment]
IjkVideoView is not part of ijkplayer's API, it only belongs to the demo.
You are on your own about all UI stuffs.

**Comment by MROU** [comment]
ths，have already been solved;

1:update AndroidMediaController UI by java reflection


@Override
    public void setAnchorView(View view) {
        super.setAnchorView(view);
        mView = LayoutInflater.from(getContext()).inflate(
                R.layout.video_button, null);
       
            button_play=(ImageView)view.findViewById(R.id.ic_play);
        
        try{

            SeekBar sb = (SeekBar) LayoutInflater.from(getContext()).inflate(
                    R.layout.video_seekbar,null);
            Field mRoot = MediaController.class
                    .getDeclaredField("mRoot");
            mRoot.setAccessible(true);
            mRootVg = (ViewGroup) mRoot.get(this);
            mRootVg.setBackgroundColor(Color.parseColor("#00FFFFFF"));
            ViewGroup vg = findSeekBarParent(mRootVg);
            int index = 1;
            for (int i = 0; i < vg.getChildCount(); i++){
                if (vg.getChildAt(i) instanceof SeekBar){
                    index = i;
                    break;
                }
            }
            vg.removeViewAt(index);
            LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(
                    LayoutParams.WRAP_CONTENT, LayoutParams.WRAP_CONTENT);
            params.weight = 1;
            vg.addView(sb, index, params);
            Field mProgress = MediaController.class
                    .getDeclaredField("mProgress");
            mProgress.setAccessible(true);
            mProgress.set(this, sb);
            sb.setVisibility(View.INVISIBLE);

            Field mEndTime = MediaController.class
                    .getDeclaredField("mEndTime");
            mEndTime.setAccessible(true);
            TextView tv_mEndTime=(TextView)mEndTime.get(this);
            Field mCurrentTime = MediaController.class
                    .getDeclaredField("mCurrentTime");
            mCurrentTime.setAccessible(true);
            TextView tv_mCurrentTime=(TextView)mCurrentTime.get(this);
            tv_mEndTime.setVisibility(View.INVISIBLE);
            tv_mCurrentTime.setVisibility(View.INVISIBLE);

//            Field mSeekListener = MediaController.class
//                    .getDeclaredField("mSeekListener");
//            mSeekListener.setAccessible(true);
//            sb.setOnSeekBarChangeListener((SeekBar.OnSeekBarChangeListener) mSeekListener
//                    .get(this));
            Field mPauseListener = MediaController.class
                    .getDeclaredField("mPauseListener");
            mPauseListener.setAccessible(true);
            Field mPauseButton = MediaController.class
                    .getDeclaredField("mPauseButton");
            mPauseButton.setAccessible(true);
            copy_btn=(ImageButton)mPauseButton.get(this);
            copy_btn.setVisibility(View.GONE);
          
        }
    }

**Comment by MROU** [comment]
ths，have already been solved;

1:update AndroidMediaController UI by java reflection


@Override
    public void setAnchorView(View view) {
        super.setAnchorView(view);
        mView = LayoutInflater.from(getContext()).inflate(
                R.layout.video_button, null);
       
            button_play=(ImageView)view.findViewById(R.id.ic_play);
        
        try{

            SeekBar sb = (SeekBar) LayoutInflater.from(getContext()).inflate(
                    R.layout.video_seekbar,null);
            Field mRoot = MediaController.class
                    .getDeclaredField("mRoot");
            mRoot.setAccessible(true);
            mRootVg = (ViewGroup) mRoot.get(this);
            mRootVg.setBackgroundColor(Color.parseColor("#00FFFFFF"));
            ViewGroup vg = findSeekBarParent(mRootVg);
            int index = 1;
            for (int i = 0; i < vg.getChildCount(); i++){
                if (vg.getChildAt(i) instanceof SeekBar){
                    index = i;
                    break;
                }
            }
            vg.removeViewAt(index);
            LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(
                    LayoutParams.WRAP_CONTENT, LayoutParams.WRAP_CONTENT);
            params.weight = 1;
            vg.addView(sb, index, params);
            Field mProgress = MediaController.class
                    .getDeclaredField("mProgress");
            mProgress.setAccessible(true);
            mProgress.set(this, sb);
            sb.setVisibility(View.INVISIBLE);

            Field mEndTime = MediaController.class
                    .getDeclaredField("mEndTime");
            mEndTime.setAccessible(true);
            TextView tv_mEndTime=(TextView)mEndTime.get(this);
            Field mCurrentTime = MediaController.class
                    .getDeclaredField("mCurrentTime");
            mCurrentTime.setAccessible(true);
            TextView tv_mCurrentTime=(TextView)mCurrentTime.get(this);
            tv_mEndTime.setVisibility(View.INVISIBLE);
            tv_mCurrentTime.setVisibility(View.INVISIBLE);

//            Field mSeekListener = MediaController.class
//                    .getDeclaredField("mSeekListener");
//            mSeekListener.setAccessible(true);
//            sb.setOnSeekBarChangeListener((SeekBar.OnSeekBarChangeListener) mSeekListener
//                    .get(this));
            Field mPauseListener = MediaController.class
                    .getDeclaredField("mPauseListener");
            mPauseListener.setAccessible(true);
            Field mPauseButton = MediaController.class
                    .getDeclaredField("mPauseButton");
            mPauseButton.setAccessible(true);
            copy_btn=(ImageButton)mPauseButton.get(this);
            copy_btn.setVisibility(View.GONE);
          
        }
    }
