### ISSUE TITLE
OpenSSL vulnerabilities in your apps

### ISSUE THREAD

**Issue by diaconuliviu85** [Bilibili/ijkplayer#1122]
Hello

How is my first post here, I can say thank you for your hard work.

I have a problem 24 hours google told me that I have a problem with OpenSSL.
OpenSSL vulnerabilities in your apps.
Although I updated to v1.1 I tried ubuntu and openssl 1.0.2g, and I re-download your source code via git. Always get from google I have a vulnerable version of OpenSSL. You have to update something? or? The figure is the first time such a problem. Thank you

**Comment by bbcallen** [comment]
You can modify the repo url and version to whatever you want by modify this file.
https://github.com/Bilibili/ijkplayer/blob/master/init-android-openssl.sh#L21
