### ISSUE TITLE
ijkmeta_create有内存泄漏

### ISSUE THREAD

**Issue by wbi1987** [Bilibili/ijkplayer#1123]
ios播放器，每次退出的时候调：
[self.player shutdown];
[self.player.view removeFromSuperview];

重新进去播放会重新init，prepareToPlay，play
但是在ijkmeta_create的地方每次都有内存泄漏。

请问一下该怎么解决？

**Comment by bbcallen** [comment]
Sorry I didn't take macbook with me this weekend.
How do you find it's leaked?

**Comment by wbi1987** [comment]
我是在测试频繁进出的时候，用instrument检测的，
Leaked Object	#	Address	                 Size	       Responsible Library	      Responsible Frame
Malloc 48 Bytes	4	< multiple >	192 Bytes	ijkMediaPlayerDemo	ijkmeta_create
Malloc 48 Bytes	1	0x170050260	48 Bytes	ijkMediaPlayerDemo	        ijkmeta_create

**Comment by wbi1987** [comment]
这个地方也有泄漏

Leaked Object	#	Address	Size	Responsible Library	Responsible Frame
Malloc < varying sizes >	15	< multiple >	1.12 KB	ijkMediaPlayerDemo	av_buffer_realloc
Malloc 32 Bytes	16	< multiple >	512 Bytes	libsystem_malloc.dylib	posix_memalign
Malloc 48 Bytes	16	< multiple >	768 Bytes	libsystem_malloc.dylib	posix_memalign

**Comment by wbi1987** [comment]
最新的k4.5.1版本已经没有泄露了，我之前测试的还是旧的版本！
