### ISSUE TITLE
 *** missing separator.  Stop. 不生成os库windows系统

### ISSUE THREAD

**Issue by tianxiao875** [Bilibili/ijkplayer#1126]
/home/Administrator/ijkplayer-master/android/ijkplayer/ijkplayer-armv5/src/main/jni/Android.mk:1: *** missing separator.  Stop.

**Comment by tianxiao875** [comment]
profiler build: NO
/home/Administrator/ijkplayer-master/android/ijkplayer/ijkplayer-armv5/src/main/                      jni/Android.mk:1: *** missing separator.  Stop.
/home/Administrator/ijkplayer-master/android
profiler build: NO
Android NDK: ERROR:/home/Administrator/ijkplayer-master/android/ijkplayer/ijkpla                      yer-armv7a/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a                       missing file
Android NDK: Check that /libijkffmpeg.so exists  or that its path is correct
/cygdrive/f/android-ndk-r10e/build/core/prebuilt-library.mk:45: *** Android NDK:                       Aborting    .  Stop.
/home/Administrator/ijkplayer-master/android
profiler build: NO
Android NDK: ERROR:../../../../ijkplayer-armv7a/src/main/jni/ffmpeg/Android.mk:i                      jkffmpeg: LOCAL_SRC_FILES points to a missing file
Android NDK: Check that /libijkffmpeg.so exists  or that its path is correct
/cygdrive/f/android-ndk-r10e/build/core/prebuilt-library.mk:45: *** Android NDK:                       Aborting    .  Stop.
/home/Administrator/ijkplayer-master/android
profiler build: NO
/home/Administrator/ijkplayer-master/android/ijkplayer/ijkplayer-x86/src/main/jn                      i/Android.mk:1: *** missing separator.  Stop.
/home/Administrator/ijkplayer-master/android
profiler build: NO
/home/Administrator/ijkplayer-master/android/ijkplayer/ijkplayer-x86_64/src/main                      /jni/Android.mk:1: *** missing separator.  Stop.
/home/Administrator/ijkplayer-master/android

**Comment by bbcallen** [comment]
Sorry, I don't maintain build scripts for windows.
I don't even know whether ijkplayer can be built successfully on windows.
