### ISSUE TITLE
IOS开始缓冲对应的方法是哪个

### ISSUE THREAD

**Issue by summeriver** [Bilibili/ijkplayer#1127]
mVideoView.setOnInfoListener(new IMediaPlayer.OnInfoListener() {
            @Override
            public boolean onInfo(IMediaPlayer iMediaPlayer, int i, int i1) {
                switch (i) {
                    case IMediaPlayer.MEDIA_INFO_BUFFERING_START:
                    break;
                }
           }
}
IOS对应的是哪个方法

**Comment by bbcallen** [comment]
No such method.
It's an event triggered by player.
