### ISSUE TITLE
Hello, please help me.. I am in all./compile-ijk.sh after the problem

### ISSUE THREAD

**Issue by tianxiao875** [Bilibili/ijkplayer#1128]
[armeabi] Prebuilt       : libijkffmpeg.so <= /home/Administrator/ijkplayer-android/android/contrib/build/ffmpeg-armv5/output/
[armeabi] Compile thumb  : ijkplayer <= ff_cmdutils.c
[armeabi] Compile thumb  : ijkplayer <= ff_ffplay.c
arm-linux-androideabi-gcc.exe: error: F:/cygwin/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_cmdutils.c: No such file or directory
arm-linux-androideabi-gcc.exe: fatal error: no input files
compilation terminated.
[armeabi] Compile thumb  : ijkplayer <= ff_ffpipeline.c
/cygdrive/f/android-ndk-r10e/build/core/build-binary.mk:464: recipe for target '/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-armv5/src/main/obj/local/armeabi/objs/ijkplayer/ff_cmdutils.o' failed
make: *** [/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-armv5/src/main/obj/local/armeabi/objs/ijkplayer/ff_cmdutils.o] Error 1
make: *** Waiting for unfinished jobs....
arm-linux-androideabi-gcc.exe: error: F:/cygwin/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c: No such file or directory
arm-linux-androideabi-gcc.exe: fatal error: no input files
compilation terminated.
/cygdrive/f/android-ndk-r10e/build/core/build-binary.mk:464: recipe for target '/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-armv5/src/main/obj/local/armeabi/objs/ijkplayer/ff_ffplay.o' failed
make: *** [/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-armv5/src/main/obj/local/armeabi/objs/ijkplayer/ff_ffplay.o] Error 1
[armeabi] Compile thumb  : ijkplayer <= ff_ffpipenode.c
arm-linux-androideabi-gcc.exe: error: F:/cygwin/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffpipeline.c: No such file or directory
arm-linux-androideabi-gcc.exe: fatal error: no input files
compilation terminated.
arm-linux-androideabi-gcc.exe: error: F:/cygwin/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffpipenode.c: No such file or directory
arm-linux-androideabi-gcc.exe: fatal error: no input files
compilation terminated.
/cygdrive/f/android-ndk-r10e/build/core/build-binary.mk:464: recipe for target '/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-armv5/src/main/obj/local/armeabi/objs/ijkplayer/ff_ffpipeline.o' failed
make: *** [/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-armv5/src/main/obj/local/armeabi/objs/ijkplayer/ff_ffpipeline.o] Error 1
/cygdrive/f/android-ndk-r10e/build/core/build-binary.mk:464: recipe for target '/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-armv5/src/main/obj/local/armeabi/objs/ijkplayer/ff_ffpipenode.o' failed
make: *** [/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-armv5/src/main/obj/local/armeabi/objs/ijkplayer/ff_ffpipenode.o] Error 1
/home/Administrator/ijkplayer-android/android
profiler build: NO
Android NDK: ERROR:/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file
Android NDK: Check that /home/Administrator/ijkplayer-android/android/contrib/build/ffmpeg-armv7a/output/libijkffmpeg.so exists  or that its path is correct
/cygdrive/f/android-ndk-r10e/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
/home/Administrator/ijkplayer-android/android
profiler build: NO
Android NDK: ERROR:/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-arm64/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file
Android NDK: Check that /libijkffmpeg.so exists  or that its path is correct
/cygdrive/f/android-ndk-r10e/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
/home/Administrator/ijkplayer-android/android
profiler build: NO
Android NDK: ERROR:/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-x86/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file
Android NDK: Check that /libijkffmpeg.so exists  or that its path is correct
/cygdrive/f/android-ndk-r10e/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
/home/Administrator/ijkplayer-android/android
profiler build: NO
Android NDK: ERROR:/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-x86_64/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file
Android NDK: Check that /libijkffmpeg.so exists  or that its path is correct
/cygdrive/f/android-ndk-r10e/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
/home/Administrator/ijkplayer-android/android

**Comment by tianxiao875** [comment]
I use the           Cymwin

**Comment by bbcallen** [comment]
Sorry, I don't maintain "cymwin".
And duplicated issue with #1126
