### ISSUE TITLE
ijkmedia/ijkplayer/ff_cmdut              ils.c: No such file or directory

### ISSUE THREAD

**Issue by tianxiao875** [Bilibili/ijkplayer#1129]
profiler build: NO
[armeabi-v7a] Compile thumb  : ijkplayer <= ff_cmdutils.c
[armeabi-v7a] Compile thumb  : ijkplayer <= ff_ffplay.c
[armeabi-v7a] Compile thumb  : ijkplayer <= ff_ffpipeline.c
arm-linux-androideabi-gcc.exe: error: F:/cygwin/home/Administrator/ijkplayer-and              roid/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ff_cmdut              ils.c: No such file or directory
arm-linux-androideabi-gcc.exe: fatal error: no input files
compilation terminated.
arm-linux-androideabi-gcc.exe: error: F:/cygwin/home/Administrator/ijkplayer-and              roid/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ff_ffpla              y.c: No such file or directory
arm-linux-androideabi-gcc.exe: fatal error: no input files
compilation terminated.
arm-linux-androideabi-gcc.exe: error: F:/cygwin/home/Administrator/ijkplayer-and              roid/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ff_ffpip              eline.c: No such file or directory
arm-linux-androideabi-gcc.exe: fatal error: no input files
compilation terminated.
/cygdrive/f/android-ndk-r10e/build/core/build-binary.mk:464: recipe for target '              /home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/mai              n/obj/local/armeabi-v7a/objs/ijkplayer/ff_cmdutils.o' failed
make: *** [/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-arm              v7a/src/main/obj/local/armeabi-v7a/objs/ijkplayer/ff_cmdutils.o] Error 1
make: *** Waiting for unfinished jobs....
[armeabi-v7a] Compile thumb  : ijkplayer <= ff_ffpipenode.c
/cygdrive/f/android-ndk-r10e/build/core/build-binary.mk:464: recipe for target '              /home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/mai              n/obj/local/armeabi-v7a/objs/ijkplayer/ff_ffplay.o' failed
make: *** [/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-arm              v7a/src/main/obj/local/armeabi-v7a/objs/ijkplayer/ff_ffplay.o] Error 1
/cygdrive/f/android-ndk-r10e/build/core/build-binary.mk:464: recipe for target '              /home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/mai              n/obj/local/armeabi-v7a/objs/ijkplayer/ff_ffpipeline.o' failed
make: *** [/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-arm              v7a/src/main/obj/local/armeabi-v7a/objs/ijkplayer/ff_ffpipeline.o] Error 1
arm-linux-androideabi-gcc.exe: error: F:/cygwin/home/Administrator/ijkplayer-and              roid/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ff_ffpip              enode.c: No such file or directory
arm-linux-androideabi-gcc.exe: fatal error: no input files
compilation terminated.
/cygdrive/f/android-ndk-r10e/build/core/build-binary.mk:464: recipe for target '              /home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/mai              n/obj/local/armeabi-v7a/objs/ijkplayer/ff_ffpipenode.o' failed
make: *** [/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-arm              v7a/src/main/obj/local/armeabi-v7a/objs/ijkplayer/ff_ffpipenode.o] Error 1
/home/Administrator/ijkplayer-android/android

**Comment by bbcallen** [comment]
Duplicated issue with #1126.
Please don't open multiple issues for same problem.

**Comment by tianxiao875** [comment]
okay。。 sorry

**Comment by spaul13** [comment]
@tianxiao875  and @bbcallen, I made some changes in ff_ffplay.c /ijkmedia/ijkplayer/ (want to see something more) but if I compile-ffmpeg.sh from /android/contrib, how can I see modified portion in the resulting .so files?

Can you please tell me whether I need to replace the modified ff_ffplay.c from the ijkmedia by the architecture specific ffplay.c in /android/contrib/ffmpeg-armv7a??

**Comment by spaul13** [comment]
@tianxiao875, can you tell me what compiling steps are u following?
