### ISSUE TITLE
怎么加avfilter

### ISSUE THREAD

**Issue by seu070507** [Bilibili/ijkplayer#1132]
@bbcallen 你好
我现在想试验一下，ijkplayer的setSpeed接口，但是需要ijk开启avfilter
我这边翻看了老得issue里面的一些做法，但还是不是完全搞明白。
1 我注意了module.sh 要开启avfilter 
  export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-avfilter"

2 不太明白如何设置ijkplayer下面 config.h里面的 CONFIG_AVFILTER，FFP_MERGE等宏定义?
  尝试直接修改里面的值，不起作用。
3. step 1，step 2 设置好了以后，如何用ijkplayer 加 filter呢？

占用你的时间，实在不好意思。

**Comment by bbcallen** [comment]
There are too many problems to use avfilter in ijkplayer.

But if you really need it, you can enable it by:
1. Modify config/module-lite.sh
```
- export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-filters"
+ export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-filters"
```

2. clean and rebuild FFmpeg

3. modify config.h
```
# remove this line, it should be defined in FFmpeg's config.h
- #define CONFIG_AVFILTER 0
```

4. Don't bother with CONFIG_AVFILTER and FFP_MERGE, if they don't broke compiling.

5. Modify compile errors if any exist.

6. After that, you should study ffmpeg/ffplay.c to learn how to configure avfilters with options.
There isn't any useful API in ijkplayer for avfilters.

**Comment by seu070507** [comment]
我主要是想利用setSpeed这个函数功能， 貌似需要开启avfilter的功能才能起作用，所以才费劲做avfilter 的设置

**Comment by seu070507** [comment]
按照你提示的步骤，貌似可以了
但是软解播放时候。在ff_ffplay.c configure_video_filters 函数中
INSERT_FILT("crop", "floor(in_w/2)*2:floor(in_h/2)*2"); 直接failed 掉了
把这句注释掉以后，视频播放没有声音。。

**Comment by bbcallen** [comment]
Did you "--enable-filters" (not filter)
Did you clean and rebuild ffmpeg?

**Comment by Android4MediaPlayer** [comment]
setSpeed？实现倍数播放吗？

**Comment by Android4MediaPlayer** [comment]
@bbcallen 6.0以下也可以倍数播放吗

**Comment by djh123** [comment]
@bbcallen hi 你好  
我按照你上面说的  修改了 编译脚本和 clean and rebuild FFmpeg 
然后 在ff_ffplay.c configure_video_filters()  中加入 过滤选项  如 
const char *filter_descr = "drawbox=x=100:y=100:w=100:h=100:color=pink@0.5";  
 if ((ret = configure_filtergraph(graph, filter_descr, filt_src, last_filter)) < 0)
        goto fail;

它是有效果的。现在问题是  我如何使用ijk的 接口 设置这些参数 ，还是说我需要自己拉接口。

**Comment by djh123** [comment]
还有就是 添加了  avfilter 后如何评估它的性能问题
