### ISSUE TITLE
请麻烦帮助下

### ISSUE THREAD

**Issue by tianxiao875** [Bilibili/ijkplayer#1133]
$ ./compile-ijk.sh armv7a
profiler build: NO
[armeabi-v7a] Compile thumb  : ijkplayer <= ff_cmdutils.c
[armeabi-v7a] Compile thumb  : ijkplayer <= ff_ffplay.c
[armeabi-v7a] Compile thumb  : ijkplayer <= ff_ffpipeline.c
arm-linux-androideabi-gcc.exe: error: F:/cygwin64/home/Administrator/ijkplayer-a                      ndroid/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ff_ffp                      lay.c: No such file or directory
arm-linux-androideabi-gcc.exe: fatal error: no input files
compilation terminated.
arm-linux-androideabi-gcc.exe: error: F:/cygwin64/home/Administrator/ijkplayer-a                      ndroid/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ff_cmd                      utils.c: No such file or directory
arm-linux-androideabi-gcc.exe: fatal error: no input files
compilation terminated.
/cygdrive/f/android-ndk-r10e/build/core/build-binary.mk:464: recipe for target '                      /home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/mai                      n/obj/local/armeabi-v7a/objs/ijkplayer/ff_cmdutils.o' failed
make: *** [/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-arm                      v7a/src/main/obj/local/armeabi-v7a/objs/ijkplayer/ff_cmdutils.o] Error 1
make: *** 正在等待未完成的任务....
arm-linux-androideabi-gcc.exe: error: F:/cygwin64/home/Administrator/ijkplayer-a                      ndroid/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ff_ffp                      ipeline.c: No such file or directory
arm-linux-androideabi-gcc.exe: fatal error: no input files
compilation terminated.
/cygdrive/f/android-ndk-r10e/build/core/build-binary.mk:464: recipe for target '                      /home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/mai                      n/obj/local/armeabi-v7a/objs/ijkplayer/ff_ffplay.o' failed
make: *** [/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-arm                      v7a/src/main/obj/local/armeabi-v7a/objs/ijkplayer/ff_ffplay.o] Error 1
/cygdrive/f/android-ndk-r10e/build/core/build-binary.mk:464: recipe for target '                      /home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/mai                      n/obj/local/armeabi-v7a/objs/ijkplayer/ff_ffpipeline.o' failed
make: *** [/home/Administrator/ijkplayer-android/android/ijkplayer/ijkplayer-arm                      v7a/src/main/obj/local/armeabi-v7a/objs/ijkplayer/ff_ffpipeline.o] Error 1
/home/Administrator/ijkplayer-android/android
关于这个问题。我搞了几天了。真的是没办法了。。。。请帮帮下我吧。git make yasm 我都安装了。。cygwin  麻烦了。。为了这个问题都快哭了，3天多了都没睡好过

**Comment by bbcallen** [comment]
Sorry, but I don't have a Windows PC.
