### ISSUE TITLE
Save Streamed Video

### ISSUE THREAD

**Issue by huggosan** [Bilibili/ijkplayer#1134]
I am streaming the video over the LAN and i am playing the video using ijkplayer. 

I would like to save the video locally in the phone using the app.

Is that possible?

**Comment by bbcallen** [comment]
You can implement IMediaDataSource, and do what ever you want to the binary stream.

**Comment by ananarola** [comment]
Hi.. i want to record live rtsp stream which play on player into local. can we achive recording feature in this player
?

**Comment by leon790** [comment]
i have the same issue, i need to record the rtsp stream, any idea how to do? @ananarola @bbcallen @huggosan

**Comment by ananarola** [comment]
Nope.. not getting anything related to this.

**Comment by bbcallen** [comment]
Check ffmpeg.c to see how to transcode/remux stream.
