### ISSUE TITLE
请教一个获取 iOS 平台上 CVPixelBufferRef 的问题

### ISSUE THREAD

**Issue by Rannie** [Bilibili/ijkplayer#1136]
现在打算获取播放器的 CVPixelBufferRef 自己在自定义的 GL View 上去渲染，看到 ijksdl_vout_overlay_videotoolbox.h 中有获取函数，如何实时的拿到 Vout ，width，height 去创建 VoutOverlay 呢？

**Comment by bbcallen** [comment]
What do you mean "实时的"?

**Comment by Rannie** [comment]
[_videoOutput copyPixelBufferForItemTime:[_playerItem currentTime] itemTimeForDisplay:nil];

现在使用 avplayer output 可以根据 item 当前时间获取 CVPixelBufferRef 
因为 avplayer 不支持 rtmp 所以想使用你们的播放器 刚才看了下 api 不太清楚如何拿到该对象回调

**Comment by bbcallen** [comment]
No such callback, but you can modify IJKSDLGLView.m to do whatever you want.

**Comment by Rannie** [comment]
`SDL_VoutOverlay *SDL_VoutVideoToolBox_CreateOverlay(int width, int height, SDL_Vout *vout);
CVPixelBufferRef SDL_VoutOverlayVideoToolBox_GetCVPixelBufferRef(SDL_VoutOverlay *overlay);`

那可不可以在播放中根据 FFPlayer 中的 vout 成员 用上面两个函数创建出 overlay 来获取当前时刻的 pixel buffer ref 呢

**Comment by bbcallen** [comment]
No,  SDL_VoutOverlay is only a container, it doesn't create any CVPixelBufferRef.

**Comment by Rannie** [comment]
非常感谢。

**Comment by szt243660543** [comment]
解决了吗？我也需要这样的需求。
