### ISSUE TITLE
ijkplayer android 怎么监测缓存进度？ 

### ISSUE THREAD

**Issue by XiaoXunLu** [Bilibili/ijkplayer#1137]
android   ijkplayer  是怎么监测缓存进度？

**Comment by XiaoXunLu** [comment]
就是加载缓存的时候，有没有方法 可以监测到缓存是否正在加载？ 我就是想判断是否已经停止了加载

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/d061590d4cd07d7598a907cd0777c9eb51bb124b/android/ijkplayer/ijkplayer-java/src/main/java/tv/danmaku/ijk/media/player/IMediaPlayer.java#L41

**Comment by XiaoXunLu** [comment]
if (what == IMediaPlayer.MEDIA_INFO_BUFFERING_START) {
}  就是在开始加载缓存的时候 我弹出了一个正在加载的进度，但有的时候会一直都停留正在加载中 我想找出问题的原因 是否是读取不了数据进缓存了

**Comment by bbcallen** [comment]
No such notification, for now.
Check the logical is the only thing you can do.
