### ISSUE TITLE
代码能否添加注释，添加播放一组视频URL方法，提供视频切换到下一个视频方法

### ISSUE THREAD

**Issue by Shannon-Yang** [Bilibili/ijkplayer#1139]
能否把代码添加上注释呢，有很多不怎么明白 

能否在IJKFFMoviePlayerController中提供一个类似于  - (id)initWithContentURL:(NSURL *)aUrl withURLs:(NSArray *)URLs withOptions:(IJKFFOptions *)options;这样的方法，可以传一组视频的URL进去播放，默认播放aUrl这个视频

能否在IJKFFMoviePlayerController或者IJKMediaPlayback中提供一个切换视频的方法，从一个视频切换到另一个视频，类似AVPlayer 的replaceCurrentItemWithPlayerItem方法  呵呵😄

**Comment by bbcallen** [comment]
1. https://developer.apple.com/library/ios/documentation/MediaPlayer/Reference/MPMoviePlayerController_Class/
2. You can create new IJKFFMoviePlayerController for new url.
