### ISSUE TITLE
Android 播放流能动态设置缓冲时间吗？

### ISSUE THREAD

**Issue by summeriver** [Bilibili/ijkplayer#1140]

**Comment by bbcallen** [comment]
Please define "缓冲时间"

**Comment by summeriver** [comment]
就是直播流的连接速度尽可能短，之后可以增加缓冲到内存的流，使在网络波动的情况下还能比较稳定

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/ff_ffplay_options.h#L110
You are on your own, If you want to modify them dynamic.
