### ISSUE TITLE
使用uri方式播放某些本地文件时，有的文件播放不了

### ISSUE THREAD

**Issue by wqmijkplayer** [Bilibili/ijkplayer#1141]
@bbcallen 播放某些本地文件时，提示partial file，这大概是什么原因？帮忙指教
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x559861e170] stream 0, offset 0x30, ret64=0xffffffffffffffda: partial file
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x559861e170] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 1280x720, 249 kb/s): unspecified pixel format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
pipe:34: could not find codec parameters

**Comment by bbcallen** [comment]
```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x559861e170] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 1280x720, 249 kb/s): unspecified pixel format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
```
