### ISSUE TITLE
[iOS]The sharecrop of EAGLContext object is not been set in class IJKSDLGLView 

### ISSUE THREAD

**Issue by troyzhao** [Bilibili/ijkplayer#1146]
If my iOS application has an EAGLContext object (cocos2dx game for example), and it has a sharegroup by default.
then the ijkplayer`s EAGLContext object is not set a sharegroup same with my app when initialized can produce a bug. the bug makes my app`s  render error.
#我英文不好，别打我#
我的cocos2dx游戏存在一个EAGLContext对象，如果在IJKSDLGLView中创建的EAGLContext，没有指定与游戏相同的sharegroup,则可能会产生问题，导致游戏纹理等绘制异常。

**Comment by troyzhao** [comment]
so,change this line makes it work well

EAGLSharegroup *sg = [[EAGLContext currentContext] sharegroup];/* use current sharegroup if exist */ _context = [[EAGLContext alloc] initWithAPI:kEAGLRenderingAPIOpenGLES2 sharegroup:sg];

**Comment by bbcallen** [comment]
Can you explain why EAGLSharegroup will fix the problem?

ijkplayer and cocos2dx should not affect each other, if they draw frames in their own CAEAGLLayer.

**Comment by troyzhao** [comment]
Apple`s Document has a describes about sharegroup.
https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/WorkingwithOpenGLESContexts/WorkingwithOpenGLESContexts.html
it say " the first context is initialized by calling initWithAPI:; a sharegroup is automatically created for the context. ".  so, if initialized the second context without the first context’s sharegroup, it creates a new one!
It is just my guess on the above, I'm not sure whether it really this case.

![eaglcontext_eaglesharegroup_2x](https://cloud.githubusercontent.com/assets/3151615/14418431/24032ec2-fff1-11e5-8e53-2326d9d6f08c.png)

**Comment by bbcallen** [comment]
https://github.com/cocos2d/cocos2d-x/blob/08383628ccbf87f49330bd22b7bf5620385047e4/cocos/platform/ios/CCES2Renderer-ios.m#L52

cocos2d-x doesn't create EAGLSharegroup by itself. I think it's exact what ijkplayer does.
I don't think ijkplayer should share the same group with cocos2d-x, if they don't share same view.

**Comment by linjiansheng** [comment]
@troyzhao @bbcallen 
纹理出问题是因为这个
https://github.com/Bilibili/ijkplayer/commit/089ef7215f778ce752c8478da047323442fda1ff

**Comment by troyzhao** [comment]
@linjiansheng  是的，可以了。问题解决，谢谢！
