### ISSUE TITLE
请问下如何设置cookie

### ISSUE THREAD

**Issue by Qrilee** [Bilibili/ijkplayer#1150]
以一部电影的磁力hash码示例，因为播放视频需要携带cookie，cookie为FTN5K=0694301b，播放链接为：
`http://sh.ctfs.ftn.qq.com/ftn_handler/a43f9b5fa52a921806fdd58d407fb0cb49770b12e79e8287852260efd8ed94929a890f3667ed97e4951f30d754c8da5d64c58a84eb63ca267863306475205ca8?compressed=0&dtype=1&fname=m.mkv`

代码如下：
` ijkMediaPlayer = new IjkMediaPlayer();

        HashMap<String, String> map = new HashMap<>();

        map.put("headers", "Cookie: FTN5K=0694301b\r\n");

        try {

            ijkMediaPlayer.setDataSource(this, Uri.parse("http://sh.ctfs.ftn.qq.com/ftn_handler/a43f9b5fa52a921806fdd58d407fb0cb49770b12e79e8287852260efd8ed94929a890f3667ed97e4951f30d754c8da5d64c58a84eb63ca267863306475205ca8?compressed=0&dtype=1&fname=m.mkv"), map);

        } catch (IOException e1) {

            e1.printStackTrace();

        }

        ijkMediaPlayer.prepareAsync();`

错误症状：无法播放视频
logcat下错误信息

`04-07 17:58:36.442 19655-19848/com.qtfreet.yunbo E/IJKMEDIA: http://sh.ctfs.ftn.qq.com/ftn_handler/a43f9b5fa52a921806fdd58d407fb0cb49770b12e79e8287852260efd8ed94929a890f3667ed97e4951f30d754c8da5d64c58a84eb63ca267863306475205ca8?compressed=0&dtype=1&fname=m.mkv: Server returned 4XX Client Error, but not one of 40{0,1,3,4}
04-07 17:58:36.460 19655-19655/com.qtfreet.yunbo E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)`

**Comment by bbcallen** [comment]
ijkMediaPlayer.setOption()

**Comment by Qrilee** [comment]
ok，谢谢解答

**Comment by lyzzbhoneyline** [comment]
@Qrilee does ijkMediaPlayer.setOption() work for you? pls share the way how to use this method, thx :D

**Comment by EvlinLee** [comment]
@bbcallen iOS的怎么设置呢？

**Comment by Qrilee** [comment]
@lyzzbhoneyline my way to set cookie

ijkMediaPlayer.setOption(IjkMediaPlayer.FFP_PROPV_DECODER_AVCODEC, "headers", "Cookie: FTN5K=" + cookie + ";\n");

I'm not sure it will work for u

**Comment by lyzzbhoneyline** [comment]
@Qrilee I'll try it, thks :)

**Comment by csvips** [comment]
@Qrilee 你好，我也是这样设置的，但是我的demo仍然无法播放qq旋风的视频。请问需要其他的设置吗？

**Comment by xinzhengzhang** [comment]
@lyzzbhoneyline #1581 
set headers to avformat not avcodec

**Comment by EmKs** [comment]
@Qrilee 你好，请问如何解决Server returned 4XX Client Error, but not one of 40{0,1,3,4}这个问题，我设置了 IjkMediaPlayer.setOption(IjkMediaPlayer.FFP_PROPV_DECODER_AVCODEC,"Cookie",cookie);后还是无法解决这个问题
具体代码如下：
String url = "http://xfcd.ctfs.ftn.qq.com/ftn_handler/c3f592e42361748b339ba8c00712d93fca2ce67c06d77c5dfeda69d49859c8cf276ee024cdfe9cef3c4a1b9afa6c02fb16eaf7651450022effb6cc1144a0709f/M.mkv";
        String cookie = "FTN5K=7d0aa1da";
        header.put("Cookie",cookie);

        IjkMediaPlayer = new IjkMediaPlayer();

        try {
            IjkMediaPlayer.setDataSource(this, Uri.parse(Path), header);
            IjkMediaPlayer.setOption(IjkMediaPlayer.FFP_PROPV_DECODER_AVCODEC,"Cookie",cookie);
            IjkMediaPlayer.prepareAsync();
        } catch (IOException e) {
            e.printStackTrace();
        }

        IjkMediaPlayer.setOnPreparedListener(new IMediaPlayer.OnPreparedListener() {
            @Override
            public void onPrepared(IMediaPlayer iMediaPlayer) {
                IjkMediaPlayer.start();
            }
        });
    }

**Comment by Qrilee** [comment]
@EmKs 你抓包看下头部信息就知道了，你试试header.put("Cookie", " " + cookie + ";\r\n");

**Comment by Qiaoidea** [comment]
如果这个header在Seek的时候需要动态变更调整的话，直接设置Option 怎么实时生效呢？ 还是不支持seek过程中调整header?
