### ISSUE TITLE
ios端 想要添加手势上下左右滑动调节音量等，应该添加在哪一个view?

### ISSUE THREAD

**Issue by DanielYQ** [Bilibili/ijkplayer#1151]
非常感谢！我给mediacontrol添加了pan手势，添加了touchesBegin,touchesMoved好像都不行，请问应该给哪一个view添加手势，是overlay吗？
已经试过很多种方法，都不成。希望得到指点，万分感谢！

**Comment by bbcallen** [comment]
Any view you want.
I don't think gesture has anything to do with player.
