### ISSUE TITLE
[Android] 测试ts直播流的时候，播着播着停掉(跟buffuer无关)

### ISSUE THREAD

**Issue by xuluming** [Bilibili/ijkplayer#1152]
android测试播ts直播流的时候,播着播着，大概几分钟后，画面停掉。这是捕获到的打印信息
![image](https://cloud.githubusercontent.com/assets/6344950/14373470/0513f1f2-fd7d-11e5-9a2d-017b20f9d1df.png)

每次的停止点都是在打印完这句话以后：E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
也就是对应的android中的这段处理错误的代码：
    private IMediaPlayer.OnErrorListener mErrorListener =
            new IMediaPlayer.OnErrorListener() {
                public boolean onError(IMediaPlayer mp, int framework_err, int impl_err) {
                    Logger.d(TAG, "Error: " + framework_err + "," + impl_err);
                    mCurrentState = STATE_ERROR;
                    mTargetState = STATE_ERROR;
                    return true;
                }
            };
framework_err=-10000      impl_err=0
希望能给与我一些帮助和解答，谢谢了！

**Comment by bbcallen** [comment]
AVERROR(ETIMEOUT)

**Comment by xuluming** [comment]
@bbcallen 这个错误代表什么意思呢，什么样的情况下会发生？

**Comment by bbcallen** [comment]
Mostly, it means I/O timed out.

**Comment by lijiankun24** [comment]
@bbcallen 有详细的错误码说明文档么
