### ISSUE TITLE
android rtmp + swfurl + token ?

### ISSUE THREAD

**Issue by diaconuliviu85** [Bilibili/ijkplayer#1155]
Hello
I met a problem that I did not understand the last two months. two months using this library in android.
Very good, but if RTMP, has more details, the player can not go.
if so RTMP: //live.xxxxxxxx.zzz 1935 / canale_live, works perfectly.
but if you have token or other information Snap: RTMP: //live.xxxxxxxx.zzz 1935 / canale_live playpath = canale swfUrl = http: //canale.xxxxxx.zzz/script/Flowplayer/flowplayer-3.2.16.swf live = 1 PAGEURL = http: //canale.xxxxx.zzz/player.aspx.

what can be done ? I saw players based on this library which can open such RTMP.
Thank you.

**Comment by bbcallen** [comment]
https://ffmpeg.org/ffmpeg-protocols.html#rtmp

**Comment by diaconuliviu85** [comment]
Thanks for the information, but the code for android where you have to change? if you could provide some additional information. Thank you

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/android/ijkplayer/ijkplayer-sample/src/main/java/tv/danmaku/ijk/media/sample/widget/media/IjkVideoView.java#L985
