### ISSUE TITLE
如何开启硬解

### ISSUE THREAD

**Issue by iosnower** [Bilibili/ijkplayer#1157]
请问如何设置，分别开启android和ios的，h264硬件解码？

**Comment by bbcallen** [comment]
See demo

**Comment by iosnower** [comment]
很抱歉，我没有在demo找到开启的代码，能给个demo代码中的位置吗

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/android/ijkplayer/ijkplayer-sample/src/main/java/tv/danmaku/ijk/media/sample/widget/media/IjkVideoView.java#L988

**Comment by SoXeon** [comment]
iOS如下： [options setPlayerOptionIntValue:1      forKey:@"videotoolbox"];

**Comment by iTony** [comment]
Android:    ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
