### ISSUE TITLE
hardware decoder crashed after selectTrack method

### ISSUE THREAD

**Issue by vahid64** [Bilibili/ijkplayer#1158]
Hello and thanks for your stable player,
hardware decoder works very well but is crashed when i use the "selectTrack" method (Just when I want switch to hd(1080) stream). 
And does not work until device reboot!

please help me

log:
1-02 04:19:35.700 9329-9329/tv.samim.iptv.android.hoteling V/AML_all_components: --------------------------------
                                                                                  author:aml.sh multi-media team
                                                                                  branch name:   
                                                                                  git version:    
                                                                                  last changed:  
                                                                                  build-time:     Wed Aug 13 20:07:59 CST 2014
                                                                                  build-name:     brian.zhu
                                                                                  uncommitted-file-num:0
                                                                                  cd /mnt/fileroot/brian.zhu/m8baby
                                                                                  hostname droid05
                                                                                  --------------------------------
01-02 04:19:35.700 9329-9329/tv.samim.iptv.android.hoteling V/OmxComponentManagerImpl: loadLibrary:225 Loading OMX library libOmxVideo.so.
01-02 04:19:35.700 9329-9329/tv.samim.iptv.android.hoteling I/omx_core: Core library has 20 components
01-02 04:19:35.700 9329-9329/tv.samim.iptv.android.hoteling E/OMXMaster: A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
01-02 04:19:35.700 9329-9329/tv.samim.iptv.android.hoteling W/ALooperRoster: ALooper::handler_id ALooperRoster::registerHandler 10
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling I/AmSoftDec: get mimetype : video/avc
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling I/AmFFmpegCodec: CreateCodec for codecMime : video/avc
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling E/OMXNodeInstance: OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling W/OMXNodeInstance: OMX_GetExtensionIndex OMX.google.android.index.prepareForAdaptivePlayback failed
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling I/ALooperRoster: ALooperRoster unregisterHandler handlerID=a
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling I/omx_core: OMX_Deinit 96 gInitCount=0
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling I/IjkMediaCodecInfo:  Baseline Profile Level 51 (1,32768)
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.vp8.decoder
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: video/x-vnd.on2.vp8
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.vp9.decoder
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: video/x-vnd.on2.vp9
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.rm.decoder
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: video/rm
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.wmv2.decoder
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: video/wmv2
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: AML.google.ac3.decoder
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: audio/ac3
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: AML.google.ec3.decoder
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: audio/eac3
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.mp2.decoder
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: audio/mpeg-L2
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.mp3.decoder
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: audio/mpeg
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: AML.google.dtshd.decoder
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: audio/dtshd
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.amrnb.encoder
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.amrwb.encoder
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.aac.encoder
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.flac.encoder
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.mpeg4.encoder
01-02 04:19:35.710 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.h263.encoder
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.amlogic.video.encoder.avc
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.h264.encoder
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.vp8.encoder
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: AACEncoder
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.raw.decoder
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: audio/raw
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.vp6.decoder
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: video/x-vnd.on2.vp6
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.vp6a.decoder
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: video/x-vnd.on2.vp6a
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.vp6f.decoder
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: video/x-vnd.on2.vp6f
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.h265.decoder
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: video/hevc
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.wmv2.decoder
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: video/wmv2
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling I/tv.danmaku.ijk.media.player.IjkMediaPlayer: selected codec: OMX.amlogic.avc.decoder.awesome rank=800
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/IJKMEDIA: SDL_AMediaCodecJava_createByCodecName
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling W/ALooperRoster: ALooper::handler_id ALooperRoster::registerHandler 11
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling W/ALooperRoster: ALooper::handler_id ALooperRoster::registerHandler 12
01-02 04:19:35.720 9329-9640/tv.samim.iptv.android.hoteling I/OMXClient: Using client-side OMX mux.
01-02 04:19:35.720 132-577/? D/OmxComponentManagerImpl: getEntryByName_2_num=1, componentName:OMX.amlogic.avc.decoder.awesome
01-02 04:19:35.720 132-577/? D/OmxComponentManagerImpl: amstream_vbuf is free
01-02 04:19:35.720 132-577/? D/OmxComponentManagerImpl: ret =0,*pEntry->mRoleNames=video_decoder.avc.awesome
01-02 04:19:35.720 132-577/? D/OmxComponentManagerImpl: ionvide is free
01-02 04:19:35.720 132-577/? D/OmxComponentManagerImpl: ready for creat omx decoder component
01-02 04:19:35.720 132-577/? V/AmlogicVideoDecoder: media.omx.latency is not set used def=0.600000
01-02 04:19:35.720 132-577/? E/OmxLogConf: Can not read property media.omx.log_levels, using 255
01-02 04:19:35.720 132-577/? D/OmxComponentManagerImpl: IncreaseEntryNumByName pEntry->mNum=1, pEntry->mMaxNum:4,componentName:OMX.amlogic.avc.decoder.awesome
01-02 04:19:35.720 132-577/? I/omx_core: OMX_getHandle_num=2
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/IJKMEDIA: SDL_AMediaCodecJava_init
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/IJKMEDIA: SDL_AMediaCodec_increaseReference(): ref=1
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/IJKMEDIA: SDL_AMediaCodecJava_configure_surface
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling E/IJKMEDIA: configure acodec:0x1d300292 format:0x1d7002ba: surface:0x1d5002a6
01-02 04:19:35.720 132-132/? D/OmxComponent: getExtensionIndex 1020 name="OMX.google.android.index.storeMetaDataInBuffers"
01-02 04:19:35.720 132-132/? D/OmxVideoDecoder: setParameter 457 OMX_IndexAndroidStoreMetadataInBuffers
01-02 04:19:35.720 132-132/? E/OMXNodeInstance: OMX_SetParameter() failed for StoreMetaDataInBuffers: 0x80001001
01-02 04:19:35.720 9329-9640/tv.samim.iptv.android.hoteling E/ACodec: [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
01-02 04:19:35.720 132-9563/? V/OmxVideoDecoder: getParameter 257 nParamIndex=0x6000001
01-02 04:19:35.720 132-813/? D/OmxVideoDecoder: setParameter nPortIndex 0 CompFmt 0x7 ColorFmt 0
01-02 04:19:35.720 132-577/? V/OmxVideoDecoder: getParameter 257 nParamIndex=0x6000001
01-02 04:19:35.720 132-1976/? D/OmxVideoDecoder: setParameter nPortIndex 1 CompFmt 0 ColorFmt 0x15
01-02 04:19:35.720 132-132/? V/OmxVideoDecoder: getParameter 257 nParamIndex=0x2000001
01-02 04:19:35.720 132-9563/? D/OmxVideoDecoder: setParameter nPortIndex 0 nFrameWidth 1920 nFrameHeight 1080 nSliceHeight 16
01-02 04:19:35.720 132-9563/? E/OmxVideoDecoder:  reset input buffer:1036800
01-02 04:19:35.720 132-813/? V/OmxVideoDecoder: getParameter 257 nParamIndex=0x2000001
01-02 04:19:35.720 132-813/? V/OmxVideoDecoder: mUseNativeBuffers 0
01-02 04:19:35.720 132-813/? V/OmxVideoDecoder: port.mDef.nBufferSize 0
01-02 04:19:35.720 132-577/? D/OmxVideoDecoder: setParameter nPortIndex 1 nFrameWidth 1920 nFrameHeight 1080 nSliceHeight 16
01-02 04:19:35.720 132-577/? V/OmxVideoDecoder: mUseNativeBuffers 0
01-02 04:19:35.720 132-577/? V/OmxVideoDecoder: port.mDef.nBufferSize 3110400
01-02 04:19:35.720 132-1976/? V/OmxVideoDecoder: getParameter 257 nParamIndex=0x2000001
01-02 04:19:35.720 9329-9640/tv.samim.iptv.android.hoteling I/ACodec: onConfigureComponent native-window finished OMX.amlogic.avc.decoder.awesome 
01-02 04:19:35.720 132-132/? D/OmxComponent: getExtensionIndex 1020 name="OMX.google.android.index.enableAndroidNativeBuffers"
01-02 04:19:35.720 132-132/? V/OmxVideoDecoder: setParameter 451 EnableNativeBuffers 1
01-02 04:19:35.720 132-132/? V/OmxVideoDecoder: mUseNativeBuffers 1
01-02 04:19:35.720 132-132/? D/AmlogicVideoDecoderAwesome: get native buffer info NV:w:1920,h:1080..
01-02 04:19:35.720 132-132/? V/OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=1920,portDef.format.video.nFrameHeight=1080
01-02 04:19:35.720 132-132/? V/OmxVideoDecoder: port.mDef.nBufferSize 3110400
01-02 04:19:35.720 9329-9329/tv.samim.iptv.android.hoteling D/IJKMEDIA: SDL_AMediaCodecJava_start
01-02 04:19:35.720 132-813/? V/OmxVideoDecoder: getParameter 257 nParamIndex=0x2000001
01-02 04:19:35.720 132-9563/? V/OmxVideoDecoder: getParameter 257 nParamIndex=0x2000001
01-02 04:19:35.720 132-9563/? V/OmxVideoDecoder: mUseNativeBuffers 1
01-02 04:19:35.720 132-9563/? D/AmlogicVideoDecoderAwesome: get native buffer info NV:w:1920,h:1080..
01-02 04:19:35.720 132-9563/? V/OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=1920,portDef.format.video.nFrameHeight=1080
01-02 04:19:35.720 132-9563/? V/OmxVideoDecoder: port.mDef.nBufferSize 3110400
01-02 04:19:35.720 132-813/? D/OmxComponent: getExtensionIndex 1020 name="OMX.google.android.index.getAndroidNativeBufferUsage"
01-02 04:19:35.720 132-813/? V/OmxVideoDecoder: getParameter 257 nParamIndex=0x7f000001
01-02 04:19:35.720 132-577/? D/OmxVideoDecoder: setParameter nPortIndex 1 nFrameWidth 1920 nFrameHeight 1080 nSliceHeight 16
01-02 04:19:35.720 132-577/? V/OmxVideoDecoder: mUseNativeBuffers 1
01-02 04:19:35.720 132-577/? D/AmlogicVideoDecoderAwesome: get native buffer info NV:w:1920,h:1080..
01-02 04:19:35.720 132-577/? V/OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=1920,portDef.format.video.nFrameHeight=1080
01-02 04:19:35.720 132-577/? V/OmxVideoDecoder: port.mDef.nBufferSize 3110400
01-02 04:19:35.720 132-1976/? D/OmxComponent: getExtensionIndex 1020 name="OMX.google.android.index.useAndroidNativeBuffer2"
01-02 04:19:35.720 132-1976/? D/OmxComponent: getExtensionIndex 1020 name="OMX.google.android.index.useAndroidNativeBuffer"
01-02 04:19:35.730 132-132/? D/OmxComponent: getExtensionIndex 1020 name="OMX.google.android.index.useAndroidNativeBuffer2"
01-02 04:19:35.730 132-132/? D/OmxComponent: getExtensionIndex 1020 name="OMX.google.android.index.useAndroidNativeBuffer"
01-02 04:19:35.730 132-9563/? D/OmxComponent: getExtensionIndex 1020 name="OMX.google.android.index.useAndroidNativeBuffer2"
01-02 04:19:35.730 132-9563/? D/OmxComponent: getExtensionIndex 1020 name="OMX.google.android.index.useAndroidNativeBuffer"
01-02 04:19:35.730 132-813/? D/OmxComponent: getExtensionIndex 1020 name="OMX.google.android.index.useAndroidNativeBuffer2"
01-02 04:19:35.730 132-813/? D/OmxComponent: getExtensionIndex 1020 name="OMX.google.android.index.useAndroidNativeBuffer"
01-02 04:19:35.730 129-233/? E/ion: ioctl c0144900 failed with code -1: Out of memory
01-02 04:19:35.730 129-233/? E/[Gralloc-ERROR]: int gralloc_alloc_buffer(alloc_device_t*, size_t, int, const native_handle_t**):115 Failed to ion_alloc from ion_client:20
01-02 04:19:35.730 129-233/? W/GraphicBufferAllocator: alloc(1920, 1080, 17, 20002900, ...) failed -1 (Operation not permitted)
                                                       
                                                       [ 01-02 04:19:35.730   129:  233 E/         ]
                                                       GraphicBufferAlloc::createGraphicBuffer(w=1920, h=1080) failed (Operation not permitted), handle=0x0
01-02 04:19:35.730 129-233/? E/BufferQueue: [SurfaceView] dequeueBuffer: SurfaceComposer::createGraphicBuffer failed
01-02 04:19:35.730 9329-9640/tv.samim.iptv.android.hoteling E/ACodec: dequeueBuffer failed: Operation not permitted (1)
01-02 04:19:35.750 9329-9640/tv.samim.iptv.android.hoteling E/ACodec: Failed to allocate buffers after transitioning to IDLE state (error 0xffffffff)
01-02 04:19:35.750 9329-9639/tv.samim.iptv.android.hoteling E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -1)
01-02 04:19:35.750 9329-9329/tv.samim.iptv.android.hoteling W/System.err: java.lang.IllegalStateException: start failed
01-02 04:19:35.760 9329-9329/tv.samim.iptv.android.hoteling W/System.err:     at android.media.MediaCodec.start(Native Method)
01-02 04:19:35.760 9329-9329/tv.samim.iptv.android.hoteling W/System.err:     at tv.danmaku.ijk.media.player.IjkMediaPlayer._setStreamSelected(Native Method)
01-02 04:19:35.760 9329-9329/tv.samim.iptv.android.hoteling W/System.err:     at tv.danmaku.ijk.media.player.IjkMediaPlayer.selectTrack(IjkMediaPlayer.java:589)

**Comment by bbcallen** [comment]
selectTrack is an experimental feature. It doesn't work well, for now.
