### ISSUE TITLE
Android - MediaPlayer.getDuration(); returning zero

### ISSUE THREAD

**Issue by kirvis250** [Bilibili/ijkplayer#116]
while on LogCat video decoding message says :

11-19 17:23:14.575: I/IJKMEDIA(19727): max_frame_duration: 10.000
11-19 17:23:14.575: I/IJKMEDIA(19727): Input #0, hls,applehttp, from 'https://??.??.??.?/lnk/index-1416391800-8400.m3u8
11-19 17:23:14.575: I/IJKMEDIA(19727):   Duration: 
11-19 17:23:14.575: I/IJKMEDIA(19727): 02:20:03.32
11-19 17:23:14.575: I/IJKMEDIA(19727): , start: 
11-19 17:23:14.575: I/IJKMEDIA(19727): 34514.422189
11-19 17:23:14.575: I/IJKMEDIA(19727): , bitrate: 
11-19 17:23:14.575: I/IJKMEDIA(19727): N/A
11-19 17:23:14.575: I/IJKMEDIA(19727):   Program 0 
11-19 17:23:14.575: I/IJKMEDIA(19727):     Metadata:
11-19 17:23:14.575: I/IJKMEDIA(19727):       variant_bitrate : 
11-19 17:23:14.575: I/IJKMEDIA(19727): 1596000
11-19 17:23:14.575: I/IJKMEDIA(19727):     Stream #0:1
11-19 17:23:14.575: I/IJKMEDIA(19727): (lit)
11-19 17:23:14.575: I/IJKMEDIA(19727): : Audio: aac ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 142 kb/s
11-19 17:23:14.575: I/IJKMEDIA(19727):  (default)
11-19 17:23:14.575: I/IJKMEDIA(19727):     Metadata:
11-19 17:23:14.575: I/IJKMEDIA(19727):       comment         : 
11-19 17:23:14.575: I/IJKMEDIA(19727): lit 1
11-19 17:23:14.575: I/IJKMEDIA(19727):       variant_bitrate : 
11-19 17:23:14.575: I/IJKMEDIA(19727): 1596000
11-19 17:23:14.575: I/IJKMEDIA(19727):     Stream #0:2
11-19 17:23:14.575: I/IJKMEDIA(19727): : Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 720x576
11-19 17:23:14.575: I/IJKMEDIA(19727): , 50 fps
11-19 17:23:14.575: I/IJKMEDIA(19727): , 50 tbr
11-19 17:23:14.575: I/IJKMEDIA(19727): , 90k tbn
11-19 17:23:14.575: I/IJKMEDIA(19727): , 100 tbc
11-19 17:23:14.575: I/IJKMEDIA(19727):     Metadata:
11-19 17:23:14.575: I/IJKMEDIA(19727):       variant_bitrate : 
11-19 17:23:14.575: I/IJKMEDIA(19727): 1596000
11-19 17:23:14.575: I/IJKMEDIA(19727):     Stream #0:0
11-19 17:23:14.575: I/IJKMEDIA(19727): (???)
11-19 17:23:14.575: I/IJKMEDIA(19727): : Audio: aac ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 135 kb/s
11-19 17:23:14.575: I/IJKMEDIA(19727):     Metadata:
11-19 17:23:14.575: I/IJKMEDIA(19727):       comment         : 
11-19 17:23:14.575: I/IJKMEDIA(19727): ??? 2
11-19 17:23:14.575: I/IJKMEDIA(19727):       variant_bitrate : 
11-19 17:23:14.575: I/IJKMEDIA(19727): 1596000
11-19 17:23:14.585: I/IJKMEDIA(19727): SDL_AndroidAudioTrack: CHANNEL_OUT_STEREO
11-19 17:23:14.585: I/IJKMEDIA(19727): SDL_AndroidAudioTrack: ENCODING_PCM_16BIT
11-19 17:23:14.615: I/IJKMEDIA(19727): sdl_audiotrack_new: init volume as 1.000000/(0.000000,1.000000)
11-19 17:23:14.615: I/IJKMEDIA(19727): SDL_RunThread: [20913] ff_audio_dec

 while getDuration() always returns zero.
Using default Android player, getDuration() works normally. 

HLS stream file looks like this.

#EXTM3U
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="lit 1",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="lit"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="??? 2",DEFAULT=NO,AUTOSELECT=YES,LANGUAGE="???",URI="tracks-2/index-1416389700-2100.m3u8"
#EXT-X-STREAM-INF:AUDIO="aac",RESOLUTION=720x576,BANDWIDTH=3526000
tracks-3,1/index-1416389700-2100.m3u8

I don't know actually if i'm doing something wrong or m3u8 file is not good or this is library bug?

**Comment by 9kay** [comment]
The same issue i meet too，do somebody know how to fix it?
