### ISSUE TITLE
执行 ./compile-ffmpeg.sh all 报错

### ISSUE THREAD

**Issue by someonesyn** [Bilibili/ijkplayer#1160]
编译执行./compile-ffmpeg.sh all的时候，都会报下面这个错
xcrun -sdk iphoneos clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.

跪求，怎么解决

**Comment by LeesimLoveXz** [comment]
i have the  same question ,somebody can help?

**Comment by Feng-xp** [comment]
同遇到这个问题，求解决办法

**Comment by Feng-xp** [comment]
我的问题解决了，报错的原因是找不到iphoneos sdk，原因是因为我之前装了2个版本的xcode，7.2和7.3的，7.3的被命名成了xcode2，然后7.2被我删掉了，所以找不到SDK了，路径变了。
只要把xcode2重命名成xcode就可以编译了。

**Comment by one-tea** [comment]
sudo /usr/bin/xcode-select -switch /Applications/Xcode.app/Contents/Developer
我的问题解决了~ 的确是xcode路径问题
