### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: couldn't find "libijkffmpeg.so"

### ISSUE THREAD

**Issue by fuyifang** [Bilibili/ijkplayer#1163]
when i import ijkplayer sample to my android studio(2.0) and use it to play mp4 crashed and report this error how to solve it ? this is my build.gradle:
`dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.android.support:preference-v7:23.0.1'
    compile 'com.android.support:support-annotations:23.0.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-java:0.4.4'
    compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.4.4'
    compile 'tv.danmaku.ijk.media:ijkplayer-armv5:0.4.5.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.4.5.1'

    compile 'com.squareup:otto:1.3.8'

    compile project(':ijkplayer-java')
    compile project(':ijkplayer-exo')

    all32Compile project(':ijkplayer-armv5')
    all32Compile project(':ijkplayer-armv7a')
    all32Compile project(':ijkplayer-x86')

    all64Compile project(':ijkplayer-armv5')
    all64Compile project(':ijkplayer-armv7a')
    all64Compile project(':ijkplayer-arm64')
    all64Compile project(':ijkplayer-x86')
    all64Compile project(':ijkplayer-x86_64')

    // armv5Compile project(':player-armv5')
    // armv7aCompile project(':player-armv7a')
    // arm64Compile project(':player-arm64')
    // x86Compile project(':player-x86')
    // x86_64Compile project(':player-x86_64')
}
`

`

**Comment by bbcallen** [comment]
Did you build FFmpeg successfully?

**Comment by fuyifang** [comment]
how to bulid FFmpeg ?

**Comment by bbcallen** [comment]
See README

**Comment by chenwulue** [comment]
是不是在windows系统无法使用的
