### ISSUE TITLE
export: (64-bit): bad variable name

### ISSUE THREAD

**Issue by lyqaiym** [Bilibili/ijkplayer#1165]
./init-android.sh
cd android/contrib
在tools/do-detect-env.sh里
加了
ANDROID_SDK=~/android/android-sdk-linux
ANDROID_NDK=~/android/android-ndk-r10e
./compile-ffmpeg.sh armv7a
报错
tools/do-compile-ffmpeg.sh: 48: export: (64-bit): bad variable name

**Comment by bbcallen** [comment]
Don't use '~', use absolute path.

**Comment by lyqaiym** [comment]
太奇葩了，我在tools/do-detect-env.sh里把export IJK_NDK_REL分成两部分写，就可以了，然后再该回去就没事了，和ANDROID_SDK=没关系啊

**Comment by lyqaiym** [comment]
刚才说错了。是我把ANDROID_NDK/RELEASE.TXT的r10e-rc4 (64-bit)的(64-bit)去掉才不错的

**Comment by yihongyuelan** [comment]
@lyqaiym 
Thanks. As you mentioned, need to remove "64-bit" and rebuild again. :)

**Comment by isuker** [comment]
export IJK_NDK_REL=$(grep -o '^r[0-9]*.*' $ANDROID_NDK/RELEASE.TXT 2>/dev/null|cut -b 2-8)

**Comment by isuker** [comment]
android/contrib/tool/do-detect-env.sh
modify to:
export IJK_NDK_REL=$(grep -o '^r[0-9]*.*' $ANDROID_NDK/RELEASE.TXT 2>/dev/null|cut -b 2-8)

**Comment by andyiac** [comment]
@lyqaiym 
it works for me ,thx
