### ISSUE TITLE
怎样边播放边录制直播视频呢？

### ISSUE THREAD

**Issue by cjztool** [Bilibili/ijkplayer#1166]
想到的方案有：

一.(基于m3u8的经验是)下载直播流，再在本地拼接成视频文件
担心占用正在播放时的带宽导致播放器播放卡顿,本地拼接开销也是问题.

二.截屏录制
基本不行,已实验过替换surfaceviw为自定义的AndroidTextureView,开启线程调用TextureView那个方法 getBitmap(bmp), 传入bmp宽高和屏幕(N6差不多2413x1357)一样的话需要耗时900+ms的时间截一次屏,而且播放画面卡顿一下.即便快到如 #301 dan-huang说的20ms,那截出来的怕也只能做成gif图了..

三.从ijkplayer缓存里直接拷贝到一个本地文件
参考 jgfntu@b1efc14 的 ffp_get_current_frame_l 函数, 里面的vp->bmp->pitches[0]始终都是0,不知啥原因就搜资料,13年的资料说是结构体SDL_Overlay已弃用,不知道是不是代码太新,,所以就改成
AVFrame* fmp=vp->frame;拿到 AVFrame,可是现在拿到了不知道该怎么弄了, 或是说整个ijkplayer视频解码完成之后哪个代码是控制缓存的呢   

求 @bbcallen 赐教

**Comment by tanhx2008** [comment]
直接从网络流读到的数据，送播放的同时，送一份本地保存，比如存成mp4文件

**Comment by cjztool** [comment]
@tanhx2008 是说重写ijkplayer的 ijkmp_set_data_source_l 吗?

**Comment by tanhx2008** [comment]
不是，视频源是网络流吧，从读数据那里（read_thread）得到的压缩数据，单独起一个任务和队列，本地保存数据

**Comment by cjztool** [comment]
@tanhx2008 你说的是改进一下我那个第一个方案不重新下载,从现在ijkplayer的下载里分一份出来是么? 大神求赐教哇.

**Comment by bbcallen** [comment]
For single file stream, you can implement IMediaDataSource.
For m3u8, it's somehow more complicate. You can implement a local http server to proxy all http request.

**Comment by cjztool** [comment]
昨天看到你回复另一issue的时候有提到这个,当时搜了下demo里没发现IMediaDataSource怎么用,然后上网搜了下,有个例子讲的是读取android_raw里的视频,以为和我现在的情况没关系.
grep了下发现有好多,是tv.danmaku.ijk.media.player.misc 的IMediaDataSource.java么? 还是jni/ijkmedia/ijkj4a/j4a/class/tv/danmaku/ijk/media/player/misc/IMediaDataSource.c呢?

**Comment by bbcallen** [comment]
Similar to http://developer.android.com/intl/zh-cn/reference/android/media/MediaDataSource.html

**Comment by cjztool** [comment]
多谢,实现这个之后如何截取视频的某一段视频呢?本想是截取正在直播的视频的某一段.

**Comment by bbcallen** [comment]
No. That's a totally different feature.

**Comment by cjztool** [comment]
OMG....那我大概该怎样改装ijkplayer呢?求指点个思路, 比如第3个方案怎么完善呢?

**Comment by bbcallen** [comment]
I don't understand your 3rd way.

**Comment by cjztool** [comment]
第3个方案是想从之前提交的截屏代码里改造成 用户按下的时候获取AVFrame然后存成视频 用户手松开就停下.
或者您有没有其他方案呢? 跪求指点啊,被产品折腾死了.没搞过这么底层的专业的视频开发..

**Comment by bbcallen** [comment]
AVFrame is decoded frame, it could be very slow to encode it back into stream.

**Comment by cjztool** [comment]
谢谢指教, 如果实现那个需求的话,我该从哪入手分出视频流到某个文件里呢?

**Comment by bbcallen** [comment]
http://git.videolan.org/?p=ffmpeg.git;a=blob;f=ffmpeg.c;h=adc3ff78006fcf87a59a084705fc84bce68632eb;hb=HEAD

**Comment by cjztool** [comment]
@bbcallen  先谢谢, 有问题再请教

**Comment by cjztool** [comment]
@bbcallen 看到ffmpeg.c的代码里有 do_streamcopy 这个函数,第一感觉是要在这里面分流写到某个文件, 一个想法是在这里暴露接口给ijkplayer, ijkplayer再暴露接口给java层供用户视频录制操作.

可是这里又有个问题是, 如果有缓存的逻辑的话,怎么确保在调用接口的时候do_streamcopy里的流和屏幕上正在播放的视频流的时间是同步的呢? 

有个check_recording_time函数不知是什么作用? 
如果时间是不同步的话,那又该去哪加这样的接口呢?

**Comment by bbcallen** [comment]
Sorry, not familiar with transcoding, you are on your own from this point.

**Comment by tanhx2008** [comment]
av_read_frame(ic, pkt)，把这里的pkt拷贝一份，av_copy_packet(pkt_mp4, pkt);
然后把pkt_mp4送本地保存任务（可以单独起一个任务和队列）存盘，应该是这样用一个基本思路

**Comment by tanhx2008** [comment]
av_interleaved_write_frame(ffp->ofmt_ctx, pkt)
这个是ffmpeg提供的写盘函数

**Comment by cjztool** [comment]
@tanhx2008 非常感谢！

**Comment by cjztool** [comment]
@tanhx2008 @tanhx2008 录屏只有图像 没有声音,日志报错:

 `E/IJKMEDIA: Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)`

录屏前加入
`acbsfc =  av_bitstream_filter_init("aac_adtstoasc");`
录屏时判断音频
`    if (!is_video)
        av_bitstream_filter_filter(aacbsfc, out_stream->codec, NULL, &pkt_i.data, &pkt_i.size, pkt_i.data, pkt_i.size, 0);`
录屏之后
`av_bitstream_filter_close(aacbsfc);`
仍然报相同的错.我该怎样加入aac_adtstoasc的音频解码呢?

**Comment by bbcallen** [comment]
run ./configure --help in ffmpeg's directory

**Comment by RDFS** [comment]
我想问一下，你的时间同步问题如何解决的呢，如何保证录制视频是当前显示的视频。

**Comment by cjztool** [comment]
@RDFS 
for循环里就是在解包渲染当前播放的视频画面  猜想是这样 按照猜想去实现,能录当前视频, 原理不清楚, 

我这出了个问题,画面音频不同步不知咋搞了..

**Comment by Yacong** [comment]
@cjztool 兄弟，请问下你实现了边播边下载到本地的功能了吗？

**Comment by fire3** [comment]
@cjztool 同问，有没有实现好呢？最终采用的是利用ffmpeg如av_interleaved_write_frame 的方式保存文件？

**Comment by shishuo365** [comment]
如果想要在Java层拿到每一帧视频数据，可以这样操作：

**Comment by FatPaper** [comment]
@cjztool 能否指导一下该功能的实现？

**Comment by lanyan520** [comment]
@FatPaper  你目前实现录制视频了么

**Comment by cjztool** [comment]
思路请参考 http://cjz010.iteye.com/blog/2399573

**Comment by chengzong** [comment]
录制mp4出现错误，请问怎么解决？Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)

**Comment by chengzong** [comment]
参照雷神的代码就好了
/**
* 最简单的基于FFmpeg的视音频复用器
* Simplest FFmpeg Muxer
*
* 雷霄骅 Lei Xiaohua
* leixiaohua1020@126.com
* 中国传媒大学/数字电视技术
* Communication University of China / Digital TV Technology
* http://blog.csdn.net/leixiaohua1020
*
* 本程序可以将视频码流和音频码流打包到一种封装格式中。
* 程序中将AAC编码的音频码流和H.264编码的视频码流打包成
* MPEG2TS封装格式的文件。
* 需要注意的是本程序并不改变视音频的编码格式。
*
* This software mux a video bitstream and a audio bitstream
* together into a file.
* In this example, it mux a H.264 bitstream (in MPEG2TS) and
* a AAC bitstream file together into MP4 format file.
*
*/

#include <stdio.h>

//extern "C"
//{
#include "libavformat/avformat.h"
//};
/*
FIX: H.264 in some container format (FLV, MP4, MKV etc.) need
"h264_mp4toannexb" bitstream filter (BSF)
*Add SPS,PPS in front of IDR frame
*Add start code ("0,0,0,1") in front of NALU
H.264 in some container (MPEG2TS) don't need this BSF.
*/
//'1': Use H.264 Bitstream Filter 
#define USE_H264BSF 0

/*
FIX:AAC in some container format (FLV, MP4, MKV etc.) need
"aac_adtstoasc" bitstream filter (BSF)
*/
//'1': Use AAC Bitstream Filter 
#define USE_AACBSF 1



int main(int argc, char* argv[])
{
	AVOutputFormat *ofmt = NULL;
	//输入对应一个AVFormatContext，输出对应一个AVFormatContext
	//（Input AVFormatContext and Output AVFormatContext）
	AVFormatContext *ifmt_ctx = NULL, *ofmt_ctx = NULL;
	AVPacket pkt;
	int ret, i;

	//char *in_filename_v = "cuc_ieschool.ts";//输入文件名（Input file URL）
	char *in_filename = "rtsp://192.168.0.123:5540/realplay?devid=008555555&channelno=0&streamtype=1&debug=1";
	//char *in_filename_v = "cuc_ieschool.h264";
	//char *in_filename_a = "cuc_ieschool.mp3";
	//char *in_filename_a = "gowest.m4a";
	//char *in_filename_a = "gowest.aac";
	//char *in_filename_a = "huoyuanjia.mp3";

	char *out_filename = "output.mp4";//输出文件名（Output file URL）
	av_register_all();
	avformat_network_init();
	//输入（Input）
	if ((ret = avformat_open_input(&ifmt_ctx, in_filename, 0, 0)) < 0) {
		printf("Could not open input file.");
		goto end;
	}
	if ((ret = avformat_find_stream_info(ifmt_ctx, 0)) < 0) {
		printf("Failed to retrieve input stream information");
		goto end;
	}

	/*if ((ret = avformat_open_input(&ifmt_ctx_a, in_filename_a, 0, 0)) < 0) {
	printf( "Could not open input file.");
	goto end;
	}
	if ((ret = avformat_find_stream_info(ifmt_ctx_a, 0)) < 0) {
	printf( "Failed to retrieve input stream information");
	goto end;
	}*/
	printf("Input Information=====================\n");
	av_dump_format(ifmt_ctx, 0, in_filename, 0);
	/*av_dump_format(ifmt_ctx_a, 0, in_filename_a, 0);*/
	printf("======================================\n");
	//输出（Output）
	avformat_alloc_output_context2(&ofmt_ctx, NULL, NULL, out_filename);
	if (!ofmt_ctx) {
		printf("Could not create output context\n");
		ret = AVERROR_UNKNOWN;
		goto end;
	}
	ofmt = ofmt_ctx->oformat;
	int videoindex_v = -1, videoindex_out = -1;
	int audioindex_a = -1, audioindex_out = -1;
	for (i = 0; i < ifmt_ctx->nb_streams; i++) {
		//根据输入流创建输出流（Create output AVStream according to input AVStream）
		if (ifmt_ctx->streams[i]->codec->codec_type == AVMEDIA_TYPE_VIDEO) {
			videoindex_v = i;
			AVStream *in_stream = ifmt_ctx->streams[i];
			AVStream *out_stream = avformat_new_stream(ofmt_ctx, in_stream->codec->codec);
			if (!out_stream) {
				printf("Failed allocating output stream\n");
				ret = AVERROR_UNKNOWN;
				goto end;
			}
			videoindex_out = out_stream->index;
			//复制AVCodecContext的设置（Copy the settings of AVCodecContext）
			if (avcodec_copy_context(out_stream->codec, in_stream->codec) < 0) {
				printf("Failed to copy context from input to output stream codec context\n");
				goto end;
			}
			out_stream->codec->codec_tag = 0;
			if (ofmt_ctx->oformat->flags & AVFMT_GLOBALHEADER)
				out_stream->codec->flags |= CODEC_FLAG_GLOBAL_HEADER;
			/*break;*/
		}

		//根据输入流创建输出流（Create output AVStream according to input AVStream）
		if (ifmt_ctx->streams[i]->codec->codec_type == AVMEDIA_TYPE_AUDIO) {
			audioindex_a = i;
			AVStream *in_stream = ifmt_ctx->streams[i];
			AVStream *out_stream = avformat_new_stream(ofmt_ctx, in_stream->codec->codec);
			if (!out_stream) {
				printf("Failed allocating output stream\n");
				ret = AVERROR_UNKNOWN;
				goto end;
			}
			audioindex_out = out_stream->index;
			//复制AVCodecContext的设置（Copy the settings of AVCodecContext）
			if (avcodec_copy_context(out_stream->codec, in_stream->codec) < 0) {
				printf("Failed to copy context from input to output stream codec context\n");
				goto end;
			}
			out_stream->codec->codec_tag = 0;
			if (ofmt_ctx->oformat->flags & AVFMT_GLOBALHEADER)
				out_stream->codec->flags |= CODEC_FLAG_GLOBAL_HEADER;

			/*break;*/
		}
	}

	//输出一下格式------------------
	printf("Output Information====================\n");
	av_dump_format(ofmt_ctx, 0, out_filename, 1);
	printf("======================================\n");
	//打开输出文件（Open output file）
	if (!(ofmt->flags & AVFMT_NOFILE)) {
		if (avio_open(&ofmt_ctx->pb, out_filename, AVIO_FLAG_WRITE) < 0) {
			printf("Could not open output file '%s'", out_filename);
			goto end;
		}
	}
	//写文件头（Write file header）
	if (avformat_write_header(ofmt_ctx, NULL) < 0) {
		printf("Error occurred when opening output file\n");
		goto end;
	}
	int frame_index = 0;
	int64_t cur_pts_v = 0, cur_pts_a = 0;

	//FIX
#if USE_H264BSF
	AVBitStreamFilterContext* h264bsfc = av_bitstream_filter_init("h264_mp4toannexb");
#endif
#if USE_AACBSF
	AVBitStreamFilterContext* aacbsfc = av_bitstream_filter_init("aac_adtstoasc");
#endif
	time_t start, end;
	time(&start);
	double cost;
	while (1) {
		/*AVFormatContext *ifmt_ctx;*/
		int stream_index = 0;
		AVStream *in_stream, *out_stream;


		//获取一个AVPacket（Get an AVPacket）
		if (av_compare_ts(cur_pts_v, ifmt_ctx->streams[videoindex_v]->time_base, cur_pts_a, ifmt_ctx->streams[audioindex_a]->time_base) <= 0) {
			/*ifmt_ctx=ifmt_ctx_v;*/
			stream_index = videoindex_out;

			if (av_read_frame(ifmt_ctx, &pkt) >= 0) {
				do {
					if (pkt.stream_index == videoindex_v) {
						cur_pts_v = pkt.pts;
						break;
					}
				} while (av_read_frame(ifmt_ctx, &pkt) >= 0);
			}
			else {
				break;
			}
		}
		else {
			/*ifmt_ctx=ifmt_ctx_a;*/
			stream_index = audioindex_out;
			if (av_read_frame(ifmt_ctx, &pkt) >= 0) {
				do {
					if (pkt.stream_index == audioindex_a) {
						cur_pts_a = pkt.pts;
						break;
					}
				} while (av_read_frame(ifmt_ctx, &pkt) >= 0);
			}
			else {
				break;
			}

		}

		in_stream = ifmt_ctx->streams[pkt.stream_index];
		out_stream = ofmt_ctx->streams[stream_index];
		//FIX
#if USE_H264BSF
		av_bitstream_filter_filter(h264bsfc, in_stream->codec, NULL, &pkt.data, &pkt.size, pkt.data, pkt.size, 0);
#endif
#if USE_AACBSF
		av_bitstream_filter_filter(aacbsfc, in_stream->codec, NULL, &pkt.data, &pkt.size, pkt.data, pkt.size, 0);
#endif
		//FIX：No PTS (Example: Raw H.264)
		//Simple Write PTS
		if (pkt.pts == AV_NOPTS_VALUE) {
			//Write PTS
			AVRational time_base1 = in_stream->time_base;
			//Duration between 2 frames (us)
			int64_t calc_duration = (double)AV_TIME_BASE / av_q2d(in_stream->r_frame_rate);
			//Parameters
			pkt.pts = (double)(frame_index*calc_duration) / (double)(av_q2d(time_base1)*AV_TIME_BASE);
			pkt.dts = pkt.pts;
			pkt.duration = (double)calc_duration / (double)(av_q2d(time_base1)*AV_TIME_BASE);
			frame_index++;
		}
		/* copy packet */
		//转换PTS/DTS（Convert PTS/DTS）
		pkt.pts = av_rescale_q(pkt.pts, in_stream->time_base, out_stream->time_base);
		pkt.dts = av_rescale_q(pkt.dts, in_stream->time_base, out_stream->time_base);
		pkt.duration = av_rescale_q(pkt.duration, in_stream->time_base, out_stream->time_base);
		pkt.pos = -1;
		pkt.stream_index = stream_index;

		printf("Write 1 Packet. size:%5d\tpts:%8d\n", pkt.size, pkt.pts);
		//写入（Write）
		if (av_interleaved_write_frame(ofmt_ctx, &pkt) < 0) {
			printf("Error muxing packet\n");
			break;
		}
		av_free_packet(&pkt);

		time(&end);
		cost = difftime(end, start);
		//printf("%f\n", cost);
		if (cost>18) {
			break;
		}
	}
	//写文件尾（Write file trailer）
	av_write_trailer(ofmt_ctx);

#if USE_H264BSF
	av_bitstream_filter_close(h264bsfc);
#endif
#if USE_AACBSF
	av_bitstream_filter_close(aacbsfc);
#endif

end:
	avformat_close_input(&ifmt_ctx);
	/*avformat_close_input(&ifmt_ctx_a);*/
	/* close output */
	if (ofmt_ctx && !(ofmt->flags & AVFMT_NOFILE))
		avio_close(ofmt_ctx->pb);
	avformat_free_context(ofmt_ctx);
	if (ret < 0 && ret != AVERROR_EOF) {
		printf("Error occurred.\n");
		return -1;
	}
	return 0;
}

**Comment by cjztool** [comment]
去年做项目的时候也参考了不少雷神的示例,做完功能还说等他毕业了一定把招来,结果噩耗传来,实在让人唏嘘..默哀!

**Comment by xsfgdut** [comment]
@chengzong 参照雷神代码，你有实现录像功能吗？
谢谢！

**Comment by lanyan520** [comment]
@xsfgdut 我目前离职了，但上家公司有专人做ijk源码修改封装，定制的需求都能实现，但是抱歉我不懂没法给你提供帮助

**Comment by zhengchengbin610** [comment]
@xsfgdut  网络上已经有人实现了播放直播时录制，我参考它已经实现了

**Comment by microxdd** [comment]
@xsfgdut 可否有示例的参考地址？

**Comment by momoxiaoray** [comment]
@zhengchengbin610 能否提供下，万分感谢

**Comment by aytunch** [comment]
@cjztool Hi, did you manage to solve recording with Audio? It has been 4 years since this issue is opened? Is there a way to record/cache the audio/video with IJKPlayer?
