### ISSUE TITLE
断网后联网问题

### ISSUE THREAD

**Issue by fuboyou** [Bilibili/ijkplayer#1168]
你好，iOS中，播放器播放中，断开网络，视频可以继续播放至缓冲部位，继续等待，无loading，打开网络，视频不继续播放，点击播放or暂停按钮，都不能唤起继续播放

**Comment by bbcallen** [comment]
You should have received an error notification.

**Comment by fuboyou** [comment]
I will try, thanks

**Comment by blueseaguo** [comment]
@fuboyou 你收到了吗，我怎么没有收到通知

**Comment by fuboyou** [comment]
@blueseaguo  你监听的那个通知？

**Comment by blueseaguo** [comment]
[[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(loadStateDidChange:)
                                                 name:IJKMPMoviePlayerLoadStateDidChangeNotification
                                               object:_player];
    
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(moviePlayBackDidFinish:)
                                                 name:IJKMPMoviePlayerPlaybackDidFinishNotification
                                               object:_player];
    
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(mediaIsPreparedToPlayDidChange:)
                                                 name:IJKMPMediaPlaybackIsPreparedToPlayDidChangeNotification
                                               object:_player];
    
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(moviePlayBackStateDidChange:)
                                                 name:IJKMPMoviePlayerPlaybackStateDidChangeNotification
                                               object:_player];
}

不就是这几个通知

**Comment by blueseaguo** [comment]
@fuboyou  加下qq 我们一起讨论下397805741

**Comment by blueseaguo** [comment]
@bbcallen 断网后，在联网是哪个通知吗？，请指教下
