### ISSUE TITLE
add a filter to the exoplayer

### ISSUE THREAD

**Issue by Usernamezhx** [Bilibili/ijkplayer#1172]
I want to add a filter to exoplayer to process frame image , i am not sure the buff position ,**ExoPlayer/library/src/main/java/com/google/android/exoplayer/MediaCodecVideoTrackRenderer.java ** is that right ?   
 **protected boolean processOutputBuffer**(long positionUs, long elapsedRealtimeUs, MediaCodec codec,ByteBuffer buffer, MediaCodec.BufferInfo bufferInfo, int bufferIndex, boolean shouldSkip) 
 I am wondering what the ByteBuffer actually contains  . many thanks .

**Comment by bbcallen** [comment]
I think you should submit this issue to ExoPlayer...
