### ISSUE TITLE
getCurrentPosition() > getDuration()

### ISSUE THREAD

**Issue by XiaoXunLu** [Bilibili/ijkplayer#1175]
通过mVideoView.getCurrentPosition() 获取的当前时间比 mVideoView.getDuration()获取的总时间 要大出2秒

**Comment by Android4MediaPlayer** [comment]
提供下url

**Comment by XiaoXunLu** [comment]
http://test.douniuonline.com/FtpData/DouNiuVodData/20160217/CBA-JiHouSai-TianShan-ShouGang-DEL600-reconn/play.m3u8

**Comment by XiaoXunLu** [comment]
http://test.douniuonline.com/FtpData/DouNiuVodData/30003/play.m3u8

**Comment by Android4MediaPlayer** [comment]
which one？

**Comment by XiaoXunLu** [comment]
都是，在视频结尾的时候 getCurrentPosition()都会比 getDuration()要大

**Comment by Android4MediaPlayer** [comment]
都跟你的视频流有关系
1.http://test.douniuonline.com/FtpData/DouNiuVodData/30003/play.m3u8,这个视频开始时间戳不为0，修改下计算duration，不减去start_diff;
2.http://test.douniuonline.com/FtpData/DouNiuVodData/20160217/CBA-JiHouSai-TianShan-ShouGang-DEL600-reconn/play.m3u8，这个视频当视频流没有的时候还有音频流数据的，默认播完的逻辑是音视频都完成才就播放完成，所以你改下这个逻辑即可

**Comment by XiaoXunLu** [comment]
好的，谢谢

**Comment by Wes120** [comment]
请问，获取的getCurrentPosition() > getDuration()，播1分30秒的视频有时候会超出10多秒，超出的时间随机，每次seekto执行后误差会小一些，请问什么问题呢
