### ISSUE TITLE
获取音频流buffer数据来做回声消除的问题

### ISSUE THREAD

**Issue by LiteHeaven** [Bilibili/ijkplayer#1176]
大神你好，我做一个IP电话APP，推流并集成了IJKPlayer，两端需要实时的推视频音频流并播放。
现在遇到回声问题，需要回声消除，不知道能不能获取到播放器播放音频时的数据流，来和推的音频流来做运算，来实现回声消除？

**Comment by LiteHeaven** [comment]
补充，安卓的

**Comment by bbcallen** [comment]
If you mean PCM data, search sdl_audio_callback()

**Comment by LiteHeaven** [comment]
多谢回复

**Comment by yuesehanpangmailang** [comment]
@LiteHeaven 请问你解决了吗，如何拿到音频流数据的？

**Comment by LiteHeaven** [comment]
@yuesehanpangmailang 最近领导又说不做了，让我去搞别的，醉了。。

**Comment by Dordong** [comment]
@LiteHeaven @yuesehanpangmailang so？最后解决没有？
