### ISSUE TITLE
home挂起问题

### ISSUE THREAD

**Issue by Fisherman91** [Bilibili/ijkplayer#1178]
当按Home键被挂起，视频暂停，重新回到应用后播放器是黑屏，怎样显示暂停前的界面

**Comment by fuboyou** [comment]
@Fisherman91 我们发现在iOS9没有这个问题，在一个iOS7的设备有这个问题，你的测试设备是？

**Comment by Fisherman91** [comment]
@fuboyou 不好意思 我忘记说设备了 我说的是安卓 安卓设备应该都会这样 我试了三星、小米

**Comment by bbcallen** [comment]
No good solution, for now.
Android have to destroy SurfaceView when entering background, but iOS doesn't have to.

**Comment by martji** [comment]
有找到好的解决办法吗 @Fisherman91

**Comment by Fisherman91** [comment]
没有 @martji

**Comment by Shayabean** [comment]
这个问题现在解决了吗？
可以提供解决思路吗？
谢谢。
