### ISSUE TITLE
Demo里的进度条是怎么随着视频播放前进的?

### ISSUE THREAD

**Issue by aldirc** [Bilibili/ijkplayer#1181]
具体代码在哪里啊？
Demo里面修改mediaProgressSlider的value,是经过refreshMediaControl方法，但是refreshMediaControl跟播放器没有找到关联，在哪里哦？？？ @bbcallen

**Comment by SoXeon** [comment]
[self performSelector:@selector(refreshMediaControl) withObject:nil afterDelay:0.5];

**Comment by aldirc** [comment]
thank you @SoXeon
