### ISSUE TITLE
#ios#  播放rmvb格式视频 只有声音 黑屏

### ISSUE THREAD

**Issue by aldirc** [Bilibili/ijkplayer#1182]
When i use the demo play rmvb video.there is only voice ,no video.
here is the log:

===== custom modules begin =====
register protocol: async
register protocol: ijkhttphook
register protocol: ijkinject
register protocol: ijklongurl
register protocol: ijksegment
register protocol: ijktcphook
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff2.8--ijk0.4.4.1--dev0.3.3--rc7
ijkmp_set_inject_opaque(0x13c5318a0)
ijkmp_set_inject_opaque()=void
2016-04-15 14:32:45.574 IJKMediaDemo[2658:696866] OK setup GL
ijkmp_ios_set_view(glView=0x13c7accd0)
ijkmp_ios_set_view(glView=0x13c7accd0)=void
2016-04-15 14:32:45.585 IJKMediaDemo[2658:696866] invalidateRenderBuffer
2016-04-15 14:32:45.587 IJKMediaDemo[2658:696889] IJKSDLGLView: setupDisplay not ready
ijkmp_set_data_source(url="http://192.168.191.1/fuyun/trunk/Public/MP4/sb22.rmvb")
ijkmp_set_data_source(url="http://192.168.191.1/fuyun/trunk/Public/MP4/sb22.rmvb")=0
ijkmp_prepare_async()
===== versions =====
FFmpeg       : ff2.8--ijk0.4.4.1--dev0.3.3--rc7
libavutil    : 54.31.100
libavcodec   : 56.60.100
libavformat  : 56.40.101
libswscale   : 3.1.101
libswresample: 1.2.101
===== options =====
player-opts : video-pictq-size             = 3
player-opts : overlay-format               = fcc-_es2
player-opts : max-fps                      = 30
player-opts : framedrop                    = 0
player-opts : videotoolbox-max-frame-width = 960
player-opts : videotoolbox                 = 1
player-opts : start-on-prepared            = 1
format-opts : ijkinject-opaque             = 5307046048
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : timeout                      = 30000000
format-opts : reconnect                    = 1
format-opts : safe                         = 0
===================

**Comment by aldirc** [comment]
ijkmp_prepare_async()=0
request: GET /fuyun/trunk/Public/MP4/sb22.rmvb HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=0-

Connection: close

Host: 192.168.191.1

Icy-MetaData: 1




2016-04-15 14:32:45.626 IJKMediaDemo[2658:696866] invalidateRenderBuffer
2016-04-15 14:32:45.627 IJKMediaDemo[2658:696883] IJKSDLGLView: setupDisplay not ready
2016-04-15 14:32:45.631 IJKMediaDemo[2658:696866] invalidateRenderBuffer
2016-04-15 14:32:45.632 IJKMediaDemo[2658:696883] IJKSDLGLView: setupDisplay not ready
Format rm probed with size=2048 and score=100
request: GET /fuyun/trunk/Public/MP4/sb22.rmvb HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=1312134647-

Connection: close

Host: 192.168.191.1

Icy-MetaData: 1




Invalid stream index 2 for index at pos 1312684347
request: GET /fuyun/trunk/Public/MP4/sb22.rmvb HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=1016-

Connection: close

Host: 192.168.191.1

Icy-MetaData: 1




Option safe not found.
Before avformat_find_stream_info() pos: 1016 bytes read:552245 seeks:2
parser not found for codec rv40, packets or times may be invalid.
parser not found for codec rv40, packets or times may be invalid.
All info found
After avformat_find_stream_info() pos: 4691 bytes read:556235 seeks:2 frames:6
max_frame_duration: 10.000
Input #0, rm, from 'http://192.168.191.1/fuyun/trunk/Public/MP4/sb22.rmvb':
  Metadata:
    title           : \316޼\253\265\347Ӱ-bbs.wujidy.com
    author          : \316޼\253\265\347Ӱ-bbs.wujidy.com
    copyright       : 
    comment         : 
    ASMRuleBook     : #($Bandwidth >= 0),Stream0Bandwidth = 64000, Stream1Bandwidth = 1486000;
    Audiences       : Easy RealMedia Tool's Audience;
    audioMode       : music
    Creation Date   : 4/6/2016 16:02:48
    Description     : This File is Created by Easy RealMedia Tools@!
    Email           : rick@redcheek.net
    Generated By    : Easy RealMedia Tools V1.8x
    HomeWeb         : http://redcheek.net
    Keywords        : 
    Modification Date: 4/6/2016 16:02:48
    videoMode       : normal
  Duration: 01:52:22.24, start: 0.000000, bitrate: 1557 kb/s
    Stream #0:0, 5, 1/1000: Audio: aac (LC) (raac / 0x63616172), 32000 Hz, stereo, fltp, 64 kb/s
    Stream #0:1, 1, 1/1000: Video: rv40, 1 reference frame (RV40 / 0x30345652), none, 1280x720 (0x0), 1/1000, 1466 kb/s, 23.98 fps, 23.98 tbr, 1k tbn, 1k tbc
aout_open_audio()
AudioCodec: avcodec, aac
aout_pause_audio(0)
No codec could be found with id 70
ijkmp_get_msg: FFP_MSG_PREPARED
2016-04-15 14:32:47.454 IJKMediaDemo[2658:696866] FFP_MSG_PREPARED:
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
2016-04-15 14:32:47.454 IJKMediaDemo[2658:696866] fps in meta 23.975983
2016-04-15 14:32:47.455 IJKMediaDemo[2658:696866] mediaIsPreparedToPlayDidChange
2016-04-15 14:32:47.455 IJKMediaDemo[2658:696866] loadStateDidChange: IJKMPMovieLoadStatePlaythroughOK: 3
2016-04-15 14:32:47.455 IJKMediaDemo[2658:696866] IJKMPMoviePlayBackStateDidChange 1: playing
Using fltp internally between filters
avcodec/Audio: first frame decoded
2016-04-15 14:32:47.537 IJKMediaDemo[2658:696866] FFP_MSG_AUDIO_RENDERING_START:
Stream ends prematurely at 130024440, should be 1312684347
Will reconnect at 130024440.
request: GET /fuyun/trunk/Public/MP4/sb22.rmvb HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=130024440-

Connection: close

Host: 192.168.191.1

Icy-MetaData: 1

**Comment by aldirc** [comment]
i have settled it! 
the reason is:
`parser not found for codec rv40, packets or times may be invalid.`
 should  support rv40 in config/module-lite.sh

**Comment by xiaohuihui000** [comment]
what's is rv40?how should i do

**Comment by teddyla** [comment]
step:
1. vi config/module-lite.sh
2. search --enable-decoder=h264
3.copy below line & paste below the decoders h264. 
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=rv40"
4. rebuild~
