### ISSUE TITLE
crash issue.

### ISSUE THREAD

**Issue by xuebao555** [Bilibili/ijkplayer#1183]
![screen shot 2016-04-15 at 1 38 21 pm](https://cloud.githubusercontent.com/assets/13804847/14553267/5e490590-030f-11e6-98db-d9e17fc1d4bf.png)

**Comment by bbcallen** [comment]
When / How did it happen?

**Comment by xuebao555** [comment]
It was happened when I was trying to play rtsp stream from ffserver.
