### ISSUE TITLE
iOS 播放中断或者停止如何 恢复播放

### ISSUE THREAD

**Issue by ailialy** [Bilibili/ijkplayer#1184]
iOS 播放中断或者停止如何 恢复播放，由于网络或者其他原因导致播放中断或停止。有收到回调，我该如何恢复正常播放，直接调用play无效…

**Comment by bbcallen** [comment]
Create a new player.

**Comment by ailialy** [comment]
thanks，我试过create a new player 确实可以解决问题,是否有更好的办法，例如在网络层做处理，而不需要shutdown player then new a new player。谢谢@bbcallen

**Comment by bbcallen** [comment]
You need to modify FFmpeg, and implement reconnection inside it.

**Comment by ailialy** [comment]
OK…thanks，i try to modify ffmpeg… thanks@bbcallen

**Comment by taojeff** [comment]
@ail

> thanks，我试过create a new player 确实可以解决问题,是否有更好的办法，例如在网络层做处理，而不需要shutdown player then new a new player。谢谢@bbcallen

中断后你怎么再次创建一个新的player的啊
