### ISSUE TITLE
iOS  端程序后台之后,切换到前台,出现有声音,但是画面卡住的情况  用的硬解.  软解不会出现该问题   希望大神给与指点

### ISSUE THREAD

**Issue by yeshibuzhong** [Bilibili/ijkplayer#1188]
ijkmp_pause()
ijkmp_pause()=0
ijkmp_get_msg: FFP_REQ_PAUSE
aout_pause_audio(1)

ijkmp_start()
ijkmp_start()=0
ijkmp_get_msg: FFP_REQ_START
aout_pause_audio(0)
decodeFrame -12903 kVTInvalidSessionErr
after scale width 960 height 480 
recovery error!!!!

**Comment by Rannie** [comment]
same issue "kVTInvalidSessionErr"

**Comment by yeshibuzhong** [comment]
IJKVideoToolBox.m  693行   改为   context->idr_based_identified = false, 暂时解决了这个问题,用户也使用了一段时间没发现有异常
