### ISSUE TITLE
Android播放网络视频时，有没有加载中等待的动画？

### ISSUE THREAD

**Issue by kartyjoin** [Bilibili/ijkplayer#1189]
Android播放网络视频时，有没有加载中等待的动画？

**Comment by bbcallen** [comment]
No.

**Comment by NoGirlFriendException** [comment]
ijkplayer只负责提供 最基础的播放功能 以及一些state 的回调
view 层面的东西 需要咱们自己app层面去做的

**Comment by wanzhi** [comment]
Listening MEDIA_INFO_BUFFERING_START and MEDIA_INFO_BUFFERING_END in the onInfoListener @kartyjoin

**Comment by kartyjoin** [comment]
Thank you , I have been through listening with buffering implement loading custom view

**Comment by menshen** [comment]
listening  MEDIA_INFO_BUFFERING_START is not work well
