### ISSUE TITLE
iOS 硬解画质不如软解,请问该如何处理

### ISSUE THREAD

**Issue by yeshibuzhong** [Bilibili/ijkplayer#1191]
iOS 硬解画质不如软解清晰,请问该如何处理?   如果采用软解4S会卡的比较严重,请大神赐教

**Comment by yeshibuzhong** [comment]
[options setPlayerOptionIntValue:960   forKey:@"videotoolbox-max-frame-width"];
我看了一下是因为这个value设置有点小,那么设置为多少合适呢

**Comment by bbcallen** [comment]
No suitable value for everyone, only suitable value for yourself.

**Comment by yeshibuzhong** [comment]
OK  thanks
