### ISSUE TITLE
播放久了之后

### ISSUE THREAD

**Issue by Jucongyuan** [Bilibili/ijkplayer#1193]
"Thread-1033" prio=5 tid=26 Native
  | group="main" sCount=1 dsCount=0 obj=0x12d7e160 self=0xb8159138
  | sysTid=28033 nice=0 cgrp=default sched=0/0 handle=0xa4cc5000
  | state=S schedstat=( 933048559 359540429 1291 ) utm=75 stm=18 core=0 HZ=100
  | stack=0x9fba3000-0x9fba5000 stackSize=1012KB
  | held mutexes=
  native: #00 pc 00012a24  /system/lib/libc.so (syscall+28)
  native: #01 pc 00016461  /system/lib/libc.so (__pthread_cond_timedwait_relative(pthread_cond_t*, pthread_mutex_t*, timespec const*)+56)
  native: #02 pc 00009a21  /data/app/com.wangxiaobao.adplayer-1/lib/arm/libijkplayer.so (???)
  native: #03 pc 00011acf  /data/app/com.wangxiaobao.adplayer-1/lib/arm/libijksdl.so (???)
  native: #04 pc 0000ebbb  /data/app/com.wangxiaobao.adplayer-1/lib/arm/libijksdl.so (???)
  native: #05 pc 0001658f  /system/lib/libc.so (__pthread_start(void*)+30)
  native: #06 pc 000145a7  /system/lib/libc.so (__start_thread+6)
  (no managed stack frames)
"Thread-1034" prio=5 tid=27 Runnable
  | group="main" sCount=1 dsCount=0 obj=0x12c05a60 self=0xb851bb40
  | sysTid=28183 nice=0 cgrp=default sched=0/0 handle=0xa4ca5000
  | state=R schedstat=( 59481688890 891770864 9520 ) utm=5938 stm=10 core=1 HZ=100
  | stack=0x9df70000-0x9df72000 stackSize=1036KB
  | held mutexes= "mutator lock"(shared held)

**Comment by compilelife** [comment]
估计题主想表达的是，播放久了以后，ijkplayer卡住，其中一个线程堆栈如上。
