### ISSUE TITLE
vr 支持

### ISSUE THREAD

**Issue by erwinshao** [Bilibili/ijkplayer#1194]
hi， 请问ijkplayer是否有计划在最近的版本中支持vr视频的播放

**Comment by HomHomLin** [comment]
现在VR视频有标准了吗？

**Comment by cicicat** [comment]
VR视频与普通视频有什么不同吗？

**Comment by bbcallen** [comment]
No plan for VR.

**Comment by ashqal** [comment]
试试[MD360Player4Android](https://github.com/ashqal/MD360Player4Android)，与IjkMediaPlayer无缝衔接
