### ISSUE TITLE
getVideoSarNum() and getVideoSarDen()

### ISSUE THREAD

**Issue by NoGirlFriendException** [Bilibili/ijkplayer#1197]
我的英语不是太好 就不用英语提问了
咱们项目中 IMediaPlayer的
getVideoSarDen
getVideoSarNum
分别是干什么用的？ 返回的值有什么意义呢?
感谢 回复！

**Comment by bbcallen** [comment]
google ffmpeg sar

**Comment by linjiansheng** [comment]
http://www.cnblogs.com/yinxiangpei/articles/3949041.html
这里说提到 PAR 一般都是 1:1，不太准确的理解 sar 就是 源视频的宽高比，即视频分辨率宽高比
