### ISSUE TITLE
播放m3u8直播视频会突然崩溃掉

### ISSUE THREAD

**Issue by hOlMoo** [Bilibili/ijkplayer#1198]
16:29:56.603 2392-6100/com.vpgame.eric I/IJKMEDIA: HLS request for url 'http://hls3.douyutv.com/live/35954rq7nxCHsQko_550/284040.ts?wsApp=HLS&wsMonitor=-1', offset 0, playlist 0
04-20 16:29:56.703 2392-6100/com.vpgame.eric D/IJKMEDIA: Continuity check failed for pid 0 expected 1 got 0
04-20 16:29:56.703 2392-6100/com.vpgame.eric D/IJKMEDIA: Continuity check failed for pid 4095 expected 1 got 0
04-20 16:29:56.703 2392-6100/com.vpgame.eric D/IJKMEDIA: Continuity check failed for pid 256 expected 15 got 0
04-20 16:29:56.743 2392-6100/com.vpgame.eric D/IJKMEDIA: Continuity check failed for pid 257 expected 12 got 0
04-20 16:29:56.843 2392-6121/com.vpgame.eric A/libc: heap corruption detected by dlfree
04-20 16:29:56.843 2392-6121/com.vpgame.eric A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 6121 (ff_audio_dec)

**Comment by bbcallen** [comment]
Possibly fixed in k0.5.1
