### ISSUE TITLE
play fast about 1-2s when seek

### ISSUE THREAD

**Issue by wqmijkplayer** [Bilibili/ijkplayer#1201]
@bbcallen 
I have a bug like below
play a special file (http://pan.baidu.com/s/1kV4crHX), start to seek, play fast about 1-2s, and then play normally
Thanks

**Comment by bbcallen** [comment]
If audio/video timestamp is not aligned at seek point, it could happen.

**Comment by wqmijkplayer** [comment]
right, audio/video time stamp is not aligned,
audio time stamp is larger than video time stamp.
other player(e.g. android mediaplayer) have no this issue,
how to fix it?

**Comment by bbcallen** [comment]
Modify ff_ffplay.c, drop those frames.

**Comment by erikhric** [comment]
Hi @bbcallen,
how can I drop all frames and try to stay in present when I'm trying to play live stream?

**Comment by bbcallen** [comment]
Search frame_drop in ff_ffplay.c

**Comment by erikhric** [comment]
@bbcallen Which one will take effect?
_ijkplayer-android/ijkmedia/ijkplayer_ **or** _/ijkplayer-android/extra/ffmpeg_ ?

After changing something I simply run this?:
```
compile-ffmpeg.sh clean
compile-ffmpeg.sh all
compile-ijk.sh all
```

**Comment by bbcallen** [comment]
"compile-ijk.sh all" is enough for ff_ffplay.c modification.
