### ISSUE TITLE
播放rtmp直播流，延迟越来越高

### ISSUE THREAD

**Issue by iosnower** [Bilibili/ijkplayer#1202]
使用android k0.4.4.1版，在播放rtmp直播流，有时由于网络的原因，会卡一会儿再恢复播放，但随着卡顿的次数增加，播放的视频延迟会积累的越来越长。
请问这种情况，如何来开善，使得延迟不会积累的太长。

**Comment by bbcallen** [comment]
No good solution, for now.

**Comment by iosnower** [comment]
感谢您的回复。
请问有没有参数，可以设置这个缓存的大小呢？或许可以把这个缓存设的小一些，不积累太多，可能会减轻一些。
请问具体的参数是哪个？

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/ff_ffplay_options.h

**Comment by lyqaiym** [comment]
@bacallen 那有没有技术本地延迟的方法？

**Comment by iosnower** [comment]
@bacallen 不好意思，里面的设置太多了，有些我也不是很理解，能不能具体推荐几个，然后我来试试，十分感谢。

**Comment by linjiansheng** [comment]
You can flush the audioq and videoq when queue is too large in ff_fplay.c:read_thread
But this only usefull the network change good, otherwise, suggest seek(0), or restart play

**Comment by iosnower** [comment]
@linjiansheng 感谢你的建议，关于flush audioq和videoq，我也是这么想的。

**Comment by danjianhua** [comment]
请问解决问题了么？ 请问下具体怎么flush audioq和videoq。
