### ISSUE TITLE
ijkMediaPlayer 不能被回收

### ISSUE THREAD

**Issue by aii1991** [Bilibili/ijkplayer#1204]
打使用ijkMediaPlayer播放的页面,然后点击返回键,
在onDestroy中调用public void stopPlayback() {
        if (mMediaPlayer != null) {
            mMediaPlayer.stop();
            mMediaPlayer.release();
            mMediaPlayer = null;
            mCurrentState = STATE_IDLE;
            mTargetState = STATE_IDLE;
            AudioManager am = (AudioManager) mAppContext.getSystemService(Context.AUDIO_SERVICE);
            am.abandonAudioFocus(null);
        }
    }
该方法,重复打开和退出.
在android studio 的memory视图中发现每打开一次页面内存就升高一定,而不会降低

**Comment by TuJHgithub** [comment]
我也遇到了相同的问题，楼主解决了吗？求助

**Comment by aii1991** [comment]
我是用了别人的东西出现的  ijkplayer测试了 不会  现在问题解决了

**Comment by TuJHgithub** [comment]
解决问题了，是我内存泄漏了

**Comment by luojinfang** [comment]
@TuJHgithub  楼主怎么解决的啊

**Comment by luojinfang** [comment]
@aii1991  楼主怎么解决的啊

**Comment by TuJHgithub** [comment]
@luojinfang 我是把activity内存泄漏了，解决就好了

**Comment by aii1991** [comment]
我是用了GiraffePlayer别人对ijkplayer的播放界面的封装,他里面用了handle的延时发送消息,在activity被销毁时没有释放掉handle,导致activity不能被回收,ijkplayer是可以被回收的

**Comment by TuJHgithub** [comment]
好吧  可能我们用的是同一个demo。把ondestory修改下就好
 public void onDestroy() {
        orientationEventListener.disable();
        handler.removeMessages(MESSAGE_FADE_OUT);
        handler.removeMessages(MESSAGE_HIDE_CENTER_BOX);
        handler.removeMessages(MESSAGE_SEEK_NEW_POSITION);
        handler.removeMessages(MESSAGE_SHOW_PROGRESS);
        handler.removeMessages(MESSAGE_RESTART_PLAY);
        videoView.stopPlayback();
    }

**Comment by aii1991** [comment]
我之前已经告诉过GiraffePlayer的作者了 他已经修复了

**Comment by luojinfang** [comment]
@aii1991  @TuJHgithub  谢谢两位

**Comment by hzhzhen** [comment]
我发现native层的内存有所升高，你们的不会？

**Comment by maowentao0416** [comment]
我也发现native层的内存会不停的升高
