### ISSUE TITLE
关于两个页面都调用 ijkplayer 的问题

### ISSUE THREAD

**Issue by zhang625152131** [Bilibili/ijkplayer#1205]
我在两个页面都使用了 ikplayer, 当我退出第一个页面进入第二个页面播放视频的时候,第二个页面会出现第一个页面的音频,是我第一个页面没有完全释放掉么? 我在viewDidDisappear 的时候调用了shutdown 和removeMovieNotificationObservers.  还需要做一些其他的什么操作么?

**Comment by blueseaguo** [comment]
是的，你没有释放完成

**Comment by blueseaguo** [comment]
这个包含播放的vc也要释放掉，如果不释放掉，也会播放适应，你看看的dealloc调用没有

**Comment by zhang625152131** [comment]
谢谢, ARC模式下 的确要在 dealloc 里面将播放 vc 释放
