### ISSUE TITLE
Error occurred when seek video with android content Uri

### ISSUE THREAD

**Issue by 109021017** [Bilibili/ijkplayer#1206]
I added a Sample "content://media/external/video/media/2698" to the sample list.
And it works great with AndroidMediaPlayer and ijkExoMediaPlayer.
But with IjkMediaPlayer when i seek the video, it just stopped playing.

Here's some log:

D/IJKMEDIA: IjkMediaPlayer_seekTo
D/IJKMEDIA: ijkmp_seek_to(11416)
D/IJKMEDIA: ijkmp_seek_to(11416)=0
D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_SEEK
D/IJKMEDIA: stream_seek 11416000(11416) + 0, 
D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_SEEK: seek to 11416
D/IJKMEDIA: ffp_toggle_buffering_l: start
D/IJKMEDIA: FFP_MSG_BUFFERING_START:
D/IjkVideoView: MEDIA_INFO_BUFFERING_START:
E/IJKMEDIA: stream 1, offset 0x59c5c5: partial file
D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_SEEK_COMPLETE
D/IJKMEDIA: FFP_MSG_SEEK_COMPLETE:
D/IJKMEDIA: ffp_toggle_buffering_l: end
D/IJKMEDIA: FFP_MSG_BUFFERING_END:
D/IjkVideoView: MEDIA_INFO_BUFFERING_END:
I/IJKMEDIA: ffp_toggle_buffering: completed: OK
D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_COMPLETED
E/IJKMEDIA: stream 1, offset 0x59c7c5: partial file
D/IJKMEDIA: FFP_MSG_COMPLETED:
I/IJKMEDIA: ffp_toggle_buffering: eof
D/IJKMEDIA: IjkMediaPlayer_native_finalize
D/IJKMEDIA: IjkMediaPlayer_release
D/IJKMEDIA: IjkMediaPlayer_native_finalize
D/IJKMEDIA: IjkMediaPlayer_release

**Comment by bbcallen** [comment]
content protocol is based on FFmpeg's pipe protocol, which doesn't support seek.
