### ISSUE TITLE
在华为CHM-CL00 上 系统为安卓4.4.4 ， 运行demo程序崩溃

### ISSUE THREAD

**Issue by mw258176257** [Bilibili/ijkplayer#1213]
04-23 02:22:42.334 5672-5694/tv.danmaku.ijk.media.sample A/libc: invalid address or address of corrupt block 0x7e5201b8 passed to dlfree
04-23 02:22:42.344 5672-5694/tv.danmaku.ijk.media.sample A/libc: Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 5694 (ff_read)

用的下面的gradle：
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.android.support:preference-v7:23.0.1'
    compile 'com.android.support:support-annotations:23.0.1'

    compile 'com.squareup:otto:1.3.8'
    compile 'tv.danmaku.ijk.media:ijkplayer-java:0.5.0'
    compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.5.0'
    compile 'tv.danmaku.ijk.media:ijkplayer-exo:0.5.0'

拖动进度条的时候崩溃。
视频地址是这个：http://baobab.wdjcdn.com/1457423930928CGI.mp4

**Comment by bbcallen** [comment]
Confirmed,
I'll take a look into it.

**Comment by bbcallen** [comment]
Possibly fixed in k0.5.1

**Comment by mw258176257** [comment]
我今天再测试下

**Comment by mw258176257** [comment]
修复OK了，感谢
