### ISSUE TITLE
 libyuv.h: No such file or directory

### ISSUE THREAD

**Issue by 473790228** [Bilibili/ijkplayer#1217]
ijksdl <= ijksdl_codec_android_mediacodec.c
/Users/xx/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijksdl/ffmpeg/abi_all/image_convert.c:25:20: fatal error: libyuv.h: No such file or directory
 #include "libyuv.h"

**Comment by bbcallen** [comment]
Seems you didn't fetch libyuv successfully.
