### ISSUE TITLE
关于iosDemo

### ISSUE THREAD

**Issue by ShixinPeng** [Bilibili/ijkplayer#1218]
弱弱的问下：iosDemo在加载样例的时候，为什么ios7一下数据源要减一呢？？

**Comment by bbcallen** [comment]
Which line?

**Comment by ShixinPeng** [comment]
//设置行数
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    //当ios版本大于或等于ios7
    if (IOS_NEWER_OR_EQUAL_TO_7) {
        return self.sampleList.count;
    } else {
        //ios7一下
        return self.sampleList.count - 1;
    }
}

**Comment by ShixinPeng** [comment]
IJKDemoSampleViewController里面的数据源方法

**Comment by bbcallen** [comment]
Can't remember.
