### ISSUE TITLE
crashed while playing http-flv.

### ISSUE THREAD

**Issue by ielicyan** [Bilibili/ijkplayer#1219]
04-25 14:22:33.972 W/IJKMEDIA(28535): message_loop exit
04-25 14:22:33.972 I/IJKMEDIA(28535): SDL_JNI_DetachThreadEnv: [31362]
04-25 14:22:33.982 I/IJKMEDIA(28535): SDL_JNI_DetachThreadEnv: [31363]
04-25 14:22:33.987 E/IJKMEDIA(28535): av_read_frame error: abb6a7bb(«,¶,§,»): AVERROR_EXIT
04-25 14:22:35.037 F/libc    (28535): invalid address or address of corrupt block 0x7c57f0f8 passed to dlfree
04-25 14:22:35.037 F/libc    (28535): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 28535 (jk.media.sample)
04-25 14:22:35.092 I/DEBUG   ( 2439): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-25 14:22:35.092 I/DEBUG   ( 2439): pid: 28535, tid: 28535, name: jk.media.sample  >>> tv.danmaku.ijk.media.sample <<<
04-25 14:22:35.092 I/DEBUG   ( 2439): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadbaad
04-25 14:22:35.092 I/DEBUG   ( 2439): Abort message: 'invalid address or address of corrupt block 0x7c57f0f8 passed to dlfree'
04-25 14:22:35.217 I/DEBUG   ( 2439):     r0 00000000  r1 40097726  r2 deadbaad  r3 4009b3cf
04-25 14:22:35.217 I/DEBUG   ( 2439):     r4 7c57f0f8  r5 400a6188  r6 40045000  r7 7c57f100
04-25 14:22:35.217 I/DEBUG   ( 2439):     r8 78f728a0  r9 6d475c78  sl 41508700  fp becd7344
04-25 14:22:35.217 I/DEBUG   ( 2439):     ip 00000001  sp becd7258  lr 4006895f  pc 40068960  cpsr 600f0030
04-25 14:22:35.217 I/DEBUG   ( 2439): backtrace:
04-25 14:22:35.217 I/DEBUG   ( 2439):     #00  pc 00011960  /system/lib/libc.so (dlfree+1191)
04-25 14:22:35.217 I/DEBUG   ( 2439):     #01  pc 0000deaf  /system/lib/libc.so (free+10)
04-25 14:22:35.217 I/DEBUG   ( 2439):     #02  pc 0019e3e5  /data/app-lib/tv.danmaku.ijk.media.sample-1/libijkffmpeg.so (ffurl_closep+40)

**Comment by bbcallen** [comment]
Possibly fixed on master.
