### ISSUE TITLE
播放m3u8格式的视频流不清晰

### ISSUE THREAD

**Issue by const-zhou** [Bilibili/ijkplayer#1220]
播放某些直播的m3u8格式的源不清晰，画面比较模糊，但是用百度第三方播放器（也是基于ffmpeg）很清晰。用手机浏览器播放在6plus上面很清晰，但在5c和se上面都比较模糊，网络环境一样。
视频源如下 ：
http://dlhls.load.cdn.zhanqi.tv/zqlive/122597_LhpxD.m3u8
想请问一下可能是什么原因？

**Comment by const-zhou** [comment]
下载m3u8描述文件发现里面有三种格式的地址，分别对应的
/zqlive/23632_1gFr7_400/index.m3u8?Dnion_vsnae=23632_1gFr7
/zqlive/23632_1gFr7_700/index.m3u8?Dnion_vsnae=23632_1gFr7
/zqlive/23632_1gFr7_1024/index.m3u8?Dnion_vsnae=23632_1gFr7
查看ijkplayer的日志，也解析出了这三种格式的地址，最终选择了400的那个。想请问一下代码里面是默认选择第一个么？如果想选择1024的那个流，应该怎么改呢？

**Comment by bbcallen** [comment]
Modify ff_ffplay.c, implement your own selecter.

**Comment by const-zhou** [comment]
嗯，谢谢。找到了

**Comment by zhangfeisysu** [comment]
@const-zhou 问题怎么解的呀？可以指导一下吗

**Comment by const-zhou** [comment]
@zhangfeisysu 我是在播放前对m3u8进行解析，拿到最清晰的那条视频流给ijkplayer进行播放的。

**Comment by zhangfeisysu** [comment]
可以详细说一说如何解析么？

**Comment by const-zhou** [comment]
@zhangfeisysu 你可以搜一下M3U8Kit这个开源库，可以拿到m3u8里面的多条源，并且可以源的质量进行排序，选择高清的源填给ijkplayer。

**Comment by linqssonny** [comment]
@bbcallen  怎么修改 ff_ffplay.c, 能说得详细一点吗

**Comment by linqssonny** [comment]
@const-zhou Android不知道怎么改
