### ISSUE TITLE
demo中的bug，导致不能使用视频硬解码

### ISSUE THREAD

**Issue by ramonqlee** [Bilibili/ijkplayer#1221]
Setting类中的函数需要做如下修正：

public boolean getUsingMediaCodec() {
//        String key = mAppContext.getString(R.string.pref_key_using_media_codec);
//        return mSharedPreferences.getBoolean(key, false);
        return (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN);
    }

**Comment by bbcallen** [comment]
Why?
The option is supposed to be modified at runtime.
