### ISSUE TITLE
native crash at /system/lib/libc.so

### ISSUE THREAD

**Issue by HazimSharif** [Bilibili/ijkplayer#1224]
Hi. 
Im using GiraffePlayer which is based on ijkplayer library. After last update for Giraffeplayer for openssl, many user of my app start having below error. I was abel to reproduce error on emulator api 15 arm7 
Could you please advise how i can fix it. 
Many thanks.

Build fingerprint: 'samsung/j1aceltexx/j1acelte:4.4.4/KTU84P/J110FXXU0APB1:user/release-keys'
Revision: '1'
pid: 2203, tid: 2337, name: ff_read >>> info.*.*.* <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadbaad
Abort message: 'invalid address or address of corrupt block 0xab7483e8 passed to dlfree'
r0 00000000 r1 4006761e r2 deadbaad r3 4006b19e
r4 ab7483e8 r5 40076180 r6 4dd4c000 r7 ab7483f0
r8 ab66c920 r9 ab3e3c7c sl 000000bc fp ab3e2b60
ip 00000001 sp 60c1b2c0 lr 400387a3 pc 400387a4 cpsr 60000030
d0 2064657373617064 d1 6120726f2073736c
d2 6f20737365726466 d3 707572726f632072
d4 0000000100000001 d5 0000000000000000
d6 0000000000000829 d7 000000000009349c
d8 4347000040e00000 d9 00000000434e0000
d10 0000000000000000 d11 0000000000000000
d12 0000000000000000 d13 0000000000000000
d14 0000000000000000 d15 0000000000000000
d16 3fef3b96a293e600 d17 400fcee5a8a4f980
d18 416312d000000000 d19 be5ae5e49f7a3d66
d20 40032e4a2a741b9f d21 4037f9dcb5112287
d22 3f1675761676a000 d23 3eddf1e79327e23d
d24 3e15043a2804671b d25 fefefefefefefefe
d26 4037f9dcb5112287 d27 400abcdf01234bb8
d28 3ff0000000000000 d29 007f007f007f007f
d30 ffffffffffffffff d31 4000000000000000
scr 28000010
 
backtrace:
#00 pc 000117a4 /system/lib/libc.so (dlfree+1191)
#01 pc 0000dcfb /system/lib/libc.so (free+10)
#02 pc 001e028d /data/app-lib/info.*.*.*-2/libijkffmpeg.so (ffurl_closep+40)
 
code around pc:
40038784 6a014478 62021e4a f7fdb95a e008fd41
40038794 4a2b482a 447a4478 f0014621 4a13f9af
400387a4 49286014 f8d14479 079a31bc f501d51c
400387b4 e8bd70e0 f02c40f8 4823bb5b f7fd4478
400387c4 4822fd15 e7fa4478 42b7688f ae10f43f
400387d4 481fe611 e7f24478 4478481e 6888e7ef
400387e4 f43f4298 e606aed4 bf00bdf8 deadbaad
400387f4 0003de6e 0003de60 0003ddc4 00032d9c
40038804 0003dd3c 0003dd2a 0003dcb2 0003dc90
40038814 0003dc30 0003dc1e 0003dbb8 0003dba0
40038824 0003db8e 0003db38 0003db10 0003da84
40038834 0003da30 0003da16 0003d9f8 0002ee82
40038844 00032a00 0003d9d4 000329da 000329d2
40038854 000329c2 000329bc b168b538 0300ea41
40038864 04150c1a f401fb00 fbb4b13d 4288f0f0
40038874 f04fbf18 e00034ff 46204604 fb16f7fe
 
code around lr:
40038780 482e61a3 6a014478 62021e4a f7fdb95a
40038790 e008fd41 4a2b482a 447a4478 f0014621
400387a0 4a13f9af 49286014 f8d14479 079a31bc
400387b0 f501d51c e8bd70e0 f02c40f8 4823bb5b
400387c0 f7fd4478 4822fd15 e7fa4478 42b7688f
400387d0 ae10f43f 481fe611 e7f24478 4478481e
400387e0 6888e7ef f43f4298 e606aed4 bf00bdf8
400387f0 deadbaad 0003de6e 0003de60 0003ddc4
40038800 00032d9c 0003dd3c 0003dd2a 0003dcb2
40038810 0003dc90 0003dc30 0003dc1e 0003dbb8
40038820 0003dba0 0003db8e 0003db38 0003db10
40038830 0003da84 0003da30 0003da16 0003d9f8
40038840 0002ee82 00032a00 0003d9d4 000329da
40038850 000329d2 000329c2 000329bc b168b538
40038860 0300ea41 04150c1a f401fb00 fbb4b13d
40038870 4288f0f0 f04fbf18 e00034ff 46204604

**Comment by bbcallen** [comment]
Try k0.5.1

**Comment by HazimSharif** [comment]
Problem solved.

Thank you :+1:
