### ISSUE TITLE
新版的不支持播放本地hls格式视频

### ISSUE THREAD

**Issue by lyqaiym** [Bilibili/ijkplayer#1226]
avio.c的ffurl_connect方法打log
av_log(uc, AV_LOG_ERROR, "Protocol not on whitelist \'%s\'!\n", uc->protocol_whitelist);
在file.c文件ff_file_protocol的.default_whitelist   = "file,crypto"增加crypto

**Comment by bbcallen** [comment]
You can also set this option from player API setOption()

**Comment by tanqu2013** [comment]
请问setOption的参数是什么？
