### ISSUE TITLE
android k0.5.1 执行./compile-ffmpeg.sh all 

### ISSUE THREAD

**Issue by zhousuqiang** [Bilibili/ijkplayer#1229]
执行./compile-ffmpeg.sh all最后好像有错误，请问这个错误有没有影响，log如下:
ijkplayer-android/android/contrib/build/ffmpeg-x86_64/toolchain/bin//x86_64-linux-android-gcc
yasm/nasm not found or too old. Use --disable-yasm for a crippled build.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.

执行./compile-ijk.sh all 到最后log信息如下：
profiler build: NO
Android NDK: ERROR:/ijkplayer-android/android/ijkplayer/ijkplayer-x86_64/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /ijkplayer-android/android/contrib/build/ffmpeg-x86_64/output/libijkffmpeg.so exists  or that its path is correct   
/Developer_Tool/adt-bundle-mac-x86_64-20131030/sdk/ndk-bundle/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.

**Comment by bbcallen** [comment]
The log sais
```
yasm/nasm not found or too old. Use --disable-yasm for a crippled build.
```

**Comment by yq8308** [comment]
"do-complie-ffmpeg.sh"
export PATH=$FF_TOOLCHAIN_PATH/bin:$PATH

**Comment by zhousuqiang** [comment]
owendeMacBook-Pro:~ owen$ brew install yasm
Warning: yasm-1.3.0 already installed, it's just not linked
owendeMacBook-Pro:~ owen$ brew link yasm
Linking /usr/local/Cellar/yasm/1.3.0... 
Error: Could not symlink include/libyasm
/usr/local/include is not writable.

请问这种情况如何解决呢

**Comment by bbcallen** [comment]
I don't know.
This seems an homebrew issue.

**Comment by zhousuqiang** [comment]
已解决，谢谢，是因为部分目录没有权限。

**Comment by YasinHe** [comment]
挖个坟，这个咋解决的呢

**Comment by pc8067** [comment]
Because OS  is not installed yasm,  if your OS is Ubuntu,you can run 'apt-get install yasm'.
