### ISSUE TITLE
(M3u8-HLS) error  k0.51

### ISSUE THREAD

**Issue by msdos2** [Bilibili/ijkplayer#1232]
04-26 17:36:00.365 17747-18271/tv.danmaku.ijk.media.sample D/VideoActivity: run: #EXTM3U #EXT-X-VERSION:3 #EXT-X-ALLOW-CACHE:NO #EXT-X-TARGETDURATION:10 #EXT-X-MEDIA-SEQUENCE:13711 #EXTINF:7.68, media-ua4g9iky8_13711.ts #EXTINF:1.64, media-ua4g9iky8_13712.ts #EXTINF:2.2, media-ua4g9iky8_13713.ts #EXTINF:4.12, media-ua4g9iky8_13714.ts #EXTINF:1.76, media-ua4g9iky8_13715.ts #EXTINF:3.12, media-ua4g9iky8_13716.ts #EXTINF:10.0, media-ua4g9iky8_13717.ts #EXTINF:10.0, media-ua4g9iky8_13718.ts #EXTINF:2.68, media-ua4g9iky8_13719.ts #EXTINF:10.0, media-ua4g9iky8_13720.ts #EXTINF:1.44, media-ua4g9iky8_13721.ts #EXTINF:7.2, media-ua4g9iky8_13722.ts #EXTINF:6.52, media-ua4g9iky8_13723.ts #EXTINF:7.24, media-ua4g9iky8_13724.ts #EXTINF:6.08, media-ua4g9iky8_13725.ts #EXTINF:6.72, media-ua4g9iky8_13726.ts #EXTINF:7.68, media-ua4g9iky8_13727.ts #EXTINF:1.64, media-ua4g9iky8_13728.ts #EXTINF:3.76, media-ua4g9iky8_13729.ts #EXTINF:1.92, media-ua4g9iky8_13730.ts #EXTINF:6.24, media-ua4g9iky8_13731.ts #EXTINF:1.96, media-ua4g9iky8_13732.ts #EXTINF:10.0, media-ua4g9iky8_13733.ts #EXTINF:10.0, media-ua4g9iky8_13734.ts #EXTINF:7.12, media-ua4g9iky8_13735.ts #EXTINF:1.88, media-ua4g9iky8_13736.ts #EXTINF:6.16, media-ua4g9iky8_13737.ts #EXTINF:4.32, media-ua4g9iky8_13738.ts #EXTINF:2.24, media-ua4g9iky8_13739.ts #EXTINF:2.08, media-ua4g9iky8_13740.ts #EXT-X-ENDLIST
04-26 17:36:00.372 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_native_init
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_native_setup
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample I/IJKMEDIA: av_version_info: ff3.0--ll0.4.5.1--dev0.4.0--rc1-2-ge387700
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: ffpipeline_create_from_android()
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_inject_opaque(0x1004ae)
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_inject_opaque()=void
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(3)
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: moncleanup
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_native_setup
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample I/IJKMEDIA: av_version_info: ff3.0--ll0.4.5.1--dev0.4.0--rc1-2-ge387700
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: ffpipeline_create_from_android()
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_inject_opaque(0x1004b6)
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_inject_opaque()=void
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOption
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOption
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOption
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
04-26 17:36:00.373 17747-17747/tv.danmaku.ijk.media.sample D/tv.danmaku.ijk.media.player.IjkMediaPlayer: Couldn't open file on client side, trying server side
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample V/IJKMEDIA: setDataSource: path http://cdn.sstream.pw/live/canalplushd_9wgyfa8/playlist.m3u8
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_data_source(url="http://cdn.sstream.pw/live/canalplushd_9wgyfa8/playlist.m3u8")
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_data_source(url="http://cdn.sstream.pw/live/canalplushd_9wgyfa8/playlist.m3u8")=0
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffc87070)
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: ffpipeline_set_surface()
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffc87070)=void
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_prepareAsync
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_prepare_async()
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample I/IJKMEDIA: ===== versions =====
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample I/IJKMEDIA: FFmpeg       : ff3.0--ll0.4.5.1--dev0.4.0--rc1-2-ge387700
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample I/IJKMEDIA: libavutil    : 55.17.103
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample I/IJKMEDIA: libavcodec   : 57.24.102
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample I/IJKMEDIA: libavformat  : 57.25.100
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample I/IJKMEDIA: libswscale   : 4.0.100
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample I/IJKMEDIA: libswresample: 2.0.101
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample I/IJKMEDIA: ===== options =====
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample I/IJKMEDIA: player-opts : get-av-frame-timeout         = 10000
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample I/IJKMEDIA: player-opts : mediacodec                   = 1
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample I/IJKMEDIA: format-opts : ijkinject-opaque             = 1049782
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample I/IJKMEDIA: format-opts : ijkapplication               = -498944320
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample I/IJKMEDIA: format-opts : X-Requested-With             = ShockwaveFlash%2F21.0.0.182
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample I/IJKMEDIA: format-opts : user-agent                   = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2598.0 Safari/537.36
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample I/IJKMEDIA: format-opts : headers                      = Referer=http://www.ponlatv.com/jwplayer6/jwplayer.flash.swf
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample I/IJKMEDIA: ===================
04-26 17:36:00.374 17747-17747/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_prepare_async()=0
04-26 17:36:00.375 17747-18275/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_RunThread: [18275] ff_vout
04-26 17:36:00.375 17747-18276/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_RunThread: [18276] ff_read
04-26 17:36:00.375 17747-18276/tv.danmaku.ijk.media.sample D/IJKMEDIA: Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto'
04-26 17:36:00.375 17747-18276/tv.danmaku.ijk.media.sample W/IJKMEDIA: No trailing CRLF found in HTTP header.
04-26 17:36:00.375 17747-18274/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_RunThread: [18274] ff_msg_loop
04-26 17:36:00.375 17747-18274/tv.danmaku.ijk.media.sample D/IJKMEDIA: message_loop
04-26 17:36:00.382 17747-18274/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_FLUSH:
04-26 17:36:00.388 17747-17759/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_native_finalize
04-26 17:36:00.388 17747-17759/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_release
04-26 17:36:00.388 17747-17759/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
04-26 17:36:00.388 17747-17759/tv.danmaku.ijk.media.sample D/IJKMEDIA: ffpipeline_set_surface()
04-26 17:36:00.388 17747-17759/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
04-26 17:36:00.388 17747-17759/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_shutdown_l()
04-26 17:36:00.388 17747-17759/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_shutdown_l()=void
04-26 17:36:00.388 17747-17759/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_dec_ref(): ref=0
04-26 17:36:00.388 17747-17759/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_shutdown_l()
04-26 17:36:00.388 17747-17759/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_shutdown_l()=void
04-26 17:36:00.509 17747-17983/tv.danmaku.ijk.media.sample D/OpenGLRenderer: endAllStagingAnimators on 0xe246fe80 (ListView) with handle 0xef039890
04-26 17:36:19.352 17747-18276/tv.danmaku.ijk.media.sample E/IJKMEDIA: http://cdn.sstream.pw/live/canalplushd_9wgyfa8/playlist.m3u8: End of file
04-26 17:36:19.352 17747-18276/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [18276]
04-26 17:36:19.352 17747-18274/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_ERROR: 0
04-26 17:36:19.353 17747-17747/tv.danmaku.ijk.media.sample E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
04-26 17:36:19.353 17747-17747/tv.danmaku.ijk.media.sample D/IjkVideoView: Error: -10000,0

**Comment by bbcallen** [comment]
Can't access this url.
403 Forbidden
