### ISSUE TITLE
When I use Android Studio programming and good config dependences of build.gradle, I don't need to compile by myself?

### ISSUE THREAD

**Issue by smarxpan** [Bilibili/ijkplayer#1236]
Correctly?

**Comment by bbcallen** [comment]
No

**Comment by smarxpan** [comment]
@bbcallen Oh, I know,  it just download java package, only by compiling  `ijkplayer-android` I can use. 
Thanks a lot. And this issue cloud be close. XD

**Comment by bbcallen** [comment]
The demo, ijkplayer-example depends on local source code. You need to build by yourself if you want to use ijkplayer in that way.
If you download from jcenter via gradle, you don't have to build by yourself.
