### ISSUE TITLE
如何在播放视频时不加载本地缓存

### ISSUE THREAD

**Issue by YunhaoYu** [Bilibili/ijkplayer#1238]
现在需要播放实时视频，播放一次之后，再次打开时会先播放上次缓存的视频，如何避免这种情况，直接播放实时视频，不加载缓存，请大神解答下

**Comment by bbcallen** [comment]
I don't think ijkplayer can cache anything.

**Comment by YunhaoYu** [comment]
Thank you,It's my fault.
