### ISSUE TITLE
The video display surface black for about 1~2 seconds at the beginning of playback.

### ISSUE THREAD

**Issue by ielicyan** [Bilibili/ijkplayer#1239]
The video display surface black for about 1~2 seconds at the beginning of playback on sample apk(Android).

**Comment by ielicyan** [comment]
The video display area black about 1~2 seconds before the first video frame shown.The video frames is not black.It is caused by the render mechanism?

**Comment by nj-code-hub** [comment]
hi, 我遇到了和你类似的问题，有解吗？
