### ISSUE TITLE
按照github上面的介绍编译后，出现Error（-10000，0）

### ISSUE THREAD

**Issue by xfmax** [Bilibili/ijkplayer#1242]
可以正常播放mp4文件，但是播放Demo提供的后缀为.rc的文件，就会出现Error（-10000，0）错误

**Comment by bbcallen** [comment]
If you prefer more codec/format
https://github.com/Bilibili/ijkplayer#before-build

**Comment by xfmax** [comment]
我之前没有使用这段命令，后台编译了一遍，不行，我才使用了这段指令，但是还是播不出来，是不是这个命令和别的命令需要顺序执行啊？

**Comment by xfmax** [comment]
我是使用mac进行编译的，我又再试了一次，试了“If you prefer more codec/format”，但还是后缀为rc的文件无法播放，显示unknown对话框，这个问题应该从哪方面入手？

**Comment by bbcallen** [comment]
So, what is rc file?

**Comment by xfmax** [comment]
编译android项目，ijkplayer-example项目一进界面
![1](https://cloud.githubusercontent.com/assets/11729753/14908388/259b0874-0e09-11e6-9b03-69acf2e2edca.jpeg)

**Comment by bbcallen** [comment]
These are not a media files...

**Comment by xfmax** [comment]
但是我用过一个别人编译的apk文件，是可以播放这个的，播放的是一个香港电视台的新闻直播
[ijkplayer-sample-all32-debug.zip](https://github.com/Bilibili/ijkplayer/files/241805/ijkplayer-sample-all32-debug.zip)
