### ISSUE TITLE
离线播放

### ISSUE THREAD

**Issue by Sunzznn** [Bilibili/ijkplayer#1245]
我的视频已经做了缓存了，但是ijk好像是一定要有网络才可以正常播放，是吗？？？

**Comment by bbcallen** [comment]
No, why do you say that?

**Comment by Sunzznn** [comment]
I want to play my offline video with IJK , how can I do that

**Comment by bbcallen** [comment]
Set your file's path as url to ijkplayer.

**Comment by Sunzznn** [comment]
but when I initialize the video :

===== custom modules begin =====
register protocol: async
register protocol: ijkhttphook
register protocol: ijkinject
register protocol: ijklongurl
register protocol: ijksegment
register protocol: ijktcphook
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff2.8--ijk0.4.4.1--dev0.3.3--rc7
ijkmp_set_inject_opaque(0x14c7e8c20)
ijkmp_set_inject_opaque()=void
2016-04-29 17:18:16.775 TalkfunSDKDemo[4981:1456629] OK setup GL
ijkmp_ios_set_view(glView=0x14c7ed040)
ijkmp_ios_set_view(glView=0x14c7ed040)=void
ijkmp_set_data_source(url="http://p2.talk-fun.com/live/513/12835/mti6mjuxmw/video-client.mp4")
ijkmp_set_data_source(url="http://p2.talk-fun.com/live/513/12835/mti6mjuxmw/video-client.mp4")=0
ijkmp_prepare_async()
===== versions =====
FFmpeg       : ff2.8--ijk0.4.4.1--dev0.3.3--rc7
libavutil    : 54.31.100
libavcodec   : 56.60.100
libavformat  : 56.40.101
libswscale   : 3.1.101
libswresample: 1.2.101
===== options =====
player-opts : start-on-prepared            = 1
player-opts : overlay-format               = fcc-_es2
player-opts : max-fps                      = 30
player-opts : framedrop                    = 0
player-opts : videotoolbox-max-frame-width = 960
player-opts : videotoolbox                 = 0
player-opts : video-pictq-size             = 3
format-opts : ijkinject-opaque             = 5578329120
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : analyzeduration              = 1000000
format-opts : timeout                      = 30000000
format-opts : reconnect                    = 1
format-opts : probsize                     = 4096
format-opts : safe                         = 0
===================
ijkmp_prepare_async()=0
ijkmp_start()
ijkmp_start()=-3
2016-04-29 17:18:16.795 TalkfunSDKDemo[4981:1456629] invalidateRenderBuffer
2016-04-29 17:18:16.797 TalkfunSDKDemo[4981:1456659] IJKSDLGLView: setupDisplay not ready
Failed to resolve hostname p2.talk-fun.com: nodename nor servname provided, or not known
http://p2.talk-fun.com/live/513/12835/mti6mjuxmw/video-client.mp4: Input/output error
2016-04-29 17:18:16.812 TalkfunSDKDemo[4981:1456629] FFP_MSG_ERROR: 0
2016-04-29 17:18:16.812 TalkfunSDKDemo[4981:1456629] IJKMPMoviePlayBackStateDidChange 2: paused,TalkfunPlayerController.m,1083
2016-04-29 17:18:16.813 TalkfunSDKDemo[4981:1456629] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1

**Comment by bbcallen** [comment]
I don't think "http://p2.talk-fun.com/live/513/12835/mti6mjuxmw/video-client.mp4" is offline video.

**Comment by Sunzznn** [comment]
I use a filePath ，this is a cache of address  but  :

===== custom modules begin =====
register protocol: async
register protocol: ijkhttphook
register protocol: ijkinject
register protocol: ijklongurl
register protocol: ijksegment
register protocol: ijktcphook
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff2.8--ijk0.4.4.1--dev0.3.3--rc7
ijkmp_set_inject_opaque(0x13f891fa0)
ijkmp_set_inject_opaque()=void
2016-04-29 18:23:34.706 TalkfunSDKDemo[5153:1478590] serving response from NSURLConnection
2016-04-29 18:23:34.707 TalkfunSDKDemo[5153:1478547] Request #50: URL = <NSMutableURLRequest: 0x13fa159f0> { URL: http://p2.talk-fun.com/live/513/12835/mti6mjuxmw/video-client.mp4 }
2016-04-29 18:23:34.777 TalkfunSDKDemo[5153:1478512] OK setup GL
ijkmp_ios_set_view(glView=0x13f8b6650)
ijkmp_ios_set_view(glView=0x13f8b6650)=void
ijkmp_set_data_source(url="/var/mobile/Containers/Data/Application/8B969164-1A77-4BC5-AC45-B61F13CF1414/Library/Caches/TTT/A5E49F100E6A45039DE09C55D5B3A915")
ijkmp_set_data_source(url="/var/mobile/Containers/Data/Application/8B969164-1A77-4BC5-AC45-B61F13CF1414/Library/Caches/TTT/A5E49F100E6A45039DE09C55D5B3A915")=0
ijkmp_prepare_async()
===== versions =====
FFmpeg       : ff2.8--ijk0.4.4.1--dev0.3.3--rc7
libavutil    : 54.31.100
libavcodec   : 56.60.100
libavformat  : 56.40.101
libswscale   : 3.1.101
libswresample: 1.2.101
===== options =====
player-opts : start-on-prepared            = 1
player-opts : overlay-format               = fcc-_es2
player-opts : max-fps                      = 30
player-opts : framedrop                    = 0
player-opts : videotoolbox-max-frame-width = 960
player-opts : videotoolbox                 = 0
player-opts : video-pictq-size             = 3
format-opts : ijkinject-opaque             = 5360918432
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : analyzeduration              = 1000000
format-opts : timeout                      = 30000000
format-opts : reconnect                    = 1
format-opts : probsize                     = 4096
format-opts : safe                         = 0
===================
ijkmp_prepare_async()=0
ijkmp_start()
ijkmp_start()=-3
2016-04-29 18:23:34.796 TalkfunSDKDemo[5153:1478512] invalidateRenderBuffer
2016-04-29 18:23:34.799 TalkfunSDKDemo[5153:1478546] IJKSDLGLView: setupDisplay not ready
/var/mobile/Containers/Data/Application/8B969164-1A77-4BC5-AC45-B61F13CF1414/Library/Caches/TTT/A5E49F100E6A45039DE09C55D5B3A915: Protocol not found
2016-04-29 18:23:34.814 TalkfunSDKDemo[5153:1478512] FFP_MSG_ERROR: 0
2016-04-29 18:23:34.814 TalkfunSDKDemo[5153:1478512] IJKMPMoviePlayBackStateDidChange 2: paused,TalkfunPlayerController.m,1116
2016-04-29 18:23:34.814 TalkfunSDKDemo[5153:1478512] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1

**Comment by Sunzznn** [comment]
hello???     this is an offline video!

**Comment by bbcallen** [comment]
```
2016-04-29 18:23:34.799 TalkfunSDKDemo[5153:1478546] IJKSDLGLView: setupDisplay not ready
/var/mobile/Containers/Data/Application/8B969164-1A77-4BC5-AC45-B61F13CF1414/Library/Caches/TTT/A5E49F100E6A45039DE09C55D5B3A915: Protocol not found
```
Search README for the section 'If you prefer more codec/format'

**Comment by Sunzznn** [comment]
ok thx
