### ISSUE TITLE
如何对IjkPlayer越界检测

### ISSUE THREAD

**Issue by compilelife** [Bilibili/ijkplayer#1246]
我们项目中碰到多次Ijk的SIGSEGV问题，但未找到规律，想通过Google AddressSanitizer来查找是否存在内存越界问题。

然而当我按照[GoogleAddressSanitizerOnAndroid](https://github.com/google/sanitizers/wiki/AddressSanitizerOnAndroid)重新编译ijk，并加入人为越界代码和调试信息，越界检测并未触发，不知道是否配置正确？或者有哪些Ijkplayer的编译选项与越界检测的编译选项有冲突？

如检测libijkplayer.so这个库，配置如下：

ijkmedia/ijkplayer/Android.mk：
```
LOCAL_CFLAGS += -std=c99 -fsanitize=address -fno-omit-frame-pointer 
LOCAL_LDLIBS += -llog -landroid -fsanitize=address
LOCAL_ARM_MODE := arm
```

android/ijkplayer/ijkplayer-armv7a/src/main/jni/Application.mk：
`NDK_TOOLCHAIN_VERSION=clang`

不知道你们是如何越界检测的呢？

PS：
在我的最小Demo（与IjkPlayer无关）上，以上方法越界检测测试成功，所以Google的教程看起来是正确的。

目标平台：Android armv7a

**Comment by bbcallen** [comment]
Maybe you also need to modify FFmpeg's build script

**Comment by compilelife** [comment]
@bbcallen 我不这么觉得，因为我只对libijkplayer.so进行越界检测，且“人为越界”的代码也是加在libijkplayer.so中，无需对ffmpeg配置。

**Comment by bbcallen** [comment]
What's the difference between your demo and ijkplayer's build config?

**Comment by alexliyu** [comment]
发现换成ffmpeg3以后，多个之前正常的设备都经常崩溃掉

**Comment by compilelife** [comment]
我找到为什么不可以了。
android/ijkplayer/ijkplayer-armv7a/src/main/jni/Application.mk中的-O3和APP_OPTIM := release与asan的选项冲突，删除这两个选项，并按官方指导即可进行越界检测。（没深入研究，也有可能是优化选项将我的测试代码优化了）

如果越界检测又发现，会另发issue。
