### ISSUE TITLE
 Failed to resolve: tv.danmaku.ijk.media:ijkplayer-x86_64:0.5.1

### ISSUE THREAD

**Issue by devslava** [Bilibili/ijkplayer#1249]
Gragle build failed:
Failed to resolve: tv.danmaku.ijk.media:ijkplayer-x86_64:0.5.1
It seems like there is no  tv.danmaku.ijk.media:ijkplayer-x86_64:0.5.1 in the jcenter repo.

**Comment by bbcallen** [comment]
There it is.
https://bintray.com/bbcallen/maven/ijkplayer-x86_64/0.5.1/view#files/tv/danmaku/ijk/media/ijkplayer-x86_64/0.5.1

**Comment by bbcallen** [comment]
Sorry. aar is uploaded, but I forgot to add it to center.
