### ISSUE TITLE
iOSDemo运行报错 "libavutil/imgutils.h" file not found

### ISSUE THREAD

**Issue by yhjiang** [Bilibili/ijkplayer#1251]
按照ReadMe的教程，一步步的执行，执行到最后一步  
` # import ios/IJKMediaPlayer for MediaPlayer.framework-like interface (recommended) `
` # open ios/IJKMediaDemo/IJKMediaDemo.xcodeproj with Xcode `

的时候，运行报错，如图所示。![](https://s3.amazonaws.com/f.cl.ly/items/0I0g2l0L2V3V0e1E1L45/13D019FF-4B54-4C9B-BE67-B29E6BA0FDA8.png?v=28b0c5a4)

**Comment by yhjiang** [comment]
已经解决了，我ffmpeg使用的是3.0的，但是git checkout -B latest 的时候，没有选择最新的0.5.1，导致的代码跟ffmpeg库版本不相符。

**Comment by James-Geng** [comment]
How do you fix it? @yhjiang

**Comment by UniqueSilence** [comment]
> 已经解决了，我ffmpeg使用的是3.0的，但是git checkout -B latest 的时候，没有选择最新的0.5.1，导致的代码跟ffmpeg库版本不相符。
你是通过什么方式解决这个问题的？git checkout -B latest 这个应该是自动选择的吧  你又通过git tag查看所有版本然后选择最新版本的嘛？

**Comment by developC** [comment]
> > 已经解决了，我ffmpeg使用的是3.0的，但是git checkout -B latest 的时候，没有选择最新的0.5.1，导致的代码跟ffmpeg库版本不相符。
> > 你是通过什么方式解决这个问题的？git checkout -B latest 这个应该是自动选择的吧  你又通过git tag查看所有版本然后选择最新版本的嘛？

你解决了吗

**Comment by UniqueSilence** [comment]
emmm 问iOS圈的人 然后他发了一个可行framework





| |
灵枫静雨
|
|
邮箱：amcinny@126.com
|

签名由 网易邮箱大师 定制

在2019年11月07日 14:16，developC 写道：

已经解决了，我ffmpeg使用的是3.0的，但是git checkout -B latest 的时候，没有选择最新的0.5.1，导致的代码跟ffmpeg库版本不相符。
你是通过什么方式解决这个问题的？git checkout -B latest 这个应该是自动选择的吧 你又通过git tag查看所有版本然后选择最新版本的嘛？

你解决了吗

**Comment by peterng014** [comment]
你解决了吗?? please help

**Comment by acidhax** [comment]
git clone https://github.com/Bilibili/ijkplayer.git ijkplayer-ios
cd ijkplayer-ios

./init-ios.sh

cd ios
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all

**Comment by DragonTnT** [comment]
1.进入ijkplayer-ios/ios/compile-ffmpeg.sh
2.找到这一行 FF_ALL_ARCHS_IOS8_SDK="armv7 arm64 i386 x86_64"
3.删除掉其中的 armv7
4.回到ijkplayer-ios/ios，并执行
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all

**Comment by iOSKVCO** [comment]
> 1.进入ijkplayer-ios/ios/compile-ffmpeg.sh
> 2.找到这一行 FF_ALL_ARCHS_IOS8_SDK="armv7 arm64 i386 x86_64"
> 3.删除掉其中的 armv7
> 4.回到ijkplayer-ios/ios，并执行
> ./compile-ffmpeg.sh clean
> ./compile-ffmpeg.sh all

最开始，错在了---iOSDemo运行报错 "libavutil/imgutils.h" file not found ----
然后我按照你的步骤---1.进入ijkplayer-ios/ios/compile-ffmpeg.sh
2.找到这一行 FF_ALL_ARCHS_IOS8_SDK="armv7 arm64 i386 x86_64"
3.删除掉其中的 armv7
4.回到ijkplayer-ios/ios，并执行
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all -------，再一次执行工程，又报错了，错误是---Undefined symbols for architecture x86_64:
"_inflate", referenced from:
_http_read_stream in IJKMediaFramework(http.o)
_rtmp_open in IJKMediaFramework(rtmpproto.o)
"_uncompress", referenced from:
_id3v2_read_internal in IJKMediaFramework(id3v2.o)
_mov_read_cmov in IJKMediaFramework(mov.o)
"_inflateInit_", referenced from:
_rtmp_open in IJKMediaFramework(rtmpproto.o)
"_inflateInit2_", referenced from:
_http_read_header in IJKMediaFramework(http.o)
"_zlibCompileFlags", referenced from:
_http_read_header in IJKMediaFramework(http.o)
"_inflateEnd", referenced from:
_http_close in IJKMediaFramework(http.o)
_http_read_header in IJKMediaFramework(http.o)
_rtmp_open in IJKMediaFramework(rtmpproto.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation) ----

**Comment by ChenFushuo** [comment]
> > 1.进入ijkplayer-ios/ios/compile-ffmpeg.sh
> > 2.找到这一行 FF_ALL_ARCHS_IOS8_SDK="armv7 arm64 i386 x86_64"
> > 3.删除掉其中的 armv7
> > 4.回到ijkplayer-ios/ios，并执行
> > ./compile-ffmpeg.sh clean
> > ./compile-ffmpeg.sh all
> 
> 最开始，错在了---iOSDemo运行报错 "libavutil/imgutils.h" file not found ---- 然后我按照你的步骤---1.进入ijkplayer-ios/ios/compile-ffmpeg.sh 2.找到这一行 FF_ALL_ARCHS_IOS8_SDK="armv7 arm64 i386 x86_64" 3.删除掉其中的 armv7 4.回到ijkplayer-ios/ios，并执行 ./compile-ffmpeg.sh clean ./compile-ffmpeg.sh all -------，再一次执行工程，又报错了，错误是---Undefined symbols for architecture x86_64: "_inflate", referenced from: _http_read_stream in IJKMediaFramework(http.o) _rtmp_open in IJKMediaFramework(rtmpproto.o) "_uncompress", referenced from: _id3v2_read_internal in IJKMediaFramework(id3v2.o) _mov_read_cmov in IJKMediaFramework(mov.o) "_inflateInit_", referenced from: _rtmp_open in IJKMediaFramework(rtmpproto.o) "_inflateInit2_", referenced from: _http_read_header in IJKMediaFramework(http.o) "_zlibCompileFlags", referenced from: _http_read_header in IJKMediaFramework(http.o) "_inflateEnd", referenced from: _http_close in IJKMediaFramework(http.o) _http_read_header in IJKMediaFramework(http.o) _rtmp_open in IJKMediaFramework(rtmpproto.o) ld: symbol(s) not found for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation) ----

这个问题解决了吗，当时咋搞的
