### ISSUE TITLE
ape,flac不能播放

### ISSUE THREAD

**Issue by abcweihua** [Bilibili/ijkplayer#1252]
怎么支持音频ape,flac播放？能不能只编译音频部分，请指教一下

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer#before-build

**Comment by abcweihua** [comment]
能不能指教一下怎么支持ape,flac音频播放？

**Comment by yuazhen** [comment]
https://github.com/Bilibili/ijkplayer#before-build
If you prefer more codec/format
cd config
rm module.sh
ln -s module-default.sh module.sh
cd android/contrib
# cd ios
sh compile-ffmpeg clean

**Comment by DiER-WANG** [comment]
您好，请问 "cd config..." 这些操作是在 "./init-ios.sh" 命令之后操作吗？因为 "./init-ios.sh" 比较慢，还没有得到结果。

**Comment by DiER-WANG** [comment]
https://github.com/Bilibili/ijkplayer/issues/2292 @abcweihua
