### ISSUE TITLE
无网络情况下，在线视频无法seek

### ISSUE THREAD

**Issue by liyh12** [Bilibili/ijkplayer#1254]
我发现每次seek都要请求网络，如果没网，即使已经buffer过了，seek到已经buffer的区域，也不行

**Comment by yuazhen** [comment]
这应该是ffmpeg的机制就是如此，例如http协议每次seek都需要重新打开http连接来请求对于位置的数据。

**Comment by bbcallen** [comment]
FFmpeg doesn't cache anything, you need to implement custom IO by yourself.

**Comment by erwinshao** [comment]
ffmpeg本身是没有提供cache机制的，ijkpalyer上层是有buffer的，seek操作时，修改ffplay.c，seek后首先搜索下PacketQueue中缓存的数据包的pts，找到了清除掉改pts上个关键帧之前的数据包，然后设置一个flag，避免seek后进行缓冲逻辑等待缓冲，如果没有找到，再使用avformat_seek_file。

**Comment by Android4MediaPlayer** [comment]
@erwinshao 你实现了？

**Comment by erwinshao** [comment]
@Android4MediaPlayer 已经实现，验证过。git pull不方便提交，代码就贴在这里：
1、新增了3个函数：ff_seek（替换掉read_thread中的avformat_seek_file）、计算video packet queue中packet_video_queue_seek、删除packet_queue的缓存的数据包 packet_queue_delete_elements_until_by_pts；
2、PacketQueue 结构体中新增一个int64_t max_pts字段，该字段在：packet_queue_put_private中需要记录下放入queue中packet的pts值；在packet_queue_flush需要置位为0；
3、VideoState新增一个/置flag,用于跳出最大缓冲模式，避免由于删除了cache中的数据量，进入了数据缓存模式， int seek_cache;在read_thread中的((((is->seek_cache || is->audioq.size + is->videoq.size > ffp->dcc.max_buffer_size))加入改flag，并在随后的代码中置位：
if (!is->eof) {
                ffp_toggle_buffering(ffp, 0);
                is->seek_cache = 0;
            }
4、SEEK_CACHE_MIN_FRAMES = 50，用于最小要1S的数据缓存才正常播放；

/* return 0 if aborted return seek pos last key frame pts*/
static int64_t packet_video_queue_seek(PacketQueue *q, int64_t seek_pos) {
    MyAVPacketList *pkt = NULL;
    int64_t key_frame_pts = 0;

    if (q->nb_packets == 0)
        return key_frame_pts;

    pkt = q->first_pkt;
    while (pkt->next) {
        if (pkt->pkt.flags & AV_PKT_FLAG_KEY)
            key_frame_pts = pkt->pkt.pts;
        if (pkt->pkt.pts >= seek_pos)
            break;
        pkt = pkt->next;
    }

    return key_frame_pts;
}

static int ff_seek(FFPlayer *ffp) {
    int ret = 0;
    VideoState *is = ffp->is;
    //计算seek的位置
    int64_t seek_target = is->seek_pos;
    int64_t seek_timestamp = av_rescale_q(seek_target, AV_TIME_BASE_Q,
                                          is->ic->streams[is->video_stream]->time_base);
    int64_t seek_min = is->seek_rel > 0 ? seek_target - is->seek_rel + 2 : INT64_MIN;
    int64_t seek_max = is->seek_rel < 0 ? seek_target - is->seek_rel - 2 : INT64_MAX;
    int64_t current_pos = ffp_get_current_position_ext(ffp) * 1000;
    ALOGW("ff_seek seek current pos:%llu, seek pos pts:%llu, timestamp:%llu, "
                  "video cached max pts:%llu\n",
          current_pos, seek_target, seek_timestamp, is->videoq.max_pts);
    if ((ffp->packet_buffering) && (seek_target > current_pos) && (is->videoq.max_pts > seek_timestamp)) {
        int64_t video_key_frame_pts = 0;
        //计算视频cache中小余seek pos最大的一个关键帧的pts
        video_key_frame_pts = packet_video_queue_seek(&is->videoq, seek_timestamp);
        ALOGW("ff_seek found last match video key frame pts:%llu\n", video_key_frame_pts);

        if (video_key_frame_pts == 0) {
            ALOGW("ff_seek can not found last match video key frame go to file seek\n");
            goto file_seek;
        }

        //删除视频cache中关键帧pts之前的数据包
        if ((ret = packet_queue_delete_elements_until_by_pts(&is->videoq, video_key_frame_pts)) <= 0) {
            ALOGE("ff_seek error seek video cache queue ret:%d, go to file seek\n", ret);
            goto file_seek;
        }
        ALOGW("ff_seek packet_queue_delete_elements delete video element num:%d\n", ret);
        //删除音频cache关键帧pts之前的数据包
        if ((ret = packet_queue_delete_elements_until_by_pts(&is->audioq, video_key_frame_pts)) <= 0) {
            ALOGE("ff_seek error delete audio cache queue ret:%d, go to file seek\n", ret);
            goto file_seek;
        }
        ALOGW("ff_seek packet_queue_delete_elements delete audio element num:%d\n", ret);
        if (is->videoq.nb_packets > SEEK_CACHE_MIN_FRAMES)
            is->seek_cache = 1;
        return ret;
    } else {
        ALOGW("ff_seek seek not match condition(enable buffering or seek_pos < current_pos or "
                      "seek_pos > videoq->max_pts)\n");
        goto file_seek;
    }

    file_seek:
    //走文件seek,原有逻辑
    ret = avformat_seek_file(is->ic, -1, seek_min, seek_target, seek_max, is->seek_flags);
    ALOGW("ff_seek in avformat_seek_file:%d\n", ret);
    if (is->audio_stream >= 0) {
        packet_queue_flush(&is->audioq);
        packet_queue_put(&is->audioq, &flush_pkt);
    }
#ifdef FFP_MERGE
    if (is->subtitle_stream >= 0) {
                packet_queue_flush(&is->subtitleq);
                packet_queue_put(&is->subtitleq, &flush_pkt);
            }
#endif
    if (is->video_stream >= 0) {
        if (ffp->node_vdec) {
            ffpipenode_flush(ffp->node_vdec);
        }
        packet_queue_flush(&is->videoq);
        packet_queue_put(&is->videoq, &flush_pkt);
    }

    return ret;
}

static int packet_queue_delete_elements_until_by_pts(PacketQueue *q, int64_t pts) {
    MyAVPacketList *pkt = NULL;
    int delete_count = 0;

    if (q->max_pts == pts) {
        packet_queue_flush(q);
        return delete_count;
    }

    SDL_LockMutex(q->mutex);
    while (1) {
        if (q->abort_request) {
            delete_count = -1;
            break;
        }

        pkt = q->first_pkt;
        if (pkt) {
            if (pkt->pkt.pts >= pts)
                break;
            q->first_pkt = pkt->next;
            if (!q->first_pkt)
                q->last_pkt = NULL;
            q->nb_packets--;
            q->size -= pkt->pkt.size + sizeof(*pkt);
            if (pkt->pkt.duration > 0)
                q->duration -= pkt->pkt.duration;
            pkt->next = q->recycle_pkt;
            q->recycle_pkt = pkt;
            av_free_packet(&pkt->pkt);
            delete_count++;
        }
    }
    SDL_UnlockMutex(q->mutex);
    return delete_count;
}

**Comment by Android4MediaPlayer** [comment]
@erwinshao 正在使用吗？你可以在github自己的用户上传

**Comment by erwinshao** [comment]
@Android4MediaPlayer ，done，你可以看看能否merge到master上去。

**Comment by Android4MediaPlayer** [comment]
上传不完全 更改有错误的
