### ISSUE TITLE
播放地址放不出来的时候，退出Activity 报错

### ISSUE THREAD

**Issue by mw258176257** [Bilibili/ijkplayer#1255]
![image](https://cloud.githubusercontent.com/assets/3024900/14935649/83bd5ef4-0f0b-11e6-8130-d9d5bee86b63.png)

当链接播放不出来的时候，直接退出当前Activity ，执行    IjkMediaPlayer.native_profileEnd(); 时候报错

**Comment by bbcallen** [comment]
Which version were you using?
Did you build from source code, or fetch from gradle?

**Comment by mw258176257** [comment]
是最新的0.51版本，用的是：
    compile 'tv.danmaku.ijk.media:ijkplayer-java:0.5.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.5.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-exo:0.5.1'
    // Other ABIs: optional
    compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.5.1'

重现方式为：比如播放一个需要翻墙的地址，但是我现在不翻墙，然后进去他会加载中，这时我直接finish Activity 会出现这个错误

**Comment by bbcallen** [comment]
Seems you didn't call IjkMediaPlayer.loadLibrariesOnce(null), did you?

**Comment by mw258176257** [comment]
在Activity onCreate 方法中调了这个方法：
![image](https://cloud.githubusercontent.com/assets/3024900/14976166/e57ef90e-113b-11e6-9f05-1a28a30c451a.png)

**Comment by bbcallen** [comment]
There is no 'initVideo' method in example project.

**Comment by mw258176257** [comment]
sorry，我再试试，可能是我改了demo的原因。
