### ISSUE TITLE
播放rtmp直播流卡顿，且重复播放卡顿内容

### ISSUE THREAD

**Issue by iosnower** [Bilibili/ijkplayer#1256]
在播放rtmp直播出现卡顿的情况时，有时会出现多次重复的播放，卡顿发生时的那段内容。
请问这是什么原因呢，难道播放过的内容，并不会删除掉吗？

**Comment by bbcallen** [comment]
Mostly caused by server side.

**Comment by iosnower** [comment]
这也是怀疑服务端的问题，在源码中没有发现，会缓存已播放过的数据
