### ISSUE TITLE
播放一段时间后A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc24 in tid 28376 (Thread-1261)

### ISSUE THREAD

**Issue by Jucongyuan** [Bilibili/ijkplayer#1259]
05-03 15:18:37.646 26991-28383/com.wangxiaobao.adplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [28383]
05-03 15:18:37.646 26991-28379/com.wangxiaobao.adplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [28379]
05-03 15:18:37.648 26991-28374/com.wangxiaobao.adplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [28374]
05-03 15:18:37.648 26991-28375/com.wangxiaobao.adplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [28375]
05-03 15:18:37.654 26991-26991/com.wangxiaobao.adplayer I/SurfaceView: New surface: Surface(name=null)/@0x158b6cf1, vis=true, frame=Rect(0, 0 - 720, 1184), this = android.view.SurfaceView{10a67fb9 V.E..... ......ID 0,0-720,1184 #7f050007 app:id/svAd}
05-03 15:18:37.654 26991-26991/com.wangxiaobao.adplayer I/SurfaceView: surfaceRedrawNeeded, this = android.view.SurfaceView{10a67fb9 V.E..... ......ID 0,0-720,1184 #7f050007 app:id/svAd}
05-03 15:18:37.654 26991-28378/com.wangxiaobao.adplayer W/AudioTrack: releaseBuffer() track 0xb9569678 disabled due to previous underrun, restarting
05-03 15:18:37.654 26991-26991/com.wangxiaobao.adplayer I/SurfaceView: finishedDrawing, this = android.view.SurfaceView{10a67fb9 V.E..... ......ID 0,0-720,1184 #7f050007 app:id/svAd}
05-03 15:18:37.659 26991-28378/com.wangxiaobao.adplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [28378]
05-03 15:18:37.666 26991-28531/com.wangxiaobao.adplayer E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xb8afd7b8)
05-03 15:18:37.666 26991-28531/com.wangxiaobao.adplayer E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xb9498bd8)
05-03 15:18:37.667 26991-28531/com.wangxiaobao.adplayer E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xb92c5bd8)
05-03 15:18:37.667 26991-28531/com.wangxiaobao.adplayer I/IJKMEDIA: av_version_info: ff3.0--ijk0.5.0--dev0.4.5--rc11
05-03 15:18:37.668 26991-28531/com.wangxiaobao.adplayer I/IJKMEDIA: ===== versions =====
05-03 15:18:37.668 26991-28531/com.wangxiaobao.adplayer I/IJKMEDIA: FFmpeg       : ff3.0--ijk0.5.0--dev0.4.5--rc11
05-03 15:18:37.668 26991-28531/com.wangxiaobao.adplayer I/IJKMEDIA: libavutil    : 55.17.103
05-03 15:18:37.668 26991-28531/com.wangxiaobao.adplayer I/IJKMEDIA: libavcodec   : 57.24.102
05-03 15:18:37.668 26991-28531/com.wangxiaobao.adplayer I/IJKMEDIA: libavformat  : 57.25.100
05-03 15:18:37.668 26991-28531/com.wangxiaobao.adplayer I/IJKMEDIA: libswscale   : 4.0.100
05-03 15:18:37.668 26991-28531/com.wangxiaobao.adplayer I/IJKMEDIA: libswresample: 2.0.101
05-03 15:18:37.668 26991-28531/com.wangxiaobao.adplayer I/IJKMEDIA: ===== options =====
05-03 15:18:37.668 26991-28531/com.wangxiaobao.adplayer I/IJKMEDIA: format-opts : ijkinject-opaque             = 0
05-03 15:18:37.668 26991-28531/com.wangxiaobao.adplayer I/IJKMEDIA: format-opts : ijkapplication               = -1196073824
05-03 15:18:37.668 26991-28531/com.wangxiaobao.adplayer I/IJKMEDIA: ===================
05-03 15:18:37.669 26991-26991/com.wangxiaobao.adplayer I/SurfaceView: Punch a hole(dispatchDraw), w = 720, h = 1184, this = android.view.SurfaceView{10a67fb9 V.E..... ........ 0,0-720,1184 #7f050007 app:id/svAd}
05-03 15:18:37.670 26991-28533/com.wangxiaobao.adplayer I/IJKMEDIA: SDL_RunThread: [28533] ff_vout
05-03 15:18:37.670 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: SDL_RunThread: [28534] ff_read
05-03 15:18:37.670 26991-28532/com.wangxiaobao.adplayer I/IJKMEDIA: SDL_RunThread: [28532] ff_msg_loop
05-03 15:18:37.675 26991-26991/com.wangxiaobao.adplayer I/SurfaceView: updateWindow -- UPDATE_WINDOW_MSG, this = Handler (android.view.SurfaceView$1) {1c16bf57}
05-03 15:18:37.675 26991-26991/com.wangxiaobao.adplayer I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{10a67fb9 V.E..... ........ 0,0-720,1184 #7f050007 app:id/svAd}
05-03 15:18:37.684 26991-28532/com.wangxiaobao.adplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [28532]
05-03 15:18:37.702 26991-28534/com.wangxiaobao.adplayer E/IJKMEDIA: Option ijkinject-opaque not found.
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: max_frame_duration: 10.000
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/wangxiaobao/resources/o_1ahef1hfgmknp9qatal41c7gm.mp4':
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA:   Metadata:
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA:     major_brand     : 
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: isom
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA:     minor_version   : 
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: 1
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA:     compatible_brands: 
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: isomavc1
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA:     creation_time   : 
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: 2012-12-18 13:05:03
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA:   Duration: 
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: 00:00:15.14
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: , start: 
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: 0.000000
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: , bitrate: 
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: 552 kb/s
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA:     Stream #0:0
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: (und)
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: : Video: h264 (avc1 / 0x31637661), yuv420p, 672x378 [SAR 1:1 DAR 16:9], 500 kb/s
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: , 
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: 25 fps, 
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: 25 tbr, 
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: 25k tbn, 
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: 50 tbc
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA:  (default)
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA:     Metadata:
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA:       creation_time   : 
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: 2012-12-18 13:05:03
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA:       handler_name    : 
05-03 15:18:37.742 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: GPAC ISO Video Handler
05-03 15:18:37.743 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA:     Stream #0:1
05-03 15:18:37.743 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: (und)
05-03 15:18:37.743 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: : Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 48 kb/s
05-03 15:18:37.743 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA:  (default)
05-03 15:18:37.743 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA:     Metadata:
05-03 15:18:37.743 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA:       creation_time   : 
05-03 15:18:37.743 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: 2012-12-18 13:05:03
05-03 15:18:37.743 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA:       handler_name    : 
05-03 15:18:37.743 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: GPAC ISO Audio Handler
05-03 15:18:37.745 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
05-03 15:18:37.745 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: SDL_Android_AudioTrack: ENCODING_PCM_16BIT
05-03 15:18:37.749 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(1.000000,0.000000)
05-03 15:18:37.750 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: audio_session_id = 736
05-03 15:18:37.750 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: AudioCodec: avcodec, aac
05-03 15:18:37.750 26991-28537/com.wangxiaobao.adplayer I/IJKMEDIA: SDL_RunThread: [28537] ff_aout_android
05-03 15:18:37.752 26991-28538/com.wangxiaobao.adplayer I/IJKMEDIA: SDL_RunThread: [28538] ff_audio_dec
05-03 15:18:37.755 26991-28534/com.wangxiaobao.adplayer I/IJKMEDIA: VideoCodec: avcodec, h264
05-03 15:18:37.756 26991-28534/com.wangxiaobao.adplayer W/IJKMEDIA: fps: 25.000000 (normal)
05-03 15:18:37.756 26991-28534/com.wangxiaobao.adplayer W/IJKMEDIA: fps: 25.000000 (normal)
05-03 15:18:37.766 26991-28544/com.wangxiaobao.adplayer I/IJKMEDIA: SDL_RunThread: [28544] ff_video_dec
05-03 15:18:37.778 26991-26991/com.wangxiaobao.adplayer I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{10a67fb9 V.E..... ........ 0,0-720,1184 #7f050007 app:id/svAd}
05-03 15:18:37.863 26991-26991/com.wangxiaobao.adplayer I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{10a67fb9 V.E..... ........ 0,0-720,1184 #7f050007 app:id/svAd}
05-03 15:18:37.883 26991-26991/com.wangxiaobao.adplayer I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{10a67fb9 V.E..... ........ 0,0-720,1184 #7f050007 app:id/svAd}
05-03 15:18:37.989 26991-26991/com.wangxiaobao.adplayer I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{10a67fb9 V.E..... ........ 0,0-720,1184 #7f050007 app:id/svAd}
05-03 15:18:38.096 26991-26991/com.wangxiaobao.adplayer I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{10a67fb9 V.E..... ........ 0,0-720,1184 #7f050007 app:id/svAd}
05-03 15:18:38.202 26991-26991/com.wangxiaobao.adplayer I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{10a67fb9 V.E..... ........ 0,0-720,1184 #7f050007 app:id/svAd}
05-03 15:18:38.309 26991-26991/com.wangxiaobao.adplayer I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{10a67fb9 V.E..... ........ 0,0-720,1184 #7f050007 app:id/svAd}
05-03 15:18:38.414 26991-26991/com.wangxiaobao.adplayer I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{10a67fb9 V.E..... ........ 0,0-720,1184 #7f050007 app:id/svAd}
05-03 15:18:38.510 26991-28376/com.wangxiaobao.adplayer A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc24 in tid 28376 (Thread-1261)
05-03 15:18:38.520 26991-26991/com.wangxiaobao.adplayer I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{10a67fb9 V.E..... ........ 0,0-720,1184 #7f050007 app:id/svAd}

**Comment by Jucongyuan** [comment]
程序崩溃就这一段日志A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc24 in tid 28376 (Thread-1261)

**Comment by bbcallen** [comment]
Sorry, nothing I can do with this single line.

**Comment by Jucongyuan** [comment]
E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19

**Comment by Jucongyuan** [comment]
05-15 18:28:59.164    6046-6372/com.wangxiaobao.adplayer I/IJKMEDIA﹕ SDL_JNI_DetachThreadEnv: [6372]
05-15 18:28:59.164    6046-6368/com.wangxiaobao.adplayer I/IJKMEDIA﹕ SDL_JNI_DetachThreadEnv: [6368]
05-15 18:28:59.165    6046-6362/com.wangxiaobao.adplayer I/IJKMEDIA﹕ SDL_JNI_DetachThreadEnv: [6362]
05-15 18:28:59.165    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ surfaceChanged callback -, this = android.view.SurfaceView{20990fe0 V.E..... ......ID 0,0-720,1230 #7f060003 app:id/svAd}
05-15 18:28:59.166    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ surfaceRedrawNeeded, this = android.view.SurfaceView{20990fe0 V.E..... ......ID 0,0-720,1230 #7f060003 app:id/svAd}
05-15 18:28:59.166    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ finishedDrawing, this = android.view.SurfaceView{20990fe0 V.E..... ......ID 0,0-720,1230 #7f060003 app:id/svAd}
05-15 18:28:59.168    6046-6367/com.wangxiaobao.adplayer W/AudioTrack﹕ releaseBuffer() track 0xb9319300 disabled due to previous underrun, restarting
05-15 18:28:59.171    6046-6367/com.wangxiaobao.adplayer I/IJKMEDIA﹕ SDL_JNI_DetachThreadEnv: [6367]
05-15 18:28:59.173    6046-6363/com.wangxiaobao.adplayer I/IJKMEDIA﹕ SDL_JNI_DetachThreadEnv: [6363]
05-15 18:28:59.174    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ updateWindow -- OnScrollChangedListener, this = android.view.SurfaceView$2@2b30525b
05-15 18:28:59.174    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ Changes: creating=false format=false size=false visible=false left=false top=false mUpdateWindowNeeded=true mReportDrawNeeded=true redrawNeeded=false forceSizeChanged=false mVisible=true mRequestedVisible=true, this = android.view.SurfaceView{3cc83047 V.E..... ......ID 0,0-720,1230 #7f060003 app:id/svAd}
05-15 18:28:59.174    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ Cur surface: Surface(name=null)/@0x1b44e13f, this = android.view.SurfaceView{3cc83047 V.E..... ......ID 0,0-720,1230 #7f060003 app:id/svAd}
05-15 18:28:59.182    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ New surface: Surface(name=null)/@0xeaf4a0c, vis=true, frame=Rect(720, 50 - 1440, 1280), this = android.view.SurfaceView{3cc83047 V.E..... ......ID 0,0-720,1230 #7f060003 app:id/svAd}
05-15 18:28:59.183    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ surfaceRedrawNeeded, this = android.view.SurfaceView{3cc83047 V.E..... ......ID 0,0-720,1230 #7f060003 app:id/svAd}
05-15 18:28:59.183    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ finishedDrawing, this = android.view.SurfaceView{3cc83047 V.E..... ......ID 0,0-720,1230 #7f060003 app:id/svAd}
05-15 18:28:59.185    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ updateWindow -- OnScrollChangedListener, this = android.view.SurfaceView$2@2a0cfaf8
05-15 18:28:59.185    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ Changes: creating=false format=false size=false visible=false left=false top=false mUpdateWindowNeeded=true mReportDrawNeeded=true redrawNeeded=false forceSizeChanged=false mVisible=true mRequestedVisible=true, this = android.view.SurfaceView{20990fe0 V.E..... ......ID 0,0-720,1230 #7f060003 app:id/svAd}
05-15 18:28:59.185    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ Cur surface: Surface(name=null)/@0x3a7a5f55, this = android.view.SurfaceView{20990fe0 V.E..... ......ID 0,0-720,1230 #7f060003 app:id/svAd}
05-15 18:28:59.190    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ New surface: Surface(name=null)/@0x3fe4ad6a, vis=true, frame=Rect(0, 50 - 720, 1280), this = android.view.SurfaceView{20990fe0 V.E..... ......ID 0,0-720,1230 #7f060003 app:id/svAd}
05-15 18:28:59.190    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ surfaceRedrawNeeded, this = android.view.SurfaceView{20990fe0 V.E..... ......ID 0,0-720,1230 #7f060003 app:id/svAd}
05-15 18:28:59.190    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ finishedDrawing, this = android.view.SurfaceView{20990fe0 V.E..... ......ID 0,0-720,1230 #7f060003 app:id/svAd}
05-15 18:28:59.197    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ Punch a hole(dispatchDraw), w = 720, h = 1230, this = android.view.SurfaceView{20990fe0 V.E..... ........ 0,0-720,1230 #7f060003 app:id/svAd}
05-15 18:28:59.198    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ updateWindow -- UPDATE_WINDOW_MSG, this = Handler (android.view.SurfaceView$1) {2fce9bd1}
05-15 18:28:59.198    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ updateWindow -- UPDATE_WINDOW_MSG, this = Handler (android.view.SurfaceView$1) {23183636}
05-15 18:28:59.216    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{3cc83047 V.E..... ......ID 0,0-720,1230 #7f060003 app:id/svAd}
05-15 18:28:59.216    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{20990fe0 V.E..... ........ 0,0-720,1230 #7f060003 app:id/svAd}
05-15 18:28:59.217    6046-6046/com.wangxiaobao.adplayer I/SurfaceView﹕ Punch a hole(dispatchDraw), w = 720, h = 1230, this = android.view.SurfaceView{3cc83047 V.E..... ........ 0,0-720,1230 #7f060003 app:id/svAd}
05-15 18:28:59.219    6046-7019/com.wangxiaobao.adplayer E/IJKMEDIA﹕ SDL_Overlay(ffmpeg): overlay_free_l(0xb8f57328)
05-15 18:28:59.219    6046-7019/com.wangxiaobao.adplayer E/IJKMEDIA﹕ SDL_Overlay(ffmpeg): overlay_free_l(0xb8f43608)
05-15 18:28:59.220    6046-7019/com.wangxiaobao.adplayer E/IJKMEDIA﹕ SDL_Overlay(ffmpeg): overlay_free_l(0xb8f19860)
05-15 18:28:59.221    6046-7019/com.wangxiaobao.adplayer I/IJKMEDIA﹕ av_version_info: ff3.0--ijk0.5.0--dev0.4.5--rc11
05-15 18:28:59.221    6046-7019/com.wangxiaobao.adplayer I/IJKMEDIA﹕ ===== versions =====
05-15 18:28:59.221    6046-7019/com.wangxiaobao.adplayer I/IJKMEDIA﹕ FFmpeg       : ff3.0--ijk0.5.0--dev0.4.5--rc11
05-15 18:28:59.221    6046-6364/com.wangxiaobao.adplayer A/libc﹕ Fatal signal 11 (SIGSEGV), code 1, fault addr 0x4 in tid 6364 (Thread-961)
05-15 18:28:59.221    6046-7019/com.wangxiaobao.adplayer I/IJKMEDIA﹕ libavutil    : 55.17.103
05-15 18:28:59.221    6046-7019/com.wangxiaobao.adplayer I/IJKMEDIA﹕ libavcodec   : 57.24.102
05-15 18:28:59.221    6046-7019/com.wangxiaobao.adplayer I/IJKMEDIA﹕ libavformat  : 57.25.100
05-15 18:28:59.221    6046-7019/com.wangxiaobao.adplayer I/IJKMEDIA﹕ libswscale   : 4.0.100
05-15 18:28:59.221    6046-7019/com.wangxiaobao.adplayer I/IJKMEDIA﹕ libswresample: 2.0.101
05-15 18:28:59.221    6046-7019/com.wangxiaobao.adplayer I/IJKMEDIA﹕ ===== options =====
05-15 18:28:59.221    6046-7019/com.wangxiaobao.adplayer I/IJKMEDIA﹕ format-opts : ijkinject-opaque             = 0
05-15 18:28:59.221    6046-7019/com.wangxiaobao.adplayer I/IJKMEDIA﹕ format-opts : ijkapplication               = -1190347472
05-15 18:28:59.221    6046-7019/com.wangxiaobao.adplayer I/IJKMEDIA﹕ ===================
05-15 18:28:59.222    6046-7022/com.wangxiaobao.adplayer I/IJKMEDIA﹕ SDL_RunThread: [7022] ff_msg_loop
05-15 18:28:59.226    6046-7022/com.wangxiaobao.adplayer I/IJKMEDIA﹕ SDL_JNI_DetachThreadEnv: [7022]
05-15 18:28:59.228    6046-7024/com.wangxiaobao.adplayer I/IJKMEDIA﹕ SDL_RunThread: [7024] ff_vout
05-15 18:28:59.228    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ SDL_RunThread: [7025] ff_read
05-15 18:28:59.241    6046-7025/com.wangxiaobao.adplayer E/IJKMEDIA﹕ Option ijkinject-opaque not found.
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ max_frame_duration: 10.000
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/wangxiaobao/resources/o_1aimsdkgk1gta17om1mtllvo1m819.mp4':
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ Metadata:
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ major_brand     :
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ isom
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ [ 05-15 18:28:59.264  6046: 7025 I/IJKMEDIA ]
    minor_version   :
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ 1
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ [ 05-15 18:28:59.264  6046: 7025 I/IJKMEDIA ]
    compatible_brands:
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ isomavc1
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ [ 05-15 18:28:59.264  6046: 7025 I/IJKMEDIA ]
    creation_time   :
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ 2014-06-09 14:29:33
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ [ 05-15 18:28:59.264  6046: 7025 I/IJKMEDIA ]
    Duration:
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ 00:00:30.00
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ , start:
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ 0.000000
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ , bitrate:
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ 556 kb/s
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ [ 05-15 18:28:59.264  6046: 7025 I/IJKMEDIA ]
    Stream #0:0
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ (und)
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ : Video: h264 (avc1 / 0x31637661), yuv420p, 672x378 [SAR 1:1 DAR 16:9], 506 kb/s
05-15 18:28:59.264    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ ,
05-15 18:28:59.265    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ 25 fps,
05-15 18:28:59.265    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ 25 tbr,
05-15 18:28:59.265    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ 25k tbn,
05-15 18:28:59.265    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ 50 tbc
05-15 18:28:59.265    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ (default)
05-15 18:28:59.265    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ [ 05-15 18:28:59.265  6046: 7025 I/IJKMEDIA ]
    Metadata:
05-15 18:28:59.265    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ creation_time   :
05-15 18:28:59.265    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ 2014-06-09 14:29:33
05-15 18:28:59.265    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ [ 05-15 18:28:59.265  6046: 7025 I/IJKMEDIA ]
    handler_name    :
05-15 18:28:59.265    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ GPAC ISO Video Handler
05-15 18:28:59.265    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ [ 05-15 18:28:59.265  6046: 7025 I/IJKMEDIA ]
    Stream #0:1
05-15 18:28:59.265    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ (und)
05-15 18:28:59.265    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ : Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 47 kb/s
05-15 18:28:59.265    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ (default)
05-15 18:28:59.265    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ [ 05-15 18:28:59.265  6046: 7025 I/IJKMEDIA ]
    Metadata:
05-15 18:28:59.265    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ creation_time   :
05-15 18:28:59.265    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ 2014-06-09 14:29:33
05-15 18:28:59.265    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ [ 05-15 18:28:59.265  6046: 7025 I/IJKMEDIA ]
    handler_name    :
05-15 18:28:59.265    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ GPAC ISO Audio Handler
05-15 18:28:59.265    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ [ 05-15 18:28:59.267  6046: 7025 I/IJKMEDIA ]
    SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
05-15 18:28:59.267    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ SDL_Android_AudioTrack: ENCODING_PCM_16BIT
05-15 18:28:59.271    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(1.000000,0.000000)
05-15 18:28:59.271    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ audio_session_id = 408
05-15 18:28:59.272    6046-7025/com.wangxiaobao.adplayer I/IJKMEDIA﹕ AudioCodec: avcodec, aac
05-15 18:28:59.272    6046-7027/com.wangxiaobao.adplayer I/IJKMEDIA﹕ SDL_RunThread: [7027] ff_aout_android
05-15 18:28:59.272    6046-7028/com.wangxiaobao.adplayer I/IJKMEDIA﹕ SDL_RunThread: [7028] ff_audio_dec

**Comment by bbcallen** [comment]
Remove your logcal filter, show all logs.
Or just run 'adb logcat'

**Comment by bravekingzhang** [comment]
请问下 ，@Jucongyuan 这个问题你解决了没有

**Comment by kukudelingyu** [comment]
请问如何获得详细的日志，我的logcat里只有02-24 15:53:59.789: A/libc(11909): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 11909    这一行
