### ISSUE TITLE
How to seek from particular position in streaming data 

### ISSUE THREAD

**Issue by anisattar** [Bilibili/ijkplayer#126]
Hi,
I want to know how to seek from a particular position,if I know the postion to seek from streaming server.
I don't want to read(av_read_frame) till the seek posion.
It will be helpful if you provide the details.

In our current implementation,If I seek to middle of the streaming data it's taking too much of time to seek..
After Analyzing the code I found that,it is reading the buffer from begining of the stream if it doesn't found the index from the index entries table,so it's waiting till that time..

Please let me know if there is any solution to seek to a particular position without reading from the beginning of the stream.

Thanks,

**Comment by flybird119** [comment]
I had the same problem, did you resolved it? @anisattar

**Comment by bbcallen** [comment]
When you use AVSEEK_FLAG_BYTE, you must also pass the position in bytes, but not time unit
