### ISSUE TITLE
How can ijkplayer support separate audio/video inputs and output as a single video

### ISSUE THREAD

**Issue by yangjiheng** [Bilibili/ijkplayer#1262]
@bbcallen , first of all, great work wrapping this player, one of the best I have ever seen.

My questions is whether it's possible to use ijkplayer take two URIs which could from a local file input or a network stream (one containing only video track, the other containing only audio track, and their PTS/DTS is perfectly aligned), to play as a merged video stream (video from the video URI and audio from the audio URI, synced). 

I know in ffmpeg, it's possible to take two input files, and use map instruction to output into one single file. Although when I tested the feature, the output video is not guaranteed to be in correct AV sync. But it could be my mistake using the commands.

Thanks again for the great work and the incoming help in advance.

**Comment by bbcallen** [comment]
AFAICT，No.
But you can DIY by modify ff_ffplay.c

**Comment by yangjiheng** [comment]
OK, I see. Let me check whether it's doable. Thanks for the reply. Again, great work!

**Comment by spaul13** [comment]
@yangjiheng and @bbcallen  can you please tell me what is exactly decoder input is it a video file or a single frame?

How can I give a single frame to the decoder (ijkplayer) and see what the output? I just want to have a standalone version of the decoder. Can you help me by giving ideas how to implement it?

**Comment by spaul13** [comment]
> OK, I see. Let me check whether it's doable. Thanks for the reply. Again, great work!

@yangjiheng did u successfully achieve this. If yes plz tell me how to achieve this.
