### ISSUE TITLE
播放器释放不了，内存溢出了

### ISSUE THREAD

**Issue by luojinfang** [Bilibili/ijkplayer#1263]
![qq 20160504213404](https://cloud.githubusercontent.com/assets/12162831/15015727/2bd4f390-1240-11e6-918b-06cac9cdcfe4.png)

**Comment by luojinfang** [comment]
05-04 21:37:36.095 5175-5175 E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/data/com.sohu.inputmethod.sogou/files/.theme/sogou/res/composing_bg.png: open failed: ENOENT (No such file or directory)
05-04 21:37:36.096 5175-5175 E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/data/com.sohu.inputmethod.sogou/files/.theme/sogou/res/composing_bg.png: open failed: ENOENT (No such file or directory)

**Comment by dazhiyu** [comment]
怎么关了，是解决了吗，是怎么解决的？求解

**Comment by luojinfang** [comment]
解决了  是另外的问题  不是播放器的问题
