### ISSUE TITLE
缓冲条的问题，onBufferingUpdate

### ISSUE THREAD

**Issue by naibbian** [Bilibili/ijkplayer#1264]
播放网络视频，在视频比较小的时候，onBufferingUpdate，更新的频率过快，导致无法完成到100%，缓冲条无法完全显示到结束位置；
这儿问题怎么解呢，求帮助！

**Comment by bbcallen** [comment]
There is no guarantee it will post the 100% buffering message.
You should listen MEDIA_INFO_BUFFERING_START, MEDIA_INFO_BUFFERING_END

**Comment by a3349384** [comment]
@bbcallen MEDIA_INFO_BUFFERING_END may never be called.

**Comment by cuiqing168** [comment]
@a3349384 me too
