### ISSUE TITLE
视频获取不到宽高，播放只有声音没有图像

### ISSUE THREAD

**Issue by songwensw** [Bilibili/ijkplayer#1265]
视频获取不到宽高，播放只有声音没有图像
视频地址：http://quahtvdata.bj116.com/1462344549000dzl225393.mp4

**Comment by luojinfang** [comment]
这个也是：http://rs.qipaoxian.com/mp4/poem/p006.mp4
只有声音没有图像

**Comment by songwensw** [comment]
我看了 2个视频都是mpeg-4，有可能没有解码器，我正在重新编译支持比较多格式的，一会试试看能行不

**Comment by luojinfang** [comment]
嗯  应该是解码的问题，我也去重新编译一下看看

**Comment by songwensw** [comment]
重新编译支持较多格式的就可以播放了~

**Comment by zcwfeng** [comment]
网页也播不了
Re:视频获取不到宽高，播放只有声音没有图像
视频地址：http://quahtvdata.bj116.com/1462344549000dzl225393.mp4

**Comment by Android4MediaPlayer** [comment]
可以的

**Comment by yhq-iOS** [comment]
@songwensw 请问如何支持多种格式？帮忙解答下 谢谢🙏
