### ISSUE TITLE
ijk如何播放本地资源文件夹的视频？如何播放下载到本地的M3U8的视频？

### ISSUE THREAD

**Issue by LuckLe** [Bilibili/ijkplayer#1267]
有谁知道的，给个思路，谢谢。

**Comment by Android4MediaPlayer** [comment]
1.加个代理服务器；
2.可能要修改ffmpeg，HLS协议也支持取本地即可

**Comment by liuhy412484577** [comment]
我播放本地m3u8 文件，如下
#EXTM3U
#EXT-X-TARGETDURATION:30
#EXT-X-VERSION:3
#EXTINF:7,
http:/127.0.0.1:12345/Downloads/Video/31822/id0.ts
#EXTINF:27.64,
http:/127.0.0.1:12345/Downloads/Video/31822/id1.ts
#EXTINF:34.52,
http:/127.0.0.1:12345/Downloads/Video/31822/id2.ts
#EXTINF:25.56,
地址中少了一个/ ,导致播放的时候，每个片段的地址：
http://127.0.0.1:12345/Downloads/Video/31822/http:/127.0.0.1:12345/Downloads/Video/31822/id11.ts
请问，设置那里可以不让他拼接啊？
