### ISSUE TITLE
android 播放器切换 出错

### ISSUE THREAD

**Issue by NoGirlFriendException** [Bilibili/ijkplayer#1268]
用的是官方提供的最新demo
我在播放过程中进行播放器内核切换.
代码是这样修改的
我修改了VideoActivity的 onOptionsItemSelected中的点击监听. 在点击的时候切换播放器
代码是这样
 if (id == R.id.action_toggle_player) { 
            if (mSettings.getPlayer() == 1 || mSettings.getPlayer() == 0) {
                mSettings.setPlayer(2);
            } else if (mSettings.getPlayer() == 2) {
                mSettings.setPlayer(3);
            } else if (mSettings.getPlayer() == 3) {
                mSettings.setPlayer(1);
            }
            int player = mVideoView.togglePlayer();
            String playerText = IjkVideoView.getPlayerText(this, player);
            mToastTextView.setText(playerText);
            mMediaController.showOnce(mToastTextView);
            return true;
        }

如果是exo 源生播放器 互相切换 或者切到ijkPlayer 都是没任何问题的
但是一旦从ijkplayer播放器 切换到 源生播放器和exo播放器
就无法正常使用了.
ijkplayer -> exoPlayer  exo播放器会报出这个异常 com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.AVC.Decoder, MediaFormat(1, video/avc, -1, 73633, 1280, 720, 0, 1.0, -1, -1, null, 247470000, false, -1, -1, -1, -1)
ijkplayer -->源生播放器的话 到是不会报异常 但是会出现无法正常播放的情况

**Comment by Android4MediaPlayer** [comment]
你是怎么做切换的

**Comment by NoGirlFriendException** [comment]
@Android4MediaPlayer 改变setting 里的 播放器 type 然后调用  mVideoView.togglePlayer(); 
这样切换的

**Comment by bbcallen** [comment]
It's a known issue, but somehow hard to fix in current implement.

**Comment by NoGirlFriendException** [comment]
@Android4MediaPlayer @bbcallen 
这个问题好像是 ijkPlayer release的时候 并不能完全 解除与 SurfaceView的联系
导致后续的播放器都不能正常使用, 报出[SurfaceView] connect: already connected 的错误。
我做了一个workAround 解决了这个问题.
就是判断了下 lastPlayer 如果是ijkplayer 我就重新调用一次 setRender. 
重新设置了1下 renderView 就可以了

后面的朋友如果有遇见这种问题 可以参考下我的思路.
