### ISSUE TITLE
https 的视频播放地址无法播放

### ISSUE THREAD

**Issue by jingcai-wei** [Bilibili/ijkplayer#1269]
自己在播放Youtube上面的视频时，播放地址为https 的视频播放地址无法播放。  请问下这个问题要怎么解决？

**Comment by jingcai-wei** [comment]
https://r8---sn-a5m7ln76.googlevideo.com/videoplayback?key=cms1&id=6c575b2f75b3a724&sparams=dur,expire,id,initcwndbps,ip,ipbits,ipbypass,itag,lmt,mime,mm,mn,ms,mv,nh,pcm2cms,pl,ratebypass,requiressl,source,upn&ip=104.250.131.73&signature=5F4715C646EC22B041013B52801203B8727FDF6F.23FF61C81CFBEE544BB012DFD3CCBF5CA784321E&fexp=9405963%2C9408214%2C9413138%2C9416126%2C9416891%2C9422596%2C9428398%2C9428769%2C9429987%2C9431012%2C9431522%2C9431675%2C9432683%2C9433096%2C9433184%2C9433946%2C9434213%2C9434604%2C9434760%2C9435850%2C9436013&ratebypass=yes&mime=video%2Fmp4&requiressl=yes&expire=1462459045&sver=3&dur=277.432&ipbits=0&lmt=1461744985609538&itag=22&pl=23&source=youtube&upn=Wa1hQJnmMF0&req_id=659def6467e6a3ee&redirect_counter=2&cms_redirect=yes&ipbypass=yes&mm=30&mn=sn-a5m7ln76&ms=nxu&mt=1462437953&mv=u&nh=IgpwcjAxLmxheDAyKgkxMjcuMC4wLjE  这个是播放地址。

**Comment by Android4MediaPlayer** [comment]
要编译带openssl

**Comment by bbcallen** [comment]
Build FFmpeg with OpenSSL support.

**Comment by jingcai-wei** [comment]
@Android4MediaPlayer @bbcallen 了解，谢谢。
