### ISSUE TITLE
Using local socket to play a video takes about 4-5 secs to start playback.

### ISSUE THREAD

**Issue by goldenpointer** [Bilibili/ijkplayer#1273]
I am using a local socket connection to the player to play the received live video(passing the FileDescriptor)

` public void setDataSource(FileDescriptor fd)`

This works fine but there is an initial delay of 4-5 secs, for the playback to actually start.( It displays black screen for the initial 4-5 secs.) 

I have disabled ijkplayer buffering.

11-23 08:14:57.528    2530-2530/  D/J4A﹕ J4ALoader: OK: 'tv.danmaku.ijk.media.player.IjkMediaPlayer' loaded
11-23 08:14:57.558    2530-2530/  D/IJKMEDIA﹕ IjkMediaPlayer_native_profileBegin
11-23 08:14:57.558    2530-2530/  D/IJKMEDIA﹕ monstartup: libijkplayer.so
11-23 08:14:57.618    2530-2530/  D/IJKMEDIA﹕ IjkMediaPlayer_native_init
11-23 08:14:57.618    2530-2530/  D/IJKMEDIA﹕ IjkMediaPlayer_native_setup
11-23 08:14:57.618    2530-2530/  I/IJKMEDIA﹕ av_version_info: ff2.8--ijk0.4.4.1--dev0.3.3--rc7
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ ffpipeline_create_from_android()
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ ijkmp_set_inject_opaque(0x1d2004ce)
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ ijkmp_set_inject_opaque()=void
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ ijkmp_android_set_mediacodec_select_callback()
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ ffpipeline_set_mediacodec_select_callback
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ ijkmp_android_set_mediacodec_select_callback()=void
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ IjkMediaPlayer_native_setLogLevel(3)
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ moncleanup
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ IjkMediaPlayer_setOptionLong
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ IjkMediaPlayer_setOptionLong
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ IjkMediaPlayer_setOptionLong
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ IjkMediaPlayer_setOptionLong
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ IjkMediaPlayer_setOptionLong
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ IjkMediaPlayer_setOption
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ IjkMediaPlayer_setOptionLong
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ IjkMediaPlayer_setDataSourceFd
11-23 08:14:57.628    2530-2530/  V/IJKMEDIA﹕ setDataSourceFd: dup(79)=80
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ ijkmp_set_data_source(url="pipe:80")
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ ijkmp_set_data_source(url="pipe:80")=0
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ IjkMediaPlayer_setVideoSurface
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0x48c0001d)
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ ffpipeline_set_surface()
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0x48c0001d)=void
11-23 08:14:57.628    2530-2530/  W/tv.danmaku.ijk.media.player.IjkMediaPlayer﹕ setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ IjkMediaPlayer_prepareAsync
11-23 08:14:57.628    2530-2530/  D/IJKMEDIA﹕ ijkmp_prepare_async()
11-23 08:14:57.628    2530-2530/  I/IJKMEDIA﹕ ===== versions =====
11-23 08:14:57.628    2530-2530/  I/IJKMEDIA﹕ FFmpeg       : ff2.8--ijk0.4.4.1--dev0.3.3--rc7
11-23 08:14:57.628    2530-2847/  I/IJKMEDIA﹕ SDL_RunThread: [2847] ff_msg_loop
11-23 08:14:57.628    2530-2847/  D/IJKMEDIA﹕ message_loop
11-23 08:14:57.628    2530-2530/  I/IJKMEDIA﹕ libavutil    : 54.31.100
11-23 08:14:57.628    2530-2530/  I/IJKMEDIA﹕ libavcodec   : 56.60.100
11-23 08:14:57.628    2530-2530/  I/IJKMEDIA﹕ libavformat  : 56.40.101
11-23 08:14:57.628    2530-2530/  I/IJKMEDIA﹕ libswscale   : 3.1.101
11-23 08:14:57.628    2530-2530/  I/IJKMEDIA﹕ libswresample: 1.2.101
11-23 08:14:57.628    2530-2530/  I/IJKMEDIA﹕ ===== options =====
11-23 08:14:57.628    2530-2530/  I/IJKMEDIA﹕ player-opts : mediacodec                   = 0
11-23 08:14:57.628    2530-2530/  I/IJKMEDIA﹕ player-opts : opensles                     = 0
11-23 08:14:57.628    2530-2530/  I/IJKMEDIA﹕ player-opts : overlay-format               = 842225234
11-23 08:14:57.628    2530-2530/  I/IJKMEDIA﹕ player-opts : framedrop                    = 1
11-23 08:14:57.628    2530-2530/  I/IJKMEDIA﹕ player-opts : start-on-prepared            = 1
11-23 08:14:57.628    2530-2530/  I/IJKMEDIA﹕ player-opts : fflags                       = nobuffer
11-23 08:14:57.628    2530-2530/  I/IJKMEDIA﹕ format-opts : ijkinject-opaque             = 488637646
11-23 08:14:57.628    2530-2530/  I/IJKMEDIA﹕ codec-opts  : skip_loop_filter             = 48
11-23 08:14:57.628    2530-2530/  I/IJKMEDIA﹕ ===================
11-23 08:14:57.638    2530-2847/  D/IJKMEDIA﹕ FFP_MSG_FLUSH:
11-23 08:14:57.648    2530-2530/  D/IJKMEDIA﹕ ijkmp_prepare_async()=0
11-23 08:14:57.648    2530-2857/  I/IJKMEDIA﹕ SDL_RunThread: [2857] ff_vout
11-23 08:14:57.648    2530-2858/  I/IJKMEDIA﹕ SDL_RunThread: [2858] ff_read
11-23 08:14:57.658    2530-2858/  D/IJKMEDIA﹕ Format mpegts probed with size=2048 and score=100
11-23 08:14:57.668    2530-2858/  D/IJKMEDIA﹕ stream=0 stream_type=1b pid=1e1 prog_reg_desc=
11-23 08:14:57.668    2530-2858/  E/IJKMEDIA﹕ Option ijkinject-opaque not found.
11-23 08:14:57.668    2530-2858/  D/IJKMEDIA﹕ Before avformat_find_stream_info() pos: 0 bytes read:55046 seeks:0
11-23 08:14:57.718    2530-2858/  I/IJKMEDIA﹕ Current profile doesn't provide more RBSP data in PPS, skipping
11-23 08:14:57.758    2530-2858/  D/IJKMEDIA﹕ Continuity check failed for pid 481 expected 4 got 6
11-23 08:14:57.758    2530-2858/  W/IJKMEDIA﹕ PES packet size mismatch
11-23 08:14:57.768    2530-2858/  E/IJKMEDIA﹕ left block unavailable for requested intra mode at 0 18
11-23 08:14:57.768    2530-2858/  E/IJKMEDIA﹕ error while decoding MB 0 18
11-23 08:14:57.768    2530-2858/  I/IJKMEDIA﹕ concealing 529 DC, 529 AC, 529 MV errors in P frame
11-23 08:14:57.778    2530-2858/  D/IJKMEDIA﹕ Continuity check failed for pid 481 expected 10 got 0
11-23 08:14:57.778    2530-2858/  W/IJKMEDIA﹕ PES packet size mismatch
11-23 08:14:57.788    2530-2858/  D/IJKMEDIA﹕ Continuity check failed for pid 481 expected 0 got 11
11-23 08:14:57.788    2530-2858/  W/IJKMEDIA﹕ PES packet size mismatch
11-23 08:14:57.878    2530-2858/  D/IJKMEDIA﹕ Continuity check failed for pid 481 expected 11 got 2
11-23 08:14:57.878    2530-2858/  W/IJKMEDIA﹕ PES packet size mismatch
11-23 08:14:58.158    2530-2858/  D/IJKMEDIA﹕ Continuity check failed for pid 481 expected 11 got 13
11-23 08:14:58.158    2530-2858/  W/IJKMEDIA﹕ PES packet size mismatch
11-23 08:14:58.658    2530-2858/  D/IJKMEDIA﹕ Continuity check failed for pid 481 expected 4 got 11
11-23 08:14:58.668    2530-2858/  W/IJKMEDIA﹕ PES packet size mismatch
11-23 08:14:58.668    2530-2858/  D/IJKMEDIA﹕ Continuity check failed for pid 481 expected 3 got 10
11-23 08:14:58.678    2530-2858/  W/IJKMEDIA﹕ PES packet size mismatch
11-23 08:14:59.128    2530-2858/  D/IJKMEDIA﹕ Continuity check failed for pid 481 expected 0 got 6
11-23 08:14:59.128    2530-2858/  W/IJKMEDIA﹕ PES packet size mismatch
11-23 08:14:59.128    2530-2858/  D/IJKMEDIA﹕ Continuity check failed for pid 481 expected 6 got 13
11-23 08:14:59.128    2530-2858/  W/IJKMEDIA﹕ PES packet size mismatch
11-23 08:14:59.168    2530-2858/  D/IJKMEDIA﹕ Continuity check failed for pid 481 expected 11 got 2
11-23 08:14:59.188    2530-2858/  W/IJKMEDIA﹕ PES packet size mismatch
11-23 08:14:59.208    2530-2858/  D/IJKMEDIA﹕ Continuity check failed for pid 481 expected 15 got 6
11-23 08:14:59.208    2530-2858/  W/IJKMEDIA﹕ PES packet size mismatch
11-23 08:14:59.318    2530-2858/  D/IJKMEDIA﹕ Continuity check failed for pid 481 expected 13 got 4
11-23 08:14:59.318    2530-2858/  W/IJKMEDIA﹕ PES packet size mismatch
11-23 08:14:59.318    2530-2858/  D/IJKMEDIA﹕ Continuity check failed for pid 481 expected 7 got 15
11-23 08:14:59.438    2530-2858/  D/IJKMEDIA﹕ Continuity check failed for pid 481 expected 12 got 2
11-23 08:14:59.438    2530-2858/  D/IJKMEDIA﹕ Continuity check failed for pid 481 expected 7 got 13
11-23 08:14:59.448    2530-2858/  W/IJKMEDIA﹕ PES packet size mismatch
11-23 08:14:59.448    2530-2858/  I/IJKMEDIA﹕ max_analyze_duration 5000000 reached at 5037200 microseconds st:0
11-23 08:14:59.448    2530-2858/  D/IJKMEDIA﹕ rfps: 24.000000 0.000916
11-23 08:14:59.448    2530-2858/  D/IJKMEDIA﹕ rfps: 24.083333 0.008511
11-23 08:14:59.448    2530-2858/  D/IJKMEDIA﹕ rfps: 24.083333 0.008511
11-23 08:14:59.448    2530-2858/  D/IJKMEDIA﹕ rfps: 48.000000 0.003665
11-23 08:14:59.448    2530-2858/  D/IJKMEDIA﹕ rfps: 23.976024 0.004264
11-23 08:14:59.448    2530-2858/  D/IJKMEDIA﹕ rfps: 23.976024 0.010632
11-23 08:14:59.448    2530-2858/  D/IJKMEDIA﹕ rfps: 47.952048 0.017056
11-23 08:14:59.448    2530-2858/  D/IJKMEDIA﹕ After avformat_find_stream_info() pos: 665478 bytes read:675590 seeks:0 frames:121
11-23 08:14:59.448    2530-2858/  I/IJKMEDIA﹕ max_frame_duration: 10.000
11-23 08:14:59.448    2530-2858/  I/IJKMEDIA﹕ Input #0, mpegts, from 'pipe:80':
11-23 08:14:59.448    2530-2858/  I/IJKMEDIA﹕ Duration:
11-23 08:14:59.448    2530-2858/  I/IJKMEDIA﹕ N/A
11-23 08:14:59.448    2530-2858/  I/IJKMEDIA﹕ , start:
11-23 08:14:59.448    2530-2858/  I/IJKMEDIA﹕ 0.000000
11-23 08:14:59.448    2530-2858/  I/IJKMEDIA﹕ , bitrate:
11-23 08:14:59.448    2530-2858/  I/IJKMEDIA﹕ N/A
11-23 08:14:59.448    2530-2858/  I/IJKMEDIA﹕ [ 11-23 08:14:59.448  2530: 2858 I/IJKMEDIA ]
    Program 1
11-23 08:14:59.448    2530-2858/  I/IJKMEDIA﹕ Stream #0:0
11-23 08:14:59.448    2530-2858/  I/IJKMEDIA﹕ [0x1e1]
11-23 08:14:59.448    2530-2858/  D/IJKMEDIA﹕ , 121, 1/90000
11-23 08:14:59.448    2530-2858/  I/IJKMEDIA﹕ : Video: h264 (Baseline), 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(left), 640x480, 1/180000
11-23 08:14:59.448    2530-2858/  I/IJKMEDIA﹕ ,
11-23 08:14:59.448    2530-2858/  I/IJKMEDIA﹕ 24 tbr,
11-23 08:14:59.448    2530-2858/  I/IJKMEDIA﹕ 90k tbn,
11-23 08:14:59.448    2530-2858/  I/IJKMEDIA﹕ 180k tbc
11-23 08:14:59.448    2530-2858/  I/IJKMEDIA﹕ [ 11-23 08:14:59.448  2530: 2858 D/IJKMEDIA ]
    detected 4 logical cores
11-23 08:14:59.458    2530-2858/  I/IJKMEDIA﹕ VideoCodec: avcodec, h264
11-23 08:14:59.458    2530-2858/  W/IJKMEDIA﹕ fps: 24.000000 (normal)
11-23 08:14:59.458    2530-4015/  I/IJKMEDIA﹕ SDL_RunThread: [4015] ff_video_dec
11-23 08:14:59.458    2530-2847/  D/IJKMEDIA﹕ FFP_MSG_VIDEO_ROTATION_CHANGED: 0
11-23 08:14:59.458    2530-2847/  D/IJKMEDIA﹕ FFP_MSG_VIDEO_SIZE_CHANGED: 640, 480
11-23 08:14:59.458    2530-2847/  D/IJKMEDIA﹕ FFP_MSG_SAR_CHANGED: 0, 1
11-23 08:14:59.458    2530-2847/  D/IJKMEDIA﹕ ijkmp_get_msg: FFP_MSG_PREPARED
11-23 08:14:59.458    2530-2847/  D/IJKMEDIA﹕ FFP_MSG_PREPARED:
11-23 08:14:59.478    2530-4015/  D/IJKMEDIA﹕ SDL_VoutFFmpeg_CreateOverlay(w=640, h=480, fmt=RV32(0x32335652, dp=0x76580180)
11-23 08:14:59.478    2530-2847/  D/IJKMEDIA﹕ FFP_MSG_VIDEO_SIZE_CHANGED: 640, 480
11-23 08:14:59.488    2530-4015/  D/IJKMEDIA﹕ Video: first frame decoded
11-23 08:14:59.498    2530-2857/  D/IJKMEDIA﹕ ANativeWindow_setBuffersGeometry: w=1080, h=810, f=(0x1) => w=640, h=480, f=RV32(0x32335652)
11-23 08:14:59.498    2530-4014/  E/IJKMEDIA﹕ left block unavailable for requested intra mode at 0 18
11-23 08:14:59.498    2530-4014/  E/IJKMEDIA﹕ error while decoding MB 0 18
11-23 08:14:59.498    2530-4014/  I/IJKMEDIA﹕ concealing 529 DC, 529 AC, 529 MV errors in P frame
11-23 08:14:59.498    2530-2847/  D/IJKMEDIA﹕ FFP_MSG_VIDEO_SIZE_CHANGED: 640, 480
11-23 08:14:59.508    2530-4015/  D/IJKMEDIA﹕ SDL_VoutFFmpeg_CreateOverlay(w=640, h=480, fmt=RV32(0x32335652, dp=0x76580180)
11-23 08:14:59.508    2530-2847/  D/IJKMEDIA﹕ FFP_MSG_VIDEO_RENDERING_START:
11-23 08:14:59.518    2530-4015/  D/IJKMEDIA﹕ SDL_VoutFFmpeg_CreateOverlay(w=640, h=480, fmt=RV32(0x32335652, dp=0x76580180)
11-23 08:14:59.518    2530-2847/  D/IJKMEDIA﹕ FFP_MSG_VIDEO_SIZE_CHANGED: 640, 480
11-23 08:14:59.528    2530-4012/  E/IJKMEDIA﹕ cbp too large (61) at 10 3
11-23 08:14:59.528    2530-4012/  E/IJKMEDIA﹕ error while decoding MB 10 3
11-23 08:14:59.528    2530-4012/  I/IJKMEDIA﹕ concealing 1119 DC, 1119 AC, 1119 MV errors in P frame
11-23 08:14:59.548    2530-2530/  D/IJKMEDIA﹕ IjkMediaPlayer_start
11-23 08:14:59.548    2530-2530/  D/IJKMEDIA﹕ ijkmp_start()
11-23 08:14:59.548    2530-2530/  D/IJKMEDIA﹕ ijkmp_start()=0
11-23 08:14:59.548    2530-2847/  D/IJKMEDIA﹕ ijkmp_get_msg: FFP_REQ_START
11-23 08:14:59.548    2530-2847/  D/IJKMEDIA﹕ ijkmp_get_msg: FFP_REQ_START: start on fly
11-23 08:14:59.558    2530-2530/  I/tv.danmaku.ijk.media.player.IjkMediaPlayer﹕ Info: MEDIA_INFO_VIDEO_RENDERING_START
11-23 08:14:59.558    2530-4013/  E/IJKMEDIA﹕ out of range intra chroma pred mode at 18 20
11-23 08:14:59.558    2530-4013/  E/IJKMEDIA﹕ error while decoding MB 18 20
11-23 08:14:59.558    2530-4013/  I/IJKMEDIA﹕ concealing 431 DC, 431 AC, 431 MV errors in P frame
11-23 08:15:00.128    2530-4012/  E/IJKMEDIA﹕ mb_type 39 in P slice too large at 1 9
11-23 08:15:00.128    2530-4012/  E/IJKMEDIA﹕ error while decoding MB 1 9
11-23 08:15:00.128    2530-4012/  I/IJKMEDIA﹕ concealing 888 DC, 888 AC, 888 MV errors in P frame
11-23 08:15:00.378    2530-4013/  E/IJKMEDIA﹕ left block unavailable for requested intra mode at 0 25
11-23 08:15:00.378    2530-4013/  E/IJKMEDIA﹕ error while decoding MB 0 25
11-23 08:15:00.388    2530-4013/  I/IJKMEDIA﹕ concealing 249 DC, 249 AC, 249 MV errors in P frame
11-23 08:15:00.878    2530-4010/  E/IJKMEDIA﹕ P sub_mb_type 6 out of range at 15 3
11-23 08:15:00.878    2530-4010/  E/IJKMEDIA﹕ error while decoding MB 15 3
11-23 08:15:00.878    2530-4010/  I/IJKMEDIA﹕ concealing 1114 DC, 1114 AC, 1114 MV errors in P frame
11-23 08:15:00.918    2530-4011/  E/IJKMEDIA﹕ cbp too large (997) at 27 4
11-23 08:15:00.918    2530-4011/  E/IJKMEDIA﹕ error while decoding MB 27 4
11-23 08:15:00.918    2530-4011/  I/IJKMEDIA﹕ concealing 1062 DC, 1062 AC, 1062 MV errors in P frame
11-23 08:15:02.218    2530-4012/  E/IJKMEDIA﹕ top block unavailable for requested intra mode at 32 0
11-23 08:15:02.218    2530-4012/  E/IJKMEDIA﹕ error while decoding MB 32 0
11-23 08:15:02.218    2530-4012/  I/IJKMEDIA﹕ concealing 1200 DC, 1200 AC, 1200 MV errors in I frame
11-23 08:15:02.288    2530-4014/  E/IJKMEDIA﹕ mb_type 114 in P slice too large at 15 3
11-23 08:15:02.288    2530-4014/  E/IJKMEDIA﹕ error while decoding MB 15 3
11-23 08:15:02.288    2530-4014/  I/IJKMEDIA﹕ concealing 1114 DC, 1114 AC, 1114 MV errors in P frame
11-23 08:15:02.618    2530-4012/  E/IJKMEDIA﹕ P sub_mb_type 8 out of range at 34 0
11-23 08:15:02.618    2530-4012/  E/IJKMEDIA﹕ error while decoding MB 34 0
11-23 08:15:02.618    2530-4012/  I/IJKMEDIA﹕ concealing 1200 DC, 1200 AC, 1200 MV errors in P frame
11-23 08:15:02.788    2530-4011/  E/IJKMEDIA﹕ P sub_mb_type 7 out of range at 2 24
11-23 08:15:02.788    2530-4011/  E/IJKMEDIA﹕ error while decoding MB 2 24
11-23 08:15:02.788    2530-4011/  I/IJKMEDIA﹕ concealing 287 DC, 287 AC, 287 MV errors in P frame
11-23 08:15:02.828    2530-4012/  D/IJKMEDIA﹕ Frame num gap 0 14
11-23 08:15:03.468    2530-4011/  E/IJKMEDIA﹕ mb_type 114 in P slice too large at 28 28
11-23 08:15:03.468    2530-4011/  E/IJKMEDIA﹕ error while decoding MB 28 28
11-23 08:15:03.468    2530-4011/  I/IJKMEDIA﹕ concealing 101 DC, 101 AC, 101 MV errors in P frame
11-23 08:15:03.498    2530-4012/  D/IJKMEDIA﹕ Frame num gap 8 6
11-23 08:15:04.208    2530-4013/  E/IJKMEDIA﹕ negative number of zero coeffs at 16 11
11-23 08:15:04.208    2530-4013/  E/IJKMEDIA﹕ error while decoding MB 16 11
11-23 08:15:04.208    2530-4013/  I/IJKMEDIA﹕ concealing 793 DC, 793 AC, 793 MV errors in I frame
11-23 08:15:05.548    2530-2858/  D/IJKMEDIA﹕ Continuity check failed for pid 481 expected 5 got 11
11-23 08:15:05.548    2530-2858/  W/IJKMEDIA﹕ PES packet size mismatch
11-23 08:15:05.828    2530-4012/  E/IJKMEDIA﹕ mb_type 191 in P slice too large at 16 14
11-23 08:15:05.828    2530-4012/  E/IJKMEDIA﹕ error while decoding MB 16 14
11-23 08:15:05.828    2530-4012/  I/IJKMEDIA﹕ concealing 673 DC, 673 AC, 673 MV errors in P frame
11-23 08:15:18.318    2530-2530/  D/IJKMEDIA﹕ ijkmp_stop()
11-23 08:15:18.318    2530-2530/  D/IJKMEDIA﹕ ijkmp_stop()=0
11-23 08:15:18.318    2530-2530/  D/IJKMEDIA﹕ IjkMediaPlayer_release
11-23 08:15:18.318    2530-2530/  D/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0x0)
11-23 08:15:18.318    2530-2530/  D/IJKMEDIA﹕ ffpipeline_set_surface()
11-23 08:15:18.318    2530-2530/  D/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0x0)=void
11-23 08:15:18.318    2530-2530/  D/IJKMEDIA﹕ ijkmp_shutdown_l()
11-23 08:15:18.318    2530-2530/  D/IJKMEDIA﹕ wait for read_tid
11-23 08:15:18.318    2530-4015/  I/IJKMEDIA﹕ SDL_JNI_DetachThreadEnv: [4015]
11-23 08:15:18.318    2530-2847/  D/IJKMEDIA﹕ message_loop exit
11-23 08:15:18.318    2530-2847/  I/IJKMEDIA﹕ SDL_JNI_DetachThreadEnv: [2847]
11-23 08:15:18.328    2530-2857/  I/IJKMEDIA﹕ SDL_JNI_DetachThreadEnv: [2857]

**Comment by bbcallen** [comment]
How it works when you play it in the form of "file://<path>"

**Comment by goldenpointer** [comment]
The play back starts without much delay with file://.

**Comment by goldenpointer** [comment]
It starts without any significant delay when I keep on writing the received data to a file and pass the path(path to the file) to the player.
This is not the case when I pass the file descriptor(using local socket). Here it takes significant amount of delay to start the playback, initially it shows the black screen for 4-5 secs and then the playback starts. I have disabled the ijkplayer buffering but still it looks like the player waits for some time initially.

**Comment by bbcallen** [comment]
Take a look at ff_pipe_protocol in libavformat/pipe.c
It lacks of seek support, which may cause the delay problem.
