### ISSUE TITLE
About license issue of libVLC part

### ISSUE THREAD

**Issue by jpxiong** [Bilibili/ijkplayer#1275]
I noticed that the libVLC in README is declared to LGPL. In fact, [libVLC](http://git.videolan.org/?p=vlc.git;a=blob;f=README;h=22222ea167c7c40ed18c363c0f600bb863a55af3;hb=HEAD) is under GPLv2. Does ijk use part of libVLC which is LGPL?

Thanks for your response.

**Comment by bbcallen** [comment]
There are both LGPL and GPL source files in libVLC.

ijkplayer only depends on libVLC's LGPL source code, you can find them by "git grep -i videolan", "git grep -i vlc"

**Comment by jpxiong** [comment]
Thank BBC very much!
