### ISSUE TITLE
机型动态适配问题

### ISSUE THREAD

**Issue by liuyuejinqiu** [Bilibili/ijkplayer#1282]
请问bilibili客户端中“根据机型动态适配”是根据什么规则来进行适配的？
例如如果我的手机是“HUAWEI MATE1”,系统版本：4.1.2，在使用bilibili客户端时，播放视频时会使用v1播放器。
如果我的手机是“XIAOMI MI2”,系统版本：5.0.2，在使用bilibili客户端时，播放视频时会使用ijkplayer。

**Comment by bbcallen** [comment]
It's not an ijkplayer feature.
Wrong place for this question.

**Comment by liuyuejinqiu** [comment]
Thankyou.
