### ISSUE TITLE
send http headers (HLS-m3u8)

### ISSUE THREAD

**Issue by msdos2** [Bilibili/ijkplayer#1283]
hello as I can send user-agent headers referer etc thanks

**Comment by bbcallen** [comment]
https://ffmpeg.org/ffmpeg-protocols.html#http

**Comment by msdos2** [comment]
Thanks bbcallen, but I'am unable to send multiple headers. For example, how could I set both referer and Connection headers? I have tried to make multiple calls to setOption but only the last value is used. Is there a way to set multiple values for http headers?

Thanks,

**Comment by bbcallen** [comment]
See libavformat/http.c
