### ISSUE TITLE
chunk模式下无法获取到duration

### ISSUE THREAD

**Issue by CSZRZ** [Bilibili/ijkplayer#1284]
您好，请问下，在chunk模式下直接调用duration 始终为0，ijkplayer支持这个模式吗？或者我需要怎样改成非chunk模式的？原先用的avplayer可以直接获取到时长。希望可以指点一下，谢谢！

**Comment by CSZRZ** [comment]
http://122.193.8.100:7079/vod/mcap8701160508183000?format=m3u8&targetType=mobile&df=sd&busiType=cpg
麻烦看下这个链接，不像传统的m3u8地址，可以直接读取到文件里面的duration，这个没有返回这个字段。
这个是log：
LS request for url 'http://153.37.221.26:9193/vod/hls/rc/szwh-800k.tindex?pos=0012&stime=20160508T183000&dur=12&tokenekot=ZmOTqlEY8FeWwMPvJSmC', offset 0, playlist 0
No trailing CRLF found in HTTP header.
request: GET /vod/hls/rc/szwh-800k.tindex?pos=0012&stime=20160508T183000&dur=12&tokenekot=ZmOTqlEY8FeWwMPvJSmC HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Connection: close

Host: 153.37.221.26:9193

Icy-MetaData: 1
貌似每次都请求12s的视频?

**Comment by bbcallen** [comment]
This is m3u8.

**Comment by CSZRZ** [comment]
不好意思，没明白你的意思。目前这链接是可以正常播放的，但是我通过duration属性取不到值。。请问我该如何获取呢？

**Comment by bbcallen** [comment]
You can't.
Without "EXT-X-ENDLIST" tag, ffmpeg assume it's a LIVE HLS.

**Comment by CSZRZ** [comment]
ok, I m sorry to hear that.thank you very much

**Comment by Android4MediaPlayer** [comment]
@CSZRZ give test url

**Comment by xiaomianbao** [comment]
@Android4MediaPlayer   http://9281.live-vod.cdn.aodianyun.com/m3u8/0x0/wsp_9281_1452595928.e984be45394c5928b7f4b4d0aaf34c39.1461993361/wsp_9281_1452595928.e984be45394c5928b7f4b4d0aaf34c39.1461993361.m3u8    
this is my url ,  I can not  get the duration  in ios ,  but it can get the duration in Android    help me please.

**Comment by Android4MediaPlayer** [comment]
Give a detailed log.

**Comment by xiaomianbao** [comment]
@bbcallen     #1437
