### ISSUE TITLE
纯音频如何后台播放？

### ISSUE THREAD

**Issue by suikatomoki** [Bilibili/ijkplayer#1286]
app退到后台后，会继续播放几秒钟，然后就会停止播放，log如下。
![-7abc19788c414a13](https://cloud.githubusercontent.com/assets/10336224/15104773/863a8162-1581-11e6-8f53-a34b2b4bd376.png)

**Comment by bbcallen** [comment]
It stops, because you stop/release it.

**Comment by suikatomoki** [comment]
解决了，真是个大大的坑。
当IjkMediaPlayer对象被定义成局部量时就会有这种问题。
此时退到后台，播放就会被中断。
声明成成员变量就好了。
![-4bd22bb4f658d488](https://cloud.githubusercontent.com/assets/10336224/15105146/d4b9a996-1584-11e6-8902-5835c5e9ed8d.png)
