### ISSUE TITLE
请问IjkMediaPlayer播放视频有声音无图像是什么原因

### ISSUE THREAD

**Issue by Fu-Cheng** [Bilibili/ijkplayer#1287]
我用IjkMediaPlayer播放"http://movement.gzstv.com/streams/video_url/835/"这样的视频地址时只有声音没有图像，onVideoSizeChanged监听没有被调用，在任何时刻调mp.getVideoWidth()都是0。用AndroidMediaPlayer播放没问题。

**Comment by bbcallen** [comment]
```
    Stream #0:0(und): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 720x576 [SAR 1:1 DAR 5:4], 1776 kb/s, 25 fps, 25 tbr, 25 tbn, 25 tbc (default)
```

It's mp4v, disabled by default, see README.

**Comment by Fu-Cheng** [comment]
请问怎样启用mp4v呢？

**Comment by bbcallen** [comment]
See README
