### ISSUE TITLE
一些关于onCompletion的建议

### ISSUE THREAD

**Issue by NoGirlFriendException** [Bilibili/ijkplayer#1289]
我个人感觉ijkPlayer 对于 onCompletion的回调时机 使用的并不完全正确
onCompletion 应该是在一个**电影正常状态下播放完毕**后产生的回调
但是在ijkPlayer中 不仅仅是在电影播放完毕后 会回调. 而且在出现error的时候 也会出现这个回调
这个逻辑明显是和 android 源生播放器 以及exoPlayer 以及我最早使用的Vitiamio 播放器都不一样.
并不是太明白为什么你们这样设计
你们大部分的接口都是与androidmediaPlayer 保持一致的 但是在这个地方是和他完全不一样的.

以及 你们的demo中 exoplayer 的wrapper类 中对于exoPlayer 报出的 状态改变的监听
   case ExoPlayer.STATE_IDLE:
            notifyOnCompletion();
我个人认为这也是不合理的 这句话应该注释掉. 
google 官方应该希望 仅仅是在ExoPlayer.STATE_ENDED: 的回调中才 应该 回调 notifyOnCompletion();
而不是你们现在的写法。

以上只是个人的一些看法和建议 如果有说的不对的地方和 错怪你们的地方 请见谅。

**Comment by NoGirlFriendException** [comment]
哦哦 我想起来了一个可能能证明你们是错误的细节
那就是如果 使用你们的demo去 初始化一个播放器 然后设置空url 故意造成error
然后这个时候去调用 start 
android 源生播放器的表现就是正确的 是不能start的 因为不是isInPlaybackState。
exo 播放器和 ijkplayer 的表现就是错误的 因为 你们在错误以后 回调了 onCompletion();
而这个回调之后VideoView的state 会变成STATE_PLAYBACK_COMPLETED
isInPlaybackState 也变成了true 这明显是不正确的.

**Comment by bbcallen** [comment]
For ijkplayer's onCompletion(), it's a bug, not by design. libavformat returns EOF and error both by error code. Sometimes it could be misunderstood.

For else, pull requests are welcome.
