### ISSUE TITLE
请教一个关于SDL_VoutOverlay的format取值的问题

### ISSUE THREAD

**Issue by changchang** [Bilibili/ijkplayer#1292]
最近在分析`ijkmedia/ijksdl/ffmpeg/ijksdl_vout_overlay_ffmpeg.c`的`func_fill_frame`函数的代码，打算测一下设备渲染格式的兼容性。

在几台android设备上测试，发现overlap的format都是两个取值，`SDL_FCC_RV32`和`SDL_FCC_YV12`，分别是在使用ffmpeg软解和开启gles渲染时的格式。

这里有一个疑问，代码中的其他几种格式：`SDL_FCC_I444P10LE`, `SDL_FCC_RV24`, `SDL_FCC_RV16`是在哪些型号的设备上或者是在哪些条件下才会出现呢？

**Comment by bbcallen** [comment]
SDL_FCC_RV24, SDL_FCC_RV16 can be enabled manually, but they are useless.
SDL_FCC_I444P10LE is used for I444p10le pixel format.

**Comment by changchang** [comment]
thanks~
