### ISSUE TITLE
Cloning into 'ios/openssl-i386'..

### ISSUE THREAD

**Issue by ivoidcat** [Bilibili/ijkplayer#1293]
Cloning into 'ios/openssl-i386'...
fatal: unable to access 'https://github.com/Bilibili/openssl.git/': Could not resolve host: github.com
tools/pull-repo-ref.sh: line 11: cd: ios/openssl-i386: No such file or directory
fatal: Not a git repository (or any of the parent directories): .git

**Comment by bbcallen** [comment]
http://translate.google.com

**Comment by bbcallen** [comment]
Buy a VPN
