### ISSUE TITLE
Change Surface runtime with same mediaplayer

### ISSUE THREAD

**Issue by FunnyDevs** [Bilibili/ijkplayer#1294]
Hi! I am not able to change the surface where the mediaplayer plays video frames. I have used ijkvideoview and i have created a "setMediaPlayer" function, but when i change the media player from one ijkvideoview to another the second surface remains empty and only audio plays. How can i do it?

Thanks

**Comment by ashqal** [comment]
You may call `SurfaceTexture#detachFromGLContext` in GL thread before change to another surface.

**Comment by FunnyDevs** [comment]
No result

**Comment by bbcallen** [comment]
Does it work in demo, when you click 'Render' button in player activity?

**Comment by FunnyDevs** [comment]
Ok, i have solved adding a delay time, after setting mediaplayer, before starting the player. With this delay the surface is able to reproduce both audio and video.
