### ISSUE TITLE
Setting Buffer Size

### ISSUE THREAD

**Issue by rocxteady** [Bilibili/ijkplayer#13]
Hello.

How can I set the buffer size of a stream? Or buffer time?
I am streaming only audio.
Default buffer time is around 5 seconds. How can I decrease this?

Thanks

**Comment by ened** [comment]
@bbcallen:

Does this API:
```
if you want to set them from application, add these api
// see how ijkmp_set_overlay_format() does
ijkmp_set_high_water_mark()
ffp_set_high_water_mark()
```

still exist?

**Comment by developeralp** [comment]
@ened 

You can ,

```
                    ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "max-buffer-size", 1024*1024);
                    ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
                    ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "min-frames",5);
                    ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "first-high-water-mark-ms",100);
                    ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "next-high-water-mark-ms",100);

```

On IjkVideoView.

Also , you can learn variables from ,

https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/ff_ffplay_def.h
https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/ff_ffplay_options.h#L110

**Comment by ened** [comment]
HI @developeralp ,

Thank you!

I was using this before:

``` swift
        opts.setPlayerOptionIntValue(5 * 1000, forKey: "first-high-water-mark-ms")
        opts.setPlayerOptionIntValue(50 * 1000, forKey: "next-high-water-mark-ms")
        opts.setPlayerOptionIntValue(100 * 1000, forKey: "last-high-water-mark-ms")
        opts.setPlayerOptionIntValue(10000, forKey: "min-frames")
        opts.setPlayerOptionIntValue((128 * 1024 * 1024), forKey: "max-buffer-size")
```

Will re-evaluate today, as it did not seem to work.

Why did you set `ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);` ?

**Comment by spaul13** [comment]
can anyone, @rocxteady , @bbcallen @ened @developeralp @tewilove please tell me how to change the size of the video buffer? what's the size of video buffer by default?

from where it's calling the buffer to write into it and who takes the data out of the buffer?

I am getting an error
**E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Buffer (100%) 26468/14750**

I have seen ijkfifobuffer is implemented but I want to know where the buffer is written actually? I have seen an array based contiguous allocation.
