### ISSUE TITLE
编译时报错，请问怎么解决？

### ISSUE THREAD

**Issue by winter120** [Bilibili/ijkplayer#1301]
按照README.md文档的步骤，编译已经执行到了./compile-ffmpeg.sh all并且已成功。下一步，执行./compile-ijk.sh all时报出以下错误：
$ ./compile-ijk.sh all
profiler build: NO
ln: failed to create symbolic link ‘android-ndk-prof/jni’: No such file or directory
E:/AndroidDownload/ijkplayer-android/android/ijkplayer/ijkplayer-armv5/src/main/jni/Android.mk:1: *** missing separator.  Stop.
/e/AndroidDownload/ijkplayer-android/android
profiler build: NO
ln: failed to create symbolic link ‘android-ndk-prof/jni’: No such file or directory
/usr/bin/sh: rem: command not found
/usr/bin/sh: rem: command not found
D:/Android/sdk/ndk-bundle/build/core/build-binary.mk:519: recipe for target 'E:/AndroidDownload/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/obj/local/armeabi-v7a' failed
make: *** [E:/AndroidDownload/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/obj/local/armeabi-v7a] Error 127
make: *** Waiting for unfinished jobs....
D:/Android/sdk/ndk-bundle/build/core/build-binary.mk:721: recipe for target 'E:/AndroidDownload/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/libs/armeabi-v7a' failed
make: *** [E:/AndroidDownload/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/libs/armeabi-v7a] Error 127
/e/AndroidDownload/ijkplayer-android/android
profiler build: NO
ln: failed to create symbolic link ‘android-ndk-prof/jni’: No such file or directory
E:/AndroidDownload/ijkplayer-android/android/ijkplayer/ijkplayer-arm64/src/main/jni/Android.mk:1: *** missing separator.  Stop.
/e/AndroidDownload/ijkplayer-android/android
profiler build: NO
ln: failed to create symbolic link ‘android-ndk-prof/jni’: No such file or directory
E:/AndroidDownload/ijkplayer-android/android/ijkplayer/ijkplayer-x86/src/main/jni/Android.mk:1: *** missing separator.  Stop.
/e/AndroidDownload/ijkplayer-android/android
profiler build: NO
ln: failed to create symbolic link ‘android-ndk-prof/jni’: No such file or directory
E:/AndroidDownload/ijkplayer-android/android/ijkplayer/ijkplayer-x86_64/src/main/jni/Android.mk:1: *** missing separator.  Stop.
/e/AndroidDownload/ijkplayer-android/android
请问如何解决

**Comment by bbcallen** [comment]
Build on linux or macos.
I don't support build for windows.

**Comment by MrZhangYang** [comment]
我也遇到同样问题，编译好几次，我也是醉了

**Comment by MrZhangYang** [comment]
@bbcallen  do you have another way for build on windows?

**Comment by evilbinary** [comment]
MSYS=winsymlinks:nativestrict 或者export MSYS="winsymlinks:lnk"

**Comment by YuDongZhang** [comment]
the same mistake , on windows
