### ISSUE TITLE
ijkplayer k0.5.0 iso encoder by videotoolbox h264

### ISSUE THREAD

**Issue by nir8** [Bilibili/ijkplayer#1306]
i have open the videotoolbox option, it work well with mp4, but when i want to play the file code with h264 it will come to the problem that "decodeFrame -12911 kVTVideoDecoderMalfunctionErr" then "[FFPlayer @ 0x16b9f400] ffp_toggle_buffering: eof".  if i close the videotoolbox option, it will work well to play local file of mp4 and h264 .

**Comment by nir8** [comment]
here is the log:

2016-05-12 09:27:24.090 IJKMediaDemo[1169:165446] url is ::: /var/mobile/Containers/Data/Application/2CCC7EE1-CCEA-4D05-8201-4CE50479FB08/Documents/test.264
2016-05-12 09:27:24.156 IJKMediaDemo[1169:165446] ijkplayer ____________+++++++++++++++______________5,0:
===== custom modules begin =====
register protocol: async
register protocol: ijkhttphook
register protocol: ijkinject
register protocol: ijklongurl
register protocol: ijksegment
register protocol: ijktcphook
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff3.0--ijk0.4.5.1--dev0.4.5--rc10
22222222222222 ffpipeline_create_from_ios 
ijkmp_set_inject_opaque(0x176b84a0)
ijkmp_set_inject_opaque()=void
2016-05-12 09:27:24.318 IJKMediaDemo[1169:165446] OK setup GL
ijkmp_ios_set_view(glView=0x17523df0)
ijkmp_ios_set_view(glView=0x17523df0)=void
2016-05-12 09:27:24.341 IJKMediaDemo[1169:165446] invalidateRenderBuffer
2016-05-12 09:27:24.343 IJKMediaDemo[1169:165671] IJKSDLGLView: setupDisplay not ready
ijkmp_set_data_source(url="/var/mobile/Containers/Data/Application/2CCC7EE1-CCEA-4D05-8201-4CE50479FB08/Documents/test.264")
ijkmp_set_data_source(url="/var/mobile/Containers/Data/Application/2CCC7EE1-CCEA-4D05-8201-4CE50479FB08/Documents/test.264")=0
ijkmp_prepare_async()
===== versions =====
FFmpeg       : ff3.0--ijk0.4.5.1--dev0.4.5--rc10
libavutil    : 55.17.103
libavcodec   : 57.24.102
libavformat  : 57.25.100
libswscale   : 4.0.100
libswresample: 2.0.101
===== options =====
player-opts : videotoolbox                 = 1
player-opts : overlay-format               = fcc-_es2
player-opts : framedrop                    = 0
player-opts : max-fps                      = 30
player-opts : video-pictq-size             = 3
player-opts : start-on-prepared            = 1
format-opts : ijkinject-opaque             = 392922272
format-opts : ijkapplication               = 391237920
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : timeout                      = 30000000
format-opts : reconnect                    = 1
format-opts : safe                         = 0
===================
ffp_prepare_async_l 111111111 fileName is：/var/mobile/Containers/Data/Application/2CCC7EE1-CCEA-4D05-8201-4CE50479FB08/Documents/test.264ijkmp_prepare_async()=0
Setting default whitelist 'file'
Format h264 probed with size=2048 and score=51
Option ijkinject-opaque not found.
AVFMT_FLAG_NOBUFFER11111111111111
Before avformat_find_stream_info() pos: 0 bytes read:32768 seeks:0
2016-05-12 09:27:24.406 IJKMediaDemo[1169:165446] invalidateRenderBuffer
2016-05-12 09:27:24.410 IJKMediaDemo[1169:165671] IJKSDLGLView: setupDisplay not ready
2016-05-12 09:27:24.432 IJKMediaDemo[1169:165446] invalidateRenderBuffer
2016-05-12 09:27:24.432 IJKMediaDemo[1169:165671] IJKSDLGLView: setupDisplay not ready
max_analyze_duration 5000000 reached at 5000000 microseconds st:0
After avformat_find_stream_info() pos: 121856 bytes read:131072 seeks:0 frames:127
max_frame_duration: 10.000
Input #0, h264, from '/var/mobile/Containers/Data/Application/2CCC7EE1-CCEA-4D05-8201-4CE50479FB08/Documents/test.264':
  Duration: N/A, bitrate: N/A
    Stream #0:0, 127, 1/1200000: Video: h264, 1 reference frame, yuv420p(left), 1280x720, 1/50, 25 fps, 25 tbr, 1200k tbn, 50 tbc
detected 2 logical cores
init_videotoolbox - 111111111111 AV_CODEC_ID_H264 0 
init_videotoolbox - 111111111111 AV_CODEC_ID_H264 1 
after scale width 1280 height 720 
m_max_ref_frames 5 
fps: 25.000000 (normal)
fps: 25.000000 (normal)
ijkmp_get_msg: FFP_MSG_PREPARED
2016-05-12 09:27:24.735 IJKMediaDemo[1169:165446] FFP_MSG_VIDEO_DECODER_OPEN: true
2016-05-12 09:27:24.736 IJKMediaDemo[1169:165446] FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
2016-05-12 09:27:24.736 IJKMediaDemo[1169:165446] FFP_MSG_SAR_CHANGED: 0, 1
2016-05-12 09:27:24.736 IJKMediaDemo[1169:165446] FFP_MSG_PREPARED:
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
2016-05-12 09:27:24.737 IJKMediaDemo[1169:165446] fps in meta 25.000000
2016-05-12 09:27:24.737 IJKMediaDemo[1169:165446] mediaIsPreparedToPlayDidChange
2016-05-12 09:27:24.738 IJKMediaDemo[1169:165446] loadStateDidChange: IJKMPMovieLoadStatePlaythroughOK: 3
flushed last keyframe pts 0 

2016-05-12 09:27:24.738 IJKMediaDemo[1169:165446] IJKMPMoviePlayBackStateDidChange 1: playing
after scale width 1280 height 720 
 
the buffer should m_convert_byte
demux_size:417 ％
 videotoolbox_decode_video_internal deconde flags is 0  

decodeFrame -12911 kVTVideoDecoderMalfunctionErr
 
ffp_toggle_buffering_l: start
aout_pause_audio(1)
2016-05-12 09:27:24.883 IJKMediaDemo[1169:165446] FFP_MSG_BUFFERING_START:
2016-05-12 09:27:24.884 IJKMediaDemo[1169:165446] loadStateDidChange: IJKMPMovieLoadStateStalled: 4

ffp_toggle_buffering_l: end
 
aout_pause_audio(0)
 
2016-05-12 09:27:25.161 IJKMediaDemo[1169:165446] FFP_MSG_BUFFERING_END:
2016-05-12 09:27:25.162 IJKMediaDemo[1169:165446] loadStateDidChange: IJKMPMovieLoadStatePlaythroughOK: 3
2016-05-12 09:27:25.162 IJKMediaDemo[1169:165446] IJKMPMoviePlayBackStateDidChange 1: playing
aout_pause_audio(1)
ffp_toggle_buffering: completed: OK
ijkmp_get_msg: FFP_MSG_COMPLETED
2016-05-12 09:27:26.177 IJKMediaDemo[1169:165446] IJKMPMoviePlayBackStateDidChange 0: stoped
2016-05-12 09:27:26.178 IJKMediaDemo[1169:165446] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackEnded: 0
2016-05-12 09:27:26.178 IJKMediaDemo[1169:165446] IJKMPMoviePlayBackStateDidChange 0: stoped
ffp_toggle_buffering: eof

**Comment by bbcallen** [comment]
Sorry, not familiar with the raw h264 container.

**Comment by progamertr** [comment]
@nir8 , Could you please share your streaming url ?

**Comment by nir8** [comment]
@progamertr ,i get the h264 stream from local network camera, i can give you a download file.
[Uploading localfile.264.zip…]()

**Comment by progamertr** [comment]
@nir8 ,  I could not download the file, could you please check the link ?

**Comment by nir8** [comment]
i had try to attach files many times, it failed all.  and now it can work well with h264. thanks !

**Comment by nir8** [comment]
i had try to attach files many times, it failed all.  and now it can work well with h264. thanks !

**Comment by nir8** [comment]
i had try to attach files many times, it failed all.  and now it can work well with h264. thanks !

**Comment by nir8** [comment]
i had try to attach files many times, it failed all.  and now it can work well with h264. thanks !

**Comment by nir8** [comment]
i had try to attach files many times, it failed all.  and now it can work well with h264. thanks !

**Comment by nir8** [comment]
i had try to attach files many times, it failed all.  and now it can work well with h264. thanks !

**Comment by nir8** [comment]
i had try to attach files many times, it failed all.  and now it can work well with h264. thanks !

**Comment by nir8** [comment]
i had try to attach files many times, it failed all.  and now it can work well with h264. thanks !

**Comment by nir8** [comment]
i had try to attach files many times, it failed all.  and now it can work well with h264. thanks !

**Comment by nir8** [comment]
i had try to attach files many times, it failed all.  and now it can work well with h264. thanks !

**Comment by nir8** [comment]
i had try to attach files many times, it failed all.  and now it can work well with h264. thanks !

**Comment by nir8** [comment]
i had try to attach files many times, it failed all.  and now it can work well with h264. thanks !

**Comment by nir8** [comment]
i had try to attach files many times, it failed all.  and now it can work well with h264. thanks !

**Comment by nir8** [comment]
i had try to attach files many times, it failed all.  and now it can work well with h264. thanks !

**Comment by nir8** [comment]
i had try to attach files many times, it failed all.  and now it can work well with h264. thanks !

**Comment by nir8** [comment]
i had try to attach files many times, it failed all.  and now it can work well with h264. thanks !

**Comment by nir8** [comment]
i had try to attach files many times, it failed all.  and now it can work well with h264. thanks !

**Comment by nir8** [comment]
i had try to attach files many times, it failed all.  and now it can work well with h264. thanks !

**Comment by nir8** [comment]
i had try to attach files many times, it failed all.  and now it can work well with h264. thanks !

**Comment by nir8** [comment]
i had try to attach files many times, it failed all.  and now it can work well with h264. thanks !
