### ISSUE TITLE
ARM64的minSdkVersion太高了

### ISSUE THREAD

**Issue by reaper12** [Bilibili/ijkplayer#1308]
ARM64的minSdkVersion太高了，无法依赖，能不能改小一点

**Comment by suikatomoki** [comment]
<uses-sdk tools:overrideLibrary="tv.danmaku.ijk.media.player_arm64,com.example.ijkplayer_x86_64"/>

**Comment by suikatomoki** [comment]
uses-sdk tools:overrideLibrary="tv.danmaku.ijk.media.player_arm64,com.example.ijkplayer_x86_64"

**Comment by wlanjie** [comment]
arm64是21后才支持的,所以最低就是21

**Comment by wuxudoong** [comment]
为啥我加了这句话还是没起作用啊<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.example.library">
    <uses-sdk tools:overrideLibrary="tv.danmaku.ijk.media:ijkplayer-arm64, tv.danmaku.ijk.media:ijkplayer-x86_64"/></manifest>。。。
