### ISSUE TITLE
android播放mpeg2video+mp2的TS流出现严重音视频不同步，卡帧马赛克

### ISSUE THREAD

**Issue by hoafer** [Bilibili/ijkplayer#131]
你好，我在android上使用github最新版的代码播放http的mpeg2video+mp2  TS直播流出现严重的音视频不同步。音频是正常的，图像卡帧花屏。之前电脑上有拉过旧版的代码播放是正常的，后来新的代码覆盖了没得对比了。附件是问题的log。具体问题的测试码流有发到你的gmail邮箱了，谢谢！

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
