### ISSUE TITLE
如何解决播放rtmp时累积延迟问题？

### ISSUE THREAD

**Issue by cdkr** [Bilibili/ijkplayer#1312]
在播放rtmp流的时候如果网络卡顿的话，延迟越来越大。我发现关掉packet-buffering的时候，如果网络关闭再重新打开，一段时间内播放速度会加快，可以解决累积延迟问题，但是没法接收buffer的Notification，而且好像更容易stalle。

而且我用各种方法设置buffer size好像都没有变化。

**Comment by bbcallen** [comment]
No good solution for both sides, for now.

**Comment by WLZJ** [comment]
@cdkr 请问，你是怎么设置buffer size的？

**Comment by cdkr** [comment]
@WLZJ 我用 `[option setPlayerOptionIntValue:5 forKey:@"max-buffer-size"];` 和 `[option setFormatOptionIntValue:32 forKey:@"rtbufsize"];`  不管设置成多少都没发现区别

**Comment by SoXeon** [comment]
在网络稳定情况下，当videoBuffer累计到一定程度修改PlayRate。在非稳定情况下，根据网络情况而定，可以增加动态buffer修改接口。
