### ISSUE TITLE
Android prepareAsync starts playback

### ISSUE THREAD

**Issue by ssuukk** [Bilibili/ijkplayer#1315]
Hello,

Android player .prepareAsync() method starts playback, that's not the right behaviour and it requires pausing the stream in onPrepared as a workaround. Unfortunately a fraction of second is still played, even with this workaround. Can you fix it, please?

**Comment by bbcallen** [comment]
mp.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "start-on-prepared", 0);

**Comment by ssuukk** [comment]
Thanks!
13.05.2016 13:49 "bbcallen" <notifications@github.com> napisał(a):
