### ISSUE TITLE
获取视频播放状态

### ISSUE THREAD

**Issue by BruceLilonglong** [Bilibili/ijkplayer#1316]
如何获得视频url加载成功的回调，如何知道视频成功的播放了

**Comment by Android4MediaPlayer** [comment]
监听oninfo,当what为MEDIA_INFO_VIDEO_RENDERING_START时播放第一帧画面了

**Comment by BruceLilonglong** [comment]
thanks!

**Comment by Android4MediaPlayer** [comment]
OK

**Comment by bbcallen** [comment]
If you mean connected, you should listen OnPreparedListener.
