### ISSUE TITLE
音视频未同步问题

### ISSUE THREAD

**Issue by MrZhuGe** [Bilibili/ijkplayer#1317]
我测试播放直播视频的时候，音频总是快视频那么两秒，难道是音视频没有保持同步么？

**Comment by Android4MediaPlayer** [comment]
give more information,eg:streaming url.

**Comment by MrZhuGe** [comment]
我是开发iOS的，测试的视频直播地址是：rtmp://live.hkstv.hk.lxdns.com/live/hks

**Comment by MrZhuGe** [comment]
找出问题了，模拟器会出现这个问题，真机暂时没有发现，谢谢你们
