### ISSUE TITLE
android用硬解码播放器切后台恢复问题

### ISSUE THREAD

**Issue by gnwell** [Bilibili/ijkplayer#1324]
需求: 需要实现播放器切后台暂停，恢复前台从暂停位置继续播放的基本功能。
问题:使用硬解码时，后台恢复后出现只播放声音，画面黑屏持续几秒(黑屏时间长短不固定）后画面才能显示。应该是surfaceview重建后重新绑定到player后导致的现象，有遇到过此问题的朋友么？

**Comment by bbcallen** [comment]
It's a known issue, and no good solution, for now.

**Comment by gnwell** [comment]
@bbcallen 请教下，视频黑屏持续期间
SDL_AMediaCodecFake_dequeueOutputBuffer 返回AMEDIACODEC__INFO_TRY_AGAIN_LATER，也就说现在MediaCodec一直没有输出数据对吧？可不可以理解次Surface发生变化都会导致codec reconfigure,重新设置后就会导致解码器输出延时的情况，这是AMEDIACODEC 的问题了？

**Comment by bbcallen** [comment]
No, actually, it's player's issue.
But for MediaCodec, it's a little difficult to workaround.

**Comment by gnwell** [comment]
@bbcallen 您指的player问题，是说在这种情况下，不应该创建新的codec么？即使surface重新建立了，也可以继续使用原来的codec？

**Comment by bbcallen** [comment]
Do not recreate MediaCodec is the best practice in theory. You can take a look at github.com/google/grafika for this idea ('Double decode' section). But in real world, it may broken on some vendor devices.

So, the only option left is that, the player should feed the correct data. This need some H264 knowledges.

**Comment by gnwell** [comment]
@bbcallen ，very appreciate for your help!!:)

**Comment by gnwell** [comment]
@bbcallen come back again. 看了下bilibili的应用，采用硬件解码，切后台回来后好像codec没有重新建立？还是用的以前的codec是么？

**Comment by bbcallen** [comment]
Sorry, I don't have any authority to talk about the detail of the application in public.

**Comment by gnwell** [comment]
@bbcallen thanks a lot though:)

**Comment by AliveingSoul** [comment]
@bbcallen 我遇到的情况是开启硬解码后，后台切换回来播放会花屏几秒，然后正常，也是跟楼主一样的原因吗？
![qq 20160519195510](https://cloud.githubusercontent.com/assets/13717899/15392724/a6d76336-1dfb-11e6-9b6a-0a710df9adc4.jpg)

**Comment by gnwell** [comment]
maybe codec requries idr frame when renew.

**Comment by gnwell** [comment]
maybe codec requries idr frame when renew.

**Comment by AliveingSoul** [comment]
@gnwell But when I turn off the screen then turn on again  ,It's not have this problem , Their life cycle should be no different

**Comment by gnwell** [comment]
check log whether the decoder is configured with your    operations. i have tried the ideas mentioned by bbcallen github.com/google/grafika for this idea ('Double decode' section). it works.

**Comment by gnwell** [comment]
check log whether the decoder is configured with your    operations. i have tried the ideas mentioned by bbcallen github.com/google/grafika for this idea ('Double decode' section). it works.

**Comment by dourgulf** [comment]
mark

**Comment by edwardZj** [comment]
@gnwell I see github.com/google/grafika for this idea ('Double decode' section).But I don't know what to do.Hope your reply in Chinese ~

**Comment by lgengsy** [comment]
mark @AliveingSoul  你解决了么 ？？

**Comment by lgengsy** [comment]
@gnwell how to fix  it

**Comment by gnwell** [comment]
@lgengsy 可以参照TextureRenderView.java的实现，关键就是在View销毁的时候不要销毁SurfaceTexture

**Comment by zhangpingV5** [comment]
看了TextureRenderView.java 还是没有搞太懂，不知道怎样去修改。大神能帮忙详细的解释下吗？万分感谢 @gnwell

**Comment by zhanggao** [comment]
@zhangpingV5 这个问题你解决了没？

**Comment by wutongluxjtu** [comment]
@gnwell 请问解决该问题，你用的 “可以参照TextureRenderView.java的实现，关键就是在View销毁的时候不要销毁SurfaceTexture” 方法， 还是用的 “Double decode” 方法？  另外，能不能给出代码示例？谢谢！

**Comment by zhanggao** [comment]
@gnwell @wutongluxjtu TextureRenderView也有这个问题。

**Comment by wutongluxjtu** [comment]
@zhanggao 目前有什么好的解决方法吗？

**Comment by wutongluxjtu** [comment]
@bbcallen 请问这个热点讨论issue， 是否考虑修复？

**Comment by bbcallen** [comment]
Nope

**Comment by zhanggao** [comment]
@wutongluxjtu 没有，我改成软解了。

**Comment by Shinlone** [comment]
https://github.com/bbcallen这个问题我也遇到了

**Comment by teddyla** [comment]
@gnwell 
android platform:
video output buffer maintain & alloc from surface.(bufferqueue).
when ur surface is in background. surface is disconnect-> bufferqueue is destroyed
----------------------------------------------------------
after surface return foreground. surface connect & realloc output buffer for omx port. then fillbuffer. wait buffer done, do avsync & queueBuffer, consumer composite & render
----------------------------------------------------------
-> becoz these sw flow need time costing, this is why black screen sustain a while.

**Comment by teddyla** [comment]
there is a solution(see google bigflake).
use two surface.  one surface for omx output buffer. & one surface for display.
use opengl es api for zero memcpy~

**Comment by bingxuebage** [comment]
碰到同样的问题，请教各位 TextureRenderView 和Double decode 怎么使用

**Comment by zhanggao** [comment]
mediaPlayer = new TextureMediaPlayer(mediaPlayer);
TextureView 硬解切后台不会黑屏。
@wutongluxjtu @bingxuebage @lgengsy

**Comment by Android4MediaPlayer** [comment]
@all,use TextureMediaPlayer

**Comment by zhanggao** [comment]
@Android4MediaPlayer SurfaceView 用 TextureMediaPlayer 是不是还会黑屏？

**Comment by jinyunfeng** [comment]
@gnwell @bbcallen 这个问题有没有一个好的解决方案，从后台切到前台reconfigure后无法输出有效的数据，是因为没有关键帧mediacodec无法解出有效数据吗？如何去解决这个问题？

**Comment by jinyunfeng** [comment]
@gnwell @bbcallen 后台切到前台后数据有问题，既无法得到关键帧，不能保证解码的正常，这个是本质原因吧？由于surface的变化重新create mediacodec并不是造成画面问题的原因。有没有可行的方案？

**Comment by raymond1012** [comment]
可以尝试用opengl来代替目前的surface

在 2017年3月15日 下午11:39，jinyunfeng <notifications@github.com>写道：

**Comment by jinyunfeng** [comment]
请问这个导致这个现象的原因是什么？是因为数据的问题mediacodec无法正常输出解码还是因为surface的变化导致的解码错误？

**Comment by raymond1012** [comment]
surface从后台切换到前台有些系统会等待下个关键帧才能渲染

2017-03-16 10:06 GMT+08:00 jinyunfeng <notifications@github.com>:

**Comment by jinyunfeng** [comment]
好的，谢谢，我先试试自己的思路，然后再去尝试你的思路，很感谢

**Comment by jinyunfeng** [comment]
依然没有解决问题，如何使用OpenGL 代替surface，能否详细说一下这个流程

**Comment by jinyunfeng** [comment]
@gnwell 你使用surfaceview实现了切回前台不黑一会的效果了吗？如果实现了，请问是如何实现的？

**Comment by wzybupt** [comment]
@1325679717 我这边会报 Cannot setSurfaceTexture to a released SurfaceTexture 这个异常，虽然surfaceTexture已经保存了，但是还是会被release掉。

**Comment by weigtman** [comment]
03-14 17:08:42.220 29823-29823/com.example.zhangyang.ijktest D/IjkVideoView: MEDIA_INFO_VIDEO_ROTATION_CHANGED: 0
03-14 17:23:50.508 31014-31014/com.example.zhangyang.ijktest D/IjkVideoView: Error: -10000,0
03-14 17:24:35.307 31155-31155/com.example.zhangyang.ijktest D/IjkVideoView: MEDIA_INFO_VIDEO_ROTATION_CHANGED: 0
和
03-14 16:33:36.396 27148-27183/com.example.zhangyang.ijktest E/IJKMEDIA: SPS unavailable in decode_picture_timing
03-14 16:33:36.396 27148-27183/com.example.zhangyang.ijktest E/IJKMEDIA: non-existing PPS 0 referenced
03-14 16:33:36.396 27148-27183/com.example.zhangyang.ijktest E/IJKMEDIA: decode_slice_header error
03-14 16:33:36.396 27148-27183/com.example.zhangyang.ijktest E/IJKMEDIA: no frame!

感谢~

**Comment by kaihuang666** [comment]
//GSYvideoPlayer已经这么做了,不过我却发现在电视上SurfaceView渲染比SurfaceTextureView好太多，比如我这台海信居然可以打开画质引擎和HDR，所以在电视上就忍了。手机上的效果差别不大。
    @Override
    public void onSurfaceTextureAvailable(SurfaceTexture texture, int width, int height) {
        if (mSaveTexture == null) {
            mSaveTexture = texture;
            mSurface = new Surface(texture);
            if (mIGSYSurfaceListener != null) {
                mIGSYSurfaceListener.onSurfaceAvailable(mSurface);
            }
        } else {
            setSurfaceTexture(mSaveTexture);
            if (mIGSYSurfaceListener != null) {
                mIGSYSurfaceListener.onSurfaceAvailable(mSurface);
            }
        }
    }
