### ISSUE TITLE
0.5.1版本的module-lite.sh编译的结果好多以前旧版本可以播放的视频格式现在都播放不了了！

### ISSUE THREAD

**Issue by dianyou1215** [Bilibili/ijkplayer#1326]

**Comment by dianyou1215** [comment]
05-19 13:48:16.801: D/MediaPlayer(10220): Don't notify duration to com.dotgame.android!
05-19 13:48:17.105: I/SurfaceView(10220): updateWindow -- setFrame
05-19 13:48:17.124: E/MediaPlayer(10220): error (1, -2147483648)
05-19 13:48:17.132: I/SurfaceView(10220): updateWindow -- OnPreDrawListener, mHaveFrame = true
05-19 13:48:17.160: D/OpenGLRenderer(10220): prepareDirty (0.00, 0.00, 720.00, 1280.00) opaque 1 <0x7b879380>
05-19 13:48:17.161: D/OpenGLRenderer(10220): drawRect multiDraw CustomTopView @43c3a9a8 paint 0x73c99e50 id 5 style 0 AA 0 color 0xff222222
05-19 13:48:17.161: D/OpenGLRenderer(10220): drawRect multiDraw View @421c81b8 paint 0x779be8d0 id 5 style 0 AA 0 color 0xffcccccc
05-19 13:48:17.162: D/OpenGLRenderer(10220): finish <0x7b879380>
05-19 13:48:17.166: D/MediaPlayer(10220): handleMessage msg:(100, 1, -2147483648)
05-19 13:48:17.167: E/MediaPlayer(10220): Error (1,-2147483648)
05-19 13:48:17.167: E/MediaPlayer(10220): stop called in state 0
05-19 13:48:17.167: E/MediaPlayer(10220): error (-38, 0)
05-19 13:48:17.177: D/IJKMEDIA(10220): IjkMediaPlayer_native_setup
05-19 13:48:17.177: D/IJKMEDIA(10220): ffpipeline_create_from_android()
05-19 13:48:17.177: D/IJKMEDIA(10220): ijkmp_set_inject_opaque()=void
05-19 13:48:17.177: D/IJKMEDIA(10220): ijkmp_android_set_mediacodec_select_callback()
05-19 13:48:17.177: D/IJKMEDIA(10220): ffpipeline_set_mediacodec_select_callback
05-19 13:48:17.177: D/IJKMEDIA(10220): ijkmp_android_set_mediacodec_select_callback()=void
05-19 13:48:17.178: D/IJKMEDIA(10220): IjkMediaPlayer_native_setLogLevel(6)
05-19 13:48:17.178: D/IJKMEDIA(10220): moncleanup
05-19 13:48:17.178: D/IJKMEDIA(10220): IjkMediaPlayer_setOptionLong
05-19 13:48:17.178: D/IJKMEDIA(10220): IjkMediaPlayer_setOptionLong
05-19 13:48:17.178: D/IJKMEDIA(10220): IjkMediaPlayer_setOptionLong
05-19 13:48:17.178: D/IJKMEDIA(10220): IjkMediaPlayer_setOptionLong
05-19 13:48:17.178: D/IJKMEDIA(10220): IjkMediaPlayer_setOptionLong
05-19 13:48:17.178: D/IJKMEDIA(10220): IjkMediaPlayer_setOptionLong
05-19 13:48:17.178: D/IJKMEDIA(10220): IjkMediaPlayer_setOptionLong
05-19 13:48:17.178: D/IJKMEDIA(10220): IjkMediaPlayer_setOptionLong
05-19 13:48:17.178: D/IJKMEDIA(10220): IjkMediaPlayer_setOption
05-19 13:48:17.179: D/IJKMEDIA(10220): IjkMediaPlayer_setOptionLong
05-19 13:48:17.179: D/IJKMEDIA(10220): IjkMediaPlayer_setOptionLong
05-19 13:48:17.179: D/IJKMEDIA(10220): IjkMediaPlayer_setOptionLong
05-19 13:48:17.179: D/IJKMEDIA(10220): IjkMediaPlayer_setOptionLong
05-19 13:48:17.179: D/IJKMEDIA(10220): IjkMediaPlayer_setDataSourceAndHeaders
05-19 13:48:17.179: V/IJKMEDIA(10220): setDataSource: path http://182.92.4.93:1122/VideoParse/YoukuM3U8/XNzMwMjA4MDM2/flvhd
05-19 13:48:17.179: D/IJKMEDIA(10220): ijkmp_set_data_source(url="http://182.92.4.93:1122/VideoParse/YoukuM3U8/XNzMwMjA4MDM2/flvhd")
05-19 13:48:17.179: D/IJKMEDIA(10220): ijkmp_set_data_source(url="http://182.92.4.93:1122/VideoParse/YoukuM3U8/XNzMwMjA4MDM2/flvhd")=0
05-19 13:48:17.179: D/IJKMEDIA(10220): IjkMediaPlayer_setVideoSurface
05-19 13:48:17.179: D/IJKMEDIA(10220): ijkmp_set_android_surface(surface=0x75d0001d)
05-19 13:48:17.179: D/IJKMEDIA(10220): ffpipeline_set_surface()
05-19 13:48:17.179: D/IJKMEDIA(10220): ijkmp_set_android_surface(surface=0x75d0001d)=void
05-19 13:48:17.180: D/IJKMEDIA(10220): IjkMediaPlayer_prepareAsync
05-19 13:48:17.180: D/IJKMEDIA(10220): ijkmp_prepare_async()
05-19 13:48:17.180: I/IJKMEDIA(10220): SDL_RunThread: [11282] ff_msg_loop
05-19 13:48:17.180: D/IJKMEDIA(10220): message_loop
05-19 13:48:17.181: D/dalvikvm(10220): threadid=41: interp stack at 0x7bda0000
05-19 13:48:17.181: D/IJKMEDIA(10220): FFP_MSG_FLUSH:
05-19 13:48:17.184: D/IJKMEDIA(10220): ijkmp_prepare_async()=0
05-19 13:48:17.184: I/IJKMEDIA(10220): SDL_RunThread: [11283] ff_vout
05-19 13:48:17.184: I/IJKMEDIA(10220): SDL_RunThread: [11284] ff_read
05-19 13:48:17.185: D/dalvikvm(10220): threadid=42: interp stack at 0x7bebe000
05-19 13:48:17.186: D/jdwp(10220):     --> RUNNING, Not SUSPENDED
05-19 13:48:17.187: W/MediaPlayer(10220): mediaplayer went away with unhandled events
05-19 13:48:17.187: E/IJKMEDIA(10220): Protocol not on whitelist 'http,https,tls,rtp,tcp,udp,crypto'!
05-19 13:48:17.187: E/IJKMEDIA(10220): http://182.92.4.93:1122/VideoParse/YoukuM3U8/XNzMwMjA4MDM2/flvhd: Invalid argument
05-19 13:48:17.188: D/IJKMEDIA(10220): FFP_MSG_ERROR: 0
05-19 13:48:17.188: I/IJKMEDIA(10220): SDL_JNI_DetachThreadEnv: [11284]
05-19 13:48:17.188: D/jdwp(10220):     --> RUNNING, Not SUSPENDED
05-19 13:48:17.192: D/jdwp(10220):     --> RUNNING, Not SUSPENDED
05-19 13:48:17.194: D/jdwp(10220):     --> RUNNING, Not SUSPENDED
05-19 13:48:17.197: D/dalvikvm(10220): threadid=42: bye!
05-19 13:48:17.258: I/SurfaceView(10220): updateWindow -- setFrame
05-19 13:48:17.290: I/SurfaceView(10220): updateWindow -- OnPreDrawListener, mHaveFrame = true
05-19 13:48:17.309: D/OpenGLRenderer(10220): prepareDirty (0.00, 0.00, 720.00, 1280.00) opaque 1 <0x7b879380>
05-19 13:48:17.310: D/OpenGLRenderer(10220): drawRect multiDraw CustomTopView @43c3a9a8 paint 0x73c99e50 id 5 style 0 AA 0 color 0xff222222
05-19 13:48:17.310: D/OpenGLRenderer(10220): drawRect multiDraw View @421c81b8 paint 0x779be8d0 id 5 style 0 AA 0 color 0xffcccccc
05-19 13:48:17.311: D/OpenGLRenderer(10220): finish <0x7b879380>
05-19 13:48:17.382: I/SurfaceView(10220): updateWindow -- setFrame
05-19 13:48:17.415: I/SurfaceView(10220): updateWindow -- OnPreDrawListener, mHaveFrame = true
05-19 13:48:17.430: D/OpenGLRenderer(10220): prepareDirty (0.00, 0.00, 720.00, 1280.00) opaque 1 <0x7b879380>
05-19 13:48:17.431: D/OpenGLRenderer(10220): drawRect multiDraw CustomTopView @43c3a9a8 paint 0x73c99e50 id 5 style 0 AA 0 color 0xff222222
05-19 13:48:17.431: D/OpenGLRenderer(10220): drawRect multiDraw View @421c81b8 paint 0x779be8d0 id 5 style 0 AA 0 color 0xffcccccc
05-19 13:48:17.432: D/OpenGLRenderer(10220): finish <0x7b879380>
05-19 13:48:17.944: I/SurfaceView(10220): updateWindow -- setFrame
05-19 13:48:17.984: D/OpenGLRenderer(10220): prepareDirty (0.00, 0.00, 720.00, 1280.00) opaque 1 <0x7b879380>
05-19 13:48:17.985: D/OpenGLRenderer(10220): drawRect multiDraw CustomTopView @43c3a9a8 paint 0x73c99e50 id 5 style 0 AA 0 color 0xff222222

**Comment by dianyou1215** [comment]
@bbcallen log已经给出来了！用module-lite.sh编译生成的so可以播放所有的视频和直播吗？

**Comment by bbcallen** [comment]
Of course module-lite.sh doesn't support all format/protocol.
But for this url, the demo works well.
```
05-19 15:01:31.869 29482-29482/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_prepare_async()=0
05-19 15:01:31.869 29482-29661/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [29661] ff_vout
05-19 15:01:31.871 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [29662] ff_read
05-19 15:01:31.871 29482-29662/tv.danmaku.ijk.media.example D/IJKMEDIA: Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto'
05-19 15:01:31.938 29482-29601/tv.danmaku.ijk.media.example D/OpenGLRenderer: endAllStagingAnimators on 0xddf59300 (ListView) with handle 0xe12ff1c0
05-19 15:01:32.063 29482-29662/tv.danmaku.ijk.media.example D/IJKMEDIA: Format hls,applehttp probed with size=2048 and score=100
05-19 15:01:32.063 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA: HLS request for url 'http://182.118.58.52/67773F9EEA13181754B0D03D23/030002010053A6E69FB9D0020AEE1EDFAF52EA-5D53-B125-F3F6-E0B06AB62C6B.flv.ts?ts_start=0&ts_end=6.567&ts_seg_no=0&ts_keyframe=1', offset 0, playlist 0
05-19 15:01:32.260 29482-29662/tv.danmaku.ijk.media.example D/IJKMEDIA: Format mpegts probed with size=2048 and score=100
05-19 15:01:32.261 29482-29662/tv.danmaku.ijk.media.example D/IJKMEDIA: stream=0 stream_type=1b pid=101 prog_reg_desc=
05-19 15:01:32.261 29482-29662/tv.danmaku.ijk.media.example D/IJKMEDIA: stream=1 stream_type=f pid=102 prog_reg_desc=
05-19 15:01:32.261 29482-29662/tv.danmaku.ijk.media.example D/IJKMEDIA: Before avformat_find_stream_info() pos: 0 bytes read:12570 seeks:0
05-19 15:01:32.268 29482-29662/tv.danmaku.ijk.media.example D/IJKMEDIA: Unknown NAL code: 0 (1424 bits)
05-19 15:01:32.269 29482-29662/tv.danmaku.ijk.media.example D/IJKMEDIA: no picture 
05-19 15:01:32.344 29482-29662/tv.danmaku.ijk.media.example D/IJKMEDIA: All info found
05-19 15:01:32.344 29482-29662/tv.danmaku.ijk.media.example D/IJKMEDIA: After avformat_find_stream_info() pos: 30268 bytes read:35290 seeks:0 frames:50
05-19 15:01:32.345 29482-29662/tv.danmaku.ijk.media.example E/IJKMEDIA: Option http-detect-range-support not found.
05-19 15:01:32.345 29482-29662/tv.danmaku.ijk.media.example D/IJKMEDIA: Before avformat_find_stream_info() pos: 1803 bytes read:1803 seeks:0
05-19 15:01:32.346 29482-29662/tv.danmaku.ijk.media.example D/IJKMEDIA: Unknown NAL code: 0 (1424 bits)
05-19 15:01:32.347 29482-29662/tv.danmaku.ijk.media.example D/IJKMEDIA: no picture 
05-19 15:01:32.353 29482-29662/tv.danmaku.ijk.media.example D/IJKMEDIA: All info found
05-19 15:01:32.354 29482-29662/tv.danmaku.ijk.media.example D/IJKMEDIA: After avformat_find_stream_info() pos: 1803 bytes read:1803 seeks:0 frames:50
05-19 15:01:32.354 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA: max_frame_duration: 10.000
05-19 15:01:32.354 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA: Input #0, hls,applehttp, from 'http://182.92.4.93:1122/VideoParse/YoukuM3U8/XNzMwMjA4MDM2/flvhd':
05-19 15:01:32.354 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA:   Duration: 
05-19 15:01:32.354 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA: 00:01:19.40
05-19 15:01:32.354 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA: , start: 
05-19 15:01:32.354 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA: 10.000000
05-19 15:01:32.354 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA: , bitrate: 
05-19 15:01:32.354 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA: 0 kb/s
05-19 15:01:32.354 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA:   Program 0 
05-19 15:01:32.355 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA:     Metadata:
05-19 15:01:32.355 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA:       variant_bitrate : 
05-19 15:01:32.355 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA: 0
05-19 15:01:32.355 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA:     Stream #0:0
05-19 15:01:32.355 29482-29662/tv.danmaku.ijk.media.example D/IJKMEDIA: , 21, 1/90000
05-19 15:01:32.355 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA: : Video: h264, 5 reference frames ([27][0][0][0] / 0x001B), yuv420p(left), 512x288 [SAR 1:1 DAR 16:9], 1/30
05-19 15:01:32.355 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA: , 
05-19 15:01:32.355 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA: 15 fps, 
05-19 15:01:32.355 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA: 15 tbr, 
05-19 15:01:32.355 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA: 90k tbn, 
05-19 15:01:32.355 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA: 30 tbc
05-19 15:01:32.355 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA:     Stream #0:1
05-19 15:01:32.355 29482-29662/tv.danmaku.ijk.media.example D/IJKMEDIA: , 29, 1/90000
05-19 15:01:32.355 29482-29662/tv.danmaku.ijk.media.example I/IJKMEDIA: : Audio: aac ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 34 kb/s
```

**Comment by dianyou1215** [comment]
@bbcallen 
我这边报错是什么意思啊？
05-19 13:48:17.187: W/MediaPlayer(10220): mediaplayer went away with unhandled events
05-19 13:48:17.187: E/IJKMEDIA(10220): Protocol not on whitelist 'http,https,tls,rtp,tcp,udp,crypto'!
05-19 13:48:17.187: E/IJKMEDIA(10220): http://182.92.4.93:1122/VideoParse/YoukuM3U8/XNzMwMjA4MDM2/flvhd: Invalid argument
05-19 13:48:17.188: D/IJKMEDIA(10220): FFP_MSG_ERROR: 0

**Comment by bbcallen** [comment]
No idea why this happens, without code.
