### ISSUE TITLE
Android使用IjkMediaPlayer播放hls直播会卡帧率

### ISSUE THREAD

**Issue by wangrunxiang** [Bilibili/ijkplayer#1329]
如题，一般低分辨率的游戏直播不卡，QQ飞车，穿越火线不卡，高分辨率的游戏直播会卡帧率，渐渐的地画面跟不上声音，比如英雄联盟

**Comment by gnwell** [comment]
是否软解?得上硬解才行

**Comment by gnwell** [comment]
是否软解?得上硬解才行

**Comment by gnwell** [comment]
而且你还得看看流是不是本身就音视频不同步了

**Comment by wangrunxiang** [comment]
我试了硬解，确实不卡了，但是硬解，部分机子只有声音没有图像，这个要咋解决？ @bbcallen

**Comment by wangrunxiang** [comment]
@gnwell

**Comment by wangrunxiang** [comment]
@gnwell

**Comment by wangrunxiang** [comment]
流是音视频同步的，应该是视频卡帧率了，音频不卡帧率导致的不同步吧 @gnwell
