### ISSUE TITLE
如何拿到最终播放地址

### ISSUE THREAD

**Issue by zhennayw** [Bilibili/ijkplayer#1331]
1、由于http会重新指向新的播放地址，我们如何能拿到最终播放的地址？有接口吗？
2、能拿到播放影片的码率吗？

非常感谢！！

**Comment by fjzboy** [comment]
setdatasource之前，先自己解析302吧，把最终得到的真正的地址设置给setdatasource

**Comment by bbcallen** [comment]
1. Modify libavformat/http.c
2. See log.

**Comment by zhennayw** [comment]
thanks very much
