### ISSUE TITLE
加载大音频 等待 时间比较长

### ISSUE THREAD

**Issue by changshuai** [Bilibili/ijkplayer#1332]
我们音频使用的是opus的格式，发现普通大小的加载速度还可以，但是如果比较大的文件，比如10分钟以上的，就会等待很长时间，大约15秒左右。请问这个问题有没有办法优化？

**Comment by bbcallen** [comment]
Sorry, not familiar with opus.

**Comment by changshuai** [comment]
不好意思，再问一个问题？这个加载等待的时间主要和什么因素有关系？有没办法通过改变 缓存大小 起到优化的作用？

**Comment by bbcallen** [comment]
1. No idea without profile
2. Depending on the answer of question 1.
