### ISSUE TITLE
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

### ISSUE THREAD

**Issue by General110** [Bilibili/ijkplayer#1338]
新手，不知道哪里出错！MP4正常 MKV就不行

05-22 20:12:31.988 2149-2149/com.gen.video D/IJKMEDIA: IjkMediaPlayer_native_profileBegin
05-22 20:12:31.988 2149-2149/com.gen.video W/IJKMEDIA: monstartup already called
                                                            
                                                            [ 05-22 20:12:31.988  2149: 2149 E/         ]
                                                            SurfaceView doesn't support rotation (0)!
                                                            
                                                            
                                                            [ 05-22 20:12:31.993  4297: 4524 D/         ]
                                                            file:device/hisi/common/liblights/lights.c, func:set_light_backlight, brightness=97
05-22 20:12:32.103 2149-2149/com.gen.video D/IJKMEDIA: IjkMediaPlayer_native_setup
05-22 20:12:32.104 2149-2149/com.gen.video D/IJKMEDIA: ffpipeline_create_from_android()
05-22 20:12:32.104 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_set_inject_opaque(0x576)
05-22 20:12:32.104 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_set_inject_opaque()=void
05-22 20:12:32.104 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
05-22 20:12:32.104 2149-2149/com.gen.video D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
05-22 20:12:32.104 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
05-22 20:12:32.104 2149-2149/com.gen.video D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(8)
05-22 20:12:32.104 2149-2149/com.gen.video D/IJKMEDIA: moncleanup
05-22 20:12:32.104 2149-2149/com.gen.video D/IJKMEDIA: IjkMediaPlayer_setOptionLong
05-22 20:12:32.104 2149-2149/com.gen.video D/IJKMEDIA: IjkMediaPlayer_setOptionLong
05-22 20:12:32.104 2149-2149/com.gen.video D/IJKMEDIA: IjkMediaPlayer_setOptionLong
05-22 20:12:32.104 2149-2149/com.gen.video D/IJKMEDIA: IjkMediaPlayer_setOptionLong
05-22 20:12:32.104 2149-2149/com.gen.video D/IJKMEDIA: IjkMediaPlayer_setOptionLong
05-22 20:12:32.104 2149-2149/com.gen.video D/IJKMEDIA: IjkMediaPlayer_setOptionLong
05-22 20:12:32.104 2149-2149/com.gen.video D/IJKMEDIA: IjkMediaPlayer_setOptionLong
05-22 20:12:32.105 2149-2149/com.gen.video D/tv.danmaku.ijk.media.player.IjkMediaPlayer: Couldn't open file on client side, trying server side
05-22 20:12:32.105 2149-2149/com.gen.video D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
05-22 20:12:32.105 2149-2149/com.gen.video V/IJKMEDIA: setDataSource: path http://127.0.0.1:8083/火线下的江湖大佬粤语HDTV01.mkv
05-22 20:12:32.105 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_set_data_source(url="http://127.0.0.1:8083/火线下的江湖大佬粤语HDTV01.mkv")
05-22 20:12:32.105 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_set_data_source(url="http://127.0.0.1:8083/火线下的江湖大佬粤语HDTV01.mkv")=0
05-22 20:12:32.105 2149-2149/com.gen.video W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
05-22 20:12:32.105 2149-2149/com.gen.video D/IJKMEDIA: IjkMediaPlayer_prepareAsync
05-22 20:12:32.105 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_prepare_async()
05-22 20:12:32.106 2149-6142/com.gen.video I/IJKMEDIA: SDL_RunThread: [6142] ff_msg_loop
05-22 20:12:32.106 2149-6142/com.gen.video D/IJKMEDIA: message_loop
05-22 20:12:32.106 2149-2149/com.gen.video I/IJKMEDIA: aout_set_volume(1.000000, 1.000000)
05-22 20:12:32.109 2149-6142/com.gen.video D/IJKMEDIA: FFP_MSG_FLUSH:
05-22 20:12:32.112 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_prepare_async()=0
05-22 20:12:32.113 2149-2149/com.gen.video D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
05-22 20:12:32.113 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_set_android_surface(surface=0xbed5c890)
05-22 20:12:32.113 2149-6143/com.gen.video I/IJKMEDIA: SDL_RunThread: [6143] ff_vout
05-22 20:12:32.113 2149-2149/com.gen.video D/IJKMEDIA: ffpipeline_set_surface()
05-22 20:12:32.113 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_set_android_surface(surface=0xbed5c890)=void
05-22 20:12:32.113 2149-6144/com.gen.video I/IJKMEDIA: SDL_RunThread: [6144] ff_read
05-22 20:12:32.199 2149-6144/com.gen.video I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [6144]
05-22 20:12:32.199 2149-6142/com.gen.video D/IJKMEDIA: FFP_MSG_ERROR: 0
05-22 20:12:32.280 2149-2149/com.gen.video E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
05-22 20:12:34.157 2149-2149/com.gen.video D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
05-22 20:12:34.157 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
05-22 20:12:34.157 2149-2149/com.gen.video D/IJKMEDIA: ffpipeline_set_surface()
05-22 20:12:34.157 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
05-22 20:12:34.545 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_stop()
05-22 20:12:34.545 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_stop()=0
05-22 20:12:34.545 2149-2149/com.gen.video D/IJKMEDIA: IjkMediaPlayer_release
05-22 20:12:34.545 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
05-22 20:12:34.545 2149-2149/com.gen.video D/IJKMEDIA: ffpipeline_set_surface()
05-22 20:12:34.545 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
05-22 20:12:34.545 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_shutdown_l()
05-22 20:12:34.549 2149-6142/com.gen.video D/IJKMEDIA: message_loop exit
05-22 20:12:34.549 2149-6142/com.gen.video I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [6142]
05-22 20:12:34.552 2149-6143/com.gen.video I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [6143]
05-22 20:12:34.553 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_shutdown_l()=void
05-22 20:12:34.553 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_dec_ref(): ref=0
05-22 20:12:34.553 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_shutdown_l()
05-22 20:12:34.553 2149-2149/com.gen.video D/IJKMEDIA: ijkmp_shutdown_l()=void
05-22 20:12:34.555 2149-2149/com.gen.video D/IJKMEDIA: IjkMediaPlayer_native_profileEnd
05-22 20:12:34.555 2149-2149/com.gen.video W/IJKMEDIA: moncleanu already called

**Comment by bbcallen** [comment]
MKV is not supported by default.
See README.

**Comment by a4tech** [comment]
How about m3u8 ?

http://cdn-fms.rbs.com.br/vod/hls_sample1_manifest.m3u8





    http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8
    http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8
    http://devimages.apple.com/iphone/samples/bipbop/gear1/prog_index.m3u8
    http://playertest.longtailvideo.com/adaptive/oceans_aes/oceans_aes.m3u8 (AES encrypted)
    http://playertest.longtailvideo.com/adaptive/captions/playlist.m3u8 (HLS stream with CEA-608 captions)
    http://playertest.longtailvideo.com/adaptive/wowzaid3/playlist.m3u8 (with metadata)
    http://content.jwplatform.com/manifests/vM7nH0Kl.m3u8
    http://cdn-fms.rbs.com.br/hls-vod/sample1_1500kbps.f4v.m3u8
    http://cdn-fms.rbs.com.br/vod/hls_sample1_manifest.m3u8
    http://vevoplaylist-live.hls.adaptive.level3.net/vevo/ch1/appleman.m3u8 (LIVE TV)
    http://vevoplaylist-live.hls.adaptive.level3.net/vevo/ch2/appleman.m3u8 (LIVE TV)
    http://vevoplaylist-live.hls.adaptive.level3.net/vevo/ch3/appleman.m3u8 (LIVE TV)
    http://www.nacentapps.com/m3u8/index.m3u8 (VOD)
    http://srv6.zoeweb.tv:1935/z330-live/stream/playlist.m3u8 (LIVE TV)
    http://content.jwplatform.com/manifests/vM7nH0Kl.m3u8 (link protection, video not encrypted)
    http://sample.vodobox.net/skate_phantom_flex_4k/skate_phantom_flex_4k.m3u8 (4K)
    http://cdn3.viblast.com/streams/hls/airshow/playlist.m3u8 (4K)
