### ISSUE TITLE
func_display_overlay_l: NULL native_window

### ISSUE THREAD

**Issue by ityancs** [Bilibili/ijkplayer#1339]
I find this log, When i try to toggle the fullscreen, I find this code in 
[https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijksdl/android/ijksdl_vout_android_nativewindow.c](func_display_overlay_l: NULL native_window).
Could you please tell me what's the problem and how could i can get this log.
Thank you very much!

**Comment by bbcallen** [comment]
It means you haven't call setSurface/setDisplay with valid Surface/SurfaceHolder,
Or you have called setSurface(NULL)/setDisplay(NULL).

**Comment by ityancs** [comment]
I occur a problem that the SurfaceView destroy but it does't create when I remove from the ViewGroup and then add to another ViewGroup sometimes(not always), the media controller is shown,but the picture is Gone.

**Comment by bbcallen** [comment]
Removing from parent view could cause surface destroyed. It's your responsibility to set new surface back.

**Comment by bbcallen** [comment]
Since you have created new issue #1341 with different title.
This issue should be closed.
