### ISSUE TITLE
Cannot play a specific video format with codec MPEG4

### ISSUE THREAD

**Issue by devsherif** [Bilibili/ijkplayer#134]
Hello,

First of all, thanks for this great repository. Building the project was really easy and smooth.

I am facing an issue when i try to play a video file i have using this player. As per VLC, this is the Media information of my video:
![screen shot 2014-12-11 at 4 34 38 pm](https://cloud.githubusercontent.com/assets/612687/5395644/d61acb24-8153-11e4-9463-269cbd8b68b8.png)

I used a lot of android apps using FFMPEG library, and they cannot run it except one app which i know that it using FFMPEG library, but it seems that they have this codec included in their FFMPEG library.

Can you let me know if i can somehow make your library able to play my video?

Appreciate your support.

Regards,
Sherif

**Comment by flztsj** [comment]
开启mpeg4支持的话，我这边开启这个才行
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mpeg4"

**Comment by lijie815917** [comment]
确实，开启mpeg4，要在module-lite.sh上加
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mpeg4"
