### ISSUE TITLE
表示在win10操作系统编译失败，各种失败，求有编译成功的大神带路，万分感谢

### ISSUE THREAD

**Issue by microsoftBoy** [Bilibili/ijkplayer#1340]
有没有在win下的教程啊，求解各种问题，
执行这个后sh ./compile-ffmpeg.sh all
中间省略。。。（无数字）
最后License: LGPL version 2.1 or later
Creating config.mak, config.h, and doc/config.texi...

WARNING: arm-linux-androideabi-pkg-config not found, library detection may fail.
make: execvp: ./version.sh: Permission denied
make: /bin/sh：命令未找到
libavfilter/Makefile:323: recipe for target 'clean' failed
make: *** [clean] Error 127
给了个这个，不知道该怎么解决

**Comment by bbcallen** [comment]
1. Fix the scripts by yourself.
2. Install VMWare and Install a debian/ubuntu/... on it.
3. Sell your PC and buy a mac/macbook

**Comment by zhaohuiyuliang** [comment]
2019年Mac环境下遇到
License: LGPL version 2.1 or later
Creating configuration files ...

WARNING: arm-linux-androideabi-pkg-config not found, library detection may fail.

--------------------
[*] compile ffmpeg
--------------------
In file included from ./libavutil/internal.h:42:0,
                 from ./libavutil/common.h:467,
                 from ./libavutil/avutil.h:296,
                 from ./libavutil/avassert.h:31,
                 from libavfilter/aeval.c:26:
./libavutil/timer.h:38:31: fatal error: linux/perf_event.h: No such file or directory
