### ISSUE TITLE
Android openGL

### ISSUE THREAD

**Issue by FirmianaRain** [Bilibili/ijkplayer#1342]
Hi， I'm a little confused about some code in file Ijksdl_elg.c.
Why call `eglMakeCurrent` and `eglReleaseThread` after `IJK_EGL_display_internal`? Does it mean anything?

**Comment by bbcallen** [comment]
Does it broke anything?

The best place to call these two functions, is the start/end of the display thread.
But surface can be changed by setSurface() at anytime, so the synchronization implement could be very complicated.

**Comment by FirmianaRain** [comment]
NO, this code does not break anything.
If a new Surface was set to player, it seems that `IJK_EGL_terminate` will be called in function `SDL_VoutAndroid_SetNativeWindow_l`.
`eglMakeCurrent` and `eglReleaseThread` will be invoked in `IJK_EGL_terminate`.

**Comment by bbcallen** [comment]
Yes, but SDL_VoutAndroid_SetNativeWindow_l is not called from display thread.

**Comment by FirmianaRain** [comment]
OK. Thank you for your reply.
