### ISSUE TITLE
ijkPlayer for IPv6-only

### ISSUE THREAD

**Issue by SoXeon** [Bilibili/ijkplayer#1343]
IJKPlayer目前有适配IPv6-only的计划吗？
苹果早在WWDC2015即已宣布在ios9支持IPv6-only的网络服务，并且要求2016年提交到App Store的应用必须兼容IPv6-only的网络。

并在今年5月4日正式发布声明：自今年6月1日开始，App Store策略要求所有iOS应该必需包含对 IPv6-only 网络的的支持，所有提交至苹果App Store的应用申请必须要兼容面IPv6-only网络。

目前通过脚本检查到IJK中使用到[u'inet_aton']函数，请问有什么好的解决方法吗？

**Comment by bbcallen** [comment]
I don't think inet_aton usage is disallowed at all. Apple only disallows it's misuses.
```
Using low-level networking APIs. Some apps work directly with sockets and other raw network APIs such as gethostbyname, gethostbyname2, and inet_aton. These APIs are prone to misuse or they only support IPv4—for example, resolving hostnames for the AF_INET address family, rather than the AF_UNSPEC address family. See Use High-Level Networking Frameworks.
```
