### ISSUE TITLE
E/libEGL: call to OpenGL ES API with no current context (logged once per thread)

### ISSUE THREAD

**Issue by ShawnAnn** [Bilibili/ijkplayer#1345]
我在Android平台集成了IjkPlayer,使用分段播放模式播放视频，在大多数手机上一切正常，但在华为p9和华为p8(也许还有别的手机)上出现错误E/libEGL: call to OpenGL ES API with no current context (logged once per thread)，我现在不知道该如何定位和解决这个错误，希望大伙提提意见

**Comment by ShawnAnn** [comment]
I've done.I finally found the reason.It is because of  the runtime permission,but the error is "E/libEGL: call to OpenGL ES API with no current context (logged once per thread)",so I got a wrong way.

**Comment by burypen** [comment]
I met the same problem as you, how you solve it ?

**Comment by ShawnAnn** [comment]
@burypen  runtime permission,just like above

**Comment by burypen** [comment]
What permissions do i need to add? thank you very much!

**Comment by ShawnAnn** [comment]
@burypen just like file read...when you use ffconcat file to play a video.

**Comment by spaul13** [comment]
I am getting the same problem for Nexus 6P while doing video decoder. I didn't get the point. 

Can anyone (specifically @ShawnAnn, @burypen ) tell me what I have to include exactly in those java folders to get those runtime permissions? Thanks a lot in advance.
