### ISSUE TITLE
android 播放 demo  出错（使用eclipse）

### ISSUE THREAD

**Issue by ailialy** [Bilibili/ijkplayer#1347]
播放 m3u8， 程序崩溃， 播放demo
LOG:
05-24 15:17:57.639: D/IJKMEDIA(12339): Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto'
05-24 15:17:57.644: A/libc(12339): @@@ ABORTING: INVALID HEAP ADDRESS IN dlfree addr=0x5ee4ce10
05-24 15:17:57.649: A/libc(12339): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 12539 (ff_read)
我该如何修改？

**Comment by ailialy** [comment]
当我播放 demo中的 m3u8 时， 播放一回就回 奔溃，  用我自己的 m3u8地址， 有的时候 播放一两秒，有的时候  直接 奔溃， 
05-24 15:17:57.644: A/libc(12339): @@@ ABORTING: INVALID HEAP ADDRESS IN dlfree addr=0x5ee4ce10
05-24 15:17:57.649: A/libc(12339): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 12539 (ff_read) 都是这个log..   看log 像是C++ 是 free了一个 野指针，我该如何查找 这个问题呢？

**Comment by Android4MediaPlayer** [comment]
使用的是哪一个版本

**Comment by ailialy** [comment]
@Android4MediaPlayer  log：
05-24 16:27:36.399: I/IJKMEDIA(8564): av_version_info: ff3.0--ijk0.4.5.1--dev0.4.5--rc10

log中  有看到  这样一条log 不知道 是否有影响
05-24 16:27:36.269: W/J4A(8564): J4ALoader: Ignore: 'android.media.PlaybackParams' need API 16

使用 NDK－r10e编译，SDK 版本 是  6.0
