### ISSUE TITLE
播放视频很卡，a-cache v-cache个位数，这两个参数什么意思

### ISSUE THREAD

**Issue by LikeSpeedSong** [Bilibili/ijkplayer#1350]
http://cceappmedia.streaming.mediaservices.chinacloudapi.cn/f8955b77-61fd-446c-9812-d82b9369bd62/%E6%9C%BA%E8%BD%A620160518122058.ism/Manifest(format=m3u8-aapl)
以上是url 放到avplayer里面不会卡顿

**Comment by bbcallen** [comment]
a-cache means audio cache.
v-cache means video cache.

**Comment by LikeSpeedSong** [comment]
为什么我这两个值这么低尼？现在视频播放起来特别卡，有啥解决办法么

**Comment by LikeSpeedSong** [comment]
Format mpegts probed with size=2048 and score=100
stream=0 stream_type=1b pid=12c prog_reg_desc=
Before avformat_find_stream_info() pos: 0 bytes read:9173 seeks:0
Current profile doesn't provide more RBSP data in PPS, skipping
no picture 
All info found
rfps: 14.666667 0.016177
rfps: 14.666667 0.016177
rfps: 14.750000 0.009067
rfps: 14.750000 0.009067
rfps: 14.833333 0.004011
rfps: 14.833333 0.004011
rfps: 14.916667 0.001008
rfps: 14.916667 0.001008
rfps: 15.000000 0.000058
rfps: 15.083333 0.001162
rfps: 15.083333 0.001162
rfps: 15.166667 0.004319
rfps: 15.166667 0.004319
rfps: 15.250000 0.009529
rfps: 15.250000 0.009529
rfps: 15.333333 0.016793
rfps: 15.333333 0.016793
rfps: 29.666667 0.016043
rfps: 29.666667 0.016043
rfps: 29.750000 0.009010
rfps: 29.750000 0.009010
rfps: 29.833333 0.004031
rfps: 29.833333 0.004031
rfps: 29.916667 0.001105
rfps: 30.000000 0.000233
rfps: 45.000000 0.000524
rfps: 60.000000 0.000931
rfps: 120.000000 0.003724
rfps: 240.000000 0.014896
rfps: 29.970030 0.000310
rfps: 59.940060 0.001241
rfps: 14.985015 0.000078
After avformat_find_stream_info() pos: 60536 bytes read:62759 seeks:0 frames:21
HLS request for url 'http://cceappmedia.streaming.mediaservices.chinacloudapi.cn/2290753f-0e3f-46fc-8406-e05ff7bcc371/%E9%97%AA%E8%80%80BLING%E7%9C%BC%E7%BA%BF%E5%A6%8620160518043348.ism/QualityLevels(326634)/Fragments(video=0,format=m3u8-aapl)', offset 0, playlist 3
request: GET /2290753f-0e3f-46fc-8406-e05ff7bcc371/%E9%97%AA%E8%80%80BLING%E7%9C%BC%E7%BA%BF%E5%A6%8620160518043348.ism/QualityLevels(326634)/Fragments(video=0,format=m3u8-aapl) HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Connection: close

Host: cceappmedia.streaming.mediaservices.chinacloudapi.cn

Icy-MetaData: 1

**Comment by bbcallen** [comment]
The log doesn't show anything wrong.
