### ISSUE TITLE
不定时的爆出这个错误，播放器退出，在线等，谢谢，十万火急

### ISSUE THREAD

**Issue by mgoann** [Bilibili/ijkplayer#1352]
05-25 14:10:49.585 1047-1572/com.fengxing.ams.tvclient E/IJKMEDIA: av_read_frame error: ffffff92(?,?,?,?): AVERROR(ETIMEDOUT)
05-25 14:10:49.595 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209302176
05-25 14:10:49.595 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209302176 ok
05-25 14:10:49.635 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 452773..
05-25 14:10:49.635 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320576
05-25 14:10:49.635 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320576 ok
05-25 14:10:49.675 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209337576
05-25 14:10:49.675 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209337576 ok
05-25 14:10:49.685 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 452814..
05-25 14:10:49.715 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 452856..
05-25 14:10:49.715 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209321864
05-25 14:10:49.715 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209321864 ok
05-25 14:10:49.755 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320664
05-25 14:10:49.755 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320664 ok
05-25 14:10:49.765 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 452898..
05-25 14:10:49.795 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 452939..
05-25 14:10:49.805 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209302176
05-25 14:10:49.805 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209302176 ok
05-25 14:10:49.845 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 452981..
05-25 14:10:49.845 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320576
05-25 14:10:49.845 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320576 ok
05-25 14:10:49.875 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453023..
05-25 14:10:49.885 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209337576
05-25 14:10:49.885 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209337576 ok
05-25 14:10:49.925 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453064..
05-25 14:10:49.925 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209321864
05-25 14:10:49.925 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209321864 ok
05-25 14:10:49.955 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453106..
05-25 14:10:49.965 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320664
05-25 14:10:49.965 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320664 ok
05-25 14:10:50.005 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453148..
05-25 14:10:50.005 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209302176
05-25 14:10:50.005 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209302176 ok
05-25 14:10:50.035 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453189..
05-25 14:10:50.055 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320576
05-25 14:10:50.055 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320576 ok
05-25 14:10:50.085 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453231..
05-25 14:10:50.095 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209337576
05-25 14:10:50.095 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209337576 ok
05-25 14:10:50.135 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453273..
05-25 14:10:50.135 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209321864
05-25 14:10:50.135 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209321864 ok
05-25 14:10:50.175 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320664
05-25 14:10:50.175 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320664 ok
05-25 14:10:50.185 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453314..
05-25 14:10:50.215 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453356..
05-25 14:10:50.215 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209302176
05-25 14:10:50.215 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209302176 ok
05-25 14:10:50.255 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320576
05-25 14:10:50.255 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320576 ok
05-25 14:10:50.265 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453398..
05-25 14:10:50.295 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453439..
05-25 14:10:50.305 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209337576
05-25 14:10:50.305 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209337576 ok
05-25 14:10:50.345 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453481..
05-25 14:10:50.345 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209321864
05-25 14:10:50.345 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209321864 ok
05-25 14:10:50.375 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453523..
05-25 14:10:50.385 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320664
05-25 14:10:50.385 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320664 ok
05-25 14:10:50.425 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453564..
05-25 14:10:50.425 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209302176
05-25 14:10:50.425 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209302176 ok
05-25 14:10:50.455 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453606..
05-25 14:10:50.465 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320576
05-25 14:10:50.465 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320576 ok
05-25 14:10:50.505 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453648..
05-25 14:10:50.505 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209337576
05-25 14:10:50.505 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209337576 ok
05-25 14:10:50.535 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453689..
05-25 14:10:50.555 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209321864
05-25 14:10:50.555 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209321864 ok
05-25 14:10:50.585 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453731..
05-25 14:10:50.595 1047-1572/com.fengxing.ams.tvclient E/IJKMEDIA: av_read_frame error: ffffff92(?,?,?,?): AVERROR(ETIMEDOUT)
05-25 14:10:50.595 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320664
05-25 14:10:50.595 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320664 ok
05-25 14:10:50.635 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453773..
05-25 14:10:50.635 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209302176
05-25 14:10:50.635 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209302176 ok
05-25 14:10:50.675 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320576
05-25 14:10:50.675 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320576 ok
05-25 14:10:50.685 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453814..
05-25 14:10:50.715 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453856..
05-25 14:10:50.715 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209337576
05-25 14:10:50.715 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209337576 ok
05-25 14:10:50.755 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209321864
05-25 14:10:50.755 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209321864 ok
05-25 14:10:50.765 134-1611/? D/AmlogicVideoDecoderAwesome:   		  Out PTS: 453898..
05-25 14:10:50.805 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320664
05-25 14:10:50.805 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320664 ok
05-25 14:10:50.845 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209302176
05-25 14:10:50.845 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209302176 ok
05-25 14:10:50.885 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320576
05-25 14:10:50.885 1047-1606/com.fengxing.ams.tvclient I/ACodec: video render this buffer -1209320576 ok
05-25 14:10:51.185 134-594/? V/AudioFlinger: removeTracks_l removing track on session 16,mId 8 
05-25 14:10:51.185 134-594/? V/AudioFlinger: acquireWakeLock_l() AudioOut_8 status 0
05-25 14:10:51.275 134-593/? V/AudioFlinger: removeTracks_l removing track on session 0,mId 7 
05-25 14:10:51.275 134-593/? V/AudioFlinger: acquireWakeLock_l() AudioOut_7 status 0
05-25 14:10:51.295 134-592/? V/AudioFlinger: removeTracks_l removing track on session 0,mId 2 
05-25 14:10:51.295 134-592/? V/AudioFlinger: acquireWakeLock_l() AudioOut_2 status 0
05-25 14:10:51.605 1047-1572/com.fengxing.ams.tvclient I/IJKMEDIA: ffp_toggle_buffering: error: -110
05-25 14:10:51.605 1047-1570/com.fengxing.ams.tvclient D/IJKMEDIA: FFP_MSG_ERROR: 0
05-25 14:10:51.605 1047-1572/com.fengxing.ams.tvclient E/IJKMEDIA: av_read_frame error: ffffff92(?,?,?,?): AVERROR(ETIMEDOUT)
05-25 14:10:51.605 1047-1047/com.fengxing.ams.tvclient E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by pauldu1104** [comment]
我也遇到了，是服务器断开导致的

**Comment by Android4MediaPlayer** [comment]
拉取数据超时了，检查网络或服务器

**Comment by YunhaoYu** [comment]
我也是不定时出现这个错误，正在找原因
05-25 17:13:49.000 14662 14704 I IJKMEDIA: ffp_toggle_buffering: error: -5

05-25 17:13:49.000 14662 14704 E IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown

05-25 17:13:49.000 14662 14702 D IJKMEDIA: FFP_MSG_ERROR: 0

05-25 17:13:49.000 14662 14662 E tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

05-25 17:13:49.000 14662 14662 D IjkVideoView: Error: -10000,0

**Comment by Android4MediaPlayer** [comment]
ETIMEDOUT

**Comment by YunhaoYu** [comment]
目前现状是服务器端和网络不稳定，如何保证出现这种情况时，APP不闪退，请问下有没有什么办法

**Comment by bbcallen** [comment]
Which version are you using?

**Comment by mgoann** [comment]
0.4.4.1

**Comment by YunhaoYu** [comment]
Android平台，0.5.1

**Comment by bbcallen** [comment]
@mgoann, create new player and seek to the last position, when you get error notification.
@YunhaoYu, please don't hijack the topic. It's very confusing. "闪退" mentioned in your comment has nothing to do with the issue creater.

**Comment by mgoann** [comment]
我现在就是这么做的，发现出错后
                       `int position = mVideoView.getCurrentPosition();
                        mVideoView.stopPlayback();
                        mVideoView.release(true);
                        Log.e(TAG, "restart player:" + position);
                        startPlayer(position);
                        return true;`

but why start player with 0 position, i seek to the last postion at OnPreparedListener.

`private void startPlayer(final long position) {
  ....
	mVideoView.setOnPreparedListener(new IMediaPlayer.OnPreparedListener() {
	    @Override
	    public void onPrepared(IMediaPlayer mp) {
	        if (position != 0)
	            mp.seekTo(position);
	    }
	});
	....
}`

**Comment by bbcallen** [comment]
Any log?
