### ISSUE TITLE
How to fast forward when playing a video

### ISSUE THREAD

**Issue by Hongzheng-Li** [Bilibili/ijkplayer#1355]
I found a method setSpeed(float speed) in IjkMediaPlayer, but it has annotation @TargetApi(Build.VERSION_CODES.M), now my android phone's version is 4.4, how can I implement the fast forward function on it?

**Comment by bbcallen** [comment]
Fix the avfilter support in ijkplayer.

**Comment by Android4MediaPlayer** [comment]
For avfilter, only support software decoder.

**Comment by Hongzheng-Li** [comment]
I have modified some code and rebuild the project to support avfilter, now I can change video speed by 
`ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "af", "atempo=2");
  ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "vf0", "setpts=PTS/(2)");` before setDataSource and start, but when video is playing, setOption doesn't work at all, @bbcallen @Android4MediaPlayer  , could you tell me how to change speed when video is playing ? Thanks a lot.

**Comment by rooque** [comment]
Just save current time,kill this instance of ijk, create another instance with the settings you want(tempo,pts) load the same source and set the time again ... you can implement some setOptionWhilePlaying() that do this  process :)

**Comment by animaonline** [comment]
@Hongzheng-Li could you please share your code? I need to enable the crop filter.

**Comment by Hongzheng-Li** [comment]
According to https://github.com/Bilibili/ijkplayer/blob/master/NEWS.md, ijkplayer added support for libavfilter in k0.4.2 and disabled the support in k0.4.5, you can look through log of ijkplayer and find corresponding code.
