### ISSUE TITLE
ijkPlayer play on IPv6

### ISSUE THREAD

**Issue by zhenwu1981** [Bilibili/ijkplayer#1358]
ijkplayer connect rtmp server on IPV6 return error. ijkplayer support the network IPV6?

**Comment by zhenwu1981** [comment]
ijkplayer 在ipv6的网络下，链接flv的地址显示链接不上，是不是获取http://hdl-w.quklive.com/live/w9464230103642991.flv这类的地址不支持ipv6的协议

**Comment by bbcallen** [comment]
Can't access this URL, even in ipv4 network.

**Comment by tbfly** [comment]
In ipv6 network, such as "http://www.sample-videos.com/video/mp4/480/big_buck_bunny_480p_20mb.mp4" can't be play.

You can setting ipv6 network as "http://www.jianshu.com/p/69ed4489762c".

**Comment by fenglinxiu** [comment]
@bbcallen I can not play this url in ipv6 either. State is IJKFFPlayerStateConnectFail. 
http://wsreplay.yizhibo.tv/video/7/a1/jZjehY2WRivg.mp4
I don't get idea. Expect your reply.

**Comment by bbcallen** [comment]
Can't connect to http://wsreplay.yizhibo.tv/video/7/a1/jZjehY2WRivg.mp4 in ipv6 network.
But samples in demo works fine, please check your server.
