### ISSUE TITLE
ios 通过currentPlaybackTime获取的时间超出duration

### ISSUE THREAD

**Issue by xyqjay** [Bilibili/ijkplayer#1361]
一个界面同时 初始化两个IJKFFMoviePlayerController,通过currentPlaybackTime获取的时间一直在增长，超出了视频实际的时长，

**Comment by xyqjay** [comment]
比如说一个viewController里 有两个IJKFFMoviePlayerController播放远程视频，（假设两个视频本身时长为30秒），视频播放完毕或暂停 ，使用timer定时获取currentPlaybackTime，currentPlaybackTime随着时间增加，而不是当前视频暂停的时间,。

**Comment by bbcallen** [comment]
Any code or log?
