### ISSUE TITLE
如何自动切换Iijplayer解码

### ISSUE THREAD

**Issue by bk378502765** [Bilibili/ijkplayer#1363]
如果设备不支持硬解，如何自动切换软解，求大神指点

**Comment by bbcallen** [comment]
ijkplayer just acts like that, if error can be detected.

**Comment by bk378502765** [comment]
我的设备硬解的时候黑屏，只有软解可以播放，而且还没有log输出（设备adb被厂家关闭了），硬解失败的是否有标识或者异常日志呢，求大神指点

**Comment by bbcallen** [comment]
Can't tell anything without log.

**Comment by bk378502765** [comment]
还有其他判断硬解失败的方法么  或者检测该设备是否支持ijkplayer硬解呢

**Comment by bbcallen** [comment]
You can redirect log to somewhere else to see what happens.

**Comment by bk378502765** [comment]
D/IJKMEDIA( 3406): ijkmp_set_android_surface(surface=0x0)
D/IJKMEDIA( 3406): ijkmp_set_android_surface(surface=0x0)=void
D/IJKMEDIA( 3406): ijkmp_stop()
D/IJKMEDIA( 3406): ijkmp_stop()=0
D/IJKMEDIA( 3406): ijkmp_set_android_surface(surface=0x0)
D/IJKMEDIA( 3406): ijkmp_set_android_surface(surface=0x0)=void
D/IJKMEDIA( 3406): ijkmp_shutdown_l()
D/IJKMEDIA( 3406): ijkmp_shutdown_l()=void
D/IJKMEDIA( 3406): ijkmp_dec_ref(): ref=0
D/IJKMEDIA( 3406): ijkmp_shutdown_l()
D/IJKMEDIA( 3406): ijkmp_shutdown_l()=void
I/SurfaceView( 3406): updateWindow -- setFrame, this = tv.danmaku.ijk.media.example.widget.media.SurfaceRenderView{41f2f388 V.E..... ......ID 0,0-1280,720}
I/IJKMEDIA( 3406): av_version_info: ff3.0--ijk0.5.0--dev0.4.5--rc11
D/IJKMEDIA( 3406): ijkmp_set_inject_opaque(0x1d60048a)
D/IJKMEDIA( 3406): ijkmp_set_inject_opaque()=void
D/IJKMEDIA( 3406): ijkmp_android_set_mediacodec_select_callback()
D/IJKMEDIA( 3406): ijkmp_android_set_mediacodec_select_callback()=void
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406): Couldn't open file on client side, trying server side
D/IJKMEDIA( 3406): ijkmp_set_data_source(url="http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear2/prog_index.m3u8")
D/IJKMEDIA( 3406): ijkmp_set_data_source(url="http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear2/prog_index.m3u8")=0
D/IJKMEDIA( 3406): ijkmp_set_android_surface(surface=0xc150001d)
D/IJKMEDIA( 3406): ijkmp_set_android_surface(surface=0xc150001d)=void
D/IJKMEDIA( 3406): ijkmp_prepare_async()
I/IJKMEDIA( 3406): FFmpeg       : ff3.0--ijk0.5.0--dev0.4.5--rc11
I/IJKMEDIA( 3406): format-opts : ijkinject-opaque             = 492831882
I/IJKMEDIA( 3406): format-opts : ijkapplication               = 1629976160
I/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406): onSelectCodec: mime=video/avc, profile=77, level=30
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.AUDIO.DECODER.MP3
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: audio/mpeg
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.AUDIO.DECODER.AMR.NB
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: audio/3gpp
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.AUDIO.DECODER.AMR.WB
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: audio/amr-wb
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.AUDIO.DECODER.ADPCM
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: audio/x-adpcm-ms
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.AUDIO.DECODER.ADPCM
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: audio/x-adpcm-dvi-ima
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.AUDIO.DECODER.GSM
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: audio/gsm
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.AUDIO.DECODER.RAW
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: audio/raw
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.AUDIO.DECODER.AAC
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: audio/mp4a-latm
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.AUDIO.DECODER.G711
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: audio/g711-alaw
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.AUDIO.DECODER.G711
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: audio/g711-mlaw
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.AUDIO.DECODER.VORBIS
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: audio/vorbis
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.AUDIO.DECODER.FLAC
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: audio/flac
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.DTS.audio_decoder.dts
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: audio/dts
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.AUDIO.DECODER.APE
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: audio/ape
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.AUDIO.DECODER.EAC3
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: audio/dd
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.AUDIO.DECODER.EAC3
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: audio/ddp
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.VIDEO.DECODER.MPEG4
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: video/mp4v-es
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.VIDEO.DECODER.H263
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: video/3gpp
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.VIDEO.DECODER.HEVC
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: video/hevc
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.VIDEO.DECODER.AVC
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: video/avc
I/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406): candidate codec: OMX.MTK.VIDEO.DECODER.AVC rank=800
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.VIDEO.DECODER.VPX
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: video/x-vnd.on2.vp8
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.google.vp9.decoder
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: video/x-vnd.on2.vp9
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.VIDEO.DECODER.DIVX
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: video/divx
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.VIDEO.DECODER.XVID
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: video/xvid
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.google.aac.decoder
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: audio/mp4a-latm
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.google.vp8.decoder
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):     mime: video/x-vnd.on2.vp8
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3406):   found codec: OMX.MTK.VIDEO.DECODER.MPEG2

**Comment by bk378502765** [comment]
出现上面的log后画面黑屏，有声音

**Comment by bbcallen** [comment]
The log shows nothing wrong.

**Comment by bk378502765** [comment]
是的  确实没有看出是什么异常  但是确实就是有声音无图像    会不会和MTK的芯片有关呢   因为这个设备是MTK的芯片

**Comment by bbcallen** [comment]
No idea.
