### ISSUE TITLE
STB EMULTOR

### ISSUE THREAD

**Issue by mikecharif14** [Bilibili/ijkplayer#1365]
Hey I just found a bug on the stb emulator after the updates, we can't configure keys, the action key list does not have a drop down list so we can pick what buttons are for what like for example I cant press yellow key on android box and link it to yellow button please let me know if I am doing somethin wrong, Im sure its abug because if I download an old  version like  0.6 it works but does not work on 0.8 and so on.

**Comment by bbcallen** [comment]
Is there anything related to ijkplayer?
