### ISSUE TITLE
大神，能不能编译支持udp,tcp,rtsp,ftp,http这种协议的ffmpeg库

### ISSUE THREAD

**Issue by amwujetuu** [Bilibili/ijkplayer#1367]

**Comment by bbcallen** [comment]
You can modify config/module-lite/sh by yourself.

**Comment by LinMaris** [comment]
It  can't  work  @bbcallen 
 WARNING: Option --enable-demuxer=latm did not match anything
WARNING: Option --enable-protocol=rtsp did not match anything
WARNING: pkg-config not found, library detection may fail.

**Comment by LiuLongChang** [comment]
The same question, could you talk about it in detail

**Comment by lovebing** [comment]
Same problem!  Run extra/ffmpeg/configure --list-protocols and no rtsp found.
if you add --enable-protocol=rtsp in config/module-lite.sh, you will get a warning when compile: 
WARNING: Option --enable-protocol=rtsp did not match anything

**Comment by lovebing** [comment]
try 
--enable-demuxer=rtsp
