### ISSUE TITLE
Opening a file and implementing an XOR function

### ISSUE THREAD

**Issue by midoreigh** [Bilibili/ijkplayer#1370]
Hi,
I am using ijk player to develop an android app.
Which function opens the file and can we get buffer of that opened file? I want to XOR the file for encryption and decryption, how can i do that? Is there any fopen function we can use?

**Comment by bbcallen** [comment]
See IMediaDataSource.

**Comment by midoreigh** [comment]
@bbcallen There is no implementation of the Interface IMediaDataSource, right? So, how would you suggest accessing the file? Can you please elaborate?
Thanks for the reply

**Comment by bbcallen** [comment]
It's some how similar to
https://developer.android.com/reference/android/media/MediaDataSource.html

**Comment by midoreigh** [comment]
Thanks man. I will check this out and I am closing this one for now. Thank you for your replies

**Comment by boomstack** [comment]
But this class is added in API level 23, how can I use it in lower api?

**Comment by midoreigh** [comment]
@boomstack Use IMediaDataSource. NOT MediaDataSource.
Implement that interface and you are good to go.
