### ISSUE TITLE
如何实现播放多个本地视频，视频之间切换的时候，保留最后一帧，不出现黑屏。

### ISSUE THREAD

**Issue by andyjmzheng** [Bilibili/ijkplayer#1372]
如何实现播放多个本地视频，视频之间切换的时候，保留最后一帧，不出现黑屏?

**Comment by andyjmzheng** [comment]
@bbcallen

**Comment by bbcallen** [comment]
Don't hide/destroy the first SurfaceView until video frame reaches the second SurfaceView, my guess.
