### ISSUE TITLE
播放rmtp视频流时刚开始有短暂的快进

### ISSUE THREAD

**Issue by Hongzheng-Li** [Bilibili/ijkplayer#1374]
用Ijkplayer打开一个rtmp流（如：rtmp://live.hkstv.hk.lxdns.com/live/hks）时，刚出现画面的半秒帧率很高，有明显的快进，请问应该怎么解决这个问题？
![image](https://cloud.githubusercontent.com/assets/9741189/15662408/e545c06a-2722-11e6-97eb-524d5099d968.png)

**Comment by bbcallen** [comment]
You can modify ff_ffplay.c, and implement the limitation of max fps.
