### ISSUE TITLE
ijkplayer jni层的log 写文件

### ISSUE THREAD

**Issue by seu070507** [Bilibili/ijkplayer#1375]
请问下，现在的ijkplayer jni层 日志 是不是没有提供写文件的接口。只能输出到logcat？

**Comment by seu070507** [comment]
这个头文件我看到了，但是只是用来输出到到终端的吧

**Comment by bbcallen** [comment]
You can modify it, can't you?

**Comment by seu070507** [comment]
可以的，如果现在的ijk不支持的话， 我这边打算注册回调给av_log_set_callback

**Comment by seu070507** [comment]
thanks anyway！

**Comment by badtea** [comment]
Chy you say English to Chinese?Just for zhuangbi?
