### ISSUE TITLE
关于全局对象没有释放的问题

### ISSUE THREAD

**Issue by seu070507** [Bilibili/ijkplayer#1379]
在函数IjkMediaPlayer_native_setup中：
    ijkmp_android_set_mediacodec_select_callback(mp, mediacodec_select_callback, (*env)->NewGlobalRef(env, weak_this));

 传递给了IJKFF_Pipeline_Opaque 的 mediacodec_select_callback_opaque
 
但是代码中没有找到相关的显示释放动作，请问这里面会不会有潜在的内存泄漏问题？

**Comment by bbcallen** [comment]
Yes, there is very likely a leak there.

**Comment by seu070507** [comment]
yes，就像我说的我在 #1375 中说的
如果我实现一个回调java的函数，添加了一个类似mediacodec_select_callback_opaque的东西
append_logdata_callback_opaque
这个也存在没有释放的风险，请教下，我需要做显性释放吗？

**Comment by bbcallen** [comment]
I think it could be fixed by replacing NewGlobalRef(env, weak_this) with ijkmp_get_weak_thiz(mp).
But I don't have android device on my hand right now. I'll take a test later and push that fix.

**Comment by Android4MediaPlayer** [comment]
fixed by replacing NewGlobalRef(env, weak_this) with ijkmp_get_weak_thiz(mp).

**Comment by seu070507** [comment]
赞！！

**Comment by bbcallen** [comment]
Fixed.
