### ISSUE TITLE
Assertion failed: (cond), function SDL_CondWaitTimeout, file /Users/martin/Desktop/ijkplayer-ios/ijkmedia/ijksdl/ijksdl_mutex.c, line 135.

### ISSUE THREAD

**Issue by m8282823** [Bilibili/ijkplayer#1380]
SDL_LockMutex(wait_mutex);
            SDL_CondWaitTimeout(is->continue_read_thread, wait_mutex, 10);
            SDL_UnlockMutex(wait_mutex);
观看一个flv格式的视频流,关闭之后全局断点崩在这一行,
ff_ffplay.c line 2838    iOS端

**Comment by oeddyo** [comment]
Hi @bbcallen 

我们刚刚试了一下也出现了这个情况

测试视频：rtmp://120.77.174.246/vod/F45107E6-DA3D-4050-BEF0-DC62840FFDDA_video.flv

如果播放这个视频，过了一会等这个视频结束（大概5秒）之后再用ijk播放这个视频的话，就会报错

希望可以帮助你reproduce这个问题

**Comment by iamsup** [comment]
我也遇到了这个问题，请问您现在还能复现这个问题么？

**Comment by xinzhengzhang** [comment]
What's your ijk version?
