### ISSUE TITLE
iOS How to use Audio Units instead of Audio Queue

### ISSUE THREAD

**Issue by robotgit** [Bilibili/ijkplayer#1381]
Hello,

The release notes state that Audio Unit was replaced by Audio Queues in iOS. However, I still see the unused Audio Unit class in the Xcode project. I would very much like to use Audio Units. How might I do this?

**Comment by bbcallen** [comment]
Just modify
```
struct SDL_Aout_Opaque {
-    IJKSDLAudioQueueController *aoutController;
+    IJKSDLAudioUnitController *aoutController;
};
```

FYI: I don't use AudioUnit directly at all, so you are on your own while using it.

**Comment by robotgit** [comment]
Thank you VERY much for taking the time to reply. I greatly appreciate it! It looks like in both the Audio Unit and Audio Queue implementations, you are passing the audio stream into SDL for rendering.

I would like very much to access the PCM audio stream. May I ask if the audio stream is still AAC encoded before it is passed back into SDL? Or, is there a way to access the PCM stream once it has been decoded?
