### ISSUE TITLE
显示第一帧视频之前buffer消息没有触发

### ISSUE THREAD

**Issue by shishuo365** [Bilibili/ijkplayer#1382]
使用 ijkplayer-example 在源码没有任何修改的情况下，播放 sample 里面的网络流，
在 IMediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START 消息触发前，关于缓冲的两条消息 IMediaPlayer.MEDIA_INFO_BUFFERING_START 和 IMediaPlayer.MEDIA_INFO_BUFFERING_END 都没有被触发；

视频开始渲染之后，缓冲的消息就正常了（即只要开始缓冲就会触发这两条消息）

**Comment by bbcallen** [comment]
There is no guarantee when and where these two messages should be notified.

**Comment by shishuo365** [comment]
采用的处理方法是：
注释掉 ff_ffplay.c 文件中 q->is_buffer_indicator 判断条件，只要有缓冲就直接触发，暂未发现不良后果；
int packet_queue_get_or_buffering() {
    if (/*q->is_buffer_indicator &&*/ !*finished)
}
