### ISSUE TITLE
HLS seek issue

### ISSUE THREAD

**Issue by ielicyan** [Bilibili/ijkplayer#1383]
Seek operation blocked for a long time.

http://livestream-test.oss-cn-beijing.aliyuncs.com/onlinetest/000000000000000000000000155037e0.m3u8

**Comment by bbcallen** [comment]
Same issue in ffplay.
It's very likely an FFmpeg hls/mpegts issue.

**Comment by ielicyan** [comment]
@bbcallen The duration(EXTINF) in m3u8 is not precise,parser to the seek position cost a lot of time.Please close this issue,thanks.
