### ISSUE TITLE
支持多音轨、多字幕吗？

### ISSUE THREAD

**Issue by m521521l** [Bilibili/ijkplayer#1392]
有没有多音轨、多字幕的接口供出？

**Comment by bbcallen** [comment]
No.

**Comment by m521521l** [comment]
有没有相关的字段可以实现多音轨多字幕的？？ 
      ijk解码应该有字幕流吧？？

**Comment by bbcallen** [comment]
Modify ff_ffplay.c yourself.
Subtitle stream is dropped by default.

**Comment by waqasyousafy** [comment]
did you got any solution i am also working on multi subtitles ?
