### ISSUE TITLE
通过cygwin编译报错

### ISSUE THREAD

**Issue by yuiopt** [Bilibili/ijkplayer#1395]
[*] make NDK standalone toolchain
--------------------
build on CYGWIN_NT-10.0 x86_64
ANDROID_SDK=/cygdrive/d/Android/sdk
ANDROID_NDK=/cygdrive/d/Android/ndk
IJK_NDK_REL=11.1.2683735
NDKr11.1.2683735 detected
Cygwin temp prefix=D:/Cygwin/tmp/
HOST_OS=cygwin
HOST_EXE=.exe
HOST_ARCH=x86_64
HOST_TAG=cygwin-x86_64
HOST_NUM_CPUS=4
BUILD_NUM_CPUS=8
Auto-config: --arch=arm
Could not find toolchain: /cygdrive/d/Android/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/cygwin-x86
Please use --toolchain=<name> with the name of a toolchain supported by the source NDK.

**Comment by bbcallen** [comment]
Sorry, I don't have a win-pc environment, that's to say I don't maintain it.

**Comment by wuhuangpeng** [comment]
跟NDK版本有关系，我试过android-ndk-r11c和android-ndk-r10e。android-ndk-r10e没有问题，而android-ndk-r11c因为里面的shell脚本实现和android-ndk-r10e有差别，目录结构也略有差异，会有很多坑，建议使用android-ndk-r10e。

**Comment by MrZhangYang** [comment]
android-ndk-r10e也有不同的啊32位和64位的选哪个？
