### ISSUE TITLE
播放视频时切换url

### ISSUE THREAD

**Issue by sysdks** [Bilibili/ijkplayer#1396]
如何在播放url1的某一时刻 切换到url2去播放，前提是保证同一个player，音视频分别共用一个PacketQueue来保证连续播放？延迟3秒左右可以接受

**Comment by bbcallen** [comment]
No such feature.

**Comment by sysdks** [comment]
我现在想实现这样的功能。请问可以指点一下大概的思路吗？ @bbcallen

**Comment by bbcallen** [comment]
No idea.
IMO, nearly everything need to be recreated or reconfigured.

**Comment by Gagster** [comment]
@bbcallen  你好，
我在 viewDidLoad 中 写了 下面的代码 能够正常的播放
 IJKFFOptions *options = [IJKFFOptions optionsByDefault];
    NSURL * url = [NSURL URLWithString:rtmpStr]; 
    self.player = [[IJKFFMoviePlayerController alloc] initWithContentURL:url withOptions:options];
    self.player.view.autoresizingMask = UIViewAutoresizingFlexibleWidth|UIViewAutoresizingFlexibleHeight;
    self.player.view.frame = FULLSCREEN;
    self.player.scalingMode = IJKMPMovieScalingModeAspectFit; 
    self.player.shouldAutoplay = YES; 
    self.view.autoresizesSubviews = YES;
    [self.view addSubview:self.player.view];

但是当我把这段代码放到 比如 buttonAction 中 通过点击button来执行 就不好用了……

正常播放的情况下 打印的log日志中会打印： invalidateRenderBuffer  
后面会打印 ijkmp_set_data_source(url="XXX")

但是通过点击按钮执行后 就只打印 ：invalidateRenderBuffer

请问这是因为什么？

recreate Player 是怎么操作的？

**Comment by bbcallen** [comment]
Seems you didn't destroy previous player.

**Comment by Gagster** [comment]
谢谢~
