### ISSUE TITLE
You need NDKr10e or later

### ISSUE THREAD

**Issue by saber900517** [Bilibili/ijkplayer#1399]
我使用的是MAC＋Android Studio,按照步骤一步步配置，NDK是从SDK Manager下载，显示版本为12，配置好profile文件后提示You need NDKr10e or later。SDK Manager下载的不是最新版本吗？

**Comment by bbcallen** [comment]
NDKr12 is still in beta, and I can't find any individual download link on android's website.
I don't have any plan to support it until it's released as stable.

**Comment by saber900517** [comment]
All right.I will install Ndkr10e. ╮(╯_╰)╭
