### ISSUE TITLE
How to make screenshot or record video?

### ISSUE THREAD

**Issue by rsolov** [Bilibili/ijkplayer#140]
Hi.

I want to make a screenshot from video player and save it to sdcard as image. Also I want to record few seconds of video. As Android developer I'm using SurfaceView for ijkplayer, but I also can't take screenshot from it in traditional way (getDrawingCache).

In JavaCV there are some method/classes like FFmpegFrameGrabber, FFmpegFrameRecorder to do this. IJKPlayer and JavaCV use FFmpeg, so I think ijkplayer may also has same features.

Can you help me?

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
