### ISSUE TITLE
使用自定义数据源的问题

### ISSUE THREAD

**Issue by mgoann** [Bilibili/ijkplayer#1404]
使用自定义数据源，实现接口tv.danmaku.ijk.media.player.misc.IMediaDataSource

public int readAt(long position, byte[] buffer, int offset, int size) throws IOException

这个方法给ijkplayer提供数据，为什么这个方法会频繁有size=0的时候调进来，这样是读不到任何数据的呀，是不是BUG，我觉得应该传1

**Comment by bbcallen** [comment]
size=0 means there is a seek request.
You can handle it now, or ignore it, and handle new position at next readAt() call.

**Comment by mgoann** [comment]
thanks a lot!

**Comment by laminsk** [comment]
@mgoann Hi I'm working on the same issue. Did you manage to solve seek problem? I'm trying to load the file from web server and not sure how to handle the seek! Any help will be appreciated.

**Comment by mgoann** [comment]
@laminsk here is example use custom datasource!
`package com.fengxing.ams.tvclient.videomedia;

import android.content.Context;
import android.net.Uri;
import android.net.http.AndroidHttpClient;

import com.fengxing.ams.tvclient.R;
import com.fengxing.ams.tvclient.Utils;
import com.fengxing.ams.tvclient.intf.IPageMediaDataSource;
import com.fengxing.ams.tvclient.intf.PlayStatusCallback;
import com.fengxing.ams.tvclient.util.IOUtil;

import org.apache.commons.io.IOUtils;
import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.client.methods.HttpGet;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.RandomAccessFile;
import java.net.URI;
import java.net.URISyntaxException;

import io.vov.vitamio.utils.Log;
import tv.danmaku.ijk.media.player.misc.IMediaDataSource;

/**
 * Created by Administrator on 2016/5/26.
 */
public class CacheMediaDataSource implements IMediaDataSource, PlayStatusCallback {

    private final long totalSize;
    private long videoId;
    private String url;
    private static final String TAG = "CacheMediaDataSource";

    private IPageMediaDataSource pipeMediaDataSource = null;

    public CacheMediaDataSource(String url, long videoId, long totalSize) {
        this.url = url;
        this.videoId = videoId;
        this.totalSize = totalSize;
        pipeMediaDataSource = new PipeMediaDataSource(videoId, url);
    }

    @Override
    public int readAt(long position, byte[] buffer, int offset, int size) throws IOException {
        try {
            if (size == 0)
                return 0;
            //读取server端的数据填充到buffer
            //判断是否有缓存文件
            int readLength = pipeMediaDataSource.readAt(position, buffer, offset, size);
            return readLength;
        } catch (Exception e) {
            Log.e(TAG, e);
        }
        return 0;
    }

    @Override
    public long getSize() throws IOException {
        return totalSize;
    }

    @Override
    public void close() throws IOException {
        if (pipeMediaDataSource != null) {
            pipeMediaDataSource.desctory();
            pipeMediaDataSource = null;
        }
    }

    @Override
    public void onStart() {

    }

    @Override
    public void onStop() {

    }
}
`

`package com.fengxing.ams.tvclient.videomedia;

import android.content.Context;
import android.net.http.AndroidHttpClient;

import com.fengxing.ams.tvclient.Utils;
import com.fengxing.ams.tvclient.intf.IPageMediaDataSource;

import java.io.IOException;

/**
 * Created by Administrator on 2016/6/3.
 */
public class PipeMediaDataSource extends AbstractMediaDataSource {

    private IPageMediaDataSource diskMediaDataSource;
    private IPageMediaDataSource networkMediaDataSource;



    public PipeMediaDataSource(long videoId, String url) {
        //初始化diskDataSource和networkDataSource
        diskMediaDataSource = new DiskMediaDataSource(videoId, Utils.getCacheRootFile());
        networkMediaDataSource = new NetworkMediaDataSource(videoId, url, Utils.getCacheRootFile());
    }

    /**
     * 读取数据内容，数据有可能来至disk，也可能是网络，也可能是两者集合
     * @param position
     * @param buffer
     * @param offset
     * @param size
     * @return
     */
    public int readAt(long position, byte[] buffer, int offset, int size) throws IOException {
        //计算page
        long startPage = this.getPageForPosition(position);
        long endPage = this.getPageForPosition(position+size);
        int readLength = 0;
        int totalSize = size;
        for (long i = 0; i <= endPage - startPage; i++) {
            //计算起始位
            long startPosition = position + readLength;
            //计算本页读取的size
            int exceptSize = 0;
            int leftSize = (int) (DiskMediaDataSource.PAGE_MAX_SIZE - (startPosition % DiskMediaDataSource.PAGE_MAX_SIZE));
            if (leftSize > totalSize) {
                exceptSize = totalSize;
            } else {
                exceptSize = leftSize;
            }
            int readLengthFormDisk = diskMediaDataSource.readAt(startPosition, buffer, offset + readLength, exceptSize);
            if (readLengthFormDisk == -1)
                return -1;
            //disk中没有读取到
            int readLengthFormNetwork = 0;
            if (readLengthFormDisk == 0)
                readLengthFormNetwork = networkMediaDataSource.readAt(startPosition, buffer, offset + readLength, exceptSize);
            //如果返回-1，视频结束
            if (readLengthFormNetwork == -1)
                return -1;
            readLength += readLengthFormDisk + readLengthFormNetwork;
            totalSize = size - readLength;
        }
        return readLength;
    }

    @Override
    public void desctory() {
        if (diskMediaDataSource != null)
            diskMediaDataSource.desctory();
        if (networkMediaDataSource != null)
            networkMediaDataSource.desctory();
    }

}
`

`package com.fengxing.ams.tvclient.videomedia;

import android.util.Log;

import com.fengxing.ams.tvclient.intf.IPageMediaDataSource;
import com.fengxing.ams.tvclient.util.ArraysUtil;

import org.apache.commons.io.FileUtils;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.MappedByteBuffer;
import java.nio.channels.FileChannel;

/**
 * Created by Administrator on 2016/6/3.
 */
public class DiskMediaDataSource extends AbstractMediaDataSource {

    private long maxPosition = -1;

    public DiskMediaDataSource (long videoId, File rootDisk) {
        this.videoId = videoId;
        this.rootDisk = rootDisk;
//        File mediaInfo = new File(rootDisk, "/" + videoId + "/media.d");
//        if (mediaInfo.exists() && mediaInfo.canRead()) {
//            try {
//                maxLength = Long.valueOf(FileUtils.readFileToString(mediaInfo));
//            } catch (IOException e) {
//                Log.e(TAG, Log.getStackTraceString(e));
//            }
//        }
    }

    @Override
    public int readAt(long position, byte[] buffer, int offset, int size) throws IOException {
        if (maxPosition == -1) {
            File mediaFile = new File(rootDisk, "/" + videoId + "/media.c");
            if (mediaFile.exists()) {
                try {
                    maxPosition = Long.valueOf(FileUtils.readFileToString(mediaFile));
                } catch (Exception e) {
                    Log.e(TAG, "read max postion error" + Log.getStackTraceString(e));
                }
            }
        } else {
            if (position >= maxPosition)
                return -1;
        }

        //外部必须保证获取的数据在一页范围内
        long expectPage = getPageForPosition(position);
        int readLength = 0;
        if (expectPage == this.getCurrentPage() && !syncPageSet.contains(expectPage)) {
            readLength = readFormBuffer(position, buffer, offset, size);
            return readLength;
        } else {
            if (!syncPageSet.contains(expectPage) && getDiskPageData(position)) {
                readLength = readFormBuffer(position, buffer, offset, size);
            }
        }
        return readLength;
    }

    private boolean getDiskPageData(long position) {
        long page = this.getPageForPosition(position);
        File pageFile = new File(rootDisk, "/" + videoId + "/" + page + ".c");
        //如果缓存文件不存在，不可读
        if (!pageFile.exists() && !pageFile.canRead())
            return false;
        if (syncPageSet.contains(page))
            return false;
        if (this.getMaxPageNum() != page) {
            //如果不是最后一页数据，则校验起长度
            if (pageFile.length() != PAGE_MAX_SIZE)
                return false;
        }
        try {
            byte[] b = FileUtils.readFileToByteArray(pageFile);
            this.write(position, b);
            return true;
        } catch (IOException e) {
            Log.e(TAG, Log.getStackTraceString(e));
            return false;
        }
    }

    private long getMaxPageNum() {
        if (maxPosition == -1)
            return -1;
        return this.getPageForPosition(maxPosition);
    }

    @Override
    public void desctory() {
        super.desctory();
    }
}
`

`package com.fengxing.ams.tvclient.videomedia;

import android.net.http.AndroidHttpClient;
import android.os.AsyncTask;
import android.util.Log;

import com.fengxing.ams.tvclient.intf.IPageMediaDataSource;
import com.fengxing.ams.tvclient.util.StringUtil;

import org.apache.commons.io.FileUtils;
import org.apache.commons.io.IOUtils;
import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.util.EntityUtils;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.util.concurrent.TimeUnit;

import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

/**
 * Created by Administrator on 2016/6/4.
 */
public class NetworkMediaDataSource extends AbstractMediaDataSource {

    OkHttpClient client = new OkHttpClient.Builder()
            .connectTimeout(10, TimeUnit.SECONDS)
            .writeTimeout(10, TimeUnit.SECONDS)
            .readTimeout(30, TimeUnit.SECONDS)
            .retryOnConnectionFailure(true)
            .build();

    public NetworkMediaDataSource(long videoId, String url, File cacheRootFile) {
        this.url = url;
        this.videoId = videoId;
        this.rootDisk = cacheRootFile;
    }

    @Override
    public int readAt(long position, byte[] buffer, int offset, int size) throws IOException {
        //由于ijkplayer每次调用size很小，会频繁的创建连接，所以根据positoin，把这个分页的数据其次性预取，然后保存到文件
        long exceptPage = this.getPageForPosition(position);
        if (exceptPage != this.getCurrentPage()) {
            //读取该分页的数据
            return readFormNetwork(position, buffer, offset, size);
        } else {
            //直接从buffer中读取
            return this.readFormBuffer(position, buffer, offset, size);
        }
    }

    @Override
    public void desctory() {
        super.desctory();
    }

    private int readFormNetwork(long position, byte[] buffer, int offset, int size) throws IOException {
        long exceptPage = this.getPageForPosition(position);
        long startPosition = this.getStartPosition(exceptPage);
        long endPosition = this.getEndPosition(exceptPage, size);
        Response response = null;
        try {
            Request request = new Request.Builder()
                    .url(url)
                    .addHeader("Range", "bytes=" + startPosition + "-" + endPosition)
                    .build();
            response = client.newCall(request).execute();
            if (response.code() == 416) {
                //写入最大长度文件
//                FileUtils.writeStringToFile(new File(rootDisk, "/" + videoId + "/media.d"), String.valueOf(position));
                return -1;
            }
            byte[] b = response.body().bytes();
            //Content-Rangebytes 6000000-17000000/67139006
            String responseRange = response.header("Content-Range");
            long firstPos = this.getFirstBytePos(responseRange);
            long lastPos = this.getLastBytePos(responseRange);
            long maxPos = this.getMaxBytePos(responseRange);
            if (firstPos != startPosition || lastPos != endPosition) {
                Log.w(TAG, "read data form server not completed, start=" + startPosition + ", end=" + endPosition + ", first=" + firstPos + ", last=" + lastPos);
            }
            this.write(position, b);
            //启动异步线程写cache文件
            syncPageSet.add(exceptPage);
            new CacheAsyncTask(this.videoId, exceptPage, b, maxPos).execute();
        } finally {
            if (response != null)
                response.close();
        }
        return this.readFormBuffer(position, buffer, offset, size);
    }

    private long getFirstBytePos(String responseRange) {
        return Long.valueOf(StringUtil.subString(responseRange, " ", "-"));
    }

    private long getLastBytePos(String responseRange) {
        return Long.valueOf(StringUtil.subString(responseRange, "-", "/"));
    }

    private long getMaxBytePos(String responseRange) {
        return Long.valueOf(StringUtil.subString(responseRange, "/", null));
    }

    /**
     * 尽量避免Task直接访问CacheOutputStream的成员变量，避免线程安全问题
     */
    private class CacheAsyncTask extends AsyncTask<Object, Object, Object> {
        private long videoIdTask;
        private long pageTask;
        private byte[] b;
        private long maxPos;

        public CacheAsyncTask(long videoId, long page, byte[] b, long maxPos) {
            this.videoIdTask = videoId;
            this.pageTask = page;
            this.b = b;
            this.maxPos = maxPos;
        }

        @Override
        protected Object doInBackground(Object... params) {
            File cacheFile = new File(rootDisk, "/" + videoIdTask + "/" + pageTask + ".c");
            File mediaFile = new File(rootDisk, "/" + videoIdTask + "/media.c");
            try {
                FileUtils.writeByteArrayToFile(cacheFile, b);
                if (!mediaFile.exists()) {
                    FileUtils.writeStringToFile(mediaFile, String.valueOf(maxPos));
                }
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }
            syncPageSet.remove(pageTask);

            return null;
        }
    }



}
`

hope can help you!

**Comment by laminsk** [comment]
@mgoann Thanks for the code. I will give it a try this weekend.

**Comment by laminsk** [comment]
@mgoann Thanks so much once again for providing the code, I've been trying to get this running but I'm missing a couple of functions. For example getPageForPosition, getStartPosition, getEndPosition, syncPageSet, readFormBuffer, FileUtils.writeStringToFile/writeByteArrayToFile and StringUtil. 

I'd be most grateful if you could provide the missing classes, and thank you so much for helping me out.

**Comment by mgoann** [comment]
package com.fengxing.ams.tvclient.videomedia;

import com.fengxing.ams.tvclient.intf.IPageMediaDataSource;

import org.apache.commons.io.IOUtils;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.util.HashSet;
import java.util.Set;

/**
 * Created by Administrator on 2016/6/4.
 */
public abstract class AbstractMediaDataSource implements IPageMediaDataSource {
    protected static final String TAG = "CacheDataSource";

    //一次申明重复利用，子类不能直接操作cache
    private ByteBuffer cacheBuffer = ByteBuffer.allocate((int) PAGE_MAX_SIZE);
    protected String url;
    private long currentPage = -1;
    protected long videoId;
    protected File rootDisk;

    @Override
    public abstract int readAt(long position, byte[] buffer, int offset, int size) throws IOException;

    @Override
    public void desctory() {
        cacheBuffer.clear();
        cacheBuffer = null;
        currentPage = -1;
    }

    public int readFormBuffer(long position, byte[] buffer, int offset, int size) {
        cacheBuffer.rewind();
        int exceptPosition = (int) (position % PAGE_MAX_SIZE);
        if (exceptPosition >= cacheBuffer.limit())
            return -1;
        cacheBuffer.position(exceptPosition);
        cacheBuffer.get(buffer, offset, size > cacheBuffer.remaining() ? cacheBuffer.remaining() : size);
        return size;
    }

    public long getPageForPosition(long position) {
        return position / PAGE_MAX_SIZE;
    }

    public long getCurrentPage() {
        return this.currentPage;
    }

    public long getStartPosition(long page) {
        return page * PAGE_MAX_SIZE;
    }

    public long getEndPosition(long page, int size) {
        return ((page + 1L) * PAGE_MAX_SIZE) - 1L;
    }

    public void write(long position, byte[] b) {
        //清理缓存数据，将位置设置为 0，将限制设置为容量
        cacheBuffer.clear();
        //放入数据
        cacheBuffer.put(b).position(0).limit(b.length);
        this.currentPage = this.getPageForPosition(position);
    }
}

**Comment by mgoann** [comment]
package com.fengxing.ams.tvclient.util;

import android.content.Context;
import android.net.wifi.WifiInfo;
import android.net.wifi.WifiManager;

import org.apache.commons.codec.Charsets;

import java.nio.charset.Charset;

public class StringUtil {
	
	public static String getDuration(int time) {
		int s = time;
		int N = s / 3600;
		s = s % 3600;
		int K = s / 60;
		s = s % 60;
		int M = s;
		StringBuilder sb = new StringBuilder();
		if (N > 0) {
			sb.append(N).append("小时");
		}
		if (K > 0) {
			sb.append(K).append("分");
		}
		if (M > 0) {
			sb.append(M).append("秒");
		}
		return sb.toString();
	}

	public static boolean isNull(String email) {
		if (email == null)
			return true;
		if (email.trim().equals(""))
			return true;
		return false;
	}

	public static boolean isEmpty(String updateInfo) {
		if (updateInfo == null)
			return true;
		if (updateInfo.trim().equals(""))
			return true;
		return false;
	}

	public static boolean isNotEmpty(String s) {
		if (s == null)
			return false;
		if (s.trim().equals(""))
			return false;
		return true;
	}

	public static byte[] getBytesUtf8(final String string) {
		return getBytes(string, Charsets.UTF_8);
	}

	private static byte[] getBytes(final String string, final Charset charset) {
		if (string == null) {
			return null;
		}
		return string.getBytes(charset);
	}

	public static String substringAfterLast(final String str, final String separator) {
		if (isEmpty(str)) {
			return str;
		}
		if (isEmpty(separator)) {
			return "";
		}
		final int pos = str.lastIndexOf(separator);
		if (pos == -1 || pos == str.length() - separator.length()) {
			return "";
		}
		return str.substring(pos + separator.length());
	}

	public static String subString(String src, String start, String end) {
		if (src == null || src.equals(""))
			return src;
		int startIndex = 0;
		int endIndex = src.length();
		if (start != null && !start.equals("")) {
			startIndex = src.indexOf(start) == -1 ? 0 : src.indexOf(start)
					+ start.length();
		}
		if (end != null && !end.equals("")) {
			endIndex = src.indexOf(end, startIndex) == -1 ? src.length() - 1
					: src.indexOf(end, startIndex);
		}
		return src.substring(startIndex, endIndex);
	}
}

**Comment by mgoann** [comment]
package com.fengxing.ams.tvclient.intf;

import java.io.IOException;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

/**
 * Created by Administrator on 2016/6/3.
 */
public interface IPageMediaDataSource {

    /**
     * 分页大小为512，disk network都按照该参数进行分页缓存，注意该数值太大会引起一次请求无法获取所有数据的问题
     */
    static final long PAGE_MAX_SIZE = 1024L * 512L;

    int readAt(long position, byte[] buffer, int offset, int size) throws IOException;

    void desctory();

    static final Set<Long> syncPageSet = Collections.synchronizedSet(new HashSet<Long>());
}

**Comment by laminsk** [comment]
@mgoann Thank you very much for your help. I've just tested the code, unfortunately, this function "Utils.getCacheRootFile" is still missing. I'd be most grateful if you could help me out. Cheers.

**Comment by mgoann** [comment]
@laminsk this method is called for get cache root file path, you can definded yourselft

**Comment by laminsk** [comment]
@mgoann Thanks for the reply. I have tried it as you suggested and running into following problems:

1)  I use CacheMediaDataSource as datasource for ijkplayer.    
CacheMediaDataSource mcachesource = new CacheMediaDataSource(source,mediaId,size);
mMediaPlayer.setDataSource(mcachesource);

In pipemediadatasource, I'm using like this:

diskMediaDataSource = new DiskMediaDataSource(videoId, new File(Environment.getExternalStorageDirectory().toString()));
networkMediaDataSource = new NetworkMediaDataSource(videoId, url, new File(Environment.getExternalStorageDirectory().toString()));

When I play "mp3" file from http url (about 4 MB file), it takes awhile to start. Usually 4-5 seconds waiting time and it will play eventually. I can see it creates the folder based on MediaID and cache the output like this (media.c, 0.c,1.c,2.c, etc...). However, I'm getting this warning message 

"W/CacheDataSource: read data form server not completed, start=2621440, end=3145727, first=2621440, last=2634957"

2) If I disable internet connection on the device and play the same music again, it simply doesn't work. Do not play from cache although cache files are stored on the device. 

What I want to do is play music/video from http and cache the files on device for offline play back. I do not have any runtime error and not sure what I'm missing but it will be most helpful if you could put together a simple demo based on your code.

Many thanks again for your help.

**Comment by a137235** [comment]
@mgoann 那个最大的size应该可以在首次网络请求时得到吧？

**Comment by mgoann** [comment]
@a137235 可以的

**Comment by a137235** [comment]
@mgoann 你这个代码机制还是有问题,特别是应用为音乐缓存时会有破音出现(首次写或者读缓存都会出现)，我感觉是每次内存分片的问题。

**Comment by mgoann** [comment]
@a137235 有BUG的，这个代码我很早贴出来的，后面经过几个版本的修改基本稳定了。

**Comment by a137235** [comment]
@mgoann 能不能共享下呢？我现在研究不怎么透彻呢，不好修复的样子。

**Comment by mgoann** [comment]
@a137235 你可以加我qq

**Comment by laminsk** [comment]
@mgoann <https://github.com/mgoann> Would you be able to put together a
working example project please?

**Comment by mgoann** [comment]
最新代码上传到这里，https://github.com/mgoann/ijkplayer-CacheDataSource，有疑问请到这里提问

**Comment by laminsk** [comment]
Thanks for providing the code. Unfortunately, I can't find these files. PlayStatusCallback, IPageMediaDataSource and Utils.

**Comment by laminsk** [comment]
@mgoann  I've managed to get the cachedatasource working somehow. Not sure you are experiencing the same problem or perhaps i'm not doing it right! Basically I'm testing it for audio files (about 3MB). I find that it slows to start the playback, is there a way to control the buffer? I want to start the audio playback straight away soon as there's enough buffer. Thanks again.

**Comment by oushizishu** [comment]
iOS使用ijkplayer的时候, 怎么自定义数据源?

**Comment by kimnamcham** [comment]
@laminsk Can you share the sample project ? Thanks

**Comment by qiujuer** [comment]
Android自定义数据源解决方案，可以实现网络文件本地缓存的功能：https://github.com/qiujuer/Planck

**Comment by aytunch** [comment]
@qiujuer Hi, Can this be bundled with IjkPlayer? is there an iOS version? Does it work:)
