### ISSUE TITLE
can not play in ipv6

### ISSUE THREAD

**Issue by fenglinxiu** [Bilibili/ijkplayer#1407]
I can not play in ipv6 network.
Error state is IJKFFPlayerStateConnectFail. 
http://wsreplay.yizhibo.tv/video/7/a1/jZjehY2WRivg.mp4
Ipv4 condition play well. I can't get any idea. Expect anyone's reply. Thanks.

**Comment by bbcallen** [comment]
Can't connect to http://wsreplay.yizhibo.tv/video/7/a1/jZjehY2WRivg.mp4 in ipv6 network.
But samples in demo works fine, please check your server.

**Comment by maytrue** [comment]
IJKPlayer does support IPV6 network. Please using domain instead of IP address.
