### ISSUE TITLE
ijkplayer如何对rtsp支持和将其播放？

### ISSUE THREAD

**Issue by cwjfeifei** [Bilibili/ijkplayer#1409]
ijkplayer如何对rtsp支持和将其播放？

**Comment by yihongyuelan** [comment]
@cwjfeifei 
在issue list里面搜索一下吧

**Comment by cwjfeifei** [comment]
https://github.com/Bilibili/ijkplayer/issues/1108我在这里找到了，修改文件使之能支持rtsp，然后编译，但是播放的时候没声音也没图像？ @yihongyuelan

**Comment by walimis** [comment]
@cwjfeifei I also built the player according to https://github.com/Bilibili/ijkplayer/issues/1108. Also the player can playing but has no video and audio. @cwjfeifei do you resolve the issue?

**Comment by CoderAO** [comment]
@cwjfeifei @walimis 我出现和你们一样的情况,修改配置文件后重新编译,可以支持rtsp了,但是没有声音没有图像,你们是否有想到解决办法?

**Comment by CoderAO** [comment]
@walimis I have the same promblem. No video or audio. Have you ever solved it ? thx!

**Comment by Coder-XL** [comment]
1、我用module-default.sh是可以播放RTSP，但是打的包快500M，太大了。
2、现在是采用修改module-lite.sh文件，
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=rtp"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=rtsp"
然后修改ff_ffplay.c文件，
修改：static int packet_queue_get_or_buffering(FFPlayer *ffp, PacketQueue *q, AVPacket *pkt, int *serial, int *finished)
{
assert(finished);
if (!ffp->packet_buffering)
return packet_queue_get(q, pkt, 1, serial);

while (1) {
    int new_packet = packet_queue_get(q, pkt, 0, serial);
    if (new_packet < 0)
        return -1;
    else if (new_packet == 0) {
        if (q->is_buffer_indicator && !*finished)
            ffp_toggle_buffering(ffp, 1);
        new_packet = packet_queue_get(q, pkt, 1, serial);
        if (new_packet < 0)
            return -1;
    }

    if (*finished == *serial) {
        av_packet_unref(pkt);
        continue;
    }
    else
        break;
}

return 1;
}

TO----->
static int packet_queue_get_or_buffering(FFPlayer *ffp, PacketQueue *q, AVPacket *pkt, int *serial, int finished)

{

while (1) {
    
    int new_packet = packet_queue_get(q, pkt, 1, serial);
    
    if (new_packet < 0)
    
    {
        
        new_packet = packet_queue_get(q, pkt, 0, serial);
        
        if(new_packet < 0)
        
        return -1;
        
    }
    else if (new_packet == 0) {
        
        if (!finished)
        
        ffp_toggle_buffering(ffp, 1);
        
        new_packet = packet_queue_get(q, pkt, 1, serial);
        
        if (new_packet < 0)
        
        return -1;
        
    }
    if (finished == *serial) {
        
        av_free_packet(pkt);
        
        continue;
        
    }
    else
    
    break;
    
}
return 1;
}

然后编译，打包播放不了，我从网上搜到的开源视频流地址：rtsp://218.204.223.237:554/live/1/66251FC11353191F/e7ooqwcfbqjoo80j.sdp

求大家指教！！！
