### ISSUE TITLE
IOS下不能拖动的问题

### ISSUE THREAD

**Issue by flyabird** [Bilibili/ijkplayer#141]
您好，非常感谢如此优秀的软件，在android和IOS下都很流畅。
用目前最新的代码，发现一个问题，在android下可以拖动，但在IOS下，拖动后会回到当前的进度，不会有拖动的效果，进度条会回去。

测试的播放地址是：http://flv.bn.netease.com/tvmrepo/2012/7/C/7/E868IGRC7-mobile.mp4  也试过flv文件，也有一样的问题。

测试的机器是iphone4，也用iphone4s的模拟器试过。不知道是什么原因，是否可以看下，多谢

**Comment by bbcallen** [comment]
Fixed

**Comment by walkermi** [comment]
怎么今天的新版，iOS的seek不起作用了？HTTP Pseudo-Streaming （MP4/FLV）及HTTP Live Streaming都无法seek了？@bbcallen

**Comment by walkermi** [comment]
怎么今天的新版，iOS的seek不起作用了？HTTP Pseudo-Streaming （MP4/FLV）及HTTP Live Streaming都无法seek了？@bbcallen

**Comment by walkermi** [comment]
怎么今天的新版，iOS的seek不起作用了？HTTP Pseudo-Streaming （MP4/FLV）及HTTP Live Streaming都无法seek了？@bbcallen
