### ISSUE TITLE
软解播放时切换播放源报一个错

### ISSUE THREAD

**Issue by cjztool** [Bilibili/ijkplayer#1410]
我用的是 k0.4.5.1版,(换了最新release 0.5.1的也是一样)
在切换播放源时 已调用 stopPlayback,  release(true)
但换了播放地址之后一段时间 只有声音 图像卡在之前一帧不动, 打印大量日志:

.... I/BufferQueue: [unnamed-21616-0](this:0x7be1ca30,id:0,api:2,p:21616,c:21616) connect: api=2 producer=(21616:xx.xx.xx.xx) producerControlledByApp=true
.... E/BufferQueue: [unnamed-21616-0](this:0x7be1ca30,id:0,api:2,p:21616,c:21616) connect: already connected (cur=2, req=2)
.... E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -22

不做任何操作一段时间之后恢复正常,
恢复时打印的日志:
... D/IJKMEDIA: IjkMediaPlayer_native_finalize
....D/IJKMEDIA: IjkMediaPlayer_release

开启硬解时,播放时切换播放源地址没有问题., 请问下这是啥原因呢,

**Comment by cjztool** [comment]
@bbcallen 大神, 端午出门旅游去了么

**Comment by bbcallen** [comment]
IjkVideoView is not designed for switching video URL.
I don't know what would happen if you do like that.

From the log, the Surface is very likely not detached from previous player in time.
That's my best guess.

**Comment by cjztool** [comment]
@bbcallen 多谢, 换源之前强行native_profileEnd了,换源之后再native_profileBegin,继续播放,这样避免了这个问题,播放结束再调end,保证成对调begin和end, 请问下, 如果没有成对调用native_profileBegin 和end 会不会引发其他潜在问题呢?

**Comment by bbcallen** [comment]
No, if you don't enable android-ndk-profiler manually.
It's only a dummy by default.

**Comment by cjztool** [comment]
end 再begin  似乎还是不行..

**Comment by cjztool** [comment]
@bbcallen  能不能指点个思路呢, 换源的时候画面卡住了

**Comment by bbcallen** [comment]
Nothing I can do without any information.

**Comment by cjztool** [comment]
@bbcallen  就是关闭硬解码之后 播放某一在线视频一段时间后,再顺序调用

mVideoView.pause();
mVideoView.stopPlayback();
mVideoView.release(true);
mVideoView.setVideoPath("一个新的播放地址");
mVideoView.play();

这样切换播放源会导致 1楼那样的日志出现.

**Comment by bbcallen** [comment]
As I said above, "IjkVideoView is not designed for switching video URL."

Take a look at demo to see how to switch player.

**Comment by cjztool** [comment]
@bbcallen  多谢提醒 换源之后声音可播, 问题出在了渲染的时候,参考demo已修正.

**Comment by xieyucheng** [comment]
oh·····  it's help for me  thank you !!!

**Comment by Tipsyume** [comment]
@cjztool 你好！你的应用在不断切换时会不会出现卡顿画面，在release的那一阵子会出现卡顿，你是怎么处理的

**Comment by zhangning2214965889** [comment]
你好，请问换源之后声音可播，画面卡住的问题是怎么解决的，我也遇到了同样的问题，能给我一点建议吗？谢谢啦
