### ISSUE TITLE
第一次创建视频的player,调[self.player isPlaying]判断是否在播放，明明在播放，返回的NO，只是第一次时候

### ISSUE THREAD

**Issue by LikeSpeedSong** [Bilibili/ijkplayer#1411]

**Comment by bbcallen** [comment]
isPlaying() status is changed synchronized, so that could happen.

**Comment by LikeSpeedSong** [comment]
那怎么解决这个问题啊

**Comment by bbcallen** [comment]
No good solution, for now.
But you can check the status periodly, as a work around.

**Comment by Gagster** [comment]
// status
    BOOL isPlaying = [self.delegatePlayer isPlaying];
    self.playButton.hidden = isPlaying;
    self.pauseButton.hidden = !isPlaying;

demo里面 为什么能够准确的获取 isPlaying 的状态呢？

**Comment by bbcallen** [comment]
It is changed asynchronized, that's to say, you don't know when it will be changed.

**Comment by Gagster** [comment]
Alright,Thanks a lot
