### ISSUE TITLE
demo视频播放出错 iOS

### ISSUE THREAD

**Issue by congni** [Bilibili/ijkplayer#1413]
如题：本来ios  demo可以正常播放直播；
今天运行突然不能播放，不知道咋回事，忘各位解答！
![image](https://cloud.githubusercontent.com/assets/7497123/15815645/1789ee1a-2c01-11e6-9688-b20d5c8b3bac.png)

**Comment by congni** [comment]
为啥没人回答啊

**Comment by congni** [comment]
![image](https://cloud.githubusercontent.com/assets/7497123/15817340/2ee5c9fe-2c0a-11e6-82e2-8319f59811ed.png)

**Comment by bbcallen** [comment]
The log has already told you what happened.
