### ISSUE TITLE
修改ff_ffplay.c中的哪个参数可以让音视频同步快速播放

### ISSUE THREAD

**Issue by m521521l** [Bilibili/ijkplayer#1416]
修改ff_ffplay.c中的哪个参数可以让音视频同步快速播放呢，改了时间戳没效果，改了compute_target_delay中的参数，视频是可以进行快放慢放，但是音频还是正常播放，求大神提供解决思路。非常感谢

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/3cd2e4752fad196b803aa6413b4addd281f20afc/ios/IJKMediaPlayer/IJKMediaPlayer/IJKMediaPlayback.h#L97

**Comment by yangwuan55** [comment]
@bbcallen 是否可以在sdk中加入直接修改播放速度的功能？
