### ISSUE TITLE
A/IJKMEDIA: Assertion !whitelist || !(e=av_dict_get(*options, "protocol_whitelist", ((void *)0), 0)) || !strcmp(whitelist, e->value) failed at libavformat/avio.c:353

### ISSUE THREAD

**Issue by a137235** [Bilibili/ijkplayer#1419]
我设置了mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT,"Protocol_whitelist","concat")，然后播放ffconcat文件就出错了，求解决思路。

**Comment by bbcallen** [comment]
set a breakpoint in debugger, and see why the assert happens.

**Comment by a137235** [comment]
I don't debug c , can you help me?
