### ISSUE TITLE
想请教一下播放 http-flv 音视频不同步的问题

### ISSUE THREAD

**Issue by LonlyCat** [Bilibili/ijkplayer#1421]
iOS端：直接使用示例demo播放基于 http-flv协议的视频流，在模拟器上运行会出现音频比视频快，在真机上运行会出现视频比音频快。但是我查阅资料，说 ffplay 默认是基于音频同步的。想请教一下是还需要在什么地方做修改么

**Comment by bbcallen** [comment]
A-V sync is implemented in ff_ffplay.c

**Comment by LonlyCat** [comment]
多谢，经过Debug发现是因为音视频的时差太大导致不执行同步方法，后跟CDN提供商协商发现是他们的问题
