### ISSUE TITLE
Cannot play SmoothStreaming source - Invalid data found when processing input

### ISSUE THREAD

**Issue by brystel** [Bilibili/ijkplayer#1422]
Hi,

Could you tell me how to play SmoothStreaming source?
Here is example url: http://video3.smoothhd.com/ondemand/Turner_Sports_PGA.ism/Manifest

Here is log from IjkPlayer:

> 06-07 19:15:43.631 tv.test.app D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
06-07 19:15:43.631 tv.test.app V/IJKMEDIA: setDataSource: path http://video3.smoothhd.com/ondemand/Turner_Sports_PGA.ism/Manifest
06-07 19:15:43.631 tv.test.app D/IJKMEDIA: ijkmp_set_data_source(url="http://video3.smoothhd.com/ondemand/Turner_Sports_PGA.ism/Manifest")
06-07 19:15:43.631 tv.test.app D/IJKMEDIA: ijkmp_set_data_source(url="http://video3.smoothhd.com/ondemand/Turner_Sports_PGA.ism/Manifest")=0
06-07 19:15:43.631 tv.test.app D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
06-07 19:15:43.631 tv.test.app D/IJKMEDIA: ijkmp_set_android_surface(surface=0xbeef5b30)
06-07 19:15:43.631 tv.test.app D/IJKMEDIA: ffpipeline_set_surface()
06-07 19:15:43.631 tv.test.app D/IJKMEDIA: ijkmp_set_android_surface(surface=0xbeef5b30)=void
06-07 19:15:43.631 tv.test.app D/IJKMEDIA: IjkMediaPlayer_prepareAsync
06-07 19:15:43.631 tv.test.app D/IJKMEDIA: ijkmp_prepare_async()
06-07 19:15:43.631 tv.test.app I/IJKMEDIA: ===== versions =====
06-07 19:15:43.631 tv.test.app I/IJKMEDIA: FFmpeg       : c59455f
06-07 19:15:43.631 tv.test.app I/IJKMEDIA: libavutil    : 54.27.100
06-07 19:15:43.632 tv.test.app I/IJKMEDIA: libavcodec   : 56.41.100
06-07 19:15:43.632 tv.test.app I/IJKMEDIA: SDL_RunThread: [13744] ff_msg_loop
06-07 19:15:43.632 tv.test.app D/IJKMEDIA: message_loop
06-07 19:15:43.632 tv.test.app I/IJKMEDIA: libavformat  : 56.36.100
06-07 19:15:43.633 tv.test.app I/IJKMEDIA: libswscale   : 3.1.101
06-07 19:15:43.634 tv.test.app I/IJKMEDIA: libswresample: 1.2.100
06-07 19:15:43.634 tv.test.app I/IJKMEDIA: ===== options =====
06-07 19:15:43.634 tv.test.app I/IJKMEDIA: player-opts : mediacodec                   = 1
06-07 19:15:43.634 tv.test.app I/IJKMEDIA: player-opts : mediacodec-auto-rotate       = 1
06-07 19:15:43.634 tv.test.app I/IJKMEDIA: player-opts : opensles                     = 0
06-07 19:15:43.634 tv.test.app I/IJKMEDIA: player-opts : overlay-format               = 842225234
06-07 19:15:43.635 tv.test.app D/IJKMEDIA: FFP_MSG_FLUSH:
06-07 19:15:43.636 tv.test.app I/IJKMEDIA: player-opts : framedrop                    = -1
06-07 19:15:43.636 tv.test.app I/IJKMEDIA: player-opts : start-on-prepared            = 0
06-07 19:15:43.636 tv.test.app I/IJKMEDIA: player-opts : max-buffer-size              = 100
06-07 19:15:43.636 tv.test.app I/IJKMEDIA: player-opts : min-frames                   = 5
06-07 19:15:43.636 tv.test.app I/IJKMEDIA: player-opts : first-high-water-mark-ms     = 100
06-07 19:15:43.637 tv.test.app I/IJKMEDIA: player-opts : next-high-water-mark-ms      = 100
06-07 19:15:43.638 tv.test.app I/IJKMEDIA: player-opts : last-high-water-mark-ms      = 100
06-07 19:15:43.638 tv.test.app I/IJKMEDIA: format-opts : ijkinject-opaque             = 1051858
06-07 19:15:43.638 tv.test.app I/IJKMEDIA: format-opts : http-detect-range-support    = 0
06-07 19:15:43.638 tv.test.app I/IJKMEDIA: codec-opts  : skip_loop_filter             = -16
06-07 19:15:43.638 tv.test.app I/IJKMEDIA: codec-opts  : skip_frame                   = -16
06-07 19:15:43.639 tv.test.app I/IJKMEDIA: ===================
06-07 19:15:43.646 tv.test.app I/IJKMEDIA: SDL_RunThread: [13745] ff_vout
06-07 19:15:43.647 tv.test.app I/IJKMEDIA: SDL_RunThread: [13746] ff_read
06-07 19:15:43.647 tv.test.app D/IJKMEDIA: ijkmp_prepare_async()=0
06-07 19:15:43.647 tv.test.app I/IJKMEDIA: SDL_RunThread: [13747] ecv_process
06-07 19:15:43.755 tv.test.app V/RenderScript: Application requested CPU execution
06-07 19:15:43.759 tv.test.app V/RenderScript: 0x9d3b2c00 Launching thread(s), CPUs 4
06-07 19:15:43.925 tv.test.app D/IJKMEDIA: Statistics: 11384 bytes read, 0 seeks
06-07 19:15:43.927 tv.test.app E/IJKMEDIA: http://video3.smoothhd.com/ondemand/Turner_Sports_PGA.ism/Manifest: Invalid data found when processing input
06-07 19:15:43.927 tv.test.app D/IJKMEDIA: FFP_MSG_ERROR: 0
06-07 19:15:43.928 tv.test.app I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [13746]
06-07 19:15:43.929 tv.test.app E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
06-07 19:15:43.929 tv.test.app D/IjkVideoView: Error: -10000,0

**Comment by bbcallen** [comment]
Can't be played in ffplay, too.
I doubt if ffmpeg support this format.

**Comment by jpoloczek** [comment]
This is supported by VLC that is build on ffmpeg.

**Comment by bbcallen** [comment]
AFAIK, VLC has it's own implements for many formats.
