### ISSUE TITLE
为什么同样的单一视频源，用ijkplayer比用默认的android内置播放器播放要模糊呢

### ISSUE THREAD

**Issue by hyyjy** [Bilibili/ijkplayer#1423]
视频源地址:http://www.hsz88.cn/video/hszmain.mp4

在安卓手机上，我用安卓的VideoView组件播放比ijkplayer的在全屏下看，要清晰些，这是为什么。请问ijkplayer有设置的地方吗，至少要跟VideoView的清晰度一样吧。

**Comment by bbcallen** [comment]
enable mediacodec.

**Comment by hyyjy** [comment]
谢谢，问题解决了，想再问下如果当前手机不支持这种硬解，而我在代码中指定了硬解，ijkplayer应该会自动用软解方式播放而不会出错的吧。

**Comment by seu070507** [comment]
不会的，需要自己添加这个功能

**Comment by zhangfeisysu** [comment]
@hyyjy 遇到了同样的问题，请问要怎么设置呢
