### ISSUE TITLE
怎样让视频根据宽度来按比例调整高度？

### ISSUE THREAD

**Issue by hyyjy** [Bilibili/ijkplayer#1425]
我在IjkVideoView外面包裹了一层relativelayout,relativelayout的宽度设置为match_parent,高度设置为wrap_content,我的想法是视频把宽度撑满，然后根据这个宽度按视频本身来等比例设置高度，这应该怎么实现，因为onMeasure方法已经removed了。

**Comment by hyyjy** [comment]
问题自己研究下，解决了，修改了doMeasure方法，不过方法不一定是最合适的。
原因是我是一个新闻详细页面，里面放了视频，文字，是包含在一个scrolview里面的，超出了屏幕，
所以在竖屏状态下ijkplayer的surfacerendview的doMeasure方法判断出来的heightSpecMode为UNSPECIFIED，进而heightSpecSize为0，走下来导致在页面中是以视频原始尺寸呈现，而不是我想要的宽度撑满，高度按视频尺寸自适应。
在横屏状态下，我是gone掉其他view的，所以播放器还是包含在scrolview里面的，从而实现视频全屏。这个时候魔术状态就出现了，heightSpecMode按道理应该为UNSPECIFIED，但是几次重绘以后，又变成了at_most的，从而正常全屏显示了。这是怎么回事？
我还想问的是，b站视频横屏全屏是怎么实现的，是不是也是gone掉其他view, 还是另开了一个窗口啥的？谢谢了~~

**Comment by bbcallen** [comment]
Sorry, bilibili is closed source software, I'm not authorized to talk about any technical detail in it.

**Comment by lijunhuayc** [comment]
你试试通过 setAspectRatio 设置 视频显示模式 试试

**Comment by DDCStoneLiu** [comment]
@bbcallen 不想解决问题 就别装逼了

**Comment by ipcjs** [comment]
这个@DDCStoneLiu是哪来的傻屌`(;¬_¬)`
