### ISSUE TITLE
返回码有具体的说明吗？不知道具体的意思

### ISSUE THREAD

**Issue by jjdxmashl** [Bilibili/ijkplayer#1426]
我当前做一个rtmp的拉流播放，停止推流或者中断推流了，返回码是哪一个的？希望能给一些返回码具体的说明

int MEDIA_INFO_UNKNOWN = 1;
    int MEDIA_INFO_STARTED_AS_NEXT = 2;
    int MEDIA_INFO_VIDEO_RENDERING_START = 3;
    int MEDIA_INFO_VIDEO_TRACK_LAGGING = 700;
    int MEDIA_INFO_BUFFERING_START = 701;
    int MEDIA_INFO_BUFFERING_END = 702;
    int MEDIA_INFO_NETWORK_BANDWIDTH = 703;
    int MEDIA_INFO_BAD_INTERLEAVING = 800;
    int MEDIA_INFO_NOT_SEEKABLE = 801;
    int MEDIA_INFO_METADATA_UPDATE = 802;
    int MEDIA_INFO_TIMED_TEXT_ERROR = 900;
    int MEDIA_INFO_UNSUPPORTED_SUBTITLE = 901;
    int MEDIA_INFO_SUBTITLE_TIMED_OUT = 902;

    int MEDIA_INFO_VIDEO_ROTATION_CHANGED = 10001;
    int MEDIA_INFO_AUDIO_RENDERING_START = 10002;

    int MEDIA_ERROR_UNKNOWN = 1;
    int MEDIA_ERROR_SERVER_DIED = 100;
    int MEDIA_ERROR_NOT_VALID_FOR_PROGRESSIVE_PLAYBACK = 200;
    int MEDIA_ERROR_IO = -1004;
    int MEDIA_ERROR_MALFORMED = -1007;
    int MEDIA_ERROR_UNSUPPORTED = -1010;
    int MEDIA_ERROR_TIMED_OUT = -110;

**Comment by bbcallen** [comment]
No, there is no detailed error code, for now.
You need to study the log output to find out what happens.

**Comment by lijunhuayc** [comment]
看字面意思可以理解大部分的。
比如MEDIA_INFO_BUFFERING_START  表示缓存开始
MEDIA_INFO_NOT_SEEKABLE  表示不可拖动
MEDIA_INFO_VIDEO_ROTATION_CHANGED 视频方向旋转
大概意思能知道的

**Comment by sunrise10** [comment]
不对望指正
     * int MEDIA_INFO_UNKNOWN = 1;//未知信息
     * int MEDIA_INFO_STARTED_AS_NEXT = 2;//播放下一条
     * int MEDIA_INFO_VIDEO_RENDERING_START = 3;//视频开始准备中，准备渲染
     * int MEDIA_INFO_VIDEO_TRACK_LAGGING = 700;//视频日志跟踪
     * int MEDIA_INFO_BUFFERING_START = 701;//开始缓冲中 开始缓冲
     * int MEDIA_INFO_BUFFERING_END = 702;//缓冲结束
     * int MEDIA_INFO_NETWORK_BANDWIDTH = 703;//网络带宽，网速方面
     * int MEDIA_INFO_BAD_INTERLEAVING = 800;//一个正常的媒体文件中，音频数据和视频数据因该是交错依次排列的，这样这个媒体才能被正常的播放，但是如果音频数据和视频数据没有正常交错排列，那里就会发出这个消息
     * int MEDIA_INFO_NOT_SEEKABLE = 801;//不可设置播放位置，直播方面
     * int MEDIA_INFO_METADATA_UPDATE = 802;//当有一组新的元数据有效的时候发出的通知
     * int MEDIA_INFO_TIMED_TEXT_ERROR = 900;
     * int MEDIA_INFO_UNSUPPORTED_SUBTITLE = 901;//不支持字幕
     * int MEDIA_INFO_SUBTITLE_TIMED_OUT = 902;//字幕超时
     * int MEDIA_INFO_VIDEO_INTERRUPT= -10000;//数据连接中断，一般是视频源有问题或者数据格式不支持，比如音频不是AAC之类的
     * int MEDIA_INFO_VIDEO_ROTATION_CHANGED = 10001;//视频方向改变，视频选择信息
     * int MEDIA_INFO_AUDIO_RENDERING_START = 10002;//音频开始准备中
     * int MEDIA_INFO_AUDIO_DECODED_START = 10003;//音频解码开始
     * int MEDIA_INFO_VIDEO_DECODED_START = 10004;//视频解码开始
     * int MEDIA_INFO_OPEN_INPUT = 10005;//avformat_open_input执行完成时间
     * int MEDIA_INFO_FIND_STREAM_INFO = 10006;//avformat_find_stream_info执行完成时间
     * int MEDIA_INFO_COMPONENT_OPEN = 10007;//IO设备操作完成时间
     * int MEDIA_INFO_VIDEO_SEEK_RENDERING_START = 10008;//seekTo第一帧视频数据渲染开始中
     * int MEDIA_INFO_AUDIO_SEEK_RENDERING_START = 10009;//seekTo第一帧音频数据渲染开始中
     * int MEDIA_INFO_MEDIA_ACCURATE_SEEK_COMPLETE = 10100; //准确seekTo已完成
     * int MEDIA_ERROR_UNKNOWN = 1;//未知错误
     * int MEDIA_ERROR_SERVER_DIED = 100;//服务挂掉，视频中断，一般是视频源异常或者不支持的视频类型,必须释放对象，然后开启新的实例。
     * int MEDIA_ERROR_NOT_VALID_FOR_PROGRESSIVE_PLAYBACK = 200;//数据错误没有有效的回收
     * int MEDIA_ERROR_IO = -1004;//IO 错误
     * int MEDIA_ERROR_MALFORMED = -1007;//流不符合有关标准或文件的编码规范
     * int MEDIA_ERROR_UNSUPPORTED = -1010;//比特流符合相关编码标准或文件的规格，但媒体框架不支持此功能
     * int MEDIA_ERROR_TIMED_OUT = -110;//数据超时
     * Error (-10000,0)
