### ISSUE TITLE
硬解码支持mpeg4 codec

### ISSUE THREAD

**Issue by seu070507** [Bilibili/ijkplayer#1428]
mpeg4 codec 也是比较常用的codec，请问ijk能否加上对mpeg4 硬解码的支持？

**Comment by seu070507** [comment]
视频编码格式是video/mp4v-es,这种格式算是比较普遍的？
是不是因为前面的codec config 不好分析计算

**Comment by Android4MediaPlayer** [comment]
It is not currently planned.

**Comment by seu070507** [comment]
能否提供思路？我现在想自己添加这个功能

**Comment by bbcallen** [comment]
I don't need it, so it's not in my config.
You can customize your own build config as config/module-whatever-you-want.sh, and link config/module.sh to it.

**Comment by seu070507** [comment]
@bbcallen 你理解错了我的意思
我是说如果实现video/mp4v-es的硬解码，mediacodec的 csd-0，csd-1等配置信息的计算该如何去完成。

**Comment by bbcallen** [comment]
I don't know. Take a look at VLC, XBMC, or latest FFmpeg.

**Comment by seu070507** [comment]
it is not only about mpeg4 codec.
I have noticed that in ijk, Codec specific data has been commented out expect h264/h265.
And also you give the commits: csd-0: naked

But vlc always set codec specific to mediacodec as long as extradata has data.

Could you please tell me the reason?

in function: ffpipenode_create_video_decoder_from_android_mediacodec


                       .........
                       
            // Codec specific data
            // SDL_AMediaFormat_setBuffer(opaque->aformat, "csd-0", opaque->avctx->extradata, opaque->avctx->extradata_size);
            ALOGE("csd-0: naked\n");
        }
                       .........

**Comment by seu070507** [comment]
@bbcallen @Android4MediaPlayer 

Any ideas?

**Comment by Android4MediaPlayer** [comment]
Take a look at VLC or ExoPlayer.

**Comment by bbcallen** [comment]
I've never tested the code path contains "csd-0: naked", because I don't have any video sample lead to that path. It's supposed to be an error.
