### ISSUE TITLE
Replay problem

### ISSUE THREAD

**Issue by GrayLuo** [Bilibili/ijkplayer#1429]
1、播放在线mp4时，stop后再play可以播放。
2、播放RTMP,RTSP流时，stop后，再play播放不了，无错误提示。需要recreate a player to play
why ? thx @bbcallen

**Comment by bbcallen** [comment]
1. For VOD stream, play after stop, means seek(0) and play()
2. For live stream, seek(0) makes no sense.

**Comment by GrayLuo** [comment]
so, 如果播放RTMP/RTSP流，锁屏、回到后台等操作返回前台后，如果想继续播放 并且 没有延迟就只能release 上一个播放器，重新创建一个播放器？ @bbcallen

**Comment by bbcallen** [comment]
1. Basically, yes, you need to create a new player, if you call stop().
2. Basically, yes, you need to call pause()/start(), and implement your "clear buffer" method in ff_ffplay.c, maybe packet_queue_flush() and something else.

**Comment by yswheye** [comment]
play after completed failed， must post delay mms。
I resolve this。
