### ISSUE TITLE
ios里面如何监控stat呢，就像安卓里面的MediaPlayer.OnInfoListener，ios里面是否有类似的api

### ISSUE THREAD

**Issue by nustee** [Bilibili/ijkplayer#1430]

**Comment by bbcallen** [comment]
Depending on what information you want to listen.

**Comment by Gagster** [comment]
你好，如这个问题所说，当网络不稳定时，视频会出现时断时续的情况。在这种情况下，通过什么方法能够监听到或者获取到视频的播放状态？当视频停顿住了，我就可以得到一个响应之类的

**Comment by Gagster** [comment]
@bbcallen

**Comment by bbcallen** [comment]
ijkplayer for iOS is very similar to MPMoviePlayerController
https://developer.apple.com/library/ios/documentation/MediaPlayer/Reference/MPMoviePlayerController_Class/

**Comment by Gagster** [comment]
Thank U~
