### ISSUE TITLE
Have support for ffmpeg command line/params? app playpath pageUrl swfUrl

### ISSUE THREAD

**Issue by FloridaStream** [Bilibili/ijkplayer#1435]
**ijkplayer** have suport for ffmpeg command line same as **vitamio**?

sample path command ```rtmp://0.0.0.0/live/ app=live playpath=channel20 token=whateversecure```
or ```http://samplesite.com/video.mp4``` ... _ps:i know, ijkplayer dont have librtmp_

```options.put("headers", "User-Agent: Mozilla/4.0 (compatible; MSIE 6.1; Windows XP) \r\n");```
```options.put("headers", "Cookie: acb=dsads\r\n");```

I use this on vitamio to load normal links and ffmpeg links commands and ffmpeg AVOptions
```mVideoView.setVideoURI(Uri.parse(path), options);```

```mVideoView.setVideoURI(Uri.parse("rtmp://0.0.0.0/live/ app=live playpath=channel20 token=whateversecure"), options);``` **app playpath and others ffmpeg command line are supported in vitamio, and in ijkplayer too?**

https://github.com/yixia/VitamioBundle/wiki/Use-FFmpeg-AVOption-in-Vitamio-4.1.0

I hope this helps you better understand what I said.

I use these custom ffmpeg parameters to run compounds links, but vitamio is unsupported, and wanted to migrate my project, I do not know if your can meet my needs.

The vitamio also use the isPlaying functions onComplete among other basic functions. 
@bbcallen

**Comment by FloridaStream** [comment]
>  **I can play with `setDataSource("rtmp://0.0.0.0/live/ app=live playpath=channel20");` ?**

- Otlher sample with ffmpeg params. _dont try to play, only a sample_

`setDataSource("rtmp://213.16.167.36/vod/ playpath=mp4:0fb03ab9-ce2d-455f-982c-6090555e0961.mp4 pageUrl=http://www.antenna.gr/webtv/watch?cid=_s/g_x_j_e7gv_o_e= swfUrl=http://www.antenna.gr/webtv/images/fbplayer.swf swfVfy=true timeout=10");`

- Using _ffmpeg_ command lines `app ` `playpath ` and othes? I need to know that, my application makes use of these _ffmpeg_ and other functions.

- I intend to build with the `librtmp `in order to have more functions, such as `token=SecureToken`

**Comment by FloridaStream** [comment]
I tried ... @bbcallen 

**LogCat**
```
06-10 23:38:02.860 32625-32625/short.ijkplayer.example D/IJKMEDIA: IjkMediaPlayer_native_profileBegin
short.ijkplayer.example W/IJKMEDIA: monstartup already called
short.ijkplayer.example D/dou361: NoSuchFieldException: class=drawable fieldname=imple_player_circle_outline_white_36dp
short.ijkplayer.example W/EGL_genymotion: eglSurfaceAttrib not implemented
short.ijkplayer.example D/IJKMEDIA: IjkMediaPlayer_native_setup
short.ijkplayer.example I/IJKMEDIA: av_version_info: ff2.8--ijk0.4.1.1--dev0.3.3--rc4
short.ijkplayer.example D/IJKMEDIA: ffpipeline_create_from_android()
short.ijkplayer.example D/IJKMEDIA: ijkmp_set_inject_opaque(0x1d300472)
short.ijkplayer.example D/IJKMEDIA: ijkmp_set_inject_opaque()=void
short.ijkplayer.example D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
short.ijkplayer.example D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
short.ijkplayer.example D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
short.ijkplayer.example D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(3)
short.ijkplayer.example D/IJKMEDIA: moncleanup
short.ijkplayer.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
short.ijkplayer.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
short.ijkplayer.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
short.ijkplayer.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
short.ijkplayer.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
short.ijkplayer.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
short.ijkplayer.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
short.ijkplayer.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
short.ijkplayer.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
short.ijkplayer.example D/tv.danmaku.ijk.media.player.IjkMediaPlayer: Couldn't open file on client side, trying server side
short.ijkplayer.example D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
short.ijkplayer.example V/IJKMEDIA: setDataSource: path rtmp://stream.grupotelemicro.com:9095/live5/ app=live5 playpath=telemicro0505_1_96
short.ijkplayer.example D/IJKMEDIA: ijkmp_set_data_source(url="rtmp://stream.grupotelemicro.com:9095/live5/ app=live5 playpath=telemicro0505_1_96")
short.ijkplayer.example D/IJKMEDIA: ijkmp_set_data_source(url="rtmp://stream.grupotelemicro.com:9095/live5/ app=live5 playpath=telemicro0505_1_96")=0
short.ijkplayer.example D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
short.ijkplayer.example D/IJKMEDIA: ijkmp_set_android_surface(surface=0x69b0001d)
short.ijkplayer.example D/IJKMEDIA: ffpipeline_set_surface()
short.ijkplayer.example D/IJKMEDIA: ijkmp_set_android_surface(surface=0x69b0001d)=void
short.ijkplayer.example D/IJKMEDIA: IjkMediaPlayer_prepareAsync
short.ijkplayer.example D/IJKMEDIA: ijkmp_prepare_async()
short.ijkplayer.example W/IJKMEDIA: remove 'timeout' option for rtmp.
short.ijkplayer.example I/IJKMEDIA: ===== versions =====
short.ijkplayer.example I/IJKMEDIA: FFmpeg       : ff2.8--ijk0.4.1.1--dev0.3.3--rc4
short.ijkplayer.example I/IJKMEDIA: libavutil    : 54.31.100
short.ijkplayer.example I/IJKMEDIA: libavcodec   : 56.60.100
short.ijkplayer.example I/IJKMEDIA: libavformat  : 56.40.101
short.ijkplayer.example I/IJKMEDIA: libswscale   : 3.1.101
short.ijkplayer.example I/IJKMEDIA: libswresample: 1.2.101
short.ijkplayer.example I/IJKMEDIA: ===== options =====
short.ijkplayer.example I/IJKMEDIA: player-opts : mediacodec                   = 0
short.ijkplayer.example I/IJKMEDIA: player-opts : opensles                     = 0
short.ijkplayer.example I/IJKMEDIA: player-opts : overlay-format               = 842225234
short.ijkplayer.example I/IJKMEDIA: player-opts : framedrop                    = 1
short.ijkplayer.example I/IJKMEDIA: player-opts : start-on-prepared            = 0
short.ijkplayer.example I/IJKMEDIA: format-opts : ijkinject-opaque             = 489686130
short.ijkplayer.example I/IJKMEDIA: format-opts : http-detect-range-support    = 0
short.ijkplayer.example I/IJKMEDIA: format-opts : reconnect                    = 1
short.ijkplayer.example I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
short.ijkplayer.example I/IJKMEDIA: ===================
short.ijkplayer.example D/IJKMEDIA: ijkmp_prepare_async()=0
short.ijkplayer.example I/IJKMEDIA: SDL_RunThread: [3838] ff_read
short.ijkplayer.example W/IJKMEDIA: remove 'timeout' option for rtmp.
short.ijkplayer.example W/IJKMEDIA: Detected librtmp style URL parameters, these aren't supported by the libavformat internal RTMP handler currently enabled. See the documentation for the correct way to pass parameters.
short.ijkplayer.example I/IJKMEDIA: SDL_RunThread: [3836] ff_msg_loop
short.ijkplayer.example D/IJKMEDIA: message_loop
short.ijkplayer.example D/IJKMEDIA: FFP_MSG_FLUSH:
short.ijkplayer.example I/IJKMEDIA: SDL_RunThread: [3837] ff_vout
short.ijkplayer.example D/IJKMEDIA: Handshaking...
short.ijkplayer.example D/IJKMEDIA: Type answer 3
short.ijkplayer.example D/IJKMEDIA: Server version 3.0.1.1
short.ijkplayer.example D/IJKMEDIA: Proto = rtmp, path = /live5/, app = live5, fname = 
short.ijkplayer.example D/IJKMEDIA: Server bandwidth = 2500000
short.ijkplayer.example D/IJKMEDIA: Client bandwidth = 2500000
short.ijkplayer.example D/IJKMEDIA: New incoming chunk size = 4096
short.ijkplayer.example D/IJKMEDIA: Creating stream...
short.ijkplayer.example D/IJKMEDIA: Sending play command for ''
short.ijkplayer.example E/IJKMEDIA: Server error: Failed to play ; stream not found.
short.ijkplayer.example E/IJKMEDIA: rtmp://stream.grupotelemicro.com:9095/live5/ app=live5 playpath=telemicro0505_1_96: Operation not permitted
short.ijkplayer.example I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [3838]
short.ijkplayer.example D/IJKMEDIA: FFP_MSG_ERROR: 0
short.ijkplayer.example E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
short.ijkplayer.example D/IjkVideoView: Error: -10000,0
```
On play Stream
`rtmp://stream.grupotelemicro.com:9095/live5/ app=live5 playpath=telemicro0505_1_96`

I get this message
> Detected librtmp style URL parameters, these aren't supported by the libavformat internal RTMP handler currently enabled. See the documentation for the correct way to pass parameters.

<br>
### it seems to me I have to compile ijkplayer with librtmp to have access to these resources, is it?
<br>
Sample parameters that I would like to have.
`swfUrl`, `pageUrl`, `token`(_with my lirtmp_), `playPath`, `flashVer`, `swfVfy`, `Conn`, `timeout`, `live=1`
_I'd appreciate any quick response, I plan to migrate from vitamio which is not supporte and is outdated._
Ref: https://rtmpdump.mplayerhq.hu/rtmpdump.1.html
![o 25282 2529 1](https://cloud.githubusercontent.com/assets/7586648/15982985/751817fc-2f6f-11e6-9343-dd5a1bc08cf1.jpg)

Thank you for your attention. :green_heart:

**Comment by bbcallen** [comment]
1. Yes for librtmp part. FYI, there is also native rtmp implement in FFmpeg.
2. Check IJKMediaPlayer.setOption(), it also been used in demo.

**Comment by FloridaStream** [comment]
I raised a question in Portuguese stackoverflow to try to implement the librtmp. If anyone has curiosity to help, please post here or post there with the answer translated into Portuguese, grateful.


**http://pt.stackoverflow.com/q/135529/8984?stw=2**


http://translate.googleusercontent.com/translate_c?depth=1&hl=en&rurl=translate.google.com&sl=pt-BR&tl=en&u=http://pt.stackoverflow.com/questions/135529/como-criar-um-build-script-para-compilar-o-librtmp-com-o-openssl&usg=ALkJrhjBx9KRpQkrLx6p0aRXblHOORxT3Q

**Comment by FloridaStream** [comment]
:heart:

**Comment by garanda21** [comment]
Do you resolve this? I'm interested to do the same thing using ijkplayer play this special rtmp urls with playpath and token. 

Appreciate any help.

**Comment by FloridaStream** [comment]
U need to make a custom compile/codes/changes to compile, its not easy. 
That's all I can say. @garanda21

**Comment by diaconuliviu85** [comment]
you did anyway? I tested but I could not . Please indicate you give ?
