### ISSUE TITLE
m3u8 Video can not get the duration

### ISSUE THREAD

**Issue by xiaomianbao** [Bilibili/ijkplayer#1437]
http://9281.live-vod.cdn.aodianyun.com/m3u8/0x0/wsp_9281_1452595928.e984be45394c5928b7f4b4d0aaf34c39.1461993361/wsp_9281_1452595928.e984be45394c5928b7f4b4d0aaf34c39.1461993361.m3u8

this is my url , I can not get the duration in ios , but it can get the duration in Android  ,we all use the ijkplayer   help me please.

我的同事都是用ijkplayer   同样的视频链接, 安卓的同事可以获取到duration 并且可以拖动视频 , ios的ijkplayer就不可以  请问需要怎么去设置

**Comment by Android4MediaPlayer** [comment]
Give a detailed log.

**Comment by Android4MediaPlayer** [comment]
#1284

**Comment by xiaomianbao** [comment]
===== custom modules begin =====
register protocol: async
register protocol: ijkhttphook
register protocol: ijkinject
register protocol: ijklongurl
register protocol: ijksegment
register protocol: ijktcphook
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff2.8--ijk0.4.1.1--dev0.3.3--rc4
ijkmp_set_inject_opaque(0x12c71ad00)
ijkmp_set_inject_opaque()=void
2016-06-12 10:37:00.567 IJKMediaDemo[1796:1012171] OK setup GL
ijkmp_ios_set_view(glView=0x12d835870)
ijkmp_ios_set_view(glView=0x12d835870)=void
ijkmp_set_data_source(url="http://9281.live-vod.cdn.aodianyun.com/m3u8/0x0/wsp_9281_1452595928.e984be45394c5928b7f4b4d0aaf34c39.1461993361/wsp_9281_1452595928.e984be45394c5928b7f4b4d0aaf34c39.1461993361.m3u8")
ijkmp_set_data_source(url="http://9281.live-vod.cdn.aodianyun.com/m3u8/0x0/wsp_9281_1452595928.e984be45394c5928b7f4b4d0aaf34c39.1461993361/wsp_9281_1452595928.e984be45394c5928b7f4b4d0aaf34c39.1461993361.m3u8")=0
ijkmp_prepare_async()
===== versions =====
FFmpeg       : ff2.8--ijk0.4.1.1--dev0.3.3--rc4
libavutil    : 54.31.100
libavcodec   : 56.60.100
libavformat  : 56.40.101
libswscale   : 3.1.101
libswresample: 1.2.101
===== options =====
player-opts : video-pictq-size             = 3
player-opts : overlay-format               = fcc-i420
player-opts : max-fps                      = 60
player-opts : framedrop                    = 0
player-opts : videotoolbox-max-frame-width = 960
player-opts : videotoolbox                 = 1
player-opts : start-on-prepared            = 1
format-opts : ijkinject-opaque             = 5040614656
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : timeout                      = 30000000
format-opts : reconnect                    = 1
format-opts : safe                         = 0
codec-opts  : skip_frame                   = 0
codec-opts  : skip_loop_filter             = 0
===================
ijkmp_prepare_async()=0
request: GET /m3u8/0x0/wsp_9281_1452595928.e984be45394c5928b7f4b4d0aaf34c39.1461993361/wsp_9281_1452595928.e984be45394c5928b7f4b4d0aaf34c39.1461993361.m3u8 HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=0-

Connection: close

Host: 9281.live-vod.cdn.aodianyun.com

Icy-MetaData: 1

**Comment by xiaomianbao** [comment]
Continuity check failed for pid 0 expected 1 got 0
Continuity check failed for pid 4097 expected 1 got 0
HLS request for url 'http://9281.live-vod.cdn.aodianyun.com/m3u8/0x0/wsp_9281_1452595928.e984be45394c5928b7f4b4d0aaf34c39.1461993361/wsp_9281_1452595928-e984be45394c5928b7f4b4d0aaf34c39-1461993361-1461993374049-4000.ts', offset 0, playlist 0
No trailing CRLF found in HTTP header.
request: GET /m3u8/0x0/wsp_9281_1452595928.e984be45394c5928b7f4b4d0aaf34c39.1461993361/wsp_9281_1452595928-e984be45394c5928b7f4b4d0aaf34c39-1461993361-1461993374049-4000.ts HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Connection: close

Host: 9281.live-vod.cdn.aodianyun.com

Icy-MetaData: 1

**Comment by xiaomianbao** [comment]
Format mpegts probed with size=2048 and score=100
stream=0 stream_type=1b pid=100 prog_reg_desc=
stream=1 stream_type=f pid=101 prog_reg_desc=
Before avformat_find_stream_info() pos: 0 bytes read:12082 seeks:0
2016-06-12 10:40:17.320 IJKMediaDemo[1799:1013450] ==========进度?======0.000000
no picture 
All info found
After avformat_find_stream_info() pos: 216952 bytes read:231657 seeks:0 frames:57
Option safe not found.
Before avformat_find_stream_info() pos: 88898 bytes read:88898 seeks:0
no picture 
All info found
After avformat_find_stream_info() pos: 88898 bytes read:88898 seeks:0 frames:57
max_frame_duration: 10.000
Input #0, hls,applehttp, from 'http://9281.live-vod.cdn.aodianyun.com/m3u8/0x0/wsp_9281_1452595928.e984be45394c5928b7f4b4d0aaf34c39.1461993361/wsp_9281_1452595928.e984be45394c5928b7f4b4d0aaf34c39.1461993361.m3u8':
  Duration: 00:59:59.20, start: 21604.385000, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0, 21, 1/90000: Video: h264, 4 reference frames ([27][0][0][0] / 0x001B), yuv420p(left), 1280x720 [SAR 1:1 DAR 16:9], 1/50, 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1, 36, 1/90000: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 103 kb/s
detected 2 logical cores
Setting 'sample_rate' to value '48000'
Setting 'sample_fmt' to value 'fltp'
Setting 'channels' to value '2'
Setting 'time_base' to value '1/48000'
Setting 'channel_layout' to value '0x3'
tb:1/48000 samplefmt:fltp samplerate:48000 chlayout:0x3
auto-inserting filter 'auto-inserted resampler 0' between the filter 'ffplay_abuffer' and the filter 'ffplay_abuffersink'
query_formats: 2 queried, 0 merged, 3 already done, 0 delayed
Using fltp internally between filters
ch:2 chl:stereo fmt:fltp r:48000Hz -> ch:2 chl:stereo fmt:s16 r:48000Hz
aout_open_audio()
2016-06-12 10:40:17.821 IJKMediaDemo[1799:1013450] ==========进度?======0.000000
AudioCodec: avcodec, aac
aout_pause_audio(0)
vtb fail!!! switch to ffmpeg decode!!!! 
VideoCodec: avcodec, h264
2016-06-12 10:40:17.891 IJKMediaDemo[1799:1013450] FFP_MSG_VIDEO_DECODER_OPEN: false
fps: 25.000000 (normal)
fps: 25.000000 (normal)
ijkmp_get_msg: FFP_MSG_PREPARED
2016-06-12 10:40:17.892 IJKMediaDemo[1799:1013450] FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
2016-06-12 10:40:17.893 IJKMediaDemo[1799:1013450] FFP_MSG_SAR_CHANGED: 1, 1
2016-06-12 10:40:17.893 IJKMediaDemo[1799:1013450] FFP_MSG_PREPARED:
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
2016-06-12 10:40:17.893 IJKMediaDemo[1799:1013450] fps in meta 25.000000
2016-06-12 10:40:17.893 IJKMediaDemo[1799:1013450] mediaIsPreparedToPlayDidChange
2016-06-12 10:40:17.893 IJKMediaDemo[1799:1013450] loadStateDidChange: IJKMPMovieLoadStatePlaythroughOK: 3
2016-06-12 10:40:17.894 IJKMediaDemo[1799:1013450] IJKMPMoviePlayBackStateDidChange 1: playing
no picture 
no picture 
Audio frame changed from rate:48000 ch:2 fmt:fltp layout:stereo serial:-1 to rate:48000 ch:2 fmt:fltp layout:stereo serial:1
Setting 'sample_rate' to value '48000'
Setting 'sample_fmt' to value 'fltp'
Setting 'channels' to value '2'
Setting 'time_base' to value '1/48000'
Setting 'channel_layout' to value '0x3'
tb:1/48000 samplefmt:fltp samplerate:48000 chlayout:0x3
auto-inserting filter 'auto-inserted resampler 0' between the filter 'ffplay_abuffer' and the filter 'ffplay_abuffersink'
query_formats: 2 queried, 0 merged, 3 already done, 0 delayed
Using fltp internally between filters
ch:2 chl:stereo fmt:fltp r:48000Hz -> ch:2 chl:stereo fmt:s16 r:48000Hz
ffp_toggle_buffering_l: start
aout_pause_audio(1)
2016-06-12 10:40:17.954 IJKMediaDemo[1799:1013450] FFP_MSG_BUFFERING_START:
2016-06-12 10:40:17.954 IJKMediaDemo[1799:1013450] loadStateDidChange: IJKMPMovieLoadStateStalled: 4
HLS request for url 'http://9281.live-vod.cdn.aodianyun.com/m3u8/0x0/wsp_9281_1452595928.e984be45394c5928b7f4b4d0aaf34c39.1461993361/wsp_9281_1452595928-e984be45394c5928b7f4b4d0aaf34c39-1461993361-1461993370031-4000.ts', offset 0, playlist 0
No trailing CRLF found in HTTP header.
Video frame changed from size:0x0 format:none serial:-1 to size:1280x720 format:yuv420p serial:1
Setting 'video_size' to value '1280x720'
Setting 'pix_fmt' to value '0'
Setting 'time_base' to value '1/90000'
Setting 'pixel_aspect' to value '1/1'
Setting 'frame_rate' to value '25/1'
w:1280 h:720 pixfmt:yuv420p tb:1/90000 fr:25/1 sar:1/1 sws_param:
Setting 'out_w' to value 'floor(in_w/2)*2'
Setting 'out_h' to value 'floor(in_h/2)*2'
query_formats: 3 queried, 2 merged, 0 already done, 0 delayed
w:1280 h:720 sar:1/1 -> w:1280 h:720 sar:1/1
SDL_VoutFFmpeg_CreateOverlay(w=1280, h=720, fmt=I420(0x30323449, dp=0x15ff7a190)
Video: first frame decoded
2016-06-12 10:40:17.980 IJKMediaDemo[1799:1013450] FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
SDL_VoutFFmpeg_CreateOverlay(w=1280, h=720, fmt=I420(0x30323449, dp=0x15ff7a190)
2016-06-12 10:40:17.987 IJKMediaDemo[1799:1013450] FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
SDL_VoutFFmpeg_CreateOverlay(w=1280, h=720, fmt=I420(0x30323449, dp=0x15ff7a190)
2016-06-12 10:40:17.988 IJKMediaDemo[1799:1013450] FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
request: GET /m3u8/0x0/wsp_9281_1452595928.e984be45394c5928b7f4b4d0aaf34c39.1461993361/wsp_9281_1452595928-e984be45394c5928b7f4b4d0aaf34c39-1461993361-1461993370031-4000.ts HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Connection: close

Host: 9281.live-vod.cdn.aodianyun.com

Icy-MetaData: 1

**Comment by xiaomianbao** [comment]
HLS request for url 'http://9281.live-vod.cdn.aodianyun.com/m3u8/0x0/wsp_9281_1452595928.e984be45394c5928b7f4b4d0aaf34c39.1461993361/wsp_9281_1452595928-e984be45394c5928b7f4b4d0aaf34c39-1461993361-1461993366017-4000.ts', offset 0, playlist 0
No trailing CRLF found in HTTP header.
request: GET /m3u8/0x0/wsp_9281_1452595928.e984be45394c5928b7f4b4d0aaf34c39.1461993361/wsp_9281_1452595928-e984be45394c5928b7f4b4d0aaf34c39-1461993361-1461993366017-4000.ts HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Connection: close

Host: 9281.live-vod.cdn.aodianyun.com

Icy-MetaData: 1

**Comment by Android4MediaPlayer** [comment]
Duration: 00:59:59.20,

**Comment by xiaomianbao** [comment]
- (void)viewDidLoad
{
    [super viewDidLoad];
    // Do any additional setup after loading the view from its nib.

//    [[UIApplication sharedApplication] setStatusBarHidden:YES];
//    [[UIApplication sharedApplication] setStatusBarOrientation:UIInterfaceOrientationLandscapeLeft animated:NO];
    
  self.timer   = [NSTimer scheduledTimerWithTimeInterval:1 target:self selector:@selector(test) userInfo:nil repeats:YES];

#ifdef DEBUG
    [IJKFFMoviePlayerController setLogReport:YES];
    [IJKFFMoviePlayerController setLogLevel:k_IJK_LOG_DEBUG];
#else
    [IJKFFMoviePlayerController setLogReport:NO];
    [IJKFFMoviePlayerController setLogLevel:k_IJK_LOG_INFO];
#endif

    [IJKFFMoviePlayerController checkIfFFmpegVersionMatch:YES];
     [IJKFFMoviePlayerController checkIfPlayerVersionMatch:YES major:1 minor:0 micro:0];

    IJKFFOptions *options = [IJKFFOptions optionsByDefault];
    [options setFormatOptionValue:@"ijktcphook" forKey:@"http-tcp-hook"];
    self.player = [[IJKFFMoviePlayerController alloc] initWithContentURL:[NSURL URLWithString:@"http://9281.live-vod.cdn.aodianyun.com/m3u8/0x0/wsp_9281_1452595928.e984be45394c5928b7f4b4d0aaf34c39.1461993361/wsp_9281_1452595928.e984be45394c5928b7f4b4d0aaf34c39.1461993361.m3u8"] withOptions:options];
    self.player.view.autoresizingMask = UIViewAutoresizingFlexibleWidth|UIViewAutoresizingFlexibleHeight;
    self.player.view.frame = self.view.bounds;
    self.player.scalingMode = IJKMPMovieScalingModeAspectFit;
    self.player.shouldAutoplay = YES;

    IJKFFMoviePlayerController *ffp = self.player;
    ffp.httpOpenDelegate = self;
    
    self.view.autoresizesSubviews = YES;
    [self.view addSubview:self.player.view];
    [self.view addSubview:self.mediaControl];
    
    self.mediaControl.delegatePlayer = self.player;
}

- (void)test
{
    IJKFFMoviePlayerController *ffp = self.player
    
    NSLog(@"duration  = %zd" ,ffp.duration);//获取播放的总时长
}

this the ios code :
this code is from  the ios demo one month ago   i can not get the duration in the demo , should i pull the new demo ? 
这是一多月前我下载的ijkplayer的demo  ,还是无法 获取播放的duration  是否要重新拉取一次最新的代码

**Comment by Android4MediaPlayer** [comment]
Yes,Maybe.

**Comment by xiaomianbao** [comment]
@Android4MediaPlayer   thinks ,  the new version ijkplayer solve the problem

**Comment by Android4MediaPlayer** [comment]
OK.
