### ISSUE TITLE
seekto 部分视频问题（doesn't provide more RBSP data in PPS）

### ISSUE THREAD

**Issue by UC10D** [Bilibili/ijkplayer#1438]
IJKMEDIA: HLS request for url 'http://121.46.19.92/ipad?file=/126/161/4lEFV0BgT02QK92xPlfFME.mp4&start=135.4&end=152.066&sig=I-I1PCrfPiFaFeTjGptRbISaj6dAbjGM&ch=my&cateCode=127119&vid=84105470&uid=null&plat=15&pt=6&prod=ott&pg=1&eye=0&cv=&qd=816', offset 0, playlist 0

Current profile doesn't provide more RBSP data in PPS, skipping

**Comment by lyqaiym** [comment]
http://laoshi.xueersi.com/AppIosCourse/getVideoPath/33355/237046
我这个视频也是，不能seekTo(0);要不一直不能回调onSeekComplete
你们的demo也不行

**Comment by Android4MediaPlayer** [comment]
works for me

**Comment by bbcallen** [comment]
Works for me.
