### ISSUE TITLE
点播播放ts流获取不到总时间，不能快进快退要怎么解决

### ISSUE THREAD

**Issue by pyp163** [Bilibili/ijkplayer#1439]
private void seekTo(int data) {
        int seek = ((int)getCurrent()) + data;
        LogDog.i("seek:"+seek+",getCurrent:"+getCurrent());
        mVideoView.seekTo(seek);
       
    }

**Comment by bbcallen** [comment]
Wrap it into HLS(m3u8).

**Comment by pyp163** [comment]
那不就要把ts转换m3u8吗工程太大了，IjkExoMediaPlayer获取不到ts的总时间，IjkMediaPlayer可以获取到总时间，播放ts，IjkExoMediaPlayer只需要两到三秒就播出来了，IjkMediaPlayer要十秒左右才能播出，什么原因？

**Comment by bbcallen** [comment]
I don't know.
