### ISSUE TITLE
如何减少直播视频流的延迟时间

### ISSUE THREAD

**Issue by vitanie** [Bilibili/ijkplayer#1440]
第一次接触ios ijkplayer，客户端的视频流和服务端的RTMP视频流延迟在1-2s之间，如何让延迟的时间缩短呢？请指教
以下是我的设置
IJKFFOptions *options = [IJKFFOptions optionsByDefault]; //使用默认配置
    [options setPlayerOptionIntValue:10 forKey:@"max-buffer-size"];
    [options setFormatOptionIntValue:10 forKey:@"rtbufsize"];
    [options setFormatOptionIntValue:2000000 forKey:@"analyzeduration"];
    [options setFormatOptionValue:@"nobuffer" forKey:@"fflags"];
    [options setFormatOptionIntValue:4096 forKey:@"probsize"];

#define DEFAULT_HIGH_WATER_MARK_IN_BYTES        (256 * 1024)

/*
 * START: buffering after prepared/seeked
 * NEXT:  buffering for the second time after START
 * MAX:   ...
 */
#define DEFAULT_START_HIGH_WATER_MARK_IN_MS     (100)
#define DEFAULT_NEXT_HIGH_WATER_MARK_IN_MS      (600)
#define DEFAULT_MAX_HIGH_WATER_MARK_IN_MS       (2 * 1000)

#define BUFFERING_CHECK_PER_BYTES               (512)
#define BUFFERING_CHECK_PER_MILLISECONDS        (200)

#define MAX_QUEUE_SIZE (5 * 1024 * 1024)
#ifdef FFP_MERGE
#define MIN_FRAMES 25
#endif
#define DEFAULT_MIN_FRAMES  5000
#define MIN_MIN_FRAMES      5
#define MAX_MIN_FRAMES      30000
#define MIN_FRAMES (ffp->min_frames)
#define EXTERNAL_CLOCK_MIN_FRAMES 2
#define EXTERNAL_CLOCK_MAX_FRAMES 10

**Comment by bbcallen** [comment]
Reduce DEFAULT_MAX_HIGH_WATER_MARK_IN_MS

**Comment by congni** [comment]
麻烦问一下，你的延迟解决了吗？

**Comment by vitanie** [comment]
目前效果不是理想  刚启动10分钟以内 延迟200ms左右 10分钟以后就从200ms的延迟增加到700ms

**Comment by xiangfly11** [comment]
有没有可能是因为网络信号强弱影响，在网络状态不好的时候存在积累包的状态，当网络状态好的情况下这些包被一次性发送出来。因此时间一长产生了延时的积累量。如果是这样有没有可能在网络状态较弱的情况下丢弃一些包？

**Comment by dourgulf** [comment]
播放器是否有一些属性能够知道当前buffer已经比较多了? 目前看上层对象有一个playableDuration, 看样子就是缓冲区里可以播放的总时长对吗? @bbcallen , 如果是的话, 有没有一个对应的当前播放的进度参数(是currentPlaybackTime吗?). 我调试发现, 有时候currentPlaybackTime竟然比playableDuration还大

**Comment by Fatsong** [comment]
@vitanie 您好，我是个新手。。。能否请问前辈上文提及的：
#define DEFAULT_HIGH_WATER_MARK_IN_BYTES (256 * 1024)
/*
START: buffering after prepared/seeked
NEXT: buffering for the second time after START
MAX: ... */ #define DEFAULT_START_HIGH_WATER_MARK_IN_MS (100) #define DEFAULT_NEXT_HIGH_WATER_MARK_IN_MS (600) #define DEFAULT_MAX_HIGH_WATER_MARK_IN_MS (2 * 1000)
#define BUFFERING_CHECK_PER_BYTES (512)
#define BUFFERING_CHECK_PER_MILLISECONDS (200)

#define MAX_QUEUE_SIZE (5 * 1024 * 1024)
#ifdef FFP_MERGE
#define MIN_FRAMES 25
#endif
#define DEFAULT_MIN_FRAMES 5000
#define MIN_MIN_FRAMES 5
#define MAX_MIN_FRAMES 30000
#define MIN_FRAMES (ffp->min_frames)
#define EXTERNAL_CLOCK_MIN_FRAMES 2
#define EXTERNAL_CLOCK_MAX_FRAMES 10

的这些配置参数具体是在哪里设置的呢？

**Comment by dourgulf** [comment]
@Fatsong  全文查找总能找到他们的踪影~

**Comment by Fatsong** [comment]
@dourgulf 谢谢~但是我用的是ijkplayer demo生成的.framework包...这些参数在工程中搜不到...所以这些东西是ffmpeg相关的参数吗...

**Comment by dourgulf** [comment]
demo里就有

**Comment by Fatsong** [comment]
@dourgulf 谢谢指导,我之前直接用的别人合并的framework包,所以找不到这些参数.我重新下载编译之后,修改了对应的FFMPEG的参数.用了一个Wowza官方的推流程序测试刚开始播放延迟在1秒以内.

**Comment by Yacong** [comment]
@dourgulf 兄弟，你的设置能给我看一下吗

**Comment by zhaoxiaobao** [comment]
延迟好像解决了一些

**Comment by notedit** [comment]
tcp有累积延迟  用tcp做低延迟播放不现实

**Comment by chenqitao** [comment]
@Fatsong 请问修改的是哪些参数呢

**Comment by Fatsong** [comment]
@chenqitao 就上文提及的那些设置,我自己没再对其他的参数做过什么改动,不过延迟问题主要还是要解决服务器端的问题,客户端能做的也就是根据直播需求修改一些参数,再没什么技术性的工作了

**Comment by zhang-bao** [comment]
@Fatsong 能把你打的包发我一份吗？1114684552@qq.com  谢谢

**Comment by jiuhexiazi** [comment]
缓冲设置
//最大缓存大小3KB
[options setPlayerOptionIntValue:(3*1024*1024) forKey:@"max-buffer-size"];
//无限读
 [options setPlayerOptionIntValue:1 forKey:@"infbuf"];
媒体流的构成和基本信息设置，针对视频分辨率小的设置（视频分辨率较大的时候可能会异常）
[options setFormatOptionIntValue:2048 forKey:@"probesize"];
 [options setFormatOptionIntValue:1000 forKey:@"analyzeduration"];
我设置这些视频出流快了不少，延时也相对减少，你们可以参考一下

**Comment by xiaomaxiaoma** [comment]
@Fatsong  能给个你设置好的framework嘛？iosdev_ma@163.com

**Comment by xiaomaxiaoma** [comment]
@vitanie  你好，你就设置成你说的那些参数，延迟就达到300MS了嘛？我按照你的设置怎么延迟比腾讯的播放器延迟还高呢，腾讯的不到1S，这个要2-3S，请问还要做什么配置吗
