### ISSUE TITLE
使用ijkplayer播rtmp流，远程服务端的rtmp服务断了，ijkplayer有回调消息吗?

### ISSUE THREAD

**Issue by vitanie** [Bilibili/ijkplayer#1441]
使用ijkplayer播rtmp流，远程服务端的rtmp服务断了，ijkplayer有回调消息吗?

**Comment by vitanie** [comment]
@devloe @devloe @tewilove @epruseal

**Comment by bbcallen** [comment]
search OnCompletionListener and OnErrorListener

**Comment by zywang** [comment]
请教，OnCompletionListener，这个对应iOS的函数是哪个
