### ISSUE TITLE
编译包含debug信息的ffmpeg库失败，要如何才能编译得到包含调试信息，可以在xcode中step into到ffmpeg库中呢？

### ISSUE THREAD

**Issue by walkermi** [Bilibili/ijkplayer#1443]
iOS版，按照文档这样
git clone https://github.com/Bilibili/ijkplayer.git ijkplayer-ios
cd ijkplayer-ios
git checkout -B latest k0.5.1

./init-ios.sh

cd ios
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all
编译正常，可以正常运行demo。但断点后无法step into到ffmpeg库代码中。

./compile-ffmpeg.sh all 改成
./compile-ffmpeg.sh all debug，编译就失败了。

CC	libavcodec/h264_cavlc.o
CC	libavcodec/h264_direct.o
error: invalid operand for inline asm constraint 'i' at line 2540962
make: *** [libavcodec/h264_direct.o] Error 1
make: *** Waiting for unfinished jobs....

请问，要如何才能编译得到包含调试信息，可以在xcode中step into到ffmpeg库中呢？

**Comment by bbcallen** [comment]
Did you run './compile-ffmpeg.sh clean', after changing it to debug?

**Comment by walkermi** [comment]
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all debug
再次编译debug前，确认是clean过的。
也试过git clone，直接尝试编译debug库，也是不行的。

**Comment by walkermi** [comment]
1、测试
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh armv7 debug
失败

2、测试
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh arm64 debug
成功

3、测试
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh i386 debug
成功

4、测试
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh x86_64 debug
成功

@bbcallen

**Comment by walkermi** [comment]
clang -v
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by bbcallen** [comment]
I can reproduce this problem here.
Seem's an FFmpeg issue, I'll see if I can make a workaround.

**Comment by walkermi** [comment]
case "$FF_BUILD_OPT" in
    debug)
        FFMPEG_CFG_FLAGS_ARM="$FFMPEG_CFG_FLAGS_ARM --disable-optimizations"
        FFMPEG_CFG_FLAGS_ARM="$FFMPEG_CFG_FLAGS_ARM --enable-debug"
        FFMPEG_CFG_FLAGS_ARM="$FFMPEG_CFG_FLAGS_ARM --disable-small"
        FFMPEG_CFG_FLAGS_ARM="$FFMPEG_CFG_FLAGS_ARM --disable-asm"   ##我先这样了，等官方fix
    ;;
    *)
        FFMPEG_CFG_FLAGS_ARM="$FFMPEG_CFG_FLAGS_ARM --enable-optimizations"
        FFMPEG_CFG_FLAGS_ARM="$FFMPEG_CFG_FLAGS_ARM --enable-debug"
        FFMPEG_CFG_FLAGS_ARM="$FFMPEG_CFG_FLAGS_ARM --enable-small"
    ;;
esac
