### ISSUE TITLE
ndk-build 失败

### ISSUE THREAD

**Issue by cedarnie** [Bilibili/ijkplayer#1444]
./compile-ijk.sh: line 66: AndroidSdk/sdk/ndk-bundle/ndk-build: No such file or directory
/Users/apple/ijkplayer/ijkplayer-android/android

执行脚本compile-ijk.sh all的时候出现以上问题，/Users/apple/ijkplayer/ijkplayer-android/android是存在的。
请问是为什么啊？

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer#before-build

**Comment by cedarnie** [comment]
多谢，ndk版本的问题，版本太新了不行

**Comment by bbcallen** [comment]
If you were using NDKr12, I'd say, it's still in beta.
I don't have any plan to support it until it's released in stable channel.
