### ISSUE TITLE
两个m3u8文件连续播放

### ISSUE THREAD

**Issue by bihackers** [Bilibili/ijkplayer#1446]
最近我项目上需要两个m3u8文件使用ijkplayer连续播放，有什么方法可以做到？

**Comment by bbcallen** [comment]
Create another player, after the first one complete.

**Comment by bihackers** [comment]
目前想达到无缝连接的播放,在什么时机去取下一个m3u8文件比较好？

**Comment by bihackers** [comment]
按照你的方法，我已经做好了，切换延时在1s左右，谢啦！
