### ISSUE TITLE
How to speed up the compilation process when we modify the source c files?

### ISSUE THREAD

**Issue by midoreigh** [Bilibili/ijkplayer#1449]
I am trying to modify the IMediaDataSource.c for my application. Instead of calling Java function in the implementation of IMediaDataSource.java, I am trying to handle the buffer in the c file itself.
1. Is that possible to do that?
2. How can we speed up the compilation process while doing so? (I am using the generated .so files in my application)

I am developing Android application

**Comment by bbcallen** [comment]
1. Of course yes. Actually, you will implement a ffmpeg module. See libavformat/file.c
2. You can try install ccache, and modify build script to use it.

**Comment by midoreigh** [comment]
Thank you bbcallen
