### ISSUE TITLE
ubuntu下编译失败问题

### ISSUE THREAD

**Issue by YasinHe** [Bilibili/ijkplayer#1454]
sdk，ndk配置等都可以，最后一步编译ffmpeg架包时（./compile-ijk.sh all）总是报错：
profiler build: NO
Android NDK: ERROR:/home/heyingxin/ijkplayer-android/android/ijkplayer/ijkplayer-armv5/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /libijkffmpeg.so exists  or that its path is correct   
/home/heyingxin/桌面/android-ndk-r10e/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
/home/heyingxin/ijkplayer-android/android
没有一个能生成，不知道是哪里不对，求教

**Comment by MatrixMuto** [comment]
从这个log看,/home/heyingxin/ijkplayer-android/android/ijkplayer/ijkplayer-armv5/src/main/jni/Android.mk里,定义MY_APP_FFMPEG_OUTPUT_PATH的时候,出了问题.

**Comment by YasinHe** [comment]
@MatrixMuto   我的脚本是根据配置步骤git下来的，这个地方脚本为：
LOCAL_PATH := $(call my-dir)

MY_APP_JNI_ROOT := $(realpath $(LOCAL_PATH))
MY_APP_PRJ_ROOT := $(realpath $(MY_APP_JNI_ROOT)/..)
MY_APP_ANDROID_ROOT := $(realpath $(MY_APP_PRJ_ROOT)/../../../..)

ifeq ($(TARGET_ARCH_ABI),armeabi-v7a)
MY_APP_FFMPEG_OUTPUT_PATH := $(realpath $(MY_APP_ANDROID_ROOT)/contrib/build/ffmpeg-armv7a/output)
MY_APP_FFMPEG_INCLUDE_PATH := $(realpath $(MY_APP_FFMPEG_OUTPUT_PATH)/include)
endif
ifeq ($(TARGET_ARCH_ABI),armeabi)
MY_APP_FFMPEG_OUTPUT_PATH := $(realpath $(MY_APP_ANDROID_ROOT)/contrib/build/ffmpeg-armv5/output)
MY_APP_FFMPEG_INCLUDE_PATH := $(realpath $(MY_APP_FFMPEG_OUTPUT_PATH)/include)
endif
ifeq ($(TARGET_ARCH_ABI),arm64-v8a)
MY_APP_FFMPEG_OUTPUT_PATH := $(realpath $(MY_APP_ANDROID_ROOT)/contrib/build/ffmpeg-arm64/output)
MY_APP_FFMPEG_INCLUDE_PATH := $(realpath $(MY_APP_FFMPEG_OUTPUT_PATH)/include)
endif
ifeq ($(TARGET_ARCH_ABI),x86)
MY_APP_FFMPEG_OUTPUT_PATH := $(realpath $(MY_APP_ANDROID_ROOT)/contrib/build/ffmpeg-x86/output)
MY_APP_FFMPEG_INCLUDE_PATH := $(realpath $(MY_APP_FFMPEG_OUTPUT_PATH)/include)
endif
ifeq ($(TARGET_ARCH_ABI),x86_64)
MY_APP_FFMPEG_OUTPUT_PATH := $(realpath $(MY_APP_ANDROID_ROOT)/contrib/build/ffmpeg-x86_64/output)
MY_APP_FFMPEG_INCLUDE_PATH := $(realpath $(MY_APP_FFMPEG_OUTPUT_PATH)/include)
endif

include $(call all-subdir-makefiles)


这里的MY_APP_FFMPEG_OUTPUT_PATH是需要修改吗？

**Comment by bbcallen** [comment]
Never tested build on windows.

**Comment by bbcallen** [comment]
Very likely caused by broken symbol link.

**Comment by YasinHe** [comment]
@bbcallen @MatrixMuto    感谢大家，我已经成功生成架包了虽然我也不清楚怎么解决的     还有一个问题我编译前已经减少了DEFAULT_LAST_HIGH_WATER_MARK_IN_MS  这个值，减为1*1000   但是还是有6秒的延迟问题，请问要怎么解决？

**Comment by yovenny** [comment]
你倒是说你是怎么解决的呀-_-

**Comment by YasinHe** [comment]
@yovenny 讲道理真的不知道，可能是跟重启有关，因为第二天我啥都没改，编译FfMPEG花了好长时间，一直在抛日志我还以为被我弄坏了。。。。

**Comment by Fozei** [comment]
好尴尬呀, 我也遇到这个错误了,跟你的一模一样, 可是我的还没有解决,有谁能找到真正的原因不?还有有人回复的先编译ffmpeg,怎么先编译它呢?小白呀.
I have the same issue, bug still not solved, and I saw bbcallen saied that we should build ffmpeg first, but I don not know how to build ffmpeg, cyring ~~~~~

**Comment by Fozei** [comment]
我找到原因了， 这个问题的出现是因为按照首页上的步骤配置好环境之后， 没有编译ffmpeg，所以那个叫bbcallen的人提醒我们先编译ffmpeg，具体的方法就是cd到contrib那个目录下  ./compile-ffmpeg.sh all, 然后就开始编译ffmpeg了，这个比较耗时，编译完成后再回退到android目录，编译ijkplayer的so文件就可以了。

**Comment by zinwalin** [comment]
➜ /Users/michael/Development/befovy_ijkplayer/android/contrib git:(master) >./compile-ffmpeg.sh all

![image](https://user-images.githubusercontent.com/5416196/83005287-31fae280-a043-11ea-9931-e5ec716a146b.png)


➜ /Users/michael/Development/befovy_ijkplayer/android git:(master) >sh compile-ijk.sh

![image](https://user-images.githubusercontent.com/5416196/83005370-4e971a80-a043-11ea-8ec7-d24c7ab946b7.png)
