### ISSUE TITLE
加载阿里的CDN直播流需要进行额外的配置吗，无法加载

### ISSUE THREAD

**Issue by ACoderBear** [Bilibili/ijkplayer#1458]
iOS从别的流切换到阿里的CDN流就报 FFP_MSG_ERROR: 0
我用的IJKFFOptions是默认的配置
请问下是需要做额外的配置么？
IJKFFOptions * options = [IJKFFOptions optionsByDefault];

Android的是可以播放出来的，也是基于ijk播放的流，但是我这边iOS就会出错，我们用了鉴权加密，但是我们计算的结果是一样的，可以排除算法问题，请大神务必帮忙一下

这是部分日志
Server bandwidth = 5000000
Client bandwidth = 5000000
New incoming chunk size = 8192
Creating stream...
Sending play command for '6666?auth_key=1465871149-0-0-be5b3e14b8bef4eecaf816fa77631b44'
rtmp://cda.ibumeng.com/mylive/6666?auth_key=1465871149-0-0-be5b3e14b8bef4eecaf816fa77631b44: Input/output error
2016-06-14 10:25:51.279 IJKMediaDemo[3915:1000805] FFP_MSG_ERROR: 0
2016-06-14 10:25:51.280 IJKMediaDemo[3915:1000805] IJKMPMoviePlayBackStateDidChange 2: paused
2016-06-14 10:25:51.280 IJKMediaDemo[3915:1000805] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1

**Comment by bbcallen** [comment]
No idea with such limited information.

**Comment by tanjianping** [comment]
@ACoderBear 你好，这个问题你解决了吗？rtmp://3158.liveplay.myqcloud.com/live/3158_e0780980638211e6a2cba4dcbef5e35a，我在播腾讯的流也遇到了类似问题

**Comment by tanjianping** [comment]
@bbcallen 类似问题：
===== versions =====
FFmpeg       : ff3.1--ijk0.6.0--20160718--001
libavutil    : 55.27.100
libavcodec   : 57.48.101
libavformat  : 57.40.101
libswscale   : 4.1.100
libswresample: 2.1.100
===== options =====
player-opts : video-pictq-size             = 3
player-opts : overlay-format               = fcc-_es2
player-opts : max-fps                      = 30
player-opts : framedrop                    = 0
player-opts : videotoolbox-max-frame-width = 960
player-opts : videotoolbox                 = 0
player-opts : start-on-prepared            = 1
format-opts : ijkinject-opaque             = 140279987343216
format-opts : ijkapplication               = 140279987346832
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : safe                         = 0
format-opts : reconnect                    = 1
===================
ijkmp_prepare_async()=0
remove 'timeout' option for rtmp.
No default whitelist set
No default whitelist set
2016-08-16 17:20:10.607 IShowDemo[83451:3364922] invalidateRenderBuffer
2016-08-16 17:20:10.607 IShowDemo[83451:3367834] IJKSDLGLView: setupDisplay not ready
2016-08-16 17:20:10.612 IShowDemo[83451:3364922] invalidateRenderBuffer
2016-08-16 17:20:10.612 IShowDemo[83451:3367834] IJKSDLGLView: setupDisplay not ready
aout_close_audio()
Statistics: 224133 bytes read, 0 seeks
Deleting stream...
wait for video_refresh_tid
SDL_Overlay(ffmpeg): overlay_free_l(0x7f957ab81780)
SDL_Overlay(ffmpeg): overlay_free_l(0x7f957aa6f600)
SDL_Overlay(ffmpeg): overlay_free_l(0x7f9572a14430)
ijkmp_shutdown_l()=void
ijkmp_dec_ref(): ref=0
ijkmp_shutdown_l()
ijkmp_shutdown_l()=void
aout_close_audio()
Handshaking...
Type answer 3
Server version 13.14.10.13
Proto = rtmp, path = /live/3158_e0780980638211e6a2cba4dcbef5e35a, app = live, fname = 3158_e0780980638211e6a2cba4dcbef5e35a
Server bandwidth = 5000000
Client bandwidth = 5000000
New incoming chunk size = 4096
Creating stream...
Sending play command for '3158_e0780980638211e6a2cba4dcbef5e35a'
Deleting stream...
rtmp://3158.liveplay.myqcloud.com/live/3158_e0780980638211e6a2cba4dcbef5e35a: Input/output error
2016-08-16 17:20:21.672 IShowDemo[83451:3364922] FFP_MSG_ERROR: 0
2016-08-16 17:20:21.672 IShowDemo[83451:3364922] IJKMPMoviePlayBackStateDidChange 2: paused
2016-08-16 17:20:21.672 IShowDemo[83451:3364922] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1

**Comment by tanjianping** [comment]
@bbcallen 怎么解决啊？

**Comment by ctiao** [comment]
问服务端
