### ISSUE TITLE
ios seek的问题

### ISSUE THREAD

**Issue by iqluoji** [Bilibili/ijkplayer#1460]
[self.player shutdown];
    [self.player.view removeFromSuperview];
   然后重新init
   再设置 self.player.currentPlaybackTime
   不改变 还是从0开始

**Comment by iqluoji** [comment]
就是ios如何seek呢

**Comment by bbcallen** [comment]
self.player.currentPlaybackTime = <What your want>

**Comment by iqluoji** [comment]
it does't work

**Comment by bbcallen** [comment]
Nothing more I can do.
