### ISSUE TITLE
ijk硬件编码打开

### ISSUE THREAD

**Issue by vitanie** [Bilibili/ijkplayer#1461]
把videotoolbox  设置为yes就是打开硬件编码吗？
IJKFFOptions *options = [IJKFFOptions optionsByDefault]; //使用默认配置
    
    //改进
    //[options setPlayerOptionIntValue:0 forKey:@"no-time-adjust"];
    //[options setPlayerOptionIntValue:1 forKey:@"audio_disable"];
    //[options setPlayerOptionIntValue:1 forKey:@"infbuf"];
    //[options setPlayerOptionIntValue:0 forKey:@"framedrop"];
    
    //videotoolbox 配置（硬件解码）
    [options setPlayerOptionIntValue:1  forKey:@"videotoolbox"];

**Comment by bbcallen** [comment]
Yes

**Comment by vitanie** [comment]
在iPhone 6plus上面设置不成功  其他机型可以，这是为何？

**Comment by vitanie** [comment]
感觉videotoolbox的解码能力比avcodec更快 能一定程度上减少播放延迟

**Comment by bbcallen** [comment]
Dunno without more information.

**Comment by sundaoran** [comment]
android 如何打开硬件解码
