### ISSUE TITLE
播放音乐时，锁屏时声音一卡一卡的

### ISSUE THREAD

**Issue by lovelycheep** [Bilibili/ijkplayer#1462]
android平台下用ijk-demo播放声音时，锁屏或者进行其他操作时，声音一卡一卡的，请问这是什么原因导致的?

**Comment by lovelycheep** [comment]
help，help， anyone can help me？

**Comment by lovelycheep** [comment]
@bbcallen 您好，现在没有找到具体的原因；在一些低端机上会出现，例如在OPPO R830手机锁屏时，就会出现短暂的多次卡顿现象；
我做过如下分析：
1、低端机内存不足时，播放会出现卡顿；但是其他播放器不会出现，而且某些软件使用的早期ijk版本貌似没问题(ijkplayer.so编译后大小是110KB，sdl编译后大小是142KB），我觉得很可能是k0.3.1版本，但是demo编译不了，studio报Unexpected end of file from server错误，所以没法验证，不知道是不是我哪里配置有问题？
2、能不能是在sdl_audio_callback中做解码导致的？低端机对回调函数做了某些优化导致的，可不可以把音频解码拿出来，callback只负责取数据，这样效率会不会更高一些？

不知道我一上的分析有没有道理，请指教，谢谢！

**Comment by bbcallen** [comment]
1. Nothing I can tell, without any log.
2. Audio is decoded in sdl_audio_callback from the very beginning. It's very unlikely being caused by this.

**Comment by lovelycheep** [comment]
@bbcallen 您好:
       找到原因了：aout_thread_n线程中每次回调的copy_size由原来的256改到SDL_Android_AudioTrack_get_min_buffer_size返回的buffer_size大小后问题基本就解决了；
      我怀疑是不是该线程调度太频繁了，比较浪费资源导致的？
     但是还是有些疑惑，不太清楚您当时的设计理念，为什么这个地方每次读取这么小的值呀？

**Comment by bbcallen** [comment]
Can't reproduce here.
Larger buffer means more latency in audio output.

**Comment by lovelycheep** [comment]
ok，thank you very much！
