### ISSUE TITLE
How can I switch URL while playing?

### ISSUE THREAD

**Issue by Gagster** [Bilibili/ijkplayer#1463]
Hi,
I've searched the issues (maybe) all about switch URL while playing.
it seems that we have to kill the current player and create a new one.
well, the problem is how to kill that player and how to create a new one with Object-C?
will u show me some codes, that will be greatful help. 
: P
Thx

**Comment by Gagster** [comment]
I've tried using the following code to kill current player, but it was still playing... AWKWARD
`self.player = nil; ` // "self"  is a viewController    "_player" is a  IJKFFMoviePlayerController

**Comment by Gagster** [comment]
```
 [IJKMediaModule sharedModule].appIdleTimerDisabled = YES;
    [IJKFFMoviePlayerController checkIfFFmpegVersionMatch:YES];
    IJKFFOptions * options = [IJKFFOptions optionsByDefault];
    [options setFormatOptionValue:@"ijktcphook" forKey:@"http-tcp-hook"];
    NSURL *theMovieURL = [NSURL URLWithString:urlStr];
    self.player = [[IJKFFMoviePlayerController alloc] initWithContentURL:theMovieURL withOptions:options];
    self.player.scalingMode = IJKMPMovieScalingModeAspectFit;
    self.player.shouldAutoplay = YES;
    [self.view addSubview:_player.view];
    [self.player prepareToPlay];
```
solved : ）

**Comment by bbcallen** [comment]
Remember to call [mp shutdown] and remove previous player.view from parent view.

**Comment by Gagster** [comment]
Thx~ : )
