### ISSUE TITLE
关闭播放器之后立刻再创建可能会导致crash

### ISSUE THREAD

**Issue by dourgulf** [Bilibili/ijkplayer#1469]
创建的代码如下:
- (void)setupPlayerWithURL:(NSURL *)URL {
#ifdef DEBUG
    [IJKFFMoviePlayerController setLogReport:YES];
    [IJKFFMoviePlayerController setLogLevel:k_IJK_LOG_DEBUG];
#else
    [IJKFFMoviePlayerController setLogReport:NO];
    [IJKFFMoviePlayerController setLogLevel:k_IJK_LOG_SILENT];
#endif
    IJKFFOptions *options = [IJKFFOptions optionsByDefault];
    self.player = [[IJKFFMoviePlayerController alloc] initWithContentURL:URL withOptions:options];
    [JCDeallocMonitor addMonitorToObj:self.player];
    [self.player setPauseInBackground:NO];
    self.player.scalingMode = IJKMPMovieScalingModeAspectFit;
    [self installMovieNotificationObservers];
}
关闭播放器只调用shutdown
偶尔会在这里发生crash:
static int ijkff_inject_callback(void *opaque, int message, void *data, size_t data_size)
{
    NSLog(@"IJKFFMoviePlayerController opaque: %p", opaque);

    IJKFFMoviePlayerController *mpc = (__bridge IJKFFMoviePlayerController*)opaque;

对象的创建和销毁日志如下:
// 这个日志是在setupPlayerWithURL方法打印的self指针
IJKFFMoviePlayerController: 0x1502a3e80
// 这个日志是在ijkff_inject_callback(方法打印的opaque指针
IJKFFMoviePlayerController opaque: 0x1502a3e80
IJKFFMoviePlayerController: 0x1502e5400
<IJKFFMoviePlayerController: 0x1502a3e80> has been deallocated
IJKFFMoviePlayerController opaque: 0x1502e5400
IJKFFMoviePlayerController opaque: 0x1502e5400
// crash发生在这里, 回调发生在一个已经deallocated的对象<0x1502a3e80>上
IJKFFMoviePlayerController opaque: 0x1502a3e80

猜想的原因应该是IJKFFMoviePlayerController对象已经deallocated了, 但是IjkMediaPlayer的线程没有完全结束, 因为shutdown是异步的过程.

解决办法还在探索.....

**Comment by LSLdalong** [comment]
您找到解决办法了吗,我也遇到了相同的问题,连续点击,在退出的时候会crash到shutdown中

**Comment by dourgulf** [comment]
正确是释放顺序是:
player.view removeFromSuperView
player shutdown
player = nil
最关键是最后一步player=nil; 之前的crash其实是因为shutdown是一个异步的过程player对象并没有立刻变成nil.
