### ISSUE TITLE
网络环境较差时，怎么调整参数使得播放器一直缓冲而不调用onError

### ISSUE THREAD

**Issue by yuxfzju** [Bilibili/ijkplayer#147]
#define DEFAULT_HIGH_WATER_MARK_IN_BYTES        (256 * 1024)

/*
 * START: buffering after prepared/seeked
 * NEXT:  buffering for the second time after START
 * MAX:   ...
 */

#define DEFAULT_START_HIGH_WATER_MARK_IN_MS     (100)
#define DEFAULT_NEXT_HIGH_WATER_MARK_IN_MS      (1 * 1000)
#define DEFAULT_MAX_HIGH_WATER_MARK_IN_MS       (5 * 1000)

1、能否指点下这几个参数的含义，我没法完全理解
2、减小第一次播放前的缓冲时间，应该怎么调整参数
3、在网络环境较差时，将会发生error的调用，能否通过调整参数，使得播放器一直保持缓冲（或者缓冲较长时间），直到网络正常。这应该怎么调整参数。是 DEFAULT_MAX_HIGH_WATER_MARK_IN_MS 还是设置timeout

问题较多， 万分感谢

**Comment by bbcallen** [comment]
1.
DEFAULT_START_HIGH_WATER_MARK_IN_MS 越小, 拖动进度后越快出画面
DEFAULT_NEXT_HIGH_WATER_MARK_IN_MS, 越小, 停下来缓冲的时间越短, 但是网速不好的时候, 缓冲次数就会很多
DEFAULT_MAX_HIGH_WATER_MARK_IN_MS, 同上

2. 见1
3. error 了就是真的出错了，和缓冲时间无关，这个时候从上层重试比较方便。

**Comment by yuxfzju** [comment]
感谢您的回答，
正在学习代码，碰到问题。播放器seek到缓冲条范围内，仍然需要重新加载缓冲，能否做到如系统的videoview一样，能够在已缓冲区域任意播放拖动
能否简单的说下改进的思路，应该从哪方面入手？

**Comment by bbcallen** [comment]
ffmpeg custom io
