### ISSUE TITLE
android:cache latency is too high

### ISSUE THREAD

**Issue by YasinHe** [Bilibili/ijkplayer#1475]
Hi:
I use the ijkplayer but I found a-cache is too high and gradually increase.And v-cache shows zero msec,but actually has the same time delay with a-cache.
So what should I do to change them I need a low delay live :-(

**Comment by bbcallen** [comment]
Both 0-msec and 0-bytes, means there is no video data for player to decode, and nothing you can do.
Better ask your server developer to align audio packet and video packet.

**Comment by YasinHe** [comment]
I don't think so.@bbcallen  In fact, there is no question of my video sources, but every time open video streams need to wait for a few seconds, I found that wait for a few seconds is the time delay, I want to know do you have any plan to realize real-time decoding and displaying    thanks~

**Comment by bbcallen** [comment]
No matter it is or it isn't the question of your video sources, from your description, that's all I can tell.

And I have no idea about so called "real-time decoding and displaying", at all.

**Comment by YasinHe** [comment]
@bbcallen ok thanks~

**Comment by dourgulf** [comment]
@bbcallen 我也有楼主的类似情况, 打开shouldShowHudView, 看到的画面:
v-cache    0 msec 0.26MB, 51 packets
a-cache     1.86 sec, 30KB, 80 packets
视频和音频都是能正常播放, 没有卡顿.
