### ISSUE TITLE
Live content streaming

### ISSUE THREAD

**Issue by nrmmota** [Bilibili/ijkplayer#148]
Will a live udp stream work, instead of the static file?

Here you specify a static file.
<code>mVideoPath = "/sdcard/download/720.flv";</code>

BTW,
Android Studio tutorial would be perfect. I haven't had the time to browse your source completely or even try it out, but it seems you've moved your stuff to AS already.

**Comment by bbcallen** [comment]
Live stream url works, too, like http://... rtmp://...
Don't forget to add network permission in your AndroidManifest.xml

For udp, you have to modify build config to enable it
https://github.com/bbcallen/ijkplayer/blob/master/config/module-lite.sh

For myself, I'm still using Eclipse for C code auto complete.

**Comment by mesropd** [comment]
It works, but have a huge delay, how to avoid a delay?

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
