### ISSUE TITLE
transparency video

### ISSUE THREAD

**Issue by hunternutkun** [Bilibili/ijkplayer#1483]
How can I setting player for playing .mov file that contain alpha channel.
Now I can play a video but it doesn't show transparency background.

**Comment by bbcallen** [comment]
I don't think ijkplayer support  transparency background.

**Comment by TeeMoYan** [comment]
> How can I setting player for playing .mov file that contain alpha channel.
> Now I can play a video but it doesn't show transparency background.

Can you play transparent video?
