### ISSUE TITLE
编译出来的文件太大，请问下怎样对ffmpeg进行瘦身，只需要基础的ffmpeg

### ISSUE THREAD

**Issue by dhc1256436519** [Bilibili/ijkplayer#1485]
编译出来的文件太大，请问下怎样对ffmpeg进行瘦身，只需要基础的ffmpeg

**Comment by losywee** [comment]
修改下 ffmpeg 的编译参数就行了

**Comment by dhc1256436519** [comment]
您知道，在这个工程里面哪个文件修改编译参数呢？是那个config文件夹里么？

**Comment by dhc1256436519** [comment]
是在config文件夹下那四个编译脚本文件里修改么？

**Comment by bbcallen** [comment]
Duplicated with #1480
Please don't open new issue, if there is same issue created by same person
