### ISSUE TITLE
how can use setLooping() ?

### ISSUE THREAD

**Issue by fingerup** [Bilibili/ijkplayer#149]
Your player is VERY high performer, big thanks.

What is the equivalent  [setLooping()](http://developer.android.com/reference/android/media/MediaPlayer.html#setLooping(boolean)) method of [MediaPlayer](http://developer.android.com/reference/android/media/MediaPlayer.html) for your IjkMediaPlayer ?

thanks

**Comment by fingerup** [comment]
I do that : 

```java
mp.setOnCompletionListener(new IMediaPlayer.OnCompletionListener()
{
	@Override
	public void onCompletion(IMediaPlayer mp)
	{
		mp.seekTo(0);
		mp.start();
	}
});
```

but my video freeze for 2sec before restart !

thanks

**Comment by bbcallen** [comment]
There is a loop option in original ffplay.c

**Comment by fingerup** [comment]
How can use modify _ffplay.c_ and change loop parameter ?
