### ISSUE TITLE
请问iOS平台下如何根据MP4 video stream中的rotate属性对视频进行旋转播放呢？

### ISSUE THREAD

**Issue by wtiandong** [Bilibili/ijkplayer#1494]
大家好，
请问iOS平台下如何根据MP4 video stream中的rotate属性对视频进行旋转播放呢？系统录制出的mov等都是有个rotate属性。请问怎么根据这个rotate属性让ijk player进行自动旋转播放呢？

非常感谢！

**Comment by bbcallen** [comment]
Rotate player.view as how you rotate normal UIView.

**Comment by dourgulf** [comment]
它的意思是需要知道原始文件的旋转属性才好rorate player.view. 有些起码的视频文件录出来的视频数据保存的时候是水平颠倒了, 然后设置一个rorate属性在文件里头, 播放器播放的时候要读取这个值才能正确还原视频数据的.

**Comment by wtiandong** [comment]
那怎么从ijkplayercontroller那块拿到这个属性呢？我看到有个ffp_get_video_rotate_degrees方法，在ff_ffplay.c里边，但是用这个会破坏封装。

**Comment by bbcallen** [comment]
The point of open source, is that you can modify it freely.

**Comment by wtiandong** [comment]
OK, Thank you very much @bbcallen
