### ISSUE TITLE
How to import this library in Android Studio ?

### ISSUE THREAD

**Issue by fingerup** [Bilibili/ijkplayer#150]
I'm on Mac (no cygwin), i have run "compile-ffmpeg.sh" and "compile-ijk.sh" ,everything went well.
In Android Studio when i run Gradle (Sync Project with Gradle Files), everything is ok.
But i have this error when i start my application on device.

```
java.lang.UnsatisfiedLinkError: Couldn't load ijkffmpeg from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/myapp.test_videomosaic-2.apk"],nativeLibraryDirectories=[/data/app-lib/myapp.test_videomosaic-2, /vendor/lib, /system/lib]]]: findLibrary returned null
	at java.lang.Runtime.loadLibrary(Runtime.java:358)
	at java.lang.System.loadLibrary(System.java:526)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:98)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:106)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:147)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:143)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:135)
	at myapp.test_videomosaic.MainActivity$PlayRunnable$1.run(MainActivity.java:102)
	at java.lang.Thread.run(Thread.java:841)
01 Force finishing activity myapp.test_videomosaic/.MainActivity
```
---
I follow [this tuto][1] for import ijkplayer in Android Studio :
* In project root directory create new folder: _libs_
* I copy _ijkmediaplayer_ folder to _libs_
* Add to settings.gradle : 
```
include ':app', ':ijkmediaplayer'
project(':ijkmediaplayer').projectDir = new File('libs/ijkmediaplayer')
```
* Add to app/build.gradle : 
```
compile project(":ijkmediaplayer")
```
---

Can you help me ?

[1]: http://stackoverflow.com/questions/16588064/how-do-i-add-a-library-project-to-the-android-studio

**Comment by fingerup** [comment]
One more thing : I have found symlink in _ijkmediaplayer/jni_ and _ijkmediaplayer/jni/ffmpeg_, i replace with folder.

**Comment by bbcallen** [comment]
Not familiar with Android Studio, yet

**Comment by fingerup** [comment]
That so bad.. Do you have an idea of where the problem is ? Can i help you ?

**Comment by bbcallen** [comment]
Android Studio is lack of NDK support in default setup, so I have no plan for it.

BTW: Pull request is welcome.

**Comment by fingerup** [comment]
Sorry, I'm not C/C++ developer, i never really used NDK/jni.
But I feel that this is possible use NDK with Android Studio : 
https://software.intel.com/en-us/videos/using-the-ndk-with-android-studio

Thank you, and good luck !

**Comment by thuantran** [comment]
@fingerup I managed to compile 0.2.2 then using this guide http://www.shaneenishry.com/blog/2014/08/17/ndk-with-android-studio/ to change the project directory structure and it works for me after some gradle file modifications.

As said you should be able to use ndk with Android Studio and with the previous guide I mentioned, it should be theoretically possible to make this library to compatible with both eclipse and Android Studio. Unfortunately I'm not familiar with git and ndk enough to do all this yet. I will try to do it once I have more time.

**Comment by stuckless** [comment]
To allow the **ijkmediademo** project to use the native libraries from **ijkmediaplayer**, then edit the `build.gradle` file in **ijkmediaplayer** and add `jniLibs.srcDirs = ['libs']` to the `sourceSets`... it should now look like this...
```gradle
   sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }
```

`jniLibs` is how you tell gradle/androidstudio where to find the native libraries.  Once they are defined for a sub-project they will be copied into dependent projects.

I just compiled and tested this, and after putting a `test.mp4` file in my downloads directory on the sd card, the demo worked fine.  

Awesome project!!!

**Comment by bbcallen** [comment]
Android Studio has been supprted: fb1b24f7dfb475e0a3546572cf88664d6ec5a6b5
