### ISSUE TITLE
同时创建多个播放器需要注意哪些事情?

### ISSUE THREAD

**Issue by dourgulf** [Bilibili/ijkplayer#1500]
@bbcallen 对于同时创建多个播放器的问题, 看到您在 #1468 上的答复说"Yes, in theory, but never tried."?
是否可以展开说一下您对同时创建多个播放器有什么担心的地方吗?

我简单的测试了一下同时创建两个播放器, addSubview到同一个父View上是可以正常播放和结束的. 我能想到需要小心的地方可能是那些Notification, 以及播放器是否存在的一些全局状态.

**Comment by bbcallen** [comment]
"Never tried" means, I have not tested it, and I don't guarantee that it could work in future.
You should take care of various system resources, e.g. hardware decoder, audio session, gles context, wake lock, volume control.

For player itself, it's OK for multiple instance.

**Comment by dourgulf** [comment]
哈哈, 原来是英文水平没理解清楚, 你的意思是"没尝试过"不是"不要尝试":)
谢谢你的提醒:(注意系统资源, 硬件解码器, 音频会话, OpenGLES的context冲突, 音量控制等等)
其中, wake lock是怎么理解, 还望指教.

**Comment by bbcallen** [comment]
"wake lock" means keep device awake.

**Comment by dourgulf** [comment]
ok, I got it, thx a lot!

**Comment by dourgulf** [comment]
@bbcallen 遇到了audio session的问题了, 同时两个播放器的情况下, 声音非常的小.

**Comment by dourgulf** [comment]
通过 [setCategory:AVAudioSessionCategoryMultiRoute withOptions:AVAudioSessionCategoryOptionMixWithOther]解决了.
