### ISSUE TITLE
直播时有画面没声音

### ISSUE THREAD

**Issue by laonanle** [Bilibili/ijkplayer#1503]
我只是简单实现了一下，直播时有视频画面但没有声音下面时打印的log：
===== custom modules begin =====
register protocol: async
register protocol: ijkhttphook
register protocol: ijkinject
register protocol: ijklongurl
register protocol: ijksegment
register protocol: ijktcphook
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff3.0--ijk0.5.0--dev0.4.5--rc11
ijkmp_set_inject_opaque(0x13c7068a0)
ijkmp_set_inject_opaque()=void
ijkmp_ios_set_view(glView=0x13c70bbd0)
ijkmp_ios_set_view(glView=0x13c70bbd0)=void
2016-06-20 15:11:14.008 ijkplayerNOSound[20302:7379406] invalidateRenderBuffer
ijkmp_set_data_source(url="rtmp://video2.xingbo.tv/xiu/1011432")
ijkmp_set_data_source(url="rtmp://video2.xingbo.tv/xiu/1011432")=0
ijkmp_prepare_async()
ijkmp_prepare_async()=0
2016-06-20 15:11:14.034 ijkplayerNOSound[20302:7379406] IJKSDLGLView:applicationDidBecomeActive: 0
2016-06-20 15:11:14.035 ijkplayerNOSound[20302:7379406] IJKFFMoviePlayerController:applicationDidBecomeActive: 0
2016-06-20 15:11:14.038 ijkplayerNOSound[20302:7379406] invalidateRenderBuffer
2016-06-20 15:11:14.072 ijkplayerNOSound[20302:7379406] invalidateRenderBuffer
2016-06-20 15:11:14.084 ijkplayerNOSound[20302:7379437] OK setup GL
2016-06-20 15:11:14.088 ijkplayerNOSound[20302:7379437] IJKSDLGLView: setupDisplay not ready
2016-06-20 15:11:14.095 ijkplayerNOSound[20302:7379437] IJKSDLGLView: setupDisplay not ready
vtb fail!!! switch to ffmpeg decode!!!! 
2016-06-20 15:11:24.218 ijkplayerNOSound[20302:7379406] FFP_MSG_VIDEO_DECODER_OPEN: false
2016-06-20 15:11:24.219 ijkplayerNOSound[20302:7379406] FFP_MSG_VIDEO_SIZE_CHANGED: 700, 394
2016-06-20 15:11:24.219 ijkplayerNOSound[20302:7379406] FFP_MSG_SAR_CHANGED: 1, 1
ijkmp_get_msg: FFP_MSG_PREPARED
2016-06-20 15:11:24.221 ijkplayerNOSound[20302:7379406] FFP_MSG_PREPARED:
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
2016-06-20 15:11:24.221 ijkplayerNOSound[20302:7379406] fps in meta 15.166667
2016-06-20 15:11:24.221 ijkplayerNOSound[20302:7379406] mediaIsPreparedToPlayDidChange
2016-06-20 15:11:24.222 ijkplayerNOSound[20302:7379406] loadStateDidChange: IJKMPMovieLoadStatePlaythroughOK: 3
2016-06-20 15:11:24.222 ijkplayerNOSound[20302:7379406] IJKMPMoviePlayBackStateDidChange 1: playing
SDL_VoutFFmpeg_CreateOverlay(w=700, h=394, fmt=I420(0x30323449, dp=0x13c706200)
Video: first frame decoded
2016-06-20 15:11:24.278 ijkplayerNOSound[20302:7379406] FFP_MSG_VIDEO_SIZE_CHANGED: 700, 394
[GLES2] Version = OpenGL ES 2.0 Apple A8 GPU - 77.14
[GLES2] Vendor = Apple Inc.
[GLES2] Renderer = Apple A8 GPU
[GLES2] Extensions = GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_vertex_array_object GL_EXT_blend_minmax GL_EXT_color_buffer_half_float GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_draw_instanced GL_EXT_instanced_arrays GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_pvrtc_sRGB GL_EXT_read_format_bgra GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_texture_lod GL_EXT_shadow_samplers GL_EXT_sRGB GL_EXT_texture_filter_anisotropic GL_EXT_texture_rg GL_EXT_texture_storage GL_APPLE_clip_distance GL_APPLE_color_buffer_packed_float GL_APPLE_copy_texture_levels GL_APPLE_framebuffer_multisample GL_APPLE_rgb_422 GL_APPLE_sync GL_APPLE_texture_format_BGRA8888 GL_APPLE_texture_max_level GL_APPLE_texture_packed_float GL_IMG_read_format GL_IMG_texture_compression_pvrtc 
create render yuv420p
2016-06-20 15:11:24.287 ijkplayerNOSound[20302:7379406] FFP_MSG_VIDEO_SIZE_CHANGED: 700, 394
use render yuv420p
2016-06-20 15:11:24.346 ijkplayerNOSound[20302:7379512] IJKSDLGLView: renderbufferStorage fromDrawable
IJK_GLES2_Renderer_TexCoords_cropRightSDL_VoutFFmpeg_CreateOverlay(w=700, h=394, fmt=I420(0x30323449, dp=0x13c706200)
SDL_VoutFFmpeg_CreateOverlay(w=700, h=394, fmt=I420(0x30323449, dp=0x13c706200)
2016-06-20 15:11:24.398 ijkplayerNOSound[20302:7379406] FFP_MSG_VIDEO_RENDERING_START:
2016-06-20 15:11:24.399 ijkplayerNOSound[20302:7379406] FFP_MSG_VIDEO_SIZE_CHANGED: 700, 394
请问这是什么原因，thank you。

**Comment by laonanle** [comment]
并不是所有的都没声音，用我们公司的直播的url的时候就没有声音，直有画面，这是啥原因呢。

**Comment by jyfree** [comment]
你们直播的音频是用什么编码的？

**Comment by laonanle** [comment]
我们这的音频格式是用flash直推的neyllow格式，多谢

**Comment by jyfree** [comment]
你要把neyllow打开，默认是关闭的。
./configure --list-decoders

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-decoders"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=aac"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=aac_latm"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=flv"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=h263"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=h263i"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=h263p"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=h264"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mp3*"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=vp6"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=vp6a"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=vp6f"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=nellymoser"

**Comment by laonanle** [comment]
在哪里打开，能具体点吗？

**Comment by jyfree** [comment]
但是我发现魅族手机系统版本5.1的，打开了也没有声音

**Comment by jyfree** [comment]
ijkplayer-android/config/module-lite.sh  文件

**Comment by laonanle** [comment]
我这是ios的

**Comment by jyfree** [comment]
一样的

**Comment by jyfree** [comment]
Before Build 时用到的

**Comment by laonanle** [comment]
我打开那个文件发现是打开着的啊，没有屏蔽啊，下面是我复制的那里面的代码，第三个＃号开始的那里：

# Individual component options:
# export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-everything"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-encoders"

# ./configure --list-decoders
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-decoders"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=aac"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=aac_latm"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=flv"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=h263"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=h263i"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=h263p"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=h264"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mp3*"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=vp6"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=vp6a"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=vp6f"

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-hwaccels"

# ./configure --list-muxers
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-muxers"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-muxer=mp4"

**Comment by laonanle** [comment]
大神，你说的打开是什么意思，蒙了啊，我打开那个文件发现你说的那段代码没被注释掉啊

**Comment by jyfree** [comment]
意思就是加上这句
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=nellymoser"
重新编译so

如果还不行的话应该就是手机系统版本不支持了

**Comment by laonanle** [comment]
噢好的，多谢

**Comment by jyfree** [comment]
建议你推流不要用flash，有些手机不一定支持nellymoser解码

**Comment by laonanle** [comment]
嗯，解决了，多谢，新版本的话推流音频格式就不用这个了

**Comment by congni** [comment]
怎么解决的？为什么我改了文件重新编译了一下，还是不行

**Comment by xiongjie1207** [comment]
按照这个重新编译就好了，目前还有个问题，就是flash推流，移动端拉流的时候，延迟很大，这个怎么解决？

**Comment by wkowko** [comment]
你好你是怎样解决的 可不可以说说QQ啊  多谢了 或者我的QQ 2277840910    多谢了
