### ISSUE TITLE
ffmpeg yuv data to rgb or jpeg

### ISSUE THREAD

**Issue by flynn89** [Bilibili/ijkplayer#1506]
How can i get yuv data， and change to rgb or jpeg ？
thx

**Comment by flynn89** [comment]
我看到IJKSDLGLView的display方法会持续调用，我想在display方法中获取视频数据，然后转成图片格式或者rgb格式，但是不知道怎么转换，请求你的帮助。

**Comment by bbcallen** [comment]
Use libyuv.

**Comment by flynn89** [comment]
ijk_image_convert 是安卓用的，iOS没法用的。
我想在iOS上用。

**Comment by bbcallen** [comment]
Or swscale, but it's slower.

**Comment by liulvhong** [comment]
调用播放器的    IJKSDLGLView *_glView;
    [_glView snapshot];
