### ISSUE TITLE
有没有EClipse版本的啊

### ISSUE THREAD

**Issue by wincentytg** [Bilibili/ijkplayer#1508]
有没有EClipse版本的啊  我用eclipse 怎么编译64位so文件  ，版主为啥 不把so文件编译好了 放出来 给我们参考使用呢 ，谢啦，

**Comment by wincentytg** [comment]
我现在有eclipse版本的代码 但是缺少64位的so文件 编译了给的C没编译出来  搞了很久 啊 要是能放出来编译好的 再感谢不过了

**Comment by bbcallen** [comment]
No.

**Comment by wincentytg** [comment]
为啥不给64位的so文件啊？

**Comment by bbcallen** [comment]
Why should I?

**Comment by wincentytg** [comment]
这不是 遇到问题了嘛  自己能搞出来 就不麻烦大神了  谢啦 拜托
