### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by easytome** [Bilibili/ijkplayer#1515]
./compile-ffmpeg.sh all 这条命令编译的时候提示
ijkplayer-master/android/contrib/../../config/module.sh:行1: module-lite.sh: 未找到命令

**Comment by java-Xs** [comment]
我也遇到了同样的问题了，请问您是怎么解决的？

**Comment by a785436663** [comment]
怎么解决的。。没解决

**Comment by msn465780** [comment]
搞了几天了都编不过，做戏能做全套吗？

**Comment by baishuai** [comment]
@easytome  是不是没有执行init-config.sh
