### ISSUE TITLE
Can this player play mms:// WMA streams on Android?

### ISSUE THREAD

**Issue by BaskarKS** [Bilibili/ijkplayer#1520]
I enabled the below protocols to play a mms URL 
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=mmsh"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=mmst"

tried to play "mms://alive.rbc.cn/fm1039" but I get error like below:
mms://alive.rbc.cn/fm1039: Protocol not found.

I tried playing the same URL with tag "mmsh / mmst" (i.e. "mmsh://alive.rbc.cn/fm1039"), below log error message i got.

06-22 13:18:53.499: E/IJKMEDIA(7123): Read data packet header failed!
06-22 13:18:53.499: E/IJKMEDIA(7123): Recv other type packet -5
06-22 13:18:53.521: E/IJKMEDIA(7123): mmsh://alive.rbc.cn/fm1039: Invalid data found when processing input

I tried searching help to enable mms in all README, i couldnt find steps to enable mms. Request to please post your valuable comments.

**Comment by bbcallen** [comment]
Duplicated #1327
