### ISSUE TITLE
ijkplayer 支持先把视频完全载入好再播放吗？(iOS)

### ISSUE THREAD

**Issue by zhangchioulin** [Bilibili/ijkplayer#1528]
有两个问题：
1. ijkplayer 支持先把视频完全载入好再播放吗？
2. ijkplayer 模拟器上打开视频会有噪音，貌似别的也会。
3. 我准备尝试为 ijkplayer 加入缓存的功能，该从哪方面入手？

**Comment by bbcallen** [comment]
1. You can download it completely, and play local file.
2. I don't expect it works on simulator.
3. libavformat/cache.c

**Comment by zhangchioulin** [comment]
Thanks a lot

**Comment by snowimba** [comment]
完全载入你不怕内存爆掉么
而且这个封装的ffmpeg没有抛出播放NSData或者本地文件的接口貌似
还有缓存的数据也拿不到
我本来也想写缓存功能，不过八成要自己去封装ffmpeg了
还有如果你有什么进展大家一起讨论讨论哈 -。-

**Comment by zhangchioulin** [comment]
我想过内存方面的事情了。感觉都往内存塞不靠谱。打算先下载完，然后播放哒。方法可能比较土。。。但是应该比较好实现。

**Comment by snowimba** [comment]
其实内存这方面我已经找到一个有用的解决办法了，就是要内存和磁盘流式联动，就像云端和内存流式联动一样，我们可以把磁盘也加入这个流，3个存储位置流式联动，这样内存不会爆，而且可以缓存本地，而且不需要等待全部下载完成才播放，就是IO操作可能会比较频繁，还有就是需要很多地方的配合，还有就是需要有播放NSData的接口，我打算直接用data形式播放：云端下载-》内存播放-》磁盘存储-》。。。全程是都是数据在流动，完美解决各种问题。

**Comment by dourgulf** [comment]
ijkplayer不是已经有缓存的吗?

**Comment by zhangchioulin** [comment]
请教是哪一个方法？

**Comment by dourgulf** [comment]
ijkplayer自身的运行逻辑就是有缓存的, 只是没有写入磁盘

**Comment by zhangchioulin** [comment]
可是我联系播放一个简短的视频，视频播放开始每次都会请求一次网络

**Comment by snowimba** [comment]
我知道有缓存，没缓存怎么播放，他只是在内存里面开了一小块缓存起来，然后播放，然后丢弃，我们现在要做真正的缓存，就是在内存开一小块播放，然后不丢弃，存磁盘，这里就是真正的本地缓存了，以后就是直接离线读取这一段数据

**Comment by CarGuo** [comment]
@snowimba 请问您实现了离线缓存的机制了吗？

**Comment by ijustkeepmoving** [comment]
@snowimba 请问如何实现你说的这个功能呢
