### ISSUE TITLE
Ubuntu下编译ijkplayer的命令:./compile-ijk.sh all出现profiler build: NO有没有影响，还有在Ubuntu下编译ijkplayer只生成一个.so文件怎么办？

### ISSUE THREAD

**Issue by 15301089517** [Bilibili/ijkplayer#1530]
Ubuntu下编译ijkplayer的命令:./compile-ijk.sh all出现profiler build: NO [armeabi-v7a] Prebuilt: 有没有影响ijkplayer的编译，还有在Ubuntu下编译ijkplayer只生成一个.so文件怎么办？

**Comment by bbcallen** [comment]
1. No
2. Need more information.

**Comment by 15301089517** [comment]
第二个问题好像解决了，但不知道咋解决的，谢谢了。

**Comment by liaosiyang** [comment]
第二个问题怎么解决的啊？我也遇到了。
