### ISSUE TITLE
android版的ijkplayer支不支持视频挂起功能

### ISSUE THREAD

**Issue by 15301089517** [Bilibili/ijkplayer#1531]
android版的ijkplayer支不支持视频挂起功能？

**Comment by bbcallen** [comment]
What is "挂起"?

**Comment by 15301089517** [comment]
挂起就是:在视频播放时,暂停，然后离开播放页面，再重新进入播放页面的时候，视频还是暂停在该离开的时候的位置，并显示离开时播放的那一帧。

**Comment by bbcallen** [comment]
Yes and No. Depending on how you use it.

**Comment by dourgulf** [comment]
意思就是说你可以在上层做这个功能, 比方说"暂停"的时候记住当前的播放位置和画面截图, 重新打开的时候就直接seekTo上一次的暂停位置. 这些功能都属于"业务"层面的, 感觉不应该提给ijkplayer去做, 自己做就行了.

**Comment by 15301089517** [comment]
谢谢，好的，那么android版的ijkplayer如何实现视频截图呢?

**Comment by dourgulf** [comment]
截图应该是Android领域的事情, 不应该来问ijkplayer了吧~
