### ISSUE TITLE
你好，在播放视频的时候如果比例不对肯定会有黑边。我想处理这个黑边请教如何着手。

### ISSUE THREAD

**Issue by zhangchioulin** [Bilibili/ijkplayer#1534]
比如说竖屏播放一个横着的视频那么肯定会有黑边。我希望为黑边放一张好看的图片。请问该如何着手?
我想了想，能不能只拿出播放视频的内容把底部的黑边单独处理。请问这个能做到吗？
又或者背景默认就是黑色的，只是在上面加的内容View。请问能不能处理背部黑色的View？

**Comment by cooliean** [comment]
你想法很独特..还不如叫人吧视频处理好了在来...

[_player setScalingMode:IJKMPMovieScalingModeAspectFit];

**Comment by dourgulf** [comment]
"比如说竖屏播放一个横着的视频那么肯定会有黑边"

**Comment by dourgulf** [comment]
"比如说竖屏播放一个横着的视频那么肯定会有黑边"
对于这个问题, 我的处理方案是直接把横屏的视频旋转到横屏显示, 方法如下:

-(void)installMovieNotificationObservers {
///...
    
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(movieNaturalSizeAvailable:)
                                                 name:IJKMPMovieNaturalSizeAvailableNotification
                                               object:_player];
///...    
}

- (void)movieNaturalSizeAvailable:(NSNotification*)notification {
    NSLog(@"movieNaturalSizeAvailable");
    CGSize videoSize = self.player.naturalSize;
    CGSize selfsize = self.player.view.bounds.size;
    if (videoSize.width > videoSize.height) {
        CGAffineTransform rotate = CGAffineTransformMakeRotation(M_PI/2);
        CGFloat wf = (videoSize.height/selfsize.width);
        CGFloat hf = (videoSize.width/selfsize.height);
        CGFloat factor = MAX(wf, hf);
        // AspectFill
        CGAffineTransform scale = CGAffineTransformMakeScale(factor*(selfsize.width/videoSize.width),
                                                             factor*(selfsize.height/videoSize.height));
        // don't use other scalling mode, it will break the transform.

        self.player.scalingMode = IJKMPMovieScalingModeFill;
        self.player.view.transform = CGAffineTransformConcat(rotate, scale);
    }
}

**Comment by zhangchioulin** [comment]
谢谢！

**Comment by dourgulf** [comment]
没事， 解决了就关掉issue吧：）

**Comment by zhangchioulin** [comment]
谢谢

**Comment by Tipsyume** [comment]
Android也有这种情况，设置IRenderView.AR_ASPECT_FIT_PARENT也无效，

**Comment by dourgulf** [comment]
你没有理解什么叫AspectFit：~

**Comment by Tipsyume** [comment]
@dourgulf 是缩放模式吧
