### ISSUE TITLE
question about compile compile-ffmpeg.sh

### ISSUE THREAD

**Issue by xiangfly11** [Bilibili/ijkplayer#1536]
Hi , I try to compile the file "compile-ffmpeg.sh". I use these commands on terminal: "./compile-ffmpeg.sh clean", it works well, and then I typed "./compile-ffmpeg.sh all", I get error like this "tools/do-compile-ffmpeg.sh: line 52: /Volumes/WorkingStation/Studying2016/iOS: No such file or directory". 
The "compile-ffmpeg.sh" directory is "/Volumes/WorkingStation/Studying2016/iOS Practice/Live_Video/ijkplayer-ios/ios/compile-ffmpeg.sh". 
Is there anyone can give me any help on it? Thanks.

**Comment by bbcallen** [comment]
Modify tools/do-compile-ffmpeg.sh at line 52. Output the directory with echo to see what happens.

**Comment by dourgulf** [comment]
估计是这个路径有空格了?"OS Practice"

**Comment by xiangfly11** [comment]
@dourgulf 是的，你说的对，我前两天发现确实是这个问题。谢谢了！
