### ISSUE TITLE
ff_read(13):EXC_BAD_ACCESS 问题

### ISSUE THREAD

**Issue by fangliquan** [Bilibili/ijkplayer#1559]
我运行IOS的demo也没问题，开始的时候也问题。现在遇到了这个问题，一直播放不了而且还闪退
工程配置我也加上了
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
这些配置 但是还是不行求解
ijkmp_prepare_async()=0
Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto'
2016-06-30 13:04:58.305 DemoQPLive[6698:2517617] invalidateRenderBuffer
2016-06-30 13:04:58.306 DemoQPLive[6698:2517647] IJKSDLGLView: setupDisplay not ready
2016-06-30 13:04:58.315 DemoQPLive[6698:2517617] invalidateRenderBuffer
2016-06-30 13:04:58.315 DemoQPLive[6698:2517647] IJKSDLGLView: setupDisplay not ready

static int onInjectDidTcpConnect(IJKFFMoviePlayerController *mpc, int type, void *data, size_t data_size)
{
    IJKAVInject_IpAddress *realData = data;
    assert(realData);
    assert(sizeof(IJKAVInject_IpAddress) == data_size);

    mpc->_monitor.tcpError = realData->error;
    mpc->_monitor.remoteIp = [NSString stringWithUTF8String:realData->ip];
    [mpc->_glView setHudValue: mpc->_monitor.remoteIp forKey:@"ip"];

    return 0;
}

![Uploading E922BC24-3962-4A66-808C-7660B95B76E1.png…]()

**Comment by dooyawoo** [comment]
你好，你这个问题解决了吗？奇怪了我自己建了一个新工程可以正常运行的，导入到已有的工程里就有这个崩溃

**Comment by fangliquan** [comment]
恩解决了，我重新生成了一个ijk的Framework库 导入了项目里面

**Comment by dooyawoo** [comment]
我也解决了，另外一个库也用到了ffmpeg，把那个库移除掉就可以了，原因未知。
