### ISSUE TITLE
seek 的时候会卡住很长时间(10分钟以上)

### ISSUE THREAD

**Issue by flybird119** [Bilibili/ijkplayer#156]
播放本地的ts文件，当往后seek 10秒钟的时候，播放会卡住10分钟以上，然后继续播放。在ff_fplay.c的read_thread函数中增加日志，发现seek的时候一直打印ffp_toggle_buffering: full，然后继续循环，导致卡住10多分钟。试过了AVSEEK_FLAG_BYTE标志，还是一样的现象。 @bbcallen

**Comment by bbcallen** [comment]
用网盘共享一下这个文件。

**Comment by flybird119** [comment]
很开心收到大神邮件，感激 ：)

网盘：http://yunpan.cn/cKAFc5MDN3hab  提取码 2d37    
lost-1.ts

是在Android平台上播放lost-1.ts文件，使能了MediaCodec，播放开始6秒钟后，想快进到10秒钟，调用seekTo（10000），出现画面卡住，大概要10多分钟才能继续播放。从ff_ffplay.c日志来看，一直在循环打印ffp_toggle_buffering: full，然后就循环回去了，一直要10多分钟才会出来。

**Comment by flybird119** [comment]
HI bbcallen, seek长时间卡住的问题能用上面那个ts文件复现吗？ @bbcallen

**Comment by bbcallen** [comment]
最近还没时间看

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
