### ISSUE TITLE
ios 9

### ISSUE THREAD

**Issue by arlindpajaziti** [Bilibili/ijkplayer#1567]
do this plugin works in latest ios version 9.3.2.
if anyone integrated to any app in ios 9.3.2 can he send screenshot

**Comment by bbcallen** [comment]
Works for me.

**Comment by arlindpajaziti** [comment]
in this page it say 
iOS
platform: iOS 6.0~8.4.x

does it mean that it works from ios 6 to ios 8.4.x 
or it will work also with latest ios version

**Comment by xinzhengzhang** [comment]
@arlindpajaziti It works on iOS 9.x , the README has been updated.
