### ISSUE TITLE
IOS 关于playableDuration  duration 两个时间

### ISSUE THREAD

**Issue by cooliean** [Bilibili/ijkplayer#1568]
//当前播放时间
    NSTimeInterval currentPlaybackTime = self.delegatePlayer.currentPlaybackTime;
    //视频的总时间
    NSTimeInterval duration = self.delegatePlayer.duration;
    //当前已经缓存的时间
    NSTimeInterval playableDuration = self.delegatePlayer.playableDuration;
有一些视频在播放完成后，这两个时间不相等，因此我通过这个来设置的缓冲进度条不准确，又人遇到过，或者知道怎么解决不呢，谢谢了。

**Comment by bbcallen** [comment]
It's a known issue.

**Comment by cooliean** [comment]
噢噢，原来是知道的啊。好吧。谢谢了。

**Comment by jonrencxr** [comment]
请问这个问题解决了吗？麻烦告诉我一下。
