### ISSUE TITLE
Stream playing problems

### ISSUE THREAD

**Issue by brystel** [Bilibili/ijkplayer#158]
Hello, I've experienced some issues with stream playing smooth (with mediacodec support).

1. Stream playing slow -> stream playing very fast -> stream playing normal.
2. Stream playing slow -> seek to the other position -> stream playing normal

These issues happen randomly during stream playing.

Below logs:

`01-22 19:19:09.379    2575-2575/com.test.tv D/tv.danmaku.ijk.media.widget.VideoView﹕ onInfo: (MEDIA_INFO_BUFFERING_END)
01-22 19:19:10.809    2575-2789/com.test.tv E/IJKMEDIA﹕ invalid band type
01-22 19:19:10.809    2575-2789/com.test.tv E/IJKMEDIA﹕ channel element 3.2 is not allocated
01-22 19:19:12.269    2575-2740/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:19:12.539    2575-2740/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:19:14.389    2575-2789/com.test.tv E/IJKMEDIA﹕ Number of bands (49) exceeds limit (40).
01-22 19:19:14.389    2575-2789/com.test.tv E/IJKMEDIA﹕ Prediction is not allowed in AAC-LC.
01-22 19:19:18.519    2575-2789/com.test.tv E/IJKMEDIA﹕ Number of bands (46) exceeds limit (40).
01-22 19:19:18.519    2575-2789/com.test.tv E/IJKMEDIA﹕ channel element 2.4 is not allocated
01-22 19:19:21.239    2575-2740/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:19:22.209    2575-2740/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:19:24.909    2575-2773/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:19:25.659    2575-2773/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:19:26.659    2575-2789/com.test.tv E/IJKMEDIA﹕ Number of bands (44) exceeds limit (40).
01-22 19:19:26.659    2575-2789/com.test.tv E/IJKMEDIA﹕ SBR was found before the first channel element.
01-22 19:19:26.659    2575-2789/com.test.tv E/IJKMEDIA﹕ Prediction is not allowed in AAC-LC.
01-22 19:19:28.959    2575-2821/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:19:30.099    2575-2821/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:19:33.729    2575-2740/com.test.tv W/IJKMEDIA﹕ skipping 3 segments ahead, expired from playlists
01-22 19:19:33.869    2575-2773/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:19:34.049    2575-2740/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:19:34.569    2575-2773/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:19:38.619    2575-2821/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:19:39.329    2575-2821/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:19:43.869    2575-2773/com.test.tv W/IJKMEDIA﹕ skipping 2 segments ahead, expired from playlists
01-22 19:19:44.609    2575-2773/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:19:45.049    2575-2740/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:19:45.819    2575-2740/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:19:48.489    2575-2821/com.test.tv W/IJKMEDIA﹕ skipping 2 segments ahead, expired from playlists
01-22 19:19:49.719    2575-2821/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:19:50.599    2575-2789/com.test.tv E/IJKMEDIA﹕ Pulse data corrupt or invalid.
01-22 19:19:50.599    2575-2789/com.test.tv E/IJKMEDIA﹕ channel element 2.14 is not allocated
01-22 19:19:54.169    2575-2773/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:19:54.609    2575-2789/com.test.tv E/IJKMEDIA﹕ Number of bands (57) exceeds limit (40).
01-22 19:19:54.609    2575-2789/com.test.tv W/IJKMEDIA﹕ Sample rate index in program config element does not match the sample rate index configured by the container.
01-22 19:19:54.619    2575-2789/com.test.tv E/IJKMEDIA﹕ Inconsistent channel configuration.
01-22 19:19:54.619    2575-2789/com.test.tv E/IJKMEDIA﹕ get_buffer() failed
`

other moment:

`
01-22 19:21:15.509    2575-2824/com.test.tv E/IJKMEDIA﹕ Number of bands (47) exceeds limit (40).
01-22 19:21:15.509    2575-2824/com.test.tv E/IJKMEDIA﹕ Input buffer exhausted before END element found
01-22 19:21:16.459    2575-2821/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:21:16.709    2575-2821/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:21:19.649    2575-2824/com.test.tv W/IJKMEDIA﹕ SSR
01-22 19:21:19.649    2575-2824/com.test.tv W/IJKMEDIA﹕ is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
01-22 19:21:19.649    2575-2824/com.test.tv W/IJKMEDIA﹕ If you want to help, upload a sample of this file to ftp://upload.ffmpeg.org/incoming/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
01-22 19:21:19.649    2575-2824/com.test.tv W/IJKMEDIA﹕ Sample rate index in program config element does not match the sample rate index configured by the container.
01-22 19:21:19.669    2575-2824/com.test.tv E/IJKMEDIA﹕ Inconsistent channel configuration.
01-22 19:21:19.669    2575-2824/com.test.tv E/IJKMEDIA﹕ get_buffer() failed
01-22 19:21:20.269    2575-2867/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:21:20.689    2575-2867/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:21:22.839    2575-2773/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:21:23.249    2575-2773/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:21:23.649    2575-2824/com.test.tv E/IJKMEDIA﹕ Number of bands (54) exceeds limit (40).
01-22 19:21:23.649    2575-2824/com.test.tv E/IJKMEDIA﹕ Number of scalefactor bands in group (57) exceeds limit (49).
01-22 19:21:26.909    2575-2867/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:21:27.449    2575-2824/com.test.tv E/IJKMEDIA﹕ Number of bands (42) exceeds limit (40).
01-22 19:21:27.449    2575-2824/com.test.tv E/IJKMEDIA﹕ TYPE_FIL: Input buffer exhausted before END element found
01-22 19:21:27.609    2575-2867/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:21:28.429    2575-2821/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:21:28.679    2575-2821/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:21:31.709    2575-2824/com.test.tv E/IJKMEDIA﹕ Input buffer exhausted before END element found
01-22 19:21:31.709    2575-2824/com.test.tv E/IJKMEDIA﹕ Number of scalefactor bands in group (15) exceeds limit (14).
01-22 19:21:35.069    2575-2773/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:21:35.599    2575-2773/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:21:39.289    2575-2867/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:21:39.909    2575-2867/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:21:41.049    2575-2821/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:21:42.049    2575-2821/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:21:42.619    2575-2773/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:21:43.639    2575-2773/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:21:43.819    2575-2824/com.test.tv E/IJKMEDIA﹕ TNS filter order 22 is greater than maximum 12.
01-22 19:21:43.819    2575-2824/com.test.tv E/IJKMEDIA﹕ channel element 2.0 is not allocated
01-22 19:21:46.909    2575-2867/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:21:47.859    2575-2867/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:21:48.409    2575-2821/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:21:49.049    2575-2821/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:21:50.659    2575-2773/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:21:51.289    2575-2773/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:21:51.659    2575-2824/com.test.tv E/IJKMEDIA﹕ Number of bands (51) exceeds limit (40).
01-22 19:21:51.659    2575-2824/com.test.tv E/IJKMEDIA﹕ invalid band type
01-22 19:21:55.529    2575-2867/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:21:56.389    2575-2867/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:21:57.199    2575-2821/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:21:58.159    2575-2821/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:21:59.469    2575-2824/com.test.tv W/IJKMEDIA﹕ Sample rate index in program config element does not match the sample rate index configured by the container.
01-22 19:21:59.469    2575-2824/com.test.tv E/IJKMEDIA﹕ decode_pce: Input buffer exhausted before END element found
01-22 19:21:59.469    2575-2824/com.test.tv E/IJKMEDIA﹕ channel element 3.10 is not allocated
01-22 19:22:03.829    2575-2867/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:22:04.099    2575-2867/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:22:04.119    2575-2821/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:22:04.619    2575-2821/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:22:07.359    2575-2824/com.test.tv E/IJKMEDIA﹕ Number of bands (56) exceeds limit (40).
01-22 19:22:07.359    2575-2824/com.test.tv E/IJKMEDIA﹕ Reserved bit set.
01-22 19:22:10.939    2575-2824/com.test.tv E/IJKMEDIA﹕ Input buffer exhausted before END element found
01-22 19:22:10.939    2575-2824/com.test.tv E/IJKMEDIA﹕ Reserved bit set.
01-22 19:22:11.759    2575-2867/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:22:11.989    2575-2821/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:22:12.059    2575-2867/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:22:12.619    2575-2821/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:22:14.779    2575-2824/com.test.tv E/IJKMEDIA﹕ invalid band type
01-22 19:22:14.779    2575-2824/com.test.tv E/IJKMEDIA﹕ channel element 3.0 is not allocated
01-22 19:22:18.649    2575-2824/com.test.tv E/IJKMEDIA﹕ Number of bands (51) exceeds limit (40).
01-22 19:22:18.649    2575-2824/com.test.tv E/IJKMEDIA﹕ Prediction is not allowed in AAC-LC.
01-22 19:22:20.259    2575-2867/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:22:21.169    2575-2867/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:22:22.529    2575-2824/com.test.tv E/IJKMEDIA﹕ invalid band type
01-22 19:22:22.529    2575-2824/com.test.tv W/IJKMEDIA﹕ Sample rate index in program config element does not match the sample rate index configured by the container.
01-22 19:22:22.549    2575-2824/com.test.tv E/IJKMEDIA﹕ Inconsistent channel configuration.
01-22 19:22:22.549    2575-2824/com.test.tv E/IJKMEDIA﹕ get_buffer() failed
01-22 19:22:26.419    2575-2821/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:22:26.979    2575-2821/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:22:30.459    2575-2824/com.test.tv E/IJKMEDIA﹕ Number of bands (13) exceeds limit (12).
01-22 19:22:30.459    2575-2824/com.test.tv W/IJKMEDIA﹕ Sample rate index in program config element does not match the sample rate index configured by the container.
01-22 19:22:30.459    2575-2824/com.test.tv E/IJKMEDIA﹕ Inconsistent channel configuration.
01-22 19:22:30.459    2575-2824/com.test.tv E/IJKMEDIA﹕ get_buffer() failed
01-22 19:22:35.319    2575-2821/com.test.tv W/IJKMEDIA﹕ skipping 1 segments ahead, expired from playlists
01-22 19:22:35.509    2575-2821/com.test.tv W/IJKMEDIA﹕ PES packet size mismatch
01-22 19:22:38.009    2575-2824/com.test.tv E/IJKMEDIA﹕ Number of bands (48) exceeds limit (40).
01-22 19:22:38.009    2575-2824/com.test.tv E/IJKMEDIA﹕ Reserved bit set.
`

**Comment by bbcallen** [comment]
Does it work fine without MediaCodec, or with other player ?

**Comment by Peterede** [comment]
I have a similar issue to this where the video shows ghosting from other frames while playing with MediaCodec enabled.  On some devices like a Nexus 7 it is okay but on a Samsung Galaxy S3 the ghosting occurs, the files play fine with MediaCodec off and also play fine with MX Player and Hardware decoding enabled.

**Comment by bbcallen** [comment]
There are multiple decoder in Samsung Exynos SoC.

Modify this file to change decoder selection strategy, to see which decoder is OK.
https://github.com/bbcallen/ijkplayer/blob/master/android/ijkmediaplayer/src/tv/danmaku/ijk/media/player/IjkMediaCodecInfo.java

**Comment by Peterede** [comment]
Thankyou, I changed the priority of the decoder that was being used and now the video plays great!
I added:

        sKnownCodecList.put("OMX.SEC.avcdec", RANK_NO_SENSE);
