### ISSUE TITLE
Could anybody do me a favour, could not play http stream correct with custom header.

### ISSUE THREAD

**Issue by lyzzbhoneyline** [Bilibili/ijkplayer#1581]
07-05 16:01:15.727 26908-26908/com.test.testvideo D/IJKMEDIA: IjkMediaPlayer_reset
07-05 16:01:15.727 26908-26908/com.test.testvideo D/IJKMEDIA: IjkMediaPlayer_release
07-05 16:01:15.727 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
07-05 16:01:15.727 26908-26908/com.test.testvideo D/IJKMEDIA: ffpipeline_set_surface()
07-05 16:01:15.727 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
07-05 16:01:15.727 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_shutdown_l()
07-05 16:01:15.727 26908-26908/com.test.testvideo D/IJKMEDIA: wait for read_tid
07-05 16:01:15.727 26908-26908/com.test.testvideo D/IJKMEDIA: wait for video_refresh_tid
07-05 16:01:15.731 26908-30362/com.test.testvideo D/IJKMEDIA: message_loop exit
07-05 16:01:15.731 26908-30362/com.test.testvideo I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [30362]
07-05 16:01:15.755 26908-30363/com.test.testvideo I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [30363]
07-05 16:01:15.755 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_shutdown_l()=void
07-05 16:01:15.755 26908-26908/com.test.testvideo D/IJKMEDIA: IjkMediaPlayer_native_setup
07-05 16:01:15.755 26908-26908/com.test.testvideo I/IJKMEDIA: av_version_info: ff2.8--ijk0.4.1.1--dev0.3.3--rc4
07-05 16:01:15.755 26908-26908/com.test.testvideo D/IJKMEDIA: ffpipeline_create_from_android()
07-05 16:01:15.755 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_set_inject_opaque(0x1d300572)
07-05 16:01:15.755 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_set_inject_opaque()=void
07-05 16:01:15.755 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
07-05 16:01:15.755 26908-26908/com.test.testvideo D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
07-05 16:01:15.755 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
07-05 16:01:15.755 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_dec_ref(): ref=0
07-05 16:01:15.755 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_shutdown_l()
07-05 16:01:15.755 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_shutdown_l()=void
07-05 16:01:15.755 26908-26908/com.test.testvideo D/IJKMEDIA: IjkMediaPlayer_release
07-05 16:01:15.755 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
07-05 16:01:15.755 26908-26908/com.test.testvideo D/IJKMEDIA: ffpipeline_set_surface()
07-05 16:01:15.755 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
07-05 16:01:15.755 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_shutdown_l()
07-05 16:01:15.755 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_shutdown_l()=void
07-05 16:01:15.755 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_dec_ref(): ref=0
07-05 16:01:15.755 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_shutdown_l()
07-05 16:01:15.755 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_shutdown_l()=void
07-05 16:01:15.755 424-9860/system_process I/MediaFocusControl:  AudioFocus  abandonAudioFocus() from android.media.AudioManager@4adf9334
07-05 16:01:15.755 424-1049/system_process I/MediaFocusControl:  AudioFocus  requestAudioFocus() from android.media.AudioManager@4adf9334
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: IjkMediaPlayer_native_setup
07-05 16:01:15.759 26908-26908/com.test.testvideo I/IJKMEDIA: av_version_info: ff2.8--ijk0.4.1.1--dev0.3.3--rc4
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: ffpipeline_create_from_android()
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_set_inject_opaque(0x1d400572)
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_set_inject_opaque()=void
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(3)
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: moncleanup
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
07-05 16:01:15.759 26908-26908/com.test.testvideo D/tv.danmaku.ijk.media.player.IjkMediaPlayer: Couldn't open file on client side, trying server side
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
                                                              <!-- a padding to disable MSIE and Chrome friendly error 
                                                              <!-- a padding to disable MSIE and Chrome friendly error ")
                                                              <!-- a padding to disable MSIE and Chrome friendly error ")=0
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_set_android_surface(surface=0xe880001d)
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: ffpipeline_set_surface()
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_set_android_surface(surface=0xe880001d)=void
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: IjkMediaPlayer_prepareAsync
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_prepare_async()
07-05 16:01:15.759 26908-26908/com.test.testvideo I/IJKMEDIA: ===== versions =====
07-05 16:01:15.759 26908-26908/com.test.testvideo I/IJKMEDIA: FFmpeg       : ff2.8--ijk0.4.1.1--dev0.3.3--rc4
07-05 16:01:15.759 26908-26908/com.test.testvideo I/IJKMEDIA: libavutil    : 54.31.100
07-05 16:01:15.759 26908-26908/com.test.testvideo I/IJKMEDIA: libavcodec   : 56.60.100
07-05 16:01:15.759 26908-26908/com.test.testvideo I/IJKMEDIA: libavformat  : 56.40.101
07-05 16:01:15.759 26908-26908/com.test.testvideo I/IJKMEDIA: libswscale   : 3.1.101
07-05 16:01:15.759 26908-26908/com.test.testvideo I/IJKMEDIA: libswresample: 1.2.101
07-05 16:01:15.759 26908-26908/com.test.testvideo I/IJKMEDIA: ===== options =====
07-05 16:01:15.759 26908-26908/com.test.testvideo I/IJKMEDIA: player-opts : mediacodec                   = 0
07-05 16:01:15.759 26908-26908/com.test.testvideo I/IJKMEDIA: player-opts : opensles                     = 0
07-05 16:01:15.759 26908-26908/com.test.testvideo I/IJKMEDIA: player-opts : overlay-format               = 842225234
07-05 16:01:15.759 26908-26908/com.test.testvideo I/IJKMEDIA: player-opts : framedrop                    = 1
07-05 16:01:15.759 26908-26908/com.test.testvideo I/IJKMEDIA: player-opts : start-on-prepared            = 0
07-05 16:01:15.759 26908-26908/com.test.testvideo I/IJKMEDIA: format-opts : ijkinject-opaque             = 490734962
07-05 16:01:15.759 26908-26908/com.test.testvideo I/IJKMEDIA: format-opts : http-detect-range-support    = 0
07-05 16:01:15.759 26908-26908/com.test.testvideo I/IJKMEDIA: format-opts : timeout                      = 10000000
07-05 16:01:15.759 26908-26908/com.test.testvideo I/IJKMEDIA: format-opts : reconnect                    = 1
07-05 16:01:15.759 26908-26908/com.test.testvideo I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
07-05 16:01:15.759 26908-26908/com.test.testvideo I/IJKMEDIA: ===================
07-05 16:01:15.759 26908-26908/com.test.testvideo D/IJKMEDIA: ijkmp_prepare_async()=0
07-05 16:01:15.771 26908-30576/com.test.testvideo I/IJKMEDIA: SDL_RunThread: [30576] ff_read
                                                              <!-- a padding to disable MSIE and Chrome friendly error : No such file or directory
07-05 16:01:15.771 26908-30576/com.test.testvideo I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [30576]
07-05 16:01:15.771 26908-30575/com.test.testvideo I/IJKMEDIA: SDL_RunThread: [30575] ff_vout
07-05 16:01:15.775 26908-30574/com.test.testvideo I/IJKMEDIA: SDL_RunThread: [30574] ff_msg_loop
07-05 16:01:15.775 26908-30574/com.test.testvideo D/IJKMEDIA: message_loop
07-05 16:01:15.775 26908-30574/com.test.testvideo D/IJKMEDIA: FFP_MSG_FLUSH:
07-05 16:01:15.775 26908-30574/com.test.testvideo D/IJKMEDIA: FFP_MSG_ERROR: 0
07-05 16:01:15.795 26908-26908/com.test.testvideo E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
07-05 16:01:15.795 26908-26908/com.test.testvideo D/IjkVideoView: Error: -10000,0
07-05 16:01:53.931 672-31101/com.google.android.gms W/Uploader: No account for auth token provided
07-05 16:02:08.930 424-446/system_process I/ActivityManager: Waited long enough for: ServiceRecord{4a99b854 u0 com.google.android.gms/.playlog.uploader.UploaderIntentService}
07-05 16:02:14.022 672-31101/com.google.android.gms D/Uploader: Network request failed class org.apache.http.conn.ConnectTimeoutException(Connect to /216.58.199.106:443 timed out)
07-05 16:02:36.830 531-567/com.android.systemui D/dalvikvm: GC_FOR_ALLOC freed 635K, 82% free 4729K/25636K, paused 13ms, total 14ms

**Comment by bbcallen** [comment]
https://ffmpeg.org/ffmpeg.html
and
```
mp.setOption(...)
```

**Comment by lyzzbhoneyline** [comment]
thx a lot.
