### ISSUE TITLE
How can I enable hardware accelerate feature in Android?

### ISSUE THREAD

**Issue by sunjinbo** [Bilibili/ijkplayer#1596]
If I try to play some HD video, there are always appear audio/video sync issue in some of my android devices, the below codes is my ijkMediaPlayer settings, and BTW, how can I enable hardware accelerate feature of ijkMediaPlayer in Android? I want to try if there is a improvement, thanks a lot!

        mMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 48);
        mMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzeduration", "2000000");
        mMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probsize", "4096");
        mMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_frame", 8);

**Comment by bbcallen** [comment]
See demo.

**Comment by kazemihabib** [comment]
@bbcallen  where is the demo? can you please give me a link?

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/search?utf8=✓&q=demo

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/android/ijkplayer/ijkplayer-example/src/main/java/tv/danmaku/ijk/media/example/widget/media/IjkVideoView.java

**Comment by kazemihabib** [comment]
@bbcallen  thanks
