### ISSUE TITLE
android 打包混淆完后报错，找不到so文件，但平常测试没问题

### ISSUE THREAD

**Issue by dazhiyu** [Bilibili/ijkplayer#1598]

**Comment by bbcallen** [comment]
Sorry, not familiar with proguard.

**Comment by jyfree** [comment]
#ijkplayer
-keep class tv.danmaku.ijk.media.player.** {*; }
-keepclasseswithmembernames class tv.danmaku.ijk.media.player.IjkMediaPlayer{
    native <methods>;
}
-keepclasseswithmembernames class tv.danmaku.ijk.media.player.ffmpeg.FFmpegApi{
    native <methods>;
}

**Comment by 18369188711why** [comment]
I solve the problem throught this way:
#you main project
-keep class tv.danmaku.ijk.media.player.** {*; }
-keep class tv.danmaku.ijk.media.player.IjkMediaPlayer{
* ;
}
-keep class tv.danmaku.ijk.media.player.ffmpeg.FFmpegApi{
* ;
}

**Comment by shouhouhuakai** [comment]
上面的解答不适合于所有的so吧
