### ISSUE TITLE
Calling seekTo does not work

### ISSUE THREAD

**Issue by thuantran** [Bilibili/ijkplayer#160]
Another minor issue that might be related with #159, if you call IjkMediaPlayer.start() then IjkMediaPlayer.seekTo() in onPrepared, it does not work, even though it does work for Android MediaPlayer. What I did to work around this issue at the moment is using this method from onPrepared:
```java
    private void playThenSeek() {
        mMp.start();
        mSurfaceView.postDelayed(new Runnable() {
            @Override
            public void run() {
                seek();
            }
        }, 50);
    }
```

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
