### ISSUE TITLE
[iOS]缓存相关

### ISSUE THREAD

**Issue by lipengda** [bilibili/ijkplayer#1602]
当我拖动进度条到没有缓存的进度时,这时候缓存停止不再增长了.(试过很多次,假如不拖动进度条到没有缓存的位置,缓存是一直增长的)
期待回复,感谢.

**Comment by lipengda** [comment]
就是假如现在 playableDuration为30%,我把进度条拖动到60%,这时playableDuration保持30%不变.不拖动的话playableDuration会持续增长,我是用来做点播.
打扰了!

**Comment by bbcallen** [comment]
Create a breakpoint in ffp_check_buffering_l() to see what happens.

**Comment by bbcallen** [comment]
Then debug to see where it goes.
