### ISSUE TITLE
does ijkplayer support HLS? and How to build if I wish to use ExoPlayer as backend?

### ISSUE THREAD

**Issue by liwei46** [Bilibili/ijkplayer#1603]
Hi all,

I am new to ijkplayer, I wish to ask the following question:
1) does ijkplayer support HLS?
2) and How to build if I wish to use ExoPlayer as backend?  In README.md, for building Android, 
the steps are 
git clone https://github.com/Bilibili/ijkplayer.git ijkplayer-android
cd ijkplayer-android
git checkout -B latest k0.5.1
./init-android.sh
cd android/contrib
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all
cd ..
./compile-ijk.sh all

what are the steps if I wish to build the latest version and use ExoPlayer?

Thanks and best regards.

Regards,
liwei

**Comment by bbcallen** [comment]
1. Yes.
2. new ExoMediaPlayer(), you don't have to build any native library, it's pure java.

FYI: ExoMediaPlayer is only a wrapper for comparison testing. Most of its features are not tested.

**Comment by liwei46** [comment]
thanks a lot!
