### ISSUE TITLE
重新编译无效

### ISSUE THREAD

**Issue by swdrts** [Bilibili/ijkplayer#161]
我采用以下脚本去编译
git clone https://github.com/bbcallen/ijkplayer.git ijkplayer-android-master
cd ijkplayer-android-master
git checkout master

cd config
ln -fs module-default.sh module.sh  #或者是ln -fs module-lite.sh module.sh
cd ..

./init-android.sh

cd android
./compile-ffmpeg.sh all
./compile-ijk.sh all
我改动了module.sh里面的任何内容，重新编译，ijkmediaplayer/libs中的so文件从大小和md5码来对比，完全一样
请问，改动了module.sh配置文件后，重新编译要怎样操作？？

**Comment by bbcallen** [comment]
```
sh compile-ffmpeg clean
```

**Comment by swdrts** [comment]
sh compile-ffmpeg clean 已经尝试过，编译结果还是一样

**Comment by bbcallen** [comment]
try
```
rm module.sh
ln -fs module-default.sh module.sh
```
