### ISSUE TITLE
Some options not take effect

### ISSUE THREAD

**Issue by hhbgk** [Bilibili/ijkplayer#1617]
Hi @bbcallen @Android4MediaPlayer 
I have some issues with play RTSP stream.
There is no(or a little?)  latency when I execute this command `ffplay -fflags nobuffer -probesize 32 -sync ext -rtsp_transport tcp rtsp://xxx.xx.x`  to play live stream on ubuntu .

However, I set those options to ijkplayer are not taking effect, like:
`ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "probesize", 32);
                    ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "fflags", "nobuffer");
                    ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "sync", "ext");`
Why？ and how to do ?
thanks in advance!

**Comment by bbcallen** [comment]
IjkMediaPlayer.OPT_CATEGORY_FORMAT

**Comment by bbcallen** [comment]
IjkMediaPlayer.OPT_CATEGORY_FORMAT

**Comment by hhbgk** [comment]
@bbcallen thanks.
In fact , I fix it after a long test. So , I still not understand what difference among `OPT_CATEGORY_FORMAT` `OPT_CATEGORY_CODEC` `OPT_CATEGORY_SWS`  `OPT_CATEGORY_PLAYER`. And I can not find any comments about that.

**Comment by bbcallen** [comment]
They are several individual modules.
