### ISSUE TITLE
iOS 开启硬解会有一半绿屏 

### ISSUE THREAD

**Issue by zywang** [Bilibili/ijkplayer#1626]
iOS开启硬解会有一半绿屏，必现，使用master最新代码，下面是我的配置

    IJKFFOptions *options = [[IJKFFOptions alloc] init];
    
    [options setPlayerOptionIntValue:30     forKey:@"max-fps"];
    [options setPlayerOptionIntValue:0      forKey:@"framedrop"];
    [options setPlayerOptionIntValue:3      forKey:@"video-pictq-size"];
    [options setPlayerOptionIntValue:1      forKey:@"videotoolbox"];
    [options setPlayerOptionIntValue:960    forKey:@"videotoolbox-max-frame-width"];
    
    [options setFormatOptionIntValue:0                  forKey:@"auto_convert"];
    [options setFormatOptionIntValue:1                  forKey:@"reconnect"];
    [options setFormatOptionIntValue:30 * 1000 * 1000   forKey:@"timeout"];
    [options setFormatOptionValue:@"ijkplayer"          forKey:@"user-agent"];

**Comment by zywang** [comment]
找到原因了，推流端使用的是腾讯直播的推流，推流开启了硬解，再使用播放器就会一半绿屏，关闭了腾讯的硬解推流，就正常了。
这个要怎么解决呢。。。

**Comment by bbcallen** [comment]
I don't know without any information.

**Comment by zywang** [comment]
确认是推流端的问题，不是播放的问题。

**Comment by ctiao** [comment]
@zywang  最后推流端怎么解决的 ？
