### ISSUE TITLE
H.265 support

### ISSUE THREAD

**Issue by mahermeg17** [Bilibili/ijkplayer#1628]
Hi,
Thank you for this work.

I need to read H.265 stream that is recently supported by ffmpeg http://www.cnx-software.com/2016/06/29/ffmpeg-3-1-adds-support-for-openmax-encoding-on-raspberry-pi-va-api-h-264-h-265-encoding-and-more/

The actual ijk player (I'm using android dist) can open a H.265 stream but just play sound but no video or sometimes can show a single frame.

So can you support H.265 or indicate me how to do it ?
Thanks in advance.

**Comment by bbcallen** [comment]
h265 is disabled by default, you need to modify config/module-lite.sh to enable it, see README.

**Comment by mahermeg17** [comment]
Thanks.
