### ISSUE TITLE
How can I merge  FFmpegMediaMetadataRetriever into the compile progress?

### ISSUE THREAD

**Issue by kingty** [bilibili/ijkplayer#1629]
https://github.com/wseemann/FFmpegMediaMetadataRetriever
I want use some funcs about this repo. so I want merge this into ijkplayer.
How can I do that ? 
It will be appreciate with your help.

**Comment by bbcallen** [comment]
1. Make sure both repo are build against same version of ffmpeg,
2. Modify build scripts to add dependence on same ffmpeg library.
