### ISSUE TITLE
play https m3u8 file Protocol not found

### ISSUE THREAD

**Issue by l123456789jy** [Bilibili/ijkplayer#1632]

**Comment by bbcallen** [comment]
Build openssl first, and enable https.

**Comment by FloridaStream** [comment]
Note: **https** working @l123456789jy .
Check **--enable-openssl**

**Comment by l123456789jy** [comment]
https://github.com/l123456789jy/ijkplayer 我自己编译了一份，有需要播放https可以使用。

**Comment by Kuoyhout** [comment]
@l123456789jy  How did you enable https and compile it?

**Comment by fukemy** [comment]
lol @l123456789jy  i love u 😍
