### ISSUE TITLE
ios播放器布局对象是哪个View？

### ISSUE THREAD

**Issue by Yeehok** [Bilibili/ijkplayer#1638]
我对player.view属性进行了布局后并不能在屏幕上看到播放器，请问布局对象应该是哪个属性？

**Comment by SoXeon** [comment]
就是这个View，参照Demo中IJKMoviePlayerViewController.m中对player.view的操作

**Comment by bbcallen** [comment]
player.view doesn't  contain any UI, it's only used for video rendering.
