### ISSUE TITLE
IJKFFMoviePlayerController iOS NSURL string issue

### ISSUE THREAD

**Issue by kwstasna** [Bilibili/ijkplayer#1639]
Hello.
I'm using your framework in an iOS project and i'm giving it a url of rtmp to play.
but if this url contains greek or chinese or any other characters my app crashes.
Does your framework support somehow special characters etc?

Thanks!

**Comment by bbcallen** [comment]
Which init function are you using, initWithContentURL or initWithContentURLString?
I'm not sure if the first one would do urlencode, but you can do urlencode yourself, and pass it to the second init function.

**Comment by kwstasna** [comment]
`IJKFFMoviePlayerController(contentURL: NSURL(string: Config.rtmpPlayUrl + room.key), withOptions: IJKFFOptions.optionsByDefault())`

**Comment by xinzhengzhang** [comment]
@kwstasna Can you provide your url which caused the app crash?

**Comment by kwstasna** [comment]
rtmp://178.62.248.233/live/α

**Comment by kwstasna** [comment]
Had to use `contentURLString`

**Comment by xinzhengzhang** [comment]
@kwstasna 
According the document https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSURL_Class/index.html#//apple_ref/occ/instm/NSURL/initWithString:
`[[NSURL alloc]initWithString:@"rtmp://178.62.248.233/live/α"]` will return nil.

By the way, I have plan to remove the interface for `contentURL` .

**Comment by kwstasna** [comment]
just dont remove contentURLString cause its working smooth !! xD

**Comment by noamtcohen** [comment]
@kwstasna can you show me the swift code you use to play the rtmp stream including the way you add the player to the view?

**Comment by kwstasna** [comment]
@noamtcohen  https://github.com/ltebean/Live
