### ISSUE TITLE
seek的时候出现System.err错误

### ISSUE THREAD

**Issue by flybird119** [Bilibili/ijkplayer#164]
01-21 10:34:56.723  3548  3587 W SDL_AMediaCodecJava_flush
01-21 10:34:56.729  3548  3566 E SDL_AMediaCodecJava_releaseOutputBuffer: releaseOutputBuffer----------------1
01-21 10:34:56.729  3548  3566 E SDL_AMediaCodecJava_releaseOutputBuffer: releaseOutputBuffer----------------2
01-21 10:34:56.732  3548  3566 E SDL_AMediaCodecJava_releaseOutputBuffer: releaseOutputBuffer----------------3
01-21 10:34:56.732  3548  3566 W System.err: java.lang.IllegalStateException
01-21 10:34:56.732  3548  3566 W System.err: 	at android.media.MediaCodec.releaseOutputBuffer(Native Method)
01-21 10:34:56.732  3548  3566 W System.err: 	at dalvik.system.NativeStart.run(Native Method)
@bbcallen

**Comment by bbcallen** [comment]
机型?

**Comment by flybird119** [comment]
hisi的平台

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
