### ISSUE TITLE
Can not play video which record by Phone on Android 4.2.2,And there will be a rotation when play the video

### ISSUE THREAD

**Issue by kingty** [bilibili/ijkplayer#1647]
I  recorded a video on two phones  and used the demo you provide.

 SUMSUNG Galaxy Mega which android version is 4.2.2,the video can't play when use IjkMediaPlayer and will cause a restart of the phone which is terrible,works for Android MediaPlayer,and works for IjkExoPlayer but with a 90 degrees rotation.

SUMSUNG Galaxy S6 which version is Android 6.0,works for all mediaPlayers,But the IjkMediaPlayer have a 90 degrees ratation.

**Comment by Android4MediaPlayer** [comment]
give out the tested file

**Comment by kingty** [comment]
The file is too big , download it [here](https://pan.baidu.com/s/1ge1WNE7)please

**Comment by Android4MediaPlayer** [comment]
ok

**Comment by bbcallen** [comment]
For SUMSUNG Galaxy Mega, I don't have such device to debug with.

For SUMSUNG Galaxy S6
https://github.com/Bilibili/ijkplayer/search?utf8=✓&q=rotate
