### ISSUE TITLE
播放帧数低

### ISSUE THREAD

**Issue by shidongdi** [Bilibili/ijkplayer#1649]
用IjkMediaPlayer播放，刚开始的几秒帧数很低（FPS开始开始显示只有十几，后面保持在25左右），画面延迟。用IjkExoMediaPlayer和原生的则帧数正常，能帮忙看下怎么解决？Log如下：
07-18 15:06:04.375 8405-8405/tv.danmaku.ijk.media.example I/J4A: API-Level: 19
07-18 15:06:04.375 8405-8405/tv.danmaku.ijk.media.example W/J4A: J4ALoader: Ignore: 'android.media.PlaybackParams' need API 19
07-18 15:06:04.460 8405-8405/tv.danmaku.ijk.media.example I/AudioManager: requestAudioFocus() status : 1
07-18 15:06:04.460 8405-8405/tv.danmaku.ijk.media.example I/AudioManager: requestAudioFocus() apk    : tv.danmaku.ijk.media.example
07-18 15:06:04.460 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: av_version_info: ff3.1--ijk0.6.0--20160715--001
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: ===== versions =====
07-18 15:06:04.465 8405-8560/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [8560] ff_msg_loop
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: FFmpeg       : ff3.1--ijk0.6.0--20160715--001
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: libavutil    : 55.27.100
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: libavcodec   : 57.48.101
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: libavformat  : 57.40.101
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: libswscale   : 4.1.100
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: libswresample: 2.1.100
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: ===== options =====
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : mediacodec                   = 1
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : mediacodec-auto-rotate       = 1
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : mediacodec-handle-resolution-change = 0
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : opensles                     = 1
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : overlay-format               = fcc-yv12
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : start-on-prepared            = 0
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : framedrop                    = 5
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : ijkinject-opaque             = 488637558
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : ijkapplication               = 2003282080
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : http-detect-range-support    = 0
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: codec-opts  : skip_frame                   = 8
07-18 15:06:04.465 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: ===================
07-18 15:06:04.470 8405-8405/tv.danmaku.ijk.media.example W/libOpenSLES: class OutputMix interface 0 requested but unavailable MPH=43
07-18 15:06:04.470 8405-8405/tv.danmaku.ijk.media.example I/IJKMEDIA: aout_set_volume(1.000000, 1.000000)
07-18 15:06:04.475 8405-8563/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [8563] ff_vout
07-18 15:06:04.475 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [8564] ff_read
07-18 15:06:04.625 8405-8564/tv.danmaku.ijk.media.example E/IJKMEDIA: Option http-detect-range-support not found.
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: max_frame_duration: 10.000
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'http://cdn.v.zjol.com.cn/120011.mp4':
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA:   Metadata:
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA:     major_brand     : 
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: isom
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA:     minor_version   : 
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: 512
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA:     compatible_brands: 
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: isomiso2avc1mp41
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA:     creation_time   : 
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: 2016-05-13 03:03:45
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA:     encoder         : 
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: Lavf57.25.100
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA:   Duration: 
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: 00:00:29.64
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: , start: 
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: 0.000000
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: , bitrate: 
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: 1434 kb/s
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA:     Stream #0:0
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: (eng)
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: : Video: h264, 1 reference frame (avc1 / 0x31637661), yuv420p(left), 1280x720 [SAR 1:1 DAR 16:9], 0/1, 1325 

kb/s
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: , 
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: 25 fps, 
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: 25 tbr, 
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: 12800 tbn, 
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: 50 tbc
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA:  (default)
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA:     Metadata:
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA:       creation_time   : 
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: 2016-05-13 03:03:45
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA:       handler_name    : 
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: VideoHandler
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA:     Stream #0:1
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: (eng)
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: : Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 102 kb/s
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA:  (default)
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA:     Metadata:
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA:       creation_time   : 
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: 2016-05-13 03:03:45
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA:       handler_name    : 
07-18 15:06:04.765 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: SoundHandler
07-18 15:06:04.770 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: OpenSL-ES: native sample rate 48000 Hz
07-18 15:06:04.770 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: API-Level: 19
07-18 15:06:04.770 8405-8564/tv.danmaku.ijk.media.example W/IJKMEDIA: OpenSL-ES: force resample 0 to native sample rate 48000
07-18 15:06:04.780 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: OpenSL-ES: bytes_per_frame  = 4 bytes
07-18 15:06:04.780 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: OpenSL-ES: milli_per_buffer = 10 ms
07-18 15:06:04.780 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: OpenSL-ES: frame_per_buffer = 441 frames
07-18 15:06:04.780 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: OpenSL-ES: bytes_per_buffer = 1764 bytes
07-18 15:06:04.780 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: OpenSL-ES: buffer_capacity  = 449820 bytes
07-18 15:06:04.780 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: AudioCodec: avcodec, aac
07-18 15:06:04.780 8405-8571/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [8571] ff_aout_opensles
07-18 15:06:04.785 8405-8572/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [8572] ff_audio_dec
07-18 15:06:04.790 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: ffpipenode_create_video_decoder_from_android_mediacodec: MediaCodec: H264_HIGH: enabled
07-18 15:06:04.790 8405-8564/tv.danmaku.ijk.media.example I/IJKMEDIA: AMediaFormat: video/avc, 1280x720

**Comment by bbcallen** [comment]
Don't use OpenSL ES.

**Comment by shidongdi** [comment]
谢谢，解决了
