### ISSUE TITLE
Need help please!

### ISSUE THREAD

**Issue by Edydaoud** [Bilibili/ijkplayer#1658]
**I can see these lines in my logcat, but can you help me how to get these info in my java class at least as a String? the more i need is to get service_name. Thank you.**

07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA: Input #0, mpegts, from 'udp://@224.1.10.44:1234':
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA:   Duration: 
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA: N/A
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA: , start: 
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA: 20953.491811
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA: , bitrate: 
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA: N/A
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA:   Program 1 
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA:     Metadata:
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA:       service_name    : 
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA: STARZ
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA:       service_provider: 
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA: UCL
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA:     Stream #0:0
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA: [0x3f6]
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example D/IJKMEDIA: , 50, 1/90000
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA: : Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, s16p, 128 kb/s
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA:     Stream #0:1
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA: [0x3f5]
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example D/IJKMEDIA: , 32, 1/90000
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA: : Video: mpeg2video, 1 reference frame ([2][0][0][0] / 0x0002), yuv420p(tv, left), 720x576 [SAR 64:45 DAR 16:9], 1001/48000, max. 3300 kb/s
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA: , 
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA: 23.98 fps, 
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA: 23.98 tbr,

**Comment by Edydaoud** [comment]
when i stream udp i got these lines in logcat 

07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA: service_name : 
07-19 11:11:22.899 21991-22077/tv.danmaku.ijk.media.example I/IJKMEDIA: STARZ

is there any way to get service name? as a string?

**Comment by bbcallen** [comment]
No such API.
Modify ff_ffplay.c to implement it.
