### ISSUE TITLE
play  encryption m3u8   Invalid data found when processing input

### ISSUE THREAD

**Issue by l123456789jy** [Bilibili/ijkplayer#1660]
我使用的是https的连接，m3u8文件加了key,使用系统播放器没有问题，播放未加密的https可以。

**Comment by bbcallen** [comment]
Build OpenSSL first, and modify config/module-lite.sh to enable https support.

**Comment by l123456789jy** [comment]
@bbcallen 找了下，能说下module-lite.sh具体哪个属性吗？

**Comment by l123456789jy** [comment]
@bbcallen 我目前可以播放https的视频，就是播放加密的https m3u8视频播放不了。

**Comment by wanglang515** [comment]
@l123456789jy m3u8加密后的文件不能播放时怎么解决的呢，Android系统原始的的确可以播放加密或者不加密的m3u8文件，但是用ijkplayer暂时不能加密的，没有加密的可以。我使用的普通的http的链接地址播放

**Comment by l123456789jy** [comment]
@wanglang515 
我没有使用ijkplayer使用Android原声播放器，你试下最新的版本试试。
