### ISSUE TITLE
ijkplayer能直接播放rtmp://格式的url吗？

### ISSUE THREAD

**Issue by asamanyx** [Bilibili/ijkplayer#1661]
如题，如果可以请简单说明一下api调用。谢谢。
刚调通demo，但demo里都是http://m3u8。

**Comment by bbcallen** [comment]
Have you tried?

**Comment by asamanyx** [comment]
刚接触，还不清楚内部的运行机制，也不清楚rtmp://的url是否能正常播放。
我在本地的测试url      
rtmp://120.76.204.244/live/desktop


打印信息：
===== custom modules begin =====
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff3.1--ijk0.6.0--20160715--001
ijkmp_set_inject_opaque(0x7fad317bc930)
ijkmp_set_inject_opaque()=void
2016-07-20 09:21:40.880 IJKMediaDemo[876:13828] OK setup GL
ijkmp_ios_set_view(glView=0x7fad315934c0)
ijkmp_ios_set_view(glView=0x7fad315934c0)=void
2016-07-20 09:21:40.883 IJKMediaDemo[876:13828] invalidateRenderBuffer
2016-07-20 09:21:40.883 IJKMediaDemo[876:14037] IJKSDLGLView: setupDisplay not ready
ijkmp_set_data_source(url="rtmp://120.76.204.244/live/desktop")
ijkmp_set_data_source(url="rtmp://120.76.204.244/live/desktop")=0
ijkmp_prepare_async()
remove 'timeout' option for rtmp.
===== versions =====
FFmpeg       : ff3.1--ijk0.6.0--20160715--001
libavutil    : 55.27.100
libavcodec   : 57.48.101
libavformat  : 57.40.101
libswscale   : 4.1.100
libswresample: 2.1.100
===== options =====
player-opts : video-pictq-size             = 3
player-opts : overlay-format               = fcc-_es2
player-opts : max-fps                      = 30
player-opts : framedrop                    = 0
player-opts : videotoolbox-max-frame-width = 960
player-opts : videotoolbox                 = 0
player-opts : start-on-prepared            = 1
format-opts : ijkinject-opaque             = 140381836265776
format-opts : ijkapplication               = 140381834266944
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : safe                         = 0
format-opts : reconnect                    = 1
===================
ijkmp_prepare_async()=0
remove 'timeout' option for rtmp.
No default whitelist set
No default whitelist set
Handshaking...
2016-07-20 09:21:40.901 IJKMediaDemo[876:13828] invalidateRenderBuffer
2016-07-20 09:21:40.901 IJKMediaDemo[876:14037] IJKSDLGLView: setupDisplay not ready
2016-07-20 09:21:40.905 IJKMediaDemo[876:13828] invalidateRenderBuffer
2016-07-20 09:21:40.905 IJKMediaDemo[876:14037] IJKSDLGLView: setupDisplay not ready
Type answer 3
Server version 4.0.0.1
Proto = rtmp, path = /live/desktop, app = live, fname = desktop
Server bandwidth = 10000000
Client bandwidth = 10000000
Creating stream...
av_version_info: ff3.1--ijk0.6.0--20160715--001
ijkmp_set_inject_opaque(0x7fad317d92c0)
ijkmp_set_inject_opaque()=void
2016-07-20 09:21:41.415 IJKMediaDemo[876:13828] OK setup GL
ijkmp_ios_set_view(glView=0x7fad3146f6b0)
ijkmp_ios_set_view(glView=0x7fad3146f6b0)=void
2016-07-20 09:21:41.421 IJKMediaDemo[876:13828] invalidateRenderBuffer
2016-07-20 09:21:41.421 IJKMediaDemo[876:14030] IJKSDLGLView: setupDisplay not ready
2016-07-20 09:21:41.422 IJKMediaDemo[876:13828] Warning: Attempt to present <IJKVideoViewController: 0x7fad317d2720> on <IJKDemoInputURLViewController: 0x7fad317717b0> whose view is not in the window hierarchy!
[rtmp @ 0x7fad3147de30] Sending play command for 'desktop'
[rtmp @ 0x7fad3147de30] New incoming chunk size = 1024
[flv @ 0x7fad31811e00] Format flv probed with size=2048 and score=100
Option ijkinject-opaque not found.
[flv @ 0x7fad31811e00] Before avformat_find_stream_info() pos: 13 bytes read:33161 seeks:0 nb_streams:0
[flv @ 0x7fad31811e00] video stream discovered after head already parsed
[flv @ 0x7fad31811e00] audio stream discovered after head already parsed
[flv @ 0x7fad31811e00] parser not found for codec mp3, packets or times may be invalid.


[flv @ 0x7fad31811e00] parser not found for codec mp3, packets or times may be invalid.
[rtmp @ 0x7fad3147de30] Sending bytes read report
[flv @ 0x7fad31811e00] Probe buffer size limit of 5000000 bytes reached
[flv @ 0x7fad31811e00] Setting avg frame rate based on r frame rate
[flv @ 0x7fad31811e00] Could not find codec parameters for stream 0 (Video: flv1, 1 reference frame, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[flv @ 0x7fad31811e00] Could not find codec parameters for stream 1 (Audio: mp3, 22050 Hz, mono): unspecified frame size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[flv @ 0x7fad31811e00] After avformat_find_stream_info() pos: 5097823 bytes read:5097823 seeks:0 frames:1598
[FFPlayer @ 0x7fad31678de0] max_frame_duration: 10.000
Input #0, flv, from 'rtmp://120.76.204.244/live/desktop':
  Metadata:
    encoder         : Lavf57.38.100
    length          : 13
  Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
    Stream #0:0, 277, 1/1000: Video: flv1, 1 reference frame, none, 8 fps, 8 tbr, 1k tbn
    Stream #0:1, 1321, 1/1000: Audio: mp3, 22050 Hz, mono
No codec could be found with id 86017
No codec could be found with id 22
Failed to open file 'rtmp://120.76.204.244/live/desktop' or configure filtergraph
2016-07-20 09:22:16.534 IJKMediaDemo[876:13828] FFP_MSG_ERROR: 0
2016-07-20 09:22:16.534 IJKMediaDemo[876:13828] IJKMPMoviePlayBackStateDidChange 2: paused
2016-07-20 09:22:16.534 IJKMediaDemo[876:13828] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1

**Comment by bellchen** [comment]
能播

**Comment by bbcallen** [comment]
```
Stream #0:0, 277, 1/1000: Video: flv1, 1 reference frame, none, 8 fps, 8 tbr, 1k tbn
Stream #0:1, 1321, 1/1000: Audio: mp3, 22050 Hz, mono
No codec could be found with id 86017
No codec could be found with id 22
```
You need to modify config/module-lite.sh to enable these decoders.

**Comment by asamanyx** [comment]
It is OK. Thanks very much.
![7b0eed0b-28f0-4b2e-846a-f91351001dd0](https://cloud.githubusercontent.com/assets/18439426/16979404/816f642c-4e93-11e6-9a94-89f429dc8bb7.png)


In ”Before Build“,  "sh compile-ffmpeg clean" is wrong, please fix it.
```
cd config
rm module.sh
ln -s module-lite.sh module.sh
cd android/contrib
# cd ios
<font color=red>sh compile-ffmpeg.sh clean</font>

./init-ios.sh

cd ios
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all
```
In LAN, my iOS simulator delay 7 seconds.How to reduce the delay?

![0abcf117-b2f4-40f8-8acc-57dc3b38dd76](https://cloud.githubusercontent.com/assets/18439426/16979407/880b1d26-4e93-11e6-9f40-bffc270452b8.png)

**Comment by bbcallen** [comment]
https://ffmpeg.org/documentation.html

**Comment by huangjunsong** [comment]
@asamanyx 你好，已经解决了不能直接播放rtmp://格式的问题了吗？是怎么解决的呢？

**Comment by asamanyx** [comment]
@huangjunsong  iOS下看我上面的说明，说白了就是我的格式是编译文件默认不支持的，增加音视频格式进去就行了。

**Comment by qq313452249** [comment]
我想请问如何播放rtmp，我用vlc可以播放不知道为什么用ijkplayer不能播放一直显示 parser not found for codec mp3, packets or times may be invalid.  
感谢

**Comment by xiruoruo** [comment]
几年前的版本我不知道，反正现在的版本是可以的哦
