### ISSUE TITLE
编译时报错，找不到 ibavformat/avformat.h 文件

### ISSUE THREAD

**Issue by ChiaoZenYee** [Bilibili/ijkplayer#1668]
编译时报错，找不到 ibavformat/avformat.h 文件 
请问怎么添加这个 ibavformat 这个库？

**Comment by leopardoooo** [comment]
我也遇到这个问题，就是用Xcode打开Demo，直接运行就会提示这个错误。

**Comment by bbcallen** [comment]
Build ffmpeg first, see README.

**Comment by GintokiS** [comment]
@ChiaoZenYee 我看到这个issue添加的时间比较长，不知现在问题解决了没。

如果正常编译完ffmpeg还是报找不到头文件的错误，请在工程里配置Header Search Paths，按照ffmpeg库文件的路径来添加头文件路径的值。

如果问题解决了，这个issue可以关闭了吗？

**Comment by ChiaoZenYee** [comment]
可以先关闭吧，暂时找到点眉目，后面有问题我在发帖请教您哈，多谢指导！


原始邮件
发件人:GintokiSnotifications@github.com
收件人:Bilibili/ijkplayerijkplayer@noreply.github.com
抄送:ChiaoZenYeejameschaozzy@126.com; Mentionmention@noreply.github.com
发送时间:2016年8月3日(周三) 18:56
主题:Re: [Bilibili/ijkplayer] 编译时报错，找不到 ibavformat/avformat.h 文件 (#1668)


@ChiaoZenYee 我看到这个issue添加的时间比较长，不知现在问题解决了没。
如果正常编译完ffmpeg还是报找不到头文件的错误，请在工程里配置Header Search Paths，按照ffmpeg库文件的路径来添加头文件路径的值。
如果问题解决了，这个issue可以关闭了吗？
