### ISSUE TITLE
How to add subtitles?

### ISSUE THREAD

**Issue by brystel** [Bilibili/ijkplayer#167]
Hello, 
Could you navigate me how can I add subtitles for local video / steam content?
Can I achieve this without native code modifications?

**Comment by bbcallen** [comment]
Better to draw a TextView in java code, only concern is how to do lip-sync which need native code modifications.

**Comment by brystel** [comment]
What do you mean by lip-sync with native code modifications? 
Cannot it be done using getCurrentPosition() method?

**Comment by bbcallen** [comment]
With getCurrentPosition(), it's very likely to sync subtitles in a polling loop
```
while (true) {
    if (mp.getCurrentPosition() >= xxxx) {
        textView.set(xxx);
        ......
    }
}
```
Maybe it works, but it's inefficient, and not accurate enough, in my opinion.

It's better to introduce something like timedTextCallback triggered by native.
http://developer.android.com/reference/android/media/MediaPlayer.html#setOnTimedTextListener(android.media.MediaPlayer.OnTimedTextListener)

**Comment by brystel** [comment]
I will try this and will inform about progress.

How to deal with subtitles in stream? 

Here is example link:
https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8

**Comment by bbcallen** [comment]
Subtitles support is removed. Bettter to try original ffplay.

**Comment by brystel** [comment]
Is it good idea to merge subtitles part from original ffplay.c into ff_ffplay.c ?
Will it be enough for subtitles from stream?

**Comment by bbcallen** [comment]
I don't need subtitles, so I don't have plan for it now.

I try to reserve the original format of ffplay.c in ff_ffplay.c,
So you can directly diff both file to find out the modification.

Most subtitles are removed by
```
#ifndef FFP_MERGE
...
#endif
```

**Comment by vincentssn** [comment]
Hi, @bbcallen, after search all the issues about subtitles, I still can not understand how to let the ffmpeg demux/decode the subtitles, and pass it to the java application. can you explain it in details? 
about the FFP_MERGE, should I modify the native code?

**Comment by bbcallen** [comment]
1. I've never used subtitles in ijkplayer, so, I can't answer the question.
2. The code commented out by FFP_MERGE is in original ffplay, but no use in ijkplayer. It's convenient for me to merge code from ffplay to ijkplayer.
3. Yes, you have to modify native code.

**Comment by vincentssn** [comment]
ok, thanks a lot @bbcallen
