### ISSUE TITLE
编译Android x86版本报错

### ISSUE THREAD

**Issue by swdrts** [Bilibili/ijkplayer#168]
采用module-default.sh编译android版本，会出现以下错误：
CC	libavcodec/x86/mlpdsp_init.o
CC	libavcodec/x86/mpegaudiodsp.o
CC	libavcodec/x86/mpegvideo.o
CC	libavcodec/x86/mpegvideodsp.o
STRIP	libavcodec/x86/me_cmp.o
CC	libavcodec/x86/mpegvideoenc.o
YASM	libavcodec/x86/mpegvideoencdsp.o
In file included from libavcodec/x86/mpegvideoenc.c:83:0:
libavcodec/x86/mpegvideoenc_template.c: In function 'dct_quantize_ssse3':
libavcodec/x86/mpegvideoenc_template.c:151:9: error: 'asm' operand has impossible constraints
         __asm__ volatile(
         ^
libavcodec/x86/mpegvideoenc_template.c:186:9: error: 'asm' operand has impossible constraints
         __asm__ volatile(
         ^
STRIP	libavcodec/x86/mpegvideoencdsp.o
CC	libavcodec/x86/mpegvideoencdsp_init.o
make: *** [libavcodec/x86/mpegvideoenc.o] 错误 1
make: *** 正在等待未完成的任务....
尝试了disable-asm和disable-yasm还算会报上面的错，最终通过--disable-decoder=dirac解决了这个错误，请问这种解决方法是否正确？
编译环境为Ubuntu 14.04，安装了yasm1.2.0

**Comment by bbcallen** [comment]
没什么问题，反正dirac很少用到。
