### ISSUE TITLE
Android版的demo如何播放视频流？

### ISSUE THREAD

**Issue by CzachQ** [Bilibili/ijkplayer#1681]
生成的apk安装后APP首页是存储目录
请问想要播放在线视频流应该如何操作呢？

谢谢！

**Comment by CzachQ** [comment]
或者是在哪里可以把播放地址写死为视频流地址呢？

**Comment by bbcallen** [comment]
Modify the source code of demo.

**Comment by CzachQ** [comment]
Found and solved, thanks.
