### ISSUE TITLE
关于多端播放的问题

### ISSUE THREAD

**Issue by MathiasLuo** [Bilibili/ijkplayer#1685]
我们现在用的是ffconcat进行播放多段视频，但是我遇到的问题是我不知道每一个视频段时间，所以说拉动会出现问题，我想问一下，有没有其他的方法来解决这个问题？

**Comment by Android4MediaPlayer** [comment]
No

**Comment by bbcallen** [comment]
No

**Comment by MathiasLuo** [comment]
那我还想问一下，我能不能在ijk中去提前获取一个视频的时长信息呢？ 就像ffprobe一样？ 
谢谢了

**Comment by bbcallen** [comment]
No
