### ISSUE TITLE
大神我使用./init-ios.sh根本下载不下来ffmpeg,每次下栽到20就错误了,去ffmpeg官网下载下来最新的包也不知道如何导入这个项目,我该怎么办呢?

### ISSUE THREAD

**Issue by SkyHarute** [Bilibili/ijkplayer#1686]
大神我使用./init-ios.sh根本下载不下来ffmpeg,每次下栽到20就错误了,去ffmpeg官网下载下来最新的包也不知道如何导入这个项目,我该怎么办呢?

**Comment by bbcallen** [comment]
Have you heard about shadowsocks?

**Comment by OneHundredSir** [comment]
解决了吗?好像使用VPN也下不下啦.
