### ISSUE TITLE
Apply filters

### ISSUE THREAD

**Issue by vuzya** [Bilibili/ijkplayer#1690]
Hello.
I could not find in docs, but maybe you can suggest:
If I have, for example, deblocking filter 
`-vf 'pp=hb/vb/dr/fq|8' `
for ffplay, is it possible to apply similar for ijkplayer?
Currently I'm using module-default.sh as module.sh, do I need to change it?
Do I need to just set some param like 
`ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "vf", "pp=hb/vb/dr/fq|8");`
? Or implement some additional functionality?

**Comment by Android4MediaPlayer** [comment]
you can try

**Comment by bbcallen** [comment]
That's the right direction.

You also need to modify https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/config.h to enable avfilter in ijkplayer
```
#define CONFIG_AVFILTER 1
```

"vf" option is removed from ff_ffplay.c, need to be copid from official ffplay into ff_ffplay_options.h and ff_ffplay.c

After this point, you are on your own. I've never get that far.

**Comment by vuzya** [comment]
Thanks. Looks like "vf0" key is what I need.
I also need to modify module.sh: remove --disable-postproc and add --enable-gpl to include pp filter to build.

Thanks a lot!

**Comment by animaonline** [comment]
@vuzya Hi there, were you able to get it working? :)

**Comment by Yair0007** [comment]
@vuzya Did you manage to make video filters work ?
