### ISSUE TITLE
基于android平台，如何调试ijkplayer中ffmpeg部分的代码？

### ISSUE THREAD

**Issue by YuEagle** [Bilibili/ijkplayer#1694]

**Comment by yuazhen** [comment]
You can try these (assuming you are using linux):
1.adb pull /system/bin/app_process32 .
2.adb pull /system/lib lib/
3.extract so libs to lib/ from your apk, especially libijkffmpeg.so
4.start your app's activity and find out its pid
5.run "gdbserver --attach :port pid" in adb shell which port is gdbserver listen port and pid is your app pid
6.run "adb forward local_port remote_port" in your local shell, which local_port is your local port and remote_port is gdbserver listen port
6.run "arm-linux-androideabi-gdb app_process32" in your local shell
7.type "target remote :local_port" in gdb shell
8.type "set solib_search_path lib/" in gdb shell
9.now the app is paused and waiting for gdb commands. you can do debug.

**Comment by bbcallen** [comment]
Nothing to add.

For myself, I debug ffmpeg on iOS or MacOS.
