### ISSUE TITLE
是不是必须调用loadLibrariesOnce，native_profileBegin和native_profileEnd？？

### ISSUE THREAD

**Issue by WeixiangZhang** [Bilibili/ijkplayer#1695]
在Android下使用，是不是必须要调用loadLibrariesOnce，native_profileBegin和native_profileEnd这三个方法。
我没调用，也能播放啊。

**Comment by bbcallen** [comment]
Go ahead.

**Comment by WeixiangZhang** [comment]
@bbcallen what do you mean "Go ahead" ??  I don't get it.

**Comment by bbcallen** [comment]
Means "do whatever you want."

**Comment by WeixiangZhang** [comment]
@bbcallen Thanks!

**Comment by mppy1** [comment]
如果不调用，在一般的手机上，都没有问题，但是性能会有问题，遇到比较差的手机，极端情况，会出现花屏、闪屏，黑屏，一闪一闪的非常影响用户体验。
