### ISSUE TITLE
cocoapods Integrated ijkplayer to the workspace

### ISSUE THREAD

**Issue by cqhcqhcqh** [Bilibili/ijkplayer#1701]
ld: illegal text-relocation to 'cstring' in 
libavcodec.a(aac_adtstoasc_bsf.o) from '_aac_adtstoasc_filter' in libavcodec.a(aac_adtstoasc_bsf.o) for architecture i386

**Comment by cqhcqhcqh** [comment]
when cocoapods Integrated ijkplayer to the workspace

pod  lib lint --no-clean --verbose --allow-warnings

can't passed validation

wish to pass validation

project source : https://github.com/cqhcqhcqh/MediaplayerLib

**Comment by bbcallen** [comment]
This repository is empty.

**Comment by cqhcqhcqh** [comment]
Please refresh again...

**Comment by cqhcqhcqh** [comment]
this repository is not empty. Please validation

**Comment by bbcallen** [comment]
Seems an FFmpeg issue.
Try google "ffmpeg  text-relocation"

**Comment by cqhcqhcqh** [comment]
Thanks a lot ! 'OTHER_LDFLAGS' => '-read_only_relocs suppress' Fixed that

**Comment by ClegeJJ** [comment]
> Thanks a lot ! 'OTHER_LDFLAGS' => '-read_only_relocs suppress' Fixed that

s.pod_target_xcconfig = { 'OTHER_LDFLAGS' => '-read_only_relocs suppress'}

i fixed that. thanks!
