### ISSUE TITLE
cygwin64 Terminal ./compile-ffmpeg.sh all failed

### ISSUE THREAD

**Issue by scanor** [Bilibili/ijkplayer#1710]
$ ./compile-ffmpeg.sh all
====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a arm64 x86 x86_64
FF_ACT_ARCHS = armv5 armv7a arm64 x86 x86_64

====================
[*] check env armv5
====================
FF_ARCH=armv5
FF_BUILD_OPT=

--------------------
[*] make NDK standalone toolchain
--------------------
build on CYGWIN_NT-6.1 x86_64
ANDROID_NDK=D:/ndk/android-ndk-r12b
IJK_NDK_REL=12.1.2977051
NDKr12.1.2977051 detected
Cygwin temp prefix=C:/cygwin64/tmp/

--------------------
[*] check ffmpeg env
--------------------

--------------------
[*] configurate ffmpeg
--------------------
/cygdrive/d/ijkplayer-master/android/contrib/build/ffmpeg-armv5/toolchain/bin/arm-linux-androideabi-gcc
./configure:行9: $'\r': 未找到命令
): No such file or directorycale: LC_ALL: 无法改变区域选项 (C
': 不是有效的标识符行:export: `LC_ALL
./configure:行13: $'\r': 未找到命令
./configure:行16: $'\r': 未找到命令
./configure:行17: 未预期的符号 `$'{\r'' 附近有语法错误
'/configure:行17: `try_exec(){

**Comment by scanor** [comment]
这个问题我已经解决了，是linux跟window换行符不同的问题

**Comment by wtchaos** [comment]
请问是如何解决的啊

**Comment by scanor** [comment]
你好，我的解决方式是将该文件的‘\r’全局替换为'\r\n'.但是值得注意的是，除了这个字符还有其他字符也要替换。。。蛋疼。。。最后我改用mac来编译了，非常顺利。。。

**Comment by wtchaos** [comment]
我在win下用sublime打开文件搜索\r\n没有搜到，但能搜到\n，我准备去ubuntu下编译了···请问你在mac下编译没有出现什么问题了么？

**Comment by scanor** [comment]
搜索\r\n当然搜不到啊，是搜索\r然后替换成\r\n啊，Ubuntu也可以，在mac下印象中木有任何障碍。

**Comment by wtchaos** [comment]
\r也搜索不到诶·······

**Comment by scanor** [comment]
估计是因为你没有开启特殊字符的搜索，你要搜索特殊字符，而不是普通字符“\r”

**Comment by wtchaos** [comment]
开了啊···\n能搜到\r搜索不到···我放弃了···去ubuntu试试···
