### ISSUE TITLE
ijkplayer能否支持rtsp

### ISSUE THREAD

**Issue by YuEagle** [Bilibili/ijkplayer#1713]
通过修改module-lite.sh添加对rtsp的支持，发现在播放的过程中一直处于pause状态并陷入死循环
#if CONFIG_RTSP_DEMUXER || CONFIG_MMSH_PROTOCOL
         if (is->paused &&
                 (!strcmp(ic->iformat->name, "rtsp") ||
                  (ic->pb && !strncmp(ffp->input_filename, "mmsh:", 5)))) {
             /* wait 10 ms to avoid trying to get another packet */
             /* XXX: horrible */
             SDL_Delay(10);
             continue;
         }
 #endif

**Comment by YuEagle** [comment]
通过修改module-lite.sh添加对rtsp的支持，发现在播放的过程中一直处于pause状态并陷入死循环
#if CONFIG_RTSP_DEMUXER || CONFIG_MMSH_PROTOCOL
         if (is->paused &&
                 (!strcmp(ic->iformat->name, "rtsp") ||
                  (ic->pb && !strncmp(ffp->input_filename, "mmsh:", 5)))) {
             /* wait 10 ms to avoid trying to get another packet */
             /* XXX: horrible */
             SDL_Delay(10);
             continue;
         }
 #endif

**Comment by bbcallen** [comment]
Seems you called pause()

**Comment by YuEagle** [comment]
My source only contains video track, and maybe Ijkplayer can not support video track only files well.
I fixed it, and you can check this issue and provide one better solution.
