### ISSUE TITLE
Vivo手机无法正常播放视频

### ISSUE THREAD

**Issue by 81813780** [Bilibili/ijkplayer#1719]
**问题描述：** 同个视频URL，经测试，小米和Moto的可以正常播放，**但是Vivo的手机播放不了。**

**Vivo手机日志如下图：**
![我是图](http://o8wshxdfk.bkt.clouddn.com/QQ%E5%9B%BE%E7%89%8720160725184731.png)

**非常感谢Bilibili提供的开源库**

**Comment by bbcallen** [comment]
I don't think you were using ijkplayer.

**Comment by 81813780** [comment]
Okay，if you thought this log was not from ijkplayer .

**Comment by bbcallen** [comment]
The log shows "pldroid-player-native".
I don't know which version they are based on, and what they have modified.
That's to say, it's out of my hands.

**Comment by 81813780** [comment]
You are right , thanks for your reply .
