### ISSUE TITLE
崩溃报告中有好多这个崩溃日志

### ISSUE THREAD

**Issue by xcxcxc** [Bilibili/ijkplayer#172]
=> Start Application received signal SIGSEGV 
	-> translating『 0x52c721 』=> 
	-> translating『 0x5647b7 』=> -[IJKSDLGLRenderI420 display:] /Users/xxxx/ijkplayer-ios-stable/ios/IJKMediaPlayer/IJKMediaPlayer/ijkmedia/ijksdl/ios/IJKSDLGLRenderI420.m: line 71
	-> translating『 0x56eb09 』=> -[IJKSDLGLView displayInternal:] /Users/xxxx/ijkplayer-ios-stable/ios/IJKMediaPlayer/IJKMediaPlayer/ijkmedia/ijksdl/ios/IJKSDLGLView.m: line 496
	-> translating『 0x56e937 』=> -[IJKSDLGLView display:] /Users/xxxx/ijkplayer-ios-stable/ios/IJKMediaPlayer/IJKMediaPlayer/ijkmedia/ijksdl/ios/IJKSDLGLView.m: line 483
	-> translating『 0x570003 』=> 
	-> translating『 0x560ea7 』=> 
	-> translating『 0x5617c7 』=> video_refresh_thread /Users/xxxx/ijkplayer-ios-stable/ijkmedia/ijkplayer/ff_ffplay.c: line 2735
	-> translating『 0x564ca5 』=> SDL_RunThread /Users/xxxx/ijkplayer-ios-stable/ios/IJKMediaPlayer/IJKMediaPlayer/ijkmedia/ijksdl/ios/ijksdl_thread_ios.m: line 26
=> End Application received signal SIGSEGV 

ijkplayer 版本: 1848841743c404ed79777c39a40deea44630ba9a

**Comment by bbcallen** [comment]
这个bug我也有收到报告，但是因为不知道重现条件，所以暂时不知道该怎么改。
