### ISSUE TITLE
err when playing mp3 file with http protocal

### ISSUE THREAD

**Issue by gqb** [Bilibili/ijkplayer#1722]

**Comment by gqb** [comment]
av_read_frame error: ffffff98(�,�,�,�): unknown
07-26 14:38:57.951 8144-8749/com.missevan.android.myapplication E/IJKMEDIA: av_read_frame error: ffffff98(�,�,�,�): unknown
07-26 14:38:58.966 8144-8749/com.missevan.android.myapplication E/IJKMEDIA: av_read_frame error: ffffff98(�,�,�,�): unknown
07-26 14:38:59.976 8144-8749/com.missevan.android.myapplication E/IJKMEDIA: av_read_frame error: ffffff98(�,�,�,�): unknown
07-26 14:39:00.991 8144-8749/com.missevan.android.myapplication E/IJKMEDIA: av_read_frame error: ffffff98(�,�,�,�): unknown
07-26 14:39:01.996 8144-8749/com.missevan.android.myapplication E/IJKMEDIA: av_read_frame error: ffffff98(�,�,�,�): unknown
07-26 14:39:03.011 8144-8749/com.missevan.android.myapplication E/IJKMEDIA: av_read_frame error: ffffff98(�,�,�,�): unknown
07-26 14:39:04.026 8144-8749/com.missevan.android.myapplication E/IJKMEDIA: av_read_frame error: ffffff98(�,�,�,�): unknown
07-26 14:39:05.036 8144-8749/com.missevan.android.myapplication I/IJKMEDIA: ffp_toggle_buffering: error: -104
07-26 14:39:05.036 8144-8749/com.missevan.android.myapplication E/IJKMEDIA: av_read_frame error: ffffff98(�,�,�,�): unknown
07-26 14:39:05.036 8144-8747/com.missevan.android.myapplication D/IJKMEDIA: FFP_MSG_ERROR: 0
07-26 14:39:05.041 8144-8144/com.missevan.android.myapplication E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
07-26 14:39:05.041 8144-8144/com.missevan.android.myapplication I/erro: -10000 -- 0
07-26 14:39:06.046 8144-8749/com.missevan.android.myapplication I/IJKMEDIA: ffp_toggle_buffering: eof

**Comment by gqb** [comment]
my source is "http://static.missevan.com/sound/201512/15/fe033ba27474875f4a5b174e349882b1225106.mp3"

**Comment by gqb** [comment]
but how to edit it? I can play mp3, but it just stop after a few minutes.

Is it enable this line ?
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-bsf=mp3_header_decompress"

**Comment by bbcallen** [comment]
Use module-default.sh if you don't want to know how to config ffmpeg.

**Comment by gqb** [comment]
I compiled it and solved the error ,but I found the method "onBufferingUpdate" can not be invoked by ijkplayer

**Comment by bbcallen** [comment]
Any log?

**Comment by bbcallen** [comment]
What do you mean "not be invoked"?
If IO speed is fast enough, there is no need to call onBufferingUpdate

**Comment by gqb** [comment]
This issue is ok now,but could you help me to solve this issue,[https://github.com/Bilibili/ijkplayer/issues/1778](url)
