### ISSUE TITLE
Android端IjkMediaPlayer播放本地视频，setOnBufferingUpdateListener监听播放进度，onBufferingUpdate不是一秒调用一次

### ISSUE THREAD

**Issue by scar1et** [Bilibili/ijkplayer#1723]
请问一下这个问题应该如何处理，或者还有没有其他api可以获得正确的播放进度

下面是代码
mediaPlayer.setOnBufferingUpdateListener(new IMediaPlayer.OnBufferingUpdateListener() {
            @Override
            public void onBufferingUpdate(IMediaPlayer mp, final int percentage) {
                LogUtils.d(TAG, String.format("percentage: %s, curPosition: %s, duration: %s",
                        percentage, mp.getCurrentPosition(), mp.getDuration()));
            }
        });

下面是Log

07-26 14:50:57.356 728-728/com.cylonspace.vrplayer D/VideoDetailActivity: percentage: 0, curPosition: 0, duration: 16462
07-26 14:50:57.866 728-728/com.cylonspace.vrplayer D/VideoDetailActivity: percentage: 46, curPosition: 388, duration: 16462
07-26 14:50:58.391 728-728/com.cylonspace.vrplayer D/VideoDetailActivity: percentage: 49, curPosition: 915, duration: 16462
07-26 14:50:58.896 728-728/com.cylonspace.vrplayer D/VideoDetailActivity: percentage: 53, curPosition: 1417, duration: 16462
07-26 14:50:59.426 728-728/com.cylonspace.vrplayer D/VideoDetailActivity: percentage: 56, curPosition: 1948, duration: 16462
07-26 14:50:59.966 728-728/com.cylonspace.vrplayer D/VideoDetailActivity: percentage: 59, curPosition: 2490, duration: 16462
07-26 14:51:00.491 728-728/com.cylonspace.vrplayer D/VideoDetailActivity: percentage: 62, curPosition: 3013, duration: 16462
07-26 14:51:00.996 728-728/com.cylonspace.vrplayer D/VideoDetailActivity: percentage: 65, curPosition: 3517, duration: 16462
07-26 14:51:01.531 728-728/com.cylonspace.vrplayer D/VideoDetailActivity: percentage: 69, curPosition: 4053, duration: 16462
07-26 14:51:02.056 728-728/com.cylonspace.vrplayer D/VideoDetailActivity: percentage: 72, curPosition: 4576, duration: 16462
07-26 14:51:02.556 728-728/com.cylonspace.vrplayer D/VideoDetailActivity: percentage: 75, curPosition: 5077, duration: 16462
07-26 14:51:03.061 728-728/com.cylonspace.vrplayer D/VideoDetailActivity: percentage: 78, curPosition: 5583, duration: 16462
07-26 14:51:03.596 728-728/com.cylonspace.vrplayer D/VideoDetailActivity: percentage: 81, curPosition: 6118, duration: 16462
07-26 14:51:04.126 728-728/com.cylonspace.vrplayer D/VideoDetailActivity: percentage: 84, curPosition: 6648, duration: 16462
07-26 14:51:04.661 728-728/com.cylonspace.vrplayer D/VideoDetailActivity: percentage: 88, curPosition: 7182, duration: 16462
07-26 14:51:05.191 728-728/com.cylonspace.vrplayer D/VideoDetailActivity: percentage: 90, curPosition: 7712, duration: 16462
07-26 14:51:05.761 728-728/com.cylonspace.vrplayer D/VideoDetailActivity: percentage: 94, curPosition: 8283, duration: 16462

**Comment by bbcallen** [comment]
Why should it be called per seconds?

**Comment by scar1et** [comment]
我自己计时实现了该需求，谢谢回复
