### ISSUE TITLE
IjkMediaPlayer for Android, when i call the method seekTo()，sometimes it show these: 

### ISSUE THREAD

**Issue by scar1et** [Bilibili/ijkplayer#1726]
E/IJKMEDIA: http://cache.utovr.com/201508270528174780.m3u8: error while seeking
E/IJKMEDIA: http://cache.utovr.com/201508270528174780.m3u8: error while seeking
E/IJKMEDIA: http://cache.utovr.com/201508270528174780.m3u8: error while seeking
......

Is there some options wrong?     
  
        mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
        mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-auto-rotate", 1);
        mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "overlay-format", IjkMediaPlayer.SDL_FCC_RV32);
        mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 60);
        mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "max-fps", 0);
        mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 48);

**Comment by bbcallen** [comment]
Nothing is wrong.
It's very likely you've got network error.

**Comment by scar1et** [comment]
But when my network resume, it always show these message

E/IJKMEDIA: http://cache.utovr.com/201508270528174780.m3u8: error while seeking
E/IJKMEDIA: http://cache.utovr.com/201508270528174780.m3u8: error while seeking
E/IJKMEDIA: http://cache.utovr.com/201508270528174780.m3u8: error while seeking

**Comment by bbcallen** [comment]
Attach to debugger, or add logs to see what happens.

**Comment by scar1et** [comment]
Thanks, I got it.

**Comment by ZhangBingbin** [comment]
@scar1et Hello,Could you tell me your how did you solve it?

**Comment by harlanc** [comment]
@bbcallen why I use local m3u8 and ts ,the problem also appears.
