### ISSUE TITLE
请问0.6.0的更新中MediaCodec和VideoToolbox这两处更新是什么含义？

### ISSUE THREAD

**Issue by CzachQ** [Bilibili/ijkplayer#1729]
MediaCodec: add options to enable resolution change.
VideoToolbox: add options to enable resolution change.

这里的enable resolution change是指什么呢
是解决了 #1601 中的问题（live stream resolution change）么？

**Comment by CzachQ** [comment]
@bbcallen 打扰了 求解
代码看到
`    public void setOption(int category, String name, String value)
    {
        _setOption(category, name, value);
    }

    public void setOption(int category, String name, long value)
    {
        _setOption(category, name, value);
    }

    /**
     * @param category
     * @param name
     * @param value
     */
    private native void _setOption(int category, String name, String value);
    private native void _setOption(int category, String name, long value);`

之后就不知道它的作用在哪里了

**Comment by bbcallen** [comment]
I don't remember, you can find it out with git log.

**Comment by CzachQ** [comment]
@bbcallen 
https://github.com/Bilibili/ijkplayer/commit/46eb7dec4f6c478ef81dfb73ed53aa411f834c76?diff=unified
在这个修改中可以看到为了这一目的 修改的代码
但看起来只是修改了代码中的一些判断条件
不过它的功能是什么呢？
或者我应该在哪个方向查找一下？
Thanks

**Comment by bbcallen** [comment]
Google "mp4 rotate"

**Comment by bbcallen** [comment]
It handles resolution change during streaming live video.

**Comment by CzachQ** [comment]
@bbcallen 
这个功能是在demo的settings 中的 MediaCodec handle resolution change 来开启的么？

**Comment by bbcallen** [comment]
Yes

**Comment by CzachQ** [comment]
thanks
