### ISSUE TITLE
播放影片时长超过了总时长,希望大神给予指点

### ISSUE THREAD

**Issue by yeshibuzhong** [Bilibili/ijkplayer#1732]
User-Agent: ijkplayer

Accept: */*

Connection: close

Host: 122.228.205.30

Icy-MetaData: 1

[mpegts @ 0x13c953a00] Continuity check failed for pid 0 expected 4 got 0
[mpegts @ 0x13c953a00] Continuity check failed for pid 4095 expected 4 got 0
[mpegts @ 0x13c953a00] Continuity check failed for pid 256 expected 13 got 0
aout_pause_audio(1)
[FFPlayer @ 0x13e0ae0b0] ffp_toggle_buffering: completed: OK
ijkmp_get_msg: FFP_MSG_COMPLETED
[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2870行] moviePlayBackStateDidChange 0: stoped
[BBIJKPlayerVC.m:2813行] moviePlayDidFinish

[BBIJKPlayerVC.m:2819行] playbackStateDidChange: MPMovieFinishReasonPlaybackEnded: 0

ijkmp_pause()
ijkmp_pause()=0
ijkmp_get_msg: FFP_REQ_PAUSE
aout_pause_audio(1)
ijkmp_stop()
ijkmp_stop()=0
[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2870行] moviePlayBackStateDidChange 0: stoped
ijkmp_seek_to(0)
ijkmp_seek_to(0)=-3
ijkmp_stop()
ijkmp_stop()=0
ijkmp_shutdown_l()
wait for read_tid
aout_close_audio()
[AVIOContext @ 0x13de35470] Statistics: 668 bytes read, 0 seeks
wait for video_refresh_tid
ijkmp_shutdown_l()=void
ijkmp_dec_ref(): ref=0
ijkmp_shutdown_l()
ijkmp_shutdown_l()=void
aout_close_audio()

**Comment by bbcallen** [comment]
Duration is parsed from format header, but currentPosition is generated from frame->pts.
There is no guarantee they should be equal.

**Comment by yeshibuzhong** [comment]
OK , thanks
