### ISSUE TITLE
iOS  软解播放4K影片卡顿非常严重

### ISSUE THREAD

**Issue by yeshibuzhong** [Bilibili/ijkplayer#1733]
av_version_info: ff2.8--ijk0.4.1.1--dev0.3.3--rc4
ijkmp_set_inject_opaque(0x151596220)
ijkmp_set_inject_opaque()=void
[IJKSDLGLView.m:310行] OK setup GL

[IJKSDLGLView.m:1642行] init sphere 12288 18432
ijkmp_ios_set_view(glView=0x1516c7660)
ijkmp_ios_set_view(glView=0x1516c7660)=void
ijkmp_set_data_source(url="http://192.168.4.26:43710/%E7%BE%8E%E5%A5%B3%E7%83%A4%E9%B8%AD.mp4")
ijkmp_set_data_source(url="http://192.168.4.26:43710/%E7%BE%8E%E5%A5%B3%E7%83%A4%E9%B8%AD.mp4")=0
ijkmp_prepare_async()
===== versions =====
[FFPlayer @ 0x151561810] FFmpeg       : ff2.8--ijk0.4.1.1--dev0.3.3--rc4
[FFPlayer @ 0x151561810] libavutil    : 54.31.100
[FFPlayer @ 0x151561810] libavcodec   : 56.60.100
[FFPlayer @ 0x151561810] libavformat  : 56.40.101
[FFPlayer @ 0x151561810] libswscale   : 3.1.101
[FFPlayer @ 0x151561810] libswresample: 1.2.101
===== options =====
[FFPlayer @ 0x151561810] player-opts : start-on-prepared            = 1
[FFPlayer @ 0x151561810] player-opts : overlay-format               = fcc-i420
[FFPlayer @ 0x151561810] player-opts : max-fps                      = 30
[FFPlayer @ 0x151561810] player-opts : framedrop                    = 0
[FFPlayer @ 0x151561810] player-opts : videotoolbox-max-frame-width = 960
[FFPlayer @ 0x151561810] player-opts : videotoolbox                 = 0
[FFPlayer @ 0x151561810] player-opts : video-pictq-size             = 3
[FFPlayer @ 0x151561810] format-opts : ijkinject-opaque             = 5659779616
[FFPlayer @ 0x151561810] format-opts : user-agent                   = ijkplayer
[FFPlayer @ 0x151561810] format-opts : auto_convert                 = 0
[FFPlayer @ 0x151561810] format-opts : http-tcp-hook                = ijktcphook
[FFPlayer @ 0x151561810] format-opts : timeout                      = 30000000
[FFPlayer @ 0x151561810] format-opts : reconnect                    = 1
[FFPlayer @ 0x151561810] format-opts : safe                         = 0
[FFPlayer @ 0x151561810] codec-opts  : skip_frame                   = 0
[FFPlayer @ 0x151561810] codec-opts  : skip_loop_filter             = 0
===================
ijkmp_prepare_async()=0
ijkmp_start()
ijkmp_start()=-3
[ijktcphook @ 0x15161a330] ijktcphook tcp://192.168.4.26:43710 (remain)
[http @ 0x151592ea0] request: GET /%E7%BE%8E%E5%A5%B3%E7%83%A4%E9%B8%AD.mp4 HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=0-

Connection: close

Host: 192.168.4.26:43710

Icy-MetaData: 1

[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1501a6200] Format mov,mp4,m4a,3gp,3g2,mj2 probed with size=2048 and score=100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1501a6200] ISO: File Type Major Brand: mp42
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1501a6200] rfps: 29.833333 0.016611
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1501a6200] rfps: 29.833333 0.016611
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1501a6200] rfps: 29.916667 0.002568
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1501a6200] rfps: 29.916667 0.010797
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1501a6200] rfps: 30.000000 0.000900
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1501a6200] rfps: 60.000000 0.003602
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1501a6200] rfps: 120.000000 0.014407
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1501a6200] rfps: 29.970030 0.000075
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1501a6200] rfps: 59.940060 0.000301
Option safe not found.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1501a6200] Before avformat_find_stream_info() pos: 160280 bytes read:163840 seeks:0
2016-07-27 14:58:34.815 BoBoPlayer4.0[1172:640707] _BSMachError: (os/kern) invalid capability (20)
2016-07-27 14:58:34.817 BoBoPlayer4.0[1172:640707] _BSMachError: (os/kern) invalid name (15)
[h264 @ 0x150252800] no picture 
[aac @ 0x150a21000] skip whole frame, skip left: 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1501a6200] All info found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1501a6200] After avformat_find_stream_info() pos: 1377746 bytes read:1379152 seeks:0 frames:16
[FFPlayer @ 0x151561810] max_frame_duration: 10.000
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'http://192.168.4.26:43710/%E7%BE%8E%E5%A5%B3%E7%83%A4%E9%B8%AD.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41M4V M4A isomavc1iso2
    creation_time   : 2014-09-04 07:02:08
    encoder         : x264 0.128.2216+688+32 a17ff54 tMod [8-bit@4:2:0 X86_64]
  Duration: 00:03:31.18, start: 0.021333, bitrate: 36126 kb/s
    Stream #0:0(und), 15, 1/1000000000: Video: h264, 4 reference frames (avc1 / 0x31637661), yuv420p(tv, bt709/unknown/unknown, left), 3840x2160 [SAR 1:1 DAR 16:9], 1/2000000000, 35956 kb/s, 29.97 fps, 29.97 tbr, 1000000000.00 tbn, 2000000000.00 tbc (default)
    Metadata:
      creation_time   : 2014-09-04 07:02:08
      handler_name    : L-SMASH Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(und), 1, 1/48000: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 164 kb/s (default)
    Metadata:
      creation_time   : 2014-09-04 07:02:08
      handler_name    : L-SMASH iTunes Metadata Handler
[ffplay_abuffer @ 0x1511dfae0] Setting 'sample_rate' to value '48000'
[ffplay_abuffer @ 0x1511dfae0] Setting 'sample_fmt' to value 'fltp'
[ffplay_abuffer @ 0x1511dfae0] Setting 'channels' to value '2'
[ffplay_abuffer @ 0x1511dfae0] Setting 'time_base' to value '1/48000'
[ffplay_abuffer @ 0x1511dfae0] Setting 'channel_layout' to value '0x3'
[ffplay_abuffer @ 0x1511dfae0] tb:1/48000 samplefmt:fltp samplerate:48000 chlayout:0x3
[ffplay_abuffersink @ 0x15141b330] auto-inserting filter 'auto-inserted resampler 0' between the filter 'ffplay_abuffer' and the filter 'ffplay_abuffersink'
[AVFilterGraph @ 0x1515551d0] query_formats: 2 queried, 0 merged, 3 already done, 0 delayed
[auto-inserted resampler 0 @ 0x151567bd0] [SWR @ 0x1504b6800] Using fltp internally between filters
[auto-inserted resampler 0 @ 0x151567bd0] ch:2 chl:stereo fmt:fltp r:48000Hz -> ch:2 chl:stereo fmt:s16 r:48000Hz
aout_open_audio()
[FFPlayer @ 0x151561810] AudioCodec: avcodec, aac
aout_pause_audio(0)
vtb fail!!! switch to ffmpeg decode!!!! 
[FFPlayer @ 0x151561810] VideoCodec: avcodec, h264
[FFPlayer @ 0x151561810] fps: 29.970120 (normal)
[IJKFFMoviePlayerController.m:807行] FFP_MSG_VIDEO_DECODER_OPEN: false

[FFPlayer @ 0x151561810] fps: 29.970030 (normal)
ijkmp_get_msg: FFP_MSG_PREPARED
[aac @ 0x150a21000] skip whole frame, skip left: 0
[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: start
aout_pause_audio(1)
[IJKFFMoviePlayerController.m:745行] FFP_MSG_VIDEO_SIZE_CHANGED: 3840, 2160

[IJKFFMoviePlayerController.m:753行] FFP_MSG_SAR_CHANGED: 1, 1

[IJKFFMoviePlayerController.m:641行] FFP_MSG_PREPARED:

ijkmp_get_meta_l
ijkmp_get_meta_l()=void
[IJKFFMoviePlayerController.m:693行] fps in meta 29.970120

[BBIJKPlayerVC.m:2860行] 211.178000
[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2889行] moviePlayBackStateDidChange 4: seeking
ijkmp_seek_to(74000)
ijkmp_seek_to(74000)=0
[BBIJKPlayerVC.m:2933行] 74
[BBIJKPlayerVC.m:2934行] 74.000000 211.178000
[BBIJKPlayerVC.m:2935行] mediaIsPreparedToPlayDidChange

[BBIJKPlayerVC.m:3040行] number=0
[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2775行] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2889行] moviePlayBackStateDidChange 4: seeking
ijkmp_get_msg: FFP_REQ_SEEK
[FFPlayer @ 0x151561810] stream_seek 74000000(74000) + -21333, 
[FFPlayer @ 0x151561810] ijkmp_get_msg: FFP_REQ_SEEK: seek to 74000
[h264 @ 0x155a79200] no picture 
[h264 @ 0x1509e0200] no picture 
Audio frame changed from rate:48000 ch:2 fmt:fltp layout:stereo serial:-1 to rate:48000 ch:2 fmt:fltp layout:stereo serial:1
[IJKFFMoviePlayerController.m:761行] FFP_MSG_BUFFERING_START:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2805行] loadStateDidChange: MPMovieLoadStateStalled: 4

[ffplay_abuffer @ 0x15141b330] Setting 'sample_rate' to value '48000'
[ffplay_abuffer @ 0x15141b330] Setting 'sample_fmt' to value 'fltp'
[ffplay_abuffer @ 0x15141b330] Setting 'channels' to value '2'
[ffplay_abuffer @ 0x15141b330] Setting 'time_base' to value '1/48000'
[ffplay_abuffer @ 0x15141b330] Setting 'channel_layout' to value '0x3'
[ffplay_abuffer @ 0x15141b330] tb:1/48000 samplefmt:fltp samplerate:48000 chlayout:0x3
[ffplay_abuffersink @ 0x151737620] auto-inserting filter 'auto-inserted resampler 0' between the filter 'ffplay_abuffer' and the filter 'ffplay_abuffersink'
[AVFilterGraph @ 0x151409b90] query_formats: 2 queried, 0 merged, 3 already done, 0 delayed
[auto-inserted resampler 0 @ 0x151490510] [SWR @ 0x150d39600] Using fltp internally between filters
[auto-inserted resampler 0 @ 0x151490510] ch:2 chl:stereo fmt:fltp r:48000Hz -> ch:2 chl:stereo fmt:s16 r:48000Hz
Video frame changed from size:0x0 format:none serial:-1 to size:3840x2160 format:yuv420p serial:1
[ffplay_buffer @ 0x151738c70] Setting 'video_size' to value '3840x2160'
[ffplay_buffer @ 0x151738c70] Setting 'pix_fmt' to value '0'
[ffplay_buffer @ 0x151738c70] Setting 'time_base' to value '1/1000000000'
[ffplay_buffer @ 0x151738c70] Setting 'pixel_aspect' to value '1/1'
[ffplay_buffer @ 0x151738c70] Setting 'frame_rate' to value '30000/1001'
[ffplay_buffer @ 0x151738c70] w:3840 h:2160 pixfmt:yuv420p tb:1/1000000000 fr:30000/1001 sar:1/1 sws_param:
[ffplay_crop @ 0x151714800] Setting 'out_w' to value 'floor(in_w/2)*2'
[ffplay_crop @ 0x151714800] Setting 'out_h' to value 'floor(in_h/2)*2'
[AVFilterGraph @ 0x1517385e0] query_formats: 3 queried, 2 merged, 0 already done, 0 delayed
[ffplay_crop @ 0x151714800] w:3840 h:2160 sar:1/1 -> w:3840 h:2160 sar:1/1
SDL_VoutFFmpeg_CreateOverlay(w=3840, h=2160, fmt=I420(0x30323449, dp=0x1515acd40)
Video: first frame decoded
[IJKFFMoviePlayerController.m:745行] FFP_MSG_VIDEO_SIZE_CHANGED: 3840, 2160

ijkmp_get_msg: FFP_MSG_SEEK_COMPLETE
[IJKFFMoviePlayerController.m:801行] FFP_MSG_SEEK_COMPLETE:

[ijktcphook @ 0x15148c650] ijktcphook tcp://192.168.4.26:43710 (remain)
[http @ 0x151592ea0] request: GET /%E7%BE%8E%E5%A5%B3%E7%83%A4%E9%B8%AD.mp4 HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=351667115-

Connection: close

Host: 192.168.4.26:43710

Icy-MetaData: 1

SDL_VoutFFmpeg_CreateOverlay(w=3840, h=2160, fmt=I420(0x30323449, dp=0x1515acd40)
[IJKFFMoviePlayerController.m:745行] FFP_MSG_VIDEO_SIZE_CHANGED: 3840, 2160

[h264 @ 0x155a79200] no picture 
[h264 @ 0x1509e0200] no picture 
Video frame changed from size:3840x2160 format:yuv420p serial:1 to size:3840x2160 format:yuv420p serial:2
[ffplay_buffer @ 0x1517b0200] Setting 'video_size' to value '3840x2160'
[ffplay_buffer @ 0x1517b0200] Setting 'pix_fmt' to value '0'
[ffplay_buffer @ 0x1517b0200] Setting 'time_base' to value '1/1000000000'
[ffplay_buffer @ 0x1517b0200] Setting 'pixel_aspect' to value '1/1'
[ffplay_buffer @ 0x1517b0200] Setting 'frame_rate' to value '30000/1001'
[ffplay_buffer @ 0x1517b0200] w:3840 h:2160 pixfmt:yuv420p tb:1/1000000000 fr:30000/1001 sar:1/1 sws_param:
[ffplay_crop @ 0x151738c70] Setting 'out_w' to value 'floor(in_w/2)*2'
[ffplay_crop @ 0x151738c70] Setting 'out_h' to value 'floor(in_h/2)*2'
[AVFilterGraph @ 0x15150f6b0] query_formats: 3 queried, 2 merged, 0 already done, 0 delayed
[ffplay_crop @ 0x151738c70] w:3840 h:2160 sar:1/1 -> w:3840 h:2160 sar:1/1
SDL_VoutFFmpeg_CreateOverlay(w=3840, h=2160, fmt=I420(0x30323449, dp=0x1515acd40)
[IJKFFMoviePlayerController.m:745行] FFP_MSG_VIDEO_SIZE_CHANGED: 3840, 2160

[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: end
aout_pause_audio(0)
[IJKSDLGLView.m:490行] OK use I420 GL renderer
[IJKSDLGLView.m:586行] OK setup GL programm
[IJKFFMoviePlayerController.m:771行] FFP_MSG_BUFFERING_END:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2775行] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2875行] moviePlayBackStateDidChange 1: playing
[IJKFFMoviePlayerController.m:814行] FFP_MSG_VIDEO_RENDERING_START:

Audio frame changed from rate:48000 ch:2 fmt:fltp layout:stereo serial:1 to rate:48000 ch:2 fmt:fltp layout:stereo serial:2
[ffplay_abuffer @ 0x151737620] Setting 'sample_rate' to value '48000'
[ffplay_abuffer @ 0x151737620] Setting 'sample_fmt' to value 'fltp'
[ffplay_abuffer @ 0x151737620] Setting 'channels' to value '2'
[ffplay_abuffer @ 0x151737620] Setting 'time_base' to value '1/48000'
[ffplay_abuffer @ 0x151737620] Setting 'channel_layout' to value '0x3'
[ffplay_abuffer @ 0x151737620] tb:1/48000 samplefmt:fltp samplerate:48000 chlayout:0x3
[ffplay_abuffersink @ 0x151490510] auto-inserting filter 'auto-inserted resampler 0' between the filter 'ffplay_abuffer' and the filter 'ffplay_abuffersink'
[AVFilterGraph @ 0x151409b90] query_formats: 2 queried, 0 merged, 3 already done, 0 delayed
[auto-inserted resampler 0 @ 0x15141b330] [SWR @ 0x150d39600] Using fltp internally between filters
[auto-inserted resampler 0 @ 0x15141b330] ch:2 chl:stereo fmt:fltp r:48000Hz -> ch:2 chl:stereo fmt:s16 r:48000Hz
avcodec/Audio: first frame decoded
[IJKFFMoviePlayerController.m:821行] FFP_MSG_AUDIO_RENDERING_START:

[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: start
aout_pause_audio(1)
[IJKFFMoviePlayerController.m:761行] FFP_MSG_BUFFERING_START:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2805行] loadStateDidChange: MPMovieLoadStateStalled: 4

[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: end
aout_pause_audio(0)
[IJKFFMoviePlayerController.m:771行] FFP_MSG_BUFFERING_END:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2775行] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2875行] moviePlayBackStateDidChange 1: playing
[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: start
aout_pause_audio(1)
[IJKFFMoviePlayerController.m:761行] FFP_MSG_BUFFERING_START:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2805行] loadStateDidChange: MPMovieLoadStateStalled: 4

[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: end
aout_pause_audio(0)
[IJKFFMoviePlayerController.m:771行] FFP_MSG_BUFFERING_END:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2775行] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2875行] moviePlayBackStateDidChange 1: playing
[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: start
aout_pause_audio(1)
[IJKFFMoviePlayerController.m:761行] FFP_MSG_BUFFERING_START:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2805行] loadStateDidChange: MPMovieLoadStateStalled: 4

[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: end
aout_pause_audio(0)
[IJKFFMoviePlayerController.m:771行] FFP_MSG_BUFFERING_END:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2775行] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2875行] moviePlayBackStateDidChange 1: playing
[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: start
aout_pause_audio(1)
[IJKFFMoviePlayerController.m:761行] FFP_MSG_BUFFERING_START:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2805行] loadStateDidChange: MPMovieLoadStateStalled: 4

[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: end
aout_pause_audio(0)
[IJKFFMoviePlayerController.m:771行] FFP_MSG_BUFFERING_END:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2775行] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2875行] moviePlayBackStateDidChange 1: playing
[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: start
aout_pause_audio(1)
[IJKFFMoviePlayerController.m:761行] FFP_MSG_BUFFERING_START:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2805行] loadStateDidChange: MPMovieLoadStateStalled: 4

[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: end
aout_pause_audio(0)
[IJKFFMoviePlayerController.m:771行] FFP_MSG_BUFFERING_END:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2775行] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2875行] moviePlayBackStateDidChange 1: playing
[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: start
aout_pause_audio(1)
[IJKFFMoviePlayerController.m:761行] FFP_MSG_BUFFERING_START:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2805行] loadStateDidChange: MPMovieLoadStateStalled: 4

[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: end
aout_pause_audio(0)
[IJKFFMoviePlayerController.m:771行] FFP_MSG_BUFFERING_END:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2775行] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2875行] moviePlayBackStateDidChange 1: playing
[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: start
aout_pause_audio(1)
[IJKFFMoviePlayerController.m:761行] FFP_MSG_BUFFERING_START:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2805行] loadStateDidChange: MPMovieLoadStateStalled: 4

[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: end
aout_pause_audio(0)
[IJKFFMoviePlayerController.m:771行] FFP_MSG_BUFFERING_END:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2775行] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2875行] moviePlayBackStateDidChange 1: playing
[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: start
aout_pause_audio(1)
[IJKFFMoviePlayerController.m:761行] FFP_MSG_BUFFERING_START:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2805行] loadStateDidChange: MPMovieLoadStateStalled: 4

[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: end
aout_pause_audio(0)
[IJKFFMoviePlayerController.m:771行] FFP_MSG_BUFFERING_END:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2775行] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2875行] moviePlayBackStateDidChange 1: playing
[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: start
aout_pause_audio(1)
[IJKFFMoviePlayerController.m:761行] FFP_MSG_BUFFERING_START:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2805行] loadStateDidChange: MPMovieLoadStateStalled: 4

[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: end
aout_pause_audio(0)
[IJKFFMoviePlayerController.m:771行] FFP_MSG_BUFFERING_END:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2775行] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2875行] moviePlayBackStateDidChange 1: playing
[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: start
aout_pause_audio(1)
[IJKFFMoviePlayerController.m:761行] FFP_MSG_BUFFERING_START:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2805行] loadStateDidChange: MPMovieLoadStateStalled: 4

[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: end
aout_pause_audio(0)
[IJKFFMoviePlayerController.m:771行] FFP_MSG_BUFFERING_END:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2775行] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2875行] moviePlayBackStateDidChange 1: playing
[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: start
aout_pause_audio(1)
[IJKFFMoviePlayerController.m:761行] FFP_MSG_BUFFERING_START:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2805行] loadStateDidChange: MPMovieLoadStateStalled: 4

[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: end
aout_pause_audio(0)
[IJKFFMoviePlayerController.m:771行] FFP_MSG_BUFFERING_END:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2775行] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2875行] moviePlayBackStateDidChange 1: playing
[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: start
aout_pause_audio(1)
[IJKFFMoviePlayerController.m:761行] FFP_MSG_BUFFERING_START:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2805行] loadStateDidChange: MPMovieLoadStateStalled: 4

[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: end
aout_pause_audio(0)
[IJKFFMoviePlayerController.m:771行] FFP_MSG_BUFFERING_END:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2775行] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2875行] moviePlayBackStateDidChange 1: playing
[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: start
aout_pause_audio(1)
[IJKFFMoviePlayerController.m:761行] FFP_MSG_BUFFERING_START:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2805行] loadStateDidChange: MPMovieLoadStateStalled: 4

[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: end
aout_pause_audio(0)
[IJKFFMoviePlayerController.m:771行] FFP_MSG_BUFFERING_END:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2775行] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2875行] moviePlayBackStateDidChange 1: playing
[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: start
aout_pause_audio(1)
[IJKFFMoviePlayerController.m:761行] FFP_MSG_BUFFERING_START:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2805行] loadStateDidChange: MPMovieLoadStateStalled: 4

[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: end
aout_pause_audio(0)
[IJKFFMoviePlayerController.m:771行] FFP_MSG_BUFFERING_END:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2775行] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2875行] moviePlayBackStateDidChange 1: playing
[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: start
aout_pause_audio(1)
[IJKFFMoviePlayerController.m:761行] FFP_MSG_BUFFERING_START:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2805行] loadStateDidChange: MPMovieLoadStateStalled: 4

[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: end
aout_pause_audio(0)
[IJKFFMoviePlayerController.m:771行] FFP_MSG_BUFFERING_END:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2775行] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2875行] moviePlayBackStateDidChange 1: playing
[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: start
aout_pause_audio(1)
[IJKFFMoviePlayerController.m:761行] FFP_MSG_BUFFERING_START:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2805行] loadStateDidChange: MPMovieLoadStateStalled: 4

[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: end
aout_pause_audio(0)
[IJKFFMoviePlayerController.m:771行] FFP_MSG_BUFFERING_END:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2775行] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2875行] moviePlayBackStateDidChange 1: playing
[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: start
aout_pause_audio(1)
[IJKFFMoviePlayerController.m:761行] FFP_MSG_BUFFERING_START:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2805行] loadStateDidChange: MPMovieLoadStateStalled: 4

[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: end
aout_pause_audio(0)
[IJKFFMoviePlayerController.m:771行] FFP_MSG_BUFFERING_END:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2775行] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2875行] moviePlayBackStateDidChange 1: playing
[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: start
aout_pause_audio(1)
[IJKFFMoviePlayerController.m:761行] FFP_MSG_BUFFERING_START:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2805行] loadStateDidChange: MPMovieLoadStateStalled: 4

[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: end
aout_pause_audio(0)
[IJKFFMoviePlayerController.m:771行] FFP_MSG_BUFFERING_END:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2775行] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[BBIJKPlayerVC.m:2866行] moviePlayStateDidChange

[BBIJKPlayerVC.m:2875行] moviePlayBackStateDidChange 1: playing
[FFPlayer @ 0x151561810] ffp_toggle_buffering_l: start
aout_pause_audio(1)
[IJKFFMoviePlayerController.m:761行] FFP_MSG_BUFFERING_START:

[BBIJKPlayerVC.m:2765行] loadStateDidChange

[BBIJKPlayerVC.m:2805行] loadStateDidChange: MPMovieLoadStateStalled: 4

**Comment by yeshibuzhong** [comment]
使用硬解可以好很多,但是有些影片不是MP4格式的,必须用软解,请大神指点

**Comment by bbcallen** [comment]
It's not possible to play 4k well with sw decoder.

**Comment by yeshibuzhong** [comment]
thanks

**Comment by ctiao** [comment]
#1107
