### ISSUE TITLE
can not play rtsp?

### ISSUE THREAD

**Issue by sandyCK** [Bilibili/ijkplayer#1737]
I followed your "Build IOS" steps with nothing wrong happened, finally open the ijkPlayerDemo, change the method "onClickPlayButton" in IJKDemoInputURLViewController.m to 

NSURL *url = [NSURL URLWithString:self.textView.text];
    NSString *scheme = [[url scheme] lowercaseString];
    if ([scheme isEqualToString:@"rtsp"]) {
        [IJKVideoViewController presentFromViewController:self withTitle:[NSString stringWithFormat:@"URL: %@", url] URL:url completion:^{
            //            [self.navigationController popViewControllerAnimated:NO];
        }];
    }

still can not play rtsp.

what else should I do?

**Comment by bbcallen** [comment]
RTSP is disabled by default.
Take a look at section "If you prefer more codec/format" in README

**Comment by Xiahaiquan** [comment]
我以为可以呢，
