### ISSUE TITLE
Seek forward does not work?

### ISSUE THREAD

**Issue by brystel** [Bilibili/ijkplayer#175]
Hello,

When I am trying to seek forward local video, the video instead of seeking plays from this same position or from backward position. 

For example when I try to seek forward using:
```
int currentPosition = player.getCurrentPosition();
int positionToSeek = currentPosition + 5000;

if (positionToSeek < player.getDuration()) {
player.seekTo(positionToSeek);
}
```

Player seeking to current position or sometimes to the position that it was before.
If I wait longer after seek forward and repeat the action, sometimes seek works well.
If I try to seek to position: ```currentPosition + 10000``` seek also usually working.

If I seek backward all seems to be ok.

**Comment by bbcallen** [comment]
No idea, any more information?

**Comment by brystel** [comment]
This problem also happens in HLS.
Is it possible to precisely seek to position in local video / hls that I want?

**Comment by bbcallen** [comment]
No, the seeked position must be a key-frame.
But you can decode and drop frames before you want.

**Comment by Scottie-M** [comment]
If it is not possible to seek to a precise time in ms, only key frames, can playback speed be adjusted? Before I compile the player, does the VideoView have ability to decode and drop frames to reach a given position?

I need to keep 2 players in sync across a network by either adjusting playback speed  or seeking to precise times, would this player be capable?

**Comment by bbcallen** [comment]
No. You must modify the ff_ffplay.c to meet your need. 
AV_SYNC_EXTERNAL_CLOCK may help a little.

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
