### ISSUE TITLE
unknown type name 'AVBSFContext' even after adding avcodec.h in ff_ffplay_def.h

### ISSUE THREAD

**Issue by liwei46** [Bilibili/ijkplayer#1755]
/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ff_ffplay_def.h:384:5: error: unknown type name 'AVBSFContext'
     AVBSFContext *bsf;
     ^
In file included from ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.h:28:0,
                 from  ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c

Hi,

I try to use a bsf filter,  and add a      AVBSFContext *bsf; in the VideoState struct, but I get above error. I already add the libavcodec/avcodec.h headfile, but it seems not have any effect. 

Are there other setting I need to modify? Thanks.

Regards,

**Comment by bbcallen** [comment]
update ffmpeg with sh init-android.sh and clean, rebuild.

**Comment by liwei46** [comment]
yes, it works. thanks a lot. Best wishes for your great work!
