### ISSUE TITLE
Put Now Playing Info on iOS?

### ISSUE THREAD

**Issue by AlejandroRuiz** [Bilibili/ijkplayer#1756]
Im trying to put the Now Playing info into the iOS lock screen by using MPNowPlayingInfoCenter.DefaultCenter.NowPlaying but without success did the library has a way to do this?

![1a](https://cloud.githubusercontent.com/assets/1253565/17238202/4f1bd25c-551f-11e6-9714-9070a404d6db.jpg)

**Comment by xinzhengzhang** [comment]
See reference [MPNowPlayingInfoCenter](https://developer.apple.com/library/ios/documentation/MediaPlayer/Reference/MPNowPlayingInfoCenter_Class/) @AlejandroRuiz

**Comment by AlejandroRuiz** [comment]
@xinzhengzhang  it was an issue on my side seems that I was missing to set MPNowPlayingInfoPropertyPlaybackRate property after setting this value with "1" everything is working fine
