### ISSUE TITLE
播放器销毁，声音还有

### ISSUE THREAD

**Issue by xy13663015647** [Bilibili/ijkplayer#1760]
播放RTSP流之后，把播放页销毁，可是设备一直还有播放时的声音，除非退出程序，声音才会消失，这是怎么回事？

**Comment by ctiao** [comment]
what does "把播放页销毁" mean ?

**Comment by xy13663015647** [comment]
我现在的问题是，播放器出现后，内存增长，我停止播放，播放器所在的控制器已经销毁，可是内存并没有降下去，如果再加载播放器，内存还会再次升高。我想播放器所在的控制器销毁了之后，播放器也就能够不占资源了

**Comment by ctiao** [comment]
如果你不需要再使用播放器
ios调用 播放器.shutdown
android 调用播放器.release

**Comment by xy13663015647** [comment]
谢谢，内存确实释放了
