### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by asdzheng** [Bilibili/ijkplayer#1763]
tv.danmaku.ijk.media.player.IjkMediaPlayer._setDataSource(Native Method)
tv.danmaku.ijk.media.player.IjkMediaPlayer.setDataSource(IjkMediaPlayer.java:383) tv.danmaku.ijk.media.player.IjkMediaPlayer.setDataSource(IjkMediaPlayer.java:408)
tv.danmaku.ijk.media.player.IjkMediaPlayer.setDataSource(IjkMediaPlayer.java:359)
tv.danmaku.ijk.media.player.IjkMediaPlayer.setDataSource(IjkMediaPlayer.java:300) com.jjcj.view.UniversalVideoView.UniversalVideoView.h(UniversalVideoView.java:334)
com.jjcj.view.UniversalVideoView.UniversalVideoView.q(UniversalVideoView.java:48)
com.jjcj.view.UniversalVideoView.o.surfaceCreated(UniversalVideoView.java:627)
android.view.SurfaceView.updateWindow(SurfaceView.java:588)
android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:243)
android.view.View.dispatchWindowVisibilityChanged(View.java:8751)

this error show in the bugly

**Comment by ctiao** [comment]
You should call reset() before setDataSource(...) to get the mediaplayer back to the idle state.  And It is not recommended to setDataSource(...) inside onWindowVisibilityChanged.

**Comment by asdzheng** [comment]
Thanks, it is my fault...
