### ISSUE TITLE
enable resolution change 实现的代码问题

### ISSUE THREAD

**Issue by CzachQ** [Bilibili/ijkplayer#1766]
该comment问题仍存在，目前最后两个comment的问题和此处相同
---
https://github.com/Bilibili/ijkplayer/blob/48cf5a2aa7b6c81bfd8ff4a4dc41e566befca689/ijkmedia/ijkplayer/android/pipeline/ffpipenode_android_mediacodec_vdec.c#L435
在这一if判断中对mediacodec_handle_resolution_change这一新特性的选项进行了处理

第450行
avcodec_parameters_to_context(new_avctx, opaque->codecpar);
这一方法包括了
`new_avctx->width = opaque->codecpar->width;`
`new_avctx->height = opaque->codecpar->height;`
这两个步骤

为什么在475-476行会有如下判断呢：
`if (opaque->codecpar->width  != new_avctx->width &&`
`                        opaque->codecpar->height != new_avctx->height)`
之间的代码没看到有对new_avctx->width/height修改的步骤

求解
@bbcallen

**Comment by CzachQ** [comment]
后来又有了发现

461行
`ret = avcodec_open2(new_avctx, codec, &codec_opts);`
在avcodec_open2这一方法中
有如下代码：
`if (avctx->coded_width && avctx->coded_height)`
`      ret = ff_set_dimensions(avctx, avctx->coded_width, avctx->coded_height);`
		 ` else if (avctx->width && avctx->height)`
			` ret = ff_set_dimensions(avctx, avctx->width, avctx->height);`

450行方法avcodec_parameters_to_context对width/height赋值而不是coded_width/height
所以执行else if 中的语句

其中ff_set_dimensions方法为：
`int ff_set_dimensions(AVCodecContext *s, int width, int height)`
` {`
		      `int ret = av_image_check_size(width, height, 0, s);`
		     ` if (ret < 0)`
			`  width = height = 0;`
		    `  s->coded_width  = width;`
		    `  s->coded_height = height;`
		`      s->width        = AV_CEIL_RSHIFT(width,  s->lowres);`
		 `     s->height       = AV_CEIL_RSHIFT(height, s->lowres);`
		  `    return ret;`
`		  }`

其中AV_CEIL_RSHIFT的定义为
`#define AV_CEIL_RSHIFT(a,b) (!av_builtin_constant_p(b) ? -((-(a)) >> (b)) \
				                                          : ((a) + (1<<(b)) - 1) >> (b))`
测试这两种表达式得到的结果是一致的
所以是这里把width/height修改了么
那么这个AV_CEIL_RSHIFT是对数值做了什么改动呢  没明白

**Comment by CzachQ** [comment]
同时求解
size_data = av_packet_get_side_data(avpkt, AV_PKT_DATA_NEW_EXTRADATA, &size_data_size);

if (size_data && size_data_size > AV_INPUT_BUFFER_PADDING_SIZE)

这里size_data、size_data_size得到的是什么数据呢？size_data_size为什么要和AV_INPUT_BUFFER_PADDING_SIZE进行比较？

**Comment by CzachQ** [comment]
问题总结
---

代码页：
https://github.com/Bilibili/ijkplayer/blob/48cf5a2aa7b6c81bfd8ff4a4dc41e566befca689/ijkmedia/ijkplayer/android/pipeline/ffpipenode_android_mediacodec_vdec.c#L435

1.
441行
if (size_data && size_data_size > AV_INPUT_BUFFER_PADDING_SIZE) 
这一判断中的size_data和 size_data_size是什么含义？

2.
这段代码是实现了源分辨率的转换时本地的分辨率变化
还是根据s->lowres在本地按比例压缩分辨率？

3.
#define AV_CEIL_RSHIFT(a,b) (!av_builtin_constant_p(b) ? -((-(a)) >> (b)) \ : ((a) + (1<<(b)) - 1) >> (b))
两种表达式结果一致为什么要写成两种呢？

@ctiao @bbcallen   谢谢！

**Comment by bbcallen** [comment]
1. They are defined by ffmpeg.
2. It's defined by ffmpeg.
3. It's implemented by ffmpeg.

**Comment by CzachQ** [comment]
ok thanks
还是想问一下
0.6.0版本的enable resolution change具体
指的是本地视频解码会根据live stream的resolution变化随时更新解码的resolution
还是在本地可以根据lowres数值对live stream的resolution进行压缩再解码

@bbcallen

**Comment by CzachQ** [comment]
感觉有些情况下不能执行重设解码器的代码呢

还是第1&2个comment里面的问题
如果在avcodec_open2里执行的时候lowres值为0
则coded_height/width和height/width值一样均为原来的avctx->height

那么下面的判断
if (opaque->codecpar->width != new_avctx->width &&opaque->codecpar->height != new_avctx->height)
结果就会为false

导致
opaque->aformat_need_recreate = true;
ffpipeline_set_surface_need_reconfigure_l(pipeline, true);
这两句代码不能执行
 
@bbcallen 
打扰很多次抱歉了，求解

**Comment by CzachQ** [comment]
刚看到
avcodec_open2方法里有注释
only call ff_set_dimensions() for non H.264/VP6F/DXV codecs so as not to overwrite previously setup dimensions 
然后细看了一下代码确实是在H.264下没有进行跟lowres有关的操作

所以opaque->codecpar->width/heigth和 new_avctx->width/height是怎么才变成不相等的呢？

@bbcallen

**Comment by CzachQ** [comment]
后来研究代码解决了
有想了解的可以看blog
http://blog.csdn.net/czach/article/details/52094151

thanks
