### ISSUE TITLE
iOS如何不完全占用音频

### ISSUE THREAD

**Issue by zhaoxiaobao** [Bilibili/ijkplayer#1775]
其他app也用到音频时，可以共用吗？而不是只能被ijk完全占用音频。

**Comment by xinzhengzhang** [comment]
@zhaoxiaobao 
Change audio output from `IJKSDLAudioQueueController` to `IJKSDLAudioUnitController`.
[AudioUnit](https://developer.apple.com/library/mac/documentation/AudioUnit/Reference/AudioUnit_Framework/index.html#//apple_ref/doc/uid/TP40007295)

**Comment by zhaoxiaobao** [comment]
@xinzhengzhang   3q

**Comment by yuesehanpangmailang** [comment]
@zhaoxiaobao 请问你修改成功了吗，是如果改的，能提供一份源码给我吗？
