### ISSUE TITLE
如何实现重播呢？

### ISSUE THREAD

**Issue by easytome** [Bilibili/ijkplayer#1777]
刚播完一次的视频，如何实现重播，现在都是从头重新加载视频，之前的缓存没有么

**Comment by ctiao** [comment]
现在使用的内存缓存，只会保存播放进度前一部分和后一部分的内存缓存。

**Comment by ajjing** [comment]
在播放结束状态时，直接setplayTime为0。不知道有没有更好的办法~

**Comment by 6ag** [comment]
我目前也是 `setplayTime = 0`

**Comment by xinzhengzhang** [comment]
See [Cache](https://www.ffmpeg.org/ffmpeg-protocols.html#cache)
