### ISSUE TITLE
Looping video

### ISSUE THREAD

**Issue by erema** [Bilibili/ijkplayer#178]
I have a little bit delay in the end of a video, how can I resolve it?

**Comment by erema** [comment]
I see. I found in ff_ffplay.c SDL_Delay(1000) after eof, but I don't understand what for this delay?

**Comment by bbcallen** [comment]
SDL_Delay(1000) is for polling in case of restart the player which is completed.
(kind of ugly, :)

**Comment by erema** [comment]
Thank you! I have another question. How can I shutdown player in the background thread? now it happens in the main thread. Thanks for help.

**Comment by bbcallen** [comment]
For android, call stop()/release() in the background thread should be fine.

ijkplayer tries to behave the same as android.media.MediaPlayer, so stop/release() are blocked.

**Comment by erema** [comment]
but for ios?

**Comment by bbcallen** [comment]
For some thread issues related to OpenGL, it's better to release resources in main thread.

Mostly, block happens in ffp_wait_stop_l(), you can wrap some API to call it at background, and then, shutdown ijkplayer. But take care of multiple instance issue.

**Comment by erema** [comment]
may be you have some ideas, how do that?

**Comment by bbcallen** [comment]
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0),^{
     [mp stop]; // this call is blocked for a while
     [mp shutdown]; // this call dispatches some stuff to main queue, but doesn't block for long
}
