### ISSUE TITLE
代码问题 jsurface的重新配置

### ISSUE THREAD

**Issue by CzachQ** [Bilibili/ijkplayer#1781]
https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/android/pipeline/ffpipenode_android_mediacodec_vdec.c#L560
这段代码中
566行 得到new_surface=(*env)->NewGlobalRef(env, pipeline->opaque->jsurface);
587行 ret = reconfigure_codec_l(env, node, new_surface);
其中包含了node->opaque->jsurface=new_surface的操作

不过它们的前提是node->opaque->jsurface != new_surface
之前的代码没有看到对new_surface指向的node->opaque->pipeline->opaque->jsurface的改动
那么这里的不同是何时发生的呢？

@bbcallen @ctiao 谢谢！

**Comment by ctiao** [comment]
new_surface还可能是NULL

**Comment by CzachQ** [comment]
3Q

不太理解IJKFF_Pipenode和IJKFF_Pipeline之间的关系呢
pipenode中含有pipeline
pipeline里有些属性名称是和pipenode重复的
所以它们之间有什么联系呢？
为什么重建surface需要从node->opaque->pipeline->opaque->jsurface获取？

**Comment by CzachQ** [comment]
如果这里取到null
587行执行
ret = reconfigure_codec_l(env, node, new_surface);

在reconfigure_codec_l(JNIEnv *env, IJKFF_Pipenode *node, jobject new_surface)中
```
if (new_surface) {
        opaque->jsurface = (*env)->NewGlobalRef(env, new_surface);
        if (J4A_ExceptionCheck__catchAll(env) || !opaque->jsurface)
            goto fail;
} else {
        opaque->jsurface = NULL;
}
```
opaque->jsurface 被赋值为null

之后依旧在reconfigure_codec_l方法中
```
amc_ret = SDL_AMediaCodec_configure_surface(env, opaque->acodec, opaque->input_aformat, opaque->jsurface, NULL, 0);
```
在 SDL_AMediaCodec_configure_surface中
(https://github.com/Bilibili/ijkplayer/blob/ae80ea4d9d0506f37c2433c08396362dcf020cb7/ijkmedia/ijksdl/android/ijksdl_codec_android_mediacodec.c#L77)
有代码
```
sdl_amedia_status_t ret = acodec->func_configure_surface(env, acodec, aformat, android_surface, crypto, flags);
```
此处的android_surface就是之前的opaque->jsurface即为null

查到
>acodec->func_configure_surface      = SDL_AMediaCodecJava_configure_surface;

在SDL_AMediaCodecJava_configure_surface中
(https://github.com/Bilibili/ijkplayer/blob/d061590d4cd07d7598a907cd0777c9eb51bb124b/ijkmedia/ijksdl/android/ijksdl_codec_android_mediacodec_java.c#L101)
有代码
```
J4AC_MediaCodec__configure(env, android_media_codec, android_media_format, android_surface, crypto, flags);
```

查到
>#define J4AC_MediaCodec__configure J4AC_android_media_MediaCodec__configure

J4AC_android_media_MediaCodec__configure代码为
(https://github.com/Bilibili/ijkplayer/blob/d061590d4cd07d7598a907cd0777c9eb51bb124b/ijkmedia/ijkj4a/j4a/class/android/media/MediaCodec.c#L344)
```
void J4AC_android_media_MediaCodec__configure(JNIEnv *env, jobject thiz, jobject format, jobject surface, jobject crypto, jint flags)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_android_media_MediaCodec.method_configure, format, surface, crypto, flags);
}
```

找不下去了TAT
想了解分辨率改变时界面是如何更新的。。
这个寻找路径太长了。。
是我找错了么？

@ctiao

**Comment by CzachQ** [comment]
感觉目前的困扰是 如果视频流的分辨率更新了
opaque->jsurface是从pipeline->opaque->jsurface更新的
但是pipeline->opaque->jsurface没有见过做出更改的地方

@ctiao

**Comment by CzachQ** [comment]
surface如何重绘还是没看懂思路，有兴趣讨论的邮件联系把，close了

**Comment by jinyunfeng** [comment]
surface重新create后传入后重新configure，为啥mediacodec的输出开始的时候没输出为黑屏，过一段时间才有画面
