### ISSUE TITLE
如何实现音注条效果

### ISSUE THREAD

**Issue by chenhuafeng** [Bilibili/ijkplayer#1788]
1.音柱条随着主播音量的变化，有幅动的效果；
2.左右声道显示有一定区别
3.当静音时，音柱条失去效果

**Comment by ctiao** [comment]
There is no such api inside ijkplayer.   You should analyze PCM data by yourself (or some other library)

**Comment by GintokiS** [comment]
https://github.com/syedhali/EZAudio
May help you.
