### ISSUE TITLE
ios端如何实现gif图片播放呢

### ISSUE THREAD

**Issue by DanielYQ** [Bilibili/ijkplayer#1789]
首先感谢作者的积极维护与回答。
是这样的，我想要在视频缓冲阶段播放一段gif图片，请问该如何解决这个问题呢。。。

**Comment by 6ag** [comment]
你完全可以在缓冲的阶段添加一个自定义view吧，这个跟IJKPlayer没有关系的。
还有，请问你的如何计算缓冲进度的呢，我 `bufferingProgress` 一直为 3， `playableDuration` 一直是 0，不知道是不是要预先设置options的什么东西。

**Comment by DanielYQ** [comment]
我也不太清楚这个缓冲进度如何计算...抱歉哦
但是在ffmpeg官方文档上看到了加载gif的相关描述，只是没有找到在ios如何实现。
