### ISSUE TITLE
Finnish Activity后，依旧在播放视频流声音

### ISSUE THREAD

**Issue by zhangxiliang** [Bilibili/ijkplayer#179]
关闭Activity前，调用了

public void stopPlayer(){
		if (mIjkMediaPlayer != null) {
			mIjkMediaPlayer.setDisplay(null);
			if (mIjkMediaPlayer.isPlaying()) {
				mIjkMediaPlayer.stop();
			}
			mIjkMediaPlayer.release();
			mIjkMediaPlayer = null;
		}
}

去停止播放器，但有时候会还有视频流声音在后台播放，比较难重现，但发生了好几次。

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
