### ISSUE TITLE
How to enable profiler for android? how to check the profile report? 

### ISSUE THREAD

**Issue by liwei46** [Bilibili/ijkplayer#1797]
Hi all,
I had notice there is a  init-android-prof.sh,  and then what to do next and how to check the profile report? 

Thanks a lot.

**Comment by ctiao** [comment]
> sh init-android-prof.sh
cd ijkprof/android-ndk-prof
ndk-build
...
...
...
sh compile-ijkplayer.sh all prof

**Comment by liwei46** [comment]
Hi ctiao,

Thanks for the reply. It should work, but I did not try it yet. 
I find using the logcat message with timestamp is good enough for me for the time being.

Regards,
