### ISSUE TITLE
Force format

### ISSUE THREAD

**Issue by Mikale1** [Bilibili/ijkplayer#180]
Hello,

I consume a video stream with ffmpeg/ffplay were the input format is not auto detected by ffmpeg so when using the ffmpeg or ffplay command line tool I have to specify the -f fmt option to force the input format and get it working. Otherwise I get "Invalid data found when processing input".

Is there a way to force the input format from ijkplayer? 
I've tried some options with the IjkMediaPlayer.setAvFormatOption() method but did not get it working.

Thanks,
Mikale

**Comment by bbcallen** [comment]
No option for this. You must modify ff_ffplay.c

https://github.com/FFmpeg/FFmpeg/blob/master/ffplay.c#L3585

**Comment by Mikale1** [comment]
Thank you for your help, it works!
For testing purposes I've added the following line at the beginning of your stream_open()-function in ff_ffplay.c
```c
iformat = av_find_input_format(forcedFileFormat);
```
I think this feature would be useful for others too, maybe you could think about integrating a IjkMediaPlayer#forceFileFormat(...) method.
