### ISSUE TITLE
ijkplayer，支持RTMP视频流地址吗

### ISSUE THREAD

**Issue by zhangxiliang** [Bilibili/ijkplayer#181]
protocol not found 是不支持RTMP吗
如果要设置防盗链参数发送到流媒体服务器，需要怎么配置呢
![qq 20150304140230](https://cloud.githubusercontent.com/assets/4599342/6478907/2e37037c-c277-11e4-8a4b-d637a1c1df95.png)

**Comment by bbcallen** [comment]
不太了解，建议你先本地编译一个ffplay，试验一下防盗链参数如何填写。

**Comment by ryanjunhung** [comment]
我是enable所有的protocol＋ＳＳＬ
所以可以正常運作。
ＥＸ：
CONFIGURE_FLAGS="$CONFIGURE_FLAGS --enable-protocols"

在build ffmpeg的時候會出現如下：

Enabled protocols:		
cache	http	rtmpt
concat	httpproxy	rtmpte
crypto	https	rtmpts
data	md5	rtp
ffrtmpcrypt	mmsh	srtp
ffrtmphttp	mmst	tcp
file	pipe	tls
ftp	rtmp	udp
gopher	rtmpe	unix
hls	rtmps
