### ISSUE TITLE
iOS ijkplayer call shutdown , the video voice will disappear with one or two seconds delay

### ISSUE THREAD

**Issue by zyi1992** [Bilibili/ijkplayer#1819]
In my project, for call shutdown not blocking main thread i drop it in async thread when the player disappear, like this :
  dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        [self.player shutdown];
  });
but this cause the voice disappear with one or two seconds delay problem even i call pause and stop before shutdown , but if i do this in main thread there would have a obvious  blocking for main thread, and had a bad effect for my viewcontroller disappear animation , so i want to know if there are a better way to call shutdown where and when ? ( ps: when test the ijkplayer demo ,it  obvious has the voice delay.  Nerver mind my poor english.)

**Comment by xinzhengzhang** [comment]
No matter which thread you call shutdown, ijk will always perform cleanup operation in background thread.
As you said there will be voice delay when close the ijk demo.
Can you provide the sample for reproducing this issue?
Thanks

**Comment by bhltyou** [comment]
退出的时候关闭声音，前提保证播放器能够正确的释放掉
