### ISSUE TITLE
Last frame in buffer after setVideoPath?

### ISSUE THREAD

**Issue by brystel** [Bilibili/ijkplayer#182]
Hi,

Is it possible that last HLS frame is in buffer after calling ```videoView.setVideoPath(url) ```?
I am using this same VideoView instance (from tv.danmaku.ijk.media.widget), and only changing videoPath.

Here is scenario:
1. Playing HLS
2. Changing HLS by ```videoView.setVideoPath(url)```
3. When there is onPrepared callback method called, I am starting mediaPlayer by ```mediaPlayer.start();```
4. For <1s I am seeing last frame from old HLS, after that new content is playing

Problem happens both with HW acceleration support and without it.

I suppose that the mediaPlayer instance in buffer has dupliacated last frames from old content.
If I right, is it possibility to clear buffer before calling .setVideoPath(...) again and again?

Do you known with this problem? Or meaby it is another issue?

Thank you

**Comment by bbcallen** [comment]
So called buffer exists in SurfaceView, not in mediaplayer,
You need do something to trigger a recreation of SurfaceView
```
videoView.getHolder().setFormat(PixelFormat.RGB_565);
```
Or
```
videoVIew.invalidate(); // dunno if works
```

**Comment by brystel** [comment]
Thank you,
It seems that mediaPlayer.reset(); does not help. The SurfaceHolder which is attached to MediaPlayer holds the last frame.
I solved problem by destroying VideoView in each source changing and creating new instance of VideoView.

**Comment by bbcallen** [comment]
Meh～ :)
