### ISSUE TITLE
怎么播放Https://打头的URL视频链接

### ISSUE THREAD

**Issue by fxxch** [Bilibili/ijkplayer#1829]
我们服务器是用的https的视频链接，但是ijkplayer始终无法播放这个视频的，音频格式也是一样的：https://www.goucrm.com//tmp/upload/0/9/208/doc/fc/49/208_1.mp3 请问有办法解决这个问题吗

**Comment by infsafe** [comment]
@fxxch 你的mp3地址错误啊。。

**Comment by ctiao** [comment]
#1269  #1632 #1115

**Comment by fxxch** [comment]
@infsafe ijkplayer 支持https的多媒体链接地址播放吗？

**Comment by fxxch** [comment]
已经解决了
编译步骤
sh init-ios-openssl.sh
sh init-ios.sh

cd ios
./compile-openssl.sh clean
./compile-ffmpeg.sh clean
./compile-openssl.sh all
./compile-ffmpeg.sh all
如此编译出来的静态库就能播放https的URL地址了

**Comment by sunfeiGit** [comment]
iOS端，怎么播放https的地址？
sh init-ios-openssl.sh
sh init-ios.sh

cd ios
./compile-openssl.sh clean
./compile-ffmpeg.sh clean
./compile-openssl.sh all
./compile-ffmpeg.sh all

编译出来的并不可以

**Comment by sunfeiGit** [comment]
请问有哪位iOS大神在进行播放https的协议，编译成功了，给一个详细的步骤，感激不尽

**Comment by iSuAbner** [comment]
编译出来的库运行在程序里面会报错的Apple Mach -O linker (id) Error 怎么办啊

**Comment by woshigaokeji** [comment]
@sunfeiGit  请问下你有处理好吗，同求iOS播放https协议的方法

**Comment by woshigaokeji** [comment]
@fxxch 请问下你编译成功是什么样子，我是先编译的./compile-ffmpeg.sh clean ./compile-ffmpeg.sh all
然后编译的./compile-openssl.sh clean   ./compile-openssl.sh all 但是我发现编译openssl好快，感觉是不是哪里不对，编译ffmpeg超级慢的

**Comment by fxxch** [comment]
我这边开始也不能播放https,后来按照我的方式编译了一下，然后打开工程里面的IJKMediaPlayer工程，编译出来的.a静态库就能播放https了，需要咨询沟通的朋友可以给我发邮件349230334@qq.com,互相学习沟通

**Comment by iSuAbner** [comment]
SSL本来就快 ffmpeg本来就慢 还得自己去下载.a的SSL库 然后编译进去 编译成功的样子就是能播放HTTPS被 。。

在 2017-02-16 12:00:59，"科了个技" <notifications@github.com> 写道：


@fxxch 请问下你编译成功是什么样子，我是先编译的./compile-ffmpeg.sh clean ./compile-ffmpeg.sh all
然后编译的./compile-openssl.sh clean ./compile-openssl.sh all 但是我发现编译openssl好快，感觉是不是哪里不对，编译ffmpeg超级慢的
