### ISSUE TITLE
ViewPager中的IjkVideoView黑屏闪烁问题

### ISSUE THREAD

**Issue by shangmingchao** [Bilibili/ijkplayer#1832]
在ViewPager中的Fragment加载IjkViewoView时，屏幕会突然黑一下，类似这样：<br/>![图片](https://github.com/shangmingchao/ijkplayer/blob/master/screenshots/screenshot_01.gif)，具体代码和图片可以看一下这个repo：[ijkplayer-debug](https://github.com/shangmingchao/ijkplayer)，请问为什么会出现这样的问题，应该怎么解决啊？

**Comment by infsafe** [comment]
@shangmingchao 你可以在activity的布局文件里面加一个0dp的surfaceview，应该可以解决这个问题。

**Comment by shangmingchao** [comment]
@infsafe 谢谢，确实可以解决问题，但您知道为什么会出现这样的问题么？有没有更优雅的解决方法？

**Comment by 539863010** [comment]
是的， 在包含Fragment的Activity中添加个0dp的SurfaceView确实能解决闪黑屏的问题
