### ISSUE TITLE
iOS 播放器 shutdown 后，还是有声音播放，播放器没有释放掉~

### ISSUE THREAD

**Issue by FuYanfang** [Bilibili/ijkplayer#1851]
ijkmp_stop()
ijkmp_stop()=0
ijkmp_shutdown_l()
aout_close_audio()
SDL_Overlay(ffmpeg): overlay_free_l(0x1702d1cd0)
SDL_Overlay(ffmpeg): overlay_free_l(0x1744c4830)
SDL_Overlay(ffmpeg): overlay_free_l(0x1744c9d80)
ijkmp_shutdown_l()=void
ijkmp_dec_ref(): ref=0
ijkmp_shutdown_l()
ijkmp_shutdown_l()=void
aout_close_audio()

**Comment by bhltyou** [comment]
player.view removeFromSuperView
player shutdown
player = nil//必须设置成nil
