### ISSUE TITLE
修改编译文件支持所有格式后,编译报错

### ISSUE THREAD

**Issue by seedzi** [Bilibili/ijkplayer#186]
build on Linux x86_64
WARNING: The shell running this script isn't bash.  Although we try to avoid bashism in scripts, things can happen.
Copying prebuilt binaries...
Copying sysroot headers and libraries...
Copying libstdc++ headers and libraries...
Copying files to: /home/huzhi/develop/workspace_test/ijkplayer-android/android/build/ffmpeg-armv7a/toolchain
Cleaning up...
Done.

--------------------
[*] check ffmpeg env
--------------------
tools/do-compile-ffmpeg.sh: 222: .: Can't open /home/huzhi/develop/workspace_test/ijkplayer-android/android/../config/module.sh

**Comment by bbcallen** [comment]
```
# choose [No] to use bash
sudo dpkg-reconfigure dash
```
