### ISSUE TITLE
播放在线视频时，输出av_read_frame error: abb6a7bb( , , , ): AVERROR_EXIT 错误

### ISSUE THREAD

**Issue by Tandrow** [Bilibili/ijkplayer#1862]
结果是视频有声音，没有画面
测试视频地址是这个：http://120.76.159.40:8088/showCook_temp/upload/video/2016/8/f8cc1fa856111adb01569d1281cd014c.mp4，
看了问题列表中好像有人提过这个问题，但用他提供的测试地址，不会输出标题中AVERROR_EXIT 错误，
不知道之前回答中说开启某些配置的方法对这个情况有没有效果，现在没有环境自己编译，如果有遇到相同问题的小伙伴麻烦告知下解决方案，或者有开启了mp4v配置的小伙伴帮忙试下有没有用，多谢了

**Comment by Vanson** [comment]
这个Chrome自带的播放器也不能解码啊

**Comment by ctiao** [comment]
>     Stream #0:0(eng): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 5792 kb/s, 59.94 fps, 59.94 tbr, 90k tbn, 2997 tbc (default)

默认编译配置裁掉了 mp4v, 开启方法见README和相关issue  #134  #1519 #184

**Comment by Tandrow** [comment]
果然是这个问题，这个项目中，ower提供了完整的so，需要的同学可以点这里看看https://github.com/tcking/GiraffePlayer
