### ISSUE TITLE
Android在一个界面同时播放多个视频的时候，会出现图像卡住，声音继续播放的现象

### ISSUE THREAD

**Issue by huyn** [Bilibili/ijkplayer#1868]
在同一个界面开启多个视频同时播放（视频的加入有先后顺序，第一个加入的视频，占据一半的屏幕，后加入的视频关闭声音），开始的时候图像都能动。当点击第一个视频以外的其它视频的时候，会和第一个视频交换位置和大小，并打开声音，这个时候，这个视频的图像会卡住，但是声音能继续播放。

log如下：
`
08-22 15:11:06.050 1236-2065/com.aube.phone E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -22`

用MediaPlayer能正常播放

**Comment by huyn** [comment]
硬解的设置漏了。不过会出现黑屏现象。

**Comment by ctiao** [comment]
#1500 #1468

**Comment by tanqu2013** [comment]
请问这个问题是如何解决的？
