### ISSUE TITLE
ijkplayer支持硬解吗?

### ISSUE THREAD

**Issue by thinkperson** [Bilibili/ijkplayer#1869]
我在osx 10.10.5上编译ijk的IOS版，然后在IOS模拟器中播放网络视频比较卡，像慢镜头的效果，而这个网络串在Linux下的ffplay上就可以流畅播放，所以可以排除网络视频的原因。想请教一下：ijk的ios版支持硬解吗？怎样开启硬解呢？

**Comment by xinzhengzhang** [comment]
#1461

**Comment by thinkperson** [comment]
非常感谢，按照您的方法开启硬解了，我跟踪代码，进入videotoolbox分支了，但在ios模拟器下播放依然很卡，像慢镜头效果。是不是IOS模拟器没办法模拟出硬解的效果？

**Comment by ctiao** [comment]
ijkplayer不保证模拟器上的播放效果。
