### ISSUE TITLE
Video quality

### ISSUE THREAD

**Issue by novodev** [Bilibili/ijkplayer#187]
Hello,
first thank you for this great project.

I have following question:
The quality of the videos played with the ijkplayer is not as good as on e.g. an android device internal video player. (the video is more pixelated)

Can you tell me where I can set the decoding options/profiles/etc. for the codecs to raise the display quality?

Thank you

**Comment by bbcallen** [comment]
For android.
```
mp.setAvCodecOption(..., ...);
```

https://www.ffmpeg.org/ffmpeg-codecs.html
You can find all codec options here.

**Comment by novodev** [comment]
After some testing I found out that the cause for the bad quality was the codec option 
skip_loop_filter. It was set to 48 in the VideoView of the ijkmediawidget. 
After setting the value to 0, the display quality of the videos is equal to all other MediaPlayers.
Thank you for your support!
