### ISSUE TITLE
How do I write the http header of url？

### ISSUE THREAD

**Issue by NathanLi** [Bilibili/ijkplayer#1879]

**Comment by xinzhengzhang** [comment]
http://stackoverflow.com/questions/33718810/ffmpeg-how-to-pass-http-headers

**Comment by NathanLi** [comment]
And What to do in iOS?

**Comment by xinzhengzhang** [comment]
Refer to demo and set format option with key named 'headers'

**Comment by NathanLi** [comment]
@xinzhengzhang  OK   Thk you.
