### ISSUE TITLE
Linking bug

### ISSUE THREAD

**Issue by ousenko** [Bilibili/ijkplayer#189]
Hi, bbcallen,

I have some linking bug I can't track down. The issue happens with arm64-v8a project:

 ``FATAL EXCEPTION: main
    Process: com.example.app, PID: 4237
    java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "/Users/drew/Projects/example/ijkplayer/android/ijkmediaplayer-arm64-v8a/obj/local/arm64-v8a/libijkffmpeg.so" needed by "/data/app/com.example.app/lib/arm64/libijksdl.so"; caused by library "/Users/drew/Projects/example/app/ijkplayer/android/ijkmediaplayer-arm64-v8a/obj/local/arm64-v8a/libijkffmpeg.so" not found```

I am no NDK expert, but it seems like the local path is hardcoded to a compiled .so file, and is of course not available at runtime.

I use the **ijkplayer** as subproject of my main project.

Could you tell me how to fix it or where to look for the bug?

**Comment by waninkoko** [comment]
This exact same bug has appeared in my list of crashes. In my case, it is happening to users who use a Nexus 9.

**Comment by ousenko** [comment]
Can  anyone tell me if  it's possible to fallback to armeabi-v7 from arm64-v8a; and to fallback to x86 from x86_64?

If so I could only use:
`ijkmediaplayer`
`ijkmediaplayer-x86`

**Comment by bbcallen** [comment]
arm64 linker on android doesn't support text relocation, for now.
https://code.google.com/p/android/issues/detail?id=81073

I'm waiting for android or ffmpeg to fix this issue.

So, don't use arm64-v8a ffmpeg on android, for now.

**Comment by bbcallen** [comment]
Fixed.
