### ISSUE TITLE
[Android 一个比较严重的问题，求帮助]  中途停顿抛出error错误的问题

### ISSUE THREAD

**Issue by xuluming** [Bilibili/ijkplayer#1891]
经过测试后发现，在播放点播（测试视频.mp4)的时候（直播的话，取消掉timeout参数就不会有这个问题了），如果中途模拟把网络断掉，断网后的一段时间，播放器会抛出error错误，重新联网再也不能继续播放视频了。。。。求帮助

**Comment by ctiao** [comment]
这是正常的流程
