### ISSUE TITLE
请问编译出错怎么解决啊？

### ISSUE THREAD

**Issue by itlws** [Bilibili/ijkplayer#1896]
我是个菜鸟，是按照文档上一步一步来的但是在执行./compile-ffmpeg.sh all命令时，提示IJK_NDK_REL=
You need the NDKr10e or later
刚开始我用的ndk时用studio里下载好的ndk，版本是12，但是不行，提示上面的信息然后我从网上下载了r10e版本的ndk编译还是提示这个，请问该怎么解决啊？

**Comment by qwerttest** [comment]
ndk配置环境变量没

**Comment by itlws** [comment]
找到问题了，是我ndk环境变量配置错了...谢谢了哈
