### ISSUE TITLE
android端如何支持hls的aes128解密播放？

### ISSUE THREAD

**Issue by fengtianze** [Bilibili/ijkplayer#1902]
我通过在gradle中添加依赖的方式引用ijkplayer。可以成功播放未加密的hls视频，但播放aes128加密hls视频时失败。

**Comment by gotone** [comment]
compile ijkplayer, remove --disable-protocol=crypto in config/module-lite.sh and recompile it.

**Comment by loveRose** [comment]
怎么玩？？？

**Comment by Android4MediaPlayer** [comment]
add openssl

**Comment by jshqhxm** [comment]
https://github.com/Bilibili/ijkplayer/issues/2891

**Comment by fukemy** [comment]
why u didnt add openss into gradle implement for android?

    implementation 'tv.danmaku.ijk.media:ijkplayer-java:0.8.8'
    implementation 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.8.8'

    implementation 'tv.danmaku.ijk.media:ijkplayer-armv5:0.8.8'
    implementation 'tv.danmaku.ijk.media:ijkplayer-arm64:0.8.8'
    implementation 'tv.danmaku.ijk.media:ijkplayer-x86:0.8.8'
    implementation 'tv.danmaku.ijk.media:ijkplayer-x86_64:0.8.8'

**Comment by woniurensheng** [comment]
> #2891

按照那个改了  还是不行，工程里需要改什么吗
