### ISSUE TITLE
Stream not plays after internet reconnect

### ISSUE THREAD

**Issue by brystel** [Bilibili/ijkplayer#191]
Hello,

I have experienced that stream wont play after reconnect to the internet.

The case is:
1. Play stream
2. Turn off internet connection
3. Wait for buffer ends (after buffer ends stream hangs)
4. Turn on internet connection

At this point the stream not starts. It also not respond to resume command

**Comment by brystel** [comment]
There is not also any message from onErrorListener.
The only message in logCat comes from native code:

E/IJKMEDIA﹕ Failed to resolve hostname teststream.net: No address associated with hostname
W/IJKMEDIA﹕ Failed to reload playlist 0

**Comment by bbcallen** [comment]
I'm working on reconnect recently,
http://git.videolan.org/?p=ffmpeg.git;a=commit;h=3f375950f3c9a9c5cf7cece6c26d3e0e7ce278cf
The patch above could fix reconnect by chance.

But I think it's better to use custome IO for full control.

**Comment by brystel** [comment]
Thank you! 
I've resolved this by detecting network connection and restarting player in case when connection is back.
