### ISSUE TITLE
iOS播放视频崩溃

### ISSUE THREAD

**Issue by RonnieJia** [Bilibili/ijkplayer#1918]
播放视频的时候有的时候没问题，但是有时候会出现奔溃在mem.c文件中。在这个函数中void av_free（void *ptr）。log中的信息是 malloc: *** error for object 0xe0000000148ff72b: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

**Comment by xinzhengzhang** [comment]
https://github.com/Bilibili/ijkplayer/commit/eb8b7c0552dd8aaa1b9d8de99c96a076ce380dc2
Fixed.
