### ISSUE TITLE
播放器在IOS8+的设备上卡顿严重

### ISSUE THREAD

**Issue by remantou** [Bilibili/ijkplayer#192]
播放器在IOS7+的iphone5s播放很顺畅，但是在IOS8+的各种设备如iphone5,iphone6,iphone6 plus上面播放卡顿很严重，然后会停住不动，网络状况没有问题。

**Comment by bbcallen** [comment]
如果播放界面上有动画效果或者阴影效果，会导致软解效率变低，解决办法
1. 不要频繁在播放界面使用动画或阴影
2. 换用AVPlayer 或者 VideoToolBox 

只从播放器本身来说，基本无解。

**Comment by jgfntu** [comment]
关于IOS的硬解码我找到一些有用的参考信息，最近也在调试，发现一些问题，供大家讨论一下：
1、知乎上有个简单介绍videotoolbox的帖子
http://www.zhihu.com/question/20692215
2、找到几个VLC的patch，貌似官方没合进去
比较新的
http://permalink.gmane.org/gmane.comp.video.videolan.vlc.devel/99468
http://permalink.gmane.org/gmane.comp.video.videolan.vlc.devel/99469
还有个比较旧的
https://mailman.videolan.org/pipermail/vlc-devel/2014-October/099971.html
两个总体差不多，我用VLCkit简单调试了下（暂时用的mp4封装的视频来验证的，因为sps和pps等信息初始化给videotoolbox时要另处理一下）
不过验证的结果有些糟糕，CPU变化不大，反正FPS降了一半，还在找原因，可能还是用错了
3、另外还有直接针对ffmpeg的hwaccel的patch
https://patches.libav.org/patch/27684/
不过在ffplay里面没调的起来hwacce的框架来解码

**Comment by bbcallen** [comment]
xbmc 的 VideoToolBox 实现是目前开源的里面，最成熟的，不过需要注意，他是GPL的。

**Comment by bbcallen** [comment]
ijkplayer已经支持ios8的硬件解码。

**Comment by xuluming** [comment]
@bbcallen iOS默认就支持硬解吗？不需要做任何设置？因为我用下面这句话无效
[options setOptionIntValue:1 forKey:@"mediacodec" ofCategory:kIJKFFOptionCategoryPlayer];

**Comment by allentsing** [comment]
@bbcallen 默认设置下[IJKFFOptions optionsByDefault] 是硬解还是软解？要改变硬解成软解，或者反过来，要在哪里设置？

**Comment by allentsing** [comment]
我说的是iOS下

**Comment by raymond1012** [comment]
[options setPlayerOptionIntValue:1      forKey:@"videotoolbox"];

**Comment by allentsing** [comment]
@raymond1012  谢谢
