### ISSUE TITLE
麻烦能告诉一下ndk和sdk版本好吗？因为在打包arm64的so包。总是因为各种版本文件找不到出错。

### ISSUE THREAD

**Issue by z2045217** [Bilibili/ijkplayer#1927]
ubuntu下编译的。git上面资料也挺详细的。但是我想打包arm64的库。但是总是因为ndk上面的原因。编译失败。如果可以的话。能给个ndk和sdk连接就好了。谢谢。

**Comment by ctiao** [comment]
NDK r10e
