### ISSUE TITLE
disable wifi & 3G，player異常回傳onCompletion

### ISSUE THREAD

**Issue by MoneyShih** [Bilibili/ijkplayer#193]
在android手機上
播放https的hls
在播放時把wifi& 3g網路關閉
當player的buffer播完後
player會回傳onCompletion而不是error
但影片實際上還沒播放完畢

**Comment by bbcallen** [comment]
这是一个需要改ffmpeg的bug...

**Comment by lyqaiym** [comment]
解决了没有？

**Comment by MoneyShih** [comment]
當時的作法是在 IjkMediaPlayer.java中的 case MEDIA_PLAYBACK_COMPLETE:
這一邊自行處理

            case MEDIA_PLAYBACK_COMPLETE:
            	
                if (player != null) {
                	long dur = player.getDuration();
                	long pos = player.getCurrentPosition();
                	if (dur >= 0 && pos - dur > -10 * 1000) {
                		Log.i("IjkMediaPlayer", "IjkMediaPlayer MEDIA_PLAYBACK_COMPLETE pos - dur > -10 * 1000");
                        player.notifyOnCompletion();
                        player.stayAwake(false);
                	} else {
                		Log.i("IjkMediaPlayer", "IjkMediaPlayer MEDIA_PLAYBACK_COMPLETE network");
                		if (dur >= 0 && mContext != null && network.getInst(mContext).isConnected() && network.getInst(mContext).isAvailable()) {
                			Log.i("IjkMediaPlayer", "IjkMediaPlayer MEDIA_PLAYBACK_COMPLETE isAvailable");
                            player.notifyOnCompletion();
                            player.stayAwake(false);
                		} else {
                			//call error
                			int what = MEDIA_ERROR_IO;
                			int extra = MEDIA_ERROR_NETWORK_UNAVAILABLE;
                            DebugLog.e(TAG, "Error (" + what + "," + extra + ")");
                            if (!player.notifyOnError(what, extra)) {

                            }
                            player.stayAwake(false);
                		}
                	}
                	
                }
            	
                //player.notifyOnCompletion();
                //player.stayAwake(false);
                return;

**Comment by feiyang1235** [comment]
好像并不管用

**Comment by heistings** [comment]
> 當時的作法是在 IjkMediaPlayer.java中的 case MEDIA_PLAYBACK_COMPLETE:
> 這一邊自行處理
> 
> ```
>         case MEDIA_PLAYBACK_COMPLETE:
> 
>             if (player != null) {
>                 long dur = player.getDuration();
>                 long pos = player.getCurrentPosition();
>                 if (dur >= 0 && pos - dur > -10 * 1000) {
>                     Log.i("IjkMediaPlayer", "IjkMediaPlayer MEDIA_PLAYBACK_COMPLETE pos - dur > -10 * 1000");
>                     player.notifyOnCompletion();
>                     player.stayAwake(false);
>                 } else {
>                     Log.i("IjkMediaPlayer", "IjkMediaPlayer MEDIA_PLAYBACK_COMPLETE network");
>                     if (dur >= 0 && mContext != null && network.getInst(mContext).isConnected() && network.getInst(mContext).isAvailable()) {
>                         Log.i("IjkMediaPlayer", "IjkMediaPlayer MEDIA_PLAYBACK_COMPLETE isAvailable");
>                         player.notifyOnCompletion();
>                         player.stayAwake(false);
>                     } else {
>                         //call error
>                         int what = MEDIA_ERROR_IO;
>                         int extra = MEDIA_ERROR_NETWORK_UNAVAILABLE;
>                         DebugLog.e(TAG, "Error (" + what + "," + extra + ")");
>                         if (!player.notifyOnError(what, extra)) {
> 
>                         }
>                         player.stayAwake(false);
>                     }
>                 }
> 
>             }
> 
>             //player.notifyOnCompletion();
>             //player.stayAwake(false);
>             return;
> ```

@ MoneyShih 对于直播来说，这样改是有问题的。
