### ISSUE TITLE
输入./init-ios.sh之后下载着下载到15%,就断了提示如下怎么解决capitan

### ISSUE THREAD

**Issue by OneHundredSir** [Bilibili/ijkplayer#1936]
MacBook-Pro:ijkplayer-ios huanghuiqun$ **./init-ios.sh**
git version 2.7.4 (Apple Git-66)
== pull gas-preprocessor base ==
Fetching origin
/Users/huanghuiqun/Downloads/ijkplayer-master 2/ios/ijkplayer-ios
== pull ffmpeg base ==
Cloning into 'extra/ffmpeg'...
remote: Counting objects: 489107, done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by OneHundredSir** [comment]
我已经使用了VPN但是还是下载不了,是网络不给力?

**Comment by LinusLiu724** [comment]
有可能是网络不给力导致的，我执行./init-android.sh也出现了类似的报错，换个网速快的网络就成功了

**Comment by Jackzigen** [comment]
> I have the same problem

你最后怎么解决的？

**Comment by haidibing** [comment]
> > I have the same problem
> 
> 你最后怎么解决的？

太久了，忘记了。。
