### ISSUE TITLE
Unable to archive/Release in iOS 8.2: Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by KCastiglione** [Bilibili/ijkplayer#194]
I was able to successfully build and run DEBUG version.

But for release, when I archive the project I get this error:

I also tried adding ffmpeg-arm64 built libraries to the Linking section of Xcode, and still get the same error.

Which build of ffmpeg should I use for Archive/Release?

     ffmpeg-arm64/  ffmpeg-armv7/  ffmpeg-armv7s/ ffmpeg-i386/   ffmpeg-x86_64/ universal/

Unable to archive iOS build 8.2

Ld /Users/live/Library/Developer/Xcode/DerivedData/IJKMediaDemo-ckbawnlaamvpauaaxwpocttydvof/Build/Intermediates/ArchiveIntermediates/IJKMediaDemo/IntermediateBuildFilesPath/IJKMediaDemo.build/Release-iphoneos/IJKMediaDemo.build/Objects-normal/arm64/IJKMediaDemo normal arm64
    cd /Users/live/src/github/ijkplayer/ios/IJKMediaDemo
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.2.sdk -L/Users/live/Library/Developer/Xcode/DerivedData/IJKMediaDemo-ckbawnlaamvpauaaxwpocttydvof/Build/Intermediates/ArchiveIntermediates/IJKMediaDemo/BuildProductsPath/Release-iphoneos -F/Users/live/Library/Developer/Xcode/DerivedData/IJKMediaDemo-ckbawnlaamvpauaaxwpocttydvof/Build/Intermediates/ArchiveIntermediates/IJKMediaDemo/BuildProductsPath/Release-iphoneos -filelist /Users/live/Library/Developer/Xcode/DerivedData/IJKMediaDemo-ckbawnlaamvpauaaxwpocttydvof/Build/Intermediates/ArchiveIntermediates/IJKMediaDemo/IntermediateBuildFilesPath/IJKMediaDemo.build/Release-iphoneos/IJKMediaDemo.build/Objects-normal/arm64/IJKMediaDemo.LinkFileList -dead_strip -fobjc-arc -fobjc-link-runtime -miphoneos-version-min=6.0 -framework CoreMedia -framework AVFoundation /Users/live/Library/Developer/Xcode/DerivedData/IJKMediaDemo-ckbawnlaamvpauaaxwpocttydvof/Build/Intermediates/ArchiveIntermediates/IJKMediaDemo/BuildProductsPath/Release-iphoneos/libIJKMediaPlayer.a -framework QuartzCore -framework CoreGraphics -framework MediaPlayer -framework OpenGLES -framework AudioToolbox -framework UIKit -lz -lbz2 -Xlinker -dependency_info -Xlinker /Users/live/Library/Developer/Xcode/DerivedData/IJKMediaDemo-ckbawnlaamvpauaaxwpocttydvof/Build/Intermediates/ArchiveIntermediates/IJKMediaDemo/IntermediateBuildFilesPath/IJKMediaDemo.build/Release-iphoneos/IJKMediaDemo.build/Objects-normal/arm64/IJKMediaDemo_dependency_info.dat -o /Users/live/Library/Developer/Xcode/DerivedData/IJKMediaDemo-ckbawnlaamvpauaaxwpocttydvof/Build/Intermediates/ArchiveIntermediates/IJKMediaDemo/IntermediateBuildFilesPath/IJKMediaDemo.build/Release-iphoneos/IJKMediaDemo.build/Objects-normal/arm64/IJKMediaDemo

Undefined symbols for architecture arm64:
  "_avcodec_find_encoder", referenced from:
      _filter_codec_opts in libIJKMediaPlayer.a(ff_cmdutils.o)
  "_avformat_match_stream_specifier", referenced from:
      _filter_codec_opts in libIJKMediaPlayer.a(ff_cmdutils.o)
  "_av_opt_find", referenced from:
      _filter_codec_opts in libIJKMediaPlayer.a(ff_cmdutils.o)
  "_avpicture_get_size", referenced from:
      _SDL_VoutFFmpeg_ConvertFrame in libIJKMediaPlayer.a(ijksdl_vout_overlay_ffmpeg.o)
  "_av_buffer_alloc", referenced from:
      _SDL_VoutFFmpeg_ConvertFrame in libIJKMediaPlayer.a(ijksdl_vout_overlay_ffmpeg.o)
  "_av_get_pix_fmt_name", referenced from:
      _SDL_VoutFFmpeg_ConvertFrame in libIJKMediaPlayer.a(ijksdl_vout_overlay_ffmpeg.o)
  "_avpicture_fill", referenced from:
      _SDL_VoutFFmpeg_CreateOverlay in libIJKMediaPlayer.a(ijksdl_vout_overlay_ffmpeg.o)
      _SDL_VoutFFmpeg_ConvertFrame in libIJKMediaPlayer.a(ijksdl_vout_overlay_ffmpeg.o)
  "_swr_set_compensation", referenced from:
      _sdl_audio_callback in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_fast_malloc", referenced from:
      _sdl_audio_callback in libIJKMediaPlayer.a(ff_ffplay.o)
  "_swr_convert", referenced from:
      _sdl_audio_callback in libIJKMediaPlayer.a(ff_ffplay.o)
  "_swr_init", referenced from:
      _sdl_audio_callback in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_get_bytes_per_sample", referenced from:
      _sdl_audio_callback in libIJKMediaPlayer.a(ff_ffplay.o)
  "_swr_free", referenced from:
      _stream_component_close in libIJKMediaPlayer.a(ff_ffplay.o)
      _sdl_audio_callback in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_strerror", referenced from:
      _print_error in libIJKMediaPlayer.a(ff_cmdutils.o)
  "_avcodec_find_decoder_by_name", referenced from:
      _stream_component_open in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_codec_get_max_lowres", referenced from:
      _stream_component_open in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_frame_get_channels", referenced from:
      _sdl_audio_callback in libIJKMediaPlayer.a(ff_ffplay.o)
  "_avcodec_open2", referenced from:
      _stream_component_open in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_get_channel_layout_nb_channels", referenced from:
      _stream_component_open in libIJKMediaPlayer.a(ff_ffplay.o)
      _sdl_audio_callback in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_log2", referenced from:
      _stream_component_open in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_samples_get_buffer_size", referenced from:
      _stream_component_open in libIJKMediaPlayer.a(ff_ffplay.o)
      _sdl_audio_callback in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_format_set_control_message_cb", referenced from:
      _read_thread in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_format_set_opaque", referenced from:
      _read_thread in libIJKMediaPlayer.a(ff_ffplay.o)
  "_avformat_open_input", referenced from:
      _read_thread in libIJKMediaPlayer.a(ff_ffplay.o)
  "_avformat_find_stream_info", referenced from:
      _read_thread in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_dump_format", referenced from:
      _read_thread in libIJKMediaPlayer.a(ff_ffplay.o)
  "_avformat_close_input", referenced from:
      _read_thread in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_freep", referenced from:
      _ijkmp_dec_ref in libIJKMediaPlayer.a(ijkplayer.o)
      _ijkmp_set_data_source in libIJKMediaPlayer.a(ijkplayer.o)
      _ffp_create in libIJKMediaPlayer.a(ff_ffplay.o)
      _ffp_destroy in libIJKMediaPlayer.a(ff_ffplay.o)
      _ffp_prepare_async_l in libIJKMediaPlayer.a(ff_ffplay.o)
      _packet_queue_destroy in libIJKMediaPlayer.a(ff_ffplay.o)
      _ffp_set_video_codec_info in libIJKMediaPlayer.a(ff_ffplay.o)
      ...
  "_av_codec_get_pkt_timebase", referenced from:
      _decoder_decode_frame in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_log_set_callback", referenced from:
      _ffp_global_init in libIJKMediaPlayer.a(ff_ffplay.o)
      _ffp_global_set_log_report in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_usleep", referenced from:
      _ffp_video_refresh_thread in libIJKMediaPlayer.a(ff_ffplay.o)
  "_avcodec_register_all", referenced from:
      _ffp_global_init in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_frame_alloc", referenced from:
      _ffp_video_thread in libIJKMediaPlayer.a(ff_ffplay.o)
      _frame_queue_init in libIJKMediaPlayer.a(ff_ffplay.o)
      _audio_thread in libIJKMediaPlayer.a(ff_ffplay.o)
      _SDL_VoutFFmpeg_CreateOverlay in libIJKMediaPlayer.a(ijksdl_vout_overlay_ffmpeg.o)
  "_avcodec_get_name", referenced from:
      _ijkmeta_set_avformat_context_l in libIJKMediaPlayer.a(ijkmeta.o)
      _stream_component_open in libIJKMediaPlayer.a(ff_ffplay.o)
      _ffpipenode_create_video_decoder_from_ffplay in libIJKMediaPlayer.a(ffpipenode_ffplay_vdec.o)
  "_avcodec_decode_video2", referenced from:
      _decoder_decode_frame in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_guess_frame_rate", referenced from:
      _ffp_video_thread in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_frame_unref", referenced from:
      _ffp_video_thread in libIJKMediaPlayer.a(ff_ffplay.o)
      _frame_queue_next in libIJKMediaPlayer.a(ff_ffplay.o)
      _frame_queue_destory in libIJKMediaPlayer.a(ff_ffplay.o)
      _overlay_free_l in libIJKMediaPlayer.a(ijksdl_vout_overlay_ffmpeg.o)
      _SDL_VoutFFmpeg_ConvertFrame in libIJKMediaPlayer.a(ijksdl_vout_overlay_ffmpeg.o)
  "_av_rescale", referenced from:
      _ffp_seek_to_l in libIJKMediaPlayer.a(ff_ffplay.o)
      _ffp_get_current_position_l in libIJKMediaPlayer.a(ff_ffplay.o)
      _ffp_get_duration_l in libIJKMediaPlayer.a(ff_ffplay.o)
      _ffp_check_buffering_l in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_frame_free", referenced from:
      _ffp_video_thread in libIJKMediaPlayer.a(ff_ffplay.o)
      _audio_thread in libIJKMediaPlayer.a(ff_ffplay.o)
      _frame_queue_destory in libIJKMediaPlayer.a(ff_ffplay.o)
      _SDL_VoutFFmpeg_CreateOverlay in libIJKMediaPlayer.a(ijksdl_vout_overlay_ffmpeg.o)
      _overlay_free_l in libIJKMediaPlayer.a(ijksdl_vout_overlay_ffmpeg.o)
  "_av_log_format_line", referenced from:
      _ffp_log_callback_report in libIJKMediaPlayer.a(ff_ffplay.o)
  "_sws_scale", referenced from:
      _SDL_VoutFFmpeg_ConvertFrame in libIJKMediaPlayer.a(ijksdl_vout_overlay_ffmpeg.o)
  "_avformat_seek_file", referenced from:
      _read_thread in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_read_frame", referenced from:
      _read_thread in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_frame_get_pkt_pos", referenced from:
      _ffp_video_thread in libIJKMediaPlayer.a(ff_ffplay.o)
      _audio_thread in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_dict_free", referenced from:
      _ijkmeta_destroy in libIJKMediaPlayer.a(ijkmeta.o)
      _ffp_create in libIJKMediaPlayer.a(ff_ffplay.o)
      _ffp_destroy in libIJKMediaPlayer.a(ff_ffplay.o)
      _read_thread in libIJKMediaPlayer.a(ff_ffplay.o)
      _stream_component_open in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_register_all", referenced from:
      _ffp_global_init in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_frame_ref", referenced from:
      _SDL_VoutFFmpeg_ConvertFrame in libIJKMediaPlayer.a(ijksdl_vout_overlay_ffmpeg.o)
  "_av_copy_packet", referenced from:
      _read_thread in libIJKMediaPlayer.a(ff_ffplay.o)
  "_avio_feof", referenced from:
      _read_thread in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_get_default_channel_layout", referenced from:
      _stream_component_open in libIJKMediaPlayer.a(ff_ffplay.o)
      _sdl_audio_callback in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_lockmgr_register", referenced from:
      _ffp_global_init in libIJKMediaPlayer.a(ff_ffplay.o)
  "_avcodec_decode_audio4", referenced from:
      _decoder_decode_frame in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_asprintf", referenced from:
      _ffp_set_video_codec_info in libIJKMediaPlayer.a(ff_ffplay.o)
      _ffp_set_audio_codec_info in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_dict_set_int", referenced from:
      _ijkmeta_set_int64_l in libIJKMediaPlayer.a(ijkmeta.o)
      _ijkmeta_set_avformat_context_l in libIJKMediaPlayer.a(ijkmeta.o)
      _stream_component_open in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_dup_packet", referenced from:
      _packet_queue_put in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_strdup", referenced from:
      _ijkmp_set_data_source in libIJKMediaPlayer.a(ijkplayer.o)
  "_av_init_packet", referenced from:
      _ffp_global_init in libIJKMediaPlayer.a(ff_ffplay.o)
      _read_thread in libIJKMediaPlayer.a(ff_ffplay.o)
  "_avcodec_flush_buffers", referenced from:
      _decoder_decode_frame in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_free_packet", referenced from:
      _packet_queue_flush in libIJKMediaPlayer.a(ff_ffplay.o)
      _packet_queue_get_or_buffering in libIJKMediaPlayer.a(ff_ffplay.o)
      _packet_queue_put in libIJKMediaPlayer.a(ff_ffplay.o)
      _decoder_decode_frame in libIJKMediaPlayer.a(ff_ffplay.o)
      _read_thread in libIJKMediaPlayer.a(ff_ffplay.o)
      _stream_component_close in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_get_sample_fmt_name", referenced from:
      _sdl_audio_callback in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_format_inject_global_side_data", referenced from:
      _read_thread in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_malloc", referenced from:
      _ijkmp_change_state_l in libIJKMediaPlayer.a(ijkplayer.o)
      _ijkmp_prepare_async in libIJKMediaPlayer.a(ijkplayer.o)
      _ijkmp_start in libIJKMediaPlayer.a(ijkplayer.o)
      _ijkmp_pause in libIJKMediaPlayer.a(ijkplayer.o)
      _ijkmp_seek_to_l in libIJKMediaPlayer.a(ijkplayer.o)
      _ffp_toggle_buffering_l in libIJKMediaPlayer.a(ff_ffplay.o)
      _ffp_check_buffering_l in libIJKMediaPlayer.a(ff_ffplay.o)
      ...
  "_av_strlcpy", referenced from:
      _ffp_prepare_async_l in libIJKMediaPlayer.a(ff_ffplay.o)
  "_avformat_network_init", referenced from:
      _ffp_global_init in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_dict_get", referenced from:
      _ijkmeta_get_string_l in libIJKMediaPlayer.a(ijkmeta.o)
      _ijkmeta_get_int64_l in libIJKMediaPlayer.a(ijkmeta.o)
      _read_thread in libIJKMediaPlayer.a(ff_ffplay.o)
      _stream_component_open in libIJKMediaPlayer.a(ff_ffplay.o)
      _filter_codec_opts in libIJKMediaPlayer.a(ff_cmdutils.o)
  "_av_frame_move_ref", referenced from:
      _audio_thread in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_find_best_stream", referenced from:
      _read_thread in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_dict_set", referenced from:
      _ijkmeta_set_avformat_context_l in libIJKMediaPlayer.a(ijkmeta.o)
      _ffp_set_format_option in libIJKMediaPlayer.a(ff_ffplay.o)
      _read_thread in libIJKMediaPlayer.a(ff_ffplay.o)
      _stream_component_open in libIJKMediaPlayer.a(ff_ffplay.o)
      _filter_codec_opts in libIJKMediaPlayer.a(ff_cmdutils.o)
  "_avcodec_find_decoder", referenced from:
      _ijkmeta_set_avformat_context_l in libIJKMediaPlayer.a(ijkmeta.o)
      _stream_component_open in libIJKMediaPlayer.a(ff_ffplay.o)
      _filter_codec_opts in libIJKMediaPlayer.a(ff_cmdutils.o)
  "_av_base64_decode", referenced from:
      +[IJKFFMrl base64Decode:] in libIJKMediaPlayer.a(IJKFFMrl.o)
  "_av_frame_get_best_effort_timestamp", referenced from:
      _decoder_decode_frame in libIJKMediaPlayer.a(ff_ffplay.o)
  "_sws_freeContext", referenced from:
      _stream_close in libIJKMediaPlayer.a(ff_ffplay.o)
  "_avcodec_get_class", referenced from:
      _filter_codec_opts in libIJKMediaPlayer.a(ff_cmdutils.o)
  "_av_get_profile_name", referenced from:
      _ijkmeta_set_avformat_context_l in libIJKMediaPlayer.a(ijkmeta.o)
  "_av_mallocz", referenced from:
      +[IJKFFMrl base64Decode:] in libIJKMediaPlayer.a(IJKFFMrl.o)
      _ijkmp_create in libIJKMediaPlayer.a(ijkplayer.o)
      _ffp_create in libIJKMediaPlayer.a(ff_ffplay.o)
      _ffp_prepare_async_l in libIJKMediaPlayer.a(ff_ffplay.o)
      _setup_find_stream_info_opts in libIJKMediaPlayer.a(ff_cmdutils.o)
  "_av_log", referenced from:
      _ffp_destroy in libIJKMediaPlayer.a(ff_ffplay.o)
      _ffp_prepare_async_l in libIJKMediaPlayer.a(ff_ffplay.o)
      _ffp_video_thread in libIJKMediaPlayer.a(ff_ffplay.o)
      _ffp_video_refresh_thread in libIJKMediaPlayer.a(ff_ffplay.o)
      _read_thread in libIJKMediaPlayer.a(ff_ffplay.o)
      _stream_component_open in libIJKMediaPlayer.a(ff_ffplay.o)
      _sdl_audio_callback in libIJKMediaPlayer.a(ff_ffplay.o)
      ...
  "_av_get_bits_per_sample", referenced from:
      _ijkmeta_set_avformat_context_l in libIJKMediaPlayer.a(ijkmeta.o)
  "_sws_getCachedContext", referenced from:
      _SDL_VoutFFmpeg_ConvertFrame in libIJKMediaPlayer.a(ijksdl_vout_overlay_ffmpeg.o)
  "_swr_alloc_set_opts", referenced from:
      _sdl_audio_callback in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_guess_sample_aspect_ratio", referenced from:
      _ffp_video_thread in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_buffer_unref", referenced from:
      _overlay_free_l in libIJKMediaPlayer.a(ijksdl_vout_overlay_ffmpeg.o)
  "_avcodec_close", referenced from:
      _stream_component_close in libIJKMediaPlayer.a(ff_ffplay.o)
  "_avformat_alloc_context", referenced from:
      _read_thread in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_gettime_relative", referenced from:
      _ffp_prepare_async_l in libIJKMediaPlayer.a(ff_ffplay.o)
      _ffp_video_refresh_thread in libIJKMediaPlayer.a(ff_ffplay.o)
      _get_clock in libIJKMediaPlayer.a(ff_ffplay.o)
      _sync_clock_to_slave in libIJKMediaPlayer.a(ff_ffplay.o)
      _stream_toggle_pause_l in libIJKMediaPlayer.a(ff_ffplay.o)
      _read_thread in libIJKMediaPlayer.a(ff_ffplay.o)
      _sdl_audio_callback in libIJKMediaPlayer.a(ff_ffplay.o)
      ...
  "_av_codec_set_lowres", referenced from:
      _stream_component_open in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_rescale_q", referenced from:
      _decoder_decode_frame in libIJKMediaPlayer.a(ff_ffplay.o)
  "_av_free", referenced from:
      +[IJKFFMrl base64Decode:] in libIJKMediaPlayer.a(IJKFFMrl.o)
      _ffp_destroy in libIJKMediaPlayer.a(ff_ffplay.o)
      _stream_close in libIJKMediaPlayer.a(ff_ffplay.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bbcallen** [comment]
Can not reproduce.

**Comment by qazmoon** [comment]
可能是你加了binutils，然后还把 bingutils的path设置到了 $PATH的最前，结果导致编译时出现符号前加下划线的现象。
