### ISSUE TITLE
分片视频播放失败

### ISSUE THREAD

**Issue by sagexy** [Bilibili/ijkplayer#1946]
编译用的是module-default.sh

ffconcat.txt文件为：
ffconcat version 1.0
file 'http://192.168.1.54/1.flv'
duration 188
file 'http://192.168.1.54/2.flv'
duration 205

使用demo工程中的代码如下：
  NSString *path = [[NSBundle mainBundle] pathForResource:@"ffconcat" ofType:@"txt"];
  NSString *playPath = [NSString stringWithFormat:@"concat:/%@",path];
  [IJKVideoViewController presentFromViewController:self withTitle:@"ffconcat" URLString:playPath completion:^{
        
    }];

添加option
    [options setFormatOptionValue:@"0" forKey:@"safe"];
    [options setFormatOptionValue:@"concat,file,subfile,duration" forKey:@"protocol_whitelist"];

![image](https://cloud.githubusercontent.com/assets/4734448/18266740/c082e888-744e-11e6-9001-b2dddeb64182.png)

播放时报错：
===== custom modules begin =====
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff3.1--ijk0.6.1--20160824--001
ijkmp_set_inject_opaque(0x15e11d5b0)
ijkmp_set_inject_opaque()=void
2016-09-06 16:19:17.845 IJKMediaDemo[85168:1756429] OK setup GL
ijkmp_ios_set_view(glView=0x15e138280)
ijkmp_ios_set_view(glView=0x15e138280)=void
2016-09-06 16:19:17.854 IJKMediaDemo[85168:1756429] invalidateRenderBuffer
2016-09-06 16:19:17.855 IJKMediaDemo[85168:1756477] IJKSDLGLView: setupDisplay not ready
2016-09-06 16:19:17.855 IJKMediaDemo[85168:1756429] Finding Airport devices.
ijkmp_set_data_source(url="concat://var/containers/Bundle/Application/9810D631-8EDD-4F3F-9DC5-34346C2FDFB2/IJKMediaDemo.app/ffconcat.txt")
ijkmp_set_data_source(url="concat://var/containers/Bundle/Application/9810D631-8EDD-4F3F-9DC5-34346C2FDFB2/IJKMediaDemo.app/ffconcat.txt")=0
ijkmp_prepare_async()
===== versions =====
FFmpeg       : ff3.1--ijk0.6.1--20160824--001
libavutil    : 55.27.100
libavcodec   : 57.48.101
libavformat  : 57.40.101
libswscale   : 4.1.100
libswresample: 2.1.100
===== options =====
player-opts : video-pictq-size             = 3
player-opts : overlay-format               = fcc-_es2
player-opts : max-fps                      = 30
player-opts : framedrop                    = 0
player-opts : videotoolbox-max-frame-width = 960
player-opts : videotoolbox                 = 0
player-opts : start-on-prepared            = 1
format-opts : ijkapplication               = 5873304064
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : protocol_whitelist           = concat,file,subfile,duration
format-opts : timeout                      = 30000000
format-opts : reconnect                    = 1
format-opts : safe                         = 0
===================
ijkmp_prepare_async()=0
2016-09-06 16:19:17.908 IJKMediaDemo[85168:1756429] invalidateRenderBuffer
2016-09-06 16:19:17.908 IJKMediaDemo[85168:1756479] IJKSDLGLView: setupDisplay not ready
2016-09-06 16:19:17.921 IJKMediaDemo[85168:1756429] invalidateRenderBuffer
2016-09-06 16:19:17.921 IJKMediaDemo[85168:1756479] IJKSDLGLView: setupDisplay not ready
Format concat probed with size=2048 and score=100
Protocol not on whitelist 'concat,file,subfile,duration'!
Impossible to open 'http://192.168.1.54/1.flv'
Statistics: 88 bytes read, 0 seeks
concat://var/containers/Bundle/Application/9810D631-8EDD-4F3F-9DC5-34346C2FDFB2/IJKMediaDemo.app/ffconcat.txt: Invalid argument
2016-09-06 16:19:17.942 IJKMediaDemo[85168:1756429] FFP_MSG_ERROR: 0
2016-09-06 16:19:17.943 IJKMediaDemo[85168:1756429] IJKMPMoviePlayBackStateDidChange 2: paused
2016-09-06 16:19:17.943 IJKMediaDemo[85168:1756429] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1
2016-09-06 16:19:22.896 IJKMediaDemo[85168:1756429] invalidateRenderBuffer
2016-09-06 16:19:22.898 IJKMediaDemo[85168:1756429] invalidateRenderBuffer
2016-09-06 16:19:22.898 IJKMediaDemo[85168:1756479] IJKSDLGLView:display: unable to tryLock GL active: 0
2016-09-06 16:19:22.898 IJKMediaDemo[85168:1756479] IJKSDLGLView: setupDisplay not ready
ijkmp_stop()
ijkmp_stop()=0
ijkmp_shutdown_l()
wait for read_tid
wait for video_refresh_tid
ijkmp_shutdown_l()=void
ijkmp_dec_ref(): ref=0
ijkmp_shutdown_l()
ijkmp_shutdown_l()=void
aout_close_audio()

貌似还是白名单问题，请大大赐教，万分感谢！

**Comment by ctiao** [comment]
Protocol not on whitelist 'concat,file,subfile,duration'!
Impossible to open 'http://192.168.1.54/1.flv'

https://www.ffmpeg.org/ffmpeg-protocols.html#Protocol-Options

**Comment by sagexy** [comment]
@ctiao 看了https://www.ffmpeg.org/ffmpeg-protocols.html#Protocol-Options这个，是不是在代码里面添加[options setFormatOptionValue:@"concat,file,subfile,duration" forKey:@"protocol_whitelist"];

没怎么明白

**Comment by sagexy** [comment]
when I put the ffconcat.txt on server 

 NSString *playPath = @"http://192.168.1.54/ffconcat.txt";

IJKFFOptions *options = [IJKFFOptions optionsByDefault];
self.player = [[IJKFFMoviePlayerController alloc] initWithContentURLString:playPath withOptions:options];

it works but I don't have set [options setFormatOptionValue:@"concat,file,subfile,duration" forKey:@"protocol_whitelist"];

so is the ffconcat.txt can be only put on server? since when I put the ffconcat.txt in bundle it doesn't work.

**Comment by michalliu** [comment]
@sagexy  请问这个问题现在解决了没，可以播吗
