### ISSUE TITLE
getCurrentPosition播放越久越不准导致我们自己加载的字幕完全乱套

### ISSUE THREAD

**Issue by passerbya** [Bilibili/ijkplayer#1950]
在android手机上配置越低getCurrentPosition比视频越晚，而且播放越久偏差越大，看issues很多人提到时间戳不准的问题，不知道有没解决计划

**Comment by raymond1012** [comment]
音画会出现不同步吗，请提供参考机型和demo程序

**Comment by passerbya** [comment]
音画是同步的，是CurrentPosition时间戳不准，我们用了外挂字幕需要知道视频播放到什么位置了。http://app.5233game.com/rrdict1.0_beta10.apk 可以试一下我们这个app

**Comment by passerbya** [comment]
机型可以用华为p6，或者联想A850

**Comment by passerbya** [comment]
搜索“meticulous”点“影视集播放”，这个是视频连播的。播放完一段，currentPosition就偏差一点，播的越久偏差越多，每次播完一段我都加了200ms偏差还是不够
播放开始时直接点下一首时间又比较正常的。而且用小米max currentPosition 又比较准，只偏差了40ms

**Comment by ctiao** [comment]
开了mediacodec？

**Comment by raymond1012** [comment]
播放下一段的时候是不是有seek操作

**Comment by passerbya** [comment]
不好意思，是由于我们在timer中10毫秒做了一次handler发消息显示、隐藏字幕导致手机卡顿引起的。现在已经好了
http://app.5233game.com/rrdict1.0_beta11.apk

**Comment by Fionashow** [comment]
@passerbya  你好，你提供的应用链接已经失效了，能否提供最新的应用地址。
