### ISSUE TITLE
JCVideoPlayerStandard cant play mp4!

### ISSUE THREAD

**Issue by mbf5923** [Bilibili/ijkplayer#1953]
i have a file on my server converted to mp4 with ffmpeg.
i need play that on my android app.i use JCVideoPlayerStandard  for play but 

`09-07 11:04:04.132 9873-9873/com.sina.barbiq I/JieCaoVideoPlayer: onClick start [1008862606] 
09-07 11:04:04.212 9873-9873/com.sina.barbiq D/JieCaoVideoPlayer: prepareVideo [1008862606] 
09-07 11:04:04.212 9873-9873/com.sina.barbiq D/JieCaoVideoPlayer: addTextureView [1008862606] 
09-07 11:04:04.257 9873-10700/com.sina.barbiq D/IJKMEDIA: IjkMediaPlayer_release
09-07 11:04:04.260 9873-10700/com.sina.barbiq D/IJKMEDIA: IjkMediaPlayer_native_setup
09-07 11:04:04.260 9873-10700/com.sina.barbiq I/IJKMEDIA: av_version_info: ff3.1--ijk0.6.0--20160715--001
09-07 11:04:04.266 9873-10700/com.sina.barbiq D/IJKMEDIA: ffpipeline_create_from_android()
09-07 11:04:04.266 9873-10700/com.sina.barbiq D/IJKMEDIA: ijkmp_set_inject_opaque(0x3004b6)
09-07 11:04:04.266 9873-10700/com.sina.barbiq D/IJKMEDIA: ijkmp_set_inject_opaque()=void
09-07 11:04:04.266 9873-10700/com.sina.barbiq D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
09-07 11:04:04.266 9873-10700/com.sina.barbiq D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
09-07 11:04:04.266 9873-10700/com.sina.barbiq D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
09-07 11:04:04.270 9873-10700/com.sina.barbiq D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
09-07 11:04:04.270 9873-10700/com.sina.barbiq V/IJKMEDIA: setDataSource: path http://65.60.3.47:3000/content/78248010-62a6-11e6-902b-7b6c8ee2f733-pre.mp4
09-07 11:04:04.270 9873-10700/com.sina.barbiq D/IJKMEDIA: ijkmp_set_data_source(url="http://65.60.3.47:3000/content/78248010-62a6-11e6-902b-7b6c8ee2f733-pre.mp4")
09-07 11:04:04.270 9873-10700/com.sina.barbiq D/IJKMEDIA: ijkmp_set_data_source(url="http://65.60.3.47:3000/content/78248010-62a6-11e6-902b-7b6c8ee2f733-pre.mp4")=0
09-07 11:04:04.270 9873-10700/com.sina.barbiq D/IJKMEDIA: IjkMediaPlayer_setOptionLong
09-07 11:04:04.270 9873-10700/com.sina.barbiq D/IJKMEDIA: IjkMediaPlayer_setLoopCount
09-07 11:04:04.276 9873-10700/com.sina.barbiq W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
09-07 11:04:04.276 9873-10700/com.sina.barbiq D/IJKMEDIA: IjkMediaPlayer_prepareAsync
09-07 11:04:04.276 9873-10700/com.sina.barbiq D/IJKMEDIA: ijkmp_prepare_async()
09-07 11:04:04.276 9873-10700/com.sina.barbiq I/IJKMEDIA: ===== versions =====
09-07 11:04:04.276 9873-10700/com.sina.barbiq I/IJKMEDIA: FFmpeg       : ff3.1--ijk0.6.0--20160715--001
09-07 11:04:04.276 9873-10700/com.sina.barbiq I/IJKMEDIA: libavutil    : 55.27.100
09-07 11:04:04.277 9873-22340/com.sina.barbiq I/IJKMEDIA: SDL_RunThread: [22340] ff_msg_loop
09-07 11:04:04.277 9873-22340/com.sina.barbiq D/IJKMEDIA: message_loop
09-07 11:04:04.278 9873-22340/com.sina.barbiq D/IJKMEDIA: FFP_MSG_FLUSH:
09-07 11:04:04.281 9873-10700/com.sina.barbiq I/IJKMEDIA: libavcodec   : 57.48.101
09-07 11:04:04.289 9873-10700/com.sina.barbiq I/IJKMEDIA: libavformat  : 57.40.101
09-07 11:04:04.309 9873-10700/com.sina.barbiq I/IJKMEDIA: libswscale   : 4.1.100
09-07 11:04:04.309 9873-10700/com.sina.barbiq I/IJKMEDIA: libswresample: 2.1.100
09-07 11:04:04.309 9873-10700/com.sina.barbiq I/IJKMEDIA: ===== options =====
09-07 11:04:04.309 9873-10700/com.sina.barbiq I/IJKMEDIA: player-opts : loop                         = 1
09-07 11:04:04.309 9873-10700/com.sina.barbiq I/IJKMEDIA: format-opts : ijkinject-opaque             = 3146934
09-07 11:04:04.309 9873-10700/com.sina.barbiq I/IJKMEDIA: format-opts : ijkapplication               = -1633500736
09-07 11:04:04.309 9873-10700/com.sina.barbiq I/IJKMEDIA: ===================
09-07 11:04:04.321 9873-22345/com.sina.barbiq I/IJKMEDIA: SDL_RunThread: [22345] ff_vout
09-07 11:04:04.321 9873-10700/com.sina.barbiq D/IJKMEDIA: ijkmp_prepare_async()=0
09-07 11:04:04.321 9873-22346/com.sina.barbiq I/IJKMEDIA: SDL_RunThread: [22346] ff_read
09-07 11:04:04.347 9873-9873/com.sina.barbiq I/JieCaoVideoPlayer: onSurfaceTextureAvailable [1008862606] 
09-07 11:04:04.349 9873-10700/com.sina.barbiq I/JieCaoVideoPlayer: set surface
09-07 11:04:04.349 9873-10700/com.sina.barbiq W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
09-07 11:04:04.349 9873-10700/com.sina.barbiq D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
09-07 11:04:04.349 9873-10700/com.sina.barbiq D/IJKMEDIA: ijkmp_set_android_surface(surface=0x9f0a1a10)
09-07 11:04:04.349 9873-10700/com.sina.barbiq D/IJKMEDIA: ffpipeline_set_surface()
09-07 11:04:04.349 9873-10700/com.sina.barbiq D/IJKMEDIA: ijkmp_set_android_surface(surface=0x9f0a1a10)=void
09-07 11:04:05.210 9873-22346/com.sina.barbiq E/IJKMEDIA: Option ijkinject-opaque not found.
09-07 11:04:07.757 9873-22346/com.sina.barbiq W/IJKMEDIA: Could not find codec parameters for stream 1 (Audio: mp3 (mp4a / 0x6134706D), 44100 Hz, 2 channels, 128 kb/s): unspecified frame size
                                                          Consider increasing the value for the 'analyzeduration' and 'probesize' options
09-07 11:04:07.757 9873-22346/com.sina.barbiq I/IJKMEDIA: max_frame_duration: 10.000
09-07 11:04:07.757 9873-22346/com.sina.barbiq I/IJKMEDIA: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'http://65.60.3.47:3000/content/78248010-62a6-11e6-902b-7b6c8ee2f733-pre.mp4':
09-07 11:04:07.757 9873-22346/com.sina.barbiq I/IJKMEDIA:   Metadata:
09-07 11:04:07.757 9873-22346/com.sina.barbiq I/IJKMEDIA:     major_brand     : 
09-07 11:04:07.757 9873-22346/com.sina.barbiq I/IJKMEDIA: isom
09-07 11:04:07.757 9873-22346/com.sina.barbiq I/IJKMEDIA:     minor_version   : 
09-07 11:04:07.757 9873-22346/com.sina.barbiq I/IJKMEDIA: 512
09-07 11:04:07.757 9873-22346/com.sina.barbiq I/IJKMEDIA:     compatible_brands: 
09-07 11:04:07.757 9873-22346/com.sina.barbiq I/IJKMEDIA: isomiso2avc1mp41
09-07 11:04:07.757 9873-22346/com.sina.barbiq I/IJKMEDIA:     encoder         : 
09-07 11:04:07.757 9873-22346/com.sina.barbiq I/IJKMEDIA: Lavf57.44.100
09-07 11:04:07.757 9873-22346/com.sina.barbiq I/IJKMEDIA:   Duration: 
09-07 11:04:07.757 9873-22346/com.sina.barbiq I/IJKMEDIA: 00:00:10.10
09-07 11:04:07.757 9873-22346/com.sina.barbiq I/IJKMEDIA: , start: 
09-07 11:04:07.757 9873-22346/com.sina.barbiq I/IJKMEDIA: -0.025057
09-07 11:04:07.757 9873-22346/com.sina.barbiq I/IJKMEDIA: , bitrate: 
09-07 11:04:07.758 9873-22346/com.sina.barbiq I/IJKMEDIA: 1424 kb/s
09-07 11:04:07.758 9873-22346/com.sina.barbiq I/IJKMEDIA:     Stream #0:0
09-07 11:04:07.758 9873-22346/com.sina.barbiq I/IJKMEDIA: (und)
09-07 11:04:07.758 9873-22346/com.sina.barbiq I/IJKMEDIA: : Video: h264 (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 1291 kb/s
09-07 11:04:07.758 9873-22346/com.sina.barbiq I/IJKMEDIA: , 
09-07 11:04:07.758 9873-22346/com.sina.barbiq I/IJKMEDIA: 29.97 fps, 
09-07 11:04:07.758 9873-22346/com.sina.barbiq I/IJKMEDIA: 29.97 tbr, 
09-07 11:04:07.758 9873-22346/com.sina.barbiq I/IJKMEDIA: 30k tbn, 
09-07 11:04:07.758 9873-22346/com.sina.barbiq I/IJKMEDIA: 59.94 tbc
09-07 11:04:07.758 9873-22346/com.sina.barbiq I/IJKMEDIA:  (default)
09-07 11:04:07.758 9873-22346/com.sina.barbiq I/IJKMEDIA:     Metadata:
09-07 11:04:07.758 9873-22346/com.sina.barbiq I/IJKMEDIA:       handler_name    : 
09-07 11:04:07.758 9873-22346/com.sina.barbiq I/IJKMEDIA: VideoHandler
09-07 11:04:07.758 9873-22346/com.sina.barbiq I/IJKMEDIA:     Stream #0:1
09-07 11:04:07.758 9873-22346/com.sina.barbiq I/IJKMEDIA: (und)
09-07 11:04:07.758 9873-22346/com.sina.barbiq I/IJKMEDIA: : Audio: mp3 (mp4a / 0x6134706D), 44100 Hz, 2 channels, 128 kb/s
09-07 11:04:07.758 9873-22346/com.sina.barbiq I/IJKMEDIA:  (default)
09-07 11:04:07.758 9873-22346/com.sina.barbiq I/IJKMEDIA:     Metadata:
09-07 11:04:07.758 9873-22346/com.sina.barbiq I/IJKMEDIA:       handler_name    : 
09-07 11:04:07.758 9873-22346/com.sina.barbiq I/IJKMEDIA: SoundHandler
09-07 11:04:07.758 9873-22346/com.sina.barbiq W/IJKMEDIA: No codec could be found with id 86017
                                                          
                                                          
                                                          --------- beginning of crash
09-07 11:04:07.762 9873-22346/com.sina.barbiq A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x9f1e0997 in tid 22346 (Thread-54086)`

**Comment by raymond1012** [comment]
I have used  your url in my ijkdemo,but no problem.  can you show detail crash stack

**Comment by mbf5923** [comment]
where i can found crash stack?
i using android studio 2.1.3

**Comment by yippeesoft** [comment]
ijkplayer or JieCaoVideoPlayer? you use JCVideoPlayerStandard https://github.com/lipangit/JieCaoVideoPlayer

**Comment by mbf5923** [comment]
yes i use JCVideoPlayerStandard
in JCVideoPlayerStandard page

**Comment by prophet173** [comment]
same thing happens on some urls... strange... it`s not JCV player issue tho, its related to IJPlayer, but did not find answer there
