### ISSUE TITLE
关于有些视频有声音没图像的问题

### ISSUE THREAD

**Issue by itlws** [Bilibili/ijkplayer#1961]
请问0.6.1不是增加了mpeg4支持么，但是视频还是有声音没有图像啊？http://movement.gzstv.com/streams/video_url/835/ 是还需要设置什么么？

**Comment by Android4MediaPlayer** [comment]
打开mpeg4支持，重新编ffmpeg

**Comment by itlws** [comment]
请问具体该怎么做啊？

**Comment by yuazhen** [comment]
try using config/module-default.sh for test. this will enable ffmpeg mpeg4 support. then,
enable mediacodec and mediacodec_mpeg4 in IjkVideoView.java by following statements:
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec_mpeg4", 1);

**Comment by itlws** [comment]
可以了，谢谢了

**Comment by yjg2014** [comment]
请问@yuazhen 您说的
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec_mpeg4", 1);
是在哪儿设置的？

**Comment by yuazhen** [comment]
IjkVideoView.java in the ijkplayer-example demo.

**Comment by lijie815917** [comment]
请问是选择 config/module-default.sh，编译后按ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec_mpeg4", 1);设置就可以了吗，为什么我的不行，打开mpeg4支持还需要做什么吗@itlws @yuazhen

**Comment by bbcallen** [comment]
config/module-default.sh is for mpeg4 decoder and parser.
mediacodec_mpeg4 is for mpeg4 hardware decoder.

**Comment by lijie815917** [comment]
can you give more details@bbcallen

**Comment by lijie815917** [comment]
ok,it can work now .but https url can not play?

**Comment by powyin** [comment]
but https url can not play?

**Comment by raymond1012** [comment]
search issue
