### ISSUE TITLE
0.6.1.2打开samples报错：lib/x86/libijkffmpeg.so: has text relocations（android版 ijkplayer-example）

### ISSUE THREAD

**Issue by xc20021** [Bilibili/ijkplayer#1964]
求助，版本0.6.1.2 android模拟器，求解打开samples列表文件原因和解决方案

----------------------- 大概错误信息如下 -------------------------
09-09 17:20:03.390 2555-2677/tv.danmaku.ijk.media.example E/Surface: getSlotFromBufferLocked: unknown buffer: 0xeaaaa800

 java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/tv.danmaku.ijk.media.example-1/lib/x86/libijkffmpeg.so: has text relocations

----------------------- 具体报错信息如下附件 -------------------------
[报错内容.txt](https://github.com/Bilibili/ijkplayer/files/463664/default.txt)

**Comment by tanhx2008** [comment]
target修改为22，或者用ndk最新版本编译下

**Comment by xc20021** [comment]
已经自行找到已存在的解决方案，谢谢。参考 #953 
https://github.com/Bilibili/ijkplayer/pull/953/commits/990796bbcb4ffb8ef4e0f28fe984d302b1ddb823
