### ISSUE TITLE
URL 播放不了

### ISSUE THREAD

**Issue by Wxy1** [Bilibili/ijkplayer#1977]
http://www.yifengke.com/videoplay?id=bd284c90-76f8-11e5-a4ae-d38fad740cd3/5e5eb340-4810-11e6-bd93-e39020f05b37
这是我的地址,WebView,帮忙解决下 谢谢

**Comment by ctiao** [comment]
> [http @ 0x7fba63d3f3a0] Stream ends prematurely at 0, should be 21125893
http://www.yifengke.com/videoplay?id=bd284c90-76f8-11e5-a4ae-d38fad740cd3/5e5eb340-4810-11e6-bd93-e39020f05b37: Input/output error

**Comment by Android4MediaPlayer** [comment]
It works well.
