### ISSUE TITLE
arm-linux-androideabi-gcc.exe: error: CreateProcess: No such file or directory

### ISSUE THREAD

**Issue by liiijz** [Bilibili/ijkplayer#1984]
I compile the project using cygwin on Windows, when link the so library, I got this error
我在Windows上使用cygwin编译，编译是OK的 但是最后生成so的时候报这个错误
arm-linux-androideabi-gcc.exe: error: CreateProcess: No such file or directory
--------------------
[*] link ffmpeg
--------------------

link compat/*.o
link libavcodec/*.o
link libavcodec/arm/*.o
link libavfilter/*.o
link libavformat/*.o
link libavutil/*.o
link libavutil/arm/*.o
link libswresample/*.o
link libswresample/arm/*.o
link libswscale/*.o
link libswscale/arm/*.o
arm-linux-androideabi-gcc.exe: error: CreateProcess: No such file or directory

各位牛人，这个是怎么回事呢？
Any suggestion?

**Comment by bbcallen** [comment]
No support for cygwin.

**Comment by chinazhangwenwei** [comment]
我看用法上说的 有用cygwin编译的啊 这个问题怎么解决啊

**Comment by ArthurWangxh** [comment]
hmm, this happened to me, frustrated, hope someone can solve it. @bbcallen @chinazhangwenwei

**Comment by rb0urd0n** [comment]
I read somewhere else that it can be a command length problem... Hope it will help
