### ISSUE TITLE
Settings {first,next,last}-high-water-mark-ms disables HW acceleration?

### ISSUE THREAD

**Issue by ened** [Bilibili/ijkplayer#1986]
On iOS, setting these options:

```
let opts = IJKFFOptions.optionsByDefault()
opts.setPlayerOptionIntValue(5 * 1000, forKey: "first-high-water-mark-ms")
opts.setPlayerOptionIntValue(10 * 1000, forKey: "next-high-water-mark-ms")
opts.setPlayerOptionIntValue(20 * 1000, forKey: "last-high-water-mark-ms")
```

Seems to disable the HW acceleration, as the logs shows a lot of messages like this:
```
[swscaler @ 0x1098a4000] No accelerated colorspace conversion found from yuv420p to rgba.
```

Is this working as intended?

iOS 10, iPhone 5s.

**Comment by bbcallen** [comment]
Yes, it's very likely a rare pixel buffer, so no one implement SIMD for it.

**Comment by ened** [comment]
OK, I'm assuming this might get added/fixed in a future version of ffmpeg. Thank you @bbcallen.
