### ISSUE TITLE
都有哪些设备支持h265编码呢

### ISSUE THREAD

**Issue by theewind** [Bilibili/ijkplayer#1987]
目前手头有iPhone5s ip6  iPad Air2 ，采用HEVC压缩和解码，发现起来就崩溃，是因为设备本身不支持么？目前有那些设备支持H265呢

**Comment by bbcallen** [comment]
I don't think iOS support hevc.

**Comment by wongzigii** [comment]
https://www.macrumors.com/guide/hevc-video-macos-high-sierra-ios-11/
