### ISSUE TITLE
crash !!!

### ISSUE THREAD

**Issue by we1019000306** [Bilibili/ijkplayer#1995]
Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
===== custom modules begin =====
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff3.1--ijk0.6.1--20160824--001
ijkmp_set_inject_opaque(0x146ab9fd0)
ijkmp_set_inject_opaque()=void
2016-09-19 11:04:18.328 News[345:44782] OK setup GL
ijkmp_ios_set_view(glView=0x146abf980)
ijkmp_ios_set_view(glView=0x146abf980)=void
2016-09-19 11:04:18.334 News[345:44782] invalidateRenderBuffer

**Comment by we1019000306** [comment]
[player prepareToPlay];
IPhone run XCode after prepareToPlay XCode crashed.I have already config FFmpeg.But Simulators run without any problems.

**Comment by we1019000306** [comment]
Demo has crashed too..

**Comment by we1019000306** [comment]
![image](https://cloud.githubusercontent.com/assets/15644020/18700205/91861c56-8008-11e6-966e-a50e7d3e6d91.png)
===== custom modules begin =====
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff3.1--ijk0.6.1--20160824--001
ijkmp_set_inject_opaque(0xfa8f8e0)
ijkmp_set_inject_opaque()=void
2016-09-21 14:36:10.679 WSCN[38194:120672] OK setup GL
ijkmp_ios_set_view(glView=0xfa90100)
ijkmp_ios_set_view(glView=0xfa90100)=void
2016-09-21 14:36:10.680 WSCN[38194:120672] invalidateRenderBuffer
2016-09-21 14:36:10.680 WSCN[38194:120713] IJKSDLGLView: setupDisplay not ready
ijkmp_set_data_source(url="http://pili-playback.wscn.wallstcn.com/wscn/chat_74_0911012717_wallstreetcn_com.m3u8?start=0&end=0")
ijkmp_set_data_source(url="http://pili-playback.wscn.wallstcn.com/wscn/chat_74_0911012717_wallstreetcn_com.m3u8?start=0&end=0")=0
ijkmp_prepare_async()
===== versions =====
FFmpeg       : ff3.1--ijk0.6.1--20160824--001
libavutil    : 55.27.100
libavcodec   : 57.48.101
libavformat  : 57.40.101
libswscale   : 4.1.100
libswresample: 2.1.100
===== options =====
player-opts : videotoolbox-max-frame-width = 960
player-opts : overlay-format               = fcc-_es2
player-opts : framedrop                    = 0
player-opts : max-fps                      = 30
player-opts : video-pictq-size             = 3
player-opts : videotoolbox                 = 0
player-opts : start-on-prepared            = 1
format-opts : ijkapplication               = 262733616
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : timeout                      = 30000000
format-opts : reconnect                    = 1
format-opts : safe                         = 0
===================
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/liumingyuan/Library/Developer/CoreSimulator/Devices/5169E525-C797-4E26-9A5C-10D197D1A455/data/Containers/Bundle/Application/E46F6CAD-05F6-4401-8EF0-BA24F742B8E1/WSCN.app/WSCN
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libSystem.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/liumingyuan/Library/Developer/CoreSimulator/Devices/5169E525-C797-4E26-9A5C-10D197D1A455/data/Containers/Bundle/Application/E46F6CAD-05F6-4401-8EF0-BA24F742B8E1/WSCN.app/WSCN
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libSystem.dylib

**Comment by we1019000306** [comment]
crash and here these logs

**Comment by we1019000306** [comment]
![image](https://cloud.githubusercontent.com/assets/15644020/18700374/7eea28c0-8009-11e6-928d-50b288ae5f82.png)

**Comment by we1019000306** [comment]
![image](https://cloud.githubusercontent.com/assets/15644020/18700468/0a01f01e-800a-11e6-84c1-f89d51fe59ca.png)

**Comment by we1019000306** [comment]
![image](https://cloud.githubusercontent.com/assets/15644020/18700529/54639e1e-800a-11e6-9d11-e409c1462924.png)

**Comment by we1019000306** [comment]
![image](https://cloud.githubusercontent.com/assets/15644020/18700930/7aabd9b8-800c-11e6-9d35-d48c10caadf4.png)

**Comment by we1019000306** [comment]
Those are stack info,and the last crash happens to clock_gettimexxxxxxx

**Comment by bltv** [comment]
get the same crash, xcode8 and ios 9.3

**Comment by we1019000306** [comment]
yeap, the same to u,Xcode8 ios 9.3

**Comment by we1019000306** [comment]
Xcode8,ios 10 is OK

**Comment by ourui** [comment]
I have the same problem!  The device system version is 9.3,  and It works on simulator.

**Comment by willerce** [comment]
遇到相同的问题，Xcode 8 和 iOS 10 正常，iOS 9 时 crash。

**Comment by willerce** [comment]
报错信息：

```
ijkmp_set_data_source(url="rtmp://live.hkstv.hk.lxdns.com/live/hks")
ijkmp_set_data_source(url="rtmp://live.hkstv.hk.lxdns.com/live/hks")=0
ijkmp_prepare_async()
remove 'timeout' option for rtmp.
===== versions =====
ijkplayer    : 
FFmpeg       : ff3.1--ijk0.6.1--20160824--001
libavutil    : 55.27.100
libavcodec   : 57.48.101
libavformat  : 57.40.101
libswscale   : 4.1.100
libswresample: 2.1.100
===== options =====
player-opts : video-pictq-size             = 3
player-opts : overlay-format               = fcc-_es2
player-opts : max-fps                      = 30
player-opts : framedrop                    = 0
player-opts : videotoolbox-max-frame-width = 960
player-opts : videotoolbox                 = 0
player-opts : start-on-prepared            = 1
format-opts : ijkapplication               = 140400104641792
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : safe                         = 0
format-opts : reconnect                    = 1
===================
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/willerce/Library/Developer/CoreSimulator/Devices/8060D8C2-9A4E-457C-919A-E06CE8D21626/data/Containers/Bundle/Application/7855B593-36B7-4260-A51C-9FC5711A0459/YLB.app/YLB
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 9.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libSystem.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/willerce/Library/Developer/CoreSimulator/Devices/8060D8C2-9A4E-457C-919A-E06CE8D21626/data/Containers/Bundle/Application/7855B593-36B7-4260-A51C-9FC5711A0459/YLB.app/YLB
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 9.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libSystem.dylib

(lldb) 
```

**Comment by bbcallen** [comment]
Seems an FFmpeg issue.

**Comment by willerce** [comment]
@bbcallen 我尝试从 master 拉下来重新编译后，播放可以正常播放了。

但是，提示框提示：

Unexpected FFmpeg Version
actual: ff3.1--ijk0.6.2--20160926--001
expect: ff3.1--ijk0.6.1--20160824--001

**Comment by zwp** [comment]
@willerce 我也遇到这个问题了，请问该怎么更新呢？我之前是打包成framework集成到工程里的

**Comment by willerce** [comment]
@zwp 我提交了PR修复了这个小问题了 https://github.com/Bilibili/ijkplayer/pull/2057

**Comment by zwp** [comment]
@willerce 谢了 ，我重新拉取编译，问题已解决
