### ISSUE TITLE
ios hardware decoding with videoToolBox has memory leak

### ISSUE THREAD

**Issue by playervideo** [Bilibili/ijkplayer#1997]
![image](https://cloud.githubusercontent.com/assets/13842787/18627579/50d8d7b4-7e8e-11e6-8bfb-d6e99cea8458.png)

**Comment by playervideo** [comment]
![image](https://cloud.githubusercontent.com/assets/13842787/18629657/a86420be-7e99-11e6-8abd-c4e74c4b3390.png)
![image](https://cloud.githubusercontent.com/assets/13842787/18629661/afae3df0-7e99-11e6-8d6e-e3792ddd66db.png)
![image](https://cloud.githubusercontent.com/assets/13842787/18629666/b8d60570-7e99-11e6-9398-047ef610be29.png)

**Comment by xinzhengzhang** [comment]
@playervideo 
What's your instruments version?

**Comment by wbi1987** [comment]
7.3.1 and 8.0

**Comment by xinzhengzhang** [comment]
xcode8.0?

**Comment by wbi1987** [comment]
xcode 7.3.1 and xcode8.0 both exist

**Comment by xinzhengzhang** [comment]
Can you provide a entire project zip?

**Comment by wbi1987** [comment]
I test with ijk demo，iPhone 6s  9.3.5

**Comment by playervideo** [comment]
8.1.2的系统上没有泄漏，8.4，9.35，10.0的系统上均有泄漏

**Comment by xinzhengzhang** [comment]
Has been fixed.
