### ISSUE TITLE
iOS xcode8 build crashed

### ISSUE THREAD

**Issue by zhushaodong** [Bilibili/ijkplayer#2000]
I updated xcode8 and build ijkplayer for iOS. Everything is OK. But the demo crash.  Has it supported xcode8 and iOS10 ?

**Comment by zhushaodong** [comment]
Simulators is OK but iPhone crashed once start play.

**Comment by zhushaodong** [comment]
the error debug at

**Comment by mayudong1** [comment]
I got the same problem. 
xcode8 + ios10 is OK, but xcode8 + ios9 crashed once start play

**Comment by lrs0304** [comment]
Because Xcode8 generate config.h and `#define HAVE_CLOCK_GETTIME 1`，and the crash will happen in the function `int64_t av_gettime_relative(void)`。

**Comment by xinzhengzhang** [comment]
[400d7e](https://github.com/Bilibili/ijkplayer/commit/400d7e367f69a657713db0afbdc875641003cfe9) 
 Fixed.
Thx~

**Comment by GrayLuo** [comment]
拉取了最新的代码，重新编译，Xcode8  iOS 9.3.2 iPhone 5S编译demo,播放，依然crash在av_gettime_relative处，请问这个如何修复的？@bbcallen @xinzhengzhang

**Comment by LiuLongChang** [comment]
The same question, and i do not know how to resolve it

**Comment by LiuLongChang** [comment]
the question appear when i call  "prepareToPlay" function

**Comment by GrayLuo** [comment]
新版本已解，更新至最新版本

**Comment by Martin-Lv** [comment]
@xinzhengzhang 查看了commit，主要是更新了ffmpeg版本。请问这个问题是ffmpeg官方修复，还是B站自己修复的？由于我们的iOS app使用了3.0版本的ffmpeg，无法更新到最新版，所以希望能知道一些关于此修复的细节。多谢！

**Comment by xinzhengzhang** [comment]
https://github.com/Bilibili/FFmpeg/commit/dd851ed5932f8a1ca28075f1d2dc2591f0b1a055

**Comment by Naituw** [comment]
@xinzhengzhang 
Shouldn't av_gettime_relative_is_monotonic apply this fix too?

https://github.com/Bilibili/FFmpeg/blob/dd851ed5932f8a1ca28075f1d2dc2591f0b1a055/libavutil/time.c#L69

**Comment by xinzhengzhang** [comment]
@Naituw 
You are right, but ffmpeg has fixed this in https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/0e8b68a2c4031e25082603ad88711be12210d41f
And it might be applied in n3.3
ijk will remove the private patch and applying this after n3.3 released.
