### ISSUE TITLE
播放有些视频没有声音

### ISSUE THREAD

**Issue by FatPaper** [Bilibili/ijkplayer#2002]
我编译的是0.6.2 的default版本，但是会出现一些视频有画面没有声音09-20 17:07:50.729 31523-31523/com.ppfuns.smi I/IJKMEDIA: av_version_info: ff3.1--ijk0.6.1--20160824--001
09-20 17:07:50.732 31523-31523/com.ppfuns.smi W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: ===== versions =====
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: FFmpeg       : ff3.1--ijk0.6.1--20160824--001
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: libavutil    : 55.27.100
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: libavcodec   : 57.48.101
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: libavformat  : 57.40.101
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: libswscale   : 4.1.100
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: libswresample: 2.1.100
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: ===== options =====
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: player-opts : mediacodec                   = 1
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: player-opts : mediacodec-auto-rotate       = 0
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: player-opts : opensles                     = 0
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: player-opts : overlay-format               = 842225234
09-20 17:07:50.732 31523-14769/com.ppfuns.smi I/IJKMEDIA: SDL_RunThread: [14769] ff_msg_loop
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: player-opts : start-on-prepared            = 0
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: player-opts : framedrop                    = 1
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: format-opts : ijkapplication               = -771155904
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: format-opts : http-detect-range-support    = 0
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: format-opts : timeout                      = 10000000
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: format-opts : reconnect                    = 1
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: codec-opts  : mediacodec-mpeg2             = 1
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: codec-opts  : mediacodec-all-videos        = 1
09-20 17:07:50.732 31523-31523/com.ppfuns.smi I/IJKMEDIA: ===================
09-20 17:07:50.735 31523-14770/com.ppfuns.smi I/IJKMEDIA: SDL_RunThread: [14770] ff_vout
09-20 17:07:50.735 31523-14771/com.ppfuns.smi I/IJKMEDIA: SDL_RunThread: [14771] ff_read
09-20 17:07:50.736 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
09-20 17:07:50.736 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
09-20 17:07:50.752 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
09-20 17:07:50.808 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
09-20 17:07:50.816 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
09-20 17:07:50.821 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
09-20 17:07:50.873 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 3
09-20 17:07:50.874 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
09-20 17:07:50.890 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
09-20 17:07:50.909 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 4
09-20 17:07:50.910 31523-14771/com.ppfuns.smi E/IJKMEDIA: Option http-detect-range-support not found.
09-20 17:07:50.912 31523-14771/com.ppfuns.smi I/IJKMEDIA: parser not found for codec mp3, packets or times may be invalid.
09-20 17:07:50.961 31523-14771/com.ppfuns.smi I/IJKMEDIA: parser not found for codec mp3, packets or times may be invalid.
09-20 17:07:52.401 31523-14771/com.ppfuns.smi I/IJKMEDIA: max_analyze_duration 7000000 reached at 7000000 microseconds st:0
09-20 17:07:52.406 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 3
09-20 17:07:52.409 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
09-20 17:07:52.529 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
09-20 17:07:52.549 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 4
09-20 17:07:52.880 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 3
09-20 17:07:52.881 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
09-20 17:07:52.901 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
09-20 17:07:52.910 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 4
09-20 17:07:52.911 31523-14771/com.ppfuns.smi W/IJKMEDIA: Could not find codec parameters for stream 1 (Audio: mp3 ([3][0][0][0] / 0x0003), 0 channels): unspecified frame size
                                                          Consider increasing the value for the 'analyzeduration' and 'probesize' options
09-20 17:07:52.911 31523-14771/com.ppfuns.smi I/IJKMEDIA: max_frame_duration: 10.000
09-20 17:07:52.911 31523-14771/com.ppfuns.smi I/IJKMEDIA: Input #0, mpegts, from 'http://192.168.1.85:8080/vod/15_2169.mp4':
09-20 17:07:52.911 31523-14771/com.ppfuns.smi I/IJKMEDIA:   Duration: 
09-20 17:07:52.911 31523-14771/com.ppfuns.smi I/IJKMEDIA: 00:45:36.72
09-20 17:07:52.911 31523-14771/com.ppfuns.smi I/IJKMEDIA: , start: 
09-20 17:07:52.911 31523-14771/com.ppfuns.smi I/IJKMEDIA: 0.887022
09-20 17:07:52.911 31523-14771/com.ppfuns.smi I/IJKMEDIA: , bitrate: 
09-20 17:07:52.911 31523-14771/com.ppfuns.smi I/IJKMEDIA: 2768 kb/s
09-20 17:07:52.911 31523-14771/com.ppfuns.smi I/IJKMEDIA:   Program 1 
09-20 17:07:52.912 31523-14771/com.ppfuns.smi I/IJKMEDIA:     Stream #0:0
09-20 17:07:52.912 31523-14771/com.ppfuns.smi I/IJKMEDIA: [0x200]
09-20 17:07:52.912 31523-14771/com.ppfuns.smi I/IJKMEDIA: : Video: h264, 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, left), 1280x720 [SAR 1:1 DAR 16:9], 0/1
09-20 17:07:52.912 31523-14771/com.ppfuns.smi I/IJKMEDIA: , 
09-20 17:07:52.912 31523-14771/com.ppfuns.smi I/IJKMEDIA: 25 fps, 
09-20 17:07:52.912 31523-14771/com.ppfuns.smi I/IJKMEDIA: 25 tbr, 
09-20 17:07:52.912 31523-14771/com.ppfuns.smi I/IJKMEDIA: 90k tbn, 
09-20 17:07:52.912 31523-14771/com.ppfuns.smi I/IJKMEDIA: 50 tbc
09-20 17:07:52.912 31523-14771/com.ppfuns.smi I/IJKMEDIA:     Stream #0:1
09-20 17:07:52.912 31523-14771/com.ppfuns.smi I/IJKMEDIA: [0x201]
09-20 17:07:52.912 31523-14771/com.ppfuns.smi I/IJKMEDIA: : Audio: mp3 ([3][0][0][0] / 0x0003), 0 channels
09-20 17:07:52.913 31523-14771/com.ppfuns.smi I/IJKMEDIA: Ignoring NAL type 9 in extradata
09-20 17:07:52.920 31523-14771/com.ppfuns.smi I/IJKMEDIA: API-Level: 23
09-20 17:07:52.920 31523-14771/com.ppfuns.smi I/IJKMEDIA: ffpipenode_create_video_decoder_from_android_mediacodec: MediaCodec: H264_HIGH: enabled
09-20 17:07:52.920 31523-14771/com.ppfuns.smi I/IJKMEDIA: AMediaFormat: video/avc, 1280x720
09-20 17:07:52.921 31523-14771/com.ppfuns.smi E/IJKMEDIA: csd-0: naked
09-20 17:07:52.921 31523-14771/com.ppfuns.smi I/IJKMEDIA: amc: rotate notify: 0
09-20 17:07:52.929 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onSelectCodec: mime=video/avc, profile=100, level=41
09-20 17:07:53.035 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: candidate codec: OMX.IMG.MSVDX.Decoder.AVC rank=800
09-20 17:07:53.040 31523-14771/com.ppfuns.smi I/IjkMediaCodecInfo:  High Profile Level 51 (8,32768)
09-20 17:07:53.041 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: candidate codec: OMX.google.h264.decoder rank=200
09-20 17:07:53.041 31523-14771/com.ppfuns.smi I/IjkMediaCodecInfo:  High Profile Level 52 (8,65536)
09-20 17:07:53.042 31523-14771/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: selected codec: OMX.IMG.MSVDX.Decoder.AVC rank=800
09-20 17:07:53.057 31523-14771/com.ppfuns.smi E/IJKMEDIA: configure acodec:0x1006f2 format:0x1006da: surface:0x1006e2
09-20 17:07:53.105 31523-14771/com.ppfuns.smi I/IJKMEDIA: reconfigure_codec_l:new acodec: 0xd09f2960
09-20 17:07:53.105 31523-14771/com.ppfuns.smi I/IJKMEDIA: VideoCodec: MediaCodec, OMX.IMG.MSVDX.Decoder.AVC
09-20 17:07:53.105 31523-14771/com.ppfuns.smi W/IJKMEDIA: fps: 25.000000 (normal)
09-20 17:07:53.105 31523-14771/com.ppfuns.smi W/IJKMEDIA: fps: 25.000000 (normal)
09-20 17:07:53.105 31523-14827/com.ppfuns.smi I/IJKMEDIA: SDL_RunThread: [14827] ff_video_dec
09-20 17:07:53.107 31523-14828/com.ppfuns.smi I/IJKMEDIA: SDL_RunThread: [14828] amediacodec_input_thread
09-20 17:07:53.207 31523-14771/com.ppfuns.smi I/IJKMEDIA: Ignoring NAL type 9 in extradata
09-20 17:07:53.208 31523-14828/com.ppfuns.smi I/IJKMEDIA: feed_input_buffer: same surface, reuse previous surface
09-20 17:07:53.316 31523-14827/com.ppfuns.smi I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: INFO_OUTPUT_BUFFERS_CHANGED
09-20 17:07:53.319 31523-14827/com.ppfuns.smi I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: INFO_OUTPUT_FORMAT_CHANGED
09-20 17:07:53.319 31523-14827/com.ppfuns.smi I/IJKMEDIA: AMEDIACODEC__INFO_OUTPUT_FORMAT_CHANGED
09-20 17:07:53.321 31523-14827/com.ppfuns.smi I/IJKMEDIA: AMEDIACODEC__INFO_OUTPUT_FORMAT_CHANGED
                                                              width-height: (1280 x 720)
                                                              color-format: (FormatUnknown: 0x100)
                                                              stride:       (1280)
                                                              slice-height: (720)
                                                              crop:         (0, 0, 1279, 719)
09-20 17:07:53.346 31523-31523/com.ppfuns.smi I/tv.danmaku.ijk.media.player.IjkMediaPlayer: Info: MEDIA_INFO_VIDEO_RENDERING_START

**Comment by bbcallen** [comment]
enable mp3 decoder before build, see README.

**Comment by FatPaper** [comment]
怎么配置
我现在编的是这个
If you prefer more codec/format
cd config
rm module.sh
ln -s module-default.sh module.sh

**Comment by bbcallen** [comment]
That's it.

**Comment by FatPaper** [comment]
@bbcallen 我现在编的就是module-default.sh
然后我在module-default.sh中加入export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mp3*"重新编译，还是没有声音

**Comment by FatPaper** [comment]
能详细点说下么，谢谢

**Comment by bbcallen** [comment]
Clean before rebuild

**Comment by FatPaper** [comment]
@bbcallen 
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all
之后还是没有声音
Could not find codec parameters for stream 1 (Audio: mp3 ([3][0][0][0] / 0x0003), 0 channels): unspecified frame size
                                                         Consider increasing the value for the 'analyzeduration' and 'probesize' options
是我配置错了？

**Comment by FatPaper** [comment]
好了需要--enable-demuxer=mp3
