### ISSUE TITLE
RTMP流断网后重新恢复网络无法继续直播

### ISSUE THREAD

**Issue by sunjinbo** [Bilibili/ijkplayer#2007]
使用RTMP直播流进行断网恢复测试，发现ijk播放器无法恢复；但是如果是点播的视频流就没有问题，可以正常恢复，请问是什么原因？具体log如下所示：

09-20 19:16:51.761 11638-11638/? D/vrlive: onResume()
09-20 19:16:51.791 11638-11638/? D/vrlive: onResume()
09-20 19:16:51.891 11638-13239/? D/vrlive: initScene()
09-20 19:16:51.891 11638-13239/? D/vrlive: initVideoPlayer rtmp://cdn.live.xxxxxxx.com/live_xxxxxxx_v2/_LC_RE_non_2714951214742505981533332_SX
09-20 19:16:52.221 11638-11638/? D/vrlive: onInfo() what=500, extra=0
09-20 19:16:52.221 11638-11638/? D/vrlive: onInfo() what=501, extra=0
09-20 19:16:52.221 11638-11638/? D/vrlive: onInfo() what=502, extra=0
09-20 19:16:52.601 11638-11638/? D/vrlive: onAudienceAvatarChanged() 
09-20 19:16:58.631 11638-11638/? D/vrlive: onInfo() what=503, extra=0
09-20 19:17:00.151 11638-11638/? D/vrlive: onInfo() what=10001, extra=0
09-20 19:17:00.261 11638-11638/? D/vrlive: onPrepared() 
09-20 19:17:00.371 11638-11638/? D/vrlive: onBufferingUpdate() - 0
09-20 19:17:00.371 11638-11638/? D/vrlive: onBufferingUpdate() - 0
09-20 19:17:00.421 11638-11638/? D/vrlive: onInfo() what=3, extra=0
09-20 19:17:00.431 11638-11638/? D/vrlive: onInfo() what=10002, extra=0
09-20 19:17:00.811 11638-11638/? D/vrlive: onBufferingUpdate() - 0
09-20 19:17:01.321 11638-11638/? D/vrlive: onBufferingUpdate() - 0
09-20 19:17:01.921 11638-11638/? D/vrlive: onBufferingUpdate() - 0
09-20 19:17:02.421 11638-11638/? D/vrlive: onBufferingUpdate() - 0
09-20 19:17:03.021 11638-11638/? D/vrlive: onBufferingUpdate() - 0
09-20 19:17:03.621 11638-11638/? D/vrlive: onBufferingUpdate() - 0
09-20 19:17:04.221 11638-11638/? D/vrlive: onBufferingUpdate() - 0
09-20 19:17:04.821 11638-11638/? D/vrlive: onBufferingUpdate() - 0
09-20 19:17:05.331 11638-11638/? D/vrlive: onBufferingUpdate() - 0
09-20 19:17:05.921 11638-11638/? D/vrlive: onBufferingUpdate() - 0
09-20 19:17:06.431 11638-11638/? D/vrlive: onBufferingUpdate() - 0
09-20 19:17:07.021 11638-11638/? D/vrlive: onBufferingUpdate() - 0
09-20 19:17:07.531 11638-11638/? D/vrlive: onBufferingUpdate() - 0
09-20 19:17:08.041 11638-11638/? D/vrlive: onBufferingUpdate() - 0
09-20 19:17:08.631 11638-11638/? D/vrlive: onBufferingUpdate() - 0
09-20 19:17:14.131 11638-11638/? D/vrlive: onError() - -10000,0 《《《《切断网络连接
09-20 19:17:14.141 11638-11638/? D/vrlive: onCompletion() 
09-20 19:17:25.611 11638-11638/? D/vrlive: onGetPlayUrlCompleted() 
09-20 19:17:25.611 11638-11638/? D/vrlive: onGetPlayUrlCompleted rtmp://cdn.live.xxxxxxx.com/live_xxxxxxx_v2/_LC_RE_non_2714951214742505981533332_SX
09-20 19:17:26.701 11638-11638/? D/vrlive: onInfo() what=500, extra=0
09-20 19:17:26.701 11638-11638/? D/vrlive: onInfo() what=501, extra=0
09-20 19:17:26.701 11638-11638/? D/vrlive: onInfo() what=502, extra=0
09-20 19:17:28.501 11638-11638/? D/vrlive: onInfo() what=503, extra=0
09-20 19:17:30.131 11638-11638/? D/vrlive: onPrepared()  《《《《网络重新连接
09-20 19:17:30.141 11638-11638/? D/vrlive: onBufferingUpdate() - 0
09-20 19:17:30.191 11638-11638/? D/vrlive: onBufferingUpdate() - 0
09-20 19:17:30.191 11638-11638/? D/vrlive: onInfo() what=10001, extra=0
09-20 19:17:30.191 11638-11638/? D/vrlive: onInfo() what=701, extra=0 《《《《收到701消息码

**Comment by bbcallen** [comment]
There is reconnect implement in libavformat/http.c, but not in ramp.
