### ISSUE TITLE
升级xcode8以后，真机没事，打包报错

### ISSUE THREAD

**Issue by xuefeime** [Bilibili/ijkplayer#2011]
![Uploading QQ20160921-0@2x.png…]()
Undefined symbols for architecture armv7:
  "_IJKMPMoviePlayerPlaybackStateDidChangeNotification", referenced from:
      -[EditMediaViewController installMovieNotificationObservers] in EditMediaViewController.o
  "_IJKMPMediaPlaybackIsPreparedToPlayDidChangeNotification", referenced from:
      -[EditMediaViewController installMovieNotificationObservers] in EditMediaViewController.o
  "_OBJC_CLASS_$_IJKFFOptions", referenced from:
      objc-class-ref in EditMediaViewController.o
      objc-class-ref in VideoPlayViewController.o
  "_IJKMPMoviePlayerPlaybackDidTimeUpdateValueKey", referenced from:
      -[EditMediaViewController moviePlayBackDidTimeUpdate:] in EditMediaViewController.o
  "_IJKMPMoviePlayerPlaybackDidTimeUpdateNotification", referenced from:
      -[EditMediaViewController installMovieNotificationObservers] in EditMediaViewController.o
      -[VideoPlayViewController viewWillAppear:] in VideoPlayViewController.o
  "_IJKMPMoviePlayerPlaybackDidFinishReasonUserInfoKey", referenced from:
      -[EditMediaViewController moviePlayBackDidFinish:] in EditMediaViewController.o
  "_IJKMPMoviePlayerPlaybackDidFinishNotification", referenced from:
      -[EditMediaViewController installMovieNotificationObservers] in EditMediaViewController.o
      -[VideoPlayViewController viewWillAppear:] in VideoPlayViewController.o
  "_IJKMPMoviePlayerLoadStateDidChangeNotification", referenced from:
      -[EditMediaViewController installMovieNotificationObservers] in EditMediaViewController.o
  "_OBJC_CLASS_$_IJKFFMoviePlayerController", referenced from:
      objc-class-ref in EditMediaViewController.o
      objc-class-ref in VideoPlayViewController.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by xuefeime** [comment]
又测试了一下，用iphone5真机测试以及打包，报上述问题，6plus可以真机测试，运行没问题。

**Comment by xuefeime** [comment]
应该是我打包的框架不支持armv7

**Comment by Chenbo0624** [comment]
你好，请问你这个问题解决了吗？我也遇到了同样的问题，用iphone5真机测试以及打包，报错，6plus可以真机测试，运行没问题。

**Comment by Ucself** [comment]
@xuefeime ijk pod库不支持32位系统，Build Settings -> Valid Arcitectures -> arm64 （去掉armc7）
![image](https://user-images.githubusercontent.com/5546554/48246467-82dbc380-e42a-11e8-956f-64b16f6fc9c9.png)
