### ISSUE TITLE
rtmp 不能播放

### ISSUE THREAD

**Issue by remantou** [Bilibili/ijkplayer#202]
![2015-03-31 5 23 20](https://cloud.githubusercontent.com/assets/8045375/6916118/24f9ac0a-d7cc-11e4-8f81-1734d30f6400.png)

**Comment by tbfly** [comment]
编译ffmpeg的时候加上librtmp支持就好了吧

**Comment by ryanjunhung** [comment]
我是enable所有的protocol＋ＳＳＬ
所以可以正常運作。
ＥＸ：
CONFIGURE_FLAGS="$CONFIGURE_FLAGS --enable-protocols"

在build ffmpeg的時候會出現如下：

Enabled protocols:

cache http rtmpt
concat httpproxy rtmpte
crypto https rtmpts
data md5 rtp
ffrtmpcrypt mmsh srtp
ffrtmphttp mmst tcp
file pipe tls
ftp rtmp udp
gopher rtmpe unix
hls rtmps
