### ISSUE TITLE
ios播放本地下载下来的flv格式的多个小视频文件，组装成concat 格式的文件，播放不了？

### ISSUE THREAD

**Issue by zyw113** [Bilibili/ijkplayer#2022]
格式大概是这样
ffconcat version 1.0
file /Users/gaolong/Library/Developer/CoreSimulator/Devices/D8ECD7F6-90D0-49A4-B121-B4205623E6DD/data/Containers/Data/Application/2084F996-445A-4E8B-90A2-C168332DE8EF/Library/Caches/ZYWDownloadVideos/CacheList/别那么骄傲 第一季7/id0.flv
duration 209
file /Users/gaolong/Library/Developer/CoreSimulator/Devices/D8ECD7F6-90D0-49A4-B121-B4205623E6DD/data/Containers/Data/Application/2084F996-445A-4E8B-90A2-C168332DE8EF/Library/Caches/ZYWDownloadVideos/CacheList/别那么骄傲 第一季7/id1.flv
duration 185
file /Users/gaolong/Library/Developer/CoreSimulator/Devices/D8ECD7F6-90D0-49A4-B121-B4205623E6DD/data/Containers/Data/Application/2084F996-445A-4E8B-90A2-C168332DE8EF/Library/Caches/ZYWDownloadVideos/CacheList/别那么骄傲 第一季7/id2.flv
duration 208

log日志
av_version_info: ff2.8--ijk0.4.4.1--dev0.3.3--rc7
ijkmp_set_inject_opaque(0x7fd6c1fe56b0)
ijkmp_set_inject_opaque()=void
2016-09-22 18:35:57.929 videoSearch[9948:323200] OK setup GL
ijkmp_ios_set_view(glView=0x7fd6c1fcffe0)
ijkmp_ios_set_view(glView=0x7fd6c1fcffe0)=void
2016-09-22 18:35:57.934 videoSearch[9948:323200] invalidateRenderBuffer
2016-09-22 18:35:57.934 videoSearch[9948:331389] IJKSDLGLView: setupDisplay not ready
ijkmp_set_data_source(url="/Users/gaolong/Library/Developer/CoreSimulator/Devices/D8ECD7F6-90D0-49A4-B121-B4205623E6DD/data/Containers/Data/Application/2084F996-445A-4E8B-90A2-C168332DE8EF/Library/Caches/ZYWDownloadVideos/CacheList/别那么骄傲 第一季7/别那么骄傲 第一季7.concat")
ijkmp_set_data_source(url="/Users/gaolong/Library/Developer/CoreSimulator/Devices/D8ECD7F6-90D0-49A4-B121-B4205623E6DD/data/Containers/Data/Application/2084F996-445A-4E8B-90A2-C168332DE8EF/Library/Caches/ZYWDownloadVideos/CacheList/别那么骄傲 第一季7/别那么骄傲 第一季7.concat")=0
ijkmp_prepare_async()
===== versions =====
FFmpeg       : ff2.8--ijk0.4.4.1--dev0.3.3--rc7
libavutil    : 54.31.100
libavcodec   : 56.60.100
libavformat  : 56.40.101
libswscale   : 3.1.101
libswresample: 1.2.101
===== options =====
player-opts : video-pictq-size             = 3
player-opts : overlay-format               = fcc-_es2
player-opts : videotoolbox-max-frame-width = 1024
player-opts : max-fps                      = 30
player-opts : framedrop                    = 8
player-opts : safe                         = 0
player-opts : videotoolbox                 = 0
player-opts : start-on-prepared            = 1
format-opts : ijkinject-opaque             = 140560354399920
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : http-tcp-hook                = ijktcphook
format-opts : timeout                      = 30000000
format-opts : reconnect                    = 1
format-opts : protocol_whitelist           = concat,file,subfile,duration
format-opts : safe                         = 0
codec-opts  : skip_frame                   = 0
codec-opts  : skip_loop_filter             = 0
===================
ijkmp_prepare_async()=0
Format concat probed with size=2048 and score=100
Impossible to open '/Users/gaolong/Library/Developer/CoreSimulator/Devices/D8ECD7F6-90D0-49A4-B121-B4205623E6DD/data/Containers/Data/Application/2084F996-445A-4E8B-90A2-C168332DE8EF/Library/Caches/ZYWDownloadVideos/CacheList/别那么骄傲'
Statistics: 1827 bytes read, 0 seeks
/Users/gaolong/Library/Developer/CoreSimulator/Devices/D8ECD7F6-90D0-49A4-B121-B4205623E6DD/data/Containers/Data/Application/2084F996-445A-4E8B-90A2-C168332DE8EF/Library/Caches/ZYWDownloadVideos/CacheList/别那么骄傲 第一季7/别那么骄傲 第一季7.concat: No such file or directory
2016-09-22 18:35:58.034 videoSearch[9948:323200] invalidateRenderBuffer
2016-09-22 18:35:58.035 videoSearch[9948:331666] IJKSDLGLView: setupDisplay not ready
2016-09-22 18:35:58.039 videoSearch[9948:323200] invalidateRenderBuffer
2016-09-22 18:35:58.039 videoSearch[9948:331666] IJKSDLGLView: setupDisplay not ready
2016-09-22 18:35:58.042 videoSearch[9948:323200] FFP_MSG_ERROR: 0
IJKMoviePlayerViewController.m:946	IJKMPMoviePlayBackStateDidChange 2: paused
IJKMoviePlayerViewController.m:911	playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1

**Comment by bbcallen** [comment]
"/Users/gaolong/Library/Developer/CoreSimulator/Devices/D8ECD7F6-90D0-49A4-B121-B4205623E6DD/data/Containers/Data/Application/2084F996-445A-4E8B-90A2-C168332DE8EF/Library/Caches/ZYWDownloadVideos/CacheList/别那么骄傲 第一季7/别那么骄傲 第一季7.concat: No such file or directory"

**Comment by xingze0308** [comment]
你好 请问你这个问题解决了吗
