### ISSUE TITLE
是否有 avfilter 的接口

### ISSUE THREAD

**Issue by djh123** [Bilibili/ijkplayer#2025]
@bbcallen hi 你好

我按照你上面说的(https://github.com/Bilibili/ijkplayer/issues/1132)
 修改了 编译脚本和 clean and rebuild FFmpeg 
然后 在ff_ffplay.c configure_video_filters() 中加入 过滤选项 如 
const char *filter_descr = "drawbox=x=100:y=100:w=100:h=100:color=pink@0.5";

if ((ret = configure_filtergraph(graph, filter_descr, filt_src, last_filter)) < 0)
goto fail;

它是有效果的。现在问题是 我如何使用ijk的 接口 设置这些参数 ，还是说我需要自己拉接口。

**Comment by bbcallen** [comment]
No such interface.
You need to define it.

**Comment by djh123** [comment]
ok many  thans。

再问下
加入avfiler  会有怎样的性能问题？怎么去评估？
