### ISSUE TITLE
nal_ref_idc iOS这种类型的Log否能关闭?

### ISSUE THREAD

**Issue by iceDays** [Bilibili/ijkplayer#2026]
导入项目 注释掉 ijksdl_log.h 文件后的确不会打印, 
但是如果打包成Framework 注释后还是会打印, 求指导

**Comment by iceDays** [comment]
nal_unit_type: 1, nal_ref_idc: 0
nal_unit_type: 1, nal_ref_idc: 2
nal_unit_type: 1, nal_ref_idc: 2
nal_unit_type: 1, nal_ref_idc: 0
nal_unit_type: 1, nal_ref_idc: 0
nal_unit_type: 1, nal_ref_idc: 2
nal_unit_type: 1, nal_ref_idc: 2
nal_unit_type: 1, nal_ref_idc: 0
nal_unit_type: 1, nal_ref_idc: 0
nal_unit_type: 1, nal_ref_idc: 2
nal_unit_type: 1, nal_ref_idc: 2
......

**Comment by JerryIsAgoodBoy** [comment]
应该是这个？
[IJKFFMoviePlayerController setLogLevel:k_IJK_LOG_SILENT];

**Comment by bbcallen** [comment]
As above
