### ISSUE TITLE
Add Digest authentication

### ISSUE THREAD

**Issue by ryanjunhung** [Bilibili/ijkplayer#203]
hi 
想請教您，如果要在ＩＯＳ的ＩＪＫ加入 Digest authentication 
應該要如何著手呢？ 麻煩您能給點方向。謝謝

**Comment by bbcallen** [comment]
没太明白，你是想用来做什么？

**Comment by ryanjunhung** [comment]
Hi 
想要透過 “摘要认证”（Digest authentication）用來與服務器認證用的。
https://github.com/ZoneMinder/ZoneMinder/issues/399

**Comment by bbcallen** [comment]
如果你指的是 https 支持，那么必须先编译openssl.
```
sh init-ios-openssl.sh
cd ios
sh compile-openssl.sh
```
不过这部分我只是确认可以编译，没有测试过真正的https连接。

**Comment by ryanjunhung** [comment]
Hi bbcallen

HTTPS 我試過可以正常連接的。

但是乎還是沒有支援Digest authentication，目前還在研究，有什麼好消息，我會來分享。

**Comment by TARKZiM** [comment]
同問, 想在Android上加上digest支持,

不知道這個該怎麼實現?

ex: rtsp://user:1234@xxx.com:9999

目前使用這種方式皆沒有收到流的數據

**Comment by bbcallen** [comment]
如果 ffplay 支持这种格式的url
那么使用 ffmpeg 未裁剪的编译应该没有问题。
```
rm config/module.sh
ln -s config/module-lite.sh config/module.sh
```

**Comment by ryanjunhung** [comment]
基本上直接帶rtsp://user:1234@xxx.com:9999
ffmpeg會自己處理digest這一段，
不過url走的port 9999，SERVER端走的是SSL，那就必須使FFMPEG 支持TLS。
那就必須先ENABLE  SSL，然後再rtsp.c這隻CODE稍微修改一下，讓他走TCP+SSL。

基本上就可以運作了。

btw,可以先看封包，app 如何跟server怎麼交握的。交握到哪個地方而失敗的。

**Comment by TARKZiM** [comment]
@bbcallen 使用lite和default都沒有效果...

@ryanjunhung sorry, 那個9999只是示意,
實際上用的url是32768這樣的port,

至於那個SSL的支持, 可以請您提供個初步的說明嗎？
抱歉, 我對於這方面還是不太熟悉的, 不知道要怎麼看封包...
只看到Log的輸出且沒有輸出異常

感激不盡

**Comment by ryanjunhung** [comment]
您必須先確定SERVER端是否需要走ＳＳＬ。
如果不需要那就不能走ＴＣＰ＋ＴＳＬ。
因為一定會失敗。

ENABLE SSL
上面bbcallen有提到
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
sh init-ios-openssl.sh
cd ios
sh compile-openssl.sh

**Comment by niyingxunzong** [comment]
@bbcallen 我想问问，这个编译openssl.sh 放在什么地方？

**Comment by zh302674199** [comment]
我用海康的摄像头测试，我发现支持摘要认证（RFC 2617） ，可以正常播放，但我改成RFC 7616的摘要认证时，无法播放，请教一下，Ijkplayer不支持RFC 7616的摘要认证算法吗？
