### ISSUE TITLE
真机播放rtsp，播放一段时间后自动停止

### ISSUE THREAD

**Issue by wlwlzcj** [Bilibili/ijkplayer#2035]
模拟器可以一直播放  有时候会提示miss packet   真机有时候能播放很久  有时候播放几秒钟就停了

===== custom modules begin =====
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff3.1--ijk0.6.1--20160824--001
ijk_version_info: 
ijkmp_set_inject_opaque(0x1808f2e0)
ijkmp_set_inject_opaque()=void
2016-09-26 16:24:17.478 JYZJGFileManager[14540:60b] OK setup GL
ijkmp_ios_set_view(glView=0x180963c0)
ijkmp_ios_set_view(glView=0x180963c0)=void
ijkmp_set_data_source(url="rtsp://admin:123456we@192.168.1.88:554/h264/ch1/main/av_stream")
ijkmp_set_data_source(url="rtsp://admin:123456we@192.168.1.88:554/h264/ch1/main/av_stream")=0
ijkmp_prepare_async()
remove 'timeout' option for rtmp.
===== versions =====
ijkplayer    : 
FFmpeg       : ff3.1--ijk0.6.1--20160824--001
libavutil    : 55.27.100
libavcodec   : 57.48.101
libavformat  : 57.40.101
libswscale   : 4.1.100
libswresample: 2.1.100
===== options =====
player-opts : start-on-prepared            = 1
player-opts : overlay-format               = fcc-_es2
player-opts : framedrop                    = 0
player-opts : max-fps                      = 30
player-opts : video-pictq-size             = 3
player-opts : videotoolbox                 = 0
player-opts : videotoolbox-max-frame-width = 960
format-opts : ijkapplication               = 403143568
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : safe                         = 0
format-opts : reconnect                    = 1
===================
ijkmp_prepare_async()=0
remove 'timeout' option for rtmp.
No default whitelist set
2016-09-26 16:24:17.500 JYZJGFileManager[14540:60b] invalidateRenderBuffer
ijkmp_set_data_source(url="rtsp://admin:123456we@192.168.1.88:554/h264/ch1/main/av_stream")
ijkmp_set_data_source(url="rtsp://admin:123456we@192.168.1.88:554/h264/ch1/main/av_stream")=-3
ijkmp_prepare_async()
ijkmp_prepare_async()=-3
2016-09-26 16:24:17.503 JYZJGFileManager[14540:2407] IJKSDLGLView: setupDisplay not ready
2016-09-26 16:24:17.520 JYZJGFileManager[14540:60b] invalidateRenderBuffer
2016-09-26 16:24:17.522 JYZJGFileManager[14540:1a0b] IJKSDLGLView: setupDisplay not ready
SDP:
v=0

o=- 1474907079159281 1474907079159281 IN IP4 192.168.1.88

s=Media Presentation

e=NONE

b=AS:5100

t=0 0

a=control:rtsp://192.168.1.88:554/h264/ch1/main/av_stream/

m=video 0 RTP/AVP 96

c=IN IP4 0.0.0.0

b=AS:5000

a=recvonly

a=x-dimensions:1280,720

a=control:rtsp://192.168.1.88:554/h264/ch1/main/av_stream/trackID=1

a=rtpmap:96 H264/90000

a=fmtp:96 profile-level-id=420029; packetization-mode=1; sprop-parameter-sets=Z00AH5WoFAFuhAAAHCAABX5AEA==,aO48gA==

m=audio 0 RTP/AVP 8

c=IN IP4 0.0.0.0

b=AS:50

a=recvonly

a=control:rtsp://192.168.1.88:554/h264/ch1/main/av_stream/trackID=2

a=rtpmap:8 PCMA/8000

a=Media_header:MEDIAINFO=494D4B48010200000400000111710110401F000000FA000000000000000000000000000000000000;

a=appversion:1.0

video codec set to: h264
RTP Profile IDC: 42 Profile IOP: 0 Level: 29
RTP Packetization Mode: 1
Extradata set to 0x16ddafe0 (size: 31)
audio codec set to: pcm_alaw
audio samplerate set to: 8000
audio channels set to: 1
No default whitelist set
No default whitelist set
end receive buffer size reported is 65536
No default whitelist set
end receive buffer size reported is 65536
setting jitter buffer size to 500
No default whitelist set
No default whitelist set
end receive buffer size reported is 65536
No default whitelist set
end receive buffer size reported is 65536
setting jitter buffer size to 500
hello state=0
Option ijkapplication not found.
nal_unit_type: 7, nal_ref_idc: 3
nal_unit_type: 8, nal_ref_idc: 3
nal_unit_type: 7, nal_ref_idc: 3
nal_unit_type: 8, nal_ref_idc: 3
unknown SEI type 229
nal_unit_type: 7, nal_ref_idc: 3
nal_unit_type: 8, nal_ref_idc: 3
nal_unit_type: 6, nal_ref_idc: 0
nal_unit_type: 5, nal_ref_idc: 3
unknown SEI type 229
unknown SEI type 229
nal_unit_type: 7, nal_ref_idc: 3
nal_unit_type: 8, nal_ref_idc: 3
nal_unit_type: 6, nal_ref_idc: 0
nal_unit_type: 5, nal_ref_idc: 3
unknown SEI type 229
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
max delay reached. need to consume packet
RTP: missed 4 packets
All info found
rfps: 24.500000 0.017131
rfps: 24.583333 0.012161
rfps: 24.583333 0.012161
rfps: 24.666667 0.008044
rfps: 24.666667 0.008044
rfps: 24.750000 0.004779
rfps: 24.750000 0.004779
rfps: 24.833333 0.002367
rfps: 24.833333 0.002367
rfps: 24.916667 0.000807
rfps: 24.916667 0.000807
rfps: 25.000000 0.000100
rfps: 25.083333 0.000245
rfps: 25.083333 0.000245
rfps: 25.166667 0.001243
rfps: 25.166667 0.001243
rfps: 25.250000 0.003093
rfps: 25.250000 0.003093
rfps: 25.333333 0.005796
rfps: 25.333333 0.005796
rfps: 25.416667 0.009351
rfps: 25.416667 0.009351
rfps: 25.500000 0.013759
rfps: 25.583333 0.019020
rfps: 50.000000 0.000400
max_frame_duration: 10.000
Input #0, rtsp, from 'rtsp://admin:123456we@192.168.1.88:554/h264/ch1/main/av_stream':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0, 28, 1/90000: Video: h264, 1 reference frame, yuv420p(left), 1280x720, 0/1, 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1, 29, 1/8000: Audio: pcm_alaw, 8000 Hz, 1 channels, 64 kb/s
No codec could be found with id 65543
detected 2 logical cores
nal_unit_type: 7, nal_ref_idc: 3
nal_unit_type: 8, nal_ref_idc: 3
VideoCodec: avcodec, h264
fps: 25.000000 (normal)
fps: 25.000000 (normal)
ijkmp_get_msg: FFP_MSG_PREPARED
nal_unit_type: 7, nal_ref_idc: 3
nal_unit_type: 8, nal_ref_idc: 3
nal_unit_type: 6, nal_ref_idc: 0
2016-09-26 16:24:19.452 JYZJGFileManager[14540:60b] FFP_MSG_VIDEO_DECODER_OPEN: false
nal_unit_type: 5, nal_ref_idc: 3
unknown SEI type 229
2016-09-26 16:24:19.453 JYZJGFileManager[14540:60b] FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
2016-09-26 16:24:19.454 JYZJGFileManager[14540:60b] FFP_MSG_SAR_CHANGED: 0, 1
2016-09-26 16:24:19.455 JYZJGFileManager[14540:60b] FFP_MSG_PREPARED:
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
2016-09-26 16:24:19.457 JYZJGFileManager[14540:60b] fps in meta 25.000000
nal_unit_type: 7, nal_ref_idc: 3
nal_unit_type: 8, nal_ref_idc: 3
nal_unit_type: 6, nal_ref_idc: 0
nal_unit_type: 5, nal_ref_idc: 3
unknown SEI type 229
nal_unit_type: 1, nal_ref_idc: 3
SDL_VoutFFmpeg_CreateOverlay(w=1280, h=720, fmt=I420(0x30323449, dp=0x1807bec0)
Video: first frame decoded
SDL_VoutFFmpeg_CreateOverlay(w=1280, h=720, fmt=I420(0x30323449, dp=0x1807bec0)
2016-09-26 16:24:19.556 JYZJGFileManager[14540:60b] FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
2016-09-26 16:24:19.558 JYZJGFileManager[14540:60b] FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
nal_unit_type: 1, nal_ref_idc: 3
SDL_VoutFFmpeg_CreateOverlay(w=1280, h=720, fmt=I420(0x30323449, dp=0x1807bec0)
[GLES2] Version = OpenGL ES 2.0 IMGSGX543-97.7
[GLES2] Vendor = Imagination Technologies
[GLES2] Renderer = PowerVR SGX 543
[GLES2] Extensions = GL_OES_depth_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_vertex_array_object GL_EXT_blend_minmax GL_EXT_color_buffer_half_float GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_draw_instanced GL_EXT_instanced_arrays GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_pvrtc_sRGB GL_EXT_read_format_bgra GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_texture_lod GL_EXT_shadow_samplers GL_EXT_sRGB GL_EXT_texture_filter_anisotropic GL_EXT_texture_rg GL_EXT_texture_storage GL_APPLE_copy_texture_levels GL_APPLE_framebuffer_multisample GL_APPLE_rgb_422 GL_APPLE_sync GL_APPLE_texture_format_BGRA8888 GL_APPLE_texture_max_level GL_IMG_read_format GL_IMG_texture_compression_pvrtc 
create render yuv420p
2016-09-26 16:24:19.563 JYZJGFileManager[14540:60b] FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
use render yuv420p
2016-09-26 16:24:19.570 JYZJGFileManager[14540:5703] IJKSDLGLView: renderbufferStorage fromDrawable
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
IJK_GLES2_Renderer_TexCoords_cropRight
2016-09-26 16:24:19.606 JYZJGFileManager[14540:60b] FFP_MSG_VIDEO_RENDERING_START:
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
Frame num gap 19 17
Increasing reorder buffer to 1
no picture 
nal_unit_type: 1, nal_ref_idc: 3
concealing 1891 DC, 1891 AC, 1891 MV errors in P frame
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
unknown SEI type 229
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 7, nal_ref_idc: 3
nal_unit_type: 8, nal_ref_idc: 3
nal_unit_type: 6, nal_ref_idc: 0
nal_unit_type: 5, nal_ref_idc: 3
unknown SEI type 229
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
nal_unit_type: 1, nal_ref_idc: 3
ffp_toggle_buffering_l: start
aout_pause_audio(1)
2016-09-26 16:24:22.106 JYZJGFileManager[14540:60b] FFP_MSG_BUFFERING_START:

**Comment by bbcallen** [comment]
Sorry, not familiar with RTSP.

**Comment by fengbenpaao** [comment]
解决没有,好像是有这个现象啊
