### ISSUE TITLE
您好，更新iOS10后，编译过不去，显示找不到audioToolBox内的相关文件？

### ISSUE THREAD

**Issue by Huaida** [Bilibili/ijkplayer#2037]
xcode更新到8.0，模拟器跟新到iOS10后，之前的项目编译不过去了，显示取到audioToolBox相关文件
![Uploading 2F1559E6ED23E29A9E0EC226186FCB73.jpg…]()

**Comment by sevenOnClass** [comment]
同问:xcode更新后,项目编译失败

![092601](https://cloud.githubusercontent.com/assets/16209754/18830255/83f5f03a-8412-11e6-8ccf-d7dc48eb67c4.jpeg)

**Comment by Huaida** [comment]
已经解决，重新编译后再次添加到项目中就可以了，注意要添加link

**Comment by sevenOnClass** [comment]
怀达...哈哈哈
