### ISSUE TITLE
Enable thread support

### ISSUE THREAD

**Issue by brystel** [Bilibili/ijkplayer#204]
Hi,

It seems to be possible to compile ffmpeg and x264 with thread support for android.
Have you tried this? Will it be possible to achieve in IJKPLAYER?

**Comment by bbcallen** [comment]
Thread support is enabled by default.
It can be set by setAvCodecOptions("threads", ...);

**Comment by brystel** [comment]
Is this option causes real improve of H264 software video decoding performance?

I cannot see any improvements with values: 0 / 1 / 2 (2 cores device)

**Comment by bbcallen** [comment]
I didn't do any benchmark on that.
It's recommended to be left as default. FFmpeg will set thread number depending on the number of your device's cores, automatically.
Usually, this option is used to disable multiple threads.

**Comment by brystel** [comment]
Thank you for your response.
It seems that manipulate with threads count does not resolved low decoding performance.

Now I am trying to compile Ijkplayer with neon support (arch armv7a) but I stuck on following compile error:
```
INSTALL	libavutil/libavutil.pc
\n--------------------
[*] link ffmpeg
--------------------
-Wl,--fix-cortex-a8
libavcodec/mpegvideo.c:413: error: undefined reference to 'ff_mpv_common_init_neon'
```

I am trying to build with following flags:
```
(...)
    FF_CFG_FLAGS="$FF_CFG_FLAGS --arch=arm"
    FF_CFG_FLAGS="$FF_CFG_FLAGS --enable-neon"
    FF_CFG_FLAGS="$FF_CFG_FLAGS --enable-thumb"

    FF_EXTRA_CFLAGS="$FF_EXTRA_CFLAGS -march=armv7-a -mfpu=neon -mfloat-abi=softfp"
    FF_EXTRA_LDFLAGS="$FF_EXTRA_LDFLAGS -Wl,--fix-cortex-a8"

    FF_ASM_OBJ_DIR="libavutil/arm/*.o libavcodec/arm/*.o libswresample/arm/*.o"
(...)
```

I have checked that ```ff_mpv_common_init_neon``` method is present in 
```ijkplayer/android/ffmpeg-armv7a/libavcodec/neon/mpegvideo.c``` file
but it does not in 
```ijkplayer/android/ffmpeg-armv7a/libavcodec/mpegvideo.c```

the ```-mfpu=neon``` flag works only with ```-mfloat-abi=soft``` flag.

Do you have any idea how to compile ```-mfpu=neon``` flag with ```-mfloat-abi=softfp``` flag?

**Comment by bbcallen** [comment]
You don't need to add -mfpu=neon. The config flag "--enable-neon" has already enable neon support. 
libavcodec would choose neon code depending on cpu info at runtime.

Actually, "-mfpu=neon" doesn't work on all armv7a devices, e.g. Nvidia Tegra2.

**Comment by FloridaStream** [comment]
you comment save my life @bbcallen, tjank you. =)
