### ISSUE TITLE
关于视频缓冲 MAX_QUEUE_SIZE

### ISSUE THREAD

**Issue by tanqu2013** [Bilibili/ijkplayer#2045]
有几个问题希望得到指导：
1.``` mMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_CODEC, "MAX_QUEUE_SIZE", 0);```，请问第一个参数和第三个参数是否设置正确（我想实现暂停视频时，停止缓存）？
2.设置视频缓存大小可以在暂停和开始的方法中调用吗？
3.请问视频缓冲大小和OnBufferingUpdateListener 中 onBufferingUpdate 回调的第二个参数 percent 有什么关系吗？

**Comment by bbcallen** [comment]
1. IjkMediaPlayer.OPT_CATEGORY_PLAYER.
2. No.
3. No.

**Comment by tanqu2013** [comment]
OK.thanks
