### ISSUE TITLE
$ ./compile-ijk.sh all

### ISSUE THREAD

**Issue by zhoujingheng** [Bilibili/ijkplayer#2046]
$ ./compile-ijk.sh all
You must define ANDROID_NDK, ANDROID_SDK before starting.
They must point to your NDK and SDK directories.\n

**Comment by migueltarga** [comment]
You must define ANDROID_NDK, ANDROID_SDK before starting.

**Comment by zhoujingheng** [comment]
How define  ANDROID_NDK, ANDROID_SDK with git bash?

**Comment by ctiao** [comment]
duplicated with: #1011

**Comment by developeralp** [comment]
@zhoujingheng 

You should use Linux (i.e : ubuntu)
