### ISSUE TITLE
Support variable playback speed

### ISSUE THREAD

**Issue by gemiren** [Bilibili/ijkplayer#205]
Thanks for the great player. Any plan to support variable playback speed?

**Comment by bbcallen** [comment]
Not for me.
But you can try work with speed field in Clock structure in ff_ffplay.c

**Comment by gemiren** [comment]
Thanks for hints. I tried to set the clock speed but seems not working. The function I called is:
   set_clock_speed(&is->audclk, speed);
    set_clock_speed(&is->vidclk, speed);
    set_clock_speed(&is->extclk, speed);

Any ideas why that does't work?

**Comment by bbcallen** [comment]
No idea, for now.
Maybe need more works than just set that option.

**Comment by jaycee11** [comment]
@gemiren  Do you found the solution  to support variable playback speed? Thanks！

**Comment by gemiren** [comment]
@jaycee11 No luck here.

**Comment by bbcallen** [comment]
Feature added
