### ISSUE TITLE
iPhone cpu used a lot when iOS ijkPlayer play h265 video 

### ISSUE THREAD

**Issue by SoXeon** [Bilibili/ijkplayer#2050]
本地播放一段
HEVC, 1720×720, 24.0fps
AC-3, 448.0kbps, 48.0kHz 32bit, 2 声道的视频
真机6sCPU占比从40%~80%浮动，主要在ff_vout上，特别是场景复杂的画面。

问题：
1. 这是普遍现象还是视频原因？
2. 是否存在可优化降低CPU占用的方案？

**Comment by bbcallen** [comment]
1. It's normal.
2. No idea.

**Comment by muyitimha** [comment]
@SoXeon 请问现在解决了吗？我ios项目走rtsp播放的时候也是cpu占用极高
