### ISSUE TITLE
碰到一个奇怪的问题，引入Ijk方式的不同引起的avi视频无法播放的问题

### ISSUE THREAD

**Issue by biezhihua** [Bilibili/ijkplayer#2054]
# 引入Ijk方式的不同引起的avi视频无法播放的问题

## 背景

我在自建的一个工程中使用compile的方式引入ijk，使用IjkMediaPlayer作为解码，使用GLSurfaceView作为界面展示。用于播放avi视频（视频格式：H.264，音频:AC3）。

```
compile 'tv.danmaku.ijk.media:ijkplayer-java:0.6.2'
compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.6.2'
```

发现无法播放，于是我将代码移植到ijkplayer-example工程下，发现播放良好。

经过一番对比我发现，如果将ijkplery工程下的arr文件

```
ijkplayer-armv7a-release.arr
ijkplayer-java-release.arr
```

以lib的形式引入到自己的demo工程中就可以播放。

```
compile(name:'ijkplayer-armv7a-release', ext:'aar')
compile(name:'ijkplayer-java-release', ext:'aar')
```

## 问题

这两种形式有什么不同，为什么会导致这样的问题。

非常希望获得大牛回答，在此非常感谢

## demo地址

https://github.com/biezhihua/IJKPlayer_AVI.git

**Comment by ctiao** [comment]
demo地址没有源码

**Comment by biezhihua** [comment]
@ctiao  项目里面包含了一个avi，20M还正在push中。稍等.

**Comment by biezhihua** [comment]
@ctiao  demo已经push完了。非常感谢。

**Comment by bbcallen** [comment]
AVI support is disabled in prebuilt aar.

**Comment by biezhihua** [comment]
@bbcallen 已经明白了。可以关闭这个issues了。谢谢您的回答。

**Comment by ctiao** [comment]
...那么你的aar文件是哪里来的

**Comment by biezhihua** [comment]
按照步骤编译并运行起来后。在ijkplayer-armv7a/build/outputs/aar/ijkplayer-armv7a-release.aar。
然后复制过去的。

**Comment by biezhihua** [comment]
@ctiao  按照步骤编译并运行起来后。在ijkplayer-armv7a/build/outputs/aar/ijkplayer-armv7a-release.aar。
然后复制过去的。

**Comment by ctiao** [comment]
那应该是在配置里开启了avi的，所以才能播放avi

**Comment by biezhihua** [comment]
@ctiao  了解了。谢谢
