### ISSUE TITLE
Android使用Gradle导入ijk的问题

### ISSUE THREAD

**Issue by dakun666** [Bilibili/ijkplayer#2055]
我使用Gradle将ijk项目导入到我自己的项目中，即这几行：
    compile 'tv.danmaku.ijk.media:ijkplayer-java:0.6.2'
    compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.6.2'
    compile 'tv.danmaku.ijk.media:ijkplayer-armv5:0.6.2'
    compile 'tv.danmaku.ijk.media:ijkplayer-arm64:0.6.2'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.6.2'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86_64:0.6.2'
在编译的时候就会报以下错误：
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [tv.danmaku.ijk.media:ijkplayer-x86_64:0.6.2] 
我设置的最低版本SDK为16，理应ijk最低SDK版本是不高于16的，为什么会出现21这个版本，是我哪里设置的不对吗？求解
我的gradle版本:2.14.1
我的androidStudio版本：2.2

**Comment by ctiao** [comment]
arm64和x86_64  minSdkVersion是21

**Comment by dakun666** [comment]
多谢多谢！
