### ISSUE TITLE
android版本，一个视频最后几帧没有画面只有声音

### ISSUE THREAD

**Issue by mgoann** [Bilibili/ijkplayer#2066]
用其他播放器可以正常播放，可以一直播放到结束，这个是视频url

> http://8537.vod.myqcloud.com/8537_a58316ea86df11e6a76c67b1ff29c014.f30.mp4?sign=9db5287c1832856821f0fd476f41a9c1&t=57ef8093

使用ijkplayer播放后，画面最后几帧出不来，只有声音，而且错误日志

> 09-30 05:50:17.631 31741-32068/com.fengxing.ams.tvclient D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
09-30 05:50:17.632 31741-32068/com.fengxing.ams.tvclient D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
09-30 05:50:17.704 31741-32069/com.fengxing.ams.tvclient D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
09-30 05:50:17.704 31741-32069/com.fengxing.ams.tvclient D/IJKMEDIA: nal_unit_type: 7, nal_ref_idc: 3
09-30 05:50:17.704 31741-32069/com.fengxing.ams.tvclient D/IJKMEDIA: nal_unit_type: 8, nal_ref_idc: 3
09-30 05:50:17.704 31741-32069/com.fengxing.ams.tvclient E/IJKMEDIA: Invalid NAL unit size.
09-30 05:50:17.704 31741-32069/com.fengxing.ams.tvclient E/IJKMEDIA: Error splitting the input into NAL units.
09-30 05:50:18.157 535-932/? D/AudioFlinger: mixer(0xf1dc0000) throttle end: throttle time(2)
09-30 05:50:18.437 31741-32059/com.fengxing.ams.tvclient E/IJKMEDIA: stream 0, offset 0x22b3606: partial file
09-30 05:50:19.466 31741-32059/com.fengxing.ams.tvclient E/IJKMEDIA: stream 0, offset 0x22b3651: partial file
09-30 05:50:19.479 535-932/? D/AudioFlinger: mixer(0xf1dc0000) throttle end: throttle time(6)
09-30 05:50:20.043 535-932/? D/AudioFlinger: mixer(0xf1dc0000) throttle end: throttle time(8)
09-30 05:50:20.432 535-932/? D/AudioFlinger: mixer(0xf1dc0000) throttle end: throttle time(7)
09-30 05:50:20.478 31741-32059/com.fengxing.ams.tvclient E/IJKMEDIA: stream 0, offset 0x22b6715: partial file
09-30 05:50:21.042 535-932/? I/AudioFlinger: BUFFER TIMEOUT: remove(4101) from active list on thread 0xf1dc0000
09-30 05:50:21.489 31741-32059/com.fengxing.ams.tvclient E/IJKMEDIA: stream 0, offset 0x22b6785: partial file
09-30 05:50:22.500 31741-32059/com.fengxing.ams.tvclient E/IJKMEDIA: stream 0, offset 0x22b67ce: partial file
09-30 05:50:23.512 31741-32059/com.fengxing.ams.tvclient E/IJKMEDIA: stream 0, offset 0x22b67fe: partial file
09-30 05:50:23.713 31741-31741/com.fengxing.ams.tvclient I/MainActivity: onActivityResult

这个目前使用的参数情况：

` ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
            ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-auto-rotate", 1);
            ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-handle-resolution-change", 1);

            ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "opensles", 0);

            ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "overlay-format", IjkMediaPlayer.SDL_FCC_RV32);
            ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 12);
            ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "start-on-prepared", 0);

            ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "http-detect-range-support", 0);`

求作者给点提示？如何解决，谢谢！

**Comment by bbcallen** [comment]
Can't access the URL.

**Comment by mgoann** [comment]
@bbcallen 不好意思，视频连接有防盗链机制，我重新生成了一个30天的token
http://8537.vod.myqcloud.com/8537_a58316ea86df11e6a76c67b1ff29c014.f30.mp4?sign=5493ad997e153e8092de307e338b1774&t=5822a346

**Comment by Android4MediaPlayer** [comment]
我测试都播放完了，没复现。

**Comment by bbcallen** [comment]
Try remove framedrop

**Comment by jaychou2012** [comment]
framedrop什么意思？

**Comment by mgoann** [comment]
@bbcallen 去掉还是不行，而且出现严重的音画不同步的现象。

**Comment by mgoann** [comment]
刚才用ijkplayer-example编译出来播放器播放未重现该问题，可以肯定不是ijkplayer的问题，可能是我自己代码的BUG，正在查找原因！

**Comment by mgoann** [comment]
大致原因找到了，使用自定义dataSource，缓存分页没有完全下载，导致数据丢失！
