### ISSUE TITLE
Can this Player be used with tvOS?

### ISSUE THREAD

**Issue by Sebacho-Barajas** [Bilibili/ijkplayer#2067]
is there any way to use it with tvOS?

**Comment by bbcallen** [comment]
I don't know. I don't have a tvOS for testing.

**Comment by Sebacho-Barajas** [comment]
if we add tvos ffmpeg codecs to the player and test it with simulator do you think it might work?

**Comment by bbcallen** [comment]
No idea without test.

**Comment by Sebacho-Barajas** [comment]
@bbcallen  I tested it with simulator and frameworks seems to work , it displayed video and audio , i had to comment IJKMPMoviePlayerController.h because tvOS does not support MPMoviePlayerController

**Comment by Sebacho-Barajas** [comment]
tested on tvOS simulator and it worked properly!

**Comment by psegalen** [comment]
Hi @Sebacho-Barajas, is there any chance you'd like to share how you made it work?
Seems to me that one would need to add a "TV Framework" target but there are many things that are unavailable on tvOS. :(

**Comment by Sebacho-Barajas** [comment]
hi @psegalen  , I did not test it on an actual device but on the simulator and it worked, it means the player can work in tvOS but they need to update the framework to support tvOS , if you need a media framework that supports ffmpeg and tvOS take a look at this framework [https://github.com/libobjc/SGPlayer](url)

**Comment by psegalen** [comment]
Hi @Sebacho-Barajas a big thank you for this, I'll test it!

**Comment by qiudaomao** [comment]
It's working well, see https://github.com/qiudaomao/ijkplayer tvos branch
