### ISSUE TITLE
Seek local file to not loaded part direct ffp_notify_msg1(ffp, FFP_MSG_COMPLETED)

### ISSUE THREAD

**Issue by hawk0620** [Bilibili/ijkplayer#2068]
Hello, bbcallen. When use ijkplayer to play local file such as a flac music(almost 30mb), if I seek it more than half of the duration (not loaded part), and it will call `ffp_notify_msg1(ffp, FFP_MSG_COMPLETED);` , then the file is direct stop (notification log is `playbackStateDidChange: IJKMPMovieFinishReasonPlaybackEnded: 0`). I want to know how to seek local file to it not loaded part. Thank u~

**Comment by bbcallen** [comment]
That should be an ffmpeg issue, take a look at the comment of avformat_seek_file().

**Comment by hawk0620** [comment]
Thanks a lot.
