### ISSUE TITLE
求教将多个ts分片存放成vod协议的文件，播放视频时，每个ts分片的进度条都从0开始。web端没有问题。

### ISSUE THREAD

**Issue by Cheng-Bin** [Bilibili/ijkplayer#2076]
播放链接： http://resource-s3.lycam.tv/apps/BWT8UYQBY1/a7d46360-0c2b-11e6-bd58-a17ac5f737ba/streams/tgtg/hls/vod.m3u8

**Comment by Cheng-Bin** [comment]
http://resource-s3.lycam.tv/apps/BWT8UYQBY1/a7d46360-0c2b-11e6-bd58-a17ac5f737ba/streams/tgtg/hls/vod.m3u8

**Comment by bbcallen** [comment]
#2061

**Comment by StuStatic** [comment]
your m3u8 may be wrong , I mean that your m3u8 could be played but the format just let the time begin with 00:00 since the the last ts  finished , I have suffered your problem when I used the wrong m3u8 ,it could be played but the time got wrong,so ask your video maker to remake your m3u8
