### ISSUE TITLE
打包之后找不到libijksdl.so

### ISSUE THREAD

**Issue by 18369188711why** [Bilibili/ijkplayer#2079]
项目中将所有的内容都编译到一个类库里，然后将类库作为module在主项目中引用，在直接使用USB连接手机运行时没有任何问题，打包之后，就出现找不到libijksdl.so的问题。
libijksdl.so文件放在了module的src/main/libs文件下，并且在grandle中配置了jniLibs的路径，载入so文件使用的是System.loadLibrary("ijksdl");
打包之后运行时打印出的日志报的是UnsatisfiedLinkError:JNI_ERR from JNI_Onload in "data/app-lib/包名/libijksdl.so"
请问该如何解决？

**Comment by 18369188711why** [comment]
非常感谢你，我已经解决这个问题了，是代码混淆的原因 
我在主项目中的混淆文件中加了这几行之后就可以了
-keep class tv.danmaku.ijk.media.player.** {*; }
-keep class tv.danmaku.ijk.media.player.IjkMediaPlayer{

; } -keep class tv.danmaku.ijk.media.player.ffmpeg.FFmpegApi{
; }

**Comment by lczxxx123** [comment]
复制这几句进去后失败啊……好像是提示不能有‘；’这个符号吧？

**Comment by lczxxx123** [comment]
语法正确的话我猜是这样：
-keep class tv.danmaku.ijk.media.player.* {*;}
-keep class tv.danmaku.ijk.media.player.IjkMediaPlayer{*;}
-keep class tv.danmaku.ijk.media.player.ffmpeg.FFmpegApi{*;}
不过只是语法通过，能不能还不一定。
我的话加入这几句后运行仍然失败。
我的环境是android studio。
ndk版本为r13b。
example的gradle里面已加入
allprojects {
    repositories {
        jcenter()
    }
}
混淆也加入，build也整个projectbuild。
然后run example，然后运行在HM2A上尝试打开文件的时候还是提示无法加载ijkffmpeg

**Comment by 516043893** [comment]
-keep class tv.danmaku.ijk.media.player.** {*;}
-keep class tv.danmaku.ijk.media.player.IjkMediaPlayer.**{*;}
-keep class tv.danmaku.ijk.media.player.ffmpeg.FFmpegApi.**{*;}

**Comment by 516043893** [comment]
-keep class tv.danmaku.ijk.media.player.** {*;}
-keep class tv.danmaku.ijk.media.player.IjkMediaPlayer.**{*;}
-keep class tv.danmaku.ijk.media.player.ffmpeg.FFmpegApi.**{*;}
