### ISSUE TITLE
您好，关于IJKPlayer播放网络上的mp4文件时，关闭之后，释放不了的问题

### ISSUE THREAD

**Issue by kinderYue** [Bilibili/ijkplayer#2081]

**Comment by kinderYue** [comment]
我时ios开发

**Comment by kinderYue** [comment]
ijkmp_stop()
ijkmp_stop()=0
ijkmp_shutdown_l()
LittleBaiTravel(1334,0x16e503000) malloc: *** error for object 0x114b14008: pointer being freed was not allocated
这是我调用 shutdown 时的log

**Comment by skyhome2016** [comment]
我释放视图时，前shutdown，就没有声音了啊，

**Comment by kinderYue** [comment]
我一调用shutdown 就crash了，是什么问题
 ijkmp_stop()
ijkmp_stop()=0
ijkmp_shutdown_l()
LittleBaiTravel(1334,0x16e503000) malloc: *** error for object 0x114b14008: pointer being freed was not allocated
为什么报野指针了

**Comment by wushenchao** [comment]
我也遇到了同样的问题调用shutdown 后 日志一直在打印 254: AQDefaultDevice (173): skipping input stream 0 0 0x0

**Comment by xinzhengzhang** [comment]
@wushenchao 
What your ijk and ffmpeg version and provide me the video sample

**Comment by wushenchao** [comment]
@xinzhengzhang  
av_version_info: ff3.0--ijk0.5.0--dev0.4.5--rc11

**Comment by xinzhengzhang** [comment]
ijkversion?

**Comment by kinderYue** [comment]
@wushenchao 建议使用vlc吧 那个也不错

**Comment by wushenchao** [comment]
@xinzhengzhang  
I used example demo, the version message: ( av_version_info: ff3.2--ijk0.7.2-20161107--001  ijk_version_info: k0.7.4,) 。
it also log AQDefaultDevice (173): skipping input stream 0 0 0x0, when i closed.

**Comment by xinzhengzhang** [comment]
@wushenchao 
To avoid blocking the current thread, ijkplayer will close itself asynchronously (iOS).
There is no need to worry about the output after you closed the player in a few milliseconds.
If the output thread still running after a long time, please let me know.

BTW, If you want to close it synchronously, just implement it reference by the `shutdown` in `IJKFFMoviePlayerController`.

**Comment by wushenchao** [comment]
@xinzhengzhang 
It still output after I closed. 

So, I try you method,It not worked.

**Comment by xinzhengzhang** [comment]
@wushenchao Please provide me the whole project which could reproduce this issue

**Comment by maker997** [comment]
@wushenchao
你的那个问题解决了吗,同求答案

**Comment by wushenchao** [comment]
没有，shutdown之后，还是一直在打印，多次掉用会崩溃。未找到解决方法。

**Comment by maker997** [comment]
@wushenchao 我的不会崩溃,就是一直打印信息.强迫症受不了啊

**Comment by wushenchao** [comment]
@maker997  真机上面好像就没有打印了。。。
