### ISSUE TITLE
播放视频图像倒立

### ISSUE THREAD

**Issue by MrQQQQQQQQQQ** [Bilibili/ijkplayer#209]
使用ijk-ios 播放视频的时候 ，有的视频在播放的时候 图像是倒立的，而使用系统自带播放器播放同一视频则正常，请问这个问题应该怎么处理呢？
谢谢！

**Comment by MrQQQQQQQQQQ** [comment]
用的是 IJKFFMoviePlayerController 播放的 网络流视频文件。

**Comment by bbcallen** [comment]
目测是MP4的rotation属性，现在暂时不支持。

**Comment by MrQQQQQQQQQQ** [comment]
那如果要做的话，应该从哪里入手呢，是否可以从解码器中获取到rotation属性，然后再对view进行调整？

**Comment by bbcallen** [comment]
我不太了解mp4的属性，但这应该是最简单的做法。

**Comment by lemoon** [comment]
@MrQQQQQQQQQQ        

ffmpeg有获取旋转角度的方法。
http://blog.csdn.net/zsc09_leaf/article/details/45848175

**Comment by bbcallen** [comment]
Partial fixed: ed814911b41f0d65ae022b08e403b3a60cda7695

**Comment by Zeaa** [comment]
@bbcallen iOS 还没有支持rotation
