### ISSUE TITLE
Is it timeout is not enabled ?

### ISSUE THREAD

**Issue by poholo** [Bilibili/ijkplayer#2091]
I set
`IJKFFOptions *options = [[IJKFFOptions alloc] init];
    
    [options setPlayerOptionIntValue:30     forKey:@"max-fps"];
    [options setPlayerOptionIntValue:0      forKey:@"framedrop"];
    [options setPlayerOptionIntValue:3      forKey:@"video-pictq-size"];
    [options setPlayerOptionIntValue:0      forKey:@"videotoolbox"];
    [options setPlayerOptionIntValue:960    forKey:@"videotoolbox-max-frame-width"];
    
    [options setFormatOptionIntValue:0                  forKey:@"auto_convert"];
    [options setFormatOptionIntValue:1                  forKey:@"reconnect"];
    [options setFormatOptionIntValue:0   forKey:@"timeout"];
    [options setFormatOptionValue:@"ijkplayer"          forKey:@"user-agent"];
`

but I receive IJKPlayer's timeout almost at 30 secends

**Comment by SoXeon** [comment]
timeout参数只对http设置有效，若果你用rtmp设置timeout，ijkplayer内部会忽略timeout参数。
rtmp的timeout参数含义和http的不一样。

**Comment by poholo** [comment]
嗯 明白了
