### ISSUE TITLE
The method 'stop' does not work [iOS]

### ISSUE THREAD

**Issue by ijovi23** [Bilibili/ijkplayer#2092]
In the iOS Demo, I added a button to `IJKMediaControl` and linked it to the following method in `IJKVideoViewController`:
```
- (void)onClickStop:(id)sender
{
    [self.player stop];
    [self.mediaControl refreshMediaControl];
}
```

When I called the method `-stop`, the video screen stopped but the audio was still playing, the progress bar was still sliding.

version: k0.6.2
config: module-default.sh
os: masOS 10.12
Xcode: 7.3.1

**Comment by bbcallen** [comment]
Fixed in 1439b2b16d3c63afad93606b07696716fff3eb5d.
You may also call pause before stop to workaround this issue.
