### ISSUE TITLE
该播放器是否支持视频清晰度自适应？

### ISSUE THREAD

**Issue by hfdftl** [Bilibili/ijkplayer#2105]
Android 版本 用一个在其他播放器能够自适应清晰度的m3u8播放地址 放到该播放器中进行播放，无法看到视频清晰度的变化。请问播放器是否有相应的设置接口 来处理该需求。

**Comment by bbcallen** [comment]
No.

**Comment by zhaodp** [comment]
FFMPEG目前不支持HLS的码率自适应
