### ISSUE TITLE
关于请求m3u8携带参数，ijk访问m3u8文件中的key没有携带参数的bug

### ISSUE THREAD

**Issue by tanqu2013** [Bilibili/ijkplayer#2112]
我使用的ijk版本是0.5.1，我设置一条携带参数的url给ijk播放器，url地址是
http://hls.videocc.net/e355544915/d/e35554491552ba86b85dfb6a698f85ed_1.m3u8?ts=1476431516994&sign=e7ff3356de34d4a0b227e5ad2b814ec8
其中携带了参数ts和sign。

如果用浏览器打开这个链接，可以看到里面的key的url是
http://hls.videocc.net/e355544915/d/e35554491552ba86b85dfb6a698f85ed_1.key?ts=1476431516994&sign=2568bf46623a2e40c1eef11da9c0d9ec
也有ts参数和sign参数。

但ijk的访问确是10-14 15:38:41.201: E/IJKMEDIA(22930): Unable to open key file http://hls.videocc.net/e355544915/2/e3555449156db6d402d88a8f4462a132_1.key
没有携带任何参数，此条log由ijk输出。这里的Unable to open key file 是因为没有携带参数，服务器不允许访问，可以不用在意。

ijk访问m3u8中的key 的url时把参数部分给截掉了，请问这是否是一个bug呢？

**Comment by bbcallen** [comment]
You need to build ffmpeg with openssl support

**Comment by tanqu2013** [comment]
OK,thanks.
