### ISSUE TITLE
Use NDK r13 build fail.Only Ndk r10e support?

### ISSUE THREAD

**Issue by yangchengtest** [Bilibili/ijkplayer#2118]
error code:
IJK_NDK_REL=13.0.3315539
You need the NDKr10e or later

**Comment by neocpp** [comment]
把do-detect-env.sh和do-compile-ffmpeg.sh更新下，新版修改了

**Comment by yangchengtest** [comment]
谢谢，更新后ok了，多谢。

**Comment by fishsoft** [comment]
这两个文件在哪，怎么找不到
