### ISSUE TITLE
ijkplayer cannot run on android studio

### ISSUE THREAD

**Issue by sent316** [Bilibili/ijkplayer#213]
Hi,

I have compiled libraries ( latest stable version ) in ubuntu 14.04 successfully. I have imported " android/ijkmediaplayer " in android studio.  When i import this project in android studio it has no layout files or any other informations in manifest.xml file, so i can't run or create apk from this project.  

How can i run this ijkmediaplayer in android studio?

Thanks in advance.

**Comment by bbcallen** [comment]
ijkmediaplayer is a lib project. apk is supposed to be created from ijkmediademo.
