### ISSUE TITLE
App freezes on destroy if is loading (using librtmp)

### ISSUE THREAD

**Issue by migueltarga** [Bilibili/ijkplayer#2135]
Hi, I know you guys don't support librtmp but Im looking for some directions if is related to ijk.
The problem is, if a rtmp video is loading (using librtmp) and I press the back button, the app freezes and i need to force quit. here is the logs:

```
10-19 07:47:14.102 14601-14601/my.app D/IJKMEDIA: ijkmp_stop()
10-19 07:47:14.102 14601-14601/my.app D/IJKMEDIA: ijkmp_stop()=0
10-19 07:47:14.102 14601-14601/my.app D/IJKMEDIA: IjkMediaPlayer_release
10-19 07:47:14.102 14601-14601/my.app D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
10-19 07:47:14.102 14601-14601/my.app D/IJKMEDIA: ffpipeline_set_surface()
10-19 07:47:14.102 14601-14601/my.app D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
10-19 07:47:14.102 14601-14601/my.app D/IJKMEDIA: ijkmp_shutdown_l()
10-19 07:47:14.102 14601-14601/my.app D/IJKMEDIA: wait for read_tid
10-19 07:47:14.102 14601-22408/my.app D/IJKMEDIA: message_loop exit
10-19 07:47:14.102 14601-22408/my.app I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [22408]
10-19 07:47:14.112 14601-22409/my.app I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [22409]
```

Thank you

**Comment by bbcallen** [comment]
Better take a breakpoint, to see where it was blocked.

**Comment by migueltarga** [comment]
it stops on "IMediaPlayer release()"


if I get a connection timeout than it releases the threat, otherwise it will keep locked:

```
10-20 07:34:34.263 17698-18162/my.app E/IJKMEDIA: RTMP_Connect0, failed to connect socket. 110 (Connection timed out)
10-20 07:34:34.263 17698-18162/my.app E/IJKMEDIA: rtmp://208.53.180.178/ctv: Unknown error occurred
10-20 07:34:34.263 17698-18162/my.app I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [18162]
10-20 07:34:34.263 17698-17698/my.app D/IJKMEDIA: wait for video_refresh_tid
10-20 07:34:34.263 17698-17698/my.app D/IJKMEDIA: ijkmp_shutdown_l()=void
10-20 07:34:34.263 17698-17698/my.app D/IJKMEDIA: ijkmp_dec_ref(): ref=0
10-20 07:34:34.263 17698-17698/my.app D/IJKMEDIA: ijkmp_shutdown_l()
10-20 07:34:34.263 17698-17698/my.app D/IJKMEDIA: ijkmp_shutdown_l()=void
```

**Comment by bbcallen** [comment]
That's it.
ijkplayer always waits connect to be closed in release(), for now.
Release player in non-ui thread as a workaround.
You can also modify ff_ffplay.c, to release input in the background, which is a little more complicated.

**Comment by migueltarga** [comment]
Awesome! Thanks @bbcallen!

**Comment by KrishnaGujju** [comment]
@migueltarga Can you help me to compile ijkplayer with librtmp.

**Comment by migueltarga** [comment]
@KrishnaGujju yes, where are you at?

**Comment by KrishnaGujju** [comment]
@migueltarga My Email Id - krishnagujjumodi@gmail.com

**Comment by diaconuliviu85** [comment]
Pls  help me to compile ijkplayer with librtmp. My email. diaconuliviu85@gmail.com . and i am invited a beer.

**Comment by SmallwolfiOS** [comment]
Can you help me to compile ijkplayer with librtmp. i have the same issue ，show me your email 
my email id  - mahaiping528@gamil.com @migueltarga migueltarga

**Comment by HatsuneMikuV** [comment]
@migueltarga @KrishnaGujju @diaconuliviu85 @SmallwolfiOS 
Can you help me to compile ijkplayer with librtmp. i have the same issue 
If any of you are free, send me a copy, thank you.
my email id - l15188588180@gmail.com
