### ISSUE TITLE
怎么添加需要的解码器？

### ISSUE THREAD

**Issue by leimeimei** [Bilibili/ijkplayer#2138]
我这里要播放一些H.264/AVC编码的mp4文件，音频编码是PCM_ALAW，目前播放不了。编译的时候怎么添加我需要的这些解码器？

**Comment by bbcallen** [comment]
run ./configure --help in ffmpeg's directory.

**Comment by wkowko** [comment]
你好具体怎样实现 我需要解码 speex 谢谢了

**Comment by HatsuneMikuV** [comment]
请问怎么实现？一直报错

**Comment by HatsuneMikuV** [comment]
@leimeimei @wkowko   请问有没有直接的文档   如何添加库

**Comment by aohanhongzhi** [comment]
同样需要解析 pcm_alaw的编码，还没有解决方案吗？
