### ISSUE TITLE
关于视频解码的问题

### ISSUE THREAD

**Issue by change2hao** [Bilibili/ijkplayer#214]
我最近的iOS工程中用到一个第三方摄像头厂商提供的SDK，里边并不是直接给播放器传一个播放地址，而是提供了两个buffer数组，一个是音频的，一个是图像的，请问一下这个应该怎么解码，并最终显示摄像头实况，是不是需要调底层接口，我对ffmpeg不是太熟悉，希望得到一些帮助活着建议，谢谢啦~

**Comment by bbcallen** [comment]
让他们给示例代码。
