### ISSUE TITLE
正在播放视频，锁屏

### ISSUE THREAD

**Issue by wanglifeifei** [Bilibili/ijkplayer#2141]
正在播放视频，此时进行锁屏，调用暂停的方法，然而还能继续播放，打印出这个 IJKSDLGLView:display: unable to tryLock GL active: 0，这个怎么解决

**Comment by bbcallen** [comment]
That's debug information. No need to be resolved.

**Comment by wanglifeifei** [comment]
但是现在，锁屏，视频播放暂停不了

**Comment by wanglifeifei** [comment]
已经解决了，是我自己写的有问题

**Comment by clark-new** [comment]
怎么解决的 能和我说下吗  最好告诉我代码怎么写的 我也遇到这个问题了
