### ISSUE TITLE
ios 为什么启用硬解码失败了

### ISSUE THREAD

**Issue by PengBoShi** [Bilibili/ijkplayer#2142]
init_videotoolbox - using avcC atom of size(38), ref_frames(1)after scale width 0 height 0 
2016-10-20 16:45:42.406819 vrplayercube[1677:374090] Error Error Domain=NSOSStatusErrorDomain Code=-12911 "(null)"
CreateVTBSession - failed with status = (-12911)could not init video tool box decoder !!!vtb fail!!! switch to ffmpeg decode!!!!

**Comment by chodison** [comment]
scale width 0 height 0

**Comment by PengBoShi** [comment]
2016-10-21 14:08:33.013078 vrplayercube[1138:221258] [DYMTLInitPlatform] platform initialization successful

2016-10-21 14:08:33.109587 vrplayercube[1138:221157] -> registered mono modules 0x1016541c0
-> applicationDidFinishLaunching()
-> applicationDidBecomeActive()
Renderer: Apple A8 GPU
Vendor:   Apple Inc.
Version:  OpenGL ES 2.0 Apple A8 GPU - 95.16
GLES:     2
GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_vertex_array_object GL_EXT_blend_minmax GL_EXT_color_buffer_half_float GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_draw_instanced GL_EXT_instanced_arrays GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_pvrtc_sRGB GL_EXT_read_format_bgra GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_texture_lod GL_EXT_shadow_samplers GL_EXT_sRGB GL_EXT_texture_filter_anisotropic GL_EXT_texture_rg GL_EXT_texture_storage GL_APPLE_clip_distance GL_APPLE_color_buffer_packed_float GL_APPLE_copy_texture_levels GL_APPLE_framebuffer_multisample GL_APPLE_rgb_422 GL_APPLE_sync GL_APPLE_texture_format_BGRA8888 GL_APPLE_texture_max_level GL_APPLE_texture_packed_float GL_IMG_r

ead_format GL_IMG_texture_compression_pvrtc 
OPENGL LOG: Creating OpenGL ES 2.0 graphics device ; Context level  <OpenGL ES 2.0> ; Context handle 1946355840
Initialize engine version: 5.4.0f3 (a6d8d714de6f)
OnLevelWasLoaded was found on GvrViewer
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed
 
(Filename:  Line: 375)

-------- Shader compilation failed
#version 100
#extension GL_EXT_frag_depth : enable
precision highp float;
uniform highp vec4 _ProjectionParams;
uniform highp vec4 _ZBufferParams;
uniform highp mat4 unity_CameraToWorld;
uniform highp mat4 _NonJitteredVP;
uniform highp mat4 _PreviousVP;
uniform highp sampler2D _CameraDepthTexture;
varying highp vec2 xlv_TEXCOORD0;
varying highp vec3 xlv_TEXCOORD1;
void main ()
{
  highp vec4 tmpvar_1;
  tmpvar_1 = texture2D (_CameraDepthTexture, xlv_TEXCOORD0);
  mediump vec2 tmpvar_2;
  highp vec4 tmpvar_3;
  tmpvar_3.w = 1.0;
  tmpvar_3.xyz = ((xlv_TEXCOORD1 * (_ProjectionParams.z / xlv_TEXCOORD1.z)) * (1.0/((
    (_ZBufferParams.x * tmpvar_1.x)
   + _ZBufferParams.y))));
  highp vec4 tmpvar_4;
  tmpvar_4 = (unity_CameraToWorld * tmpvar_3);
  highp vec4 tmpvar_5;
  tmpvar_5 = (_PreviousVP * tmpvar_4);
  highp vec4 tmpvar_6;
  tmpvar_6 = (_NonJitteredVP * tmpvar_4);
  highp vec2 tmpvar_7;
  tmpvar_7 = (((tmpvar_5.xy / tmpvar_5.w) + 1.0) / 2.0);
  highp vec2 tmpvar_8;
  tmpvar_8 = (((tmpvar_6.xy / tmpvar_6.w) + 1.0) / 2.0);
  tmpvar_2 = (tmpvar_8 - tmpvar_7);
  mediump vec4 tmpvar_9;
  tmpvar_9.zw = vec2(0.0, 1.0);
  tmpvar_9.xy = tmpvar_2;
  gl_FragDepthEXT = tmpvar_1.x;
  gl_FragData[0] = tmpvar_9;
}
-------- failed compiling:
fragment evaluation shader
WARNING: 0:4: extension 'GL_EXT_frag_depth' is not supported
ERROR: 0:38: Use of undeclared identifier 'gl_FragDepthEXT'

Note: Creation of internal variant of shader 'Hidden/Internal-MotionVectors' failed.
WARNING: Shader Unsupported: 'Hidden/Internal-MotionVectors' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/Internal-MotionVectors' - Setting to default shader.
UnloadTime: 2.009958 ms
===== custom modules begin =====
skip     protocol: async (duplicated)
register protocol: ijkhttphook
register protocol: ijkinject
register protocol: ijklongurl
register protocol: ijksegment
register protocol: ijktcphook
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff3.0--ijk0.5.0--dev0.4.5--rc11
ijkmp_set_inject_opaque(0x10c23cc70)
ijkmp_set_inject_opaque()=void
2016-10-21 14:08:34.873220 vrplayercube[1138:221157] OK setup GL

ijkmp_ios_set_view(glView=0x10c112f90)
ijkmp_ios_set_view(glView=0x10c112f90)=void
prepareToPlay  time :  1477030114883
ijkmp_set_data_source(url="rtmp://192.168.1.114:1935/guoshanche/0005.mp4")
ijkmp_set_data_source(url="rtmp://192.168.1.114:1935/guoshanche/0005.mp4")=0
ijkmp_prepare_async()
remove 'timeout' option for rtmp.
===== versions =====
FFmpeg       : ff3.0--ijk0.5.0--dev0.4.5--rc11
libavutil    : 55.17.103
libavcodec   : 57.24.102
libavformat  : 57.25.100
libswscale   : 4.0.100
libswresample: 2.0.101
===== options =====
player-opts : start-on-prepared            = 1
player-opts : overlay-format               = fcc-_es2
player-opts : max-fps                      = 30
player-opts : framedrop                    = 0
player-opts : videotoolbox-max-frame-width = 960
player-opts : videotoolbox                 = 1
player-opts : video-pictq-size             = 3
format-opts : ijkinject-opaque             = 4498639984
format-opts : ijkapplication               = 4359464576
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : safe                         = 0
format-opts : reconnect                    = 1
===================
ijkmp_prepare_async()=0
remove 'timeout' option for rtmp.
No default whitelist set
No default whitelist set
Handshaking...
Type answer 3
Server version 13.14.10.13
Proto = rtmp, path = /guoshanche/0005.mp4, app = guoshanche, fname = mp4:0005.mp4
Server bandwidth = 5000000
Client bandwidth = 5000000
New incoming chunk size = 102400
Creating stream...
Setting up 1 worker threads for Enlighten.
  Thread -> id: 16f733000 -> priority: 1 
Sending play command for 'mp4:0005.mp4'
2016-10-21 14:08:35.016863 vrplayercube[1138:221157] invalid mode 'kCFRunLoopCommonModes' provided to CFRunLoopRunSpecific - break on _CFRunLoopError_RunCalledWithInvalidMode to debug. This message will only appear once per execution.

**Comment by PengBoShi** [comment]
启用硬解码失败

**Comment by bbcallen** [comment]
The log doesn't show anything useful.
