### ISSUE TITLE
Which tools do you use to read this project？

### ISSUE THREAD

**Issue by vincentssn** [Bilibili/ijkplayer#2149]
These day I meet some problems that I must try to modify the ijkplayer, but I found it hard to read many code if I use raw vim and iterm+zsh in command line. Can you recommend some useful tools for me? Either Mac os or windows is ok!

**Comment by migueltarga** [comment]
This issue is not related to the project.
But you can use Sublime Text, Eclipse, Android Studio, Visual Code...

**Comment by PengBoShi** [comment]
I can help you

**Comment by PengBoShi** [comment]
Can you speak Chinese? I am working hard on my English .

**Comment by bbcallen** [comment]
xcode

**Comment by WangMJ** [comment]
source insight

**Comment by vincentssn** [comment]
@PengBoShi 谢谢PengBoshi，你读这类工程用的是什么工具？
