### ISSUE TITLE
Deinterlacing

### ISSUE THREAD

**Issue by rvlaskamp** [Bilibili/ijkplayer#215]
Is it possible to enable deinterlacing on a video stream? I am using your project in an Android app and playing a multicast mpeg-ts stream. The stream is interlaced.

**Comment by bbcallen** [comment]
Post process and video filters are removed from ffplay, due to extra memory copy.
You need to merge those codes from ffplay.

**Comment by rvlaskamp** [comment]
Ok, thanks. Can you explain me how I can merge those codes from ffplay? And how can I use them in the Android app?

**Comment by bbcallen** [comment]
Diff ff_ffplay.c and original ffplay.c, to see the difference.

**Comment by qazmoon** [comment]
@rvlaskamp  hi, I add the code to process deinterlacing,  but  it will have memory leak if play a long time stream.
the code is at:
https://github.com/Bilibili/ijkplayer/issues/314

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
