### ISSUE TITLE
视频有声音没画面

### ISSUE THREAD

**Issue by zywang** [Bilibili/ijkplayer#2150]
hi，请帮忙看下，在我们平台上有部分视频只有声音，没有画面。下面是视频地址，期待回复。

http://ugcvideo-10038986.video.myqcloud.com/mixiongrecorder/10108_1477104386095.mp4

**Comment by zywang** [comment]
补充：使用系统iOS或Android系统播放器可以播放，VLC也能播放。

**Comment by PengBoShi** [comment]
那你看看解码是不是成功了。

**Comment by PengBoShi** [comment]
哥们 我试了一下 你的这个地址 这不是ijk的问题 是你这个视频有问题

**Comment by PengBoShi** [comment]
你们这个视频是有问题的。pkt的 pts和duration都不对的。接收到的视频数据根本没有加入缓存队列，而是释放了。

**Comment by zywang** [comment]
hi，这个视频是有问题，我一个同事制作完导出时候没有选择编码器导致的。

**Comment by LiuLongChang** [comment]
遇见了同样的问题   只有声音没有画面       不知道在iOS端怎么解决

**Comment by leopardpan** [comment]
@LiuLongChang  我也遇到这个问题了，请问你解决了吗？

**Comment by YYHNobug** [comment]
只有声音没有画面 不知道在iOS端怎么解决
