### ISSUE TITLE
windows系统下使用Cygwin编译出现下面错误

### ISSUE THREAD

**Issue by dyl169** [Bilibili/ijkplayer#2154]
Toolchain installed to /cygdrive/d/android/other/ijkplayer-master/android/contrib/build/ffmpeg-armv5/toolchain.
touch: 无法创建'/cygdrive/d/android/other/ijkplayer-master/android/contrib/build/ffmpeg-armv5/toolchain/touch': No such file or directory

**Comment by bbcallen** [comment]
Sorry, I don't maintain cygwin support.

**Comment by dyl169** [comment]
请问windows系统如何编译。

**Comment by dyl169** [comment]
请问windows系统下如何编译。

**Comment by bbcallen** [comment]
No idea, I rarely develop on windows.

**Comment by dyl169** [comment]
thank you
