### ISSUE TITLE
ijkplayer new version can not paly aes-128 hls streams.

### ISSUE THREAD

**Issue by asircao** [Bilibili/ijkplayer#2158]
ijkplayer new version can not paly aes-128 hls streams. ffmpeg version is ff3.1--ijk0.6.2--20160926--001

ffmpeg version ff3.0--ijk0.5.0--dev0.4.5--rc11 can play aes-128 hls streams.

you can test it with this url: http://45.79.157.148/zhengduoyan_mac_key/zhengduoyan.m3u8

**Comment by bbcallen** [comment]
You need to build ffmpeg with openssl support

**Comment by asircao** [comment]
@bbcallen thanks for your message.  I hava build openssl first, then build ffmpeg. libssl.a and libcrypto.a be linked. you can play that test url, that url can play by ffplay, but can not play by ijkplayer.

**Comment by bbcallen** [comment]
You can make a diff between this two version of ffmpeg/libavformat/hls.c, to see what's going wrong.

**Comment by asircao** [comment]
@bbcallen ijkplayer info : Failed to open segment of playlist 0 
means ffmpeg/libavformat/hls.c:open_input  run failed, I diff hls.c between ffmpeg branch origin/release/3.1 and ff3.1--ijk0.6.2--20160926--001, this function is same.

**Comment by bbcallen** [comment]
Make a breakpoint to see what's going wrong in there.

**Comment by asircao** [comment]
enable crypto will work
