### ISSUE TITLE
FFMpeg 2.6.2

### ISSUE THREAD

**Issue by KCastiglione** [Bilibili/ijkplayer#216]
Can this be updated to latest ffmpeg 2.6.2? if so how?
Thank you!

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/init-android.sh
It could be modified like this
```
# ijk-r0.2.2-dev is based on n2.6.0
# IJK_FFMPEG_COMMIT=ijk-r0.2.1-dev
IJK_FFMPEG_COMMIT=ijk-r0.2.2-dev
```

or without patch
```
IJK_FFMPEG_COMMIT=n2.6.2
```

I'm working on some patch, which has not be tested enough, yet

**Comment by KCastiglione** [comment]
Thank you for your reply.
How about for iOS ? Is it same? Thank you

**Comment by bbcallen** [comment]
Same in this file:
https://github.com/Bilibili/ijkplayer/blob/master/init-ios.sh

**Comment by KCastiglione** [comment]
Thank you very much!
