### ISSUE TITLE
编译ijk后，使用as 编译demo出错400

### ISSUE THREAD

**Issue by aaword** [Bilibili/ijkplayer#2160]
as 向jcenter 下载依赖库的时候报了400的错误， 浏览器访问正常。
dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'

        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.3'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.6'
[问题截图](http://zhidao.baidu.com/question/308206039226886564.html)

**Comment by bbcallen** [comment]
You need a proxy.
