### ISSUE TITLE
每次seekto的时候，视频都要重新联网下载缓存,而不是使用已有的缓存

### ISSUE THREAD

**Issue by dingchao823** [Bilibili/ijkplayer#2161]
我看了b站的客户端是没有这个问题的，应该不是ijk的问题，这样的用户体验很不好。请问有解决的方法吗。

**Comment by bbcallen** [comment]
bilibili is a closed software, I'm not authorized to talk detail about it.

**Comment by PengBoShi** [comment]
ijk是开源的 完全可以自己去改ijk啊

**Comment by ZhanRu** [comment]
我也遇到了，不知道有没有人改过这个问题。

**Comment by zhangferry** [comment]
@dingchao823 @ZhanRu Have you figure it out?Thanks!

**Comment by raymond1012** [comment]
see ffmpeg async protocol

2017-03-16 12:26 GMT+08:00 zhangferry <notifications@github.com>:

**Comment by ZhanRu** [comment]
@zhangferry https://github.com/danikula/AndroidVideoCache

**Comment by zhangferry** [comment]
@ZhanRu Thanks you first.Do you know the OC code?

**Comment by ZhanRu** [comment]
@zhangferry  I don't know ...

**Comment by zhangferry** [comment]
All right.Thanks!
