### ISSUE TITLE
是否已经兼容做了Airplay这块？

### ISSUE THREAD

**Issue by poholo** [Bilibili/ijkplayer#2162]
我在代码中发现了这些，是否已经做了Airplay的兼容？
`@property (nonatomic) BOOL allowsMediaAirPlay; 
@property (nonatomic) BOOL isDanmakuMediaAirPlay;
@property (nonatomic, readonly) BOOL airPlayMediaActive;`

**Comment by bbcallen** [comment]
airplay is a feature of AVPlayer, not ijkplayer.
