### ISSUE TITLE
输入RTMP直播流地址无法播放视频

### ISSUE THREAD

**Issue by haofanning** [Bilibili/ijkplayer#2164]
video address:
rtmp://live.hkstv.hk.lxdns.com:1935/live/stream456

**Comment by bbcallen** [comment]
Can't play this URL with any player I've got.

**Comment by haofanning** [comment]
我用demo中的input url页面输入这个直播地址，点击play按键没有任何反应。这个地址我进行推流的时候才能测试使用，用其他播放器是没有问题的
