### ISSUE TITLE
About .SDP, Please help me

### ISSUE THREAD

**Issue by xiaowasly** [bilibili/ijkplayer#2166]
I have two url :rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov    And  rtsp://218.204.223.237:554/live/1/66251FC11353191F/e7ooqwcfbqjoo80j.sdp
All RTSP format ,  but The second url can not Play ,why?  Please help me ,thanks.
Include SDP ,What is different?

**Comment by xiaowasly** [comment]
.sdp

**Comment by bbcallen** [comment]
Sorry, not familiar with RTSP stuffs.

**Comment by java-Xs** [comment]
the second url is live Stream ?

**Comment by xiaowasly** [comment]
First of all, thank you for your reply, this question is too old, there is no such question now
