### ISSUE TITLE
compile-ffmpeg said "No such file or directory"

### ISSUE THREAD

**Issue by ProudNoob** [Bilibili/ijkplayer#2169]
I have followed your tutorial up to the compile-ffmpeg.sh all step, but it doesn't work:

```
[root@localhost contrib]# ./compile-ffmpeg.sh all
====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a arm64 x86 x86_64
FF_ACT_ARCHS = armv5 armv7a arm64 x86 x86_64

====================
[*] check env armv5
====================
FF_ARCH=armv5
FF_BUILD_OPT=

--------------------
[*] make NDK standalone toolchain
--------------------
build on Linux x86_64
ANDROID_NDK=/var/www/ijkplayer/android-ndk-r13
IJK_NDK_REL=13.0.3315539
NDKr13.0.3315539 detected
HOST_OS=linux
HOST_EXE=
HOST_ARCH=x86_64
HOST_TAG=linux-x86_64
HOST_NUM_CPUS=1
BUILD_NUM_CPUS=2
Auto-config: --arch=arm
Toolchain installed to /var/www/ijkplayer/ijkplayer-android/android/contrib/build/ffmpeg-armv5/toolchain.
touch: cannot touch `/var/www/ijkplayer/ijkplayer-android/android/contrib/build/ffmpeg-armv5/toolchain/touch': No such file or directory
```

Then when I tried to run ./compile-ijk.sh all, it threw an error message: 

```
[root@localhost android]# ./compile-ijk.sh all
profiler build: NO
Android NDK: ERROR:/var/www/ijkplayer/ijkplayer-android/android/ijkplayer/ijkplayer-armv5/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file
Android NDK: Check that /var/www/ijkplayer/ijkplayer-android/android/contrib/build/ffmpeg-armv5/output/libijkffmpeg.so exists  or that its path is correct
/var/www/ijkplayer/android-ndk-r13/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
/var/www/ijkplayer/ijkplayer-android/android
profiler build: NO
Android NDK: ERROR:/var/www/ijkplayer/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file
Android NDK: Check that /libijkffmpeg.so exists  or that its path is correct
/var/www/ijkplayer/android-ndk-r13/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
/var/www/ijkplayer/ijkplayer-android/android
profiler build: NO
Android NDK: ERROR:/var/www/ijkplayer/ijkplayer-android/android/ijkplayer/ijkplayer-arm64/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file
Android NDK: Check that /libijkffmpeg.so exists  or that its path is correct
/var/www/ijkplayer/android-ndk-r13/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
/var/www/ijkplayer/ijkplayer-android/android
profiler build: NO
Android NDK: ERROR:/var/www/ijkplayer/ijkplayer-android/android/ijkplayer/ijkplayer-x86/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file
Android NDK: Check that /libijkffmpeg.so exists  or that its path is correct
/var/www/ijkplayer/android-ndk-r13/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
/var/www/ijkplayer/ijkplayer-android/android
profiler build: NO
Android NDK: ERROR:/var/www/ijkplayer/ijkplayer-android/android/ijkplayer/ijkplayer-x86_64/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file
Android NDK: Check that /libijkffmpeg.so exists  or that its path is correct
/var/www/ijkplayer/android-ndk-r13/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
/var/www/ijkplayer/ijkplayer-android/android
```
 
What did I do wrong? I build this on CentOS release 6.8 (Final)

**Comment by bbcallen** [comment]
Using NDKr10e, or fetch master to build.

**Comment by ProudNoob** [comment]
It works fine now. Sorry for the trouble.

**Comment by maikoulin** [comment]
How do  you solve  this problem

**Comment by ProudNoob** [comment]
bbcallen literally said "Using NDKr10e, or fetch master to build"

**Comment by RamboPan** [comment]
@maikoulin 
download NDKr10e,place somewhere you like . and set ANDROID_NDK="the ndk'path". and run again.
下一个NDKr10e版本ndk，放在一个你想放的位置，更改前面的步骤ndk路径改为刚的位置，在运行一次就OK了。

**Comment by fukemy** [comment]
not working for me, mac-os 64:
```
build on Darwin x86_64
ANDROID_NDK=/Users/thehe/Library/Android/sdk/ndk-bundle
NDKr10e(64-bit) detected
```

```
--------------------
# to continue to build ffmpeg, run script below,
sh compile-ffmpeg.sh 
# to continue to build ijkplayer, run script below,
sh compile-ijk.sh 
THG:contrib thehe$ cd ..
THG:android thehe$ ./compile-ijk.sh 
profiler build: NO
Android NDK: ERROR:/Users/thehe/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /libijkffmpeg.so exists  or that its path is correct   
/Users/thehe/Library/Android/sdk/ndk-bundle/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
```

**Comment by AikinLei** [comment]
> not working for me, mac-os 64:
> 
> ```
> build on Darwin x86_64
> ANDROID_NDK=/Users/thehe/Library/Android/sdk/ndk-bundle
> NDKr10e(64-bit) detected
> ```
> 
> ```
> --------------------
> # to continue to build ffmpeg, run script below,
> sh compile-ffmpeg.sh 
> # to continue to build ijkplayer, run script below,
> sh compile-ijk.sh 
> THG:contrib thehe$ cd ..
> THG:android thehe$ ./compile-ijk.sh 
> profiler build: NO
> Android NDK: ERROR:/Users/thehe/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file    
> Android NDK: Check that /libijkffmpeg.so exists  or that its path is correct   
> /Users/thehe/Library/Android/sdk/ndk-bundle/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
> ```

Have you solved it  ？？

**Comment by AikinLei** [comment]
> not working for me, mac-os 64:
> 
> ```
> build on Darwin x86_64
> ANDROID_NDK=/Users/thehe/Library/Android/sdk/ndk-bundle
> NDKr10e(64-bit) detected
> ```
> 
> ```
> --------------------
> # to continue to build ffmpeg, run script below,
> sh compile-ffmpeg.sh 
> # to continue to build ijkplayer, run script below,
> sh compile-ijk.sh 
> THG:contrib thehe$ cd ..
> THG:android thehe$ ./compile-ijk.sh 
> profiler build: NO
> Android NDK: ERROR:/Users/thehe/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file    
> Android NDK: Check that /libijkffmpeg.so exists  or that its path is correct   
> /Users/thehe/Library/Android/sdk/ndk-bundle/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
> ```

Have you solved it ？？

**Comment by ta893115871** [comment]
#!/bin/bash


cd config

# rm删除
rm module.sh
# 从新指向 ，比如指向module-lite-hevc.sh

ln -s module-default.sh module.sh

cd ../android/contrib

# 清除
./compile-ffmpeg.sh clean

# 编译ffmpeg
./compile-ffmpeg.sh armv7a

cd ..

# 编译生成so
./compile-ijk.sh armv7a



guixiuzhong@guxiuzhongdeMacBook-Pro-2 ijkplayer-android % ./build_armv7a.sh  
====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a arm64 x86 x86_64
FF_ACT_ARCHS = FF_ACT_ARCHS_64

/Users/guixiuzhong/Desktop/ijk/ijkplayer-android/android/contrib
Removing .version
Removing config.h
Removing doc/config.texi
Removing ffbuild/.config
Removing ffbuild/config.fate
Removing ffbuild/config.log
Removing ffbuild/config.mak
Removing ffbuild/config.sh
Removing libavcodec/bsf_list.c
Removing libavcodec/libavcodec.version
Removing libavfilter/libavfilter.version
Removing libavformat/libavformat.version
Removing libavformat/protocol_list.c
Removing libavutil/avconfig.h
Removing libavutil/ffversion.h
Removing libavutil/libavutil.version
Removing libswresample/libswresample.version
Removing libswscale/libswscale.version
/Users/guixiuzhong/Desktop/ijk/ijkplayer-android/android/contrib
/Users/guixiuzhong/Desktop/ijk/ijkplayer-android/android/contrib
/Users/guixiuzhong/Desktop/ijk/ijkplayer-android/android/contrib
/Users/guixiuzhong/Desktop/ijk/ijkplayer-android/android/contrib
====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a arm64 x86 x86_64
FF_ACT_ARCHS = armv7a

====================
[*] check env armv7a
====================
FF_ARCH=armv7a
FF_BUILD_OPT=

--------------------
[*] make NDK standalone toolchain
--------------------
build on Darwin x86_64
ANDROID_NDK=/Users/guixiuzhong/Library/Android/sdk/ndk/android-ndk-r10e
NDKr10e(64-bit) detected
Copying prebuilt binaries...
Copying sysroot headers and libraries...
Copying c++ runtime headers and libraries...
Copying files to: /Users/guixiuzhong/Desktop/ijk/ijkplayer-android/android/contrib/build/ffmpeg-armv7a/toolchain
Cleaning up...
Done.

--------------------
[*] check ffmpeg env
--------------------

--------------------
[*] configurate ffmpeg
--------------------
/Users/guixiuzhong/Desktop/ijk/ijkplayer-android/android/contrib/build/ffmpeg-armv7a/toolchain/bin//arm-linux-androideabi-gcc
Unknown option "--disable-ffserver".
See ./configure --help for available options.
profiler build: NO
Android NDK: ERROR:/Users/guixiuzhong/Desktop/ijk/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /Users/guixiuzhong/Desktop/ijk/ijkplayer-android/android/contrib/build/ffmpeg-armv7a/output/libijkffmpeg.so exists  or that its path is correct   
/Users/guixiuzhong/Library/Android/sdk/ndk/android-ndk-r10
