### ISSUE TITLE
ijkplayer 软解慢，造成播放会有卡顿

### ISSUE THREAD

**Issue by PengBoShi** [Bilibili/ijkplayer#2173]
ijkplayer 软解慢，造成播放会出现卡顿。FFmpeg有没有设置 解码速度的API呢

**Comment by bbcallen** [comment]
No.

**Comment by PengBoShi** [comment]
谢谢。查资料，应该是可以开多线程解码的。目前我在尝试

**Comment by PengBoShi** [comment]
好像ijk中默认的就是三个线程在解码

**Comment by wtiandong** [comment]
解码这件事儿没法并行亲。H264是一个序列，b帧p帧都得基于前边的帧进行解码，这件事儿本身就是串行的。三线程解码是解码视频、解码音频和read packet，这个可以并行。
