### ISSUE TITLE
网络条件较差的环境下退出直播间概率性崩溃(ijkff_inject_callback)

### ISSUE THREAD

**Issue by SilverBulletZyp** [Bilibili/ijkplayer#2174]
网络条件较差的情况时，退出直播间存在概率性崩溃，崩溃的地方如下图

![x jwgjbcj2z 9 6 x39 8](https://cloud.githubusercontent.com/assets/12904640/19722566/e1372dbe-9ba9-11e6-8687-6bd554f243a5.jpg)

![qq20161026-1](https://cloud.githubusercontent.com/assets/12904640/19722572/e7338cee-9ba9-11e6-90df-abbf25ae0461.png)

代码中释放ijkplayer的部分如下

``` objective-c
[self.ijkPlayer.view removeFromSuperview];
[self.ijkPlayer shutdown];
[self removePlayerRoomIJKViewNotification];
self.ijkPlayer = nil;
```

请问怎么修改可以解决这个问题呢？

**Comment by skyhome2016** [comment]
![e4a4c983-f2bd-48e4-b7b2-8a0972d53fa8](https://cloud.githubusercontent.com/assets/20390643/19753741/dbc3ad9a-9c39-11e6-8cff-af807b15df64.png)

**Comment by xinzhengzhang** [comment]
@SilverBulletZyp 
Try this patch [4787a6c9](https://github.com/Bilibili/ijkplayer/commit/4787a6c96c9eb1bc226fc773de891d23b1dab0f3)

**Comment by SilverBulletZyp** [comment]
@xinzhengzhang 我更新到0.6.3版本，在2G网络下测试还是会出现崩溃，位置为第一幅图1300行

**Comment by xinzhengzhang** [comment]
@SilverBulletZyp Update to master.

**Comment by SilverBulletZyp** [comment]
@xinzhengzhang 已经修复，非常感谢！
