### ISSUE TITLE
[av212109] Always in buffering state, may be problems in check_buffering

### ISSUE THREAD

**Issue by xqq** [Bilibili/ijkplayer#218]
大概因为packet本身没有duration，所以无法判断什么时候结束缓冲导致

http://www.bilibili.com/video/av212109

General
Format                         : Flash Video
File size                      : 41.9 MiB
Duration                       : 11mn 51s
Overall bit rate               : 494 Kbps

Video
Format                         : VP6
Duration                       : 12mn 9s
Bit rate                       : 423 Kbps
Width                          : 512 pixels
Height                         : 384 pixels
Frame rate mode                : Constant
Frame rate                     : 9.053 fps
Bit depth                      : 8 bits
Bits/(Pixel*Frame)             : 0.238
Stream size                    : 36.8 MiB (88%)

**Comment by bbcallen** [comment]
iOS版暂时没重现这问题，后面找时间调试一下安卓版。。。
