### ISSUE TITLE
如何调节音量（媒体音量而不是系统音量）

### ISSUE THREAD

**Issue by yhq-iOS** [Bilibili/ijkplayer#2181]
麻烦涉及过给点儿思路 谢谢了

**Comment by dourgulf** [comment]
我想楼主是希望增益吧，就是设备已经调到最高音量了，还想视频的声音在高一点。
估计楼主是在做连线之类的功能吧，连线之后，如果播放器和录音同时进行，打开了回音抑制之后，播放器的默认音量会被压低，效果就是听不清楚对方说啥。

**Comment by yhq-iOS** [comment]
thanks

**Comment by yycc** [comment]
我遇到的情况是，主播上麦并消除回声，然后连麦，同时播放连麦视频，声音变得很小。AVAudioSession设置[[AVAudioSession sharedInstance] setCategory: AVAudioSessionCategoryPlayAndRecord withOptions:AVAudioSessionCategoryOptionDefaultToSpeaker|AVAudioSessionCategoryOptionMixWithOthers error: nil]。楼主是否已解决类似问题？

**Comment by dourgulf** [comment]
连麦是个需要做很多工作的功能，不是简单拉一路推一路就行的，也不是ijk的解决范围了。

**Comment by yycc** [comment]
好吧😫，谢谢 @dourgulf

**Comment by notedit** [comment]
我在做连麦系统  已经基本可以工作  @dourgulf   你可以通过我的邮箱联系我

**Comment by yycc** [comment]
@notedit 能分享下您的思路吗？

**Comment by notedit** [comment]
用webrtc  进行混音合流  然后推到rtmp  cdn上去

**Comment by yycc** [comment]
谢谢 @notedit 。

**Comment by yuesehanpangmailang** [comment]
求同，如何解决 AVAudioSessionCategoryPlayAndRecord 后播放器声音变小
