### ISSUE TITLE
iOS ijk和unity CPU占用率太高了。

### ISSUE THREAD

**Issue by PengBoShi** [Bilibili/ijkplayer#2185]
ijk单跑大约50%，unity单跑15%，但是把ijk中的数据拿到unity中渲染，就会达到140%。为什么

**Comment by DeloDuan** [comment]
你怎么渲染的？ 直接unity 调用c++么?

**Comment by yeshibuzhong** [comment]
@DeloDuan   请问你是怎么渲染的  我这也需要渲染   不清楚怎么做

**Comment by yeshibuzhong** [comment]
@PengBoShi   兄弟  你是怎么渲染的

**Comment by yeshibuzhong** [comment]
@PengBoShi     目前还没有搞定, 希望哥们指点一下

**Comment by alordred** [comment]
求大神告知下怎么嵌入的

**Comment by PengBoShi** [comment]
unity导出一个工程 然后把ijkplayer导入这个工程




发自网易邮箱大师
在2017年07月26日 15:14，ALordRedness 写道：

求大神告知下怎么嵌入的

**Comment by Felix-Liufei** [comment]
您好大神，请问有demo地址么？我也想弄下ijk数据交给u3d渲染，求指点，谢谢。ps：unity导出工程，导入ijkplayer这些都完成了，就差渲染，一直没画面。

**Comment by cj657206427** [comment]
> @yeshibuzhong 搞定了，不过我这边渲染流程有点绕：
> 
> 1. 先将ijkplayer输出纹理的色彩空间改为RGBA格式；
> 2. 然后屏蔽了ijkplayer本身的渲染接口SDL_VoutDisplayYUVOverlay；
> 3. 通过SDL_VoutOverlayVideoToolBox_GetCVPixelBufferRef将每帧纹理获取后，供unity调用。
> 4. unity每次update渲染的时候，调用步骤3的接口取得CVPixelBuffer，然后交给OpenGLES或Metal渲染即可。

为何要改成RBGA，直接将YUV给到Unity，数据量会小很多，然后在shader中再去将yuv转rgb

**Comment by heberthe** [comment]
> @yeshibuzhong 搞定了，不过我这边渲染流程有点绕：
> 
> 1. 先将ijkplayer输出纹理的色彩空间改为RGBA格式；
> 2. 然后屏蔽了ijkplayer本身的渲染接口SDL_VoutDisplayYUVOverlay；
> 3. 通过SDL_VoutOverlayVideoToolBox_GetCVPixelBufferRef将每帧纹理获取后，供unity调用。
> 4. unity每次update渲染的时候，调用步骤3的接口取得CVPixelBuffer，然后交给OpenGLES或Metal渲染即可。

你好，可以加个 QQ （314285308）沟通下吗？通过你的方式，我在用 metal 渲染时一直碰到-6660 错误.
