### ISSUE TITLE
渲染问题renderer.c中的IJK_GLES2_Renderer_use方法

### ISSUE THREAD

**Issue by jiangmingz** [Bilibili/ijkplayer#2190]
/*
 * Per-Renderer routine
 */
GLboolean IJK_GLES2_Renderer_use(IJK_GLES2_Renderer *renderer)
{
    if (!renderer)
        return GL_FALSE;

    assert(renderer->func_use);
    if (!renderer->func_use(renderer))
        return GL_FALSE;

    IJK_GLES_Matrix modelViewProj;
    IJK_GLES2_loadOrtho(&modelViewProj, -1.0f, 1.0f, -1.0f, 1.0f, -1.0f, 1.0f);
    glUniformMatrix4fv(renderer->um4_mvp, 1, GL_FALSE, modelViewProj.m);                    IJK_GLES2_checkError_TRACE("glUniformMatrix4fv(um4_mvp)");

    IJK_GLES2_Renderer_TexCoords_reset(renderer);
    IJK_GLES2_Renderer_TexCoords_reloadVertex(renderer);

    IJK_GLES2_Renderer_Vertices_reset(renderer);
    IJK_GLES2_Renderer_Vertices_reloadVertex(renderer);

    return GL_TRUE;
}
为什么 IJK_GLES2_Renderer_Vertices_reset 和 IJK_GLES2_Renderer_Vertices_reloadVertex要重复调用一次

**Comment by bbcallen** [comment]
Vertices could be changed when view size is changed.

**Comment by bbcallen** [comment]
Vertices could be changed when view size is changed.

**Comment by bbcallen** [comment]
Vertices could be changed when view size is changed.

**Comment by bbcallen** [comment]
Vertices could be changed when view size is changed.

**Comment by jiangmingz** [comment]
@bbcallen thx
