### ISSUE TITLE
请问SurfaceView如何实现截取当前播放所在的帧的图片

### ISSUE THREAD

**Issue by liao10108180** [Bilibili/ijkplayer#2192]

**Comment by YBJAY00000** [comment]
一般可以直接显示到surfacetexture上，然后getbitmap就可以了

**Comment by liao10108180** [comment]
能具体点吗？

**Comment by YBJAY00000** [comment]
你把图像显示到TextureView上，然后可以通过mTextureView.getBitmap()就可以拿到这一帧的图片了啊

**Comment by bbcallen** [comment]
You can't do that with SurfaceView.

**Comment by liao10108180** [comment]
ok！thank you very much！！！
