### ISSUE TITLE
rtp protocol not found

### ISSUE THREAD

**Issue by ashank** [Bilibili/ijkplayer#2199]
i play a movie，but play fail，the log  tell me  the  protocol not found,why?

**Comment by bbcallen** [comment]
duplicated with #2198

**Comment by ailinykh** [comment]
try to enable rtp protocol in `config/module-lite.sh` before ffmpeg compile
```
-export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=rtp"
```
it is disabled by default
