### ISSUE TITLE
IJKMediaPlayer - iOS Auto Rotation DeviceOrientation

### ISSUE THREAD

**Issue by KCastiglione** [Bilibili/ijkplayer#220]
Is it possible to dynamically change the orientation of IJKMediaPlayer to support the autorotation of devices and play video of different aspect ratio?

Can you please show how to support Autorotation in IJKMediaDemo for iOS 

Thank you.

**Comment by bbcallen** [comment]
Sorry, I'm not quite familiar with iOS UI programming.
However, I don't think there is any difference between rotating/scaling a player.view and rotating/scaling a normal view.
And you can also do scaling stuff by modify the property 'scalingMode'.
