### ISSUE TITLE
如何设置降低画面色彩鲜明度，设置整体画面偏暗？

### ISSUE THREAD

**Issue by tanqu2013** [Bilibili/ijkplayer#2205]
现在的界面色彩鲜明度比较高，整体色调也是偏明亮，请问有什么方法可以设置整体色调偏暗，色彩鲜明度不那么敏锐吗？

**Comment by notedit** [comment]
自己写渲染的shader

**Comment by bbcallen** [comment]
1. using avfilter
2. using gles shader.

**Comment by tanqu2013** [comment]
OK,Thanks.
