### ISSUE TITLE
请问那个慢放视频的问题

### ISSUE THREAD

**Issue by wtiandong** [Bilibili/ijkplayer#2208]
我们希望播放器有那个慢速播放的功能。现在我看有这个方法：
ijkmp_set_playback_rate
可以设置，在有声的视频下是可以的，似乎是将声音慢放了，视频同步到音频，于是视频也慢放了。
但是现在我们有一些视频没有audio stream。这个就不起效了。
然后我打开了config.h里边#define CONFIG_AVFILTER 1，以及ff_ffplayer_debug.h里边的#define FFP_AVFILTER_PLAYBACK_RATE，都打开了以后，就行了。但是config.h里边写着AVFilter这块似乎还没有变到release的状态？那请问这种情况下我怎么慢放视频呢？
而且我需要是在播放的过程中随时可变播放速率，就类似ios的AVPlayer那样。
谢谢！

**Comment by bbcallen** [comment]
No support for video-only stream.

**Comment by wtiandong** [comment]
好吧。。。thanks....
