### ISSUE TITLE
调用shutdown就crash了，请问是什么原因引起的

### ISSUE THREAD

**Issue by kinderYue** [Bilibili/ijkplayer#2209]
ijkmp_stop()
ijkmp_stop()=0
ijkmp_shutdown_l()
XXXX(1334,0x16e503000) malloc: *** error for object 0x114b14008: pointer being freed was not allocated
这是调用shutdown后的log
具体是崩溃在SDL_WaitThread

**Comment by bbcallen** [comment]
Try checkout master

**Comment by klauswng** [comment]
如果你的ffmpeg开启了mem_align，用ffmpeg的接口分配了内存，然后用系统的free接口来释放，在ios下，就会出现这样的问题。
