### ISSUE TITLE
视频画面延迟

### ISSUE THREAD

**Issue by wbi1987** [Bilibili/ijkplayer#221]
我用ijkplayer和vitamio进行测试，在同一部手机上同时接入一个http视频源，ijkplayer画面总是滞后于vitamio，请问一下ijkplayer的缓冲buffer是在哪设置的？谢谢！

**Comment by bbcallen** [comment]
滞后是指比vitamio加载慢，还是说画面落后于声音？

**Comment by wbi1987** [comment]
比vitamio加载慢，vitamio画面已经出来了，但是ijkplayer还要再缓冲一下画面才出来

**Comment by bbcallen** [comment]
手动改小 ff_ffplay.c 里面的下面几个宏定义，单位是毫秒
```
#define DEFAULT_HIGH_WATER_MARK_IN_BYTES        (256 * 1024)

/*
 * START: buffering after prepared/seeked
 * NEXT:  buffering for the second time after START
 * MAX:   ...
 */
#define DEFAULT_START_HIGH_WATER_MARK_IN_MS     (100)
#define DEFAULT_NEXT_HIGH_WATER_MARK_IN_MS      (1 * 1000)
#define DEFAULT_MAX_HIGH_WATER_MARK_IN_MS       (5 * 1000)
```
因为这个机制现在不是很完善，所以没有开放成设置。

另外 ffmpeg 本身的 probesize 也会影响缓冲时间。

**Comment by wbi1987** [comment]
谢谢！按照您的指示，延时确实能够得到改善，不过这个宏BUFFERING_CHECK_PER_MILLISECONDS 也要适当改小一些。
playable_duration_ms这个变量指示的是当前已缓冲的视频时长吗？也就是播放界面上的缓冲进度条。
#define MIN_FRAMES 50000，我把这个宏定义改小，播放界面上的缓冲进度条就会不可见。

**Comment by bbcallen** [comment]
安卓播放界面上的缓冲条是用百分比算的，以保持和系统播放器差不多的行为。用这个也可以。
MIN_FRAMES 改小，预缓冲的大小也会小，自然就不可见了。
