### ISSUE TITLE
关于设置硬解报错的问题

### ISSUE THREAD

**Issue by tanqu2013** [Bilibili/ijkplayer#2210]
openVideo中只有
mMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
这一条setOption，其他都被我注释了。

运行会报错
11-03 15:53:55.941: I/tv.danmaku.ijk.media.player.IjkMediaPlayer(28320): selected codec: OMX.Exynos.avc.dec rank=800
11-03 15:53:55.941: D/IJKMEDIA(28320): SDL_AMediaCodecJava_createByCodecName
11-03 15:53:55.941: I/ACodec(28320):  [] Now uninitialized
11-03 15:53:55.941: I/OMXClient(28320): Using client-side OMX mux.
11-03 15:53:55.971: D/IJKMEDIA(28320): SDL_AMediaCodecJava_init
11-03 15:53:55.971: D/IJKMEDIA(28320): SDL_AMediaCodec_increaseReference(): ref=1
11-03 15:53:55.971: D/IJKMEDIA(28320): SDL_AMediaCodecJava_configure_surface
11-03 15:53:55.971: E/IJKMEDIA(28320): configure acodec:0x100bea format:0x100bd2: surface:0x100bda
11-03 15:53:55.971: E/MediaCodec(28320): native_window_api_connect returned an error: Invalid argument (-22)
11-03 15:53:55.971: E/MediaCodec(28320): configure failed with err 0xffffffea, resetting...
11-03 15:53:55.981: I/ACodec(28320):  [OMX.Exynos.avc.dec] Now uninitialized
11-03 15:53:55.981: I/ACodec(28320):  [] Now uninitialized
11-03 15:53:55.981: I/OMXClient(28320): Using client-side OMX mux.
11-03 15:53:58.301: W/System.err(28320): android.media.MediaCodec$CodecException: Error 0xffffffea
11-03 15:53:58.301: W/System.err(28320): 	at android.media.MediaCodec.native_configure(Native Method)
11-03 15:53:58.301: W/System.err(28320): 	at android.media.MediaCodec.configure(MediaCodec.java:577)
11-03 15:53:58.301: E/IJKMEDIA(28320): reconfigure_codec_l:configure_surface: failed
11-03 15:53:58.301: D/IJKMEDIA(28320): SDL_AMediaCodec_decreaseReference(): ref=0
11-03 15:53:58.301: I/IJKMEDIA(28320): SDL_AMediaCodecJava_delete
11-03 15:53:58.321: I/ACodec(28320):  [OMX.Exynos.avc.dec] Now uninitialized
11-03 15:53:58.321: I/IJKMEDIA(28320): VideoCodec: avcodec, h264
11-03 15:53:58.321: W/IJKMEDIA(28320): fps: 15.000000 (normal)
11-03 15:53:58.321: W/IJKMEDIA(28320): fps: 15.000000 (normal)
11-03 15:53:58.321: D/IJKMEDIA(28320): FFP_MSG_VIDEO_SIZE_CHANGED: 1920, 1080
11-03 15:53:58.321: D/IJKMEDIA(28320): FFP_MSG_SAR_CHANGED: 0, 1
11-03 15:53:58.321: D/IJKMEDIA(28320): ijkmp_get_msg: FFP_MSG_PREPARED
11-03 15:53:58.321: D/IJKMEDIA(28320): FFP_MSG_PREPARED:
11-03 15:53:58.321: D/IJKMEDIA(28320): avcodec/Audio: first frame decoded
11-03 15:53:58.321: D/IjkVideoView(28320): onVideoSizeChanged: (1920x1080)
11-03 15:53:58.331: D/IJKMEDIA(28320): FFP_MSG_AUDIO_RENDERING_START:
11-03 15:53:58.331: W/AudioTrack(28320): releaseBuffer() track 0x7f76864a00 disabled due to previous underrun, restarting
11-03 15:53:58.331: I/IJKMEDIA(28320): SDL_RunThread: [29012] ff_video_dec
11-03 15:53:58.341: D/IJKMEDIA(28320): FFP_MSG_VIDEO_ROTATION_CHANGED: 0
11-03 15:53:58.341: D/IjkVideoView(28320): VIDEO: 1920x1080x1.777778[SAR:0:0], Surface: 1920x1080, LP: 1440x810, Window: 1440x2560x0.562500
11-03 15:53:58.341: D/IjkVideoView(28320): onVideoSizeChanged: (1920x1080)
11-03 15:53:58.351: D/IjkVideoView(28320): VIDEO: 1920x1080x1.777778[SAR:0:1], Surface: 1920x1080, LP: 1440x810, Window: 1440x2560x0.562500
11-03 15:53:58.351: D/IjkVideoView(28320): onPrepared
11-03 15:53:58.391: D/IjkVideoView(28320): VIDEO: 1920x1080x1.777778[SAR:0:1], Surface: 1920x1080, LP: 1440x810, Window: 1440x2560x0.562500
11-03 15:53:58.391: D/IjkVideoView(28320): VIDEO: 1920x1080x1.777778[SAR:0:1], Surface: 1920x1080, LP: 1440x810, Window: 1440x2560x0.562500
11-03 15:53:58.391: D/IjkVideoView(28320): onInfo: (10002, 0)
11-03 15:53:58.401: I/System.out(28320): (HTTPLog)-Static: isSBSettingEnabled false
11-03 15:53:58.401: I/System.out(28320): KnoxVpnUidStorageknoxVpnSupported API value returned is false

请问是什么原因呢？

**Comment by 18369188711why** [comment]
查看参数设置
https://github.com/Bilibili/ijkplayer/blob/5b73bf7eae66a3942e2689ecbe6e51b679abe161/ijkmedia/ijkplayer/ff_ffplay_options.h

**Comment by tanqu2013** [comment]
参数设置没有问题，我使用的ijk版本是0.5.1，手机是三星S6 android version 5.1.1

**Comment by tanqu2013** [comment]
请问还需要提供什么资料，或者提供哪个方向的资料？

**Comment by bbcallen** [comment]
At least something I can debug with.
