### ISSUE TITLE
IJKMediaPlayer怎么打包成.framwork库，急！！！

### ISSUE THREAD

**Issue by liwuking** [Bilibili/ijkplayer#2213]
我编译IJKMediaPlayer工程后直接拿到的库放入我新建的工程总是提示找不到.h文件，请给个可行的方法，最后.framwork库真机模拟器通用，辛苦了，哥们，谢谢

**Comment by dourgulf** [comment]
可以参考一下我的分支

**Comment by dourgulf** [comment]
https://github.com/dourgulf/ijkplayer
这个分支的demo程序和库项目增加了打包成framework的脚本

**Comment by TerrySolar** [comment]
http://blog.csdn.net/terry_solar/article/details/52743485

这篇文章有详细的图文教程

**Comment by dourgulf** [comment]
其实打包framework是iOS开发者的基本技能，真和ijk无关，作者close这个issue是正确的。
