### ISSUE TITLE
ios why sometimes take long time to decode first video frame

### ISSUE THREAD

**Issue by bupojung** [Bilibili/ijkplayer#2214]
I add log to decoder_decode_frame_videotoolbox (VideoToolBoxContext* context) and find out that
the function was called 229 times and the 230th call decoded the first frame. and it takes 7343ms too get the first video frame。

could anyone tell me why the first 229 packets of video data cann't decoded? and how can i reduce the first video frame time?

**more infomantions:**
I found that the first 229 packets VTDecompressionSessionDecodeFrame returns -8969 witch means bad data

**Comment by bbcallen** [comment]
Debug into avformat_find_stream_info

**Comment by bupojung** [comment]
`int videotoolbox_decode_frame(VideoToolBoxContext* context)
{
    FFPlayer *ffp = context->ffp;
    VideoState *is = ffp->is;
    Decoder *d = &is->viddec;
    int got_frame = 0;
    int xx = 0;
    do {
        ALOGI("videotoolbox_decode_frame:%d\n",xx);
        int ret = -1;
        if (is->abort_request || d->queue->abort_request) {
            
            ALOGI("videotoolbox_decode_frame:%d, is->abort_request:%d,d->queue->abort_request:%d,\n",xx,is->abort_request,d->queue->abort_request);
            return -1;
        }

        if (!d->packet_pending || d->queue->serial != d->pkt_serial) {
            AVPacket pkt;
            do {
                ALOGI("videotoolbox_decode_frame is flush packet:%d\n",xx);
                if (d->queue->nb_packets == 0)
                    SDL_CondSignal(d->empty_queue_cond);
                ffp_video_statistic_l(ffp);
                if (ffp_packet_queue_get_or_buffering(ffp, d->queue, &pkt, &d->pkt_serial, &d->finished) < 0)// 获取视频数据包，如果没有开始缓冲
                {
                    ALOGI("videotoolbox_decode_frame queue aborted:%d\n",xx);
                    return -1;

                }
                if (ffp_is_flush_packet(&pkt)) {
                    avcodec_flush_buffers(d->avctx);
                    context->refresh_request = true;
                    context->serial += 1;
                    d->finished = 0;
                    ALOGI("videotoolbox_decode_frame:%d flushed last keyframe pts %lld \n",xx,d->pkt.pts);
                    d->next_pts = d->start_pts;
                    d->next_pts_tb = d->start_pts_tb;
                }
            } while (ffp_is_flush_packet(&pkt) || d->queue->serial != d->pkt_serial);

            av_packet_split_side_data(&pkt);

            av_packet_unref(&d->pkt);
            d->pkt_temp = d->pkt = pkt;
            d->packet_pending = 1;
        }
        ALOGI("videotoolbox_decode_frame got packet:%d \n",xx);
        ret = decode_video(context, d->avctx, &d->pkt_temp, &got_frame);
        if (ret < 0) {
            d->packet_pending = 0;
            ALOGI("videotoolbox_decode_frame decode_video failed:%d \n",xx);

        } else {
            d->pkt_temp.dts =
            d->pkt_temp.pts = AV_NOPTS_VALUE;
            if (d->pkt_temp.data) {
                if (d->avctx->codec_type != AVMEDIA_TYPE_AUDIO)
                    ret = d->pkt_temp.size;
                d->pkt_temp.data += ret;
                d->pkt_temp.size -= ret;
                if (d->pkt_temp.size <= 0)
                    d->packet_pending = 0;
            } else {
                if (!got_frame) {
                    d->packet_pending = 0;
                    d->finished = d->pkt_serial;
                    ALOGI("videotoolbox_decode_frame no frame decoded:%d d->finished:%d\n",xx,d->finished);
                }else{
                    ALOGI("videotoolbox_decode_frame got frame but no data decoded:%d\n",xx);

                }
            }
        }
        xx++;

    } while (!got_frame && !d->finished);
    ALOGI("videotoolbox_decode_frame got frame vtbox:%d got frame:%d :time:%f \n",xx,got_frame,CFAbsoluteTimeGetCurrent() * 1000);
    return got_frame;
}`

this is where i add log.  the attachment is the output log.
[video_decode_log_2.txt](https://github.com/Bilibili/ijkplayer/files/571180/video_decode_log_2.txt)

**Comment by bupojung** [comment]
I found that the first 229 packets VTDecompressionSessionDecodeFrame returns -8969

**Comment by bupojung** [comment]
I have found the problem， the first dozens of data packets are not I frame， the decoder cannot decode and returns a -8969 error which means bad data.
I reduce the gop interval time to solve this problem.

**Comment by Goallying** [comment]
@bupojung  i have this problem too . can you remember how to solve this problem? i cant understand what you mean "I reduce the gop interval time to solve this problem." can you paste some code ? plz and thanks .

**Comment by bupojung** [comment]
@Goallying I found that，when set nobuffer flag，the frames been analysed will be droped and not buffer， so the key frame may be droped. So, you can just not set the nobuffer flag.
`[options setFormatOptionValue:@"nobuffer" forKey:@"fflags"]// just remove this code`
