### ISSUE TITLE
swift 要如何导入?

### ISSUE THREAD

**Issue by adad184** [Bilibili/ijkplayer#222]

**Comment by bbcallen** [comment]
Swift support is not in to-do list.

**Comment by KittenYang** [comment]
@adad184  可以使用桥接，可以参考这篇博客：[http://kittenyang.com/swiftandoc/]()

**Comment by adad184** [comment]
@KittenYang 嗯.. 我自己已经搞定了    不光是桥接的问题   直接桥接还挺麻烦的

**Comment by bbcallen** [comment]
麻烦点主要是哪些？是接口的限制么？

**Comment by adad184** [comment]
我是把.xcodeproj拖入项目的方式导入framework的   

然后编译的时候还要导入
AVFoundation
AudioToolbox
CoreMedia
libz

还要保留根目录下面的 ijkmedia目录(直接copy走ios/IJKMediaPlayer 是不行的)

然后还要把libIJKMediaPlayer.a 添加到 Target Dependencies 和 Link Binary With Libraries 

完成这些以后  再桥接 #import <IJKMediaPlayer/IJKMediaPlayer.h>

就ok了..

之后的使用就不需要import了(奇怪的是 如果import 会报错 不知道为什么)  可以直接用
