### ISSUE TITLE
Stream audio data from a local file to ijk player through an internal socket

### ISSUE THREAD

**Issue by bava502** [Bilibili/ijkplayer#224]
Hi,
I want to download audio data from a remote URL, save to a local file, open the file and stream audio data to ijkplayer via an internal socket connection created with ijk player. Instead of passing remote audio URL directly to ijkplayer,  i would like to pass "local host" URL. 
I have done this successfully with android media player but not succeeded with ijk player.

I am writing http header info like below:
                        httpString.append("HTTP/1.0 200 OK\r\n");
                        httpString.append("Content-Type: audio/mpeg\r\n");
			httpString.append("Content-Length: ");
			httpString.append(contentLength);
			httpString.append("\r\n");
			httpString.append("Accept-Ranges: bytes\r\n");
			httpString.append("Connection: keep-alive\r\n");
			
			httpString.append("\r\n");

This is working fine with android media player. 
If exact content length of audio is passed then play back is ending abruptly if data streaming via socket is slow.
If content length is passed as "-1" then playback is working fine with ijkplayer but i would like to pass exact content length so that player will provide me with duration of audio depending on which i can display total time, elapsed time and remaining time.

Could you help me if I am missing anything here?

**Comment by bbcallen** [comment]
Any log?

**Comment by bava502** [comment]
HTTP Request header from ijk player is as below:
05-12 15:08:59.700: D/MediaStream(19072):   2205 GET /mediaStreamService HTTP/1.1
05-12 15:08:59.710: D/MediaStream(19072):   2205 User-Agent: Lavf/56.4.101
05-12 15:08:59.710: D/MediaStream(19072):   2205 Accept: */*
05-12 15:08:59.710: D/MediaStream(19072):   2205 Range: bytes=0-
05-12 15:08:59.710: D/MediaStream(19072):   2205 Connection: close
05-12 15:08:59.720: D/MediaStream(19072):   2205 Host: 127.0.0.1:40443
05-12 15:08:59.720: D/MediaStream(19072):   2205 Icy-MetaData: 1

Response headers written to ijk player are:
05-12 15:09:02.740: D/MediaStream(19072):   2205 HTTP/1.0 206 Partial Content
05-12 15:09:02.740: D/MediaStream(19072): Content-Range: bytes 0-3328625/3328626
05-12 15:09:02.740: D/MediaStream(19072): Content-Type: audio/mpeg
05-12 15:09:02.740: D/MediaStream(19072): Content-Length: 3328625
05-12 15:09:02.740: D/MediaStream(19072): Accept-Ranges: bytes
05-12 15:09:02.740: D/MediaStream(19072): Connection: keep-alive

Once audio data is written to ijk player via socket connection playback starts but ends abruptly with below logs after some time:
05-12 15:09:09.290: E/IJKMEDIA(19072): incomplete frame
05-12 15:09:10.000: E/IJKMEDIA(19072): ffp_toggle_buffering: completed: (error=0)
05-12 15:09:10.000: W/IJKMEDIA(19072): ijkmp_get_msg: FFP_MSG_COMPLETED
05-12 15:09:10.000: W/IJKMEDIA(19072): FFP_MSG_COMPLETED:
05-12 15:09:10.010: E/IJKMEDIA(19072): unknown FFP_MSG_xxx(700)
05-12 15:09:10.010: E/IJKMEDIA(19072): ffp_toggle_buffering: eof



If content length is negative like below then playback works fine without any error:
05-12 15:18:42.460: D/MediaStream(19072):   2205 HTTP/1.0 206 Partial Content
05-12 15:18:42.460: D/MediaStream(19072): Content-Range: bytes 0--2/-1
05-12 15:18:42.460: D/MediaStream(19072): Content-Type: audio/mpeg
05-12 15:18:42.460: D/MediaStream(19072): Content-Length: -2
05-12 15:18:42.460: D/MediaStream(19072): Accept-Ranges: bytes
05-12 15:18:42.460: D/MediaStream(19072): Connection: keep-alive

**Comment by bava502** [comment]
Also got below logs while trying again:
05-12 15:57:47.880: E/IJKMEDIA(29211): stream 0, offset 0x1155e: partial file
05-12 15:57:48.900: E/IJKMEDIA(29211): stream 0, offset 0x11664: partial file
05-12 15:57:49.910: E/IJKMEDIA(29211): stream 0, offset 0x1176d: partial file
05-12 15:57:50.920: E/IJKMEDIA(29211): stream 0, offset 0x11873: partial file
05-12 15:57:51.690: E/IJKMEDIA(29211): decode_band_types: Input buffer exhausted before END element found
05-12 15:57:51.930: E/IJKMEDIA(29211): ffp_toggle_buffering: completed: (error=0)
05-12 15:57:51.930: E/IJKMEDIA(29211): stream 0, offset 0x1197e: partial file
05-12 15:57:51.930: W/IJKMEDIA(29211): ijkmp_get_msg: FFP_MSG_COMPLETED
05-12 15:57:51.930: W/IJKMEDIA(29211): FFP_MSG_COMPLETED:
05-12 15:57:51.930: E/IJKMEDIA(29211): unknown FFP_MSG_xxx(700)

**Comment by bbcallen** [comment]
1. "incomplete frame" seems from FFmpeg internal. Have you tried that url with ffplay on PC?

2. If you don't want to provide content-length, you should remove "Accept-Ranges" line.

3. "partial file" is bug from FFmpeg internal, too, which I'm working on recently.

**Comment by bava502** [comment]
If  URL is passed to ijk player,  playback works without any issue. Problem is with creating socket connection(local host) with player and write audio data on it. 
If content length is passed as negative value then playback works fine but i don't get duration of the audio.
To get duration i need to pass content-length. If i pass content-length then i see playback issues as mentioned above.

**Comment by bbcallen** [comment]
```
Response headers written to ijk player are:
05-12 15:09:02.740: D/MediaStream(19072): 2205 HTTP/1.0 206 Partial Content
05-12 15:09:02.740: D/MediaStream(19072): Content-Range: bytes 0-3328625/3328626
# Seems should be off-by-one error?
# 05-12 15:09:02.740: D/MediaStream(19072): Content-Range: bytes 0-3328624/3328625
05-12 15:09:02.740: D/MediaStream(19072): Content-Type: audio/mpeg
05-12 15:09:02.740: D/MediaStream(19072): Content-Length: 3328625
05-12 15:09:02.740: D/MediaStream(19072): Accept-Ranges: bytes
05-12 15:09:02.740: D/MediaStream(19072): Connection: keep-alive
````

**Comment by bava502** [comment]
Thanks for helping me. I corrected content-Range now but still see the issue.

Looks like issue is due to "Connection:close"  http header. Following is the code snippet from http.c.
I think my issue will be resolved if i enable persistent connection to enable multiple requests.
 if (!has_header(s->headers, "\r\nConnection: ")) {
        if (s->multiple_requests) {
               len += av_strlcpy(headers + len, "Connection: keep-alive\r\n",
                              sizeof(headers) - len);
          } else {
              len += av_strlcpy(headers + len, "Connection: close\r\n",
                               sizeof(headers) - len);
           }
      }

From FFMPEG documentation i can see below comment: 
multiple_requests:: Use persistent connections if set to 1, default is 0.

Any idea on how to enable http persistent connections which means when i read http headers from ijk player i should get "Connection: keep-alive" instead of "Connection: close" as shown in my previous logs shared.

**Comment by bbcallen** [comment]
mp.setAvFormatOption("multiple_requests", "1");

**Comment by bava502** [comment]
Thanks.. I am able to set "multiple_requests" as you mentioned above but still there are issues with playback. I am looking into it. 

Meanwhile there is one more issue i am seeing very frequently(Not related to above implementation). Callback of MEDIA_BUFFERING_UPDATE  stops in between abruptly when tried to play an audio URL. For example, I receive buffering updates of the audio up to 50% and stops suddenly but playback continues till the end of the file. It shows wrong indication on the progress bar.

**Comment by bbcallen** [comment]
There is no guarantee that MEDIA_BUFFERING_UPDATE could always tell correct size.
Have a look at ffp_check_buffering_l() in ff_ffplay.c.
