### ISSUE TITLE
Ios update to 0.7.3, play the video for a while, app crashed

### ISSUE THREAD

**Issue by yuanxun2007** [Bilibili/ijkplayer#2246]
When I use open  [options setPlayerOptionIntValue:1 forKey:@"videotoolbox"]; //开启硬件解码, the other thread will continuing consume the memory, at end, app crashed

**Comment by xinzhengzhang** [comment]
This is a leak introduced in 0.7.1.
It has been fixed and released into tag k0.7.4.
I will merge into master after a fully test.

Please let me know if there are still problems.
Thanks for the feedback~

**Comment by yuanxun2007** [comment]
Thank you, I have test it and passed, no more crashed by memory now.
