### ISSUE TITLE
更新到最新代码0.7.3后，获取当前播放进度为0

### ISSUE THREAD

**Issue by tanhx2008** [Bilibili/ijkplayer#2247]
ffp_get_current_position_l，返回值为0

**Comment by tanhx2008** [comment]
mVideoPath = "rtmp://live.hkstv.hk.lxdns.com/live/hks";

**Comment by tanhx2008** [comment]
用 demo 播放本地 mp4 视频也是一样，进度条一直为0

**Comment by tanhx2008** [comment]
} else if (ffp->decoder_reorder_pts) {
                        frame->pts = frame->pkt_pts;
                    } else {
                        frame->pts = frame->pkt_dts;
                    }
这里修改的原因是？加上 pts 这个代码后，进度正常

**Comment by xinzhengzhang** [comment]
@tanhx2008 
This patch was merged from [6f74e3](https://github.com/Bilibili/FFmpeg/commit/6f74e3cde6147b9a9bda5071e505e9ffbb99096a)

It looks fine with me by testing it in both iOS and Android demo with `rtmp://live.hkstv.hk.lxdns.com/live/hks`.

Please provide the whole project for reproducing this issue.

**Comment by tanhx2008** [comment]
Oh, perhaps I did not update ffmpeg?
