### ISSUE TITLE
请问执行 ./init-ios.sh 这么慢并且总会出错，有什么解决办法吗？

### ISSUE THREAD

**Issue by xiangzi0911** [Bilibili/ijkplayer#2248]
lvxiangdeMac-mini:ijkplayer-master lvxiang$ ./init-ios.sh
git version 2.7.4 (Apple Git-66)
== pull gas-preprocessor base ==
Fetching origin
/Users/lvxiang/Demo/ijkplayer-master
== pull ffmpeg base ==
Cloning into 'extra/ffmpeg'...
remote: Counting objects: 494447, done.
Receiving objects:   0% (1445/494447), 404.00 KiB | 4.00 KiB/s

**Comment by bbcallen** [comment]
Blame GFW
