### ISSUE TITLE
iOS10.0以下真机模拟器Crash

### ISSUE THREAD

**Issue by xingze0308** [Bilibili/ijkplayer#2252]
您好
我在使用ijikPlayer的时候 在iOS系统版本为10.0以下会奔溃(10.0可以正常播放)  以下是奔溃信息:
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/xingze/Library/Developer/CoreSimulator/Devices/79DF536A-00D6-4641-A3C5-A2FAF08ABD92/data/Containers/Bundle/Application/146869FB-BBFB-45CE-84B0-8C9136DC6837/SDE.app/SDE
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libSystem.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/xingze/Library/Developer/CoreSimulator/Devices/79DF536A-00D6-4641-A3C5-A2FAF08ABD92/data/Containers/Bundle/Application/146869FB-BBFB-45CE-84B0-8C9136DC6837/SDE.app/SDE
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libSystem.dylib

可不可以给点提示  这是模拟器奔溃的信息 真机也会奔溃 只不过没有这些奔溃信息 只是卡到dyld_sim`dyld_fatal_error:这里

**Comment by bbcallen** [comment]
See #1995

**Comment by xingze0308** [comment]
thank you

**Comment by xingze0308** [comment]
@bbcallen  thank you very much
