### ISSUE TITLE
您好，bbcallen，能不能提供一个编译好的库（Android版）

### ISSUE THREAD

**Issue by jaycee11** [Bilibili/ijkplayer#226]
我们这边一直没编译好，方便的话发邮件给我，或者放到github上边一个编译好的库，邮箱：6453862@qq.com，谢谢！

**Comment by bbcallen** [comment]
库太大了，不适合放到代码库。有编译问题可以贴到这里解决。如果只是希望简单集成，建议使用vitamio，播放能力差不多。

**Comment by jaycee11** [comment]
vitamio企业用需要购买授权呢，一年80W
