### ISSUE TITLE
_clock_gettime

### ISSUE THREAD

**Issue by xingze0308** [Bilibili/ijkplayer#2260]
xcode7.3  run  log:
Undefined symbols for architecture armv7:
  "_clock_gettime", referenced from:
      _av_gettime_relative in IJKMediaFramework(time.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

please help me...
thank you

**Comment by xinzhengzhang** [comment]
what's your ffmpeg version in logcat?

**Comment by xingze0308** [comment]
hello  I use ijkPlayer k0.4.5 version
There will be a iOS9 & XCode8 carsh
but iOS10 & XCode8 is OK
We must Use k0.4.5 version
 I put the video file .concat format
please tell me the latest version support？

**Comment by bbcallen** [comment]
Yes.

**Comment by xinzhengzhang** [comment]
use ijk master or cherry-pick this [patch](https://github.com/Bilibili/FFmpeg/commit/487a3861c229cce08ea02bd0d896f6f3bb6b765d) to your ffmpeg
