### ISSUE TITLE
compile openssl error

### ISSUE THREAD

**Issue by lijie815917** [Bilibili/ijkplayer#2261]
Refusing to clobber existing install directory: /Users/lijie/experiment/ijkplayer-android/android/contrib/build/openssl-armv5/toolchain.

make-standalone-toolchain.sh used to install a new toolchain into an existing
directory. This is not desirable, as it will not clean up any stale files. If
you wish to remove the install directory before creation, pass --force.

工具：Mac，androidstudio 2.2
我是按照教程去sdkmanager download的ndk，版本为13.1.3,但r是编译时候报上面的错误,看之前的有的回答是切换master或者用ndkr10e版本，但是我试过切换master不行，ndkr10e版本找不到下载链接了，难道不能兼容？我应该要怎么去解决，谢谢

**Comment by bbcallen** [comment]
1. rm the directory /Users/lijie/experiment/ijkplayer-android/android/contrib/build
2. checkout master
3. retry.

**Comment by lijie815917** [comment]
ok.i solve it by ndkr10e version,thanks.

**Comment by jdpxiaoming** [comment]
may be your build.sh make a folder before the make-standalone-toolchain.sh, for my case ,
`
mkdir -p $FF_PREFIX
# mkdir -p $FF_SYSROOT //commennt this line .

if [ ! -f "$FF_TOOLCHAIN_TOUCH" ]; then
$ANDROID_NDK/build/tools/make-standalone-toolchain.sh \
        $FF_MAKE_TOOLCHAIN_FLAGS \
        --platform=$FF_ANDROID_PLATFORM \
        --toolchain=$FF_TOOLCHAIN_NAME
    touch $FF_TOOLCHAIN_TOUCH;
fi
`
