### ISSUE TITLE
iOS 怎么在控制器内切换播放源啊

### ISSUE THREAD

**Issue by iSuAbner** [Bilibili/ijkplayer#2269]
就像系统的AVPlayer那样更改item 为current item就切换视频播放源的 求解

**Comment by Engandend** [comment]
我目前的做法是 关闭当前的player 并且移除，然后重新加一个
不知道有没有更好的方法

**Comment by iSuAbner** [comment]
关闭当前player是指退出这个控制器然后再新创建一个吗? 我想做的是在一个控制器里切换不同清晰度 也就是切换不同的网址，如果退出player应该不好。

**Comment by Engandend** [comment]
我目前的做法是 关闭当前的player 并且移除，然后重新加一个
不知道有没有更好的方法

**Comment by bbcallen** [comment]
You can't.

**Comment by yuanxun2007** [comment]
@bbcallen Any plan?

**Comment by iSuAbner** [comment]
remove view and build a new view add to controller , i have been solved this question . the code is 
 [_player shutdown];
    [_player.view removeFromSuperview];
    if (_player != nil) {
        //_player.tcpOpenDelegate = nil;
        _player = nil;
    }
    [self removeMovieNotificationObservers];
    
    [IJKMediaModule sharedModule].appIdleTimerDisabled = YES;
    [IJKFFMoviePlayerController checkIfFFmpegVersionMatch:YES];
    IJKFFOptions * options = [IJKFFOptions optionsByDefault];
    [options setFormatOptionValue:@"ijktcphook" forKey:@"http-tcp-hook"];
    
    NSURL * theMovieURL;
    
    if ([url hasPrefix:@"http"] || [url hasPrefix:@"https"]) {
         theMovieURL =[NSURL URLWithString:url];
    }else{
         theMovieURL = [NSURL fileURLWithPath:url];
    }
    self.player = [[IJKFFMoviePlayerController alloc] initWithContentURL:theMovieURL withOptions:options];
#pragma mark 注册通知
    [self installMovieNotificationObservers];
    self.player.scalingMode = IJKMPMovieScalingModeAspectFit;
#pragma mark 跳转时间
    self.player.shouldAutoplay = YES;
    [self.view addSubview:_player.view];
    self.view.autoresizesSubviews = YES;
    [self.view addSubview:self.player.view];
    [self.view addSubview:self.mediaControl];
    self.mediaControl.delegatePlayer = self.player;
    //改成[paly还不动了];
    [self.player prepareToPlay];
    [self.mediaControl refreshMediaControl];
