### ISSUE TITLE
您好，播放m3u8文件时快进视频

### ISSUE THREAD

**Issue by jaycee11** [Bilibili/ijkplayer#227]
播放m3u8文件时快进视频时，有时候回出现不准确的情况，比如说有时候快进到10:30秒，可能回退到5分多，可以用http://7xixq1.com1.z0.glb.clouddn.com/test1000.m3u8这个文件做下测试

**Comment by bbcallen** [comment]
目测拖动条控件的问题，拖到那个地方手先别放，多停一会儿。
