### ISSUE TITLE
Start playing stream frames callback

### ISSUE THREAD

**Issue by dmdque** [Bilibili/ijkplayer#2272]
I'd like to show a loading animation until the first frames of an rtmp video actually start playing, instead of having a black screen.

I can't find a built-in callback for this type of thing. My approach right now is to create a thread which listens to `IJKFFMoviePlayerController`'s `fpsAtOutput` until it's nonzero.

Is there a better or built-in way to do this?

**Comment by bbcallen** [comment]
IJKMPMoviePlayerFirstVideoFrameRenderedNotification

**Comment by dmdque** [comment]
Thanks
