### ISSUE TITLE
iOS怎么在播放开始的时候设置指定的时间点，让播放器从这个时间点开始播放

### ISSUE THREAD

**Issue by iSuAbner** [Bilibili/ijkplayer#2275]
如题，也就是seek 我设置setCurrentPlaybackTime 是不好使的

**Comment by bbcallen** [comment]
call seek when prepared.

**Comment by iSuAbner** [comment]
我想切换URL的时候同时切换到上次播放视频的位置，我的代码是这样的 我想知道这样做哪里不对
  //移除上一个view 
    [_player shutdown];
    [_player.view removeFromSuperview];
    if (_player != nil) {
        _player = nil;
    }
    //新建一个新的view 
    [IJKMediaModule sharedModule].appIdleTimerDisabled = YES;
    [IJKFFMoviePlayerController checkIfFFmpegVersionMatch:YES];
    IJKFFOptions * options = [IJKFFOptions optionsByDefault];
    [options setFormatOptionValue:@"ijktcphook" forKey:@"http-tcp-hook"];
    NSURL *theMovieURL = [NSURL fileURLWithPath:path];
    self.player = [[IJKFFMoviePlayerController alloc] initWithContentURL:theMovieURL withOptions:options];
    self.player.scalingMode = IJKMPMovieScalingModeAspectFit;
    self.player.shouldAutoplay = YES;
    [self.view addSubview:_player.view];
    [self.player prepareToPlay];
//设置seek的时间  这个时间算是prepare之后的设置时间吗？
    [self.player setCurrentPlaybackTime:10.0];

**Comment by bbcallen** [comment]
IJKMPMediaPlaybackIsPreparedToPlayDidChangeNotification

**Comment by iSuAbner** [comment]
thanks to your reply , I also noticed that notification，I can set current time under this change,once again thank you for your reply .

**Comment by gongyua** [comment]
你好 这个问题解决了吗，JKFFMoviePlayerController里没setCurrentPlaybackTime这个方法

**Comment by aipaiSpaceMan** [comment]
我也是用currentPlaybackTime，seek回来后会有问题，会往回跳秒

**Comment by raymond1012** [comment]
seek 后是从最近的关键帧开始播放

2017-04-14 15:04 GMT+08:00 aipaiSpaceMan <notifications@github.com>:

**Comment by 2882889** [comment]
@raymond1012 如何能让播放器seek到当前帧而不是关键帧呢？多等一会儿也可以，谢谢啦

**Comment by renzifeng** [comment]
[options setPlayerOptionIntValue:1 forKey:@"enable-accurate-seek"];

**Comment by weikeyan** [comment]
> 我也是用currentPlaybackTime，seek回来后会有问题，会往回跳秒

解决了吗
