### ISSUE TITLE
不是很懂，自己的APP嵌入了这个项目，是不是要开放源码

### ISSUE THREAD

**Issue by szpnygo** [Bilibili/ijkplayer#228]
是不是要遵循GPL开放自己的APP源码，开源中国不是说美拍也用的这个项目。

**Comment by bbcallen** [comment]
ijkplayer 本身是LGPL，不是GPL，依赖的项目也没有 GPL 。
通俗的讲，LGPL只需要模块开源，不需要调用者开源。

1. 如果你没有修改 ffmpeg 的编译配置，而且没有修改 ijkplayer 代码，那么你只需要告诉别人 ijkplayer 的源码哪里下载就可以了。

2. 如果你修改过 ijkplayer，那么绝大多数情况，你需要把修改过的 ijkplayer 开源。比如：
https://github.com/HupuInc/ijkplayer
https://github.com/JavanEu/ijkplayer
都是修改过的 ijkplayer

(修改的文件头部注明是 Apache 协议的不用开源。)

3. 如果你修改了 FFmpeg 的配置，引入了其他 GPL 的模块，只有这种情况才需要整个 App 开源。不过这种情况是 GPL 模块导致的，而不是 ijkplayer 导致的。

4. LGPL/GPL 在天朝目前属于灰色地带，做到上面的就算是符合 FSF 的精神了。如果担心法律问题，请咨询你的律师/法务以及 LGPL/GPL 专家。

5. 特别说明，App 是否商用，不受 ijkplayer 的限制，也不受 LGPL 的限制。但因为引用的模块众多，协议种类繁杂，所以这个声明只是我个人观点，不具有法律效力。

**Comment by szpnygo** [comment]
非常感谢您的回答
