### ISSUE TITLE
反复播放1080p视频mp4(aac+h264 ),卡顿;

### ISSUE THREAD

**Issue by fengbenpaao** [Bilibili/ijkplayer#2288]
11-17 16:16:38.186 26367-3116/tv.danmaku.ijk.media.example D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
11-17 16:16:38.306 26367-3112/tv.danmaku.ijk.media.example D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
11-17 16:16:38.356 26367-3113/tv.danmaku.ijk.media.example D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
11-17 16:16:38.446 26367-3111/tv.danmaku.ijk.media.example D/IJKMEDIA: ffp_toggle_buffering_l: start
11-17 16:16:38.446 26367-3102/tv.danmaku.ijk.media.example D/IJKMEDIA: FFP_MSG_BUFFERING_START:
11-17 16:16:38.446 26367-3104/tv.danmaku.ijk.media.example D/IJKMEDIA: ffp_toggle_buffering_l: end
11-17 16:16:38.446 26367-3102/tv.danmaku.ijk.media.example D/IJKMEDIA: FFP_MSG_BUFFERING_END:
11-17 16:16:38.466 26367-26367/tv.danmaku.ijk.media.example D/IjkVideoView: MEDIA_INFO_BUFFERING_START:
11-17 16:16:38.466 26367-26367/tv.danmaku.ijk.media.example D/IjkVideoView: MEDIA_INFO_BUFFERING_END:
11-17 16:16:38.486 26367-3114/tv.danmaku.ijk.media.example D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
11-17 16:16:38.486 26367-3111/tv.danmaku.ijk.media.example D/IJKMEDIA: ffp_toggle_buffering_l: start
11-17 16:16:38.486 26367-3102/tv.danmaku.ijk.media.example D/IJKMEDIA: FFP_MSG_BUFFERING_START:
11-17 16:16:38.486 26367-3104/tv.danmaku.ijk.media.example D/IJKMEDIA: ffp_toggle_buffering_l: end
11-17 16:16:38.486 26367-3102/tv.danmaku.ijk.media.example D/IJKMEDIA: FFP_MSG_BUFFERING_END:
11-17 16:16:38.496 26367-3111/tv.danmaku.ijk.media.example D/IJKMEDIA: ffp_toggle_buffering_l: start
11-17 16:16:38.496 26367-3102/tv.danmaku.ijk.media.example D/IJKMEDIA: FFP_MSG_BUFFERING_START:
11-17 16:16:38.496 26367-3104/tv.danmaku.ijk.media.example D/IJKMEDIA: ffp_toggle_buffering_l: end

**Comment by bbcallen** [comment]
Duplicated with #2100
