### ISSUE TITLE
一个同步问题

### ISSUE THREAD

**Issue by shcalm** [Bilibili/ijkplayer#229]
/android/ijkmediaplayer/src/tv/danmaku/ijk/media/player/AndroidMediaPlayer.java
  public AndroidMediaPlayer() {
        synchronized (mInitLock) {
            mInternalMediaPlayer = new MediaPlayer();
        }
        mInternalMediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
        mInternalListenerAdapter = new AndroidMediaPlayerListenerHolder(this);
        attachInternalListeners();
    }
请问一下 mInternalMediaPlayer = new MediaPlayer();为什么要做同步呢?..

**Comment by bbcallen** [comment]
曾经用来作为异步释放的保护，现在没用了。
