### ISSUE TITLE
hls在m3u8文件里写两个套ts流，如何进行视频切换

### ISSUE THREAD

**Issue by zyjohnyoung** [Bilibili/ijkplayer#2295]
如题，我现在想播放写着两套码率的ts流的m3u8文件，并实现码率切换，请问ijkplayer有这种功能吗，如果有该怎么实现呢

**Comment by bbcallen** [comment]
The best way is that you create new player for new bitrate.
Bitrate switching (selectTrack()/deselectTrack()) doesn't work well, for now.

**Comment by zyjohnyoung** [comment]
谢谢！！
