### ISSUE TITLE
求助：黑屏,MediaCodec问题

### ISSUE THREAD

**Issue by FatPaper** [Bilibili/ijkplayer#2308]
根据demo代码在某些手机上播放某些视频（开启MediaCodec情况下），将播放页面切换至后台掉用播放pause，然后切换至前台调用start，MediaCodec会状态异常，跟踪了下代码，在IjkVideoView的onSurfaceCreated里将bindSurfaceHolder(mMediaPlayer,mSurfaceHolder);注释掉，MediaCodec就不会状态异常，请教一下可能是什么原因引起的
MediaCodec log:
11-21 12:14:40.352 28329-29129/com.ppfuns.smi W/System.err: java.lang.IllegalStateException
11-21 12:14:40.352 28329-29129/com.ppfuns.smi W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
11-21 12:14:40.352 28329-29129/com.ppfuns.smi W/System.err:     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1046)

**Comment by bbcallen** [comment]
What kind of devices?

**Comment by FatPaper** [comment]
魅族3、oppo R9、乐视，暂时发现这几个，在华为p9就不会出现，之前我根据demo代码写的videoView实现，出现这种情况，以为是我的写法问题，然后我就用demo测试了一下，一样的情况

**Comment by bbcallen** [comment]
Did it keep black screen, or show videos after a while?

**Comment by FatPaper** [comment]
一直黑屏，有声音，然后过段时间声音也没了，感觉是把缓存播放完后就没了

**Comment by FatPaper** [comment]
http://119.44.6.100:8011/vod/15_2145.mp4，这是播放链接，surfaceview没有destroy的时候，start和pause操作完全没有问题，但是surfaceview从可见切换至不可见，再从不可见切换至可见，就会有问题

**Comment by bbcallen** [comment]
Did you test in original demo, or in your own app with IjkVideoView's source code?

**Comment by FatPaper** [comment]
就是在原始demo里测试的，只不过我在VideoActivity里重写onpause和onresume
`@Override
    protected void onResume() {
        super.onResume();
        if(mVideoView != null){
            mVideoView.start();
        }
    }

    @Override
    protected void onPause() {
        super.onPause();
        if(mVideoView != null){
            mVideoView.pause();
        }
    }`
然后我在menu里随便添加了一项，跳转到一个TestActivity，然后返回然后点击返回键返回VideoActivity

**Comment by bbcallen** [comment]
If onSurfaceCreated() is called when navitgate back to VideoActivity. There must be an onSurfaceDestroyed() before that.
Try setDisplay(NULL) in onSurfaceDestroyed().

**Comment by FatPaper** [comment]
原始代码里已经将display设置为null了
`@Override
        public void onSurfaceDestroyed(@NonNull IRenderView.ISurfaceHolder holder) {
            if (holder.getRenderView() != mRenderView) {
                Log.e(TAG, "onSurfaceDestroyed: unmatched render callback\n");
                return;
            }

            // after we return from this we can't use the surface any more
            mSurfaceHolder = null;
            // REMOVED: if (mMediaController != null) mMediaController.hide();
            // REMOVED: release(true);
            releaseWithoutStop();
        }`
`public void releaseWithoutStop() {
        if (mMediaPlayer != null)
            mMediaPlayer.setDisplay(null);
    }`
不是播放所有视频都会这样的

**Comment by FatPaper** [comment]
@Override
        public void onSurfaceDestroyed(@NonNull IRenderView.ISurfaceHolder holder) {
            if (holder.getRenderView() != mRenderView) {
                Log.e(TAG, "onSurfaceDestroyed: unmatched render callback\n");
                return;
            }

            // after we return from this we can't use the surface any more
            mSurfaceHolder = null;
            // REMOVED: if (mMediaController != null) mMediaController.hide();
            // REMOVED: release(true);
            releaseWithoutStop();
        }

**Comment by FatPaper** [comment]
@bbcallen 
http://pan.baidu.com/s/1eRQ22NS,这是我测试用的原始代码，播放链接我写死在代码里，在魅族3和oppo R9上按我那样的步骤操作，黑屏是必现的

**Comment by codeczx** [comment]
I hava also met this question.

**Comment by halfhq** [comment]
同样有这个情况，在多台设备上重现。
仅仅开启mediacodec时会发生。
使用demo也会存在

**Comment by andyjmzheng** [comment]
@FatPaper @bbcallen @halfhq 
开启mediacodec 后。黑屏的问题解决了吗？我也遇到了。

**Comment by SuperXmx** [comment]
@bbcallen @FatPaper @halfhq 
请问找到解决方案了吗？ 使用的是0.7.5也是一样，开启硬解后偶尔会出现
 E/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] ERROR(0x80001005)
02-17 11:27:49.906 23985-27574/tv.danmaku.ijk.media.example E/ACodec: signalError(omxError 0x80001005, internalError -2147483648)
02-17 11:27:49.906 23985-27574/tv.danmaku.ijk.media.example W/ACodec: onEvent--OMX Bad Parameter!!
02-17 11:27:49.906 23985-27572/tv.danmaku.ijk.media.example E/MediaCodec: Codec reported err 0xfffffbb1, actionCode 0, while in state 6
02-17 11:27:49.906 23985-27579/tv.danmaku.ijk.media.example W/System.err: java.lang.IllegalStateException
02-17 11:27:49.906 23985-27579/tv.danmaku.ijk.media.example W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
02-17 11:27:49.906 23985-27579/tv.danmaku.ijk.media.example W/System.err:     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1046)
02-17 11:27:49.906 23985-27579/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
02-17 11:27:49.908 23985-27556/tv.danmaku.ijk.media.example D/libc-netbsd: getaddrinfo: liveksyunaipai.hlslive.ks-cdn.com get result from proxy >>
02-17 11:27:49.908 23985-27580/tv.danmaku.ijk.media.example W/System.err: java.lang.IllegalStateException
02-17 11:27:49.908 23985-27580/tv.danmaku.ijk.media.example W/System.err:     at android.media.MediaCodec.native_queueInputBuffer(Native Method)
02-17 11:27:49.908 23985-27580/tv.danmaku.ijk.media.example W/System.err:     at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:844)
02-17 11:27:49.908 23985-27580/tv.danmaku.ijk.media.example E/IJKMEDIA: feed_input_buffer: SDL_AMediaCodec_getInputBuffer failed
02-17 11:27:49.908 23985-27580/tv.danmaku.ijk.media.example I/IJKMEDIA: MediaCodec: enqueue_thread_func: exit: -1
02-17 11:27:49.908 23985-27580/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [27580]
02-17 11:27:50.908 23985-27579/tv.danmaku.ijk.media.example W/System.err: java.lang.IllegalStateException
02-17 11:27:50.908 23985-27579/tv.danmaku.ijk.media.example W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
02-17 11:27:50.908 23985-27579/tv.danmaku.ijk.media.example W/System.err:     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1046)
02-17 11:27:50.908 23985-27579/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
02-17 11:27:51.909 23985-27579/tv.danmaku.ijk.media.example W/System.err: java.lang.IllegalStateException
02-17 11:27:51.909 23985-27579/tv.danmaku.ijk.media.example W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
02-17 11:27:51.909 23985-27579/tv.danmaku.ijk.media.example W/System.err:     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1046)

**Comment by halfhq** [comment]
@andyjmzheng @SuperXmx 切换回前台重新执行seek

**Comment by houshunwei** [comment]
if this mp4 codec is mpeg4, then you may has the same problem as me.

1. how to reproduce?
I have tried mpeg2video,mpeg4,h264 codec, only mpeg4 has black screen problem on MTK platform(use MediaCodec to decode).
you can generate a mpeg4 codec mp4 use the following cmd line:
> ffmpeg -i festival.mp4 -c:v mpeg4 -c:a copy festival_mpeg4.mp4

2. easiest fix
tv.danmaku.ijk.media.player.IjkMediaCodecInfo.java
` else if (name.startsWith("omx.mtk.")) {
            // 1. MTK only works on 4.3 and above
            // 2. MTK works on MIUI 6 (4.2.1)
            // 3. MTK still not ok when mpeg4；ok for mpeg2video, h264
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.JELLY_BEAN_MR2 || name.endsWith("decoder.mpeg4"))
                rank = RANK_NO_SENSE;
            else
                rank = RANK_TESTED;
        } `
as you can see, i add 'name.endsWith("decoder.mpeg4")',  let mpeg4 to use software codec in MTK platform.

3. root cause?
I decode  festival_mpeg4.mp4 using my MediaExtractor and Mediacodec. it works fine!
so i think it's a bug for ffmpeg/ffplay when invoking MediaCodec. I will post here if i find the root cause.
