### ISSUE TITLE
ln -s module-default.sh config/module.sh

### ISSUE THREAD

**Issue by zlbruce** [Bilibili/ijkplayer#231]
`README.md`中`ln`的命令有问题，应该为`ln -s module-default.sh config/module.sh`

**Comment by bbcallen** [comment]
现在的确是 ”ln -s“ 啊

**Comment by zlbruce** [comment]
`config/module-default.sh` ---> `module-default.sh`

**Comment by bbcallen** [comment]
Fixed. Thanks
