### ISSUE TITLE
多个地址连续播放

### ISSUE THREAD

**Issue by lulukdog** [Bilibili/ijkplayer#2312]
如题，希望可以将多个url地址下的视频连接成一个长视频，其实每个地址都是一小段，希望可以完整连接。在setSurface的时候不太清楚要如何将新的视频控制器（MediaWrapper）和Surface绑定在一起，或是有其他接口或demo解决这个问题？

**Comment by xinzhengzhang** [comment]
Can not understand what you means.
May be [concat](https://www.ffmpeg.org/ffmpeg-formats.html#toc-concat-1) will be helpful

**Comment by lulukdog** [comment]
I want to play a Web-Crawler video which is compose of more than one urls.I use the function "openRemoteFile" to prepare one url and play.The question is how can I play another url after first url closely to make it no blink between the two urls. thq.

**Comment by xinzhengzhang** [comment]
As I said,  [concat](https://www.ffmpeg.org/ffmpeg-formats.html#Syntax) is what you want.
Search ffmpeg concat demuxer.

**Comment by lulukdog** [comment]
thank u for give me this advise.it give a way to concat videos.but the video urls I get is not same duration and even I don't know the time of each one.I only get the stream of a video.

**Comment by xinzhengzhang** [comment]
Duration is necessary for concat demuxer

**Comment by lulukdog** [comment]
3q~ I realize it with surfacetexture

**Comment by kaihuang666** [comment]
> 3q~ I realize it with surfacetexture

I have a same question like yours, but I use ffconcat to realize it. How you realized it puzzled me  a lot. Did you redefine a Player as listener of media when seeking to another media?

**Comment by lulukdog** [comment]
> > 3q~ I realize it with surfacetexture
> 
> I have a same question like yours, but I use ffconcat to realize it. How you realized it puzzled me a lot. Did you redefine a Player as listener of media when seeking to another media?

sorry! I haven't  do it for a long time..
