### ISSUE TITLE
NDK can not be developed

### ISSUE THREAD

**Issue by blue1991** [Bilibili/ijkplayer#2321]
I have three problem.
1.   I executed "sh android/patch-debugging-with-lldb.sh armv7a" , print :
patch apply ==> armv7a
error: 打补丁失败：android/ijkplayer/.gitignore:6
error: android/ijkplayer/.gitignore：补丁未应用
git apply ==> patches/0001-gitignore-ignore-.externalNativeBuild.patch
error: 打补丁失败：android/ijkplayer/build.gradle:5
error: android/ijkplayer/build.gradle：补丁未应用
git apply ==> patches/0002-gradle-upgrade-build-tool-to-2.2.0-beta2.patch
error: 打补丁失败：android/ijkplayer/ijkplayer-armv7a/build.gradle:10
error: android/ijkplayer/ijkplayer-armv7a/build.gradle：补丁未应用
error: 打补丁失败：android/ijkplayer/ijkplayer-example/build.gradle:44
error: android/ijkplayer/ijkplayer-example/build.gradle：补丁未应用
git apply ==> patches/0003-armv7a-enable-debugging-with-LLDB.patch
error: 打补丁失败：ijkmedia/ijkplayer/Android.mk:59
error: ijkmedia/ijkplayer/Android.mk：补丁未应用
git apply ==> patches/0004-armv7a-link-prebuilt-staic-libraries-of-ffmepg.patch

2.    and android studio log:
![image](https://cloud.githubusercontent.com/assets/22043241/20522554/ed8ed29a-b0eb-11e6-841d-fe0024c515f4.png)

3.    I want to include https://github.com/g-truc/glm, but build failed.I created a android studio2.2's demo,it's   successful.

**Comment by ctiao** [comment]
temporary workaround:  
```
git checkout k0.6.2
patch sh android/patch-debugging-with-lldb.sh armv7a
git stash
git checkout master
git stash pop
```

i'll fix it asap

**Comment by blue1991** [comment]
@ctiao I did that:
git clone https://github.com/Bilibili/ijkplayer.git ijkplayer-android
cd ijkplayer-android
git checkout k0.6.2
./init-android.sh
cd android/contrib
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all

but,print that:

====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a arm64 x86 x86_64
FF_ACT_ARCHS = armv5 armv7a arm64 x86 x86_64

====================
[*] check env armv5
====================
FF_ARCH=armv5
FF_BUILD_OPT=

--------------------
[*] make NDK standalone toolchain
--------------------
build on Linux x86_64
ANDROID_NDK=/home/chen/Android/Sdk/ndk-bundle
IJK_NDK_REL=13.1.3345770
You need the NDKr10e or later

**Comment by ctiao** [comment]
You need the NDKr10e or later

**Comment by blue1991** [comment]
![image](https://cloud.githubusercontent.com/assets/22043241/20554251/87d49980-b195-11e6-8b96-c13a6bc03746.png)

The NDK is  latest version, when i git checkout -B latest k0.7.4, i can build. 
But,i checkout k0.6.2, build failed.
Try a few times before, as well.

**Comment by ctiao** [comment]
temporary workaround:  
```
git checkout k0.6.2
patch sh android/patch-debugging-with-lldb.sh armv7a
git stash

git checkout -B latest k0.7.4

git stash pop
```

NDK r13 was not supported in k0.6.2 version

**Comment by blue1991** [comment]
@ctiao I did that, successful.But, when i include https://github.com/g-truc/glm,log is that:
![image](https://cloud.githubusercontent.com/assets/22043241/20591247/9708f6da-b262-11e6-8631-e4ec8ce35a9e.png)
How do I support C ++ compilation?Can you help me? This is my file structure：
![image](https://cloud.githubusercontent.com/assets/22043241/20591331/f88b88fa-b262-11e6-8433-f8e0372b6851.png)
and i add "LOCAL_C_INCLUDES += $(realpath $(LOCAL_PATH)/ijkmedia/ijkplayer/glm)" in jni/Android.mk.

**Comment by blue1991** [comment]
I solved the problem,thanks!

**Comment by marinat** [comment]
@blue1991 How did you solved it?

**Comment by fukemy** [comment]
@blue1991  how did u solve it?
