### ISSUE TITLE
请问你这里用到了WebRTC么？我们库有冲突？

### ISSUE THREAD

**Issue by Bone111** [Bilibili/ijkplayer#2323]
请问你这里用到了WebRTC么？我们库有冲突？

**Comment by notedit** [comment]
没有用到    请说出具体的冲突原因

**Comment by Bone111** [comment]
我们项目中有anychat，只要一加入这个库，anychat视频就没有画面。

**Comment by xinzhengzhang** [comment]
![v1_ 2f5hb1sxyukj21w _o](https://cloud.githubusercontent.com/assets/1487445/20550352/9995d60a-b16f-11e6-8d05-ec07a5a99b20.png)

Guanwopishi
