### ISSUE TITLE
Access to HLS playlist segments

### ISSUE THREAD

**Issue by brystel** [Bilibili/ijkplayer#233]
Hello,

Is it possible to get .ts segments name from loaded .m3u8 playlist?
Another question, how to start playback from specific .ts segment?

For example, .m3u8 playlist has 100 segments and I would like to get segments names and start playing from fifth segment.

Thank you

**Comment by bbcallen** [comment]
Not possible without new API.

**Comment by brystel** [comment]
Ok, it is worth to try.
Could you navigate my where to start for achieve my purpose?

**Comment by bbcallen** [comment]
Have a look at libavformat/hls.c
