### ISSUE TITLE
概率播放异常虽然很低

### ISSUE THREAD

**Issue by JavanEu** [Bilibili/ijkplayer#234]
我遇到使用ijkplayer播放的时候，直接播放http链接的视频。遇到视频卡在最后一帧，单声音继续播放的问题。不知道作者你有没有遇到？

**Comment by bbcallen** [comment]
#235 的修改是与这个有关么?

**Comment by ctiao** [comment]
我也遇到过卡帧并且声音继续播放的情况

**Comment by JavanEu** [comment]
@bbcallen 木有 #235 是独立的功能。我的推送实现精确seek操作。我有需要就实现了。顺带共享给你。

概率很低~就是播放到一半突然卡住。音频继续，但画面已经废了。这个我会叫人帮忙复现下。

可能是网络层问题吗？

**Comment by JavanEu** [comment]
@ctiao 你也是http直连吗？

**Comment by ctiao** [comment]
@JavanEu   http和本地文件都遇到过，所以应该不是网络层的问题

**Comment by lsjwzh** [comment]
@JavanEu  我猜应该是视频遇到异常就就不再继续解码了，但是音频仍然继续解码中。。。在魅族的机器上用魅族自带播放器播放不完整文件时，也遇到过类似情况。。

**Comment by JavanEu** [comment]
@lsjwzh 有些mp4的组织方式是音频数据在头部保存。边下载边播放可能已经下载了音频流的大部分数据所以可以音频部分正常播放。 确实如果视频流解码出问题，就再也解码不处数据了。

我担心是某些特殊视频播放的时候造成，htttp会不断的获取一些特殊位置的数据。这个切换的过程中出问题了。我最近刚在ijk的基础上实现下载缓存的机制。测试阶段发现。视频解码的时候如果有seek操作会带来不确定的seek移动。

**Comment by JavanEu** [comment]
@lsjwzh @ctiao 遇到一种错误情况的视频我有缓存下载。缓存下来的mp4文件无法正常播放的。我比较过数据发现里面一片数据都是0，相当于没有下载成功。我还在查是否跟我的缓冲机制有关系。

**Comment by JavanEu** [comment]
@ctiao 本地文件感觉应该不会吧。估计是视频文件有问题。可以使用VLC试一试

**Comment by lsjwzh** [comment]
@JavanEu  对。这样的情况会出现。。。之前用的cdn，就会偶尔出现下载的数据不准确之类的情况

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.

**Comment by bhltyou** [comment]
@JavanEu j
请问你的本地缓存现在成功了吗
