### ISSUE TITLE
编码hevc支持问题

### ISSUE THREAD

**Issue by feng55** [Bilibili/ijkplayer#2344]
启用./configure --list-encoders命令，只看到了nvenc_hevc"。hevc_nvenc"。hevc_qsv"，hevc_vaapi"这几个有关hevc编码的选项，但是设置了 --enable-encoder=nvenc_hevc 之后编译的库还是不支持hevc编码，在解码中使用--enable-decoder=hevc。发现支持解码，请问，我该如何编译支持hevc编码的版本呢

**Comment by xinzhengzhang** [comment]
#2340
