### ISSUE TITLE
iOS-播放器如何彻底销毁？

### ISSUE THREAD

**Issue by yhq-iOS** [Bilibili/ijkplayer#2349]
从播放界面返回后，声音还存在。急求 ！望尽快解答，万分感谢

**Comment by xinzhengzhang** [comment]
Has `shutdown` been called?

**Comment by yhq-iOS** [comment]
在- (void)viewWillDisappear:(BOOL)animated 调用了shutdown。 
退出播放界面，切换到后台，仍能收到IJKSDLGLView:applicationDidBecomeActive: 0 和 IJKFFMoviePlayerController:applicationDidBecomeActive: 0通知。

**Comment by xinzhengzhang** [comment]
It seems you leak the controller.

**Comment by yhq-iOS** [comment]
确实是 谢谢
