### ISSUE TITLE
使用Xcode7.3.1编译，提示不期望的FFmpeg版本

### ISSUE THREAD

**Issue by noveleven** [Bilibili/ijkplayer#2350]
使用Xcode7编译ffmpeg，再使用Xcode7构建版本运行弹出提示框：实际ff3.1 ijk0.6.1 期望ff3.2 ijk0.7.4。
使用Xcode8编译ffmpeg，再使用Xcode8构建版本运行正常。
使用Xcode8编译ffmpeg，再使用Xcode7构建版本运行报符号缺失。

**Comment by rickliu2000** [comment]
Xcode8 也这样。。。提示版本不对

**Comment by xinzhengzhang** [comment]
@noveleven 
Version code of ffmpeg has nothing relation with xcode version.
Which symbol is missing when compiling ffmpeg with xcode8 and running under xcode7?

**Comment by noveleven** [comment]
@xinzhengzhang I used master branch to do it, i'll try again later using other released source, and symbol missing seems like a clock symbol missing. BTW, thank zhang sir.

**Comment by xinzhengzhang** [comment]
The issue about `clock_get_time` has been fixed in latest ffmpeg.
Obviously there is something wrong when you compile the ffmpeg under xcode7 toolchain.

**Comment by dlhub** [comment]
So it is with the Xcode Version 8.0
log:
!!!!!!!!!!
actual: ff3.2--ijk0.7.2-20161107--001
 expect: ff3.2--ijk0.7.4--20161116--001

!!!!!!!!!!
av_version_info: ff3.2--ijk0.7.2-20161107--001
ijk_version_info: k0.7.5
ijkmp_set_inject_opaque(0x1700069c0)
ijkmp_set_inject_opaque()=void

**Comment by xinzhengzhang** [comment]
@dlhub 
It seems automatically generate script in ffmpeg has a bug when tag twice in the same commit with different name. This warning is no need to worry and I will fix it in next release.

**Comment by dlhub** [comment]
@xinzhengzhang 
I see, thanks for your kind interpretation

**Comment by noveleven** [comment]
k0.7.4 work like a charm! It's weird that after I confirmed the built-in clang version and checked out k0.7.5 compiling with xcode7, there was always an unexpected ffmpeg version with the wrong version of ijk. If someone also encounters the same problem, hope this can help.
