### ISSUE TITLE
On ios https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.

### ISSUE THREAD

**Issue by rickliu2000** [Bilibili/ijkplayer#2352]
init-iOS-openssl.sh
compile-openssl.sh
I added the two steps below.But still, not able to use ssl live stream

**Comment by rickliu2000** [comment]
solved

**Comment by patzhangjiwang** [comment]
how do you solved??? @rickliu2000

**Comment by zmw123** [comment]
how do you solved

**Comment by YGLau** [comment]
how??? same question @rickliu2000
