### ISSUE TITLE
三星手机两个ijkplayer拉流闪屏

### ISSUE THREAD

**Issue by yuyashuai** [Bilibili/ijkplayer#2371]
同一个屏幕中用两个ijkplayer，同时拉两道流，两个播放器都可以播放，但是第一个播放器上除了正常的流之外，还会一直闪出第二个播放器的帧。只有在三星手机上有这种问题

**Comment by yuyashuai** [comment]
其中一个ijkplayer播放的画面是两道流掺杂在一起的，

**Comment by xinzhengzhang** [comment]
still can not understand

**Comment by oncealong** [comment]
> 同一个屏幕中用两个ijkplayer，同时拉两道流，两个播放器都可以播放，但是第一个播放器上除了正常的流之外，还会一直闪出第二个播放器的帧。只有在三星手机上有这种问题

你好, 请问这个问题解决了么? 我的使用场景也是同时显示两个player和TextureView, 其中一个TextureView会偶尔显示另一个TextureView的内容. 这个现象只在某些低版本手机上(4.4)出现, 怀疑是系统的bug
