### ISSUE TITLE
关于小米2和小米Note顶配版卡死

### ISSUE THREAD

**Issue by JavanEu** [Bilibili/ijkplayer#239]
@bbcallen @ctiao 我在使用ijkplayer作为feed里面通用播放器的时候遇到一个问题。他们在高速滑动下会把机器弄死机~不知道你们有没有遇到过!

**Comment by bbcallen** [comment]
feed 是什么?

**Comment by JavanEu** [comment]
@bbcallen  就是在链表展示多个视频的时候ListView里面。由于滑动。可能会出来该问题刚好C层的NativeWindow 刷新SurfaceView 。小米的机器很奇怪。直接卡住

**Comment by bbcallen** [comment]
链表展示多个视频是类似搜狐视频那样，滑到哪个item，就在哪个item上开始播放么?
具体是怎样使用的？有没有伪代码说明一下使用方式。

**Comment by jgfntu** [comment]
这两部机器是android5.0的系统么，之前我自己定制的定点开始播放功能时，5.0系统里面java层的一个long时间值传到native层就出问题了，后来改成了int暂时规避（4.x系统没这问题）。你可以看看有没有ANR类似的log

**Comment by bbcallen** [comment]
哪个 API?

**Comment by JavanEu** [comment]
@jgfntu 小米Note 的是5.0的。 
@bbcallen 跟你说的情况差不多。就是滑动到哪个item哪个播放。但是判断条件是当播放器的区域离开屏幕范围将其stop。但是ffplay停止的过程比较慢。需要等待thread退出。可能在离开屏幕的时候还有机会刷新。

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.

**Comment by zhanggao** [comment]
@JavanEu 后来你是否有解决这个问题？
