### ISSUE TITLE
应用层问题，请教

### ISSUE THREAD

**Issue by asawalker** [Bilibili/ijkplayer#240]
android端，Activity中的Videoview，调用pause()后，点击home键，回到了桌面后，再次点击demo应用，进入activity后，发现VideoView区域是黑的，并不是我pause()的时候的视频画面。

请教下，这个问题怎么解决，给个思路。谢谢

**Comment by ctiao** [comment]
这是SurfaceView限制,回到桌面后SurfaceView一定会被销毁， 可以考虑尝试使用TextureView输出视频画面。

**Comment by asawalker** [comment]
非常感谢您的回答，谢谢！

**Comment by xqq** [comment]
这应该与 SurfaceView/TextureView 无关。。。

**Comment by asawalker** [comment]
@xqq 你有什么解决方案吗？

**Comment by UC10D** [comment]
SurfaceView 销毁了
