### ISSUE TITLE
android硬解码数据格式转换

### ISSUE THREAD

**Issue by PengBoShi** [Bilibili/ijkplayer#2405]
我想把android硬解码出来的数据转成YUV420P的。android硬解码的数据格式是什么？会不会因为手机不同而解码的格式不同

**Comment by xinzhengzhang** [comment]
depend on device

**Comment by PengBoShi** [comment]
谢谢，请问一下，android硬解码出来的数据我想要用FFmpeg转成YUV的，在func_fill_frame这个函数中操作。硬解码出来的数据格式我应该在哪里怎么获取呢

**Comment by xinzhengzhang** [comment]
#2410

**Comment by PengBoShi** [comment]
谢谢，我看了一下，但是我觉得并没有我需要的信息，我依旧不知道怎么获取android硬解码的数据格式

**Comment by xinzhengzhang** [comment]
I said it depends on you hardware device which implement mediacodec.

**Comment by PengBoShi** [comment]
你说的是在ffpipenode_android_mediacodec_vdec.c吗

**Comment by quelleG** [comment]
av_get_pix_fmt_name(is->viddec.avctx->pix_fmt)
