### ISSUE TITLE
Which module based on Vitamio?

### ISSUE THREAD

**Issue by jpxiong** [Bilibili/ijkplayer#242]
As I know , the vitamio need the business negotiation, so can you please tell me which module based on Vitamio ?

Thanks.

**Comment by bbcallen** [comment]
1. ijkmediawidget uses several vitamio's java source file, which are licensed under Apache 2.0
https://github.com/yixia/VitamioBundle/blob/master/vitamio/src/io/vov/vitamio/widget/VideoView.java
https://github.com/yixia/VitamioBundle/blob/master/vitamio/src/io/vov/vitamio/widget/

2. vitamio's FFmpeg build script is referenced.
https://github.com/yixia/FFmpeg-Android

I think these parts is safe for commercial use.

ijkmediawidget is only a demo. Mostly, it's not enough for your need in a serious application.
If you write your own UI based on ijkmediaplayer project, there would be nothing in binary related to vitamio's sdk.

**Comment by jpxiong** [comment]
Thanks for you great support !
