### ISSUE TITLE
Can't live stream youtube

### ISSUE THREAD

**Issue by iamstudentVN** [Bilibili/ijkplayer#2430]
I try test link on the VLC, Edge. It works fine. But i try on ijkplayer i got error: unknow?
> https://manifest.googlevideo.com/api/manifest/hls.......m3u8

![1](https://cloud.githubusercontent.com/assets/12800744/21124549/36b6a688-c112-11e6-9be3-bfb20c9938bd.jpg)

**Comment by iamstudentVN** [comment]
I've found the cause: open openssl. But i using:
`dependencies {
    # required, enough for most devices.
    compile 'tv.danmaku.ijk.media:ijkplayer-java:0.7.5'
    compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.7.5'

    # Other ABIs: optional
    compile 'tv.danmaku.ijk.media:ijkplayer-armv5:0.7.5'
    compile 'tv.danmaku.ijk.media:ijkplayer-arm64:0.7.5'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.7.5'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86_64:0.7.5'

    # ExoPlayer as IMediaPlayer: optional, experimental
    compile 'tv.danmaku.ijk.media:ijkplayer-exo:0.7.5'
}`
how to build openssl?

**Comment by gotone** [comment]
recompile ijkplayer with openssl support.

**Comment by iamstudentVN** [comment]
@gotone  how to recompile ijkplayer with openssl?

**Comment by xinzhengzhang** [comment]
#1824

**Comment by iamstudentVN** [comment]
@xinzhengzhang I know how to compile it? I try code on Git bash but it get error. I do not know what this command to run on any program
 `./init-android.sh

cd android/contrib
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all

cd ..
./compile-ijk.sh all`

![image](https://cloud.githubusercontent.com/assets/12800744/21169504/5f78575a-c1ef-11e6-9d18-10874d659ed9.png)

**Comment by xinzhengzhang** [comment]
Please install Cygwin make package or define the GNUMAKE variable to point to it.

**Comment by iamstudentVN** [comment]
Yes, i installed Cygwin make package. But **"define the GNUMAKE variable to point to it"** what mean?
![image](https://cloud.githubusercontent.com/assets/12800744/21170178/6a92c4d0-c1f5-11e6-81f2-1efbe705290d.png)

**Comment by xinzhengzhang** [comment]
Sorry, I don't maintain cygwin support.

**Comment by iamstudentVN** [comment]
@xinzhengzhang how to fix it?
`$ ./compile-ijk.sh all
profiler build: NO
ln: failed to create symbolic link 'android-ndk-prof/jni': No such file or directory
Android NDK: Your APP_BUILD_SCRIPT points to an unknown file: /cygdrive/C/Users/sieunhangao/ijkplayer-android/jni/Android.mk
C:/NDK/build/core/add-application.mk:199: *** Android NDK: Aborting...    .  Stop.
/c/cygwin64/home/sieunhangao/ijkplayer-android/android
`

**Comment by iamstudentVN** [comment]
ok it's work, close here :)

**Comment by x64Dev** [comment]
Although the file "gen_cygpath.py" does exists it still gives me error. Any idea how to resolve below issues? I'm building to make the youtube live stream work. I'm following the instructions from the official github Overview page.

C:\Python27\python.exe: can't open file '/cygdrive/C/Android/Sdk/ndk-bundle/buil
d/gen_cygpath.py': [Errno 2] No such file or directory
Android NDK: android-9 is unsupported. Using minimum supported version android-16.
C:\Python27\python.exe: can't open file '/cygdrive/C/Android/Sdk/ndk-bundle/buil
d/extract_manifest.py': [Errno 2] No such file or directory
Android NDK: WARNING: APP_PLATFORM android-16 is higher than android:minSdkVersion 1 in /cygdrive/c/Android/ijkplayer-android/android/ijkplayer/ijkplayer-armv5/src/main/AndroidManifest.xml. NDK binaries will *not* be compatible with devices older than android-16. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.
C:\Python27\python.exe: can't open file '/cygdrive/C/Android/Sdk/ndk-bundle/buil
d/extract_manifest.py': [Errno 2] No such file or directory
/cygdrive/C/Android/Sdk/ndk-bundle/build/core/add-application.mk:178: *** Android NDK: APP_STL stlport_static is no longer supported. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    .  Stop.
/cygdrive/c/Android/ijkplayer-android/android
profiler build: NO
C:\Python27\python.exe: can't open file '/cygdrive/C/Android/Sdk/ndk-bundle/buil
d/gen_cygpath.py': [Errno 2] No such file or directory
Android NDK: android-9 is unsupported. Using minimum supported version android-16.
C:\Python27\python.exe: can't open file '/cygdrive/C/Android/Sdk/ndk-bundle/buil
d/extract_manifest.py': [Errno 2] No such file or directory
Android NDK: WARNING: APP_PLATFORM android-16 is higher than android:minSdkVersion 1 in /cygdrive/c/Android/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/AndroidManifest.xml. NDK binaries will *not* be compatible with devices older than android-16. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.
C:\Python27\python.exe: can't open file '/cygdrive/C/Android/Sdk/ndk-bundle/buil
d/extract_manifest.py': [Errno 2] No such file or directory
/cygdrive/C/Android/Sdk/ndk-bundle/build/core/add-application.mk:178: *** Android NDK: APP_STL stlport_static is no longer supported. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    .  Stop.
/cygdrive/c/Android/ijkplayer-android/android
profiler build: NO
C:\Python27\python.exe: can't open file '/cygdrive/C/Android/Sdk/ndk-bundle/buil
d/gen_cygpath.py': [Errno 2] No such file or directory
C:\Python27\python.exe: can't open file '/cygdrive/C/Android/Sdk/ndk-bundle/buil
d/extract_manifest.py': [Errno 2] No such file or directory
Android NDK: WARNING: APP_PLATFORM android-21 is higher than android:minSdkVersion 1 in /cygdrive/c/Android/ijkplayer-android/android/ijkplayer/ijkplayer-arm64/src/main/AndroidManifest.xml. NDK binaries will *not* be compatible with devices older than android-21. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.
C:\Python27\python.exe: can't open file '/cygdrive/C/Android/Sdk/ndk-bundle/buil
d/extract_manifest.py': [Errno 2] No such file or directory
/cygdrive/C/Android/Sdk/ndk-bundle/build/core/add-application.mk:178: *** Android NDK: APP_STL stlport_static is no longer supported. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    .  Stop.
/cygdrive/c/Android/ijkplayer-android/android
profiler build: NO
C:\Python27\python.exe: can't open file '/cygdrive/C/Android/Sdk/ndk-bundle/buil
d/gen_cygpath.py': [Errno 2] No such file or directory
Android NDK: android-9 is unsupported. Using minimum supported version android-16.
C:\Python27\python.exe: can't open file '/cygdrive/C/Android/Sdk/ndk-bundle/buil
d/extract_manifest.py': [Errno 2] No such file or directory
Android NDK: WARNING: APP_PLATFORM android-16 is higher than android:minSdkVersion 1 in /cygdrive/c/Android/ijkplayer-android/android/ijkplayer/ijkplayer-x86/src/main/AndroidManifest.xml. NDK binaries will *not* be compatible with devices older than android-16. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.
C:\Python27\python.exe: can't open file '/cygdrive/C/Android/Sdk/ndk-bundle/buil
d/extract_manifest.py': [Errno 2] No such file or directory
/cygdrive/C/Android/Sdk/ndk-bundle/build/core/add-application.mk:178: *** Android NDK: APP_STL stlport_static is no longer supported. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    .  Stop.
/cygdrive/c/Android/ijkplayer-android/android
profiler build: NO
C:\Python27\python.exe: can't open file '/cygdrive/C/Android/Sdk/ndk-bundle/buil
d/gen_cygpath.py': [Errno 2] No such file or directory
C:\Python27\python.exe: can't open file '/cygdrive/C/Android/Sdk/ndk-bundle/buil
d/extract_manifest.py': [Errno 2] No such file or directory
Android NDK: WARNING: APP_PLATFORM android-21 is higher than android:minSdkVersion 1 in /cygdrive/c/Android/ijkplayer-android/android/ijkplayer/ijkplayer-x86_64/src/main/AndroidManifest.xml. NDK binaries will *not* be compatible with devices older than android-21. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.
C:\Python27\python.exe: can't open file '/cygdrive/C/Android/Sdk/ndk-bundle/buil
d/extract_manifest.py': [Errno 2] No such file or directory
/cygdrive/C/Android/Sdk/ndk-bundle/build/core/add-application.mk:178: *** Android NDK: APP_STL stlport_static is no longer supported. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    .  Stop.
/cygdrive/c/Android/ijkplayer-android/android
