### ISSUE TITLE
How to build ijkplayer with openssl ?

### ISSUE THREAD

**Issue by iamstudentVN** [Bilibili/ijkplayer#2433]
I I follow this site: http://stackoverflow.com/questions/38529791/android-lib-ijkplayer-load-https-url but cannot build it with error:
`WARNING: arm-linux-androideabi-pkg-config not found, library detection may fail.
tools/do-compile-ffmpeg.sh: line 308: make: command not found`

`$ ./compile-ijk.sh all
profiler build: NO
ERROR: Cannot find 'make' program. Please install Cygwin make package
or define the GNUMAKE variable to point to it.
/c/Users/sieunhangao/ijkplayer-android/android
profiler build: NO
ERROR: Cannot find 'make' program. Please install Cygwin make package
or define the GNUMAKE variable to point to it.
/c/Users/sieunhangao/ijkplayer-android/android
profiler build: NO
ERROR: Cannot find 'make' program. Please install Cygwin make package
or define the GNUMAKE variable to point to it.
/c/Users/sieunhangao/ijkplayer-android/android
profiler build: NO
ERROR: Cannot find 'make' program. Please install Cygwin make package
or define the GNUMAKE variable to point to it.
/c/Users/sieunhangao/ijkplayer-android/android
profiler build: NO
ERROR: Cannot find 'make' program. Please install Cygwin make package
or define the GNUMAKE variable to point to it.
/c/Users/sieunhangao/ijkplayer-android/android`

**Comment by noveleven** [comment]
If you use a windows environment to compile ffmpeg, you need install [Cygwin](http://www.cygwin.com/).

**Comment by iamstudentVN** [comment]
@noveleven i installed Cygwin but get there errors

**Comment by iamstudentVN** [comment]
I set `GNUMAKE=$PROGDIR/cygwin64/bin/make` in file ndk-build and get error:
`ln: failed to create symbolic link 'android-ndk-prof/jni': No such file or directory
2 [main] make (5428) C:\android-ndk-r10e\cygwin64\bin\make.exe: *** fatal error - cygheap base mismatch detected - 0x1802FF408/0x180302408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
/c/Users/sieunhangao/ijkplayer-android/android`

**Comment by iamstudentVN** [comment]
ok it's work, close here :)
