### ISSUE TITLE
ijkmp_ios_set_glview cause memory leaks

### ISSUE THREAD

**Issue by PonyCui** [Bilibili/ijkplayer#244]
should add 
ijkmp_ios_set_glview(_mediaPlayer, nil);
to IJKFFMoviePlayerController dealloc method, or it will cause IJKSDLGLView circular reference issue(IJKSDLGLView never release).

**Comment by bbcallen** [comment]
IJKFFMoviePlayerController must be released in [mp shutdown] explicitily.

**Comment by PonyCui** [comment]
Thanks. It's okay.
