### ISSUE TITLE
encrpty m3u8

### ISSUE THREAD

**Issue by owenstar** [Bilibili/ijkplayer#2453]
播放本地服务器加密m3u8文件，报错，但是相同方法在AVPlayer就可以播放。请问是哪里的问题？
2016-12-19 11:21:27.583 IJKMediaDemo[46473:929071] 服务器路径：/Users/dehuxia/Library/Developer/CoreSimulator/Devices/551E11B6-EDFA-46EB-8B6C-CBDF7DE3233F/data/Containers/Data/Application/9954E5F3-15A1-4676-A701-FB527AEB16E2/Documents/Downloads

```
2016-12-19 11:21:27:583 IJKMediaDemo[46473:a07] HTTPServer: Started HTTP server on port 9479
2016-12-19 11:21:27.584 IJKMediaDemo[46473:929071] 开启HTTP服务器 端口:9479
2016-12-19 11:21:28:546 IJKMediaDemo[46473:6e03] Bonjour Service Published: domain(local.) type(_http._tcp.) name(Dehu)
2016-12-19 11:21:29.998 IJKMediaDemo[46473:929071] /Users/dehuxia/Library/Developer/CoreSimulator/Devices/551E11B6-EDFA-46EB-8B6C-CBDF7DE3233F/data/Containers/Data/Application/9954E5F3-15A1-4676-A701-FB527AEB16E2/Documents/Downloads/bb
===== custom modules begin =====
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff3.2--ijk0.7.5--20161205--001
ijk_version_info: 
ijkmp_set_inject_opaque(0x608000009e50)
ijkmp_set_inject_opaque()=void
2016-12-19 11:21:55.531 IJKMediaDemo[46473:929071] OK setup GL
ijkmp_ios_set_view(glView=0x7fca8a82b780)
ijkmp_ios_set_view(glView=0x7fca8a82b780)=void
2016-12-19 11:21:55.578 IJKMediaDemo[46473:929071] invalidateRenderBuffer
2016-12-19 11:21:55.578 IJKMediaDemo[46473:934014] IJKSDLGLView: setupDisplay not ready
ijkmp_set_data_source(url="http://127.0.0.1:9479/aa/bb.m3u8")
ijkmp_set_data_source(url="http://127.0.0.1:9479/aa/bb.m3u8")=0
ijkmp_prepare_async()
===== versions =====
ijkplayer    : 
FFmpeg       : ff3.2--ijk0.7.5--20161205--001
libavutil    : 55.34.100
libavcodec   : 57.64.100
libavformat  : 57.56.100
libswscale   : 4.2.100
libswresample: 2.3.100
===== options =====
player-opts : video-pictq-size             = 3
player-opts : overlay-format               = fcc-_es2
player-opts : max-fps                      = 30
player-opts : framedrop                    = 0
player-opts : videotoolbox-max-frame-width = 960
player-opts : videotoolbox                 = 0
player-opts : start-on-prepared            = 1
format-opts : ijkapplication               = 140507883802592
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : timeout                      = 30000000
format-opts : reconnect                    = 1
format-opts : safe                         = 0
===================
ijkmp_prepare_async()=0
Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'
2016-12-19 11:21:55.606518 IJKMediaDemo[46473:934052] [] nw_host_stats_add_src recv too small, received 24, expected 28
the user-agent option is deprecated, please use user_agent option
request: GET /aa/bb.m3u8 HTTP/1.1
User-Agent: ijkplayer
Accept: */*
Range: bytes=0-
Connection: close
Host: 127.0.0.1:9479
Icy-MetaData: 1


Format hls,applehttp probed with size=2048 and score=100
HLS request for url 'http://127.0.0.1:9479/aa/bb0.ts', offset 0, playlist 0
the user-agent option is deprecated, please use user_agent option
request: GET /aa/file.key HTTP/1.1
User-Agent: ijkplayer
Accept: */*
Connection: close
Host: 127.0.0.1:9479
Icy-MetaData: 1


Statistics: 16 bytes read, 0 seeks
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb1.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb2.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb3.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb4.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb5.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb6.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb7.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb8.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb9.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb10.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb11.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb12.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb13.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb14.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb15.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb16.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb17.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb18.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb19.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb20.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb21.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb22.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb23.ts', offset 0, playlist 0
Failed to open segment of playlist 0
Error when loading first segment 'http://127.0.0.1:9479/aa/bb0.ts'
Statistics: 790 bytes read, 0 seeks
http://127.0.0.1:9479/aa/bb.m3u8: Invalid data found when processing input
2016-12-19 11:21:55.613 IJKMediaDemo[46473:929071] invalidateRenderBuffer
2016-12-19 11:21:55.613 IJKMediaDemo[46473:934054] IJKSDLGLView: setupDisplay not ready
2016-12-19 11:21:55.668 IJKMediaDemo[46473:929071] FFP_MSG_ERROR: 0
2016-12-19 11:21:55.668 IJKMediaDemo[46473:929071] IJKMPMoviePlayBackStateDidChange 2: paused
2016-12-19 11:21:55.669 IJKMediaDemo[46473:929071] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1
```

**Comment by owenstar** [comment]
用你们的demo测试LOG日志如下：
2016-12-19 11:21:27.583 IJKMediaDemo[46473:929071] 服务器路径：/Users/dehuxia/Library/Developer/CoreSimulator/Devices/551E11B6-EDFA-46EB-8B6C-CBDF7DE3233F/data/Containers/Data/Application/9954E5F3-15A1-4676-A701-FB527AEB16E2/Documents/Downloads
2016-12-19 11:21:27:583 IJKMediaDemo[46473:a07] HTTPServer: Started HTTP server on port 9479
2016-12-19 11:21:27.584 IJKMediaDemo[46473:929071] 开启HTTP服务器 端口:9479
2016-12-19 11:21:28:546 IJKMediaDemo[46473:6e03] Bonjour Service Published: domain(local.) type(_http._tcp.) name(Dehu)
2016-12-19 11:21:29.998 IJKMediaDemo[46473:929071] /Users/dehuxia/Library/Developer/CoreSimulator/Devices/551E11B6-EDFA-46EB-8B6C-CBDF7DE3233F/data/Containers/Data/Application/9954E5F3-15A1-4676-A701-FB527AEB16E2/Documents/Downloads/bb
===== custom modules begin =====
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff3.2--ijk0.7.5--20161205--001
ijk_version_info: 
ijkmp_set_inject_opaque(0x608000009e50)
ijkmp_set_inject_opaque()=void
2016-12-19 11:21:55.531 IJKMediaDemo[46473:929071] OK setup GL
ijkmp_ios_set_view(glView=0x7fca8a82b780)
ijkmp_ios_set_view(glView=0x7fca8a82b780)=void
2016-12-19 11:21:55.578 IJKMediaDemo[46473:929071] invalidateRenderBuffer
2016-12-19 11:21:55.578 IJKMediaDemo[46473:934014] IJKSDLGLView: setupDisplay not ready
ijkmp_set_data_source(url="http://127.0.0.1:9479/aa/bb.m3u8")
ijkmp_set_data_source(url="http://127.0.0.1:9479/aa/bb.m3u8")=0
ijkmp_prepare_async()
===== versions =====
ijkplayer    : 
FFmpeg       : ff3.2--ijk0.7.5--20161205--001
libavutil    : 55.34.100
libavcodec   : 57.64.100
libavformat  : 57.56.100
libswscale   : 4.2.100
libswresample: 2.3.100
===== options =====
player-opts : video-pictq-size             = 3
player-opts : overlay-format               = fcc-_es2
player-opts : max-fps                      = 30
player-opts : framedrop                    = 0
player-opts : videotoolbox-max-frame-width = 960
player-opts : videotoolbox                 = 0
player-opts : start-on-prepared            = 1
format-opts : ijkapplication               = 140507883802592
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : timeout                      = 30000000
format-opts : reconnect                    = 1
format-opts : safe                         = 0
===================
ijkmp_prepare_async()=0
Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'
2016-12-19 11:21:55.606518 IJKMediaDemo[46473:934052] [] nw_host_stats_add_src recv too small, received 24, expected 28
the user-agent option is deprecated, please use user_agent option
request: GET /aa/bb.m3u8 HTTP/1.1
User-Agent: ijkplayer
Accept: */*
Range: bytes=0-
Connection: close
Host: 127.0.0.1:9479
Icy-MetaData: 1


Format hls,applehttp probed with size=2048 and score=100
HLS request for url 'http://127.0.0.1:9479/aa/bb0.ts', offset 0, playlist 0
the user-agent option is deprecated, please use user_agent option
request: GET /aa/file.key HTTP/1.1
User-Agent: ijkplayer
Accept: */*
Connection: close
Host: 127.0.0.1:9479
Icy-MetaData: 1


Statistics: 16 bytes read, 0 seeks
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb1.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb2.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb3.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb4.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb5.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb6.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb7.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb8.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb9.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb10.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb11.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb12.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb13.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb14.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb15.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb16.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb17.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb18.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb19.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb20.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb21.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb22.ts', offset 0, playlist 0
Failed to open segment of playlist 0
HLS request for url 'http://127.0.0.1:9479/aa/bb23.ts', offset 0, playlist 0
Failed to open segment of playlist 0
Error when loading first segment 'http://127.0.0.1:9479/aa/bb0.ts'
Statistics: 790 bytes read, 0 seeks
http://127.0.0.1:9479/aa/bb.m3u8: Invalid data found when processing input
2016-12-19 11:21:55.613 IJKMediaDemo[46473:929071] invalidateRenderBuffer
2016-12-19 11:21:55.613 IJKMediaDemo[46473:934054] IJKSDLGLView: setupDisplay not ready
2016-12-19 11:21:55.668 IJKMediaDemo[46473:929071] FFP_MSG_ERROR: 0
2016-12-19 11:21:55.668 IJKMediaDemo[46473:929071] IJKMPMoviePlayBackStateDidChange 2: paused
2016-12-19 11:21:55.669 IJKMediaDemo[46473:929071] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1

**Comment by xinzhengzhang** [comment]
#2348

**Comment by owenstar** [comment]
已将 --disable-protocol=crypto 改为--enable-protocol=crypto 然后重新
./compile-ffmpeg.sh clean
./compile-openssl.sh all
./compile-ffmpeg.sh all
还是报这个错误

**Comment by owenstar** [comment]
I have been solved it ,thanks.

**Comment by IOSWLW** [comment]
怎么解决的   @owenstar

**Comment by VitProg** [comment]
@owenstar
how you solved the problem?

**Comment by loveRose** [comment]
怎么解决的？？？

**Comment by Android4MediaPlayer** [comment]
add openssl

**Comment by qinshuai1334** [comment]
@owenstar how to resolve this problem?

**Comment by mdaslamHossin** [comment]
Where to add oppenssl@Android@MediaPi
