### ISSUE TITLE
ijkplayer怎么做视频加解密

### ISSUE THREAD

**Issue by yuxfzju** [Bilibili/ijkplayer#246]
RT

**Comment by bbcallen** [comment]
首先，你打算怎么加密?

**Comment by yuxfzju** [comment]
抱歉，没有详细说明。如果对视频文件本身做AES加密，应该怎么处理播放时的解密操作
ijkplayer应该没有相应的接口吧

**Comment by bbcallen** [comment]
如果是 HLS，参考 libavformat/hls.c，需要先编译 openssl，不过加密功能本身并不需要接口参与。
如果是自定义加密方式，那么当然没有相应的接口。

**Comment by toumubaoqiong** [comment]
如果加密是http的，有没有什么好的方案进行进行解密？

**Comment by pengzee** [comment]
> 

http加密和播放器也没关系吧，解密的过程应该你的业务自己处理，然后将解密后的视频流交给播放器
