### ISSUE TITLE
请教IOS播放器静音问题

### ISSUE THREAD

**Issue by wuxianzhao** [bilibili/ijkplayer#2462]
请问播放器可以控制静音吗，不控制设备声音，只控制视频声音，类似avplayer里面的静音，谢谢！

**Comment by xinzhengzhang** [comment]
Find it it in `IJKMediaPlayback`

**Comment by MarkBuster** [comment]
播放器静音播放视频的时候。。会中断其它后台音乐。。有办法设置不中断其它音乐么。。打开声音的时候才中断
