### ISSUE TITLE
Does android ijkplayer support hw decoder in all android API( >= 9) version ?

### ISSUE THREAD

**Issue by jpxiong** [Bilibili/ijkplayer#247]
I have noticed that:
Android
    platform: API 9~22
    cpu: ARMv7a, x86, ARMv5 (not tested on real devices)
    api: MediaPlayer-like
    video output: NativeWindow
    audio output: OpenSL ES, AudioTrack
    hw decoder: MediaCodec

As I know, MediaCodec released in API 16, so ijkplayer don't support hw decoder under API 16 version, using the ffmpeg's software decoder. Am I right?

**Comment by bbcallen** [comment]
Yes.

**Comment by jpxiong** [comment]
Thanks.
