### ISSUE TITLE
iOS ijkplay偶发崩溃

### ISSUE THREAD

**Issue by bluedaquiri** [Bilibili/ijkplayer#2473]
`2016-12-22 10:29:48.562 MediaLiveStream[15409:883145] OK setup GL
ijkmp_ios_set_view(glView=0x7ff740e437b0)
ijkmp_ios_set_view(glView=0x7ff740e437b0)=void
2016-12-22 10:29:48.563 MediaLiveStream[15409:883145] invalidateRenderBuffer
ijkmp_prepare_async()
2016-12-22 10:29:48.563 MediaLiveStream[15409:892700] IJKSDLGLView: setupDisplay not ready
ijkmp_prepare_async()=0
2016-12-22 10:29:48.568 MediaLiveStream[15409:883145] invalidateRenderBuffer
2016-12-22 10:29:48.569 MediaLiveStream[15409:892700] IJKSDLGLView: setupDisplay not ready
aout_open_audio()
aout_pause_audio(0)
vtbformat_init - using avcC atom of size(25), ref_frames(2)m_max_ref_frames 2 
vtbformat_init - using avcC atom of size(25), ref_frames(2)m_max_ref_frames 2 
after scale width 360 height 640 
aout_pause_audio(1)
flushed last keyframe pts 0 
2016-12-22 10:29:49.700 MediaLiveStream[15409:883145] FFP_MSG_VIDEO_DECODER_OPEN: true
ijkmp_get_msg: FFP_MSG_PREPARED
2016-12-22 10:29:49.734 MediaLiveStream[15409:883145] FFP_MSG_VIDEO_SIZE_CHANGED: 360, 640
2016-12-22 10:29:49.734 MediaLiveStream[15409:883145] FFP_MSG_SAR_CHANGED: 0, 1
2016-12-22 10:29:49.735 MediaLiveStream[15409:883145] FFP_MSG_PREPARED:
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
2016-12-22 10:29:49.735 MediaLiveStream[15409:883145] fps in meta 20.000000
ijkmp_set_playback_rate(1.000000)
ijkmp_set_playback_rate()=void
ijkmp_set_playback_volume(1.000000)
ijkmp_set_playback_volume()=void
ijkmp_start()
ijkmp_start()=0
ijkmp_get_msg: FFP_REQ_START
aout_pause_audio(0)
aout_close_audio()
aout_set_volume()
ijkmp_get_msg: FFP_REQ_START
aout_pause_audio(0)
vtbformat_init - using avcC atom of size(25), ref_frames(2)m_max_ref_frames 2 
after scale width 360 height 640 
SDL_VoutVideoToolBox_CreateOverlay(w=360, h=640, fmt=_VTB, dp=0x7ff740e43690)
Video: first frame decoded
2016-12-22 10:29:49.857 MediaLiveStream[15409:883145] FFP_MSG_VIDEO_SIZE_CHANGED: 360, 640
[GLES2] Version = OpenGL ES 2.0 APPLE-12.0.41
[GLES2] Vendor = Apple Inc.
[GLES2] Renderer = Apple Software Renderer
[GLES2] Extensions = GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_vertex_array_object GL_EXT_blend_minmax GL_EXT_color_buffer_half_float GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_draw_instanced GL_EXT_instanced_arrays GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_pvrtc_sRGB GL_EXT_read_format_bgra GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_texture_lod GL_EXT_shadow_samplers GL_EXT_sRGB GL_EXT_texture_filter_anisotropic GL_EXT_texture_rg GL_EXT_texture_storage GL_APPLE_clip_distance GL_APPLE_color_buffer_packed_float GL_APPLE_copy_texture_levels GL_APPLE_framebuffer_multisample GL_APPLE_rgb_422 GL_APPLE_sync GL_APPLE_texture_format_BGRA8888 GL_APPLE_texture_max_level GL_APPLE_texture_packed_float GL_IMG_read_format GL_IMG_texture_compression_pvrtc 
create render yuv420sp_vtb
use render yuv420sp_vtb
2016-12-22 10:29:49.860 MediaLiveStream[15409:896844] IJKSDLGLView: renderbufferStorage fromDrawable
2016-12-22 10:29:49.865 MediaLiveStream[15409:883145] FFP_MSG_VIDEO_SIZE_CHANGED: 360, 640
IJK_GLES2_Renderer_TexCoords_cropRight
avcodec/Audio: first frame decoded
2016-12-22 10:29:49.921 MediaLiveStream[15409:883145] FFP_MSG_AUDIO_RENDERING_START:
SDL_VoutVideoToolBox_CreateOverlay(w=360, h=640, fmt=_VTB, dp=0x7ff740e43690)
2016-12-22 10:29:50.257 MediaLiveStream[15409:883145] FFP_MSG_VIDEO_RENDERING_START:
SDL_VoutVideoToolBox_CreateOverlay(w=360, h=640, fmt=_VTB, dp=0x7ff740e43690)
2016-12-22 10:29:50.257 MediaLiveStream[15409:883145] FFP_MSG_VIDEO_SIZE_CHANGED: 360, 640
2016-12-22 10:29:57.774 MediaLiveStream[15409:883145] -[__NSCFConstantString size]: unrecognized selector sent to instance 0x10f6c71f8
2016-12-22 10:29:57.794 MediaLiveStream[15409:883145] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString size]: unrecognized selector sent to instance 0x10f6c71f8'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000113a4ad85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001134bedeb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000113a53d3d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x0000000113999cfa ___forwarding___ + 970
	4   CoreFoundation                      0x00000001139998a8 _CF_forwarding_prep_0 + 120
	5   UIKit                               0x0000000111156400 -[UIImageView _updateImageViewForOldImage:newImage:] + 585
	6   UIKit                               0x0000000111151f34 -[UIImageView setImage:] + 379
	7   UIKit                               0x00000001112f768a -[UIButton _updateImageView] + 174
	8   UIKit                               0x00000001112f81c2 -[UIButton layoutSubviews] + 235
	9   UIKit                               0x0000000110ffe980 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 703
	10  QuartzCore                          0x0000000110cb5c00 -[CALayer layoutSublayers] + 146
	11  QuartzCore                          0x0000000110caa08e _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
	12  QuartzCore                          0x0000000110ca9f0c _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
	13  QuartzCore                          0x0000000110c9e3c9 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 277
	14  QuartzCore                          0x0000000110ccc086 _ZN2CA11Transaction6commitEv + 486
	15  QuartzCore                          0x0000000110ccc7f8 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 92
	16  CoreFoundation                      0x000000011396fc37 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	17  CoreFoundation                      0x000000011396fba7 __CFRunLoopDoObservers + 391
	18  CoreFoundation                      0x00000001139657fb __CFRunLoopRun + 1147
	19  CoreFoundation                      0x00000001139650f8 CFRunLoopRunSpecific + 488
	20  GraphicsServices                    0x0000000115e81ad2 GSEventRunModal + 161
	21  UIKit                               0x0000000110f43f09 UIApplicationMain + 171
	22  MediaLiveStream                     0x000000010f2ee84f main + 111
	23  libdyld.dylib                       0x000000011479f92d start + 1
	24  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

当我调用shutdown的时候偶发

**Comment by xinzhengzhang** [comment]
-[__NSCFConstantString size]: unrecognized selector sent to instance
Not ijk issue

**Comment by bluedaquiri** [comment]
I'm so sorry, I fixed it. It's my issue
