### ISSUE TITLE
视频自动播放功能。

### ISSUE THREAD

**Issue by asawalker** [Bilibili/ijkplayer#248]
VideoView 设置setVideoPath() 后，会自动播放，请问下，怎么去掉此功能，看上层源码，貌似无法解决，需要底层去修改，请问在底层的哪个文件中做修改？谢谢

**Comment by ctiao** [comment]
https://github.com/Bilibili/ijkplayer/commit/942250d1e165a994b5ff536de3cf4d7128ae64fc

**Comment by xqq** [comment]
建议直接用 IjkMediaPlayer。VideoView 只是一个 demo 且没有完整提供前者的接口
对 IjkMediaPlayer 调用 setAutoPlayOnPrepared(false) 关闭自动播放

**Comment by asawalker** [comment]
@ctiao @xqq 非常感谢你们的回答！

**Comment by asawalker** [comment]
@xqq 我调用了setAutoPlayOnPrepared(false) 报错了java.lang.UnsatisfiedLinkError: Native method not found: tv.danmaku.ijk.media.player.IjkMediaPlayer._setAutoPlayOnPrepared:(Z)V
我看了下kmedia/ijkplayer/android/ijkplayer_jni.c 是有IjkMediaPlayer_setAutoPlayOnPrepared(JNIEnv *env, jobject thiz, jboolean enabled)这个函数的。

**Comment by asawalker** [comment]
难道是编译的问题？

**Comment by xqq** [comment]
clean 后重编译呢……确定是最新的代码么

**Comment by asawalker** [comment]
@xqq  我重新拉了代码，并编译。还是报错：java.lang.UnsatisfiedLinkError: Native method not found: tv.danmaku.ijk.media.player.IjkMediaPlayer._setAutoPlayOnPrepared:(Z)V

**Comment by asawalker** [comment]
难道是上层代码中我调用setAutoPlayOnPrepared()函数的地方不对吗？ 我是在这个地方加的
 ijkMediaPlayer = new IjkMediaPlayer();
                ijkMediaPlayer.setAvOption(AvFormatOption_HttpDetectRangeSupport.Disable);
                ijkMediaPlayer.setOverlayFormat(AvFourCC.SDL_FCC_RV32);

                ijkMediaPlayer.setAvCodecOption("skip_loop_filter", "48");
                ijkMediaPlayer.setFrameDrop(12);
                ijkMediaPlayer.setAutoPlayOnPrepared(false);

**Comment by bbcallen** [comment]
请把你在编译时控制台上完整的步骤和显示的信息复制贴过来 (除了FFmpeg编译的信息以外)。
并尽可能加上 git status 来显示代码库的状态。

**Comment by asawalker** [comment]
root@iZ25clgt798Z:~/player/mediaplayer# git clone https://github.com/bbcallen/ijkplayer.git
Cloning into 'ijkplayer'...
remote: Counting objects: 9102, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 9102 (delta 1), reused 0 (delta 0), pack-reused 9098
Receiving objects: 100% (9102/9102), 3.94 MiB | 1.51 MiB/s, done.
Resolving deltas: 100% (5576/5576), done.
Checking connectivity... done.

root@iZ25clgt798Z:~/player/mediaplayer/ijkplayer# sh init-android.sh
== pull ffmpeg base ==
Cloning into 'extra/ffmpeg'...
remote: Counting objects: 424288, done.
remote: Compressing objects: 100% (88492/88492), done.
remote: Total 424288 (delta 336982), reused 422314 (delta 335081)
Receiving objects: 100% (424288/424288), 100.58 MiB | 218.00 KiB/s, done.
Resolving deltas: 100% (336982/336982), done.
Checking connectivity... done.
== pull ffmpeg fork armv7a ==
Cloning into 'android/ffmpeg-armv7a'...
remote: Counting objects: 5438, done.
remote: Compressing objects: 100% (230/230), done.
remote: Total 5438 (delta 751), reused 623 (delta 623), pack-reused 4585
Receiving objects: 100% (5438/5438), 8.34 MiB | 1.23 MiB/s, done.
Resolving deltas: 100% (3196/3196), done.
Checking connectivity... done.
Counting objects: 421796, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (88539/88539), done.
Writing objects: 100% (421796/421796), done.
Total 421796 (delta 333525), reused 420394 (delta 332353)
Branch ijk-r0.2.1-dev set up to track remote branch ijk-r0.2.1-dev from origin.
Switched to a new branch 'ijk-r0.2.1-dev'
/root/player/mediaplayer/ijkplayer
== pull ffmpeg fork armv5 ==
Cloning into 'android/ffmpeg-armv5'...
remote: Counting objects: 5438, done.
remote: Compressing objects: 100% (230/230), done.
remote: Total 5438 (delta 751), reused 623 (delta 623), pack-reused 4585
Receiving objects: 100% (5438/5438), 8.34 MiB | 2.84 MiB/s, done.
Resolving deltas: 100% (3196/3196), done.
Checking connectivity... done.
Counting objects: 421796, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (88539/88539), done.
Writing objects: 100% (421796/421796), done.
Total 421796 (delta 333525), reused 420394 (delta 332353)
Branch ijk-r0.2.1-dev set up to track remote branch ijk-r0.2.1-dev from origin.
Switched to a new branch 'ijk-r0.2.1-dev'
/root/player/mediaplayer/ijkplayer
== pull ffmpeg fork x86 ==
Cloning into 'android/ffmpeg-x86'...
remote: Counting objects: 5438, done.
remote: Compressing objects: 100% (230/230), done.
remote: Total 5438 (delta 751), reused 623 (delta 623), pack-reused 4585
Receiving objects: 100% (5438/5438), 8.34 MiB | 1.57 MiB/s, done.
Resolving deltas: 100% (3196/3196), done.
Checking connectivity... done.
Counting objects: 421796, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (88539/88539), done.
Writing objects: 100% (421796/421796), done.
Total 421796 (delta 333525), reused 420394 (delta 332353)
Branch ijk-r0.2.1-dev set up to track remote branch ijk-r0.2.1-dev from origin.
Switched to a new branch 'ijk-r0.2.1-dev'
/root/player/mediaplayer/ijkplayer
== pull ffmpeg fork arm64-v8a ==
Cloning into 'android/ffmpeg-arm64-v8a'...
remote: Counting objects: 5438, done.
remote: Compressing objects: 100% (230/230), done.
remote: Total 5438 (delta 751), reused 623 (delta 623), pack-reused 4585
Receiving objects: 100% (5438/5438), 8.34 MiB | 2.28 MiB/s, done.
Resolving deltas: 100% (3196/3196), done.
Checking connectivity... done.
Counting objects: 421796, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (88539/88539), done.
Writing objects: 100% (421796/421796), done.
Total 421796 (delta 333525), reused 420394 (delta 332353)
Branch ijk-r0.2.1-dev set up to track remote branch ijk-r0.2.1-dev from origin.
Switched to a new branch 'ijk-r0.2.1-dev'
/root/player/mediaplayer/ijkplayer
== pull libyuv base ==
Cloning into 'extra/libyuv'...
remote: Counting objects: 10978, done.
remote: Compressing objects: 100% (1629/1629), done.
remote: Total 10978 (delta 9334), reused 10978 (delta 9334), pack-reused 0
Receiving objects: 100% (10978/10978), 2.06 MiB | 688.00 KiB/s, done.
Resolving deltas: 100% (9334/9334), done.
Checking connectivity... done.
== pull libyuv fork ==
Cloning into 'ijkmedia/ijkyuv'...
Checking connectivity... done.
Counting objects: 10978, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (1629/1629), done.
Writing objects: 100% (10978/10978), done.
Total 10978 (delta 9334), reused 10978 (delta 9334)
Branch ijk-r0.2.1-dev set up to track remote branch ijk-r0.2.1-dev from origin.
Switched to a new branch 'ijk-r0.2.1-dev'
/root/player/mediaplayer/ijkplayer

root@iZ25clgt798Z:~/player/mediaplayer/ijkplayer/android# sh compile-ffmpeg.sh

/root/player/mediaplayer/ijkplayer/android/ijkmediaplayer/jni/ijkmedia/ijkyuv/source/convert.cc: In function 'int libyuv::RAWToI420(const uint8*, int, uint8*, int, uint8*, int, uint8*, int, int, int)':
/root/player/mediaplayer/ijkplayer/android/ijkmediaplayer/jni/ijkmedia/ijkyuv/source/convert.cc:1086:21: warning: unused variable 'row' [-Wunused-variable]
     align_buffer_64(row, kRowSize * 2);
                     ^
/root/player/mediaplayer/ijkplayer/android/ijkmediaplayer/jni/ijkmedia/ijkyuv/include/libyuv/row.h:28:10: note: in definition of macro 'align_buffer_64'
   uint8* var = reinterpret_cast<uint8*>                                        \
          ^
[armeabi-v7a] Compile++ thumb: yuv_static <= convert_argb.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= convert_from.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= convert_from_argb.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= convert_to_argb.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= convert_to_i420.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= cpu_id.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= format_conversion.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= planar_functions.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= rotate.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= rotate_argb.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= rotate_mips.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= row_any.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= row_common.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= row_mips.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= row_posix.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= scale.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= scale_argb.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= scale_common.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= scale_mips.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= scale_posix.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= video_common.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= compare_neon.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= rotate_neon.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= row_neon.cc
[armeabi-v7a] Compile++ thumb: yuv_static <= scale_neon.cc
[armeabi-v7a] StaticLibrary  : libyuv_static.a
[armeabi-v7a] StaticLibrary  : libstdc++.a
[armeabi-v7a] SharedLibrary  : libijksdl.so
[armeabi-v7a] SharedLibrary  : libijkplayer.so
[armeabi-v7a] Install        : libijkplayer.so => libs/armeabi-v7a/libijkplayer.so
[armeabi-v7a] Install        : libijksdl.so => libs/armeabi-v7a/libijksdl.so
[armeabi-v7a] Install        : libijkutil.so => libs/armeabi-v7a/libijkutil.so
/root/player/mediaplayer/ijkplayer/android

编译完成，libs 目录下，生成 .so动态库

**Comment by asawalker** [comment]
@bbcallen 麻烦看下，谢谢

**Comment by bbcallen** [comment]
现在地址是 https://github.com/Bilibili/ijkplayer.git

**Comment by asawalker** [comment]
@bbcallen , 我拉了 https://github.com/Bilibili/ijkplayer.git的代码，编译了，是OK的，非常感谢！！！

**Comment by allforyou2016** [comment]
这个方法setAutoPlayOnPrepared在0.8.8版本是不是已经去掉了，那该怎么设置呢？

**Comment by mminng** [comment]
> 这个方法setAutoPlayOnPrepared在0.8.8版本是不是已经去掉了，那该怎么设置呢？

找到方法了 setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "start-on-prepared", 0)
