### ISSUE TITLE
 [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0

### ISSUE THREAD

**Issue by owenstar** [Bilibili/ijkplayer#2482]
为什么播放MP4或者m3u8视频一直打印 AQDefaultDevice (173): skipping input stream 0 0 0x0，shutdown后也一直打印？应该怎么取消打印？快要发版本了，求大神帮忙？ijk0.7.5版本

**Comment by owenstar** [comment]
xcode8 与 ios10的bug

**Comment by momo13014** [comment]
@owenstar 这个问题你解决了吗？我也遇到这样的问题

**Comment by MingLoan** [comment]
I have this issue too
