### ISSUE TITLE
Android RTSP直播停止问题

### ISSUE THREAD

**Issue by Harryuan** [Bilibili/ijkplayer#2484]
直播有时可以播很长时间，有时很短就停在那个画面了，如果另外一台手机也连接该RTSP服务器时，就更容易发生直播停止情况。停止的Android log显示如下：
I/IJKMEDIA: ffp_toggle_buffering: completed: OK
D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_COMPLETED
D/IJKMEDIA: FFP_MSG_COMPLETED:

这是什么意思？正常停止吗？
是否有让直播不停止的方法？多谢！

**Comment by xinzhengzhang** [comment]
EOF received

**Comment by KrisRoofe** [comment]
这可能是网络的问题，推流不稳定，经常中断造成的。

**Comment by aouyu** [comment]
我也遇到和你一样的问题，播放一会儿停止了。log完全一致。搜索了一些方法修改源码重编了so文件仍然有这个问题存在。应该不是楼上说的网络问题。VLC播放器播放同样的RTSP可以播很久。还没解决...
