### ISSUE TITLE
Where shoud I set setAvFormatOption

### ISSUE THREAD

**Issue by wisien92** [Bilibili/ijkplayer#2485]
Hi, 

I am trying out the lib for RTSP playback. I have build and added RTSP support, but now I want to test some flags.

https://www.ffmpeg.org/ffmpeg-protocols.html#rtsp

These should be set via code using  AVOptions or avformat. I have seen issues that people set them using setAvFormatOption in widget/media/IjkVideoView - but ijkMediaPlayer does not have this function defined.

 Question is how should I set those flags and where?

**Comment by xinzhengzhang** [comment]
`setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "key", value);`

**Comment by wisien92** [comment]
thanks
