### ISSUE TITLE
Use ffmpeg to merge several parts into one video

### ISSUE THREAD

**Issue by CoXier** [Bilibili/ijkplayer#2489]
Here,I have succeeded in extracting video urls from www.youku.com. However I get several segment parts of one video.

## For example :
 A original url: http://v.youku.com/v_show/id_XMTg3NzIyMTQ0NA==.html?spm=a2hjl.20010157.m_89771.5~5!2~5~5~5~5~5~5!2~A&from=y1.3-jilupian-shouye-2867-10157.89797-89771.1-1

After parsering,I get:
- http://k.youku.com/player/getFlvPath/sid/9482553601463125317f8_00/st/flv/fileid/0300020300585B5B84AE8B086AC2AE8C32B3FC-325C-73AA-0901-9F0EBC4A6DA0?ypp=0&myp=0&K=a78a50ef79afbde2261f6b5e&ctype=12&token=4119&ev=1&ep=eyacGEyIVcgA5CfZiz8bYi%2FjcyEHXP4J9h%2BFg9JhALshQO3NnEzZw%2BzFRo1CHv9oASB3ZeOCqNKVaTZnYfNBrBsQ2E3ZSPrg9%2FDi5aQlxOVyFR1HdLmmtFSaQjH4&hd=0&oip=1078436452
- http://k.youku.com/player/getFlvPath/sid/9482553601463125317f8_00/st/flv/fileid/0300020301585B5B84AE8B086AC2AE8C32B3FC-325C-73AA-0901-9F0EBC4A6DA0?ypp=0&myp=0&K=d2ec471631de5bdc282bfcb7&ctype=12&token=4119&ev=1&ep=eyacGEyIVcgA5CfZiz8bYi%2FjcyEHXP4J9h%2BFg9JhALohQO3NnEzZw%2BzFRo1CHv9oASB3ZeOCqNKVaTZnYfNBrBsQ2E3ZSPrg9%2FDi5aQlxOVyFR1HdLmmtFSaQjH4&hd=0&oip=1078436452

- .....

## My question
How can I play one video with several urls?

Thanks

**Comment by xinzhengzhang** [comment]
See `concat` protocol in https://ffmpeg.org/ffmpeg-protocols.html#toc-concat
