### ISSUE TITLE
[ios] BufferingTime及快放问题

### ISSUE THREAD

**Issue by Brace** [Bilibili/ijkplayer#249]
关于iOS版本中的两个问题请教

1. 有看到IJKFFMoviePlayerController.m中的_bufferingPosition与_bufferingProgress，不太明白​​_bufferingProgress的意思，可否将其转换成delay秒数(float)？

2. 如果想要实现快放的功能，可否给予实作的参考？

非常感谢！

**Comment by bbcallen** [comment]
1.
_bufferingPosition 相当于 playableDuraition = currentPosition + 缓冲区数据的微秒数，用来显示进度条下面的缓冲条。
_bufferingProgress 通常从 0~100，缓冲区填充的字节百分比，如果因为网速不够快，停下来缓冲的时候，缓冲到100%时恢复播放，这个时候可以用来显示缓冲进度。播放时，缓冲也在进行，所以可以超过100

2. 暂时没考虑如何实现快放。

**Comment by Brace** [comment]
目前是以播放rtmp streaming为来源，因此PlayableDuration都是-1或是0，

不过bufferProgress仍会有数值，且也会随着播放暂停而持续长大

请问这样的话还有办法取得缓冲秒数吗？

**Comment by bbcallen** [comment]
没有简单的办法。

**Comment by bbcallen** [comment]
Feature added
