### ISSUE TITLE
为什么iOS版没有FFP_MSG_VIDEO_SIZE_CHANGED通知给上层？

### ISSUE THREAD

**Issue by walkermi** [Bilibili/ijkplayer#250]
为什么iOS版没有FFP_MSG_VIDEO_SIZE_CHANGED通知给上层？

这是出于什么考虑？iOS版有其他方法获得播放源的视频尺寸吗？

@bbcallen

**Comment by bbcallen** [comment]
因为 MPMoviePlayerViewController 也没有啊，如果需要你可以自己在 IJKFFMoviePlayerController 上加接口。

**Comment by bbcallen** [comment]
收回，MPMoviePlayerController 有个 naturalSize 看起来像是干这个的。

**Comment by walkermi** [comment]
没有这个接口，按iOS的demo，播放的视频比例不正确，有什么办法在打开后能获取到视频尺寸？@bbcallen

**Comment by walkermi** [comment]
只能类似android版一样，添加这个notifIcation吗？尺寸的参数如何传出来呢？

**Comment by walkermi** [comment]
没看到MPMoviePlayerController 有个 naturalSize 方法啊？是哪个branch？怎么用？

**Comment by bbcallen** [comment]
是系统的 MPMoviePlayerController，不是 IJKMPMoviePlayerController，你急着用的话，可以自己先改一个。

**Comment by walkermi** [comment]
系统的 MPMoviePlayerController不支持rtmp和hls的播放吧？目前只能选择自己修改 IJKFFMoviePlayerController ，类似Android版一样将FFP_MSG_VIDEO_SIZE_CHANGED通知传出来吗？

**Comment by bbcallen** [comment]
是的。
