### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by Simion777** [Bilibili/ijkplayer#251]
I don't know how resolve this error:

05-28 11:09:18.002  14844-21906/com.example.myproject.myproject E/IJKMEDIA﹕ Failed to open file '/storage/emulated/0/Android/data/........./1.mp4' or configure filtergraph

I

**Comment by bbcallen** [comment]
I don't know, too...

More information, please.

**Comment by Simion777** [comment]
I have more video in my assets project,  .mp4. Videos with different resolution. It doesn't open Video with width:432 and height:320 and  appear an  Alert Dialog with message "Cannot play video, Sorry, this video cannot be played"
Logcat:
05-28 11:09:18.002 14844-21906/com.example.myproject.myproject E/IJKMEDIA﹕ Failed to open file '/storage/emulated/0/Android/data/........./1.mp4' or configure filtergraph

**Comment by Simion777** [comment]
Sorry for my english

**Comment by bbcallen** [comment]
I don't think 'storage/emulated/0/Android/data/........./1.mp4' is valid file path.

**Comment by Simion777** [comment]
Failed to open file '/storage/emulated/0/Android/data/com.example.nemo.bodibuilding/BodyBuilding/1.mp4' or configure filtergraph 
this is my real path. It works fine with resolution bigger than width:432 and height:320.

**Comment by bbcallen** [comment]
Are you access this file from another package or from same package ?

**Comment by Simion777** [comment]
If you have time test this video in your player
https://www.dropbox.com/s/tf5cd09984f7hfz/1.mp4?dl=0  
this video doesn't work,
and this video work  
https://www.dropbox.com/s/9hfwi5jma6zmc5g/3.mp4?dl=0

**Comment by bbcallen** [comment]
Stream #0:0(eng), 1, 1/15360: Video: mpeg4 (mp4v / 0x7634706D), none, 432x320, 518 kb/s, SAR 800:1917 DAR 40:71, 15 fps, 15 tbr, 15360 tbn, 15360 tbc (default)

The video codec is mpv4, which is disabled by default,

You need to:
```
cd config
rm module.sh
ln -s module-default.sh module.sh
cd android
sh compile-ffmpeg clean
sh compiel-ffmpeg
```

**Comment by Simion777** [comment]
Thank's man. Working, fine player, and tell me in this player exist method setlooping, i don't find it

**Comment by bbcallen** [comment]
Not supported, yet.
