### ISSUE TITLE
iOS h265

### ISSUE THREAD

**Issue by PengBoShi** [Bilibili/ijkplayer#2517]
请问一下 iOS 硬解码支持h265吗 是videotoolbox不支持 还是iOS设备硬件不支持呢

**Comment by xinzhengzhang** [comment]
Neither support

**Comment by dourgulf** [comment]
哈哈，都不支持：）

**Comment by xinzhengzhang** [comment]
Reference to some website it seems that h265 has been integrated in some device like ip6+
Although [kcmvideocodectype_hevc](https://developer.apple.com/reference/coremedia/kcmvideocodectype_hevc]) first appeared in ios9 but apple has never declared that hevc has been supported and I also tried it.
@dourgulf  I would appreciate you if there is something magic about h265 to share.

**Comment by PengBoShi** [comment]
thanks

**Comment by dourgulf** [comment]
是的，之前看过简书的一个文章iOS有HEVC的相关宏，但是，实际调用都没有效果
