### ISSUE TITLE
Are there some pre-compiled codes in Android JAR ?

### ISSUE THREAD

**Issue by jpxiong** [Bilibili/ijkplayer#252]
I have noticed that there are x86/classes.jar and armeabi-v7a/classes.jar after build the java layer code, so what's the difference between x86/classes.jar and armeabi-v7a/classes.jar ?

**Comment by bbcallen** [comment]
x86 is build for intel atom SoC, armeabi-v7a is build for armv7a SoC, which is used by most android phone.

Read NDK document for more detail.

**Comment by jpxiong** [comment]
I understand the shared library. I mean the jar.

**Comment by bbcallen** [comment]
No difference. They can be merged in to a single jar.

**Comment by jpxiong** [comment]
Thanks for your great help!
