### ISSUE TITLE
解压能否支持 speex 格式的音频

### ISSUE THREAD

**Issue by erwinshao** [Bilibili/ijkplayer#253]
hi，bbcallen，现在准备用 ijkplay 来播放 flv 的直播流，但音频是 speex 格式的。ffmpeg 的是有这个 flag 的，编译好 speex 后，编译 ffmpeg 一直报找不到 speex 库，去掉了configure中的enabled libspeex          && require_pkg_config speex speex/speex.h speex_decoder_init -lspeex，在do-compile-ffmpeg.sh 的link ffmpeg中显性的 link speex 库，链接报错。能否提供一下 ffmpeg 扩展外部编码库的编译脚本的例子。多谢。

**Comment by bbcallen** [comment]
参考 openssl 的编译配置。
