### ISSUE TITLE
請問支持Motion JPEG over HTTP 流播放嗎?

### ISSUE THREAD

**Issue by Adatan** [Bilibili/ijkplayer#254]
先感謝提供了這麼好的項目

現有播放Motion JPEG over HTTP流的需求，請問有支持嗎?

**Comment by bbcallen** [comment]
默认配置只开启了很少一部分格式，所以肯定不支持。
如果ffplay本身支持的话，手动修改 config 下的配置可以支持。

**Comment by Adatan** [comment]
修改config後已解決，感謝!
