### ISSUE TITLE
android 硬件加速 mpeg4 格式，播放无图像，有声音

### ISSUE THREAD

**Issue by peterhuang007** [Bilibili/ijkplayer#2541]
在 ff_ffplay_options.h  开启 { "mediacodec-mpeg4",                       "MediaCodec: enable MPEG4",
        OPTION_OFFSET(mediacodec_mpeg4),        OPTION_INT(1, 0, 1) },使用ijkplay-example 用例播放mpeg4 格式的视频，无图像，有声音，
1.使用的版本 git checkout -B latest k0.7.5

**Comment by xinzhengzhang** [comment]
ffprobe your video stream and paste the output

**Comment by peterhuang007** [comment]
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'A1.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf57.40.101
  Duration: 00:00:02.84, start: 0.000000, bitrate: 724 kb/s
    Stream #0:0(und): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 480x640 [SAR 1:1 DAR 3:4], 601 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 30k tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(zho): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 126 kb/s (default)
    Metadata:
      handler_name    : SoundHandler

**Comment by peterhuang007** [comment]
@xinzhengzhang

**Comment by xinzhengzhang** [comment]
add `-enable-decoder=mpeg4`

**Comment by peterhuang007** [comment]
@xinzhengzhang  
编译已经配置 --enable-decoders（这个是软件解码的应该和硬件解码没关系吧）   已经开启所有的解码器了，在编译日志里也出现了 Enabled decoders:	mpeg4

**Comment by peterhuang007** [comment]
@xinzhengzhang
[A1.mp4.zip](https://github.com/Bilibili/ijkplayer/files/686576/A1.mp4.zip)

**Comment by raymond1012** [comment]
不是所有的机器都支持mpeg4的硬解，请直接使用软解。

**Comment by yuazhen** [comment]
not all mpeg4 is supported by MediaCodec. please see #1875

**Comment by bruceshu** [comment]
@peterhuang007 你好，我这边也遇到相同问题，mpeg4编码的视频硬解，画面花屏，软解正常。但是在相同的机器上，用系统自带的mediaplayer硬解，就能正常播放。请问这个问题你解决了吗？

**Comment by Lee-Jian** [comment]
@bruceshu 你好 mpeg4编码的视频硬解，画面花屏，软解正常 这个问题解决了吗

**Comment by JohnDwang** [comment]
只有声音没有画面 如何处理

**Comment by JohnDwang** [comment]
mp4格式的

**Comment by bruceshu** [comment]
@Lee-Jian 我的问题解决了，mpeg4硬解跟芯片有关，建议你用软解

**Comment by linjiansheng** [comment]
amlogic 芯片 低版本基本不支持 mpeg4 硬解码
