### ISSUE TITLE
使用ijkplayer有没有定制好的UI？

### ISSUE THREAD

**Issue by MangoSeries** [Bilibili/ijkplayer#2549]
如题，有没有定制好的UI，还是说都得自己自定义播放的界面？
感谢！

**Comment by xinzhengzhang** [comment]
DEMO

**Comment by MangoSeries** [comment]
@xinzhengzhang 我就是看了DEMO发现UI非常简陋，难道是我找错地方了？不就是IJKMediaDemo这个吗

**Comment by xinzhengzhang** [comment]
Then implement your own

**Comment by MangoSeries** [comment]
@xinzhengzhang 知道了，谢谢！
