### ISSUE TITLE
Version K0.7.6 iOS complier Error

### ISSUE THREAD

**Issue by SkyWalkeer** [Bilibili/ijkplayer#2558]
剛剛抓下新版本(k0.7.6), 下來編譯, 利用./compile-ffmpeg.sh all 成功後,
開啟專案 IJKMediaDemo 執行會出現以下 Error Message

duplicate symbol _validate_avcC_spc in:

/Users/Administrator/Library/Developer/Xcode/DerivedData/IJKMediaDemo-einubmkawjcavogsoynxsvfiooud/Build/Products/Debug-iphonesimulator/IJKMediaFramework.framework/IJKMediaFramework(IJKVideoToolBoxAsync.o)
    
/Users/Administrator/Library/Developer/Xcode/DerivedData/IJKMediaDemo-einubmkawjcavogsoynxsvfiooud/Build/Products/Debug-iphonesimulator/IJKMediaFramework.framework/IJKMediaFramework(IJKVideoToolBoxSync.o)

ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

請問如何解決？謝謝.

**Comment by xinzhengzhang** [comment]
What's your xcode version? Can not reproduce to me.
Try clean it.

**Comment by SkyWalkeer** [comment]
my xcode  version is 7.3.1

**Comment by xinzhengzhang** [comment]
The travis of ijkplayer is based on xcode 7.1 and it was built successfully.
My develop environment is xcode 8.2.1 and also it was built successfully .

**Comment by SkyWalkeer** [comment]
ok~~thanks for your help.

**Comment by arun542** [comment]
Hey i am getting the same error, if i remove JKMediaFramework.framework from Link Binary with libraries then this error goes away

**Comment by xinzhengzhang** [comment]
https://github.com/Bilibili/ijkplayer/commit/3cf3fd4b7b11f53acde7910715dbb7ad3ed5cfa7
