### ISSUE TITLE
硬件解码初始化失败，但如果页面跳转在恢复到播放页面硬件解码是可以的

### ISSUE THREAD

**Issue by 10045125** [Bilibili/ijkplayer#256]
![image](https://cloud.githubusercontent.com/assets/2945098/7912619/ba7831de-089b-11e5-8483-7adfd0db0a60.png)
这个是暂停的log
![image](https://cloud.githubusercontent.com/assets/2945098/7912637/ea874630-089b-11e5-96a5-c0a2175dd16c.png)
 如果这个时候从一个Activity的页面回到播放器页面，硬件解码显示是成功的，log为
06-01 20:22:45.935: W/IJKMEDIA(31391): SDL_AMediaCodecJava_start
06-01 20:22:45.935: I/ACodec(31391): [OMX.Exynos.avc.dec] Now Loaded->Idle
06-01 20:22:45.935: E/Parcel(31391): nm 96
06-01 20:22:45.950: E/Parcel(31391): nm 96
06-01 20:22:45.955: I/IJKMEDIA(31391): VideoCodec: MediaCodec, OMX.Exynos.avc.dec
06-01 20:22:45.955: I/IJKMEDIA(31391): fps: 30.303030 (normal)
06-01 20:22:45.955: I/IJKMEDIA(31391): fps: 30.000000 (normal)
06-01 20:22:45.955: I/IJKMEDIA(31391): SDL_RunThread: [469] ff_video_dec
06-01 20:22:45.955: W/IJKMEDIA(31391): ijkmp_get_msg: FFP_MSG_PREPARED
06-01 20:22:45.955: W/IJKMEDIA(31391): FFP_MSG_PREPARED:
06-01 20:22:45.955: W/IJKMEDIA(31391): FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
06-01 20:22:45.955: W/IJKMEDIA(31391): FFP_MSG_SAR_CHANGED: 1, 1
06-01 20:22:45.955: I/IJKMEDIA(31391): SDL_RunThread: [470] amediacodec_input_thread
06-01 20:22:45.980: I/ACodec(31391): [OMX.Exynos.avc.dec] Now Idle->Executing
06-01 20:22:45.980: D/tv.danmaku.ijk.media.widget.VideoView(31391): onPrepared
06-01 20:22:45.980: W/IJKMEDIA(31391): IjkMediaPlayer_start
06-01 20:22:45.980: W/IJKMEDIA(31391): ijkmp_start()
06-01 20:22:45.980: W/IJKMEDIA(31391): ijkmp_start()=0
06-01 20:22:45.980: W/IJKMEDIA(31391): ijkmp_get_msg: FFP_REQ_START
06-01 20:22:45.980: D/IJKMEDIA(31391): ijkmp_get_msg: FFP_REQ_START: start on fly
06-01 20:22:45.980: D/tv.danmaku.ijk.media.widget.VideoView(31391): onVideoSizeChanged: (1280x720)
06-01 20:22:45.980: I/ACodec(31391): [OMX.Exynos.avc.dec] Now Executing
06-01 20:22:45.980: D/tv.danmaku.ijk.media.widget.VideoView(31391): onVideoSizeChanged: (1280x720)
06-01 20:22:45.990: I/onScrollMax(31391): onScrollMax
06-01 20:22:45.990: E/mFrameLayoutMain Max(31391): 1
06-01 20:22:45.990: E/Max(31391): View.VISIBLE0
06-01 20:22:45.990: I/ACodec(31391): [OMX.Exynos.avc.dec] Now handling output port settings change
06-01 20:22:45.995: E/Parcel(31391): nm 96
06-01 20:22:46.010: I/ACodec(31391): [OMX.Exynos.avc.dec] Now Executing

我不确定是什么原因，在java层很少关于硬件解码的代码。希望作者回复，谢谢！

**Comment by bbcallen** [comment]
没有看懂你的调用方式，能说详细一点么？

**Comment by 10045125** [comment]
我使用IJKPlayer最新的代码进行的编译，调用的时候是在VideoView中加入了这句ijkMediaPlayer.setMediaCodecEnabled(true);

之后在播放是调用是
mFullScreenVideoView.setVideoPath(url);
		mFullScreenVideoView.requestFocus();
		mFullScreenVideoView.start();
开启硬件解码，小米4显示的log是

06-02 11:31:56.718: I/tv.danmaku.ijk.media.player.IjkMediaPlayer(17021): selected codec: OMX.qcom.video.decoder.avc rank=800
06-02 11:31:56.718: W/IJKMEDIA(17021): SDL_AMediaCodecJava_createByCodecName
06-02 11:31:56.728: I/OMXClient(17021): Using client-side OMX mux.
06-02 11:31:56.838: W/IJKMEDIA(17021): SDL_AMediaCodecJava_init
06-02 11:31:56.838: W/IJKMEDIA(17021): SDL_AMediaCodecJava_configure_surface
06-02 11:31:56.838: E/IJKMEDIA(17021): configure 0x1d2004fe 0x1d2004ee
06-02 11:31:56.848: E/MediaCodec(17021): native_window_api_connect returned an error: Invalid argument (-22)
06-02 11:31:56.848: W/System.err(17021): java.lang.IllegalStateException
06-02 11:31:56.848: W/System.err(17021): 	at android.media.MediaCodec.native_configure(Native Method)
06-02 11:31:56.848: W/System.err(17021): 	at android.media.MediaCodec.configure(MediaCodec.java:262)
06-02 11:31:56.848: W/System.err(17021): 	at dalvik.system.NativeStart.run(Native Method)
06-02 11:31:56.848: E/IJKMEDIA(17021): reconfigure_codec_l:configure_surface: failed
06-02 11:31:56.848: I/IJKMEDIA(17021): SDL_AMediaCodecJava_delete
06-02 11:31:56.858: I/IJKMEDIA(17021): VideoCodec: avcodec, h264
06-02 11:31:56.858: I/IJKMEDIA(17021): fps: 29.969876 (normal)
06-02 11:31:56.858: I/IJKMEDIA(17021): fps: 29.970030 (normal)
06-02 11:31:56.858: W/IJKMEDIA(17021): ijkmp_get_msg: FFP_MSG_PREPARED
06-02 11:31:56.858: W/IJKMEDIA(17021): FFP_MSG_PREPARED:
06-02 11:31:56.858: W/IJKMEDIA(17021): FFP_MSG_VIDEO_SIZE_CHANGED: 480, 272
06-02 11:31:56.858: W/IJKMEDIA(17021): FFP_MSG_SAR_CHANGED: 0, 1
06-02 11:31:56.858: I/IJKMEDIA(17021): SDL_RunThread: [17223] ff_video_dec
06-02 11:31:56.888: W/IJKMEDIA(17021): FFP_MSG_VIDEO_SIZE_CHANGED: 480, 272
06-02 11:31:56.888: W/IJKMEDIA(17021): SDL_VoutFFmpeg_CreateOverlay(w=480, h=272, fmt=RV32(0x32335652, dp=0x7c8a6a20)
06-02 11:31:56.888: D/tv.danmaku.ijk.media.widget.VideoView(17021): onPrepared
06-02 11:31:56.888: W/IJKMEDIA(17021): IjkMediaPlayer_start
06-02 11:31:56.888: W/IJKMEDIA(17021): ijkmp_start()
06-02 11:31:56.888: W/IJKMEDIA(17021): ijkmp_get_msg: FFP_REQ_START


但是有一个奇怪的地方是，如果此时我进行了页面跳转，也就是说从当前的Activity跳转到另一个Activity之后，回到之前的Activity。硬件解码是OK的。小米4的log：

06-02 11:36:37.728: I/tv.danmaku.ijk.media.player.IjkMediaPlayer(17021): selected codec: OMX.qcom.video.decoder.avc rank=800
06-02 11:36:37.728: W/IJKMEDIA(17021): SDL_AMediaCodecJava_createByCodecName
06-02 11:36:37.728: I/OMXClient(17021): Using client-side OMX mux.
06-02 11:36:37.908: W/IJKMEDIA(17021): SDL_AMediaCodecJava_init
06-02 11:36:37.908: W/IJKMEDIA(17021): SDL_AMediaCodecJava_configure_surface
06-02 11:36:37.908: E/IJKMEDIA(17021): configure 0x1d200522 0x1d6004ee
06-02 11:36:37.908: I/ACodec(17021): DRC Mode: Dynamic Buffer Mode
06-02 11:36:37.928: W/IJKMEDIA(17021): SDL_AMediaCodecJava_start
06-02 11:36:37.978: I/IJKMEDIA(17021): VideoCodec: MediaCodec, OMX.qcom.video.decoder.avc
06-02 11:36:37.978: I/IJKMEDIA(17021): fps: 29.969876 (normal)
06-02 11:36:37.978: I/IJKMEDIA(17021): fps: 29.970030 (normal)
06-02 11:36:37.978: W/IJKMEDIA(17021): ijkmp_get_msg: FFP_MSG_PREPARED
06-02 11:36:37.978: W/IJKMEDIA(17021): FFP_MSG_PREPARED:
06-02 11:36:37.978: W/IJKMEDIA(17021): FFP_MSG_VIDEO_SIZE_CHANGED: 480, 272
06-02 11:36:37.978: W/IJKMEDIA(17021): FFP_MSG_SAR_CHANGED: 0, 1
06-02 11:36:37.978: D/tv.danmaku.ijk.media.widget.VideoView(17021): onPrepared
06-02 11:36:37.988: W/IJKMEDIA(17021): IjkMediaPlayer_start
06-02 11:36:37.988: W/IJKMEDIA(17021): ijkmp_start()
06-02 11:36:37.988: W/IJKMEDIA(17021): ijkmp_get_msg: FFP_REQ_START
06-02 11:36:37.988: D/IJKMEDIA(17021): ijkmp_get_msg: FFP_REQ_START: start on fly
06-02 11:36:37.988: W/IJKMEDIA(17021): ijkmp_start()=0

**Comment by bbcallen** [comment]
前一份日志显示的是 "OMX.Exynos.avc.dec"，这个好像是三星的设备？
另外，我想知道默认的IjkMediaDemo是否能正常播放?
如果IjkMediaDemo正常的话，你的Activity与IjkMediaDemo有什么不同？
你的两个Activity分别做了什么，VideoView是在哪个Activity里的?

错误应该与surface的生命周期有关。

**Comment by 10045125** [comment]
Thanks,是你说的问题，我修改过来了。我为了适配横屏的视频大小修改了一小部分源码，按视频很屏幕比例进行了缩放。

具体是在
@Override
	protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
		// int width = getDefaultSize(mVideoWidth, widthMeasureSpec);
		// int height = getDefaultSize(mVideoHeight, heightMeasureSpec);
		int width = getDefaultSize(mVideoWidth, widthMeasureSpec);
		int height = getDefaultSize(mVideoHeight, heightMeasureSpec);

		if (mVideoWidth > 0 && mVideoHeight > 0) {
			if (mVideoWidth * height > width * mVideoHeight) {
				height = width * mVideoHeight / mVideoWidth;
			} else if (mVideoWidth * height < width * mVideoHeight) {
				width = height * mVideoWidth / mVideoHeight;
			}
		}
		setMeasuredDimension(width, height);
	}

之后将setVideoLayout修改为getHolder().setFixedSize(mVideoWidth, mVideoHeight);就能够适应横竖屏的适配缩放。
       再次感谢你的耐心解答，Thanks.
