### ISSUE TITLE
How to set option analyzeduration and probesize in  iOS

### ISSUE THREAD

**Issue by KCastiglione** [Bilibili/ijkplayer#257]
How to set option analyzeduration and probesize in  iOS?
This is my player

     @property(atomic, retain) id<IJKMediaPlayback> rtmpPlayer;

and initialized like this:

     self.rtmpPlayer = [[IJKFFMoviePlayerController alloc] initWithContentURL:theMovieURL withOptions:nil];

Thank you for a great library!

**Comment by bbcallen** [comment]
For master
ijkmp_set_option_int(_mediaPlayer, IJKMP_OPT_CATEGORY_FORMAT, "analyzeduration", xxxxx);
For latest tag
ijkmp_set_format_option(_mediaPlayer, "analyzeduration", "xxxxx");

**Comment by Brace** [comment]
Can explain more about setting analyzeduration and probesize in iOS?

If i want to set this like android
ijkMediaPlayer.setAvFormatOption("analyzeduration", “2000000”); 
ijkMediaPlayer.setAvFormatOption("fflags", “nobuffer”);
ijkMediaPlayer.setAvFormatOption("probsize", “4096”);

ref. https://github.com/kolyvan/kxmovie/issues/104

Thanks a lot!

**Comment by KCastiglione** [comment]
@bbcallen Thank you for reply.
Do I have to set it in ijkplayer.c and recompile the library for IJKMediaPlayer?


Is there a way to set it dynamically from iOS on this 
      @property(atomic, retain) id<IJKMediaPlayback> rtmpPlayer;


These are the built libraries that I have and there is no access to the C methods

![screen shot 2015-06-02 at 10 45 49 am](https://cloud.githubusercontent.com/assets/96905/7942698/b464f4fc-0914-11e5-8a60-5195ad4ab9d0.png)

**Comment by bbcallen** [comment]
Search ijkmp_set_option_int/ijkmp_set_format_option in IJKFFMoviePlayerController.

**Comment by walkermi** [comment]
为什么不在IJKMediaPlayback中开放这个接口对外呢？这样就接近Android的设置方法，是不是更直观？
@bbcallen

**Comment by bbcallen** [comment]
因为我还在改别的地方。。。

**Comment by bbcallen** [comment]
Fixed: ee1e34c89c7b272258a3cdbf27657641d3f63c8f

**Comment by KCastiglione** [comment]
Thank you for fixing the new OptionsConvenience Feature. Can you please give an example of how to actually set the example, I updated to the latest library, and in header file have:


      @property(atomic, retain) id<IJKMediaPlayback> player;


and in m file implementation

      self.rtmpPlayer = [[IJKFFMoviePlayerController alloc] initWithContentURL:theMovieURL withOptions:nil];



The new option setPlayerOptionValue doesn't work, it doesnt have the method. Does the header file definition need to change?

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/ee1e34c89c7b272258a3cdbf27657641d3f63c8f/ios/IJKMediaPlayer/IJKMediaPlayer/IJKFFMoviePlayerController%2BOptionConvenience.h

Try clean and build
