### ISSUE TITLE
Cygwin64 无法创建，新手不懂如何编译，百度一步步操作，但是还是有问题。

### ISSUE THREAD

**Issue by Yee1014** [bilibili/ijkplayer#2589]
pc@pc-PC /cygdrive/e/Demos/ijkplayer-master/android/contrib
$ ./compile-ffmpeg.sh armv7a
====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a arm64 x86 x86_64
FF_ACT_ARCHS = armv7a

====================
[*] check env armv7a
====================
FF_ARCH=armv7a
FF_BUILD_OPT=

--------------------
[*] make NDK standalone toolchain
--------------------
build on CYGWIN_NT-6.1 x86_64
ANDROID_NDK=D:/Tools/Android/android-sdk/ndk-bundle
IJK_NDK_REL=13.1.3345770
NDKr13.1.3345770 detected
Cygwin temp prefix=D:/Tools/cygwin64/tmp/
HOST_OS=cygwin
HOST_EXE=.exe
HOST_ARCH=x86_64
HOST_TAG=windows-x86_64
HOST_NUM_CPUS=2
BUILD_NUM_CPUS=4
Auto-config: --arch=arm
Toolchain installed to /cygdrive/e/Demos/ijkplayer-master/android/contrib/build/ffmpeg-armv7a/toolchain.
touch: 无法创建'/cygdrive/e/Demos/ijkplayer-master/android/contrib/build/ffmpeg-armv7a/toolchain/touch': No such file or directory

**Comment by yippeesoft** [comment]
还是虚拟机LINUX吧··

**Comment by lingchen52** [comment]
还是用虚拟机安装ubuntu去编译吧
