### ISSUE TITLE
buffer开始和结束事件有时候播放不会有

### ISSUE THREAD

**Issue by Android4MediaPlayer** [Bilibili/ijkplayer#259]
进行多次播放VOD节目，buffer通知事件值比较大得概率不会有通知上来

**Comment by bbcallen** [comment]
所以，你的问题是？

**Comment by Android4MediaPlayer** [comment]
加载不消失，以end来消失的

**Comment by bbcallen** [comment]
给个日志看看，我记得是保证成对通知的。

**Comment by Android4MediaPlayer** [comment]
对，成对，是有时没事件，因为我开始点击播放就显示加载，收到end才消掉

**Comment by bbcallen** [comment]
buf事件不保证一定发生。prepared之后就可以隐藏加载提示，如果你担心隐藏后立刻又出现，可以考虑做一个延时隐藏。

**Comment by GrayLuo** [comment]
播放过程中，在网络差的情况下经常收不到buffer通知（IJKMPMoviePlayerLoadStateDidChangeNotification通知），但此时画面却长时间卡在那里了，并没有播放。@bbcallen ,thx.
此时收到log:
decodeFrame -12911 kVTVideoDecoderMalfunctionErr
decodeFrame -12911 kVTVideoDecoderMalfunctionErr
decodeFrame -12911 kVTVideoDecoderMalfunctionErr
decodeFrame -12911 kVTVideoDecoderMalfunctionErr
decodeFrame -12911 kVTVideoDecoderMalfunctionErr



SDL_VoutVideoToolBox_CreateOverlay(w=640, h=480, fmt=_VTB, dp=0x191e5510)
2016-06-14 18:42:10.982 SioEyeAPP[1387:512844] FFP_MSG_VIDEO_SIZE_CHANGED: 640, 480
decodeFrame -12911 kVTVideoDecoderMalfunctionErr
decodeFrame -12911 kVTVideoDecoderMalfunctionErr
decodeFrame -12911 kVTVideoDecoderMalfunctionErr
decodeFrame -12911 kVTVideoDecoderMalfunctionErr
decodeFrame -12911 kVTVideoDecoderMalfunctionErr
decodeFrame -12911 kVTVideoDecoderMalfunctionErr
decodeFrame -12911 kVTVideoDecoderMalfunctionErr
SDL_VoutVideoToolBox_CreateOverlay(w=640, h=480, fmt=_VTB, dp=0x191e5510)
2016-06-14 18:42:37.779 SioEyeAPP[1387:512844] FFP_MSG_VIDEO_SIZE_CHANGED: 640, 480
decodeFrame -12911 kVTVideoDecoderMalfunctionErr
decodeFrame -12911 kVTVideoDecoderMalfunctionErr
decodeFrame -12911 kVTVideoDecoderMalfunctionErr
decodeFrame -12911 kVTVideoDecoderMalfunctionErr
decodeFrame -12911 kVTVideoDecoderMalfunctionErr
