### ISSUE TITLE
start rtsp only in tcp mode

### ISSUE THREAD

**Issue by tulkas85** [Bilibili/ijkplayer#26]
Hi, How can I force MediaPlayer to prepare video only using Tcp ?
Sometimes udp stream does not pass  through  3G connections

thanks

**Comment by spaul13** [comment]
@tulkas85  @bbcallen can anyone please tell me how to enable the RTSP streaming? I have a video on my server (strong desktop). I want to take that video and play it on my android phone using ijkmediaplayer.

**Comment by spaul13** [comment]
@tulkas85 I am getting an error similar to you where it's showing my buffer gets full (100%) and after that, the video streaming on android stops. It does n't go far from 100%. 

But I have noticed for your cache size is going >100 %, how you did that? and secondly how to resolve the issue where buffer gets full.

_02-14 07:56:11.320 22174-22174/? D/EasyMovieTexture: OnBufferUpdate()
02-14 07:56:11.888 22174-22174/? I/System.out: I am in Media_buffering update, msg.arg174122 and buffer position 74122
02-14 07:56:11.888 22174-22174/? E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Buffer (100%) 74122/14750_
