### ISSUE TITLE
Setting default whitelist always 'file,crypto'

### ISSUE THREAD

**Issue by CoXier** [Bilibili/ijkplayer#2601]
@xinzhengzhang 
In the example you  provided for android,I modify some code to support `concat`.First I write a string into a file called `test.ffconcat` while the string is:

```java
String concat = "ffconcat version 1.0\n" +
                    "file 'http://k.youku.com/player/getFlvPath/sid/048455411693812bdd99a_00/st/flv/fileid/030001010058774A2CB9A9059E49FE220E3CC1-C869-0180-6843-BF9932E316E8?ypp=0&myp=0&K=afa53a85a7e5c378282c0be9%26sign%3D253e61392b8eff662013212ab183c891&ctype=12&token=0544&ev=1&ep=ciacHkyIUs8B4yrcgD8bNXi2fX5eXP4J9h%2BFgNJjALshQO%2B4nU%2FTtO%2B5P%2FZCE%2FBsditwZenzq6XkGTMVYYNLr2EQ30%2BgOfrm9vTg5d8lzZkDZGw1c8uivFSeRjT1&hd=1&oip=1939659569'\n" +
                    "duration 178.667\n" +
                    "file 'http://k.youku.com/player/getFlvPath/sid/048455417446012115ebe_00/st/flv/fileid/0300010100587615E18FCC059E49FE0E9FBA38-2F1A-8CA4-CF5B-6D259E2DB1AB?ypp=0&myp=0&K=fb386578479b75df282c0be9%26sign%3D76b64c31b582d61b852d66229b9e9677&ctype=12&token=0504&ev=1&ep=ciacHkyIUs8H4SfZiD8bZi3nISVaXP4J9h%2BFgNJjALshQO%2B5mDukxpXGPYxCE%2FBsditwZeuEoqaVG0McYfI1qBkQ1z3ZPfqTiPWR5asnxpUJExtCAMymxlSeRjD1&hd=1&oip=1939659569'\n" +
                    "duration 156.200\n";
```
Then I modify the method `createPlayer` in `IjkVideoView`:

```java
public IMediaPlayer createPlayer() {
        IjkMediaPlayer ijkMediaPlayer = null;
        if (mUri != null) {
            ijkMediaPlayer = new IjkMediaPlayer();
            IjkMediaPlayer.native_setLogLevel(IjkMediaPlayer.IJK_LOG_DEBUG);
            ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "safe", 0);
            ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "protocol_whitelist", "ffconcat,file,http,https");
            ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
            ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-auto-rotate", 1);
            ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-auto-rotate", 0);
            ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-handle-resolution-change", 1);

            ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "opensles", 1);

            ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "overlay-format", IjkMediaPlayer.SDL_FCC_RV32);

            ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 1);
            ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "start-on-prepared", 0);

            ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "http-detect-range-support", 0);

            ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 48);
        }
        return ijkMediaPlayer;
    }
```
**Note** that I set `protocol_whitelist` by `IjkMediaPlayer.OPT_CATEGORY_PLAYER` or `IjkMediaPlayer.OPT_CATEGORY_FORMAT`,however it always report this error:

> 16 20:13:26.467 14728-14821/tv.danmaku.ijk.media.example E/IJKMEDIA: Protocol not on whitelist 'file,crypto'!
01-16 20:13:26.467 14728-14821/tv.danmaku.ijk.media.example E/IJKMEDIA: Impossible to open 'http://k.youku.com/player/getFlvPath/sid/048455411693812bdd99a_00/st/flv/fileid/030001010058774A2CB9A9059E49FE220E3CC1-C869-0180-6843-BF9932E316E8?ypp=0&myp=0&K=afa53a85a7e5c378282c0be9%26sign%3D253e61392b8eff662013212ab183c891&ctype=12&token=0544&ev=1&ep=ciacHkyIUs8B4yrcgD8bNXi2fX5eXP4J9h%2BFgNJjALshQO%2B4nU%2FTtO%2B5P%2FZCE%2FBsditwZenzq6XkGTMVYYNLr2EQ30%2BgOfrm9vTg5d8lzZkDZGw1c8uivFSeRjT1&hd=1&oip=1939659569'
01-16 20:13:26.467 14728-14821/tv.danmaku.ijk.media.example D/IJKMEDIA: Statistics: 891 bytes read, 0 seeks
01-16 20:13:26.469 14728-14821/tv.danmaku.ijk.media.example E/IJKMEDIA: /storage/emulated/0/test.ffconcat: Invalid argument

It seems this setting useless.

**Comment by xinzhengzhang** [comment]
Remove ` which wrapping the url

**Comment by CoXier** [comment]
@xinzhengzhang 
I have removed `.But it still reports  above errors

**Comment by luosch** [comment]
@CoXier replace

```java
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "protocol_whitelist", "ffconcat,file,http,https");
```
with
```java
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "protocol_whitelist", "concat,http,tcp,https,tls,file");
```

**Comment by CoXier** [comment]
@luosch 
Thanks,it works.In fact I forgot `tcp` protocol.

**Comment by Mattmlm** [comment]
In case anyone else has difficulty reading, the key changes are:
- Set the ijkmediaplayer's **format** option (not player) for "protocol_whitelist"
- Add **https and tcp** to protocol_whitelist
- And also add **"safe"** to the format options.

These changes work for both iOS and Android since they're just parameters to ffmpeg.
