### ISSUE TITLE
Android  ijkplayer  C 代码用什么工具调试比较好(win 7系统) ?

### ISSUE THREAD

**Issue by xiasc01** [Bilibili/ijkplayer#2608]
Android  ijkplayer  C 代码用什么工具调试比较好(win 7系统) ?？？求指点

**Comment by houshunwei** [comment]
https://gold.xitu.io/entry/57ea254e5bbb50005d6f079c
关键是：
如果NDK代码位于项目的Model中，必须在如下位置Symbol Directories，增加NDK所在项目的根路径，否则LLDB调试器会报找不到符号文件错误，是无法进行调试的
