### ISSUE TITLE
Dump v-cache RTSP stream

### ISSUE THREAD

**Issue by GrantRolls** [bilibili/ijkplayer#2612]
I'm after a live video feed from an IP camera. Sometimes - if there is a delay between starting the feed and rendering the video - The v-cache will fill upwards of 10 seconds

How can I dump this cache mid feed, to get back to real-time view?

Cheers

**Comment by xinzhengzhang** [comment]
Need to modify ff_ffplay and drop the expired frame

**Comment by Harryuan** [comment]
@xinzhengzhang 
would you please tell us how to modify the ff_ffplay in detail?
Thank you very much.

**Comment by alhazmy13** [comment]
@xinzhengzhang i need your help with this, how i can drop the expired frame?
