### ISSUE TITLE
How to use hwdecode with ffmpeg

### ISSUE THREAD

**Issue by linKnowEasy** [Bilibili/ijkplayer#2616]
1. according to [wiki:HWAccelIntro](https://trac.ffmpeg.org/wiki/HWAccelIntro) ffmpeg didn't support hwdecode.
2. so how to create VTDecompressionSessionRef and decode  with avpacket.

thanks for your help

中文
1. ffmpeg [wiki:HWAccelIntro](https://trac.ffmpeg.org/wiki/HWAccelIntro) 好像不是不支持硬解码的。
那这样的话。 怎么根据 avpacket 来进行调用 videotoolbox 来进行硬解码呢, 因为感觉设计到了 sps pps, 不能保证 avpacket 的data 都包含 sps pps , 且 data 的数据 格式也不是标准的  NALU 类型。

描述可能有点混乱, 目的:
1. 如果ffmpeg 能调用 videotoolbox 的硬解码的话. 想请教一下怎么调用的。
2. ffmpeg 不能调用的话, 那么是怎么对 ffmpeg 的video stream 做适配的。
如果回答起来比较麻烦, 能否贴一下 相关处理的 文件地址呢。

谢谢能抽空查看 抑或 回答

**Comment by xinzhengzhang** [comment]
Set player option with `key: videotoolbox value :1`
I guess `IJKVideoTooBox.h` is what you want.

**Comment by linKnowEasy** [comment]
it work .
thanks
