### ISSUE TITLE
I have always got "Error: -10000,0", what's this mean?

### ISSUE THREAD

**Issue by jpxiong** [Bilibili/ijkplayer#262]
I haven't found the definition of -10000 in ijkplayer, so what's the error code mean?

If I want to redefine the error code, any suggestions?

Thanks.

**Comment by bbcallen** [comment]
Error code has no mean for now.

**Comment by niceteg** [comment]
Dear friend! 

Have you already seen that nice  stuff? Oh, you've  got to take a look  <http://up.eco-mower.com/lnzhkjcc>

Typos courtesy of my iPhone, teg

**Comment by niceteg** [comment]
Greetings! 

I'm  so happy to hear the  latest  news  from our  friends, you may read it  here <http://daria.foxyan.com/lnmr/898>


Yours, teg
