### ISSUE TITLE
linking error while building Xcode 8.2.1

### ISSUE THREAD

**Issue by arun542** [Bilibili/ijkplayer#2624]
duplicate symbol _validate_avcC_spc in:
    /Users/arun/Library/Developer/Xcode/DerivedData/AnimatedApp-cuhnpgcdvefdejauxnwryqzihxit/Build/Products/Debug-iphonesimulator/IJKMediaFramework.framework/IJKMediaFramework(IJKVideoToolBoxAsync.o)
    /Users/arun/Library/Developer/Xcode/DerivedData/AnimatedApp-cuhnpgcdvefdejauxnwryqzihxit/Build/Products/Debug-iphonesimulator/IJKMediaFramework.framework/IJKMediaFramework(IJKVideoToolBoxSync.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by xinzhengzhang** [comment]
#2558
