### ISSUE TITLE
currentPlaybackTime函数获取时间不准.

### ISSUE THREAD

**Issue by wtwmiao** [Bilibili/ijkplayer#2625]
IJKFFMoviePlayerController 里的currentPlaybackTime函数获取时间不准,具体表现 视频还没有播放结束,进度条已经移动到最后,通过定时器不断取currentPlaybackTime 值,发现视频还在播放,但是时间已经到了视频末尾.
IJKAVMoviePlayerController 里的实现就没有这个问题.

**Comment by xinzhengzhang** [comment]
seems the length of audio is shorter than video

**Comment by wtwmiao** [comment]
程序调试了一下,主要是1080P视频显示来不及. A-V 不断变大,将 丢帧功能开启就好了.

**Comment by SoXeon** [comment]
@wtwmiao 请问如何开启丢帧功能？
