### ISSUE TITLE
4K高清视频无法使用硬解播放

### ISSUE THREAD

**Issue by keyofwork** [Bilibili/ijkplayer#2629]
我在使用ijkplayer播放4K高清视频时无法使用硬解
操作：
1.重新打包SO，支持更多的视频格式
2.开启mediacodec选项，支持硬解
3.视频文件  http://www.yunpanxia.com/c/379351
播放时还是显示使用avcodec进行的解码，显示不流畅
但选择使用androidmediaplayer播放时可以正常播放。

**Comment by linbiaojj** [comment]
我也遇到一样问题，用ijkExoMediaPlayer播放正常

**Comment by raymond1012** [comment]
need enable mediacodec-hevc
