### ISSUE TITLE
"Latency of playing stream" stacked when  network shocked . 

### ISSUE THREAD

**Issue by Adatan** [Bilibili/ijkplayer#263]
Hi , here is my question of real time playing.

By adjust some variables in ff_ffplay_def.h , the latency can be reduced.

But when the network shocked (means buffering start),  the latency would increase.

The network shocked more times, the latency stacked more.

And this situation is also happened when "stream pause then play again".

ex. default latency = 1 sec.  Pause for 10 sec and then play , the latency will increase to 11 sec.

Is there any method to solve this?

**Comment by bbcallen** [comment]
Does such proble exist in original ffplay on PC?

Current buffering strategy in ijkplayer is improved for on-demand streams, not good enough for low-latency live streams.

**Comment by Adatan** [comment]
Yes , this problem exist in original ffplay on PC too.
I had try add "-fflags nobuffer" , and it look like no improvement.
Can you provide any advice for this problem?  
Thanks a lot.

**Comment by bbcallen** [comment]
Sorry, not familiar with live stream.
Do you know any other open source media player can handle this problem?

**Comment by Adatan** [comment]
VLC looks working fine on PC.
When the network shocked , the display view of VLC is broken .
Once the network recovered,  the display view would work normally and latency has no increase.

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
