### ISSUE TITLE
android ijkplayer 播放视频无画面，有声音

### ISSUE THREAD

**Issue by godcok** [Bilibili/ijkplayer#2634]
先正常播放一个视频，然后调用stop，再播放另外一个URL  ，此时会无画面，只有声音

**Comment by raymond1012** [comment]
recreate ijkplayer when switch url

**Comment by godcok** [comment]
是重新创建的

**Comment by raymond1012** [comment]
检查你的surface设置，非播放器问题

2017-02-08 16:32 GMT+08:00 godcok <notifications@github.com>:

**Comment by godcok** [comment]
首次播放没问题，在未销毁surface的时候，停止原播放，开启一个新的播放，就出这个问题

**Comment by raymond1012** [comment]
播放器不保证重用安全，必须每次重新创建，即new ijkmediaplayer->release->new ijkmediaplayer

2017-02-08 16:44 GMT+08:00 godcok <notifications@github.com>:

**Comment by godcok** [comment]
是这样一个流程来操作的，但是如果我把我的ijkPlayerView从父布局中移除，再添加回来就不会有问题

**Comment by godcok** [comment]
如果不移除的话，就会出现有声音，无画面，另外还有个问题，我们这边https貌似无法播放，http的视频试过没问题

**Comment by raymond1012** [comment]
compile openssl

**Comment by xingchenfengn** [comment]
你好，我也遇到了这样的问题，请问怎么解决的呀

**Comment by sanchibing** [comment]
你好，我也遇到了这样的问题，请问怎么解决的呀

**Comment by godcok** [comment]
之前用TextureView有这样的问题，后来我换了SurfaceView就没事了

**Comment by lamster2018** [comment]
你好，我也遇到了这样的问题，请问怎么解决的呀

**Comment by gongtingshisi** [comment]
me too.it occurs when returning back from another app.

**Comment by codertrack** [comment]
initrenderviews
