### ISSUE TITLE
在xcode8.2.1跑不了，有人遇到吗？

### ISSUE THREAD

**Issue by liukuiqing** [Bilibili/ijkplayer#2636]
Undefined symbols for architecture arm64:
  "___gxx_personality_v0", referenced from:
      std::__1::map<long long, void*, std::__1::less<long long>, std::__1::allocator<std::__1::pair<long long const, void*> > >::operator[](long long const&) in IJKMediaFramework(ijkstl.o)
  "operator delete(void*)", referenced from:
      std::__1::map<long long, void*, std::__1::less<long long>, std::__1::allocator<std::__1::pair<long long const, void*> > >::operator[](long long const&) in IJKMediaFramework(ijkstl.o)
      _ijk_map_destroy in IJKMediaFramework(ijkstl.o)
      std::__1::__tree<std::__1::__value_type<long long, void*>, std::__1::__map_value_compare<long long, std::__1::__value_type<long long, void*>, std::__1::less<long long>, true>, std::__1::allocator<std::__1::__value_type<long long, void*> > >::destroy(std::__1::__tree_node<std::__1::__value_type<long long, void*>, void*>*) in IJKMediaFramework(ijkstl.o)
      std::__1::map<long long, void*, std::__1::less<long long>, std::__1::allocator<std::__1::pair<long long const, void*> > >::__construct_node_with_key(long long const&) in IJKMediaFramework(ijkstl.o)
      std::__1::__tree<std::__1::__value_type<long long, void*>, std::__1::__map_value_compare<long long, std::__1::__value_type<long long, void*>, std::__1::less<long long>, true>, std::__1::allocator<std::__1::__value_type<long long, void*> > >::erase(std::__1::__tree_const_iterator<std::__1::__value_type<long long, void*>, std::__1::__tree_node<std::__1::__value_type<long long, void*>, void*>*, long>) in IJKMediaFramework(ijkstl.o)
  "operator new(unsigned long)", referenced from:
      _ijk_map_create in IJKMediaFramework(ijkstl.o)
      std::__1::map<long long, void*, std::__1::less<long long>, std::__1::allocator<std::__1::pair<long long const, void*> > >::__construct_node_with_key(long long const&) in IJKMediaFramework(ijkstl.o)
ld: symbol(s) not found for architecture arm64

**Comment by xinzhengzhang** [comment]
seems you have not linked c++
Refer demo project

**Comment by lixiao7215981** [comment]
ProjectTargets->General－>Linked Frameworks and Libraries -> add libstdc++.tbd

**Comment by liukuiqing** [comment]
thank you

**Comment by liukuiqing** [comment]
thank you，
