### ISSUE TITLE
请教播放器频繁切换不同视频地址闪退的问题！

### ISSUE THREAD

**Issue by wuxianzhao** [Bilibili/ijkplayer#2638]
环境是ios 8 9 10
页面中有3-4个直播按钮，点击按钮播放不同的直播流，大概切换10次左右就会闪退，页面中只有一个播放器，每次点击按钮更换流地址
提示错误：libBacktraceRecording: can't allocate VM for dispatch queues list

请大神帮忙看下这个是播放器的问题还是程序本身的问题，非常感谢！

**Comment by raymond1012** [comment]
recreate ijkplayer when switch url

**Comment by wuxianzhao** [comment]
重新创建player也是这个提示

**Comment by wuxianzhao** [comment]
刚才又测试了下，2台真机，iphone6 和 iphone6s，系统都是10.2.1  
iphone 6  上面还是提示 ：libBacktraceRecording: can't allocate VM for dispatch queues list
iphone6s 上面提示：
Duration: N/A, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 371000
    Stream #0:0, 0, 1/90000: Video: h264, 1 reference frame ([27][0][0][0] / 0x001B), none(left), 90k tbr, 90k tbn, 180k tbc
    Metadata:
      variant_bitrate : 371000
    Stream #0:1, 0, 1/90000: Audio: aac ([15][0][0][0] / 0x000F), 0 channels, fltp
    Metadata:
      variant_bitrate : 371000
vtbformat_init - avcC atom too data small or missingAssertion failed: (mutex), function SDL_LockMutex, file /Users/ww/Downloads/testapp/ijkplayer-master/ijkmedia/ijksdl/ijksdl_mutex.c, line 63.
现在有点搞不太明白了，请大神帮帮忙

**Comment by wuxianzhao** [comment]
我直接建一个空项目，项目里面导入ijkplayer.framework，页面中放几个按钮切换视频也是出现上面的问题，这样看来应该和原来app里面的程序没有关系。

**Comment by raymond1012** [comment]
每次切换url都应重新创建播放器

2017-02-08 17:29 GMT+08:00 wuxianzhao <notifications@github.com>:

**Comment by raymond1012** [comment]
http://stackoverflow.com/questions/34336920/memory-leak-with-libbacktracerecording-dylib-in-react-native-ios-application

在 2017年2月8日 下午5:31，raymond zheng <raymondzheng1412@gmail.com>写道：

**Comment by wuxianzhao** [comment]
我试了试,ijkplayer.framework空项目导入没这个问题，但我打包成了.a文件，难道是我打包的时候参数设置错了，唯一不同的也就是这个包不一样，我再测试下看看，非常感谢！！！

**Comment by wuxianzhao** [comment]
找到问题，播放器本身没问题，是集成了第三方播放器统计代码的问题，感谢@raymond1012,关闭了！！
