### ISSUE TITLE
android播放在线视频锁屏后停止播放，再开屏不继续播放

### ISSUE THREAD

**Issue by xu819241519** [Bilibili/ijkplayer#2639]
播放在线视频时，锁屏后视频停止播放，再开屏视频不自动播放，还是停在锁屏的那帧画面。

**Comment by xu819241519** [comment]
原来是需要在settings中开启后台播放才行。。。

**Comment by huyue05** [comment]
怎么开启后台播放

**Comment by xu819241519** [comment]
@huyue05 在demo中的右上角设置，点开后会有Enable background play
