### ISSUE TITLE
ijkMediaPlayer.setAvFormatOption("fflags", “nobuffer”); with no display

### ISSUE THREAD

**Issue by jpxiong** [Bilibili/ijkplayer#264]
when I set the option as following:
ijkMediaPlayer.setAvFormatOption("fflags", “nobuffer”);

No display ! 
Is it a bug ?

**Comment by bbcallen** [comment]
This option has nothing to do with ijkplayer's buffering mechanism.
Try ffplay on PC with this option first.

**Comment by jpxiong** [comment]
ffplay on PC works fine. 

#210 has been discussed the option, it seems work here.
ijkMediaPlayer.setAvFormatOption("analyzeduration", “2000000”); 
ijkMediaPlayer.setAvFormatOption("fflags", “nobuffer”);
ijkMediaPlayer.setAvFormatOption("probsize", “4096”);

what's i missed ?

**Comment by bbcallen** [comment]
Dunno without debug.
Any log?

**Comment by jpxiong** [comment]
/Users/jerikc/log.log:479:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_set_data_source(url="/storage/emulated/0/xpg.mp4")
/Users/jerikc/log.log:480:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_set_data_source(url="/storage/emulated/0/xpg.mp4")=0
/Users/jerikc/log.log:481:06-05 10:49:26.238 W/IJKMEDIA( 5434): IjkMediaPlayer_setVideoSurface
/Users/jerikc/log.log:482:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_set_android_surface(surface=0xc6e0001d)
/Users/jerikc/log.log:483:06-05 10:49:26.238 D/IJKMEDIA( 5434): ffpipeline_set_surface()
/Users/jerikc/log.log:484:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_set_android_surface(surface=0xc6e0001d)=void
/Users/jerikc/log.log:485:06-05 10:49:26.238 W/IJKMEDIA( 5434): IjkMediaPlayer_prepareAsync
/Users/jerikc/log.log:486:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_prepare_async()
/Users/jerikc/log.log:487:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_prepare_async()=0
/Users/jerikc/log.log:488:06-05 10:49:26.243 I/IJKMEDIA( 5434): SDL_RunThread: [5769] ff_read
/Users/jerikc/log.log:489:06-05 10:49:26.243 I/IJKMEDIA( 5434): SDL_RunThread: [5768] ff_vout
/Users/jerikc/log.log:490:06-05 10:49:26.243 D/IJKMEDIA( 5434): ffpipenode_create_video_output_from_android_mediacodec()
/Users/jerikc/log.log:491:06-05 10:49:26.243 I/IJKMEDIA( 5434): SDL_RunThread: [5767] ff_msg_loop
/Users/jerikc/log.log:492:06-05 10:49:26.243 W/IJKMEDIA( 5434): message_loop
/Users/jerikc/log.log:493:06-05 10:49:26.243 W/IJKMEDIA( 5434): FFP_MSG_FLUSH:
/Users/jerikc/log.log:495:06-05 10:49:26.273 E/IJKMEDIA( 5434): Option http-detect-range-support not found.
/Users/jerikc/log.log:502:06-05 10:49:26.318 I/IJKMEDIA( 5434): max_frame_duration: 3600.000
/Users/jerikc/log.log:503:06-05 10:49:26.318 I/IJKMEDIA( 5434): Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/xpg.mp4':
/Users/jerikc/log.log:504:06-05 10:49:26.318 I/IJKMEDIA( 5434):   Metadata:
/Users/jerikc/log.log:505:06-05 10:49:26.318 I/IJKMEDIA( 5434):     major_brand     : 
/Users/jerikc/log.log:506:06-05 10:49:26.318 I/IJKMEDIA( 5434): isom
/Users/jerikc/log.log:507:06-05 10:49:26.318 I/IJKMEDIA( 5434): 
/Users/jerikc/log.log:508:06-05 10:49:26.318 I/IJKMEDIA( 5434):     minor_version   : 
/Users/jerikc/log.log:509:06-05 10:49:26.318 I/IJKMEDIA( 5434): 512
/Users/jerikc/log.log:510:06-05 10:49:26.318 I/IJKMEDIA( 5434): 
/Users/jerikc/log.log:511:06-05 10:49:26.318 I/IJKMEDIA( 5434):     compatible_brands: 
/Users/jerikc/log.log:512:06-05 10:49:26.318 I/IJKMEDIA( 5434): isomiso2avc1mp41
/Users/jerikc/log.log:513:06-05 10:49:26.318 I/IJKMEDIA( 5434): 
/Users/jerikc/log.log:514:06-05 10:49:26.318 I/IJKMEDIA( 5434):     encoder         : 
/Users/jerikc/log.log:515:06-05 10:49:26.318 I/IJKMEDIA( 5434): Lavf54.63.104
/Users/jerikc/log.log:516:06-05 10:49:26.318 I/IJKMEDIA( 5434): 
/Users/jerikc/log.log:517:06-05 10:49:26.318 I/IJKMEDIA( 5434):   Duration: 
/Users/jerikc/log.log:518:06-05 10:49:26.318 I/IJKMEDIA( 5434): 00:06:19.46
/Users/jerikc/log.log:519:06-05 10:49:26.318 I/IJKMEDIA( 5434): , start: 
/Users/jerikc/log.log:520:06-05 10:49:26.318 I/IJKMEDIA( 5434): 0.000000
/Users/jerikc/log.log:521:06-05 10:49:26.318 I/IJKMEDIA( 5434): , bitrate: 
/Users/jerikc/log.log:522:06-05 10:49:26.318 I/IJKMEDIA( 5434): 4541 kb/s
/Users/jerikc/log.log:523:06-05 10:49:26.318 I/IJKMEDIA( 5434): 
/Users/jerikc/log.log:524:06-05 10:49:26.318 I/IJKMEDIA( 5434):     Stream #0:0
/Users/jerikc/log.log:525:06-05 10:49:26.318 I/IJKMEDIA( 5434): (und)
/Users/jerikc/log.log:526:06-05 10:49:26.318 I/IJKMEDIA( 5434): : Video: h264 (High) (avc1 / 0x31637661), yuv420p, 2048x1152 [SAR 1:1 DAR 16:9], 4409 kb/s
/Users/jerikc/log.log:527:06-05 10:49:26.318 I/IJKMEDIA( 5434): , 
/Users/jerikc/log.log:528:06-05 10:49:26.318 I/IJKMEDIA( 5434): 23.98 fps, 
/Users/jerikc/log.log:529:06-05 10:49:26.318 I/IJKMEDIA( 5434): 23.98 tbr, 
/Users/jerikc/log.log:530:06-05 10:49:26.318 I/IJKMEDIA( 5434): 90k tbn, 
/Users/jerikc/log.log:531:06-05 10:49:26.318 I/IJKMEDIA( 5434): 47.95 tbc
/Users/jerikc/log.log:532:06-05 10:49:26.318 I/IJKMEDIA( 5434):  (default)
/Users/jerikc/log.log:533:06-05 10:49:26.318 I/IJKMEDIA( 5434): 
/Users/jerikc/log.log:534:06-05 10:49:26.318 I/IJKMEDIA( 5434):     Metadata:
/Users/jerikc/log.log:535:06-05 10:49:26.318 I/IJKMEDIA( 5434):       handler_name    : 
/Users/jerikc/log.log:536:06-05 10:49:26.318 I/IJKMEDIA( 5434): VideoHandler
/Users/jerikc/log.log:537:06-05 10:49:26.318 I/IJKMEDIA( 5434): 
/Users/jerikc/log.log:538:06-05 10:49:26.318 I/IJKMEDIA( 5434):     Stream #0:1
/Users/jerikc/log.log:539:06-05 10:49:26.318 I/IJKMEDIA( 5434): (und)
/Users/jerikc/log.log:540:06-05 10:49:26.318 I/IJKMEDIA( 5434): : Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s
/Users/jerikc/log.log:541:06-05 10:49:26.318 I/IJKMEDIA( 5434):  (default)
/Users/jerikc/log.log:542:06-05 10:49:26.318 I/IJKMEDIA( 5434): 
/Users/jerikc/log.log:543:06-05 10:49:26.318 I/IJKMEDIA( 5434):     Metadata:
/Users/jerikc/log.log:544:06-05 10:49:26.318 I/IJKMEDIA( 5434):       handler_name    : 
/Users/jerikc/log.log:545:06-05 10:49:26.318 I/IJKMEDIA( 5434): SoundHandler
/Users/jerikc/log.log:546:06-05 10:49:26.318 I/IJKMEDIA( 5434): 
/Users/jerikc/log.log:547:06-05 10:49:26.323 I/IJKMEDIA( 5434): SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
/Users/jerikc/log.log:548:06-05 10:49:26.323 I/IJKMEDIA( 5434): SDL_Android_AudioTrack: ENCODING_PCM_16BIT
/Users/jerikc/log.log:573:06-05 10:49:26.363 I/IJKMEDIA( 5434): SDL_Android_AudioTrack_new: init volume as 1.000000/(0.000000,1.000000)
/Users/jerikc/log.log:574:06-05 10:49:26.363 I/IJKMEDIA( 5434): AudioCodec: avcodec, aac
/Users/jerikc/log.log:576:06-05 10:49:26.368 I/IJKMEDIA( 5434): SDL_RunThread: [5773] ff_audio_dec
/Users/jerikc/log.log:578:06-05 10:49:26.378 I/IJKMEDIA( 5434): SDL_RunThread: [5772] ff_aout_android
/Users/jerikc/log.log:628:06-05 10:49:26.433 I/IJKMEDIA( 5434): VideoCodec: avcodec, h264
/Users/jerikc/log.log:629:06-05 10:49:26.433 I/IJKMEDIA( 5434): fps: 23.976025 (normal)
/Users/jerikc/log.log:630:06-05 10:49:26.433 I/IJKMEDIA( 5434): SDL_RunThread: [5780] ff_video_dec
/Users/jerikc/log.log:631:06-05 10:49:26.433 I/IJKMEDIA( 5434): fps: 23.976024 (normal)
/Users/jerikc/log.log:632:06-05 10:49:26.433 W/IJKMEDIA( 5434): ijkmp_get_msg: FFP_MSG_PREPARED
/Users/jerikc/log.log:633:06-05 10:49:26.433 W/IJKMEDIA( 5434): FFP_MSG_PREPARED:
/Users/jerikc/log.log:634:06-05 10:49:26.433 W/IJKMEDIA( 5434): FFP_MSG_VIDEO_SIZE_CHANGED: 2048, 1152
/Users/jerikc/log.log:635:06-05 10:49:26.433 W/IJKMEDIA( 5434): FFP_MSG_SAR_CHANGED: 1, 1
/Users/jerikc/log.log:636:06-05 10:49:26.433 D/IJKMEDIA( 5434): ffp_toggle_buffering_l: start
/Users/jerikc/log.log:637:06-05 10:49:26.433 W/IJKMEDIA( 5434): FFP_MSG_BUFFERING_START:
/Users/jerikc/log.log:645:06-05 10:49:26.488 W/IJKMEDIA( 5434): IjkMediaPlayer_start
/Users/jerikc/log.log:646:06-05 10:49:26.488 W/IJKMEDIA( 5434): ijkmp_start()
/Users/jerikc/log.log:647:06-05 10:49:26.488 W/IJKMEDIA( 5434): ijkmp_get_msg: FFP_REQ_START
/Users/jerikc/log.log:648:06-05 10:49:26.488 D/IJKMEDIA( 5434): ijkmp_get_msg: FFP_REQ_START: start on fly
/Users/jerikc/log.log:649:06-05 10:49:26.488 W/IJKMEDIA( 5434): ijkmp_start()=0
/Users/jerikc/log.log:652:06-05 10:49:26.513 W/IJKMEDIA( 5434): IjkMediaPlayer_start
/Users/jerikc/log.log:653:06-05 10:49:26.513 W/IJKMEDIA( 5434): ijkmp_start()
/Users/jerikc/log.log:654:06-05 10:49:26.513 W/IJKMEDIA( 5434): ijkmp_get_msg: FFP_REQ_START
/Users/jerikc/log.log:655:06-05 10:49:26.513 D/IJKMEDIA( 5434): ijkmp_get_msg: FFP_REQ_START: start on fly
/Users/jerikc/log.log:656:06-05 10:49:26.513 W/IJKMEDIA( 5434): ijkmp_start()=0
/Users/jerikc/log.log:683:06-05 10:49:26.538 I/tv.danmaku.ijk.media.player.IjkMediaPlayer( 5434): Info (701,0)
/Users/jerikc/log.log:748:06-05 10:49:30.383 D/IJKMEDIA( 5434): ffp_toggle_buffering_l: end
/Users/jerikc/log.log:749:06-05 10:49:30.383 W/IJKMEDIA( 5434): FFP_MSG_BUFFERING_END:
/Users/jerikc/log.log:752:06-05 10:49:30.383 I/tv.danmaku.ijk.media.player.IjkMediaPlayer( 5434): Info (702,0)
/Users/jerikc/log.log:1155:06-05 10:49:43.998 W/IJKMEDIA( 5434): IjkMediaPlayer_seekTo
/Users/jerikc/log.log:1156:06-05 10:49:43.998 W/IJKMEDIA( 5434): ijkmp_seek_to(84619)
/Users/jerikc/log.log:1157:06-05 10:49:43.998 W/IJKMEDIA( 5434): ijkmp_seek_to(84619)=0
/Users/jerikc/log.log:1158:06-05 10:49:43.998 W/IJKMEDIA( 5434): ijkmp_get_msg: FFP_REQ_SEEK
/Users/jerikc/log.log:1159:06-05 10:49:43.998 E/IJKMEDIA( 5434): stream_seek 84619000(84619) + 0, 
/Users/jerikc/log.log:1160:06-05 10:49:43.998 D/IJKMEDIA( 5434): ijkmp_get_msg: FFP_REQ_SEEK: seek to 84619
/Users/jerikc/log.log:1161:06-05 10:49:44.533 D/IJKMEDIA( 5434): ffp_toggle_buffering_l: start
/Users/jerikc/log.log:1162:06-05 10:49:44.533 W/IJKMEDIA( 5434): FFP_MSG_BUFFERING_START:
/Users/jerikc/log.log:1163:06-05 10:49:44.533 I/tv.danmaku.ijk.media.player.IjkMediaPlayer( 5434): Info (701,0)
/Users/jerikc/log.log:1166:06-05 10:49:44.588 W/IJKMEDIA( 5434): ijkmp_get_msg: FFP_MSG_SEEK_COMPLETE
/Users/jerikc/log.log:1167:06-05 10:49:44.588 W/IJKMEDIA( 5434): FFP_MSG_SEEK_COMPLETE:
/Users/jerikc/log.log:1195:06-05 10:49:44.923 W/IJKMEDIA( 5434): FFP_MSG_VIDEO_SIZE_CHANGED: 2048, 1152
/Users/jerikc/log.log:1196:06-05 10:49:44.923 W/IJKMEDIA( 5434): SDL_VoutFFmpeg_CreateOverlay(w=2048, h=1152, fmt=RV32(0x32335652, dp=0x77b98db0)
/Users/jerikc/log.log:1198:06-05 10:49:45.023 W/IJKMEDIA( 5434): SDL_VoutFFmpeg_CreateOverlay(w=2048, h=1152, fmt=RV32(0x32335652, dp=0x77b98db0)
/Users/jerikc/log.log:1199:06-05 10:49:45.023 W/IJKMEDIA( 5434): FFP_MSG_VIDEO_SIZE_CHANGED: 2048, 1152
/Users/jerikc/log.log:1201:06-05 10:49:45.083 W/IJKMEDIA( 5434): SDL_VoutFFmpeg_CreateOverlay(w=2048, h=1152, fmt=RV32(0x32335652, dp=0x77b98db0)
/Users/jerikc/log.log:1202:06-05 10:49:45.083 W/IJKMEDIA( 5434): FFP_MSG_VIDEO_SIZE_CHANGED: 2048, 1152
/Users/jerikc/log.log:1203:06-05 10:49:45.098 D/IJKMEDIA( 5434): ffp_toggle_buffering_l: end
/Users/jerikc/log.log:1204:06-05 10:49:45.098 W/IJKMEDIA( 5434): FFP_MSG_BUFFERING_END:
/Users/jerikc/log.log:1218:06-05 10:49:45.108 D/IJKMEDIA( 5434): ANativeWindow_setBuffersGeometry: w=2048, h=1152, f=(0x4) => w=2048, h=1152, f=RV32(0x32335652)
/Users/jerikc/log.log:1242:06-05 10:49:45.148 I/tv.danmaku.ijk.media.player.IjkMediaPlayer( 5434): Info (702,0)

**Comment by jpxiong** [comment]
After I do the seekTo() operation, there is display!

**Comment by jpxiong** [comment]
/Users/jerikc/log.log:449:06-05 10:49:26.238 W/IJKMEDIA( 5434): IjkMediaPlayer_native_setup
/Users/jerikc/log.log:450:06-05 10:49:26.238 D/IJKMEDIA( 5434): ffpipeline_create_from_android()
/Users/jerikc/log.log:451:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_set_format_callback(0x78157c6d, 0x1d60044a)
/Users/jerikc/log.log:452:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_set_format_callback()=void
/Users/jerikc/log.log:453:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_android_set_mediacodec_select_callback()
/Users/jerikc/log.log:454:06-05 10:49:26.238 D/IJKMEDIA( 5434): ffpipeline_set_mediacodec_select_callback
/Users/jerikc/log.log:455:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_android_set_mediacodec_select_callback()=void
/Users/jerikc/log.log:456:06-05 10:49:26.238 W/IJKMEDIA( 5434): IjkMediaPlayer_setAvFormatOption
/Users/jerikc/log.log:457:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_set_format_option(http-detect-range-support, 0)
/Users/jerikc/log.log:458:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_set_format_option()=void
/Users/jerikc/log.log:459:06-05 10:49:26.238 W/IJKMEDIA( 5434): IjkMediaPlayer_setOverlayFormat
/Users/jerikc/log.log:460:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_set_overlay_format(RV32(0x32335652))
/Users/jerikc/log.log:461:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_set_overlay_format()=void
/Users/jerikc/log.log:462:06-05 10:49:26.238 W/IJKMEDIA( 5434): IjkMediaPlayer_setAvCodecOption
/Users/jerikc/log.log:463:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_set_codec_option()
/Users/jerikc/log.log:464:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_set_codec_option()=void
/Users/jerikc/log.log:465:06-05 10:49:26.238 W/IJKMEDIA( 5434): IjkMediaPlayer_setFrameDrop
/Users/jerikc/log.log:466:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_set_framedrop(12)
/Users/jerikc/log.log:467:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_set_framedrop()=void
/Users/jerikc/log.log:468:06-05 10:49:26.238 W/IJKMEDIA( 5434): IjkMediaPlayer_setAvFormatOption
/Users/jerikc/log.log:469:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_set_format_option(analyzeduration, 2000000)
/Users/jerikc/log.log:470:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_set_format_option()=void
/Users/jerikc/log.log:471:06-05 10:49:26.238 W/IJKMEDIA( 5434): IjkMediaPlayer_setAvFormatOption
/Users/jerikc/log.log:472:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_set_format_option(fflags, nobuffer)
/Users/jerikc/log.log:473:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_set_format_option()=void
/Users/jerikc/log.log:474:06-05 10:49:26.238 W/IJKMEDIA( 5434): IjkMediaPlayer_setAvFormatOption
/Users/jerikc/log.log:475:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_set_format_option(probsize, 4096)
/Users/jerikc/log.log:476:06-05 10:49:26.238 W/IJKMEDIA( 5434): ijkmp_set_format_option()=void
/Users/jerikc/log.log:477:06-05 10:49:26.238 W/IJKMEDIA( 5434): IjkMediaPlayer_setDataSourceAndHeaders
/Users/jerikc/log.log:478:06-05 10:49:26.238 V/IJKMEDIA( 5434): setDataSource: path /storage/emulated/0/xpg.mp4

**Comment by bbcallen** [comment]
Why do you need this option for local file?

**Comment by jpxiong** [comment]
I just use the local file to test. I need these options to do low_latency for live streaming. If you can give me some suggestion about live streaming, that will be good.

**Comment by bbcallen** [comment]
Can you do that with original ffplay on PC?
Do you know any other open source media player can handle this problem?

**Comment by jpxiong** [comment]
Sure, I can. ffplay on PC works fine. I haven't found any other solution about low latency for live streaming at present.

But in issue #210 has been discussed the option:
ijkMediaPlayer.setAvFormatOption("analyzeduration", “2000000”); 
ijkMediaPlayer.setAvFormatOption("fflags", “nobuffer”);
ijkMediaPlayer.setAvFormatOption("probsize", “4096”);

Now it cannot work. Maybe it's regression ,i guess.

**Comment by ayyb1988** [comment]
@bbcallen @jpxiong  i also have this issue.     play rtmp streaming have 5-10s delay.  accordiing to in issue [#210 ](https://github.com/Bilibili/ijkplayer/issues/210)  ,i also set
```
ijkMediaPlayer.setAvFormatOption("analyzeduration", “2000000”); 
ijkMediaPlayer.setAvFormatOption("fflags", “nobuffer”);
ijkMediaPlayer.setAvFormatOption("probsize", “4096”);
```
when i open this rtsp,it's stop  . and then  i press start button

log is

SeekComplete
mp.getDataSource()=rtmp://124.172.240.44:1935/live/test1?user=jetsun&pwd=6383
mp.getCurrentPosition()=0
mp.getDuration()=0
mp.getMediaInfo().mVideoDecoder=null
mp.getVideoHeight()=0
mp.getVideoWidth=0

in VideoPlayerActivity.class  ,i add

        mVideoView.setOnSeekCompleteListener(new IMediaPlayer.OnSeekCompleteListener() {
            @Override
            public void onSeekComplete(IMediaPlayer mp) {
                System.out.println("SeekComplete " + "\nmp.getDataSource()="+mp.getDataSource() +"\nmp.getCurrentPosition()="+mp.getCurrentPosition()
                        +"\nmp.getDuration()="+mp.getDuration()+"\nmp.getMediaInfo().mVideoDecoder="+mp.getMediaInfo().mVideoDecoder
                        +"\nmp.getVideoHeight()="+mp.getVideoHeight()+"\nmp.getVideoWidth="+mp.getVideoWidth());
            }
        });

**Comment by jpxiong** [comment]
After disable the IJK BUFERING, it works fine:

ijkmediaplayer/jni//ijkmedia/ijkplayer/android/pipeline/ffpipenode_android_mediacodec_vdec.c
```C
 418 #ifdef USE_IJK_BUFERING
 419             if (ffp_packet_queue_get_or_buffering(ffp, d->queue, &pkt, &d->pkt_serial, &d->finished) < 0) {
 420 #else
 421             if (ffp_packet_queue_get(d->queue, &pkt, 1,  &d->pkt_serial) < 0) {
 422 #endif
```
ijkmediaplayer/jni//ijkmedia/ijkplayer/ff_ffplay.c
```C
2639 #ifdef USE_IJK_BUFERING
2640         io_tick_counter = SDL_GetTickHR();
2641         if (abs((int)(io_tick_counter - prev_io_tick_counter)) > BUFFERING_CHECK_PER_MILLISECONDS) {
2642             prev_io_tick_counter = io_tick_counter;
2643             ffp_check_buffering_l(ffp);
2644         }
2645 #endif
```

ijkmediaplayer/jni//ijkmedia/ijkplayer/ff_ffplay_def.h
```C 
33 #ifdef USE_IJK_BUFERING
 34 #define DEFAULT_HIGH_WATER_MARK_IN_BYTES        (256 * 1024)
 35 
 36 /*
 37  * START: buffering after prepared/seeked
 38  * NEXT:  buffering for the second time after START
 39  * MAX:   ...
 40  */
 41 #define DEFAULT_START_HIGH_WATER_MARK_IN_MS     (100)
 42 #define DEFAULT_NEXT_HIGH_WATER_MARK_IN_MS      (1 * 1000)
 43 #define DEFAULT_MAX_HIGH_WATER_MARK_IN_MS       (5 * 1000)
 44 
 45 #define BUFFERING_CHECK_PER_BYTES               (512)
 46 #define BUFFERING_CHECK_PER_MILLISECONDS        (500)
 47 
 48 #define MAX_QUEUE_SIZE (10 * 1024 * 1024)
 49 #define MIN_FRAMES 50000
 50 #else
 51 #define MAX_QUEUE_SIZE (15 * 1024 * 1024)
 52 #define MIN_FRAMES 5
 53 #endif
```

```C
586 #ifdef USE_IJK_BUFERING
587     ffp->high_water_mark_in_bytes       = DEFAULT_HIGH_WATER_MARK_IN_BYTES;
588 
589     ffp->start_high_water_mark_in_ms    = DEFAULT_START_HIGH_WATER_MARK_IN_MS;
590     ffp->next_high_water_mark_in_ms     = DEFAULT_NEXT_HIGH_WATER_MARK_IN_MS;
591     ffp->max_high_water_mark_in_ms      = DEFAULT_MAX_HIGH_WATER_MARK_IN_MS;
592     ffp->current_high_water_mark_in_ms  = DEFAULT_START_HIGH_WATER_MARK_IN_MS;
593 #endif
```

Thank @bbcallen 's [comment](https://github.com/jpxiong/ijkplayer/commit/c039c9f2bd010127e75ba7507cd7659d8fc6addb#commitcomment-11560802).

**Comment by bbcallen** [comment]
I'll adopt an option to enable/disable that feature

**Comment by jpxiong** [comment]
Sorry. When I do this:
```JAVA
ijkMediaPlayer.setMediaCodecEnabled(true);
```
ijkMediaPlayer.setAvFormatOption("fflags", “nobuffer”) setting  works fine. Otherwise, it doesn't work even through disable the ijk buffering.

**Comment by Android4MediaPlayer** [comment]
@bbcallen 期待加入此功能 @jpxiong 谢谢分享

**Comment by linjiansheng** [comment]
@bbcallen How to disable this feature in iOS?
```
    { "packet-buffering",                   "pause output until enough packets have been read after stalling",
        OPTION_OFFSET(packet_buffering),    OPTION_INT(1, 0, 1) },
```

**Comment by noamtcohen** [comment]
@jpxiong does you fork: https://github.com/jpxiong/ijkplayer disable buffering?

**Comment by nguyenlamson** [comment]
@noamtcohen @jpxiong Do you guys can build https://github.com/jpxiong/ijkplayer. I could not find option ijkMediaPlayer.setAvFormatOption. Do we still need in @jpxiong build???

**Comment by sanchibing** [comment]
@nguyenlamson   ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzeduration", 2000000);

**Comment by animaonline** [comment]
> This option has nothing to do with ijkplayer's buffering mechanism.
@bbcallen setting this flag does indeed affect the buffering, I have managed to reduce the latency of a RTSP stream to 200ms on my iPhone 7 Plus, the only problem is that now the video is failing to load on lower end iOS 10 devices like iPad 2, iPhone 5, etc.. 

You have also mentioned something about adding a function to togglet that, is that something that is available now?

Could you also please re-open this issue.

Thank you
