### ISSUE TITLE
播放器后台运行

### ISSUE THREAD

**Issue by wbi1987** [Bilibili/ijkplayer#265]
您好，我现在把播放器切后台时不释放所有的资源(不调用release)，只是关闭视频显示的surface，我调用了
    ijkmp_android_set_surface(env, mp, NULL );
切到后台后好像surface没有关闭，一直打印：
    voud_display_overlay_l: NULL native_window

请问一下这是什么原因，除了要调用上面那个接口还要调用其他的吗？谢谢！

**Comment by JavanEu** [comment]
@wbi1987 那个是刷新的线程没有停。

**Comment by JavanEu** [comment]
@wbi1987 pause 播放器就好了

**Comment by wbi1987** [comment]
@JavanEu 谢谢你的解答，我是想在切换到后台以后音频还继续播放，而视频不进行渲染，降低资源消耗，pause的话音频也暂停了！

**Comment by JavanEu** [comment]
@wbi1987 建议是自己去为ijk加点客制化的逻辑就好了。我也是自己定义了一些ijk没有的处理方式。因为产品需求。

**Comment by bbcallen** [comment]
暂时不支持。

**Comment by ayyb1988** [comment]
@JavanEu  能开源下自定义的这块吗？ @wbi1987 在切换到后台以后音频还继续播放，而视频不进行渲染，降低资源消耗，我也有这种需求

**Comment by ayyb1988** [comment]
videoview 中添加 mMediaPlayer.setKeepInBackground(true);不起作用

**Comment by Android4MediaPlayer** [comment]
@ayyb1988 修改下 当在后台的时候视频不render

**Comment by bbcallen** [comment]
Feature added
