### ISSUE TITLE
iOS端,播放m3u8视频的时候,拖动进度条后一直卡住,很久后才继续播放

### ISSUE THREAD

**Issue by NNlml** [Bilibili/ijkplayer#2662]
http://vr.tudou.com/v2proxy/v2.m3u8?debug=1&it=264480085&st=5&pw= 播放的是这个.播放后拉动进度条一直在等.

**Comment by raymond1012** [comment]
url is invalid

2017-02-10 14:48 GMT+08:00 NNlml <notifications@github.com>:

**Comment by NNlml** [comment]
..知道了.我再试试
