### ISSUE TITLE
'Range' request header

### ISSUE THREAD

**Issue by CoXier** [Bilibili/ijkplayer#2667]
##  Sohu's server returns 403 
Recently I am working on parsing some videos's address from a web site [Sohu](http://tv.sohu.com/).After parsing,I use **IjkPlayer** to play it.However I get 403 code,with Chi-Hsuan Yen's (A author of youtube-dl) help,I know ‘range' header result in the 403 response code.

Test url:
> http://58.216.27.242/sohu/v1/TmPCo6IsWF6HNJA1eENBetWl0SCRz8bFP86iemsBhYXUyYbSoO2VqVw.mp4?k=CcCnFw&p=XWPIWho70ScAZMoUoTWCr&r=TmI20LscWOo70Sc2ZDASqTPGRD6sfYWSqm8VR5&q=OpCAoEOyzSXWsSCGqLkGhWqDXpCGoLPyoLr3TL1yoSkChRxIWJbtRY6OfONSqD2tWGoUZDk&cip=122.205.8.154

## A Solution

```java
headers.put("Range"," ");
setVideoURI(uri, headers);
```

## However

If I set Range :space,I can't seek this video when I play it on Android Phone.So do you have another solution for 403 code?

Thanks in advance.

**Comment by xinzhengzhang** [comment]
When you set the `Range` header it will replace the normal seek request which caused your seek failed.
For your situation it seems that modify `http.c` and add a blank `Range` header is necessary.

**Comment by CoXier** [comment]
Where is `http.c`  file?

**Comment by CoXier** [comment]
while my project depends ijkplayer,I think modifying `http.c` in `ffmpeg` is not suitable for me.
