### ISSUE TITLE
支持用第三方模块（包下载和解封装）吗

### ISSUE THREAD

**Issue by Android4MediaPlayer** [Bilibili/ijkplayer#267]
相当于不用ffmpeg下载和解封装，用自己模块已拿到完整的音频和视频数据，然后只需调用ijk解码播放

**Comment by bbcallen** [comment]
1. 下载可以用 custom IO
2. 解封装与解码有较多的公共依赖，要拆开工作量比较大，可以参考VLC

**Comment by Android4MediaPlayer** [comment]
1.有参考例子吗？
2.有哪些地方耦合比较大？有计划做吗？

**Comment by bbcallen** [comment]
1. http://git.videolan.org/?p=vlc.git;a=tree;f=modules/demux/avformat;h=8de88da2ed8edca2d2bd51691f72809f71311969;hb=HEAD
2. 见 ff_ffplay.c 里解封装到解码的流程。没有计划。

**Comment by Android4MediaPlayer** [comment]
1.没看到例子
2.可以做成插件形式，扩展性很好

**Comment by bbcallen** [comment]
1.这是VLC用custom IO从ffmpeg接管io的代码。
2."扩展性很好"的目的是什么?

**Comment by Android4MediaPlayer** [comment]
1.那好好看下
2.添加第三方解码库或者流协议解封装，接入很简单了，也比较快，通过注册下就可以了

**Comment by Android4MediaPlayer** [comment]
@bbcallen 接管IO的有DEMO使用么

**Comment by bbcallen** [comment]
那么你应该扩展ffmpeg，而不是扩展ijkplayer

**Comment by Android4MediaPlayer** [comment]
不一样的

**Comment by bbcallen** [comment]
ffmpeg 的解码，封装，IO协议，都是通过你所说的"注册下就可以了"的方式集成的。

**Comment by Android4MediaPlayer** [comment]
比如mediacodec videotoolbox这些 太自定义了 没法从ffmpeg端来做，不然每加一个要套入ffmpeg

**Comment by bbcallen** [comment]
ijkplayer里，MediaCodec VideoToolbox 主要的工作量都是和ffmpeg集成，如果抛开ffmpeg，那么你所要做的，就是与你自己定义的流程，数据结构，API等重新集成一遍。

**Comment by Android4MediaPlayer** [comment]
明白了，就是不用ffplay这一套了，所有的要重新架构一遍了，工作量还是不小，那暂时还是考虑添加个custom IO还是可以的，我主要想法还是想把ijk做强大，万能的东东

**Comment by bbcallen** [comment]
强大，万能不是 ijkplayer 的目标。
ijkplayer 的目标是简单，易用。

VLC的目标倒的确是强大，万能。不过 VLC 的 Android/iOS 版本我改不动了。

**Comment by Android4MediaPlayer** [comment]
主要还是想能有比较好的扩展性，暂时就这样罗
