### ISSUE TITLE
`getCurrentPosition` method returns different results

### ISSUE THREAD

**Issue by CoXier** [Bilibili/ijkplayer#2673]
I listen the player's progress until it completes.I print the position log:

> 02-14 09:21:11.185 3920-3920/com.hustunique.jianguo.parsingplayer D/TAG: 178013
02-14 09:21:12.173 3920-3920/com.hustunique.jianguo.parsingplayer D/TAG: 179010
02-14 09:21:13.176 3920-3920/com.hustunique.jianguo.parsingplayer D/TAG: 180014
02-14 09:21:14.181 3920-3920/com.hustunique.jianguo.parsingplayer D/TAG: 181016
02-14 09:21:15.169 3920-3920/com.hustunique.jianguo.parsingplayer D/TAG: 181977
02-14 09:21:15.201 3920-3920/com.hustunique.jianguo.parsingplayer D/TAG: 182026
02-14 09:21:16.179 3920-3920/com.hustunique.jianguo.parsingplayer D/TAG: 183018
02-14 09:21:17.164 3920-3920/com.hustunique.jianguo.parsingplayer D/TAG: 184001
02-14 09:21:18.177 3920-3920/com.hustunique.jianguo.parsingplayer D/TAG: 185013
02-14 09:21:19.176 3920-3920/com.hustunique.jianguo.parsingplayer D/TAG: 186005
02-14 09:21:20.173 3920-3920/com.hustunique.jianguo.parsingplayer D/TAG: 187002
02-14 09:21:21.172 3920-3920/com.hustunique.jianguo.parsingplayer D/TAG: 188001

As you see,when the player completes this video,the method `getCurrentPosition` returns `188001`.

However when I invoke this method again after the player completes,the Log is:

> 02-14 09:22:21.336 3920-3920/com.hustunique.jianguo.parsingplayer D/TAG: 185753

Why this time returns `185753`?So strange.Obviously `185753` is around 3 seconds less than `188001`.

**Comment by raymond1012** [comment]
because sometime audio is longer than video, but ijk synchronize by audio
time

2017-02-14 9:29 GMT+08:00 CoXier <notifications@github.com>:

**Comment by CoXier** [comment]
If so,how does `188001` happen?

**Comment by raymond1012** [comment]
sorry, the previous reply is wrong, I have reproduced through 120fps sample
stream. The root cause of this issue is decode frame slower than audio
ouput, so audio is done, video still refresh， av_gettime_relative also
increases,
but the clock will be set right value when play completed, because state is
pause. you can flush video when audio is done.

2017-02-14 15:57 GMT+08:00 CoXier <notifications@github.com>:
