### ISSUE TITLE
init-android.sh中IJK_FFMPEG_COMMIT=ff3.2--ijk0.7.6--20170203--001中我在github上没发现这个版本

### ISSUE THREAD

**Issue by Kfreedo** [Bilibili/ijkplayer#2682]
IJK_FFMPEG_COMMIT=ff3.2--ijk0.7.6--20170203--001
在https://github.com/Bilibili/FFmpeg.git 中没有发现这个分支；

如果这个是一次提交，如何查看这次提交？ 
我用git log 没有看到

**Comment by raymond1012** [comment]
IJK_FFMPEG_COMMIT=ff3.2--ijk0.7.6--20170203--001  是 tag name
