### ISSUE TITLE
ios8设备shutdown 延迟

### ISSUE THREAD

**Issue by remantou** [Bilibili/ijkplayer#269]
在ios8的设备上 退出播放器界面 shut down之后
ijkmp_stop()
ijkmp_stop()=0
ijkmp_stop()
ijkmp_stop()=0
ijkmp_stop()
aout_close_audio()
ijkmp_stop()=0
ijkmp_shutdown_l()
wait for read_tid

会在这个"wait for read_tid"之后停留很短时间 然后才会出现
wait for video_refresh_tid
SDL_Overlay(ffmpeg): overlay_free_l(0x1704982e0)
SDL_Overlay(ffmpeg): overlay_free_l(0x174490310)
SDL_Overlay(ffmpeg): overlay_free_l(0x1704962b0)
ijkmp_shutdown_l()=void
ijkmp_dec_ref(): ref=0
ijkmp_shutdown_l()
ijkmp_shutdown_l()=void
aout_close_audio()

导致主线程好像被阻塞了很短一段时间 表现就试 退出来之后 很短时间内界面不能响应 请问这是什么原因？但是在IOS7的设备上很正常 shutdown非常快

**Comment by bbcallen** [comment]
Master上的代码么？还是最后的tag？

**Comment by remantou** [comment]
ff_ffplay.c中 这部分
static void stream_close(VideoState *is)
{
    /* XXX: use a special url_shutdown call to abort parse cleanly */
    is->abort_request = 1;
    packet_queue_abort(&is->videoq);
    packet_queue_abort(&is->audioq);
    ALOGW("wait for read_tid\n");
    SDL_WaitThread(is->read_tid, NULL);
    ALOGW("wait for video_refresh_tid\n");
    SDL_WaitThread(is->video_refresh_tid, NULL);
 
控制台出现 wait for read_tid之后 卡了一会儿 才出现 wait for video_refresh_tid 好像是SDL_WaitThread(is->read_tid, NULL)阻塞了主线程？

**Comment by remantou** [comment]
master上的

**Comment by bbcallen** [comment]
需要一个靠谱的异步 shutdown 。

**Comment by remantou** [comment]
怎么入手啊

**Comment by Zard1096** [comment]
在
- (void)shutdownWaitStop:(VVIJKFFMoviePlayerController *) mySelf
中,可能是返回主线程进行关闭导致了阻塞，
[self performSelectorOnMainThread:@selector(shutdownClose:) withObject:self waitUntilDone:YES];
我尝试用一个子线程控制关闭，并在dealloc中释放掉该线程
closeThread = [[NSThread alloc] initWithTarget:self selector:@selector(shutdownClose:) object:self];
[closeThread setName:@"CloseIJK"];
[closeThread start];
就能在不影响主线程的情况下进行关闭。
暂时没有调试出有什么问题，dealloc也能正常触发，如有不对希望指正

**Comment by remantou** [comment]
会崩溃
<img width="946" alt="2015-07-14 2 20 31" src="https://cloud.githubusercontent.com/assets/8045375/8667524/92e06902-2a33-11e5-9fc3-d37d78e48519.png">

**Comment by Zard1096** [comment]
这我就不清楚了，我用的代码不是最新的，最新的master上有可能在这部分上有修改

**Comment by wqmijkplayer** [comment]
求助：
      ijkplayer有设计文档吗？
谢谢

**Comment by gpr321** [comment]
请问异步shutdown流程是否合理？
- (void)shutdown
{
    if (!_mediaPlayer)
        return;

    __weak IJKFFMoviePlayerController *wself = self;
    dispatch_async(_operationQueue, ^{
        __strong IJKFFMoviePlayerController *strongself = wself;
        [strongself shutdownWaitStop:strongself];
    });
//    [self performSelectorInBackground:@selector(shutdownWaitStop:) withObject:self];
}

- (void)shutdownWaitStop:(IJKFFMoviePlayerController *) mySelf
{
    if (!_mediaPlayer)
        return;
    ijkmp_stop(_mediaPlayer);
    
    [self shutdownClose:self];
    
//    [self performSelectorOnMainThread:@selector(shutdownClose:) withObject:self waitUntilDone:YES];
}

- (void)shutdownClose:(IJKFFMoviePlayerController *) mySelf
{
    if (!_mediaPlayer)
        return;
    
    ijkmp_shutdown(_mediaPlayer);
    ijkmp_set_weak_thiz(_mediaPlayer, nil);
    ijkmp_dec_ref_p(&_mediaPlayer);
}

**Comment by gpr321** [comment]
由于之前使用shutdownWaitStop经常会卡住主线程，因此改动如上，但不知道会不会破坏播放器的整体平衡

**Comment by bbcallen** [comment]
I don't know.
Blocked shutdown is intended, since I haven't tested multiple instances of ijkplayer on iOS.

ijkplayer itself is safe for multiple instance.
The only concern of "multiple instances of ijkplayer on iOS." is about the API limit ( if there are any ), e.g. audio session, VideoToolbox context, gles context, appIdleTimeout.

In the other words, feel free to use like that if you have tested it enough.

**Comment by remantou** [comment]
最新的似乎已经解决了这个问题 现在shutdown没有延迟了 另外 @Zard1096 我之前试过异步处理 但是重复快速进 退播放器测试时 我这边会crash。。

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
