### ISSUE TITLE
android ffmpeg添加水印没有透明

### ISSUE THREAD

**Issue by kria113** [Bilibili/ijkplayer#2690]
编译ffmpeg.c相关代码，连接libijkffmpeg.so
传入ffmpeg.c main参数为：
ffmpeg  -r 15 -i  /sdcard/video0.h264 -i /sdcard/water.png -filter_complex overlay=x=10:y=10 -y /sdcard/join.mp4
得到的join.mp4文件的水印是黑色背景的，相同命令在windows上面测试水印是透明的；
编译configure添加了对png的支持
这是什么原因呢？

**Comment by adamchen0510** [comment]
麻烦问下你这个问题解决了吗？

**Comment by adamchen0510** [comment]
我刚才找到问题了，我是自己交叉编译的原生ffmpeg，没用这个ijkplayer，本来编译的时候加了一个选项减少so size：-disable-swscale-alpha，去掉这个选项就好了，或许你碰到的是一个问题

**Comment by adamchen0510** [comment]
我看了ijkplayer的代码，是一样的。
在config/module.sh中也是使用了-disable-swscale-alpha

**Comment by kria113** [comment]
最后没有使用ffmpeg贴图方法，因为会涉及到编解码太慢了，所以我用了ndk的硬件编码，贴图部分是我自己写的，对于需要贴图的png我初始化数据后对数据做了一些计算(贴图保持不变)，然后与背景图根据a通道对rgb值计算出来的，看了下与ffmpeg里面的方式一致，只是我做了png数据前期计算，会快一点。
