### ISSUE TITLE
ffmpeg连接第三方的动态库产生的问题

### ISSUE THREAD

**Issue by java-Xs** [Bilibili/ijkplayer#2698]
首先更改了ffmpeg的部分源码；目的是链接第三方库；在执行第一个脚本时，下载到本地ffmpeg源码；然后不同平台的架构也用下载好的ffmpeg源码。这个是修改了脚本；然后再执行compile-ijk.sh脚本时；产生了jik动态库的错误，关于这脚本，我没有修改过；想不通是哪里出了问题，看看有没有同样的朋友遇到过这个问题
问题log如下：profiler build: NO
[armeabi-v7a] Prebuilt       : libijkffmpeg.so <= /home/paul/Development/test-ijkplayer/ijkplayer-master/android/contrib/build/ffmpeg-armv7a/output/
[armeabi-v7a] Install        : libijkffmpeg.so => libs/armeabi-v7a/libijkffmpeg.so
[armeabi-v7a] SharedLibrary  : libijksdl.so
[armeabi-v7a] SharedLibrary  : libijkplayer.so
/home/paul/Development/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ff_ffplay_def.h:768: error: undefined reference to 'av_application_closep'
/home/paul/Development/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ff_ffplay_def.h:768: error: undefined reference to 'av_application_closep'
/home/paul/Development/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:3327: error: undefined reference to 'av_application_closep'
/home/paul/Development/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:3328: error: undefined reference to 'av_application_open'
/home/paul/Development/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ijkavformat/allformats.c:78: error: undefined reference to 'ijkav_register_ijkmediadatasource_protocol'
/home/paul/Development/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ijkavformat/allformats.c:80: error: undefined reference to 'ijkav_register_async_protocol'
/home/paul/Development/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ijkavformat/allformats.c:81: error: undefined reference to 'ijkav_register_ijklongurl_protocol'
/home/paul/Development/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ijkavformat/allformats.c:82: error: undefined reference to 'ijkav_register_ijktcphook_protocol'
/home/paul/Development/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ijkavformat/allformats.c:83: error: undefined reference to 'ijkav_register_ijkhttphook_protocol'
/home/paul/Development/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ijkavformat/allformats.c:84: error: undefined reference to 'ijkav_register_ijksegment_protocol'
/home/paul/Development/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ijkavformat/ijklivehook.c:58: error: undefined reference to 'av_application_on_io_control'
/home/paul/Development/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ijkavformat/ijklivehook.c:58: error: undefined reference to 'av_application_on_io_control'
/home/paul/Development/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ijkavformat/async.c:193: error: undefined reference to 'av_application_on_async_statistic'
/home/paul/Development/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ijkavformat/async.c:208: error: undefined reference to 'av_application_on_async_read_speed'
/home/paul/Development/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ijkavformat/async.c:193: error: undefined reference to 'av_application_on_async_statistic'
/home/paul/Development/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ijkavformat/async.c:193: error: undefined reference to 'av_application_on_async_statistic'
/home/paul/Development/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ijkavformat/async.c:193: error: undefined reference to 'av_application_on_async_statistic'
/home/paul/Development/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ijkavformat/ijkurlhook.c:67: error: undefined reference to 'av_application_on_io_control'
/home/paul/Development/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ijkavformat/ijksegment.c:59: error: undefined reference to 'av_application_on_io_control'
collect2: error: ld returned 1 exit status
/home/paul/Development/android-ndk-r12b/build/core/build-binary.mk:677: recipe for target '/home/paul/Development/test-ijkplayer/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/obj/local/armeabi-v7a/libijkplayer.so' failed
make: *** [/home/paul/Development/test-ijkplayer/ijkplayer-master/android/ijkplayer/ijkplayer-armv7a/src/main/obj/local/armeabi-v7a/libijkplayer.so] Error 1
/home/paul/Development/test-ijkplayer/ijkplayer-master/android

**Comment by Android4MediaPlayer** [comment]
应该ffmpeg问题，最近发现一个很好的交流群，547962153，加入与更多伙伴交流吧

**Comment by java-Xs** [comment]
不对    ffmpeg动态库已经生成的了

**Comment by WangFeiF** [comment]
我在使用ijk的时候也遇到了相同的问题，我是讲自己的编的ffmpeg库，放在了ijk项目中，会找不到这个方法。不知道对你有没有用，可以和我交流 Q：422967883

**Comment by ximencx** [comment]
@java-Xs @WangFeiF 我也遇到了这个问题 请问怎么解决呢

**Comment by laixh** [comment]
ffmpeg armv7的没有这些接口定义，把arm64文件对应的接口移植到armv7就行
