### ISSUE TITLE
有没有官方的一个ios工程引入ijkplayer

### ISSUE THREAD

**Issue by HatsuneMikuV** [Bilibili/ijkplayer#2699]
网上看到好多  工程导入   但是操作起来   总是出现点问题     想知道官方有木有靠谱点的文档教程

**Comment by raymond1012** [comment]
see README

**Comment by HatsuneMikuV** [comment]
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install git
brew install yams

我卡在这个地方，

xinpure:~ mt$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
xinpure:~ mt$ brew install git
touch: /usr/local/Homebrew/.git/FETCH_HEAD: Permission denied
touch: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.git/FETCH_HEAD: Permission denied
fatal: Unable to create '/usr/local/Homebrew/.git/index.lock': Permission denied
error: could not lock config file .git/config: Permission denied
You can link formula with `brew link git`
Warning: git-2.10.2 already installed, it's just not linked

**Comment by allentsing** [comment]
直接用封装好的.framework文件，去我的GitHub看，https://github.com/allentsing/ATijkplayeriOS
