### ISSUE TITLE
ios使用module-default.sh配置无法播放rtsp

### ISSUE THREAD

**Issue by longa** [Bilibili/ijkplayer#270]
流媒体服务器使用live555，module-default.sh配置

报错信息：
[rtsp @ 0x1288a1c00] Unable to open RTSP for listening
rtsp://192.168.1.254/xxxx.mov: Can't assign requested address

求解，求解。

**Comment by longa** [comment]
补充，FFmpeg官网下载的ffplay可以正常播放

**Comment by bbcallen** [comment]
看起来像测试环境的问题，google 一下 EADDRNOTAVAIL 相关的问题。

**Comment by longa** [comment]
好的，我先google一下

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
