### ISSUE TITLE
Android .ass Subtitles

### ISSUE THREAD

**Issue by migueltarga** [Bilibili/ijkplayer#2700]
I recently noticed that you guys added the support for .ass subtitles...
How do I use it? Is it a ffmpeg argument?

Thank you!

**Comment by eseffair** [comment]
@migueltarga, I have the same doubt....

Thanks in advance for any reply.

**Comment by yuazhen** [comment]
Did you mean PR #2450 ? It currently only support ass substream which means a dedicate subtitle stream is required in a movie file and the subtitle stream is being parsed in ff_ffplay.c not in java layer.
This feature can be enabled by call ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "subtitle", 1);

**Comment by migueltarga** [comment]
Oh, I see!
Thank you for the explanation. By the way, this is a nice feature! thanks.

**Comment by Android4MediaPlayer** [comment]
@migueltarga can give us sample url?

**Comment by Peterede** [comment]
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "subtitle", 1); should be added to the example player
