### ISSUE TITLE
OMX.Exynos.AVC.Decoder hardware decode doesn't work

### ISSUE THREAD

**Issue by jpxiong** [Bilibili/ijkplayer#271]
I use the android native player, the logs as following:

06-09 13:41:41.541 I/OMXCodec( 2354): Attempting to allocate OMX node 'OMX.Exynos.AVC.Decoder'
06-09 13:41:41.566 I/OMXCodec( 2354): Successfully allocated OMX node 'OMX.Exynos.AVC.Decoder'
06-09 13:41:41.566 I/OMXCodec( 2354): [OMX.Exynos.AVC.Decoder] AVC profile = 100 (High), level = 50
06-09 13:41:41.571 I/OMXCodec( 2354): [OMX.Exynos.AVC.Decoder] video dimensions are 2048 x 1152
06-09 13:41:41.616 I/OMXCodec( 2354): Attempting to allocate OMX node 'OMX.google.aac.decoder'
06-09 13:41:41.621 I/OMXCodec( 2354): Successfully allocated OMX node 'OMX.google.aac.decoder'
06-09 13:41:41.731 I/OMXCodec( 2354): [OMX.Exynos.AVC.Decoder] video dimensions are 2048 x 1152
06-09 13:41:41.731 I/OMXCodec( 2354): [OMX.Exynos.AVC.Decoder] Crop rect is 2048 x 1152 @ (0, 0)

the cpu usage is only about <= 10%

But use the ijkplayer, the cpu usage is 50% sometimes.

So how to enable the hardware decode?

**Comment by xqq** [comment]
Have you called IjkMediaPlayer.setMediaCodecEnabled(true) ?

**Comment by jpxiong** [comment]
Yes. I missed it. If I want to add a new decoder, how to do it ? Thanks.

**Comment by xqq** [comment]
In most cases, ijkplayer will select the most suitable hardware OMX decoder.
If the selection doesn't match your expectation, add your expected decoder name to IjkMediaCodecInfo.java and set a suitable rank.

Report here if you found ijkplayer has wrong decoder selection.

**Comment by jpxiong** [comment]
@xqq Thanks. In fact, I want to know the rank. That means, how to set the suitable rank ? As I know, there is RANK_TESTED, RANK_LAST_CHANCE... I have no idea about setting a suitable rank. Any suggestion is preferred. Thanks again.

**Comment by xqq** [comment]
I don't understand your requirements.

RANK_TESTED means it's a tested stable hardware decoder.
Set your decoder to RANK_MAX to force use it.

ijkplayer will choose the highest rank decoder at last, which matches your video minetype.

**Comment by jpxiong** [comment]
@xqq Got it. Thanks for your great help.
