### ISSUE TITLE
Android RTSP Protocol not found

### ISSUE THREAD

**Issue by DKKovalev** [Bilibili/ijkplayer#2710]
Hello, i'm trying to use this library to get the stream using RTSP protocol. But i get this error: "E/IJKMEDIA: rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov: Protocol not found"
Here's my steps:
1. Compile library using Build Guide from Readme
2. Get `libijkffmpeg.so` from `ijkplayer-android -> android -> ijkplayer -> ijkplayer-armv7a -> src -> libs`
3. Put `libijkffmpeg.so` in `jnilibs` folder
4. Add `compile 'tv.danmaku.ijk.media:ijkplayer-java:0.7.7.1'
            compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.7.7.1'` to `build.gradle`
I tried to change `module.sh` to `module-default.sh` and `module-lite.sh`. Also i tried to add `export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=rtp"` and `export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=rtsp"` but it didn't solve my problem.

**Comment by zupper** [comment]
@DKKovalev did you manage to find out what the problem was? Did you resolve it?
