### ISSUE TITLE
直播首开都在1S左右，hls点播首开经常达到4s+。

### ISSUE THREAD

**Issue by zhanggao** [Bilibili/ijkplayer#2712]
点播的首开能优化吗？参数应该如何设置？

**Comment by zhanggao** [comment]
点播断网后需要重连，重连调用IjkVideoView.setVideoPath有时候也耗时4s+。

**Comment by raymond1012** [comment]
please check http speed

2017-02-19 17:08 GMT+08:00 zhanggao <notifications@github.com>:

**Comment by xiaohuihui000** [comment]
这个问题解决了吗？首开耗时挺长的

**Comment by lrs0304** [comment]
换好点的CDN，秒开分分钟的事

**Comment by zhanggao** [comment]
@lrs0304 不换 cdn 能优化回放的打开速度不？ 换cdn不现实，用到很多家的。
