### ISSUE TITLE
Multiple SurfaceViews in one activity

### ISSUE THREAD

**Issue by DKKovalev** [Bilibili/ijkplayer#2713]
Hello, i'm trying to create an app that allows users to see rtsp streams from multiple sources in one screen. I created custom RecyclerView adapter with SurfaceViews as items and started `IjkMediaPlayer` in `onBindViewHolder()` method. But only last item plays the stream. How can i achieve multiple instances in one screen?

**Comment by raymond1012** [comment]
I think you only set the last surface to ijk, By the way, ijkplayer can't
support multiple surface at the same time

2017-02-19 17:40 GMT+08:00 Kovalev Dmitriy <notifications@github.com>:

**Comment by DKKovalev** [comment]
@raymond1012 thanks for reply. I figured why only last surface contained the stream and achieved multiple surfaces in one screen by using RecyclerView. But i've got another issue. When i imported modules ijkplayer-java and ijkplayer-armv7a in empty project, everything works fine. But when i'm doing the same to my work project, it's crashing with error `UnsatisfiedLinkError couldn't find "libijkffmpeg.so"`

**Comment by raymond1012** [comment]
1. because ijk will use the last surface
2. libijkffmpeg.so need to be compiled

2017-02-20 19:56 GMT+08:00 Kovalev Dmitriy <notifications@github.com>:

**Comment by DKKovalev** [comment]
To compile library, i used the guide from [Readme](https://github.com/Bilibili/ijkplayer/blob/master/README.md), except, i added the line to enable rtsp demux and rtp protocol. After compilation i opened my project and added ijkplayer-java and ijkplayer-armv7a as modules and added those modules to project dependencies. Did i miss some step? Because if i create a brand new project and do the exact same steps, everything's working like charm

**Comment by lamantinv** [comment]
@DKKovalev How did you achieve multiple surfaces to render different videos? Could you share your code or at least some idea to start?
