### ISSUE TITLE
编译成功后，真机测试出现问题，求救啊

### ISSUE THREAD

**Issue by HatsuneMikuV** [Bilibili/ijkplayer#2716]
!!!!!!!!!!
actual: N-80227-g653751a
 expect: ff3.2--ijk0.7.6--20170203--001

!!!!!!!!!!
av_version_info: N-80227-g653751a
ijk_version_info: k0.7.7.1-3-geb265a5
ijkmp_set_inject_opaque(0x1459b7250)
ijkmp_set_inject_opaque()=void
ijkmp_set_ijkio_inject_opaque(0x1459b7250)
ijkmp_set_ijkio_inject_opaque()=void
2017-02-20 13:54:30.279 GuluGulu[61363:2508385] OK setup GL
ijkmp_ios_set_view(glView=0x145d934e0)
ijkmp_ios_set_view(glView=0x145d934e0)=void

**Comment by HatsuneMikuV** [comment]
因为工程中使用到了七牛的播放器作为直播，现在因为要播放片段视屏（一组url），自己使用ijk实现了concat协议，但是底层都用到了ffmpeg，因为这个问题冲突了，导致的这个问题，二现在七牛并不支持concat协议，不知道有什么办法解决吗？

**Comment by HatsuneMikuV** [comment]
!!!!!!!!!!
actual: N-80227-g653751a
 expect: ff3.1--ijk0.6.2--20160926--001

!!!!!!!!!!
av_version_info: N-80227-g653751a
ijk_version_info: 
ijkmp_set_inject_opaque(0x138a01640)
ijkmp_set_inject_opaque()=void
2017-02-20 20:33:47.324 GuluGulu[2356:90728] OK setup GL
ijkmp_ios_set_view(glView=0x1392db9b0)
ijkmp_ios_set_view(glView=0x1392db9b0)=void
2017-02-20 20:33:47.328 GuluGulu[2356:90728] invalidateRenderBuffer
ijkmp_set_data_source(url="/var/containers/Bundle/Application/FF8F3189-4BAB-4294-8F25-92974045392C/GuluGulu.app/test.concat")
ijkmp_set_data_source(url="/var/containers/Bundle/Application/FF8F3189-4BAB-4294-8F25-92974045392C/GuluGulu.app/test.concat")=0
ijkmp_prepare_async()
===== versions =====
[FFPlayer @ 0x139015d00] ijkplayer    : 
[FFPlayer @ 0x139015d00] FFmpeg       : N-80227-g653751a
[FFPlayer @ 0x139015d00] libavutil    : 55.24.100
[FFPlayer @ 0x139015d00] libavcodec   : 57.44.101
[FFPlayer @ 0x139015d00] libavformat  : 57.37.101
[FFPlayer @ 0x139015d00] libswscale   : 4.1.100
[FFPlayer @ 0x139015d00] libswresample: 2.0.101
===== options =====
[FFPlayer @ 0x139015d00] player-opts : video-pictq-size             = 3
[FFPlayer @ 0x139015d00] player-opts : overlay-format               = fcc-_es2
[FFPlayer @ 0x139015d00] player-opts : protocol_whitelist           = ffconcat,file,http,https
[FFPlayer @ 0x139015d00] player-opts : max-fps                      = 30
[FFPlayer @ 0x139015d00] player-opts : framedrop                    = 0
[FFPlayer @ 0x139015d00] player-opts : videotoolbox-max-frame-width = 960
[FFPlayer @ 0x139015d00] player-opts : videotoolbox                 = 0
[FFPlayer @ 0x139015d00] player-opts : start-on-prepared            = 1
[FFPlayer @ 0x139015d00] format-opts : ijkapplication               = 5253566000
[FFPlayer @ 0x139015d00] format-opts : protocol_whitelist           = concat,http,tcp,https,tls,file
[FFPlayer @ 0x139015d00] format-opts : user-agent                   = ijkplayer
[FFPlayer @ 0x139015d00] format-opts : auto_convert                 = 0
[FFPlayer @ 0x139015d00] format-opts : timeout                      = 30000000
[FFPlayer @ 0x139015d00] format-opts : reconnect                    = 1
[FFPlayer @ 0x139015d00] format-opts : safe                         = 0
===================
2017-02-20 20:33:47.328 GuluGulu[2356:90853] IJKSDLGLView: setupDisplay not ready
ijkmp_prepare_async()=0
[AVIOContext @ 0x1392c6590] Statistics: 336 bytes read, 0 seeks
/var/containers/Bundle/Application/FF8F3189-4BAB-4294-8F25-92974045392C/GuluGulu.app/test.concat: Invalid data found when processing input
2017-02-20 20:33:47.344 GuluGulu[2356:90728] invalidateRenderBuffer
2017-02-20 20:33:47.345 GuluGulu[2356:90853] IJKSDLGLView: setupDisplay not ready
2017-02-20 20:33:47.355 GuluGulu[2356:90728] invalidateRenderBuffer
2017-02-20 20:33:47.355 GuluGulu[2356:90853] IJKSDLGLView: setupDisplay not ready
2017-02-20 20:33:47.412 GuluGulu[2356:90728] FFP_MSG_ERROR: 0
2017-02-20 20:33:47.413 GuluGulu[2356:90728] IJKMPMoviePlayBackStateDidChange 2: paused
2017-02-20 20:33:47.414 GuluGulu[2356:90728] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1

**Comment by raymond1012** [comment]
/var/containers/Bundle/Application/FF8F3189-4BAB-4294-8F25-92974045392C/GuluGulu.app/test.concat:
Invalid data found when processing input

2017-02-20 20:34 GMT+08:00 Icarus <notifications@github.com>:

**Comment by HatsuneMikuV** [comment]
已经解决   谢谢大大们的帮助

**Comment by graveliang** [comment]
想问一下是怎样解决的，麻烦楼主了

**Comment by RegenHo** [comment]
我也遇到了相同的问题，请问你是如何解决的？

**Comment by HatsuneMikuV** [comment]
@graveliang @RegenHo http://blog.csdn.net/liushihua147/article/details/60962967
