### ISSUE TITLE
Hi，iOS为啥"videotoolbox-max-frame-width" 设置成960呢，是有原因的吗？

### ISSUE THREAD

**Issue by mobileworm** [Bilibili/ijkplayer#2717]
+ (IJKFFOptions *)optionsByDefault
{
    IJKFFOptions *options = [[IJKFFOptions alloc] init];

    [options setPlayerOptionIntValue:30     forKey:@"max-fps"];
    [options setPlayerOptionIntValue:0      forKey:@"framedrop"];
    [options setPlayerOptionIntValue:3      forKey:@"video-pictq-size"];
    [options setPlayerOptionIntValue:0      forKey:@"videotoolbox"];
    [options setPlayerOptionIntValue:960    forKey:@"videotoolbox-max-frame-width"];

    [options setFormatOptionIntValue:0                  forKey:@"auto_convert"];
    [options setFormatOptionIntValue:1                  forKey:@"reconnect"];
    [options setFormatOptionIntValue:30 * 1000 * 1000   forKey:@"timeout"];
    [options setFormatOptionValue:@"ijkplayer"          forKey:@"user-agent"];

    options.showHudView   = NO;

    return options;
}

**Comment by raymond1012** [comment]
仅仅是默认值，你可以根据你的实际情况修改

2017-02-20 15:00 GMT+08:00 mobileworm <notifications@github.com>:

**Comment by mobileworm** [comment]
OK，Thanks
