### ISSUE TITLE
Video playing with no sound 

### ISSUE THREAD

**Issue by idanya** [Bilibili/ijkplayer#272]
Compiled with module-default.sh for android.
videos are playing but with no sound. 
Testing video: http://www.wowza.com/downloads/content/sample.mp4

Log:
    06-11 01:07:38.601  26230-26230/a.b.c D/PhoneWindow﹕ *FMB* isFloatingMenuEnabled mFloatingMenuBtn : null
06-11 01:07:38.601  26230-26230/a.b.c D/PhoneWindow﹕ *FMB* isFloatingMenuEnabled return false
06-11 01:07:38.621  26230-26417/a.b.c D/mali_winsys﹕ new_window_surface returns 0x3000,  [1440x2560]-format:1
06-11 01:07:38.651  26230-26230/a.b.c I/MediaPlayer﹕ Need to enable context aware info
06-11 01:07:38.651  26230-26230/a.b.c V/MediaPlayer-JNI﹕ native_setup
06-11 01:07:38.651  26230-26230/a.b.c V/MediaPlayer﹕ constructor
06-11 01:07:38.651  26230-26230/a.b.c V/MediaPlayer﹕ setListener
06-11 01:07:38.651  26230-26230/a.b.c V/MediaPlayer-JNI﹕ setAudioStreamType: 3
06-11 01:07:38.651  26230-26230/a.b.c V/MediaPlayer﹕ MediaPlayer::setAudioStreamType
06-11 01:07:38.661  26230-26230/a.b.c V/MediaPlayer﹕ setVideoSurfaceTexture
06-11 01:07:38.661  26230-26230/a.b.c V/MediaPlayer-JNI﹕ setVolume: left 1.000000  right 1.000000
06-11 01:07:38.661  26230-26230/a.b.c V/MediaPlayer﹕ MediaPlayer::setVolume(1.000000, 1.000000)
06-11 01:07:38.661  26230-26230/a.b.c V/MediaPlayer-JNI﹕ setAudioStreamType: 3
06-11 01:07:38.661  26230-26230/a.b.c V/MediaPlayer﹕ MediaPlayer::setAudioStreamType
06-11 01:07:38.661  26230-26230/a.b.c V/MediaPlayer﹕ setVideoSurfaceTexture
06-11 01:07:38.661  26230-26230/a.b.c V/MediaPlayer﹕ prepareAsync
06-11 01:07:38.661  26230-26480/a.b.c I/System.out﹕ (HTTPLog)-Static: isSBSettingEnabled false
06-11 01:07:38.731  26230-26230/a.b.c I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@25cb31f4 time:20078892
06-11 01:07:38.731  26230-26230/a.b.c I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@3bb0d9e7 time:20078892
06-11 01:07:38.891  26230-26480/a.b.c I/System.out﹕ KnoxVpnUidStorageknoxVpnSupported API value returned is false
06-11 01:07:39.001  26230-26230/a.b.c V/ActivityThread﹕ updateVisibility : ActivityRecord{1876cb8c token=android.os.BinderProxy@3bb0d9e7 {a.b.c/a.b.c.activities.MainActivity}} show : false
06-11 01:07:39.201  26230-26480/a.b.c V/MediaHTTPConnection﹕ mTotalSize is 39115156
06-11 01:07:39.201  26230-26482/a.b.c D/MediaHTTPConnection﹕ setReadTimeOut =  30000ms
06-11 01:07:39.761  26230-26230/a.b.c I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@25cb31f4 time:20079921
06-11 01:07:40.161  26230-26245/a.b.c D/MediaHTTPConnection﹕ setReadTimeout with 30000ms
06-11 01:07:40.161  26230-26245/a.b.c I/System.out﹕ (HTTPLog)-Static: isSBSettingEnabled false
06-11 01:07:40.161  26230-26245/a.b.c I/System.out﹕ KnoxVpnUidStorageknoxVpnSupported API value returned is false
06-11 01:07:41.281  26230-26245/a.b.c D/MediaHTTPConnection﹕ setReadTimeout with 30000ms
06-11 01:07:41.281  26230-26245/a.b.c I/System.out﹕ (HTTPLog)-Static: isSBSettingEnabled false
06-11 01:07:41.281  26230-26245/a.b.c I/System.out﹕ KnoxVpnUidStorageknoxVpnSupported API value returned is false
06-11 01:07:41.581  26230-26245/a.b.c V/MediaHTTPConnection﹕ mTotalSize is 39115156
06-11 01:07:42.691  26230-26245/a.b.c D/MediaHTTPConnection﹕ setReadTimeout with 30000ms
06-11 01:07:42.691  26230-26245/a.b.c I/System.out﹕ (HTTPLog)-Static: isSBSettingEnabled false
06-11 01:07:42.691  26230-26245/a.b.c I/System.out﹕ KnoxVpnUidStorageknoxVpnSupported API value returned is false
06-11 01:07:44.851  26230-26244/a.b.c V/MediaPlayer﹕ message received msg=200, ext1=972, ext2=0
06-11 01:07:44.851  26230-26244/a.b.c W/MediaPlayer﹕ info/warning (972, 0)
06-11 01:07:44.851  26230-26244/a.b.c V/MediaPlayer﹕ callback application
06-11 01:07:44.851  26230-26244/a.b.c V/MediaPlayer﹕ back from callback
06-11 01:07:44.851  26230-26244/a.b.c V/MediaPlayer﹕ message received msg=5, ext1=424, ext2=240
06-11 01:07:44.861  26230-26244/a.b.c V/MediaPlayer﹕ New video size 424 x 240
06-11 01:07:44.861  26230-26244/a.b.c V/MediaPlayer﹕ callback application
06-11 01:07:44.861  26230-26244/a.b.c V/MediaPlayer﹕ back from callback
06-11 01:07:44.861  26230-26244/a.b.c V/MediaPlayer﹕ message received msg=1, ext1=0, ext2=0
06-11 01:07:44.861  26230-26244/a.b.c V/MediaPlayer﹕ prepared
06-11 01:07:44.861  26230-26244/a.b.c V/MediaPlayer﹕ callback application
06-11 01:07:44.861  26230-26244/a.b.c V/MediaPlayer﹕ back from callback
06-11 01:07:44.861  26230-26230/a.b.c E/MediaPlayer﹕ Should have subtitle controller already set
06-11 01:07:44.861  26230-26230/a.b.c I/initVideo﹕ onPrepared called. Starting playback.
06-11 01:07:44.861  26230-26230/a.b.c W/MediaPlayer﹕ this is IMEDIA_PLAYER_VIDEO_EXIST
06-11 01:07:44.871  26230-26230/a.b.c I/MediaPlayer﹕ sendBroadcast android.media.IMediaPlayer.videoexist
06-11 01:07:44.871  26230-26230/a.b.c V/MediaPlayer-JNI﹕ start
06-11 01:07:44.871  26230-26230/a.b.c V/MediaPlayer﹕ start
06-11 01:07:44.951  26230-26245/a.b.c D/MediaHTTPConnection﹕ setReadTimeout with 30000ms
06-11 01:07:44.951  26230-26245/a.b.c I/System.out﹕ (HTTPLog)-Static: isSBSettingEnabled false
06-11 01:07:45.121  26230-26245/a.b.c V/MediaHTTPConnection﹕ mTotalSize is 39115156
06-11 01:07:45.491  26230-26244/a.b.c V/MediaPlayer﹕ message received msg=5, ext1=424, ext2=240
06-11 01:07:45.491  26230-26244/a.b.c V/MediaPlayer﹕ New video size 424 x 240
06-11 01:07:45.491  26230-26244/a.b.c V/MediaPlayer﹕ callback application
06-11 01:07:45.491  26230-26244/a.b.c V/MediaPlayer﹕ back from callback
06-11 01:07:45.491  26230-26244/a.b.c V/MediaPlayer﹕ message received msg=200, ext1=3, ext2=0
06-11 01:07:45.491  26230-26230/a.b.c W/MediaPlayer﹕ this is IMEDIA_PLAYER_VIDEO_EXIST
06-11 01:07:45.501  26230-26244/a.b.c W/MediaPlayer﹕ info/warning (3, 0)
06-11 01:07:45.501  26230-26244/a.b.c V/MediaPlayer﹕ callback application
06-11 01:07:45.501  26230-26230/a.b.c I/MediaPlayer﹕ sendBroadcast android.media.IMediaPlayer.videoexist
06-11 01:07:45.501  26230-26244/a.b.c V/MediaPlayer﹕ back from callback
06-11 01:07:45.501  26230-26244/a.b.c V/MediaPlayer﹕ message received msg=6, ext1=0, ext2=0
06-11 01:07:45.501  26230-26244/a.b.c V/MediaPlayer﹕ Received MEDIA_STARTED
06-11 01:07:45.501  26230-26244/a.b.c V/MediaPlayer﹕ callback application
06-11 01:07:45.501  26230-26244/a.b.c V/MediaPlayer﹕ back from callback
06-11 01:07:45.501  26230-26244/a.b.c V/MediaPlayer﹕ message received msg=200, ext1=702, ext2=0
06-11 01:07:45.501  26230-26230/a.b.c V/MediaPlayer-JNI﹕ getCurrentPosition: 50 (msec)
06-11 01:07:45.501  26230-26230/a.b.c V/MediaPlayer-JNI﹕ isPlaying: 1
06-11 01:07:45.501  26230-26244/a.b.c W/MediaPlayer﹕ info/warning (702, 0)
06-11 01:07:45.501  26230-26244/a.b.c V/MediaPlayer﹕ callback application
06-11 01:07:45.501  26230-26244/a.b.c V/MediaPlayer﹕ back from callback
06-11 01:07:45.851  26230-26244/a.b.c V/MediaPlayer﹕ message received msg=3, ext1=0, ext2=0
06-11 01:07:45.851  26230-26244/a.b.c V/MediaPlayer﹕ buffering 0
06-11 01:07:45.851  26230-26244/a.b.c V/MediaPlayer﹕ callback application
06-11 01:07:45.851  26230-26244/a.b.c V/MediaPlayer﹕ back from callback
06-11 01:07:46.851  26230-26482/a.b.c V/MediaPlayer﹕ message received msg=3, ext1=1, ext2=0
06-11 01:07:46.851  26230-26482/a.b.c V/MediaPlayer﹕ buffering 1
06-11 01:07:46.851  26230-26482/a.b.c V/MediaPlayer﹕ callback application
06-11 01:07:46.851  26230-26482/a.b.c V/MediaPlayer﹕ back from callback
06-11 01:07:47.851  26230-26482/a.b.c V/MediaPlayer﹕ message received msg=3, ext1=1, ext2=0
06-11 01:07:47.851  26230-26482/a.b.c V/MediaPlayer﹕ buffering 1
06-11 01:07:47.851  26230-26482/a.b.c V/MediaPlayer﹕ callback application
06-11 01:07:47.861  26230-26482/a.b.c V/MediaPlayer﹕ back from callback
06-11 01:07:48.851  26230-26482/a.b.c V/MediaPlayer﹕ message received msg=3, ext1=3, ext2=0
06-11 01:07:48.851  26230-26482/a.b.c V/MediaPlayer﹕ buffering 3

**Comment by bbcallen** [comment]
I don't think this log is from IjkMediaPlayer

**Comment by idanya** [comment]
I have imported the ijkmediaplayer project as a library and using AndroidMediaPlayer class the same way I use MediaPlayer from the android sdk... As I doing something wrong ?

**Comment by bbcallen** [comment]
AndroidMediaPlayer is only a wrapper of android.media.MediaPlayer.
IjkMediaPlayer is the wrapper of ffplay.

**Comment by idanya** [comment]
Found it. Thank you. 
It's working now.
