### ISSUE TITLE
Android6.0以下调用setSpeed的问题

### ISSUE THREAD

**Issue by skybdemq** [Bilibili/ijkplayer#2725]
HI
我在6.0以下系统的手机播放视频，视频的帧率为15FPS，调用setSpeed后，播放的速度比设置的快，比如设置0.7倍，实际播放的速度超过1倍。
如果视频的帧率为24FPS，调用setSpeed设置播放速度就不会有上面的问题。
另设置了播放倍速后，视频的声音会变调

**Comment by ctiao** [comment]
提供下这个视频样本 ？

**Comment by skybdemq** [comment]
这是视频的链接，麻烦看看
http://p2-2.talk-fun.com/bGl2ZS8xNDkvMTM3NTEvbXRteG1qZTlvcS8xMzEyMTQ5X3ZpZGVvLWNsaWVudC0xLm1wNHwxODU1MzA5MDM0.mp4?limit=36K&encrypt=1

**Comment by renhui** [comment]
声音变调问题，我在Ijk0.7.9版本调整好了。http://www.cnblogs.com/renhui/p/6510872.html

**Comment by ltpostbox** [comment]
@renhui 你好 我在新的 0.8.4版本 添加了ijkMediaPlayer.setOption(); 跑在华为5.1版本上 还是有变调问题，大神这个怎么解决，跪求思路！

**Comment by ltpostbox** [comment]
已解决

**Comment by ijustkeepmoving** [comment]
@ltpostbox 能分享一下如何使用的吗？
