### ISSUE TITLE
armv7a的版本-mfpu=neon  编译不通过

### ISSUE THREAD

**Issue by agaochen** [Bilibili/ijkplayer#2728]

**Comment by agaochen** [comment]
要让编译出来的库支持neon要怎么写？

**Comment by agaochen** [comment]
INSTALL	libavutil/avconfig.h
INSTALL	libavutil/ffversion.h
INSTALL	libavutil/libavutil.pc

--------------------
[*] link ffmpeg
--------------------
-Wl,--fix-cortex-a8
link compat/*.o
link libavcodec/*.o
link libavcodec/arm/*.o
link libavfilter/*.o
link libavformat/*.o
link libavutil/*.o
link libavutil/arm/*.o
link libswresample/*.o
link libswresample/arm/*.o
link libswscale/*.o
link libswscale/arm/*.o
libavcodec/mpegvideo.c:314: error: undefined reference to 'ff_mpv_common_init_neon'
collect2: error: ld returned 1 exit status

**Comment by agaochen** [comment]
ld没有找到ff_mpv_common_init_neon函数

**Comment by bbcallen** [comment]
run ./configure --help in ffmpeg's directory.

**Comment by agaochen** [comment]
好吧，FF_ASSEMBLER_SUB_DIRS="arm neon"要这样写
