### ISSUE TITLE
separating buffering from decoding/playback

### ISSUE THREAD

**Issue by jpoloczek** [Bilibili/ijkplayer#273]
Hi,

How can I separate in IJPlayer or FFmpeg buffering from decoding and playback?

I would like to create a player based on ijkplayer for my android device (it is limited to 1 hw decoder) that buffers simultaneously (up to buffer filled in 100%) and plays only selected stream.

In such case I would load into many buffers many various audio or video streams without decoding them and then when needed just connect selected buffer with videoview I have (videoview will decode and play them). As mentioned before I can only have one hw decoder so I can have only 1 videoview with hw decoding.

How can I do it? I've heard that it might be done in ffmpeg demuxer.

Best regards,
Janusz

**Comment by bbcallen** [comment]
I don't quite get your idea.
You can recreate new player with new stream in a single videoview.

**Comment by jpoloczek** [comment]
The problem is that on this limited android device I can have only 1 instance of hardware decoder.

So my idea is to make buffering of raw data without decoding them in separate proces and when needed redirect the data for decoding and playback to the only one hardware decoder I have.

I'd like to develop simple app that will switch video streams from IP cameras faster due to finished buffering in the background. In such case I will have for example 2 or 3 buffers only reading data and filling the buffer and when buffer is full pausing buffering.

The proces will look like this:

1)buffering of stream no.1 simultaneously with buffering of stream no.2 and buffering of stream no.3
2) connecting buffer no.2 with hardware decoder
3) start decoding and playing stream no.2
4) when button is pressed switching to next stream no. 3 means that instead of waiting for first TS to be loaded into buffer no.3 I will have already loaded TS in buffer as it has been done before and switching will only connect buffer no.3 with hardware decoder, so switch may be done in miliseconds instead of waiting 2-3 seconds to load data into buffer.

I canot do it traditional way as I only have one hardware decoder available (it has been confirmed by chipset manufacturer), so I need to separate buffering from decoding.

How can I modify IJKplayer of ffmpeg to do it?

**Comment by bbcallen** [comment]
If your stream is streamed over http, you can implement a local http server.
At the back of the local http server, multiple streams are read and saved to local storage.
When you switch stream, you just switch to different local http url.

**Comment by jpoloczek** [comment]
I cannot modify server side and this app will work on HLS streams delivered from different streaming servers spread across the globe.

The only thing that I can modify is my stream player based on IJKPlayer and ffmpeg, so the question is how to separate buffering (reading raw data into buffer without decoding) and separate decoding/playback to be able to choose manualy in my player what buffer (1st , 2nd or 3rd) will be decoded.

**Comment by bbcallen** [comment]
HLS is delivered over http, so local http server would be my choice.

As an alternative, stream_cycle_channel() in ffplay may help you a little.

**Comment by jpoloczek** [comment]
Is is possible to load data to buffer without decoding it and without even assigning decoder to particular stream/buffer?
If it's possible I would be able to modify ffmpeg to send data from selected buffer to 1 decoder I have.

Regarding stream_cycle_channel()  - is there any description available how to use it? I tried to find any description but google returns only junk answers to this topic.

**Comment by bbcallen** [comment]
It's possible, but it's too complicated for ijkplayer.

As I suggested, local http server would be my choice.

**Comment by jpoloczek** [comment]
Hi Bbcallen,

My company has a business proposal for you. Please send me an email: jpoloczek (at) tlen.pl 
if interested

**Comment by bbcallen** [comment]
Sorry, I have a full-time job, I can't take up any custom work.
ijkplayer is open source at all. It has many in common with ffplay.
It's better to find a real freelancer for this.
