### ISSUE TITLE
Is this option is not need anymore ? I think you should delete this optiion from IjkVideoView.

### ISSUE THREAD

**Issue by renhui** [Bilibili/ijkplayer#2734]
This is my log :  E/IJKMEDIA: Option http-detect-range-support not found.

**Comment by renhui** [comment]
And I can't find 'http-detect-range-support' in  'ff_ffplay_options.h'

**Comment by raymond1012** [comment]
http-detect-range-support is unused

2017-02-24 11:36 GMT+08:00 renhui <notifications@github.com>:
