### ISSUE TITLE
ijkplayer fail to play rtmp video

### ISSUE THREAD

**Issue by simon-fu** [Bilibili/ijkplayer#274]
hi guys, ijkplayer fail to play rtmp video.

device: iPhone6 Simulator, iOS8.3  
git commit-id: d37d36fe2976594cd56f40bb7b0b3fc98a1bc361  
config: module-default.sh  
log: see below  

	ijkmp_set_format_callback(0x10fef5d50, 0x7fd6a14e5180)
	ijkmp_set_format_callback()=void
	ijkmp_set_option_int(start-on-prepared, 1)
	ijkmp_set_option_int()=void
	2015-06-12 12:34:22.460 IJKMediaDemo[81345:4132615] OK setup GL
	ijkmp_ios_set_view(glView=0x7fd6a1676310)
	ijkmp_ios_set_view(glView=0x7fd6a1676310)=void
	ijkmp_set_option(overlay-format, fcc-i420)
	ijkmp_set_option()=void
	2015-06-12 12:34:22.461 IJKMediaDemo[81345:4132615] ========================================
	= FFmpeg options:
	= skip_loop_filter: avdicard all;
	= skipFrame:        avdiscard nonref
	= frameBufferCount: 3
	= maxFps:           30
	= timeout:          30000000
	========================================
	ijkmp_set_option_int(skip_loop_filter, 48)
	ijkmp_set_option_int()=void
	ijkmp_set_option_int(skip_frame, 8)
	ijkmp_set_option_int()=void
	ijkmp_set_option_int(max-fps, 30)
	ijkmp_set_option_int()=void
	ijkmp_set_option_int(framedrop, 0)
	ijkmp_set_option_int()=void
	ijkmp_set_option_int(video-pictq-size, 3)
	ijkmp_set_option_int()=void
	ijkmp_set_option_int(max-buffer-size, 123)
	ijkmp_set_option_int()=void
	ijkmp_ios_set_videotoolbox_enabled enable(EnableFlag=1)
	ijkmp_ios_set_videotoolbox_enabled enable(EnableFlag=1)
	ijkmp_ios_set_frame_max_width (width=960)
	ijkmp_ios_set_frame_max_width after(width=960)
	ijkmp_set_option_int(reconnect, 1)
	ijkmp_set_option_int()=void
	ijkmp_set_option_int(timeout, 30000000)
	ijkmp_set_option_int()=void
	ijkmp_set_data_source(url="rtmp://172.16.4.238:1935/vod/mp4:sample.mp4")
	ijkmp_set_data_source(url="rtmp://172.16.4.238:1935/vod/mp4:sample.mp4")=0
	ijkmp_set_option(safe, 0)
	ijkmp_set_option()=void
	ijkmp_prepare_async()
	===== options =====
	player-opts : start-on-prepared    = 1
	player-opts : overlay-format       = fcc-i420
	player-opts : max-fps              = 30
	player-opts : framedrop            = 0
	player-opts : video-pictq-size     = 3
	player-opts : max-buffer-size      = 123
	format-opts : reconnect            = 1
	format-opts : timeout              = 30000000
	format-opts : safe                 = 0
	codec-opts  : skip_loop_filter     = 48
	codec-opts  : skip_frame           = 8
	===================
	ijkmp_prepare_async()=0
	ijkmp_start()
	ijkmp_start()=-3
	[rtmp @ 0x7fd6a166bc10] Cannot open connection tcp://172.16.4.238:1935?listen&listen_timeout=-64771072
	rtmp://172.16.4.238:1935/vod/mp4:sample.mp4: Address already in use
	2015-06-12 12:34:22.474 IJKMediaDemo[81345:4132615] FFP_MSG_ERROR: 0
	2015-06-12 12:34:22.474 IJKMediaDemo[81345:4132615] moviePlayBackStateDidChange 2: paused
	2015-06-12 12:34:22.475 IJKMediaDemo[81345:4132615] playbackStateDidChange: MPMovieFinishReasonPlaybackError: 1

**Comment by bbcallen** [comment]
http://blog.brightworks.com/2006/10/20/workaround-if-youre-getting-address-already-in-use-bind-error/

**Comment by simon-fu** [comment]
the post seems irrelevant to ijkplayer ...

**Comment by bbcallen** [comment]
```
[rtmp @ 0x7fd6a166bc10] Cannot open connection tcp://172.16.4.238:1935?listen&listen_timeout=-64771072
rtmp://172.16.4.238:1935/vod/mp4:sample.mp4: Address already in use
```
According to log, the error seems irrelevant to client ...
Try google "rtmp", "Address already in use"

**Comment by bbcallen** [comment]
Fixed on master;
