### ISSUE TITLE
Is there a way to change the video resolution?

### ISSUE THREAD

**Issue by Sebacho-Barajas** [Bilibili/ijkplayer#2758]
Is there a way to change the video/stream resolution on iOS?

**Comment by Sebacho-Barajas** [comment]
what I meant if is there a method to change the video quality in iOS 
Eg from 1080 to 720 etc

**Comment by raymond1012** [comment]
can not

2017-03-01 16:13 GMT+08:00 Sebacho-Barajas <notifications@github.com>:
