### ISSUE TITLE
setAutoPlayOnPrepared(false)在较差网速下，会导致无法开始播放

### ISSUE THREAD

**Issue by eblislu** [Bilibili/ijkplayer#276]
在比较差的网速下，如果设置了setAutoPlayOnPrepared(false)，那么在prepare完成后，ff_ffplay会给一个FFP_MSG_BUFFERING_START消息，如果此时调用pause进行暂停，那么ff_ffplay就不会进行缓冲了，也不会发送FFP_MSG_BUFFERING_END消息，导致播放无法继续。
初步调试，问题出在
ff_ffplay.c的
if (!ffp->start_on_prepared) {
        while (is->pause_req && !is->abort_request) {
            SDL_Delay(100);
        }
}
请问，这几句能去掉么？有没有啥不良影响呢？

**Comment by bbcallen** [comment]
如果再调用 start 呢?

**Comment by Android4MediaPlayer** [comment]
prepare之后要调用start的
