### ISSUE TITLE
exec "./compile-ijk.sh all" got error

### ISSUE THREAD

**Issue by johnlee175** [Bilibili/ijkplayer#2760]
error: invalid argument '-std=c99' not allowed with 'C++/ObjC++'
make: *** [/xx/github/ijkplayer/android/ijkplayer/ijkplayer-armv7a/src/main/obj/local/armeabi-v7a/objs/ijkplayer/ijkavutil/ijkstl.o] Error 1

os: mac
ndk-version: 14.0.3529234-beta1

**Comment by johnlee175** [comment]
Year, I add "LOCAL_CPPFLAGS += -std=c++98" to ijkmedia/ijkplayer/Android.mk, and fix it.
But, the following error happened: (so sad)

/xx/github/ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:678: error: undefined reference to '__atomic_exchange_4'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by yippeesoft** [comment]
编译里面移除掉  ijkplayer-armv5 先，或者单独编译armv7下

**Comment by FloridaStream** [comment]
Try this http://stackoverflow.com/questions/25711122/error-invalid-argument-std-gnu99-not-allowed-with-c-objc

**Comment by johnlee175** [comment]
Thanks
