### ISSUE TITLE
解码花屏问题请教

### ISSUE THREAD

**Issue by PengBoShi** [Bilibili/ijkplayer#2769]
一组GOP没有B帧，如果我保留 i 帧，把中间的几个p帧丢掉，后面的p帧还能正常解码吗？会出现花屏吗？

**Comment by yinwenjie** [comment]
直接丢包后面大概率会花屏，没办法确定丢掉的P帧会不会是后面的reference frame。类似的问题不建议人为扔原始码流，最好从render端考虑

**Comment by PengBoShi** [comment]
但是decoder后render前丢掉，影响效率 会有卡顿的。

**Comment by PengBoShi** [comment]
@yinwenjie 但是decoder后render前丢掉，影响效率 会有卡顿的。

**Comment by PengBoShi** [comment]
@yinwenjie p帧的参考帧是i帧还是它前面的那一帧，或者是跟编码相关？

**Comment by PengBoShi** [comment]
@bbcallen 求教一下 p帧的参考帧是前面的i帧还是它前面的那一帧，或者是跟编码相关？

**Comment by yinwenjie** [comment]
码流里面会指定，不一定是前面的一帧或者是I帧，每种情况不一样

**Comment by PengBoShi** [comment]
@yinwenjie 非常感谢
