### ISSUE TITLE
ijkplayer的回调通知问题

### ISSUE THREAD

**Issue by PengBoShi** [Bilibili/ijkplayer#2770]
iOS ijkplayer有timeout的回调或者通知吗，是不是timeout或者URL输入错误 只有一个FFP_MSG_ERROR？ android的ijkplayer有很有多错误ID。

**Comment by raymond1012** [comment]
只有连接错误

**Comment by PengBoShi** [comment]
@raymond1012 是只有一个FFP_MSG_ERROR吗，你说的只有有个连接错误，是iOS对吧，android呢，android也是只有这一个吗

**Comment by raymond1012** [comment]
都是一样的

2017-03-02 18:25 GMT+08:00 Peng_bo_Shi <notifications@github.com>:

**Comment by PengBoShi** [comment]
@raymond1012 非常感谢
