### ISSUE TITLE
0.7.7.1 ios直播播放失败

### ISSUE THREAD

**Issue by zhudaye12138** [Bilibili/ijkplayer#2775]
编译时加入了openssl。安卓可以播
URL：http://hls1.plu.cn/onlive/f0b2918476a6438992e4f6a6ae55e674_550/playlist.m3u8?wsSecret=54ad7a3486d06fbf0fd6d0d50d24dd7a&wsTime=58b8c2a5

ERROR:
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
ijkmp_set_playback_rate(1.000000)
ijkmp_set_playback_rate()=void
ijkmp_set_playback_volume(1.000000)
ijkmp_set_playback_volume()=void
ijkmp_seek_to(0)
ijkmp_seek_to(0)=0
2017-03-02 19:27:41:341 LOL[782:191103] IJKMPMoviePlaybackStateSeekingForward
2017-03-02 19:27:41:341 LOL[782:191103] IJKMPMoviePlaybackStateSeekingForward
ijkmp_get_msg: FFP_REQ_SEEK
aout_pause_audio(1)

**Comment by PengBoShi** [comment]
你可以多加一些log 看看为什么调用了shutdown

**Comment by raymond1012** [comment]
log 显示你主动close了

**Comment by zhudaye12138** [comment]
我刚才传错log了，这个不是我主动close的，是自动pause。我把状态打出来，发现下载速度 tcp-spd 有值。但v-cache、a-cache一直没增涨。（不知道这里怎么传图）

**Comment by zhudaye12138** [comment]
昨天的直播地址失效了，换了个URL。不知道什么情况下回导致 aout_pause_audio(1) ？

**Comment by zhudaye12138** [comment]
问题解决了，我在播放直播视频时设置了currentPlaybackTime，导致走到IJKMPMoviePlaybackStateSeekingForward。。。
