### ISSUE TITLE
Invalid data found when processing input 无法播放本地视频

### ISSUE THREAD

**Issue by DemonWitcher** [Bilibili/ijkplayer#2776]
compile 'tv.danmaku.ijk.media:ijkplayer-java:0.7.7.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.7.7.1'
你好,我通过以上方式添加ijk,播放一些网络视频没问题,但是播放本地视频.rmvb就会出现以下日志
已经确定本地的这个视频不是损坏的  可以被多个其他播放器播放
请问这是什么问题呢,万分感谢.
我的设备是红米1S,已经在本机视频播放器上和一个vitamio播放器上试过这个本地的视频路径,都可以播放

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
我给了以上权限
再次尝试了一下 把测试视频换成本地.mkv格式,用tv.danmaku.ijk.media.player.AndroidMediaPlayer来播放,结果是有画面但是没声音 
用ijkplayer播放本地.mkv也不行,加载不上视频,会出现以下日志
目前用ijkplayer播放本地.mkv和.rmvb都会出现下面日志
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: IjkMediaPlayer_native_init
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: IjkMediaPlayer_native_setup
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: av_version_info: ff3.2--ijk0.7.6--20170203--001
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: ijk_version_info: k0.7.7.1
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: ffpipeline_create_from_android()
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: ijkmp_set_inject_opaque(0x1d2004aa)
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: ijkmp_set_inject_opaque()=void
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x1d2004aa)
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(3)
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: moncleanup
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/tv.danmaku.ijk.media.player.IjkMediaPlayer: Couldn't open file on client side, trying server side
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer V/IJKMEDIA: setDataSource: path /storage/emulated/0/abc.rmvb
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: ijkmp_set_data_source(url="/storage/emulated/0/abc.rmvb")
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: ijkmp_set_data_source(url="/storage/emulated/0/abc.rmvb")=0
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0xb0b0001d)
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: ffpipeline_set_surface()
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0xb0b0001d)=void
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: IjkMediaPlayer_prepareAsync
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: ijkmp_prepare_async()
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: ===== versions =====
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: ijkplayer    : k0.7.7.1
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: FFmpeg       : ff3.2--ijk0.7.6--20170203--001
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: libavutil    : 55.34.100
03-02 22:20:17.165 16694-16755/com.witcher.videoplayer I/IJKMEDIA: SDL_RunThread: [16755] ff_msg_loop
03-02 22:20:17.165 16694-16755/com.witcher.videoplayer D/IJKMEDIA: message_loop
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: libavcodec   : 57.64.100
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: libavformat  : 57.56.100
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: libswscale   : 4.2.100
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: libswresample: 2.3.100
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: ===== options =====
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: player-opts : mediacodec                   = 0
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: player-opts : opensles                     = 0
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: player-opts : overlay-format               = 842225234
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: player-opts : framedrop                    = 1
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: player-opts : start-on-prepared            = 0
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: format-opts : ijkapplication               = 1632343264
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: format-opts : ijkiomanager                 = 1632343352
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: format-opts : http-detect-range-support    = 0
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer I/IJKMEDIA: ===================
03-02 22:20:17.165 16694-16755/com.witcher.videoplayer D/IJKMEDIA: FFP_MSG_FLUSH:
03-02 22:20:17.165 16694-16756/com.witcher.videoplayer I/IJKMEDIA: SDL_RunThread: [16756] ff_vout
03-02 22:20:17.165 16694-16694/com.witcher.videoplayer D/IJKMEDIA: ijkmp_prepare_async()=0
03-02 22:20:17.165 16694-16757/com.witcher.videoplayer I/IJKMEDIA: SDL_RunThread: [16757] ff_read
03-02 22:20:17.165 16694-16757/com.witcher.videoplayer D/IJKMEDIA: Setting default whitelist 'file,crypto'
03-02 22:20:17.305 16694-16694/com.witcher.videoplayer I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@420931e0 time:601011121
03-02 22:20:17.305 16694-16757/com.witcher.videoplayer D/IJKMEDIA: Statistics: 1048576 bytes read, 0 seeks
03-02 22:20:17.305 16694-16757/com.witcher.videoplayer E/IJKMEDIA: /storage/emulated/0/abc.rmvb: Invalid data found when processing input
03-02 22:20:17.315 16694-16755/com.witcher.videoplayer D/IJKMEDIA: FFP_MSG_ERROR: 0
03-02 22:20:17.315 16694-16757/com.witcher.videoplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [16757]
03-02 22:20:17.315 16694-16694/com.witcher.videoplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by songmao123** [comment]
你好，你这个问题解决了吗？

**Comment by DemonWitcher** [comment]
@songmao123   后来我换了个mp4格式的本地 可以播放  IJK就是不支持MKV和RMVB

**Comment by songmao123** [comment]
@DemonWitcher 是支持的！需要重新编译，按照READMEL里面的`If you prefer more codec/format`那个命令重新编译，不过我是以module的方式导入armv7那个工程导入到项目的，就可以播放mkv格式的视频了。

**Comment by DemonWitcher** [comment]
@songmao123    感谢  我也试一下 ^_^
