### ISSUE TITLE
ijkplayer 实例复用播放时，图像会存在残留

### ISSUE THREAD

**Issue by erwinshao** [Bilibili/ijkplayer#278]
hi，bbcallen，目前在一个视频列表中，使用多个ijkplayer实例来复用播放不同的视频文件，在快速滑动时，上一个视频播放的实例，会重新播放新的视频文件，在开始播放前，surface会显示之前视频的图像，然后再切换到新的视频画面。目前想到的方法时，播放新的视频前，在surface上显示要播放的新视频第一帧的bitmap，查看源码调用SDL_VoutDisplayYUVOverlay可以达到这个效果，但 bitmap 怎么样转换成SDL_VoutOverlay？另外请问有其它更好的思路解决么？

**Comment by bbcallen** [comment]
如果可以接受短时间的黑屏，创建一个新的surface比较简单。或者在java层，切换播放器之前，给surfaceholder设置一个不常用的pixelformat  (RGB565)，以达到强制reset surface的作用。

**Comment by erwinshao** [comment]
多谢你的回复，在切换视频时，如果能很快的切到新视频的第一帧图片，然后等待解码播放。这样从视觉过渡上是最自然的。播放器中已经有从 ffmpeg AVFrame to SDL_VoutOverlay的函数，我尝试下bitmap转换成 avframe应该就可以了。

**Comment by garymabin** [comment]
复用播放的场景，也有用户去处理类似“刷新”操作的时候，给SurfaceHolder设置pixelformat似乎不生效，切换播放器之前，调用lockCanvas去绘制一张黑屏可以

**Comment by toumubaoqiong** [comment]
@erwinshao 问题解决了没？是怎样顺利过渡到新视频的第一帧图片的？

**Comment by erwinshao** [comment]
@toumubaoqiong ，在 java 层 reset player，底层就会释放掉Surface，java 层拿到 Surface 后就可以opegl 把第一帧的 bitmap draw 上去了。

**Comment by ielicyan** [comment]
@erwinshao java层怎么拿到的新视频的第一帧数据，用的textureview吗，另外得等到新视频开始解码才能拿到第一帧的bitmap吧？谢谢

**Comment by nicolasiJasica** [comment]
mark
