### ISSUE TITLE
Error:Neither path nor baseDir may be null or empty string. path='null' 

### ISSUE THREAD

**Issue by cikichen** [Bilibili/ijkplayer#279]
import android folder to android studio 1.2.2, but build failed. Please help me! Thanks.

Error:Error:Neither path nor baseDir may be null or empty string. path='null' basedir='/Users/x/Developer/ijkplayer/ijkplayer-android/android/ijkmediaplayer'

**Comment by bbcallen** [comment]
Try new gradle build script: bb410c178d55ac672e8c9a173e07d206e25f9a4d

**Comment by leageshine** [comment]
test

**Comment by leageshine** [comment]
The same problem blocked me too. But I tackled it.
In my situation ,the bad point located at build.gradle file of the app.  The error log told me which line caused the error. I found that line referring a file path parameter, while the parameter is read from a properties file. But the parameter not exist in that properties file!!! That is the source of the  problem. So I appended a parameter to the properties file. Problem solved.
