### ISSUE TITLE
ijk具体支持什么视频格式？

### ISSUE THREAD

**Issue by OCer** [Bilibili/ijkplayer#2792]
我用的是最多格式的那个，但是不知道具体支持什么格式

**Comment by raymond1012** [comment]
see module.sh

2017-03-07 11:07 GMT+08:00 子天 <notifications@github.com>:

**Comment by OCer** [comment]
我看了下module-default.sh 很多东西都注释掉了  其实我只是想要支持的后缀名

**Comment by bbcallen** [comment]
https://ffmpeg.org/general.html
