### ISSUE TITLE
Unable to play RTMP video

### ISSUE THREAD

**Issue by KCastiglione** [Bilibili/ijkplayer#280]
This is the version I am using : c8bf63520d7f11c0466435e1681cde33bc8a87f1
This is output from IJKMediaDemo without any changes and just specifying the rtmp source.
These are steps I did

       git clone https://github.com/Bilibili/ijkplayer.git
       cd ijkplayer/
       ./init-ios.sh
       cd ios
       ./compile-ffmpeg.sh clean
       ./compile-ffmpeg.sh all
       open IJKMediaDemo/IJKMediaDemo.xcodeproj
       

Please tell me how to make it work

       ijkmp_set_format_callback(0x101299, 0x14d0cb40)
       ijkmp_set_format_callback()=void
       ijkmp_set_option_int(start-on-prepared, 1)
       ijkmp_set_option_int()=void
       2015-06-16 20:13:56.308 IJKMediaDemo[351:19521] OK setup GL
       ijkmp_ios_set_view(glView=0x14d18fd0)
       ijkmp_ios_set_view(glView=0x14d18fd0)=void
       ijkmp_set_option(overlay-format, fcc-i420)
       ijkmp_set_option()=void
       2015-06-16 20:13:56.320 IJKMediaDemo[351:19521] ========================================
       = FFmpeg options:
       = skip_loop_filter: avdicard all;
       = skipFrame:        avdiscard nonref
       = frameBufferCount: 3
       = maxFps:           30
       = timeout:          30000000
       ========================================
       ijkmp_set_option_int(skip_loop_filter, 48)
       ijkmp_set_option_int()=void
       ijkmp_set_option_int(skip_frame, 8)
       ijkmp_set_option_int()=void
       ijkmp_set_option_int(max-fps, 30)
       ijkmp_set_option_int()=void
       ijkmp_set_option_int(framedrop, 0)
       ijkmp_set_option_int()=void
       ijkmp_set_option_int(video-pictq-size, 3)
       ijkmp_set_option_int()=void
       ijkmp_ios_set_videotoolbox_enabled enable(EnableFlag=1)
       ijkmp_ios_set_videotoolbox_enabled enable(EnableFlag=1)
       ijkmp_ios_set_frame_max_width (width=960)
       ijkmp_ios_set_frame_max_width after(width=960)
       ijkmp_set_option_int(reconnect, 1)
       ijkmp_set_option_int()=void
       ijkmp_set_option_int(timeout, 30000000)
       ijkmp_set_option_int()=void
       ijkmp_set_data_source(url="rtmp://10.0.1.236/live/mov")
       ijkmp_set_data_source(url="rtmp://10.0.1.236/live/mov")=0
       ijkmp_set_option(safe, 0)
       ijkmp_set_option()=void
       ijkmp_prepare_async()
       ===== options =====
       player-opts : start-on-prepared    = 1
       player-opts : overlay-format       = fcc-i420
       player-opts : max-fps              = 30
       player-opts : framedrop            = 0
       player-opts : video-pictq-size     = 3
       format-opts : reconnect            = 1
       format-opts : timeout              = 30000000
       format-opts : safe                 = 0
       codec-opts  : skip_loop_filter     = 48
       codec-opts  : skip_frame           = 8
       ===================
       ijkmp_prepare_async()=0
       ijkmp_start()
       ijkmp_start()=-3
       [rtmp @ 0x14ea3800] Cannot open connection tcp://10.0.1.236:1935?listen&listen_timeout=-64771072
       rtmp://10.0.1.236/live/mov: Can't assign requested address
       2015-06-16 20:13:58.810 IJKMediaDemo[351:19521] FFP_MSG_ERROR: 0
       2015-06-16 20:13:58.810 IJKMediaDemo[351:19521] moviePlayBackStateDidChange 2: paused
       2015-06-16 20:13:58.811 IJKMediaDemo[351:19521] playbackStateDidChange: MPMovieFinishReasonPlaybackError: 1

I am able to play the same stream fine with VLC player on my mac, on my iPhone and also  in ffplay from command prompt. So it is not a network issue.

**Comment by zhanglehs** [comment]
I meet the same problem.
The android version of ijkplayer plays rtmp stream very well, but the IOS version doesn't work.

**Comment by zhanglehs** [comment]
oh, i got a solution just now.

use the k0.2.3 version of code (after pull the code, execute "git checkout -B latest k0.2.3"), then you will find out it can work now.

I have great interest to find out what happened in k0.3.0, but i'm too busy now. if any one who find out the reason, please notice me by email( zhangle86@qq.com), thanks.

**Comment by KCastiglione** [comment]
@zhanglehs @bbcallen 
thanks for confirming the problem with k0.3.0. 

will reverting back to k0.2.3 use ffmpeg 2.7 or the older version?
i would like to use ffmpeg 2.7 and also ee1e34c89c7b272258a3cdbf27657641d3f63c8f this option convenience. will these be available in k0.2.3?

look forward to getting k0.3.0 resolved.

thank you for a great library!

**Comment by bbcallen** [comment]
Previous version will not be maintained.

Problem must be introduced between ffmepg 2.6 and ffmpeg 2.7.
Is there any stream I can debug with?

**Comment by tasdg-yamamoto** [comment]
@bbcallen 
RTMP video is error when IJKF Options set  in iOS.

I was setting IJKF Options in k0.2.3.

IJKMoviePlayerViewController.m
```
    IJKFFOptions *options = [IJKFFOptions optionsByDefault];
    self.player = [[IJKFFMoviePlayerController alloc] initWithContentURL:theMovieURL withOptions:options];
```
I meet the same problem in k0.2.3.

```
ijkmp_set_format_callback(0x10afff480, 0x7ff270d38460)
ijkmp_set_format_callback()=void
ijkmp_set_auto_play_on_prepared(1)
ijkmp_set_auto_play_on_prepared()=void
2015-06-24 19:45:43.027 IJKMediaDemo[26110:1749321] OK setup GL
ijkmp_ios_set_view(glView=0x7ff270f2a630)
ijkmp_ios_set_view(glView=0x7ff270f2a630)=void
ijkmp_set_overlay_format(I420(0x30323449))
ijkmp_set_overlay_format()=void
2015-06-24 19:45:43.028 IJKMediaDemo[26110:1749321] ========================================
= FFmpeg options:
= skip_loop_filter: avdicard all;
= skipFrame:        avdiscard nonref
= frameBufferCount: 3
= maxFps:           30
= timeout:          30000000
========================================
ijkmp_set_codec_option()
ijkmp_set_codec_option()=void
ijkmp_set_codec_option()
ijkmp_set_codec_option()=void
ijkmp_set_picture_queue_capicity(3)
ijkmp_set_picture_queue_capicity()=void
ijkmp_set_max_fp(30)
ijkmp_set_max_fp()=void
ijkmp_set_framedrop(0)
ijkmp_set_framedrop()=void
ijkmp_ios_set_videotoolbox_enabled enable(EnableFlag=1)
ijkmp_ios_set_videotoolbox_enabled enable(EnableFlag=1)
ijkmp_ios_set_frame_max_width (width=960)
ijkmp_ios_set_frame_max_width after(width=960)
ijkmp_set_format_option(timeout, 30000000)
ijkmp_set_format_option()=void
ijkmp_set_data_source(url="rtmp://fml.cine.io/20C45E/cines/Qy80rnnWg")
ijkmp_set_data_source(url="rtmp://fml.cine.io/20C45E/cines/Qy80rnnWg")=0
ijkmp_set_format_option(safe, 0)
ijkmp_set_format_option()=void
ijkmp_prepare_async()
ijkmp_prepare_async()=0
ijkmp_start()
ijkmp_start()=-3
[rtmp @ 0x7ff270c7c920] Cannot open connection tcp://fml.cine.io:1935?listen&listen_timeout=-64771072
rtmp://fml.cine.io/20C45E/cines/Qy80rnnWg: Can't assign requested address
2015-06-24 19:45:43.049 IJKMediaDemo[26110:1749321] FFP_MSG_ERROR: 0
2015-06-24 19:45:43.050 IJKMediaDemo[26110:1749321] moviePlayBackStateDidChange 2: paused
2015-06-24 19:45:43.050 IJKMediaDemo[26110:1749321] playbackStateDidChange: MPMovieFinishReasonPlaybackError: 1
```

k0.3.0 is setting optionsByDefault, when options is null.

IJKFFMoviePlayerController.m
```
        // apply ffmpeg options
        if (options == nil) {
            options = [IJKFFOptions optionsByDefault];
        }
        [options applyTo:_mediaPlayer];
        _pauseInBackground = options.pauseInBackground;
```
It is working, when options set nil.
But I want to use IJKF Options.

**Comment by tasdg-yamamoto** [comment]
It is working,  when I was setting IJKFFOptions's timeout to 0 in k0.3.0.
In the case of playing RTMP video, do it need to set timeout to 0?

```
    IJKFFOptions* options = [IJKFFOptions optionsByDefault];
    options.timeout = 0;
    self.player = [[IJKFFMoviePlayerController alloc] initWithContentURL:self.url withOptions:options];
```

**Comment by KCastiglione** [comment]
@bbcallen
here is an RTMP url to debug:

rtmp://fms.12E5.edgecastcdn.net/0012E5/mp4:videos/8Juv1MVa-485.mp4


incase this url expires, i got it from here by 'view source', 
 http://support.jwplayer.com/customer/portal/articles/1430358-using-rtmp-streaming

**Comment by bbcallen** [comment]
Seems caused by 'timeout' option.
Force set it to -1 for a temporary workaround

**Comment by bbcallen** [comment]
fixed: 738565c7cced622eaa8960aae7a7f5e57b386f7f

**Comment by ken94301** [comment]
I think RTSP has the same issue. I can't do RTSP and RTMP streaming with default IJKOptions. I must overwrite default options to make it work.

**Comment by bbcallen** [comment]
blind fixed: 8a6389f9d2e9b95a98e521a3eede695446f0eb63
thanks.

**Comment by KCastiglione** [comment]
thanks looks like it is fixed!

**Comment by bbcallen** [comment]
Thank @tasdg-yamamoto , who found the key point.

**Comment by poholo** [comment]
use 
`-(void)setPlayerOptionIntValue:    (int64_t)value forKey:(NSString *)key;` ?
