### ISSUE TITLE
Ijkplayer returns 403  but ffplay not

### ISSUE THREAD

**Issue by CoXier** [Bilibili/ijkplayer#2801]
## There is a test URL
[http://125.64.2.48/sohu/v1/TmPCo6IsWF6HNJA1eENBetWl0SCRz8bFP86iemsBhYXUyYbSoO2VqVw.mp4?k=vMALuK&p=XWPIWho70ScAZMoUoTWCr&r=TmI20LscWOo70Sc2ZDASqTPGRD6sfYeSqm8VR5&q=OpC7hW7IWBodRD6tfD6SotE7ZDvsWhXtZhXsRhbHfJ6tvmbcWJbXfhetRhASqD2tRYoUZDk&cip=211.69.194.217](http://125.64.2.48/sohu/v1/TmPCo6IsWF6HNJA1eENBetWl0SCRz8bFP86iemsBhYXUyYbSoO2VqVw.mp4?k=vMALuK&p=XWPIWho70ScAZMoUoTWCr&r=TmI20LscWOo70Sc2ZDASqTPGRD6sfYeSqm8VR5&q=OpC7hW7IWBodRD6tfD6SotE7ZDvsWhXtZhXsRhbHfJ6tvmbcWJbXfhetRhASqD2tRYoUZDk&cip=211.69.194.217)

## ffplay is ok when I set headers like below:
```java
ffplay -headers "Range: bytes=0-55084477"$'\r\n' -i "http://125.64.2.48/sohu/v1/TmPCo6IsWF6HNJA1eENBetWl0SCRz8bFP86iemsBhYXUyYbSoO2VqVw.mp4?k=vMALuK&p=XWPIWho70ScAZMoUoTWCr&r=TmI20LscWOo70Sc2ZDASqTPGRD6sfYeSqm8VR5&q=OpC7hW7IWBodRD6tfD6SotE7ZDvsWhXtZhXsRhbHfJ6tvmbcWJbXfhetRhASqD2tRYoUZDk&cip=211.69.194.217"
```

## Ijkplayer still returns 403

```java
private void setVideoURI(Uri uri) {
        Map<String,String> headers = new HashMap<>();
        headers.put("Range"," bytes=0-55084477;\r\n");
        setVideoURI(uri, headers);
    }
```
Is there any difference between `ijkplayer` and `ffplay`?

**Comment by CoXier** [comment]
It's my fault.

```java
private void setVideoURI(Uri uri) {
        Map<String,String> headers = new HashMap<>();
        headers.put("Range"," bytes=0-55084477");
        setVideoURI(uri, headers);
    }
```

**Comment by 18369188711why** [comment]
Hello, I have the same problem there days, could you help me?
1.Where should I place the setVideoURI(Uri uri) method?
2.I find you had asked the same question before with the issue #2667, so if I want to solve the problem, must I change the http.c?
Thank you.

**Comment by 18369188711why** [comment]
I find the setVideoURI(Uri uri)  method, but how can I set it if I don't use IjkVideoView?
Thank you so much.

**Comment by CoXier** [comment]
It doesn't matter with IjkVideoView.

2017-03-21 21:21 GMT+08:00 18369188711why <notifications@github.com>:

**Comment by JinManli** [comment]
iOS answer

**Comment by JinManli** [comment]
And What to do in iOS?

**Comment by zhuyifan2013** [comment]
55084477 是怎么来的？ @CoXier

**Comment by CoXier** [comment]
I get the json data and know the length.

**Comment by zhuyifan2013** [comment]
@CoXier  但是我也加了 Range  还一直是 403 ，不知道还需要配置什么参数？
