### ISSUE TITLE
Android如何实现播放硬解码的rmvb， mkv, avi格式？

### ISSUE THREAD

**Issue by JiannaiJ** [Bilibili/ijkplayer#2802]
Android如何实现播放硬解码的rmvb， mkv, avi格式？

**Comment by raymond1012** [comment]
google

2017-03-08 15:47 GMT+08:00 JiannaiJ <notifications@github.com>:

**Comment by teddyla** [comment]
rmvb, mkv, avi are "container",  not codec.
you should check test files'  video | audio codec(ijkplayer do not support offload, not support audio hw dec) whether the vendor chip's hw dec supported

**Comment by JiannaiJ** [comment]
@teddyla  有点答非所问的意思啊，翻译不准确？ 换一个问法：   是否支持编译so库支持播放rmvb,mkv,avi格式的视频？（设置支持这三种视频的硬解码播放）
