### ISSUE TITLE
由于视频播放延时的原因，我修改了ffplay.c的内容 然后发现音频延时未改变

### ISSUE THREAD

**Issue by lunhui0924** [Bilibili/ijkplayer#2806]
查询的结果说是ijkPlayer默认音频为主时钟 如何修改为视频主时钟

**Comment by raymond1012** [comment]
see av_sync_type

**Comment by lunhui0924** [comment]
@raymond1012 此处修改后 经常buffering， 修改回原来的 视频正常 声音有三秒的延时

**Comment by raymond1012** [comment]
请确认视频源是否问题

2017-03-09 15:51 GMT+08:00 lunhui0924 <notifications@github.com>:
