### ISSUE TITLE
手机竖屏录制的视频播放时画面旋转了90度

### ISSUE THREAD

**Issue by zentertainzhaomingliang** [Bilibili/ijkplayer#281]
hello，你好

我发现了一个bug，用android手机竖屏录制的视频metadata中，有一个rotate=90的属性，用ijkplayer播放时，画面会有一个90度的旋转。我用ffplay播放时不加 -noautorotate选项播放正常，从ffmpeg官方文档上看，解码时是会处理这个rotate属性的，不知道ijkplayer是否有计划处理这个问题？

**Comment by bbcallen** [comment]
暂时不支持mp4的旋转属性。

ffplay 是通过video-filter来支持的，对于安卓来说，额外的内存拷贝损耗太多性能。建议通过读取meta的方式，然后旋转surfaceview来实现。

2个月内暂时没有计划。

**Comment by bbcallen** [comment]
Partial supported: ed814911b41f0d65ae022b08e403b3a60cda7695
