### ISSUE TITLE
播放大概2s 后自动停止播放

### ISSUE THREAD

**Issue by CavanLife** [Bilibili/ijkplayer#2816]
ijkmp_start()
ijkmp_start()=0
ijkmp_get_msg: FFP_REQ_START
aout_pause_audio(1)
aout_pause_audio(1)
2017-03-10 11:50:10.864014 H2H[1577:342891] FFP_MSG_BUFFERING_START:

ijkmp_get_msg: FFP_MSG_SEEK_COMPLETE
aout_pause_audio(0)
2017-03-10 11:50:10.865848 H2H[1577:342891] FFP_MSG_SEEK_COMPLETE:

2017-03-10 11:50:10.983379 H2H[1577:342891] FFP_MSG_BUFFERING_END:

ijkmp_start()
ijkmp_start()=0
ijkmp_get_msg: FFP_REQ_START
aout_pause_audio(0)
aout_pause_audio(1)
ijkmp_get_msg: FFP_MSG_COMPLETED

以上为触发开始播放按钮后输出的 log
------------------------------

出现情景：
web 端刷新视频后，iOS 端会大概播放2~3s，然后就自动停止播放了。
打开 showHudView 视图，可以看到 v-cache 和 a-cache 也全部归零了。

@bbcallen 请问这是什么原因？即使调用 play 方法也不可以，该怎么解决请问

**Comment by raymond1012** [comment]
ijkmp_get_msg: FFP_MSG_COMPLETED eof了

**Comment by CavanLife** [comment]
@raymond1012 FFP_MSG_COMPLETED eof了，你说这是什么意思呢？不太明白啊。OC 里面怎么处理呢请问，着急中。。。

**Comment by raymond1012** [comment]
显示文件已经结束了

2017-03-13 9:31 GMT+08:00 Cavan <notifications@github.com>:
