### ISSUE TITLE
播放 rtmp 直播流解析 codec id 出错

### ISSUE THREAD

**Issue by erwinshao** [Bilibili/ijkplayer#282]
hi，我在用 ijkplayer 播放 rtmp 流时，接续报错。用 ffplay 可以播放。流的编码信息：h264+speex
以下是播放流和本地播放 flv 的解析部分日志：
6-19 10:03:52.458 D/IJKMEDIA(23280): ffpipenode_create_video_output_from_android_mediacodec()
06-19 10:03:52.508 I/IJKMEDIA(23280): max_frame_duration: 3600.000
06-19 10:03:52.508 I/IJKMEDIA(23280): Input #0, flv, from '/sdcard/abc.flv':
06-19 10:03:52.508 I/IJKMEDIA(23280):   Metadata:
06-19 10:03:52.508 I/IJKMEDIA(23280):     encoder         :
06-19 10:03:52.508 I/IJKMEDIA(23280): Lavf56.33.101
06-19 10:03:52.508 I/IJKMEDIA(23280):
06-19 10:03:52.508 I/IJKMEDIA(23280):   Duration:
06-19 10:03:52.508 I/IJKMEDIA(23280): 00:00:04.11
06-19 10:03:52.508 I/IJKMEDIA(23280): , start:
06-19 10:03:52.508 I/IJKMEDIA(23280): 0.000000
06-19 10:03:52.508 I/IJKMEDIA(23280): , bitrate:
06-19 10:03:52.508 I/IJKMEDIA(23280): 463 kb/s
06-19 10:03:52.508 I/IJKMEDIA(23280):
06-19 10:03:52.508 I/IJKMEDIA(23280):     Stream #0:0
06-19 10:03:52.508 I/IJKMEDIA(23280): : Video: h264, yuv420p, 320x240, 384 kb/s
06-19 10:03:52.508 I/IJKMEDIA(23280): ,
06-19 10:03:52.508 I/IJKMEDIA(23280): 19.25 fps,
06-19 10:03:52.508 I/IJKMEDIA(23280): 19 tbr,
06-19 10:03:52.508 I/IJKMEDIA(23280): 1k tbn,
06-19 10:03:52.508 I/IJKMEDIA(23280): 38 tbc
06-19 10:03:52.508 I/IJKMEDIA(23280):
06-19 10:03:52.508 I/IJKMEDIA(23280):     Stream #0:1
06-19 10:03:52.508 I/IJKMEDIA(23280): : Audio: speex, 16000 Hz, mono, s16, 27 kb/s
06-19 10:03:52.508 I/IJKMEDIA(23280):
06-19 10:03:52.508 I/IJKMEDIA(23280): stream parser codec type id:0, code id:28
06-19 10:03:52.508 I/IJKMEDIA(23280): stream parser codec type id:1, code id:86052
06-19 10:03:52.518 I/IJKMEDIA(23280): SDL_Android_AudioTrack: CHANNEL_OUT_MONO
06-19 10:03:52.518 I/IJKMEDIA(23280): SDL_Android_AudioTrack: ENCODING_PCM_16BIT
06-19 10:03:52.528 I/IJKMEDIA(23280): SDL_Android_AudioTrack_new: init volume as 1.000000/(0.000000,1.000000)
06-19 10:03:52.528 I/IJKMEDIA(23280): AudioCodec: avcodec, speex
06-19 10:03:52.528 I/IJKMEDIA(23280): SDL_RunThread: [23626] ff_aout_android
06-19 10:03:52.528 I/IJKMEDIA(23280): SDL_RunThread: [23627] ff_audio_dec
06-19 10:03:52.538 I/IJKMEDIA(23280): VideoCodec: avcodec, h264
06-19 10:03:52.538 I/IJKMEDIA(23280): fps: 19.250000 (normal)
06-19 10:03:52.538 I/IJKMEDIA(23280): SDL_RunThread: [23633] ff_video_dec
06-19 10:03:52.538 I/IJKMEDIA(23280): fps: 19.000000 (normal)
以下是解析 stream 的日志：
06-18 21:24:56.536 I/IJKMEDIA(12698): Input #0, flv, from 'rtmp://42.156.239.60:1935/live_relay/9223370602221002878~AB8LRN2DSRqEfkh-n_T7wCZZP1I?viewId=9223370602220949895|cbe8c8019163411395371d8d6d8269ba|9223370602221002878~AB8LRN2DSRqEfkh-n_T7wCZZP1I':
06-18 21:24:56.536 I/IJKMEDIA(12698):   Duration:
06-18 21:24:56.536 I/IJKMEDIA(12698): N/A
06-18 21:24:56.536 I/IJKMEDIA(12698): , start:
06-18 21:24:56.536 I/IJKMEDIA(12698): 93.745000
06-18 21:24:56.536 I/IJKMEDIA(12698): , bitrate:
06-18 21:24:56.536 I/IJKMEDIA(12698): N/A
06-18 21:24:56.536 I/IJKMEDIA(12698):
06-18 21:24:56.536 I/IJKMEDIA(12698):     Stream #0:0
06-18 21:24:56.536 I/IJKMEDIA(12698): : Video: flv1, none
06-18 21:24:56.536 I/IJKMEDIA(12698): ,
06-18 21:24:56.536 I/IJKMEDIA(12698): 14.99 fps,
06-18 21:24:56.536 I/IJKMEDIA(12698): 14.99 tbr,
06-18 21:24:56.536 I/IJKMEDIA(12698): 1k tbn,
06-18 21:24:56.536 I/IJKMEDIA(12698): 1k tbc
06-18 21:24:56.536 I/IJKMEDIA(12698):
06-18 21:24:56.536 I/IJKMEDIA(12698):     Stream #0:1
06-18 21:24:56.536 I/IJKMEDIA(12698): : Subtitle: text
06-18 21:24:56.536 I/IJKMEDIA(12698):
06-18 21:24:56.536 I/IJKMEDIA(12698): stream parser codec type id:0, code id:22
06-18 21:24:56.536 I/IJKMEDIA(12698): stream parser codec type id:3, code id:94210
06-18 21:24:56.536 W/IJKMEDIA(12698): No codec could be found with id 22
06-18 21:24:56.536 E/IJKMEDIA(12698): Failed to open file 'rtmp://42.156.239.60:1935/live_relay/9223370602221002878~AB8LRN2DSRqEfkh-n_T7wCZZP1I?viewId=9223370602220949895|cbe8c8019163411395371d8d6d8269ba|9223370602221002878~AB8LRN2DSRqEfkh-n_T7wCZZP1I' or configure filtergraph

**Comment by erwinshao** [comment]
确认是直播流格式的问题。关闭。

**Comment by bbcallen** [comment]
需要启用 flv1 decoder，参考README的说明

**Comment by HatsuneMikuV** [comment]
请问如何编译添加speex库   和x264
