### ISSUE TITLE
setSpeed not working

### ISSUE THREAD

**Issue by azgalaxy** [Bilibili/ijkplayer#2820]
Calling setSpeed on MediaPlayer (IjkMediaPlayer, Ijkplayer k0.7.7.1) has no effect. 

Video Info  
  - h264 (avc1) 
  - yuvj420p
  - 1920x1080 
  - 1084 kb/s

**Comment by azgalaxy** [comment]
[MP4-Stream](https://goo.gl/qUrIZD)

**Comment by raymond1012** [comment]
setspeed 依赖于音频的速度控制，sample stream没有音频

2017-03-10 21:21 GMT+08:00 azgalaxy <notifications@github.com>:

**Comment by azgalaxy** [comment]
How to change the speed of a stream without having audio?

**Comment by raymond1012** [comment]
you can try modify video_refresh, modify refresh speed

2017-03-13 16:28 GMT+08:00 azgalaxy <notifications@github.com>:

**Comment by iponkan** [comment]
@raymond1012 使用setSpeed没有效果呢，视频信息：mpeg-4，
codec H.264/avc/Mpeg-4 avc
bitrate 2.0Mbits/sec
720*480，本地视频
