### ISSUE TITLE
how to limit domain 

### ISSUE THREAD

**Issue by janyo1201** [Bilibili/ijkplayer#2822]
hi , all
ijkplay 該如何實現限制domain 存取？
比如我的 domain 為aaa.com , 在視頻主機端有限制 使用者是從 aaa.com 的才可以觀看視頻，
但利用ijkplayer 能直接設定 aaa.com 的才可以觀看視頻嗎？

**Comment by Android4MediaPlayer** [comment]
服务端做吧
