### ISSUE TITLE
Errors: Option ijkapplication ..., SDL_Overlay(ffmpeg) ...

### ISSUE THREAD

**Issue by azgalaxy** [Bilibili/ijkplayer#2823]
How to interpret the following error messages?

- Mediaplayer creation
  Option ijkapplication not found.  
 
- Mediaplayer  release
  SDL_Overlay(ffmpeg): overlay_free_l(0xe..........)

**Comment by raymond1012** [comment]
Mediaplayer creation
Option ijkapplication not found.  ------ ijkapplication not found, but
ijkapplication
will be set when http open

Mediaplayer release
SDL_Overlay(ffmpeg): overlay_free_l(0xe..........)  ------ log level is
error, we will fix

2017-03-10 22:49 GMT+08:00 azgalaxy <notifications@github.com>:

**Comment by azgalaxy** [comment]
Option ijkapplication:
I do not use the http protocol for media streaming.

**Comment by tuanvn91** [comment]
still error, not fixed
