### ISSUE TITLE
OnLineVideo tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

### ISSUE THREAD

**Issue by Fozei** [Bilibili/ijkplayer#2828]
Hello dear friends, while doing my project , I find these issue as titile.
I am using IjkPlayer to play on line video, the url format like this : http://192.168.3.74:53467/temp7.mp4, 
and I set the video path by API : mVideoView.setVideoPath(url);
and I built the ijk-player by deafult mode to support more video formate.
The video start playing successfully, but few minutes later, the error occurs. And this is not incidental, it happens everytime.
But when I swap the player type to Ijk-AndrodiMediaPlayer, it plays normal.
Below is my logcat, I catch out the unnormals， hope someone can give me some tips, thanks.
## BEFORE error happens, I saw the log cat with one time http request:
`03-13 10:12:25.464 16065-17109/ D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
03-13 10:12:25.534 16065-17110/XXXX D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
03-13 10:12:25.559 16065-17077/XXXX I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 3
03-13 10:12:25.559 16065-17077/XXXX I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
03-13 10:12:25.589 16065-17077/XXXX I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
03-13 10:12:25.589 16065-17077/XXXX D/IJKMEDIA: request: GET /temp7.mp4 HTTP/1.1
                                                            User-Agent: Lavf/57.56.100
                                                            Accept: */*
                                                            Range: bytes=30693769-
                                                            Connection: close
                                                            Host: 192.168.3.74:53467
                                                            Icy-MetaData: 1
03-13 10:12:25.599 16065-17106/XXXX D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
03-13 10:12:25.659 16065-17077/XXXX I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 4
03-13 10:12:25.664 16065-17107/XXXX D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
                                                            
                                                            
                                                            [ 03-13 10:12:25.684 16065:16065 I/         ]
                                                            mTimeStr = 07:26
03-13 10:12:25.734 16065-17108/XXXX D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2`

## HERE is the error happens:
`03-13 10:12:26.464 16065-17109/XXXX D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
03-13 10:12:26.534 16065-17110/XXXX E/IJKMEDIA: Invalid nal size 1584
03-13 10:12:26.534 16065-17110/XXXX E/IJKMEDIA: Error splitting the input into NAL units.
OnLineVideo tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

                                                            [ 03-13 10:12:26.694 16065:16065 I/         ]
                                                            mTimeStr = 07:27
03-13 10:12:26.979 16065-17077/XXXX I/IJKMEDIA: ffp_toggle_buffering: error: -5
03-13 10:12:26.979 16065-17075/XXXX D/IJKMEDIA: FFP_MSG_ERROR: 0
03-13 10:12:26.979 16065-16065/XXXX E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
03-13 10:12:26.979 16065-17077/XXXX I/IJKMEDIA: ffp_toggle_buffering: eof
03-13 10:13:32.819 16065-16065/XXXX D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
03-13 10:13:32.819 16065-16065/XXXX D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
03-13 10:13:32.819 16065-16065/XXXX D/IJKMEDIA: ffpipeline_set_surface()
03-13 10:13:32.819 16065-16065/XXXX D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
03-13 10:13:33.224 16065-16065/XXXX D/IJKMEDIA: ijkmp_stop()
03-13 10:13:33.224 16065-17075/XXXX D/IJKMEDIA: message_loop exit
03-13 10:13:33.224 16065-17075/XXXX I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [17075]
03-13 10:13:33.224 16065-16065/XXXX D/IJKMEDIA: ijkmp_stop()=0
03-13 10:13:33.224 16065-16065/XXXX D/IJKMEDIA: IjkMediaPlayer_release
03-13 10:13:33.224 16065-16065/XXXX D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
03-13 10:13:33.224 16065-16065/XXXX D/IJKMEDIA: ffpipeline_set_surface()
03-13 10:13:33.224 16065-16065/XXXX D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
03-13 10:13:33.229 16065-16065/XXXX D/IJKMEDIA: ijkmp_shutdown_l()
03-13 10:13:33.229 16065-17111/XXXX I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [17111]
03-13 10:13:33.229 16065-16065/XXXX D/IJKMEDIA: wait for read_tid
03-13 10:13:33.229 16065-17105/XXXX I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [17105]
03-13 10:13:33.234 16065-17076/XXXX I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [17076]
03-13 10:13:33.269 16065-17077/XXXX I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [17077]
03-13 10:13:33.274 16065-17104/XXXX I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [17104]
03-13 10:13:33.284 16065-16065/XXXX D/IJKMEDIA: Statistics: 20589512 bytes read, 6 seeks
03-13 10:13:33.284 16065-16065/XXXX D/IJKMEDIA: wait for video_refresh_tid
03-13 10:13:33.334 16065-16065/XXXX E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x5318ee48)
03-13 10:13:33.334 16065-16065/XXXX E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x5323b660)
03-13 10:13:33.334 16065-16065/XXXX E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x52f3b6b0)
03-13 10:13:33.334 16065-16065/XXXX D/IJKMEDIA: ijkmp_shutdown_l()=void
03-13 10:13:33.334 16065-16065/XXXX D/IJKMEDIA: ijkmp_dec_ref(): ref=0
03-13 10:13:33.334 16065-16065/XXXX D/IJKMEDIA: ijkmp_shutdown_l()
03-13 10:13:33.334 16065-16065/XXXX D/IJKMEDIA: ijkmp_shutdown_l()=void
03-13 10:13:38.484 16065-16074/XXXX D/IJKMEDIA: IjkMediaPlayer_native_finalize
03-13 10:13:38.484 16065-16074/XXXX D/IJKMEDIA: IjkMediaPlayer_release
`

**Comment by Fozei** [comment]
Hi, glade to get feedback from you!
What kind of stream-sample I can offer to you ?

**Comment by raymond1012** [comment]
http://192.168.3.74:53467/temp7.mp4

2017-03-13 14:51 GMT+08:00 Fozei <notifications@github.com>:

**Comment by Fozei** [comment]
Hi~!
I just confirmed this issue is not about IjkPlayer. I use another web server feed this video source to ijkplayer, it performs normal, but the reason that why the previous web server can feed ijk-AndroidMediaPlayer well but ijk-player, still confuses me, anyhow, I can close this issue now, thanks for your kindly help again.
