### ISSUE TITLE
部分 mp4  视频黑屏  

### ISSUE THREAD

**Issue by XXiaoQing** [Bilibili/ijkplayer#2832]
[视频地址](http://oms6ub0ck.bkt.clouddn.com/mttest.mp4) Android 使用demo播放这个视频，有声音，没有画面，但是大部分mp4视频是能正常播放的，目前这个视频在有的浏览器上面也是黑屏，用迅雷播放是能正常播放的，所以视频是没有问题的
 
 版本：0.7.7.1

**Comment by raymond1012** [comment]
https://github.com/Bilibili/ijkplayer/issues/2541

**Comment by andrewhuhong** [comment]
使用demo可以正常播放， 我把video加到我的工程中，我这边测试的mp4，全部是有声音，没有画面，so库也编译，检对加入了，这是什么的问题?

**Comment by raymond1012** [comment]
please check surface

2017-03-27 15:30 GMT+08:00 Andrew <notifications@github.com>:

**Comment by kevin321happy** [comment]
同问

**Comment by XXiaoQing** [comment]
自己的问题自己来回答下，我猜测的可能原因和编码是有问题的。环境 ：Android ,使用系统的播放器 mediaplayer 能够播放，exoplayer 也是能够播放，但是 ijkplayer 不能播放，同样的视频仅仅采用 h264 编码转换了下就能够播放了，我出现这个问题的原因是视频源没有做处理，有 pc 端，移动端（Android、iOS）,视频格式虽然是 mp4 ,以前不了解（现在也只是了解皮毛），mp4 只是容器，以前没有看视频的编码格式，要解决这个问题，我从自身解决，全部转码，统一为 h264 编码

**Comment by GggggitHub** [comment]
@XXiaoQing 兄弟，你怎么解决的，如何转码的，有细节么？我也遇到了同样的一些黑屏 MP4。

**Comment by cjcj125125** [comment]
如何编码？
