### ISSUE TITLE
最低版本

### ISSUE THREAD

**Issue by zouzhenglu** [Bilibili/ijkplayer#2833]
productFlavors {
        all32 { minSdkVersion 9 }
        all64 { minSdkVersion 21 }
        // armv5 {}
        // armv7a {}
        // arm64 { minSdkVersion 21 }
        // x86 {}
    }

这样我要是用这个的话以后得发两个包了？？

**Comment by raymond1012** [comment]
1个，64位机的zygote会模拟32的环境

2017-03-14 10:36 GMT+08:00 zouzhenglu <notifications@github.com>:

**Comment by zouzhenglu** [comment]
那我是不是按照demo的协商productFlavors，到时候直接打出一个all64位的包就行了

**Comment by raymond1012** [comment]
默认一般出32位包

**Comment by zouzhenglu** [comment]
那这个minSdkVersion我不设置可以么

**Comment by raymond1012** [comment]
不行

**Comment by zouzhenglu** [comment]
ok，thx
