### ISSUE TITLE
怎样限制只能缓冲当前进度以后5分钟的视频

### ISSUE THREAD

**Issue by xbingo** [Bilibili/ijkplayer#284]
RT，为了节省流量，希望视频不要缓冲得太多。可以指定最大缓冲时间，或者是指定最大缓冲大小吗？

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/ff_ffplay_def.h#L47
修改 MAX_QUEUE_SIZE 可以改变最大预读字节数

**Comment by xbingo** [comment]
这个值可以运行时改变吗

**Comment by bbcallen** [comment]
现在不能，不过你把这个值简单换成全局变量就可以运行时修改了。

**Comment by bbcallen** [comment]
Feature added
