### ISSUE TITLE
Do  ijkplayer support  rtsp  rtp over tcp with interleave way

### ISSUE THREAD

**Issue by zds05** [Bilibili/ijkplayer#2843]
I have implemented rtsp  rtp over tcp to play video , can I play voice  with the video TCP channel ,I look the code find it do not support interleave way,It can not support demux.so do I have to use another TCP channel?

**Comment by raymond1012** [comment]
https://github.com/Bilibili/ijkplayer/issues/2790

**Comment by zds05** [comment]
已经实现rtp over tcp 单独播放音频或者视频了，但是好像ijkplayer 不支持使用一个tcp通道同时播放音频和视频，我看了下代码，不支持区分音视频

**Comment by zds05** [comment]
My fault，ijkplayer can support transfer video and audio with same TCP  channel
