### ISSUE TITLE
我把config中的ffmpeg改成--enable-ffmpeg，编译出错

### ISSUE THREAD

**Issue by zengqingf** [Bilibili/ijkplayer#2844]
错误log如下
`ffmpeg.c:223:9: warning: ignoring return value of function declared with
      warn_unused_result attribute [-Wunused-result]
        av_buffersrc_add_frame_flags(ist->filters[i]->filter, frame,
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ffmpeg.c:298:9: warning: ignoring return value of function declared with
      warn_unused_result attribute [-Wunused-result]
        av_buffersrc_add_frame(ist->filters[i]->filter, NULL);
        ^~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ffmpeg.c:1425:25: error: implicit declaration of function
      'av_buffersink_get_type' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
                    if (av_buffersink_get_type(filter) == AVMEDIA_TYPE_VIDEO)
                        ^
ffmpeg.c:1425:25: note: did you mean 'av_buffersink_get_frame'?
./libavfilter/buffersink.h:122:5: note: 'av_buffersink_get_frame' declared here
int av_buffersink_get_frame(AVFilterContext *ctx, AVFrame *frame);
    ^
ffmpeg.c:1436:40: error: implicit declaration of function
      'av_buffersink_get_time_base' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
                AVRational filter_tb = av_buffersink_get_time_base(filter);
                                       ^
ffmpeg.c:1436:40: note: did you mean 'av_buffersink_get_frame_rate'?
./libavfilter/buffersink.h:106:12: note: 'av_buffersink_get_frame_rate' declared
      here
AVRational av_buffersink_get_frame_rate(AVFilterContext *ctx);
           ^
ffmpeg.c:1436:28: error: initializing 'AVRational' (aka 'struct AVRational')
      with an expression of incompatible type 'int'
                AVRational filter_tb = av_buffersink_get_time_base(filter);
                           ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ffmpeg.c:1990:19: warning: 'avpicture_fill' is deprecated
      [-Wdeprecated-declarations]
        int ret = avpicture_fill(&pict, opkt.data, ost->st->codecpar->fo...
                  ^
./libavcodec/avcodec.h:5453:5: note: 'avpicture_fill' has been explicitly marked
      deprecated here
int avpicture_fill(AVPicture *picture, const uint8_t *ptr,
    ^
ffmpeg.c:3157:35: error: implicit declaration of function
      'av_buffersink_get_format' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        enc_ctx->sample_fmt     = av_buffersink_get_format(ost->filter->filter);
                                  ^
ffmpeg.c:3157:35: note: did you mean 'av_buffersink_get_frame'?
./libavfilter/buffersink.h:122:5: note: 'av_buffersink_get_frame' declared here
int av_buffersink_get_frame(AVFilterContext *ctx, AVFrame *frame);
    ^
ffmpeg.c:3161:35: error: implicit declaration of function
      'av_buffersink_get_sample_rate' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        enc_ctx->sample_rate    = av_buffersink_get_sample_rate(ost->fil...
                                  ^
ffmpeg.c:3161:35: note: did you mean 'av_buffersink_get_frame_rate'?
./libavfilter/buffersink.h:106:12: note: 'av_buffersink_get_frame_rate' declared
      here
AVRational av_buffersink_get_frame_rate(AVFilterContext *ctx);
           ^
ffmpeg.c:3162:35: error: implicit declaration of function
      'av_buffersink_get_channel_layout' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        enc_ctx->channel_layout = av_buffersink_get_channel_layout(ost->...
                                  ^
ffmpeg.c:3162:35: note: did you mean 'av_frame_get_channel_layout'?
./libavutil/frame.h:548:9: note: 'av_frame_get_channel_layout' declared here
int64_t av_frame_get_channel_layout       (const AVFrame *frame);
        ^
ffmpeg.c:3163:35: error: implicit declaration of function
      'av_buffersink_get_channels' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        enc_ctx->channels       = av_buffersink_get_channels(ost->filter...
                                  ^
ffmpeg.c:3169:32: error: assigning to 'AVRational' (aka 'struct AVRational')
      from incompatible type 'int'
  ...enc_ctx->time_base = av_buffersink_get_time_base(ost->filter->filter);
                        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ffmpeg.c:3180:27: error: implicit declaration of function 'av_buffersink_get_w'
      is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        enc_ctx->width  = av_buffersink_get_w(ost->filter->filter);
                          ^
ffmpeg.c:3180:27: note: did you mean 'av_buffersink_get_type'?
ffmpeg.c:1425:25: note: 'av_buffersink_get_type' declared here
                    if (av_buffersink_get_type(filter) == AVMEDIA_TYPE_VIDEO)
                        ^
ffmpeg.c:3181:27: error: implicit declaration of function 'av_buffersink_get_h'
      is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        enc_ctx->height = av_buffersink_get_h(ost->filter->filter);
                          ^
ffmpeg.c:3181:27: note: did you mean 'av_buffersink_get_w'?
ffmpeg.c:3180:27: note: 'av_buffersink_get_w' declared here
        enc_ctx->width  = av_buffersink_get_w(ost->filter->filter);
                          ^
ffmpeg.c:3185:13: error: implicit declaration of function
      'av_buffersink_get_sample_aspect_ratio' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
            av_buffersink_get_sample_aspect_ratio(ost->filter->filter);
            ^
ffmpeg.c:3185:13: note: did you mean 'av_buffersink_get_sample_rate'?
ffmpeg.c:3161:35: note: 'av_buffersink_get_sample_rate' declared here
        enc_ctx->sample_rate    = av_buffersink_get_sample_rate(ost->fil...
                                  ^
ffmpeg.c:3183:41: error: incompatible operand types ('AVRational'
      (aka 'struct AVRational') and 'int')
            ost->frame_aspect_ratio.num ? // overridden by the -aspect c...
                                        ^
ffmpeg.c:3283:28: error: implicit declaration of function
      'av_buffersink_get_hw_frames_ctx' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        if (ost->filter && av_buffersink_get_hw_frames_ctx(ost->filter->...
                           ^
ffmpeg.c:3283:28: note: did you mean 'av_buffersink_get_frame_rate'?
./libavfilter/buffersink.h:106:12: note: 'av_buffersink_get_frame_rate' declared
      here
AVRational av_buffersink_get_frame_rate(AVFilterContext *ctx);
           ^
ffmpeg.c:3284:57: warning: incompatible integer to pointer conversion passing
      'int' to parameter of type 'AVBufferRef *' (aka 'struct AVBufferRef *')
      [-Wint-conversion]
  ...= av_buffer_ref(av_buffersink_get_hw_frames_ctx(ost->filter->filter));
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./libavutil/buffer.h:147:41: note: passing argument to parameter 'buf' here
AVBufferRef *av_buffer_ref(AVBufferRef *buf);
                                        ^
ffmpeg.c:3316:15: warning: 'avcodec_copy_context' is deprecated
      [-Wdeprecated-declarations]
        ret = avcodec_copy_context(ost->st->codec, ost->enc_ctx);
              ^
./libavcodec/avcodec.h:4241:5: note: 'avcodec_copy_context' has been explicitly
      marked deprecated here
int avcodec_copy_context(AVCodecContext *dest, const AVCodecContext *src);
    ^
ffmpeg.c:3316:45: warning: 'codec' is deprecated [-Wdeprecated-declarations]
        ret = avcodec_copy_context(ost->st->codec, ost->enc_ctx);
                                            ^
./libavformat/avformat.h:898:21: note: 'codec' has been explicitly marked
      deprecated here
    AVCodecContext *codec;
                    ^
ffmpeg.c:3350:18: warning: 'codec' is deprecated [-Wdeprecated-declarations]
        ost->st->codec->codec= ost->enc_ctx->codec;
                 ^
./libavformat/avformat.h:898:21: note: 'codec' has been explicitly marked
      deprecated here
    AVCodecContext *codec;
                    ^
ffmpeg.c:3747:43: warning: 'codec' is deprecated [-Wdeprecated-declarations]
            debug = input_streams[0]->st->codec->debug<<1;
                                          ^
./libavformat/avformat.h:898:21: note: 'codec' has been explicitly marked
      deprecated here
    AVCodecContext *codec;
                    ^
ffmpeg.c:3766:35: warning: 'codec' is deprecated [-Wdeprecated-declarations]
            input_streams[i]->st->codec->debug = debug;
                                  ^
./libavformat/avformat.h:898:21: note: 'codec' has been explicitly marked
      deprecated here
    AVCodecContext *codec;
                    ^
9 warnings and 13 errors generated.
make: *** [ffmpeg.o] Error 1
make: *** Waiting for unfinished jobs....`

**Comment by freeterfei** [comment]
hello , have you resolved this problem?
