### ISSUE TITLE
播放视频时，在有运动场景的时候会有马赛克，，运动画面越快越严重

### ISSUE THREAD

**Issue by kithan** [Bilibili/ijkplayer#285]
用本地视频测试时，视频播放会没有其他的播放器清晰。
请问这种视频的运动导致的马赛克，应该怎么去分析。（接触时间比较短）

**Comment by xqq** [comment]
尝试 IjkMediaPlayer.setAvCodecOption("skip_loop_filter", "-16"); 即 "None"；
或 setMediaCodecEnabled(true) 开启硬件解码。

**Comment by Android4MediaPlayer** [comment]
@kithan 你播放的是什么视频？能提供参数么

**Comment by kithan** [comment]
一个本地的mp4视频，还有网络的直播视频;
mp4的视频信息
06-23 11:17:19.485: I/IJKMEDIA(26805):   Metadata:
06-23 11:17:19.485: I/IJKMEDIA(26805):     major_brand     : 
06-23 11:17:19.485: I/IJKMEDIA(26805): mp42
06-23 11:17:19.490: I/IJKMEDIA(26805):     minor_version   : 
06-23 11:17:19.490: I/IJKMEDIA(26805): 0
06-23 11:17:19.490: I/IJKMEDIA(26805):     compatible_brands: 
06-23 11:17:19.490: I/IJKMEDIA(26805): isommp42
06-23 11:17:19.490: I/IJKMEDIA(26805):     creation_time   : 
06-23 11:17:19.490: I/IJKMEDIA(26805): 2015-02-10 07:28:35
06-23 11:17:19.490: I/IJKMEDIA(26805):   Duration: 
06-23 11:17:19.490: I/IJKMEDIA(26805): 00:01:36.06
06-23 11:17:19.490: I/IJKMEDIA(26805): , start: 
06-23 11:17:19.490: I/IJKMEDIA(26805): 0.000000
06-23 11:17:19.490: I/IJKMEDIA(26805): , bitrate: 
06-23 11:17:19.490: I/IJKMEDIA(26805): 500 kb/s
06-23 11:17:19.490: I/IJKMEDIA(26805):     Stream #0:0
06-23 11:17:19.490: I/IJKMEDIA(26805): (und)
06-23 11:17:19.490: I/IJKMEDIA(26805): : Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 640x360 [SAR 1:1 DAR 16:9], 449 kb/s
06-23 11:17:19.490: I/IJKMEDIA(26805): , 
06-23 11:17:19.490: I/IJKMEDIA(26805): 24 fps, 
06-23 11:17:19.490: I/IJKMEDIA(26805): 24 tbr, 
06-23 11:17:19.490: I/IJKMEDIA(26805): 24k tbn, 
06-23 11:17:19.490: I/IJKMEDIA(26805): 48 tbc
06-23 11:17:19.490: I/IJKMEDIA(26805):  (default)
06-23 11:17:19.490: I/IJKMEDIA(26805):     Metadata:
06-23 11:17:19.490: I/IJKMEDIA(26805):       creation_time   : 
06-23 11:17:19.490: I/IJKMEDIA(26805): 2015-02-10 07:28:32
06-23 11:17:19.490: I/IJKMEDIA(26805):       handler_name    : 
06-23 11:17:19.490: I/IJKMEDIA(26805): o00155kqubm.2.temp.mp4_tmp_0.mp4_tmp_h264.mp4_tmp.h264 - Imported with GPAC 0.5.0-rev4065
06-23 11:17:19.490: I/IJKMEDIA(26805):     Stream #0:1
06-23 11:17:19.490: I/IJKMEDIA(26805): (und)
06-23 11:17:19.490: I/IJKMEDIA(26805): : Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 48 kb/s
06-23 11:17:19.490: I/IJKMEDIA(26805):  (default)
06-23 11:17:19.490: I/IJKMEDIA(26805):     Metadata:
06-23 11:17:19.490: I/IJKMEDIA(26805):       creation_time   : 

网络视频的帧率比较高，下面是视频信息
06-23 10:57:41.820: I/IJKMEDIA(24905): , start: 
06-23 10:57:41.820: I/IJKMEDIA(24905): 79346.122144
06-23 10:57:41.820: I/IJKMEDIA(24905): , bitrate: 
06-23 10:57:41.820: I/IJKMEDIA(24905): N/A
06-23 10:57:41.820: I/IJKMEDIA(24905):   Program 0 
06-23 10:57:41.820: I/IJKMEDIA(24905):     Metadata:
06-23 10:57:41.820: I/IJKMEDIA(24905):       variant_bitrate : 
06-23 10:57:41.820: I/IJKMEDIA(24905): 0
06-23 10:57:41.820: I/IJKMEDIA(24905):     Stream #0:0
06-23 10:57:41.820: I/IJKMEDIA(24905): : Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt470bg), 720x576 [SAR 16:11 DAR 20:11]
06-23 10:57:41.820: I/IJKMEDIA(24905): , 
06-23 10:57:41.820: I/IJKMEDIA(24905): 50 fps, 
06-23 10:57:41.820: I/IJKMEDIA(24905): 25 tbr, 
06-23 10:57:41.820: I/IJKMEDIA(24905): 90k tbn, 
06-23 10:57:41.820: I/IJKMEDIA(24905): 50 tbc
06-23 10:57:41.820: I/IJKMEDIA(24905):     Stream #0:1
06-23 10:57:41.820: I/IJKMEDIA(24905): : Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 124 kb/s
06-23 10:57:41.830: I/IJKMEDIA(24905): SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
06-23 10:57:41.830: I/IJKMEDIA(24905): SDL_Android_AudioTrack: ENCODING_PCM_16BIT
06-23 10:57:41.830: I/IJKMEDIA(24905): SDL_Android_AudioTrack_new: init volume as 1.000000/(0.000000,1.000000)
06-23 10:57:41.830: I/IJKMEDIA(24905): AudioCodec: avcodec, aac
06-23 10:57:41.830: I/IJKMEDIA(24905): SDL_RunThread: [25139] ff_aout_android
06-23 10:57:41.830: I/IJKMEDIA(24905): SDL_RunThread: [25140] ff_audio_dec
06-23 10:57:41.835: I/IJKMEDIA(24905): VideoCodec: avcodec, h264

根据xqq的方法 开启硬解就ok了 ，非常干系。（skip_loop_filter参数设置会导致没有视频流）。
但是有一个问题，硬解mediacodec对于android来说 ，现在不支持硬解的情况，比例多么？不支持硬解的话，开启功能后能自动切换到软解么，还是需要在上层判断再开启mediacodec

**Comment by bbcallen** [comment]
mediacodec只支持 安卓4.1.2 及以上，MTK只支持安卓 4.3 及以上。
旗舰机基本都支持，小众SoC需要测试。

判断的因素很多，ijkplayer 自带一套最简单的判断。
https://github.com/Bilibili/ijkplayer/blob/ba31a7bb7ee20276354499b21fb297fa80848301/android/ijkplayer/player-java/src/main/java/tv/danmaku/ijk/media/player/IjkMediaCodecInfo.java

不支持分好几种情况，H264以外或者解码器初始化失败都会自动跳软解。但是安卓魔改系统的兼容性实在是很差，很多时候，从解码器API并不能得知出错的状态，这种情况可能就会花屏，绿屏，黑屏，闪退，卡死等等。所以兼容性得你自己测试。

马赛克和多线程没关系，试试
IjkMediaPlayer.setAvCodecOption("skip_loop_filter", "0");

**Comment by kithan** [comment]
谢谢bbcallen，非常详细。
