### ISSUE TITLE
FFmpeg 层如何向上层抛事件？

### ISSUE THREAD

**Issue by zhanggao** [Bilibili/ijkplayer#2853]
能调用 ffp_notify_msg1 这些函数不？

**Comment by raymond1012** [comment]
可以

2017-03-16 19:29 GMT+08:00 zhanggao <notifications@github.com>:

**Comment by zhanggao** [comment]
FFmpeg 层没有 FFPlayer 对象，调用 ffp_notify_msg1 需要传FFPlayer 对象，这个如何处理呢？
