### ISSUE TITLE
ijkplayer的demo切换音轨播放跳跃

### ISSUE THREAD

**Issue by Khaos116** [bilibili/ijkplayer#2854]
您好：
       我是一名安卓开发者，我在Demo中播放本地视频时，切换音轨播放会跳跃，安卓原生播放器和VLC切换音轨就不会这样，但是我非常喜欢ijkplayer，不太想用其他的播放器，希望大神能修复这个问题O(∩_∩)O~~谢谢！！

**Comment by xiongziliang** [comment]
这个问题我解决了 ： ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "min-frames", 2);

**Comment by liy452083759** [comment]
谢谢，我试试

**Comment by centuryrain** [comment]
iOS 如何实现切换音轨？

**Comment by 52yaoer** [comment]
伴音切换不回来到原音呢，咋设置的？

**Comment by 52yaoer** [comment]
你好，已经解决了，，是传参数的问题，，

**Comment by VeiZhang** [comment]
@xiongziliang min-frames 这个配置是设置缓存大小，会影响播放缓冲。有没有其他办法？

**Comment by xiongziliang** [comment]
> @xiongziliang 你好，min-frames 这个配置是设置缓存大小，会影响播放缓冲。有没有其他办法？

播放器缓冲还有很多地方设置 这个只是其一(ijk实现的 好像是解码帧缓存个数) ，你可以通过设置其他FFmpeg的缓存选项试试

**Comment by VeiZhang** [comment]
@xiongziliang 好的，谢谢

**Comment by yuan631111976** [comment]
我修改源码，解决了，切换播放跳越，音画不同的的问题，做到了无感切换音轨  https://download.csdn.net/download/u010422517/21520852

**Comment by Khaos116** [comment]
![image](https://user-images.githubusercontent.com/11989916/131288793-70a41266-7db2-4b0e-98c6-e5f9c20f66a8.png)
好家伙

**Comment by xia-chu** [comment]
> ![image](https://user-images.githubusercontent.com/11989916/131288793-70a41266-7db2-4b0e-98c6-e5f9c20f66a8.png)
> 好家伙

看标题 估计没源码。。。

**Comment by Khaos116** [comment]
![image](https://user-images.githubusercontent.com/11989916/131309771-c5a3ce4e-6d20-451f-b5ce-b04c2dcf20ea.png)

**Comment by Khaos116** [comment]
> > ![image](https://user-images.githubusercontent.com/11989916/131288793-70a41266-7db2-4b0e-98c6-e5f9c20f66a8.png)
> > 好家伙
> 
> 看标题 估计没源码。。。
肯定是SO，尴尬的是下载量为0

**Comment by dlisagod** [comment]
啊，这个问题我也遇到了，难搞噢，看了别人的设置那个参数的也不起效
