### ISSUE TITLE
播放iOS录制的视频出现视频方向旋转了90度的问题

### ISSUE THREAD

**Issue by XiMuYouZi** [Bilibili/ijkplayer#2857]
我使用AVFoundation框架录制了视频，然后使用ijkplayer的demo播放该视频，出现视频向右旋转了90度的问题，不管是竖屏录制，还是横屏录制，都会出现视频方向不对的问题。

请问如何解决呢？

**Comment by Android4MediaPlayer** [comment]
怎么解决的

**Comment by Android4MediaPlayer** [comment]
avfilter或者gles？

**Comment by BlueTopsky** [comment]
怎么解决的啊

**Comment by DSKcpp** [comment]
怎么解决的？

**Comment by Echo-Joker** [comment]
怎么解决的

**Comment by GoKnow** [comment]
怎么解决的

**Comment by kuxingsen** [comment]
直播场景下通过AVFoundation启用摄像头录制内容时，可以为AVVaptureSession添加AVCaptureVideoDataOutput以获得录制的视频帧。为output的AVCaptureConnection设置VideoOrientation为AVCaptureVideoOrientationPortrait即可。
AVVaptureSession* iSession;
AVCaptureVideoDataOutput* videoOutput;

 `-(void)initVideoDataOuput {
    self.videoOutput = [[AVCaptureVideoDataOutput alloc] init];
    self.videoOutput.alwaysDiscardsLateVideoFrames = YES;
    self.videoOutput.videoSettings = [NSDictionary dictionaryWithObject:[NSNumber numberWithInt:kCVPixelFormatType_32BGRA] forKey:(id)kCVPixelBufferPixelFormatTypeKey];//设置像素格式
    if ([self.iSession canAddOutput:self.videoOutput])    [self.iSession addOutput:self.videoOutput];
    AVCaptureConnection *connection = [self.videoOutput connectionWithMediaType:AVMediaTypeVideo];
    [connection setVideoOrientation:AVCaptureVideoOrientationPortrait];
    dispatch_queue_t queue = dispatch_queue_create("myQueue", NULL);
    [self.videoOutput setSampleBufferDelegate:self queue:queue];//self实现<AVCaptureVideoDataOutputSampleBufferDelegate>,回调- (void)captureOutput:didOutputSampleBuffer:fromConnection:(AVCaptureConnection *)connection
}
 `
