### ISSUE TITLE
ios 8+ 如何切换软硬解码

### ISSUE THREAD

**Issue by wdpeng** [Bilibili/ijkplayer#286]
如题

**Comment by Zard1096** [comment]
根据要求自行创建AV/MP(硬解)的控制器或者FF(软解)的控制器

**Comment by bbcallen** [comment]
见 IJKFFOptions 的 videotoolboxEnabled 字段，最新版本默认就是开启的。

**Comment by walkermi** [comment]
为何又改成默认不开启了？

    options.videoToolboxEnabled     = NO;

**Comment by bbcallen** [comment]
因为我希望开启硬解的人知道自己在做什么。
