### ISSUE TITLE
[IjkMediaPlayer: Error (-10000,0)]播放在线视频几分钟后报错-10000

### ISSUE THREAD

**Issue by frendyxzc** [Bilibili/ijkplayer#2860]
错误如题，以下为相关日志，请问有解决方法吗？

03-19 17:57:26.250 27304-28550/com.aaa.app I/IJKMEDIA: ===== versions =====
03-19 17:57:26.250 27304-28628/com.aaa.app I/IJKMEDIA: SDL_RunThread: [28628] ff_msg_loop
03-19 17:57:26.250 27304-28550/com.aaa.app I/IJKMEDIA: ijkplayer    : k0.7.6-28-geb265a5
03-19 17:57:26.250 27304-28550/com.aaa.app I/IJKMEDIA: FFmpeg       : ff3.2--ijk0.7.6--20170203--001
03-19 17:57:26.250 27304-28550/com.aaa.app I/IJKMEDIA: libavutil    : 55.34.100
03-19 17:57:26.250 27304-28550/com.aaa.app I/IJKMEDIA: libavcodec   : 57.64.100
03-19 17:57:26.250 27304-28550/com.aaa.app I/IJKMEDIA: libavformat  : 57.56.100
03-19 17:57:26.250 27304-28550/com.aaa.app I/IJKMEDIA: libswscale   : 4.2.100
03-19 17:57:26.250 27304-28550/com.aaa.app I/IJKMEDIA: libswresample: 2.3.100
03-19 17:57:26.250 27304-28550/com.aaa.app I/IJKMEDIA: ===== options =====
03-19 17:57:26.250 27304-28550/com.aaa.app I/IJKMEDIA: player-opts : loop                         = 1
03-19 17:57:26.250 27304-28550/com.aaa.app I/IJKMEDIA: format-opts : ijkapplication               = 1253974224
03-19 17:57:26.250 27304-28550/com.aaa.app I/IJKMEDIA: format-opts : ijkiomanager                 = 1259303816
03-19 17:57:26.250 27304-28550/com.aaa.app I/IJKMEDIA: ===================
03-19 17:57:26.260 27304-28629/com.aaa.app I/IJKMEDIA: SDL_RunThread: [28629] ff_vout
03-19 17:57:26.270 27304-28630/com.aaa.app I/IJKMEDIA: SDL_RunThread: [28630] ff_read
03-19 17:57:26.270 27304-28630/com.aaa.app I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
03-19 17:57:26.450 27304-28550/com.aaa.app W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
03-19 17:57:29.270 27304-28630/com.aaa.app I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
03-19 17:57:29.300 27304-28630/com.aaa.app I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
03-19 17:57:29.360 27304-28630/com.aaa.app I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
03-19 17:57:29.360 27304-28630/com.aaa.app I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 3
03-19 17:57:29.360 27304-28630/com.aaa.app I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
03-19 17:57:29.400 27304-28630/com.aaa.app I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
03-19 17:57:29.450 27304-28630/com.aaa.app I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 4
03-19 17:57:29.660 27304-28630/com.aaa.app E/IJKMEDIA: Option ijkiomanager not found.
03-19 17:57:29.670 27304-28630/com.aaa.app I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 3
03-19 17:57:29.670 27304-28630/com.aaa.app I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
03-19 17:57:29.700 27304-28630/com.aaa.app I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
03-19 17:57:29.740 27304-28630/com.aaa.app I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 4
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: max_frame_duration: 10.000
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'http://video.myxianwen.cn/vods5/201702/origin/55-201702171536031_tr.mp4':
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA:   Metadata:
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA:     major_brand     : 
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: isom
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA:     minor_version   : 
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: 512
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA:     compatible_brands: 
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: isomiso2avc1mp41
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA:     encoder         : 
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: Lavf55.19.104
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA:   Duration: 
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: 00:02:57.13
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: , start: 
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: 0.000000
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: , bitrate: 
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: 720 kb/s
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA:     Stream #0:0
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: (und)
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: : Video: h264 (avc1 / 0x31637661), yuv420p, 720x404 [SAR 404:405 DAR 16:9], 586 kb/s
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: , 
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: 24 fps, 
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: 24 tbr, 
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: 12288 tbn, 
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: 48 tbc
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA:  (default)
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA:     Metadata:
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA:       handler_name    : 
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: VideoHandler
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA:     Stream #0:1
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: (und)
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: : Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA:  (default)
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA:     Metadata:
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA:       handler_name    : 
03-19 17:57:29.780 27304-28630/com.aaa.app I/IJKMEDIA: SoundHandler
03-19 17:57:29.790 27304-28630/com.aaa.app I/IJKMEDIA: SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
03-19 17:57:29.790 27304-28630/com.aaa.app I/IJKMEDIA: SDL_Android_AudioTrack: ENCODING_PCM_16BIT
03-19 17:57:29.800 27304-28630/com.aaa.app I/IJKMEDIA: SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(0.000000,1.000000)
03-19 17:57:29.800 27304-28630/com.aaa.app I/IJKMEDIA: audio_session_id = 817
03-19 17:57:29.810 27304-28644/com.aaa.app I/IJKMEDIA: SDL_RunThread: [28644] ff_aout_android
03-19 17:57:29.810 27304-28630/com.aaa.app I/IJKMEDIA: AudioCodec: avcodec, aac
03-19 17:57:29.810 27304-28645/com.aaa.app I/IJKMEDIA: SDL_RunThread: [28645] ff_audio_dec
03-19 17:57:29.820 27304-28630/com.aaa.app I/IJKMEDIA: VideoCodec: avcodec, h264
03-19 17:57:29.820 27304-28630/com.aaa.app W/IJKMEDIA: fps: 24.000000 (normal)
03-19 17:57:29.820 27304-28630/com.aaa.app W/IJKMEDIA: fps: 24.000000 (normal)
03-19 17:57:29.830 27304-28650/com.aaa.app I/IJKMEDIA: SDL_RunThread: [28650] ff_video_dec
03-19 17:57:30.370 27304-28550/com.aaa.app I/tv.danmaku.ijk.media.player.IjkMediaPlayer: Info: MEDIA_INFO_VIDEO_RENDERING_START
03-19 17:57:32.970 27304-28630/com.aaa.app E/IJKMEDIA: Stream ends prematurely at 3628558, should be 15956304
03-19 17:57:32.970 27304-28630/com.aaa.app E/IJKMEDIA: stream 1, offset 0x375f74: partial file
03-19 17:57:32.980 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:57:33.090 27304-28630/com.aaa.app E/IJKMEDIA: stream 1, offset 0x3760f9: partial file
03-19 17:57:33.090 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:57:33.200 27304-28630/com.aaa.app E/IJKMEDIA: stream 0, offset 0x376277: partial file
03-19 17:57:33.200 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:57:33.310 27304-28630/com.aaa.app E/IJKMEDIA: stream 1, offset 0x376784: partial file
03-19 17:57:33.310 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:57:33.420 27304-28630/com.aaa.app E/IJKMEDIA: stream 1, offset 0x376904: partial file
... ...
... ...
03-19 17:58:01.030 27304-28630/com.aaa.app I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 3
03-19 17:58:01.030 27304-28630/com.aaa.app I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
03-19 17:58:01.070 27304-28630/com.aaa.app I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
03-19 17:58:01.110 27304-28630/com.aaa.app I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 4
03-19 17:58:02.140 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:02.250 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:02.360 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:02.470 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:02.580 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:02.690 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
... ...
... ...
03-19 17:58:05.010 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:05.120 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:05.230 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:05.340 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:05.450 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:05.560 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:05.670 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:05.780 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:05.890 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:06.010 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:06.120 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:06.230 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:06.340 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:06.450 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:06.560 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:06.670 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:06.780 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:06.890 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:06.960 27304-28646/com.aaa.app E/IJKMEDIA: Invalid nal size 1230
03-19 17:58:06.960 27304-28646/com.aaa.app E/IJKMEDIA: Error splitting the input into NAL units.
03-19 17:58:07.000 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:07.110 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:07.220 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:07.330 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:07.440 27304-28630/com.aaa.app I/IJKMEDIA: ffp_toggle_buffering: error: -5
03-19 17:58:07.440 27304-28630/com.aaa.app E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
03-19 17:58:07.440 27304-28550/com.aaa.app E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
03-19 17:58:07.550 27304-28630/com.aaa.app I/IJKMEDIA: ffp_toggle_buffering: eof

**Comment by raymond1012** [comment]
Error splitting the input into NAL units    —源文件的h264有问题

**Comment by frendyxzc** [comment]
@raymond1012 这几天线上比较多视频出现这种情况，在H5和iOS好像是可以正常播放的，想问下在安卓是有什么特殊格式不支持吗

**Comment by raymond1012** [comment]
没有

2017-03-20 11:45 GMT+08:00 frendy <notifications@github.com>:

**Comment by frendyxzc** [comment]
@raymond1012 已解决，视频服务器问题，谢谢

**Comment by liweilup** [comment]
@frendyxzc  我也遇到这个问题请问是什么原因引起的？谢谢

**Comment by liweilup** [comment]
在VLC 用H265格式起RTSP服务就会报Error splitting the input into NAL units  ，但是直接打开H265文件是可以的，由于刚接触视频这块，请问有那些原因会导致这个问题，谢谢告知

**Comment by frendyxzc** [comment]
@liweilup 简单搭个网页版拉流试试？

我这边之前是视频服务器配置问题引起的，现象是播一段时间后缓冲的都是坏帧

**Comment by LittleNum** [comment]
@frendyxzc 请问，视频服务配置问题，具体是指什么，我目前也碰到了这个问题，没有头绪，望指教。。

**Comment by XuYinShuang** [comment]
你好，我也是在线播放视频碰到这个问题，请问你是怎么解决的呢，我这边是Android

**Comment by YeJiashen** [comment]
> 

您这个问题解决了吗, 我这边也是Android, 遇到了这个问题. 您那边的服务器是做了哪些配置上的修改呢?
