### ISSUE TITLE
Android   黑屏 

### ISSUE THREAD

**Issue by XXiaoQing** [Bilibili/ijkplayer#2863]
版本：0.7.8.1  使用 demo  播放 [http://static.video.mtdz.xiaohua.com/video/2241705/b19550f9-85ec-5e3f-03f0-1c3b99600091.mp4](url) ，不管是使用硬解码还是软解码都是有声音，没有画面黑屏，其他视频播放正常

**Comment by woodnaonly** [comment]
兄弟你是怎么解决的？

**Comment by XXiaoQing** [comment]
@woodnaonly 现在还在解决中

**Comment by woodnaonly** [comment]
@XXiaoQing 兄弟切换到exo模式 可以解决

**Comment by XXiaoQing** [comment]
@woodnaonly 使用 exoPlayer  的确是可以播放，但是  exoPlayer  在切换全屏的时候支持不是很好，还引入了3000多个方法，所以就没有使用。现在的方法是对视频就行转码，用户上传视频前统一转码，这样就能播放，现在问题出在转码上了
