### ISSUE TITLE
buffer百分比对吗

### ISSUE THREAD

**Issue by Android4MediaPlayer** [Bilibili/ijkplayer#287]
@bbcallen  ffp_notify_msg3(ffp, FFP_MSG_BUFFERING_UPDATE, (int)buf_time_position, buf_percent);
buf_percent是缓冲的时候的百分比不？

**Comment by Zard1096** [comment]
是的

**Comment by Android4MediaPlayer** [comment]
不对吧

**Comment by Zard1096** [comment]
buf_percent是已经缓冲了多少的百分比，不用再除以100

**Comment by Android4MediaPlayer** [comment]
@Zard1096 你DEBUG了吗 发现不准

**Comment by Zard1096** [comment]
我在极差的网络环境下percent到100就能继续播放了，没问题，你是指什么不准？

**Comment by Android4MediaPlayer** [comment]
上报是否及时问题，计算是对的。
