### ISSUE TITLE
播放视频，手机不息屏 是怎么设置的

### ISSUE THREAD

**Issue by wanglifeifei** [Bilibili/ijkplayer#2875]

**Comment by raymond1012** [comment]
see stayAwake

2017-03-22 18:59 GMT+08:00 wanglifeifei <notifications@github.com>:

**Comment by wanglifeifei** [comment]
是系统方法吗，我用ijkplayer播放音乐，然后手机一直不息屏，然后 我也设置了让系统自动息屏，也不管用

**Comment by raymond1012** [comment]
because stayAwake call PowerManager.WakeLock

2017-03-23 11:51 GMT+08:00 wanglifeifei <notifications@github.com>:

**Comment by wanglifeifei** [comment]
如果，我想让在播放视频的过程中 手机自动息屏，我该怎么设置？

**Comment by wanglifeifei** [comment]
非常感谢，我已经看到在ijkplayer 不息屏的处理的方法
