### ISSUE TITLE
Using vf filters when VideoToolbox is enabled

### ISSUE THREAD

**Issue by animaonline** [Bilibili/ijkplayer#2878]
It seems that when I enable VideoToolbox all filters are discarded, does anyone know how to make it work together?

```
    [options setPlayerOptionIntValue:1 forKey:@"videotoolbox"];
    [options setFormatOptionIntValue:1 forKey:@"reconnect"];

    [options setPlayerOptionValue:@"crop=1900:1000:590:550" forKey:@"vf0"];
```

**Comment by bbcallen** [comment]
No such support.
avfilters are mostly YUV420p based, while VideoToolbox frames are NV12.

You have to implement such convert chain, by yourself.
NV12 -> YUV420p -> avfilters -> YUV420p -> NV12
or
NV12 -> NV12 based avfilters -> NV12
In addition, extra frame copy may slow down the decode-render chain.

If you focus on certain filters, it's better to link gpu-based-filters against ijkplayer's render layer, eg. GPUImage.
That's also need to modify the source code.
