### ISSUE TITLE
一个视频被切成多个mp4的分片，用ijkplayer要怎么播放呢？

### ISSUE THREAD

**Issue by uimeet** [Bilibili/ijkplayer#2886]
一个视频被切成多个mp4的分片，用ijkplayer要怎么播放呢？

谢谢

**Comment by uimeet** [comment]
我知道有人提过类似问题，但是得到的回复是使用ffmpeg concat合并视频，但是视频都是http地址，难道需要把所有视频下载到本地来合并之后再播放？

**Comment by uimeet** [comment]
没有类似m3u8这种解决方案吗？

**Comment by raymond1012** [comment]
concat 并不是把concat视频下载到本地，只需要按照格式提供url即可

**Comment by maolubin** [comment]
@raymond1012 哥求例子啊，新人萌懂

**Comment by Android4MediaPlayer** [comment]
@maolubin http://trac.ffmpeg.org/wiki/Concatenate，请参考这个制作concat文件
