### ISSUE TITLE
拖动进度条，之前缓冲的视频音频都没有了。及如何播放分片视频。

### ISSUE THREAD

**Issue by sarahzuo** [Bilibili/ijkplayer#289]
非常感谢bbcallen提供那么好的视频库，我有一个问题请教。
当拖动播放器的进度条，比如快进或者退后一定时间，我用如下方法[myIJKMediaPlaybackObject setCurrentPlaybackTime:someTime]， 这样设置了播放进度之后发现之前缓冲的视频和音频size都变成了0，得重新从设置的时间开始缓冲。而我们平常所使用的播放器体验是在缓冲区内拖动进度条并不会丢失已经缓存的数据。所以请问我应该怎么做才能保住已经缓冲了的数据呢？

**Comment by bbcallen** [comment]
暂时不支持。具体如何实现，我还在考虑。

**Comment by sarahzuo** [comment]
请问近期会添加这个功能吗？如果近期不添加，能不能给个思路呢？想想：）

**Comment by sarahzuo** [comment]
还有一个关于播放分片视频的问题，我查阅了之前相关的issue #211 ,和 #38 ,还是有些不懂：

1. 例如一个视频有3段分片，是不是在创建播放器的时候将第一段分片的url当作参数传入，后两段分片写入一个文件？
2. 这个文件怎样传给ffmpeg呢？
3. 文件中的duration是怎样获取的呢？
这些问题研究了半天还没有结果，还请各位不吝赐教。

**Comment by sarahzuo** [comment]
当播放优酷上的视频时（大部分都是分片的），如果够得到此视频的m3u8地址，是否直接将此m3u8地址传入就万事大吉了呢？即：[[IJKFFMoviePlayerController alloc] initWithContentURL:[NSURL URLWithString:m3u8_url] withOptions:[IJKFFOptions optionsByDefault]];
如果以上可行，是不是并不需要获取所有的分片url ，然后在客户端将这些url根据ffmpeg的concat规则组装成txt了？

**Comment by sarahzuo** [comment]
最后终于整明白了。
1、如果播放视频网站的分片视频，如果能够获取到视频的m3u8地址，则将这个m3u8地址作为参数传入
即：[[IJKFFMoviePlayerController alloc] initWithContentURL:[NSURL URLWithString:m3u8_url] withOptions:[IJKFFOptions optionsByDefault]];
2、如果能够解析出每一个分片的url，则将这一系列url写成一个txt文件，此内部格式为：
ffconcat version 1.0
file 'url1'
duration xx
file 'url2'
duration xx
...

将这个txt文件的url传入，即
[[IJKFFMoviePlayerController alloc] initWithContentURL:[NSURL URLWithString:txt_url] withOptions:[IJKFFOptions optionsByDefault]];

ps：用这两种方式我都没有用有三个参数的构造函数（- (id)initWithContentURL:(NSURL *)aUrl
             withOptions:(IJKFFOptions *)options
     withSegmentResolver:(id<IJKMediaSegmentResolver>)segmentResolver），所以不知道这第三个参数的作用。

**Comment by simtice** [comment]
@sarahzuo 我的还是不行
ffconcat version 1.0
file http://cn-gdfs5-dx.acgvideo.com/vg7/2/0e/6546710-1.flv?expires=1460724300&ssig=yqOcE8bCE8ntlgkB1v7rqQ&oi=3070666578&appkey=f3bb208b3d081dc8&or=3074230573&rate=0
duration 267544
file http://cn-gdfs5-dx.acgvideo.com/vg7/2/0e/6546710-2.flv?expires=1460724300&ssig=jJ_iWb08zIhLxU6KICXx4w&oi=3070666578&appkey=f3bb208b3d081dc8&or=3074230573&rate=0
duration 442732
file http://cn-gdfs5-dx.acgvideo.com/vg7/2/0e/6546710-3.flv?expires=1460724300&ssig=T-c2-csCpdmW3xuCdKIHGg&oi=3070666578&appkey=f3bb208b3d081dc8&or=3074230573&rate=0
duration 276423

能否帮忙测试以下
