### ISSUE TITLE
ios 最新版本 播放带key的 m3u8失败，同样的地址通过VLC  还有 ffplay 是可以正常播放的

### ISSUE THREAD

**Issue by jshqhxm** [Bilibili/ijkplayer#2891]
av_version_info: ff3.2--ijk0.7.6--20170203--001

ijk_version_info: k0.7.8.1

ijkmp_set_inject_opaque(0x60000001bab0)

ijkmp_set_inject_opaque()=void

ijkmp_set_ijkio_inject_opaque(0x60000001bab0)

ijkmp_set_ijkio_inject_opaque()=void

2017-03-23 17:06:21.799 IJKMediaDemo[96425:961368] OK setup GL

ijkmp_ios_set_view(glView=0x7f8329e299e0)

ijkmp_ios_set_view(glView=0x7f8329e299e0)=void

2017-03-23 17:06:21.801 IJKMediaDemo[96425:961368] invalidateRenderBuffer

2017-03-23 17:06:21.801 IJKMediaDemo[96425:1093725] IJKSDLGLView: setupDisplay not ready

ijkmp_set_data_source(url="http://vodlist.5iketang.com:8086/playUri.m3u8?vid=VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2&vid2=")

ijkmp_set_data_source(url="http://vodlist.5iketang.com:8086/playUri.m3u8?vid=VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2&vid2=")=0

ijkmp_prepare_async()

===== versions =====

[FFPlayer @ 0x7f832a853400] ijkplayer    : k0.7.8.1

[FFPlayer @ 0x7f832a853400] FFmpeg       : ff3.2--ijk0.7.6--20170203--001

[FFPlayer @ 0x7f832a853400] libavutil    : 55.34.100

[FFPlayer @ 0x7f832a853400] libavcodec   : 57.64.100

[FFPlayer @ 0x7f832a853400] libavformat  : 57.56.100

[FFPlayer @ 0x7f832a853400] libswscale   : 4.2.100

[FFPlayer @ 0x7f832a853400] libswresample: 2.3.100

===== options =====

[FFPlayer @ 0x7f832a853400] player-opts : video-pictq-size             = 3

[FFPlayer @ 0x7f832a853400] player-opts : overlay-format               = fcc-_es2

[FFPlayer @ 0x7f832a853400] player-opts : max-fps                      = 30

[FFPlayer @ 0x7f832a853400] player-opts : framedrop                    = 0

[FFPlayer @ 0x7f832a853400] player-opts : videotoolbox-max-frame-width = 960

[FFPlayer @ 0x7f832a853400] player-opts : videotoolbox                 = 0

[FFPlayer @ 0x7f832a853400] player-opts : start-on-prepared            = 1

[FFPlayer @ 0x7f832a853400] format-opts : ijkapplication               = 140201319247152

[FFPlayer @ 0x7f832a853400] format-opts : ijkiomanager                 = 105553118698272

[FFPlayer @ 0x7f832a853400] format-opts : user-agent                   = ijkplayer

[FFPlayer @ 0x7f832a853400] format-opts : auto_convert                 = 0

[FFPlayer @ 0x7f832a853400] format-opts : timeout                      = 30000000

[FFPlayer @ 0x7f832a853400] format-opts : reconnect                    = 1

[FFPlayer @ 0x7f832a853400] format-opts : safe                         = 0

===================

ijkmp_prepare_async()=0

[http @ 0x7f8329f2ff60] Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'

2017-03-23 17:06:21.813 IJKMediaDemo[96425:961368] invalidateRenderBuffer

2017-03-23 17:06:21.813 IJKMediaDemo[96425:1093725] IJKSDLGLView: setupDisplay not ready

[http @ 0x7f832b853200] the user-agent option is deprecated, please use user_agent option

[http @ 0x7f8329f2ff60] request: GET /playUri.m3u8?vid=VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2&vid2= HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=0-

Connection: close

Host: vodlist.5iketang.com:8086

Icy-MetaData: 1

[hls,applehttp @ 0x7f832b85b400] Format hls,applehttp probed with size=2048 and score=100

[hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00000.ts', offset 0, playlist 0

[http @ 0x7f832b871800] the user-agent option is deprecated, please use user_agent option

[http @ 0x7f8329f02440] request: GET /v/fetchplaykey?&vid=VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f&df=2 HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Connection: close

Host: vodlist.5iketang.com

Icy-MetaData: 1

[AVIOContext @ 0x7f8329e23ce0] Statistics: 16 bytes read, 0 seeks

[hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0

[hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00001.ts', offset 0, playlist 0

[hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0

[hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00002.ts', offset 0, playlist 0

[hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0

[hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00003.ts', offset 0, playlist 0

[hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0

[hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00004.ts', offset 0, playlist 0

[hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0

[hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00005.ts', offset 0, playlist 0

[hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0

[hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00006.ts', offset 0, playlist 0

[hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0

[hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00007.ts', offset 0, playlist 0

[hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0

[hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00008.ts', offset 0, playlist 0

[hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0

[hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00009.ts', offset 0, playlist 0

[hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0

[hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00010.ts', offset 0, playlist 0

[hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0

[hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00011.ts', offset 0, playlist 0

[hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0

[hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00012.ts', offset 0, playlist 0

[hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0

[hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00013.ts', offset 0, playlist 0

[hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0

[hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00014.ts', offset 0, playlist 0

[hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0

[hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00015.ts', offset 0, playlist 0

[hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0

[hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00016.ts', offset 0, playlist 0

[hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0

[hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00017.ts', offset 0, playlist 0

[hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0

[hls,applehttp @ 0x7f832b85b400] Error when loading first segment 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00000.ts'

[AVIOContext @ 0x7f8329d392f0] Statistics: 2737 bytes read, 0 seeks

http://vodlist.5iketang.com:8086/playUri.m3u8?vid=VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2&vid2=: Invalid data found when processing input

2017-03-23 17:06:22.137 IJKMediaDemo[96425:961368] FFP_MSG_ERROR: 0

2017-03-23 17:06:22.138 IJKMediaDemo[96425:961368] IJKMPMoviePlayBackStateDidChange 2: paused

2017-03-23 17:06:22.138 IJKMediaDemo[96425:961368] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1

av_version_info: ff3.2--ijk0.7.6--20170203--001

ijk_version_info: k0.7.8.1

ijkmp_set_inject_opaque(0x608000203710)

ijkmp_set_inject_opaque()=void

ijkmp_set_ijkio_inject_opaque(0x608000203710)

ijkmp_set_ijkio_inject_opaque()=void

2017-03-23 17:06:22.357 IJKMediaDemo[96425:961368] OK setup GL

ijkmp_ios_set_view(glView=0x7f8329d5cb90)

ijkmp_ios_set_view(glView=0x7f8329d5cb90)=void

2017-03-23 17:06:22.359 IJKMediaDemo[96425:961368] invalidateRenderBuffer

2017-03-23 17:06:22.359 IJKMediaDemo[96425:1093725] IJKSDLGLView: setupDisplay not ready

2017-03-23 17:06:22.359 IJKMediaDemo[96425:961368] Warning: Attempt to present <IJKVideoViewController: 0x7f8329c632d0> on <IJKDemoInputURLViewController: 0x7f8329c587b0> whose view is not in the window hierarchy!

**Comment by raymond1012** [comment]
ijk base on ffmpeg 3.2, we plan to update at next month

**Comment by jshqhxm** [comment]
问题解决了，迷迷糊糊看了看 hls.c  中代码， hls 中 aes_128 解密使用了 crypto 这个解密库   最新的配置项中 config/module.sh  中开关放开就可以了， ffmeg 中使用工厂类是 没有找到 crypto这个实例所以解析失败了
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=crypto"

**Comment by zhanggao** [comment]
@jshqhxm 我这边加了opengssl，还有crypto也改成了enable还是报这个错，请问还有别的要修改的不？

**Comment by GJson** [comment]
> @jshqhxm 我这边加了opengssl，还有crypto也改成了enable还是报这个错，请问还有别的要修改的不？

你这边问题解决好了吗？ 遇到一样的问题

**Comment by GJson** [comment]
> av_version_info: ff3.2--ijk0.7.6--20170203--001
> 
> ijk_version_info: k0.7.8.1
> 
> ijkmp_set_inject_opaque(0x60000001bab0)
> 
> ijkmp_set_inject_opaque()=void
> 
> ijkmp_set_ijkio_inject_opaque(0x60000001bab0)
> 
> ijkmp_set_ijkio_inject_opaque()=void
> 
> 2017-03-23 17:06:21.799 IJKMediaDemo[96425:961368] OK setup GL
> 
> ijkmp_ios_set_view(glView=0x7f8329e299e0)
> 
> ijkmp_ios_set_view(glView=0x7f8329e299e0)=void
> 
> 2017-03-23 17:06:21.801 IJKMediaDemo[96425:961368] invalidateRenderBuffer
> 
> 2017-03-23 17:06:21.801 IJKMediaDemo[96425:1093725] IJKSDLGLView: setupDisplay not ready
> 
> ijkmp_set_data_source(url="http://vodlist.5iketang.com:8086/playUri.m3u8?vid=VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2&vid2=")
> 
> ijkmp_set_data_source(url="[http://vodlist.5iketang.com:8086/playUri.m3u8?vid=VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2&vid2=")=0](http://vodlist.5iketang.com:8086/playUri.m3u8?vid=VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2&vid2=%22)=0)
> 
> ijkmp_prepare_async()
> 
> ===== versions =====
> 
> [FFPlayer @ 0x7f832a853400] ijkplayer : k0.7.8.1
> 
> [FFPlayer @ 0x7f832a853400] FFmpeg : ff3.2--ijk0.7.6--20170203--001
> 
> [FFPlayer @ 0x7f832a853400] libavutil : 55.34.100
> 
> [FFPlayer @ 0x7f832a853400] libavcodec : 57.64.100
> 
> [FFPlayer @ 0x7f832a853400] libavformat : 57.56.100
> 
> [FFPlayer @ 0x7f832a853400] libswscale : 4.2.100
> 
> [FFPlayer @ 0x7f832a853400] libswresample: 2.3.100
> 
> ===== options =====
> 
> [FFPlayer @ 0x7f832a853400] player-opts : video-pictq-size = 3
> 
> [FFPlayer @ 0x7f832a853400] player-opts : overlay-format = fcc-_es2
> 
> [FFPlayer @ 0x7f832a853400] player-opts : max-fps = 30
> 
> [FFPlayer @ 0x7f832a853400] player-opts : framedrop = 0
> 
> [FFPlayer @ 0x7f832a853400] player-opts : videotoolbox-max-frame-width = 960
> 
> [FFPlayer @ 0x7f832a853400] player-opts : videotoolbox = 0
> 
> [FFPlayer @ 0x7f832a853400] player-opts : start-on-prepared = 1
> 
> [FFPlayer @ 0x7f832a853400] format-opts : ijkapplication = 140201319247152
> 
> [FFPlayer @ 0x7f832a853400] format-opts : ijkiomanager = 105553118698272
> 
> [FFPlayer @ 0x7f832a853400] format-opts : user-agent = ijkplayer
> 
> [FFPlayer @ 0x7f832a853400] format-opts : auto_convert = 0
> 
> [FFPlayer @ 0x7f832a853400] format-opts : timeout = 30000000
> 
> [FFPlayer @ 0x7f832a853400] format-opts : reconnect = 1
> 
> [FFPlayer @ 0x7f832a853400] format-opts : safe = 0
> 
> ===================
> 
> ijkmp_prepare_async()=0
> 
> [http @ 0x7f8329f2ff60] Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'
> 
> 2017-03-23 17:06:21.813 IJKMediaDemo[96425:961368] invalidateRenderBuffer
> 
> 2017-03-23 17:06:21.813 IJKMediaDemo[96425:1093725] IJKSDLGLView: setupDisplay not ready
> 
> [http @ 0x7f832b853200] the user-agent option is deprecated, please use user_agent option
> 
> [http @ 0x7f8329f2ff60] request: GET /playUri.m3u8?vid=VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2&vid2= HTTP/1.1
> 
> User-Agent: ijkplayer
> 
> Accept: _/_
> 
> Range: bytes=0-
> 
> Connection: close
> 
> Host: vodlist.5iketang.com:8086
> 
> Icy-MetaData: 1
> 
> [hls,applehttp @ 0x7f832b85b400] Format hls,applehttp probed with size=2048 and score=100
> 
> [hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00000.ts', offset 0, playlist 0
> 
> [http @ 0x7f832b871800] the user-agent option is deprecated, please use user_agent option
> 
> [http @ 0x7f8329f02440] request: GET /v/fetchplaykey?&vid=VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f&df=2 HTTP/1.1
> 
> User-Agent: ijkplayer
> 
> Accept: _/_
> 
> Connection: close
> 
> Host: vodlist.5iketang.com
> 
> Icy-MetaData: 1
> 
> [AVIOContext @ 0x7f8329e23ce0] Statistics: 16 bytes read, 0 seeks
> 
> [hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00001.ts', offset 0, playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00002.ts', offset 0, playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00003.ts', offset 0, playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00004.ts', offset 0, playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00005.ts', offset 0, playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00006.ts', offset 0, playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00007.ts', offset 0, playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00008.ts', offset 0, playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00009.ts', offset 0, playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00010.ts', offset 0, playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00011.ts', offset 0, playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00012.ts', offset 0, playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00013.ts', offset 0, playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00014.ts', offset 0, playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00015.ts', offset 0, playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00016.ts', offset 0, playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] HLS request for url 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00017.ts', offset 0, playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] Failed to open segment of playlist 0
> 
> [hls,applehttp @ 0x7f832b85b400] Error when loading first segment 'http://cache.vod.5iketang.com/5iketang/0/2017-01-14/PRgHqBbrIHts/VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2-00000.ts'
> 
> [AVIOContext @ 0x7f8329d392f0] Statistics: 2737 bytes read, 0 seeks
> 
> http://vodlist.5iketang.com:8086/playUri.m3u8?vid=VID-SCEHLhLq-HsgL-6f0ba29113b176f35191c93f-2&vid2=: Invalid data found when processing input
> 
> 2017-03-23 17:06:22.137 IJKMediaDemo[96425:961368] FFP_MSG_ERROR: 0
> 
> 2017-03-23 17:06:22.138 IJKMediaDemo[96425:961368] IJKMPMoviePlayBackStateDidChange 2: paused
> 
> 2017-03-23 17:06:22.138 IJKMediaDemo[96425:961368] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1
> 
> av_version_info: ff3.2--ijk0.7.6--20170203--001
> 
> ijk_version_info: k0.7.8.1
> 
> ijkmp_set_inject_opaque(0x608000203710)
> 
> ijkmp_set_inject_opaque()=void
> 
> ijkmp_set_ijkio_inject_opaque(0x608000203710)
> 
> ijkmp_set_ijkio_inject_opaque()=void
> 
> 2017-03-23 17:06:22.357 IJKMediaDemo[96425:961368] OK setup GL
> 
> ijkmp_ios_set_view(glView=0x7f8329d5cb90)
> 
> ijkmp_ios_set_view(glView=0x7f8329d5cb90)=void
> 
> 2017-03-23 17:06:22.359 IJKMediaDemo[96425:961368] invalidateRenderBuffer
> 
> 2017-03-23 17:06:22.359 IJKMediaDemo[96425:1093725] IJKSDLGLView: setupDisplay not ready
> 
> 2017-03-23 17:06:22.359 IJKMediaDemo[96425:961368] Warning: Attempt to present <IJKVideoViewController: 0x7f8329c632d0> on <IJKDemoInputURLViewController: 0x7f8329c587b0> whose view is not in the window hierarchy!
请问这个问题解决了吗

**Comment by currymax** [comment]
请问加密是aes 128加密的哪一种方式？EBC，CBC？
