### ISSUE TITLE
请问一下android编译出的三个库文件可以打包成一个库吗？

### ISSUE THREAD

**Issue by playererer** [Bilibili/ijkplayer#2896]
把libijkffmpeg和libijksdl编成静态库，然后打包进最终的libijkplayer.so中，但是这样子的话jni层有一些代码冲突，比如JNI_LOAD和JNI_UNLOAD，请问一下有没有谁处理过这个问题，或者给一些处理建议，谢谢了！

**Comment by bbcallen** [comment]
Just merge them in the order of loading
