### ISSUE TITLE
Android multiple ijkvideoview

### ISSUE THREAD

**Issue by marksanchez** [Bilibili/ijkplayer#2898]
Hi, is it possible to display multiple views in one activity with single source?
I'm streaming through RTSP TS, for example the TS video has 2 stream. Can i show both stream in 2 different view only but only using 1 streamer (to save bandwith)?

**Comment by marksanchez** [comment]
I am currently reading the ijkplayer_jni.c, please help or if anyone can give suggestion on what to do? thanks.

**Comment by bbcallen** [comment]
No.
And I don't think it could save any bandwidth in that way.
