### ISSUE TITLE
求助：iOS，按照步骤集成后，build，提示：No such file or directory。

### ISSUE THREAD

**Issue by hwqforapple** [Bilibili/ijkplayer#2899]
run custom shell script "ijkversion.h"
sh: /Users/.../../ijkmedia/ijkplayer/version.sh: No such file or directory

**Comment by jshqhxm** [comment]
代码没下全吧

**Comment by hwqforapple** [comment]
demo 放在下载的目录下面能正常运行，换个目录也是出现这样的问题

**Comment by ytfh2017** [comment]
我也遇到这个问题，请问怎么解决的？

**Comment by samalakranthi** [comment]
即使我有同样的问题。

**Comment by DeliriousLee** [comment]
+1

**Comment by DeliriousLee** [comment]
我擦，我已经解决了
在IJKMediaPlayer.xcodeproj里面的
![2018-07-19 5 49 59](https://user-images.githubusercontent.com/24474112/42935462-466afab2-8b7c-11e8-8072-6621bf7bc590.png)

`sh "${PROJECT_DIR}/../../ijkmedia/ijkplayer/version.sh" "${PROJECT_DIR}/../../ijkmedia/ijkplayer" "ijkversion.h" `
这两句写定了需要把和ios同一个目录下面的这个文件**ijkmedia**文件夹一起粘贴进工程文件里面
![2018-07-19 5 53 14 1](https://user-images.githubusercontent.com/24474112/42935873-5888facc-8b7d-11e8-8a2c-e9a206235f22.png)

**Comment by SuAdrenine** [comment]
@DeliriousLee 大兄弟，有详细教程吗，我这边不想用编译framework的方式，想用你这样关联工程的方式编译，但是一直失败

**Comment by DeliriousLee** [comment]
> @DeliriousLee 大兄弟，有详细教程吗，我这边不想用编译framework的方式，想用你这样关联工程的方式编译，但是一直失败

我后来还是用的编译framework，忘了当初什么坑了。不过我有编译好的framework，你要不要？
https://pan.baidu.com/s/18h86bK43wPRQCwjaYm3CdQ 密码pwd：j3fh
编译教程：
https://www.jianshu.com/p/9743a68c2939
https://blog.csdn.net/qq372848728/article/details/62170288

**Comment by SuAdrenine** [comment]
@DeliriousLee 编译成framework库我已经成功了，我就想学学联合编译那个，网上教程把这个忽略，我想尝试两种办法
