### ISSUE TITLE
可以做到无限制视频倍速播放吗？

### ISSUE THREAD

**Issue by crazy1235** [Bilibili/ijkplayer#2927]
您好，请问使用ijkplayer可以做到无限制视频倍速播放吗？
还是只能做到0.5-2 ？

**Comment by raymond1012** [comment]
原理上是可以支持无限制倍速的，但是要考虑解码能力和网络速度以及不同厂商音频输出的范围，综合设置一个倍速范围

2017-04-03 17:35 GMT+08:00 yansen <notifications@github.com>:
