### ISSUE TITLE
倍速播放变调问题

### ISSUE THREAD

**Issue by jackiesea** [Bilibili/ijkplayer#2930]
现在有没有好的解决办法啊，6.0以下setSpeed变调，6.0以上效果也不好，无法像vlc一样

**Comment by raymond1012** [comment]
使用soundtouch将ffmpeg 解码的pcm变速变调

2017-04-05 9:49 GMT+08:00 jackiesea <notifications@github.com>:

**Comment by renhui** [comment]
倍速可不可以做到不变调 ?

**Comment by 0ct0cat** [comment]
倍速以通过改变声卡的配置(采样率之类的）实现的，要做到不变调，要对pcm数据做处理。。。不清楚有没有什么lib可以用。

**Comment by jackiesea** [comment]
vlc可以实现完美倍速，我已经集成了，但是有个蛋疼的bug，release释放资源时底层会阻塞主线程导致程序卡死，向官方反馈了该bug尚未回应，哪位大神可以修改下底层这个bug。

**Comment by pokercc** [comment]
使用soundtouch将ffmpeg 解码的pcm变速变调？
官方正在开发吗？

**Comment by abero1993** [comment]
@jackiesea 可以在应用层屏蔽这个bug，在子线程调用播放类

**Comment by karlzheng** [comment]
学习
