### ISSUE TITLE
全屏播放问题

### ISSUE THREAD

**Issue by yaoyoyo** [Bilibili/ijkplayer#2934]
hi 
背景：使用ijkplayer时，想让画面占满播放器全屏播放
对于普通的VideoView，只用如下处理即可： 
>  @Override
>  protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
>      int width = getDefaultSize(0, widthMeasureSpec);
>      int height = getDefaultSize(0, heightMeasureSpec);
>      setMeasuredDimension(width, height);
>  }

但IjkVideoView是继承自FrameLayout，尝试使用如下处理，视频会无法播放
>public class CustomVideoView extends IjkVideoView {
>
>    public CustomVideoView(Context context) {
>        super(context);
>    }
>
>    public CustomVideoView(Context context, AttributeSet attrs) {
>        super(context, attrs);
>    }
>
>    public CustomVideoView(Context context, AttributeSet attrs, int defStyleAttr) {
>        super(context, attrs, defStyleAttr);
>    }
>
>    public CustomVideoView(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
>        super(context, attrs, defStyleAttr, defStyleRes);
>    }
>
>    @Override
>    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
>        if (this.getWidth() != 0) {
>            setMeasuredDimension(this.getWidth(), this.getHeight());
>            return;
>        }
>        int width = getDefaultSize(0, widthMeasureSpec);
>        int height = getDefaultSize(0, heightMeasureSpec);
>        setMeasuredDimension(width, height);
>    }
>}

没有查找到相关api，请问各位大大应该如何实现

**Comment by yaoyoyo** [comment]
done
`videoView.setDisplayAspectRatio(IRenderView.AR_MATCH_PARENT);`

**Comment by drivedreams** [comment]
Ijk设置match parent  调正他的父容器就可以了




发自网易邮箱大师
在2017年04月06日 11:55，yaoyoyo 写道：

hi
背景：使用ijkplayer时，想让画面占满播放器全屏播放
对于普通的VideoView，只用如下处理即可：

@Override
protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
int width = getDefaultSize(0, widthMeasureSpec);
int height = getDefaultSize(0, heightMeasureSpec);
setMeasuredDimension(width, height);
}

但IjkVideoView是继承自FrameLayout，尝试使用如下处理，视频会无法播放

public class CustomVideoView extends IjkVideoView {

public CustomVideoView(Context context) {
super(context);
}

public CustomVideoView(Context context, AttributeSet attrs) {
super(context, attrs);
}

public CustomVideoView(Context context, AttributeSet attrs, int defStyleAttr) {
super(context, attrs, defStyleAttr);
}

public CustomVideoView(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
super(context, attrs, defStyleAttr, defStyleRes);
}

@Override
protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
if (this.getWidth() != 0) {
setMeasuredDimension(this.getWidth(), this.getHeight());
return;
}
int width = getDefaultSize(0, widthMeasureSpec);
int height = getDefaultSize(0, heightMeasureSpec);
setMeasuredDimension(width, height);
}
}

没有查找到相关api，请问各位大大应该如何实现
