### ISSUE TITLE
Is there any plan to support h265 codec?

### ISSUE THREAD

**Issue by masudo** [Bilibili/ijkplayer#294]
As h265 makes a huge difference in file size of video without quality loose, I'm wondering if there is any plan to add it to ijk? as ffmpeg already support it.

**Comment by bbcallen** [comment]
You can enable h264 anytime via
```
cd config
rm module.sh
ln -s module-default.sh module.sh
cd android/contrib
# cd ios
sh compile-ffmpeg clean
```

**Comment by masudo** [comment]
Sorry bbcallen, but did you mean h265 or h264? I'm looking for playing h265 encoded streams with ijkplayer.

**Comment by bbcallen** [comment]
Sorry, I mean h265.
h265 is supported by FFmpeg 2.7, but is disabled by config/module-lite.sh in ijkplayer.
You need to switch to module-default.sh to enable h265 parser and decoder.

**Comment by masudo** [comment]
Thanks, that's great!
