### ISSUE TITLE
Android ijkplayer 设置setAspectRatio fill_parent无法覆盖全屏

### ISSUE THREAD

**Issue by Samcasa** [Bilibili/ijkplayer#2954]
直播播放rtmp流 .
1. ijkplayer xml width height 均为match_parent
2. 设置mVideoView.setAspectRatio(IRenderView.AR_ASPECT_FILL_PARENT);
画面两侧还是有大概10dp没有覆盖.

**Comment by zhanggao** [comment]
可能流本来就那个样子？

**Comment by Samcasa** [comment]
拉伸覆盖全屏,流有问题应该也可以覆盖全屏吧

**Comment by Samcasa** [comment]
用七牛的播放器sdk播放流可以覆盖全屏

**Comment by bbcallen** [comment]
duplicated with #2981
