### ISSUE TITLE
是否有可能直接播放已压缩过的裸流？Is it posible to play byte[] directly?

### ISSUE THREAD

**Issue by RainFool** [Bilibili/ijkplayer#2957]
目前我可以拿到网络上传输的经过压缩的yuv裸流，这些数据以回调形式回传到应用，能否将这些数据使用自定义IMediaDataSource的方式直接播放？
Now I have a callback like
`@Override
    public boolean render(ByteBuffer byteBuffer) {
        return true;
    }`,can i use `IjkMediaPlayer.setDataSource(IMediaDataSource mediaDataSource)` to play it?
and how?

**Comment by raymond1012** [comment]
可以，但是通过IMediaDataSource得到的yuv数据无法直接渲染，你需要配置分辨率等参数

**Comment by RainFool** [comment]
请问设置分辨率参数在哪里设？sps、pps等信息已经在第一次的接口回调中封装好了，现在的的问题是这个IMediaDataSource不好写，因为没有size，而且是通过多次调用render这个函数获取ByteBuffer的，请问这种情况可以使用吗

**Comment by raymond1012** [comment]
分辨率参数的设置需要查看下SDL_Android_NativeWindow_display_l显示部分的代码，IMediaDataSource没有size是什么意思不是很懂，多次调用render肯定是没问题的，因为这个就是用于显示的

**Comment by RainFool** [comment]
抱歉说的不清楚。
我目前遇到的情况是，已经从网络中取到了流，是以一个接口回调的形式给我的：
```
@Override 
public boolean render(ByteBuffer byteBuffer) { 
  return true; 
}
```
这个接口是我自己定义的，数据来了就通过这个接口通知。

然后，我想接入ijkPlayer做解码和渲染，自定义了一个Activity，初始化好了播放器：
`
public class ScreenRenderActivity extends BaseActivity {

    @BindView(R.id.render_texture)
    AutoFitTextureView mRenderView;
    private IjkMediaPlayer ijkMediaPlayer;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_screen_render);

        IjkMediaPlayer.loadLibrariesOnce(null);
        IjkMediaPlayer.native_profileBegin("libijkplayer.so");

        ijkMediaPlayer = new IjkMediaPlayer();
        ijkMediaPlayer.native_setLogLevel(IjkMediaPlayer.IJK_LOG_DEBUG);
        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-auto-rotate", 0);
        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-handle-resolution-change", 1);
        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "opensles", 1);
        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "overlay-format", IjkMediaPlayer.SDL_FCC_RV32);
        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 1);
        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "start-on-prepared", 0);
        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "http-detect-range-support", 0);
        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 48);

        ijkMediaPlayer.setOnPreparedListener(new IMediaPlayer.OnPreparedListener() {
            @Override
            public void onPrepared(IMediaPlayer iMediaPlayer) {
                KLog.d("start");
                ijkMediaPlayer.start();
            }
        });

        mRenderView.setSurfaceTextureListener(new TextureView.SurfaceTextureListener() {
            @Override
            public void onSurfaceTextureAvailable(SurfaceTexture surface, int width, int height) {
                ijkMediaPlayer.setSurface(new Surface(surface));
//                test();
            }

            @Override
            public void onSurfaceTextureSizeChanged(SurfaceTexture surface, int width, int height) {

            }

            @Override
            public boolean onSurfaceTextureDestroyed(SurfaceTexture surface) {

                return true;
            }

            @Override
            public void onSurfaceTextureUpdated(SurfaceTexture surface) {

            }
        });

    }

    @Subscribe
    public void setDataSource(DataSourceEvent event) {
        KLog.d();
        ijkMediaPlayer.setDataSource(event.getCrvpMediaDataSource());
        ijkMediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
        ijkMediaPlayer.prepareAsync();
    }
}
`

然后，这里的setDataSource会在一个合适的时机注入到Activity，因此这个接口：
`
public interface IMediaDataSource {
    int  readAt(long position, byte[] buffer, int offset, int size);
    long getSize();
    void close();
}
`
就不知道如何实现了，getSize在FileDataSource里时返回了File.size,但是我现在只有byte数据，没有size，而且readAt该怎么写，我在内部给buffer填充了我自己定义的render回调里的bytebyffer（当然进行过一次拷贝，保证bytebuffer合法），但是一直是黑屏没有显示。

请问这种方式可行吗，这个IMediaDataSource应该怎么实现，或者有其他方法将byte数据怼进ijkPlayer吗？

谢谢

**Comment by raymond1012** [comment]
可以根据ijkmediadatasource.c 来写java

2017-04-14 19:42 GMT+08:00 RainFool <notifications@github.com>:

**Comment by RainFool** [comment]
请问目前有实践过得代码可以参考吗？ @raymond1012

**Comment by raymond1012** [comment]
没有

2017-04-18 11:57 GMT+08:00 RainFool <notifications@github.com>:

**Comment by karoline97** [comment]
@RainFool 请教一下，请问你实现了直接把流给进播放器播放了吗？怎么实现的，谢谢

**Comment by RainFool** [comment]
@karoline97 并没有，当时只是一个尝试，这块没有先例页不好搞
