### ISSUE TITLE
初始化时如何设置Cookie?

### ISSUE THREAD

**Issue by EmKs** [Bilibili/ijkplayer#2958]
看了
https://github.com/Bilibili/ijkplayer/issues/1150
这个问题后去setOption还是无法解决问题，而后看到
https://github.com/Bilibili/ijkplayer/issues/1816
中所说，需要初始化的时候设置Cookie，请问如何设置？

**Comment by raymond1012** [comment]
setOption  cookies

**Comment by EmKs** [comment]
@raymond1012 
设置后出现Failed to resolve hostname xfcd.ctfs.ftn.qq.com: No address associated with hostname
网页是可以打开的
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
E/IJKMEDIA: Failed to resolve hostname xfcd.ctfs.ftn.qq.com: No address associated with hostname
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
E/IJKMEDIA: http://xfcd.ctfs.ftn.qq.com/ftn_handler/2c1d6a728dab510bce9e3745770c6f6320a8f1a7a028f94d45583caa1ef9b4183ca39244b6afaf7b7af2f5bc476768e7da0f2d833b9406e82f6cf036d4dd41a1/M.mkv: I/O error
D/IJKMEDIA: FFP_MSG_ERROR: 0
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [2890]
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by raymond1012** [comment]
打不开啊

2017-04-14 15:51 GMT+08:00 EmKs <notifications@github.com>:

**Comment by EmKs** [comment]
@需要有Cookie才行，你可以试着ping一下，路线是通的

**Comment by raymond1012** [comment]
你可以抓下包定位下

2017-04-14 16:07 GMT+08:00 EmKs <notifications@github.com>:

**Comment by EmKs** [comment]
@raymond1012 刚才的问题已经解决了，现在是设置后出现 Server returned 4XX Client Error, but not one of 40{0,1,3,4}错误，与
https://github.com/Bilibili/ijkplayer/issues/1816
中所提到的错误一样但是后面他说要加上Cookie初始化。就是这一步不知道怎么做
具体代码如下
       surfaceView = (SurfaceView) findViewById(R.id.SurfaceView);
        surfaceHolder = surfaceView.getHolder();

        surfaceHolder.addCallback(this);


        header.put("headers","Cookie: FTN5K=12b8331c0");

        IjkMediaPlayer = new IjkMediaPlayer();
        IjkMediaPlayer.setOption(IjkMediaPlayer.FFP_PROPV_DECODER_AVCODEC,"headers","Cookie: FTN5K=12b8331c0");
        try {
            IjkMediaPlayer.setDataSource(this, Uri.parse(Path), header);
        } catch (IOException e) {
            e.printStackTrace();
        }

        IjkMediaPlayer.setOnPreparedListener(this);
    }

    @Override
    public void surfaceCreated(SurfaceHolder holder) {
        IjkMediaPlayer.setDisplay(holder);
        IjkMediaPlayer.prepareAsync();
    }

    @Override
    public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {

    }

    @Override
    public void surfaceDestroyed(SurfaceHolder holder) {
    }

    @Override
    public void onPrepared(IMediaPlayer iMediaPlayer) {
        IjkMediaPlayer.start();
    }
}

**Comment by liceim** [comment]
@EmKs 请问初始化设置cookie的问题解决了吗？

**Comment by xinzhengzhang** [comment]
#1816

**Comment by kkzone** [comment]
> @raymond1012 刚才的问题已经解决了，现在是设置后出现 Server returned 4XX Client Error, but not one of 40{0,1,3,4}错误，与
> #1816
> 中所提到的错误一样但是后面他说要加上Cookie初始化。就是这一步不知道怎么做
> 具体代码如下
> surfaceView = (SurfaceView) findViewById(R.id.SurfaceView);
> surfaceHolder = surfaceView.getHolder();
> 
> ```
>     surfaceHolder.addCallback(this);
> 
> 
>     header.put("headers","Cookie: FTN5K=12b8331c0");
> 
>     IjkMediaPlayer = new IjkMediaPlayer();
>     IjkMediaPlayer.setOption(IjkMediaPlayer.FFP_PROPV_DECODER_AVCODEC,"headers","Cookie: FTN5K=12b8331c0");
>     try {
>         IjkMediaPlayer.setDataSource(this, Uri.parse(Path), header);
>     } catch (IOException e) {
>         e.printStackTrace();
>     }
> 
>     IjkMediaPlayer.setOnPreparedListener(this);
> }
> 
> @Override
> public void surfaceCreated(SurfaceHolder holder) {
>     IjkMediaPlayer.setDisplay(holder);
>     IjkMediaPlayer.prepareAsync();
> }
> 
> @Override
> public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {
> 
> }
> 
> @Override
> public void surfaceDestroyed(SurfaceHolder holder) {
> }
> 
> @Override
> public void onPrepared(IMediaPlayer iMediaPlayer) {
>     IjkMediaPlayer.start();
> }
> ```
> 
> }

这个returned 4XX Client Error错误的问题解决了吗，怎么解决的？
