### ISSUE TITLE
htttp://blabla.mp4, Protocol not found

### ISSUE THREAD

**Issue by tysheng** [Bilibili/ijkplayer#2969]
```
04-18 09:07:58.564 20880-21282/com.alex.e E/IJKMEDIA: http://e0575.s.qupai.me/v/4d07a5ff-e970-4d94-a261-67e53e2f1581.mp4: Protocol not found
04-18 09:07:58.565 20880-21274/com.alex.e E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
04-18 09:07:58.586 20880-20880/com.alex.e E/JieCaoVideoPlayer: onError -10000 - 0 [236200007] 
```

any options to set? the  newest version 0.7.9, Android 7.1.1

**Comment by raymond1012** [comment]
need openssl

2017-04-18 9:09 GMT+08:00 Tianyang Sheng <notifications@github.com>:

**Comment by tysheng** [comment]
@raymond1012 
any samples or specific docs?

**Comment by tysheng** [comment]
not support http?

**Comment by raymond1012** [comment]
http://blog.csdn.net/linchaolong/article/details/52805666

2017-04-18 10:51 GMT+08:00 Tianyang Sheng <notifications@github.com>:

**Comment by raymond1012** [comment]
http://e0575.s.qupai.me/v/4d07a5ff-e970-4d94-a261-67e53e2f1581.mp4
will jump to https://xxxx


2017-04-18 10:54 GMT+08:00 Tianyang Sheng <notifications@github.com>:

**Comment by tysheng** [comment]
got it, thx @raymond1012
