### ISSUE TITLE
compileijk.sh fails for x86 

### ISSUE THREAD

**Issue by masudo** [Bilibili/ijkplayer#297]
I'm experinecing below error when I run compile-ijk.sh all, it used to works before changing to last 0.3 version, could anyone tell me how can I fix that?

/home/user/src/ijkplayer-android/android
Android NDK: ERROR:/home/user/src/ijkplayer-android/android/ijkplayer/player-x86/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /libijkffmpeg.so exists  or that its path is correct   
/home/user/Android/android-ndk-r10d/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.

**Comment by masudo** [comment]
I ran compile-ijk.sh x86 and could get it work, not sure why it doesn't work with compile-ijk.sh all.

**Comment by garymabin** [comment]
please compile ffmpeg first, run ikplayer/android/contrib/compile-ffmpeg.sh x86

**Comment by masudo** [comment]
yeah I think that was my problem, in previous versions it used to compile all platforms all together, I think README should be updated to include more info for people who wants to compile it for other platforms.

**Comment by bbcallen** [comment]
Fixed in README.md: 37f1a2133db1307f89d169ba68adc5dd58e4e7f3
