### ISSUE TITLE
播放rtsp音视频不同步，音频比视频慢了5-6秒，如何才能同步

### ISSUE THREAD

**Issue by daobenzhen** [Bilibili/ijkplayer#2972]
![config](https://cloud.githubusercontent.com/assets/18129871/25121792/7718b4c2-2455-11e7-81b8-151473c88ae3.jpg)
这是我的配置，该怎么改

**Comment by nickhuangClimax** [comment]
> ![config](https://cloud.githubusercontent.com/assets/18129871/25121792/7718b4c2-2455-11e7-81b8-151473c88ae3.jpg)
> 这是我的配置，该怎么改

請問您有解決嗎? 我播RTSP也是聲音比影像慢了4秒
