### ISSUE TITLE
Android， 已经缓冲完的区域， seek，会重新请求该数据，没有使用缓冲区的数据直接播放

### ISSUE THREAD

**Issue by ZhangBingbin** [Bilibili/ijkplayer#2978]
Android， 已经缓冲完的区域， seek，会重新请求该数据，没有使用缓冲区的数据直接播放

**Comment by raymond1012** [comment]
i think you need https://www.ffmpeg.org/ffmpeg-protocols.html#async

2017-04-19 10:22 GMT+08:00 ZhangBingbin <notifications@github.com>:

**Comment by ZhangBingbin** [comment]
@raymond1012 你好，我已经在我的播放地址前面加上了"async:",然而还是没有起到作用，并且我也在Protocal_whitelist中加入了async

**Comment by raymond1012** [comment]
async的默认缓冲是前4m后4m，而默认缓冲是15m所以你看不出效果，需要修改两块缓冲的大小

2017-04-19 11:04 GMT+08:00 ZhangBingbin <notifications@github.com>:

**Comment by ZhangBingbin** [comment]
不好意思，可不可以弱弱的问一下怎么去修改缓冲的大小

**Comment by ZhangBingbin** [comment]
您的意思是说让我重新编译ffmpeg的async的默认缓冲大小是不是，把async的默认缓冲大小也改为15s对嘛

**Comment by raymond1012** [comment]
通过setoption将min-frames改小，将async的缓冲区增大

2017-04-19 14:55 GMT+08:00 ZhangBingbin <notifications@github.com>:

**Comment by ZhangBingbin** [comment]
你好， ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER,"min-frames",1);
这是设置我的min-frames，那如何将async的缓冲区域增大呢

**Comment by raymond1012** [comment]
min-frames不能太小，100左右比较合适，async请查看async.c

2017-04-19 15:15 GMT+08:00 ZhangBingbin <notifications@github.com>:

**Comment by ZhangBingbin** [comment]
好的，谢谢大神

**Comment by ZhangBingbin** [comment]
不好意思，我可以再问最后一个问题嘛，修改async的默认缓冲大小可以通过setOption来修改吗

**Comment by raymond1012** [comment]
可以

2017-04-19 15:24 GMT+08:00 ZhangBingbin <notifications@github.com>:

**Comment by ZhangBingbin** [comment]
我还是不清楚他的这个setOption设置async的缓冲大小的参数是哪个，大神能指点下吗

**Comment by aasdsjk** [comment]
@raymond1012 请问一下 怎么设置async 的默认缓冲大小？

**Comment by xinzhengzhang** [comment]
Seek request will cause the buffer be flushed.
The option for `async` will not become effective unless you enable it.

**Comment by songhongwang** [comment]
@xinzhengzhang 
请问怎么通过setOption设置async的缓冲大小？
我遇到的问题就是每次seek都会重新缓冲，而不是使用已经缓冲的数据流。

**Comment by hywenbinger** [comment]
@ZhangBingbin @songhongwang 通过setOption设置async的缓冲大小该怎么写，这个问题搞定了吗？

**Comment by hywenbinger** [comment]
@raymond1012 请问具体怎么设置async的缓冲大小？
