### ISSUE TITLE
播放rtmp问题

### ISSUE THREAD

**Issue by remantou** [Bilibili/ijkplayer#298]
ijkmp_prepare_async()
===== options =====
player-opts : start-on-prepared    = 1
player-opts : overlay-format       = fcc-i420
player-opts : max-fps              = 30
player-opts : framedrop            = 0
player-opts : video-pictq-size     = 3
format-opts : reconnect            = 1
format-opts : timeout              = 30000000
format-opts : safe                 = 0
codec-opts  : skip_loop_filter     = 48
codec-opts  : skip_frame           = 8
===================
ijkmp_prepare_async()=0
ijkmp_start()
ijkmp_start()=-3
Cannot open connection tcp:。。
Can't assign requested address

**Comment by bbcallen** [comment]
Fixed on master

**Comment by remantou** [comment]
播rtmp的时候 我昨天把option的timeout改为0 也能播了 不知道是不是这个问题

**Comment by bbcallen** [comment]
因为ffmpeg里http的timeout和rtmp的timeout的含义是完全不同的。

**Comment by remantou** [comment]
原来如此 谢谢

**Comment by Android4MediaPlayer** [comment]
请close这个问题。
