### ISSUE TITLE
0.7.9播放阿里云上音频失败

### ISSUE THREAD

**Issue by ruidge** [Bilibili/ijkplayer#2986]
0.7.9播放阿里云上音频失败,地址为https://jjkappdatapower.oss-cn-beijing.aliyuncs.com/e5f21b9e516ac237243537b20e585a65?Expires=1523588618&OSSAccessKeyId=7cCMZ6BshwIMA6jR&Signature=DQ19FQ1WElwLCYTPY7tGMUH27ao%3D&code=67b8930ceeb1ed539e27ef0d843380ca

**Comment by ruidge** [comment]
替换为Http可以了...

**Comment by raymond1012** [comment]
i think you need config openssl

2017-04-19 14:58 GMT+08:00 ruidge <notifications@github.com>:

**Comment by ruidge** [comment]
I use ijkmediaplayer on android by config in gradle file , and api doc is rare . can I config openssl in api ?

**Comment by raymond1012** [comment]
http://blog.csdn.net/linchaolong/article/details/52805666

2017-04-19 18:30 GMT+08:00 ruidge <notifications@github.com>:
