### ISSUE TITLE
android ijkplayer RTSP播放的时间，怎么设置验证用户名和密码参数设置方法

### ISSUE THREAD

**Issue by sanchibing** [Bilibili/ijkplayer#2988]
Android ijkplayer RTSP play time, how to set up to verify the user name and password parameters set method, there are familiar friends to the guidance, thanks!
android ijkplayer RTSP播放的时间，怎么设置验证用户名和密码参数设置方法，有熟悉的朋友给指导下，谢谢了

**Comment by ctwdtw** [comment]
@sanchibing Did you find the solution? 請問您後來有找到方法了嗎？
