### ISSUE TITLE
hls adaptive bitrate switching doesn't work

### ISSUE THREAD

**Issue by masudo** [Bilibili/ijkplayer#299]
The problem is right now ffmpeg does not supports switching between different hls variants with different bandwidth  defined in m3u8 file based on user available bandwidth and play only the first one.
there is an issue in ffpemg tracker related to this problem but that is abandoned  and nobody works on it.
https://trac.ffmpeg.org/ticket/2886

I wanted to see if  ijkplayer can implement this feature to force ffmpeg to switch to a variant on the fly or at least letting user choose different variant while hls stream is playing.

here you can find my test file:

http://91.109.23.24/cms/media/uploads/media/trailers/kungfupanda/adaptive_kungfu_panda.m3u8

**Comment by bbcallen** [comment]
Parsing m3u8 outside of ijkplayer, and pass the stream you want.

**Comment by masudo** [comment]
that makes whole idea of segmentation and everything useless and we could use other formats instead of hls if we have to stop the stream.

The point in using hls is that it have segmented streams so when user bandwidth changes player should switch and continue getting segments of appropriate stream based on new bandwidth seamlessly.

The scenario is consider we parsed the m3u8 file and  passed the second stream to ijkplayer streams segmented in 100 files and ijkplayer starts playing, somewhere in middle user bandwidth changes and we want to tell the ijkplayer to start stream from segment 40,  How we can make ijkplayer force ffmpeg to switch streams seamlessly?

**Comment by brystel** [comment]
Any advices? How to add bitrate switching mechanism into ijkplayer?

**Comment by bbcallen** [comment]
1. This is how ffplay switch between two different tracks
http://git.videolan.org/?p=ffmpeg.git;a=blob;f=ffplay.c;h=4a084b4480b949ba16b0ec3b878bf3306af8a8e8;hb=HEAD#l3191
Maybe a little help.

2. libavformat/hls.c seems to parse all alternative streams in read_head() sequencely which cause playback of this kind of HLS start very slowly. It need an asynchronized parsing refactor.

**Comment by Zo2m4bie** [comment]
Hello. I made some work around this issue. So if you need you can use my implementation http://zo2m4bie.blogspot.com/2016/08/force-ffmpeg-to-work-with-hls-adaptive.html

**Comment by NikmanSergey** [comment]
@Zo2m4bie, thank you for this solution.

However, some notes and problems:
1) With latest version of FFMPEG _ffurl_open_ never called - use _ffurl_open_whitelist_ instead.
2) _ret_ value in _read_data_ is more often negative, so _loaded_bytes_ value is negative too. Should ignore negatives or use absolute value to get truly downloaded bites?
3) _freeData()_ is crashing, don't know why yet.
4) Do you think _freeData()_ sholud be called from java, can't this be called natively?
5) Resoulution change is applying only in software mode - with Mediacodec resolution is not changing.
6) @bbcallen, what is introduced in k0.6.0 _mediacodec-handle-resolution-change_ option? In what cases it works? Can't this be used to solve 5) issue? Thanks.

**Comment by Zo2m4bie** [comment]
@NikmanSergey thatnk you for your review. I will change ffurl_open, and will look at read_data. Also I will look at crush in freeData().

4) Do you think freeData() sholud be called from java, can't this be called natively?

I got in touch with guy who know ffmpeg better then me. He proposed move freeData() into hls.c method close.

 I will update my article when after fixing this problems

**Comment by NikmanSergey** [comment]
@Zo2m4bie any progress?

It seems, that often _freeData()_ crush is because _read_data_ and _hls_close_ (called from _stream_close()_ in ff_ffplay.c) happens in two different threads, but uses the same data.

During playback _ffurl_open()_ and _ffurl_close()_ running in read_data's thread. But after playback has stoped _ffurl_close()_ is also called in different thread.
