### ISSUE TITLE
进度条回退

### ISSUE THREAD

**Issue by CarGuo** [Bilibili/ijkplayer#2990]
下方链接进度条拖动后又回到起始位置：
http://ocgk7i2aj.bkt.clouddn.com/eeb0a46f-2bf0-4d7e-be4d-f2a6225a6021
请问有什么解决办法？

**Comment by raymond1012** [comment]
视频太短，估计只有一个gop，seek是需要找关键帧的

2017-04-19 20:48 GMT+08:00 Shuyu Guo <notifications@github.com>:

**Comment by CarGuo** [comment]
好的～～thx
