### ISSUE TITLE
Android用SurfaceRenderView能实现镜像翻转吗，需要修改底层源码吗

### ISSUE THREAD

**Issue by niufeihu** [Bilibili/ijkplayer#2996]
Android用SurfaceRenderView能实现镜像翻转吗，需要修改底层源码吗

**Comment by niufeihu** [comment]
已经解决，使用TextureRenderView的setTransform方法成功翻转

**Comment by niufeihu** [comment]
已经解决

**Comment by gangzibo** [comment]
> 已经解决，使用TextureRenderView的setTransform方法成功翻转

您好：ijkPlayer中的androidSample中TextureRenderView这个类里面 没有这个setTransform方法，确定是这个类
