### ISSUE TITLE
MEDIA_INFO_VIDEO_RENDERING_START标志无返回

### ISSUE THREAD

**Issue by pys200603027** [Bilibili/ijkplayer#300]
hi，最近用Ijk感觉不错，但是想知道播放器什么时候开始第一帧，该标志位好像在源码中没有处理到

**Comment by bbcallen** [comment]
SDL_VoutDisplayYUVOverlay()
注意，硬解和软解的输出时机不同。

**Comment by Android4MediaPlayer** [comment]
在video_refresh函数加类似这样的代码：
....
            // FFP_MERGE: if (is->subtitle_st) { {...}

display:

            if(!is->first_play) {
                is->first_play =  1;
                ffp_notify_msg1(ffp, FFP_MSG_VIDEO_RENDERING_START);
            }

            /* display picture */
....

**Comment by Android4MediaPlayer** [comment]
@bbcallen 有更好地方式么 测试发现一般出现在702事件之后

**Comment by Android4MediaPlayer** [comment]
@pys200603027 已经添加了，请关闭
