### ISSUE TITLE
LFLiveKit 和 ijkplayer 同时推流和播放时推流不了怎么解决

### ISSUE THREAD

**Issue by yn288163** [Bilibili/ijkplayer#3000]
想要在一个界面同时有播放和推送的功能，但是只要在界面加入了ijkplayer 功能以后就无法正常推送，推送显示连接成功，但是画面声音均无法正常推送

**Comment by wongzhichao** [comment]
恩，我也在用，你只要在来疯之前初始化ijkplayer就可以了

**Comment by yn288163** [comment]
@wongzhichao ，按照你的方法问题解决了~谢谢

**Comment by xiaofange** [comment]
最好是更改一下IJKPlayer中的AVAudioSessionCategoryPlay改成AVAudioSessionCategoryPlayAndRecord，因为IJKPlayer默认音频是只支持AVAudioSessionCategoryPlay而你的推流中是需要AVAudioSessionCategoryPlayAndRecord所以，更改一下[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord
                                           withOptions:AVAudioSessionCategoryOptionDefaultToSpeaker | AVAudioSessionCategoryOptionMixWithOthers
                                                  error:&error]
