### ISSUE TITLE
使用AVAudioSession录制声音后，没有声音

### ISSUE THREAD

**Issue by IphoneCoder** [Bilibili/ijkplayer#3002]
项目中，当播放器正在播放时，用户可录制声音，录制结束后，调用                                   
      AVAudioSession *sesson = [AVAudioSession sharedInstance];
    [sesson setCategory:AVAudioSessionCategoryPlayback error:&error];
    
    [[AVAudioSession sharedInstance] setActive:YES error:&error];   没有声音 ，视频流正常，没有错误日志，谢谢

**Comment by aDreamCatcher** [comment]
你的问题解决了吗？

**Comment by IphoneCoder** [comment]
录音的时候，把AVAudioSession设置为setCategory:AVAudioSessionCategoryPlayAndRecord ，当录音结束的时候，调用[sesson setCategory:AVAudioSessionCategoryPlayback error:&error];
[[AVAudioSession sharedInstance] setActive:YES error:&error]; 就可以了

**Comment by feng55** [comment]
但是你在设置AVAudioSessionCategoryPlayAndRecord 时录制视频，这时候ijk播放还有声音吗
