### ISSUE TITLE
安卓直播硬解 部分设备花屏。

### ISSUE THREAD

**Issue by zhanggao** [Bilibili/ijkplayer#3004]
ffprobe version N-85266-g1229007 Copyright (c) 2007-2017 the FFmpeg developers
built with gcc 6.3.0 (GCC)
configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --e
nable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --
enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv
--enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-li
bfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug -
-enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enabl
e-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-li
bsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolam
e --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx
--enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable
-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
libavutil 55. 59.100 / 55. 59.100
libavcodec 57. 90.100 / 57. 90.100
libavformat 57. 72.100 / 57. 72.100
libavdevice 57. 7.100 / 57. 7.100
libavfilter 6. 83.100 / 6. 83.100
libswscale 4. 7.100 / 4. 7.100
libswresample 2. 8.100 / 2. 8.100
libpostproc 54. 6.100 / 54. 6.100
Metadata:
duration 0.00
width 360.00
height 640.00
framerate 0.00
audiodatarate 0.00
audiosamplerate 44100.00
audiosamplesize 16.00
cdn_ip 183.131.130.118
filesize 0.00
leid xVJlZR0SPc
leport 1941
stereo TRUE
videodatarate 0.00
Metadata:
Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
Stream #0:0: Video: h264 (Baseline), yuv420p(progressive), 352x640, 1k tbr,
1k tbn
Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp
[FORMAT]
nb_streams=2
nb_programs=0
format_name=flv
format_long_name=FLV (Flash Video)
start_time=0.000000
duration=0.000000
size=N/A
bit_rate=N/A
probe_score=100
[/FORMAT]

**Comment by zhanggao** [comment]
metadata 里面缺少 videocodecid audiocodecid audiochannels 等信息，请问这个该如何解决呢？

**Comment by ctiao** [comment]
什么设备？

**Comment by zhanggao** [comment]
@ctiao 魅族m1、mx5。url早失效了。

**Comment by zhanggao** [comment]
https://cloud.githubusercontent.com/assets/5298896/25131955/553cd250-247a-11e7-97e1-a2500de8c8fb.png
