### ISSUE TITLE
只播放本地视频，应该用config里面的哪个sh文件

### ISSUE THREAD

**Issue by TonightGod** [Bilibili/ijkplayer#3008]
在做app的瘦身，app只做本地视频的播放，怎么尽可能的缩小ijk的体积

**Comment by raymond1012** [comment]
module.sh

2017-04-24 16:39 GMT+08:00 TonightGod <notifications@github.com>:

**Comment by TonightGod** [comment]
module.sh 链接到的module-default.sh、module-lite-hevc.sh和module-lite.sh其中一个，应该链接到哪个上面

**Comment by raymond1012** [comment]
module-lite.sh

2017-04-24 16:51 GMT+08:00 TonightGod <notifications@github.com>:

**Comment by TonightGod** [comment]
谢谢🙏
