### ISSUE TITLE
安卓：如何取到本地视频每一帧解码后的YUV或RGB数据

### ISSUE THREAD

**Issue by dan-huang** [Bilibili/ijkplayer#301]
并对该数据进行处理。比如将视频中的每一帧都转为黑白的灰度图并显示出来。

**Comment by garymabin** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/ff_ffplay.c#L627
输出视频到nativeWindow的地方在这里，不过只有软解（ffmpeg）才能获取到yuv帧，数据在SDL_VoutOverlay中的pixels与pitches

**Comment by dan-huang** [comment]
项目是按照Build Android -> Android Studio编译的，成功在nexus6运行，ijk直接读取了相机中的本地视频。这样解码播放是软解吗。找不到它是怎么引用到ff_ffplay.c的。

如果是硬解的话，是不是只能编译vlc for android才有可能做到取出解码后、播放前的像素数据。

**Comment by bbcallen** [comment]
1. 默认是软解
2. 如果用TextureView输出，可以在java层通过TextureView读取当前显示的帧。

**Comment by dan-huang** [comment]
![screen shot 2015-06-30 at 10 43 32 am](https://cloud.githubusercontent.com/assets/1590420/8422966/f2abef8e-1f14-11e5-893a-9f1a78bba42c.png)

找不到TextureView，只在ijkmediaplayer.java中看到了import android.graphics.SurfaceTexture，    @AccessedByNative  private int mNativeSurfaceTexture; 

但没看到有每一帧的回调。初入安卓，还望指点- -

**Comment by bbcallen** [comment]
demo没有这样的功能，需要你自己把 VideoView 改成从 TextureView 继承。

**Comment by Android4MediaPlayer** [comment]
相当于把surfaceView换成textureView，下面ijkplayer不用变啊

**Comment by Android4MediaPlayer** [comment]
很简单的 你自己添加下 @dan-huang

**Comment by dan-huang** [comment]
好的，我试试~

**Comment by dan-huang** [comment]
SurfaceView的回调中直接是SurfaceHolder，与IjkMediaPlayer->setDisplay->_setVideoSurface(surface)  中的Surface类，可以很好的转换，surface = holder.getSurface()。
但TextureView回调是SurfaceTexture，怎么将SurfaceTexture和最终的_setVideoSurface中的Surface类连接起来呢。

**Comment by xqq** [comment]
@dan-huang  Surface 的公开构造函数是传入 SurfaceTexture 构造

**Comment by dan-huang** [comment]
按三位所说：
1. 将VideoView直接改成继承TextureView
2. 将SurfaceHolder的三个回调改成对应的SurfaceTextureListener中的回调
3. 将SurfaceTexture传递给ijkMediaPlayer（之前是SurfaceHolder）
4. 在SurfaceTextureListener中的onSurfaceTextureUpdated，用getBitMap获取当前帧的数据。

不知道有没有更好的方式获取当前帧数据。

多谢  @bbcallen    @Android4MediaPlayer    @garymabin

**Comment by dan-huang** [comment]
获取到当前帧后，对它做灰度处理（也可以是任意操作，gaussian blur, grabcut等），怎么将处理后的bitmap显示到手机上呢。

比如 TextureView.setBitMap(Bitmap bm) 之类的，但没有这个方法。

**Comment by xqq** [comment]
找个Canvas画上去，比如 TextureView.lockCanvas()，但应该不能在与视频输出同一个 TextureView 上绘制。

用这种办法将视频中的每一帧都转为黑白的灰度图并显示出来，额外开销大概有点大

**Comment by garymabin** [comment]
@dan-huang @xqq, TextureView应该不是必须的， ijk这边大概只需要一个Surface，可以利用与SurfaceTexture绑定的textureId，用opengles获取出来数据，再做后处理（显示或者保存）http://bigflake.com/mediacodec/CameraToMpegTest.java.txt 这个例子是把摄像头数据直接编码然后输出到文件，跟目前你的这个流程是类似的，可以看看它的SurfaceTextureManager类的实现

**Comment by bbcallen** [comment]
如果你只是想要做显示黑白画面，那么就只能用使用软解。
然后在 jni 中找到 android_render_yv12_on_yv12 这个函数，将其修改为只渲染 Y-plane，忽略 Cr-plane 和 Cb-plane 分量。
必要的话，还得在 image_convert.c 中使用更节省性能(忽略CrCb分量)的转换。

**Comment by dan-huang** [comment]
黑白为举例用，实际上要应用较复杂的图像处理过程。不过目前只需要得到图像处理过程的耗时，现阶段已经能达到这个目的了。

**Comment by dan-huang** [comment]
对当前帧进行计算后，计算结果是一个矩形框，怎样将矩形框画到画面上呢。

iOS的话可以用gcd强制在主线程上画一个透明带边框的UIView

安卓求思路~是不是也需要强制占用主线程的资源。怎样画一个矩形框 或者 将带红色边框的透明视图置于VideoView之上。

**Comment by dan-huang** [comment]
有一个小tip，getBitMap()会执行得较慢，如果得到的bitmap越大，就越慢。1920*1080的bitmap大约需要200ms。

如果视频源的分辨率较小（640*480），仅仅只是为了显示而将TextureView的大小设置成了全屏（1920*1080），则可以通过getBitmap(Bitmap bmp)，缩短获取的时间。其中（Bitmap bmp）是初始化了宽、高的bitmap。

比如Bitmap bmp = Bitmap.createBitmap(640, 480, Bitmap.Config.ARGB_8888);
则getBitmap(bmp)只需要20ms左右。

**Comment by xqq** [comment]
@dan-huang thanks

**Comment by playervideo** [comment]
TextureView 在API level 14 添加进来的，改成继承TextureView的话，那android 4.0以前的系统都不支持了

**Comment by Android4MediaPlayer** [comment]
是这样的

**Comment by playervideo** [comment]
请问一下有什么更好的截图方式吗？我尝试了从ff_ffplay.c中拿解码后的数据，但是开硬解的话就拿不到了，我也尝试了在VideoView中用MediaMetadataRetriever这个类，但是只能截本地视频，网络流无法截图。

**Comment by shishuo365** [comment]
如果想要在Java层拿到每一帧视频数据，可以这样操作ijkplayer-sample：
1.修改布局文件 activity_player.xml 中 IjkVideoView 对象为不可见 android:visibility="gone"
2.修改业务逻辑 IjkVideoView.Java 中 openVideo() 的第一行，让界面不可见时，逻辑依然可以走通
```
if (mUri == null /*|| mSurfaceHolder == null*/)
```
3.使用共享内存的方式(DirectBuffer)把FFplay解码后的每一帧数据共享给JAVA层
FFplay解码后的帧图像位置
```
static int queue_picture(...) {
...
  if (vp->bmp) {
    SDL_VoutLockYUVOverlay(vp->bmp);
    // 把bmp图像放进共享内存
    ...
  }
...
}
```
至于JAVA层如何与JNI层进行交互，就不详述了，可以参考Android官网的示例。

**Comment by fengbenpaao** [comment]
能描述得详细点吗?

**Comment by xxmty** [comment]
@bbcallen @dan-huang @all 开启MediaCodec后，为什么直接渲染，不再放队列呢？要怎么读取硬解码后的帧数据呢？急，请帮忙看看。

**Comment by fengbenpaao** [comment]
我现在通过 底层 播放的时候，没发一帧yuv上来，都与之进行内存共享，将每帧都获取；  现在录制，抓图，包括opengl变化，都正常了啊

**Comment by dpmaycry** [comment]
@dan-huang 对当前帧进行计算后，计算结果是一个矩形框，怎样将矩形框画到画面上呢。
这个问题有什么好的解决方案么，我现在在用textureview预览camera，得到的数据应该是在onSurfaceTextureUpdated里的SurfaceTexture，有什么办法利用这里的SurfaceTexture来在同一个textureview里画个框么

**Comment by fengbenpaao** [comment]
@dan-huang  利用 jni与java内存共享的方式，直接跳过SDL播放器，  发送消息告知java层去读取yuv数据，利用opengL 对yuv进行渲染，很流畅，  可以做各种变换；      2.如果你改造SDL的话，再去做opengl渲染 ，好慢，改造过程好繁杂

**Comment by spysoos** [comment]
@fengbenpaao 请问 你是使用 @shishuo365 提供的思路吗？

**Comment by fengbenpaao** [comment]
@spysoos   利用jni创建一个共享内存块，然后得到该内存的指针，每个yuv拷贝到该内存块中，通过jni回调java 告知上层，上层获取数据 保存为一张张图片，就可以了；     
2.如果不用共享内存，利用jni回调 一个buf给到java层也是可以的，可能会卡；

**Comment by hhbgk** [comment]
@fengbenpaao Android使用硬解码后，这方法还适用吗？

**Comment by shishuo365** [comment]
@hhbgk 同样适用；取数据的位置是在渲染前，这时候所有的解码已经完成，渲染的是原始的YUV/RGB数据，软硬解同样适用。

**Comment by shishuo365** [comment]
@hhbgk 同样适用；取数据的位置是在渲染前，这时候所有的解码已经完成，渲染的是原始的YUV/RGB数据，软硬解同样适用。

**Comment by ipcjs** [comment]
@shishuo365 
你这个获取帧数据的时机应该是，帧数据入队的时候吧
和播放器当前显示的帧会有明显差异吗？

**Comment by xsfgdut** [comment]
@fengbenpaao 请问jni创建一个共享内存块这个思路是怎么实现，能否提供一个？谢谢

**Comment by caoustc** [comment]
@shishuo365 @fengbenpaao 麻烦问下怎样能转换出需要的数据呢，在硬解下vp->bmp->pitches[0]一直是0，能否提供一下实现的例子呢，谢谢

**Comment by wyw1267** [comment]
> @hhbgk 同样适用；取数据的位置是在渲染前，这时候所有的解码已经完成，渲染的是原始的YUV/RGB数据，软硬解同样适用。

大佬，mediacodec硬解送渲染前的数据通过什么方法可以拿出来呢？
