### ISSUE TITLE
播放LocalServer已缓存的视频问题？

### ISSUE THREAD

**Issue by ClaudeLi** [Bilibili/ijkplayer#3013]
你好我在iOS客户端上搭载了LocalServer来缓存视频，我发现在调用ijkPlayer播放视频时，如果断网 已经缓存的片段 没法播放，没法seek？即使本地服务器上已缓存完整了完整视频，同样有这个问题。请问是什么问题

**Comment by callmewenxi** [comment]
请问有LocalServer相关的资料吗?

**Comment by ClaudeLi** [comment]
可以参考第三方开源库 GCDWebServer和CocoaHttpServer 都可以实现LocalServer




发自网易邮箱大师
在2017年05月31日 14:54，callmewenxi 写道：

请问有LocalServer相关的资料吗?

**Comment by callmewenxi** [comment]
@ClaudeLi 请问做法是通过CocoaHttpServer或者GCDWebServer直接下载并缓存数据然后丢给播放器吗?还是通过NSURLSession之类的去下载,然后通过代理将数据丢给播放器?

后面的这种方式已经实现了,但是如果遇到mp4的moov信息在后面的话,会导致播放失败?
如果是通过CocoaHttpServer或GCDWebServer直接下载然后塞数据给播放器,需要这么做呢?在网上找不到任何资料.

**Comment by ClaudeLi** [comment]
开启LocalServer  将视频URL组织成类似这种形式：
http://localhost:port?url=videoUrl
把组织好的URL交给播放器播放，播放器把请求发送到LocalServer上，LocalServer解析到实际的音频地址后发送请求或者读取已缓存的数据。 github上应该有一些例子的 之前看到过 你可以搜GCDWebServer 应该就可以找到




发自网易邮箱大师
在2017年06月06日 19:34，callmewenxi 写道：

@ClaudeLi 请问做法是通过CocoaHttpServer或者GCDWebServer直接下载并缓存数据然后丢给播放器吗?还是通过NSURLSession之类的去下载,然后通过代理将数据丢给播放器?

后面的这种方式已经实现了,但是如果遇到mp4的moov信息在后面的话,会导致播放失败?
如果是通过CocoaHttpServer或GCDWebServer直接下载然后塞数据给播放器,需要这么做呢?在网上找不到任何资料.

**Comment by callmewenxi** [comment]
@ClaudeLi https://github.com/fq050766/AVPlayerWithGCDwebserver 这个是吧?这个我看了源码,不是边下边播的,应该是缓存完再播的,如果不是这个的话,希望你能说说是那个demo,这个问题已经困扰了我很久了?

"LocalServer解析到实际的音频地址后发送请求或者读取已缓存的数据"
LocalServer解析到实际的音频地址后发送请求 这个是只要将拼接好的地址塞给播放器, 已经开启的LocalServer会自动解析到是指的音频地址发送请求?还是说这个请求需要我自己代码去实现?

**Comment by ceekay1991** [comment]
@ClaudeLi 使用LocalServer时，如果用户拖动的时候，需要的数据本地还没有下载，这时候，localServer怎么通知下载器从seek的位置开始下载数据？
