### ISSUE TITLE
播放avi视频的问题

### ISSUE THREAD

**Issue by TonightGod** [Bilibili/ijkplayer#3014]
如果想播放avi视频还想用module-lite.sh,应该如何配置module-lite.sh需要添加哪些COMMON_FF_CFG_FLAGS

**Comment by raymond1012** [comment]
http://www.ffmpeg.org/ffmpeg-protocols.html

**Comment by szhansen** [comment]
同问，楼主解决了吗 ？分享下，谢谢

**Comment by huangcy3373** [comment]
@TonightGod @szhansen 大家有解决吗
