### ISSUE TITLE
infinite_buffer value problem

### ISSUE THREAD

**Issue by cjwyl1** [Bilibili/ijkplayer#3015]
Hello, when I study IJK, I find the logic as follows:

`/* if the queue are full, no need to read more */ 

        if (ffp->infinite_buffer<1 && !is->seek_req && (is->audioq.size + is->videoq.size + is->subtitleq.size > ffp->dcc.max_buffer_size
            || (   stream_has_enough_packets(is->audio_st, is->audio_stream, &is->audioq, MIN_FRAMES)
                && stream_has_enough_packets(is->video_st, is->video_stream, &is->videoq, MIN_FRAMES)
                && stream_has_enough_packets(is->subtitle_st, is->subtitle_stream, &is->subtitleq, MIN_FRAMES)))) {
            if (!is->eof) {
                ffp_toggle_buffering(ffp, 0);
            }
            /* wait 10 ms */
            SDL_LockMutex(wait_mutex);
            SDL_CondWaitTimeout(is->continue_read_thread, wait_mutex, 10);
            SDL_UnlockMutex(wait_mutex);
            continue;
        }`

I think it is used for some replays to limit it's max-buffer-size. But when i test with some URL like "RTP://...", i found they also be Impacted by the code above. Then i found this code:
`if (ffp->infinite_buffer <= 0 && is->realtime)
        ffp->infinite_buffer = 1;`
Maybe it's mean the realtime-URL will not be limited with the max-buffer-size. However, I found the
 ffp->infinite_buffer is equal to zero. After I search the code, I found those code:
`FFPlayer *ffp_create()
{
    av_log(NULL, AV_LOG_INFO, "av_version_info: %s\n", av_version_info());
    av_log(NULL, AV_LOG_INFO, "ijk_version_info: %s\n", ijk_version_info());

    FFPlayer* ffp = (FFPlayer*) av_mallocz(sizeof(FFPlayer));
    if (!ffp)
        return NULL;

    msg_queue_init(&ffp->msg_queue);
    ffp->af_mutex = SDL_CreateMutex();
    ffp->vf_mutex = SDL_CreateMutex();

    ffp_reset_internal(ffp);
    ffp->av_class = &ffp_context_class;
    ffp->meta = ijkmeta_create();

    av_opt_set_defaults(ffp);

    return ffp;
}`

In the code `ffp_reset_internal(ffp);` , it set `ffp->infinite_buffer        = -1;` . But in the code `av_opt_set_defaults(ffp);` , it set ffp->infinite_buffer the default Value zero . 

`{ "infbuf",                         "don't limit the input buffer size (useful with realtime streams)",
        OPTION_OFFSET(infinite_buffer), OPTION_INT(0, 0, 1) }`

is it wrong?

**Comment by raymond1012** [comment]
if (ffp->infinite_buffer < 0 && is->realtime)
ffp->infinite_buffer = 1;

2017-04-25 17:02 GMT+08:00 cjwyl1 <notifications@github.com>:

**Comment by cjwyl1** [comment]
@raymond1012  the ffp->infinite_buffer will be set to ZERO due to the code `av_opt_set_defaults(ffp);`

**Comment by raymond1012** [comment]
so the ffp->infinite_buffer is always 0

2017-04-25 18:02 GMT+08:00 cjwyl1 <notifications@github.com>:

**Comment by cjwyl1** [comment]
T.T 
so if I don't want to use max-buffer-size logic that I mention above, change the ffp->infinite_buffer = 1
is right?

**Comment by raymond1012** [comment]
yes

2017-04-25 19:36 GMT+08:00 cjwyl1 <notifications@github.com>:

**Comment by cjwyl1** [comment]
Thanks~ >_<
