### ISSUE TITLE
iOS播放竖着拍摄的视频就会自动旋转90度，怎么解决？

### ISSUE THREAD

**Issue by BlueTopsky** [Bilibili/ijkplayer#3016]
iOS里面没有TextureView，请问怎么解决这一问题啊，播放竖着拍摄的视频就会自动旋转了90度，播放横着拍摄的视频时是正常的

**Comment by raymond1012** [comment]
模仿android 实现auto rotate

**Comment by BlueTopsky** [comment]
自动旋转不是问题，关键是有的视频用代码检测不到是否已经被旋转了，因此不知道该不该去旋转此视频
