### ISSUE TITLE
关于ffp->error的疑问

### ISSUE THREAD

**Issue by Fanping** [Bilibili/ijkplayer#3024]
在视频播放过程中，当网络发生错误的时候，ffp->error并没有获得网络错误的信息，但是看error.h中的定义，应该是可以包含各类错误信息的，请教下：ffp->error错误内容是否只针对ffplayer本身的错误，而不包含网络等相关错误？

谢谢~

**Comment by andyleftzhang** [comment]
同问+1

**Comment by raymond1012** [comment]
io 的错误会赋值给 ffp->error
