### ISSUE TITLE
compile error with x86 arch

### ISSUE THREAD

**Issue by wanzhang** [Bilibili/ijkplayer#303]
====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a x86 arm64
FF_ACT_ARCHS = armv5 armv7a x86

====================
[*] check env x86
====================
NDKr10b (64-bit) detected

--------------------
[*] make NDK standalone toolchain
--------------------
build on Linux x86_64

--------------------
[*] check ffmpeg env
--------------------

--------------------
[*] configurate ffmpeg
--------------------
reuse configure

--------------------
[*] compile ffmpeg
--------------------
CC	libavcodec/x86/mpegvideoenc.o
CC	libavcodec/x86/rv34dsp_init.o
CC	libavcodec/x86/rv40dsp_init.o
YASM	libavcodec/x86/rv34dsp.o
In file included from libavcodec/x86/mpegvideoenc.c:83:0:
libavcodec/x86/mpegvideoenc_template.c: In function 'dct_quantize_ssse3':
libavcodec/x86/mpegvideoenc_template.c:151:9: error: 'asm' operand has impossible constraints
         __asm__ volatile(
         ^
libavcodec/x86/mpegvideoenc_template.c:186:9: error: 'asm' operand has impossible constraints
         __asm__ volatile(
         ^
STRIP	libavcodec/x86/rv34dsp.o
make: *** [libavcodec/x86/mpegvideoenc.o] Error 1
make: *** Waiting for unfinished jobs....
YASM	libavcodec/x86/rv40dsp.o
YASM	libavcodec/x86/sbrdsp.o
STRIP	libavcodec/x86/sbrdsp.o
STRIP	libavcodec/x86/rv40dsp.o

**Comment by bbcallen** [comment]
If you don't need mpegvideo encoder, disable it as a workaround.

**Comment by bbcallen** [comment]
Can't reproduce with NDKr10e on MacOS.

Have a look at your yasm version.

$ yasm --version
yasm 1.2.0
Compiled on Feb 22 2014.
Copyright (c) 2001-2011 Peter Johnson and other Yasm developers.
Run yasm --license for licensing overview and summary.
