### ISSUE TITLE
Module ijkplayer depends on undefined modules: ijksoundtouch

### ISSUE THREAD

**Issue by JoyHong** [Bilibili/ijkplayer#3035]
~/Git/ijkplayer-android/android$ ./compile-ijk.sh all
profiler build: NO

~/Android/Sdk/ndk-bundle/build/core/build-binary.mk:687: Android NDK: Module ijkplayer depends on undefined modules: ijksoundtouch    
~/Android/Sdk/ndk-bundle/build/core/build-binary.mk:700: *** Android NDK: Aborting (set APP_ALLOW_MISSING_DEPS=true to allow missing dependencies)    .  Stop.
~/Git/ijkplayer-android/android
profiler build: NO

**Comment by raymond1012** [comment]
need init-android
