### ISSUE TITLE
Android Activity处于后台时无法切换视频源

### ISSUE THREAD

**Issue by SaudM** [Bilibili/ijkplayer#3038]
调用IjkVideoView的start方法时，如果此时Activity处于后台，则不回调IMediaPlayer.OnPreparedListener的onPrepared方法。如果切换会前台，则立即开始正常播放。请问解决办法

**Comment by lrs0304** [comment]
activity生命周期停止了，用service解决吧

**Comment by zhanggao** [comment]
![image](https://cloud.githubusercontent.com/assets/5298896/25794230/99f75cde-3402-11e7-9b03-339382d44dc2.png)
问题大概在这，在后台时，SurfaceView不可用，你把创建逻辑改下试下。

**Comment by SaudM** [comment]
Thanks，This problem has been resolved

**Comment by lzkc72** [comment]
> Thanks，This problem has been resolved

hello,,I've been puzzled by this problem for several days!!
i want to ask you how you solved it at that time.
sorry to bother you

**Comment by zhanggao** [comment]
@lzkc72 
use TextureView, 
onSurfaceTextureDestroyed return true.
