### ISSUE TITLE
flv 播放没有声音

### ISSUE THREAD

**Issue by cicoco** [Bilibili/ijkplayer#3039]
http://ah.download.cycore.cn/rrt/c472411e8fce43b1310f08fc0d5dc1be/42775364858/c1538d516d9895203cf25d1ec957cd82.flv 
这个文件播放没有声音
机型：魅蓝M3 Note
ijkplayer版本：0.7.9 compile-lite.sh编译版

**Comment by raymond1012** [comment]
此文件并非flv而是avi，需要使能avi，另外可能是文件中音视频排列顺序有问题会导致不停的seek，所以如果放在网络端播放会比较卡顿
