### ISSUE TITLE
魅族mx4手机，使用ijkmediaplayer获取当前时间的问题

### ISSUE THREAD

**Issue by pys200603027** [Bilibili/ijkplayer#304]
hi bbcallen 
mx4手机上，ijkmediaplayer.getCurrentPosition()获取到的是unix时间戳,不知你有没有遇到过
![2v9ofe jz erjo18 b9lxu](https://cloud.githubusercontent.com/assets/5933158/8459016/ff48bbc6-204c-11e5-97a5-307709555c71.png)

**Comment by bbcallen** [comment]
没有。

**Comment by pys200603027** [comment]
问题已经解决，测试了两个xm4，android4.4.2版本的会有此问题，(int)ijkmediaplayer.getCurrentPosition()转换下解决了问题
感谢bbcallen 和ijk
