### ISSUE TITLE
使用在原始demo上改成使用TextureRenderView重复退出进入多次后出现not release错误

### ISSUE THREAD

**Issue by niufeihu** [Bilibili/ijkplayer#3054]
demo默认使用的是SurfaceRenderView,改成使用TextureRenderView，连续退出进入activity多次后出现not release崩溃
TextureRenderView 的mp.setSurface(openSurface());我猜原因每次都new Surface。但是将new Surface的值release后还是会出现not release错误。

**Comment by raymond1012** [comment]
need call releaseSurfaceTexture
