### ISSUE TITLE
android studio导入debug模式报错

### ISSUE THREAD

**Issue by net168** [Bilibili/ijkplayer#3055]
编译成功后，执行sh android/patch-debugging-with-lldb.sh armv7a出现以下错误：

patch apply ==> armv7a
error: patch failed: android/ijkplayer/.gitignore:6
error: android/ijkplayer/.gitignore: patch does not apply
git apply ==> patches/0001-gitignore-ignore-.externalNativeBuild.patch
error: patch failed: android/ijkplayer/build.gradle:5
error: android/ijkplayer/build.gradle: patch does not apply
git apply ==> patches/0002-gradle-upgrade-build-tool-to-2.2.0-beta2.patch
error: patch failed: android/ijkplayer/ijkplayer-example/build.gradle:44
error: android/ijkplayer/ijkplayer-example/build.gradle: patch does not apply
git apply ==> patches/0003-armv7a-enable-debugging-with-LLDB.patch
error: patch failed: android/ijkplayer/ijkplayer-java/src/main/java/tv/danmaku/ijk/media/player/IjkMediaPlayer.java:165
error: android/ijkplayer/ijkplayer-java/src/main/java/tv/danmaku/ijk/media/player/IjkMediaPlayer.java: patch does not apply
error: patch failed: ijkmedia/ijkplayer/Android.mk:59
error: ijkmedia/ijkplayer/Android.mk: patch does not apply
error: patch failed: ijkmedia/ijksdl/Android.mk:70
error: ijkmedia/ijksdl/Android.mk: patch does not apply
git apply ==> patches/0004-armv7a-link-prebuilt-staic-libraries-of-ffmepg.patch

**Comment by raymond1012** [comment]
patch-debugging-with-lldb.sh is expired

**Comment by net168** [comment]
不打算修复这个失效的sh吗？

**Comment by net168** [comment]
能否提供下 该debug模式 回溯到哪个ijkplayer 的 release版本是可用的？
