### ISSUE TITLE
android如何配置混淆

### ISSUE THREAD

**Issue by denghanhao** [Bilibili/ijkplayer#3059]
如题

**Comment by zhanggao** [comment]
涉及native的类keep下。然后打包运行，哪个类报错了就把哪个类加进去。

**Comment by wdhonor** [comment]
-keep com.dou361.ijkplayer.** {*; }
-keep tv.danmaku.ijk.**{*; }

**Comment by denghanhao** [comment]
已经可以了，我是这样配置的
-keep class tv.danmaku.ijk.media.player.** {*;}
-keep class tv.danmaku.ijk.media.player.IjkMediaPlayer{*;}
-keep class tv.danmaku.ijk.media.player.ffmpeg.FFmpegApi{*;}

**Comment by harlanc** [comment]
@denghanhao  请问你的操作混淆的是哪部分代码？
