### ISSUE TITLE
IjkMediaPlayer Options/Categories

### ISSUE THREAD

**Issue by azgalaxy** [Bilibili/ijkplayer#3060]
The IjkMediaPlayer has three different types of options:

    - OPT_CATEGORY_PLAYER
    - OPT_CATEGORY_FORMAT
    - OPT_CATEGORY_CODEC

Which options can be applied to these types throw setOption ?  and where can we find them?
can we set all FFmpeg/FFplay options throw IjkMediaPlayer? 

Regards

**Comment by raymond1012** [comment]
different maps
