### ISSUE TITLE
使用nellymoser音频编码，加载视频会比较慢，但用aac编码加载会很快

### ISSUE THREAD

**Issue by jyfree** [Bilibili/ijkplayer#3061]
ijkplayer在max_frame_duration之前做了什么操作，打印这条log需要的时间会比较长

05-09 17:32:17.251 7547-32214/com.jj.shows D/IJKMEDIA: FFP_MSG_FLUSH:
05-09 17:32:17.491 7547-32216/com.jj.shows E/IJKMEDIA: Option http-detect-range-support not found.
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: max_frame_duration: 3600.000

**Comment by jyfree** [comment]
详细log：

05-09 17:32:13.491 7547-7547/com.jj.shows D/IJKMEDIA: IjkMediaPlayer_reset
05-09 17:32:13.491 7547-7547/com.jj.shows D/IJKMEDIA: IjkMediaPlayer_release
05-09 17:32:13.501 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
05-09 17:32:13.501 7547-7547/com.jj.shows D/IJKMEDIA: ffpipeline_set_surface()
05-09 17:32:13.501 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
05-09 17:32:13.501 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_shutdown_l()
05-09 17:32:13.501 7547-32149/com.jj.shows D/IJKMEDIA: message_loop exit
05-09 17:32:13.541 7547-32151/com.jj.shows E/IJKMEDIA: AVC: nal size 3228
05-09 17:32:13.541 7547-32151/com.jj.shows E/IJKMEDIA: missing picture in access unit with size 1436
05-09 17:32:13.551 7547-7547/com.jj.shows E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xabc0a0c0)
05-09 17:32:13.551 7547-7547/com.jj.shows E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xac10f270)
05-09 17:32:13.551 7547-7547/com.jj.shows E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xac1199f8)
05-09 17:32:13.551 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_shutdown_l()=void
05-09 17:32:13.551 7547-7547/com.jj.shows D/IJKMEDIA: IjkMediaPlayer_native_setup
05-09 17:32:13.551 7547-7547/com.jj.shows D/IJKMEDIA: ffpipeline_create_from_android()
05-09 17:32:13.551 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_format_callback(0x7e6af1f1, 0x1010b2)
05-09 17:32:13.551 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_format_callback()=void
05-09 17:32:13.551 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
05-09 17:32:13.551 7547-7547/com.jj.shows D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
05-09 17:32:13.551 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
05-09 17:32:13.551 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_dec_ref(): ref=0
05-09 17:32:13.551 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_shutdown_l()
05-09 17:32:13.551 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_shutdown_l()=void
05-09 17:32:13.551 7547-7547/com.jj.shows D/IJKMEDIA: IjkMediaPlayer_release
05-09 17:32:13.551 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
05-09 17:32:13.551 7547-7547/com.jj.shows D/IJKMEDIA: ffpipeline_set_surface()
05-09 17:32:13.551 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
05-09 17:32:13.551 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_shutdown_l()
05-09 17:32:13.551 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_shutdown_l()=void
05-09 17:32:13.551 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_dec_ref(): ref=0
05-09 17:32:13.551 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_shutdown_l()
05-09 17:32:13.551 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_shutdown_l()=void
05-09 17:32:13.881 7547-7547/com.jj.shows D/IJKMEDIA: IjkMediaPlayer_native_profileEnd
05-09 17:32:13.881 7547-7547/com.jj.shows W/IJKMEDIA: moncleanu already called
05-09 17:32:16.341 7547-7559/com.jj.shows D/IJKMEDIA: IjkMediaPlayer_native_finalize
05-09 17:32:16.341 7547-7559/com.jj.shows D/IJKMEDIA: IjkMediaPlayer_release
05-09 17:32:17.091 7547-7547/com.jj.shows D/IJKMEDIA: IjkMediaPlayer_native_profileBegin
05-09 17:32:17.091 7547-7547/com.jj.shows W/IJKMEDIA: monstartup already called
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: IjkMediaPlayer_native_setup
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ffpipeline_create_from_android()
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_format_callback(0x7e6af1f1, 0xfb6)
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_format_callback()=void
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: IjkMediaPlayer_setOptionLong
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_option_int(overlay-format, 842225234)
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_option_int()=void
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: IjkMediaPlayer_setOptionLong
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_option_int(framedrop, 12)
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_option_int()=void
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: IjkMediaPlayer_setOptionLong
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_option_int(http-detect-range-support, 0)
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_option_int()=void
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: IjkMediaPlayer_setOption
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_option(user_agent, (null))
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_option()=void
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: IjkMediaPlayer_setOptionLong
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_option_int(skip_loop_filter, 0)
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_option_int()=void
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
05-09 17:32:17.251 7547-7547/com.jj.shows V/IJKMEDIA: setDataSource: path http://pull.9shows.com/live/587143.flv?wsSecret=0523a23ff73fddab360ed91e1afc1bde&wsTime=1494322337
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_data_source(url="http://pull.9shows.com/live/587143.flv?wsSecret=0523a23ff73fddab360ed91e1afc1bde&wsTime=1494322337")
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_data_source(url="http://pull.9shows.com/live/587143.flv?wsSecret=0523a23ff73fddab360ed91e1afc1bde&wsTime=1494322337")=0
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffcbb340)
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ffpipeline_set_surface()
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffcbb340)=void
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: IjkMediaPlayer_prepareAsync
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_prepare_async()
05-09 17:32:17.251 7547-7547/com.jj.shows I/IJKMEDIA: ===== options =====
05-09 17:32:17.251 7547-7547/com.jj.shows I/IJKMEDIA: player-opts : overlay-format               = 842225234
05-09 17:32:17.251 7547-7547/com.jj.shows I/IJKMEDIA: player-opts : framedrop                    = 12
05-09 17:32:17.251 7547-7547/com.jj.shows I/IJKMEDIA: format-opts : http-detect-range-support    = 0
05-09 17:32:17.251 7547-7547/com.jj.shows I/IJKMEDIA: codec-opts  : skip_loop_filter             = 0
05-09 17:32:17.251 7547-7547/com.jj.shows I/IJKMEDIA: ===================
05-09 17:32:17.251 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_prepare_async()=0
05-09 17:32:17.251 7547-32215/com.jj.shows I/IJKMEDIA: SDL_RunThread: [32215] ff_vout
05-09 17:32:17.251 7547-32215/com.jj.shows D/IJKMEDIA: ffpipenode_create_video_output_from_android_mediacodec()
05-09 17:32:17.251 7547-32214/com.jj.shows I/IJKMEDIA: SDL_RunThread: [32214] ff_msg_loop
05-09 17:32:17.251 7547-32214/com.jj.shows D/IJKMEDIA: message_loop
05-09 17:32:17.251 7547-32216/com.jj.shows I/IJKMEDIA: SDL_RunThread: [32216] ff_read
05-09 17:32:17.251 7547-32214/com.jj.shows D/IJKMEDIA: FFP_MSG_FLUSH:
05-09 17:32:17.491 7547-32216/com.jj.shows E/IJKMEDIA: Option http-detect-range-support not found.
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: max_frame_duration: 3600.000
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: Input #0, flv, from 'http://pull.9shows.com/live/587143.flv?wsSecret=0523a23ff73fddab360ed91e1afc1bde&wsTime=1494322337':
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA:   Metadata:
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA:     Server          : 
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: WSCacheServer
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA:     avcprofile      : 
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: 66
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA:     avclevel        : 
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: 51
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA:     displayWidth    : 
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: 480
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA:     displayHeight   : 
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: 360
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA:     fps             : 
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: 24
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA:   Duration: 
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: 00:00:00.00
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: , start: 
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: 0.000000
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: , bitrate: 
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: N/A
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA:     Stream #0:0
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: : Video: h264 (Baseline), yuv420p(tv), 480x360 [SAR 1:1 DAR 4:3]
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: , 
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: 24.42 fps, 
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: 15.08 tbr, 
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: 1k tbn, 
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: 48 tbc
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA:     Stream #0:1
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: : Audio: nellymoser, 44100 Hz, mono, flt
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: SDL_Android_AudioTrack: CHANNEL_OUT_MONO
05-09 17:32:18.691 7547-32216/com.jj.shows I/IJKMEDIA: SDL_Android_AudioTrack: ENCODING_PCM_16BIT
05-09 17:32:18.701 7547-32216/com.jj.shows I/IJKMEDIA: SDL_Android_AudioTrack_new: init volume as 1.000000/(0.000000,1.000000)
05-09 17:32:18.701 7547-32216/com.jj.shows I/IJKMEDIA: AudioCodec: avcodec, nellymoser
05-09 17:32:18.711 7547-32228/com.jj.shows I/IJKMEDIA: SDL_RunThread: [32228] ff_audio_dec
05-09 17:32:18.711 7547-32227/com.jj.shows I/IJKMEDIA: SDL_RunThread: [32227] ff_aout_android
05-09 17:32:18.721 7547-32216/com.jj.shows I/IJKMEDIA: VideoCodec: avcodec, h264
05-09 17:32:18.721 7547-32216/com.jj.shows W/IJKMEDIA: fps: 24.416667 (normal)
05-09 17:32:18.721 7547-32216/com.jj.shows W/IJKMEDIA: fps: 15.083333 (normal)
05-09 17:32:18.721 7547-32234/com.jj.shows I/IJKMEDIA: SDL_RunThread: [32234] ff_video_dec
05-09 17:32:18.721 7547-32214/com.jj.shows D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_PREPARED
05-09 17:32:18.721 7547-32214/com.jj.shows D/IJKMEDIA: FFP_MSG_PREPARED:
05-09 17:32:18.721 7547-32214/com.jj.shows D/IJKMEDIA: FFP_MSG_VIDEO_SIZE_CHANGED: 480, 360
05-09 17:32:18.721 7547-32214/com.jj.shows D/IJKMEDIA: FFP_MSG_SAR_CHANGED: 1, 1
05-09 17:32:18.721 7547-32214/com.jj.shows D/IJKMEDIA: FFP_MSG_BUFFERING_START:
05-09 17:32:18.731 7547-32234/com.jj.shows D/IJKMEDIA: SDL_VoutFFmpeg_CreateOverlay(w=480, h=360, fmt=RV32(0x32335652, dp=0xab6a81f8)
05-09 17:32:18.731 7547-32214/com.jj.shows D/IJKMEDIA: FFP_MSG_VIDEO_SIZE_CHANGED: 480, 360
05-09 17:32:18.731 7547-32234/com.jj.shows D/IJKMEDIA: SDL_VoutFFmpeg_CreateOverlay(w=480, h=360, fmt=RV32(0x32335652, dp=0xab6a81f8)
05-09 17:32:18.731 7547-32214/com.jj.shows D/IJKMEDIA: FFP_MSG_VIDEO_SIZE_CHANGED: 480, 360
05-09 17:32:18.741 7547-32234/com.jj.shows D/IJKMEDIA: SDL_VoutFFmpeg_CreateOverlay(w=480, h=360, fmt=RV32(0x32335652, dp=0xab6a81f8)
05-09 17:32:18.741 7547-32214/com.jj.shows D/IJKMEDIA: FFP_MSG_VIDEO_SIZE_CHANGED: 480, 360
05-09 17:32:18.741 7547-7547/com.jj.shows D/IJKMEDIA: IjkMediaPlayer_start
05-09 17:32:18.741 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_start()
05-09 17:32:18.741 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_start()=0
05-09 17:32:18.741 7547-32214/com.jj.shows D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
05-09 17:32:18.761 7547-7547/com.jj.shows D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
05-09 17:32:18.761 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffcba510)
05-09 17:32:18.761 7547-7547/com.jj.shows D/IJKMEDIA: ffpipeline_set_surface()
05-09 17:32:18.761 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffcba510)=void
05-09 17:32:18.761 7547-7547/com.jj.shows D/IJKMEDIA: IjkMediaPlayer_start
05-09 17:32:18.761 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_start()
05-09 17:32:18.761 7547-7547/com.jj.shows D/IJKMEDIA: ijkmp_start()=0
05-09 17:32:18.761 7547-32214/com.jj.shows D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
05-09 17:32:19.291 7547-32214/com.jj.shows D/IJKMEDIA: FFP_MSG_BUFFERING_END:
05-09 17:32:19.291 7547-32215/com.jj.shows D/IJKMEDIA: ANativeWindow_setBuffersGeometry: w=480, h=360, f=(0x4) => w=480, h=360, f=RV32(0x32335652)

**Comment by raymond1012** [comment]
try debug avformat_open_input
