### ISSUE TITLE
视频 Metadata : rotate : 90 播放时 视频旋转了90度 如何设置不旋转

### ISSUE THREAD

**Issue by ClaudeLi** [Bilibili/ijkplayer#3063]
有些视频的 Metadata 包含了rotate 90 / 180 / 270 在播放时 被旋转了，请问这个可以设置么？

**Comment by fgh345** [comment]
请问怎么解决的


> 有些视频的 Metadata 包含了rotate 90 / 180 / 270 在播放时 被旋转了，请问这个可以设置么？

请问怎么解决的

**Comment by fgh345** [comment]
请问怎么解决的


> 有些视频的 Metadata 包含了rotate 90 / 180 / 270 在播放时 被旋转了，请问这个可以设置么？

请问怎么解决的

**Comment by ClaudeLi** [comment]
> 请问怎么解决的
> 
> > 有些视频的 Metadata 包含了rotate 90 / 180 / 270 在播放时 被旋转了，请问这个可以设置么？
> 
> 请问怎么解决的

根据rotate 自己给layer层做旋转，
这里有份iOS编译成framework的 https://github.com/ClaudeLi/IJKPlayerWithSSL

**Comment by fgh345** [comment]
非常感谢!
怎么读取到rotate呢 我主要是找不到这个参数




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ClaudeLi"<notifications@github.com&gt;; 
发送时间: 2020年2月14日(星期五) 中午1:10
收件人: "bilibili/ijkplayer"<ijkplayer@noreply.github.com&gt;; 
抄送: "君值韶华莫等闲"<1145073867@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [bilibili/ijkplayer] 视频 Metadata : rotate : 90 播放时 视频旋转了90度 如何设置不旋转 (#3063)



 
请问怎么解决的
  
有些视频的 Metadata 包含了rotate 90 / 180 / 270 在播放时 被旋转了，请问这个可以设置么？
  
请问怎么解决的
  
根据rotate 自己给layer层做旋转，
 这里有份iOS编译成framework的 https://github.com/ClaudeLi/IJKPlayerWithSSL

**Comment by ClaudeLi** [comment]
> 非常感谢! 怎么读取到rotate呢 我主要是找不到这个参数
> […](#)

FFP_MSG_VIDEO_ROTATION_CHANGED

**Comment by fgh345** [comment]
好的 多谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ClaudeLi"<notifications@github.com&gt;; 
发送时间: 2020年2月14日(星期五) 中午1:20
收件人: "bilibili/ijkplayer"<ijkplayer@noreply.github.com&gt;; 
抄送: "君值韶华莫等闲"<1145073867@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [bilibili/ijkplayer] 视频 Metadata : rotate : 90 播放时 视频旋转了90度 如何设置不旋转 (#3063)



 
非常感谢! 怎么读取到rotate呢 我主要是找不到这个参数
 …
  
FFP_MSG_VIDEO_ROTATION_CHANGED
