### ISSUE TITLE
FFMPeg properties propagate

### ISSUE THREAD

**Issue by georginovakov** [Bilibili/ijkplayer#3065]
Hi, 
I am using ijkplayer for android and it works great with HD  streams.
When I try to play SD streams I have problems with the quality. I think the problem is related to upscaling. Nut anyway I am trying to pass the following properties to ffmpeg and I am not sure how to do it through ijkPlayer:

./ffmpeg -i 'udp://'
 -acodec copy -vcodec mpeg2video -me_method epzs 
 -cmp 2 
 -subcmp 2 
 -b:v 2400k 
 -bufsize 1750k 
 -minrate 2400k
 -maxrate 2400k 
 -muxrate 3000k 
 -q:v 7 
 -g 50 
 -pix_fmt yuv420p 
 -s 720x576  
 -f mpegts 
 -r 25 

Thanks

**Comment by raymond1012** [comment]
some properties can set by setoption
