### ISSUE TITLE
关于ASAO音频的解码

### ISSUE THREAD

**Issue by marsye109** [Bilibili/ijkplayer#3066]
你好，我用IJK播放视频流的时候只有画面没有声音， 音频是ASAO格式，请问有什么办法可以支持吗？

**Comment by yuazhen** [comment]
默认应该是没有开启nellymoser解码器的，需要自行配置ffmpeg开启nellymoser格式的支持，然后重编ffmpeg。
修改config/module.sh，详细方法见[README.md](https://github.com/Bilibili/ijkplayer/blob/master/README.md)
