### ISSUE TITLE
其他文件格式播放没有问题，但H264文件格式获取不到时间.

### ISSUE THREAD

**Issue by PickUpKeyboard94Doing** [Bilibili/ijkplayer#3068]
其他文件格式播放没有问题，但H264文件格式获取不到currentPlaybackTime和duration。
![78b09e3a-fa0c-4cd6-9944-5bb6ea9ee10c](https://cloud.githubusercontent.com/assets/26448871/25881897/34143a2e-3572-11e7-83b0-b4806b1523bc.png)

**Comment by raymond1012** [comment]
缺少时间戳和封装时间
