### ISSUE TITLE
setDataSource(Context context, Uri uri, Map<String, String> headers)可以修改uri吗

### ISSUE THREAD

**Issue by niufeihu** [Bilibili/ijkplayer#3069]
我有一个RecyclerView，假如第一个item的uri是0，第十个item的uri是1，滑动过程中复用了第一个item，然后第十个item的uri变成了0，我想设置第十个item的uri，就调用了MediaPlayer.setDataSource方法，结果报错了java.lang.IllegalStateException at tv.danmaku.ijk.media.player.IjkMediaPlayer._setDataSource(Native Method)。有没有办法初始化了MediaPlayer之后改变uri.

**Comment by raymond1012** [comment]
no way
