### ISSUE TITLE
iOS 播放器如何设置静音

### ISSUE THREAD

**Issue by chrisyang123** [Bilibili/ijkplayer#3070]
self.player.playbackVolume 设置值为 0 以及设置 [options setPlayerOptionIntValue:128 forKey:@"vol"]都没有效果。

**Comment by wanglifeifei** [comment]
self.player.playbackVolume 设置值为 0 ,就可以让播放器静音。我就是这么做的

**Comment by MRsJackYang** [comment]
为什么我这儿就没有playbackVolume这个属性

**Comment by raymond1012** [comment]
try upgrade ijk to lastest

**Comment by chrisyang123** [comment]
self.player.playbackVolume 为0，可以让播放器静音
