### ISSUE TITLE
编译出来的Demo怎么不支持多格式？

### ISSUE THREAD

**Issue by xiongdaAS** [Bilibili/ijkplayer#3076]
ijkplayer不是基于ffmpeg吗？怎么编译出来的demo不支持多格式播放

**Comment by zhanggao** [comment]
修改 config/module.sh，很多东西被裁减掉了，自己把自己需要的格式加上。

**Comment by xiongdaAS** [comment]
有相关说明文档吗？

**Comment by zhanggao** [comment]
这玩意儿不需要文档啊，module-default.sh 是支持格式最全的，就对照着改下，enable disable 一看就知道什么意思。

**Comment by xiongdaAS** [comment]
可以了。还有一个问题，哔哩哔哩客户端里，三指旋转屏幕，这个功能是怎么实现的呀？demo只有一个简单的播放，啥都看不出来

**Comment by xiongdaAS** [comment]
config中全部配置后，发现TS格式的视频也不能播放，是不支持这个格式的视频吗

**Comment by raymond1012** [comment]
需要分析ts中的视频压缩和音频压缩格式，再enable对应的decode
