### ISSUE TITLE
提示找不到libijkffmpeg.so

### ISSUE THREAD

**Issue by hm1027** [Bilibili/ijkplayer#3077]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.bydauto.car.i_key.myapplication-1/base.apk"],nativeLibraryDirectories=[/data/app/com.bydauto.car.i_key.myapplication-1/lib/arm64, /data/app/com.bydauto.car.i_key.myapplication-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"
采用以下方式依赖：
compile project(':ijkplayer-java')
    all32Compile project(':ijkplayer-armv7a')
依赖库ijkplayer-armv7a中/libs/也有armv7a文件夹且有.so文件，为什么提示找不到.so？？

**Comment by hm1027** [comment]
找到原因了，是和第三方依赖库Bmob冲突，请问下该如何解决呢

**Comment by raymond1012** [comment]
fix it by yourself

**Comment by yuandonghua** [comment]
被依赖的库中没有.so文件，找不到.so文件怎么解决呢？
