### ISSUE TITLE
android ijkplayer播放4K视频卡顿，切换成exoplayer就流畅了

### ISSUE THREAD

**Issue by linbiaojj** [Bilibili/ijkplayer#3085]
android ijkplayer播放4K视频卡顿，已经开了硬解了的，切换成exoplayer就很流畅。但是应用需要显示视频实时网络速度，exoplayer没有获取网络速度的接口。

很可能是4K视频使用硬解失败，我的问题跟[issue 2629](https://github.com/Bilibili/ijkplayer/issues/2629)类似

**Comment by zhanghuicuc** [comment]
exoplayer的BandwidthMeter可以用于估算网络吞吐量

**Comment by raymond1012** [comment]
确认是否真的使用了硬解，see https://github.com/Bilibili/ijkplayer/issues/2629
