### ISSUE TITLE
播放本地avi视频出错，帮忙看下

### ISSUE THREAD

**Issue by saberChen** [Bilibili/ijkplayer#3088]
ChannelElement 1.1 missing 
ChannelElement 1.2 missing 
ChannelElement 1.3 missing 
ChannelElement 1.4 missing 
ChannelElement 1.5 missing 
ChannelElement 1.6 missing 
ChannelElement 1.7 missing 
ChannelElement 1.8 missing 
ChannelElement 1.9 missing 

好多上面这个提示，

Probe buffer size limit of 5000000 bytes reached
decoding for stream 0 failed
Estimating duration from bitrate, this may be inaccurate
Could not find codec parameters for stream 0 (Audio: aac, 5.0, fltp, 452 kb/s): unspecified sample rate
Consider increasing the value for the 'analyzeduration' and 'probesize' options
After avformat_find_stream_info() pos: 5000192 bytes read:6062240 seeks:4 frames:1485
/var/containers/Bundle/Application/987F3502-2A34-4A2F-83AF-CE91F5F069C5/PhiCloud.app/3.avi: could not find codec parameters
2017-05-11 19:24:13.639153+0800 PhiCloud[6080:2145730] FFP_MSG_ERROR: 0
2017-05-11 19:24:13.640176+0800 PhiCloud[6080:2145730] IJKMPMoviePlayBackStateDidChange 2: paused
2017-05-11 19:24:13.640423+0800 PhiCloud[6080:2145730] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1
ijkmp_start()
ijkmp_start()=-3

**Comment by raymond1012** [comment]
maybe aac is error
