### ISSUE TITLE
ijk player subtitle

### ISSUE THREAD

**Issue by bluemix** [Bilibili/ijkplayer#310]
does ijk player supports subtitles?
and if so, how to do it?
thanks in advance.

**Comment by bbcallen** [comment]
No, subtitles based on ffplay need avfilter which needs extra memcpy.

**Comment by bluemix** [comment]
ok, thanks a lot @bbcallen

**Comment by Android4MediaPlayer** [comment]
之前我有实现subtitle就是bbcallen这种方式做的，把subtitle属性给UI，UI来做显示。

**Comment by bluemix** [comment]
@Android4MediaPlayer I really didn't fully understand what I'd translate from your text. can you explain it in English, please?

**Comment by shiqyn** [comment]
@bluemix :   How  re-enable subtitle demux codes  ? Can you help me

**Comment by Android4MediaPlayer** [comment]
@bluemix  Before I realized that subtitle is bbcallen this way, the subtitle property to UI, UI to do the show.

**Comment by shiqyn** [comment]
@Android4MediaPlayer  subtitle属性在哪呢？

**Comment by Android4MediaPlayer** [comment]
ffplay自带的啊

**Comment by shiqyn** [comment]
@Android4MediaPlayer 如何将字幕文件传给ffplay? UI层如何回调呢？
