### ISSUE TITLE
如何监听打印错误信息

### ISSUE THREAD

**Issue by Archer353** [Bilibili/ijkplayer#3105]
想获得播放错误时的message，比如探测数据失败；或者是url已经超时失效了；或者是链接有效，但是不是可播放链接等错误时的message，现在postEvent会受到通知，但看不到有效的错误message，该如何获得这种message呢？（注：这些message在日志里能看到，但我想在界面上获得并显示出来）

**Comment by raymond1012** [comment]
you can see ffp_log_callback_brief, try redirect to message
