### ISSUE TITLE
请问，librtmp格式的视频怎么播放？

### ISSUE THREAD

**Issue by iOS-XHWang** [Bilibili/ijkplayer#3107]
合作方给的不是普通的rtmp，说这叫librtmp，有大神知道这个怎么播放吗？

**Comment by zhanghuicuc** [comment]
librtmp不是一个媒体格式，是一个rtmp开发用的库
跟合作方确认清楚吧

**Comment by iOS-XHWang** [comment]
@zhanghuicuc 那怎么播放librtmp的视频？

**Comment by Jakees** [comment]
你可以自己去把IJKplayer做一下对librtmp的扩展支持，至于能不能成功还是要看实际情况，你可以尝试将Ijkplayer工程所使用的ffmpeg 静态链接到 librtmo库（重新编译OpenSSL <openssl是 librtmp依赖的一个lib>和Librtmp），重新编译一下

**Comment by MSAlertController** [comment]
@Jakees 有人写过类似的文章吗？我百度搜不到啊，就只能搜到一篇安卓的，完全看不懂。。。技术不好，求大神指点指点。

**Comment by iOS-XHWang** [comment]
@Jakees 有人写过类似的文章吗？我百度搜不到啊，就只能搜到一篇安卓的，完全看不懂。。。技术不好，求大神指点指点。

**Comment by iOS-XHWang** [comment]
@xinzhengzhang 你是谁啊，凭什么把我问题给关了。。。
