### ISSUE TITLE
android ijkplayer 怎么播放raw和asset 里视频文件

### ISSUE THREAD

**Issue by xwlichen** [Bilibili/ijkplayer#3109]

**Comment by raymond1012** [comment]
通过java接口获取文件路径设给ijk或者通过IMediaDataSource来作为io

**Comment by weilv1990** [comment]
> 通过java接口获取文件路径设给ijk或者通过IMediaDataSource来作为io
试了下如果通过FileDescriptor这样的的接口（setDataSource(FileDescriptor fd)）设置直接会报错：
12-04 16:03:52.533 18329-18329/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_prepare_async()=0
12-04 16:03:52.533 18329-18729/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [18729] ff_read
12-04 16:03:52.534 18329-18728/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [18728] ff_vout
12-04 16:03:52.534 18329-18729/tv.danmaku.ijk.media.example D/IJKMEDIA: Opening 'pipe:51' for reading
12-04 16:03:52.553 18329-18329/tv.danmaku.ijk.media.example I/Choreographer: Skipped 3446 frames!  The application may be doing too much work on its main thread.
12-04 16:03:52.707 18329-18729/tv.danmaku.ijk.media.example D/IJKMEDIA: Statistics: 1048576 bytes read, 0 seeks
12-04 16:03:52.707 18329-18729/tv.danmaku.ijk.media.example E/IJKMEDIA: pipe:51: Invalid data found when processing input
12-04 16:03:52.707 18329-18729/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [18729]
12-04 16:03:52.707 18329-18727/tv.danmaku.ijk.media.example D/IJKMEDIA: FFP_MSG_ERROR: 0
12-04 16:03:52.707 18329-18329/tv.danmaku.ijk.media.example E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
请问ijk现在是不是还不支持FileDescriptor播放assets和raw下的文件？这样看来只能自定义IMediaDataSource来实现了吗
