### ISSUE TITLE
ijk有支持网络重试接口吗？

### ISSUE THREAD

**Issue by Android4MediaPlayer** [Bilibili/ijkplayer#311]
当遇到网络突然不好，之前下载好的播放完就会error退出，如会打印av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
若能重试两三次就会避免这种网络抖动问题，ffmpeg支持吗？还是要修改ijk逻辑了？

**Comment by bbcallen** [comment]
可能连ffmpeg都要改。

**Comment by Android4MediaPlayer** [comment]
这个怎么改呢？加上的话ijk的抗网络能力就强了，建议计划添加

**Comment by bbcallen** [comment]
Patch welcome.

**Comment by Android4MediaPlayer** [comment]
在ffmpeg里已经有重连 但是没有重连次数设置，添加下面代码就可以了
......
    int send_expect_100;
    char *method;
    int reconnect;
    int reconnect_count;
    int reconnecting;
    int listen;
} HTTPContext;

 { "reconnect_count", "reconnect counts after disconnect before EOF when open auto reconnect", OFFSET(reconnect_count), AV_OPT_TYPE_INT, { .i64 = -1 },  -1, INT_MAX, .flags = D|E },

static int http_read_stream(URLContext *h, uint8_t *buf, int size){
....
 return AVERROR_EOF;
    if (s->reconnect && s->reconnecting == 1 &&!h->is_streamed && s->filesize > 0 && s->off < s->filesize) {
        av_log(h, AV_LOG_INFO, "Will again reconnect at %"PRId64".\n", s->off);
        seek_ret = http_seek_internal(h, s->off, SEEK_SET, 1);
        if (seek_ret != s->off) {
            av_log(h, AV_LOG_ERROR, "Failed to reconnect at %"PRId64".\n", s->off);
            if(s->reconnect_count > 0) {
                s->reconnect_count --;
                if(s->reconnect_count > 0) {
                    s->reconnecting = 1;
                    return -20150706;
                }
                s->reconnecting = 0;
            }
            return read_ret;
        }

        read_ret = http_buf_read(h, buf, size);
        return read_ret;
    }

    if (s->end_chunked_post && !s->end_header) {
....
 seek_ret = http_seek_internal(h, s->off, SEEK_SET, 1);
        if (seek_ret != s->off) {
            av_log(h, AV_LOG_ERROR, "Failed to reconnect at %"PRId64".\n", s->off);
            if(s->reconnect_count > 0) {
                s->reconnect_count --;
                if(s->reconnect_count > 0) {
                    s->reconnecting = 1;
                }
                return -20150706;
            }
            return read_ret;
        }
....
}

**Comment by heistings** [comment]
@Android4MediaPlayer 你好，请问后来你是如何设置 reconnect 的？
