### ISSUE TITLE
iOS 播放 AVFoundation 拍摄的视频会被旋转90°

### ISSUE THREAD

**Issue by DSKcpp** [Bilibili/ijkplayer#3112]
使用了 AVFoundation 在竖屏情况下拍摄的视频，使用 IJKFFMoviePlayerController 播放被旋转90°。
使用 IJKMediaDemo 播放也是同样的问题，视频本身方向是对的，在 web 和本地都是正确的

IJKFFMoviePlayerController 的设置
```Swift
let options = IJKFFOptions.byDefault()
options?.setOptionIntValue(1, forKey: "videotoolbox", of: kIJKFFOptionCategoryPlayer)
options?.setPlayerOptionIntValue(60, forKey: "max-fps")
options?.setPlayerOptionIntValue(0, forKey: "framedrop")
options?.setFormatOptionIntValue(1, forKey: "auto_convert")
```
视频地址 http://ac-mjnLiyS2.clouddn.com/tyVEjWCCX6owBE1ODd8oBbC

![img_1999](https://cloud.githubusercontent.com/assets/10255725/26163471/67973adc-3b5c-11e7-871a-c9b568daf04a.PNG)

**Comment by raymond1012** [comment]
need setoption mediacodec-auto-rotate is 1

**Comment by DSKcpp** [comment]
@raymond1012  mediacodec-auto-rotate is Android only options, iOS not work

**Comment by raymond1012** [comment]
模仿android 自己写个旋转

**Comment by DSKcpp** [comment]
@raymond1012 有相关代码吗？

**Comment by raymond1012** [comment]
see FFP_MSG_VIDEO_ROTATION_CHANGED

2017-05-18 13:55 GMT+08:00 Peter Chi <notifications@github.com>:

**Comment by sealband** [comment]
@DSKcpp  有找到解决方案吗

**Comment by Echo-Joker** [comment]
找到解决方法了吗

**Comment by czeludzki** [comment]
@DSKcpp 后来怎么解决的?

**Comment by smalldu** [comment]
同求解决方案！！！

**Comment by czeludzki** [comment]
@smalldu 可以去看看我的代码库里对 ijkplayer 的 fork
https://github.com/czeludzki/ijkplayer
