### ISSUE TITLE
close x264 decoder sometime tombstone occured

### ISSUE THREAD

**Issue by jiansr** [Bilibili/ijkplayer#3113]
when close a player,IjkMediaPlayer_release() function will be called, and stream_close() will be called indeed.
in function stream_close() ,video decoder will be closed.but sometime tombstone occured. 

05-17 19:32:33.008  8827  8972 D IJKMEDIA: IjkMediaPlayer_release
05-17 19:32:33.008  8827  8972 D IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
05-17 19:32:33.008  8827  8972 D IJKMEDIA: ffpipeline_set_surface()
05-17 19:32:33.008  8827  8972 D IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
05-17 19:32:33.008  8827  8972 D IJKMEDIA: ijkmp_shutdown_l()
05-17 19:32:33.030  8827 15304 E IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xac149340)
05-17 19:32:33.034  8827 15304 E IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xac1c7338)
05-17 19:32:33.036  8827 15304 E IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xac9e2b40)
05-17 19:32:33.038  8827 15304 D IJKMEDIA: ijkmp_shutdown_l()=void

05-17 19:32:33.113   292   292 I DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-17 19:32:33.113   292   292 I DEBUG   : Build fingerprint: 'Android/msm8916_64/msm8916_64:5.0.2/LRX22G/pub802061844:userdebug/release-keys'
05-17 19:32:33.113   292   292 I DEBUG   : Revision: '0'
05-17 19:32:33.113   292   292 I DEBUG   : ABI: 'arm'
05-17 19:32:33.113   292   292 I DEBUG   : pid: 8827, tid: 8972, name: VideoPlay  >>> com.xxxx.video.myplayer<<<
05-17 19:32:33.114   292   292 I DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x64
05-17 19:32:33.121   301   953 D audio_hw_primary: out_set_parameters: enter: usecase(0: deep-buffer-playback) kvpairs: routing=2
05-17 19:32:33.122   301   953 D audio_hw_extn: audio_extn_set_anc_parameters: anc_enabled:0
05-17 19:32:33.143   292   292 I DEBUG   :     r0 abcf2340  r1 ac66c590  r2 00000001  r3 00000064
05-17 19:32:33.143   292   292 I DEBUG   :     r4 ad40e8f0  r5 00000000  r6 00000001  r7 00006f4c
05-17 19:32:33.143   292   292 I DEBUG   :     r8 00006f48  r9 ac66c410  sl ad414f90  fp ad415838
05-17 19:32:33.143   292   292 I DEBUG   :     ip 00000000  sp e1df8300  lr e1ef138b  pc e1eeed52  cpsr 400f0030
05-17 19:32:33.144   292   292 I DEBUG   : 
05-17 19:32:33.144   292   292 I DEBUG   : backtrace:
05-17 19:32:33.144   292   292 I DEBUG   :     #00 pc 00070d52  /data/app/com.xxxx.video.myplayer-1/lib/arm/libijkffmpeg.so
05-17 19:32:33.144   292   292 I DEBUG   :     #01 pc 00073387  /data/app/com.xxxx.video.myplayer-1/lib/arm/libijkffmpeg.so (ff_h264_update_thread_context+424)

**Comment by jiansr** [comment]
both ijkplayer 0.6.1 and ijkplayer 0.7.8 has this problem，ijkplayer 0.7.9 no test!!

**Comment by raymond1012** [comment]
try see libijkffmpeg.so  where lead to crash

**Comment by jiansr** [comment]
zj@zj-VBox:~/develop/bilibili/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/obj/local/armeabi-v7a$ arm-linux-androideabi-objdump -T -R libijkffmpeg.so > 1.sybo
zj@zj-VBox:~/develop/bilibili/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/obj/local/armeabi-v7a$ arm-linux-androideabi-addr2line -C -f -e libijkffmpeg.so 000731de 
ff_h264_update_thread_context
/home/zj/develop/bilibili/ijkplayer-android/android/contrib/ffmpeg-armv7a/libavcodec/h264_slice.c:299
zj@zj-VBox:~/develop/bilibili/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/obj/local/armeabi-v7a$ arm-linux-androideabi-addr2line -C -f -e libijkffmpeg.so 00073386
ff_h264_update_thread_context
/home/zj/develop/bilibili/ijkplayer-android/android/contrib/ffmpeg-armv7a/libavcodec/h264_slice.c:372


this error log is ijkplayer 0.6.1 ijkffmpeg 3.1
000731de is ff_h264_update_thread_context libavcodec/h264_slice.c:299
000731de+424 is  ff_h264_update_thread_context libavcodec/h264_slice.c:372

add libavcodec/h264_slice.c:372 code is
**********************************************
if (h->context_initialized || h1->context_initialized) {
	if ((err = h264_slice_header_init(h)) < 0) {
		av_log(h->avctx, AV_LOG_ERROR, "h264_slice_header_init() failed");
		return err;
	}
}
***************************************************
it seems that h264_slice_header_init() is crash line

**Comment by jiansr** [comment]
tombstone has been fixed!!

1、	h264_slice.c				0xf8
	h264_slice_header_init()----> ff_set_sar(h->avctx, sps->sar)
	*********before-it-add*****************
	if(!sps)goto fail;
	
2、	h264_picture.c	0x64
	ff_h264_ref_picture()----> av_assert0(!dst->f->buf[0])
	*********before-it-add*****************	
	if(!dst || !dst->f)goto fail;
	
3,	h264.c 0x54b0
	ff_h264_alloc_tables()----> h->slice_ctx[0].intra4x4_pred_mode = h->intra4x4_pred_mode
	*********before-it-add*****************
	if(!h->slice_ctx)goto fail;
	
4,	libavcodec/utils.c		0x000de601
	ff_thread_ref_frame()----> av_assert0(!dst->progress)
	*********before-it-add*****************
	if(dst->progress)return -1;
