### ISSUE TITLE
目前ijkplayer支持mips和mips64的机型吗 

### ISSUE THREAD

**Issue by li504799868** [Bilibili/ijkplayer#3124]
目前ijkplayer支持mips和mips64的机型吗，如果支持，我该往这两个文件夹拷贝哪些so库呢

**Comment by raymond1012** [comment]
don't support

2017-05-22 10:05 GMT+08:00 li504799868 <notifications@github.com>:

**Comment by li504799868** [comment]
OK  3Q

**Comment by li504799868** [comment]
现在这两种手机在市场的占有率高吗
