### ISSUE TITLE
关于要怎么使用so包的问题

### ISSUE THREAD

**Issue by li504799868** [Bilibili/ijkplayer#3130]
编译结束之后会出现5种 so库， 如果要是全部拿过来的话，apk的大小就会突然增大很多 ，所以我 想请教一下，至少拷贝那几种就可以适配所有的机型，我看bilibili里面是只有armeabi-v7a 和 x86的。

**Comment by raymond1012** [comment]
armeabi-v7a 和 x86 可以覆盖市面上绝大部分机型
