### ISSUE TITLE
android 使用硬解码

### ISSUE THREAD

**Issue by PengBoShi** [Bilibili/ijkplayer#3132]
在mediacodec.c文件中
class_id = class_J4AC_android_media_MediaCodec.id;
    name     = "getInputBuffers";
    sign     = "()[Ljava/nio/ByteBuffer;";
    class_J4AC_android_media_MediaCodec.method_getInputBuffers = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_android_media_MediaCodec.method_getInputBuffers == NULL)
        goto fail;

这个方法中，sign="()[Ljava/nio/ByteBuffer;";  这里面的 [ 是做什么用的？误加的？其他的方法没有

**Comment by raymond1012** [comment]
that is format, see https://github.com/Bilibili/jni4android
