### ISSUE TITLE
请问 如何设置支持的视频格式

### ISSUE THREAD

**Issue by yhm** [Bilibili/ijkplayer#3143]
iOS版本，demo播放本地视频，貌似只能播放MP4格式视频，rmvb、mkv都不支持，我记得之前是支持的，为什么现在没法播放了？

**Comment by zhegexiazhi** [comment]
求解

**Comment by 0ct0cat** [comment]
修改ffmpeg的配置，默认rmvb mkv没有打开。不过rmvb应该只能使用软解。

**Comment by wuchiachih** [comment]
Just enabled mkv support by adding the following flags in module-lite.sh:

--enable-muxer=matroska
--enable-muxer=matroska_audio
--enable-demuxer=matroska
