### ISSUE TITLE
ios 播放横屏问题，加急！！谢谢各位大哥

### ISSUE THREAD

**Issue by kaqise** [Bilibili/ijkplayer#3148]
我现在项目中所有界面都不需要横屏，只有播放界面需要横屏，我监听设备横屏通知来修改播放PlayerView的约束和将他横屏，但是这个时候输入设备并没有默认横屏（查询 po [UIScreen mainScreen].bounds.size.width时还是竖屏的值）,我要怎么让设备认为现在已经是横屏了呢？或者大家有什么好的办法让播放页横屏？谢谢大家了~~~~

**Comment by Z-hui** [comment]
我是在- (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window  判断nav的childVc的最后一个是否是playerVC

**Comment by kaqise** [comment]
我这面的横屏都已经解决了，但是在我横屏滑动调节音量的时候  音量的弹出框还是竖着的..这个问题要怎么解决？

**Comment by Z-hui** [comment]
那是你约束又问题吧 难道你旋转屏幕 你是把播放器的view旋转了九十度？？？？我这是变更的约束，旋转以后改一下宽 高
