### ISSUE TITLE
视频比例调整问题。

### ISSUE THREAD

**Issue by asawalker** [Bilibili/ijkplayer#315]
您好，麻烦请假下，视频比例，是否可以调整？例如：   4:3、16:9、根据视频自适应比例  等等。
是否有函数可以调整呢？谢谢

**Comment by bbcallen** [comment]
系统播放器怎样调整，ijkplayer就怎样调整。一般来说，这些API不属于播放器。

**Comment by Android4MediaPlayer** [comment]
是的，你自己操作view就可以做到了

**Comment by walkermi** [comment]
Android版setOnVideoSizeChangedListener调用后，有通知视频的尺寸给应用层，方便应用层调整播放比例。但iOS版没有，出于什么考虑？还是iOS版有更好的调整比例的方案？

**Comment by bbcallen** [comment]
@property(nonatomic) MPMovieScalingMode scalingMode;

**Comment by walkermi** [comment]
这个不如Android版本的方式灵活吧？如果播放端希望显示指定部分的图像，而不是全部显示，不知道具体的视频尺寸，没办法对view做裁剪偏移处理吧？@bbcallen

**Comment by Zard1096** [comment]
具体视频尺寸可以获取到，FF播放器中_videoWidth和_videoHeight即视频真实尺寸,AV播放器你可以通过加载的track来获得。view的偏移，你怎么高兴怎么来。

**Comment by wzw88486969** [comment]
<RelativeLayout
 android:layout_width="280dp"
 android:layout_height="280dp">
 
    <com.tal.media.widget.VideoView
        android:id="@+id/video_view"
        android:layout_width="match_parent"
		android:layout_height="match_parent"
        android:layout_gravity="center" />
    
</RelativeLayout>

这样就可以了
