### ISSUE TITLE
ijkplayer使用ITrackInfo[]得到的音轨顺序是乱的

### ISSUE THREAD

**Issue by lingchen52** [Bilibili/ijkplayer#3152]
我有一个有多个音轨的m3u8直播流，在使用ITrackInfo[]获取音轨信息时，得到的顺序是乱的，里面的音轨信息相同，但只有一个和视频同步，多次进入APK获取的音轨顺序是不同的，导致播放时有时声音正常，有时不正常，怎么解决这个问题？
`final List<Integer> audiotracks = new ArrayList<>(); 
       
mIjkplayerLivePreview.setOnPreparedListener(new IMediaPlayer.OnPreparedListener() {    
        
           @Override  
          
          public void onPrepared(IMediaPlayer mp) {    
            
                    ITrackInfo[] iTrackInfos = mIjkplayerLivePreview.getTrackInfo();  
              
                   for (int i = 0; i < iTrackInfos.length; i++) {     
               
                           Log.d("LivePreviewActivity", "TrackType:" + iTrackInfos[i].getTrackType());   
                
                           Log.d("LivePreviewActivity", "ITrackInfo.MEDIA_TRACK_TYPE_AUDIO:" + ITrackInfo.MEDIA_TRACK_TYPE_AUDIO);      
            
                          if (iTrackInfos[i].getTrackType() == ITrackInfo.MEDIA_TRACK_TYPE_AUDIO) {     
           
                                     Log.d("LivePreviewActivity", iTrackInfos[i].getInfoInline());   
                    
                                     if(iTrackInfos[i].getInfoInline().contains("kb/s")){        
                   
                                                 audiotracks.add(i);            
                
                                                Log.d("LivePreviewActivity", "------------");    
                   
                                    }        
            
                        }   
             
           }      
         
 if (audiotracks.size() > 0) {         
           
          mIjkplayerLivePreview.selectTrack(audiotracks.size() - 1);   
             
}`

**Comment by raymond1012** [comment]
ITrackInfo[] 是依赖于读流中的音视频顺序，由于打开直播流的时间不固定，无法确定顺序，建议新加个字段来标示音频类型
