### ISSUE TITLE
声画不同步 在线MP4 声音慢 画面快

### ISSUE THREAD

**Issue by songhongwang** [Bilibili/ijkplayer#3154]

**Comment by songhongwang** [comment]
问题描述：
播放网络mp4文件，起始1-2秒的视频画面像慢放一样，随后播放正常

解决方法：
 ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "opensles", 0);

请大神指点为什么会这样？

**Comment by raymond1012** [comment]
可能是你设备的opensles的播放速度有问题，导致画面为了同步音频而变慢。opensles设置为0，即使用audiotrack
作为音频输出，这也是android推荐的做法

2017-05-27 18:07 GMT+08:00 song <notifications@github.com>:
