### ISSUE TITLE
Android User-Agent 添加后不能覆盖本身播放器的UA呢

### ISSUE THREAD

**Issue by Mongolian** [Bilibili/ijkplayer#3156]
ijk 0.7.6
设置UA的方式在没代码中的
 setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "User-Agent", entry.getValue());

设置成功后，日志中：
: request: GET /0/cb/17932018-1.mp4?wsTime=1495992488&platform=pc&wsSecret2=bb6f271981f7b167246fd6f3d147f639&oi=1987337182&rate=300 HTTP/1.1
                                            User-Agent: Lavf/57.56.100
                                            Accept: */*
                                            Range: bytes=0-
                                            Connection: close
                                            Host: ws.acgvideo.com
                                            Icy-MetaData: 1
                                            User-Agent:Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

发现有两个同名的User-Agent ,这是为什么呢？ 求大神解答

**Comment by raymond1012** [comment]
use setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "user_agent", "
