### ISSUE TITLE
drain_output_buffer_l函数里对TI decoder有说明但没处理，注释掉了，是否要打开呢？

### ISSUE THREAD

**Issue by Android4MediaPlayer** [Bilibili/ijkplayer#316]
// TI decoder could crash after reconfigure
            // ffp_notify_msg3(ffp, FFP_MSG_VIDEO_SIZE_CHANGED, width, height);
            // opaque->frame_width  = width;
            // opaque->frame_height = height;

**Comment by bbcallen** [comment]
取决于你自己的测试结果，暂时我不打算维护被注释的逻辑，所以我自己不会提交这样的修改。

**Comment by Android4MediaPlayer** [comment]
恩，想知道原由，这样写了代码是之前测试出了问题所以注释？

**Comment by bbcallen** [comment]
Galaxy Nexus 切换 surface 会 crash

**Comment by Android4MediaPlayer** [comment]
不能解决了吗？

**Comment by bbcallen** [comment]
没空解决。

**Comment by Android4MediaPlayer** [comment]
好，我看下我这边有这个机器不，有了我来看下 解决了再说明

**Comment by Android4MediaPlayer** [comment]
@bbcallen 这个机器出厂都是4.0版本，是不支持mediacodec的？是刷机了还是官方升级高版本了
