### ISSUE TITLE
iOS audio streaming latency

### ISSUE THREAD

**Issue by kiwi07** [Bilibili/ijkplayer#3160]
Hello,

in case streaming audio with url like this: https://drive.google.com/uc?export=view&id=0B_XQ1jTz03dVZ0VWSzVTclpGUE0
the player delays about 5-7seconds before starting to play.
How can I start playing without delay?

Please see log in attachment file:

[log.txt](https://github.com/Bilibili/ijkplayer/files/1040332/log.txt)

**Comment by raymond1012** [comment]
i think the audio data is disorder lead to this issue

**Comment by kiwi07** [comment]
Hi Raymond,

Have any idea / ijkplayer options to start playing immediately?
VLC can play that link immediately.
Please help!
