### ISSUE TITLE
Can ijkplayer play the livestream that encode h265 in (iPhone 5/iPad gen3) and below?

### ISSUE THREAD

**Issue by letien91** [Bilibili/ijkplayer#3164]
Hi. Out server is using H265 to encode video. But iPhone5/iPad gen3 isn't supported H265. 
So my question is: Can ijkplayer play the livestream that encode h265 in (iPhone 5/iPad gen3) and below?

Thanks.

**Comment by PengBoShi** [comment]
用FFmpeg应该没问题的吧，你得重新build FFmpeg ，让你的FFmpeg支持H265 我记得默认是不支持的。只是效率怎么样 CPU占用率 解码速度 还得你自己试试。

**Comment by letien91** [comment]
@PengBoShi : Thanks for your support.
So, the resolve is: Open module.sh and add **--enable-decoder = hevc** below **--enable-decoder = h264**. Right?

**Comment by raymond1012** [comment]
use module-lite-hevc.sh
