### ISSUE TITLE
请问支持RTSP和mkv播放需要怎么修改module-default.sh

### ISSUE THREAD

**Issue by qyning** [Bilibili/ijkplayer#3165]
module-lite.sh 开启rtsp和mjpeg可以播放rtsp，有5s延时: 但是不支持mkv播放
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=rtsp"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=rtp"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mjpeg"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=mjpeg"

如果直接使用module-default.sh 能播放mkv，但是不支持播放rtsp，添加或不添加上面的配置都不能播放rtsp，请教怎么同时支持rtsp和mkv播放

**Comment by raymond1012** [comment]
http://www.ffmpeg.org/ffmpeg-protocols.html

**Comment by qyning** [comment]
http://www.ffmpeg.org/ffmpeg-protocols.html
I can not find the relevant content, you can give some tips?
I don't know how to support mkv  change  in  module-lite.sh
