### ISSUE TITLE
seekTo 以后ijkplayer 没有使用已经缓冲的数据，反而重新开始缓冲了？

### ISSUE THREAD

**Issue by songhongwang** [Bilibili/ijkplayer#3166]
看到一种解决办法如下：
Seek request will cause the buffer be flushed.
The option for async will not become effective unless you enable it.

请问一下 怎么设置async 的默认缓冲大小？

**Comment by raymond1012** [comment]
https://www.ffmpeg.org/ffmpeg-protocols.html#async and see async.c

**Comment by songhongwang** [comment]
@raymond1012 
我加了async:URL可是还是没什么效果
对于async.c我应该怎么改，还有就是想知道能不能通过setOption之类的方式禁止清空缓冲区的数据？

**Comment by raymond1012** [comment]
你需要读懂ijk的缓冲机制，然后将默认缓冲方式减少到一个很小的值，同时在async.c中加入缓冲字节数上报，上层使用该缓冲值，目前async
默认是4M，可以自行修改

2017-06-01 14:47 GMT+08:00 song <notifications@github.com>:

**Comment by dcw0505** [comment]
@songhongwang 这个问题解决了吗？我现在也遇到这个问题，不知道怎么处理。。

**Comment by zhangchaojiong** [comment]
@dcw0505  我已经解决了： 请调用 seekto，不要使用下面这行代码去 做 seekto
`  ((IjkMediaPlayer) mMediaPlayer).setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "seek-at-start", curSeekPos);`

**Comment by jeff201903** [comment]
@zhangchaojiong 能具体点吗，怎么调用？谢谢
