### ISSUE TITLE
iOS-我只想播放音乐，不播放画面，ijkplayer有相关的设置吗？

### ISSUE THREAD

**Issue by wanglifeifei** [Bilibili/ijkplayer#3169]

**Comment by HDHunter** [comment]
不使用setHolder（）即可。作为媒体资源，除了解码编码方案不同。其他的，只是策略差异而已，不影响。

**Comment by raymond1012** [comment]
{ "vn",                             "disable video",         OPTION_OFFSET(video_disable),
