### ISSUE TITLE
如何获取缓冲的百分比？I need loading buffer progress but "onBufferingUpdate" could not help which just return playing progress.

### ISSUE THREAD

**Issue by dvlee1024** [Bilibili/ijkplayer#317]
I want to get loading buffer progress, but this methor "onBufferingUpdate" just return video's playing progress to me. Have ijkmedia got a function return loading buffer? 

有其他接口可以获取视频加载时卡顿时的缓冲百分比吗？
```
onBufferingUpdate(IMediaPlayer mp, final int percent)
```
```
switch(msg.what){
       case MEDIA_BUFFERING_UPDATE:
                long bufferPosition = msg.arg1;
                Log.i("sky","============buffer: " + msg.arg1 + " 2:"+msg.arg2);
                if (bufferPosition < 0) {
                    bufferPosition = 0;
                }

                long percent = 0;
                long duration = player.getDuration();
                if (duration > 0) {
                    percent = bufferPosition * 100 / duration;
                }
                if (percent >= 100) {
                    percent = 100;
                }

                // DebugLog.efmt(TAG, "Buffer (%d%%) %d/%d",  percent, bufferPosition, duration);
                player.notifyOnBufferingUpdate((int)percent);
                return;
}
```

**Comment by cikichen** [comment]
mark. same to me

**Comment by Android4MediaPlayer** [comment]
第二个参数就是缓冲百分比的即msg.arg2;

**Comment by dvlee1024** [comment]
@Android4MediaPlayer onBufferingUpdate(IMediaPlayer mp, final int percent)

**Comment by Android4MediaPlayer** [comment]
对的 处理下边界问题

**Comment by bbcallen** [comment]
不要依赖百分比超过100%，即使系统播放器也不保证这一点。
根据 701/702 这一对消息来作处理。

**Comment by Android4MediaPlayer** [comment]
是的，buffering 的图标消失不要取决于这个值而是根据702来，过程中可用这个值做显示。

**Comment by dvlee1024** [comment]
是的，接收到缓冲开始701才显示缓冲数据，接收到缓冲结束702就不显示了

**Comment by Android4MediaPlayer** [comment]
@dvlee1024 还有问题吗

**Comment by dvlee1024** [comment]
问题解决了，谢谢

**Comment by cuiqing168** [comment]
有一些视频没有收到702

**Comment by fanei** [comment]
switch(msg.what){
       case MEDIA_BUFFERING_UPDATE:
                long bufferPosition = msg.arg1;
                Log.i("sky","============buffer: " + msg.arg1 + " 2:"+msg.arg2);
                if (bufferPosition < 0) {
                    bufferPosition = 0;
                }

                long percent = 0;
                long duration = player.getDuration();
                if (duration > 0) {
                    percent = bufferPosition * 100 / duration;
                }
                if (percent >= 100) {
                    percent = 100;
                }

                // DebugLog.efmt(TAG, "Buffer (%d%%) %d/%d",  percent, bufferPosition, duration);
                player.notifyOnBufferingUpdate((int)percent);
                return;
}

请问，这个是在那个监听里处理的呢？监听的哪个呢？ @dvlee1024

**Comment by harlanc** [comment]
mark

**Comment by xx394984678** [comment]
在IjkMediaPlayer类中，handler处理的

**Comment by fantasy525** [comment]
> @dvlee1024 还有问题吗

你好，那个百分比是你当前buffer的位置占总时长的百分比吧？
我需要这样一个百分比，比如我seek到很远一个地方，此时开始loading加载，loading结束后开始播放，我想在loading开始和loading结束开始播放这期间加一个百分比的展示，这样用户知道从开始loading到可以播放中间的进度，我观察你们说的百分比即使视频开始播放了他也在变化，一直到不再缓冲，也就是到达默认的缓冲大小后就不变化了，请问有其他办法拿到我说的数值吗？
