### ISSUE TITLE
出现anr

### ISSUE THREAD

**Issue by engglea** [Bilibili/ijkplayer#3177]
在连接的wifi没有网络的时候，点击播放，然后结束，在reset和release时候出现anr。

**Comment by zhanggao** [comment]
同遇到了，在请求没返回的时候relese会卡。网不好的情况下，在画面没开始播放前release，卡顿发生的概率很高。

**Comment by raymond1012** [comment]
getaddrinfo lead to anr

**Comment by engglea** [comment]
How to solve the problem?

**Comment by AricGuo** [comment]
请问找到解决方式了吗
