### ISSUE TITLE
reset和release时候出现anr

### ISSUE THREAD

**Issue by engglea** [Bilibili/ijkplayer#3179]
如题

**Comment by raymond1012** [comment]
getaddrinfo lead to anr

**Comment by engglea** [comment]
How to solve the problem?

**Comment by raymond1012** [comment]
直接使用ip地址或者建立dns缓存

**Comment by engglea** [comment]
谢谢！试下。

**Comment by zhanggao** [comment]
@raymond1012 请问如何建立dns缓存？安卓系统本身不是会自动缓存dns吗？难道要修改dns缓存策略？
由于cnd给的最终的播放域名可能好几个、ts的域名和m3u8的域名都不一样没发用ip直接访问。

**Comment by raymond1012** [comment]
手动建立映射关系，在tcp层做替换，android的缓存ffmpeg怎么会用，除非你通过自定义接口设下去

在 2017年6月5日 下午2:51，zhanggao <notifications@github.com>写道：

**Comment by zhanggao** [comment]
static void *tcp_getaddrinfo_worker(void *arg)
{
    TCPAddrinfoRequest *req = arg;

    getaddrinfo(req->hostname, req->servname, &req->hints, &req->res);
    pthread_mutex_lock(&req->mutex);
    req->finished = 1;
    pthread_cond_signal(&req->cond);
    pthread_mutex_unlock(&req->mutex);
    av_buffer_unref(&req->buffer);
    return NULL;
}

我发现 ijkplayer 用的 ffmpeg 最终是调用系统的 getaddrinfo 函数进行dns解析的。
这步不会使用到系统的缓存吗？

**Comment by raymond1012** [comment]
getaddrinfo 默认会调用socket的，据我所知, dns缓存要依赖于系统服务其他支持

**Comment by zhanggao** [comment]
你的意思是 getaddrinfo 默认不会缓存以前的结果。
需要自己把 getaddrinfo 得到的 域名->ip 对应关系缓存起来，下次碰到同样的域名就不调用 getaddrinfo？

**Comment by raymond1012** [comment]
据我所知是这样的，但是一般dns服务器上会有映射关系的缓存，这个问题的根本还是getaddrinfo是阻塞的，建议使用
addrinfo_timeout设置超时时间，在ijk_tcp_getaddrinfo_nonblock中实现重试

2017-06-05 18:45 GMT+08:00 zhanggao <notifications@github.com>:

**Comment by engglea** [comment]
今天的一个测试结果，可以在播放之前dns解析，然后将ip地址在设置。设置timeout，可以结束，但是还是会有等待的提示框。

**Comment by raymond1012** [comment]
等待的提示框是什么，anr的提示？

2017-06-05 19:09 GMT+08:00 engglea <notifications@github.com>:

**Comment by engglea** [comment]
对，程序无响应。

**Comment by zhanggao** [comment]
可以把 IjkMediaPlayer.release 方法放子线程调用吗？我放子线程调用没发现什么问题。

**Comment by raymond1012** [comment]
那就要看看，还有哪里导致anr

2017-06-05 19:12 GMT+08:00 engglea <notifications@github.com>:

**Comment by engglea** [comment]
我这放到子线程好像还是有anr，在连接wifi，不能上网的时候。

**Comment by zhanggao** [comment]
今天测试了下，发现 getaddrinfo 这个函数应该是有缓存机制的。
第一次 转某个域名可能耗时比较久，后面调用同一个域名耗时基本可以忽略。

**Comment by raymond1012** [comment]
这个不是getaddrinfo的缓存，而是运营商dns服务器的缓存

2017-06-06 10:33 GMT+08:00 zhanggao <notifications@github.com>:

**Comment by zhanggao** [comment]
设置了addrinfo_timeout 这个函数 ijk_tcp_getaddrinfo_nonblock 还是阻塞的。

**Comment by engglea** [comment]
是阻塞的，还是会有anr。

**Comment by zhanggao** [comment]
我在 ijk_tcp_getaddrinfo_nonblock 这个函数里打印出的timeout的值本来就是大于0的，上层没设置也大于0，而且值还是变化的。

**Comment by engglea** [comment]
我设置这个值了，还是阻塞，出现anr

**Comment by Tipsyume** [comment]
@zhanggao 你是怎么用线程处理 释放 的，我这边使用线程池做IJKMediaPlayer的释放，频繁出现IJKMediaPlayer对象空指针，可否加个QQ：471497524

**Comment by zhaokidd** [comment]
reset和release卡顿的问题有解决方法么.在工作线程中释放播放器资源是会有问题的.

**Comment by zhaokidd** [comment]
没看懂各位的讨论， 释放播放器资源和 dns缓存与关系么

**Comment by Android4MediaPlayer** [comment]
@raymond1012 超时用多久呢

**Comment by raymond1012** [comment]
5秒以内比较合适，另外那段代码有问题，不能实现超时，要稍微改一下

**Comment by Android4MediaPlayer** [comment]
...代码有问题不更新下哈

**Comment by zhanggao** [comment]
@zhaokidd 在建立连接阶段，如果调用了播放器的release，会导致release方法阻塞。
可以将player的释放放在子线程里，得处理好引用的问题。

**Comment by wxjer** [comment]
将dns随便写个值然后播放，退出，基本复现，打算试试子线程处理

**Comment by ranchohxk** [comment]
这个有解决的办法么，设置dns-cache-enable，dns-cache-timeout来处理么

**Comment by zhanggao** [comment]
https://github.com/Bilibili/ijkplayer/issues/3048
