### ISSUE TITLE
当我用demo播放网络mp4的时候，每次开头都会有几秒钟的黑屏时间，这个时间我要如何去监听？

### ISSUE THREAD

**Issue by cikichen** [Bilibili/ijkplayer#318]
我试过setOnBufferingUpdateListener和setOnInfoListener，但是都没调用

**Comment by Android4MediaPlayer** [comment]
请提供片源或地址

**Comment by cikichen** [comment]
http://media.itutu.tv/tfs/L1iIdTBXYT1R4lIVrK.mp4

**Comment by Android4MediaPlayer** [comment]
我觉得正常 先去下载数据 会发给你prepared消息 然后你会start 接着就有有701事件 等

**Comment by cikichen** [comment]
但是我应该监听哪个方法去处理这段黑屏时间呢

**Comment by Android4MediaPlayer** [comment]
onpreparelistener

**Comment by cikichen** [comment]
是的，我目前就是这样写的
            `mVideoView.setOnPreparedListener(new IMediaPlayer.OnPreparedListener() {
                @Override
                public void onPrepared(IMediaPlayer mp) {
                    mp.start();
                }
            });`

**Comment by Catherine0728** [comment]
你解决了么？这个问题

**Comment by Movement123** [comment]
private final IMediaPlayer.OnInfoListener mOnInfoListener = new IMediaPlayer.OnInfoListener() {
        @Override
        public boolean onInfo(IMediaPlayer iMediaPlayer, int status, int extra) {
            if(status == IMediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START){
                //TODO 
            }
            return true;
        }
    };
