### ISSUE TITLE
Problem with error handling * Status Code* android

### ISSUE THREAD

**Issue by 4anas** [Bilibili/ijkplayer#3183]
The status code can be determined when the error occurs!
Example:
When I run the following link on IjkMediaPlayer **http://93.184.221.133/hls-live/20C1A9/bbc_world/ls_satlink/b_828.m3u8**
The following error appears in android monitor:
> 06-03 18:09:21.900 18921-24085/fc.bfiptv E/IJKMEDIA: http://93.184.221.133/hls-live/20C1A9/bbc_world/ls_satlink/b_828.m3u8: Server returned 404 Not Found
06-03 18:09:21.900 18921-19768/fc.bfiptv E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

I need when the error occurs to get the status code to be displayed to the user
```
Like
onError(.....){
TextView.setText("status code"+IjkMediaPlayer .getStatusCode());
}
```
**Any advise on how to do this?**

Thanks!

**Comment by raymond1012** [comment]
this is meaningless. The error number always is -10000

**Comment by 4anas** [comment]
Thank you for your answer. Is there no way to determine the type of error؟
