### ISSUE TITLE
求助 关于重定向

### ISSUE THREAD

**Issue by Caij** [Bilibili/ijkplayer#3184]
url：https://api.youku.com/videos/player/filedata=WcEl1oUuWdTJOakExTnpJd05BPT18MHwxfDEwMDUw

这个连接会重定向到另一个连接 通过浏览器是可以播放的， 但是使用ijk加载出错， 请问需要设置什么东西吗， 没找到相关方面的文档。  谢谢!

**Comment by raymond1012** [comment]
ijk 是支持跳转的，你确认使能了https吗

**Comment by Caij** [comment]
上面那有点问题  下面这个新的url
 https://api.youku.com/videos/player/filedata=WcEl1oUuWdTJOakExTnpJd05BPT18MHwxfDEwMDUw    

https需要自己手动编译吗 我是直接导入你们编译好的。

**Comment by raymond1012** [comment]
search issue about https

**Comment by Caij** [comment]
我发现这个最终的url是一个http的，开始连接是https ， 这个是跨域的问题， 也需要编译https吗  编译ssl 会增加体积。

**Comment by shenmingyang** [comment]
请问你这个问题解决了么 我现在也是从https 重定向到http 也是没法播放的

**Comment by Caij** [comment]
@shenmingyang  使用ijk开启https的就行  你再issue中搜索编译https  应该就能搜索到答案。

**Comment by shenmingyang** [comment]
我已经开启了https  如果我开始使用的是https 重定向的也是https 就是可以播放的  但是重定向到http 就是没法播放的。。很无奈

**Comment by Caij** [comment]
@shenmingyang  我记得我当时试了是有用的  但是体积增加了1M+， 所以我放弃了。  我现在使用的是exoplay

**Comment by shenmingyang** [comment]
好吧  我怎么试都不行 。。不知道是啥问题 头疼

**Comment by shenmingyang** [comment]
你有设置什么参数么

**Comment by Caij** [comment]
不记得了 你可以重新开一个issue  把你的地址放上去  让其他人帮你试试。  我之前的测试项目已经不在了。

**Comment by shenmingyang** [comment]
恩 谢谢
