### ISSUE TITLE
个别m3u8格式视频currentPlaybackTime时间不正确，seekTime会回跳很多

### ISSUE THREAD

**Issue by zhangferry** [Bilibili/ijkplayer#3186]
测试视频：http://m3u8-vod.cn-beijing.aliyuncs.com/cloudvideo/m3u8_route/m3u8TokenRoute.json?sign=ct59353be30cf25b200959bd02&sid=19807861

测试环境：ijkplayer的官方Demo

测试步骤：拖动进度条至视频源中部大约50分钟处，松手currentPlaybackTime变成5分钟。拖动之后的播放最开始几秒视频会有少许音视频的延迟（大概率），之后正常。重复此快进操作当前时间都会回滚，此视频必现，回滚时间不定，基本都是5分钟之内。
测试过慢速拖动，拖动停留一段时间松手均有此问题。

希望各位大大帮助一下！！
补充：

    [options setPlayerOptionIntValue:5 forKey:@"framedrop"];//加此项配置也有问题

**Comment by 0ct0cat** [comment]
这个是seekbar本身的问题，不用拖动方式的seek，用点击的方式seek即可。bbcallen解释过这个问题。

**Comment by zhangferry** [comment]
@raymond1012 @0ct0cat  我感觉不是seekbar的问题，我先是在自己的播放器上遇到的这个问题，然后用ijkDemo测试的。
还有一点补充：我拖动进度条，让视频正常播放，播到6分钟的时候，当前时间变成0分0秒了，但是视频还是接着的，只不过当前时间不正确。后面继续播，基本都是五六分钟当前时间清零，视频本身都是连续的。

感觉是m3u8分段格式问题。另外，我用avplayer播这条视频，当前时间是正确的

**Comment by aasdsjk** [comment]
您好，这个问题有没有什么进展？
