### ISSUE TITLE
界面残留，久久不退

### ISSUE THREAD

**Issue by dvlee1024** [Bilibili/ijkplayer#319]
调用stopPlayback，视频停止，但界面会残留。在没有关闭播放器activity的情况下，再播放一个视频，只有声音，画面仍是残留的画面，需要等很久才恢复正常。急！！

VideoView 现在继承了TextureView，跟这个有关吗？

**Comment by garymabin** [comment]
调查是不是跟TextureView有关，你应该把VideoView去还原成继承SurfaceView，比较结果就知道了；视频的最后一帧残留，可以参考#278在视频停止播放时将Surface置黑

**Comment by dvlee1024** [comment]
@garymabin 换回SurfaceView，效果确实好多了，看来真是换了TextureView导致的问题。残留的图会停留很久，多达几分钟。

因为需要截图功能，换用了TextureView。继续研究，看哪里导致图片卡住残留下来不更新的

**Comment by dvlee1024** [comment]
发现手动gc一下就显示出来了，看来是surface还是什么没释放导致的

**Comment by garymabin** [comment]
@dvlee1024  感觉还是你对VideoView的修改可能有点问题，我这边简单写了个，测试了一下，好像没有残留的问题，具体的可以看看这个gist https://gist.github.com/garymabin/6654faf95f5e45fb88d4,  setVideoLayout()的部分修改可以无视

**Comment by dvlee1024** [comment]
解决了，在ijkmediaplayer添加了释放suface的方法, 在stopPlayback里面调用
``` java
public void releaseDisplay(){
        if(mSurface!=null){
            mSurface.release();
        }
    }
```

**Comment by garymabin** [comment]
感觉还是按照类似处理SurfaceHolder的生命周期一样加上对SurfaceTexure的生命周期的监听比较好。

**Comment by dvlee1024** [comment]
@garymabin 谢谢你的代码，知道要怎么改了

**Comment by Tipsyume** [comment]
@dvlee1024 我这边也遇到这种情况，我是直接 用jikvideoview播放的，延迟大，切换地址有画面残留

**Comment by Tipsyume** [comment]
@dvlee1024 可以加你的企鹅吗，有问题要请教一下你。我的企鹅：471497524

**Comment by Tipsyume** [comment]
@garymabin 你的地址打不开？什么情况
