### ISSUE TITLE
麻烦大神赐教如何调试ijkplayer,ijksdl等c代码

### ISSUE THREAD

**Issue by ibanezsc** [Bilibili/ijkplayer#3190]
在ubuntu下按照README.md说明编译一切正常。想在Android studio调试ijkplayer的c代码却不知道怎么操作，README.md上关于android studio调试说明也只能在k0.6.2版本才可以补丁成功编译成功，其他版本不能正常打补丁。我把ubuntu编译好的工程拉倒Windows上用android studio 导入，无法调试进入c代码，请大神赐教，怎么才能调试。不胜感激。

**Comment by tsingo** [comment]
android studio下C代码以库的形式存在是无法调试c的，IOS下就可以。android 我都是添加打印调试的。

**Comment by ibanezsc** [comment]
谢谢你的答复，和我预想的一样。bbcallen也说过类似的话。
