### ISSUE TITLE
android硬解码 设备如果没有解码芯片

### ISSUE THREAD

**Issue by PengBoShi** [Bilibili/ijkplayer#3194]
如果使用了android硬解码，但是 设备没有解码芯片的话 ijk是怎么处理的。是去走软解码吗 还是有其他处理

**Comment by 0ct0cat** [comment]
没有解码芯片？一般soc都是自带，不需要外挂。
如果不支持mediacodec，默认走软解。

**Comment by teddyla** [comment]
android MediaCodec impl:  if non vendor codec, use android sw codecs.
u could check whether vendor codec is supported by  MediaCodecInfo  parameter "name"
ex:
OMX.qcom.video.decoder.hevc    ->  qcom hevc hw dec.
