### ISSUE TITLE
请问能够直接把数据流给ijkplayer吗？

### ISSUE THREAD

**Issue by 505god** [Bilibili/ijkplayer#3198]
你好，
我现在应用场景是这样的：手机连着u盘，u盘里面的视频文件是没有绝对地址的；

我现在能够读到u盘里面的视频文件的流数据，请问能够直接把流数据给ijkplayer播放吗？

谢谢

**Comment by raymond1012** [comment]
I think you need https://www.ffmpeg.org/ffmpeg-protocols.html#pipe
