### ISSUE TITLE
where is the IJKFormatSegmentConcatContext defined?

### ISSUE THREAD

**Issue by wanzhang** [Bilibili/ijkplayer#320]
I can not find  the IJKFormatSegmentConcatContext  definition.

**Comment by Android4MediaPlayer** [comment]
please go to see concerted.c and avformat.h.

**Comment by wanzhang** [comment]
Yes, I found it in “avformat.h” finally.  It is strange to put a custom API in ffmpeg header file.

**Comment by bbcallen** [comment]
It's a callback structure depended by both modified ffmpeg and ijkplayer.

**Comment by wanzhang** [comment]
I use my own ffmpeg version without ijk-r0.2.4-dev commit.  Thanks all for reply, and I close this issue.
