### ISSUE TITLE
我想问下ijkplayer支持samba协议局域网内视频播放？

### ISSUE THREAD

**Issue by huaxiangyang** [Bilibili/ijkplayer#321]

**Comment by bbcallen** [comment]
Ask FFmpeg.
ijkplayer doesn't support any protocol directly.

**Comment by huaxiangyang** [comment]
What does not directly support any protocol? Is there any good solution?

**Comment by bbcallen** [comment]
Protocols are implemented in FFmpeg,
ijkplayer supports protocols via FFmpeg.

**Comment by huaxiangyang** [comment]
That means the LAN can be achieved through the samba protocol to play the video is not?

**Comment by ctiao** [comment]
enable the protocol you want  via ./configure

**Comment by huaxiangyang** [comment]
How to configure this?

**Comment by ctiao** [comment]
https://github.com/FFmpeg/FFmpeg/blob/master/configure

**Comment by huaxiangyang** [comment]
I do not have the conditions to compile the so file, you who can help me compile, to support the samba protocol.

**Comment by Android4MediaPlayer** [comment]
--enable-libsmbclien

**Comment by Android4MediaPlayer** [comment]
--enable-libsmbclient

**Comment by huaxiangyang** [comment]
There are a lot of support in the model adaptation, you are how to solve?

**Comment by bbcallen** [comment]
If you don't want to compile ffmpeg by yourself, Vitamio would be more suitable for you.
https://www.vitamio.org
Vitamio is much more easier than ijkplayer.

**Comment by pantunes** [comment]
Hello guys,

I'm struggling to make smb work with FFMpeg. I know that this is not FFMpeg repository, but maybe you guys can give me a hint of my issue.

I use your project to compile FFMpeg and I included the following lines in module.sh to compile FFMpeg with smb:
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-libsmbclient"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-gpl"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-version3"

and I get the error from config.log:
(.....)
xcrun -sdk iphoneos clang -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DPIC -arch arm64 -miphoneos-version-min=5.1.1 -std=c99 -fomit-frame-pointer -fPIC -pthread -E -o /var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.VySDu9nU.o /var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.r4paf5Hj.c
/var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.r4paf5Hj.c:1:10: fatal error: 'libsmbclient.h' file not found
#include <libsmbclient.h>
         ^
1 error generated.
ERROR: smbclient not found

I have smbclient installed in my mac, not sure where is the problem.

Thank you in advance!

**Comment by bbcallen** [comment]
You should cross-compile libsmbclient first, and set its include path and lib path via ffmpeg/configure

**Comment by pantunes** [comment]
Hi bbcallen,

Thanks a lot for your feedback.

I think I've managed to fix that error, but now I get some other one related with some missing .h files. I'm stuck now and I've been not able to check something similar online with solution.

Extract of config.log:
(...)
xcrun -sdk iphoneos clang -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -arch arm64 -miphoneos-version-min=5.1.1 -I/Users/pauloantunes/Downloads/__kxsmb-arm64/samba/source3/include -std=c99 -E -o /var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.4IrT6Og6.o /var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.aA67vg8t.c
/var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.aA67vg8t.c:1:10: fatal error: 'features.h' file not found
#include <features.h>
         ^
1 error generated.
check_cpp_condition newlib.h defined _NEWLIB_VERSION
check_cpp
BEGIN /var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.aA67vg8t.c
    1	#include <newlib.h>
    2	#if !(defined _NEWLIB_VERSION)
    3	#error "unsatisfied condition: defined _NEWLIB_VERSION"
    4	#endif
END /var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.aA67vg8t.c
xcrun -sdk iphoneos clang -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -arch arm64 -miphoneos-version-min=5.1.1 -I/Users/pauloantunes/Downloads/__kxsmb-arm64/samba/source3/include -std=c99 -E -o /var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.4IrT6Og6.o /var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.aA67vg8t.c
/var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.aA67vg8t.c:1:10: fatal error: 'newlib.h' file not found
#include <newlib.h>
         ^
1 error generated.
check_cpp_condition _mingw.h defined __MINGW64_VERSION_MAJOR
check_cpp
BEGIN /var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.aA67vg8t.c
    1	#include <_mingw.h>
    2	#if !(defined __MINGW64_VERSION_MAJOR)
    3	#error "unsatisfied condition: defined __MINGW64_VERSION_MAJOR"
    4	#endif
END /var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.aA67vg8t.c
xcrun -sdk iphoneos clang -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -arch arm64 -miphoneos-version-min=5.1.1 -I/Users/pauloantunes/Downloads/__kxsmb-arm64/samba/source3/include -std=c99 -E -o /var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.4IrT6Og6.o /var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.aA67vg8t.c
/var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.aA67vg8t.c:1:10: fatal error: '_mingw.h' file not found
#include <_mingw.h>
         ^
1 error generated.
check_cpp_condition _mingw.h defined __MINGW_VERSION
check_cpp
BEGIN /var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.aA67vg8t.c
    1	#include <_mingw.h>
    2	#if !(defined __MINGW_VERSION)
    3	#error "unsatisfied condition: defined __MINGW_VERSION"
    4	#endif
END /var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.aA67vg8t.c
xcrun -sdk iphoneos clang -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -arch arm64 -miphoneos-version-min=5.1.1 -I/Users/pauloantunes/Downloads/__kxsmb-arm64/samba/source3/include -std=c99 -E -o /var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.4IrT6Og6.o /var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.aA67vg8t.c
/var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.aA67vg8t.c:1:10: fatal error: '_mingw.h' file not found
#include <_mingw.h>
         ^
1 error generated.
check_cpp_condition _mingw.h defined __MINGW32_VERSION
check_cpp
(.....)

This log, https://gist.github.com/stuarts/3824299, is similar to mine (the missing files), even if this user is trying to compile other lib than me (FFMpeg with smb support), what makes me think that should be a path problem? 

Thank you in advance again!

**Comment by pantunes** [comment]
Hello guys!

Just figured out that missing .h were not the issue, but this:
(extraction from config.log)

xcrun -sdk iphoneos clang -arch arm64 -miphoneos-version-min=7.0 -L/Users/pauloantunes/Downloads/__kxsmb-arm64/samba/source3/bin/arm64 -Wl,-dynamic,-search_paths_first -I/opt/local/include -L/opt/local/lib/samba3 -o /var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.w6nHx1JK /var/folders/ln/sq78qzbs0kx4_vgkf5h78bnh0000gn/T//ffconf.zD4Zj8Kg.o -lsmbclient -lm -lbz2 -lz
Undefined symbols for architecture arm64:
  "_CFStringAppendCString", referenced from:
      _macosxfs_encoding_pull in libsmbclient.a(charset_macosxfs.o)
  "_CFStringAppendPascalString", referenced from:
      _macosxfs_encoding_pull in libsmbclient.a(charset_macosxfs.o)
  "_CFStringCreateMutable", referenced from:
      _macosxfs_encoding_pull in libsmbclient.a(charset_macosxfs.o)
  "_CFStringCreateMutableWithExternalCharactersNoCopy", referenced from:
      _macosxfs_encoding_push in libsmbclient.a(charset_macosxfs.o)

I tried to compile different versions of samba and generate all platforms and I always run into these errors for each architecture armv7, amr64. (Undefined symbols for architecture X)

I see in the xrun command that -L is pointing to my samba3 installation and my smbclient compiled libraries. Is it possible that is just checking in my samba3 library folder instead of my compiled samba libraries?

Would be great if you could give me a hint!

Thanks a lot once again!

**Comment by waiwaib** [comment]
@pantunes hi,guys!
I want build ffmpeg contains smbclient on macos ,but get ERROR: smbclient not found,
so,Could you like tell me how do your cross-compile libsmbclient on macos?
thanks~

**Comment by JzwOnly** [comment]
@waiwaib Could you like tell me how do your cross-compile libsmbclient on macOS
Is this problem solved?

**Comment by JzwOnly** [comment]
@pantunes 
same problem, Is this problem solved？
