### ISSUE TITLE
Cannot get IJKMediaFrameworkWithSSL.framework work on Device.

### ISSUE THREAD

**Issue by kiwi07** [Bilibili/ijkplayer#3213]
it seems it cannot load the framework when build on device. if I set IJKMediaFrameworkWithSSL.framework linking is option, not require. It can build but does not play anything.

Please help me fix this.
<img width="1512" alt="screen shot 2017-06-12 at 4 55 49 pm" src="https://user-images.githubusercontent.com/5070135/27028799-287d7f44-4f90-11e7-8691-d78b1d5ada11.png">
<img width="1512" alt="screen shot 2017-06-12 at 4 51 55 pm" src="https://user-images.githubusercontent.com/5070135/27028801-28d165d2-4f90-11e7-9d86-a59e1ee6767f.png">

**Comment by kiwi07** [comment]
I've fixed this.

**Comment by isurukej** [comment]
@kiwi07 
Can you show the step you solved this problem?
I have the same problem here on ios.
