### ISSUE TITLE
iOS怎么扩展rmvb/mkv等格式?

### ISSUE THREAD

**Issue by LXJason** [Bilibili/ijkplayer#3215]
扩展rmvb/mkv格式具体需要改那个文件? 需要加什么代码?
还是直接按照README这句编译即可?
If you prefer more codec/format
cd config
rm module.sh
ln -s module-default.sh module.sh
cd android/contrib
//cd ios
sh compile-ffmpeg.sh clean
恳求大神指导,万分感激!

**Comment by raymond1012** [comment]
search issue
