### ISSUE TITLE
关于./init-ios.sh 克隆时间太长解决方法

### ISSUE THREAD

**Issue by WangYng** [Bilibili/ijkplayer#3226]
打开init-ios.sh 把其中的https://github.com/Bilibili/FFmpeg.git 全部替换成 https://git.oschina.net/wangyng/FFmpeg.git
https://github.com/Bilibili/gas-preprocessor.git 替换成https://git.oschina.net/wangyng/gas-preprocessor.git

这个仓库在深圳.如果你在深圳clone速度可以达10 MiB/s

**Comment by zhanggao** [comment]
用下载软件下载，手动拷到对应目录。
