### ISSUE TITLE
我用Ubuntu编译完三个.so文件后放自己的项目报错

### ISSUE THREAD

**Issue by qiebixuefu12345** [Bilibili/ijkplayer#3230]
运行到IjkMediaPlayer.loadLibrariesOnce(null);这行代码时就抛出:java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.hx.ijkplayer_demo-1/lib/arm/libijksdl.so"

**Comment by YY030913** [comment]
你的是怎么解决的？我在mac编译，所有平台的都生成了，放入自己项目也是报这个错误。

**Comment by befovy** [comment]
@YY030913 具体是什么错呢？ 给一份比较完整的崩溃日志吧


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
