### ISSUE TITLE
0.8.0 版本编译完出现了很明显的丢帧

### ISSUE THREAD

**Issue by li504799868** [Bilibili/ijkplayer#3235]
我之前使用的是0.7.9版本  但是我之前以为默认不支持 m3u8 ,所以就使用了
cd config
rm module.sh
ln -s module-default.sh module.sh
cd android/contrib
# cd ios
sh compile-ffmpeg.sh clean

这次我知道默认是m3u8格式，就没使用上面的代码，但是编译完so包，视频出现了很明显的丢帧，请问我该怎么解决这个问题，还是上面的那段代码的作用是什么？？？

**Comment by li504799868** [comment]
我又测试了一下，发现了一个有规律的事情，我这现在使用的是切片，每一个切片5秒，而丢帧的地方恰巧就是没5秒一次 ，我想问一下这有什么解决办法吗

**Comment by li504799868** [comment]
再补充一下，我发现以前也丢帧，只不过不同的手机可能丢帧的情况不一样，我之前可能并没有注意到，每每次丢帧都是在一个切片的长度，我想问一下这种情况出现的原因是什么，我该怎么解决

**Comment by halfhq** [comment]
确定每个切片的ts是否连续，并且每个切片ts第一帧是否是关键帧
使用ffmpeg命令(可以下载别人编译好的，或者在ubuntu上使用）
ffmpeg  -i hls.m3u8 -c copy -y hls.ts
将你的m3u8文件合并成一个文件，播放看下是否有丢帧情况

**Comment by li504799868** [comment]
不好意思，这么久才回复，我们通过你发的这个命令重新合并视频文件，试了很多播放器，包括ijkplayer都是不丢帧的，那为什么我播放切片的时候丢帧了呢

**Comment by li504799868** [comment]
原因找到了  是因为视频被加密 不同手机的硬件解密速度不同 出现了类似丢帧的卡顿
