### ISSUE TITLE
播放m3u8视频，seek后视频会网回跳，如何解决精确seek这个问题？

### ISSUE THREAD

**Issue by smilence19** [Bilibili/ijkplayer#324]
m3u8 是分段视频， 当我 seek 到 第三段视频的10秒处时，会回跳到第三段视频的0秒开始播放，如何精确seek呢？

**Comment by Android4MediaPlayer** [comment]
M3U8的播放本身就会这样，服务器的分片可以尽量小点

**Comment by smilence19** [comment]
ios系统播放器 和 vlc  是可以精确定位的，应该怎么加这个功能呢

**Comment by Android4MediaPlayer** [comment]
要做肯定可以加，稍微复杂点，在hls协议层加range请求。

**Comment by Android4MediaPlayer** [comment]
@smilence19 你能提供下一个有效的测试地址吗

**Comment by smilence19** [comment]
http://hot.vrs.sohu.com/ipad2457075_4648026007963_5668396.m3u8?plat=17&prod=app 这个地址就可以，我用vlc里面的方式，先获取ts的size，然后根据时长比获取字节实现段内seek，效果不是很好，感觉有点延时，有没有更好的方式呢？

**Comment by bbcallen** [comment]
revert this commit on ffmpeg.
```
commit 255dd6631771e7bdca8124adbf9e2c40ac7c6791
Author: Zhang Rui <bbcallen@gmail.com>
Date:   Mon Oct 27 21:35:43 2014 +0800

    avformat/hls: disable seek within segment
```

**Comment by bbcallen** [comment]
revert this commit on ffmpeg.
```
commit 255dd6631771e7bdca8124adbf9e2c40ac7c6791
Author: Zhang Rui <bbcallen@gmail.com>
Date:   Mon Oct 27 21:35:43 2014 +0800

    avformat/hls: disable seek within segment
```

**Comment by Android4MediaPlayer** [comment]
@smilence19 注释掉在avformat/hls.c的1589行pls->seek_timestamp = AV_NOPTS_VALUE; 就会比较精准位置SEEK，你试一试吧

**Comment by Android4MediaPlayer** [comment]
这个功能我发现还是会有BUG的 你可以debug去完善

**Comment by walkermi** [comment]
@Android4MediaPlayer xcode下debug，貌似只可以step into到ffplay.c的代码中，怎么处理才能跳入到avformat/hls.c中呢？

**Comment by Android4MediaPlayer** [comment]
ffmpeg也要debug模式

**Comment by walkermi** [comment]
@Android4MediaPlayer @bbcallen 
cd ios
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all debug
这样 编译，得到debug模式的库，在xcode打开demo，step into ffplay.c，但是继续step into ffmpeglib还是不行啊！

求指点，打搅了。

**Comment by zhanggao** [comment]
现版本最新的代码 pls->seek_timestamp = AV_NOPTS_VALUE;已经被删掉了，还是没法精准定位。
个别hls资源，没法seek到第一个切片。

**Comment by zhanggao** [comment]
把这句代码 pls->seek_timestamp = AV_NOPTS_VALUE; 加上后，能seek到正确的ts切片。
再加上enable-accurate-seek才能精准seek。
刚理解错了，revert this commit on ffmpeg. 理解成需要舍弃这个提交。

**Comment by yuanjun708** [comment]
@zhanggao  你好 我问题下  pls->seek_timestamp = AV_NOPTS_VALUE 这句加到哪里了
