### ISSUE TITLE
when compile-ffmpeg.sh 

### ISSUE THREAD

**Issue by heitaoflower** [Bilibili/ijkplayer#3240]
Hi, when i try to compile ffmpeg , i encounter this issue, please help me .

$ ./compile-ffmpeg.sh armv7a
====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a arm64 x86 x86_64
FF_ACT_ARCHS = armv7a

====================
[*] check env armv7a
====================
FF_ARCH=armv7a
FF_BUILD_OPT=

--------------------
[*] make NDK standalone toolchain
--------------------
build on CYGWIN_NT-6.3 x86_64
ANDROID_NDK=E:/SDK/android-ndk-r10e
NDKr10e(64-bit) detected
Cygwin temp prefix=E:/SDK/cygwin64/tmp/

--------------------
[*] check ffmpeg env
--------------------

--------------------
[*] configurate ffmpeg
--------------------
/cygdrive/e/GIT/video/ijkplayer/android/contrib/build/ffmpeg-armv7a/toolchain/bin/arm-linux-androideabi-gcc
./configure: line 554: $'aac_adtstoasc_bsf\r=yes': command not found
./configure: line 554: $'chomp_bsf\r=yes': command not found
./configure: line 554: $'dump_extradata_bsf\r=yes': command not found
./configure: line 554: $'dca_core_bsf\r=yes': command not found
./configure: line 554: $'extract_extradata_bsf\r=yes': command not found
./configure: line 554: $'h264_mp4toannexb_bsf\r=yes': command not found
./configure: line 554: $'hevc_mp4toannexb_bsf\r=yes': command not found
./configure: line 554: $'imx_dump_header_bsf\r=yes': command not found
./configure: line 554: $'mjpeg2jpeg_bsf\r=yes': command not found
./configure: line 554: $'mjpega_dump_header_bsf\r=yes': command not found
./configure: line 554: $'mp3_header_decompress_bsf\r=yes': command not found
./configure: line 554: $'mpeg4_unpack_bframes_bsf\r=yes': command not found
./configure: line 554: $'mov2textsub_bsf\r=yes': command not found
./configure: line 554: $'noise_bsf\r=yes': command not found
./configure: line 554: $'remove_extradata_bsf\r=yes': command not found
./configure: line 554: $'text2movsub_bsf\r=yes': command not found
./configure: line 554: $'vp9_superframe_bsf\r=yes': command not found

**Comment by goodcyg** [comment]
ffmpeg配置编译宏参数对吗？仔细检查一下

**Comment by heitaoflower** [comment]
这个问题出现在我用github拉取代码的时候 LR回车设置的与Unix不一致造成的，多谢。

**Comment by whosyourka** [comment]
@heitaoflower Can you tell me how to solve this problem？

**Comment by Heipi** [comment]
Can you tell me how to solve this problem？
