### ISSUE TITLE
No such file libavfilter.a

### ISSUE THREAD

**Issue by heitaoflower** [Bilibili/ijkplayer#3241]
E:\GIT\video\ijkplayer\android\contrib\build\ffmpeg-armv7a\toolchain\bin\arm-linux-androideabi-ranlib.exe: '/e/GIT/video/ijkplayer/android/contrib/build/ffmpeg-armv7a/output/lib/libavfilter.a': No such file
make: *** [library.mak:95: install-libavfilter-static] Error 1

**Comment by goodcyg** [comment]
libavfilter.a路径对吗？应该是路径不对，找不到。

**Comment by heitaoflower** [comment]
问题已经解决了，都是因为GIT拉取的代码 WINDOWS 与 UNIX 的回车 LR不一致造成的。
