### ISSUE TITLE
视频播放过程中视频源设备网络中断没回调

### ISSUE THREAD

**Issue by bingzhao0719** [Bilibili/ijkplayer#3244]
ijk播放视频的过程中（视频源来自另外一台设备），把视频源设备的网络断开，ijk没有走onError，视频源设备的网络断开，这边的视频播放需要做出相应的动作，怎么办？

**Comment by raymond1012** [comment]
断网重连或者做你想要的，在ffmpeg中的io层你可以知道断网

**Comment by WangShuo1143368701** [comment]
@bingzhao0719 ,请问你解决了吗

**Comment by helloworldcm** [comment]
@bingzhao0719 我也遇到了相同的问题 请问你解决了么
