### ISSUE TITLE
iOS-我想用ijkplayer播放音乐，不让再去走解析视频流，和页面的渲染，我该如何设置

### ISSUE THREAD

**Issue by wanglifeifei** [Bilibili/ijkplayer#3249]

**Comment by xiruoruo** [comment]
如何设置呢？

**Comment by yangbo930204** [comment]
> 如何设置呢？

IJKFFOptions *options = [IJKFFOptions optionsByDefault];
// 禁止视频
[options setPlayerOptionIntValue:1 forKey:@"vn"];

**Comment by xiruoruo** [comment]
> > 如何设置呢？
> 
> IJKFFOptions *options = [IJKFFOptions optionsByDefault];
> // 禁止视频
> [options setPlayerOptionIntValue:1 forKey:@"vn"];

谢谢咯~
