### ISSUE TITLE
android: live question

### ISSUE THREAD

**Issue by fengqingyundan** [Bilibili/ijkplayer#325]
Hi,

I use ijkplayer for play live stream on android device, then I got two questions:

1. The play time was lag about 4s, and the lag time increased along playing, such as 4s 6s 10s..., and I follow the issue #264 to disable buffer, but it didn't work, can you give me advise?

2. I got error when play the live stream, the logs are below:

07-10 17:14:31.931  19127-24674/com.bokecc.sdk.mobile.live E/IJKMEDIA﹕ AVC: nal size 56
07-10 17:14:31.931  19127-24674/com.bokecc.sdk.mobile.live E/IJKMEDIA﹕ missing picture in access unit with size 50
07-10 17:14:32.196  19127-24686/com.bokecc.sdk.mobile.live E/IJKMEDIA﹕ AVC: nal size 56
07-10 17:14:32.196  19127-24686/com.bokecc.sdk.mobile.live E/IJKMEDIA﹕ AVC: nal size 56
07-10 17:14:32.196  19127-24686/com.bokecc.sdk.mobile.live E/IJKMEDIA﹕ no frame!
07-10 17:14:32.941  19127-24674/com.bokecc.sdk.mobile.live E/IJKMEDIA﹕ ffp_toggle_buffering: completed: (error=0)
07-10 17:14:32.941  19127-24672/com.bokecc.sdk.mobile.live W/IJKMEDIA﹕ ijkmp_get_msg: FFP_MSG_COMPLETED
07-10 17:14:32.941  19127-24672/com.bokecc.sdk.mobile.live W/IJKMEDIA﹕ FFP_MSG_COMPLETED:
07-10 17:14:33.956  19127-24674/com.bokecc.sdk.mobile.live E/IJKMEDIA﹕ ffp_toggle_buffering: eof

thanks!

**Comment by bbcallen** [comment]
1. No idea on low-latency live stream. If ffplay can't do that, ijkplayer can't do, too.
2. The log shows an EOF.
