### ISSUE TITLE
android：如何修改module.sh的配置，支持本地视频(rmvb/mkv/mp4/mov/avi)文件的播放？

### ISSUE THREAD

**Issue by lifeissobe7utiful** [Bilibili/ijkplayer#3250]
如何修改配置文件module-lite，使ijkplayer支持本地视频(rmvb/mkv/mp4/mov/avi)文件的播放，希望编译的so文件尽可能小

**Comment by raymond1012** [comment]
see https://www.ffmpeg.org/
