### ISSUE TITLE
无法播放本地  m3u8 !有两个问题！

### ISSUE THREAD

**Issue by Quntiao** [Bilibili/ijkplayer#326]
1.本地m3u8只能播放第一段
2.本地m3u8不能seek，会显示 range 错误，本地没有range啊！
m3u8格式如下:

#EXTM3U
#EXT-X-TARGETDURATION:2260.09
#EXT-X-VERSION:3
#EXTINF:194.0
/storage/emulated/0/test/download/1755/1.flv
#EXTINF:180.0
/storage/emulated/0/test/download/1755/2.flv
#EXTINF:180.0
/storage/emulated/0/test/download/1755/3.flv
#EXTINF:209.0
/storage/emulated/0/test/download/1755/4.flv
#EXTINF:198.0
/storage/emulated/0/test/download/1755/5.flv
#EXTINF:210.0
/storage/emulated/0/test/download/1755/6.flv
#EXTINF:180.0
/storage/emulated/0/test/download/1755/7.flv
#EXTINF:180.0
/storage/emulated/0/test/download/1755/8.flv
#EXTINF:180.0
/storage/emulated/0/test/download/1755/9.flv
#EXTINF:180.0
/storage/emulated/0/test/download/1755/10.flv
#EXTINF:190.0
/storage/emulated/0/test/download/1755/11.flv
#EXTINF:180.0
/storage/emulated/0/test/download/1755/12.flv
#EXT-X-ENDLIST

**Comment by bbcallen** [comment]
Log, please.

**Comment by Quntiao** [comment]
=下 我貌似知道，优点问题 .ts是可以的 .flv是不可以的
我正在测试

**Comment by Quntiao** [comment]
07-13 14:18:01.298  31792-31798/com.quntiao.lol E/jdwp﹕ Failed sending reply to debugger: Broken pipe
07-13 14:18:17.918  31792-32104/com.quntiao.lol E/IJKMEDIA﹕ Option http-detect-range-support not found.
07-13 14:18:18.008  31792-32104/com.quntiao.lol E/IJKMEDIA﹕ csd-0[44]: 00000001
07-13 14:18:18.008  31792-32104/com.quntiao.lol E/IJKMEDIA﹕ csd-0[44]: 6764001f
07-13 14:18:18.008  31792-32104/com.quntiao.lol E/IJKMEDIA﹕ csd-0[44]: acc86011
07-13 14:18:18.008  31792-32104/com.quntiao.lol E/IJKMEDIA﹕ csd-0[44]: 413febff
07-13 14:18:18.008  31792-32104/com.quntiao.lol E/IJKMEDIA﹕ csd-0[44]: 04510450
07-13 14:18:18.008  31792-32104/com.quntiao.lol E/IJKMEDIA﹕ csd-0[44]: 10000003
07-13 14:18:18.008  31792-32104/com.quntiao.lol E/IJKMEDIA﹕ csd-0[44]: 00100000
07-13 14:18:18.008  31792-32104/com.quntiao.lol E/IJKMEDIA﹕ csd-0[44]: 030328f1
07-13 14:18:18.008  31792-32104/com.quntiao.lol E/IJKMEDIA﹕ csd-0[44]: 8319e000
07-13 14:18:18.008  31792-32104/com.quntiao.lol E/IJKMEDIA﹕ csd-0[44]: 00000168
07-13 14:18:18.008  31792-32104/com.quntiao.lol E/IJKMEDIA﹕ csd-0[44]: e9bb2c8b
07-13 14:18:18.148  31792-32104/com.quntiao.lol E/OMXMaster﹕ A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
07-13 14:18:18.148  31792-32104/com.quntiao.lol E/OMXNodeInstance﹕ OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
07-13 14:18:18.258  31792-32104/com.quntiao.lol E/IJKMEDIA﹕ configure 0x1d20051a 0x1d20050a
07-13 14:18:30.278  31792-32104/com.quntiao.lol E/IJKMEDIA﹕ Invalid stream index 2

**Comment by Quntiao** [comment]
可以关闭了，发现了 码率不一致！

**Comment by iOSSinger** [comment]
@ghost 请问怎么切片成flv格式的,而不是ts
