### ISSUE TITLE
Building ffmpeg executable

### ISSUE THREAD

**Issue by idanya** [Bilibili/ijkplayer#327]
Trying to get the compilation process to output the ffmpeg executable.
I have commented out these lines:
 #export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-programs"
 #export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-ffmpeg"

seems like there is no effect on the output and I still can't get the executable to build.
Is it possible to get a "small" ffmpeg executable that will link to the shared libraries I am already using (with the ijk wrapper) ?

**Comment by bbcallen** [comment]
Of course, it's possible, but not with ijk wrapper simplely.
ijk build scripts has its own link proccess from .o files,
which is very likely has broken ffmpeg's dependency.

You'd better get familar with original ffmpeg build proccess as a startpoint.

**Comment by happybird1999** [comment]
what os?
