### ISSUE TITLE
如何抓取详情错误日志？

### ISSUE THREAD

**Issue by momoxiaoray** [Bilibili/ijkplayer#3278]
06-28 09:51:10.109 18047-18047/********* E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xbcd7f8c0)
06-28 09:51:10.109 18047-18047/*********E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xbcd7fa40)
06-28 09:51:10.110 18047-18047/********* E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xbcd7fac0)
06-28 09:51:13.495 18047-21708/********* E/IJKMEDIA: Option ijkiomanager not found.
06-28 09:51:13.564 18047-21708/********* E/IJKMEDIA: ffpipenode_create_video_decoder_from_android_mediacodec: MediaCodec: AVC/H264 is disabled. codec_id:28 
06-28 09:51:13.937 18047-18047/********* E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xbcd7f400)
06-28 09:51:13.938 18047-18047/********* E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xbcd7f4c0)
06-28 09:51:13.939 18047-18047/********* E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xbcd7f700)
06-28 09:51:15.742 18047-21782/********* E/IJKMEDIA: error reading header
06-28 09:51:15.743 18047-21782/********* E/IJKMEDIA: http:/**************32/movicpa00005a5423534000000002609?virtualDomain=syhjcms.vod_hpd.zte.com: End of file
06-28 09:51:16.303 18047-21819/********* E/IJKMEDIA: moov atom not found
06-28 09:51:16.303 18047-21819/********* E/IJKMEDIA: http://*************.3gp?rrsip=182.138.52.138&icpid=&accounttype=1&limitflux=-1&limitdur=-1&GuardEncType=2&accountinfo=M9cB4JE7T2mKcHb3bikKmlf6Kdig8x9nHuAhKLLuHe1LZvxQzJI3rdchVDyAcnPxqyzQJjCL1hkAsFn49b%2BTkPOinfu7kiPJ145bGT2gy6EycDbv714qQv%2BZ6TJkXHTf9mUWjfvL3TbI2rct9Qrn0A%3D%3D%3A20170628095118%2C18628291608%2C125.69.141.193%2C20170628095118%2Cprogcpa00005a3854848000000002620%2C1A95199FF69316D3F29548330E68F5D6%2C0%2C1%2C0%2C-1%2C4%2C1%2C123%2C1%2C14695%2C1%2CEND: Invalid data found when processing input

“ Invalid data found when processing input” 有时是服务器鉴权的问题，这个问题要抓取出来给局方反馈，有时也会报404、403的错误，怎么抓取这个详细错误信息呢？

**Comment by raymond1012** [comment]
在http层增加log

**Comment by momoxiaoray** [comment]
thks
