### ISSUE TITLE
how to on/off one filter in playback duration

### ISSUE THREAD

**Issue by fjzboy** [Bilibili/ijkplayer#3279]
i defined one function in ff_ffplay.c file, for danymic turn on/off one filter(loudnorm filter), it can work when i play one audio. but the play position is incorrect(play position is changed to 0)。who can help me to fix it ? 

```
void ffp_enable_loudnorm(FFPlayer* ffp, int enable) 
{
    const char* filter_descr = "loudnorm=I=-18:TP=-1.5:LRA=11:measured_I=-27.2:measured_TP=-14.4:measured_LRA=0.1:measured_thresh=-37.7:offset=-0.7:linear=true:print_format=summary";
    ALOGD("ffp_enable_loudnorm = %d, ffp->afilters=%s", enable, ffp->afilters);

    if (enable)
    {
        ffp->afilters = filter_descr;
    } else {
        ffp->afilters = NULL;
    }
    ffp->af_changed = 1;
    return;
}
```

thank you.

**Comment by fjzboy** [comment]
the pts is changed by loudnorm filter when reconfigure the loudnorm filter.
but i did not where pts is used by the loudnorm filter. so i remove the code of changing frame'pts.
and it work well.

**Comment by JerryIsAgoodBoy** [comment]
@fjzboy hello , do u remove the FFmpeg's code about changing frame's pts?
