### ISSUE TITLE
请问安卓如何获取rtmp流的绝对时间戳和扩展信息

### ISSUE THREAD

**Issue by skybdemq** [Bilibili/ijkplayer#328]
现在想根据当前播放rtmp流的时间与白板做同步，如果采用播放计时的时间同步会不准确的情况，目前考虑的是发送rtmp流时注入个时间戳信息，请问在ijkplayer如何获取

**Comment by bbcallen** [comment]
你用其他播放器如何获取?

**Comment by skybdemq** [comment]
目前没实现获取
