### ISSUE TITLE
解码器和协议注册写的把人看懵了

### ISSUE THREAD

**Issue by goodcyg** [Bilibili/ijkplayer#3280]
void ffp_global_init()
{
    if (g_ffmpeg_global_inited)
        return;

    /* register all codecs, demux and protocols */
    avcodec_register_all();
#if CONFIG_AVDEVICE
    avdevice_register_all();
#endif
#if CONFIG_AVFILTER
    avfilter_register_all();
#endif
    
    av_register_all();

    ijkav_register_all();

    avformat_network_init();

    av_lockmgr_register(lockmgr);
    av_log_set_callback(ffp_log_callback_brief);

    av_init_packet(&flush_pkt);
    flush_pkt.data = (uint8_t*)&flush_pkt;
    //test
    flush_pkt.buf="flush_pkt";

    g_ffmpeg_global_inited = true;

}
void ijkav_register_all(void)
{
    static int initialized;

    if (initialized)
        return;
    initialized = 1;
   

    av_register_all();

    /* protocols */
    av_log(NULL, AV_LOG_INFO, "===== custom modules begin =====\n");
#ifdef __ANDROID__
    IJK_REGISTER_PROTOCOL(ijkmediadatasource);
#endif
    IJK_REGISTER_PROTOCOL(ijkio);
   IJK_REGISTER_PROTOCOL(async);

    IJK_REGISTER_PROTOCOL(ijklongurl);
    IJK_REGISTER_PROTOCOL(ijktcphook);
    IJK_REGISTER_PROTOCOL(ijkhttphook);
    IJK_REGISTER_PROTOCOL(ijksegment);
    /* demuxers */
    IJK_REGISTER_DEMUXER(ijklivehook);
    av_log(NULL, AV_LOG_INFO, "===== custom modules end =====\n");
}

**Comment by goodcyg** [comment]
1.av_register_all();在ffp_global_init和ijkav_register_all分别被注册了两次。这是为啥？
2.av_register_all();已经内部调用了avcodec_register_all(); 还在 这样写不知道目的如何还是bug？
ffp_global_init（）
{
  avcodec_register_all()；
  。。。。。。
  av_register_all()
}

**Comment by raymond1012** [comment]
确实存在重复注册的情况，但是不影响使用，后续会修改

**Comment by jeffasd** [comment]
IJK_REGISTER_PROTOCOL(ijklongurl);
IJK_REGISTER_PROTOCOL(ijktcphook);
IJK_REGISTER_PROTOCOL(ijkhttphook);
IJK_REGISTER_PROTOCOL(ijksegment);
这几个协议对应的函数全部为空函数 是怎么回事？
