### ISSUE TITLE
播放自己服务器的内网视频，播放不了，

### ISSUE THREAD

**Issue by gexing12311** [Bilibili/ijkplayer#3295]
播放自己服务器的内网视频，播放不了，视频地址在我们自己的内网服务器，没有放到外网，但是Androd系统自带的mediaplayer可以播放，为什么呢？
Failed to resolve hostname ysht.km.com: No address associated with hostname

07-04 19:16:34.658 8715-8715/com.km.video E/KmPlayerView: VideoPath : http://ysht.km.com/dianyingimg/catchvideo/video/2.mp4
07-04 19:16:34.659 8715-8715/com.km.video E/KmTextcureView: stopPlay()
07-04 19:16:34.659 8715-8715/com.km.video E/KmTextcureView: prepareMediaPlayer()
07-04 19:16:34.659 8715-8715/com.km.video E/KmTextcureView: create ijk mediaplayer 
07-04 19:16:34.708 8715-8715/com.km.video D/J4A: J4ALoader: OK: 'android.os.Build$VERSION' loaded
07-04 19:16:34.708 8715-8715/com.km.video D/J4A: J4ALoader: OK: 'android.os.Build' loaded
07-04 19:16:34.710 8715-8715/com.km.video D/J4A: J4ALoader: OK: 'java.nio.Buffer' loaded
07-04 19:16:34.710 8715-8715/com.km.video D/J4A: J4ALoader: OK: 'java.nio.ByteBuffer' loaded
07-04 19:16:34.710 8715-8715/com.km.video D/J4A: J4ALoader: OK: 'java.util.ArrayList' loaded
07-04 19:16:34.717 8715-8715/com.km.video I/J4A: API-Level: 21
07-04 19:16:34.717 8715-8715/com.km.video D/J4A: J4ALoader: OK: 'android.media.AudioTrack' loaded
07-04 19:16:34.719 8715-8715/com.km.video D/J4A: J4ALoader: OK: 'android.media.MediaCodec$BufferInfo' loaded
07-04 19:16:34.721 8715-8715/com.km.video D/J4A: J4ALoader: OK: 'android.media.MediaCodec' loaded
07-04 19:16:34.721 8715-8715/com.km.video D/J4A: J4ALoader: OK: 'android.media.MediaFormat' loaded
07-04 19:16:34.721 8715-8715/com.km.video W/J4A: J4ALoader: Ignore: 'android.media.PlaybackParams' need API 21
07-04 19:16:34.722 8715-8715/com.km.video D/J4A: J4ALoader: OK: 'android.os.Bundle' loaded
07-04 19:16:34.722 8715-8715/com.km.video D/J4A: J4ALoader: OK: 'tv.danmaku.ijk.media.player.misc.IMediaDataSource' loaded
07-04 19:16:34.722 8715-8715/com.km.video D/J4A: J4ALoader: OK: 'tv.danmaku.ijk.media.player.misc.IAndroidIO' loaded
07-04 19:16:34.722 8715-8715/com.km.video D/J4A: J4ALoader: OK: 'tv.danmaku.ijk.media.player.IjkMediaPlayer' loaded
07-04 19:16:34.740 8715-8715/com.km.video D/IJKMEDIA: IjkMediaPlayer_native_init
07-04 19:16:34.742 8715-8715/com.km.video D/IJKMEDIA: IjkMediaPlayer_native_setup
07-04 19:16:34.742 8715-8715/com.km.video I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170518--001
07-04 19:16:34.742 8715-8715/com.km.video I/IJKMEDIA: ijk_version_info: k0.8.0
07-04 19:16:34.743 8715-8715/com.km.video D/IJKMEDIA: ffpipeline_create_from_android()
07-04 19:16:34.743 8715-8715/com.km.video D/IJKMEDIA: ijkmp_set_inject_opaque(0x1004de)
07-04 19:16:34.743 8715-8715/com.km.video D/IJKMEDIA: ijkmp_set_inject_opaque()=void
07-04 19:16:34.743 8715-8715/com.km.video D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x1004de)
07-04 19:16:34.746 8715-8715/com.km.video D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
07-04 19:16:34.746 8715-8715/com.km.video D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
07-04 19:16:34.746 8715-8715/com.km.video D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
07-04 19:16:34.746 8715-8715/com.km.video D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
07-04 19:16:34.746 8715-8715/com.km.video D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
07-04 19:16:34.746 8715-8715/com.km.video D/IJKMEDIA: ijkmp_set_android_surface(surface=0xbeaf4070)
07-04 19:16:34.747 8715-8715/com.km.video D/IJKMEDIA: ffpipeline_set_surface()
07-04 19:16:34.747 8715-8715/com.km.video D/IJKMEDIA: ijkmp_set_android_surface(surface=0xbeaf4070)=void
07-04 19:16:34.748 8715-8715/com.km.video W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
07-04 19:16:34.748 8715-8715/com.km.video D/tv.danmaku.ijk.media.player.IjkMediaPlayer: Couldn't open file on client side, trying server side
07-04 19:16:34.748 8715-8715/com.km.video D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
07-04 19:16:34.748 8715-8715/com.km.video D/IJKMEDIA: ijkmp_set_data_source(url="http://ysht.km.com/dianyingimg/catchvideo/video/2.mp4")
07-04 19:16:34.748 8715-8715/com.km.video D/IJKMEDIA: ijkmp_set_data_source(url="http://ysht.km.com/dianyingimg/catchvideo/video/2.mp4")=0
07-04 19:16:34.748 8715-8715/com.km.video D/IJKMEDIA: IjkMediaPlayer_prepareAsync
07-04 19:16:34.748 8715-8715/com.km.video D/IJKMEDIA: ijkmp_prepare_async()
07-04 19:16:34.748 8715-8715/com.km.video I/IJKMEDIA: ===== versions =====
07-04 19:16:34.748 8715-8715/com.km.video I/IJKMEDIA: ijkplayer    : k0.8.0
07-04 19:16:34.748 8715-8715/com.km.video I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170518--001
07-04 19:16:34.748 8715-8715/com.km.video I/IJKMEDIA: libavutil    : 55.58.100
07-04 19:16:34.748 8715-8715/com.km.video I/IJKMEDIA: libavcodec   : 57.89.100
07-04 19:16:34.748 8715-9604/com.km.video I/IJKMEDIA: SDL_RunThread: [9604] ff_msg_loop
07-04 19:16:34.748 8715-9604/com.km.video D/IJKMEDIA: message_loop
07-04 19:16:34.749 8715-8715/com.km.video I/IJKMEDIA: libavformat  : 57.71.100
07-04 19:16:34.750 8715-9604/com.km.video D/IJKMEDIA: FFP_MSG_FLUSH:
07-04 19:16:34.751 8715-8715/com.km.video I/IJKMEDIA: libswscale   : 4.6.100
07-04 19:16:34.751 8715-8715/com.km.video I/IJKMEDIA: libswresample: 2.7.100
07-04 19:16:34.751 8715-8715/com.km.video I/IJKMEDIA: ===== options =====
07-04 19:16:34.751 8715-8715/com.km.video I/IJKMEDIA: format-opts : ijkapplication               = -1211847200
07-04 19:16:34.751 8715-8715/com.km.video I/IJKMEDIA: format-opts : ijkiomanager                 = -1206497168
07-04 19:16:34.751 8715-8715/com.km.video I/IJKMEDIA: ===================
07-04 19:16:34.756 8715-9605/com.km.video I/IJKMEDIA: SDL_RunThread: [9605] ff_vout
07-04 19:16:34.756 8715-8715/com.km.video D/IJKMEDIA: ijkmp_prepare_async()=0
07-04 19:16:34.756 8715-9606/com.km.video I/IJKMEDIA: SDL_RunThread: [9606] ff_read
07-04 19:16:34.756 8715-8715/com.km.video E/KmTextcureView: prepare openVideo() : http://ysht.km.com/dianyingimg/catchvideo/video/2.mp4
07-04 19:16:34.758 8715-9606/com.km.video I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
07-04 19:16:34.823 8715-8715/com.km.video E/DetailsPlayer: OnSuccess
07-04 19:16:35.023 8715-8715/com.km.video E/DetailsPlayer: Refresh UI
07-04 19:16:35.023 8715-8715/com.km.video E/DetailsPlayer: refreshUI() 
07-04 19:16:35.023 8715-8715/com.km.video W/info: stopLoadMore mPullLoading = false
07-04 19:16:35.864 8715-8726/com.km.video I/art: Debugger is no longer active
07-04 19:16:39.834 8715-9606/com.km.video E/IJKMEDIA: Failed to resolve hostname ysht.km.com: No address associated with hostname
07-04 19:16:39.835 8715-9606/com.km.video I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
07-04 19:16:39.835 8715-9606/com.km.video E/IJKMEDIA: http://ysht.km.com/dianyingimg/catchvideo/video/2.mp4: I/O error
07-04 19:16:39.835 8715-9604/com.km.video D/IJKMEDIA: FFP_MSG_ERROR: 0
07-04 19:16:39.840 8715-9606/com.km.video I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [9606]
07-04 19:16:39.845 8715-8715/com.km.video E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
07-04 19:16:39.845 8715-8715/com.km.video E/KmTextcureView: onError()
07-04 19:16:39.849 8715-8715/com.km.video E/KmPlayerView: onError
07-04 19:16:39.851 8715-8715/com.km.video E/KmTextcureView: stopPlayback()
07-04 19:16:39.853 8715-8715/com.km.video D/IJKMEDIA: ijkmp_stop()
07-04 19:16:39.853 8715-9605/com.km.video I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [9605]
07-04 19:16:39.854 8715-8715/com.km.video D/IJKMEDIA: ijkmp_stop()=0
07-04 19:16:39.854 8715-9604/com.km.video D/IJKMEDIA: message_loop exit
07-04 19:16:39.854 8715-9604/com.km.video I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [9604]
07-04 19:16:39.854 8715-8715/com.km.video D/IJKMEDIA: IjkMediaPlayer_reset
07-04 19:16:39.854 8715-8715/com.km.video D/IJKMEDIA: IjkMediaPlayer_release
07-04 19:16:39.854 8715-8715/com.km.video D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
07-04 19:16:39.854 8715-8715/com.km.video D/IJKMEDIA: ffpipeline_set_surface()
07-04 19:16:39.854 8715-8715/com.km.video D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
07-04 19:16:39.854 8715-8715/com.km.video D/IJKMEDIA: ijkmp_shutdown_l()
07-04 19:16:39.858 8715-8715/com.km.video D/IJKMEDIA: ijkmp_shutdown_l()=void
07-04 19:16:39.858 8715-8715/com.km.video D/IJKMEDIA: IjkMediaPlayer_native_setup
07-04 19:16:39.858 8715-8715/com.km.video I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170518--001
07-04 19:16:39.858 8715-8715/com.km.video I/IJKMEDIA: ijk_version_info: k0.8.0
07-04 19:16:39.858 8715-8715/com.km.video D/IJKMEDIA: ffpipeline_create_from_android()
07-04 19:16:39.858 8715-8715/com.km.video D/IJKMEDIA: ijkmp_set_inject_opaque(0x2004e2)
07-04 19:16:39.858 8715-8715/com.km.video D/IJKMEDIA: ijkmp_set_inject_opaque()=void
07-04 19:16:39.858 8715-8715/com.km.video D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x2004e2)
07-04 19:16:39.860 8715-8715/com.km.video D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
07-04 19:16:39.860 8715-8715/com.km.video D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
07-04 19:16:39.860 8715-8715/com.km.video D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
07-04 19:16:39.860 8715-8715/com.km.video D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
07-04 19:16:39.860 8715-8715/com.km.video D/IJKMEDIA: ijkmp_dec_ref(): ref=0
07-04 19:16:39.860 8715-8715/com.km.video D/IJKMEDIA: ijkmp_shutdown_l()
07-04 19:16:39.860 8715-8715/com.km.video D/IJKMEDIA: ijkmp_shutdown_l()=void
07-04 19:16:39.862 8715-8715/com.km.video D/IJKMEDIA: IjkMediaPlayer_release
07-04 19:16:39.862 8715-8715/com.km.video D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
07-04 19:16:39.862 8715-8715/com.km.video D/IJKMEDIA: ffpipeline_set_surface()
07-04 19:16:39.862 8715-8715/com.km.video D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
07-04 19:16:39.862 8715-8715/com.km.video D/IJKMEDIA: ijkmp_shutdown_l()
07-04 19:16:39.862 8715-8715/com.km.video D/IJKMEDIA: ijkmp_shutdown_l()=void
07-04 19:16:39.862 8715-8715/com.km.video D/IJKMEDIA: ijkmp_dec_ref(): ref=0
07-04 19:16:39.862 8715-8715/com.km.video D/IJKMEDIA: ijkmp_shutdown_l()
07-04 19:16:39.862 8715-8715/com.km.video D/IJKMEDIA: ijkmp_shutdown_l()=void

**Comment by raymond1012** [comment]
E/IJKMEDIA: Failed to resolve hostname ysht.km.com: No address associated with hostname
