### ISSUE TITLE
release的ANR导致finalize抛异常TimeoutException

### ISSUE THREAD

**Issue by chenwq-bjtu** [Bilibili/ijkplayer#3297]
![image](https://user-images.githubusercontent.com/22881484/27847704-f1290d1c-6171-11e7-8282-1d7cab955663.png)
release的ANR一直无解的状态下，能不能把这里注释掉？这里释放播放器的用意是什么？
 protected void finalize() throws Throwable {
        super.finalize();
        // fix crash bug of release player timeout
        //native_finalize();
    }

**Comment by raymond1012** [comment]
可以，只要确保每次播放后都能release就行

**Comment by chenwq-bjtu** [comment]
好的，谢谢。这里释放播放器的用意是什么？能给解惑一下吗
