### ISSUE TITLE
播放器报错 mpjni: seekTo: null mp

### ISSUE THREAD

**Issue by wchengyu** [Bilibili/ijkplayer#3300]
java.lang.IllegalStateException: mpjni: seekTo: null mp
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.seekTo(IjkMediaPlayer.java)

**Comment by raymond1012** [comment]
可能是多线程导致release后依然call seekTo，建议        
        try {
            _seekTo(msec);
        } catch (IllegalStateException e) {
            e.printStackTrace();
        }

**Comment by wchengyu** [comment]
还有这个问题也很多，求指点。

java.lang.RuntimeException: Error during attachToGLContext (see logcat for details)
