### ISSUE TITLE
[Android]why minSdkVersion need 21?

### ISSUE THREAD

**Issue by jeffreyxuworld** [Bilibili/ijkplayer#3305]
when complile: 
compile 'tv.danmaku.ijk.media:ijkplayer-arm64:0.8.0'
compile 'tv.danmaku.ijk.media:ijkplayer-x86_64:0.8.0'
both need minSdkVersion = 21
but most of our project's minSdkVersion is not.
why need 21?

**Comment by raymond1012** [comment]
beacause the x86_64 and arm64 only be used after android 5.0

**Comment by JingweiWang** [comment]
Thank you 磊哥
