### ISSUE TITLE
Android暂停再切后台，返回时黑屏

### ISSUE THREAD

**Issue by annidy** [Bilibili/ijkplayer#3313]
RT

**Comment by chinaminiren** [comment]
http://www.jianshu.com/p/278ab2e5ac5b

**Comment by andyjmzheng** [comment]
@chinaminiren 你好。能更详细的说一下吗？按照你的思路我没有解决黑屏的问题

**Comment by cjunopen** [comment]
@Override
 public void onSurfaceTextureAvailable(SurfaceTexture surface, int width, int height) {
                    Log.d(TAG, "onSurfaceTextureAvailable: ");
                    if (mSurfaceTexture != null){
                        textureView.setSurfaceTexture(mSurfaceTexture);
                        if (isPause){
                            isPause = false;
                            ijkMediaPlayer.start();
                        }

                    }else {
                        mSurfaceTexture = surface;
                        mSurface = new Surface(surface);
                        ijkMediaPlayer.setSurface(mSurface);
                    }
                }

@Override
                public boolean onSurfaceTextureDestroyed(SurfaceTexture surface) {
                    //mSurfaceTexture = surface;
                    Log.d(TAG, "onSurfaceTextureDestroyed: ");
                    return false;
                }
