### ISSUE TITLE
播放器能不能设置起播位置？

### ISSUE THREAD

**Issue by crisiscain** [Bilibili/ijkplayer#3318]
大神，我想在start时直接seek到某个地址播放可以做到吗？要怎么做？
在perpareasync函数后调用seekto函数返回-3状态不对，怎么处理？

**Comment by chinaminiren** [comment]
是可以的，有相关api 的

**Comment by crisiscain** [comment]
可以详细一些吗？

**Comment by chinaminiren** [comment]
{ "seek-at-start",                  "set offset of player should be seeked",
        OPTION_OFFSET(seek_at_start),       OPTION_INT64(0, 0, INT_MAX) },

**Comment by crisiscain** [comment]
感谢你的帮助

**Comment by crisiscain** [comment]
所以seek-at-start导致的状态错误？有办法解决吗？

**Comment by xinzhengzhang** [comment]
https://github.com/Bilibili/ijkplayer/pull/3327
