### ISSUE TITLE
播放时候视频模糊的问题》

### ISSUE THREAD

**Issue by JavanEu** [Bilibili/ijkplayer#332]
最近我发现一直录制的视频使用系统播放器的时候内容里面的黑暗部分不会模糊马赛克，但是使用ijk的时候马赛克明显。
http://pan.baidu.com/s/1sjoPJQX 
@bbcallen 
附带的视频尾部的左上角的暗处，ijk播放模糊明显。

**Comment by bbcallen** [comment]
[self setCodecOptionIntValue:IJK_AVDISCARD_DEFAULT forKey:@"skip_loop_filter"];

**Comment by JavanEu** [comment]
@bbcallen  Andoid的版本也有同样的接口吗？
我在源代码里面看到 is_video_high_fps

**Comment by bbcallen** [comment]
mp.setOption(OPT_CATEGORY_CODEC, "skip_loop_filter", 0);

**Comment by JavanEu** [comment]
@bbcallen  skip_loop_filter 这个参数是干嘛的~ 确实有效呢

**Comment by bbcallen** [comment]
$ git grep skip_loop_filter | grep options
libavcodec/options_table.h:{"skip_loop_filter", "skip loop filtering process for the selected frames", OFFSET(skip_loop_filter), AV_OPT_TYPE_INT, {.i64 = AVDISCARD_DEFAULT }, INT_MIN, INT_MAX, V|D, "avdiscard"},

**Comment by phantomgz** [comment]
@bbcallen, Could you help me, which place should add this code, 
[self setCodecOptionIntValue:IJK_AVDISCARD_DEFAULT forKey:@"skip_loop_filter"];
or enable VideoToolbox.

sorry, I'm not family with Ojective-C
