### ISSUE TITLE
能在项目中使用并且进行闭源商业发布吗？

### ISSUE THREAD

**Issue by wsgaowxh** [Bilibili/ijkplayer#3320]
安卓，只在gradle中进行引用，不修改源码，请问可以进行闭源商业发布吗？谢谢

**Comment by raymond1012** [comment]
没有我们已知的法律风险，但是不能作为法律上的保证，建议你咨询你们自己的法务

**Comment by bbcallen** [comment]
AFAIK, Yes, it's safe from ijkplayer's part.
But, IANAL, you should always ask your lawyer for these stuffs before use it in your product.
