### ISSUE TITLE
sound touch 在48000时不起作用

### ISSUE THREAD

**Issue by idoit** [Bilibili/ijkplayer#3321]
soundtouch在48000采样率上，倍速播放不起作用。

**Comment by raymond1012** [comment]
need sample file

**Comment by idoit** [comment]
准确的说是在倍速时，音视频不同步了。

**Comment by raymond1012** [comment]
是音频慢还是视频慢

2017-07-11 16:25 GMT+08:00 邓军 <notifications@github.com>:

**Comment by idoit** [comment]
如果是2倍速，视频慢，音频快，如果是0.5倍速，还是同步的。

**Comment by raymond1012** [comment]
如果是音频达到了正常的2倍速，而视频跟不上，那么就是视频解码能力不行，建议可以打开使能丢帧的option

2017-07-12 8:48 GMT+08:00 邓军 <notifications@github.com>:

**Comment by idoit** [comment]
硬解码开启了在6.0以下机器上不同步，软解码还好。
