### ISSUE TITLE
Detect when the streaming has been paused

### ISSUE THREAD

**Issue by jutikorn** [Bilibili/ijkplayer#3330]
How to detect when streamer paused the video. I can find only the OnCompletionListener which can detect when streamer has stopped there broadcast.

**Comment by raymond1012** [comment]
isPlaying

**Comment by jutikorn** [comment]
@raymond1012 thanks for your reply. Deosn't it has something like a listener or callback to handle when `isPlaying` has been changed?

**Comment by raymond1012** [comment]
you can add FFP_MSG_PLAYBACK_STATE_CHANGED

2017-07-12 13:02 GMT+08:00 jutikorn <notifications@github.com>:
