### ISSUE TITLE
m3u8文件内为.flv  f4v ,无法播放，could not find codec parameters

### ISSUE THREAD

**Issue by KgdFnYpeu** [Bilibili/ijkplayer#3331]
m3u8里分段为.ts则正常可播放
http://pl.feixiong.tv/Admin/Service/plconcat?url=http%3A%2F%2Fv.youku.com%2Fv_show%2Fid_XMjgyODA1OTg4OA%3D%3D.html&source_id=1&sel_type=FLV&stream_type=SD 此为播放地址，为m3u8文件，但是里面分段是flv文件，例：http://k.youku.com/player/getFlvPath/sid/049975222387112deb8f4/st/flv/fileid/030002040059433ECBF3C32F960AD6052FE007-B486-2AB5-F87C-BA5953DEEE0E?k=11a66e03d2fc6888261fc8ad&hd=0&myp=0&ts=395&ctype=12&ev=1&token=0509&oip=1992197172&ep=ciadE06IVMwC5ivYiT8bM3mwfCELXP4J9h%2BFg9JmALshQey8mkuiteuzPfxAYPAfclNyFuv0qaaS%0AakATYYJHoW4Q3T%2FaPPqW9veQ5d8iwZkFZW1DB7jXwVSeRjD4&ccode=0401&duration=394&expire=18000&psid=4b88e9730cba313221d26a3f79e758f0&ups_client_netip=118.190.132.52&ups_ts=1499752223&ups_userid=&utid=H1XrEeDQakcCAXa%2BhDTRYWjC&vid=XMjgyODA1OTg4OA%3D%3D&vkey=A75fbe3cd0a1ea6b74d57e7786ec897d6
 放到浏览器可下载播放，但是用ijk播放时显示**could not find codec parameters** 我试过README中的办法 
**If you prefer more codec/format**
cd config
rm module.sh
ln -s module-default.sh module.sh
cd android/contrib
sh compile-ffmpeg.sh clean
打包后仍不能播放，麻烦看看有什么解决办法，谢谢！版本android

IjkMediaPlayer_setVideoSurface
        D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
        D/IJKMEDIA: ffpipeline_set_surface()
        D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
        07-11 13:44:43.214 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_native_profileBegin
        07-11 13:44:43.214 5676-5676/ W/IJKMEDIA: monstartup already called
        07-11 13:44:43.214 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_native_setup
        07-11 13:44:43.214 5676-5676/ I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170518--001
        07-11 13:44:43.214 5676-5676/ I/IJKMEDIA: ijk_version_info: k0.8.0
        07-11 13:44:43.214 5676-5676/ D/IJKMEDIA: ffpipeline_create_from_android()
        07-11 13:44:43.214 5676-5676/ D/IJKMEDIA: ijkmp_set_inject_opaque(0x20089a)
        07-11 13:44:43.214 5676-5676/ D/IJKMEDIA: ijkmp_set_inject_opaque()=void
        07-11 13:44:43.214 5676-5676/ D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x20089a)
        07-11 13:44:43.215 5676-5676/ D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
        07-11 13:44:43.215 5676-5676/ D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
        07-11 13:44:43.215 5676-5676/ D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
        07-11 13:44:43.215 5676-5676/ D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
        07-11 13:44:43.215 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(3)
        07-11 13:44:43.215 5676-5676/ D/IJKMEDIA: moncleanup
        07-11 13:44:43.215 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_setOptionLong
        07-11 13:44:43.215 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_setOptionLong
        07-11 13:44:43.215 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_setOptionLong
        07-11 13:44:43.215 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_setOptionLong
        07-11 13:44:43.215 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_setOptionLong
        07-11 13:44:43.215 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_setOptionLong
        07-11 13:44:43.215 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_setOptionLong
        07-11 13:44:43.215 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_setOptionLong
        07-11 13:44:43.388 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_reset
        07-11 13:44:43.388 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_release
        07-11 13:44:43.388 5676-5676/ D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
        07-11 13:44:43.388 5676-5676/ D/IJKMEDIA: ffpipeline_set_surface()
        07-11 13:44:43.388 5676-5676/ D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
        07-11 13:44:43.388 5676-5676/ D/IJKMEDIA: ijkmp_shutdown_l()
        07-11 13:44:43.388 5676-5676/ D/IJKMEDIA: wait for read_tid
        07-11 13:44:43.389 5676-11262/ D/IJKMEDIA: message_loop exit
        07-11 13:44:43.389 5676-11262/ I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [11262]
        07-11 13:44:43.389 5676-5676/ D/IJKMEDIA: Statistics: 2533 bytes read, 0 seeks
        07-11 13:44:43.389 5676-5676/ D/IJKMEDIA: wait for video_refresh_tid
        07-11 13:44:43.389 5676-11263/ I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [11263]
        07-11 13:44:43.390 5676-5676/ D/IJKMEDIA: ijkmp_shutdown_l()=void
        07-11 13:44:43.390 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_native_setup
        07-11 13:44:43.390 5676-5676/ I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170518--001
        07-11 13:44:43.390 5676-5676/ I/IJKMEDIA: ijk_version_info: k0.8.0
        07-11 13:44:43.390 5676-5676/ D/IJKMEDIA: ffpipeline_create_from_android()
        07-11 13:44:43.390 5676-5676/ D/IJKMEDIA: ijkmp_set_inject_opaque(0x8ca)
        07-11 13:44:43.390 5676-5676/ D/IJKMEDIA: ijkmp_set_inject_opaque()=void
        07-11 13:44:43.390 5676-5676/ D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x8ca)
        07-11 13:44:43.390 5676-5676/ D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
        07-11 13:44:43.390 5676-5676/ D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
        07-11 13:44:43.390 5676-5676/ D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
        07-11 13:44:43.390 5676-5676/ D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
        07-11 13:44:43.390 5676-5676/ D/IJKMEDIA: ijkmp_dec_ref(): ref=0
        07-11 13:44:43.390 5676-5676/ D/IJKMEDIA: ijkmp_shutdown_l()
        07-11 13:44:43.390 5676-5676/ D/IJKMEDIA: ijkmp_shutdown_l()=void
        07-11 13:44:43.392 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_release
        07-11 13:44:43.392 5676-5676/ D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
        07-11 13:44:43.392 5676-5676/ D/IJKMEDIA: ffpipeline_set_surface()
        07-11 13:44:43.392 5676-5676/ D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
        07-11 13:44:43.392 5676-5676/ D/IJKMEDIA: ijkmp_shutdown_l()
        07-11 13:44:43.392 5676-5676/ D/IJKMEDIA: ijkmp_shutdown_l()=void
        07-11 13:44:43.392 5676-5676/ D/IJKMEDIA: ijkmp_dec_ref(): ref=0
        07-11 13:44:43.392 5676-5676/ D/IJKMEDIA: ijkmp_shutdown_l()
        07-11 13:44:43.392 5676-5676/ D/IJKMEDIA: ijkmp_shutdown_l()=void
        07-11 13:44:43.394 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_native_profileEnd
        07-11 13:44:43.394 5676-5676/ W/IJKMEDIA: moncleanu already called
        07-11 13:44:43.451 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
        07-11 13:44:43.451 5676-5676/ D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffc33120)
        07-11 13:44:43.451 5676-5676/ D/IJKMEDIA: ffpipeline_set_surface()
        07-11 13:44:43.451 5676-5676/ D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffc33120)=void
        07-11 13:44:44.292 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_reset
        07-11 13:44:44.292 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_release
        07-11 13:44:44.292 5676-5676/ D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
        07-11 13:44:44.292 5676-5676/ D/IJKMEDIA: ffpipeline_set_surface()
        07-11 13:44:44.292 5676-5676/ D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
        07-11 13:44:44.292 5676-5676/ D/IJKMEDIA: ijkmp_shutdown_l()
        07-11 13:44:44.292 5676-5676/ D/IJKMEDIA: ijkmp_shutdown_l()=void
        07-11 13:44:44.292 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_native_setup
        07-11 13:44:44.292 5676-5676/ I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170518--001
        07-11 13:44:44.293 5676-5676/ I/IJKMEDIA: ijk_version_info: k0.8.0
        07-11 13:44:44.293 5676-5676/ D/IJKMEDIA: ffpipeline_create_from_android()
        07-11 13:44:44.293 5676-5676/ D/IJKMEDIA: ijkmp_set_inject_opaque(0x100842)
        07-11 13:44:44.293 5676-5676/ D/IJKMEDIA: ijkmp_set_inject_opaque()=void
        07-11 13:44:44.293 5676-5676/ D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x100842)
        07-11 13:44:44.294 5676-5676/ D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
        07-11 13:44:44.294 5676-5676/ D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
        07-11 13:44:44.294 5676-5676/ D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
        07-11 13:44:44.294 5676-5676/ D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
        07-11 13:44:44.294 5676-5676/ D/IJKMEDIA: ijkmp_dec_ref(): ref=0
        07-11 13:44:44.294 5676-5676/ D/IJKMEDIA: ijkmp_shutdown_l()
        07-11 13:44:44.294 5676-5676/ D/IJKMEDIA: ijkmp_shutdown_l()=void
        07-11 13:44:44.296 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
        07-11 13:44:44.296 5676-5676/ D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffc33ab0)
        07-11 13:44:44.296 5676-5676/ D/IJKMEDIA: ffpipeline_set_surface()
        07-11 13:44:44.296 5676-5676/ D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffc33ab0)=void
        07-11 13:44:44.296 5676-5676/ D/tv.danmaku.ijk.media.player.IjkMediaPlayer: Couldn't open file on client side, trying server side
        07-11 13:44:44.296 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_setOption
        07-11 13:44:44.296 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_setOption
        07-11 13:44:44.296 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
        07-11 13:44:44.296 5676-5676/ D/IJKMEDIA: ijkmp_set_data_source(url="http://pl.feixiong.tv/Admin/Service/plconcat?url=http%3A%2F%2Fv.youku.com%2Fv_show%2Fid_XMjgyODA1OTg4OA%3D%3D.html&source_id=1&sel_type=FLV&stream_type=SD")
        07-11 13:44:44.296 5676-5676/ D/IJKMEDIA: ijkmp_set_data_source(url="http://pl.feixiong.tv/Admin/Service/plconcat?url=http%3A%2F%2Fv.youku.com%2Fv_show%2Fid_XMjgyODA1OTg4OA%3D%3D.html&source_id=1&sel_type=FLV&stream_type=SD")=0
        07-11 13:44:44.296 5676-5676/ D/IJKMEDIA: IjkMediaPlayer_prepareAsync
        07-11 13:44:44.296 5676-5676/ D/IJKMEDIA: ijkmp_prepare_async()
        07-11 13:44:44.296 5676-5676/ I/IJKMEDIA: ===== versions =====
        07-11 13:44:44.297 5676-5676/ I/IJKMEDIA: ijkplayer    : k0.8.0
        07-11 13:44:44.297 5676-5676/ I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170518--001
        07-11 13:44:44.297 5676-5676/ I/IJKMEDIA: libavutil    : 55.58.100
        07-11 13:44:44.297 5676-5676/ I/IJKMEDIA: libavcodec   : 57.89.100
        07-11 13:44:44.297 5676-5676/ I/IJKMEDIA: libavformat  : 57.71.100
        07-11 13:44:44.297 5676-5676/ I/IJKMEDIA: libswscale   : 4.6.100
        07-11 13:44:44.297 5676-5676/ I/IJKMEDIA: libswresample: 2.7.100
        07-11 13:44:44.297 5676-5676/ I/IJKMEDIA: ===== options =====
        07-11 13:44:44.297 5676-5676/ I/IJKMEDIA: format-opts : ijkapplication               = -1396464832
        07-11 13:44:44.297 5676-5676/ I/IJKMEDIA: format-opts : ijkiomanager                 = -1396464952
        07-11 13:44:44.297 5676-5676/ I/IJKMEDIA: format-opts : headers                      = User-Agent:Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Mobile/14F89
        07-11 13:44:44.297 5676-5676/ I/IJKMEDIA: format-opts : protocol_whitelist           = async,cache,crypto,file,http,https,ijkhttphook,ijkinject,ijklivehook,ijklongurl,ijksegment,ijktcphook,pipe,rtp,tcp,tls,udp,ijkurlhook,data
        07-11 13:44:44.297 5676-5676/ I/IJKMEDIA: ===================
        07-11 13:44:44.297 5676-11319/ I/IJKMEDIA: SDL_RunThread: [11319] ff_msg_loop
        07-11 13:44:44.297 5676-11319/ D/IJKMEDIA: message_loop
        07-11 13:44:44.298 5676-5676/ D/IJKMEDIA: ijkmp_prepare_async()=0
        07-11 13:44:44.299 5676-11321/ I/IJKMEDIA: SDL_RunThread: [11321] ff_read
        07-11 13:44:44.299 5676-11320/ I/IJKMEDIA: SDL_RunThread: [11320] ff_vout
        07-11 13:44:44.301 5676-11319/ D/IJKMEDIA: FFP_MSG_FLUSH:
        07-11 13:44:44.305 5676-11321/ I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
        07-11 13:44:44.309 5676-11321/ I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
        07-11 13:44:44.343 5676-11321/ I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
        07-11 13:44:44.343 5676-11321/ D/IJKMEDIA: request: GET /Admin/Service/plconcat?url=http%3A%2F%2Fv.youku.com%2Fv_show%2Fid_XMjgyODA1OTg4OA%3D%3D.html&source_id=1&sel_type=FLV&stream_type=SD HTTP/1.1
        User-Agent: Lavf/57.71.100
        Accept: */*
                                                              Range: bytes=0-
                                                              Connection: close
                                                              Host: pl.feixiong.tv
                                                              Icy-MetaData: 1
                                                              User-Agent:Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Mobile/14F89
07-11 13:44:44.446 5676-11321/ W/IJKMEDIA: Unknown content coding: none
07-11 13:44:44.447 5676-11321/ I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
07-11 13:44:44.450 5676-11321/ D/IJKMEDIA: Format hls,applehttp probed with size=2048 and score=100
07-11 13:44:44.450 5676-11321/ I/IJKMEDIA: HLS request for url 'http://k.youku.com/player/getFlvPath/sid/049975184593712e3a1b8/st/flv/fileid/030002040059433ECBF3C32F960AD6052FE007-B486-2AB5-F87C-BA5953DEEE0E?k=4ae49b80fa7dde36282c7f58&hd=0&myp=0&ts=395&ctype=12&ev=1&token=0539&oip=1992197172&ep=ciadE06IV8YE4Crcjz8bMi%2BzdSUHXP4J9h%2BFg9JmALshQey8mkuiteuzPfxAYPAfclNyFuv0qaaS%0AakATYYJHoW4Q3T%2FaPPqW9veQ5d8iwZkFZW1DB7jXwVSeRjP4&ccode=0401&duration=394&expire=18000&psid=e27460ab004ebbd2feaf1e1fc24e7a15&ups_client_netip=118.190.132.52&ups_ts=1499751845&ups_userid=&utid=pVPrEQDV7QcCAXa%2BhDRi1mZa&vid=XMjgyODA1OTg4OA%3D%3D&vkey=A31a8d04df600f7b4e0f8322f393424f4', offset 0, playlist 0
07-11 13:44:44.451 5676-11321/ I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
07-11 13:44:44.456 5676-11321/ I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
07-11 13:44:44.490 5676-11321/ I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
07-11 13:44:44.490 5676-11321/ D/IJKMEDIA: request: GET /player/getFlvPath/sid/049975184593712e3a1b8/st/flv/fileid/030002040059433ECBF3C32F960AD6052FE007-B486-2AB5-F87C-BA5953DEEE0E?k=4ae49b80fa7dde36282c7f58&hd=0&myp=0&ts=395&ctype=12&ev=1&token=0539&oip=1992197172&ep=ciadE06IV8YE4Crcjz8bMi%2BzdSUHXP4J9h%2BFg9JmALshQey8mkuiteuzPfxAYPAfclNyFuv0qaaS%0AakATYYJHoW4Q3T%2FaPPqW9veQ5d8iwZkFZW1DB7jXwVSeRjP4&ccode=0401&duration=394&expire=18000&psid=e27460ab004ebbd2feaf1e1fc24e7a15&ups_client_netip=118.190.132.52&ups_ts=1499751845&ups_userid=&utid=pVPrEQDV7QcCAXa%2BhDRi1mZa&vid=XMjgyODA1OTg4OA%3D%3D&vkey=A31a8d04df600f7b4e0f8322f393424f4 HTTP/1.1
                                                              User-Agent: Lavf/57.71.100
                                                              Accept: */*
        Connection: close
        Host: k.youku.com
        Icy-MetaData: 1
        User-Agent:Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Mobile/14F89
        07-11 13:44:44.527 5676-11321/ I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
        07-11 13:44:44.532 5676-11321/ I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
        07-11 13:44:44.532 5676-11321/ D/IJKMEDIA: request: GET /youku/6573EB5C8D44D845857ACC4028/030002040059433ECBF3C32F960AD6052FE007-B486-2AB5-F87C-BA5953DEEE0E.flv?sid=049975184593712e3a1b8&ctype=12&ccode=0401&duration=394&expire=18000&psid=e27460ab004ebbd2feaf1e1fc24e7a15&ups_client_netip=118.190.132.52&ups_ts=1499751845&ups_userid=&utid=pVPrEQDV7QcCAXa%2BhDRi1mZa&vkey=A31a8d04df600f7b4e0f8322f393424f4&vid=XMjgyODA1OTg4OA%3D%3D HTTP/1.1
        User-Agent: Lavf/57.71.100
        Accept: */*
                                                              Connection: close
                                                              Host: 101.227.210.18
                                                              Icy-MetaData: 1
                                                              User-Agent:Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Mobile/14F89
07-11 13:44:44.558 5676-11321/ I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
07-11 13:44:44.579 5676-11321/ D/IJKMEDIA: Format flv probed with size=2048 and score=100
07-11 13:44:44.583 5676-11321/ E/IJKMEDIA: Option ijkiomanager not found.
07-11 13:44:44.583 5676-11321/ D/IJKMEDIA: Before avformat_find_stream_info() pos: 2533 bytes read:2533 seeks:0 nb_streams:0
07-11 13:44:44.583 5676-11321/ D/IJKMEDIA: Statistics: 37562 bytes read, 0 seeks
07-11 13:44:44.584 5676-11321/ I/IJKMEDIA: No longer receiving playlist 0
07-11 13:44:44.584 5676-11321/ D/IJKMEDIA: After avformat_find_stream_info() pos: 2533 bytes read:2533 seeks:0 frames:0
07-11 13:44:44.584 5676-11321/ W/IJKMEDIA: http://pl.feixiong.tv/Admin/Service/plconcat?url=http%3A%2F%2Fv.youku.com%2Fv_show%2Fid_XMjgyODA1OTg4OA%3D%3D.html&source_id=1&sel_type=FLV&stream_type=SD: could not find codec parameters
07-11 13:44:44.584 5676-11321/ I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [11321]
07-11 13:44:44.584 5676-11319/ D/IJKMEDIA: FFP_MSG_ERROR: 0
07-11 13:44:44.591 5676-5676/ E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by raymond1012** [comment]
invaild flv url

**Comment by KgdFnYpeu** [comment]
@raymond1012 flv url is work,but a minute is change  403,not this problem,thanks

**Comment by Aweigh** [comment]
@KgdFnYpeu 大神,现在也遇到这个问题，请问您是怎么解决的？

**Comment by wwwtete** [comment]
@KgdFnYpeu 请问最后如何解决的？同样在m3u8中使用f4v无法播放？

**Comment by KgdFnYpeu** [comment]
使用.concat协议，和m3u8差不多，也是分段，你可以自己构造试试看，因为现在没做这方面了，祝好运
