### ISSUE TITLE
android版本软解播放性能的问题

### ISSUE THREAD

**Issue by scottguosk** [Bilibili/ijkplayer#334]
@bbcallen 我这里集成了ijkplayer，测试时候发现在某些低端机上（系统版本2.3；4.0；4.1）使用软解音视频会严重不同步，我想问问ijkplayer有没有可以设置丢帧机制的地方？或者说针对这种情况有没有方法可以改善？

**Comment by qazmoon** [comment]
@scottguosk  新版本中有哦。
```C++
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 12);
```

**Comment by scottguosk** [comment]
@qazmoon 这个我用的版本中也有，我也设置了
((IjkMediaPlayer)m_MediaPlayer).setFrameDrop(12);

但还是会有不同步的问题

**Comment by bbcallen** [comment]
多低端的设备？什么SoC？视频格式？分辨率？码率？帧率？

**Comment by scottguosk** [comment]
@bbcallen 比方ZTE N880E这台手机，播放的是一个直播流flv，分辨率是480P，码率是1Mbps左右，帧率在15-20之间，播一会就会明显音画不同步。

我试着把setFrameDrop这个设置的值调大（到40），好像也没有明显改善

**Comment by bbcallen** [comment]
MSM7627A，软解没希望的。

**Comment by scottguosk** [comment]
@bbcallen ok，那对于调整音画同步的接口是setFrameDrop吗？他的参数表示什么意思，方便的话帮忙解释下，谢谢了

**Comment by bbcallen** [comment]
```
    { "framedrop",                      "drop frames when cpu is too slow",
        OPTION_OFFSET(framedrop),       OPTION_INT(0, -1, 120) },
```
