### ISSUE TITLE
hi,can u help me build ijkplayer?

### ISSUE THREAD

**Issue by happybird1999** [Bilibili/ijkplayer#335]
cloned your source code, but i cant build this source code.
so, i hope u can help me build this project, build for android
:)  thank u

**Comment by bbcallen** [comment]
Sorry, I don't have for this.
Post your problem here.

**Comment by avenwu** [comment]
@happybird1999  
Recently I have build the ijkplayer and ffmpeg souce code and succeeded; 
1. make sure your local SDK and and NDK has the same version;
2. you should follow the instructions sequencely;
3. google the error you've got;
4. ask question with detailed information;

**Comment by happybird1999** [comment]
@avenwu 
hello, can u tell me u on which os pass compiled the ijkplayer?
thanks.

**Comment by happybird1999** [comment]
jsz@ubuntu:~/ijkplayer-android/android/contrib$ ./compile-ffmpeg.sh all
====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a x86 arm64
FF_ACT_ARCHS = armv5 armv7a x86

====================
[*] check env armv5
====================
build on Linux x86_64
ANDROID_SDK=/home/jsz/android-sdk-linux
ANDROID_NDK=/home/jsz/android-ndk-r10e
NDKr10e-rc4 (64-bit) detected

--------------------
[*] make NDK standalone toolchain
--------------------
WARNING: The shell running this script isn't bash.  Although we try to avoid bashism in scripts, things can happen.
Copying prebuilt binaries...
Copying sysroot headers and libraries...
Copying c++ runtime headers and libraries...
Copying files to: /home/jsz/ijkplayer-android/android/contrib/build/ffmpeg-armv5/toolchain
Cleaning up...
Done.

--------------------
[*] check ffmpeg env
--------------------

--------------------
[*] configurate ffmpeg
--------------------
/home/jsz/ijkplayer-android/android/contrib/build/ffmpeg-armv5/toolchain/bin//arm-linux-androideabi-gcc
install prefix            /home/jsz/ijkplayer-android/android/contrib/build/ffmpeg-armv5/output
source path               .
C compiler                arm-linux-androideabi-gcc
C library                 bionic
host C compiler           gcc
host C library            glibc
ARCH                      arm (armv5te)
big-endian                no
runtime cpu detection     yes
ARMv5TE enabled           yes
ARMv6 enabled             yes
ARMv6T2 enabled           yes
VFP enabled               yes
NEON enabled              yes
THUMB enabled             no
debug symbols             yes
strip symbols             yes
optimize for size         no
optimizations             yes
static                    yes
shared                    no
postprocessing support    no
new filter support        no
network support           yes
threading support         pthreads
safe bitstream reader     yes
SDL support               no
opencl enabled            no
texi2html enabled         no
perl enabled              yes
pod2man enabled           yes
makeinfo enabled          no
makeinfo supports HTML    no

External libraries:
zlib

Enabled decoders:
aac			h264			mp3on4
aac_latm		mp3			mp3on4float
flv			mp3adu			vp6
h263			mp3adufloat		vp6a
h263i			mp3float		vp6f
h263p

Enabled encoders:

Enabled hwaccels:

Enabled parsers:
aac			h263			mpegaudio
aac_latm		h264

Enabled demuxers:
aac			latm			mp3
concat			live_flv		mpegps
data			loas			mpegts
flv			m4v			mpegvideo
hls			mov

Enabled muxers:
adts			mov			mpegts
latm			mp4

Enabled protocols:
cache			hls			rtmp
concat			http			rtmpt
crypto			httpproxy		subfile
data			icecast			tcp
ffrtmphttp		md5			udp
file			pipe			udplite
ftp

Enabled filters:

Enabled bsfs:
aac_adtstoasc		h264_mp4toannexb	mpeg4_unpack_bframes
chomp			imx_dump_header		noise
dump_extradata		mp3_header_decompress	remove_extradata

Enabled indevs:

Enabled outdevs:

License: LGPL version 2.1 or later
Creating config.mak, config.h, and doc/config.texi...

WARNING: arm-linux-androideabi-pkg-config not found, library detection may fail.

--------------------
[*] compile ffmpeg
--------------------
CC	libavformat/aacdec.o
CC	libavformat/adtsenc.o
CC	libavformat/allformats.o
CC	libavformat/apetag.o
CC	libavformat/avc.o
CC	libavformat/avio.o
CC	libavformat/aviobuf.o
CC	libavformat/cache.o
CC	libavformat/concat.o
CC	libavformat/concatdec.o
CC	libavformat/crypto.o
CC	libavformat/cutils.o
CC	libavformat/data_uri.o
CC	libavformat/dump.o
CC	libavformat/file.o
CC	libavformat/flvdec.o
CC	libavformat/format.o
libavformat/format.c: In function 'av_probe_input_format3':
libavformat/format.c:178:17: warning: assignment discards 'const' qualifier from pointer target type [enabled by default]
         lpd.buf = zerobuffer;
                 ^
CC	libavformat/ftp.o
CC	libavformat/hevc.o
CC	libavformat/hls.o
CC	libavformat/hlsproto.o
CC	libavformat/http.o
CC	libavformat/httpauth.o
CC	libavformat/icecast.o
CC	libavformat/id3v1.o
CC	libavformat/id3v2.o
CC	libavformat/id3v2enc.o
CC	libavformat/img2.o
CC	libavformat/isom.o
CC	libavformat/latmenc.o
CC	libavformat/loasdec.o
CC	libavformat/m4vdec.o
CC	libavformat/md5proto.o
CC	libavformat/metadata.o
CC	libavformat/mov.o
CC	libavformat/mov_chan.o
CC	libavformat/movenc.o
libavformat/movenc.c: In function 'ff_mov_write_packet':
libavformat/movenc.c:4538:1: warning: label 'end' defined but not used [-Wunused-label]
 end:
 ^
libavformat/movenc.c: In function 'mov_flush_fragment':
libavformat/movenc.c:856:8: warning: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Wstrict-overflow]
     if (cluster_idx >= track->entry)
        ^
CC	libavformat/movenchint.o
CC	libavformat/mp3dec.o
CC	libavformat/mpeg.o
CC	libavformat/mpegts.o
CC	libavformat/mpegtsenc.o
CC	libavformat/mpegvideodec.o
CC	libavformat/mux.o
libavformat/mux.c: In function 'init_pts':
libavformat/mux.c:421:13: warning: 'pts' is deprecated (declared at libavformat/avformat.h:866) [-Wdeprecated-declarations]
             frac_init(&st->pts, 0, 0, den);
             ^
libavformat/mux.c: In function 'compute_pkt_fields2':
libavformat/mux.c:505:13: warning: 'pts' is deprecated (declared at libavformat/avformat.h:866) [-Wdeprecated-declarations]
             pkt->pts = st->pts.val;
             ^
libavformat/mux.c:541:5: warning: 'pts' is deprecated (declared at libavformat/avformat.h:866) [-Wdeprecated-declarations]
     st->pts.val = pkt->dts;
     ^
libavformat/mux.c:553:9: warning: 'pts' is deprecated (declared at libavformat/avformat.h:866) [-Wdeprecated-declarations]
         if (frame_size >= 0 && (pkt->size || st->pts.num != st->pts.den >> 1 || st->pts.val)) {
         ^
libavformat/mux.c:553:9: warning: 'pts' is deprecated (declared at libavformat/avformat.h:866) [-Wdeprecated-declarations]
libavformat/mux.c:553:9: warning: 'pts' is deprecated (declared at libavformat/avformat.h:866) [-Wdeprecated-declarations]
libavformat/mux.c:554:13: warning: 'pts' is deprecated (declared at libavformat/avformat.h:866) [-Wdeprecated-declarations]
             frac_add(&st->pts, (int64_t)st->time_base.den * frame_size);
             ^
libavformat/mux.c:558:9: warning: 'pts' is deprecated (declared at libavformat/avformat.h:866) [-Wdeprecated-declarations]
         frac_add(&st->pts, (int64_t)st->time_base.den * st->codec->time_base.num);
         ^
libavformat/mux.c: In function 'ff_write_chained':
libavformat/mux.c:1046:5: warning: 'destruct' is deprecated (declared at ./libavcodec/avcodec.h:1183) [-Wdeprecated-declarations]
     pkt->destruct = local_pkt.destruct;
     ^
libavformat/mux.c:1046:5: warning: 'destruct' is deprecated (declared at ./libavcodec/avcodec.h:1183) [-Wdeprecated-declarations]
CC	libavformat/network.o
libavformat/network.c: In function 'ff_listen_bind':
libavformat/network.c:215:5: error: implicit declaration of function 'closesocket' [-Werror=implicit-function-declaration]
     closesocket(fd);
     ^
cc1: some warnings being treated as errors
common.mak:57: recipe for target 'libavformat/network.o' failed
make: *** [libavformat/network.o] Error 1

my os is ubuntu ,so i shuld next step to build for ijkplayer?

**Comment by avenwu** [comment]
@happybird1999 
I built on OSX 10.10.3

**Comment by bbcallen** [comment]
```
CC libavformat/network.o
libavformat/network.c: In function 'ff_listen_bind':
libavformat/network.c:215:5: error: implicit declaration of function 'closesocket' [-Werror=implicit-function-declaration]
closesocket(fd);
^
cc1: some warnings being treated as errors
common.mak:57: recipe for target 'libavformat/network.o' failed
make: *** [libavformat/network.o] Error 1
```
u should fix this error
