### ISSUE TITLE
iOS k0.8.0 IJK_REGISTER_PROTOCOL 函数体全部为空

### ISSUE THREAD

**Issue by jeffasd** [Bilibili/ijkplayer#3350]
IJK_REGISTER_PROTOCOL(ijkio);
    IJK_REGISTER_PROTOCOL(async);
    IJK_REGISTER_PROTOCOL(ijklongurl);
    IJK_REGISTER_PROTOCOL(ijktcphook);
    IJK_REGISTER_PROTOCOL(ijkhttphook);
    IJK_REGISTER_PROTOCOL(ijksegment);
这些宏定义是注册协议用的，
宏的定义为
#define IJK_REGISTER_PROTOCOL(x)                                        \
    {                                                                   \
        extern URLProtocol ijkimp_ff_##x##_protocol;                        \
        int ijkav_register_##x##_protocol(URLProtocol *protocol, int protocol_size);\
        ijkav_register_##x##_protocol(&ijkimp_ff_##x##_protocol, sizeof(URLProtocol));  \
    }
将上面的所有的宏展开为
ijkav_register_ijkio_protocol(async, size)

ijkav_register_ijkio_protocol
ijkav_register_async_protocol
ijkav_register_ijklongurl_protocol
ijkav_register_ijktcphook_protocol
ijkav_register_ijkhttphook_protocol
ijkav_register_ijksegment_protocol

但是 工程里面没有实现ijkav_register_ijkio_protocol 等一系列函数
此处的宏定义相当于内容为空，最终没有执行注册函数。

且ffurl_register_protocol函数没法正确编译。
真正的注册log为：
===== custom modules begin =====
register demuxer : ijklivehook
===== custom modules end =====

简单说就是这几个宏
IJK_REGISTER_PROTOCOL(ijkio);
    IJK_REGISTER_PROTOCOL(async);
    IJK_REGISTER_PROTOCOL(ijklongurl);
    IJK_REGISTER_PROTOCOL(ijktcphook);
    IJK_REGISTER_PROTOCOL(ijkhttphook);
    IJK_REGISTER_PROTOCOL(ijksegment);
相当于没有写，里面全是空内容

**Comment by jeffasd** [comment]
查看了 ijkavformat/allformats.c发现这个文件最近几个版本经常改动是否无意间把这些协议注册函数给忽略了？

**Comment by raymond1012** [comment]
see ijkutils.c

**Comment by jeffasd** [comment]
iOS k0.8.0 版本 
ijkutils.c 文件就两个函数
void ijk_av_freep(void *arg)
int ijk_av_strstart(const char *str, const char *pfx, const char **ptr)
这个情况正确吗？

**Comment by jeffasd** [comment]
@raymond1012 函数里面没有关于注册的函数

**Comment by jeffasd** [comment]
@raymond1012 麻烦看一下吧，iOS k0.8.0 版本 这个版本协议注册函数内文件都是空的，仔细分析下，就能看出来。

**Comment by jeffasd** [comment]
@raymond1012 您把我这个问题再次打开吧？多谢了

**Comment by jeffasd** [comment]
@raymond1012 
![e7ada730-051b-4311-966c-1c02a5b54423](https://user-images.githubusercontent.com/15375686/28200984-855ba874-68a1-11e7-9c9b-075c91b6e8ac.png)

**Comment by raymond1012** [comment]
search in ffmpeg

2017-07-14 14:34 GMT+08:00 jeffasd <notifications@github.com>:

**Comment by jeffasd** [comment]
@raymond1012 找到了 
![3333](https://user-images.githubusercontent.com/15375686/28201680-b77b73f4-68a4-11e7-92d3-86d1d007325f.png)

**Comment by jeffasd** [comment]
@raymond1012 将上面的代理整理下为：
memcpy(&ff_##x##_protocol, protocol, protocol_size);


    IJK_REGISTER_PROTOCOL(ijkio);
    IJK_REGISTER_PROTOCOL(async);
    IJK_REGISTER_PROTOCOL(ijklongurl);
    IJK_REGISTER_PROTOCOL(ijktcphook);
    IJK_REGISTER_PROTOCOL(ijkhttphook);
    IJK_REGISTER_PROTOCOL(ijksegment);



extern URLProtocol ijkimp_ff_ijkhttphook_protocol;
int ijkav_register_ijkhttphook_protocol(URLProtocol *protocol, int protocol_size);
int ijkav_register_ijkhttphook_protocol(ijkimp_ff_ijkhttphook_protocol, sizeof(URLProtocol));

extern URLProtocol ff_ijkhttphook_protocol;
int ijkav_register_ijkhttphook_protocol(URLProtocol *protocol, int protocol_size);                        \
int ijkav_register_ijkhttphook_protocol(URLProtocol *protocol, int protocol_size)                         \
{                                                                                                   \
    if (protocol_size != sizeof(URLProtocol)) {                                                     \
        av_log(NULL, AV_LOG_ERROR, "ijkav_register_ijkhttphook_protocol: ABI mismatch.\n");               \
        return -1;                                                                                  \
    }                                                                                               \
    memcpy(&ff_ijkhttphook_protocol, protocol, protocol_size);                                            \
    return 0;                                                                                       \
}

//此处代码完成的只是将ijk层定义的URLProtocol 结构体变量赋值给FFmpeg层的URLProtocol 结构体变量，但是此处并没有进行协议注册
我的理解是否正确呢？
可能这就是 在执行了 下面的宏定义后 ijkurlhook.c内的函数没有一个http的回调的原因
    IJK_REGISTER_PROTOCOL(ijkio);
    IJK_REGISTER_PROTOCOL(async);
    IJK_REGISTER_PROTOCOL(ijklongurl);
    IJK_REGISTER_PROTOCOL(ijktcphook);
    IJK_REGISTER_PROTOCOL(ijkhttphook);
    IJK_REGISTER_PROTOCOL(ijksegment);

ijkurlhook.c文件的目录为:
/Users/cdd/Downloads/player/ijkplayer-ios/ijkmedia/ijkplayer/ijkavformat/ijkurlhook.c
我在ijkurlhook.c文件内 将所有的函数全部打上断点 发现没有一个函数被调用。是不是在
ijkutils.c文件内只进行了
memcpy(&ff_ijkhttphook_protocol, protocol, protocol_size); 
而没有真正执行协议注册函数导致的？

**Comment by jeffasd** [comment]
@raymond1012 ?我上面分析的ijkurlhook.c文件没有一个函数回调 分析的是否正确？目前我遇到的问题是
ijkurlhook.c文件内的函数没有一个函数被调用。

**Comment by bhltyou** [comment]
@jeffasd  qq群：534580622 愿意的话加群一起交流

**Comment by bandaoxiatian** [comment]
```
libavformat/protocol_list.c
libavformat/protocols.c
libavformat/avio.c
```
protocol_list.c中的静态数组url_protocols存储hook protocols，avio.c中的url_find_protocol根据名字匹配protocol，
以ijkhttphook为例，https:改成ijkhttphook:https:就走回调了。找了半天：）  @jeffasd
