### ISSUE TITLE
  java.lang.NoClassDefFoundError: tv.danmaku.ijk.media.player.IjkMediaPlayer

### ISSUE THREAD

**Issue by liuhuan2015** [Bilibili/ijkplayer#3351]
在小米5（Android 7.0）手机上面和一个华为手机（Android 6.0）上面正常，但是在一个SAMSUNG手机SM-A7000（Android 4.4.4）上面却报这个错误，在IjkMediaPlayer初始化的时候就报错。这个位置： IjkMediaPlayer.loadLibrariesOnce(null);（此处报错找不到）
IjkMediaPlayer.native_profileBegin("libijkplayer.so");
这个怎么解决，问下~谢谢。

**Comment by minghao8848** [comment]
这个问题您解决了没，我在小米3(Adroid4.4)上也遇到了这个问题

**Comment by minghao8848** [comment]
我是参考这个搞定的，添加MultiDex就好了
http://www.jianshu.com/p/8b4f711da0bb

**Comment by liuhuan2015** [comment]
谢谢谢谢，当时这个问题纠结了我好几天，四处找答案，提了issue没人回答，觉得自己一定是提了一个别人眼中特别简单的一个错误，后来发现确实是打dex包出问题了，那段时间赶项目赶得焦头烂额，就很久没再回来看这个issue了。

**Comment by liuhuan2015** [comment]
项目快速开发，集成了很多第三方的类库依赖

**Comment by liuhuan2015** [comment]
忽然看了下，你是12月份回答的，哈，不过还是很感谢。
