### ISSUE TITLE
How to play audio with no display?

### ISSUE THREAD

**Issue by jpxiong** [Bilibili/ijkplayer#336]

**Comment by bbcallen** [comment]
Try ffp->video_disable.
I didn't test it.

**Comment by jpxiong** [comment]
So there isn't interface on ijkplayer layer, right ?

**Comment by bbcallen** [comment]
No, there isn't, for now.

**Comment by jpxiong** [comment]
I added the following options as following:
```
+       { "display_disable",                    "display_disable: enable",
+        OPTION_OFFSET(display_disable),   OPTION_INT(0, 0, 1) },
+       { "video_disable",                      "video_disable: enable",
+        OPTION_OFFSET(video_disable),   OPTION_INT(0, 0, 1) },
```
I invoked the option like this:
```
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "display_disable", 1);
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "video_disable", 1);
```
I am not sure the OPT_CATEGORY_XXX. It can't work for audio streaming, but audio local file works fine. Did I miss something ? I would debug it. But if you can help me verify the OPT_CATEGORY_XXX, that will be great. Thanks.

**Comment by jpxiong** [comment]
@bbcallen Dear bbcallen, Which OPT_CATEGORY do display_disable and video_disable options belong to ? Could you please tell me? Thanks.

**Comment by bbcallen** [comment]
Every option added to ff_ffplay.c is OPT_CATEGORY_PLAYER.
It's recommened to debug with player logic on iOS with xcode which is more friendly.

**Comment by jpxiong** [comment]
thanks
