### ISSUE TITLE
compile-ffmpeg file error in Mac machine

### ISSUE THREAD

**Issue by lokeshdudhat** [Bilibili/ijkplayer#3366]
./compile-ffmpeg.sh all

====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a arm64 x86 x86_64
FF_ACT_ARCHS = armv5 armv7a arm64 x86 x86_64

====================
[*] check env armv5
====================
FF_ARCH=armv5
FF_BUILD_OPT=

--------------------
[*] make NDK standalone toolchain
--------------------
build on Darwin x86_64
ANDROID_NDK=/Users/apple/Library/Android/sdk/ndk-bundle
IJK_NDK_REL=15.1.4119039
NDKr15.1.4119039 detected
HOST_OS=darwin
HOST_EXE=
HOST_ARCH=x86_64
HOST_TAG=darwin-x86_64
HOST_NUM_CPUS=4
BUILD_NUM_CPUS=8
Auto-config: --arch=arm
ERROR: Failed to create toolchain.

**Help me for this error**

**Comment by weiwei2012start** [comment]
我是cenos7, ANDROID_NDK=/opt/android/ndk/android-ndk-r13b， 也遇到了同样的问题。
Toolchain installed to android/contrib/build/ffmpeg-armv7a/toolchain.
touch: 无法创建"/android/contrib/build/ffmpeg-armv7a/toolchain/touch": 没有那个文件或目录

**Comment by weiwei2012start** [comment]
我把ndk的版本换成 NDK r10e，现在成功了。

**Comment by lokeshdudhat** [comment]
Thanks

**Comment by fukemy** [comment]
how did u solve that @lokeshdudhat ?
