### ISSUE TITLE
iOS里面没有TextureView，请问怎么解决这一问题啊，播放竖着拍摄的视频就会自动旋转了90度，播放横着拍摄的视频时是正常的

### ISSUE THREAD

**Issue by Echo-Joker** [Bilibili/ijkplayer#3368]

**Comment by raymond1012** [comment]
need sample stream

**Comment by Echo-Joker** [comment]
![Uploading 7D23973650A3EBD8FE3C66EC25B945D0.jpg…]()
![Uploading 214C5C15B5F63749DAB18197F9960231.jpg…]()

**Comment by Echo-Joker** [comment]
是本地相册库的视频 IJKMediaDemo 里面选择movie picker 但是工程支持的方向有竖屏，我选择一个竖屏拍摄的视频但是播放的界面是横屏的

**Comment by Echo-Joker** [comment]
![alt text](http://chuantu.biz/t5/141/1500380509x2890174381.jpg)

![alt text](http://chuantu.biz/t5/141/1500380509x2890174381.jpg)

**Comment by Echo-Joker** [comment]
![播放效果](http://chuantu.biz/t5/141/1500380480x2002907554.jpg "播放效果")
![拍摄效果](http://chuantu.biz/t5/141/1500380509x2890174381.jpg  "拍摄效果")

**Comment by Echo-Joker** [comment]
+ (NSUInteger)rotationFromVideoFileWithURL:(NSURL *)url
{
    NSUInteger degress = 0;
    AVAsset *asset = [AVAsset assetWithURL:url];
    NSArray *tracks = [asset tracksWithMediaType:AVMediaTypeVideo];
    if([tracks count] > 0) {
        AVAssetTrack *videoTrack = [tracks objectAtIndex:0];
        CGAffineTransform t = videoTrack.preferredTransform;
        if(t.a == 0 && t.b == 1.0 && t.c == -1.0 && t.d == 0){
            // Portrait
            degress = 90;
        }else if(t.a == 0 && t.b == -1.0 && t.c == 1.0 && t.d == 0){
            // PortraitUpsideDown
            degress = 270;
        }else if(t.a == 1.0 && t.b == 0 && t.c == 0 && t.d == 1.0){
            // LandscapeRight
            degress = 0;
        }else if(t.a == -1.0 && t.b == 0 && t.c == 0 && t.d == -1.0){
            // LandscapeLeft
            degress = 180;
        }
    }
    return degress;
}
获取视频的方向之后 再去旋转视频player的视图
    playerView.transform = CGAffineTransformMakeRotation(M_PI * [IJKPlayer rotationFromVideoFileWithURL:mediaURL.toUrl] / 180.0);
    playerView.frame = self.bounds;

**Comment by liangliang521** [comment]
(NSUInteger)rotationFromVideoFileWithURL:(NSURL *)url
{
NSUInteger degress = 0;
AVAsset *asset = [AVAsset assetWithURL:url];
NSArray *tracks = [asset tracksWithMediaType:AVMediaTypeVideo];
if([tracks count] > 0) {
AVAssetTrack *videoTrack = [tracks objectAtIndex:0];
CGAffineTransform t = videoTrack.preferredTransform;
if(t.a == 0 && t.b == 1.0 && t.c == -1.0 && t.d == 0){
// Portrait
degress = 90;
}else if(t.a == 0 && t.b == -1.0 && t.c == 1.0 && t.d == 0){
// PortraitUpsideDown
degress = 270;
}else if(t.a == 1.0 && t.b == 0 && t.c == 0 && t.d == 1.0){
// LandscapeRight
degress = 0;
}else if(t.a == -1.0 && t.b == 0 && t.c == 0 && t.d == -1.0){
// LandscapeLeft
degress = 180;
}
}
return degress;
}
获取视频的方向之后 再去旋转视频player的视图
playerView.transform = CGAffineTransformMakeRotation(M_PI * [IJKPlayer rotationFromVideoFileWithURL:mediaURL.toUrl] / 180.0);
playerView.frame = self.bounds;

**Comment by dagundejuzi** [comment]
如果是网络视频怎么破？
