### ISSUE TITLE
do you have a plan to support opengl es in android?

### ISSUE THREAD

**Issue by peckjerry** [Bilibili/ijkplayer#338]
ijkplayer display video by nativewindow now,do you have a plan to support opengl es?

**Comment by bbcallen** [comment]
Not, yet, but interesting.

**Comment by Android4MediaPlayer** [comment]
I will try to do this, please black give some idea

**Comment by wanzhang** [comment]
What benifit to replace native window with opengl? I learn that VLC player also use native window to render video.

**Comment by garymabin** [comment]
ffmpeg decode H264 frames to yuv format by default, so use opengles to transfer yuv to rgb data can reduce some caculation on CPU and make more use of GPU.

**Comment by bbcallen** [comment]
BTW: ANativeWindow supports YV12 format directly on some devices, (like Tegra, Qualcomm ), by set player option "overlay-format" to "fcc-yv12".

**Comment by bbcallen** [comment]
Already supported in android.
