### ISSUE TITLE
dlopen failed: library "libijkffmpeg.so" not found

### ISSUE THREAD

**Issue by kivenerwang** [Bilibili/ijkplayer#3385]
使用动态加载 so 库
                System.load(Player.mLibPath + "/libijkffmpeg.so");
                System.load(Player.mLibPath + "/libijkplayer.so");
                System.load(Player.mLibPath + "/libijksdl.so");

报错： 
07-22 15:00:10.748 E/AndroidRuntime(27750): java.lang.UnsatisfiedLinkError: dlopen failed: library "libijkffmpeg.so" not found

查看log ：
07-22 15:00:10.744 W/linker  (27750): /data/data/com.video.player/libs/arm64-v8a/libijkffmpeg.so: unused DT entry: type 0x6ffffffe arg 0x28df0

07-22 15:00:10.744 W/linker  (27750): /data/data/com.video.player/libs/arm64-v8a/libijkffmpeg.so: unused DT entry: type 0x6fffffff arg 0x2

07-22 15:00:10.746 D/GraphicBuffer(27750): unregister, handle(0x7f75792160) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)

07-22 15:00:10.747 D/GraphicBuffer(27750): unregister, handle(0x7f75792a20) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
看样子已经在加载了。后续去加载 sql.so 的时候 报 libijkffmpeg not found  有人碰到过这个问题，有解决方案吗？
[log1.txt](https://github.com/Bilibili/ijkplayer/files/1167175/log1.txt)

**Comment by kivenerwang** [comment]
关于 load 的顺序 我都尝试过， 不会是由 load 的顺序导致的。

**Comment by kivenerwang** [comment]
问题已解决。 so 库能够正常加载

07-22 15:49:17.432 I/player2345(30692): load so success.

07-22 15:49:17.432 D/IJKMEDIA(30692): IjkMediaPlayer_native_init

**Comment by hseury** [comment]
请问你怎么解决的呀，我也遇到了这个问题

**Comment by nsacer** [comment]
你好，请问最终是如何解决的呢？
