### ISSUE TITLE
播放rtsp一直不显示，能帮我看下日志吗

### ISSUE THREAD

**Issue by huangcy3373** [Bilibili/ijkplayer#3386]
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: ===== versions =====
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: ijkplayer    : k0.8.0-5-g0f367e9
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170518--001
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: libavutil    : 55.58.100
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: libavcodec   : 57.89.100
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: libavformat  : 57.71.100
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: libswscale   : 4.6.100
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: libswresample: 2.7.100
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: ===== options =====
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : mediacodec                   = 1
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : mediacodec-auto-rotate       = 0
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : mediacodec-handle-resolution-change = 0
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : opensles                     = 0
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : overlay-format               = 842225234
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : framedrop                    = 1
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : start-on-prepared            = 0
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : packet-buffering             = 0
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : ijkapplication               = 1993508400
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : ijkiomanager                 = 1993508504
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : http-detect-range-support    = 0
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : fflags                       = nobuffer
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : probsize                     = 4096
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : analyzemaxduration           = 100
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : flush_packets                = 1
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : rtsp_transport               = tcp
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: codec-opts  : skip_loop_filter             = 0
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: codec-opts  : skip_frame                   = 8
07-23 14:56:56.199 3472-3472/tv.danmaku.ijk.media.example I/IJKMEDIA: ===================
07-23 14:56:56.209 3472-5552/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [5552] ff_msg_loop
07-23 14:56:56.209 3472-5552/tv.danmaku.ijk.media.example D/IJKMEDIA: message_loop
07-23 14:56:56.209 3472-5552/tv.danmaku.ijk.media.example D/IJKMEDIA: FFP_MSG_FLUSH:
07-23 14:56:56.209 3472-5553/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [5553] ff_vout
07-23 14:56:56.209 3472-3472/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_prepare_async()=0
07-23 14:56:56.209 3472-5554/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [5554] ff_read
07-23 14:56:56.209 3472-5554/tv.danmaku.ijk.media.example W/IJKMEDIA: remove 'timeout' option for rtmp.
07-23 14:56:56.209 3472-5554/tv.danmaku.ijk.media.example D/IJKMEDIA: No default whitelist set
07-23 14:56:56.239 3472-5554/tv.danmaku.ijk.media.example I/IJKMEDIA: SDP:
07-23 14:56:56.239 3472-5554/tv.danmaku.ijk.media.example D/IJKMEDIA: Failed to parse interval end specification ''
07-23 14:56:56.239 3472-5554/tv.danmaku.ijk.media.example D/IJKMEDIA: video codec set to: h264
07-23 14:56:56.239 3472-5554/tv.danmaku.ijk.media.example D/IJKMEDIA: RTP Packetization Mode: 1
07-23 14:56:56.239 3472-5554/tv.danmaku.ijk.media.example D/IJKMEDIA: RTP Profile IDC: 4d Profile IOP: 40 Level: 1e
07-23 14:56:56.239 3472-5554/tv.danmaku.ijk.media.example D/IJKMEDIA: Extradata set to 0x76e65e18 (size: 62)
07-23 14:56:56.429 3472-3472/tv.danmaku.ijk.media.example I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@41ffc908 time:48740658

**Comment by songzhiming** [comment]
@huangcy3373 麻烦问下你怎么处理的

**Comment by huangcy3373** [comment]
@songzhiming 你是什么不能播？

**Comment by songzhiming** [comment]
@huangcy3373 rtmp的  ，然后就一个提示remove 'timeout' option for rtmp.

**Comment by huangcy3373** [comment]
问题一般都是配置文件没改好，其他地方一般不用改，还有可能就是IjkVideoView中setOption可能改下
