### ISSUE TITLE
If enable avfilter , some video (eg. asf and avi) rotated 180 degrees.

### ISSUE THREAD

**Issue by AlanJaver** [Bilibili/ijkplayer#3395]
I found below code in ff_ffplay.c, ffplay_video_thread(void *arg) :

> #if CONFIG_AVFILTER
> ...
> #else
>   ffp_notify_msg2(ffp, FFP_MSG_VIDEO_ROTATION_CHANGED, ffp_get_video_rotate_degrees(ffp));
> #endif

**If I change to:**

> #if  CONFIG_AVFILTER
> ...
> #else
> #endif
> ffp_notify_msg2(ffp, FFP_MSG_VIDEO_ROTATION_CHANGED, ffp_get_video_rotate_degrees(ffp));

**It works well. But I don't know whether this is a good solution?**

**Comment by Android4MediaPlayer** [comment]
Only ffmpeg decoding is applicable

**Comment by AlanJaver** [comment]
@Android4MediaPlayer 
Thanks for reply.

I am not sure whether my modifications is stable. In my testing, it is OK by now. But I'm afraid it will bring some other bugs.
Could you please give me some suggestion?

**Comment by Android4MediaPlayer** [comment]
It is in principle OK.

**Comment by AlanJaver** [comment]
@Android4MediaPlayer OK, thank you.
