### ISSUE TITLE
mediacodec reconfig failed

### ISSUE THREAD

**Issue by Android4MediaPlayer** [Bilibili/ijkplayer#340]
A/ACodec(21255): frameworks/av/media/libstagefright/ACodec.cpp:1360 CHECK(format.eColorFormat == OMX_COLOR_FormatYUV420Planar || format.eColorFormat == OMX_COLOR_FormatYUV420SemiPlanar || format.eColorFormat == OMX_COLOR_FormatCbYCrY || format.eColorFormat == OMX_TI_COLOR_FormatYUV420PackedSemiPlanar || format.eColorFormat == OMX_QCOM_COLOR_FormatYVU420SemiPlanar) failed.

**Comment by bbcallen** [comment]
can't do nothing with this short piece of log.

**Comment by Android4MediaPlayer** [comment]
07-20 15:08:07.212: I/IJKMEDIA(21255): SDL_AMediaCodecJava_dequeueOutputBuffer(1000000)
07-20 15:08:07.212: I/IJKMEDIA(21255): SDL_AMediaCodecJava_dequeueOutputBuffer: buffer ready (11) ====================
07-20 15:08:07.232: D/dalvikvm(449): JIT code cache reset in 4 ms (1048368 bytes 4/0)
07-20 15:08:07.252: I/IJKMEDIA(21255): SDL_AMediaCodecJava_releaseOutputBuffer
07-20 15:08:07.252: I/IJKMEDIA(21255): SDL_AMediaCodecJava_dequeueOutputBuffer(1000000)
07-20 15:08:07.252: I/IJKMEDIA(21255): SDL_AMediaCodecJava_dequeueOutputBuffer: buffer ready (12) ====================
07-20 15:08:07.252: I/IJKMEDIA(21255): SDL_AMediaCodecJava_getInputBuffer
07-20 15:08:07.252: I/IJKMEDIA(21255): SDL_AMediaCodecJava_queueInputBuffer: 2
07-20 15:08:07.252: I/IJKMEDIA(21255): SDL_AMediaCodecJava_dequeueInputBuffer(1000000)
07-20 15:08:07.252: I/IJKMEDIA(21255): SDL_AMediaCodecJava_getInputBuffer
07-20 15:08:07.252: I/IJKMEDIA(21255): SDL_AMediaCodecJava_queueInputBuffer: 1
07-20 15:08:07.252: I/IJKMEDIA(21255): SDL_AMediaCodecJava_dequeueInputBuffer(1000000)
07-20 15:08:07.252: I/IJKMEDIA(21255): SDL_AMediaCodecJava_getInputBuffer
07-20 15:08:07.262: D/dalvikvm(449): GC_CONCURRENT freed 2254K, 21% free 16989K/21383K, paused 3ms+13ms, total 127ms
07-20 15:08:07.262: D/dalvikvm(449): WAIT_FOR_CONCURRENT_GC blocked 79ms
07-20 15:08:07.262: I/IJKMEDIA(21255): SDL_AMediaCodecJava_queueInputBuffer: 9
07-20 15:08:07.262: D/dalvikvm(449): WAIT_FOR_CONCURRENT_GC blocked 124ms
07-20 15:08:07.262: D/dalvikvm(449): WAIT_FOR_CONCURRENT_GC blocked 122ms
07-20 15:08:07.262: I/videoPlayEvent(21255): =====activity on onPause===
07-20 15:08:07.262: D/VideoPlayerActivity(21255): onPause
07-20 15:08:07.262: I/IJKMEDIA(21255): ijkmp_pause()
07-20 15:08:07.262: I/IJKMEDIA(21255): SDL_AMediaCodecJava_dequeueInputBuffer(1000000)
07-20 15:08:07.262: I/IJKMEDIA(21255): ijkmp_pause()=0
07-20 15:08:07.262: I/IJKMEDIA(21255): ijkmp_get_msg: FFP_REQ_PAUSE
07-20 15:08:07.292: D/dalvikvm(725): WAIT_FOR_CONCURRENT_GC blocked 0ms
07-20 15:08:07.452: D/dalvikvm(725): GC_EXPLICIT freed 800K, 20% free 12907K/16071K, paused 3ms+12ms, total 166ms
07-20 15:08:07.512: D/VideoView(21255): -----------surface destroy
07-20 15:08:07.512: E/VideoView(21255): -----------surface destroy to pause
07-20 15:08:07.512: I/IJKMEDIA(21255): ijkmp_pause()
07-20 15:08:07.512: I/IJKMEDIA(21255): ijkmp_pause()=0
07-20 15:08:07.512: I/IJKMEDIA(21255): ijkmp_get_msg: FFP_REQ_PAUSE
07-20 15:08:07.512: I/IJKMEDIA(21255): IjkMediaPlayer_setVideoSurface
07-20 15:08:07.512: I/IJKMEDIA(21255): ijkmp_set_android_surface(surface=0x0)
07-20 15:08:07.512: D/IJKMEDIA(21255): ffpipeline_set_surface()
07-20 15:08:07.512: I/IJKMEDIA(21255): ijkmp_set_android_surface(surface=0x0)=void
07-20 15:08:07.532: I/hwcomposer(124): Setting interactive mode: On
07-20 15:08:07.992: D/dalvikvm(1030): GC_CONCURRENT freed 839K, 41% free 10193K/17159K, paused 6ms+4ms, total 47ms
07-20 15:08:07.992: D/dalvikvm(1030): WAIT_FOR_CONCURRENT_GC blocked 41ms
07-20 15:08:08.052: D/dalvikvm(1030): GC_CONCURRENT freed 508K, 39% free 10545K/17159K, paused 6ms+4ms, total 42ms
07-20 15:08:08.052: D/dalvikvm(1030): WAIT_FOR_CONCURRENT_GC blocked 36ms
07-20 15:08:08.072: W/InputMethodManagerService(449): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@41ba56e8 attribute=null
07-20 15:08:08.082: W/InputMethodManagerService(449): Focus gain on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@41a49380 (uid=10080 pid=1030)
07-20 15:08:08.132: I/ActivityManager(449): Start proc com.qihoo360.mobilesafe:FloatWindow for service com.qihoo360.mobilesafe/.assist.service.FloatService: pid=21493 uid=10079 gids={3003, 1015, 3001, 3002, 1006, 1028}
07-20 15:08:08.152: D/dalvikvm(21493): Trying to load lib /data/data/com.qihoo360.mobilesafe/files/com.qihoo360.mobilesafe/libb.so.4x.so 0x41578008
07-20 15:08:08.152: D/dalvikvm(21493): Added shared lib /data/data/com.qihoo360.mobilesafe/files/com.qihoo360.mobilesafe/libb.so.4x.so 0x41578008
07-20 15:08:08.152: D/dalvikvm(21493): No JNI_OnLoad found in /data/data/com.qihoo360.mobilesafe/files/com.qihoo360.mobilesafe/libb.so.4x.so 0x41578008, skipping init
07-20 15:08:08.162: D/dalvikvm(21493): Trying to load lib /data/data/com.qihoo360.mobilesafe/files/libmsb.so.4x.so 0x41578008
07-20 15:08:08.162: D/dalvikvm(21493): Added shared lib /data/data/com.qihoo360.mobilesafe/files/libmsb.so.4x.so 0x41578008
07-20 15:08:08.192: D/dalvikvm(21493): GetMethodID: not returning static method Landroid/os/SystemProperties;.native_get (Ljava/lang/String;)Ljava/lang/String;
07-20 15:08:08.202: D/dalvikvm(21493): GetMethodID: not returning static method Ljava/lang/ProcessManager;.exec ([Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Ljava/io/FileDescriptor;Ljava/io/FileDescriptor;Ljava/io/FileDescriptor;Z)I
07-20 15:08:08.292: D/dalvikvm(21493): GC_CONCURRENT freed 288K, 9% free 7480K/8199K, paused 1ms+2ms, total 24ms
07-20 15:08:08.292: D/dalvikvm(21493): WAIT_FOR_CONCURRENT_GC blocked 13ms
07-20 15:08:08.372: D/dalvikvm(21493): GC_CONCURRENT freed 157K, 8% free 7860K/8455K, paused 1ms+1ms, total 25ms
07-20 15:08:08.372: D/dalvikvm(21493): WAIT_FOR_CONCURRENT_GC blocked 8ms
07-20 15:08:08.472: D/dalvikvm(21493): GC_CONCURRENT freed 156K, 7% free 8233K/8839K, paused 12ms+8ms, total 45ms
07-20 15:08:08.472: D/dalvikvm(21493): WAIT_FOR_CONCURRENT_GC blocked 15ms
07-20 15:08:08.512: I/MobileSafeApplication(21493): runtime.process.name=com.qihoo360.mobilesafe:FloatWindow
07-20 15:08:08.512: I/ws000(21493): process ui=false persist=false persistUI=false crash=false contact=false barcode=false permm=false v=5.5.0.1041
07-20 15:08:08.562: I/ws001(21493): c.l.s=2 c.r.s=3
07-20 15:08:08.572: D/dalvikvm(21493): GC_CONCURRENT freed 217K, 8% free 8558K/9223K, paused 2ms+2ms, total 35ms
07-20 15:08:08.572: D/dalvikvm(21493): WAIT_FOR_CONCURRENT_GC blocked 9ms
07-20 15:08:08.582: D/dalvikvm(21493): Trying to load lib /data/data/com.qihoo360.mobilesafe/lib/libipc_pref.527.2.so 0x415b2410
07-20 15:08:08.582: I/ipc_pref(21493): [RegisterJniFunctions:19]	RegisterJniFunction methods count: 11
07-20 15:08:08.582: D/dalvikvm(21493): Added shared lib /data/data/com.qihoo360.mobilesafe/lib/libipc_pref.527.2.so 0x415b2410
07-20 15:08:08.582: I/ipc_pref(21493): [JNI_OnLoad:43]	JNI_OnLoad
07-20 15:08:08.582: I/ipc_pref(21493): [init:19]	init /data/data/com.qihoo360.mobilesafe/shared_prefs/ipc_pref
07-20 15:08:08.582: I/ipc_pref(21493): [init:70]	/data/data/com.qihoo360.mobilesafe/shared_prefs/ipc_pref
07-20 15:08:08.592: D/dalvikvm(21493): Trying to load lib /data/data/com.qihoo360.mobilesafe/files/so_libs/libbreakpad-jni-1.2.so 0x415b2410
07-20 15:08:08.592: D/dalvikvm(21493): Added shared lib /data/data/com.qihoo360.mobilesafe/files/so_libs/libbreakpad-jni-1.2.so 0x415b2410
07-20 15:08:08.592: D/dalvikvm(21493): No JNI_OnLoad found in /data/data/com.qihoo360.mobilesafe/files/so_libs/libbreakpad-jni-1.2.so 0x415b2410, skipping init
07-20 15:08:08.602: D/CrashHandler(21493): path = /data/data/com.qihoo360.mobilesafe/files/native_crash
07-20 15:08:08.622: I/ws001(21493): loading /data/data/com.qihoo360.mobilesafe/files/nettraffic.apk ...
07-20 15:08:08.632: I/dex(21493): load /data/data/com.qihoo360.mobilesafe/files/nettraffic.apk ...
07-20 15:08:08.632: I/dex(21493): load /data/data/com.qihoo360.mobilesafe/files/nettraffic.apk = dalvik.system.DexClassLoader[/data/data/com.qihoo360.mobilesafe/files/nettraffic.apk]
07-20 15:08:08.652: I/ws001(21493): loading /data/data/com.qihoo360.mobilesafe/files/nettraffic.apk ok
07-20 15:08:08.652: I/ws001(21493): loading /data/data/com.qihoo360.mobilesafe/files/appmgr.apk ...
07-20 15:08:08.662: I/dex(21493): load /data/data/com.qihoo360.mobilesafe/files/appmgr.apk ...
07-20 15:08:08.662: I/dex(21493): load /data/data/com.qihoo360.mobilesafe/files/appmgr.apk = dalvik.system.DexClassLoader[/data/data/com.qihoo360.mobilesafe/files/appmgr.apk]
07-20 15:08:08.672: I/ws001(21493): loading /data/data/com.qihoo360.mobilesafe/files/appmgr.apk ok
07-20 15:08:08.702: D/dalvikvm(21493): Trying to load lib /data/data/com.qihoo360.mobilesafe/files/libcleandroid_utils-jni-1.1.so 0x415b2410
07-20 15:08:08.702: D/dalvikvm(21493): Added shared lib /data/data/com.qihoo360.mobilesafe/files/libcleandroid_utils-jni-1.1.so 0x415b2410
07-20 15:08:08.712: D/dalvikvm(21493): GC_CONCURRENT freed 427K, 10% free 8655K/9543K, paused 18ms+5ms, total 47ms
07-20 15:08:08.752: W/ResourceType(21493): No package identifier when getting value for resource number 0x00000000
07-20 15:08:08.762: I/ipc_pref(21493): [open:30]	open /data/data/com.qihoo360.mobilesafe/shared_prefs/com.qihoo360.mobilesafe_preferences.xml
07-20 15:08:08.942: D/dalvikvm(21493): GC_CONCURRENT freed 326K, 9% free 8759K/9607K, paused 13ms+3ms, total 59ms
07-20 15:08:08.972: D/dalvikvm(21493): Trying to load lib /data/data/com.qihoo360.mobilesafe/files/libmobilesafe360_clear-jni-3.4.so 0x41733340
07-20 15:08:08.972: D/dalvikvm(21493): Added shared lib /data/data/com.qihoo360.mobilesafe/files/libmobilesafe360_clear-jni-3.4.so 0x41733340
07-20 15:08:10.612: D/sWindowSession(21493):  sWindowSession = android.view.IWindowSession$Stub$Proxy@416a0fe0
07-20 15:08:10.612: D/sWindowSession(21493):  sessionField name = mRemote
07-20 15:08:10.612: D/sWindowSession(21493):  orgIB = android.os.BinderProxy@415d0b20
07-20 15:08:12.362: D/dalvikvm(1030): GC_CONCURRENT freed 1161K, 39% free 10479K/17159K, paused 13ms+3ms, total 44ms
07-20 15:08:12.362: D/dalvikvm(1030): WAIT_FOR_CONCURRENT_GC blocked 30ms
07-20 15:08:14.492: D/SizeAdaptiveLayout(610): com.android.internal.widget.SizeAdaptiveLayout@4206b990child view android.widget.RelativeLayout@41f91140 measured out of bounds at 84px clamped to 85px
07-20 15:08:18.462: D/dalvikvm(1030): GC_CONCURRENT freed 1065K, 39% free 10488K/17159K, paused 13ms+5ms, total 46ms
07-20 15:08:18.462: D/dalvikvm(1030): WAIT_FOR_CONCURRENT_GC blocked 22ms
07-20 15:08:18.992: D/dalvikvm(21493): GC_CONCURRENT freed 309K, 9% free 8875K/9671K, paused 2ms+3ms, total 23ms
07-20 15:08:22.092: D/Daemon(1779): [startService]...component:com.getui.demo/com.igexin.sdk.PushService
07-20 15:08:22.092: D/Daemon(1779): [startService]Parent process is running,ChildPid is 21534, ParentPid is 1779
07-20 15:08:22.092: D/Daemon(1779): startService called...
07-20 15:08:22.092: D/Daemon(1779): waiting...
07-20 15:08:22.092: D/Daemon(21534): [startService]Child process is running,CurPid is 0, ChildPid is 21534
07-20 15:08:22.192: D/AndroidRuntime(21534): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
07-20 15:08:22.192: D/AndroidRuntime(21534): CheckJNI is OFF
07-20 15:08:22.202: D/dalvikvm(21534): Trying to load lib libjavacore.so 0x0
07-20 15:08:22.212: D/dalvikvm(21534): Added shared lib libjavacore.so 0x0
07-20 15:08:22.212: D/dalvikvm(21534): Trying to load lib libnativehelper.so 0x0
07-20 15:08:22.212: D/dalvikvm(21534): Added shared lib libnativehelper.so 0x0
07-20 15:08:22.352: D/AndroidRuntime(21534): Calling main entry com.android.commands.am.Am
07-20 15:08:22.362: D/AndroidRuntime(21534): Shutting down VM
07-20 15:08:22.362: I/AndroidRuntime(21534): NOTE: attach of thread 'Binder_3' failed
07-20 15:08:22.362: D/dalvikvm(21534): GC_CONCURRENT freed 103K, 89% free 490K/4096K, paused 0ms+1ms, total 3ms
07-20 15:08:22.372: D/dalvikvm(21534): Debugger has detached; object registry had 1 entries
07-20 15:08:24.052: D/dalvikvm(707): WAIT_FOR_CONCURRENT_GC blocked 0ms
07-20 15:08:24.082: D/dalvikvm(707): GC_EXPLICIT freed 298K, 40% free 16816K/27911K, paused 2ms+3ms, total 29ms
07-20 15:08:24.552: D/SizeAdaptiveLayout(610): com.android.internal.widget.SizeAdaptiveLayout@4206b990child view android.widget.RelativeLayout@41f91140 measured out of bounds at 84px clamped to 85px
07-20 15:08:24.592: D/dalvikvm(1030): GC_CONCURRENT freed 1073K, 39% free 10488K/17159K, paused 24ms+4ms, total 90ms
07-20 15:08:24.592: D/dalvikvm(1030): WAIT_FOR_CONCURRENT_GC blocked 35ms
07-20 15:08:26.382: D/penglei(21255): 从前台进入前台-------
07-20 15:08:26.442: D/dalvikvm(725): WAIT_FOR_CONCURRENT_GC blocked 0ms
07-20 15:08:26.532: D/dalvikvm(725): GC_EXPLICIT freed 198K, 21% free 12827K/16071K, paused 12ms+4ms, total 84ms
07-20 15:08:26.532: I/videoPlayEvent(21255): =====activity on resume===
07-20 15:08:26.532: I/IJKMEDIA(21255): IjkMediaPlayer_start
07-20 15:08:26.532: I/IJKMEDIA(21255): ijkmp_start()
07-20 15:08:26.532: I/IJKMEDIA(21255): ijkmp_start()=0
07-20 15:08:26.532: I/IJKMEDIA(21255): ijkmp_get_msg: FFP_REQ_START
07-20 15:08:26.532: D/IJKMEDIA(21255): ijkmp_get_msg: FFP_REQ_START: paused to start on fly
07-20 15:08:26.532: E/IJKMEDIA(21255): voud_display_overlay_l: NULL native_window
07-20 15:08:26.542: I/IJKMEDIA(21255): IjkMediaPlayer_setVideoSurface
07-20 15:08:26.542: I/IJKMEDIA(21255): ijkmp_set_android_surface(surface=0xfba0001d)
07-20 15:08:26.542: D/IJKMEDIA(21255): ffpipeline_set_surface()
07-20 15:08:26.542: I/IJKMEDIA(21255): SDL_AMediaCodecJava_releaseOutputBuffer
07-20 15:08:26.542: I/IJKMEDIA(21255): ijkmp_set_android_surface(surface=0xfba0001d)=void
07-20 15:08:26.542: D/IJKMEDIA(21255): ffpipeline_set_surface_need_reconfigure(0)
07-20 15:08:26.542: I/IJKMEDIA(21255): SDL_AMediaCodecJava_stop
07-20 15:08:26.542: E/BufferQueue(124): [SurfaceView] queueBuffer: SurfaceTexture has been abandoned!
07-20 15:08:26.542: I/IJKMEDIA(21255): SDL_AMediaCodecJava_releaseOutputBuffer
07-20 15:08:26.542: E/SurfaceTextureClient(21255): queueBuffer: error queuing buffer to SurfaceTexture, -19
07-20 15:08:26.542: E/MediaCodec(21255): Codec reported an error. (omx error 0x80001001, internalError -19)
07-20 15:08:26.552: W/System.err(21255): java.lang.IllegalStateException
07-20 15:08:26.552: W/System.err(21255): 	at android.media.MediaCodec.releaseOutputBuffer(Native Method)
07-20 15:08:26.552: W/System.err(21255): 	at dalvik.system.NativeStart.run(Native Method)
07-20 15:08:26.552: E/IJKMEDIA(21255): SDL_AMediaCodecJava_releaseOutputBuffer: releaseOutputBuffer
07-20 15:08:26.552: D/NvOsDebugPrintf(127): NvMMDecTVMRDestroyParser Begin 
07-20 15:08:26.552: D/NvOsDebugPrintf(127): --------- Closing TVMR Frame Delivery Thread -------------
07-20 15:08:26.562: W/BufferQueue(124): [SurfaceView] cancelBuffer: BufferQueue has been abandoned!
07-20 15:08:26.562: I/IJKMEDIA(21255): SDL_AMediaCodecJava_releaseOutputBuffer
07-20 15:08:26.562: W/BufferQueue(124): [SurfaceView] cancelBuffer: BufferQueue has been abandoned!
07-20 15:08:26.562: D/NvOsDebugPrintf(127): ------- NvAvpClose -------
07-20 15:08:26.562: D/NvOsDebugPrintf(127): NvMMDecTVMRDestroyParser Done 
07-20 15:08:26.562: D/NvOsDebugPrintf(127): NvMMLiteTVMRDecPrivateClose Done 
07-20 15:08:26.562: W/BufferQueue(124): [SurfaceView] cancelBuffer: BufferQueue has been abandoned!
07-20 15:08:26.562: W/BufferQueue(124): [SurfaceView] cancelBuffer: BufferQueue has been abandoned!
07-20 15:08:26.562: W/BufferQueue(124): [SurfaceView] cancelBuffer: BufferQueue has been abandoned!
07-20 15:08:26.562: W/BufferQueue(124): [SurfaceView] cancelBuffer: BufferQueue has been abandoned!
07-20 15:08:26.562: W/BufferQueue(124): [SurfaceView] cancelBuffer: BufferQueue has been abandoned!
07-20 15:08:26.562: W/BufferQueue(124): [SurfaceView] cancelBuffer: BufferQueue has been abandoned!
07-20 15:08:26.562: W/BufferQueue(124): [SurfaceView] cancelBuffer: BufferQueue has been abandoned!
07-20 15:08:26.562: W/BufferQueue(124): [SurfaceView] cancelBuffer: BufferQueue has been abandoned!
07-20 15:08:26.562: W/BufferQueue(124): [SurfaceView] cancelBuffer: BufferQueue has been abandoned!
07-20 15:08:26.562: W/BufferQueue(124): [SurfaceView] cancelBuffer: BufferQueue has been abandoned!
07-20 15:08:26.562: W/BufferQueue(124): [SurfaceView] cancelBuffer: BufferQueue has been abandoned!
07-20 15:08:26.562: W/BufferQueue(124): [SurfaceView] cancelBuffer: BufferQueue has been abandoned!
07-20 15:08:26.562: W/BufferQueue(124): [SurfaceView] cancelBuffer: BufferQueue has been abandoned!
07-20 15:08:26.562: W/BufferQueue(124): [SurfaceView] cancelBuffer: BufferQueue has been abandoned!
07-20 15:08:26.562: W/BufferQueue(124): [SurfaceView] cancelBuffer: BufferQueue has been abandoned!
07-20 15:08:26.572: W/BufferQueue(124): [SurfaceView] cancelBuffer: BufferQueue has been abandoned!
07-20 15:08:26.572: W/System.err(21255): java.lang.IllegalStateException
07-20 15:08:26.572: W/System.err(21255): 	at android.media.MediaCodec.releaseOutputBuffer(Native Method)
07-20 15:08:26.572: W/System.err(21255): 	at dalvik.system.NativeStart.run(Native Method)
07-20 15:08:26.572: E/IJKMEDIA(21255): SDL_AMediaCodecJava_releaseOutputBuffer: releaseOutputBuffer
07-20 15:08:26.572: E/IJKMEDIA(21255): SDL_VoutOverlayAMediaCodec_releaseFrame: SDL_AMediaCodec_releaseOutputBuffer: failed (-10000)
07-20 15:08:26.592: I/IJKMEDIA(21255): SDL_AMediaCodecJava_configure_surface
07-20 15:08:26.592: E/IJKMEDIA(21255): configure 0x1e800312 0x1d3002f2
07-20 15:08:26.592: A/ACodec(21255): frameworks/av/media/libstagefright/ACodec.cpp:1360 CHECK(format.eColorFormat == OMX_COLOR_FormatYUV420Planar || format.eColorFormat == OMX_COLOR_FormatYUV420SemiPlanar || format.eColorFormat == OMX_COLOR_FormatCbYCrY || format.eColorFormat == OMX_TI_COLOR_FormatYUV420PackedSemiPlanar || format.eColorFormat == OMX_QCOM_COLOR_FormatYVU420SemiPlanar) failed.
07-20 15:08:26.612: E/OMXNodeInstance(127): !!! Observer died. Quickly, do something, ... anything...

**Comment by Android4MediaPlayer** [comment]
@bbcallen  API调用过程，播放过程页面被遮盖后收到surfacedestroy消息时调用API暂停并设置surface为NULL，回来的时候start并设置surface，但是画面不会显示了并出现异常

**Comment by Android4MediaPlayer** [comment]
机型NEXUS_7，4.1.1

**Comment by bbcallen** [comment]
No support for surface switching, yet

**Comment by Android4MediaPlayer** [comment]
这个怎么去做呢？尤其按HOME键需要这么做，一般系统会销毁surface

**Comment by Android4MediaPlayer** [comment]
@bbcallen How  to fix the surface switching?

**Comment by bbcallen** [comment]
It need to be implemented, not only be fixed.

**Comment by Android4MediaPlayer** [comment]
OK,the implemented to modify,how much work?

**Comment by bbcallen** [comment]
Many

**Comment by Android4MediaPlayer** [comment]
have you a plan to implemented? give some reference resources

**Comment by bbcallen** [comment]
Not in two months.

**Comment by bbcallen** [comment]
Feature added
