### ISSUE TITLE
ios正常，android在同编译条件下播放concat文件报MEDIA_ERROR_IJK_PLAYER异常

### ISSUE THREAD

**Issue by ioryli** [Bilibili/ijkplayer#341]
ios正常，android在同变异条件下播放concat文件报MEDIA_ERROR_IJK_PLAYER异常。
在ijkplayer_jni.c  ：

  case FFP_MSG_ERROR:
            MPTRACE("FFP_MSG_ERROR: %d", msg.arg1);
            post_event(env, weak_thiz, MEDIA_ERROR, MEDIA_ERROR_IJK_PLAYER, msg.arg1);
            break;

concat文件file.txt 内容：
     ffconcat version 1.0
file 'http://video.dispatch.tc.qq.com/65088705/m0016nwmqws.p203.1.mp4?vkey=50B69AC7369E03229347F391B93A4AB83F83E29424B2149E5486B35E4A39DBF1FB78A6899F5A0D5EBE3D18010BDE8D6359C488E04B0257EA3359E484C8911172E9BCE0C1BB9B8AA560B6437684CD4447E350F2137C14E6EC'
duration 300
file 'http://video.dispatch.tc.qq.com/65088705/m0016nwmqws.p203.2.mp4?vkey=506A52C5A8AB64E3076DE548A247B30C449DBA9BC01716AD3DAD04D21F61E3FF2918F1F5614C61DCECDAAA6F805C0AA46C8D013BEAFC87843F7DBE5B31355610C8B54BF3349B123CD5FFDBBC3617CBB5BA4F48812D4BE92D'
duration 300

![error](https://cloud.githubusercontent.com/assets/13433982/8800165/377c099e-2fe3-11e5-9c65-8d93a323a20f.png)

求助～～

**Comment by gongjiehong** [comment]
顶上去，同问

**Comment by bbcallen** [comment]
Any log?

**Comment by ioryli** [comment]
是的 日志已经发到主贴的截图了。 我自己想办法解决了
在 concat的源码里面把 safe 模式给关掉了。
    //iory modify
//    if (cat->safe > 0 && !safe_filename(filename)) {
//        av_log(avf, AV_LOG_ERROR, "Unsafe file name '%s'\n", filename);
//        FAIL(AVERROR(EPERM));
//    }
    if ( 0 && !safe_filename(filename)) {
        av_log(avf, AV_LOG_ERROR, "Unsafe file name '%s'\n", filename);
        FAIL(AVERROR(EPERM));
    }

这样可以正常播放了  ， 但是不知道是否有隐患。

**Comment by ioryli** [comment]
bbcallen 兄， 能否方便加个QQ呢， 希望有更加深入的交流· 目前公司正在打算从vitamio大力切到ijk，谢谢：）

**Comment by Android4MediaPlayer** [comment]
估计他挺忙的，github交流比较好

**Comment by bbcallen** [comment]
Please contact our BD for any business service.
http://www.bilibili.com/html/contact.html

**Comment by ioryli** [comment]
@bbcallen  ,这里我这样操作是否有什么隐患么？ 
//iory modify
// if (cat->safe > 0 && !safe_filename(filename)) {
// av_log(avf, AV_LOG_ERROR, "Unsafe file name '%s'\n", filename);
// FAIL(AVERROR(EPERM));
// }
if ( 0 && !safe_filename(filename)) {
av_log(avf, AV_LOG_ERROR, "Unsafe file name '%s'\n", filename);
FAIL(AVERROR(EPERM));
}

**Comment by bbcallen** [comment]
没
