### ISSUE TITLE
iOS 怎么设置重复循环播放的

### ISSUE THREAD

**Issue by zklycumt1226** [Bilibili/ijkplayer#3415]
各位大佬，请问ijk iOS是怎么设置循环播放的？

**Comment by raymond1012** [comment]
监听complete，然后start

**Comment by Android4MediaPlayer** [comment]
设置loop

**Comment by wpdejin** [comment]
一、如果是用AVPlayer播放器，循环播放设置如下：
IJKAVMoviePlayerController.m页面
- (void)didPrepareToPlayAsset:(AVURLAsset *)asset withKeys:(NSArray *)requestedKeys
找到以上方法的591行添加如下代码
 [[NSNotificationCenter defaultCenter]addObserver:self selector:@selector(runLoopPlay:) name:AVPlayerItemDidPlayToEndTimeNotification object:nil];
再添加接受循环播放的方法
- (void)runLoopPlay:(NSNotification *)n{
    AVPlayerItem * p = [n object];
    [p seekToTime:kCMTimeZero];
    [_player play];
}
二、如果使用IJKFFMoviePlayerController.m 播放器，自动循环设置如下：
- (id)initWithContentURLString:(NSString *)aUrlString
                   withOptions:(IJKFFOptions *)options 
找到以上方法214行添加如下代码
//自动循环播放，最多播放100遍
ijkmp_set_loop(_mediaPlayer, 100);

**Comment by bluesky0109** [comment]
@raymond1012 
```- (void)moviePlayBackDidFinish:(NSNotification*)notification {
    //    MPMovieFinishReasonPlaybackEnded,
    //    MPMovieFinishReasonPlaybackError,
    //    MPMovieFinishReasonUserExited
    int reason = [[[notification userInfo] valueForKey:IJKMPMoviePlayerPlaybackDidFinishReasonUserInfoKey] intValue];
    
    if (reason != IJKMPMovieFinishReasonUserExited) {
        self.player.currentPlaybackTime = 0;
        if (!self.player.isPlaying) {
            [self.player play];
        }
    }```

监听 finished 后 重新调用播放 会进入死循环 一直反复进入 finished
