### ISSUE TITLE
请问编译时如何修改ffmpeg在rtsp协议中的rtsp over udp 或者 rtsp over tcp选项？现在编译出来的so可以识别rtsp地址，但还是无法播放

### ISSUE THREAD

**Issue by camelsmith** [Bilibili/ijkplayer#3416]
请问编译时如何修改ffmpeg在rtsp协议中的rtsp over udp 或者 rtsp over tcp选项？现在编译出来的so可以识别rtsp地址，但还是无法播放。
    之前用过VLC编译，配置的时候在 live555.cpp中有一段代码，将add_boot 中的 false改为 true可以将rtsp协议设置为 rtsp over tcp：

    add_boot("rtsp-tcp",true,
             N_("Use RTP over RTSP (TCP)"),
             N_("Use RTP over RTSP (TCP)"),true)

但是在ijkplayer中，我没找到有live555.cpp，请问要在哪里进行这个选项的配置？

**Comment by raymond1012** [comment]
search issue

**Comment by camelsmith** [comment]
已经自己找到答案，可以在 ijkplayer-java库中的ijkVideoView类中
在适当的位置添加该配置信息，第三个参数 可选 tcp 或者 rtp
                    ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "rtsp_transport", "tcp");
