### ISSUE TITLE
ARMv8 x64处理器下播放器崩溃

### ISSUE THREAD

**Issue by Matrixbirds** [Bilibili/ijkplayer#343]

**Comment by Android4MediaPlayer** [comment]
机型，日志？

**Comment by avenwu** [comment]
@Matrixbirds  https://github.com/Bilibili/ijkplayer/pull/354

**Comment by killnono** [comment]
有同样一个问题，
引入armv7a and x86，
nexus 5x上直接报错：
                                                                               java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.yangcong345.android.phone/files/instant-run/dex/slice-slice_9_83e32a1cf6ed52aa4ac1ded65d7b2f8c73528c7f-classes.dex", dex file "/data/data/com.yangcong345.android.phone/files/instant-run/dex/slice-slice_8_261fbcbac79d47f2b520399820afdd8127d2bc3f-classes.dex", dex file "/data/data/com.yangcong345.android.phone/files/instant-run/dex/slice-slice_7_ada358f41673f90e3721693f73d2f5430d07f102-classes.dex", dex file "/data/data/com.yangcong345.android.phone/files/instant-run/dex/slice-slice_6_722ba857d483c64c160526a5ef74d1530a4b48c5-classes.dex", dex file "/data/data/com.yangcong345.android.phone/files/instant-run/dex/slice-slice_5_540152165e58beabb7371757b7cba0dd1e9c94a3-classes.dex", dex file "/data/data/com.yangcong345.android.phone/files/instant-run/dex/slice-slice_4_48ce358492ce7acc5083490de1d514db07d458c8-classes.dex", dex file "/data/data/com.yangcong345.android.phone/files/instant-run/dex/slice-slice_3_54b17104ff51e36309ee358bb482ba9eb8e40548-classes.dex", dex file "/data/data/com.yangcong345.android.phone/files/instant-run/dex/slice-slice_2_6b9dbe2e935be4db1bb58c2882fd4f764b75e82c-classes.dex", dex file "/data/data/com.yangcong345.android.phone/files/instant-run/dex/slice-slice_1_4d768590575b6d5474c5e790d12657e281d0e787-classes.dex", dex file "/data/data/com.yangcong345.android.phone/files/instant-run/dex/slice-slice_0_e4170ba19e15f3e2e23ac769fc1e77e451f115be-classes.dex", dex file "/data/data/com.yangcong345.android.phone/files/instant-run/dex/slice-dependencies_8d57b397bfb5c28f6c0d4d080c590303c1a58904-classes2.dex", dex file "/data/data/com.yangcong345.android.phone/files/instant-run/dex/slice-dependencies_8d57b397bfb5c28f6c0d4d080c590303c1a58904-classes.dex"],nativeLibraryDirectories=[/data/app/com.yangcong345.android.phone-2/lib/arm64, /data/app/com.yangcong345.android.phone-2/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"

**Comment by DanielXiao123** [comment]
I have the same issue.

**Comment by xujianhong** [comment]
Me,too.
Nexus 5x
java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-x86-0.6.3_40fc163d814d45080b3bb396bfba5d61294a4a40-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-java-0.6.3_0d244924bb8eeae162d2ca5ca37330db997f6e8f-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-exo-0.6.3_1dccdd01437ba8596431125bff51cebfac2b702c-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-armv7a-0.6.3_aa27c6af8fae2b0e8dbf20e70fe58f4df69b2542-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-armv5-0.6.3_25f31592461452b6214f52da77d5aaee1c670c46-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-support-annotations-24.2.1_a4630f5e61d0713a1dd0cb6da274e57b87f84006-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-pushservice-5.1.0.48_6c9885767d29cb8602c2452720aa4fb36e9373c2-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-okio-1.8.0_06f7f952010e37a20e0067d81e65675288b9e24f-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-okhttp-3.3.1_2ea39afb3973a142a4b831a99bc4e2df1de6a0a5-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-libammsdk_1d597bd99e280d824867d0060dcce21c882f0e2f-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-internal_impl-24.2.1_f4e3b596a7c7bce8e78ab5801487483d7cea7227-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-internal_impl-24.2.1_bac709185240692d232ab1f82c6f3bad58d4f274-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-internal_impl-24.2.1_8a18df9556ed02ab453ae6ae2a76a6c6e88435e4-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-internal_impl-24.2.1_5e2c8f8c0a440b648a9f319aa61c23394d069ddd-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-internal_impl-24.2.1_1ffeb27fb740d412bdc0600e92bb8f2a635060b5-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-glide-3.7.0_1f3ddf859a86296da03fddcf50d19f29d652df81-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-fastjson-1.2.3_dcaee9cf03170f87ea790935ca1dbd1448aa0b1e-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-com.jakewharton-butterknife-8.4.0_ad95ad62cbbf26824ee449350666ae45265191a5-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-com.h6ah4i.android.widget.verticalseekbar-verticalseekbar-0.7.0_ec5692d749a0bafd54721f9212110db2c7436059-classes.dex", dex 
11-03 17:09:14.000 29546-29546/com.daomingedu.stumusic E/PlayView: file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-com.google.android.exoplayer-exoplayer-r1.5.11_927ff0c417839087e90e2de896106bb3ef194ed7-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-com.android.support-support-vector-drawable-24.2.1_cde145515f21ebf8c421d05f5847b2bb737a7399-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-com.android.support-support-v4-24.2.1_3b7dbd5c72ffbb557fffcc83e4c0e9a060440403-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-com.android.support-support-media-compat-24.2.1_efca6a3780557433e20a3843fa668243a87ae631-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-com.android.support-support-fragment-24.2.1_42dfe399e2b8eb0547df35c5b6abc3534af71be0-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-com.android.support-support-core-utils-24.2.1_5bece4dc834a1a051282943642659d83b4ed9922-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-com.android.support-support-core-ui-24.2.1_1909bccd40effc3e2d92473f4c94033392c2ebe3-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-com.android.support-support-compat-24.2.1_c7211644a32cfe478527ba79032f410bc6daf804-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-com.android.support-recyclerview-v7-24.2.1_34ea3493dd9a646d0eebd1b9635d9916a2f903a1-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-com.android.support-preference-v7-24.2.1_b2ef609257878e8a7bf4f944ec7614dec2bfca5e-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-com.android.support-design-24.0.0_9d279b197c17b8d97e82c32e8d347228496c9f3f-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-com.android.support-appcompat-v7-24.2.1_976874f2301b6c2d7420bf10e614037f89647d51-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-com.android.support-animated-vector-drawable-24.2.1_c5c9d1a207fd7640a42192ddbdc09dc86a6e79fd-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-butterknife-annotations-8.4.0_a2a255623276bf6fd1b525dcb3e3c692cac62c3e-classes.dex", dex file "/data/data/com.daomingedu.stumusic/files/instant-run/dex/slice-alipaySdk-20160809_649f18707e55532c78822a3b2c716318936f6166-classes.dex"],nativeLibraryDirectories=[/data/app/com.daomingedu.stumusic-1/lib/arm64, /system/fake-libs64, /data/app/com.daomingedu.stumusic-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libijkffmpeg.so"
                                                                       at java.lang.Runtime.loadLibrary0(Runtime.java:972)
                                                                       at java.lang.System.loadLibrary(System.java:1530)
                                                                       at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:163)
                                                                       at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:174)
                                                                       at com.daomingedu.ijkplayertest.widget.PlayView.<init>(PlayView.java:172)
                                                                       at com.daomingedu.ijkplayertest.widget.PlayView.<init>(PlayView.java:0)
                                                                       at com.daomingedu.stumusic.base.BaseVideoAct.initViews(BaseVideoAct.java:29)
                                                                       at com.daomingedu.stumusic.ui.myclass.GradedHomeworkAct.initViews(GradedHomeworkAct.java:84)
                                                                       at com.daomingedu.stumusic.ui.myclass.GradedHomeworkAct.onCreate(GradedHomeworkAct.java:78)
                                                                       at android.app.Activity.performCreate(Activity.java:6664)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
11-03 17:09:14.000 29546-29546/com.daomingedu.stumusic E/PlayView:     at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
