### ISSUE TITLE
ape格式不能播放（用了module-default.sh）

### ISSUE THREAD

**Issue by a7859696** [Bilibili/ijkplayer#3438]
01-18 13:03:23.117 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_native_profileBegin
01-18 13:03:23.117 5915-5915/tv.danmaku.ijk.media.example W/IJKMEDIA: monstartup already called
01-18 13:03:23.206 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_native_setup
01-18 13:03:23.206 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170518--001
01-18 13:03:23.206 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: ijk_version_info: k0.8.0
01-18 13:03:23.207 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: ffpipeline_create_from_android()
01-18 13:03:23.207 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_inject_opaque(0x1007ee)
01-18 13:03:23.207 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_inject_opaque()=void
01-18 13:03:23.207 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x1007ee)
01-18 13:03:23.209 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
01-18 13:03:23.209 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
01-18 13:03:23.209 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
01-18 13:03:23.209 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
01-18 13:03:23.209 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(3)
01-18 13:03:23.209 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: moncleanup
01-18 13:03:23.209 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-18 13:03:23.210 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-18 13:03:23.210 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-18 13:03:23.210 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-18 13:03:23.210 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-18 13:03:23.210 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-18 13:03:23.210 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-18 13:03:23.211 5915-5915/tv.danmaku.ijk.media.example D/tv.danmaku.ijk.media.player.IjkMediaPlayer: Couldn't open file on client side, trying server side
01-18 13:03:23.211 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
01-18 13:03:23.211 5915-5915/tv.danmaku.ijk.media.example V/IJKMEDIA: setDataSource: path /storage/emulated/0/Music/逃跑计划夜空中最亮的星.ape
01-18 13:03:23.212 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_data_source(url="/storage/emulated/0/Music/逃跑计划夜空中最亮的星.ape")
01-18 13:03:23.212 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_data_source(url="/storage/emulated/0/Music/逃跑计划夜空中最亮的星.ape")=0
01-18 13:03:23.212 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
01-18 13:03:23.212 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffc39240)
01-18 13:03:23.212 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: ffpipeline_set_surface()
01-18 13:03:23.212 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffc39240)=void
01-18 13:03:23.212 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_prepareAsync
01-18 13:03:23.212 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_prepare_async()
01-18 13:03:23.213 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: ===== versions =====
01-18 13:03:23.213 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: ijkplayer    : k0.8.0
01-18 13:03:23.213 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170518--001
01-18 13:03:23.213 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: libavutil    : 55.58.100
01-18 13:03:23.213 5915-7010/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [7010] ff_msg_loop
01-18 13:03:23.213 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: libavcodec   : 57.89.100
01-18 13:03:23.213 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: libavformat  : 57.71.100
01-18 13:03:23.213 5915-7010/tv.danmaku.ijk.media.example D/IJKMEDIA: message_loop
01-18 13:03:23.213 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: libswscale   : 4.6.100
01-18 13:03:23.213 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: libswresample: 2.7.100
01-18 13:03:23.213 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: ===== options =====
01-18 13:03:23.213 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : mediacodec                   = 0
01-18 13:03:23.213 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : opensles                     = 0
01-18 13:03:23.213 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : overlay-format               = 842225234
01-18 13:03:23.213 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : framedrop                    = 1
01-18 13:03:23.213 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : start-on-prepared            = 0
01-18 13:03:23.213 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : ijkapplication               = -768042128
01-18 13:03:23.213 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : ijkiomanager                 = -527104784
01-18 13:03:23.213 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : http-detect-range-support    = 0
01-18 13:03:23.213 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
01-18 13:03:23.213 5915-5915/tv.danmaku.ijk.media.example I/IJKMEDIA: ===================
01-18 13:03:23.214 5915-5915/tv.danmaku.ijk.media.example E/IJKMEDIA: lixuan--7a--AudioTrack
01-18 13:03:23.215 5915-7010/tv.danmaku.ijk.media.example D/IJKMEDIA: FFP_MSG_FLUSH:
01-18 13:03:23.216 5915-5915/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_prepare_async()=0
01-18 13:03:23.216 5915-7011/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [7011] ff_vout
01-18 13:03:23.217 5915-7012/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [7012] ff_read
01-18 13:03:23.217 5915-7012/tv.danmaku.ijk.media.example D/IJKMEDIA: Setting default whitelist 'file,crypto'
01-18 13:03:23.336 5915-5954/tv.danmaku.ijk.media.example D/OpenGLRenderer: endAllActiveAnimators on 0xebb9b100 (ListView) with handle 0xd23894d0
01-18 13:03:23.772 5915-7012/tv.danmaku.ijk.media.example W/IJKMEDIA: Format ape detected only with low score of 25, misdetection possible!
01-18 13:03:23.772 5915-7012/tv.danmaku.ijk.media.example E/IJKMEDIA: Unsupported file version - 4.11
01-18 13:03:23.772 5915-7012/tv.danmaku.ijk.media.example D/IJKMEDIA: Statistics: 1048576 bytes read, 0 seeks
01-18 13:03:23.772 5915-7012/tv.danmaku.ijk.media.example E/IJKMEDIA: /storage/emulated/0/Music/逃跑计划夜空中最亮的星.ape: Not yet implemented in FFmpeg, patches welcome
01-18 13:03:23.772 5915-7012/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [7012]
01-18 13:03:23.772 5915-7010/tv.danmaku.ijk.media.example D/IJKMEDIA: FFP_MSG_ERROR: 0
01-18 13:03:23.789 5915-5915/tv.danmaku.ijk.media.example E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
01-18 13:03:23.790 5915-5915/tv.danmaku.ijk.media.example D/IjkVideoView: Error: -10000,0
01-18 13:03:23.800 5915-5915/tv.danmaku.ijk.media.example I/AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
01-18 13:03:26.702 5915-5915/tv.danmaku.ijk.media.example E/Bitmap: ===========the width is96the height is81

**Comment by raymond1012** [comment]
first you need enable ape demux and decode, then your ape need have a correct probe

**Comment by a7859696** [comment]
ijk里面有设置让ape  demux and decode 的方法吗？  用怎样修改demo才能播

**Comment by a7859696** [comment]
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=ape”
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=ape”
使用这样不行。

需要到代码的哪里去添加一个 demux和decode ？

**Comment by raymond1012** [comment]
check 一下 CONFIG_APE_DECODER 和 CONFIG_APE_DEMUXER 在config.h是否被使能

2017-08-05 16:42 GMT+08:00 a7859696 <notifications@github.com>:

**Comment by a7859696** [comment]
谢谢回答。能播放了，发现可能是我到ape音频本身有问题，换了资源后default和你说的方法都能让ape播放

**Comment by a7859696** [comment]
...音频没有问题。不能播放的是比特率高于900多的，能播放的是比特率低于900的。。 代码中有限制吗？

**Comment by a7859696** [comment]
找到原因的。  播放不了ape文件 version4.11(Monkey's Aduio 4.11) .  。  这是什么原因导致的呢

**Comment by mouseOf2ch** [comment]
@a7859696 ,你好，我也遇到这个问题了，请问你是怎么解决的？
