### ISSUE TITLE
git checkout -B latest k0.8.1.2 失败      求大神相互!在线等!急急急急.....

### ISSUE THREAD

**Issue by TianLuhua** [Bilibili/ijkplayer#3439]
按照步骤一步一步来的,执行:git checkout -B latest k0.8.1.2时候,提示如下:
tianluhua@tianluhua-vm-ubuntu:~/work/ijkplayer-android$ git checkout -B latest k0.8.1.2
fatal: 不能同时更新路径并切换到分支'latest'。
您是想要检出 'k0.8.1.2' 但其未能解析为提交么？
tianluhua@tianluhua-vm-ubuntu:~/work/ijkplayer-android$ 

( git checkout -B latest k0.8.1.2  还有这种操作!  切分支? 还是? )

**Comment by raymond1012** [comment]
wait k0.8.2, or use master

**Comment by TianLuhua** [comment]
好的,谢谢!
