### ISSUE TITLE
请教：私有协议传输直播视频如何处理？

### ISSUE THREAD

**Issue by Hearnseu** [Bilibili/ijkplayer#344]
现在我通过一个私有的UDP socket来传输音视频数据，连接后就会有源源不断的直播数据传过来，那么请问bbcallen 及各位大神：这种情况如如何利用ijkplayer来播放音视频，麻烦指点大致思路或实现方法，谢谢！

**Comment by Android4MediaPlayer** [comment]
把你的私有协议添加到ffmpeg，可走自定义IO方式

**Comment by Hearnseu** [comment]
谢谢你的解答，我去研究一下怎么实现
