### ISSUE TITLE
播放器器seek响应非常慢

### ISSUE THREAD

**Issue by wbi1987** [Bilibili/ijkplayer#3440]
同样的流用系统原生的播放器，或者其他播放器seek都很快，但是ijkplayer就很慢

**Comment by wbi1987** [comment]
http://open-audio.nosdn.127.net/nos/mp3/2017/08/01/SCPQIKSN3_sd.mp3

**Comment by fjzboy** [comment]
wbi1987， 我也遇到这个问题，请问下你是怎么解决的？

**Comment by fjzboy** [comment]
我设置async以后，seek 很短的时间段很快，但是seek的时间如果很长的，就要等很久很久，5分钟以上

**Comment by xksds** [comment]
if(NULL != is && NULL != is->ic)
        is->ic->flags |= AVFMT_FLAG_FAST_SEEK;

@wbi1987 @fjzboy

**Comment by xksds** [comment]
还有吧网络协议层的cache设置小一点
