### ISSUE TITLE
在Android上ijk硬解和其他播放器的硬解实现方式一样吗？

### ISSUE THREAD

**Issue by Shinlone** [Bilibili/ijkplayer#3442]
同样的设备，vlc-android和其他播放器可以硬解，说明设备支持硬解，ijk开启硬解后没有硬解，这个可能的原因是什么呢？

**Comment by raymond1012** [comment]
need setoption mediacodec is 1

**Comment by Shinlone** [comment]
![image](https://user-images.githubusercontent.com/14052531/28967973-5bca232c-7950-11e7-9a37-9328c7f1611b.png)

我设置了，会不会存在第三种情况

**Comment by Android4MediaPlayer** [comment]
need your log
