### ISSUE TITLE
请问ijkio，ffio，cache这几个协议有人用过吗，用过的能不能指教一下

### ISSUE THREAD

**Issue by bhltyou** [bilibili/ijkplayer#3446]

**Comment by lrs0304** [comment]
我也很好奇ijkio这个

**Comment by raymond1012** [comment]
ijkio 主要是ijk为了方便接管 ffmpeg的io层，做一些我们自己定制化的东西而设计的

**Comment by bhltyou** [comment]
@raymond1012  请问如何使用 能说一下吗 谢谢

**Comment by raymond1012** [comment]
可以参考ijkiocache来加入自己需要的io层控制逻辑，然后使用ijkio:xxx:ffio:url 来使用自己的逻辑

**Comment by zhanggao** [comment]
有java层的实现例子吗 @raymond1012

**Comment by halfhq** [comment]
我尝试过在java层直接修改m3u8文件中的url来使用ijkio，
当初主要是为了重试功能，但结果与我期望的不一致。
比如一个url地址是 http://xxx.com/1.ts，
在java中直接替换成 ijkio:http://xxx.com/1.ts
