### ISSUE TITLE
Controller 問題

### ISSUE THREAD

**Issue by ajer001** [Bilibili/ijkplayer#345]
Hi,

冒昧請教幾個問題：

1. 
請問 IJKFFMoviePlayerController  /  IJKAVMoviePlayerController  /  IJKMPMoviePlayerController 的差異是什麼呢？

2. 
RTSP 用 IJKFFMoviePlayerController 可以播，但是 IJKMPMoviePlayerController 卻無法，
這是正常的嗎？

3.
IJKFFMoviePlayerController 的 CPU Loading 好像很高？

Thanks.

**Comment by bbcallen** [comment]
1. FF is based on FFmpeg,  AV is based on AVPlayer system api, MP is based on MPMoviePlayerViewController system api.
2. Yes, it's normal
3. Yes, IJKFFMoviePlayerController use FFmpeg as default, which decode with CPU.

**Comment by ajer001** [comment]
Hi,

CPU in high loading means SW decoding, right? or I'm misunderstood ?
Is it possible to force to do HW decode ?


Tannks.

**Comment by bbcallen** [comment]
Yes.
VideoToolbox can be enabled with IJKFFOption.setVideoToolboxEnabled

**Comment by ajer001** [comment]
Hi,

should I add or modify any build config for HW decode ?
I found the decode is always empty.

Thanks.

**Comment by bbcallen** [comment]
It depends on whether you need other container formats or protocols, such as mkv, wmv, ...
What do you mean "the decode is always empty"?

**Comment by ajer001** [comment]
From build log, hwaccels list is empty ?

Enabled decoders:
aac			mp3adu			mp3on4
h264			mp3adufloat		mp3on4float
mp3			mp3float

Enabled encoders:

Enabled hwaccels:

Enabled parsers:
aac			h264			mpegaudio

Enabled demuxers:
aac			hls			mpegts
asf			mov			rm
h264			mp3			rtsp

**Comment by bbcallen** [comment]
ijkplayer use its own hw decode implement, but not FFmpeg's h264_vda

**Comment by ajer001** [comment]
Therefore, I don't need to add any HWACC or VDA related build config ?
BTW, is it normal that CPU loading still high in iPhoneSimulator ?
H264 rtsp video with AAC-LC audio.

**Comment by bbcallen** [comment]
1. Yes.
2. I doubt if VideoToolbox works in iPhoneSimulator. I only test VideoToolbox in real devices.

**Comment by ajer001** [comment]
OK, Thanks so much :)

**Comment by bbcallen** [comment]
Check if VideoToolbox is open successfully.
```
[mp isVideoToolboxOpen]
```
