### ISSUE TITLE
ijkPlayer再多次使用後，出現畫面快播，沒有聲音

### ISSUE THREAD

**Issue by KARC76926** [Bilibili/ijkplayer#3450]
[ijkplayer_log.txt](https://github.com/Bilibili/ijkplayer/files/1206997/ijkplayer_log.txt)

這個發生狀況主要會發生再重複使用約30次左右
出現
Error code -20 when initializing AudioTrack.
java.lang.IllegalStateException: play() called on uninitialized AudioTrack.
這兩個關鍵詞後
ijkplayer 就會出現異常．

**Comment by raymond1012** [comment]
AudioTrack  初始化失败，确认每次播放完都有释放？

**Comment by KARC76926** [comment]
objMediaPlayerInternal.resetListeners();
objMediaPlayerInternal.reset();
objMediaPlayerInternal.release();
objMediaPlayerInternal = null;
這是目前離開ijkplayer做的處理．
請問這因該沒錯吧，還是說這個過程需要一段時間，無法立即完成？

**Comment by raymond1012** [comment]
释放没有问题，释放函数本身是同步的，使用的手机是什么型号，是不是在多个型号的手机上都能复现

**Comment by KARC76926** [comment]
了解，謝謝，我再做確認．
現在試用HUAWEI nova再做實驗
我還會再用其它手機試試

**Comment by raymond1012** [comment]
另外我在你提供的log里没有看到IjkMediaPlayer_release的调用，需要确认是否调用到了release

**Comment by KARC76926** [comment]
OK,我會再檢查我內部流程．
