### ISSUE TITLE
Mjpeg flaky streaming

### ISSUE THREAD

**Issue by chrisjenx** [Bilibili/ijkplayer#346]
Hi, thanks for your superb work, the first project to clone and just work!

I am trying to play mjpeg streams, they seem to throw some odd errors:

`deprecated pixel format used, make sure you did set range correctly`

This is a good test stream which displays odd behavours, buffers thans plays at a fast rate then buffers again: http://204.239.12.142/mjpg/video.mjpg

I would guess maybe I need to compile ffmpeg with some different flags? Or there are better `setOptions` I can pass to the player?

I would like to verify that VLC does play that stream correctly.

Thanks again,
Chris.

**Comment by Android4MediaPlayer** [comment]
please compiler ffmpeg to open to support mjpg.

**Comment by bbcallen** [comment]
Try ffplay on PC first, I guess there are some problems about Audio/Video sync when playing video only stream.

There are setOptionValue() method in player class.

**Comment by bbcallen** [comment]
Buffers caused by the pause-and-buffer logic in ijkplayer.
After several seconds packets are filled, player outputs all frames at once, and buffer again.

I've add an option 'packet-buffering' since b9584c5eccde6f9a6e270c14539fb1dd3faf2028
The pause-and-buffer logic can be disabled by
```
[mp setPlayerOptionIntValue:0 forKey:"packet-buffering"];
```

**Comment by chrisjenx** [comment]
Hi, just to confirm `ffplay -f mjpeg -i http://204.239.12.142/mjpg/video.mjpg` works fine on desktop.

I'll try with the latest HEAD. Turning off  `packet-buffering`. (I'm using Android btw)

**Comment by chrisjenx** [comment]
@Android4MediaPlayer not sure what you mean?
I have the following flags enabled in my `module.sh`:

```bash
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mjpeg"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mjpegb"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=jpeg2000"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=png"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=bmp"

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=mpegps"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=mpegts"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=mpegvideo"

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-parser=mjpeg"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-parser=png"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-parser=bmp"

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=http"
```

That should cover all versions of mjpeg? Unless there is something blatent I am missing.

**Comment by chrisjenx** [comment]
@bbcallen `packet-buffering, 0` fixes the issue for the most part, but when the mjpeg stream reaches EOF (which they do as they are predominately broken). IJK stops with:
```bash
07-28 12:59:12.321  32308-32332/tv.danmaku.ijk.media.sample I/IJKMEDIA﹕ ffp_toggle_buffering: completed: OK
07-28 12:59:12.322  32308-32329/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_get_msg: FFP_MSG_COMPLETED
07-28 12:59:12.322  32308-32329/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ FFP_MSG_COMPLETED:
07-28 12:59:12.322  32308-32308/tv.danmaku.ijk.media.sample D/tv.danmaku.ijk.media.widget.VideoView﹕ onCompletion
07-28 12:59:13.332  32308-32332/tv.danmaku.ijk.media.sample I/IJKMEDIA﹕ ffp_toggle_buffering: eof
```

ffplay seems to do something similar where it just stops streaming silently. 

I can work around it, but IJK thinks it's seeking when hitting play. which is this case isn't true:
```
07-28 13:03:23.878  32308-32308/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ IjkMediaPlayer_start
07-28 13:03:23.878  32308-32308/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_start()
07-28 13:03:23.878  32308-32308/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_start()=0
07-28 13:03:23.878  32308-32329/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_get_msg: FFP_REQ_START
07-28 13:03:23.878  32308-32332/tv.danmaku.ijk.media.sample E/IJKMEDIA﹕ http://204.239.12.142/mjpg/video.mjpg: error while seeking
07-28 13:03:23.878  32308-32332/tv.danmaku.ijk.media.sample I/IJKMEDIA﹕ ffp_toggle_buffering: completed: OK
07-28 13:03:23.878  32308-32329/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_get_msg: FFP_MSG_SEEK_COMPLETE
07-28 13:03:23.878  32308-32329/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ FFP_MSG_SEEK_COMPLETE:
07-28 13:03:23.878  32308-32329/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_get_msg: FFP_MSG_COMPLETED
07-28 13:03:23.878  32308-32329/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ FFP_MSG_COMPLETED:
07-28 13:03:23.889  32308-32308/tv.danmaku.ijk.media.sample D/tv.danmaku.ijk.media.widget.VideoView﹕ onSeekComplete
07-28 13:03:23.889  32308-32308/tv.danmaku.ijk.media.sample D/tv.danmaku.ijk.media.widget.VideoView﹕ onCompletion
07-28 13:03:24.889  32308-32332/tv.danmaku.ijk.media.sample I/IJKMEDIA﹕ ffp_toggle_buffering: eof
```

For what it's worth, Mjpeg Streams should be handled as "realtime" streams. Seeking shouldn't really be supported. (Same as RTSP etc)

**Comment by bbcallen** [comment]
1. Maybe reverting this commit from ffmpeg could make ijkplayer stops streaming silently like ffplay
```
commit 90ece6cd690a215cf01b648426cdcaee55516fbf
Author: Zhang Rui <bbcallen@gmail.com>
Date:   Tue Apr 21 17:47:26 2015 +0800

    Revert "Fix url_feof() for file appendings."
    
    This reverts commit 3bd624b4ee355328382295af411f5343b1329f43.
    
    avio_feof() could reset eof_reached which is not expected.
```

2. Calling start() after completed means restart in ijkplayer (also in android.media.MediaPlayer), so, player tries to seek to the beginning. You can add some check before avformat_seek_file() and skip it;

3. There are no "-f" and "-probesize" in ijkplayer, but they can be moved into ijkplayer from ffplay easily.

4. If some features are missing or some bugs exist in both ijkplayer and ffplay, it's recommended to submit issues or a patched to ffmpeg to get more reliable advices. I would merge them from ffplay regularly

**Comment by chrisjenx** [comment]
@bbcallen I have raised an issue with ffplay: https://trac.ffmpeg.org/ticket/4750#ticket hopefully they will address the issue with the prematurly ending stream.

1. I'll try `start()` as a work around for now.

2. Can you point me to which file I can add these too? (My C knowledge is pretty bad, sorry).

3. Issues raised against ffplay(ffmpeg) :+1:

**Comment by bbcallen** [comment]
Most playback feature are implemented in ff_ffplay.c which is based on ffplay.c in ffmpeg.

**Comment by chrisjenx** [comment]
Hi @bbcallen seems like: `-probesize -analyzeduration` are not handled by `ffplay.c` and are passed through to ffmpeg.

I can't see if `avoptions` which are not handled by `ff_ffplay.c` are passed to ffmpeg, from passing in options, I'm pretty certain they aren't.

**Comment by bbcallen** [comment]
-probesize -analyzeduration are supposed to be handled by AVFormatContext.
See libavformat/options_table.h

**Comment by chrisjenx** [comment]
I'm going to close this as the `iformat` you have added + the FormatOptions have it working for me.

There seems to be a pretty epic latency on rtsp streams (4seconds). But I think that will require more messing around with buffering in `ff_play` + ffmpeg flags.
