### ISSUE TITLE
支持amr格式的音频吗

### ISSUE THREAD

**Issue by chenmengxuan2** [Bilibili/ijkplayer#3460]
你好，我集成到项目中后发现没有声音，我们声音的格式是amr的，请问支持amr格式的播放吗

**Comment by raymond1012** [comment]
need enable amr demux and decode

2017-08-10 15:01 GMT+08:00 chenmengxuan2 <notifications@github.com>:

**Comment by chenmengxuan2** [comment]
Excuse me， how to enable amr demux and decode

**Comment by JustDo23** [comment]
# ./configure --list-decoders
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=amrnb"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=amrwb"

# ./configure --list-muxers
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-muxer=amr"

# ./configure --list-demuxers
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=amr"

**Comment by JustDo23** [comment]
默认配置并不支持播放 **`amr`** 格式音频文件。在 **`module-lite.sh`** 文件中添加如下配置

```bash
# ./configure --list-decoders
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=amrnb"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=amrwb"

# ./configure --list-muxers
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-muxer=amr"

# ./configure --list-demuxers
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=amr"
```
