### ISSUE TITLE
WARNING: aarch64-linux-android-pkg-config not found, library detection may fail.

### ISSUE THREAD

**Issue by dovginka** [Bilibili/ijkplayer#3469]
我使用Ubuntu系统编译ijk，在./compile-ffmpeg.sh all 这一步报了一些警告，请问如何解决，我最后是否编译成功了呢？影响使用不？

WARNING: aarch64-linux-android-pkg-config not found, library detection may fail.

--------------------
[*] compile ffmpeg
--------------------
libavfilter/avfiltergraph.c: In function 'avfilter_graph_free':
libavfilter/avfiltergraph.c:132:5: warning: 'resample_lavr_opts' is deprecated (declared at libavfilter/avfilter.h:847) [-Wdeprecated-declarations]
     av_freep(&(*graph)->resample_lavr_opts);
     ^
libavformat/concatdec.c: In function 'detect_stream_specific':
libavformat/concatdec.c:208:9: warning: 'av_bitstream_filter_init' is deprecated (declared at ./libavcodec/avcodec.h:5929) [-Wdeprecated-declarations]
         if (!(bsf = av_bitstream_filter_init("h264_mp4toannexb"))) {
         ^
libavformat/concatdec.c: In function 'concat_read_close':
libavformat/concatdec.c:400:17: warning: 'av_bitstream_filter_close' is deprecated (declared at ./libavcodec/avcodec.h:5973) [-Wdeprecated-declarations]
                 av_bitstream_filter_close(cat->files[i].streams[j].bsf);
                 ^
libavformat/concatdec.c: In function 'filter_packet':
libavformat/concatdec.c:564:9: warning: 'av_bitstream_filter_filter' is deprecated (declared at ./libavcodec/avcodec.h:5961) [-Wdeprecated-declarations]
         ret = av_bitstream_filter_filter(bsf, cs->avctx, NULL,
         ^
libavformat/dump.c: In function 'dump_stream_format':
libavformat/dump.c:462:5: warning: 'codec' is deprecated (declared at libavformat/avformat.h:898) [-Wdeprecated-declarations]
     avctx->properties = st->codec->properties;
     ^
libavformat/dump.c:463:5: warning: 'codec' is deprecated (declared at libavformat/avformat.h:898) [-Wdeprecated-declarations]
     avctx->codec      = st->codec->codec;
     ^
libavformat/dump.c:464:5: warning: 'codec' is deprecated (declared at libavformat/avformat.h:898) [-Wdeprecated-declarations]
     avctx->qmin       = st->codec->qmin;
     ^
libavformat/dump.c:465:5: warning: 'codec' is deprecated (declared at libavformat/avformat.h:898) [-Wdeprecated-declarations]
     avctx->qmax       = st->codec->qmax;

**Comment by raymond1012** [comment]
不影响，告警是因为ffmpeg希望不要使用一些老的api而是使用新的

**Comment by dovginka** [comment]
好的，谢谢
