### ISSUE TITLE
编译 ijk的时候报这个错，什么问题？

### ISSUE THREAD

**Issue by zhangbl** [Bilibili/ijkplayer#347]
$ ./compile-ijk.sh all
profiler build: NO
/cygdrive/e/ijkplayer-master/android/ijkplayer/player-armv5/src/main/jni/Android.mk:1: *** missing separator。 停止。
/cygdrive/e/ijkplayer-master/android
profiler build: NO
Prebuilt       : libijkffmpeg.so <= /cygdrive/e/ijkplayer-master/android/contrib/build/ffmpeg-armv7a/output/
Install        : libijkffmpeg.so => libs/armeabi-v7a/libijkffmpeg.so
/cygdrive/e/ijkplayer-master/android
profiler build: NO
/cygdrive/e/ijkplayer-master/android/ijkplayer/player-x86/src/main/jni/Android.mk:1: *** missing separator。 停止。
/cygdrive/e/ijkplayer-master/android

**Comment by zhangbl** [comment]
why?why?why? The important question is said for three times

**Comment by bbcallen** [comment]
Dunno. I don't have cygwin environment by my hand.

**Comment by hljstardust** [comment]
I occur the question too

**Comment by hljstardust** [comment]
how to resolve?
