### ISSUE TITLE
OnInfoListener那个网络带宽监听怎样才能触发？我一直监听不到回调

### ISSUE THREAD

**Issue by jiaqiangsheng** [Bilibili/ijkplayer#3477]

**Comment by raymond1012** [comment]
OnInfoListener 不是用于监听网络的

**Comment by jiaqiangsheng** [comment]
我没说监听网络，这个不是事件回调监听么？我看监听缓冲开始701，缓冲结束702都可以监听到，但是网络带宽（下载速度）703一直监听不到，源码上不是说当缓冲开始到结束的时候会回调703么？为什么我只能收到701、702的回调事件，而703接收不到回调事件。

**Comment by raymond1012** [comment]
MEDIA_INFO_NETWORK_BANDWIDTH 不支持了，可以定期调用ffp_get_property_int64 FFP_PROP_INT64_TCP_SPEED
