### ISSUE TITLE
播放没有IOD的MP4文件大量无效缓存导致卡顿

### ISSUE THREAD

**Issue by annidy** [Bilibili/ijkplayer#3486]
本地播放正常，网络播放需要很长时间的缓冲。有人遇到吗？
[测试文件](http://1252033264.vod2.myqcloud.com/d7a4cabbvodgzp1252033264/d62f45dc9031868223000127838/f0.mp4)

**Comment by raymond1012** [comment]
视频帧排序问题，按照目前ffmpeg中mov的索引方式，会发生多次seek
