### ISSUE TITLE
iOS有声音无画面，手机发热严重

### ISSUE THREAD

**Issue by zywang** [Bilibili/ijkplayer#3492]
版本和机型信息如下
ijkplayer k0.8.2
iPhone 5s (10.2.1)

问题描述
今天线上一个用户反馈，在我们app内播放所有视频的时候都只有声音没有画面，而且手机很烫。

有没有遇到类似的问题的吗？

请教大神，帮忙分析下可能什么原因，从哪里入手解决呢。

ps:
我猜可能是因为某个原因硬解没打开，使用软解播放导致的。

**Comment by raymond1012** [comment]
这样的描述没人能确认问题

**Comment by ChinaBanana** [comment]
最近也遇到这个问题，可能是视频解码完成后没有放到主线程刷新UI，不知道如何解决
