### ISSUE TITLE
下载播放问题

### ISSUE THREAD

**Issue by willchyis** [Bilibili/ijkplayer#3507]
PV_PLAYER__IjkMediaPlayer模式时
先下载视频到本地，下了一点后就进行播放，黑屏无法播放
日志如下：
error reading header
/storage/emulated/0/Download/20170818.mp4: End of file
/storage/emulated/0/Download/20170818.mp4: Invalid data found when processing input

如先播放下载的一点的视频，再进行断点续传就可以播放了。
同时进行不能播放，只有等完全下载完才能播放！！！

PV_PLAYER__AndroidMediaPlayer模式可以同时进行

请问这怎么解决？

**Comment by raymond1012** [comment]
mp4的头可能在文件尾部，从log来看，应该是确少头部导致的
