### ISSUE TITLE
请问ijkhttphook如何设置？

### ISSUE THREAD

**Issue by fjzboy** [Bilibili/ijkplayer#3508]
在setDatasource时，给url前面加了"ijkhttphook:"，然后播放，断网，再打开网络，
当播放完buffer以后，直接走了onCompletion了，而不是继续播放？ 这个ijkhttphook不是断网重连的作用吗？

**Comment by raymond1012** [comment]
是的，但是需要setOnNativeInvokeListener

**Comment by fjzboy** [comment]
@raymond1012 感谢您的答复， 请教下，这个OnNativeInvokeListener里面做什么处理呢？ 还有没有简单的示例代码？

**Comment by raymond1012** [comment]
用于断网后的回调，没有demo

2017-08-22 17:52 GMT+08:00 哈利萝卜头 <notifications@github.com>:

**Comment by fjzboy** [comment]
@raymond1012  断网以后，在OnNativeInvokeListener可以收到通知，然后重连的逻辑要自己实现？

**Comment by raymond1012** [comment]
也可以直接return ture

2017-08-22 17:59 GMT+08:00 哈利萝卜头 <notifications@github.com>:

**Comment by fjzboy** [comment]
@raymond1012 ，  it works!  thank you so much
