### ISSUE TITLE
无法播放

### ISSUE THREAD

**Issue by asawalker** [Bilibili/ijkplayer#351]
无法播放 优酷PC端的视频地址。
eg："http://k.youku.com/player/getFlvPath/sid/743744984607212cc7aee_00/st/flv/fileid/0300010F0055AD3A385307021AB75A5DC01B37-EEB5-2168-7ECF-3BDA97EB6795?K=b1148da285e0f60324124816&ctype=12&ev=1&oip=2014996627&token=3767&ep=dSaXHU2JX8YE4yPYij8bNH%2FlJSJaXP4J9h%2BFgNIUALshTZnLmk%2FSz5izTvhCFPhoACUDYe6F2NDmGEMTYYU2220Q3U%2BuMfrni4OV5a4hsOEJYWxEdMresVSdRDb2"

请教下为什么？谢谢！

**Comment by Android4MediaPlayer** [comment]
可以播放的，是一个三分十五秒的视频

**Comment by bbcallen** [comment]
Log, plz.

**Comment by Android4MediaPlayer** [comment]
My ijkplayer can play,please give log for can't play this
