### ISSUE TITLE
替换自己编译的ffmpeg库 build ijkplayer失败

### ISSUE THREAD

**Issue by xiasha1988** [Bilibili/ijkplayer#3515]
完全使用ijkplayer自带的代码，build ijkplayer跑demo都是正常的。现替换自己编译的ffmpeg库，build ijkplayer的时候失败

android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ijkavformat/allformats.c:78: error: undefined reference to 'ijkav_register_ijkmediadatasource_protocol'
android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ijkavformat/allformats.c:80: error: undefined reference to 'ijkav_register_async_protocol'
android/ijkplayer/ijkplayer-armv7a/src/main/jni/ijkmedia/ijkplayer/ijkavformat/allformats.c:81: error: undefined reference to 'ijkav_register_ijklongurl_protocol'

有人碰到过类似问题吗？请指教，谢谢！

**Comment by raymond1012** [comment]
ijk 对ffmpeg有很多私有的patch

2017-08-24 14:33 GMT+08:00 xiasha1988 <notifications@github.com>:

**Comment by xiasha1988** [comment]
@raymond1012 能说详细点吗？其他的接口不可以用的，我都手动改了。这个错误不知道怎么改？

**Comment by raymond1012** [comment]
see ijk ffmpeg commit

2017-08-24 15:21 GMT+08:00 xiasha1988 <notifications@github.com>:

**Comment by nishisahlot** [comment]
did any body find any update on this. I am facing the same issue.
