### ISSUE TITLE
每次快进后之前缓冲的都没有了，又重新缓冲

### ISSUE THREAD

**Issue by dcw0505** [Bilibili/ijkplayer#3517]
ios用IJKFFMoviePlayerController初始化播放器，怎么每次快进后之前缓冲的都没有了，又重新缓冲呢？

**Comment by raymond1012** [comment]
use async

**Comment by dcw0505** [comment]
谢谢，那怎么设置async呢

**Comment by raymond1012** [comment]
async:http:xxxx

2017-08-29 10:01 GMT+08:00 dcw0505 <notifications@github.com>:

**Comment by dcw0505** [comment]
NSURL *url = [NSURL URLWithString:@"async:http://112.124.3.146:8088/vedio/test.mp4"];
IJKFFMoviePlayerController *player = [[IJKFFMoviePlayerController alloc] initWithContentURL:url withOptions:options];

是这样的方式吗？
还是在哪里配置？

**Comment by TheLittleBoy** [comment]
@dcw0505   我也试了，不好使啊。你找到解决办法了么？

**Comment by jeff201903** [comment]
我发现好几个issue都是这样，但是回答却都解决不了问题
