### ISSUE TITLE
小屏幕播放，onInfo 方法不能响应

### ISSUE THREAD

**Issue by Mongolian** [Bilibili/ijkplayer#352]
我在做小屏幕播放的时候，Videoview 上面覆盖一个默认图，当播放的时候注册的OnInfoListener 监听回调会经常不能执行，导致的结果就是视频已经开始播放，还是显示的默认图，请问这个是什么原因呢？有办法解决么~

**Comment by Android4MediaPlayer** [comment]
network is good,the buffer_info_start or buffer_info_end won't be notyfied.

**Comment by Android4MediaPlayer** [comment]
you can add like VIDEO_RENDERING_START for android

**Comment by Mongolian** [comment]
network is good ,this  onInfo(IMediaPlayer mp, int what, int extra) not call

**Comment by bbcallen** [comment]
There is no guarantee what, when and how onInfo would return.
You should always determine the prepared event by OnPreparedListener.
