### ISSUE TITLE
4倍速播放m4a音频文件没效果

### ISSUE THREAD

**Issue by eaggle** [Bilibili/ijkplayer#3521]
4倍速播放m4a音频文件没效果，但是1.3334倍速播放有效果，在安卓7.0  谷歌pixel机型跟华为mate8上面都是这样，会是什么原因呢？

**Comment by raymond1012** [comment]
only support 0.5~2.0

2017-08-25 16:38 GMT+08:00 eaggle <notifications@github.com>:

**Comment by eaggle** [comment]
thanks
