### ISSUE TITLE
报错 error reading header / End of file 

### ISSUE THREAD

**Issue by cnghost** [Bilibili/ijkplayer#3523]
08-28 17:12:45.392 16333-17046/com.mjnet.yz E/IJKMEDIA: error reading header
08-28 17:12:45.392 16333-17046/com.mjnet.yz E/IJKMEDIA: http://127.0.0.1:9501/%E4%BD%A0%E7%9A%84%E5%90%8D%E5%AD%97.mp4: End of file
08-28 17:12:45.393 16333-16333/com.mjnet.yz E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

同样的url地址，我用vlc播放没问题，用ijkplayer就报这个错。
这个URL偶然性的会播放成功，20次会出现1次吧。其他时候都是这个错。

**Comment by raymond1012** [comment]
主要是对mp4 demux的方式不同导致的，如果你要用ijk，那么就应该使用符合ffmpeg demux的mp4

**Comment by gongtingshisi** [comment]
我遇到类似的问题。E/IJKMEDIA(23469): error reading header
E/IJKMEDIA(23469): http://********.mp4: Invalid data found when processing input

**Comment by gongtingshisi** [comment]
I/IJKMEDIA(23469): ===== versions =====
I/IJKMEDIA(23469): ijkplayer    : k0.8.4
I/IJKMEDIA(23469): FFmpeg       : ff3.3--ijk0.8.0--20170829--001
I/IJKMEDIA(23469): libavutil    : 55.58.100
I/IJKMEDIA(23469): libavcodec   : 57.89.100
I/IJKMEDIA(23469): libavformat  : 57.71.100
I/IJKMEDIA(23469): libswscale   : 4.6.100
I/IJKMEDIA(23469): libswresample: 2.7.100
I/IJKMEDIA(23469): ===== options =====
I/IJKMEDIA(23469): player-opts : loop                         = 1
I/IJKMEDIA(23469): format-opts : ijkapplication               = -653944848
I/IJKMEDIA(23469): format-opts : ijkiomanager                 = -606331520
I/IJKMEDIA(23469): ===================

**Comment by wangqi-jeffrey** [comment]
I also encountered the same problem, the last video still played properly, open the next video when an error, and continue to load.
`2020-03-22 13:37:26.482 13735-13735/com.stx.openeyes E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xca9b50c0)
2020-03-22 13:37:26.482 13735-13735/com.stx.openeyes E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xca9b5100)
2020-03-22 13:37:26.482 13735-13735/com.stx.openeyes E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xca9b5140)
2020-03-22 13:37:27.223 13735-13864/com.stx.openeyes E/IJKMEDIA: error reading header
2020-03-22 13:37:27.223 13735-13864/com.stx.openeyes E/IJKMEDIA: /storage/emulated/0/Android/data/com.stx.openeyes/cache/video-cache/e24a332d438ef2a8d5dca163003283d5: End of file`

**Comment by cnghost** [comment]
ijkplayer-android/android/contrib/ffmpeg-arm64/libavformat/mov.c
ijkplayer-android/android/contrib/ffmpeg-armv7a/libavformat/mov.c


static void mov_fix_index(MOVContext *mov, AVStream *st) 函数中
注释掉此LOG，end of file错误不再出现
av_log(mov-&gt;fc, AV_LOG_DEBUG, "stts: %"PRId64" ctts: %"PRId64", ctts_index: %"PRId64", ctts_count: %"PRId64"\n",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;curr_cts, curr_ctts, ctts_index_old, ctts_count_old);







------------------&nbsp;Original&nbsp;------------------
