### ISSUE TITLE
android studio上如何最快速配置好ijkplayer

### ISSUE THREAD

**Issue by Kasail** [Bilibili/ijkplayer#3529]
我在项目的build.gradle里添加了这两个依赖
![image](https://user-images.githubusercontent.com/30954027/29865221-928b8cc8-8da7-11e7-955a-3a1d2a62244d.png)
之后在Activity里使用是可以看到若干IJK相关类的，但是没有IjkVideoView这个类，在布局文件中也用不了这个控件，是不是我还少了很多配置步骤？  
可以简明列举一下步骤吗

**Comment by Kasail** [comment]
老司机带带路？

**Comment by raymond1012** [comment]
see readme
