### ISSUE TITLE
why  build libijkffmpeg.so only？

### ISSUE THREAD

**Issue by zhangbl** [Bilibili/ijkplayer#353]
build on cygwin  ndk r10e

$ ./compile-ijk.sh all
profiler build: NO
/cygdrive/e/ijkplayer-master/android/ijkplayer/player-armv5/src/main/jni/Android.mk:1: *** missing separator。 Stop。
/cygdrive/e/ijkplayer-master/android
profiler build: NO
[armeabi-v7a] Prebuilt       : libijkffmpeg.so <= /cygdrive/e/ijkplayer-master/android/contrib/build/ffmpeg-armv7a/output/
[armeabi-v7a] Install        : libijkffmpeg.so => libs/armeabi-v7a/libijkffmpeg.so
/cygdrive/e/ijkplayer-master/android
profiler build: NO
/cygdrive/e/ijkplayer-master/android/ijkplayer/player-x86/src/main/jni/Android.mk:1: *** missing separator。 Stop。
/cygdrive/e/ijkplayer-master/android

**Comment by x64Dev** [comment]
You found the solution?
