### ISSUE TITLE
拖动时，下载的位置不是拖动到的位置，加载时间比较长

### ISSUE THREAD

**Issue by jiutianxuanyao** [Bilibili/ijkplayer#3537]
1、m3u8地址视频拖动时，短视频缓冲时间短，长视频缓冲时间长。
2、缓冲过程中，一直有ts下载，且速度并不慢。
观察发现：拖动时，下载的位置并不是拖动到的位置，而是从拖动到的位置前一段距离开始下载的，如果短视频，需要下载的ts比较少，长视频需要下载的ts比较多，所以短视频缓冲时间短，长视频缓冲时间长，而这个播放器应该需要下载到拖动的位置才会播放。
问：请问这个是流的问题，还是播放器的问题？

**Comment by TonyJR** [comment]
播放位置与拖动位置不同是因为视频必须从关键帧开始渲染，所以当你seek某个时间点的时候，实际播放位置是这个时间点前面的第一个关键帧

**Comment by jiutianxuanyao** [comment]
已结解决，流的问题，据说是时间不对造成的
