### ISSUE TITLE
怎么控制缓冲区的大小，

### ISSUE THREAD

**Issue by aiHiNiHao** [Bilibili/ijkplayer#3538]
现在我的情况是：当播放器暂停时，会把整个视频文件都给缓冲，就算断网了也可以看完视频，造成流量的浪费，怎么能暂停时让播放器只缓冲当前时间以后固定的长度，

**Comment by raymond1012** [comment]
setoption  min-frames or max-buffer-size

**Comment by aiHiNiHao** [comment]
setPropertyLong()?

**Comment by raymond1012** [comment]
setoption

2017-09-04 10:35 GMT+08:00 aiHiNiHao <notifications@github.com>:

**Comment by aiHiNiHao** [comment]
Thank you
