### ISSUE TITLE
ijkplayer走到OnErrorListener之后,怎么重新回复到IDLE状态

### ISSUE THREAD

**Issue by hankooxiaozei** [Bilibili/ijkplayer#3539]
断网之后会走到onError方法中,目前的播放器的状态应该是ERROR,然后我想调用reset回到IDLE状态,但是播放器并没有,这时候setDatasource依然会抛非法状态异常,我应该怎么使播放器回到IDLE状态呢,重新new一个吗

**Comment by raymond1012** [comment]
recreate player
