### ISSUE TITLE
0.8.2不支持rtmp协议，已经选择默认配置文件编译

### ISSUE THREAD

**Issue by zllikey** [Bilibili/ijkplayer#3540]
09-03 23:28:46.429 2555-2760/ W/IJKMEDIA: remove 'timeout' option for rtmp.
09-03 23:28:46.429 2555-2760/ E/IJKMEDIA: Protocol 'rtmp' not on whitelist 'async,cache,crypto,file,http,https,ijkhttphook,ijkinject,ijklivehook,ijklongurl,ijksegment,ijktcphook,pipe,rtp,tcp,tls,udp,ijkurlhook,data'!
09-03 23:28:46.433 2555-2760/ E/IJKMEDIA: rtmp://live.hkstv.hk.lxdns.com/live/hks: Invalid argument
错误提示

**Comment by zllikey** [comment]
找到解决方法了，用了setdatasource(url,header),此方法有问题
用回setdatasource(url)解决

**Comment by nq117** [comment]
请问怎么配置的

**Comment by zllikey** [comment]
@nq117 主页有提示编译配置文件

**Comment by nq117** [comment]
@zllikey 没有看到配置直播流的  请指教一下  谢谢

**Comment by hywenbinger** [comment]
@nq117,the mean is use setDataSource(String fileName),please try again.
