### ISSUE TITLE
在线播放MP4，一段时间后会自己停止，然后报错

### ISSUE THREAD

**Issue by wlxfxy** [Bilibili/ijkplayer#3541]
E IJKMEDIA: stream 1, offset 0x1f4197a: partial file
E IJKMEDIA: av_read_frame error: ffffff98(�,�,�,�): unknown
E IJKMEDIA: Invalid NAL unit size (2135 > 1636).
E IJKMEDIA: Error splitting the input into NAL units.
E IJKMEDIA: stream 1, offset 0x1f41b44: partial file
E IJKMEDIA: av_read_frame error: ffffff98(�,�,�,�): unknown
I IJKMEDIA: ffp_toggle_buffering: error: -104
E IJKMEDIA: stream 1, offset 0x1f42049: partial file
D IJKMEDIA: FFP_MSG_ERROR: 0
E tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
E IJKMEDIA: av_read_frame error: ffffff98(�,�,�,�): unknown
D IJKMEDIA: IjkMediaPlayer_release

**Comment by raymond1012** [comment]
source file issue

**Comment by huangxiankui** [comment]
想问下这个问题是怎么处理的呢，是什么原因

**Comment by shenguojun** [comment]
同样遇到，留个言

**Comment by shenguojun** [comment]
https://github.com/Bilibili/ijkplayer/issues/445 找到办法了，需要设置```setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "reconnect", 1)```

**Comment by robinx2012** [comment]
> #445 找到办法了，需要设置`setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "reconnect", 1)`

+1
