### ISSUE TITLE
请问播放mov格式的  有画面没有声音  是怎么一回事

### ISSUE THREAD

**Issue by nq117** [Bilibili/ijkplayer#3542]
09-04 10:53:46.461 8145-8145/com.ijk.nq I/IJKMEDIA: ===== versions =====
09-04 10:53:46.461 8145-8145/com.ijk.nq I/IJKMEDIA: ijkplayer    : k0.8.2
09-04 10:53:46.461 8145-8145/com.ijk.nq I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170710--001
09-04 10:53:46.461 8145-8145/com.ijk.nq I/IJKMEDIA: libavutil    : 55.58.100
09-04 10:53:46.461 8145-8145/com.ijk.nq I/IJKMEDIA: libavcodec   : 57.89.100
09-04 10:53:46.461 8145-8207/com.ijk.nq I/IJKMEDIA: SDL_RunThread: [8207] ff_msg_loop
09-04 10:53:46.461 8145-8145/com.ijk.nq I/IJKMEDIA: libavformat  : 57.71.100
09-04 10:53:46.461 8145-8207/com.ijk.nq D/IJKMEDIA: message_loop
09-04 10:53:46.461 8145-8145/com.ijk.nq I/IJKMEDIA: libswscale   : 4.6.100
09-04 10:53:46.461 8145-8145/com.ijk.nq I/IJKMEDIA: libswresample: 2.7.100
09-04 10:53:46.461 8145-8145/com.ijk.nq I/IJKMEDIA: ===== options =====
09-04 10:53:46.461 8145-8145/com.ijk.nq I/IJKMEDIA: player-opts : mediacodec                   = 0
09-04 10:53:46.461 8145-8145/com.ijk.nq I/IJKMEDIA: player-opts : opensles                     = 0
09-04 10:53:46.461 8145-8145/com.ijk.nq I/IJKMEDIA: player-opts : overlay-format               = 842225234
09-04 10:53:46.462 8145-8145/com.ijk.nq I/IJKMEDIA: player-opts : framedrop                    = 1
09-04 10:53:46.462 8145-8145/com.ijk.nq I/IJKMEDIA: player-opts : start-on-prepared            = 0
09-04 10:53:46.462 8145-8145/com.ijk.nq I/IJKMEDIA: format-opts : ijkapplication               = -1618055984
09-04 10:53:46.462 8145-8207/com.ijk.nq D/IJKMEDIA: FFP_MSG_FLUSH:
09-04 10:53:46.462 8145-8145/com.ijk.nq I/IJKMEDIA: format-opts : ijkiomanager                 = -1882453840
09-04 10:53:46.462 8145-8145/com.ijk.nq I/IJKMEDIA: format-opts : http-detect-range-support    = 0
09-04 10:53:46.462 8145-8145/com.ijk.nq I/IJKMEDIA: format-opts : timeout                      = 10000000
09-04 10:53:46.462 8145-8145/com.ijk.nq I/IJKMEDIA: format-opts : reconnect                    = 1
09-04 10:53:46.462 8145-8145/com.ijk.nq I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
09-04 10:53:46.462 8145-8145/com.ijk.nq I/IJKMEDIA: ===================
09-04 10:53:46.465 8145-8208/com.ijk.nq I/IJKMEDIA: SDL_RunThread: [8208] ff_vout
09-04 10:53:46.465 8145-8145/com.ijk.nq D/IJKMEDIA: ijkmp_prepare_async()=0
09-04 10:53:46.468 8145-8209/com.ijk.nq I/IJKMEDIA: SDL_RunThread: [8209] ff_read
09-04 10:53:46.468 8145-8209/com.ijk.nq D/IJKMEDIA: Setting default whitelist 'file,crypto'
09-04 10:53:46.503 8145-8209/com.ijk.nq D/IJKMEDIA: Format mov,mp4,m4a,3gp,3g2,mj2 probed with size=2048 and score=100
09-04 10:53:46.504 8145-8209/com.ijk.nq D/IJKMEDIA: ISO: File Type Major Brand: qt  
09-04 10:53:46.510 8145-8145/com.ijk.nq W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
09-04 10:53:46.620 8145-8209/com.ijk.nq D/IJKMEDIA: Unknown dref type 0x206c7275 size 12
09-04 10:53:46.625 8145-8209/com.ijk.nq D/IJKMEDIA: Unknown dref type 0x206c7275 size 12
09-04 10:53:46.626 8145-8209/com.ijk.nq E/IJKMEDIA: Option ijkapplication not found.
09-04 10:53:46.626 8145-8209/com.ijk.nq D/IJKMEDIA: Before avformat_find_stream_info() pos: 87653503 bytes read:97399 seeks:2 nb_streams:2
09-04 10:53:46.627 8145-8209/com.ijk.nq D/IJKMEDIA: nal_unit_type: 7, nal_ref_idc: 3
09-04 10:53:46.627 8145-8209/com.ijk.nq D/IJKMEDIA: nal_unit_type: 8, nal_ref_idc: 3
09-04 10:53:46.633 8145-8209/com.ijk.nq D/IJKMEDIA: nal_unit_type: 5, nal_ref_idc: 3
09-04 10:53:46.634 8145-8209/com.ijk.nq I/IJKMEDIA: Reinit context to 1280x720, pix_fmt: yuv420p
09-04 10:53:46.657 8145-8209/com.ijk.nq D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
09-04 10:53:46.672 8145-8209/com.ijk.nq D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
09-04 10:53:46.683 8145-8209/com.ijk.nq D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
09-04 10:53:46.700 8145-8209/com.ijk.nq D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
09-04 10:53:46.729 8145-8209/com.ijk.nq D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
09-04 10:53:46.737 8145-8209/com.ijk.nq D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
09-04 10:53:46.790 8145-8209/com.ijk.nq D/IJKMEDIA: All info found
09-04 10:53:46.791 8145-8209/com.ijk.nq D/IJKMEDIA: After avformat_find_stream_info() pos: 1509376 bytes read:1345927 seeks:4 frames:61
09-04 10:53:46.791 8145-8209/com.ijk.nq I/IJKMEDIA: max_frame_duration: 10.000
09-04 10:53:46.791 8145-8209/com.ijk.nq I/IJKMEDIA: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/PapaGo/PapaGo/2017_0101_020502_139A.MOV':
09-04 10:53:46.791 8145-8209/com.ijk.nq I/IJKMEDIA:   Metadata:
09-04 10:53:46.791 8145-8209/com.ijk.nq I/IJKMEDIA:     major_brand     : 
09-04 10:53:46.791 8145-8209/com.ijk.nq I/IJKMEDIA: qt  
09-04 10:53:46.791 8145-8209/com.ijk.nq I/IJKMEDIA:     minor_version   : 
09-04 10:53:46.791 8145-8209/com.ijk.nq I/IJKMEDIA: 0
09-04 10:53:46.791 8145-8209/com.ijk.nq I/IJKMEDIA:     compatible_brands: 
09-04 10:53:46.791 8145-8209/com.ijk.nq I/IJKMEDIA: qt  
09-04 10:53:46.791 8145-8209/com.ijk.nq I/IJKMEDIA:     creation_time   : 
09-04 10:53:46.791 8145-8209/com.ijk.nq I/IJKMEDIA: 2017-01-01T02:06:02.000000Z
09-04 10:53:46.791 8145-8209/com.ijk.nq I/IJKMEDIA:     original_format : 
09-04 10:53:46.791 8145-8209/com.ijk.nq I/IJKMEDIA: NVT-IM
09-04 10:53:46.792 8145-8209/com.ijk.nq I/IJKMEDIA:     original_format-eng: 
09-04 10:53:46.792 8145-8209/com.ijk.nq I/IJKMEDIA: NVT-IM
09-04 10:53:46.792 8145-8209/com.ijk.nq I/IJKMEDIA:     comment         : 
09-04 10:53:46.792 8145-8209/com.ijk.nq I/IJKMEDIA: CarDV-TURNKEY
09-04 10:53:46.792 8145-8209/com.ijk.nq I/IJKMEDIA:     comment-eng     : 
09-04 10:53:46.792 8145-8209/com.ijk.nq I/IJKMEDIA: CarDV-TURNKEY
09-04 10:53:46.792 8145-8209/com.ijk.nq I/IJKMEDIA:   Duration: 
09-04 10:53:46.792 8145-8209/com.ijk.nq I/IJKMEDIA: 00:01:00.00
09-04 10:53:46.792 8145-8209/com.ijk.nq I/IJKMEDIA: , start: 
09-04 10:53:46.792 8145-8209/com.ijk.nq I/IJKMEDIA: 0.000000
09-04 10:53:46.792 8145-8209/com.ijk.nq I/IJKMEDIA: , bitrate: 
09-04 10:53:46.792 8145-8209/com.ijk.nq I/IJKMEDIA: 11687 kb/s
09-04 10:53:46.792 8145-8209/com.ijk.nq I/IJKMEDIA:     Stream #0:0
09-04 10:53:46.792 8145-8209/com.ijk.nq I/IJKMEDIA: (eng)
09-04 10:53:46.792 8145-8209/com.ijk.nq D/IJKMEDIA: , 60, 1/60000
09-04 10:53:46.792 8145-8209/com.ijk.nq I/IJKMEDIA: : Video: h264, 1 reference frame (avc1 / 0x31637661), yuv420p(left), 1280x720, 0/1, 9819 kb/s
09-04 10:53:46.793 8145-8209/com.ijk.nq I/IJKMEDIA: , 
09-04 10:53:46.793 8145-8209/com.ijk.nq I/IJKMEDIA: 60 fps, 
09-04 10:53:46.793 8145-8209/com.ijk.nq I/IJKMEDIA: 60 tbr, 
09-04 10:53:46.793 8145-8209/com.ijk.nq I/IJKMEDIA: 60k tbn, 
09-04 10:53:46.793 8145-8209/com.ijk.nq I/IJKMEDIA: 120 tbc
09-04 10:53:46.793 8145-8209/com.ijk.nq I/IJKMEDIA:  (default)
09-04 10:53:46.793 8145-8209/com.ijk.nq I/IJKMEDIA:     Metadata:
09-04 10:53:46.793 8145-8209/com.ijk.nq I/IJKMEDIA:       creation_time   : 
09-04 10:53:46.793 8145-8209/com.ijk.nq I/IJKMEDIA: 2017-01-01T02:06:02.000000Z
09-04 10:53:46.793 8145-8209/com.ijk.nq I/IJKMEDIA:       handler_name    : 
09-04 10:53:46.793 8145-8209/com.ijk.nq I/IJKMEDIA: DataHandler
09-04 10:53:46.793 8145-8209/com.ijk.nq I/IJKMEDIA:       encoder         : 
09-04 10:53:46.793 8145-8209/com.ijk.nq I/IJKMEDIA: h264
09-04 10:53:46.793 8145-8209/com.ijk.nq I/IJKMEDIA:     Stream #0:1
09-04 10:53:46.793 8145-8209/com.ijk.nq I/IJKMEDIA: (eng)
09-04 10:53:46.793 8145-8209/com.ijk.nq D/IJKMEDIA: , 1, 1/32000
09-04 10:53:46.793 8145-8209/com.ijk.nq I/IJKMEDIA: : Audio: pcm_s16le (sowt / 0x74776F73), 32000 Hz, 1 channels, 512 kb/s
09-04 10:53:46.793 8145-8209/com.ijk.nq I/IJKMEDIA:  (default)
09-04 10:53:46.794 8145-8209/com.ijk.nq I/IJKMEDIA:     Metadata:
09-04 10:53:46.794 8145-8209/com.ijk.nq I/IJKMEDIA:       creation_time   : 
09-04 10:53:46.794 8145-8209/com.ijk.nq I/IJKMEDIA: 2017-01-01T02:06:02.000000Z
09-04 10:53:46.794 8145-8209/com.ijk.nq I/IJKMEDIA:       handler_name    : 
09-04 10:53:46.794 8145-8209/com.ijk.nq I/IJKMEDIA: DataHandler
09-04 10:53:46.794 8145-8209/com.ijk.nq W/IJKMEDIA: No codec could be found with id 65536
09-04 10:53:46.794 8145-8209/com.ijk.nq D/IJKMEDIA: detected 4 logical cores
09-04 10:53:46.794 8145-8209/com.ijk.nq D/IJKMEDIA: nal_unit_type: 7, nal_ref_idc: 3
09-04 10:53:46.794 8145-8209/com.ijk.nq D/IJKMEDIA: nal_unit_type: 8, nal_ref_idc: 3
09-04 10:53:46.795 8145-8209/com.ijk.nq I/IJKMEDIA: VideoCodec: avcodec, h264
09-04 10:53:46.796 8145-8209/com.ijk.nq W/IJKMEDIA: fps: 60.000000 (too high)
09-04 10:53:46.796 8145-8209/com.ijk.nq W/IJKMEDIA: fps: 60.000000 (too high)
09-04 10:53:46.796 8145-8207/com.ijk.nq D/IJKMEDIA: FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
09-04 10:53:46.796 8145-8207/com.ijk.nq D/IJKMEDIA: FFP_MSG_SAR_CHANGED: 0, 1
09-04 10:53:46.796 8145-8207/com.ijk.nq D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_PREPARED
09-04 10:53:46.796 8145-8207/com.ijk.nq D/IJKMEDIA: FFP_MSG_PREPARED:
09-04 10:53:46.796 8145-8230/com.ijk.nq I/IJKMEDIA: SDL_RunThread: [8230] ff_video_dec
09-04 10:53:46.797 8145-8207/com.ijk.nq D/IJKMEDIA: FFP_MSG_VIDEO_ROTATION_CHANGED: 0
09-04 10:53:46.797 8145-8230/com.ijk.nq D/IJKMEDIA: ffp_toggle_buffering_l: start
09-04 10:53:46.797 8145-8207/com.ijk.nq D/IJKMEDIA: FFP_MSG_BUFFERING_START:
09-04 10:53:46.798 8145-8145/com.ijk.nq D/IjkVideoView: MEDIA_INFO_VIDEO_ROTATION_CHANGED: 0
                                                        
                                                        [ 09-04 10:53:46.798  8145: 8145 E/         ]
                                                        SurfaceView doesn't support rotation (0)!
09-04 10:53:46.831 8145-8145/com.ijk.nq D/IJKMEDIA: IjkMediaPlayer_start
09-04 10:53:46.831 8145-8145/com.ijk.nq D/IJKMEDIA: ijkmp_start()
09-04 10:53:46.831 8145-8207/com.ijk.nq D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
09-04 10:53:46.831 8145-8207/com.ijk.nq D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START: start on fly
09-04 10:53:46.831 8145-8145/com.ijk.nq D/IJKMEDIA: ijkmp_start()=0
09-04 10:53:46.837 8145-8207/com.ijk.nq D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
09-04 10:53:46.837 8145-8207/com.ijk.nq D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START: start on fly
09-04 10:53:46.838 8145-8225/com.ijk.nq D/IJKMEDIA: nal_unit_type: 5, nal_ref_idc: 3
09-04 10:53:46.838 8145-8225/com.ijk.nq I/IJKMEDIA: Reinit context to 1280x720, pix_fmt: yuv420p
09-04 10:53:46.843 8145-8226/com.ijk.nq D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
09-04 10:53:46.850 8145-8227/com.ijk.nq D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
09-04 10:53:46.856 8145-8228/com.ijk.nq D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
09-04 10:53:46.865 8145-8229/com.ijk.nq D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
09-04 10:53:46.869 8145-8230/com.ijk.nq D/IJKMEDIA: SDL_VoutFFmpeg_CreateOverlay(w=1280, h=720, fmt=RV32(0x32335652, dp=0x8fcc47e0)
09-04 10:53:46.874 8145-8207/com.ijk.nq D/IJKMEDIA: FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
09-04 10:53:46.877 8145-8230/com.ijk.nq D/IJKMEDIA: Video: first frame decoded
09-04 10:53:46.877 8145-8225/com.ijk.nq D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
09-04 10:53:46.877 8145-8207/com.ijk.nq D/IJKMEDIA: FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
09-04 10:53:46.877 8145-8230/com.ijk.nq D/IJKMEDIA: SDL_VoutFFmpeg_CreateOverlay(w=1280, h=720, fmt=RV32(0x32335652, dp=0x8fcc47e0)
09-04 10:53:46.889 8145-8226/com.ijk.nq D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
09-04 10:53:46.892 8145-8230/com.ijk.nq D/IJKMEDIA: SDL_VoutFFmpeg_CreateOverlay(w=1280, h=720, fmt=RV32(0x32335652, dp=0x8fcc47e0)
09-04 10:53:46.892 8145-8207/com.ijk.nq D/IJKMEDIA: FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
09-04 10:53:46.904 8145-8227/com.ijk.nq D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
09-04 10:53:46.938 8145-8209/com.ijk.nq D/IJKMEDIA: ffp_toggle_buffering_l: end
09-04 10:53:46.940 8145-8207/com.ijk.nq D/IJKMEDIA: FFP_MSG_BUFFERING_END:
09-04 10:53:46.949 8145-8208/com.ijk.nq D/IJKMEDIA: ANativeWindow_setBuffersGeometry: w=1280, h=720, f=(0x4) => w=1280, h=720, f=RV32(0x32335652)
09-04 10:53:46.955 8145-8207/com.ijk.nq D/IJKMEDIA: FFP_MSG_VIDEO_RENDERING_START:
09-04 10:53:46.955 8145-8145/com.ijk.nq I/tv.danmaku.ijk.media.player.IjkMediaPlayer: Info: MEDIA_INFO_VIDEO_RENDERING_START

**Comment by raymond1012** [comment]
need enable pcm s16le

**Comment by lawn1** [comment]
enable pcm s16le
 在哪个文件里面改，有没有操作步骤

**Comment by lawn1** [comment]
@raymond1012 
enable pcm s16le
在哪个文件里面改，有没有操作步骤

**Comment by lawn1** [comment]
@nq117 在吗

**Comment by nq117** [comment]
怎么了




| |
ltwp163163
邮箱：ltwp163163@163.com
|

Signature is customized by Netease Mail Master

在2018年07月03日 01:30，lawn1 写道：

@nq117 在吗
