### ISSUE TITLE
[Android]屏蔽视频声音问题

### ISSUE THREAD

**Issue by jeffreyxuworld** [Bilibili/ijkplayer#3554]
环境：ijk+里面集成的ExoPlayer
用ijk mediaPlayer对象去屏蔽,不起作用
用的audioManager.setStreamMute(AudioManager.STREAM_MUSIC, true);用全局audioManager去屏蔽的，但是按音量加键会恢复声音；
希望项目维护人员，可以帮忙修复更新下问题；

**Comment by raymond1012** [comment]
直接setoption an ，audio将不会解码

**Comment by jeffreyxuworld** [comment]
没有使用IjkMediaPlayer，用的initEXOPlayer，所以没有initIJKOption、setOption的东西。

**Comment by jeffreyxuworld** [comment]
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "audio_disable", 1);    
对IjkMediaPlayer应该是不适用吧

**Comment by raymond1012** [comment]
setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "an", 1);

2017-09-07 15:45 GMT+08:00 JeffreyWorld <notifications@github.com>:

**Comment by jeffreyxuworld** [comment]
对IjkExoMediaPlayer应该是不起左右，没走ijk option相关的东西；

**Comment by raymond1012** [comment]
ExoMediaPlayer 不支持

2017-09-07 16:04 GMT+08:00 JeffreyWorld <notifications@github.com>:

**Comment by jeffreyxuworld** [comment]
IjkExoMediaPlayer有什么好的解决方案？我这边试过很多，目前还是不行，想做到类似屏蔽了视频列表的声音后，比如在微博里看视频列表，点音量加键不会恢复声音，保持屏蔽状态
