### ISSUE TITLE
AndroidMediaPlayer和IjkMediaPlayer硬解区别？

### ISSUE THREAD

**Issue by hywenbinger** [Bilibili/ijkplayer#3555]
最近在项目中接入了ijkplayer，new IjkMediaPlayer时，mediacodec-all-videos置为1，看内部逻辑是调用了ffpipenode_create_video_decoder_from_android_mediacodec，请问：它和AndroidMediaPlayer有什么区别吗？

**Comment by raymond1012** [comment]
本质基本一样
