### ISSUE TITLE
使用私有协议的第三模块接收到的视频buffer流 如何使用ijkplayer进行解码播放？

### ISSUE THREAD

**Issue by sparkjin2015** [Bilibili/ijkplayer#3558]
使用java soceket实现私有协议 解析出视频流buffer (h.264 )
如何快速接入到ijkplayer? 使用ijkplayer解码并播放？

**Comment by raymond1012** [comment]
参见ijk video_thread 解码线程，填充pkg queue

**Comment by sparkjin2015** [comment]
可以通过实现IAndroidIO接口 达到上面的目的吗？

**Comment by raymond1012** [comment]
可以
