### ISSUE TITLE
get_video_frame的疑惑

### ISSUE THREAD

**Issue by zcgit** [Bilibili/ijkplayer#3559]
大家好，我在查看源码的时候看到ff_ffplay.c文件中的get_video_frame方法中有个计算diff的地方，大致意思应该是当前该视频帧应该显示的时间和当前音频时钟的时间差，如果时间差小于AV_NOSYNC_THRESHOLD就丢弃该视频帧，那这里岂不是很容易就丢帧了？我的理解是这里的视频dpts很难和当前的音频时钟对上吧，那就导致一直丢帧，画面不刷新的问题，不知道我哪里理解不对了，希望看到并能帮助我的人解答疑惑，谢谢大家了。

**Comment by raymond1012** [comment]
首先你要enable framedrop，才会触发，另外framedrop的逻辑最多也只会一半的帧

**Comment by zcgit** [comment]
恩，你好，我确实打开了framedrop这个，现在我发现在播放1080p的时候就会经常遇到视频的dpts和音频时间戳对不上，我猜测是不是因为解码的时候cpu效率跟不上，导致解码视频的速度慢了导致的。<br/><br/>我看了这个链接：https://github.com/Bilibili/ijkplayer/pull/3325 ，其中他说到：”**因为在弱网情况下，会出现音频在渲染中，但是在视频解码线程中解码当前帧是B帧，或者连续B帧，就不会马上出YUV数据，这个时候yuv的队列中又没有一帧数据，导致音频一直在渲染，而视频卡在第一个B帧之前的图像上，一直到没有视频的packet才会挂起操作。这个时候音频已经跑在视频前面一段时间了，当恢复播放后，就会导致视频帧会快速播放来同步音频数据。**”，<br/><br/>我遇到的情况和这个非常类似，但是，不同的是我播放本地的1080p(iphone6p录制的)，也会遇到这里频繁丢帧的情况，我想问一下，如果是因为我cpu不够快（或者我的CPU波动比较大，因为我还有其他的非播放逻辑需要处理，需要每帧做一些其他操作）是不是就会非常容易出现这种情况呢？

**Comment by raymond1012** [comment]
你的问题和3325无关，enable mediacodec试试，如果还是不行，就是机器性能问题

**Comment by zcgit** [comment]
ok，多谢了，我目前还没用硬解码部分，我用的机器是iphone6P，我试着打开ffmpeg自身的videotoolbox，但是貌似没什们用，我看IJKPLAYER是自己使用了videotoolbox的，难道ffmpeg没有用吗？还有一个，我说明下我的使用环境吧：<br/>
我目前是在游戏中集成ffmpeg，我直接在游戏的每帧里面去刷新画面，调用video_refresh获取视频数据在opengl里绘制，这样我觉得理论上是没问题的，我本想直接集成ijkplayer这样可以减少不少工作量，但是这样的话，我的游戏里就会出现一个ijkplayer的openlgview和一个游戏本身的openglview，不太方便以后操作opengl，而且最大的问题是ijkplayer里面用到了大量的函数指针，导致集成起来很麻烦。<br/>
您觉得我这种使用环境会影响到视频播放吗？<br/>

**Comment by zcgit** [comment]
我找到问题了，因为我是每帧(1.0/60秒)去调用刷新界面的，对于高清视频来说太占CPU了，所以我将帧率下降到30左右就明显改善了。

**Comment by zmobs** [comment]
> 我找到问题了，因为我是每帧(1.0/60秒)去调用刷新界面的，对于高清视频来说太占CPU了，所以我将帧率下降到30左右就明显改善了。不过有一个问题，就是ffmpeg自带的videotoolbox有起作用吗？我打开了编译条件之后，发现变化不大。@raymond1012

我遇到了跟您一样的情况。 请问你针对这种情况是怎么修复的
