### ISSUE TITLE
Link issue

### ISSUE THREAD

**Issue by mars-rover** [Bilibili/ijkplayer#356]
when I am trying to tailor your code into my project, I encounter a issue:
Undefined symbols for architecture i386:
  "_SDL_CreateThreadEx", referenced from:
      _ijkmp_prepare_async_l in ijkplayer.o
      _stream_open in ff_ffplay.o
      _decoder_start in ff_ffplay.o
ld: symbol(s) not found for architecture i386
how could I solve it? Have any one encounter this issue like me?

**Comment by bbcallen** [comment]
Did you succeed to run Demo?
Did you add library in "Build Phases" -> "Link Binary With Libraries"?

**Comment by mars-rover** [comment]
Yes, I have succeed to run Demo, And I have added libraries. I can run this on iPhone but can't build it on iOS simulator.

**Comment by bbcallen** [comment]
Did you build ffmpeg for i386?
```
sh compile-ffmpeg.sh i386
```

**Comment by mars-rover** [comment]
I followed your README's step. And I have succeed run this Cutting demo
{
|____ijkmedia
| |____ijkplayer
| |____ijksdl
|____ios
| |____build
| |____IJKMediaDemo
| |____IJKMediaPlayer
}
But when I try to create my own demo, It failed by the upper issue.

**Comment by mars-rover** [comment]
I followed your README's step. And I have succeed run this Cutting demo
{
|____ijkmedia
| |____ijkplayer
| |____ijksdl
|____ios
| |____build
| |____IJKMediaDemo
| |____IJKMediaPlayer
}
But when I try to create my own demo, It failed by the upper issue.

**Comment by mars-rover** [comment]
Are you still online? I close this issue by mistake, sorry about that~~~

**Comment by bbcallen** [comment]
Better push your project to github to see where is the problem.

**Comment by mars-rover** [comment]
Thanks a lot, I have worked it out. You made me fall in love with Github!!
