### ISSUE TITLE
播放本地视频，如何抛出当前播放的是整个视频的第几帧？

### ISSUE THREAD

**Issue by Luriwei** [Bilibili/ijkplayer#3563]
因为需要对每一帧进行处理，需要知道当前是第几帧（精确的帧数）。
而且需要调用seek方法后也能够知道当前是第几帧，求解。

**Comment by raymond1012** [comment]
在解码线程，做个计数就可以

**Comment by Luriwei** [comment]
假如视频有20秒，当前播放到1秒，解码到5秒了，如果现在我seekto到15秒的进度，播放器还会解码5-15秒之间的视频流嘛，比较担心seekto后中间的视频就不解码了，导致计数不准。@raymond1012
