### ISSUE TITLE
在海信电视上，硬解音视频不同步。

### ISSUE THREAD

**Issue by maikoulin** [Bilibili/ijkplayer#3566]
在海信电视上，软解音视频能够同步，硬解音视频不同步，有可能是什么引起的。

**Comment by raymond1012** [comment]
硬解性能不行或者view渲染问题

**Comment by maikoulin** [comment]
如果说性能问题，那么软解不应该更容易不同步码

**Comment by raymond1012** [comment]
软解依赖于cpu，而硬解依赖于芯片内的解码组件

**Comment by maikoulin** [comment]
如果这么说，我这边直接用mediaplay是没问题的。音视频也能能够同步

**Comment by maikoulin** [comment]
播放的视频源是H264 720*567 的，fps也才20 .对性能的要求不高

**Comment by raymond1012** [comment]
如果硬件烂，一切皆有可能

**Comment by maikoulin** [comment]
。。。。。。。。。。。
