### ISSUE TITLE
OnPauseListener missing

### ISSUE THREAD

**Issue by mavencode01** [Bilibili/ijkplayer#357]
Thanks for your wonderful library...really helped me in my project.

Am wondering how can I check if a video is paused?
Seems there is no way to set the callback for  `setOnPauseListener`

Thanks,

**Comment by Android4MediaPlayer** [comment]
please add it by yourself

**Comment by bbcallen** [comment]
No good way.
Actually, there are several internal threads need to be paused,
but it's quite difficult to know when they are all paused.

I would use a timer to poll per 100 milliseconds as Android does in android.widget.VideoView.
