### ISSUE TITLE
enable-accurate-seek, 这个参数能用来精确定位吗

### ISSUE THREAD

**Issue by xiaowu4** [Bilibili/ijkplayer#3570]
某些极端情况下，视频中只有最开始也就是第一帧是I帧，当seek到其他时间点时总是直接从头开始播放，怎么seek到哪个时间点就在那个时间点播放，而不是seek到关键帧播放

**Comment by raymond1012** [comment]
是的

在 2017年9月12日 下午3:07，xiaowu4 <notifications@github.com>写道：

**Comment by xiaowu4** [comment]
再请问一下，是将这个参数设为1吗？我将ff_ffplay.c中的该参数全部设为了1，还有ff_ffplay_def.h中的ffp的默认值也设为了1，但是还是没有效果，还有其他需要设置的吗

**Comment by xiaowu4** [comment]
还需要将OPTION_OFFSET(enable_accurate_seek), OPTION_INT(0, 0, 1) },改为OPTION_OFFSET(enable_accurate_seek), OPTION_INT(1, 0, 1) }，感谢

**Comment by raymond1012** [comment]
setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);

2017-09-12 15:41 GMT+08:00 xiaowu4 <notifications@github.com>:

**Comment by zhanggao** [comment]
精准seek为什么要加个参数控制，难道有什么坑？
为什么没有直接写死成1。

**Comment by zhanggao** [comment]
我设置了 enable-accurate-seek 1 后还是不能精准seek。0.7.8.1版本，看git提交记录是有加enable-accurate-seek相关逻辑代码的。

**Comment by JerryIsAgoodBoy** [comment]
enable-accurate-seek 开启后，播放m3u8视频会seek失败，不止何故

**Comment by hljstardust** [comment]
我设置了 enable-accurate-seek 1也还是不行啊

**Comment by nicolasiJasica** [comment]
亲测 可行，iOS
[options setPlayerOptionIntValue:1 forKey:@"enable-accurate-seek"]

**Comment by inmine** [comment]
> 

请问拖动进度,怎么做呢.添加了[options setPlayerOptionIntValue:1 forKey:@"enable-accurate-seek"]也是不好使

**Comment by kunlunjiangbo** [comment]
ios设置精准seek后，直接精准seek可以正常seek，但是暂停后seek，则要等10s画面才更新，有遇到这种问题吗？

**Comment by Jamishon** [comment]
> ios设置精准seek后，直接精准seek可以正常seek，但是暂停后seek，则要等10s画面才更新，有遇到这种问题吗？

ijkplayer的seek只能往前去寻找最近的关键帧，所以不太准确因为一个GOP才有一个关键帧，可能跨越数秒，所以不准确，要做到准确要找到关键帧 I帧，然后通过 P帧，D帧合成精确的那一帧，所以这当中要计算，要消耗CPU和内存，所以要花时间
