### ISSUE TITLE
ios h264 视频 只有声音 没有图像

### ISSUE THREAD

**Issue by G1King** [Bilibili/ijkplayer#3574]
[h264 @ 0x103b6ae00] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x103b6ae00] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x103b6ae00] Invalid NAL unit size (0 > 715).
[h264 @ 0x103b6ae00] Error splitting the input into NAL units.
[h264 @ 0x103b6b400] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x103b6b400] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x103b6b400] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x103b6b400] Invalid NAL unit size (0 > 693).
[h264 @ 0x103b6b400] Error splitting the input into NAL units.
[h264 @ 0x103617400] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x103617400] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x103617400] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x103617400] Invalid NAL unit size (0 > 153).
[h264 @ 0x103617400] Error splitting the input into NAL units.
[h264 @ 0x103b6ae00] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x103b6ae00] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x103b6ae00] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x103b6ae00] Invalid NAL unit size (0 > 700).
[h264 @ 0x103b6ae00] Error splitting the input into NAL units.
[h264 @ 0x103b6b400] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x103b6b400] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x103b6b400] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x103b6b400] Invalid NAL unit size (0 > 666).
[h264 @ 0x103b6b400] Error splitting the input into NAL units.
[h264 @ 0x103617400] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x103617400] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x103617400] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x103617400] Invalid NAL unit size (0 > 131).
[h264 @ 0x103617400] Error splitting the input into NAL units.
[h264 @ 0x103b6ae00] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x103b6ae00] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x103b6ae00] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x103b6ae00] Invalid NAL unit size (0 > 714).
[h264 @ 0x103b6ae00] Error splitting the input into NAL units.
[h264 @ 0x103b6b400] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x103b6b400] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x103b6b400] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x103b6b400] Invalid NAL unit size (0 > 673).
[h264 @ 0x103b6b400] Error splitting the input into NAL units.
[h264 @ 0x103617400] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x103617400] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x103617400] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x103617400] Invalid NAL unit size (0 > 109).
[h264 @ 0x103617400] Error splitting the input into NAL units.
[h264 @ 0x103b6ae00] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x103b6ae00] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x103b6ae00] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x103b6ae00] Invalid NAL unit size (0 > 678).
[h264 @ 0x103b6ae00] Error splitting the input into NAL units.
[h264 @ 0x103b6b400] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x103b6b400] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x103b6b400] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x103b6b400] Invalid NAL unit size (0 > 705).
[h264 @ 0x103b6b400] Error splitting the input into NAL units.
[h264 @ 0x103617400] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x103617400] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x103617400] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x103617400] Invalid NAL unit size (0 > 814).
[h264 @ 0x103617400] Error splitting the input into NAL units.
[h264 @ 0x103b6ae00] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x103b6ae00] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x103b6ae00] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x103b6ae00] Invalid NAL unit size (0 > 166).
[h264 @ 0x103b6ae00] Error splitting the input into NAL units.
[h264 @ 0x103b6b400] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x103b6b400] nal_unit_type: 8, nal_ref_idc: 1

**Comment by TheLittleBoy** [comment]
我也遇到过，只是后来重新打包发布，就没问题了。

**Comment by raymond1012** [comment]
source file issue

**Comment by G1King** [comment]
源文件问题？？ 要重新编译打包吗

**Comment by TheLittleBoy** [comment]
clear 一下，然后再archive

**Comment by G1King** [comment]
@raymond1012  But  v0.6.3 is ok   why ？？？ Thanks
