### ISSUE TITLE
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

### ISSUE THREAD

**Issue by bhuangzubin13** [Bilibili/ijkplayer#3578]
09-13 14:42:08.539 10065-10065/com.wwc2.video E/VideoTextureView: [(VideoTextureView.java:281)#openVideo Thread:main]
                                                                  初始化IjkMediaPlayer
09-13 14:42:08.551 10065-10065/com.wwc2.video D/J4A: J4ALoader: OK: 'android.os.Build$VERSION' loaded
09-13 14:42:08.551 10065-10065/com.wwc2.video D/J4A: J4ALoader: OK: 'android.os.Build' loaded
09-13 14:42:08.551 10065-10065/com.wwc2.video D/J4A: J4ALoader: OK: 'java.nio.Buffer' loaded
09-13 14:42:08.551 10065-10065/com.wwc2.video D/J4A: J4ALoader: OK: 'java.nio.ByteBuffer' loaded
09-13 14:42:08.551 10065-10065/com.wwc2.video D/J4A: J4ALoader: OK: 'java.util.ArrayList' loaded
09-13 14:42:08.551 10065-10065/com.wwc2.video I/J4A: API-Level: 24
09-13 14:42:08.551 10065-10065/com.wwc2.video D/J4A: J4ALoader: OK: 'android.media.AudioTrack' loaded
09-13 14:42:08.552 10065-10065/com.wwc2.video D/J4A: J4ALoader: OK: 'android.media.MediaCodec$BufferInfo' loaded
09-13 14:42:08.552 10065-10065/com.wwc2.video D/J4A: J4ALoader: OK: 'android.media.MediaCodec' loaded
09-13 14:42:08.552 10065-10065/com.wwc2.video D/J4A: J4ALoader: OK: 'android.media.MediaFormat' loaded
09-13 14:42:08.552 10065-10065/com.wwc2.video D/J4A: J4ALoader: OK: 'android.media.PlaybackParams' loaded
09-13 14:42:08.552 10065-10065/com.wwc2.video D/J4A: J4ALoader: OK: 'android.os.Bundle' loaded
09-13 14:42:08.552 10065-10065/com.wwc2.video D/J4A: J4ALoader: OK: 'tv.danmaku.ijk.media.player.misc.IMediaDataSource' loaded
09-13 14:42:08.553 10065-10065/com.wwc2.video D/J4A: J4ALoader: OK: 'tv.danmaku.ijk.media.player.misc.IAndroidIO' loaded
09-13 14:42:08.553 10065-10065/com.wwc2.video D/J4A: J4ALoader: OK: 'tv.danmaku.ijk.media.player.IjkMediaPlayer' loaded
09-13 14:42:08.561 10065-10065/com.wwc2.video D/IJKMEDIA: IjkMediaPlayer_native_init
09-13 14:42:08.562 10065-10065/com.wwc2.video D/IJKMEDIA: IjkMediaPlayer_native_setup
09-13 14:42:08.562 10065-10065/com.wwc2.video I/IJKMEDIA: av_version_info: ff3.2--ijk0.7.6--20170324--001
09-13 14:42:08.562 10065-10065/com.wwc2.video I/IJKMEDIA: ijk_version_info: k0.7.9
09-13 14:42:08.562 10065-10065/com.wwc2.video D/IJKMEDIA: ffpipeline_create_from_android()
09-13 14:42:08.562 10065-10065/com.wwc2.video D/IJKMEDIA: ijkmp_set_inject_opaque(0x1007b6)
09-13 14:42:08.562 10065-10065/com.wwc2.video D/IJKMEDIA: ijkmp_set_inject_opaque()=void
09-13 14:42:08.562 10065-10065/com.wwc2.video D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x1007b6)
09-13 14:42:08.563 10065-10065/com.wwc2.video D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
09-13 14:42:08.563 10065-10065/com.wwc2.video D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
09-13 14:42:08.563 10065-10065/com.wwc2.video D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
09-13 14:42:08.563 10065-10065/com.wwc2.video D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
09-13 14:42:08.563 10065-10065/com.wwc2.video D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(7)
09-13 14:42:08.563 10065-10065/com.wwc2.video D/IJKMEDIA: moncleanup
09-13 14:42:08.563 10065-10065/com.wwc2.video D/IJKMEDIA: IjkMediaPlayer_setOptionLong
09-13 14:42:08.563 10065-10065/com.wwc2.video D/IJKMEDIA: IjkMediaPlayer_setOptionLong
09-13 14:42:08.563 10065-10065/com.wwc2.video D/IJKMEDIA: IjkMediaPlayer_setOptionLong
09-13 14:42:08.563 10065-10065/com.wwc2.video D/IJKMEDIA: IjkMediaPlayer_setOptionLong
09-13 14:42:08.563 10065-10065/com.wwc2.video D/IJKMEDIA: IjkMediaPlayer_setOptionLong
09-13 14:42:08.563 10065-10065/com.wwc2.video D/IJKMEDIA: IjkMediaPlayer_setOptionLong
09-13 14:42:08.563 10065-10065/com.wwc2.video D/IJKMEDIA: IjkMediaPlayer_setOptionLong
09-13 14:42:08.563 10065-10065/com.wwc2.video D/IJKMEDIA: IjkMediaPlayer_setOptionLong
09-13 14:42:08.563 10065-10065/com.wwc2.video D/IJKMEDIA: IjkMediaPlayer_setOptionLong
09-13 14:42:08.565 10065-10065/com.wwc2.video E/VideoTextureView: [(VideoTextureView.java:322)#openVideo Thread:main]
                                                                  IjkMediaPlayer配置完成
09-13 14:42:08.565 10065-10065/com.wwc2.video D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
09-13 14:42:08.565 10065-10065/com.wwc2.video V/IJKMEDIA: setDataSource: path /storage/emulated/0/1.mp4
09-13 14:42:08.566 10065-10065/com.wwc2.video D/IJKMEDIA: ijkmp_set_data_source(url="/storage/emulated/0/1.mp4")
09-13 14:42:08.566 10065-10065/com.wwc2.video D/IJKMEDIA: ijkmp_set_data_source(url="/storage/emulated/0/1.mp4")=0
09-13 14:42:08.566 10065-10065/com.wwc2.video D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
09-13 14:42:08.566 10065-10065/com.wwc2.video D/IJKMEDIA: ijkmp_set_android_surface(surface=0x7fe7bfdb58)
09-13 14:42:08.566 10065-10065/com.wwc2.video D/IJKMEDIA: ffpipeline_set_surface()
09-13 14:42:08.566 10065-10065/com.wwc2.video D/IJKMEDIA: ijkmp_set_android_surface(surface=0x7fe7bfdb58)=void
09-13 14:42:08.566 10065-10065/com.wwc2.video W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
09-13 14:42:08.566 10065-10065/com.wwc2.video D/IJKMEDIA: IjkMediaPlayer_prepareAsync
09-13 14:42:08.566 10065-10065/com.wwc2.video D/IJKMEDIA: ijkmp_prepare_async()
09-13 14:42:08.566 10065-10156/com.wwc2.video I/IJKMEDIA: SDL_RunThread: [10156] ff_msg_loop
09-13 14:42:08.567 10065-10156/com.wwc2.video D/IJKMEDIA: message_loop
09-13 14:42:08.569 10065-10065/com.wwc2.video D/IJKMEDIA: ijkmp_prepare_async()=0
09-13 14:42:08.569 10065-10156/com.wwc2.video D/IJKMEDIA: FFP_MSG_FLUSH:
09-13 14:42:08.571 10065-10158/com.wwc2.video I/IJKMEDIA: SDL_RunThread: [10158] ff_read
09-13 14:42:08.571 10065-10157/com.wwc2.video I/IJKMEDIA: SDL_RunThread: [10157] ff_vout
09-13 14:42:08.573 10065-10158/com.wwc2.video I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [10158]
09-13 14:42:08.573 10065-10156/com.wwc2.video D/IJKMEDIA: FFP_MSG_ERROR: 0
09-13 14:42:08.575 10065-10105/com.wwc2.video I/GLConsumer: [SurfaceTexture-0-10065-0] attachToContext
09-13 14:42:08.598 10065-10105/com.wwc2.video D/OpenGLRenderer: CacheTexture 12 upload: x, y, width height = 0, 0, 43, 29
09-13 14:42:08.605 10065-10105/com.wwc2.video D/GraphicBuffer: register, handle(0x72520bef00) (w:1080 h:1776 s:1088 f:0x1 u:0x000b00)
09-13 14:42:08.609 10065-10105/com.wwc2.video D/OpenGLRenderer: ProgramCache.generateProgram: 1
09-13 14:42:08.613 10065-10105/com.wwc2.video D/OpenGLRenderer: ProgramCache.generateProgram: 4
09-13 14:42:08.616 10065-10105/com.wwc2.video D/OpenGLRenderer: ProgramCache.generateProgram: 34359738371
09-13 14:42:08.627 10065-10105/com.wwc2.video D/GraphicBuffer: register, handle(0x725216d380) (w:1080 h:1776 s:1088 f:0x1 u:0x000b00)
09-13 14:42:08.636 10065-10065/com.wwc2.video V/InputMethodManager: onWindowFocus: com.wwc2.video.play.VideoTextureView{3f94f1b VFED..... .F...... 0,0-1776,1080 #7f0c0086 app:id/videotextureview} softInputMode=32 first=true flags=#5910300
09-13 14:42:08.650 10065-10065/com.wwc2.video E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by bhuangzubin13** [comment]
运行在android 7.0系统上播放mp4错误

**Comment by raymond1012** [comment]
路径没有权限或者mp4文件问题
