### ISSUE TITLE
iOS Seek 异常

### ISSUE THREAD

**Issue by zhudaye12138** [Bilibili/ijkplayer#358]
@"http://pl.youku.com/playlist/m3u8?ts=1437621689&keyframe=0&vid=XMTI5MTE4NjUwOA==&type=flv&ep=diaXHU%2BPV8gI7CHYiD8bZyThISRZXJZ3kmaA%2FLYXBMV%2BLa%2FA6DPcqJmzSvo%3D&sid=443762168927012083ecf&token=4345&ctype=12&ev=1&oip=3728081270"

用demo试的，这个m3u8地址的视频，seek会出错。不能到达准确位置。

其他m3u8和mp4都可以，不清楚是什么问题，麻烦抽空帮忙看看。感谢~

**Comment by Android4MediaPlayer** [comment]
log?

**Comment by bbcallen** [comment]
Revert the commit in ffmpeg

```
commit 255dd6631771e7bdca8124adbf9e2c40ac7c6791
Author: Zhang Rui <bbcallen@gmail.com>
Date:   Mon Oct 27 21:35:43 2014 +0800

    avformat/hls: disable seek within segment
```
