### ISSUE TITLE
datasource加入header cookie

### ISSUE THREAD

**Issue by gnastnosaj** [Bilibili/ijkplayer#359]
有什么办法可以在请求中加入cookie

**Comment by bbcallen** [comment]
http://git.videolan.org/?p=ffmpeg.git;a=blob;f=libavformat/http.c;h=676bfd5c5a869c8f16b968f1af44fb974fd4fbd1;hb=HEAD#l117

**Comment by gnastnosaj** [comment]
thanks

**Comment by zmsoft** [comment]
@gnastnosaj 你的cookie设置成功了吗，需要修改http.c然后重新打framework包吗
