### ISSUE TITLE
播放m3u8解析出的ts格式视频，有画面无声音？

### ISSUE THREAD

**Issue by Lucky-Hong** [Bilibili/ijkplayer#3596]
hello，在使用ijk播放m3u8解析出的ts格式视频，有画面无声音，音频是ac3格式的，有什么特殊配制吗？还是说ijk不支持ts格式的视频呢？

**Comment by raymond1012** [comment]
ts支持，ac3需要enable

**Comment by Lucky-Hong** [comment]
嗯，ac3格式具体需要如何设置，可以提供下方法吗？万分感谢哈～

**Comment by Lucky-Hong** [comment]
ac3默认不支持，配置下config就可以解决
cd config
rm module.sh
ln -s module-default.sh module.sh
cd ios/contrib
sh compile-ffmpeg.sh clean

**Comment by YYHNobug** [comment]
> hello，在使用ijk播放m3u8解析出的ts格式视频，有画面无声音，音频是ac3格式的，有什么特殊配制吗？还是说ijk不支持ts格式的视频呢？

您好，您是怎么播放ts的，m3u8不是包含很多个ts吗，怎么轮询逐个播放ts的？
