### ISSUE TITLE
有声音无图像，特定视频(264)，任意设备，log输出'no picture'，附测试视频

### ISSUE THREAD

**Issue by AlanJaver** [Bilibili/ijkplayer#3597]
有声音无图像，log里看有一行'no picture'，搜了下在 ffmpeg/libavcodec/h264_slice.c 里输出的。应该是视频本身格式有点问题，可能需要做些容错，因为vlc正常播放。

测试视频：https://drive.google.com/file/d/0B7sZNfsoiLPlRTN0SlFWVk1kTnc/view?usp=sharing

log:

	09-18 19:58:45.149 14234-14234/tv.danmaku.ijk.media.example I/Timeline: Timeline: Activity_launch_request time:41522090
	09-18 19:58:45.199 14234-14234/tv.danmaku.ijk.media.example V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@fdd9c8b
	09-18 19:58:45.199 14234-14234/tv.danmaku.ijk.media.example V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@5903168
	09-18 19:58:45.199 14234-14234/tv.danmaku.ijk.media.example V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@be2e981
	09-18 19:58:45.200 14234-14234/tv.danmaku.ijk.media.example V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@d88ea26
	                                                                              
	                                                                              [ 09-18 19:58:45.201 14234:14234 E/         ]
	                                                                              SurfaceView doesn't support rotation (0)!
	09-18 19:58:45.213 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_native_profileBegin
	09-18 19:58:45.213 14234-14234/tv.danmaku.ijk.media.example W/IJKMEDIA: monstartup already called
	09-18 19:58:45.219 14234-14234/tv.danmaku.ijk.media.example D/ActivityThreadInjector: clearCachedDrawables.
	09-18 19:58:45.247 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_native_setup
	09-18 19:58:45.247 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170710--001
	09-18 19:58:45.247 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: ijk_version_info: k0.8.3
	09-18 19:58:45.248 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ffpipeline_create_from_android()
	09-18 19:58:45.248 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_inject_opaque(0x4fa)
	09-18 19:58:45.248 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_inject_opaque()=void
	09-18 19:58:45.248 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x4fa)
	09-18 19:58:45.248 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
	09-18 19:58:45.248 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
	09-18 19:58:45.248 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
	09-18 19:58:45.248 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
	09-18 19:58:45.248 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(3)
	09-18 19:58:45.248 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: moncleanup
	09-18 19:58:45.248 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
	09-18 19:58:45.248 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
	09-18 19:58:45.248 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
	09-18 19:58:45.248 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
	09-18 19:58:45.248 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example D/tv.danmaku.ijk.media.player.IjkMediaPlayer: Couldn't open file on client side, trying server side
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example V/IJKMEDIA: setDataSource: path /storage/emulated/0/Егор Крид - Что они знают.mp4
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_data_source(url="/storage/emulated/0/Егор Крид - Что они знают.mp4")
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_data_source(url="/storage/emulated/0/Егор Крид - Что они знают.mp4")=0
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffe1bb20)
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ffpipeline_set_surface()
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffe1bb20)=void
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_prepareAsync
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_prepare_async()
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: ===== versions =====
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: ijkplayer    : k0.8.3
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170710--001
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: libavutil    : 55.58.100
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: libavcodec   : 57.89.100
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: libavformat  : 57.71.100
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: libswscale   : 4.6.100
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: libswresample: 2.7.100
	09-18 19:58:45.249 14234-13344/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [13344] ff_msg_loop
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: ===== options =====
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : mediacodec                   = 0
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : opensles                     = 0
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : overlay-format               = 842225234
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : framedrop                    = 1
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : start-on-prepared            = 0
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : ijkapplication               = -1418471776
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : ijkiomanager                 = -1420451464
	09-18 19:58:45.249 14234-13344/tv.danmaku.ijk.media.example D/IJKMEDIA: message_loop
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : http-detect-range-support    = 0
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
	09-18 19:58:45.249 14234-14234/tv.danmaku.ijk.media.example I/IJKMEDIA: ===================
	09-18 19:58:45.254 14234-13345/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [13345] ff_vout
	09-18 19:58:45.254 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_prepare_async()=0
	09-18 19:58:45.254 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [13346] ff_read
	09-18 19:58:45.254 14234-13344/tv.danmaku.ijk.media.example D/IJKMEDIA: FFP_MSG_FLUSH:
	09-18 19:58:45.255 14234-13346/tv.danmaku.ijk.media.example D/IJKMEDIA: Setting default whitelist 'file,crypto'
	09-18 19:58:45.257 14234-13346/tv.danmaku.ijk.media.example D/IJKMEDIA: Format mov,mp4,m4a,3gp,3g2,mj2 probed with size=2048 and score=100
	09-18 19:58:45.257 14234-13346/tv.danmaku.ijk.media.example D/IJKMEDIA: ISO: File Type Major Brand: dash
	09-18 19:58:45.258 14234-13346/tv.danmaku.ijk.media.example D/IJKMEDIA: Unknown dref type 0x206c7275 size 12
	09-18 19:58:45.268 14234-13346/tv.danmaku.ijk.media.example D/IJKMEDIA: Offset DTS by ctts[0].duration: 3600
	09-18 19:58:45.268 14234-13346/tv.danmaku.ijk.media.example D/IJKMEDIA: Processing st: 0, edit list 0 - media time: 3600, duration: 0
	09-18 19:58:45.268 14234-13346/tv.danmaku.ijk.media.example D/IJKMEDIA: shifted frame pts, curr_cts: 0 @ 0, ctts: 3600, ctts_count: 1961
	09-18 19:58:45.268 14234-13346/tv.danmaku.ijk.media.example D/IJKMEDIA: drop a frame at curr_cts: 3600 @ 0
	09-18 19:58:45.269 14234-13346/tv.danmaku.ijk.media.example D/IJKMEDIA: Unknown dref type 0x206c7275 size 12
	09-18 19:58:45.277 14234-13346/tv.danmaku.ijk.media.example E/IJKMEDIA: Option ijkapplication not found.
	09-18 19:58:45.277 14234-13346/tv.danmaku.ijk.media.example D/IJKMEDIA: Before avformat_find_stream_info() pos: 69015289 bytes read:108675 seeks:1 nb_streams:2
	09-18 19:58:45.278 14234-13346/tv.danmaku.ijk.media.example D/IJKMEDIA: nal_unit_type: 7, nal_ref_idc: 3
	09-18 19:58:45.278 14234-13346/tv.danmaku.ijk.media.example D/IJKMEDIA: nal_unit_type: 8, nal_ref_idc: 3
	09-18 19:58:45.282 14234-13346/tv.danmaku.ijk.media.example D/IJKMEDIA: nal_unit_type: 5, nal_ref_idc: 3
	09-18 19:58:45.282 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: Reinit context to 1920x1088, pix_fmt: yuv420p
	09-18 19:58:45.297 14234-13346/tv.danmaku.ijk.media.example D/IJKMEDIA: no picture 
	09-18 19:58:45.321 14234-13346/tv.danmaku.ijk.media.example D/IJKMEDIA: All info found
	09-18 19:58:45.321 14234-13346/tv.danmaku.ijk.media.example D/IJKMEDIA: After avformat_find_stream_info() pos: 65602573 bytes read:174211 seeks:3 frames:2
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: max_frame_duration: 10.000
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/Егор Крид - Что они знают.mp4':
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA:   Metadata:
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA:     major_brand     : 
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: dash
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA:     minor_version   : 
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: 0
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA:     compatible_brands: 
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: iso6avc1mp41
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA:     creation_time   : 
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: 2017-03-06T13:41:30.000000Z
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA:   Duration: 
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: 00:03:32.58
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: , start: 
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: 0.000000
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: , bitrate: 
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: 2597 kb/s
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA:     Stream #0:0
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: (und)
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example D/IJKMEDIA: , 1, 1/90000
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: : Video: h264, 1 reference frame (avc1 / 0x31637661), yuv420p(tv, bt709, left), 1920x1080 (1920x1088) [SAR 1:1 DAR 16:9], 0/1, 2469 kb/s
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: , 
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: 25 fps, 
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: 25 tbr, 
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: 90k tbn, 
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: 50 tbc
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA:  (default)
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA:     Metadata:
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA:       creation_time   : 
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: 2017-03-06T13:41:30.000000Z
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA:       handler_name    : 
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: VideoHandler
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA:     Stream #0:1
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: (und)
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example D/IJKMEDIA: , 1, 1/44100
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: : Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA:  (default)
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA:     Metadata:
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA:       creation_time   : 
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: 2017-03-06T13:41:19.000000Z
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA:       handler_name    : 
	09-18 19:58:45.322 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: SoundHandler
	09-18 19:58:45.324 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
	09-18 19:58:45.324 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_Android_AudioTrack: ENCODING_PCM_16BIT
	09-18 19:58:45.331 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(0.000000,1.000000)
	09-18 19:58:45.332 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: audio_session_id = 345
	09-18 19:58:45.333 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: AudioCodec: avcodec, aac
	09-18 19:58:45.333 14234-13351/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [13351] ff_audio_dec
	09-18 19:58:45.334 14234-13350/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [13350] ff_aout_android
	09-18 19:58:45.334 14234-13346/tv.danmaku.ijk.media.example D/IJKMEDIA: nal_unit_type: 7, nal_ref_idc: 3
	09-18 19:58:45.334 14234-13346/tv.danmaku.ijk.media.example D/IJKMEDIA: nal_unit_type: 8, nal_ref_idc: 3
	09-18 19:58:45.335 14234-14277/tv.danmaku.ijk.media.example D/OpenGLRenderer: endAllStagingAnimators on 0xab3dcb68 (ListView) with handle 0xac9b1f68
	09-18 19:58:45.344 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: VideoCodec: avcodec, h264
	09-18 19:58:45.345 14234-13346/tv.danmaku.ijk.media.example W/IJKMEDIA: fps: 25.000000 (normal)
	09-18 19:58:45.345 14234-13346/tv.danmaku.ijk.media.example W/IJKMEDIA: fps: 25.000000 (normal)
	09-18 19:58:45.345 14234-13363/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [13363] ff_video_dec
	09-18 19:58:45.345 14234-13344/tv.danmaku.ijk.media.example D/IJKMEDIA: FFP_MSG_VIDEO_ROTATION_CHANGED: 0
	09-18 19:58:45.345 14234-13344/tv.danmaku.ijk.media.example D/IJKMEDIA: FFP_MSG_VIDEO_SIZE_CHANGED: 1920, 1080
	09-18 19:58:45.345 14234-13344/tv.danmaku.ijk.media.example D/IJKMEDIA: FFP_MSG_SAR_CHANGED: 1, 1
	09-18 19:58:45.345 14234-13344/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_PREPARED
	09-18 19:58:45.345 14234-13344/tv.danmaku.ijk.media.example D/IJKMEDIA: FFP_MSG_PREPARED:
	09-18 19:58:45.345 14234-14234/tv.danmaku.ijk.media.example D/IjkVideoView: MEDIA_INFO_VIDEO_ROTATION_CHANGED: 0
	                                                                            
	                                                                            [ 09-18 19:58:45.345 14234:14234 E/         ]
	                                                                            SurfaceView doesn't support rotation (0)!
	09-18 19:58:45.371 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_start
	09-18 19:58:45.371 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_start()
	09-18 19:58:45.371 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_start()=0
	09-18 19:58:45.371 14234-13344/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
	09-18 19:58:45.371 14234-13344/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START: start on fly
	09-18 19:58:45.385 14234-13344/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
	09-18 19:58:45.385 14234-13344/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START: start on fly
	09-18 19:58:45.386 14234-13352/tv.danmaku.ijk.media.example D/IJKMEDIA: nal_unit_type: 5, nal_ref_idc: 3
	09-18 19:58:45.386 14234-13352/tv.danmaku.ijk.media.example I/IJKMEDIA: Reinit context to 1920x1088, pix_fmt: yuv420p
	09-18 19:58:45.386 14234-13350/tv.danmaku.ijk.media.example D/IJKMEDIA: Using fltp internally between filters
	09-18 19:58:45.387 14234-13350/tv.danmaku.ijk.media.example D/IJKMEDIA: avcodec/Audio: first frame decoded
	09-18 19:58:45.387 14234-13344/tv.danmaku.ijk.media.example D/IJKMEDIA: FFP_MSG_AUDIO_RENDERING_START:
	09-18 19:58:45.387 14234-14234/tv.danmaku.ijk.media.example D/IjkVideoView: MEDIA_INFO_AUDIO_RENDERING_START:
	09-18 19:58:45.391 14234-13352/tv.danmaku.ijk.media.example D/IJKMEDIA: no picture 
	09-18 19:58:47.290 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
	09-18 19:58:47.290 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
	09-18 19:58:47.290 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ffpipeline_set_surface()
	09-18 19:58:47.290 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
	09-18 19:58:47.591 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_stop()
	09-18 19:58:47.591 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_stop()=0
	09-18 19:58:47.591 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_release
	09-18 19:58:47.591 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
	09-18 19:58:47.591 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ffpipeline_set_surface()
	09-18 19:58:47.591 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
	09-18 19:58:47.591 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_shutdown_l()
	09-18 19:58:47.591 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: wait for read_tid
	09-18 19:58:47.591 14234-13363/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [13363]
	09-18 19:58:47.591 14234-13344/tv.danmaku.ijk.media.example D/IJKMEDIA: message_loop exit
	09-18 19:58:47.591 14234-13344/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [13344]
	09-18 19:58:47.599 14234-13345/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [13345]
	09-18 19:58:47.661 14234-13346/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [13346]
	09-18 19:58:47.662 14234-13351/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [13351]
	09-18 19:58:47.708 14234-13350/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [13350]
	09-18 19:58:47.712 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: Statistics: 3483779 bytes read, 3 seeks
	09-18 19:58:47.712 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: wait for video_refresh_tid
	09-18 19:58:47.722 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_shutdown_l()=void
	09-18 19:58:47.722 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_dec_ref(): ref=0
	09-18 19:58:47.722 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_shutdown_l()
	09-18 19:58:47.722 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_shutdown_l()=void
	09-18 19:58:47.724 14234-14234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_native_profileEnd
	09-18 19:58:47.724 14234-14234/tv.danmaku.ijk.media.example W/IJKMEDIA: moncleanu already called

**Comment by raymond1012** [comment]
ffmpeg的问题，你可以向ffmpeg提patch
