### ISSUE TITLE
用wget加cookie能下载，用ijkplayer播放提示HTTP 416

### ISSUE THREAD

**Issue by gnastnosaj** [Bilibili/ijkplayer#360]
HTTP error 416 Error

Option http-detect-range-support not found.

Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 1280x720, 2970 kb/s): unspecified pixel format
    Consider increasing the value for the 'analyzeduration' and 'probesize' options

**Comment by Android4MediaPlayer** [comment]
please give more log.

**Comment by gnastnosaj** [comment]
07-28 12:01:39.425    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ IjkMediaPlayer_native_setup
07-28 12:01:39.425    2338-2338/tk.jasontsang.pandora D/IJKMEDIA﹕ ffpipeline_create_from_android()
07-28 12:01:39.425    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_format_callback(0x6e84f1a9, 0x1d20039a)
07-28 12:01:39.425    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_format_callback()=void
07-28 12:01:39.425    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_android_set_mediacodec_select_callback()
07-28 12:01:39.425    2338-2338/tk.jasontsang.pandora D/IJKMEDIA﹕ ffpipeline_set_mediacodec_select_callback
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_android_set_mediacodec_select_callback()=void
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ IjkMediaPlayer_setAvFormatOption
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_format_option(http-detect-range-support, 1)
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_format_option()=void
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ IjkMediaPlayer_setOverlayFormat
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_option_int(overlay-format, 842225234)
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_option_int()=void
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ IjkMediaPlayer_setAvCodecOption
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_codec_option()
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_codec_option()=void
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ IjkMediaPlayer_setFrameDrop
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_option_int(framedrop, 12)
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_option_int()=void
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ IjkMediaPlayer_setAvFormatOption
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_format_option(headers, Cookie: gdriveid=A71B59CA5B89FF0244D84B2818CBDDBF
    )
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_format_option()=void
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ IjkMediaPlayer_setDataSourceAndHeaders
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora V/IJKMEDIA﹕ setDataSource: path http://gdl.lixian.vip.xunlei.com/download?fid=oAjIJAEaM9ZEShUqP6ArQRjAM9hz9jCTAAAAAKcTbYY5I56nDBuY6e25ZlCCK3AC&mid=666&threshold=150&tid=A19F94B54B2B10B2869F117A46ECD038&srcid=4&verno=1&g=A7136D8639239EA70C1B98E9EDB96650822B7002&scn=t37&i=A7136D8639239EA70C1B98E9EDB96650822B7002&t=1&ui=243176037&ti=1019918734464000&s=2469459571&m=0&n=01325E8736616C70680E538D3E2E323031551FD36D30702E572473C91B4C2E48325705C90D45414C48251F892F34000000&ff=0&co=63E91343754EEC5F076DB6BDB7A4CFC2&cm=1&pk=lixian&ak=1:1:6:4&e=1445827215&ms=10485760&ck=A71B59CA5B89FF0244D84B2818CBDDBF&at=947CEDEA1F7F4C48590F51579EAAA413
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_data_source(url="http://gdl.lixian.vip.xunlei.com/download?fid=oAjIJAEaM9ZEShUqP6ArQRjAM9hz9jCTAAAAAKcTbYY5I56nDBuY6e25ZlCCK3AC&mid=666&threshold=150&tid=A19F94B54B2B10B2869F117A46ECD038&srcid=4&verno=1&g=A7136D8639239EA70C1B98E9EDB96650822B7002&scn=t37&i=A7136D8639239EA70C1B98E9EDB96650822B7002&t=1&ui=243176037&ti=1019918734464000&s=2469459571&m=0&n=01325E8736616C70680E538D3E2E323031551FD36D30702E572473C91B4C2E48325705C90D45414C48251F892F34000000&ff=0&co=63E91343754EEC5F076DB6BDB7A4CFC2&cm=1&pk=lixian&ak=1:1:6:4&e=1445827215&ms=10485760&ck=A71B59CA5B89FF0244D84B2818CBDDBF&at=947CEDEA1F7F4C48590F51579EAAA413")
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_data_source(url="http://gdl.lixian.vip.xunlei.com/download?fid=oAjIJAEaM9ZEShUqP6ArQRjAM9hz9jCTAAAAAKcTbYY5I56nDBuY6e25ZlCCK3AC&mid=666&threshold=150&tid=A19F94B54B2B10B2869F117A46ECD038&srcid=4&verno=1&g=A7136D8639239EA70C1B98E9EDB96650822B7002&scn=t37&i=A7136D8639239EA70C1B98E9EDB96650822B7002&t=1&ui=243176037&ti=1019918734464000&s=2469459571&m=0&n=01325E8736616C70680E538D3E2E323031551FD36D30702E572473C91B4C2E48325705C90D45414C48251F892F34000000&ff=0&co=63E91343754EEC5F076DB6BDB7A4CFC2&cm=1&pk=lixian&ak=1:1:6:4&e=1445827215&ms=10485760&ck=A71B59CA5B89FF0244D84B2818CBDDBF&at=947CEDEA1F7F4C48590F51579EAAA413")=0
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ IjkMediaPlayer_setVideoSurface
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0x5440001d)
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora D/IJKMEDIA﹕ ffpipeline_set_surface()
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0x5440001d)=void
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ IjkMediaPlayer_prepareAsync
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_prepare_async()
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora I/IJKMEDIA﹕ ===== options =====
07-28 12:01:39.435    2338-4020/tk.jasontsang.pandora I/IJKMEDIA﹕ SDL_RunThread: [4020] ff_msg_loop
07-28 12:01:39.435    2338-4020/tk.jasontsang.pandora W/IJKMEDIA﹕ message_loop
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora I/IJKMEDIA﹕ player-opts : overlay-format       = 842225234
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora I/IJKMEDIA﹕ format-opts : http-detect-range-support = 1
07-28 12:01:39.435    2338-4020/tk.jasontsang.pandora W/IJKMEDIA﹕ FFP_MSG_FLUSH:
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora I/IJKMEDIA﹕ format-opts : framedrop            = 12
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora I/IJKMEDIA﹕ format-opts : headers              = Cookie: gdriveid=gdriveid
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora I/IJKMEDIA﹕ codec-opts  : skip_loop_filter     = 48
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora I/IJKMEDIA﹕ ===================
07-28 12:01:39.435    2338-4021/tk.jasontsang.pandora I/IJKMEDIA﹕ SDL_RunThread: [4021] ff_vout
07-28 12:01:39.435    2338-4021/tk.jasontsang.pandora D/IJKMEDIA﹕ ffpipenode_create_video_output_from_android_mediacodec()
07-28 12:01:39.435    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_prepare_async()=0
07-28 12:01:39.435    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ SDL_RunThread: [4022] ff_read
07-28 12:01:39.465    2338-2338/tk.jasontsang.pandora D/ProgressBar﹕ setProgressDrawable mProgressDrawable = null, d = android.graphics.drawable.LayerDrawable@42d7a008needUpdate = false
07-28 12:01:39.465    2338-2338/tk.jasontsang.pandora D/ProgressBar﹕ setProgressDrawable drawableHeight = 36
07-28 12:01:39.465    2338-2338/tk.jasontsang.pandora D/ProgressBar﹕ setProgress = 0
07-28 12:01:39.465    2338-2338/tk.jasontsang.pandora D/ProgressBar﹕ setProgress = 0, fromUser = false
07-28 12:01:39.465    2338-2338/tk.jasontsang.pandora D/ProgressBar﹕ mProgress = 0mIndeterminate = false, mMin = 0, mMax = 1000
07-28 12:01:39.475    2338-2338/tk.jasontsang.pandora D/AbsSeekBar﹕ AbsSeekBar Constructor: misSeebarAnimationAvailable = true
07-28 12:01:39.485    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ IjkMediaPlayer_setVideoSurface
07-28 12:01:39.485    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0x5bf0001d)
07-28 12:01:39.485    2338-2338/tk.jasontsang.pandora D/IJKMEDIA﹕ ffpipeline_set_surface()
07-28 12:01:39.485    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0x5bf0001d)=void
07-28 12:01:39.605    2338-2338/tk.jasontsang.pandora D/AbsListView﹕ onVisibilityChanged() is called, visibility : 4
07-28 12:01:39.605    2338-2338/tk.jasontsang.pandora D/AbsListView﹕ unregisterIRListener() is called
07-28 12:02:11.956    2338-4022/tk.jasontsang.pandora W/IJKMEDIA﹕ HTTP error 416 Error
07-28 12:02:15.270    2338-4022/tk.jasontsang.pandora W/IJKMEDIA﹕ HTTP error 416 Error
07-28 12:02:15.350     964-1042/? V/SmartFaceService - 3rd party pause﹕ onReceive [android.intent.action.ACTIVITY_STATE/tk.jasontsang.pandora/pause]
07-28 12:02:15.450     964-1042/? V/SmartFaceService - 3rd party pause﹕ onReceive [android.intent.action.ACTIVITY_STATE/tk.jasontsang.pandora/resume]
07-28 12:02:15.470    2338-2338/tk.jasontsang.pandora D/AbsListView﹕ onVisibilityChanged() is called, visibility : 0
07-28 12:02:15.470    2338-2338/tk.jasontsang.pandora D/AbsListView﹕ unregisterIRListener() is called
07-28 12:02:15.490    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ IjkMediaPlayer_reset
07-28 12:02:15.490    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ IjkMediaPlayer_release
07-28 12:02:15.490    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0x0)
07-28 12:02:15.490    2338-2338/tk.jasontsang.pandora D/IJKMEDIA﹕ ffpipeline_set_surface()
07-28 12:02:15.490    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0x0)=void
07-28 12:02:15.490    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_shutdown_l()
07-28 12:02:15.490    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ wait for read_tid
07-28 12:02:15.490    2338-4020/tk.jasontsang.pandora W/IJKMEDIA﹕ message_loop exit
07-28 12:02:15.580    2338-4022/tk.jasontsang.pandora E/IJKMEDIA﹕ Option http-detect-range-support not found.
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora W/IJKMEDIA﹕ Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 1280x720, 2970 kb/s): unspecified pixel format
    Consider increasing the value for the 'analyzeduration' and 'probesize' options
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ max_frame_duration: 3600.000
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'http://gdl.lixian.vip.xunlei.com/download?fid=oAjIJAEaM9ZEShUqP6ArQRjAM9hz9jCTAAAAAKcTbYY5I56nDBuY6e25ZlCCK3AC&mid=666&threshold=150&tid=A19F94B54B2B10B2869F117A46ECD038&srcid=4&verno=1&g=A7136D8639239EA70C1B98E9EDB96650822B7002&scn=t37&i=A7136D8639239EA70C1B98E9EDB96650822B7002&t=1&ui=243176037&ti=1019918734464000&s=2469459571&m=0&n=01325E8736616C70680E538D3E2E323031551FD36D30702E572473C91B4C2E48325705C90D45414C48251F892F34000000&ff=0&co=63E91343754EEC5F076DB6BDB7A4CFC2&cm=1&pk=lixian&ak=1:1:6:4&e=1445827215&ms=10485760&ck=A71B59CA5B89FF0244D84B2818CBDDBF&at=947CEDEA1F7F4C48590F51579EAAA413':
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ Metadata:
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ major_brand     :
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ mp42
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ [ 07-28 12:02:15.590  2338: 4022 I/IJKMEDIA ]
    minor_version   :
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ 0
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ [ 07-28 12:02:15.590  2338: 4022 I/IJKMEDIA ]
    compatible_brands:
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ mp42mp41
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ [ 07-28 12:02:15.590  2338: 4022 I/IJKMEDIA ]
    creation_time   :
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ 2015-04-05 10:38:30
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ [ 07-28 12:02:15.590  2338: 4022 I/IJKMEDIA ]
    Duration:
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ 01:44:03.31
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ , bitrate:
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ N/A
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ [ 07-28 12:02:15.590  2338: 4022 I/IJKMEDIA ]
    Stream #0:0
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ (eng)
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ : Video: h264 (avc1 / 0x31637661), none, 1280x720, 2970 kb/s
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ ,
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ 29.97 fps,
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ 29.97 tbr,
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ 30k tbn,
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ 60k tbc
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ (default)
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ [ 07-28 12:02:15.590  2338: 4022 I/IJKMEDIA ]
    Metadata:
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ creation_time   :
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ 2015-04-05 10:38:30
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ [ 07-28 12:02:15.590  2338: 4022 I/IJKMEDIA ]
    handler_name    :
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ Alias Data Handler
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ [ 07-28 12:02:15.590  2338: 4022 I/IJKMEDIA ]
    encoder         :
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ AVC Coding
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ [ 07-28 12:02:15.590  2338: 4022 I/IJKMEDIA ]
    Stream #0:1
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ (eng)
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ : Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ (default)
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ [ 07-28 12:02:15.590  2338: 4022 I/IJKMEDIA ]
    Metadata:
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ creation_time   :
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ 2015-04-05 10:38:30
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ [ 07-28 12:02:15.590  2338: 4022 I/IJKMEDIA ]
    handler_name    :
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ Alias Data Handler
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ [ 07-28 12:02:15.590  2338: 4022 I/IJKMEDIA ]
    SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
07-28 12:02:15.590    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ SDL_Android_AudioTrack: ENCODING_PCM_16BIT
07-28 12:02:15.600    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ SDL_Android_AudioTrack_new: init volume as 1.000000/(0.000000,1.000000)
07-28 12:02:15.600    2338-4131/tk.jasontsang.pandora I/IJKMEDIA﹕ SDL_RunThread: [4131] ff_aout_android
07-28 12:02:15.600    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ AudioCodec: avcodec, aac
07-28 12:02:15.600    2338-4132/tk.jasontsang.pandora I/IJKMEDIA﹕ SDL_RunThread: [4132] ff_audio_dec
07-28 12:02:15.600    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ VideoCodec: avcodec, h264
07-28 12:02:15.600    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ fps: 29.970030 (normal)
07-28 12:02:15.600    2338-4138/tk.jasontsang.pandora I/IJKMEDIA﹕ SDL_RunThread: [4138] ff_video_dec
07-28 12:02:15.600    2338-4022/tk.jasontsang.pandora I/IJKMEDIA﹕ fps: 29.970030 (normal)
07-28 12:02:15.610    2338-4131/tk.jasontsang.pandora D/dalvikvm﹕ threadid=17: thread exiting, not yet detached (count=0)
07-28 12:02:15.620    2338-4022/tk.jasontsang.pandora D/dalvikvm﹕ threadid=15: thread exiting, not yet detached (count=0)
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ wait for video_refresh_tid
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_shutdown_l()=void
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ IjkMediaPlayer_native_setup
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora D/IJKMEDIA﹕ ffpipeline_create_from_android()
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_format_callback(0x6e84f1a9, 0x1d3003a6)
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_format_callback()=void
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_android_set_mediacodec_select_callback()
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora D/IJKMEDIA﹕ ffpipeline_set_mediacodec_select_callback
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_android_set_mediacodec_select_callback()=void
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_dec_ref(): ref=0
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_shutdown_l()
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_shutdown_l()=void
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ IjkMediaPlayer_release
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0x0)
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora D/IJKMEDIA﹕ ffpipeline_set_surface()
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0x0)=void
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_shutdown_l()
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_shutdown_l()=void
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_dec_ref(): ref=0
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_shutdown_l()
07-28 12:02:15.620    2338-2338/tk.jasontsang.pandora W/IJKMEDIA﹕ ijkmp_shutdown_l()=void
07-28 12:02:15.630    2338-2338/tk.jasontsang.pandora D/AbsListView﹕ unregisterIRListener() is called

**Comment by gnastnosaj** [comment]
'analyzeduration' and 'probesize' 加了没效果

**Comment by gnastnosaj** [comment]
好像是视频源的问题

**Comment by hellosuperX** [comment]
请问查找到原因了吗
