### ISSUE TITLE
播放本地1080p视频,声音一卡一卡的

### ISSUE THREAD

**Issue by liy452083759** [Bilibili/ijkplayer#3602]
09-20 14:12:21.784 6188-6188/com.iptv.klys I/IJKMEDIA: ===== versions =====
09-20 14:12:21.784 6188-6188/com.iptv.klys I/IJKMEDIA: ijkplayer    : k0.7.5-3-g79b1eaa
09-20 14:12:21.794 6188-6188/com.iptv.klys I/IJKMEDIA: FFmpeg       : ff3.2--ijk0.7.2-20161107--001
09-20 14:12:21.794 6188-6188/com.iptv.klys I/IJKMEDIA: libavutil    : 55.34.100
09-20 14:12:21.794 6188-6188/com.iptv.klys I/IJKMEDIA: libavcodec   : 57.64.100
09-20 14:12:21.794 6188-6188/com.iptv.klys I/IJKMEDIA: libavformat  : 57.56.100
09-20 14:12:21.794 6188-6188/com.iptv.klys I/IJKMEDIA: libswscale   : 4.2.100
09-20 14:12:21.794 6188-6188/com.iptv.klys I/IJKMEDIA: libswresample: 2.3.100
09-20 14:12:21.794 6188-6188/com.iptv.klys I/IJKMEDIA: ===== options =====
09-20 14:12:21.794 6188-6188/com.iptv.klys I/IJKMEDIA: format-opts : ijkapplication               = -1190285168
09-20 14:12:21.794 6188-6188/com.iptv.klys I/IJKMEDIA: ===================
09-20 14:12:21.804 6188-6514/com.iptv.klys I/IJKMEDIA: SDL_RunThread: [6514] ff_msg_loop
09-20 14:12:21.814 6188-6516/com.iptv.klys I/IJKMEDIA: SDL_RunThread: [6516] ff_read
09-20 14:12:21.824 6188-6515/com.iptv.klys I/IJKMEDIA: SDL_RunThread: [6515] ff_vout
09-20 14:12:21.894 6188-6516/com.iptv.klys E/IJKMEDIA: Option ijkapplication not found.
09-20 14:12:22.064 6188-6516/com.iptv.klys I/IJKMEDIA: Reinit context to 1920x1088, pix_fmt: yuv420p
09-20 14:12:23.304 6188-6516/com.iptv.klys I/IJKMEDIA: max_frame_duration: 10.000
09-20 14:12:23.314 6188-6516/com.iptv.klys I/IJKMEDIA: Input #0, mpegts, from '/mnt/shared/Other/11007020000067002_006.ts':
09-20 14:12:23.314 6188-6516/com.iptv.klys I/IJKMEDIA:   Duration: 
09-20 14:12:23.314 6188-6516/com.iptv.klys I/IJKMEDIA: 00:03:19.70
09-20 14:12:23.314 6188-6516/com.iptv.klys I/IJKMEDIA: , start: 
09-20 14:12:23.314 6188-6516/com.iptv.klys I/IJKMEDIA: 0.000000
09-20 14:12:23.314 6188-6516/com.iptv.klys I/IJKMEDIA: , bitrate: 
09-20 14:12:23.314 6188-6516/com.iptv.klys I/IJKMEDIA: 11438 kb/s
09-20 14:12:23.314 6188-6516/com.iptv.klys I/IJKMEDIA:   Program 1 
09-20 14:12:23.314 6188-6516/com.iptv.klys I/IJKMEDIA:     Metadata:
09-20 14:12:23.314 6188-6516/com.iptv.klys I/IJKMEDIA:       service_name    : 
09-20 14:12:23.314 6188-6516/com.iptv.klys I/IJKMEDIA: Service01
09-20 14:12:23.324 6188-6516/com.iptv.klys I/IJKMEDIA:       service_provider: 
09-20 14:12:23.324 6188-6516/com.iptv.klys I/IJKMEDIA: FFmpeg
09-20 14:12:23.334 6188-6516/com.iptv.klys I/IJKMEDIA:     Stream #0:0
09-20 14:12:23.334 6188-6516/com.iptv.klys I/IJKMEDIA: [0x100]
09-20 14:12:23.334 6188-6516/com.iptv.klys I/IJKMEDIA: : Video: h264, 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(progressive, left), 1920x1080 (1920x1088) [SAR 1:1 DAR 16:9], 0/1
09-20 14:12:23.334 6188-6516/com.iptv.klys I/IJKMEDIA: , 
09-20 14:12:23.334 6188-6516/com.iptv.klys I/IJKMEDIA: 29.97 fps, 
09-20 14:12:23.334 6188-6516/com.iptv.klys I/IJKMEDIA: 29.97 tbr, 
09-20 14:12:23.334 6188-6516/com.iptv.klys I/IJKMEDIA: 90k tbn, 
09-20 14:12:23.334 6188-6516/com.iptv.klys I/IJKMEDIA: 59.94 tbc
09-20 14:12:23.334 6188-6516/com.iptv.klys I/IJKMEDIA:     Stream #0:1
09-20 14:12:23.334 6188-6516/com.iptv.klys I/IJKMEDIA: [0x101]
09-20 14:12:23.334 6188-6516/com.iptv.klys I/IJKMEDIA: : Audio: aac ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 169 kb/s
09-20 14:12:23.364 6188-6516/com.iptv.klys I/IJKMEDIA: SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
09-20 14:12:23.364 6188-6516/com.iptv.klys I/IJKMEDIA: SDL_Android_AudioTrack: ENCODING_PCM_16BIT
09-20 14:12:23.394 6188-6516/com.iptv.klys I/IJKMEDIA: SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(0.000000,1.000000)
09-20 14:12:23.394 6188-6516/com.iptv.klys I/IJKMEDIA: audio_session_id = 16
09-20 14:12:23.414 6188-6516/com.iptv.klys I/IJKMEDIA: AudioCodec: avcodec, aac
09-20 14:12:23.424 6188-6540/com.iptv.klys I/IJKMEDIA: SDL_RunThread: [6540] ff_aout_android
09-20 14:12:23.424 6188-6516/com.iptv.klys I/IJKMEDIA: Ignoring NAL type 9 in extradata
09-20 14:12:23.434 6188-6516/com.iptv.klys I/IJKMEDIA: VideoCodec: avcodec, h264
09-20 14:12:23.444 6188-6541/com.iptv.klys I/IJKMEDIA: SDL_RunThread: [6541] ff_audio_dec
09-20 14:12:23.444 6188-6542/com.iptv.klys I/IJKMEDIA: SDL_RunThread: [6542] ff_video_dec
09-20 14:12:23.444 6188-6516/com.iptv.klys W/IJKMEDIA: fps: 29.970030 (normal)
09-20 14:12:23.454 6188-6516/com.iptv.klys W/IJKMEDIA: fps: 29.970030 (normal)
09-20 14:12:23.474 6188-6516/com.iptv.klys I/IJKMEDIA: Ignoring NAL type 9 in extradata
09-20 14:12:23.484 6188-6542/com.iptv.klys I/IJKMEDIA: Reinit context to 1920x1088, pix_fmt: yuv420p
09-20 14:12:23.504 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 10001,,extra = 0
09-20 14:12:23.544 6188-6188/com.iptv.klys I/act.VideoActivity: logTime:preparePlay = 1806
09-20 14:12:23.544 6188-6188/com.iptv.klys I/BasePlayActivity: preparePlay: vocalTract = 0
09-20 14:12:23.564 6188-6188/com.iptv.klys I/VideoActivity: getTrackInfoSize: i= 1
09-20 14:12:23.564 6188-6188/com.iptv.klys I/VideoActivity: getTrackInfoSize: infoInline= AUDIO, aac, 169 kb/s, 48000 Hz
09-20 14:12:23.574 6188-6188/com.iptv.klys I/BasePlayActivity: start: 
09-20 14:12:23.614 6188-6188/com.iptv.klys I/UserStoreProcess: addUserPlayLog: {"userId":"MFZH4ad99979321c83dd","entryId":"1","project":"lxyyad","resCode":"11006010000337","source":"1","stopTime":0,"resType":1,"allTime":120}url= http://202.99.114.28:25603/API_ROP/user/play/add/res
09-20 14:12:23.634 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:23.634 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 10002,,extra = 0
09-20 14:12:23.734 6188-6188/com.iptv.klys I/OkHttpResponseCallback: onResponse: com.dr.iptv.msg.res.user.play.PlayLogAddResponse  = {"streamNo":"00000MbNR1Vr0e983173","code":10000000,"text":"成功"}
09-20 14:12:24.014 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:25.614 6188-6188/com.iptv.klys I/tv.danmaku.ijk.media.player.IjkMediaPlayer: Info: MEDIA_INFO_VIDEO_RENDERING_START
09-20 14:12:25.614 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 3,,extra = 0
09-20 14:12:25.714 6188-6188/com.iptv.klys I/act.VideoActivity: logTime:updateSeeBar = 2164
09-20 14:12:32.094 6188-6188/com.iptv.klys I/BasePlayActivity: onGlobalFocusChanged: newFocus = null
09-20 14:12:38.584 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:38.584 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:39.554 6188-6540/com.iptv.klys W/AudioTrack: releaseBuffer() track 0xb9208d80 name=s:162;n:3;f:-1 disabled due to previous underrun, restarting
09-20 14:12:39.554 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:39.584 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:39.834 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:39.844 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:39.844 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:39.864 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:40.634 6188-6540/com.iptv.klys W/AudioTrack: releaseBuffer() track 0xb9208d80 name=s:162;n:3;f:-1 disabled due to previous underrun, restarting
09-20 14:12:40.654 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:40.654 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:41.334 6188-6540/com.iptv.klys W/AudioTrack: releaseBuffer() track 0xb9208d80 name=s:162;n:3;f:-1 disabled due to previous underrun, restarting
09-20 14:12:41.354 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:41.354 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:42.204 6188-6540/com.iptv.klys W/AudioTrack: releaseBuffer() track 0xb9208d80 name=s:162;n:3;f:-1 disabled due to previous underrun, restarting
09-20 14:12:42.244 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:42.244 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:42.474 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:42.514 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:43.514 6188-6540/com.iptv.klys W/AudioTrack: releaseBuffer() track 0xb9208d80 name=s:162;n:3;f:-1 disabled due to previous underrun, restarting
09-20 14:12:43.524 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:43.554 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:44.324 6188-6540/com.iptv.klys W/AudioTrack: releaseBuffer() track 0xb9208d80 name=s:162;n:3;f:-1 disabled due to previous underrun, restarting
09-20 14:12:44.354 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:44.354 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:44.934 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:44.934 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:45.794 6188-6540/com.iptv.klys W/AudioTrack: releaseBuffer() track 0xb9208d80 name=s:162;n:3;f:-1 disabled due to previous underrun, restarting
09-20 14:12:45.794 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:45.814 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:46.984 6188-6540/com.iptv.klys W/AudioTrack: releaseBuffer() track 0xb9208d80 name=s:162;n:3;f:-1 disabled due to previous underrun, restarting
09-20 14:12:46.984 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:46.984 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:47.234 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:47.244 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:48.384 6188-6540/com.iptv.klys W/AudioTrack: releaseBuffer() track 0xb9208d80 name=s:162;n:3;f:-1 disabled due to previous underrun, restarting
09-20 14:12:48.404 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:48.424 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:49.314 6188-6540/com.iptv.klys W/AudioTrack: releaseBuffer() track 0xb9208d80 name=s:162;n:3;f:-1 disabled due to previous underrun, restarting
09-20 14:12:49.344 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:49.344 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:49.344 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:49.344 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:49.494 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:49.494 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:49.784 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:49.814 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:49.924 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:49.934 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:50.024 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:50.024 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:50.034 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:50.034 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:50.164 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:50.214 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:50.524 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:50.564 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:50.704 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0
09-20 14:12:50.704 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 702,,extra = 0
09-20 14:12:50.814 6188-6188/com.iptv.klys I/BasePlayActivity: onInfo: what = 701,,extra = 0

**Comment by liupeng110** [comment]
播放本地4k视频很卡,卡顿

**Comment by raymond1012** [comment]
软解性能不行
