### ISSUE TITLE
敢问Android端Ijkplayer如何设置解码方式？

### ISSUE THREAD

**Issue by flyingun** [Bilibili/ijkplayer#3603]
如何设置软解码、硬解码，望告知，多谢。

**Comment by raymond1012** [comment]
// Android only options
    { "mediacodec",                             "MediaCodec: enable H264 (deprecated by 'mediacodec-avc')",
        OPTION_OFFSET(mediacodec_avc),          OPTION_INT(0, 0, 1) },
