### ISSUE TITLE
setDatasource 函数的疑问。

### ISSUE THREAD

**Issue by harlanc** [Bilibili/ijkplayer#3608]
/**
     * Sets the data source (FileDescriptor) to use.  The FileDescriptor must be
     * seekable (N.B. a LocalSocket is not seekable). It is the caller's responsibility
     * to close the file descriptor. It is safe to do so as soon as this call returns.
     *
     * @param fd the FileDescriptor for the file you want to play
     * @param offset the offset into the file where the data to be played starts, in bytes
     * @param length the length in bytes of the data to be played
     * @throws IllegalStateException if it is called in an invalid state
     */
    private void setDataSource(FileDescriptor fd, long offset, long length)
            throws IOException, IllegalArgumentException, IllegalStateException {
        // FIXME: handle offset, length
        setDataSource(fd);
    }

这里的FIXME，意思是这个函数还有待改善么？后面两个参数都没有用到。

**Comment by raymond1012** [comment]
希望支持从文件的某个偏移量开始播放
