### ISSUE TITLE
" Command not found" error

### ISSUE THREAD

**Issue by zhangbl** [Bilibili/ijkplayer#361]
build on ndk r9d

zhangbl@ubuntu:~/Development/ijkplayer/ijkplayer-master/android$ sh compile-ijk.sh
profiler build: NO
ln: failed to create symbolic link ‘android-ndk-prof’: File exists
[armeabi-v7a] Install        : libijkffmpeg.so => libs/armeabi-v7a/libijkffmpeg.so
make: /home/zhangbl/Documents/android-ndk-r9d/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86/bin/arm-linux-androideabi-strip: Command not found
make: *** [/home/zhangbl/Development/ijkplayer/ijkplayer-master/android/ijkplayer/player-armv7a/src/main/libs/armeabi-v7a/libijkffmpeg.so] Error 127
make: *** Deleting file `/home/zhangbl/Development/ijkplayer/ijkplayer-master/android/ijkplayer/player-armv7a/src/main/libs/armeabi-v7a/libijkffmpeg.so'
/home/zhangbl/Development/ijkplayer/ijkplayer-master/android
zhangbl@ubuntu:~/Development/ijkplayer/ijkplayer-master/android$

**Comment by zhangbl** [comment]
how to fix this error?

**Comment by zhangbl** [comment]
but when i build on ndk-r10e , build libijkffmpeg.so only ,Why?

zhangbl@ubuntu:~/Development/ijkplayer-master/android$ sh compile-ijk.sh
profiler build: NO
[armeabi-v7a] Install        : libijkffmpeg.so => libs/armeabi-v7a/libijkffmpeg.so
/home/zhangbl/Development/ijkplayer-master/android
zhangbl@ubuntu:~/Development/ijkplayer-master/android$

**Comment by bbcallen** [comment]
try
```
# choose [No] to use bash
sudo dpkg-reconfigure dash
```

**Comment by zhangbl** [comment]
@bbcallen  it's useless , what does the "profiler build: NO"  mean ?
