### ISSUE TITLE
有关IjkMediaPlayer  指针引用计数的问题

### ISSUE THREAD

**Issue by chinaminiren** [Bilibili/ijkplayer#3614]
static IjkMediaPlayer *jni_get_media_player(JNIEnv* env, jobject thiz) 函数中
对获取到的 IjkMediaPlayer 指针 进行引用计数+1( ijkmp_inc_ref) 
这样用确实没有任何问题。我只是疑惑，在什么场景下这样用的必要性？
播放器create--到播放器release  这个IjkMediaPlayer 指针不是一直存在吗？为何还要进行引用计数的机制呢？
谢谢！

**Comment by raymond1012** [comment]
解决并发调用ijk api问题
