### ISSUE TITLE
ios ijkPlayer ：Play video only sound has no image！

### ISSUE THREAD

**Issue by G1King** [Bilibili/ijkplayer#3617]
Log：
FFPlayer @ 0x1038df600] max_frame_duration: 10.000
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'http://lingdao.spicu.com.cn/leaderApp/sys/file/cdee2f41fc3e41a5a277a4d638cb5ec2':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2009-06-01T10:18:15.000000Z
  Duration: 00:14:28.83, start: 0.000000, bitrate: 228 kb/s
    Stream #0:0(und), 1, 1/18: Video: h264, 1 reference frame (avc1 / 0x31637661), none(left), 480x320, 0/1, 177 kb/s, 18 fps, 18 tbr, 18 tbn, 36 tbc (default)
    Metadata:
      creation_time   : 2009-06-01T10:18:15.000000Z
      handler_name    : VideoHandler
    Stream #0:1(und), 0, 1/44100: Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 47 kb/s (default)
    Metadata:
      creation_time   : 2009-06-01T10:18:15.000000Z
      handler_name    : SoundHandler
aout_open_audio()
[FFPlayer @ 0x1038df600] AudioCodec: avcodec, aac
aout_pause_audio(0)
detected 2 logical cores
[h264 @ 0x10393f800] nal_unit_type: 7, nal_ref_idc: 3
[h264 @ 0x10393f800] nal_unit_type: 8, nal_ref_idc: 3
[FFPlayer @ 0x1038df600] VideoCodec: avcodec, h264
2017-09-22 16:59:52.454313+0800 ZFPlayer[1009:313145] FFP_MSG_VIDEO_DECODER_OPEN: false
[FFPlayer @ 0x1038df600] fps: 18.000000 (normal)
[FFPlayer @ 0x1038df600] fps: 18.000000 (normal)
2017-09-22 16:59:52.454663+0800 ZFPlayer[1009:313145] FFP_MSG_VIDEO_SIZE_CHANGED: 480, 320
2017-09-22 16:59:52.455453+0800 ZFPlayer[1009:313145] FFP_MSG_SAR_CHANGED: 0, 1
ijkmp_get_msg: FFP_MSG_PREPARED
[h264 @ 0x10393f800] nal_unit_type: 9, nal_ref_idc: 0
2017-09-22 16:59:52.455691+0800 ZFPlayer[1009:313145] FFP_MSG_PREPARED:
[h264 @ 0x10393f800] nal_unit_type: 7, nal_ref_idc: 1
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
[aac @ 0x103801800] skip whole frame, skip left: 0
2017-09-22 16:59:52.455825+0800 ZFPlayer[1009:313145] fps in meta 18.000000
ijkmp_set_playback_rate(1.000000)
[FFPlayer @ 0x1038df600] Playback rate: 1.000000
ijkmp_set_playback_rate()=void
ijkmp_set_playback_volume(1.000000)
ijkmp_set_playback_volume()=void
2017-09-22 16:59:52.455949+0800 ZFPlayer[1009:313145] 加载状态变成了已经缓存完成，如果设置了自动播放, 会自动播放
ijkmp_start()
ijkmp_start()=0
2017-09-22 16:59:52.456202+0800 ZFPlayer[1009:313145] mediaIsPrepareToPlayDidChange
[h264 @ 0x10393f800] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x10393f800] nal_unit_type: 6, nal_ref_idc: 02017-09-22 16:59:52.456333+0800 ZFPlayer[1009:313145] 播放器的播放状态变了，现在是播放状态 1: playing

ijkmp_get_msg: FFP_REQ_START
[h264 @ 0x10393f800] Invalid NAL unit size (0 > 2819).
[FFPlayer @ 0x1038df600] ijkmp_get_msg: FFP_REQ_START: start on fly
[h264 @ 0x10393f800] Error splitting the input into NAL units.
aout_pause_audio(0)
aout_close_audio()
aout_set_volume()
[h264 @ 0x10393e400] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x10393e400] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x10393e400] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x10393e400] Invalid NAL unit size (0 > 15).
[h264 @ 0x10393e400] Error splitting the input into NAL units.
[h264 @ 0x103940e00] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x103940e00] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x103940e00] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x103940e00] Invalid NAL unit size (0 > 14).
[h264 @ 0x103940e00] Error splitting the input into NAL units.
[h264 @ 0x10393f800] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x10393f800] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x10393f800] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x10392017-09-22 16:59:52.460290+0800 ZFPlayer[1009:313145] 播放器的播放状态变了，现在是播放状态 1: playing
3f800] Invalid NAL unit size (0 > 34).
[h264 @ 0x10393f800] Error splitting the input into NAL units.
[h264 @ 0x10393e400] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x10393e400] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x10393e400] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x10393e400] Invalid NAL unit size (0 > 263).
[h264 @ 0x10393e400] Error splitting the input into NAL units.
[h264 @ 0x103940e00] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x103940e00] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x103940e00] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x103940e00] Invalid NAL unit size (0 > 27).
[h264 @ 0x103940e00] Error splitting the input into NAL units.
[h264 @ 0x10393f800] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x10393f800] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x10393f800] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x10393f800] Invalid NAL unit size (0 > 169).
[h264 @ 0x10393f800] Error splitting the input into NAL units.
[h264 @ 0x10393e400] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x10393e400] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x10393e400] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x10393e400] Invalid NAL unit size (0 > 156).
[h264 @ 0x10393e400] Error splitting the input into NAL units.
[h264 @ 0x103940e00] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x103940e00] nal_unit_type: 8, nal_ref_idc: 1

[h264 @ 0x103940e00] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x103940e00] Invalid NAL unit size (0 > 14).
[h264 @ 0x103940e00] Error splitting the input into NAL units.
[h264 @ 0x10393f800] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x10393f800] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x10393f800] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x10393f800] Invalid NAL unit size (0 > 295).
[h264 @ 0x10393f800] Error splitting the input into NAL units.
[h264 @ 0x10393e400] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x10393e400] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x10393e400] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x10393e400] Invalid NAL unit size (0 > 304).
[h264 @ 0x10393e400] Error splitting the input into NAL units.
[h264 @ 0x103940e00] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x103940e00] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x103940e00] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x103940e00] Invalid NAL unit size (0 > 19).
[h264 @ 0x103940e00] Error splitting the input into NAL units.
[h264 @ 0x10393f800] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x10393f800] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x10393f800] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x10393f800] Invalid NAL unit size (0 > 332).
[h264 @ 0x10393f800] Error splitting the input into NAL units.
[h264 @ 0x10393e400] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x10393e400] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x10393e400] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x10393e400] Invalid NAL unit size (0 > 227).
[h264 @ 0x10393e400] Error splitting the input into NAL units.
[h264 @ 0x103940e00] nal_unit_type: 9, nal_ref_idc: 0
[h264 @ 0x103940e00] nal_unit_type: 8, nal_ref_idc: 1
[h264 @ 0x103940e00] nal_unit_type: 6, nal_ref_idc: 0
[h264 @ 0x103940e00] Invalid NAL unit size (0 > 222).
[h264 @ 0x103940e00] Error splitting the input into NAL units.
[h264 @ 0x10393f800] nal_unit_type: 9, nal_ref_idc: 0 

V0.62 There are no problems like this。bug V0.8.3 that's the problem！！

**Comment by TynnPassBy** [comment]
I've had the same problem. Have you solved it

**Comment by raymond1012** [comment]
Error splitting the input into NAL units.   source file issue

**Comment by G1King** [comment]
@TynnPassBy  sorry It hasn't been settled yet

**Comment by G1King** [comment]
@raymond1012   But  using V0.6.3 can play !!! so I don't think it's a source file problem.

**Comment by animaonline** [comment]
iOS 11?

**Comment by CloudIAU** [comment]
我在iOS11下也遇到过这样的情况，我的解决方法是：
在IJKSDLGLView.m文件中，- (BOOL)setupEAGLContext:(EAGLContext *)context 方法的
`  glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_RENDERBUFFER, _renderbuffer);`
代码下面添加
`[CATransaction flush];`
在- (void)displayInternal: (SDL_VoutOverlay *) overlay 方法中
`IJK_GLES2_Renderer_setGravity(_renderer, _rendererGravity, _backingWidth, _backingHeight);`
代码下面也添加
`[CATransaction flush];`
即可解决这个问题，供参考。

**Comment by raymond1012** [comment]
@CloudIAU  解决ios11 真机卡？

**Comment by Derek-X-Wang** [comment]
@CloudIAU 太棒了，谢谢大神，简直是救命。我都准备实在没办法就换MobileVLCKit了。
能麻烦大神讲一下这个问题的原因吗？想学习一下:)

**Comment by LeesimEverglow** [comment]
@CloudIAU 我发现如果我放在最顶层控制器内的播放器 比如首页内的 iOS11下会不现实  但是如果是推出的界面iOS11下会显示画面  你遇到的是这种情况么 还是全部界面的视频都播放不了？

**Comment by erikhric** [comment]
I had same issue when I used swift. I suspect that problem is this line
`self.player.view.autoresizingMask = [.flexibleWidth, .flexibleHeight]`
I copied player class from Sample Project and used via bridging header and video works. 
But I still don't have any audio :(

**Comment by LeesimEverglow** [comment]
@erikhric  Are you using iOS11 above problems before what happened?If so,you can use @CloudIAU answer.

in IJKSDLGLView.m，
- (BOOL)setupEAGLContext:(EAGLContext *)context
glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_RENDERBUFFER, _renderbuffer);
below this line . add code [CATransaction flush];

i- (void)displayInternal: (SDL_VoutOverlay *) overlay 
IJK_GLES2_Renderer_setGravity(_renderer, _rendererGravity, _backingWidth, _backingHeight);
below this line . add code [CATransaction flush] too;
