### ISSUE TITLE
Demo project cannot build - linker error - Missing -lcrypto

### ISSUE THREAD

**Issue by liuzhen2008** [Bilibili/ijkplayer#3618]
iOS 11.0
xcode 9.0

I basically followed the steps and opened up the demo. Added the dependencies in xcode.

<img width="886" alt="screen shot 2017-09-22 at 11 47 18 am" src="https://user-images.githubusercontent.com/2473837/30752951-e4270dd2-9f8b-11e7-8b02-a5400b08710f.png">

But in the end i am still getting this error

ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by liuzhen2008** [comment]
turns out i need to run compile-openssl.sh as well.

Why weren't they in the docs?

**Comment by LXXuanCai** [comment]
怎么解决的

**Comment by Android4MediaPlayer** [comment]
you need to run compile-openssl.sh
