### ISSUE TITLE
ijkplayer是否支持swf格式

### ISSUE THREAD

**Issue by Zard1096** [Bilibili/ijkplayer#362]
RT，我在ffmpeg的文件夹libavformat中有发现swf和swfdec，按理应该支持swf的播放，我也在配置文件中配置了一下swf，但是在播放的时候仍然弹出了Invalid data found when processing input。

**Comment by bbcallen** [comment]
Did you clean your previous build?
Did you test same video with ffplay on PC.

**Comment by Android4MediaPlayer** [comment]
recompiler ffmpeg

**Comment by qazmoon** [comment]
@Android4MediaPlayer 英语真差，不过俺的更差，^_^

**Comment by Android4MediaPlayer** [comment]
@qazmoon 没必要那么专业

**Comment by Zard1096** [comment]
Exact cleaning the build.
Testing on ffplay by FFmpeg.org/ffplay-2.7.2,didn't work too.
But two different swf file has different error.This is ffplay Log(Xcode Log for iOS is similar):
This first file's Log:

ffplay version 2.7.2-tessus Copyright (c) 2003-2015 the FFmpeg developers
  built with Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --as=yasm --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-version3 --enable-librtmp --enable-ffplay --disable-ffmpeg --disable-ffprobe --disable-ffserver --disable-indev=qtkit --disable-indev=x11grab_xcb
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
/Users/Zard1096/Downloads/1-141021135448.swf: Invalid data found when processing input
    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0


This is second file's Log:

ffplay version 2.7.2-tessus Copyright (c) 2003-2015 the FFmpeg developers
  built with Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --as=yasm --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-version3 --enable-librtmp --enable-ffplay --disable-ffmpeg --disable-ffprobe --disable-ffserver --disable-indev=qtkit --disable-indev=x11grab_xcb
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
[aac @ 0x7ff0f3826800] Format aac detected only with low score of 1, misdetection possible!
[aac @ 0x7ff0f408c000] More than one AAC RDB per ADTS frame is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0x7ff0f408c000] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
[aac @ 0x7ff0f408c000] channel element 3.7 is not allocated
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.B f=0/0   
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] channel element 2.3 is not allocated
[aac @ 0x7ff0f408c000] SBR was found before the first channel element.
[aac @ 0x7ff0f408c000] channel element 1.0 is not allocated
[aac @ 0x7ff0f408c000] Number of bands (24) exceeds limit (4).
[aac @ 0x7ff0f408c000] Number of scalefactor bands in group (63) exceeds limit (40).
[aac @ 0x7ff0f408c000] channel element 2.4 is not allocated
[aac @ 0x7ff0f408c000] channel element 2.1 is not allocated
[aac @ 0x7ff0f408c000] channel element 3.8 is not allocated
[aac @ 0x7ff0f408c000] channel element 2.10 is not allocated
[aac @ 0x7ff0f408c000] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
[aac @ 0x7ff0f408c000] channel element 3.0 is not allocated
[aac @ 0x7ff0f408c000] channel element 2.9 is not allocated
[aac @ 0x7ff0f408c000] channel element 2.14 is not allocated
[aac @ 0x7ff0f408c000] Number of bands (7) exceeds limit (3).
[aac @ 0x7ff0f408c000] Number of bands (30) exceeds limit (22).
[aac @ 0x7ff0f408c000] SBR was found before the first channel element.
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] Reserved bit set.
[aac @ 0x7ff0f408c000] Number of scalefactor bands in group (45) exceeds limit (43).
[aac @ 0x7ff0f408c000] channel element 2.11 is not allocated
[aac @ 0x7ff0f408c000] Reserved bit set.
[aac @ 0x7ff0f408c000] Number of scalefactor bands in group (58) exceeds limit (43).
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] channel element 3.6 is not allocated
[aac @ 0x7ff0f408c000] Dependent coupling is not supported together with LTP
    Last message repeated 17 times
[aac @ 0x7ff0f408c000] channel element 2.9 is not allocated
[aac @ 0x7ff0f408c000] channel element 1.10 is not allocated
[aac @ 0x7ff0f408c000] channel element 1.14 is not allocated
[aac @ 0x7ff0f408c000] channel element 3.3 is not allocated
[aac @ 0x7ff0f408c000] Reserved bit set.
[aac @ 0x7ff0f408c000] Number of scalefactor bands in group (55) exceeds limit (40).
[aac @ 0x7ff0f408c000] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] Reserved bit set.
[aac @ 0x7ff0f408c000] Number of bands (39) exceeds limit (33).
[aac @ 0x7ff0f408c000] channel element 1.1 is not allocated
[aac @ 0x7ff0f408c000] Dependent coupling is not supported together with LTP
    Last message repeated 27 times
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
[aac @ 0x7ff0f408c000] channel element 3.10 is not allocated
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] Number of bands (9) exceeds limit (7).
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] channel element 2.4 is not allocated
[aac @ 0x7ff0f408c000] Dependent coupling is not supported together with LTP
    Last message repeated 27 times
[aac @ 0x7ff0f408c000] channel element 2.0 is not allocated
[aac @ 0x7ff0f408c000] channel element 1.9 is not allocated
[aac @ 0x7ff0f408c000] Reserved bit set.
[aac @ 0x7ff0f408c000] Number of bands (24) exceeds limit (23).
[aac @ 0x7ff0f408c000] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] channel element 2.12 is not allocated
[aac @ 0x7ff0f408c000] channel element 2.8 is not allocated
[aac @ 0x7ff0f408c000] channel element 2.1 is not allocated
[aac @ 0x7ff0f408c000] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] channel element 3.8 is not allocated
[aac @ 0x7ff0f408c000] channel element 2.14 is not allocated
    Last message repeated 1 times
[aac @ 0x7ff0f408c000] Reserved bit set.
[aac @ 0x7ff0f408c000] Number of scalefactor bands in group (61) exceeds limit (43).
[aac @ 0x7ff0f408c000] Number of bands (46) exceeds limit (28).
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] channel element 1.8 is not allocated
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] channel element 1.6 is not allocated
[aac @ 0x7ff0f408c000] SBR was found before the first channel element.
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] channel element 3.1 is not allocated
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] channel element 1.9 is not allocated
[aac @ 0x7ff0f408c000] Number of bands (30) exceeds limit (20).
[aac @ 0x7ff0f408c000] invalid band type
[aac @ 0x7ff0f408c000] TNS filter order 17 is greater than maximum 12.
[aac @ 0x7ff0f408c000] Number of bands (25) exceeds limit (18).
[aac @ 0x7ff0f408c000] channel element 2.5 is not allocated
[aac @ 0x7ff0f408c000] channel element 1.11 is not allocated
[aac @ 0x7ff0f408c000] channel element 2.7 is not allocated
[aac @ 0x7ff0f408c000] Dependent coupling is not supported together with LTP
    Last message repeated 29 times
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] Reserved bit set.
[aac @ 0x7ff0f408c000] Number of bands (31) exceeds limit (17).
[aac @ 0x7ff0f408c000] channel element 1.3 is not allocated
[aac @ 0x7ff0f408c000] Number of bands (13) exceeds limit (10).
[aac @ 0x7ff0f408c000] channel element 1.10 is not allocated
[aac @ 0x7ff0f408c000] channel element 3.4 is not allocated
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
[aac @ 0x7ff0f408c000] channel element 1.5 is not allocated
[aac @ 0x7ff0f408c000] channel element 1.12 is not allocated
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] decode_pce: Input buffer exhausted before END element found
[aac @ 0x7ff0f408c000] channel element 3.4 is not allocated
[aac @ 0x7ff0f408c000] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] channel element 3.2 is not allocated
[aac @ 0x7ff0f408c000] Reserved bit set.
[aac @ 0x7ff0f408c000] ms_present = 3 is reserved.
[aac @ 0x7ff0f408c000] channel element 3.2 is not allocated
[aac @ 0x7ff0f408c000] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
[aac @ 0x7ff0f408c000] Reserved bit set.
[aac @ 0x7ff0f408c000] Number of bands (11) exceeds limit (7).
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] channel element 1.12 is not allocated
[aac @ 0x7ff0f408c000] Reserved bit set.
[aac @ 0x7ff0f408c000] Number of bands (15) exceeds limit (11).
[aac @ 0x7ff0f408c000] channel element 1.8 is not allocated
[aac @ 0x7ff0f408c000] Number of bands (37) exceeds limit (35).
[aac @ 0x7ff0f408c000] Dependent coupling is not supported together with LTP
    Last message repeated 29 times
[aac @ 0x7ff0f408c000] invalid band type
[aac @ 0x7ff0f408c000] Number of bands (20) exceeds limit (3).
[aac @ 0x7ff0f408c000] channel element 2.12 is not allocated
[aac @ 0x7ff0f408c000] channel element 1.14 is not allocated
[aac @ 0x7ff0f408c000] Dependent coupling is not supported together with LTP
    Last message repeated 29 times
[aac @ 0x7ff0f408c000] channel element 3.8 is not allocated
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] channel element 3.2 is not allocated
[aac @ 0x7ff0f408c000] Reserved bit set.
[aac @ 0x7ff0f408c000] Number of bands (10) exceeds limit (9).
[aac @ 0x7ff0f408c000] channel element 2.4 is not allocated
[aac @ 0x7ff0f408c000] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
[aac @ 0x7ff0f408c000] channel element 2.8 is not allocated
[aac @ 0x7ff0f408c000] Reserved bit set.
[aac @ 0x7ff0f408c000] Number of scalefactor bands in group (50) exceeds limit (40).
[aac @ 0x7ff0f408c000] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
[aac @ 0x7ff0f408c000] channel element 3.12 is not allocated
[aac @ 0x7ff0f408c000] Number of scalefactor bands in group (51) exceeds limit (40).
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] Number of bands (21) exceeds limit (10).
[aac @ 0x7ff0f408c000] channel element 1.8 is not allocated
[aac @ 0x7ff0f408c000] channel element 3.1 is not allocated
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] Prediction is not allowed in AAC-LC.
[aac @ 0x7ff0f408c000] channel element 3.0 is not allocated
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] channel element 1.14 is not allocated
[aac @ 0x7ff0f408c000] channel element 2.2 is not allocated
[aac @ 0x7ff0f408c000] Dependent coupling is not supported together with LTP
    Last message repeated 25 times
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
[aac @ 0x7ff0f408c000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7ff0f408c000] Inconsistent channel configuration.
[aac @ 0x7ff0f408c000] get_buffer() failed
[aac @ 0x7ff0f408c000] channel element 1.10 is not allocated
[aac @ 0x7ff0f408c000] channel element 2.6 is not allocated
[aac @ 0x7ff0f3826800] decoding for stream 0 failed
[aac @ 0x7ff0f3826800] Estimating duration from bitrate, this may be inaccurate
[aac @ 0x7ff0f3826800] Could not find codec parameters for stream 0 (Audio: aac (LTP), 7.1, fltp, 1397 kb/s): unspecified sample rate
Consider increasing the value for the 'analyzeduration' and 'probesize' options
/Users/Zard1096/Downloads/80bOOOPICdb.swf: could not find codec parameters
    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0  


Second file set the option  'analyzeduration' and 'probesize' is also useless(including increasing the value).
These two can be played on the Web browser like Safari(installed Flash Player) and Chrome.

These two swf file: http://pan.baidu.com/s/1hqu8Gte, password: ah8w.
The files come from internet，if there is infringement, please contact me to delete them.

Is these swf files not standard format,or all swf format could not be play,thx @bbcallen 
Sorry for my poor english.

**Comment by bbcallen** [comment]
I'm not familiar with swf format. If ffplay doesn't work,too, you'd better submit this issue to ffmpeg, to get more reliable answers.

**Comment by Zard1096** [comment]
Thx. I will do it and bring answer on this issue.

**Comment by Zard1096** [comment]
No reply from the forum.
I will close this issue until I got answer.
If anyone have the answer or idea about it,plz reply on 
https://ffmpeg.zeranoe.com/forum/viewtopic.php?f=7&t=2552.
Thx.

**Comment by fgh345** [comment]
> RT，我在ffmpeg的文件夹libavformat中有发现swf和swfdec，按理应该支持swf的播放，我也在配置文件中配置了一下swf，但是在播放的时候仍然弹出了Invalid data found when processing input。

请问 您最终解决了吗?
