### ISSUE TITLE
videotoolbox

### ISSUE THREAD

**Issue by zcgit** [Bilibili/ijkplayer#3622]
我看ffmpeg在编译的时候可以设置--enable-videotoolbox来支持硬解码，为什么ijk还要自己实现硬解码那块呢？难道ffmpeg是只支持编码而不支持解码吗？

**Comment by raymond1012** [comment]
为了更好的兼容render 部分，减少对ffmpeg的改动

**Comment by zcgit** [comment]
可是我打开ffmpeg的这个貌似也没有用到硬解啊，是不是硬解确实不行啊，需要按ijk这种手动接入才行吗？
我用这种方式：
AVHWAccel *hwaccel=NULL;
    while((hwaccel = av_hwaccel_next(hwaccel))){
        log("name:%s type:%d id:%u pix:%d",hwaccel->name,hwaccel->type,hwaccel->id,hwaccel->pix_fmt);
    }
获取的是：
name:h263_videotoolbox type:0 id:5 pix:334
name:h264_videotoolbox type:0 id:28 pix:334
name:mpeg1_videotoolbox type:0 id:1 pix:334
name:mpeg2_videotoolbox type:0 id:2 pix:334
name:mpeg4_videotoolbox type:0 id:13 pix:334
然后avcodec_find_decoder_by_name("h264_videotoolbox") 为空，不知道是什么原因？<br/>谢谢你@raymond1012
