### ISSUE TITLE
提个bug，已经缓存的视频，再次打开播放

### ISSUE THREAD

**Issue by hljstardust** [Bilibili/ijkplayer#3625]
提个bug，已经缓存的视频，再次打开播放，之前的缓存内容会被清除，并重新开始缓存，这个怎么解决？

**Comment by raymond1012** [comment]
如果是用了ijk的cache 功能，此为正常现象

**Comment by MrLaird** [comment]
@hljstardust 请教下视频缓存你是怎么打开的？
