### ISSUE TITLE
编译Android版本报错：'asm' operand has impossible constraints

### ISSUE THREAD

**Issue by TongKai** [Bilibili/ijkplayer#363]
开始我是使用默认的module.sh来进行编译的，可以成功编译。后来我想支持更多的格式，就按照步骤，执行了ln -s命令，之后就报错了，错误如下：

In file included from libavcodec/x86/mpegvideoenc.c:83:0:
libavcodec/x86/mpegvideoenc_template.c: In function 'dct_quantize_ssse3':
libavcodec/x86/mpegvideoenc_template.c:151:9: error: 'asm' operand has impossible constraints
         __asm__ volatile(
         ^
libavcodec/x86/mpegvideoenc_template.c:186:9: error: 'asm' operand has impossible constraints
         __asm__ volatile(
         ^
make: *** [libavcodec/x86/mpegvideoenc.o] Error 1

但是当我使用module-lite.sh时又不会报错，很郁闷~~希望可以各位可以解答。

**Comment by lionel0806** [comment]
Just modify android/contrib/tools/do-compile-ffmpeg.sh file, 
change the line
       FF_CFG_FLAGS="$FF_CFG_FLAGS --enable-asm"
to
       FF_CFG_FLAGS="$FF_CFG_FLAGS --disable-asm"

**Comment by TongKai** [comment]
I  modified the file as you said,but I got another problem:

--------------------
[*] link ffmpeg
--------------------
arm-linux-androideabi-gcc: error: libavutil/arm/*.o: No such file or directory
arm-linux-androideabi-gcc: error: libavcodec/arm/*.o: No such file or directory
arm-linux-androideabi-gcc: error: libswresample/arm/*.o: No such file or directory

**Comment by gordanxu** [comment]
遇到了同样的问题，修改之后报同样的错误，还请帮忙解答下，谢谢~
