### ISSUE TITLE
ijkplayer有动态库版本嘛

### ISSUE THREAD

**Issue by MarkBuster** [Bilibili/ijkplayer#3635]
听说能解决 ffmpeg冲突的问题。。

**Comment by raymond1012** [comment]
no

**Comment by lieryang** [comment]
我们项目现在有这个库, 因为业务需要同时需要 FFmpeg 现在导入项目能跑起来, 但是是哟好难过 FFmpeg 的时候会崩溃, 就是这个 framwork和 FFmpeg 会有冲突!  你解决了吗?
