### ISSUE TITLE
iOS11 播放只有声音没有图像

### ISSUE THREAD

**Issue by jjjdeveloper** [Bilibili/ijkplayer#3643]
ijkplayer在iOS11经常出现有声音没图像的情况,iOS10也都没问题,升到iOS11碰到这样的问题的,各位大佬有没有解决方案

**Comment by raymond1012** [comment]
ios11 模拟器bug

**Comment by jjjdeveloper** [comment]
非模拟器 真机阿

**Comment by CloudIAU** [comment]
我在iOS11下也遇到过这样的情况，我的解决方法是：
在IJKSDLGLView.m文件中，- (BOOL)setupEAGLContext:(EAGLContext *)context 方法的
`  glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_RENDERBUFFER, _renderbuffer);`
代码下面添加
`[CATransaction flush];`
在- (void)displayInternal: (SDL_VoutOverlay *) overlay 方法中
`IJK_GLES2_Renderer_setGravity(_renderer, _rendererGravity, _backingWidth, _backingHeight);`
代码下面也添加
`[CATransaction flush];`
即可解决这个问题，供参考。

**Comment by LeesimEverglow** [comment]
@CloudIAU  感谢 按照你的办法 重打了framework确实可以了

**Comment by fadaixiaohai** [comment]
@CloudIAU 感谢 确实能解决

**Comment by blueseaguo** [comment]
mark

**Comment by waitWindComing** [comment]
mark

**Comment by Sweet1225** [comment]
mark

**Comment by saijiang** [comment]
IJKFFOptions *options = [IJKFFOptions optionsByDefault];
    [options setOptionIntValue:2 forKey:@"videotoolbox" ofCategory:kIJKFFOptionCategoryPlayer];

**Comment by MichaelSSY** [comment]
@CloudIAU  我按照你的操作还是只有声音不显示画面啊？我的是最新的iOS系统！

**Comment by zhangfurun** [comment]
我也是  只有声音,黑屏

**Comment by wangzhaoyang123** [comment]
在ios的其他系统上也会出现类似的问题吗

**Comment by Antinust** [comment]
@CloudIAU 加了[CATransaction flush]，在iOS 13系统上出现了新的崩溃：Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread，有遇到么？

**Comment by outer1** [comment]
> @CloudIAU 加了[CATransaction flush]，在iOS 13系统上出现了新的崩溃：Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread，有遇到么？

我也遇到了了，在13.3.1上量特别大。。。有解决方案及时同步哈
