### ISSUE TITLE
How to drop several frames after starting a live stream.

### ISSUE THREAD

**Issue by garymabin** [Bilibili/ijkplayer#365]
Hi, I'm using ijkplayer to play a rtmp stream, there are some camera prepared frames at the start of the stream. How can I set to drop several frames after starting?

**Comment by bbcallen** [comment]
You need to modify ff_ffplay.c for this.

**Comment by garymabin** [comment]
@bbcallen , is there any key frame judge strategy in current implementation?

**Comment by bbcallen** [comment]
No.

**Comment by Android4MediaPlayer** [comment]
check if packet is key frame after starting, then queue, otherwise discard.

**Comment by Android4MediaPlayer** [comment]
for example:
av_read_frame(ic, pkt);
if(pkt->flags &AV_PKT_FLAG_KEY )
{
printf(“pkt is key frame\n”);
}

**Comment by garymabin** [comment]
I found it was not a client issue finally,  seems to be some bug around rtmp server.
