### ISSUE TITLE
Android Studio使用jcenter方式导入ijkplayer，发现不支持avi格式

### ISSUE THREAD

**Issue by xiongliangshan** [Bilibili/ijkplayer#3651]
compile 'tv.danmaku.ijk.media:ijkplayer-java:0.8.3'
    compile 'tv.danmaku.ijk.media:ijkplayer-exo:0.8.3'

    compile 'tv.danmaku.ijk.media:ijkplayer-armv5:0.8.3'
    compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.8.3'
    compile 'tv.danmaku.ijk.media:ijkplayer-arm64:0.8.3'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.8.3'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86_64:0.8.3'

**Comment by raymond1012** [comment]
enable avi in module-lite.sh
