### ISSUE TITLE
紧急！不能播放ape文件，已经用了module-default.sh

### ISSUE THREAD

**Issue by mouseOf2ch** [Bilibili/ijkplayer#3653]
下面是logcat：
updateConfiguration freq=2462 BSSID=38:97:d6:18:df:50 RSSI=-53 "FlyAuDio"WPA_PSK
10-10 19:13:51.145 1067-1067/system_process E/WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 25 num clients 12
10-10 19:13:51.145 1067-1067/system_process E/WifiTrafficPoller:  packet count Tx=8273 Rx=69260
10-10 19:13:51.145 1067-1067/system_process E/WifiTrafficPoller: notifying of data activity 1
10-10 19:13:51.379 14764-15336/cn.flyaudio.videoplayer E/IJKMEDIA: Unsupported file version - 4.11
10-10 19:13:51.381 14764-15336/cn.flyaudio.videoplayer E/IJKMEDIA: /storage/emulated/0/musicTest/ape/天空 - 王菲.ape: Not yet implemented in FFmpeg, patches welcome
10-10 19:13:51.382 14764-14764/cn.flyaudio.videoplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
10-10 19:13:51.684 1067-2072/system_process E/WifiMonitor: handleEvent unknown: 14  CTRL-EVENT-SCAN-STARTED

**Comment by mouseOf2ch** [comment]
@bbcallen

**Comment by raymond1012** [comment]
need enable ape demuxer and decoder

**Comment by mouseOf2ch** [comment]
@raymond1012 ，我已经在module-default.sh里面添加了
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=ape”
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=ape”
还是不行

**Comment by raymond1012** [comment]
编译后看看CONFIG_APE_DECODER 和 CONFIG_APE_DEMUXER 的值是不是变为1了

2017-10-11 10:27 GMT+08:00 mouseOf2ch <notifications@github.com>:

**Comment by mouseOf2ch** [comment]
@raymond1012  logcat里面能看到CONFIG_APE_DECODER 和 CONFIG_APE_DEMUXER 的值？

**Comment by raymond1012** [comment]
不能，在config.h中 根据配置自动生成

2017-10-11 10:33 GMT+08:00 mouseOf2ch <notifications@github.com>:

**Comment by mouseOf2ch** [comment]
@raymond1012 CONFIG_APE_DECODER 为0

**Comment by mouseOf2ch** [comment]
@raymond1012

**Comment by raymond1012** [comment]
添加到module-lite.sh中

2017-10-11 14:20 GMT+08:00 mouseOf2ch <notifications@github.com>:

**Comment by mouseOf2ch** [comment]
@raymond1012 ,添加到module-lite.sh中？module-lite.sh不是用来减少播放格式的吗？
if you prefer less codec/format for smaller binary size (by default)
cd config
rm module.sh
ln -s module-lite.sh module.sh
cd android/contrib
# cd ios
sh compile-ffmpeg.sh clean
上面是IJKPLAYER的remind

**Comment by mouseOf2ch** [comment]
@raymond1012 添加的话是把
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=ape”
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=ape”
添加到module-lite.sh？

**Comment by mouseOf2ch** [comment]
@raymond1012

**Comment by raymond1012** [comment]
默认 module.sh ln module-lite.sh

2017-10-11 15:45 GMT+08:00 mouseOf2ch <notifications@github.com>:

**Comment by mouseOf2ch** [comment]
@raymond1012 添加使用更多格式不是ln -s module-default.sh module.sh？
要是添加到module-lite.sh不就没用到了module-lite.sh了？还是说在编译的时候依然会用到 module-lite.sh

**Comment by mouseOf2ch** [comment]
@raymond1012 ，那我添加
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=ape”
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=ape”
到module-lite.sh时用那种方式编译：
1.If you prefer more codec/format；
2.If you prefer less codec/format for smaller binary size (by default)

**Comment by raymond1012** [comment]
如果你想用module-default.sh, 那么就 ln -s module-default.sh module.sh

2017-10-11 15:53 GMT+08:00 mouseOf2ch <notifications@github.com>:

**Comment by mouseOf2ch** [comment]
@raymond1012 这样的话使用 ln -s module-default.sh module.sh，那之前说的添加到module-lite.sh还有用吗？

**Comment by mouseOf2ch** [comment]
@raymond1012 ，按照你给的解决思路是：在module-lite.sh添加对ape文件的支持，再 ln -s module-default.sh module.sh，然后编译？

**Comment by mouseOf2ch** [comment]
@raymond1012

**Comment by mouseOf2ch** [comment]
@raymond1012 ，按照你给的解决思路是：在module-lite.sh添加对ape文件的支持，再 ln -s module-default.sh module.sh，然后编译？

**Comment by mouseOf2ch** [comment]
@raymond1012 ,谢谢大大耐心的解答，不过我试了之后还是不能播放

**Comment by mouseOf2ch** [comment]
@raymond1012 是不是要该底层代码？

**Comment by raymond1012** [comment]
不需要，只要确定config.h里是对的，那就没问题

**Comment by mouseOf2ch** [comment]
@raymond1012 可是不管在module-lite.sh添加
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=ape”
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=ape”
还是在module-default.sh里添加支持，都还是不能播放ape格式文件，是不是还要再添加什么步骤，其他的格式都可以播放，唯独ape不能，纳闷啊！

**Comment by mouseOf2ch** [comment]
多添加了这两个试下：
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-parser=ape"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-muxer=ape"

**Comment by mouseOf2ch** [comment]
@raymond1012 不管怎么加都不能播放，config.h都不行，我怀疑是不是要多加什么步骤，按道理来说module-default.sh应该能播放ape文件的，其他各种格式都能播放，就它搞特殊（^ ^）

**Comment by mouseOf2ch** [comment]
@raymond1012  config.h中CONFIG_APE_DECODER 和 CONFIG_APE_DEMUXER 一直为0

**Comment by mouseOf2ch** [comment]
@bbcallen

**Comment by mouseOf2ch** [comment]
@raymond1012

**Comment by eximpression** [comment]
你这个ape文件的编码版本是4.11，ffmpeg里支持的最高版本是3.99.就这样。
