### ISSUE TITLE
断网再恢复，不能重连

### ISSUE THREAD

**Issue by aslgd** [Bilibili/ijkplayer#3659]
三星S6手机，播放在线视频过程中，手动断开网络再连接，视频不能继续缓冲播放。
protocol是 async:ijkhttphook:
请问有没有解决方法？

**Comment by raymond1012** [comment]
需要实现 onnativeinvoke 并返回true，才能重试

2017-10-12 14:35 GMT+08:00 aslgd <notifications@github.com>:

**Comment by aslgd** [comment]
已经监听了onNativeInvoke，现象是断网以后，不会回调到onNativeInvoke方法

**Comment by DyncKathline** [comment]
实现 onnativeinvoke 并返回true。重连后，可以继续播放，但是一段时间后可能会走onError方法
mp.getVideoCachedDuration();
mp.getAudioCachedDuration();
都会更新值（跟没重连之前一样的效果），为什么会出现这样的问题？

**Comment by DyncKathline** [comment]
@raymond1012

**Comment by raymond1012** [comment]
need log

2017-10-19 8:55 GMT+08:00 DyncKathline <notifications@github.com>:

**Comment by DyncKathline** [comment]
10-19 10:31:21.278 7039-7039/org.dync.ijkplayer I/NetworkChangedReceiver: 手机网络数据断开
10-19 10:31:21.278 7039-7039/org.dync.ijkplayer I/NetworkChangedReceiver: NetworkInfo: [type: MOBILE[LTE], state: DISCONNECTED/DISCONNECTED, reason: connected, extra: CTNET, failover: false, available: true, roaming: false, metered: true]
10-19 10:31:21.286 7039-7039/org.dync.ijkplayer I/NetworkChangedReceiver: WIFI网络连上
10-19 10:31:21.286 7039-7039/org.dync.ijkplayer I/NetworkChangedReceiver: NetworkInfo: [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "HiWiFi_DYNC_5G", failover: false, available: true, roaming: false, metered: false]
10-19 10:31:21.816 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 1, offset 0x1088db7: partial file
10-19 10:31:21.816 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:31:21.926 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 0, offset 0x1088f1b: partial file
10-19 10:31:21.926 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:31:22.037 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 1, offset 0x1089d44: partial file
10-19 10:31:22.037 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:31:22.147 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 1, offset 0x1089ef8: partial file
10-19 10:31:22.147 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown10-19 10:31:40.396 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 1, offset 0x110d610: partial file
10-19 10:31:40.397 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:31:40.508 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 0, offset 0x110d76e: partial file
10-19 10:31:40.508 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:31:40.618 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 1, offset 0x110ed92: partial file
10-19 10:31:40.618 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:31:40.728 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 0, offset 0x110eef5: partial file
10-19 10:31:40.729 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:31:41.613 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 1, offset 0x1111941: partial file
10-19 10:31:41.613 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:31:41.724 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 0, offset 0x1111aa0: partial file
10-19 10:31:41.724 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:31:41.834 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 1, offset 0x11120bd: partial file
10-19 10:31:41.834 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:31:41.945 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 1, offset 0x1112220: partial file
10-19 10:31:41.945 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:31:42.055 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 0, offset 0x1112391: partial file
10-19 10:31:42.055 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
......
10-19 10:32:04.619 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 0, offset 0x1181960: partial file
10-19 10:32:04.619 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:32:04.729 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 1, offset 0x1181c9f: partial file
10-19 10:32:04.729 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:32:04.839 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 0, offset 0x1181e0b: partial file
10-19 10:32:04.839 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:32:04.950 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 1, offset 0x1183867: partial file
10-19 10:32:04.950 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:32:05.060 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 1, offset 0x11839db: partial file
10-19 10:32:05.060 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:32:05.171 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 0, offset 0x1183b46: partial file
10-19 10:32:05.171 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:32:05.281 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 1, offset 0x1183ee1: partial file
10-19 10:32:05.281 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:32:05.393 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 1, offset 0x1184051: partial file
10-19 10:32:05.393 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:32:05.504 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 0, offset 0x11841c1: partial file
10-19 10:32:05.504 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:32:05.614 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 1, offset 0x1186112: partial file
10-19 10:32:05.614 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:32:05.725 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 1, offset 0x1186280: partial file
10-19 10:32:05.725 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:32:05.836 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 0, offset 0x11863eb: partial file
10-19 10:32:05.836 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:32:05.946 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 1, offset 0x118688b: partial file
10-19 10:32:05.946 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:32:06.057 7039-8331/org.dync.ijkplayer E/IJKMEDIA: stream 0, offset 0x11869f8: partial file
10-19 10:32:06.057 7039-8331/org.dync.ijkplayer E/IJKMEDIA: av_read_frame error: unknown
10-19 10:32:06.168 7039-8331/org.dync.ijkplayer I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 3
10-19 10:32:06.169 7039-8331/org.dync.ijkplayer I/IJKMEDIA: Hit DNS cache hostname = baobab.wdjcdn.com
10-19 10:32:06.169 7039-8331/org.dync.ijkplayer I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
10-19 10:32:06.189 7039-8331/org.dync.ijkplayer I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
10-19 10:32:06.204 7039-8331/org.dync.ijkplayer I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 4
10-19 10:32:53.517 7039-8346/org.dync.ijkplayer E/IJKMEDIA: decode_band_types: Input buffer exhausted before END element found
10-19 10:32:54.292 7039-8331/org.dync.ijkplayer I/IJKMEDIA: ffp_toggle_buffering: error: -103
10-19 10:32:54.292 7039-8331/org.dync.ijkplayer I/IJKMEDIA: ffp_toggle_buffering: eof
10-19 10:32:54.293 7039-7039/org.dync.ijkplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by DyncKathline** [comment]
![image](https://user-images.githubusercontent.com/16282974/31751725-940c1494-b4b9-11e7-9e1f-acebfa572d1d.png)

**Comment by tigerface** [comment]
然后就没下文了。。这日志打的哗哗的
