### ISSUE TITLE
如何配置ijkplayer支持FTP地址播放视频

### ISSUE THREAD

**Issue by TakakuraAnzu** [Bilibili/ijkplayer#3660]
将FTP服务器上的视频地址传入ijkplayer黑屏不能播放，FFmpeg官网文档上是支持FTP播放的，如何配置编译文件才能使ijkplayer支持播放FTP视频
下面的Debug日志:
10-12 14:21:07.651 25967-25967/com.illya.player I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170829--001
10-12 14:21:07.652 25967-25967/com.illya.player I/IJKMEDIA: ijk_version_info: k0.8.3-20-ge1d04bd8
10-12 14:21:07.657 25967-25967/com.illya.player D/IJKMEDIA: ffpipeline_create_from_android()
10-12 14:21:07.657 25967-25967/com.illya.player D/IJKMEDIA: ijkmp_set_inject_opaque(0x100846)
10-12 14:21:07.657 25967-25967/com.illya.player D/IJKMEDIA: ijkmp_set_inject_opaque()=void
10-12 14:21:07.657 25967-25967/com.illya.player D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x100846)
10-12 14:21:07.658 25967-25967/com.illya.player D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
10-12 14:21:07.658 25967-25967/com.illya.player D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
10-12 14:21:07.658 25967-25967/com.illya.player D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
10-12 14:21:07.658 25967-25967/com.illya.player D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
10-12 14:21:07.658 25967-25967/com.illya.player D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(3)
10-12 14:21:07.658 25967-25967/com.illya.player D/IJKMEDIA: moncleanup
10-12 14:21:07.658 25967-25967/com.illya.player D/IJKMEDIA: IjkMediaPlayer_setOptionLong
10-12 14:21:07.658 25967-25967/com.illya.player D/IJKMEDIA: IjkMediaPlayer_setOptionLong
10-12 14:21:07.658 25967-25967/com.illya.player D/IJKMEDIA: IjkMediaPlayer_setOptionLong
10-12 14:21:07.658 25967-25967/com.illya.player D/IJKMEDIA: IjkMediaPlayer_setOptionLong
10-12 14:21:07.658 25967-25967/com.illya.player D/IJKMEDIA: IjkMediaPlayer_setOptionLong
10-12 14:21:07.658 25967-25967/com.illya.player D/IJKMEDIA: IjkMediaPlayer_setOptionLong
10-12 14:21:07.658 25967-25967/com.illya.player D/IJKMEDIA: IjkMediaPlayer_setOptionLong
10-12 14:21:07.659 25967-25967/com.illya.player D/tv.danmaku.ijk.media.player.IjkMediaPlayer: Couldn't open file on client side, trying server side
10-12 14:21:07.659 25967-25967/com.illya.player D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
10-12 14:21:07.659 25967-25967/com.illya.player V/IJKMEDIA: setDataSource: path ftp://illya:niconiconi@192.168.10.125:21/Desktop/01.mp4
10-12 14:21:07.659 25967-25967/com.illya.player D/IJKMEDIA: ijkmp_set_data_source(url="ftp://illya:niconiconi@192.168.10.125:21/Desktop/01.mp4")
10-12 14:21:07.659 25967-25967/com.illya.player D/IJKMEDIA: ijkmp_set_data_source(url="ftp://illya:niconiconi@192.168.10.125:21/Desktop/01.mp4")=0
10-12 14:21:07.659 25967-25967/com.illya.player D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
10-12 14:21:07.659 25967-25967/com.illya.player D/IJKMEDIA: ijkmp_set_android_surface(surface=0x7fec60cb58)
10-12 14:21:07.661 25967-25967/com.illya.player D/IJKMEDIA: ffpipeline_set_surface()
10-12 14:21:07.661 25967-25967/com.illya.player D/IJKMEDIA: ijkmp_set_android_surface(surface=0x7fec60cb58)=void
10-12 14:21:07.661 25967-25967/com.illya.player D/IJKMEDIA: IjkMediaPlayer_prepareAsync
10-12 14:21:07.661 25967-25967/com.illya.player D/IJKMEDIA: ijkmp_prepare_async()
10-12 14:21:07.661 25967-25967/com.illya.player I/IJKMEDIA: ===== versions =====
10-12 14:21:07.661 25967-25967/com.illya.player I/IJKMEDIA: ijkplayer    : k0.8.3-20-ge1d04bd8
10-12 14:21:07.661 25967-25967/com.illya.player I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170829--001
10-12 14:21:07.661 25967-25967/com.illya.player I/IJKMEDIA: libavutil    : 55.58.100
10-12 14:21:07.661 25967-32438/com.illya.player I/IJKMEDIA: SDL_RunThread: [32438] ff_msg_loop
10-12 14:21:07.661 25967-32438/com.illya.player D/IJKMEDIA: message_loop
10-12 14:21:07.662 25967-32438/com.illya.player D/IJKMEDIA: FFP_MSG_FLUSH:
10-12 14:21:07.663 25967-25967/com.illya.player I/IJKMEDIA: libavcodec   : 57.89.100
10-12 14:21:07.663 25967-25967/com.illya.player I/IJKMEDIA: libavformat  : 57.71.100
10-12 14:21:07.663 25967-25967/com.illya.player I/IJKMEDIA: libswscale   : 4.6.100
10-12 14:21:07.663 25967-25967/com.illya.player I/IJKMEDIA: libswresample: 2.7.100
10-12 14:21:07.663 25967-25967/com.illya.player I/IJKMEDIA: ===== options =====
10-12 14:21:07.663 25967-25967/com.illya.player I/IJKMEDIA: player-opts : mediacodec                   = 0
10-12 14:21:07.663 25967-25967/com.illya.player I/IJKMEDIA: player-opts : opensles                     = 0
10-12 14:21:07.663 25967-25967/com.illya.player I/IJKMEDIA: player-opts : overlay-format               = 842225234
10-12 14:21:07.663 25967-25967/com.illya.player I/IJKMEDIA: player-opts : framedrop                    = 1
10-12 14:21:07.663 25967-25967/com.illya.player I/IJKMEDIA: player-opts : start-on-prepared            = 0
10-12 14:21:07.663 25967-25967/com.illya.player I/IJKMEDIA: format-opts : ijkapplication               = 547869392640
10-12 14:21:07.663 25967-25967/com.illya.player I/IJKMEDIA: format-opts : ijkiomanager                 = 547329783424
10-12 14:21:07.663 25967-25967/com.illya.player I/IJKMEDIA: format-opts : http-detect-range-support    = 0
10-12 14:21:07.664 25967-25967/com.illya.player I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
10-12 14:21:07.664 25967-25967/com.illya.player I/IJKMEDIA: ===================
10-12 14:21:07.666 25967-25967/com.illya.player D/IJKMEDIA: ijkmp_prepare_async()=0
10-12 14:21:07.666 25967-32439/com.illya.player I/IJKMEDIA: SDL_RunThread: [32439] ff_vout
10-12 14:21:07.666 25967-32440/com.illya.player I/IJKMEDIA: SDL_RunThread: [32440] ff_read
10-12 14:21:07.666 25967-32440/com.illya.player D/IJKMEDIA: Setting default whitelist 'tcp'
10-12 14:21:07.666 25967-32440/com.illya.player I/IJKMEDIA: Hit DNS cache hostname = 192.168.10.125
10-12 14:21:07.766 25967-32440/com.illya.player D/IJKMEDIA: 220 192.168.10.125 FTP server (tnftpd 20100324+GSSAPI) ready.
10-12 14:21:07.771 25967-32440/com.illya.player D/IJKMEDIA: 331 User illya accepted, provide password.
10-12 14:21:07.931 25967-32440/com.illya.player D/IJKMEDIA: 230 User illya logged in.
10-12 14:21:07.935 25967-32440/com.illya.player D/IJKMEDIA: 200 Type set to I.
10-12 14:21:07.937 25967-32440/com.illya.player D/IJKMEDIA: 211-Features supported
10-12 14:21:07.986 25967-32440/com.illya.player D/IJKMEDIA:  MDTM
10-12 14:21:07.986 25967-32440/com.illya.player D/IJKMEDIA:  MLST Type*;Size*;Modify*;Perm*;Unique*;
10-12 14:21:07.986 25967-32440/com.illya.player D/IJKMEDIA:  REST STREAM
10-12 14:21:07.986 25967-32440/com.illya.player D/IJKMEDIA:  SIZE
10-12 14:21:07.986 25967-32440/com.illya.player D/IJKMEDIA:  TVFS
10-12 14:21:07.986 25967-32440/com.illya.player D/IJKMEDIA: 211 End
10-12 14:21:07.991 25967-32440/com.illya.player D/IJKMEDIA: 257 "/Users/illya" is the current directory.
10-12 14:21:07.995 25967-32440/com.illya.player D/IJKMEDIA: 350 Restarting at 0. Send STORE or RETRIEVE to initiate transfer.
10-12 14:21:08.000 25967-32440/com.illya.player D/IJKMEDIA: 213 322610272
10-12 14:21:08.004 25967-32440/com.illya.player D/IJKMEDIA: 229 Entering Extended Passive Mode (|||60832|)
10-12 14:21:08.004 25967-32440/com.illya.player I/IJKMEDIA: Hit DNS cache hostname = 192.168.10.125

**Comment by raymond1012** [comment]
应该是和ftp 配置有关，播放器应该是主动模式才对

**Comment by TakakuraAnzu** [comment]
版本问题,不用另外配置

**Comment by TakakuraAnzu** [comment]
版本问题,不用另外配置

**Comment by TakakuraAnzu** [comment]
@Pcookie 版本问题不能播放,不用特别配置,使用其他版本即可

**Comment by lm3515** [comment]
@TakakuraAnzu 哪个版本可以播？

**Comment by swithun-liu** [comment]
@TakakuraAnzu 请问，咋搞好的
