### ISSUE TITLE
我在MAC下只编译出了libijkffmpeg.so，其他的没有编译出来，请问下是什么原因

### ISSUE THREAD

**Issue by wangyuehong1982** [Bilibili/ijkplayer#367]
昨天我按照文档上说的在MAC上，用bash编译，可是只是编译出 libijkffmpeg.so 这一个so库，请问我是哪里出了什么错误吗？

**Comment by Android4MediaPlayer** [comment]
贴出你的编译命令行

**Comment by wangyuehong1982** [comment]
您好：下面是我用bash编译的命令
./init-android.sh
cd android/contrib
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all
cd ..
./compile-ijk.sh all
就这几行，编译出后的libijkffmpeg.so有好几十M（我是初学者，见谅）

**Comment by Android4MediaPlayer** [comment]
你的命令行的输出日志 可能你的ijk没编译成功

**Comment by wangyuehong1982** [comment]
您好，我也觉得我没有编译成功。我可以在重新编译一次吗？如果可以的话，只需要重新执行一次上面的命令就可以了嘛？

**Comment by wangyuehong1982** [comment]
我是昨天编译的，命令的日志已经清空了

**Comment by Android4MediaPlayer** [comment]
可先编译一个平台的
cd android/contrib
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh
cd ..
./compile-ijk.sh

**Comment by wangyuehong1982** [comment]
恩，我刚才执行 ./compile-ffmpeg.sh clean 的时候 报出：
warning: failed to remove .config
warning: failed to remove .version
warning: failed to remove compat/strtod.d
warning: failed to remove compat/strtod.o
warning: failed to remove config.fate
warning: failed to remove config.h
warning: failed to remove config.log
warning: failed to remove config.mak
warning: failed to remove doc/config.texi
warning: failed to remove doc/examples/pc-uninstalled/libavcodec.pc
warning: failed to remove doc/examples/pc-uninstalled/libavformat.pc
warning: failed to remove doc/examples/pc-uninstalled/libavutil.pc
warning: failed to remove doc/examples/pc-uninstalled/libswresample.pc
warning: failed to remove doc/examples/pc-uninstalled/libswscale.pc
warning: failed to remove libavcodec/012v.d
warning: failed to remove libavcodec/012v.o
warning: failed to remove libavcodec/4xm.d
warning: failed to remove libavcodec/4xm.o
。。。。。。
这样的错误，请问有影响吗？

**Comment by wangyuehong1982** [comment]
上面的错误已经解决

**Comment by Android4MediaPlayer** [comment]
情况怎么样了

**Comment by wangyuehong1982** [comment]
您好，执行./compile-ijk.sh的时候好像出问题了

--------------------
[*] link ffmpeg
--------------------
-Wl,--fix-cortex-a8

--------------------
[*] create files for shared ffmpeg
--------------------
sh-3.2# cd ..
sh-3.2# ls
.DS_Store	.gitignore	compile-ijk.sh	contrib		ijkplayer
sh-3.2# ./compile-ijk.sh
profiler build: NO
[armeabi-v7a] Prebuilt       : libijkffmpeg.so <= /Users/NiKOo/Desktop/projects/ijkplayer-master/android/contrib/build/ffmpeg-armv7a/output/
[armeabi-v7a] Install        : libijkffmpeg.so => libs/armeabi-v7a/libijkffmpeg.so
/Users/NiKOo/desktop/projects/ijkplayer-master/android

**Comment by wangyuehong1982** [comment]
执行 ./compile-ffmpeg.sh 的时候日志打印出来很多warning

**Comment by zhangbl** [comment]
我跟你的一样，我直接用ndk编译也是只有一个so包，我感觉是mk文件的问题，求解。。。

**Comment by wangyuehong1982** [comment]
按照文档说明重新打了一个轻量级的so库，结果还是打出来一个libijkffmpeg.so（13.7MB）

**Comment by zhangbl** [comment]
可以自己把 ijkmedia下的mk导入，去掉android-ndk-profiler，就可以编译出来了

**Comment by wangyuehong1982** [comment]
编译成功了，谢谢！

**Comment by xiaoyaomeng** [comment]
编译Android也遇到这种情况，请问你们是怎么解决？

**Comment by hljstardust** [comment]
@wangyuehong1982 我也遇到了，请问这个问题是怎么解决的？
