### ISSUE TITLE
Android 如何去除指定的 header

### ISSUE THREAD

**Issue by TimmyMa** [Bilibili/ijkplayer#3673]
`IjkMediaPlayer` 在请求视频的时候会默认带上一些 header ，使用 `IjkMediaPlayer.setOption(int category, String name, String value)` -> `_setOption` 可以覆盖默认 header，请问有没有接口可以去除指定的默认的 header 呢？或是允许手动指定 header 内容？

**Comment by raymond1012** [comment]
没有，除非去修改http.c
