### ISSUE TITLE
本地m3u8文件,libijkffmpeg.so抛出了错误,请问是不支持这种还是需要设置?

### ISSUE THREAD

**Issue by xuqinghao1991** [Bilibili/ijkplayer#3676]
我是本地起了个server,用的保留地址,随机生成的端口号
androidMediaPlayer,ijkExoMediaPlayer都可以播放,ijkMediaPlayer不可以,但是我们要用IjkmediaPlayer.
libijkffmpeg.so抛出来的错误,全局搜索到的
Unable to open key file https://verify.offcn.com/apikeys/getkeys/?v=1&n=201709%2Fcf5d35c6e65c74dd26d32ad5313d5681%2F1504577129841&zgKeys=9803jTImoSX%2F0hz0fJ97XnLPdoNv7nn6tq0OuVFa9J%2BI7e4swlQbf3vh

m3u8文件:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:5
#EXT-X-KEY:METHOD=AES-128,URI="https://verify.offcn.com/apikeys/getkeys/?v=1&n=201709%2Fcf5d35c6e65c74dd26d32ad5313d5681%2F1504577129841&zgKeys=9803jTImoSX%2F0hz0fJ97XnLPdoNv7nn6tq0OuVFa9J%2BI7e4swlQbf3vh",IV=0x63373730656435656335663331666332
#EXTINF:2.333333,
http://kejian3.offcn.com/tushu/201708/jszg/xxzhsz-08/15045771298410.zg
#EXTINF:3.933333,
http://kejian3.offcn.com/tushu/201708/jszg/xxzhsz-08/15045771298411.zg

**Comment by raymond1012** [comment]
need compile openssl

**Comment by xuqinghao1991** [comment]
@raymond1012 可以了,这个问题解决了,请问我播放本地m3u8文件报这2个错误,请问怎么解决
1.Error when loading first segment 'http://kejian3.offcn.com/tushu/201708/jszg/xxzhsz08/15045771298410.zg'
2.http://127.0.0.1:12049/storage/emulated/0/offcnitc/yidongzixishi/18811242229/tempFile/m3u8_path.m3u8: Invalid data found when processing input
本地m3u8文件其中一部分
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:5
#EXT-X-KEY:METHOD=AES-128,URI="https://verify.offcn.com/apikeys/getkeys/?v=1&n=201709%2Fcf5d35c6e65c74dd26d32ad5313d5681%2F1504577129841&zgKeys=9803jTImoSX%2F0hz0fJ97XnLPdoNv7nn6tq0OuVFa9J%2BI7e4swlQbf3vh",IV=0x63373730656435656335663331666332
#EXTINF:2.333333,
http://kejian3.offcn.com/tushu/201708/jszg/xxzhsz-08/15045771298410.zg
#EXTINF:3.933333,
http://kejian3.offcn.com/tushu/201708/jszg/xxzhsz-08/15045771298411.zg
#EXTINF:3.533333,
http://kejian3.offcn.com/tushu/201708/jszg/xxzhsz-08/15045771298412.zg
#EXTINF:4.000000,
http://kejian3.offcn.com/tushu/201708/jszg/xxzhsz-08/15045771298413.zg
#EXTINF:4.000000,
http://kejian3.offcn.com/tushu/201708/jszg/xxzhsz-08/15045771298414.zg
#EXT-X-ENDLIST
