### ISSUE TITLE
动态直播流没有总时长duration，ijk播放器无法获取总时长，是否支持seekTo功能？

### ISSUE THREAD

**Issue by Lucky-Hong** [Bilibili/ijkplayer#3677]
测试步骤：iOS平台下，在直播过程中，拿到一个动态的直播流，支持4个小时的时移功能，默认播放当前时间的直播（电视直播），可以时移（相对当前时间后退）4小时内任意一点进行播放，即可以进行seekTo功能，但是这个直播流的duration是0，ijk内部是否进行处理过duration为0的情况，或者说是不支持此情况下的seekTo功能？目前问题定位在此，时移某一点无法进行播放，请问有没有好的解决办法？或者是ijk需要进行什么配置？
测试地址（附上一个支持时移的直播流地址）：http://111.44.138.251:15414/contents39/live/CHANNEL9908b259e5a74eb59270318d56a33840/SD_217579031606857011/timeshift.m3u8
希望各位大大帮助一下，感谢！！

**Comment by Lucky-Hong** [comment]
说明：iOS平台

**Comment by hywenbinger** [comment]
直播流不能seekTo

**Comment by Lucky-Hong** [comment]
@hywenbinger 嗯，那也就是说即使加上一个时移的直播流，也无法进行seekTo功能，是这样不？

**Comment by Lucky-Hong** [comment]
@hywenbinger 说明下，上述那个测试地址，实际上是一个伪直播，直播时直接服务器往外推流，肯定是不支持seekTo的功能，但是他这4个小时的时移，其实服务器是有缓存的，只是那个m3u8的文件一直在变，里面的切片和配置文件都在动态更新，特别那个配置文件的文字都变了，感觉就是ijk在计算总时长duration的时候出问题了，会不会是ijk会认哪个文件，但是这个文件却一直在变，导致无法播放时移到某一点的视频呢？（seekTo应该和总时长没关系吧），或者有没有其它解决的思路呢？
