### ISSUE TITLE
本地m3u8文件播放报错,麻烦解答下吧,困扰好几天了,谢谢

### ISSUE THREAD

**Issue by xuqinghao1991** [Bilibili/ijkplayer#3679]
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", "crypto,file,http,https,tcp,tls,udp");设置了白名单也还是报这个错误
本地起了个server用来播放,用的是保留地址,端口号是随机生成的.
http://127.0.0.1:12049/storage/emulated/0/tempFile/m3u8_path.m3u8
报错内容
1.Error when loading first segment 'http://kejian3.offcn.com/tushu/201708/jszg/xxzhsz-08/15045771298410.zg'
2.http://127.0.0.1:12049/storage/emulated/0/tempFile/m3u8_path.m3u8: Invalid data found when processing input
本地m3u8文件一部分:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:5
#EXT-X-KEY:METHOD=AES-128,URI="https://verify.offcn.com/apikeys/getkeys/?v=1&n=201709%2Fcf5d35c6e65c74dd26d32ad5313d5681%2F1504577129841&zgKeys=9803jTImoSX%2F0hz0fJ97XnLPdoNv7nn6tq0OuVFa9J%2BI7e4swlQbf3vh",IV=0x63373730656435656335663331666332
#EXTINF:2.333333,
http://kejian3.offcn.com/tushu/201708/jszg/xxzhsz-08/15045771298410.zg
#EXTINF:3.933333,
http://kejian3.offcn.com/tushu/201708/jszg/xxzhsz-08/15045771298411.zg
#EXTINF:3.533333,
http://kejian3.offcn.com/tushu/201708/jszg/xxzhsz-08/15045771298412.zg
#EXTINF:4.000000,
http://kejian3.offcn.com/tushu/201708/jszg/xxzhsz-08/15045771298413.zg
#EXTINF:4.000000,
http://kejian3.offcn.com/tushu/201708/jszg/xxzhsz-08/15045771298414.zg
#EXTINF:4.000000,
http://kejian3.offcn.com/tushu/201708/jszg/xxzhsz-08/15045771298415.zg
#EXTINF:4.000000,
http://kejian3.offcn.com/tushu/201708/jszg/xxzhsz-08/15045771298416.zg
#EXTINF:4.000000,
http://kejian3.offcn.com/tushu/201708/jszg/xxzhsz-08/15045771298417.zg
#EXTINF:4.000000,
http://kejian3.offcn.com/tushu/201708/jszg/xxzhsz-08/15045771298418.zg
#EXTINF:4.000000,
http://kejian3.offcn.com/tushu/201708/jszg/xxzhsz-08/15045771298419.zg
#EXT-X-ENDLIST

**Comment by gkj17** [comment]
请问您是怎么解决的呢
