### ISSUE TITLE
"No such file or directory" error

### ISSUE THREAD

**Issue by TongKai** [Bilibili/ijkplayer#368]
I am in trouble when I compile android version.Error log as I show.

[*] link ffmpeg
arm-linux-androideabi-gcc: error: libavutil/arm/.o: No such file or directory
arm-linux-androideabi-gcc: error: libavcodec/arm/.o: No such file or directory
arm-linux-androideabi-gcc: error: libswresample/arm/*.o: No such file or directory

Please help me,Thx.And ignore my poor English.

**Comment by Android4MediaPlayer** [comment]
more log,plz

**Comment by TongKai** [comment]
Sorry,that's all.I execute the command line:./compile-ffmpeg.sh all .The script can run for some time,then it stop,and shows me the log as I post.

**Comment by bbcallen** [comment]
No enough information.
