### ISSUE TITLE
android硬解码播放本地6帧以内的mp4文件

### ISSUE THREAD

**Issue by Luriwei** [Bilibili/ijkplayer#3681]
如题，android采用硬解码播放本地几帧的视频，一帧也解码不出来，显示黑屏；而用软解则可以解码出来，这个问题要怎么解决呢，谢啦

**Comment by Luriwei** [comment]
log如下：
D/IJKMEDIA: SDL_AMediaCodecJava_createByCodecName
D/IJKMEDIA: SDL_AMediaCodecJava_init
D/IJKMEDIA: SDL_AMediaCodec_increaseReference(): ref=1
D/IJKMEDIA: SDL_AMediaCodecJava_configure_surface
E/IJKMEDIA: configure acodec:0x200b92 format:0xbb2: surface:0xba6
D/IJKMEDIA: SDL_AMediaCodecJava_start
I/IJKMEDIA: reconfigure_codec_l:new acodec: 0xcfc83d20
D/IJKMEDIA: SDL_AMediaCodec_increaseReference(): ref=2
I/IJKMEDIA: VideoCodec: MediaCodec, OMX.qcom.video.decoder.avc
W/IJKMEDIA: fps: 29.970030 (normal)
W/IJKMEDIA: fps: 29.970030 (normal)
I/IJKMEDIA: SDL_RunThread: [15408] ff_video_dec
D/IJKMEDIA: FFP_MSG_VIDEO_SIZE_CHANGED: 3840, 1920
D/IJKMEDIA: FFP_MSG_SAR_CHANGED: 1, 1
D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_PREPARED
D/IJKMEDIA: FFP_MSG_PREPARED:
I/IJKMEDIA: SDL_RunThread: [15409] amediacodec_input_thread
D/IJKMEDIA: IjkMediaPlayer_start
D/IJKMEDIA: ijkmp_start()
D/IJKMEDIA: ijkmp_start()=0
D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
D/IJKMEDIA: ffpipeline_set_surface_need_reconfigure_l(0)
I/IJKMEDIA: feed_input_buffer: same surface, reuse previous surface
I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: INFO_OUTPUT_BUFFERS_CHANGED
I/IJKMEDIA: ffp_toggle_buffering: completed: OK
D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_COMPLETED
D/IJKMEDIA: FFP_MSG_COMPLETED:
I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: INFO_OUTPUT_FORMAT_CHANGED
I/IJKMEDIA: AMEDIACODEC__INFO_OUTPUT_FORMAT_CHANGED
D/IJKMEDIA: SDL_AMediaFormatJava_init
I/IJKMEDIA: AMEDIACODEC__INFO_OUTPUT_FORMAT_CHANGED
                                                                  width-height: (2560 x 1600)
                                                                  color-format: (QCOM_FORMATYUV420PackedSemiPlanar32m: 0x7fa30c04)
                                                                  stride:       (2560)
                                                                  slice-height: (1600)
                                                                  crop:         (0, 0, 2559, 1279)
D/IJKMEDIA: SDL_VoutAMediaCodec_CreateOverlay(w=3840, h=1920, fmt=_AMC vout=0xc5dfffe0)
D/IJKMEDIA: FFP_MSG_VIDEO_SIZE_CHANGED: 3840, 1920
D/IJKMEDIA: Video: first frame decoded

**Comment by chodison** [comment]
sample file

**Comment by Luriwei** [comment]
@chodison 文件在这，麻烦了~

[YITL_Stitch_0945_360.zip](https://github.com/Bilibili/ijkplayer/files/1397905/YITL_Stitch_0945_360.zip)

**Comment by Luriwei** [comment]
这个问题还有人在关注嘛，顶一下~~

**Comment by chodison** [comment]
@Luriwei 是个别机型吗？可以列举下测试机型

**Comment by Luriwei** [comment]
@chodison 应该不是个别机型的问题，我这边试了小米Max（系统7.0），小米5（系统7.0），小米MIX2（系统7.1.1），红米Note4（系统6.0），华为P9（系统7.0）均无法播放。之前提供的6帧的视频如果不停的调用播放器的start方法，有可能加载出其中一帧。
此处再提供一个4帧的视频，这个视频无论如何都播放不了了，跟到源码里看到这几帧都已经queueInputBuffer了，但是dequeueOutputBuffer时一只返回-1，然后就不停地重试。
[YITL_Stitch_0947_360.zip](https://github.com/Bilibili/ijkplayer/files/1445381/YITL_Stitch_0947_360.zip)

**Comment by Luriwei** [comment]
还有人在关注这个吗，我自己用mediacodec播放这几个视频是可以的，yongijkplayer的硬解就不行，比较奇怪

**Comment by chodison** [comment]
@Luriwei 六帧的视频地址在哪

**Comment by Luriwei** [comment]
@chodison 就在我之前的评论里，我压缩为zip文件了。

**Comment by SmallWeed** [comment]
#3900

**Comment by raymond1012** [comment]
android 6.0以上至少4帧，硬解才会出帧，如果你的视频只有几帧建议软解
