### ISSUE TITLE
The problem to  build ijkplayer with librtmp

### ISSUE THREAD

**Issue by only79** [Bilibili/ijkplayer#369]
Hi, I want to build ffmpeg with librtmp in ijkplayer project. Now I modify contrib/tools/do-compile-ffmpeg.sh file, the string after "+++" is my additional code. 

# Optimization options (experts only):
FF_CFG_FLAGS="$FF_CFG_FLAGS --enable-asm"
FF_CFG_FLAGS="$FF_CFG_FLAGS --enable-inline-asm"
+++FF_CFG_FLAGS="$FF_CFG_FLAGS --enable-nonfree"
+++FF_CFG_FLAGS="$FF_CFG_FLAGS --enable-gpl"
+++FF_CFG_FLAGS="$FF_CFG_FLAGS --enable-librtmp"
#--------------------
echo ""
echo "--------------------"
echo "[*] configurate ffmpeg"
echo "--------------------"
cd $FF_SOURCE

then I execute contrib/compile-ffmpeg.sh, errors as follows:
**********************************************************************************
ERROR: librtmp not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
************************************************************************************

    anyone can help me? Thanks.

**Comment by Zard1096** [comment]
You should install pkg-config and librtmp from brew or other way.

**Comment by bbcallen** [comment]
FFmpeg doesn't build librtmp for you, you should build it by yourself, and add include/lib path to FFmpeg's configuration.

**Comment by only79** [comment]
I understand, Thanks!

**Comment by Android4MediaPlayer** [comment]
@only79 Is it ok？
