### ISSUE TITLE
貌似dns cache功能有bug。

### ISSUE THREAD

**Issue by zhanggao** [Bilibili/ijkplayer#3696]
升级0.8.4后，同一直播间，rtmp和http-flv链接不断的释放打开，后面会无法连接http-flv。
0.7.8.1无这个问题。

**Comment by zhanggao** [comment]
貌似dns cache功能有bug。
设置dns_cache_clear 1 后不会有问题。

**Comment by raymond1012** [comment]
dns_cache_clear 是配合重连使用的，就是当http连接失败，则清楚对应的dns cache

**Comment by zhanggao** [comment]
https://github.com/Bilibili/ijkplayer/issues/3700
已找到问题了
