### ISSUE TITLE
为用ijkMediaPlayer播放视屏的时候总是有点卡顿！！！用系统的MediaPlayer就没有卡顿的现象！！

### ISSUE THREAD

**Issue by TianLuhua** [Bilibili/ijkplayer#3697]
ijkMediaPlayer版本：k0.8.4
使用的module-default.sh配置

**Comment by TianLuhua** [comment]
flv、mp4、mkv等都会有点卡顿，MPG和rmvb会好点

**Comment by TianLuhua** [comment]
--------- beginning of /dev/log/main
V/AudioPolicyService( 1181): getOutput()
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
V/AudioPolicyService( 1181): getOutput()
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
V/AudioPolicyService( 1181): getOutput()
[ 9478.806673] adau17x1_hw_params: params_rate=44100, adau->clk_src(0)
D/AudioPolicyMan[ 9478.814486] [set_dma_outbuffer], original len[16384]
agerBase( 1181): getDeviceForStrategy() strategy 0, device 2
D/AudioFlinger( 1181): AudioFlinger_ThreadBase_TrackBase_TrackBase ---> mCblkMemory allocate(size = 64)
V/AudioPolicyService( 1181): startOutput()
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 1, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 2, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 3, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 2, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 4, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 5, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForVolume 2
D/AudioPolicyManagerBase( 1181): getDeviceForVolume 2
--------- beginning of /dev/log/system
I/ActivityManager( 1600): START u0 {cmp=example.media.ijk.danmaku.tlh.tlhplayer/com.action.amp.ampplyer.activities.VideoActivity (has extras)} from pid 21118
V/AudioPolicyService( 1181): releaseOutput()
V/AudioPolicyService( 1181): inserting command: 6 at index 0, num commands 0
V/AudioPolicyService( 1181): AudioCommandThread() adding release output 2
V/AudioPolicyService( 1181): AudioCommandThread() waking up
V/AudioPolicyService( 1181): AudioCommandThread() processing release output 2
V/AudioPolicyService( 1181): doReleaseOutput from tid 1350
V/AudioPolicyService( 1181): AudioCommandThread() going to sleep
D/FastMixer( 1181): WARNING : memclear mixbuffer 2048 bytes
D/audio_hw_primary( 1181): start_output_stream()  persist.sys.spdif_setting=0 
V/audio_hw_primary( 1181): stat : /proc/asound/card1 : -1 type: 0
V/audio_hw_primary( 1181): stat : /proc/asound/card2 : -1 type: 0
V/android.view/ViewRootImpl(21118): handleMessage 6
I/audio_hw_primary( 1181): Card(0) Device(0) Name Normal Play
I/audio_hw_primary( 1181): start_output_stream, channel(2), samplerate(44100)
E/        (21118): SurfaceView doesn't support rotation (0)!
D/IJKMEDIA(21118): IjkMediaPlayer_native_profileBegin
W/IJKMEDIA(21118): monstartup already called
V/audio_hw_primary( 1181): out_get_latency : latency(23)
V/audio_hw_primary( 1181): out_get_latency : latency(23)
I/MediaFocusControl( 1600):  AudioFocus  requestAudioFocus() from android.media.AudioManager@42274c80
D/IJKMEDIA(21118): IjkMediaPlayer_native_setup
I/IJKMEDIA(21118): av_version_info: ff3.3--ijk0.8.0--20170829--001
I/IJKMEDIA(21118): ijk_version_info: k0.8.4-2-ge1d04bd8
D/IJKMEDIA(21118): ffpipeline_create_from_android()
D/IJKMEDIA(21118): ijkmp_set_inject_opaque(0x210004a2)
D/IJKMEDIA(21118): ijkmp_set_inject_opaque()=void
D/IJKMEDIA(21118): ijkmp_set_ijkio_inject_opaque(0x210004a2)
V/AudioPolicyService( 1181): stopOutput()
V/AudioPolicyService( 1181): inserting command: 5 at index 0, num commands 0
V/AudioPolicyService( 1181): AudioCommandThread() adding stop output 2
V/AudioPolicyService( 1181): AudioCommandThread() waking up
V/AudioPolicyService( 1181): AudioCommandThread() processing stop output 2
V/AudioPolicyService( 1181): doStopOutput from tid 1350
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 1, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 2, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 3, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 2, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 4, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 5, device 2
V/AudioPolicyService( 1181): AudioCommandThread() going to sleep
D/IJKMEDIA(21118): ijkmp_set_ijkio_inject_opaque()=void
D/IJKMEDIA(21118): ijkmp_android_set_mediacodec_select_callback()
D/IJKMEDIA(21118): ffpipeline_set_mediacodec_select_callback
D/IJKMEDIA(21118): ijkmp_android_set_mediacodec_select_callback()=void
D/IJKMEDIA(21118): IjkMediaPlayer_native_setLogLevel(3)
D/IJKMEDIA(21118): moncleanup
D/IJKMEDIA(21118): IjkMediaPlayer_setOptionLong
D/IJKMEDIA(21118): IjkMediaPlayer_setOptionLong
D/IJKMEDIA(21118): IjkMediaPlayer_setOptionLong
D/IJKMEDIA(21118): IjkMediaPlayer_setOptionLong
D/IJKMEDIA(21118): IjkMediaPlayer_setOptionLong
D/IJKMEDIA(21118): IjkMediaPlayer_setOptionLong
D/IJKMEDIA(21118): IjkMediaPlayer_setOptionLong
D/tv.danmaku.ijk.media.player.IjkMediaPlayer(21118): Couldn't open file on client side, trying server side
D/IJKMEDIA(21118): IjkMediaPlayer_setDataSourceAndHeaders
V/IJKMEDIA(21118): setDataSource: path /storage/usb0/amediaBig/信念.flv
D/IJKMEDIA(21118): ijkmp_set_data_source(url="/storage/usb0/amediaBig/信念.flv")
D/IJKMEDIA(21118): ijkmp_set_data_source(url="/storage/usb0/amediaBig/信念.flv")=0
D/IJKMEDIA(21118): IjkMediaPlayer_setVideoSurface
D/IJKMEDIA(21118): ijkmp_set_android_surface(surface=0x90b0001d)
D/IJKMEDIA(21118): ffpipeline_set_surface()
D/IJKMEDIA(21118): ijkmp_set_android_surface(surface=0x90b0001d)=void
D/IJKMEDIA(21118): IjkMediaPlayer_prepareAsync
D/IJKMEDIA(21118): ijkmp_prepare_async()
I/IJKMEDIA(21118): ===== versions =====
I/IJKMEDIA(21118): SDL_RunThread: [482] ff_msg_loop
D/IJKMEDIA(21118): message_loop
D/IJKMEDIA(21118): FFP_MSG_FLUSH:
I/IJKMEDIA(21118): ijkplayer    : k0.8.4-2-ge1d04bd8
I/IJKMEDIA(21118): FFmpeg       : ff3.3--ijk0.8.0--20170829--001
I/IJKMEDIA(21118): libavutil    : 55.58.100
I/IJKMEDIA(21118): libavcodec   : 57.89.100
I/IJKMEDIA(21118): libavformat  : 57.71.100
I/IJKMEDIA(21118): libswscale   : 4.6.100
I/IJKMEDIA(21118): libswresample: 2.7.100
I/IJKMEDIA(21118): ===== options =====
I/IJKMEDIA(21118): player-opts : mediacodec                   = 0
I/IJKMEDIA(21118): player-opts : opensles                     = 0
I/IJKMEDIA(21118): player-opts : overlay-format               = 842225234
I/IJKMEDIA(21118): player-opts : framedrop                    = 1
I/IJKMEDIA(21118): player-opts : start-on-prepared            = 0
I/IJKMEDIA(21118): format-opts : ijkapplication               = 1666588544
I/IJKMEDIA(21118): format-opts : ijkiomanager                 = 1661119872
I/IJKMEDIA(21118): format-opts : http-detect-range-support    = 0
I/IJKMEDIA(21118): codec-opts  : skip_loop_filter             = 48
I/IJKMEDIA(21118): ===================
I/IJKMEDIA(21118): SDL_RunThread: [483] ff_vout
D/IJKMEDIA(21118): ijkmp_prepare_async()=0
I/IJKMEDIA(21118): SDL_RunThread: [484] ff_read
D/IJKMEDIA(21118): Setting default whitelist 'file,crypto'
D/IJKMEDIA(21118): Format flv probed with size=2048 and score=100
D/IJKMEDIA(21118): FFP_MSG_OPEN_INPUT:
E/IJKMEDIA(21118): Option ijkapplication not found.
D/IJKMEDIA(21118): Before avformat_find_stream_info() pos: 13 bytes read:32768 seeks:0 nb_streams:0
D/IJKMEDIA(21118): nal_unit_type: 7, nal_ref_idc: 3
D/IJKMEDIA(21118): nal_unit_type: 8, nal_ref_idc: 3
D/IJKMEDIA(21118): user data:"x264 - core 125 - H.264/MPEG-4 AVC codec - Copyleft 2003-2012 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x1:0x131 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=2 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=2 b_pyramid=2 b_adapt=0 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=12 keyint_min=7 scenecut=40 intra_refresh=0 rc_lookahead=12 rc=abr mbtree=1 bitrate=1000 ratetol=1.0 qcomp=0.60 qpmin=6 qpmax=51 qpstep=4 ip_ratio=1.40 aq=1:1.00"
D/IJKMEDIA(21118): nal_unit_type: 7, nal_ref_idc: 3
D/IJKMEDIA(21118): nal_unit_type: 8, nal_ref_idc: 3
D/IJKMEDIA(21118): nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA(21118): nal_unit_type: 5, nal_ref_idc: 3
D/IJKMEDIA(21118): user data:"x264 - core 125 - H.264/MPEG-4 AVC codec - Copyleft 2003-2012 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x1:0x131 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=2 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=2 b_pyramid=2 b_adapt=0 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=12 keyint_min=7 scenecut=40 intra_refresh=0 rc_lookahead=12 rc=abr mbtree=1 bitrate=1000 ratetol=1.0 qcomp=0.60 qpmin=6 qpmax=51 qpstep=4 ip_ratio=1.40 aq=1:1.00"
I/IJKMEDIA(21118): Reinit context to 1920x1088, pix_fmt: yuv420p
D/IJKMEDIA(21118): no picture 
D/IJKMEDIA(21118): IjkMediaPlayer_native_finalize
D/IJKMEDIA(21118): IjkMediaPlayer_release
D/dalvikvm(21118): GC_FOR_ALLOC freed 1099K, 19% free 11264K/13744K, paused 123ms, total 126ms
D/IJKMEDIA(21118): skip whole frame, skip left: 0
D/IJKMEDIA(21118): All info found
D/IJKMEDIA(21118): After avformat_find_stream_info() pos: 271689 bytes read:294912 seeks:0 frames:108
D/IJKMEDIA(21118): FFP_MSG_FIND_STREAM_INFO:
I/IJKMEDIA(21118): max_frame_duration: 10.000
I/IJKMEDIA(21118): Input #0, flv, from '/storage/usb0/amediaBig/信念.flv':
I/IJKMEDIA(21118):   Metadata:
I/IJKMEDIA(21118):     encoder         : 
I/IJKMEDIA(21118): Lavf54.6.100
I/IJKMEDIA(21118): 
I/IJKMEDIA(21118):   Duration: 
I/IJKMEDIA(21118): 00:03:12.92
I/IJKMEDIA(21118): , start: 
I/IJKMEDIA(21118): 0.080000
I/IJKMEDIA(21118): , bitrate: 
I/IJKMEDIA(21118): 1152 kb/s
I/IJKMEDIA(21118): 
I/IJKMEDIA(21118):     Stream #0:0
D/IJKMEDIA(21118): , 41, 1/1000
I/IJKMEDIA(21118): : Video: h264, 1 reference frame, yuv420p(progressive, left), 1920x1080 (1920x1088) [SAR 1:1 DAR 16:9], 0/1, 1000 kb/s
I/IJKMEDIA(21118): , 
I/IJKMEDIA(21118): 25 fps, 
I/IJKMEDIA(21118): 25 tbr, 
I/IJKMEDIA(21118): 1k tbn, 
I/IJKMEDIA(21118): 50 tbc
I/IJKMEDIA(21118): 
I/IJKMEDIA(21118):     Stream #0:1
D/IJKMEDIA(21118): , 67, 1/1000
I/IJKMEDIA(21118): : Audio: aac, 44100 Hz, stereo, fltp, 128 kb/s
I/IJKMEDIA(21118): 
I/IJKMEDIA(21118): SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
I/IJKMEDIA(21118): SDL_Android_AudioTrack: ENCODING_PCM_16BIT
V/AudioPolicyService( 1181): getOutput()
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
V/AudioPolicyService( 1181): getOutput()
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
V/AudioPolicyService( 1181): getOutput()
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
V/AudioPolicyService( 1181): getOutput()
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
V/AudioPolicyService( 1181): getOutput()
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
V/AudioPolicyService( 1181): getOutput()
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
D/AudioFlinger( 1181): AudioFlinger_ThreadBase_TrackBase_TrackBase ---> mCblkMemory allocate(size = 32832)
I/IJKMEDIA(21118): SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(0.000000,1.000000)
I/IJKMEDIA(21118): audio_session_id = 534
I/IJKMEDIA(21118): AudioCodec: avcodec, aac
I/IJKMEDIA(21118): SDL_RunThread: [486] ff_aout_android
I/IJKMEDIA(21118): SDL_RunThread: [487] ff_audio_dec
V/AudioPolicyService( 1181): startOutput()
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 1, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 2, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 3, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 4, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 5, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForVolume 2
D/AudioPolicyManagerBase( 1181): getDeviceForVolume 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() from cache strategy 3, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 3, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 1, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 2, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 3, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 4, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 0, device 2
D/AudioPolicyManagerBase( 1181): getDeviceForStrategy() strategy 5, device 2
D/IJKMEDIA(21118): nal_unit_type: 7, nal_ref_idc: 3
D/IJKMEDIA(21118): nal_unit_type: 8, nal_ref_idc: 3
I/IJKMEDIA(21118): VideoCodec: avcodec, h264
W/IJKMEDIA(21118): fps: 25.000000 (normal)
W/IJKMEDIA(21118): fps: 25.000000 (normal)
D/IJKMEDIA(21118): FFP_MSG_COMPONENT_OPEN:
D/IJKMEDIA(21118): FFP_MSG_VIDEO_SIZE_CHANGED: 1920, 1080
I/IJKMEDIA(21118): SDL_RunThread: [492] ff_video_dec
D/IJKMEDIA(21118): FFP_MSG_SAR_CHANGED: 1, 1
D/IJKMEDIA(21118): ijkmp_get_msg: FFP_MSG_PREPARED
D/IJKMEDIA(21118): FFP_MSG_PREPARED:
D/IJKMEDIA(21118): FFP_MSG_VIDEO_ROTATION_CHANGED: 0
V/android.view/ViewRootImpl(21118): handleMessage 5
V/android.view/ViewRootImpl(21118): handleMessage 6
I/ActivityManager( 1600): Displayed example.media.ijk.danmaku.tlh.tlhplayer/com.action.amp.ampplyer.activities.VideoActivity: +456ms
D/IjkVideoView(21118): MEDIA_INFO_VIDEO_ROTATION_CHANGED: 0
E/        (21118): SurfaceView doesn't support rotation (0)!
D/IJKMEDIA(21118): IjkMediaPlayer_start
D/IJKMEDIA(21118): ijkmp_start()
D/IJKMEDIA(21118): ijkmp_get_msg: FFP_REQ_START
D/IJKMEDIA(21118): ijkmp_get_msg: FFP_REQ_START: start on fly
D/IJKMEDIA(21118): ijkmp_start()=0
D/IJKMEDIA(21118): ijkmp_get_msg: FFP_REQ_START
D/IJKMEDIA(21118): ijkmp_get_msg: FFP_REQ_START: start on fly
D/IJKMEDIA(21118): nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA(21118): skip whole frame, skip left: 0
D/IJKMEDIA(21118): nal_unit_type: 5, nal_ref_idc: 3
D/IJKMEDIA(21118): user data:"x264 - core 125 - H.264/MPEG-4 AVC codec - Copyleft 2003-2012 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x1:0x131 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=2 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=2 b_pyramid=2 b_adapt=0 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=12 keyint_min=7 scenecut=40 intra_refresh=0 rc_lookahead=12 rc=abr mbtree=1 bitrate=1000 ratetol=1.0 qcomp=0.60 qpmin=6 qpmax=51 qpstep=4 ip_ratio=1.40 aq=1:1.00"
I/IJKMEDIA(21118): Reinit context to 1920x1088, pix_fmt: yuv420p
D/IJKMEDIA(21118): Using fltp internally between filters
D/IJKMEDIA(21118): avcodec/Audio: first frame decoded
D/IJKMEDIA(21118): FFP_MSG_AUDIO_DECODED_START:
D/IJKMEDIA(21118): FFP_MSG_AUDIO_RENDERING_START:
D/IJKMEDIA(21118): no picture 
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 2
V/android.view/ViewRootImpl(21118): handleMessage 13
V/android.view/ViewRootImpl(21118): handleMessage 8
D/IjkVideoView(21118): MEDIA_INFO_AUDIO_RENDERING_START:
D/IJKMEDIA(21118): no picture 
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 2
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 2
D/IJKMEDIA(21118): SDL_VoutFFmpeg_CreateOverlay(w=1920, h=1080, fmt=RV32(0x32335652, dp=0x65736950)
D/IJKMEDIA(21118): FFP_MSG_VIDEO_SIZE_CHANGED: 1920, 1080
W/SurfaceFlinger( 1178): couldn't log to binary event log: overflow.
D/IJKMEDIA(21118): Video: first frame decoded
D/IJKMEDIA(21118): FFP_MSG_VIDEO_DECODED_START:
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 2
D/IJKMEDIA(21118): ANativeWindow_setBuffersGeometry: w=1920, h=1080, f=(0x4) => w=1920, h=1080, f=RV32(0x32335652)
D/IJKMEDIA(21118): FFP_MSG_VIDEO_SIZE_CHANGED: 1920, 1080
D/IJKMEDIA(21118): SDL_VoutFFmpeg_CreateOverlay(w=1920, h=1080, fmt=RV32(0x32335652, dp=0x65736950)
D/IJKMEDIA(21118): FFP_MSG_VIDEO_RENDERING_START:
V/android.view/ViewRootImpl(21118): handleMessage 22
V/android.view/ViewRootImpl(21118): handleMessage 22
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(21118): Info: MEDIA_INFO_VIDEO_RENDERING_START
D/IjkVideoView(21118): MEDIA_INFO_VIDEO_RENDERING_START:
D/IJKMEDIA(21118): SDL_VoutFFmpeg_CreateOverlay(w=1920, h=1080, fmt=RV32(0x32335652, dp=0x65736950)
D/IJKMEDIA(21118): FFP_MSG_VIDEO_SIZE_CHANGED: 1920, 1080
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 2
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 2
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 2
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA(21118): nal_unit_type: 5, nal_ref_idc: 3
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 2
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 2
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 2
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 2
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 2
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 2
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 2
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA(21118): nal_unit_type: 5, nal_ref_idc: 3
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 2
D/IJKMEDIA(21118): nal_unit_type: 1, nal_ref_idc: 2

**Comment by raymond1012** [comment]
setoption mediacodec is 1

**Comment by TianLuhua** [comment]
意思就是又回到了硬解码咯！非常感谢！！！
