### ISSUE TITLE
播放音乐时pause后再seek时有一点声音

### ISSUE THREAD

**Issue by lovelycheep** [Bilibili/ijkplayer#3698]
你好，最近发现一个问题：
播放音乐时pause后再seek时有一点余音；

我尝试过以下方式都没起作用：
1、把audio_buf重置；
2、调用frame_queue_flush清空sampq；
3、调用SDL_Android_AudioTrack_flush；
4、查看重采样swr_get_delay的output、input都没有缓冲samples；

请问能否帮忙分析一下这个问题，万分感谢

**Comment by raymond1012** [comment]
fix this issue in next version

**Comment by lovelycheep** [comment]
thank you very much！
