### ISSUE TITLE
I just compiled the libijkffmpeg.so

### ISSUE THREAD

**Issue by wangyuehong1982** [Bilibili/ijkplayer#370]
Hi, I want the .so libraries for Android, and use the MAC to finish, but I just compiled libijkffmpeg.so, this is my codes in bash:
1.
cd config
rm module.sh
ln -s module-lite.sh module.sh
cd android/contrib
2.
./compile-ffmpeg.sh clean
3.
./compile-ffmpeg.sh (when I run the code, the log prints many warnings)
4.
./compile-ijk.sh
 (the log prints profiler build: NO
[armeabi-v7a] Prebuilt : libijkffmpeg.so <= /Users/NiKOo/Desktop/projects/ijkplayer-master/android/contrib/build/ffmpeg-armv7a/output/
[armeabi-v7a] Install : libijkffmpeg.so => libs/armeabi-v7a/libijkffmpeg.so
/Users/NiKOo/desktop/projects/ijkplayer-master/android)
the size of the libijkffmpeg.so is 13.7MB
I don`t find other libraries, why? Who can answer me, thanks!

**Comment by bbcallen** [comment]
Can't reproduce.

**Comment by wangyuehong1982** [comment]
but why can`t reproduce?

**Comment by bbcallen** [comment]
I wonder, too.

**Comment by Android4MediaPlayer** [comment]
The compiler was failed,please try to do the following steps:
cd android/ijkplayer/player-armv7a/src/main/jni/
ln -s ../../../../../../ijkmedia ijkmedia

**Comment by Android4MediaPlayer** [comment]
The compiler was failed,please try to do the following steps:
cd android/ijkplayer/player-armv7a/src/main/jni/
rm ijkmedia
ln -s ../../../../../../ijkmedia ijkmedia

**Comment by wangyuehong1982** [comment]
the problem is ok, thanks

**Comment by mrldc** [comment]
I follow steps:  relink  ijkmedia.
but it still compile failed.
The log is ::
profiler build: NO
[armeabi-v7a] Prebuilt       : libijkffmpeg.so <= /cygdrive/d/ijkplayer-master/a
ndroid/contrib/build/ffmpeg-armv7a/output/
[armeabi-v7a] Install        : libijkffmpeg.so => libs/armeabi-v7a/libijkffmpeg.
so
[armeabi-v7a] Cygwin         : Generating dependency file converter script
[armeabi-v7a] Compile thumb  : ijkplayer <= ff_cmdutils.c
arm-linux-androideabi-gcc.exe: error: D:/ijkplayer-master/android/ijkplayer/play
er-armv7a/src/main/jni/ijkmedia/ijkplayer/ff_cmdutils.c: No such file or directo
ry
arm-linux-androideabi-gcc.exe: fatal error: no input files
compilation terminated.
make: *** [/cygdrive/d/ijkplayer-master/android/ijkplayer/player-armv7a/src/main
/obj/local/armeabi-v7a/objs/ijkplayer/ff_cmdutils.o] Error 1
/cygdrive/d/ijkplayer-master/android
profiler build: NO
[armeabi-v7a] Install        : libijkffmpeg.so => libs/armeabi-v7a/libijkffmpeg.
so
[armeabi-v7a] Compile thumb  : ijkplayer <= ff_cmdutils.c
arm-linux-androideabi-gcc.exe: error: D:/ijkplayer-master/android/ijkplayer/play
er-armv7a/src/main/jni/ijkmedia/ijkplayer/ff_cmdutils.c: No such file or directo
ry
arm-linux-androideabi-gcc.exe: fatal error: no input files
compilation terminated.
make: *** [/cygdrive/d/ijkplayer-master/android/ijkplayer/player-armv7a/src/main
/obj/local/armeabi-v7a/objs/ijkplayer/ff_cmdutils.o] Error 1
/cygdrive/d/ijkplayer-master/android
profiler build: NO
/cygdrive/d/ijkplayer-master/android/ijkplayer/player-x86/src/main/jni/Android.m
k:1: *** missing separator.  Stop.
/cygdrive/d/ijkplayer-master/android

@Android4MediaPlayer can you help me to solve this problem?thanks!
