### ISSUE TITLE
Android  Api最低版本21？，

### ISSUE THREAD

**Issue by nances** [Bilibili/ijkplayer#3704]
![wechatimg8180](https://user-images.githubusercontent.com/6659276/32095979-a171d5c6-baca-11e7-8292-11aac42913a8.jpeg)

**Comment by raymond1012** [comment]
是x86要求

**Comment by nances** [comment]
@raymond1012 您好，我看最新版本的，红米Note手机会出现音频不同步的问题，我项目中以前的So文件不知道是哪个版本的，不会出现这个问题！请问知道是什么原因吗？

**Comment by o03150** [comment]
@raymond1012 不止x86要求吧,除了armv7a,其他基本都要求21
