### ISSUE TITLE
ios ijkplayer切到后台更换4G后回来重新创建后tcp-speed 很低卡死

### ISSUE THREAD

**Issue by yecoco** [Bilibili/ijkplayer#3705]
对于ijkplayer切到后台时，我会移除并释放播放器，然后在进前台时重新创建。这样子在不切换网络时一切ok，但是当切到后台去设置里改变网络时，比如切换成4g再回到前台时播放器就很卡，并且tcp-speed显示很低，退出播放界面重进也一样，只能杀死程序后重新打开才变正常，请问这是为什么呢，是不是某个关键位置没释放掉？

**Comment by yecoco** [comment]
今天试了下用以前编译的sdk就没出现这种问题，用最新打包的sdk就出现这种问题了。。 。

**Comment by Chauvetok** [comment]
楼主现在解决了吗？我也是切换网络到4G时视频很卡耶。。。

**Comment by TomBin647** [comment]
兄弟 有解决办法么 ? 切换的时候卡死了
