### ISSUE TITLE
ijk 0.8.4版本设置 setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "soundtouch", 0); 还是出现变调问题

### ISSUE THREAD

**Issue by ltpostbox** [Bilibili/ijkplayer#3708]
ijkMediaPlayer.setDataSource(this, Uri.parse(videoUrl)); 
ijkMediaPlayer.prepareAsync();
 ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "soundtouch", 0); 

 ijkplayer-java:0.8.4 版本 还是变调声音 在华为5.1系统上运行的效果 跪求解决思路

**Comment by raymond1012** [comment]
ijkMediaPlayer.setDataSource(this, Uri.parse(videoUrl));
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "soundtouch", 1);
ijkMediaPlayer.prepareAsync();

**Comment by ltpostbox** [comment]
@raymond1012  非常感谢大神 ！
