### ISSUE TITLE
How to auto play next one with RTMP video？

### ISSUE THREAD

**Issue by mars-rover** [Bilibili/ijkplayer#371]
I want to know how to auto play next RTMP video, but I failed, could you show me some tips?

**Comment by bbcallen** [comment]
What is "next RTMP"?

**Comment by mars-rover** [comment]
RTMP is the "Real Time Messaging Protocol", I need to let my app auto play next RTMP Video when The Current RTMP video end up.

**Comment by bbcallen** [comment]
Create a new player with new URL, when OnComplete event happen.

**Comment by mars-rover** [comment]
It works, Thank you very much!

**Comment by maliujie** [comment]
How to auto next MP3 in background
