### ISSUE TITLE
vtb fail!!! switch to ffmpeg decode!!!!

### ISSUE THREAD

**Issue by mars-rover** [Bilibili/ijkplayer#372]
The following is the log, why do I failed hardware decode?

ijkmp_set_format_callback(0x10354d, 0x15ee4140)
ijkmp_set_format_callback()=void
ijkmp_set_option_int(start-on-prepared, 1)
ijkmp_set_option_int()=void
2015-07-30 23:14:23.446 FFmpeg[1307:44833] OK setup GL
ijkmp_ios_set_view(glView=0x15ed1720)
ijkmp_ios_set_view(glView=0x15ed1720)=void
ijkmp_set_option(overlay-format, fcc-i420)
ijkmp_set_option()=void
ijkmp_set_option_int(framedrop, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(max-fps, 30)
ijkmp_set_option_int()=void
ijkmp_set_option_int(video-pictq-size, 3)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox-max-frame-width, 960)
ijkmp_set_option_int()=void
ijkmp_set_option(user-agent, ijkplayer)
ijkmp_set_option()=void
ijkmp_set_option_int(reconnect, 1)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_loop_filter, 48)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_frame, 8)
ijkmp_set_option_int()=void
ijkmp_set_data_source(url="rtmp://222.73.60.16/live/3659787?userId=&roomId=3659787")
ijkmp_set_data_source(url="rtmp://222.73.60.16/live/3659787?userId=&roomId=3659787")=0
ijkmp_set_option(safe, 0)
ijkmp_set_option()=void
ijkmp_prepare_async()
===== options =====
player-opts : start-on-prepared            = 1
player-opts : overlay-format               = fcc-i420
player-opts : framedrop                    = 0
player-opts : max-fps                      = 30
player-opts : video-pictq-size             = 3
player-opts : videotoolbox-max-frame-width = 960
format-opts : user-agent                   = ijkplayer
format-opts : reconnect                    = 1
format-opts : safe                         = 0
codec-opts  : skip_loop_filter             = 48
codec-opts  : skip_frame                   = 8
===================
ijkmp_prepare_async()=0
ijkmp_start()
ijkmp_start()=-3
remove 'timeout' option for rtmp.
Handshaking...
Type answer 3
Server version 0.0.0.0
Proto = rtmp, path = /live/3659787?userId=&roomId=3659787, app = live, fname = 3659787?userId=&roomId=3659787
Server bandwidth = 2500000
Client bandwidth = 2500000
Creating stream...
Sending play command for '3659787?userId=&roomId=3659787'
Server error: call to function _checkbw failed
Format flv probed with size=2048 and score=100
Option user-agent not found.
Before avformat_find_stream_info() pos: 13 bytes read:17386 seeks:0
Unknown type |RtmpSampleAccess
AVC: Consumed only 1 bytes instead of 16913
AVC: Consumed only 1 bytes instead of 1466
AVC: Consumed only 1 bytes instead of 1942
AVC: Consumed only 1 bytes instead of 1715
AVC: Consumed only 1 bytes instead of 1718
AVC: Consumed only 1 bytes instead of 1499
AVC: Consumed only 1 bytes instead of 1962
missing picture in access unit with size 308
Stream discovered after head already parsed
All info found
rfps: 9.833333 0.014140
rfps: 9.833333 0.014140
rfps: 9.916667 0.002069
rfps: 9.916667 0.002069
rfps: 10.000000 0.008772
rfps: 19.833333 0.008278
rfps: 19.833333 0.008278
rfps: 19.916667 0.012297
rfps: 29.750000 0.018625
rfps: 29.833333 0.019960
After avformat_find_stream_info() pos: 93454 bytes read:93454 seeks:0 frames:63
max_frame_duration: 3600.000
Input #0, flv, from 'rtmp://222.73.60.16/live/3659787?userId=&roomId=3659787':
  Metadata:
    Server          : C++ RTMP Media Server (www.rtmpd.com)
    audiochannels   : 2
    audioinputvolume: 46
    avclevel        : 21
    avcprofile      : 100
    bandwidth       : 0
    copyright       : 
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0, 41, 1/1000: Video: h264, 5 reference frames, yuv420p(left), 480x360 (480x368), 1/50, 25 fps, 9.92 tbr, 1k tbn, 50 tbc
    Stream #0:1, 22, 1/1000: Audio: mp3, 32000 Hz, stereo, s16p, 80 kb/s
aout_open_audio()
AudioCodec: avcodec, mp3
aout_pause_audio(0)
detected 2 logical cores
vtb fail!!! switch to ffmpeg decode!!!! 
VideoCodec: avcodec, h264
fps: 25.000000 (normal)
fps: 9.916667 (normal)
ijkmp_get_msg: FFP_MSG_PREPARED
2015-07-30 23:14:24.689 FFmpeg[1307:44833] FFP_MSG_VIDEO_DECODER_OPEN: false
2015-07-30 23:14:24.690 FFmpeg[1307:44833] FFP_MSG_PREPARED:
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
2015-07-30 23:14:24.692 FFmpeg[1307:44833] fps in meta 25.000000
2015-07-30 23:14:24.693 FFmpeg[1307:44833] mediaIsPreparedToPlayDidChange
2015-07-30 23:14:24.694 FFmpeg[1307:44833] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3
2015-07-30 23:14:24.695 FFmpeg[1307:44833] FFP_MSG_VIDEO_SIZE_CHANGED: 480, 360
2015-07-30 23:14:24.696 FFmpeg[1307:44833] FFP_MSG_SAR_CHANGED: 0, 1
AVC: Consumed only 1 bytes instead of 16913
2015-07-30 23:14:24.697 FFmpeg[1307:44833] moviePlayBackStateDidChange 1: playing
AVC: Consumed only 1 bytes instead of 1466
AVC: Consumed only 1 bytes instead of 1942
SDL_VoutFFmpeg_CreateOverlay(w=480, h=360, fmt=I420(0x30323449, dp=0x15d0ef30)
2015-07-30 23:14:24.745 FFmpeg[1307:44833] FFP_MSG_VIDEO_SIZE_CHANGED: 480, 360
2015-07-30 23:14:24.753 FFmpeg[1307:44933] OK use I420 GL renderer
2015-07-30 23:14:24.753 FFmpeg[1307:44833] FFP_MSG_VIDEO_SIZE_CHANGED: 480, 360
AVC: Consumed only 1 bytes instead of 1715
2015-07-30 23:14:24.766 FFmpeg[1307:44933] OK setup GL programm
2015-07-30 23:14:24.779 FFmpeg[1307:44933] OK setup GL framebuffer 640:560
SDL_VoutFFmpeg_CreateOverlay(w=480, h=360, fmt=I420(0x30323449, dp=0x15d0ef30)
SDL_VoutFFmpeg_CreateOverlay(w=480, h=360, fmt=I420(0x30323449, dp=0x15d0ef30)
2015-07-30 23:14:24.803 FFmpeg[1307:44833] FFP_MSG_VIDEO_SIZE_CHANGED: 480, 360
AVC: Consumed only 1 bytes instead of 1718
AVC: Consumed only 1 bytes instead of 1499
AVC: Consumed only 1 bytes instead of 1962
AVC: Consumed only 1 bytes instead of 1500
AVC: Consumed only 1 bytes instead of 1448
AVC: Consumed only 1 bytes instead of 1057
AVC: Consumed only 1 bytes instead of 1255
AVC: Consumed only 1 bytes instead of 1743
AVC: Consumed only 1 bytes instead of 1515

**Comment by bbcallen** [comment]
You didn't enable it.
VTB is disabled by default.

**Comment by mars-rover** [comment]
how to enable it?

**Comment by mars-rover** [comment]
Does it project support the videoToolBox for RTMP? I got some ERR when I set the ffp->video toolbox = 1;
ijkmp_set_format_callback(0x25130, 0xbf262f0)
ijkmp_set_format_callback()=void
ijkmp_set_option_int(start-on-prepared, 1)
ijkmp_set_option_int()=void
2015-07-31 12:25:00.620 FFmpeg[5700:88133] OK setup GL
ijkmp_ios_set_view(glView=0xbf34330)
ijkmp_ios_set_view(glView=0xbf34330)=void
ijkmp_set_option(overlay-format, fcc-i420)
ijkmp_set_option()=void
ijkmp_set_option_int(framedrop, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(max-fps, 30)
ijkmp_set_option_int()=void
ijkmp_set_option_int(video-pictq-size, 3)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox-max-frame-width, 960)
ijkmp_set_option_int()=void
ijkmp_set_option(user-agent, ijkplayer)
ijkmp_set_option()=void
ijkmp_set_option_int(reconnect, 1)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_loop_filter, 48)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_frame, 8)
ijkmp_set_option_int()=void
ijkmp_set_data_source(url="rtmp://222.73.33.117/live/3659787?userId=&roomId=3659787")
ijkmp_set_data_source(url="rtmp://222.73.33.117/live/3659787?userId=&roomId=3659787")=0
ijkmp_set_option(safe, 0)
ijkmp_set_option()=void
ijkmp_prepare_async()
===== options =====
player-opts : start-on-prepared            = 1
player-opts : overlay-format               = fcc-i420
player-opts : framedrop                    = 0
player-opts : max-fps                      = 30
player-opts : video-pictq-size             = 3
player-opts : videotoolbox-max-frame-width = 960
format-opts : user-agent                   = ijkplayer
format-opts : reconnect                    = 1
format-opts : safe                         = 0
codec-opts  : skip_loop_filter             = 48
codec-opts  : skip_frame                   = 8
===================
ijkmp_prepare_async()=0
remove 'timeout' option for rtmp.
ijkmp_start()
ijkmp_start()=-3
Handshaking...
Type answer 3
Server version 0.0.0.0
Proto = rtmp, path = /live/3659787?userId=&roomId=3659787, app = live, fname = 3659787?userId=&roomId=3659787
Server bandwidth = 2500000
Client bandwidth = 2500000
Creating stream...
Sending play command for '3659787?userId=&roomId=3659787'
Server error: call to function _checkbw failed
Format flv probed with size=2048 and score=100
Option user-agent not found.
Before avformat_find_stream_info() pos: 13 bytes read:14422 seeks:0
Unknown type |RtmpSampleAccess
AVC: Consumed only 1 bytes instead of 13949
AVC: Consumed only 1 bytes instead of 1281
AVC: Consumed only 1 bytes instead of 608
AVC: Consumed only 1 bytes instead of 1405
AVC: Consumed only 1 bytes instead of 882
AVC: Consumed only 1 bytes instead of 1297
AVC: Consumed only 1 bytes instead of 1345
Stream discovered after head already parsed
All info found
rfps: 15.416667 0.018168
rfps: 15.416667 0.018168
rfps: 15.500000 0.005382
rfps: 15.500000 0.005382
rfps: 15.583333 0.000201
rfps: 15.666667 0.002627
rfps: 15.666667 0.002627
rfps: 15.750000 0.012659
rfps: 15.750000 0.012659
After avformat_find_stream_info() pos: 83568 bytes read:83568 seeks:0 frames:58
max_frame_duration: 3600.000
Input #0, flv, from 'rtmp://222.73.33.117/live/3659787?userId=&roomId=3659787':
  Metadata:
    Server          : C++ RTMP Media Server (www.rtmpd.com)
    audiochannels   : 2
    audioinputvolume: 46
    avclevel        : 21
    avcprofile      : 100
    bandwidth       : 0
    copyright       : 
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0, 41, 1/1000: Video: h264 (High), 5 reference frames, yuv420p(left), 480x360 (480x368), 1/50, 25 fps, 15.58 tbr, 1k tbn, 50 tbc
    Stream #0:1, 17, 1/1000: Audio: mp3, 32000 Hz, stereo, s16p, 80 kb/s
aout_open_audio()
AudioCodec: avcodec, mp3
aout_pause_audio(0)
detected 4 logical cores
init_videotoolbox - using avcC atom of size(41), ref_frames(5)after scale width 480 height 360 
m_max_ref_frames 5 
fps: 25.000000 (normal)
fps: 15.583333 (normal)
flushed last keyframe pts 0 
ijkmp_get_msg: FFP_MSG_PREPARED
after scale width 480 height 360 
missing picture in access unit with size 487
2015-07-31 12:26:18.057 FFmpeg[5700:88133] FFP_MSG_VIDEO_DECODER_OPEN: true
2015-07-31 12:26:18.057 FFmpeg[5700:88133] FFP_MSG_PREPARED:
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
2015-07-31 12:26:18.057 FFmpeg[5700:88133] fps in meta 25.000000
2015-07-31 12:26:18.057 FFmpeg[5700:88133] mediaIsPreparedToPlayDidChange
2015-07-31 12:26:18.057 FFmpeg[5700:88133] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3
2015-07-31 12:26:18.057 FFmpeg[5700:88133] FFP_MSG_VIDEO_SIZE_CHANGED: 480, 360
2015-07-31 12:26:18.058 FFmpeg[5700:88133] FFP_MSG_SAR_CHANGED: 0, 1
2015-07-31 12:26:18.058 FFmpeg[5700:88133] moviePlayBackStateDidChange 1: playing
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
av_read_frame error: fffffffb(\377,\377,\377,\373): unknown
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
decode callback -12349 UNKNOWN
decodeFrame -12349 UNKNOWN
aout_pause_audio(1)
ffp_toggle_buffering: error: -5
av_read_frame error: fffffffb(\377,\377,\377,\373): unknown
2015-07-31 12:26:30.580 FFmpeg[5700:88133] FFP_MSG_ERROR: 0
2015-07-31 12:26:30.580 FFmpeg[5700:88133] moviePlayBackStateDidChange 1: playing
ffp_toggle_buffering: eof
2015-07-31 12:26:33.886 FFmpeg[5700:88133] playbackStateDidChange: MPMovieFinishReasonPlaybackError:

**Comment by mars-rover** [comment]
Could you tell me how to enable VTB? I am really worry about it!! Thanks a lot!!

**Comment by bbcallen** [comment]
It's enabled, but I think there are something wrong in the stream.

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
