### ISSUE TITLE
FFMPEG DSD音频支持问题

### ISSUE THREAD

**Issue by xksds** [Bilibili/ijkplayer#3721]
Hi ALL

FFMPEG已经内置了DSD的各种格式解码器，但是有些samplerate特别大的音频，会在开始解析时出现失败。事实解码器是支持的。
跟下代码发现在audio_open时，因为Uint取值问题，导致wanted_spec.samples为零。
改了下代码，可以正常播放。

# 更改文件：
ijkmedia/ijkplayer/ff_ffplay.c ，函数：static int audio_open

#ifdef __TEST__
    int max = FFMAX(SDL_AUDIO_MIN_BUFFER_SIZE, 2 << av_log2(wanted_spec.freq / SDL_AoutGetAudioPerSecondCallBacks(ffp->aout)));
    wanted_spec.samples = max > 32768 ? 32768 : max;
#else
    wanted_spec.samples = FFMAX(SDL_AUDIO_MIN_BUFFER_SIZE, 2 << av_log2(wanted_spec.freq / SDL_AoutGetAudioPerSecondCallBacks(ffp->aout)));
#endif

# 或者更改ijksdl

文件：ijkmedia/ijksdl/ijksdl_audio.c，函数：void SDL_CalculateAudioSpec
#ifdef __TEST__
    if(0 == spec->samples)
        spec->samples = 32768;
    spec->size *= spec->samples;
#else
    spec->size *= spec->samples;
#endif

# 更好的办法
更改wanted_spec.samples 的类型，使其兼容更大的数值。

**Comment by raymond1012** [comment]
need sample

**Comment by xksds** [comment]
http://www.2l.no/hires/

![image](https://user-images.githubusercontent.com/6055000/32363834-434e7e62-c0ac-11e7-86ff-72c92d925c3f.png)
