### ISSUE TITLE
同时 在一个设备中new 多个IjkMediaPlayer，会卡么？

### ISSUE THREAD

**Issue by harlanc** [Bilibili/ijkplayer#3722]
需要做全景播放。比如需要在后台new出来40个 IjkMediaPlayer,39个在后台播放，1个在前台显示，对手机内存，CPU的要求是多少？会卡么？有没有相关的测试数据呢？

**Comment by raymond1012** [comment]
我们没有相关需求，也没有相关数据，如果你们测试出来，请发一份给我们
