### ISSUE TITLE
每次切换播放视频可以重用(不释放)旧的播放器资源么？

### ISSUE THREAD

**Issue by harlanc** [Bilibili/ijkplayer#3724]
看ijkplayer的例子也是这么写的，每次重新打开视频都得重新new一个ijkMediaPlayer.重新设置一次。我的问题是，可不可以只重新setDataSource和prepareSync一次就可以了呢？其它的不变。每次重新new ijkplayer有什么作用么？

**Comment by HaloMego** [comment]
**我是这样处理的**
---
~~~
public void switchVideoResource(String url){
	if (mMediaPlayer!=null){
		mMediaPlayer.reset();
		setRender(2);
		mMediaPlayer.setDataSource(url);
		mMediaPlayer.prepareAsync();
	}
}
~~~

**Comment by HaloMego** [comment]
**anyone else has a better idea?**

**Comment by harlanc** [comment]
@HaloMego 谢谢，测试通过了么？

**Comment by HaloMego** [comment]
正处于自研阶段，还没测试。

**Comment by NotLooker** [comment]
可以的，
我这边使用的是videoview ，还url重新播放的话,
public void switchVideoResource(String url){
	if (mVideoView!=null){
	        mVideoView.toggleRender();
		mVideoView.setVideoPath(url);
	}
}

**Comment by harlanc** [comment]
@HaloMego 我也尝试了你的方法，不过执行一次reset，相当于release之后在创建，好多options貌似是应该重新set一遍。

**Comment by HaloMego** [comment]
虽然Listeners没有被release，但是options应该重新设置。

**Comment by harlanc** [comment]
@HaloMego 我们做了简单的测试，功能上没有问题。

**Comment by houtengzhi** [comment]
@HaloMego 我用的是k0.8.8版本，reset之后再重新setDataSource，有声音，但是画面还是停留在上一个源的最后一帧

**Comment by HaloMego** [comment]
@houtengzhi 抱歉，我没遇到过这种问题，我建议你debug 一下。或者去qq 群里问下。

**Comment by lakeinchina** [comment]
@houtengzhi  只有声音不出画面的原因是你要重新设置一下surface

**Comment by houtengzhi** [comment]
@lakeinchina 是这样的，问题已经解决
