### ISSUE TITLE
android 设置2倍播放速度后,声调变了

### ISSUE THREAD

**Issue by Greathfs** [Bilibili/ijkplayer#3738]
mPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "soundtouch", 0);
        mPlayer.setSpeed(2.0f);

**Comment by raymond1012** [comment]
mPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "soundtouch", 1);


2017-11-08 15:49 GMT+08:00 HuangFuSheng <notifications@github.com>:

**Comment by Greathfs** [comment]
thx
