### ISSUE TITLE
Root cause of 'green screen'

### ISSUE THREAD

**Issue by hhbgk** [Bilibili/ijkplayer#3743]
Hi guys, I have an issue with my player. It will "green screen"（Not mosaic） once playing but without any errors(log). I have no idea with this, anyone know what is the root cause of this?
And my IJK params:
I/IJKMEDIA: av_version_info: ff3.2--ijk0.7.6--20170324--001
I/IJKMEDIA: ijk_version_info: k0.7.9
I/IJKMEDIA: ===== versions =====
I/IJKMEDIA: ijkplayer    : k0.7.9
I/IJKMEDIA: FFmpeg       : ff3.2--ijk0.7.6--20170324--001
I/IJKMEDIA: libavutil    : 55.34.100
I/IJKMEDIA: libavcodec   : 57.64.100
I/IJKMEDIA: SDL_RunThread: [18638] ff_msg_loop
I/IJKMEDIA: libavformat  : 57.56.100
I/IJKMEDIA: libswscale   : 4.2.100
I/IJKMEDIA: libswresample: 2.3.100
I/IJKMEDIA: ===== options =====
I/IJKMEDIA: player-opts : mediacodec                   = 0
I/IJKMEDIA: player-opts : opensles                     = 0
I/IJKMEDIA: player-opts : overlay-format               = 842225234
I/IJKMEDIA: player-opts : min-frames                   = 150
I/IJKMEDIA: player-opts : max-buffer-size              = 2097152
I/IJKMEDIA: player-opts : packet-buffering             = 0
I/IJKMEDIA: player-opts : framedrop                    = 1
I/IJKMEDIA: player-opts : start-on-prepared            = 0
I/IJKMEDIA: player-opts : infbuf                       = 1
I/IJKMEDIA: format-opts : ijkapplication               = 367373315920
I/IJKMEDIA: format-opts : ijkiomanager                 = 367386400592
I/IJKMEDIA: format-opts : http-detect-range-support    = 0
I/IJKMEDIA: format-opts : probesize                    = 1048576
I/IJKMEDIA: format-opts : analyzeduration              = 5000
I/IJKMEDIA: codec-opts  : skip_frame                   = 16
I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
I/IJKMEDIA: ===================
I/IJKMEDIA: SDL_RunThread: [18639] ff_vout
I/IJKMEDIA: SDL_RunThread: [18640] ff_read

**Comment by yuazhen** [comment]
Because you are using avcodec, I guess the overlay-format in your example may be a YUV format and the surface of the all-zero data will be displayed as a "green screen" when processed in the YUV format.
You can try use RGB formats such as RGB565 or RGBA8888, etc.

**Comment by hhbgk** [comment]
@yuazhen thanks for your reply ! You are right, in my example, I use the config which is IJK example using. Some codes like:
`ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "overlay-format", IjkMediaPlayer.SDL_FCC_RV32);`
SO, how to use RGB formats in IJK examle ? Do I have to overwrite it myself?

**Comment by hhbgk** [comment]
OK, I got it. But that problem still there after I changed  "overlay-format" to RGB. Some things I have to say is, it will be more better if using hard codec.
