### ISSUE TITLE
播放多码率的视频源

### ISSUE THREAD

**Issue by java-Xs** [Bilibili/ijkplayer#3744]
ijkplayer 好像不不能播放多码率的视频源，或者有人知道怎么修改吗？望告知 谢谢

**Comment by PengBoShi** [comment]
软解应该好改一些，多初始化几个AVcodecContext,用哪个码率的就使用对应的AVcodecContext，硬解码需要重新初始化解码器

**Comment by java-Xs** [comment]
他会根据网络  自动的切换？   而不用咱们自己判断网络的变化情况吧

**Comment by PengBoShi** [comment]
肯定不会的，这个你自己写。

**Comment by java-Xs** [comment]
好吧  3Q

**Comment by DysaniazzZ** [comment]
@java-Xs IJK 支持动态码率这块，您后来是怎么解决的呢？
