### ISSUE TITLE
Metadata字段值超出utf8字符集导致iOS崩溃

### ISSUE THREAD

**Issue by shishuo365** [Bilibili/ijkplayer#3751]
在 fillMetaInternal 方法中，ijkmeta_get_string_l(rawMeta, name) 获取的结果如下：
Open Broadcaster Software v0.624b (\xb6\xac\302\355\314\330\xb1\360\260\346 - \xbd\342\276\366Potplayer\xb2\xa5\xb7\305\306\367\324ڻ\xbbƬ\xba\363OBS\312\323Ƶ\301\367\xba\332\306\301\265\304\316\312\314\342)

在 [NSString stringWithUTF8String:value] 转换为UTF8字符串的过程中，发生错误

**Comment by raymond1012** [comment]
确实有非UTF8的情况，可以让视频云压制的时候过滤，或者stringWithUTF8String时过滤
