### ISSUE TITLE
关于编译release版本库的问题

### ISSUE THREAD

**Issue by harlanc** [Bilibili/ijkplayer#3755]
三个动态库：
libijkffmpeg.so
libijkplayer.so
libijksdl.so

如何用命令行编译出release版本？

看到编译文件中有好多--enable-debug，把这些都去掉？？

**Comment by harlanc** [comment]
没人回复么？给个提示也行，谢谢

**Comment by harlanc** [comment]
原来release和debug版本的so库会同时生成

**Comment by PersistSmile** [comment]
请问 release版本和debug版本的 so库分别生成在什么路径下了？  怎么知道某个so是debug版本还是release版本

**Comment by befovy** [comment]
按照默认的Android 编译配置，所有的so库都是release 版本


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by PersistSmile** [comment]
> 按照默认的Android 编译配置，所有的so库都是release 版本
> 
> :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

请教 怎么修改编译配置，可以把so库编译成debug版本呢

**Comment by befovy** [comment]
@PersistSmile 
./compile-ffmpeg.sh armv7a debug 是编译debug 的ffmpeg


ijksdl.so 和 ijkplayer.so 不太清楚怎么编译 debug 版本的。

但是我修改过 cmake 版本的 ijkplayer ，可以在 android 中进行debug， 也可以编译 debug 版本

http://blog.befovy.com/post/issue_20190630_3/

https://github.com/befovy/ijkplayer
