### ISSUE TITLE
播放网络直播流（rtmp协议），tcp_speed大于10kb时可以成功，小于10kb时挂起无法播放（客户端测试时的表象）

### ISSUE THREAD

**Issue by TUBB** [Bilibili/ijkplayer#3760]
**挂起无法播放时的日志如下：**

11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: ===== versions =====
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: ijkplayer    : k0.8.4
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170829--001
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: libavutil    : 55.58.100
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: libavcodec   : 57.89.100
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: libavformat  : 57.71.100
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: libswscale   : 4.6.100
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: libswresample: 2.7.100
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: ===== options =====
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : mediacodec                   = 0
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : opensles                     = 0
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : overlay-format               = 842225234
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : packet-buffering             = 0
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : start-on-prepared            = 0
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : framedrop                    = 1
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : ijkapplication               = -1417563184
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : ijkiomanager                 = -1416726768
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : http-detect-range-support    = 0
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : analyzemaxduration           = 100
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : probesize                    = 10240
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : flush_packets                = 1
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example I/IJKMEDIA: ===================
11-15 10:44:47.091 26975-26975/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_prepare_async()=0
11-15 10:44:47.091 26975-29865/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [29865] ff_msg_loop
11-15 10:44:47.091 26975-29866/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [29866] ff_vout
11-15 10:44:47.091 26975-29867/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [29867] ff_read
11-15 10:44:47.091 26975-29865/tv.danmaku.ijk.media.example D/IJKMEDIA: message_loop
11-15 10:44:47.091 26975-29865/tv.danmaku.ijk.media.example D/IJKMEDIA: FFP_MSG_FLUSH:
11-15 10:44:47.091 26975-29867/tv.danmaku.ijk.media.example W/IJKMEDIA: remove 'timeout' option for rtmp.
11-15 10:44:47.091 26975-29867/tv.danmaku.ijk.media.example D/IJKMEDIA: No default whitelist set
11-15 10:44:47.091 26975-29867/tv.danmaku.ijk.media.example D/IJKMEDIA: No default whitelist set
11-15 10:44:47.101 26975-29867/tv.danmaku.ijk.media.example I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
11-15 10:44:47.111 26975-29867/tv.danmaku.ijk.media.example I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
11-15 10:44:47.111 26975-29867/tv.danmaku.ijk.media.example D/IJKMEDIA: Handshaking...
11-15 10:44:47.121 26975-29867/tv.danmaku.ijk.media.example D/IJKMEDIA: Type answer 3
11-15 10:44:47.121 26975-29867/tv.danmaku.ijk.media.example D/IJKMEDIA: Server version 13.14.10.13
11-15 10:44:47.121 26975-29867/tv.danmaku.ijk.media.example D/IJKMEDIA: Proto = rtmp, path = /myapp/test3, app = myapp, fname = test3
11-15 10:44:47.131 26975-29867/tv.danmaku.ijk.media.example D/IJKMEDIA: Server bandwidth = 5000000
11-15 10:44:47.171 26975-29867/tv.danmaku.ijk.media.example D/IJKMEDIA: Client bandwidth = 5000000
11-15 10:44:47.171 26975-29867/tv.danmaku.ijk.media.example D/IJKMEDIA: New incoming chunk size = 4096
11-15 10:44:47.171 26975-29867/tv.danmaku.ijk.media.example D/IJKMEDIA: Creating stream...
11-15 10:44:47.211 26975-29867/tv.danmaku.ijk.media.example D/IJKMEDIA: Sending play command for 'test3'

**Comment by TUBB** [comment]
原因已找到，获取到的音视频数据解封装失败，服务器rtmp模块安装不正确导致

**Comment by Nelson-KK** [comment]
您好，我想问下，我使用avformat_open_input打开网络流进行录制，中间会跳帧，您知道怎么回事吗
