### ISSUE TITLE
android ip摄像头播放一会后异常停止

### ISSUE THREAD

**Issue by darkcater** [Bilibili/ijkplayer#3765]
内网播放,应该不存在网速问题,ip摄像机里面直接读取的rtsp流,但是我再android 端播放一会后就直接停了,问下是怎么回事,有什么解决办法吗
11-15 20:52:15.335 15559-21277/com.renrenzhineng.renrendemo I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [21277]
11-15 20:52:15.335 15559-21321/com.renrenzhineng.renrendemo W/AudioTrack: releaseBuffer() track 0xec5bf300 disabled due to previous underrun, restarting
11-15 20:52:15.339 15559-15559/com.renrenzhineng.renrendemo E/test: CURRENT_STATE_PREPAREING
11-15 20:52:15.342 15559-21321/com.renrenzhineng.renrendemo I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [21321]
11-15 20:52:15.348 15559-16752/com.renrenzhineng.renrendemo E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xc89f9600)
11-15 20:52:15.351 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: av_version_info: ff3.2--ijk0.7.6--20170324--001
11-15 20:52:15.351 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: ijk_version_info: 
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo W/IJKMEDIA: remove 'timeout' option for rtmp.
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: ===== versions =====
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: ijkplayer    : 
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: FFmpeg       : ff3.2--ijk0.7.6--20170324--001
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: libavutil    : 55.34.100
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: libavcodec   : 57.64.100
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: libavformat  : 57.56.100
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: libswscale   : 4.2.100
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: libswresample: 2.3.100
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: ===== options =====
11-15 20:52:15.352 15559-21385/com.renrenzhineng.renrendemo I/IJKMEDIA: SDL_RunThread: [21385] ff_msg_loop
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: player-opts : loop                         = 1
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: player-opts : packet-buffering             = 0
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: player-opts : mediacodec-auto-rotate       = 1
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: player-opts : framedrop                    = 3
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: player-opts : mediacodec-handle-resolution-change = 1
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: format-opts : ijkapplication               = -710938624
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: format-opts : ijkiomanager                 = -933829464
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: format-opts : analyzemaxduration           = 100
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: format-opts : probesize                    = 10240
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: format-opts : flush_packets                = 1
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: format-opts : rtsp_transport               = tcp
11-15 20:52:15.352 15559-16752/com.renrenzhineng.renrendemo I/IJKMEDIA: ===================
11-15 20:52:15.353 15559-21386/com.renrenzhineng.renrendemo I/IJKMEDIA: SDL_RunThread: [21386] ff_vout
11-15 20:52:15.353 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: SDL_RunThread: [21387] ff_read
11-15 20:52:15.353 15559-16752/com.renrenzhineng.renrendemo W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
11-15 20:52:15.354 15559-21387/com.renrenzhineng.renrendemo W/IJKMEDIA: remove 'timeout' option for rtmp.
11-15 20:52:17.403 15559-21387/com.renrenzhineng.renrendemo E/IJKMEDIA: Option ijkapplication not found.
11-15 20:52:18.529 15559-21387/com.renrenzhineng.renrendemo W/IJKMEDIA: Stream #0: not enough frames to estimate rate; consider increasing probesize
11-15 20:52:18.529 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: decoding for stream 0 failed
11-15 20:52:18.530 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: max_frame_duration: 10.000
11-15 20:52:18.530 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: Input #0, rtsp, from 'rtsp://admin:admin12345@172.16.1.232:554/1':
11-15 20:52:18.530 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA:   Metadata:
11-15 20:52:18.530 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA:     title           : 
11-15 20:52:18.530 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: Media Presentation
11-15 20:52:18.530 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA:   Duration: 
11-15 20:52:18.530 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: N/A
11-15 20:52:18.530 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: , start: 
11-15 20:52:18.530 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: 0.000000
11-15 20:52:18.530 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: , bitrate:  
11-15 20:52:18.530 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: 64 kb/s
11-15 20:52:18.530 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA:     Stream #0:0
11-15 20:52:18.530 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: : Video: h264, yuvj420p(pc, bt709, progressive), 1280x720
11-15 20:52:18.530 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: , 
11-15 20:52:18.530 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: 90k tbr, 
11-15 20:52:18.530 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: 90k tbn, 
11-15 20:52:18.530 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: 180k tbc
11-15 20:52:18.530 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA:     Stream #0:1
11-15 20:52:18.530 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: : Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
11-15 20:52:18.531 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: SDL_Android_AudioTrack: CHANNEL_OUT_MONO
11-15 20:52:18.531 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: SDL_Android_AudioTrack: ENCODING_PCM_16BIT
11-15 20:52:18.538 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(0.000000,1.000000)
11-15 20:52:18.538 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: audio_session_id = 23785
11-15 20:52:18.538 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: AudioCodec: avcodec, pcm_alaw
11-15 20:52:18.538 15559-21398/com.renrenzhineng.renrendemo I/IJKMEDIA: SDL_RunThread: [21398] ff_aout_android
11-15 20:52:18.538 15559-21399/com.renrenzhineng.renrendemo I/IJKMEDIA: SDL_RunThread: [21399] ff_audio_dec
11-15 20:52:18.541 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: VideoCodec: avcodec, h264
11-15 20:52:18.542 15559-21387/com.renrenzhineng.renrendemo W/IJKMEDIA: fps: 90000.000000 (normal)
11-15 20:52:18.542 15559-21409/com.renrenzhineng.renrendemo I/IJKMEDIA: SDL_RunThread: [21409] ff_video_dec
11-15 20:52:18.547 15559-15559/com.renrenzhineng.renrendemo E/test: CURRENT_STATE_PLAYING
11-15 20:52:18.602 15559-21398/com.renrenzhineng.renrendemo I/AudioTrack-JNI: audioTrack continuously zero data counter >= 10, send pause/stop state to pg, counter: 0
11-15 20:52:19.374 15559-16752/com.renrenzhineng.renrendemo I/tv.danmaku.ijk.media.player.IjkMediaPlayer: Info: MEDIA_INFO_VIDEO_RENDERING_START
11-15 20:52:19.402 15559-21398/com.renrenzhineng.renrendemo I/AudioTrack-JNI: audioTrack send start state to pg
11-15 20:52:22.011 15559-21398/com.renrenzhineng.renrendemo W/AudioTrack: releaseBuffer() track 0xec5bf300 disabled due to previous underrun, restarting
11-15 20:52:22.793 15559-15570/com.renrenzhineng.renrendemo I/art: Background sticky concurrent mark sweep GC freed 1589(66KB) AllocSpace objects, 4(10MB) LOS objects, 6% free, 24MB/26MB, paused 7.584ms total 36.020ms
11-15 20:52:22.906 15559-21398/com.renrenzhineng.renrendemo W/AudioTrack: releaseBuffer() track 0xec5bf300 disabled due to previous underrun, restarting
11-15 20:52:23.733 15559-21398/com.renrenzhineng.renrendemo W/AudioTrack: releaseBuffer() track 0xec5bf300 disabled due to previous underrun, restarting
11-15 20:52:23.809 15559-21406/com.renrenzhineng.renrendemo I/IJKMEDIA: concealing 1249 DC, 1249 AC, 1249 MV errors in P frame
11-15 20:52:24.547 15559-21398/com.renrenzhineng.renrendemo W/AudioTrack: releaseBuffer() track 0xec5bf300 disabled due to previous underrun, restarting
11-15 20:52:27.367 15559-21398/com.renrenzhineng.renrendemo W/AudioTrack: releaseBuffer() track 0xec5bf300 disabled due to previous underrun, restarting
11-15 20:52:28.405 15559-21398/com.renrenzhineng.renrendemo W/AudioTrack: releaseBuffer() track 0xec5bf300 disabled due to previous underrun, restarting
11-15 20:52:28.412 15559-21406/com.renrenzhineng.renrendemo I/IJKMEDIA: concealing 1263 DC, 1263 AC, 1263 MV errors in P frame
11-15 20:52:29.991 15559-21398/com.renrenzhineng.renrendemo W/AudioTrack: releaseBuffer() track 0xec5bf300 disabled due to previous underrun, restarting
11-15 20:52:29.993 15559-21407/com.renrenzhineng.renrendemo W/IJKMEDIA: Increasing reorder buffer to 1
11-15 20:52:34.793 15559-21398/com.renrenzhineng.renrendemo W/AudioTrack: releaseBuffer() track 0xec5bf300 disabled due to previous underrun, restarting
11-15 20:52:43.417 15559-21402/com.renrenzhineng.renrendemo E/IJKMEDIA: cabac decode of qscale diff failed at 70 29
11-15 20:52:43.417 15559-21402/com.renrenzhineng.renrendemo E/IJKMEDIA: error while decoding MB 70 29, bytestream 1225
11-15 20:52:43.418 15559-21402/com.renrenzhineng.renrendemo I/IJKMEDIA: concealing 1259 DC, 1259 AC, 1259 MV errors in P frame
11-15 20:52:43.490 15559-21387/com.renrenzhineng.renrendemo I/IJKMEDIA: ffp_toggle_buffering: completed: OK
11-15 20:52:43.491 15559-15559/com.renrenzhineng.renrendemo E/test: CURRENT_STATE_AUTO_COMPLETE
11-15 20:52:43.492 15559-15559/com.renrenzhineng.renrendemo I/AudioManager: abandonAudioFocus

**Comment by raymond1012** [comment]
error while decoding MB 70 29, bytestream 1225     解码错误
