### ISSUE TITLE
请教视频显示的问题

### ISSUE THREAD

**Issue by goodcyg** [Bilibili/ijkplayer#3769]
demo中视频显示是开启一个子线程video_display来显示的，那么最终的视频显示是在子线程里显示的吗？如果是iOS不运行在子线程中刷新UI，demo中是咋做到的？如果是切换到主线程中显示的？是如果切换的？
详细代码在哪里？我没有找到相关的代码？请指点具体位置？谢谢！

**Comment by raymond1012** [comment]
ios下个版本将会支持外部view的渲染，即ijk 只提供数据，所以可以等待下个版本来定制化你的需求

**Comment by goodcyg** [comment]
@raymond1012 我不是要定制需求，我遇到类似的问题想借鉴一下你们的做法。我是想知道ff_ffplay.c中视频显示是开启一个子线程video_display来显示图像的，这个图像刷新是最终在主线程还是在子线程中？如果是iOS不运行在子线程中刷新UI，demo中是咋做到的？如果是切换到主线程中显示的？是如果切换的？
详细代码在哪里？我没有找到相关的代码？请指点具体位置？谢谢！
