### ISSUE TITLE
RTMP  

### ISSUE THREAD

**Issue by zhangbl** [Bilibili/ijkplayer#377]
I can not play rtmp living stream, this is error log as below:

08-03 17:17:49.193: E/IJKMEDIA(21550): rtmp://dplay.xiuimg.com/vshow/vbc73efa25c8b376c6138b4fab9e010e4_4f16be47e3bac9d7c34219a51181b15b: I/O error
08-03 17:17:49.193: D/IJKMEDIA(21550): FFP_MSG_ERROR: 0
08-03 17:17:49.194: E/tv.danmaku.ijk.media.player.IjkMediaPlayer(21550): Error (-10000,0)

**Comment by Android4MediaPlayer** [comment]
cd config
rm module.sh
ln -s module-default.sh module.sh
cd android
# cd ios
sh compile-ffmpeg clean

**Comment by Android4MediaPlayer** [comment]
cd config
rm module.sh
ln -s module-default.sh module.sh
cd android/contrib
# cd ios/contri
sh compile-ffmpeg.sh clean
sh compile-ffmpeg.sh

**Comment by Android4MediaPlayer** [comment]
cd config
rm module.sh
ln -s module-default.sh module.sh
cd android/contrib
# cd ios/contrib
sh compile-ffmpeg.sh clean
sh compile-ffmpeg.sh

**Comment by zhangbl** [comment]
Thanks for your reply.  but I compile ffmpeg by module-default.sh   , run on android platform

**Comment by Android4MediaPlayer** [comment]
cd android/contrib

**Comment by zhangbl** [comment]
I know , I have complied  all the .so files

**Comment by Android4MediaPlayer** [comment]
OK，can the vlc play it? please check the url is valid.
