### ISSUE TITLE
peimission denied问题

### ISSUE THREAD

**Issue by daisyjingjinglj** [Bilibili/ijkplayer#3771]
附上我运行后的logcat，错误信息是peimission denied，说一下我的引用流程。
首先在linux下编译拿到了demo，demo可以成功运行，音频视频都可以播放。之后我自己建立了一个新的工程，引入了ijkplayer-java，ijkplayer-exo，以及各个ABI的module，同时将example中的service以及widget复制了进来，自己写了一个播放的Activity，播放的时候出现了错误，测试了一下，这个错误就在ijkVideoView.setPath()的时候发生，有大神知道原因以及解决方式吗？
PS：有的人说是视频格式不支持，但好像并不是，因为我把这个路径放到官方demo中运行是没有出错并且流畅播放。
11-17 16:18:21.143 29968-3449/com.test2ijkplayer I/IJKMEDIA: SDL_RunThread: [3449] ff_msg_loop
11-17 16:18:21.143 29968-29968/com.test2ijkplayer I/IJKMEDIA: libswresample: 2.7.100
11-17 16:18:21.143 29968-29968/com.test2ijkplayer I/IJKMEDIA: ===== options =====
11-17 16:18:21.143 29968-29968/com.test2ijkplayer I/IJKMEDIA: player-opts : mediacodec                   = 0
11-17 16:18:21.143 29968-29968/com.test2ijkplayer I/IJKMEDIA: player-opts : opensles                     = 0
11-17 16:18:21.143 29968-29968/com.test2ijkplayer I/IJKMEDIA: player-opts : overlay-format               = 842225234
11-17 16:18:21.143 29968-29968/com.test2ijkplayer I/IJKMEDIA: player-opts : framedrop                    = 1
11-17 16:18:21.143 29968-29968/com.test2ijkplayer I/IJKMEDIA: player-opts : start-on-prepared            = 0
11-17 16:18:21.143 29968-29968/com.test2ijkplayer I/IJKMEDIA: format-opts : ijkapplication               = -1202678880
11-17 16:18:21.143 29968-29968/com.test2ijkplayer I/IJKMEDIA: format-opts : ijkiomanager                 = -1199634288
11-17 16:18:21.143 29968-29968/com.test2ijkplayer I/IJKMEDIA: format-opts : http-detect-range-support    = 0
11-17 16:18:21.143 29968-29968/com.test2ijkplayer I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
11-17 16:18:21.143 29968-29968/com.test2ijkplayer I/IJKMEDIA: ===================
11-17 16:18:21.151 29968-3450/com.test2ijkplayer I/IJKMEDIA: SDL_RunThread: [3450] ff_vout
11-17 16:18:21.151 29968-3451/com.test2ijkplayer I/IJKMEDIA: SDL_RunThread: [3451] ff_read
11-17 16:18:21.152 29968-3451/com.test2ijkplayer E/IJKMEDIA: /sdcard/sintel.mp4: Permission denied
11-17 16:18:21.152 29968-3451/com.test2ijkplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [3451]
11-17 16:18:21.382 29968-29968/com.test2ijkplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by RyandHo** [comment]
我的也出现了，在AndroidManifest.xml中添加<uses-permission android:name="android.permission.INTERNET" />权限就好了

**Comment by Edion-Liu** [comment]
是加了啥权限啊

**Comment by huagnzhiqiang** [comment]
> 我的也出现了，在AndroidManifest.xml中添加权限就好了

请问是加了什么权限？

**Comment by xiaoqiangit** [comment]
看看是不是安卓10以上的机型加上这个权限试下。我的是这样的解决的。

android:requestLegacyExternalStorage="true"
