### ISSUE TITLE
关于arm64只支持21的问题

### ISSUE THREAD

**Issue by zjx19930911** [Bilibili/ijkplayer#3775]
我有个华为的机子是arm64的, 
把compile 'tv.danmaku.ijk.media:ijkplayer-arm64:0.8.3' 注释掉会报错
couldn't find "libijkffmpeg.so 
可是又不可能把 minSdkVersion 改为21 
请问大家都肿么解决滴

**Comment by zjx19930911** [comment]
已解决
在AndroidManifest.xml中添加
<uses-sdk tools:overrideLibrary="tv.danmaku.ijk.media.player_arm64,tv.danmaku.ijk.media.player_x86" />

**Comment by weiwenhuaming01** [comment]
@zjx19930911  你怎么解决的?

**Comment by zjx19930911** [comment]
@weiwenhuaming01    加这个<uses-sdk tools:overrideLibrary="tv.danmaku.ijk.media.player_arm64,tv.danmaku.ijk.media:ijkplayer-exo" />

**Comment by zjx19930911** [comment]
<uses-sdk tools:overrideLibrary="tv.danmaku.ijk.media.player_arm64,tv.danmaku.ijk.media:ijkplayer-exo" />

**Comment by zjx19930911** [comment]
`<uses-sdk tools:overrideLibrary="tv.danmaku.ijk.media.player_arm64,tv.danmaku.ijk.media:ijkplayer-exo" />`

**Comment by zjx19930911** [comment]
@weiwenhuaming01 加这个 `<uses-sdk tools:overrideLibrary="tv.danmaku.ijk.media.player_arm64,tv.danmaku.ijk.media:ijkplayer-exo" />`

**Comment by ymwm-lxl** [comment]
> @ weiwenhuaming01加这个`<uses-sdk tools:overrideLibrary="tv.danmaku.ijk.media.player_arm64,tv.danmaku.ijk.media:ijkplayer-exo" />`

我添加了这一行代码，但是仍旧无法编译，
