### ISSUE TITLE
Restart player

### ISSUE THREAD

**Issue by Zo2m4bie** [Bilibili/ijkplayer#378]
Hi. I have situation when I have low memory in my app and I need to restart(reconnect) player to clean buffer. For this I tried to call release() method and call setVideoURI(). But then I receive this error: 

       E/BufferQueueProducer﹕ [unnamed-9636-2] connect(P): already connected (cur=2 req=2)
        E/IJKMEDIA﹕ SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -22

 I tried to stop media player before setViedoUrl() method, but it didn't help. Can you tell me how to correct restart player/connection or clean buffer

**Comment by bbcallen** [comment]
VideoView doesn't support restart. You need to write your own VideoView, in which release IJKMediaPlayer and create new MediaPlayer().

**Comment by Zo2m4bie** [comment]
I thought when I call release(), MediaPlayer will be released because there is this two methods inside

            mMediaPlayer.reset();
            mMediaPlayer.release();

**Comment by Zo2m4bie** [comment]
Can you explain me how to correct release media player that in next time when I will call setVideoURI() I won't have this exception?

     08-03 16:41:21.364   9636-10747/com.tac.m2m.phone E/BufferQueueProducer﹕ [unnamed-9636-2] connect(P): already connected (cur=2 req=2)
     08-03 16:41:21.364   9636-10747/com.tac.m2m.phone E/IJKMEDIA﹕ SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -22

**Comment by garymabin** [comment]
I think create a brand new media player is easier as is done in current
implementation of VideoView.

2015-08-03 23:56 GMT+08:00 Zo2m4bie <notifications@github.com>:

**Comment by bbcallen** [comment]
Would you please paste full logs here, or push your modified code to github?

**Comment by Zo2m4bie** [comment]
I added only this method to VideoView:

     public void restartVideoView(){
            release(true);
            mSeekWhenPrepared = 0;
            openVideo();
     }
 
Full log after calling restartVideoView():

      W/IJKMEDIA﹕ IjkMediaPlayer_reset
      W/IJKMEDIA﹕ IjkMediaPlayer_release
      W/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0x0)
      D/IJKMEDIA﹕ ffpipeline_set_surface()
      W/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0x0)=void
      W/IJKMEDIA﹕ ijkmp_shutdown_l()
      W/IJKMEDIA﹕ wait for read_tid
      W/IJKMEDIA﹕ message_loop exit
      W/art﹕ Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[44,tid=11518,Native,Thread*=0xa1940800,peer=0x12c8d280,"Thread-4219"]
      W/art﹕ Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[43,tid=11508,Native,Thread*=0xaefa8800,peer=0x12c80100,"Thread-4218"]
      W/IJKMEDIA﹕ wait for video_refresh_tid
      E/IJKMEDIA﹕ SDL_Overlay(ffmpeg): overlay_free_l(0xaec2ff40)
      E/IJKMEDIA﹕ SDL_Overlay(ffmpeg): overlay_free_l(0xaec2ff70)
      E/IJKMEDIA﹕ SDL_Overlay(ffmpeg): overlay_free_l(0xaec2ffa0)
      W/IJKMEDIA﹕ ijkmp_shutdown_l()=void
      W/IJKMEDIA﹕ IjkMediaPlayer_native_setup
      D/IJKMEDIA﹕ ffpipeline_create_from_android()
      W/IJKMEDIA﹕ ijkmp_set_format_callback(0xa07551a9, 0x200c1e)
      W/IJKMEDIA﹕ ijkmp_set_format_callback()=void
      W/IJKMEDIA﹕ ijkmp_android_set_mediacodec_select_callback()
      D/IJKMEDIA﹕ ffpipeline_set_mediacodec_select_callback
      W/IJKMEDIA﹕ ijkmp_android_set_mediacodec_select_callback()=void
      W/IJKMEDIA﹕ ijkmp_dec_ref(): ref=0
      W/IJKMEDIA﹕ ijkmp_shutdown_l()
      W/IJKMEDIA﹕ ijkmp_shutdown_l()=void
      W/IJKMEDIA﹕ IjkMediaPlayer_release
      W/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0x0)
      D/IJKMEDIA﹕ ffpipeline_set_surface()
      W/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0x0)=void
      W/IJKMEDIA﹕ ijkmp_shutdown_l()
      W/IJKMEDIA﹕ ijkmp_shutdown_l()=void
      W/IJKMEDIA﹕ ijkmp_dec_ref(): ref=0
      W/IJKMEDIA﹕ ijkmp_shutdown_l()
      W/IJKMEDIA﹕ ijkmp_shutdown_l()=void
      W/IJKMEDIA﹕ IjkMediaPlayer_native_setup
      D/IJKMEDIA﹕ ffpipeline_create_from_android()
      W/IJKMEDIA﹕ ijkmp_set_format_callback(0xa07551a9, 0xb32)
      W/IJKMEDIA﹕ ijkmp_set_format_callback()=void
      W/IJKMEDIA﹕ ijkmp_android_set_mediacodec_select_callback()
      D/IJKMEDIA﹕ ffpipeline_set_mediacodec_select_callback
      W/IJKMEDIA﹕ ijkmp_android_set_mediacodec_select_callback()=void
      W/IJKMEDIA﹕ IjkMediaPlayer_setAvFormatOption
      W/IJKMEDIA﹕ ijkmp_set_format_option(http-detect-range-support, 0)
      W/IJKMEDIA﹕ ijkmp_set_format_option()=void
      W/IJKMEDIA﹕ IjkMediaPlayer_setOverlayFormat
      W/IJKMEDIA﹕ ijkmp_set_option_int(overlay-format, 842225234)
      W/IJKMEDIA﹕ ijkmp_set_option_int()=void
      W/IJKMEDIA﹕ IjkMediaPlayer_setAvCodecOption
      W/IJKMEDIA﹕ ijkmp_set_codec_option()
      W/IJKMEDIA﹕ ijkmp_set_codec_option()=void
      W/IJKMEDIA﹕ IjkMediaPlayer_setFrameDrop
      W/IJKMEDIA﹕ ijkmp_set_option_int(framedrop, 12)
      W/IJKMEDIA﹕ ijkmp_set_option_int()=void
      W/IJKMEDIA﹕ IjkMediaPlayer_setVolume
      W/IJKMEDIA﹕ ijkmp_android_set_volume(0.000000, 0.000000)
      W/IJKMEDIA﹕ ijkmp_android_set_volume(0.000000, 0.000000)=void
      W/IJKMEDIA﹕ IjkMediaPlayer_setDataSourceAndHeaders
      V/IJKMEDIA﹕ setDataSource: path http://thereismyurl/streaming/channel/9-live.m3u8
      W/IJKMEDIA﹕ ijkmp_set_data_source(url=" http://threreismyurl/streaming/channel/9-live.m3u8")
      W/IJKMEDIA﹕ ijkmp_set_data_source(url=" http://threreismyurl/streaming/channel/9-live.m3u8")=0
      W/IJKMEDIA﹕ IjkMediaPlayer_setVideoSurface
      W/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0xa0a279d0)
      D/IJKMEDIA﹕ ffpipeline_set_surface()
      W/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0xa0a279d0)=void
      W/tv.danmaku.ijk.media.player.IjkMediaPlayer﹕ setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
      W/IJKMEDIA﹕ IjkMediaPlayer_prepareAsync
      W/IJKMEDIA﹕ ijkmp_prepare_async()
      I/IJKMEDIA﹕ ===== options =====
      I/IJKMEDIA﹕ player-opts : overlay-format       = 842225234
      I/IJKMEDIA﹕ format-opts : http-detect-range-support = 0
      I/IJKMEDIA﹕ format-opts : framedrop            = 12
      I/IJKMEDIA﹕ codec-opts  : skip_loop_filter     = 48
      I/IJKMEDIA﹕ ===================
      I/IJKMEDIA﹕ SDL_RunThread: [12422] ff_msg_loop
      W/IJKMEDIA﹕ message_loop
      W/IJKMEDIA﹕ FFP_MSG_FLUSH:
      W/IJKMEDIA﹕ ijkmp_prepare_async()=0
      I/IJKMEDIA﹕ SDL_RunThread: [12424] ff_read
      I/IJKMEDIA﹕ SDL_RunThread: [12423] ff_vout
      D/IJKMEDIA﹕ ffpipenode_create_video_output_from_android_mediacodec()
      E/IJKMEDIA﹕ non-existing PPS 0 referenced
      E/IJKMEDIA﹕ non-existing PPS 0 referenced
      E/IJKMEDIA﹕ decode_slice_header error
      E/IJKMEDIA﹕ no frame!
      E/IJKMEDIA﹕ non-existing PPS 0 referenced
      E/IJKMEDIA﹕ non-existing PPS 0 referenced
      E/IJKMEDIA﹕ decode_slice_header error
      E/IJKMEDIA﹕ no frame!
      E/IJKMEDIA﹕ non-existing PPS 0 referenced
      E/IJKMEDIA﹕ non-existing PPS 0 referenced
      E/IJKMEDIA﹕ decode_slice_header error
      E/IJKMEDIA﹕ no frame!
      E/IJKMEDIA﹕ Option framedrop not found.
      I/IJKMEDIA﹕ max_frame_duration: 10.000
      I/IJKMEDIA﹕ Input #0, hls,applehttp, from ' http://threreismyurl/streaming/channel/9-live.m3u8':
      I/IJKMEDIA﹕ Duration:
      I/IJKMEDIA﹕ N/A
      I/IJKMEDIA﹕ , start:
      I/IJKMEDIA﹕ 17392.901356
      I/IJKMEDIA﹕ , bitrate:
      I/IJKMEDIA﹕ N/A
      I/IJKMEDIA﹕ [ 08-04 11:18:35.490 11220:12424 I/IJKMEDIA ]
         Program 0
      I/IJKMEDIA﹕ Metadata:
      I/IJKMEDIA﹕ variant_bitrate :
      I/IJKMEDIA﹕ 0
      I/IJKMEDIA﹕ [ 08-04 11:18:35.491 11220:12424 I/IJKMEDIA ]
         Stream #0:0
      I/IJKMEDIA﹕ : Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p, 640x360 [SAR 1:1 DAR 16:9]
      I/IJKMEDIA﹕ ,
      I/IJKMEDIA﹕ 25 fps,
      I/IJKMEDIA﹕ 25 tbr,
      I/IJKMEDIA﹕ 90k tbn,
      I/IJKMEDIA﹕ 50 tbc
      I/IJKMEDIA﹕ [ 08-04 11:18:35.491 11220:12424 I/IJKMEDIA ]
         Stream #0:1
      I/IJKMEDIA﹕ : Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, mono, fltp, 43 kb/s
      I/IJKMEDIA﹕ [ 08-04 11:18:35.501 11220:12424 I/IJKMEDIA ]
         SDL_Android_AudioTrack: CHANNEL_OUT_MONO
      I/IJKMEDIA﹕ SDL_Android_AudioTrack: ENCODING_PCM_16BIT
      I/IJKMEDIA﹕ SDL_Android_AudioTrack_new: init volume as 1.000000/(0.000000,1.000000)
      I/IJKMEDIA﹕ AudioCodec: avcodec, aac
      I/IJKMEDIA﹕ VideoCodec: avcodec, h264
      I/IJKMEDIA﹕ fps: 25.000000 (normal)
      I/IJKMEDIA﹕ fps: 25.000000 (normal)
      W/IJKMEDIA﹕ ijkmp_get_msg: FFP_MSG_PREPARED
      W/IJKMEDIA﹕ FFP_MSG_PREPARED:
      D/tac.com.m2m.ijkplayer.VideoView﹕ onPrepared
      W/IJKMEDIA﹕ IjkMediaPlayer_start
      W/IJKMEDIA﹕ ijkmp_start()
      W/IJKMEDIA﹕ ijkmp_start()=0
      W/IJKMEDIA﹕ ijkmp_get_msg: FFP_REQ_START
      D/IJKMEDIA﹕ ijkmp_get_msg: FFP_REQ_START: start on fly
      W/IJKMEDIA﹕ FFP_MSG_VIDEO_SIZE_CHANGED: 640, 360
      D/tac.com.m2m.ijkplayer.VideoView﹕ onVideoSizeChanged: (640x360)
      W/IJKMEDIA﹕ FFP_MSG_SAR_CHANGED: 1, 1
      D/tac.com.m2m.ijkplayer.VideoView﹕ onVideoSizeChanged: (640x360)
      W/IJKMEDIA﹕ ijkmp_get_msg: FFP_REQ_START
      D/IJKMEDIA﹕ ijkmp_get_msg: FFP_REQ_START: start on fly
      I/IJKMEDIA﹕ SDL_RunThread: [12435] ff_audio_dec
      I/IJKMEDIA﹕ SDL_RunThread: [12441] ff_video_dec
      I/IJKMEDIA﹕ SDL_RunThread: [12434] ff_aout_android
      W/IJKMEDIA﹕ SDL_VoutFFmpeg_CreateOverlay(w=640, h=360, fmt=RV32(0x32335652, dp=0xa187c388)
      W/IJKMEDIA﹕ FFP_MSG_VIDEO_SIZE_CHANGED: 640, 360
      D/tac.com.m2m.ijkplayer.VideoView﹕ onVideoSizeChanged: (640x360)
      D/IJKMEDIA﹕ ANativeWindow_setBuffersGeometry: w=400, h=225, f=(0x1) => w=640, h=360, f=RV32(0x32335652)
      E/BufferQueueProducer﹕ [unnamed-11220-2] connect(P): already connected (cur=2 req=2)
      E/IJKMEDIA﹕ SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -22
      W/IJKMEDIA﹕ FFP_MSG_VIDEO_SIZE_CHANGED: 640, 360
      D/tac.com.m2m.ijkplayer.VideoView﹕ onVideoSizeChanged: (640x360)
      W/IJKMEDIA﹕ SDL_VoutFFmpeg_CreateOverlay(w=640, h=360, fmt=RV32(0x32335652, dp=0xa187c388)
      W/IJKMEDIA﹕ FFP_MSG_VIDEO_SIZE_CHANGED: 640, 360
      D/tac.com.m2m.ijkplayer.VideoView﹕ onVideoSizeChanged: (640x360)
      W/IJKMEDIA﹕ SDL_VoutFFmpeg_CreateOverlay(w=640, h=360, fmt=RV32(0x32335652, dp=0xa187c388)
      E/BufferQueueProducer﹕ [unnamed-11220-2] connect(P): already connected (cur=2 req=2)
      E/IJKMEDIA﹕ SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -22

**Comment by garymabin** [comment]
try to use `stopPlayback` to stop player, there is a reasonable way to reset the player below.
```
public void reset() {
    mView.stopPlayback();
    //you can use some delay here when you recreate a player.
    mView.setVideoPath(newUrl);
    mView.requestFocus();
    mView.start();
}

**Comment by Zo2m4bie** [comment]
@garymabin No, it has not helped. I  tried without delay and with delay, received the same error

**Comment by garymabin** [comment]
@Zo2m4bie I don't know how you really do the delay stuff, it really works for me like this.
```
	@Override
	public void reset(boolean forced) {
		mView.stopPlayback();
		mHandler.postDelayed(new Runnable() {
			@Override
			public void run() {
				mView.setVideoPath(newUrl);
				mView.requestFocus();
				mView.start();
			}
		}, 500);
	}

**Comment by Zo2m4bie** [comment]
Yes, it works. I found why it didn't work for me, I changed VideoView parent view, in sample it extends from SurfaceView, I changed it to TextureView(because I need to receive frame from surface).  Also can I some how get frame from stream(last frame or which is showing now)?

**Comment by Zo2m4bie** [comment]
@bbcallen if I receive this messages log:

    08-03 16:41:21.364   9636-10747/com.tac.m2m.phone E/BufferQueueProducer﹕ [unnamed-9636-2] connect(P): already connected (cur=2 req=2)
    08-03 16:41:21.364   9636-10747/com.tac.m2m.phone E/IJKMEDIA﹕ SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -22

Is it mean that my videoview didn't release old data and I still connect to old thread?

**Comment by Zo2m4bie** [comment]
@bbcallen I created pull request with my videoview which extends from TextureView. Could you please look at this code and maybe you will see why restarting doesn't work and this error happends?

**Comment by Zo2m4bie** [comment]
I have seen you added work with TextureView via TextureRenderView, I thought it will fix bug with restarting, but it steel happens. If you select TextureRenderView to show video and after connecting to the first stream you will call

    release(true);
    setVideoPath("new url");
    start();

Video doesn't start and I see in logs:
    
    E/BufferQueueProducer﹕ [unnamed-9636-2] connect(P): already connected (cur=2 req=2)
    E/IJKMEDIA﹕ SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -22
I have seen you added work with TextureView via TextureRenderView, I thought it will fix bug with restring, but it steel happening. It you select TextureRenderView to show video and after connecting to the first stream I call

    release(true);
    setVideoPath("new url");
    start();

Video doesn't start and I see in logs:
    
    E/BufferQueueProducer﹕ [unnamed-9636-2] connect(P): already connected (cur=2 req=2)
    E/IJKMEDIA﹕ SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -22

**Comment by bbcallen** [comment]
IjkVideoView is only a demo, and is not supposed to be used like that.
Always release previous MediaPlayer and SurfaceView/TextureView before you create new MediaPlayer instance.

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
