### ISSUE TITLE
IJkplayer ios avi file not working

### ISSUE THREAD

**Issue by alpeshprajapati1989** [Bilibili/ijkplayer#3784]
i want to play .avi file from http link using ijkmediaplayer but not playing.
please help me out.

**Comment by alpeshprajapati1989** [comment]
is there .avi file support in os?

**Comment by raymond1012** [comment]
enable AVI_DEMUXER

**Comment by alpeshprajapati1989** [comment]
where i enable AVI_DEMUXER in code.

**Comment by alpeshprajapati1989** [comment]
IJKFFOptions *options = [[IJKFFOptions alloc] init];
    [options setFormatOptionValue:@"YES"          forKey:@"AVI_DEMUXER"];

Its write way to enable.

**Comment by raymond1012** [comment]
enable AVI_DEMUXER in module-lite.sh

2017-11-23 12:32 GMT+08:00 alpeshprajapati1989 <notifications@github.com>:

**Comment by alpeshprajapati1989** [comment]
I have older code, In there i am not getting module-lite.sh file

**Comment by alpeshprajapati1989** [comment]
I write like this in module-lite.sh file
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=avi"
and
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-muxer=avi"

then after execute .sh script but not working .avi file yet

**Comment by fza3230200** [comment]
> I write like this in module-lite.sh file
> export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=avi"
> and
> export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-muxer=avi"
> 
> then after execute .sh script but not working .avi file yet

now do you resolve this question?
