### ISSUE TITLE
三星S7 S8 mediacodec解码 不使用surface的时候为什么解码速度很慢？

### ISSUE THREAD

**Issue by PengBoShi** [Bilibili/ijkplayer#3789]
三星S7 S8 mediacodec解码 不使用surface的时候为什么解码速度很慢？求助大神

**Comment by Android4MediaPlayer** [comment]
不明白意思

**Comment by PengBoShi** [comment]
@Android4MediaPlayer 就是使用mediacodec的时候 不设置surface。我们使用unity渲染，所以没有使用surface。没有设置surface的时候 mediacodec解码速度慢了很多。

**Comment by Android4MediaPlayer** [comment]
很大可能是你渲染层问题，应该不是解码

**Comment by PengBoShi** [comment]
@Android4MediaPlayer我做过测试的，使用原生的ijkplayer，不设置surface 不渲染的情况下 解码速度就是慢了很多

**Comment by PengBoShi** [comment]
而且用华为V8就没有这个问题的。

**Comment by Android4MediaPlayer** [comment]
你把surface设置为NULL试一下

**Comment by PengBoShi** [comment]
android develop 有说明 使用surface 效率高_

**Comment by ZhangYaRu** [comment]
> 三星S7 S8 mediacodec解码 不使用surface的时候为什么解码速度很慢？求助大神

你好, 我的mediacodec在S8手机上无法解码, 其他手机上没有问题, 请问知道为什么吗?
