### ISSUE TITLE
播放本地加密m3u8完成后一直刷log:error while seeking

### ISSUE THREAD

**Issue by harlanc** [Bilibili/ijkplayer#3797]
log 如下，不知道是什么原因。

11-29 16:24:03.427 18727-18931/com.gvr.gvr_sphere D/IJKMEDIA: FFP_MSG_SEEK_COMPLETE:
11-29 16:24:03.427 18727-18931/com.gvr.gvr_sphere D/IJKMEDIA: FFP_MSG_BUFFERING_END:
11-29 16:24:03.647 18727-18933/com.gvr.gvr_sphere D/IJKMEDIA: ffp_toggle_buffering_l: start
11-29 16:24:03.648 18727-18933/com.gvr.gvr_sphere E/IJKMEDIA: /storage/emulated/0/Download/results/test.m3u8: error while seeking
11-29 16:24:03.648 18727-18933/com.gvr.gvr_sphere D/IJKMEDIA: ffp_toggle_buffering_l: end
11-29 16:24:03.648 18727-18931/com.gvr.gvr_sphere D/IJKMEDIA: FFP_MSG_BUFFERING_START:
11-29 16:24:03.649 18727-18931/com.gvr.gvr_sphere D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_SEEK_COMPLETE
11-29 16:24:03.649 18727-18931/com.gvr.gvr_sphere D/IJKMEDIA: FFP_MSG_SEEK_COMPLETE:
11-29 16:24:03.649 18727-18931/com.gvr.gvr_sphere D/IJKMEDIA: FFP_MSG_BUFFERING_END:
11-29 16:24:03.869 18727-18933/com.gvr.gvr_sphere D/IJKMEDIA: ffp_toggle_buffering_l: start
11-29 16:24:03.870 18727-18933/com.gvr.gvr_sphere E/IJKMEDIA: /storage/emulated/0/Download/results/test.m3u8: error while seeking
11-29 16:24:03.870 18727-18933/com.gvr.gvr_sphere D/IJKMEDIA: ffp_toggle_buffering_l: end
11-29 16:24:03.870 18727-18931/com.gvr.gvr_sphere D/IJKMEDIA: FFP_MSG_BUFFERING_START:
11-29 16:24:03.870 18727-18931/com.gvr.gvr_sphere D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_SEEK_COMPLETE
11-29 16:24:03.871 18727-18931/com.gvr.gvr_sphere D/IJKMEDIA: FFP_MSG_SEEK_COMPLETE:
11-29 16:24:03.871 18727-18931/com.gvr.gvr_sphere D/IJKMEDIA: FFP_MSG_BUFFERING_END:
11-29 16:24:04.091 18727-18933/com.gvr.gvr_sphere D/IJKMEDIA: ffp_toggle_buffering_l: start
11-29 16:24:04.091 18727-18931/com.gvr.gvr_sphere D/IJKMEDIA: FFP_MSG_BUFFERING_START:
11-29 16:24:04.091 18727-18933/com.gvr.gvr_sphere E/IJKMEDIA: /storage/emulated/0/Download/results/test.m3u8: error while seeking
11-29 16:24:04.092 18727-18931/com.gvr.gvr_sphere D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_SEEK_COMPLETE
11-29 16:24:04.092 18727-18933/com.gvr.gvr_sphere D/IJKMEDIA: ffp_toggle_buffering_l: end
11-29 16:24:04.092 18727-18931/com.gvr.gvr_sphere D/IJKMEDIA: FFP_MSG_SEEK_COMPLETE:
11-29 16:24:04.092 18727-18931/com.gvr.gvr_sphere D/IJKMEDIA: FFP_MSG_BUFFERING_END:
11-29 16:24:04.313 18727-18933/com.gvr.gvr_sphere D/IJKMEDIA: ffp_toggle_buffering_l: start
11-29 16:24:04.314 18727-18933/com.gvr.gvr_sphere E/IJKMEDIA: /storage/emulated/0/Download/results/test.m3u8: error while seeking
11-29 16:24:04.314 18727-18933/com.gvr.gvr_sphere D/IJKMEDIA: ffp_toggle_buffering_l: end
11-29 16:24:04.314 18727-18931/com.gvr.gvr_sphere D/IJKMEDIA: FFP_MSG_BUFFERING_START:
11-29 16:24:04.314 18727-18931/com.gvr.gvr_sphere D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_SEEK_COMPLETE
11-29 16:24:04.314 18727-18931/com.gvr.gvr_sphere D/IJKMEDIA: FFP_MSG_SEEK_COMPLETE:
11-29 16:24:04.315 18727-18931/com.gvr.gvr_sphere D/IJKMEDIA: FFP_MSG_BUFFERING_END:
11-29 16:24:04.535 18727-18933/com.gvr.gvr_sphere D/IJKMEDIA: ffp_toggle_buffering_l: start

**Comment by harlanc** [comment]
原因是做成了循环播放，播完之后再seekto(0)好像就会出现这个问题

**Comment by zhaokidd** [comment]
setLooping(true)会有这个问题，如果要循环播放有什么好的方案么

**Comment by harlanc** [comment]
@zhaokidd 判断是否播放完毕，有一个监听事件，监听到事件后直接call_play(0)

**Comment by zhaokidd** [comment]
@harlanc  没发现有 这个方法  看安卓官方文档发现的一个解决方法:调用 IMediaPlayer的stop方法将播放器置于stop状态  然后prepareSync()开始播放即可

**Comment by harlanc** [comment]
@zhaokidd 哦，我们用的是IMediaPlayer.OnCompletionListener，播放完毕，重新播放

**Comment by zhaokidd** [comment]
@harlanc 一样的 ，我也是在这个回调中处理。不过我没找到你说的 call_Play()方法

**Comment by shangshu-litao** [comment]
您好，这个问题解决了吗，怎么播放本地加密过的m3u8文件

**Comment by harlanc** [comment]
加密过的m3u8文件？加密ts还是加密m3u8? HLS 加密后用ijkplayer一样可以播放，编译参数应该需要修改一下，支持encrypted HLS.

**Comment by YYHNobug** [comment]
你好，我的场景是：iOS需要播放加密的m3u8文件，后台把每个ts地址进行加密，客户端进行解密后播放，请问IJK支持吗？现在解密每个ts已实现，该怎么播放？希望得到您的帮助。
已修改export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=crypto”，支持crypto协议
