### ISSUE TITLE
hisi H264 1920x1080 video play fail(see detail log)

### ISSUE THREAD

**Issue by szhansen** [Bilibili/ijkplayer#3799]
ijk.media.example W/IJKMEDIA: monstartup already called                                                                              
ijk.media.example I/AudioManager: requestAudioFocus() status : 1                                                                      
ijk.media.example I/AudioManager: requestAudioFocus() apk    : tv.danmaku.ijk.media.example                                           
ijk.media.example I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170829--001                                                         
ijk.media.example I/IJKMEDIA: ijk_version_info: k0.8.4                                                                                
ijk.media.example I/IJKMEDIA: ===== versions =====                                                                                    
ijk.media.example I/IJKMEDIA: ijkplayer    : k0.8.4                                                                                   
ijk.media.example I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170829--001                                                           
ijk.media.example I/IJKMEDIA: SDL_RunThread: [27687] ff_msg_loop                                                                      
ijk.media.example I/IJKMEDIA: libavutil    : 55.58.100                                                                                
ijk.media.example I/IJKMEDIA: libavcodec   : 57.89.100                                                                                
ijk.media.example I/IJKMEDIA: libavformat  : 57.71.100                                                                                
ijk.media.example I/IJKMEDIA: libswscale   : 4.6.100                                                                                  
ijk.media.example I/IJKMEDIA: libswresample: 2.7.100                                                                                  
ijk.media.example I/IJKMEDIA: ===== options =====                                                                                     
ijk.media.example I/IJKMEDIA: player-opts : mediacodec                   = 0                                                          
ijk.media.example I/IJKMEDIA: player-opts : opensles                     = 0                                                          
ijk.media.example I/IJKMEDIA: player-opts : overlay-format               = 842225234                                                  
ijk.media.example I/IJKMEDIA: player-opts : framedrop                    = 1                                                          
ijk.media.example I/IJKMEDIA: player-opts : start-on-prepared            = 0                                                          
ijk.media.example I/IJKMEDIA: format-opts : ijkapplication               = -377696688                                                 
ijk.media.example I/IJKMEDIA: format-opts : ijkiomanager                 = -196035968                                                 
ijk.media.example I/IJKMEDIA: format-opts : http-detect-range-support    = 0                                                          
ijk.media.example I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48                                                         
ijk.media.example I/IJKMEDIA: ===================                                                                                     
ijk.media.example I/IJKMEDIA: SDL_RunThread: [27688] ff_vout                                                                          
ijk.media.example I/IJKMEDIA: SDL_RunThread: [27689] ff_read                                                                          
ijk.media.example E/IJKMEDIA: /storage/emulated/0/DCIM/ROV/Videos/stream_chn1.h264: Invalid data found when processing input          
ijk.media.example I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [27689]                                                                        
ijk.media.example E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)                                                      
ijk.media.example I/AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
ijk.media.example I/art: current process_level is : 0

**Comment by szhansen** [comment]
use VLC Player both below video is ok:
H264-MPEG-4 AVC(part10)(h264)
H264-MPEG-4 AVC(part10)(avc1)

but use ijkplayer,not support H264-MPEG-4 AVC(part10)(h264)

**Comment by Android4MediaPlayer** [comment]
@szhansen video sample url?

**Comment by yuazhen** [comment]
> ijk.media.example
 E/IJKMEDIA: /storage/emulated/0/DCIM/ROV/Videos/stream_chn1.h264: Invalid data found when processing input

It seems like your video file is corrupted.

**Comment by szhansen** [comment]
@Android4MediaPlayer 
here is the video:
https://pan.baidu.com/s/1gfLB3iF

Thank you so much.

**Comment by Android4MediaPlayer** [comment]
@szhansen OK. add blow config parameter in module-lite.sh.
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=h264"

**Comment by szhansen** [comment]
@Android4MediaPlayer 
ok,I will have a try right now.
thank you so much.

**Comment by szhansen** [comment]
@Android4MediaPlayer 
Great,solved...
thanks a  lot.
