### ISSUE TITLE
关于ijkplayer播放视频时提前收到MPMovieFinishReasonPlaybackEnded

### ISSUE THREAD

**Issue by coramo** [Bilibili/ijkplayer#38]
我使用ijkplayer做多个文件播放
方式是一开始就初始化两个播放器
先开始播放第一个 
第一个播放结束 就开始播放第二个 销毁第一个 创建下一个
这里出现的问题是 在播放第二段的时候 也就是第一段播放完了 接着播放的二段 
这个途中却提前收到了MPMovieFinishReasonPlaybackEnded 时间 不知道这是不是bug

还有个就是貌似存在内存泄漏 内存没有完全回收

**Comment by simtice** [comment]
@jgfntu @DaaarksunWang  我的还是不行
ffconcat version 1.0
file http://cn-gdfs5-dx.acgvideo.com/vg7/2/0e/6546710-1.flv?expires=1460724300&ssig=yqOcE8bCE8ntlgkB1v7rqQ&oi=3070666578&appkey=f3bb208b3d081dc8&or=3074230573&rate=0
duration 267544
file http://cn-gdfs5-dx.acgvideo.com/vg7/2/0e/6546710-2.flv?expires=1460724300&ssig=jJ_iWb08zIhLxU6KICXx4w&oi=3070666578&appkey=f3bb208b3d081dc8&or=3074230573&rate=0
duration 442732
file http://cn-gdfs5-dx.acgvideo.com/vg7/2/0e/6546710-3.flv?expires=1460724300&ssig=T-c2-csCpdmW3xuCdKIHGg&oi=3070666578&appkey=f3bb208b3d081dc8&or=3074230573&rate=0
duration 276423

能否帮忙测试以下

**Comment by Coramo** [comment]
@simtice 

时长是秒为单位  然后你可以检查下其中的URL是否能正常播放

只能帮到这里了.
