### ISSUE TITLE
为何音频流找不到？

### ISSUE THREAD

**Issue by goodcyg** [Bilibili/ijkplayer#3803]
编译的库，我在mac 下运行demo，我的mov文件里，明明有aac音频流，avformat_find_stream_info查找后pFormatCtx—>nb_streams=1,只有视频流，没有音频流，这是咋回事？代码如下：
         pFormatCtx=avformat_alloc_context();
    
        AVInputFormat *iformat=av_find_input_format("h264");
        ret=avformat_open_input(&pFormatCtx,filename, iformat,NULL);
        if(ret!=0)
        {
            av_strerror(ret, errbuf, ERR_BUF_SIZE);
            printf("errbuf:%s\n",errbuf);
            return -1; // Couldn't open file
        }
          
        // Retrieve stream information
        if(avformat_find_stream_info(pFormatCtx,0)<0)
            return -1; // Couldn't find stream information
这里查看pFormatCtx—>nb_streams=1，我是在mac运行的，不是在ios下。

**Comment by goodcyg** [comment]
自己解决了。

**Comment by goodcyg** [comment]
自己解决了。

**Comment by tommyfeng** [comment]
请问你是如何解决的，能否说一下，谢谢！@goodcyg
