### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by mars-rover** [Bilibili/ijkplayer#381]
The following is the log

ijkmp_set_format_callback(0x25110, 0xbf50e90)
ijkmp_set_format_callback()=void
ijkmp_set_option_int(start-on-prepared, 1)
ijkmp_set_option_int()=void
ijkmp_ios_set_view(glView=0xca60420)
ijkmp_ios_set_view(glView=0xca60420)=void
ijkmp_set_option(overlay-format, fcc-i420)
ijkmp_set_option()=void
ijkmp_set_option_int(framedrop, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(max-fps, 30)
ijkmp_set_option_int()=void
ijkmp_set_option_int(video-pictq-size, 3)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox-max-frame-width, 960)
ijkmp_set_option_int()=void
ijkmp_set_option(user-agent, ijkplayer)
ijkmp_set_option()=void
ijkmp_set_option_int(reconnect, 1)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_loop_filter, 48)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_frame, 8)
ijkmp_set_option_int()=void
ijkmp_set_data_source(url="rtmp://live.hkstv.hk.lxdns.com/live/hks")
ijkmp_set_data_source(url="rtmp://live.hkstv.hk.lxdns.com/live/hks")=0
ijkmp_set_option(safe, 0)
ijkmp_set_option()=void
ijkmp_prepare_async()
===== options =====
player-opts : start-on-prepared            = 1
player-opts : overlay-format               = fcc-i420
player-opts : framedrop                    = 0
player-opts : max-fps                      = 30
player-opts : video-pictq-size             = 3
player-opts : videotoolbox-max-frame-width = 960
format-opts : user-agent                   = ijkplayer
format-opts : reconnect                    = 1
format-opts : safe                         = 0
codec-opts  : skip_loop_filter             = 48
codec-opts  : skip_frame                   = 8
===================
ijkmp_prepare_async()=0
ijkmp_start()
ijkmp_start()=-3
remove 'timeout' option for rtmp.
2015-08-04 10:28:53.869 FFmpeg[696:13796] {
    UIDeviceOrientationRotateAnimatedUserInfoKey = 0;
}
2015-08-04 10:28:53.887 FFmpeg[696:13796] IJKSDLGLView:applicationDidBecomeActive: 0
2015-08-04 10:28:53.887 FFmpeg[696:13796] IJKFFMoviePlayerController:applicationDidBecomeActive: 0
Handshaking...
Type answer 3
Server version 0.0.0.0
Proto = rtmp, path = /live/hks, app = live, fname = hks
Server bandwidth = 2500000
Client bandwidth = 2500000
Creating stream...
Sending play command for 'hks'
New incoming chunk size = 4096
Format flv probed with size=2048 and score=100
Option user-agent not found.
Before avformat_find_stream_info() pos: 13 bytes read:24214 seeks:0
Unknown type |RtmpSampleAccess
Unknown type onStatus
Stream discovered after head already parsed
Current profile doesn't provide more RBSP data in PPS, skipping
non-existing SPS 0 referenced in buffering period
non-existing SPS 0 referenced in buffering period
Non-increasing DTS in stream 1: packet 2 with DTS 0, packet 3 with DTS 0
Non-increasing DTS in stream 1: packet 3 with DTS 0, packet 4 with DTS 0
Non-increasing DTS in stream 1: packet 4 with DTS 0, packet 5 with DTS 0
Non-increasing DTS in stream 1: packet 5 with DTS 0, packet 6 with DTS 0
Non-increasing DTS in stream 1: packet 6 with DTS 0, packet 7 with DTS 0
Non-increasing DTS in stream 1: packet 7 with DTS 0, packet 8 with DTS 0
Non-increasing DTS in stream 1: packet 8 with DTS 0, packet 9 with DTS 0
Non-increasing DTS in stream 1: packet 9 with DTS 0, packet 10 with DTS 0
Non-increasing DTS in stream 1: packet 10 with DTS 0, packet 11 with DTS 0
All info found
rfps: 14.833333 0.016449
rfps: 14.833333 0.016449
rfps: 14.916667 0.004120
rfps: 14.916667 0.004120
rfps: 15.000000 0.000017
rfps: 15.083333 0.004139
rfps: 15.083333 0.004139
rfps: 15.166667 0.016486
rfps: 15.166667 0.016486
rfps: 29.833333 0.016481
rfps: 29.833333 0.016481
rfps: 29.916667 0.004162
rfps: 30.000000 0.000067
rfps: 60.000000 0.000270
rfps: 120.000000 0.001079
rfps: 240.000000 0.004316
rfps: 29.970030 0.000593
rfps: 59.940060 0.002371
rfps: 14.985015 0.000148
After avformat_find_stream_info() pos: 271394 bytes read:271394 seeks:0 frames:135
max_frame_duration: 3600.000
Input #0, flv, from 'rtmp://live.hkstv.hk.lxdns.com/live/hks':
  Metadata:
    author          : PowerSmart
    copyright       : 
    description     : 
    datarate        : 500
    livetime        : 1435542502
    timeshift       : 0
  Duration: 01:00:00.00, start: 0.000000, bitrate: N/A
    Stream #0:0, 83, 1/1000: Audio: aac (LC), 32000 Hz, stereo, fltp
    Stream #0:1, 52, 1/1000: Video: h264 (Constrained Baseline), 1 reference frame, yuv420p(left), 640x480, 1/30, 15.17 fps, 15 tbr, 1k tbn, 30 tbc
aout_open_audio()
AudioCodec: avcodec, aac
aout_pause_audio(0)
detected 4 logical cores
vtb fail!!! switch to ffmpeg decode!!!! 
VideoCodec: avcodec, h264
fps: 15.166667 (normal)
fps: 15.000000 (normal)
ijkmp_get_msg: FFP_MSG_PREPARED
non-existing SPS 0 referenced in buffering period
2015-08-04 10:28:56.996 FFmpeg[696:13796] FFP_MSG_VIDEO_DECODER_OPEN: false
2015-08-04 10:28:56.997 FFmpeg[696:13796] FFP_MSG_PREPARED:
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
2015-08-04 10:28:56.997 FFmpeg[696:13796] fps in meta 15.166667
2015-08-04 10:28:56.997 FFmpeg[696:13796] mediaIsPreparedToPlayDidChange
2015-08-04 10:28:56.997 FFmpeg[696:13796] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3
2015-08-04 10:28:56.997 FFmpeg[696:13796] FFP_MSG_VIDEO_SIZE_CHANGED: 640, 480
2015-08-04 10:28:56.998 FFmpeg[696:13796] FFP_MSG_SAR_CHANGED: 0, 1
2015-08-04 10:28:56.998 FFmpeg[696:13796] moviePlayBackStateDidChange 1: playing
Current profile doesn't provide more RBSP data in PPS, skipping
non-existing SPS 0 referenced in buffering period
SDL_VoutFFmpeg_CreateOverlay(w=640, h=480, fmt=I420(0x30323449, dp=0xbf52430)
2015-08-04 10:28:57.002 FFmpeg[696:13796] FFP_MSG_VIDEO_SIZE_CHANGED: 640, 480
SDL_VoutFFmpeg_CreateOverlay(w=640, h=480, fmt=I420(0x30323449, dp=0xbf52430)
2015-08-04 10:28:57.003 FFmpeg[696:13796] FFP_MSG_VIDEO_SIZE_CHANGED: 640, 480
SDL_VoutFFmpeg_CreateOverlay(w=640, h=480, fmt=I420(0x30323449, dp=0xbf52430)
2015-08-04 10:28:57.005 FFmpeg[696:13796] FFP_MSG_VIDEO_SIZE_CHANGED: 640, 480
2015-08-04 10:28:57.135 FFmpeg[696:13796] OK setup GL
2015-08-04 10:28:57.136 FFmpeg[696:13988] OK use I420 GL renderer
2015-08-04 10:28:57.156 FFmpeg[696:13988] OK setup GL programm
2015-08-04 10:28:57.156 FFmpeg[696:13988] OK setup GL framebuffer 640:560
non-existing SPS 0 referenced in buffering period
Current profile doesn't provide more RBSP data in PPS, skipping
non-existing SPS 0 referenced in buffering period
non-existing SPS 0 referenced in buffering period
Current profile doesn't provide more RBSP data in PPS, skipping
……
……
……
Current profile doesn't provide more RBSP data in PPS, skipping
non-existing SPS 0 referenced in buffering period
non-existing SPS 0 referenced in buffering period
non-existing SPS 0 referenced in buffering period
Sending bytes read report
Current profile doesn't provide more RBSP data in PPS, skipping
non-existing SPS 0 referenced in buffering period
non-existing SPS 0 referenced in buffering period
Current profile doesn't provide more RBSP data in PPS, skipping
non-existing SPS 0 referenced in buffering period
Unknown packet type received 0x00
Unknown packet type received 0x00
Unknown packet type received 0x00
Unknown packet type received 0x00
Unknown packet type received 0x00
Unknown packet type received 0x00
Unknown packet type received 0x00
Unknown packet type received 0x00
Unknown packet type received 0x00
Unknown packet type received 0x00
non-existing SPS 0 referenced in buffering period
Stream discovered after head already parsed
Unknown packet type received 0x00
Unknown packet type received 0x00
Unknown packet type received 0x00
Unknown packet type received 0x00
Unknown packet type received 0x00
Unknown packet type received 0x00
Unknown packet type received 0x00
Unknown packet type received 0x00
Unknown packet type received 0x00
Unknown packet type received 0x00
Unknown packet type received 0x00
Stream discovered after head already parsed
FFmpeg(696,0x4e101d4) malloc: *** error for object 0xd039404: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug

**Comment by bbcallen** [comment]
Seems an FFmpeg issue.

**Comment by mars-rover** [comment]
ok, thanks, It crash not open.
