### ISSUE TITLE
build error on macos

### ISSUE THREAD

**Issue by leonard0629** [Bilibili/ijkplayer#382]
i got a message "ijkplayer-android/android/ijkplayer/player-armv5/src/main/jni/ijkmedia/ijksdl/ffmpeg/abi_all/image_convert.c:25:20: fatal error: libyuv.h: No such file or directory" when built the ijkplayer for android. How can i install this lib?

**Comment by leonard0629** [comment]
i just use the cmd "git checkout -B latest k0.3.1", is that the correct/latest version?

**Comment by bbcallen** [comment]
Full build log, please.

**Comment by leonard0629** [comment]
ok, i'll post it when back home.but another question, now i'm building this on cygwin, at last step, i compiled just one libijkffmepg.so
$ ./compile-ijk.sh all
profiler build: NO
[armeabi-v7a] Prebuilt       : libijkffmpeg.so <= /cygdrive/f/Program/code/workspace_idea/ijkplayer-android/android/contrib/build/ffmpeg-armv7a/output/
[armeabi-v7a] Install        : libijkffmpeg.so => libs/armeabi-v7a/libijkffmpeg.so
[armeabi-v7a] Compile thumb  : ijkplayer <= ff_cmdutils.c
arm-linux-androideabi-gcc.exe: error: F:/Program/code/workspace_idea/ijkplayer-android/android/ijkplayer/player-armv7a/src/main/jni/ijkmedia/ijkplayer/ff_cmdutils.c: No such file or directory
arm-linux-androideabi-gcc.exe: fatal error: no input files
compilation terminated.
/cygdrive/f/tools/Android/android-ndk-r10e/build/core/build-binary.mk:464: recipe for target '/cygdrive/f/Program/code/workspace_idea/ijkplayer-android/android/ijkplayer/player-armv7a/src/main/obj/loc
al/armeabi-v7a/objs/ijkplayer/ff_cmdutils.o' failed
make: *** [/cygdrive/f/Program/code/workspace_idea/ijkplayer-android/android/ijkplayer/player-armv7a/src/main/obj/local/armeabi-v7a/objs/ijkplayer/ff_cmdutils.o] Error 1
/cygdrive/f/Program/code/workspace_idea/ijkplayer-android/android
profiler build: NO
[armeabi-v7a] Install        : libijkffmpeg.so => libs/armeabi-v7a/libijkffmpeg.so
[armeabi-v7a] Compile thumb  : ijkplayer <= ff_cmdutils.c
arm-linux-androideabi-gcc.exe: error: F:/Program/code/workspace_idea/ijkplayer-android/android/ijkplayer/player-armv7a/src/main/jni/ijkmedia/ijkplayer/ff_cmdutils.c: No such file or directory
arm-linux-androideabi-gcc.exe: fatal error: no input files
compilation terminated.
/cygdrive/f/tools/Android/android-ndk-r10e/build/core/build-binary.mk:464: recipe for target '/cygdrive/f/Program/code/workspace_idea/ijkplayer-android/android/ijkplayer/player-armv7a/src/main/obj/loc
al/armeabi-v7a/objs/ijkplayer/ff_cmdutils.o' failed
make: *** [/cygdrive/f/Program/code/workspace_idea/ijkplayer-android/android/ijkplayer/player-armv7a/src/main/obj/local/armeabi-v7a/objs/ijkplayer/ff_cmdutils.o] Error 1
/cygdrive/f/Program/code/workspace_idea/ijkplayer-android/android
profiler build: NO
[x86] Prebuilt       : libijkffmpeg.so <= /cygdrive/f/Program/code/workspace_idea/ijkplayer-android/android/contrib/build/ffmpeg-x86/output/
[x86] Install        : libijkffmpeg.so => libs/x86/libijkffmpeg.so
[x86] Compile        : ijkplayer <= ff_cmdutils.c
i686-linux-android-gcc.exe: error: F:/Program/code/workspace_idea/ijkplayer-android/android/ijkplayer/player-x86/src/main/jni/ijkmedia/ijkplayer/ff_cmdutils.c: No such file or directory
i686-linux-android-gcc.exe: fatal error: no input files
compilation terminated.
/cygdrive/f/tools/Android/android-ndk-r10e/build/core/build-binary.mk:464: recipe for target '/cygdrive/f/Program/code/workspace_idea/ijkplayer-android/android/ijkplayer/player-x86/src/main/obj/local/
x86/objs/ijkplayer/ff_cmdutils.o' failed
make: *** [/cygdrive/f/Program/code/workspace_idea/ijkplayer-android/android/ijkplayer/player-x86/src/main/obj/local/x86/objs/ijkplayer/ff_cmdutils.o] Error 1
/cygdrive/f/Program/code/workspace_idea/ijkplayer-android/android

**Comment by bbcallen** [comment]
Sorry, I don't maintain build under cygwin, because I don't take windows laptop with me all the time.

Seems there is some problems in making a symbol link.
