### ISSUE TITLE
 Unexpected FFmpeg Version

### ISSUE THREAD

**Issue by MarkBuster** [Bilibili/ijkplayer#3822]
集成了 TXLiteAVSDK_UGC  腾讯云小视频的SDK，在进行ijk播放视频的时候，报了  Unexpected FFmpeg Version 的提示。
pod 'TXLiteAVSDK_UGC', :podspec => 'http://pod-1252463788.cosgz.myqcloud.com/liteavsdkspec/TXLiteAVSDK_UGC.podspec'
![5c8c8aa634f173b120a514b4b507483a](https://user-images.githubusercontent.com/11814460/33662803-2d8fab06-dac8-11e7-99b7-33e8f93530d2.jpg)
，除了联系 腾讯方面进行sdk更改，我这边能做哪些处理嘛，我更新了最新的ijk，也还有这个提示

**Comment by MarkBuster** [comment]
没事了。。换了个优酷的 重命名SDK就好了。。。

**Comment by WSFeng** [comment]
@MarkBuster 你具体怎么处理的?
