### ISSUE TITLE
官方demo，ijkio:httphook:XXX播放正常，ijkio:androidio:XXX播放失败，报错：moov atom not found

### ISSUE THREAD

**Issue by shuqiao** [Bilibili/ijkplayer#3834]
问题：
ijkplayer官方Demo，播放本地mp4视频，ijkio:httphook:XXX播放正常，ijkio:androidio:XXX播放失败

猜测：是需要额外的协议支持吗？

代码：

 ((IjkMediaPlayer) mMediaPlayer).setAndroidIOCallback(new FileAndroidIO());
//         mUri = Uri.parse("ijkio:httphook:" + mUri.toString());
            mUri = Uri.parse("ijkio:androidio:" + mUri.toString());

报错：
12-11 12:00:12.461 14436-14436/tv.danmaku.ijk.media.example I/SurfaceView: surfaceCreated callback +, this = tv.danmaku.ijk.media.example.widget.media.SurfaceRenderView{22bce477 V.E..... ......ID 0,0-1080,1860}
12-11 12:00:12.464 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170829--001
12-11 12:00:12.464 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: ijk_version_info: k0.8.4-2-ge1d04bd8
12-11 12:00:12.465 14436-14436/tv.danmaku.ijk.media.example I/ANDROID_IO_TRACE: before , /storage/emulated/legacy/DCIM/Camera/VID_20171118_165029.mp4 , /storage/emulated/legacy/DCIM/Camera/VID_20171118_165029.mp4
12-11 12:00:12.465 14436-14436/tv.danmaku.ijk.media.example I/ANDROID_IO_TRACE: after , null , ijkio:androidio:/storage/emulated/legacy/DCIM/Camera/VID_20171118_165029.mp4
12-11 12:00:12.466 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: ===== versions =====
12-11 12:00:12.466 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: ijkplayer    : k0.8.4-2-ge1d04bd8
12-11 12:00:12.466 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170829--001
12-11 12:00:12.466 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: libavutil    : 55.58.100
12-11 12:00:12.466 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: libavcodec   : 57.89.100
12-11 12:00:12.466 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: libavformat  : 57.71.100
12-11 12:00:12.466 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: libswscale   : 4.6.100
12-11 12:00:12.466 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: libswresample: 2.7.100
12-11 12:00:12.466 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: ===== options =====
12-11 12:00:12.466 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : mediacodec                   = 0
12-11 12:00:12.466 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : opensles                     = 0
12-11 12:00:12.466 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : overlay-format               = 842225234
12-11 12:00:12.466 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : framedrop                    = 1
12-11 12:00:12.466 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : start-on-prepared            = 0
12-11 12:00:12.466 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : ijkapplication               = -1422023760
12-11 12:00:12.466 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : ijkiomanager                 = -1423553896
12-11 12:00:12.466 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : http-detect-range-support    = 0
12-11 12:00:12.466 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : androidio-inject-callback    = 6293058
12-11 12:00:12.466 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
12-11 12:00:12.466 14436-14436/tv.danmaku.ijk.media.example I/IJKMEDIA: ===================
12-11 12:00:12.467 14436-16996/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [16996] ff_msg_loop
12-11 12:00:12.469 14436-16997/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [16997] ff_vout
12-11 12:00:12.471 14436-16998/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [16998] ff_read
12-11 12:00:12.471 14436-16998/tv.danmaku.ijk.media.example E/IJKMEDIA: Value -2048888821134655488.000000 for parameter 'async' is not a valid set of 32bit integer flags
12-11 12:00:12.472 14436-16998/tv.danmaku.ijk.media.example I/ANDROID_IO_TRACE: open , url = /storage/emulated/legacy/DCIM/Camera/VID_20171118_165029.mp4
12-11 12:00:12.473 14436-16998/tv.danmaku.ijk.media.example I/ANDROID_IO_TRACE: read , size=32768 , bufferLength = 32768 , read=32768
12-11 12:00:12.474 14436-16998/tv.danmaku.ijk.media.example I/ANDROID_IO_TRACE: seek , offset=0, whence=65536
12-11 12:00:12.474 14436-16998/tv.danmaku.ijk.media.example E/IJKMEDIA: moov atom not found
12-11 12:00:12.474 14436-16998/tv.danmaku.ijk.media.example I/ANDROID_IO_TRACE: close
12-11 12:00:12.474 14436-16998/tv.danmaku.ijk.media.example E/IJKMEDIA: ijkio:androidio:/storage/emulated/legacy/DCIM/Camera/VID_20171118_165029.mp4: Invalid data found when processing input
12-11 12:00:12.474 14436-16998/tv.danmaku.ijk.media.example I/IJKMEDIA: ANDROID_IO_TRACE: read_thread goto fail , err = -1094995529
12-11 12:00:12.474 14436-16998/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [16998]
12-11 12:00:12.480 14436-14436/tv.danmaku.ijk.media.example I/SurfaceView: surfaceCreated callback -, this = tv.danmaku.ijk.media.example.widget.media.SurfaceRenderView{22bce477 V.E..... ......ID 0,0-1080,1860}
12-11 12:00:12.480 14436-14436/tv.danmaku.ijk.media.example I/SurfaceView: surfaceChanged -- format=4 w=1080 h=1860, this = tv.danmaku.ijk.media.example.widget.media.SurfaceRenderView{22bce477 V.E..... ......ID 0,0-1080,1860}
12-11 12:00:12.480 14436-14436/tv.danmaku.ijk.media.example I/SurfaceView: surfaceChanged callback +, this = tv.danmaku.ijk.media.example.widget.media.SurfaceRenderView{22bce477 V.E..... ......ID 0,0-1080,1860}
12-11 12:00:12.480 14436-14436/tv.danmaku.ijk.media.example I/SurfaceView: surfaceChanged callback -, this = tv.danmaku.ijk.media.example.widget.media.SurfaceRenderView{22bce477 V.E..... ......ID 0,0-1080,1860}
12-11 12:00:12.480 14436-14436/tv.danmaku.ijk.media.example I/SurfaceView: surfaceRedrawNeeded, this = tv.danmaku.ijk.media.example.widget.media.SurfaceRenderView{22bce477 V.E..... ......ID 0,0-1080,1860}
12-11 12:00:12.480 14436-14436/tv.danmaku.ijk.media.example I/SurfaceView: finishedDrawing, this = tv.danmaku.ijk.media.example.widget.media.SurfaceRenderView{22bce477 V.E..... ......ID 0,0-1080,1860}
12-11 12:00:12.495 14436-14436/tv.danmaku.ijk.media.example I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = tv.danmaku.ijk.media.example.widget.media.SurfaceRenderView{22bce477 V.E..... ......ID 0,0-1080,1860}
12-11 12:00:12.495 14436-14436/tv.danmaku.ijk.media.example I/SurfaceView: Changes: creating=false format=false size=false visible=false left=false top=false mUpdateWindowNeeded=true mReportDrawNeeded=true redrawNeeded=false forceSizeChanged=false mVisible=true mRequestedVisible=true, this = tv.danmaku.ijk.media.example.widget.media.SurfaceRenderView{22bce477 V.E..... ......ID 0,0-1080,1860}
12-11 12:00:12.495 14436-14436/tv.danmaku.ijk.media.example I/SurfaceView: Cur surface: Surface(name=null)/@0x399e8e5f, this = tv.danmaku.ijk.media.example.widget.media.SurfaceRenderView{22bce477 V.E..... ......ID 0,0-1080,1860}
12-11 12:00:12.499 14436-14436/tv.danmaku.ijk.media.example I/SurfaceView: New surface: Surface(name=null)/@0x145dc0ac, vis=true, frame=Rect(0, 60 - 1080, 1920), this = tv.danmaku.ijk.media.example.widget.media.SurfaceRenderView{22bce477 V.E..... ......ID 0,0-1080,1860}
12-11 12:00:12.499 14436-14436/tv.danmaku.ijk.media.example I/SurfaceView: surfaceRedrawNeeded, this = tv.danmaku.ijk.media.example.widget.media.SurfaceRenderView{22bce477 V.E..... ......ID 0,0-1080,1860}
12-11 12:00:12.499 14436-14436/tv.danmaku.ijk.media.example I/SurfaceView: finishedDrawing, this = tv.danmaku.ijk.media.example.widget.media.SurfaceRenderView{22bce477 V.E..... ......ID 0,0-1080,1860}
12-11 12:00:12.501 14436-14436/tv.danmaku.ijk.media.example I/SurfaceView: Punch a hole(dispatchDraw), w = 1080, h = 1860, this = tv.danmaku.ijk.media.example.widget.media.SurfaceRenderView{22bce477 V.E..... ........ 0,0-1080,1860}
12-11 12:00:12.525 14436-14436/tv.danmaku.ijk.media.example I/SurfaceView: updateWindow -- UPDATE_WINDOW_MSG, this = Handler (android.view.SurfaceView$1) {9c3895b}
12-11 12:00:12.525 14436-14436/tv.danmaku.ijk.media.example E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by shuqiao** [comment]
@raymond1012 帮忙看下这个问题可否 对androidio很感兴趣～感谢

**Comment by raymond1012** [comment]
需要接入android java部分代码

2017-12-11 12:05 GMT+08:00 Summer舒舒 <notifications@github.com>:

**Comment by shuqiao** [comment]
定义回调：类 FileAndroidIO.java

public class FileAndroidIO implements IAndroidIO {
    private static String TAG = "ANDROID_IO_TRACE";

    private RandomAccessFile file;

    public FileAndroidIO() {
    }

    @Override
    public int open(String url) throws IOException {
        Log.i(TAG, "open , url = " + url);

        this.file = new RandomAccessFile(new File(url), "r");
        return 1;
    }

    @Override
    public int read(byte[] buffer, int size) throws IOException {
        int read = file.read(buffer, 0, size);

        Log.i(TAG, "read , size=" + size + " , bufferLength = " + buffer.length + " , read=" + read);
        return read;
    }

    @Override
    public long seek(long offset, int whence) throws IOException {
        Log.i(TAG, "seek , offset=" + offset + ", whence=" + whence);

        file.seek(offset);
        return file.getFilePointer();
    }

    @Override
    public int close() throws IOException {
        Log.i(TAG, "close");

        file.close();
        file = null;
        return 1;
    }
}

设置回调： 类 IjkVideoView.java
    private void openVideo() {
        if (mUri == null || mSurfaceHolder == null) {
            // not ready for playback just yet, will try again later
            return;
        }
        // we shouldn't clear the target state, because somebody might have
        // called start() previously
        release(false);

        AudioManager am = (AudioManager) mAppContext.getSystemService(Context.AUDIO_SERVICE);
        am.requestAudioFocus(null, AudioManager.STREAM_MUSIC, AudioManager.AUDIOFOCUS_GAIN);

        try {
            mMediaPlayer = createPlayer(mSettings.getPlayer());

            // TODO: create SubtitleController in MediaPlayer, but we need
            // a context for the subtitle renderers
            final Context context = getContext();
            // REMOVED: SubtitleController

            // REMOVED: mAudioSession
            mMediaPlayer.setOnPreparedListener(mPreparedListener);
            mMediaPlayer.setOnVideoSizeChangedListener(mSizeChangedListener);
            mMediaPlayer.setOnCompletionListener(mCompletionListener);
            mMediaPlayer.setOnErrorListener(mErrorListener);
            mMediaPlayer.setOnInfoListener(mInfoListener);
            mMediaPlayer.setOnBufferingUpdateListener(mBufferingUpdateListener);
            mMediaPlayer.setOnSeekCompleteListener(mSeekCompleteListener);
            mMediaPlayer.setOnTimedTextListener(mOnTimedTextListener);
            mCurrentBufferPercentage = 0;

//-------------------------修改-------------------------
            ((IjkMediaPlayer) mMediaPlayer).setAndroidIOCallback(new FileAndroidIO());
//            mUri = Uri.parse("ijkio:httphook:" + mUri.toString());
            mUri = Uri.parse("ijkio:androidio:" + mUri.toString());
//-------------------------修改-------------------------

            String scheme = mUri.getScheme();
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M &&
                    mSettings.getUsingMediaDataSource() &&
                    (TextUtils.isEmpty(scheme) || scheme.equalsIgnoreCase("file"))) {
                IMediaDataSource dataSource = new FileMediaDataSource(new File(mUri.toString()));
                mMediaPlayer.setDataSource(dataSource);
            } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.ICE_CREAM_SANDWICH) {
                mMediaPlayer.setDataSource(mAppContext, mUri, mHeaders);
            } else {
                mMediaPlayer.setDataSource(mUri.toString());
            }
            bindSurfaceHolder(mMediaPlayer, mSurfaceHolder);
            mMediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
            mMediaPlayer.setScreenOnWhilePlaying(true);
            mPrepareStartTime = System.currentTimeMillis();
            mMediaPlayer.prepareAsync();
            if (mHudViewHolder != null)
                mHudViewHolder.setMediaPlayer(mMediaPlayer);

            // REMOVED: mPendingSubtitleTracks

            // we don't set the target state here either, but preserve the
            // target state that was there before.
            mCurrentState = STATE_PREPARING;
            attachMediaController();
        } catch (IOException ex) {
            Log.w(TAG, "Unable to open content: " + mUri, ex);
            mCurrentState = STATE_ERROR;
            mTargetState = STATE_ERROR;
            mErrorListener.onError(mMediaPlayer, MediaPlayer.MEDIA_ERROR_UNKNOWN, 0);
        } catch (IllegalArgumentException ex) {
            Log.w(TAG, "Unable to open content: " + mUri, ex);
            mCurrentState = STATE_ERROR;
            mTargetState = STATE_ERROR;
            mErrorListener.onError(mMediaPlayer, MediaPlayer.MEDIA_ERROR_UNKNOWN, 0);
        } finally {
            // REMOVED: mPendingSubtitleTracks.clear();
        }
    }

@raymond1012 这是我的修改 有错敬请指正～

**Comment by raymond1012** [comment]
没有问题

2017-12-11 14:48 GMT+08:00 Summer舒舒 <notifications@github.com>:

**Comment by shuqiao** [comment]
感谢你的回复～

代码无其他修改 ，已测试多个mp4本地视频，均是ijkio:httphook:XXX播放正常，ijkio:androidio:XXX播放失败，出错log如上。

这是测试视频之一：
[测试视频](http://p3.niceimg.net/upload/video/2017/11/21/5384e2d44870b2d92af1cb62dd52918b)

希望你看下是否有问题～感谢

**Comment by raymond1012** [comment]
由于你播放的是mp4，所以需要模仿http.c 中实现不同的 whence，最主要的是要提供filesize

在 2017年12月11日 下午4:01，Summer舒舒 <notifications@github.com>写道：

**Comment by shuqiao** [comment]
感谢你的回复～

根据你的提示，我昨晚重新check了代码，是我忽略了在whence=AVSEEK_SIZE时需要返回filesize。
现在问题已解决可以正常播放视频了，很开心，再次感谢你😄～

@raymond1012
