### ISSUE TITLE
这个错误该怎么处理,Couldn't open file on client side, trying server side

### ISSUE THREAD

**Issue by luckyer** [Bilibili/ijkplayer#3835]
12-12 09:47:40.807  2964  2964 D IJKMEDIA: IjkMediaPlayer_native_init
12-12 09:47:40.808  2964  2964 D IJKMEDIA: IjkMediaPlayer_native_setup
12-12 09:47:40.808  2964  2964 I IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170829--001
12-12 09:47:40.808  2964  2964 I IJKMEDIA: ijk_version_info: k0.8.4-2-ge1d04bd
12-12 09:47:40.808  2964  2964 D IJKMEDIA: ffpipeline_create_from_android()
12-12 09:47:40.808  2964  2964 D IJKMEDIA: ijkmp_set_inject_opaque(0x1004ee)
12-12 09:47:40.808  2964  2964 D IJKMEDIA: ijkmp_set_inject_opaque()=void
12-12 09:47:40.808  2964  2964 D IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x1004ee)
12-12 09:47:40.809  2964  2964 D IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
12-12 09:47:40.809  2964  2964 D IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
12-12 09:47:40.809  2964  2964 D IJKMEDIA: ffpipeline_set_mediacodec_select_callback
12-12 09:47:40.809  2964  2964 D IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
12-12 09:47:40.809  2964  2964 D IJKMEDIA: IjkMediaPlayer_native_setLogLevel(3)
12-12 09:47:40.809  2964  2964 D IJKMEDIA: moncleanup
12-12 09:47:40.809  2964  2964 D IJKMEDIA: IjkMediaPlayer_setOptionLong
12-12 09:47:40.810  2964  2964 D IJKMEDIA: IjkMediaPlayer_setOptionLong
12-12 09:47:40.810  2964  2964 D IJKMEDIA: IjkMediaPlayer_setOptionLong
12-12 09:47:40.810  2964  2964 D IJKMEDIA: IjkMediaPlayer_setOptionLong
12-12 09:47:40.810  2964  2964 D IJKMEDIA: IjkMediaPlayer_setOptionLong
12-12 09:47:40.810  2964  2964 D IJKMEDIA: IjkMediaPlayer_setOptionLong
12-12 09:47:40.810  2964  2964 D IJKMEDIA: IjkMediaPlayer_setOptionLong
12-12 09:47:40.810  2964  2964 D tv.danmaku.ijk.media.player.IjkMediaPlayer: Couldn't open file on client side, trying server side
12-12 09:47:40.810  2964  2964 D IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
12-12 09:47:40.810  2964  2964 V IJKMEDIA: setDataSource: path http://haokan.baidu.com/v?pd=wisenatural&vid=7761278051937992817
12-12 09:47:40.810  2964  2964 D IJKMEDIA: ijkmp_set_data_source(url="http://haokan.baidu.com/v?pd=wisenatural&vid=7761278051937992817")
12-12 09:47:40.810  2964  2964 D IJKMEDIA: ijkmp_set_data_source(url="http://haokan.baidu.com/v?pd=wisenatural&vid=7761278051937992817")=0
12-12 09:47:40.810  2964  2964 D IJKMEDIA: IjkMediaPlayer_setVideoSurface
12-12 09:47:40.810  2964  2964 D IJKMEDIA: ijkmp_set_android_surface(surface=0xffc22780)
12-12 09:47:40.810  2964  2964 D IJKMEDIA: ffpipeline_set_surface()
12-12 09:47:40.810  2964  2964 D IJKMEDIA: ijkmp_set_android_surface(surface=0xffc22780)=void
12-12 09:47:40.810  2964  2964 D IJKMEDIA: IjkMediaPlayer_prepareAsync
12-12 09:47:40.810  2964  2964 D IJKMEDIA: ijkmp_prepare_async()
12-12 09:47:40.810  2964  2964 I IJKMEDIA: ===== versions =====
12-12 09:47:40.810  2964  2964 I IJKMEDIA: ijkplayer    : k0.8.4-2-ge1d04bd
12-12 09:47:40.810  2964  2964 I IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170829--001
12-12 09:47:40.810  2964  2964 I IJKMEDIA: libavutil    : 55.58.100
12-12 09:47:40.810  2964  2997 I IJKMEDIA: SDL_RunThread: [2997] ff_msg_loop
12-12 09:47:40.811  2964  2964 I IJKMEDIA: libavcodec   : 57.89.100
12-12 09:47:40.811  2964  2997 D IJKMEDIA: message_loop
12-12 09:47:40.811  2964  2964 I IJKMEDIA: libavformat  : 57.71.100
12-12 09:47:40.811  2964  2964 I IJKMEDIA: libswscale   : 4.6.100
12-12 09:47:40.811  2964  2964 I IJKMEDIA: libswresample: 2.7.100
12-12 09:47:40.811  2964  2964 I IJKMEDIA: ===== options =====
12-12 09:47:40.811  2964  2964 I IJKMEDIA: player-opts : mediacodec                   = 0
12-12 09:47:40.811  2964  2964 I IJKMEDIA: player-opts : opensles                     = 0
12-12 09:47:40.811  2964  2964 I IJKMEDIA: player-opts : overlay-format               = 842225234
12-12 09:47:40.811  2964  2964 I IJKMEDIA: player-opts : framedrop                    = 1
12-12 09:47:40.811  2964  2964 I IJKMEDIA: player-opts : start-on-prepared            = 0
12-12 09:47:40.811  2964  2964 I IJKMEDIA: format-opts : ijkapplication               = -1427301392
12-12 09:47:40.811  2964  2964 I IJKMEDIA: format-opts : ijkiomanager                 = -1427301304
12-12 09:47:40.811  2964  2964 I IJKMEDIA: format-opts : http-detect-range-support    = 0
12-12 09:47:40.811  2964  2964 I IJKMEDIA: codec-opts  : skip_loop_filter             = 48
12-12 09:47:40.811  2964  2964 I IJKMEDIA: ===================
12-12 09:47:40.812  2964  2997 D IJKMEDIA: FFP_MSG_FLUSH:
12-12 09:47:40.813  2964  2998 I IJKMEDIA: SDL_RunThread: [2998] ff_vout
12-12 09:47:40.813  2964  2964 D IJKMEDIA: ijkmp_prepare_async()=0
12-12 09:47:40.813  2964  2999 I IJKMEDIA: SDL_RunThread: [2999] ff_read
12-12 09:47:40.813  2964  2999 D IJKMEDIA: Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'
12-12 09:47:40.815  2964  2999 I tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
12-12 09:47:40.843  2964  2999 I tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
12-12 09:47:40.851  2964  2999 I tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
12-12 09:47:40.851  2964  2999 I IJKMEDIA: Add dns cache hostname = haokan.baidu.com, ip = 180.97.36.46
12-12 09:47:40.851  2964  2999 D IJKMEDIA: request: GET /v?pd=wisenatural&vid=7761278051937992817 HTTP/1.1
12-12 09:47:40.851  2964  2999 D IJKMEDIA: User-Agent: Lavf/57.71.100
12-12 09:47:40.851  2964  2999 D IJKMEDIA: Accept: */*
12-12 09:47:40.851  2964  2999 D IJKMEDIA: Range: bytes=0-
12-12 09:47:40.851  2964  2999 D IJKMEDIA: Connection: close
12-12 09:47:40.851  2964  2999 D IJKMEDIA: Host: haokan.baidu.com
12-12 09:47:40.851  2964  2999 D IJKMEDIA: Icy-MetaData: 1
12-12 09:47:40.851  2964  2999 D IJKMEDIA: 
12-12 09:47:40.851  2964  2999 D IJKMEDIA: 
12-12 09:47:40.866  1848  1867 I ActivityManager: Displayed tv.danmaku.ijk.media.example/.activities.FileExplorerActivity: +384ms
12-12 09:47:41.391  2964  2999 I tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
12-12 09:47:41.430  2964  2999 D IJKMEDIA: Statistics: 52120 bytes read, 0 seeks
12-12 09:47:41.430  2964  2999 E IJKMEDIA: http://haokan.baidu.com/v?pd=wisenatural&vid=7761278051937992817: Invalid data found when processing input
12-12 09:47:41.430  2964  2999 I IJKMEDIA: SDL_JNI_DetachThreadEnv: [2999]
12-12 09:47:41.430  2964  2997 D IJKMEDIA: FFP_MSG_ERROR: 0
12-12 09:47:41.431  2964  2964 E tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
12-12 09:47:41.431  2964  2964 D IjkVideoView: Error: -10000,0
12-12 09:47:41.438  2964  2964 I AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
12-12 09:47:41.483  1337  1491 E BufferQueueProducer: [tv.danmaku.ijk.media.example/tv.danmaku.ijk.media.example.activities.FileExplorerActivity] connect(P): already connected (cur=1 req=1)
12-12 09:47:41.483  2964  2983 D mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000

**Comment by luckyer** [comment]
换了个视频就好了,看来支持的还是不够呢.

**Comment by ushergo** [comment]
我也出现了这个问题：

**Comment by ushergo** [comment]
D/tv.danmaku.ijk.media.player.IjkMediaPlayer: Couldn't open file on client side, trying server side
D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders

**Comment by ushergo** [comment]
W/IJKMEDIA: Could not find codec parameters for stream 0 (Video: hevc, 1 reference frame, none): unspecified size
    Consider increasing the value for the 'analyzeduration' and 'probesize' options
W/IJKMEDIA: Could not find codec parameters for stream 1 (Audio: pcm_alaw, 8000 Hz, 1 channels, 64 kb/s): unspecified sample format
    Consider increasing the value for the 'analyzeduration' and 'probesize' options
