### ISSUE TITLE
相同配置IJKMediaFrameworkWithSSL 比 IJKMediaFramework 小了很多

### ISSUE THREAD

**Issue by appjar** [Bilibili/ijkplayer#3836]
相同的配置，为何编译出来的IJKMediaFrameworkWithSSL.framework 比 IJKMediaFramework.framework 小了很多？前者只有26MB 后者超过100MB。

**Comment by toss156** [comment]
IJKMediaFrameworkWithSSL.framework 是动态库， IJKMediaFramework.framework是静态库

**Comment by appjar** [comment]
@toss156 所言极是，多谢！
