### ISSUE TITLE
android ijkplayer播放HLS H265格式视频会有花屏

### ISSUE THREAD

**Issue by harlanc** [Bilibili/ijkplayer#3839]
播放H265 的 mp4文件是好的，但是把mp4切片成HLS ts后播放就会有花屏的现象。不知道有没有人遇到过这个问题？如何解决？

**Comment by Android4MediaPlayer** [comment]
把视频地址发下才好定位

**Comment by harlanc** [comment]
@Android4MediaPlayer https://pan.baidu.com/s/1dEKJTYh

**Comment by Android4MediaPlayer** [comment]
@harlanc 首次播放花屏还是什么情况下

**Comment by harlanc** [comment]
@Android4MediaPlayer  每次都能重现

**Comment by harlanc** [comment]
@Android4MediaPlayer 请问这是bug么？这部分的代码大致范围在什么地方呢？

**Comment by Android4MediaPlayer** [comment]
我用了你的测试片源，没有出现花屏，是跟机型有关系吗

**Comment by harlanc** [comment]
你是用的ijkplayer-example测试的么？settings是咋选择的？我的机器是小米5

**Comment by Android4MediaPlayer** [comment]
ijk mediacodec

**Comment by Android4MediaPlayer** [comment]
@harlanc yes

**Comment by harlanc** [comment]
@Android4MediaPlayer module-lite.sh中  原来是因为hevc的选项没加全。
