### ISSUE TITLE
iOS,集成ijk后archive出错

### ISSUE THREAD

**Issue by decemberLi** [Bilibili/ijkplayer#384]
archive的时候，submit to App Store按钮是灰色的。程序也被分配到了other app里面去了。不知道有人遇到过没有。when I archive my app, the "submit to app store"button is unusable.

**Comment by Zard1096** [comment]
Check which scheme did you archive.
It likely that you archive scheme IJKMediaPlayer(just a lib).

**Comment by decemberLi** [comment]
i archive my app,not IJKMediaPlayer (the lib).I slove it as use lib not use the project。

**Comment by bbcallen** [comment]
Can you archive IJKMediaDemo ?
