### ISSUE TITLE
build with ndk 16.1.4479499

### ISSUE THREAD

**Issue by Leifzhang** [Bilibili/ijkplayer#3840]
ndk 版本 16.1.4479499  报错
ANDROID_NDK=/Users/zhangyang/Library/Android/sdk/ndk-bundle
IJK_NDK_REL=16.1.4479499
You need the NDKr10e or later

**Comment by Android4MediaPlayer** [comment]
目前只最高支持到r14

**Comment by Leifzhang** [comment]
我已经降低了ndk版本 进行编译了

**Comment by HaobinXu** [comment]
怎么降低ndk版本？

**Comment by Leifzhang** [comment]
谷歌官网重新下载一个低版本  替换配置文件就好了

**Comment by HaobinXu** [comment]
嗯，成功了，谢谢
