### ISSUE TITLE
User agent

### ISSUE THREAD

**Issue by MiriSy** [Bilibili/ijkplayer#3846]
how to put user agent when play video stream

**Comment by Android4MediaPlayer** [comment]
which platform ? setting option for user_agent

**Comment by MiriSy** [comment]
you mean wich player ?  i want in auto mode

**Comment by MiriSy** [comment]
in android platform

**Comment by Android4MediaPlayer** [comment]
@MiriSy eg:String mUserAgent = "ijkplayer";
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "user_agent", 0);

**Comment by MiriSy** [comment]
Android4MediaPlayer where to write that in player activity or ijkVideoView or where ?

**Comment by yrom** [comment]
You can write it on [`IjkVideoView#createPlayer`](https://github.com/Bilibili/ijkplayer/blob/e1d04bd8e14fae6077510da799fd3573c45e816a/android/ijkplayer/ijkplayer-example/src/main/java/tv/danmaku/ijk/media/example/widget/media/IjkVideoView.java#L1019) of sample project.

```
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "user_agent", "ijkplayer/1.0");
```
