### ISSUE TITLE
getCurrentPosition : Android, get wrong current position after pause/play

### ISSUE THREAD

**Issue by xksds** [Bilibili/ijkplayer#3848]
Dis:
      We get play current position use the **SAME** thread normally, but some time UI thread invoke this API get wrong value, position jumped forward. After debug this issue, I found that updated **WRONG clock** during restart playback from pause.
     I fixed this by modify ffplayer and passed self-test, I'm **NOT guarantee** this works perfect but just works fine for me.

File : 
     **ff_ffplay.c**
Func : 
     **static void stream_toggle_pause_l(FFPlayer *ffp, int pause_on)***

        // We need set correct clock.
        bool bHaveVideo = false;
        if (NULL != is->ic) {
            for (int i = 0; i < is->ic->nb_streams; i ++) {
                if (NULL != is->ic->streams[i] && NULL != is->ic->streams[i]->codecpar && AVMEDIA_TYPE_VIDEO == is->ic->streams[i]->codecpar->codec_type) {
                    bHaveVideo = true;
                }
            }
        }

        if (true == bHaveVideo) {
            set_clock(&is->vidclk, get_clock(&is->vidclk), is->vidclk.serial);
        } else
            set_clock(&is->audclk, get_clock(&is->audclk), is->audclk.serial);
        //set_clock(&is->vidclk, get_clock(&is->vidclk), is->vidclk.serial);

**Comment by gaokun** [comment]
我也遇到了同样的问题, 找了半天, 最后查到是这个函数的返回的数据不对.
pause了后, 感觉时间还在走, 再play, 获取的position不对, 但再次pause & play就正常了.
很不稳定.

按照你的方法来fix, 是需要编译ffplayer再放到项目里吗?  
不好意思我帮项目解决问题, 不是做android的, 具体操作不太懂.

望指点
Ken

**Comment by xksds** [comment]
@gaokun 
需要从新编译，修改后按照ijk的编译步骤执行就可以。

**Comment by gaokun** [comment]
@xksds 十分感谢

**Comment by VijayBest** [comment]
@xksds This solution is not working for me.
