### ISSUE TITLE
How do I get the framework to update when I change its code?

### ISSUE THREAD

**Issue by awfulcode** [Bilibili/ijkplayer#385]
I'm trying to understand when does it call IJKSDLAudioQueueController and when it calls IJKSDLAudioUnitController, so I added some NSLog entries to those classes, but all changes I make to the framework aren't reflected in the built app. Same thing goes for trying to put breakpoints in it. Do you know what I'm doing wrong here?

**Comment by Zard1096** [comment]
Do you clean the framework build and rebuild it(for logs)?
If you build framework and include it,the breakpoints are useless.
You shuould add the project which you build the framework to your test project and include this framework(in build phases).When you compile program it will be first compile ijk then compile your program,and the breakpoints will enable.

**Comment by bbcallen** [comment]
IJKSDLAudioUnitController is an alternative of IJKSDLAudioQueueController.
They can't be switched at runtime.
IJKSDLAudioQueueController is being used currently.

**Comment by awfulcode** [comment]
Cool. Thanks, guys.
