### ISSUE TITLE
0.8.4这个版本还需要自己去配置支持udp:// 吗？  我是直接compile的。

### ISSUE THREAD

**Issue by Lijinqi** [Bilibili/ijkplayer#3852]
播放udp://的时候会提示 E/IJKMEDIA: udp://<ip>:28888: Immediate exit requested

**Comment by zhuwei** [comment]
请问你是怎么解决的。。
我在module-lite.sh加了
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=h264"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=udp"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=rtp"
然后udp://:8888没有反应呢，发送端用的ffmpeg命令。。

**Comment by Lijinqi** [comment]
应该不需要改.sh文件   "udp://@:28888"  没反应一般都是播放的流有问题

**Comment by zhuwei** [comment]
@Lijinqi 不应该是流问题。我用qgroundcontrol和vlc客户端都可以播放。

**Comment by zhuwei** [comment]
@Lijinqi 你的解决了？能播放吗？

**Comment by Lijinqi** [comment]
@zhuwei 你可以播放本地视频，或者用vlc 串流试试能不能播放。vlc  udp 串流的地址：你播放端的ip + 端口。
然后播放端URI：udp://:推流ip:port
排除一下问题先  我们的问题可能不是一样的。我用上面的方法是可以播放的。 也可能是你的流少了点信息，导致解析不出来。

**Comment by Lijinqi** [comment]
@zhuwei 无法播放这个我也不清楚啥情况。  延迟的话可能你需要去修改 c文件 ，再自己编译。我之前反正不管怎么设置  延迟还是有。

**Comment by zhuwei** [comment]
怎么修改c能把延迟降到2-300ms?

**Comment by zhuwei** [comment]
我晕，搞错了，我是用vlckit播放成功

**Comment by roger2380** [comment]
> @Lijinqi 播放本地和rtsp都没问题。 udp://:推流ip:port这个无法播放，没办法我就播放sdp文件，结果可以播放了。但是延迟3秒，局域网。不能接受啊。 然而设置了[mediaDictionary setObject:@"100" forKey:@"network-caching"];，结果画面完全不动。。

sdp如何播放，sdp文件放哪里
