### ISSUE TITLE
内存一直无法释放

### ISSUE THREAD

**Issue by baiyongbing** [Bilibili/ijkplayer#3858]

**Comment by baiyongbing** [comment]
每次开启一个直播退出后内存一直存在
        [self.livePlayer stop];
        [self.livePlayer didShutdown];
        [self.livePlayer.view removeFromSuperview];
        self.livePlayer = nil;
这样没有退出吗

**Comment by raymond1012** [comment]
need call shutdown

**Comment by maowentao0416** [comment]
我是调用stop release，IjkMediaPlayer_release
但是native层的内存还是在一直增加
