### ISSUE TITLE
Setting overlay-format to SDL_FCC_I420

### ISSUE THREAD

**Issue by Yair0007** [Bilibili/ijkplayer#3860]
I cant seem to find a reference to SDL_FCC_I420 (using SDL_FCC_YV12 instead).

Whats the integer value for I420 ?

Thanks

**Comment by moeyard** [comment]
But I found SDL_FCC_I420 is defined in  [https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijksdl/ijksdl_fourcc.h](url) , or want to know if  supported ?
