### ISSUE TITLE
IjkMediaPlayer.setAndroidIOCallback  这个方法设置之后没有回调；

### ISSUE THREAD

**Issue by SquareLeo** [Bilibili/ijkplayer#3866]
RT，这个方法设置之后要设置其他参数才能获取回调数据么？

然后在回调的方法中public int read(byte[] bytes, int i) throws IOException
这里面的bytes数据是H264的数据，还是YUV420p或者YUV420sp 数据，或者其他的数据

谢谢~~

**Comment by raymond1012** [comment]
这个是io的回调，即取代默认的http，走java自定义的io
