### ISSUE TITLE
J4A_loadClass__J4AC_MediaCodec 在哪里调用的 ？怎么调用的？

### ISSUE THREAD

**Issue by PengBoShi** [Bilibili/ijkplayer#3873]
J4A_loadClass__J4AC_MediaCodec 在哪里调用的 ？怎么调用的？

**Comment by oncealong** [comment]
look here: https://www.jianshu.com/p/84151c863c72
Ijksdl_android_jni.c
JNI_OnLoad(JavaVM *vm, void *reserved)
    |--J4A_LoadAll__catchAll(env);
