### ISSUE TITLE
why can't  iphone5s  play h265-videostream？

### ISSUE THREAD

**Issue by bigfi2000** [Bilibili/ijkplayer#3874]
I did compiled code with the module-lite- hevc.sh, and then play the h265 video stream with  demo, and I find that it doesn't show up，Has anyone encountered this problem? How to solve it?

**Comment by bigfi2000** [comment]
我用module-lite-hevc.sh脚本编译的ijkplayer，但是在ios模拟器或iphone5s真机上都播放不出h265视频流，声音好像是可以解码并播放，这是为什么呢?请大家指教，不甚感激。下面是打印的日志：

===== custom modules begin =====
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff3.3--ijk0.8.0--20170829--001
ijk_version_info: 
ijkmp_set_inject_opaque(0x60000000cd80)
ijkmp_set_inject_opaque()=void
ijkmp_set_ijkio_inject_opaque(0x60000000cd80)
ijkmp_set_ijkio_inject_opaque()=void
2017-12-26 15:34:53.139 IJKMediaDemo[869:443145] OK setup GL
ijkmp_ios_set_view(glView=0x7fd963c2f410)
ijkmp_ios_set_view(glView=0x7fd963c2f410)=void
2017-12-26 15:34:53.144 IJKMediaDemo[869:443145] invalidateRenderBuffer
2017-12-26 15:34:53.145 IJKMediaDemo[869:443256] IJKSDLGLView: setupDisplay not ready
ijkmp_set_data_source(url="rtsp://192.168.1.23/1")
ijkmp_set_data_source(url="rtsp://192.168.1.23/1")=0
ijkmp_prepare_async()
remove 'timeout' option for rtmp.
===== versions =====
ijkplayer    : 
FFmpeg       : ff3.3--ijk0.8.0--20170829--001
libavutil    : 55.58.100
libavcodec   : 57.89.100
libavformat  : 57.71.100
libswscale   : 4.6.100
libswresample: 2.7.100
===== options =====
player-opts : max_cached_duration          = 1000
player-opts : overlay-format               = fcc-_es2
player-opts : infbuf                       = 1
player-opts : videotoolbox                 = 0
player-opts : videotoolbox-max-frame-width = 960
player-opts : video-pictq-size             = 3
player-opts : max-fps                      = 30
player-opts : framedrop                    = 0
player-opts : packet-buffering             = 0
player-opts : start-on-prepared            = 1
format-opts : ijkapplication               = 140571658262048
format-opts : ijkiomanager                 = 140571658350416
format-opts : rtsp_transport               = tcp
format-opts : auto_convert                 = 0
format-opts : flush_packets                = 1
format-opts : safe                         = 0
format-opts : analyzeduration              = 50000
format-opts : user-agent                   = ijkplayer
format-opts : reconnect                    = 1
format-opts : probsize                     = 10240
codec-opts  : skip_frame                   = 0
codec-opts  : skip_loop_filter             = 0
===================
ijkmp_prepare_async()=0
remove 'timeout' option for rtmp.
No default whitelist set
Add dns cache hostname = 192.168.1.23, ip = 
SDP:
v=0
o=CameraStreaming 3132335948 1236907222000 IN IP4 192.168.1.23
s=10
c=IN IP4 0.0.0.0
t=0 0
a=control:*
m=video 0 RTP/AVP 96
a=control:trackID=0
a=rtpmap:96 H265/90000
a=fmtp:96 sprop-vps=QAEMAf//AWAAAAMAsAAAAwAAAwB7rAk=;sprop-sps=QgEBAWAAAAMAsAAAAwAAAwB7oAPAgBDlja5JMvk=;sprop-pps=RAHA8vA8kA==
m=audio 0 RTP/AVP 97
a=control:trackID=1
a=rtpmap:97 MPEG4-GENERIC/44100/2
a=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1210

video codec set to: hevc
audio codec set to: aac
audio samplerate set to: 44100
audio channels set to: 2
setting jitter buffer size to 0
setting jitter buffer size to 0
hello state=0
2017-12-26 15:34:53.171 IJKMediaDemo[869:443145] invalidateRenderBuffer
2017-12-26 15:34:53.171 IJKMediaDemo[869:443256] IJKSDLGLView: setupDisplay not ready
Option ijkapplication not found.
nal_unit_type: 32(VPS), nuh_layer_id: 0, temporal_id: 0
nal_unit_type: 33(SPS), nuh_layer_id: 0, temporal_id: 0
nal_unit_type: 34(PPS), nuh_layer_id: 0, temporal_id: 0
Decoding VPS
Main profile bitstream
Decoding SPS
Main profile bitstream
Decoding PPS
2017-12-26 15:34:53.187 IJKMediaDemo[869:443145] FFP_MSG_OPEN_INPUT:
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
max_analyze_duration 50000 reached at 69660 microseconds st:1
max_frame_duration: 10.000
Input #0, rtsp, from 'rtsp://192.168.1.23/1':
  Metadata:
    title           : 10
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0, 0, 1/90000: Video: hevc (Main), 1 reference frame, yuv420p(tv), 1920x1080, 0/1, 90k tbr, 90k tbn, 90k tbc
    Stream #0:1, 5, 1/44100: Audio: aac (LC), 44100 Hz, stereo, fltp
2017-12-26 15:34:53.495 IJKMediaDemo[869:443145] FFP_MSG_FIND_STREAM_INFO:
aout_open_audio()
AudioCodec: avcodec, aac
aout_pause_audio(0)
detected 4 logical cores
nal_unit_type: 32(VPS), nuh_layer_id: 0, temporal_id: 0
nal_unit_type: 33(SPS), nuh_layer_id: 0, temporal_id: 0
nal_unit_type: 34(PPS), nuh_layer_id: 0, temporal_id: 0
Decoding VPS
Main profile bitstream
Decoding SPS
Main profile bitstream
Decoding PPS
VideoCodec: avcodec, hevc
fps: 90000.000000 (normal)
2017-12-26 15:34:53.788 IJKMediaDemo[869:443145] FFP_MSG_VIDEO_DECODER_OPEN: false
ijkmp_get_msg: FFP_MSG_PREPARED
2017-12-26 15:34:53.789 IJKMediaDemo[869:443145] FFP_MSG_COMPONENT_OPEN:
2017-12-26 15:34:53.789 IJKMediaDemo[869:443145] FFP_MSG_VIDEO_SIZE_CHANGED: 1920, 1080
2017-12-26 15:34:53.789 IJKMediaDemo[869:443145] FFP_MSG_SAR_CHANGED: 0, 1
2017-12-26 15:34:53.790 IJKMediaDemo[869:443145] FFP_MSG_PREPARED:
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
ijkmp_set_playback_rate(1.000000)
Playback rate: 1.000000
ijkmp_set_playback_rate()=void
ijkmp_set_playback_volume(1.000000)
ijkmp_set_playback_volume()=void
2017-12-26 15:34:53.790 IJKMediaDemo[869:443145] mediaIsPreparedToPlayDidChange
2017-12-26 15:34:53.790 IJKMediaDemo[869:443145] loadStateDidChange: IJKMPMovieLoadStatePlaythroughOK: 3
2017-12-26 15:34:53.790 IJKMediaDemo[869:443145] IJKMPMoviePlayBackStateDidChange 1: playing
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
aout_close_audio()
aout_set_volume()
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
Using fltp internally between filters
avcodec/Audio: first frame decoded
2017-12-26 15:34:55.839 IJKMediaDemo[869:443145] FFP_MSG_AUDIO_DECODED_START:
2017-12-26 15:34:55.839 IJKMediaDemo[869:443145] FFP_MSG_AUDIO_RENDERING_START:
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
CSeq 5 expected, 0 received.
ijkmp_stop()
aout_pause_audio(1)
ijkmp_stop()=0
ijkmp_shutdown_l()
aout_pause_audio(1)
aout_pause_audio(1)
convert image convert_frame_count = 0
wait for read_tid
Decoding VPS
Main profile bitstream
Decoding SPS
Main profile bitstream
Decoding PPS
aout_close_audio()
wait for video_refresh_tid
ijkmp_shutdown_l()=void
ijkmp_set_inject_opaque(0x0)
ijkmp_set_inject_opaque()=void
ijkmp_set_ijkio_inject_opaque(0x0)
ijkmp_set_ijkio_inject_opaque()=void
ijkmp_dec_ref(): ref=0
ijkmp_shutdown_l()
ijkmp_shutdown_l()=void
aout_close_audio()

**Comment by PengBoShi** [comment]
其他的真机是可以的 ？

**Comment by moeyard** [comment]
可以播放h265 的 文件吗? 看log已经识别出h265了, 怀疑ios 下 rtsp 有问题.

**Comment by bigfi2000** [comment]
其他的真机没试过啊 我就用了5s测的，你有碰到过这种问题吗 感谢！ @PengBoShi

**Comment by bigfi2000** [comment]
@moeyard 我去抓个文件先试试，谢谢提醒！

**Comment by bigfi2000** [comment]
不是源码的问题，是我的网络问题，晕死了，谢谢大家提醒

**Comment by zxb1094** [comment]
@bigfi2000 请问下你是怎么设置的才支持rtsp流播放的？我按照ijk0.7.6设置module-lite.sh里面的东西不能支持rtsp流播放

**Comment by bigfi2000** [comment]
@zxb1094 打开moudule-lite.sh，加入
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=rtp" 
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=tcp" 
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=rtsp" 
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=sdp" 
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=rtp"

然后
rm module.sh
ln -s module-lite.sh module.sh

**Comment by zxb1094** [comment]
@bigfi2000 兄弟按照你的设置  还是卡在下面那里
2017-12-27 09:51:28.794201 IJKMediaDemo[12418:2178324] [DYMTLInitPlatform] platform initialization successful
===== custom modules begin =====
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff3.3--ijk0.8.0--20170829--001
ijk_version_info: k0.8.4
ijkmp_set_inject_opaque(0x170200be0)
ijkmp_set_inject_opaque()=void
ijkmp_set_ijkio_inject_opaque(0x170200be0)
ijkmp_set_ijkio_inject_opaque()=void
2017-12-27 09:51:32.447051 IJKMediaDemo[12418:2178271] OK setup GL

ijkmp_ios_set_view(glView=0x11bd546f0)
ijkmp_ios_set_view(glView=0x11bd546f0)=void
2017-12-27 09:51:32.471525 IJKMediaDemo[12418:2178271] invalidateRenderBuffer

ijkmp_set_data_source(url="rtsp://admin:1234567a@192.168.7.99:554/h264/ch1/main")
ijkmp_set_data_source(url="rtsp://admin:1234567a@192.168.7.99:554/h264/ch1/main")=0
ijkmp_prepare_async()
remove 'timeout' option for rtmp.
===== versions =====
ijkplayer    : k0.8.4
FFmpeg       : ff3.3--ijk0.8.0--20170829--001
libavutil    : 55.58.100
libavcodec   : 57.89.100
libavformat  : 57.71.100
2017-12-27 09:51:32.477532 IJKMediaDemo[12418:2178322] IJKSDLGLView: setupDisplay not ready

libswscale   : 4.6.100
libswresample: 2.7.100
===== options =====
player-opts : min-frames                   = 3
player-opts : overlay-format               = 842094169
player-opts : packet-buffering             = 0
player-opts : videotoolbox                 = 1
player-opts : fps                          = 30
player-opts : video-pictq-size             = 3
player-opts : videotoolbox-max-frame-width = 960
player-opts : max-fps                      = 0
player-opts : framedrop                    = 60
player-opts : start-on-prepared            = 1
format-opts : ijkapplication               = 4762640512
format-opts : ijkiomanager                 = 4762826544
format-opts : fflags                       = nobuffer
format-opts : auto_convert                 = 0
format-opts : max-buffer-size              = 1024
format-opts : safe                         = 0
format-opts : analyzeduration              = 2000000
format-opts : user-agent                   = ijkplayer
format-opts : reconnect                    = 1
format-opts : probsize                     = 4096
codec-opts  : skip_loop_filter             = 48
===================
ijkmp_prepare_async()=0
remove 'timeout' option for rtmp.
No default whitelist set
2017-12-27 09:51:32.499367 IJKMediaDemo[12418:2178271] invalidateRenderBuffer

2017-12-27 09:51:32.499602 IJKMediaDemo[12418:2178321] IJKSDLGLView: setupDisplay not ready

Add dns cache hostname = 192.168.7.99, ip = 
SDP:
v=0

o=- 1514368156103049 1514368156103049 IN IP4 192.168.7.99

s=Media Presentation

e=NONE

b=AS:5100

t=0 0

a=control:rtsp://192.168.7.99:554/h264/ch1/main/

m=video 0 RTP/AVP 96

c=IN IP4 0.0.0.0

b=AS:5000

a=recvonly

a=x-dimensions:2560,1920

a=control:rtsp://192.168.7.99:554/h264/ch1/main/trackID=1

a=rtpmap:96 H264/90000

a=fmtp:96 profile-level-id=420029; packetization-mode=1; sprop-parameter-sets=Z01AMo2NQBQAeP+AtwEBAUAAAPoAADDUOhgAeYK7y40MADzBXeXCgA==,aO44gA==

m=audio 0 RTP/AVP 0

c=IN IP4 0.0.0.0

b=AS:50

a=recvonly

a=control:rtsp://192.168.7.99:554/h264/ch1/main/trackID=2

a=rtpmap:0 PCMU/8000

a=Media_header:MEDIAINFO=494D4B48010200000400000110710110401F000000FA000000000000000000000000000000000000;

a=appversion:1.0


video codec set to: h264
RTP Profile IDC: 42 Profile IOP: 0 Level: 29
RTP Packetization Mode: 1
Extradata set to 0x1700a8820 (size: 52)
请问怎么处理呢

**Comment by bigfi2000** [comment]
@zxb1094

 [options setFormatOptionValue:@"tcp" forKey:@"rtsp_transport"];

你设置这个试试

**Comment by zxb1094** [comment]
@bigfi2000   还是一样  不能播放
