### ISSUE TITLE
初始是https 然后 我重定向到http的url 没法播放 请问有什么限制么

### ISSUE THREAD

**Issue by shenmingyang** [Bilibili/ijkplayer#3875]
如果我初始是https 重定向的也是https就是可以播放的
ijkmp_stop()
aout_pause_audio(1)
ijkmp_stop()=0
ijkmp_shutdown_l()
aout_pause_audio(1)
aout_pause_audio(1)
wait for read_tid
aout_close_audio()
[AVIOContext @ 0x1021ad080] Statistics: 14180929 bytes read, 2 seeks
wait for video_refresh_tid
ijkmp_shutdown_l()=void
ijkmp_set_inject_opaque(0x0)
ijkmp_set_inject_opaque()=void
ijkmp_set_ijkio_inject_opaque(0x0)
ijkmp_set_ijkio_inject_opaque()=void
ijkmp_dec_ref(): ref=0
ijkmp_shutdown_l()
ijkmp_shutdown_l()=void
aout_close_audio()
av_version_info: ff3.3--ijk0.8.0--20170829--001
ijk_version_info: 
ijkmp_set_inject_opaque(0x1c401caf0)
ijkmp_set_inject_opaque()=void
ijkmp_set_ijkio_inject_opaque(0x1c401caf0)
ijkmp_set_ijkio_inject_opaque()=void
2017-12-26 13:34:45.060692+0800 IJKMediaDemo[17339:5808417] OK setup GL
ijkmp_ios_set_view(glView=0x10218ab30)
ijkmp_ios_set_view(glView=0x10218ab30)=void
2017-12-26 13:34:45.065113+0800 IJKMediaDemo[17339:5808417] invalidateRenderBuffer
2017-12-26 13:34:45.065486+0800 IJKMediaDemo[17339:5810481] IJKSDLGLView:display: unable to tryLock GL active: 0
ijkmp_set_data_source(url="https://musicapi.diyidan.net/video/6294360860123517729")
ijkmp_set_data_source(url="https://musicapi.diyidan.net/video/6294360860123517729")=0
ijkmp_prepare_async()
===== versions =====
[FFPlayer @ 0x10313e200] ijkplayer    : 
[FFPlayer @ 0x10313e200] FFmpeg       : ff3.3--ijk0.8.0--20170829--001
[FFPlayer @ 0x10313e200] libavutil    : 55.58.100
[FFPlayer @ 0x10313e200] libavcodec   : 57.89.100
[FFPlayer @ 0x10313e200] libavformat  : 57.71.100
[FFPlayer @ 0x10313e200] libswscale   : 4.6.100
[FFPlayer @ 0x10313e200] libswresample: 2.7.100
===== options =====
[FFPlayer @ 0x10313e200] player-opts : video-pictq-size             = 3
[FFPlayer @ 0x10313e200] player-opts : overlay-format               = fcc-_es2
[FFPlayer @ 0x10313e200] player-opts : max-fps                      = 30
[FFPlayer @ 0x10313e200] player-opts : framedrop                    = 1
[FFPlayer @ 0x10313e200] player-opts : videotoolbox-max-frame-width = 960
[FFPlayer @ 0x10313e200] player-opts : videotoolbox                 = 1
[FFPlayer @ 0x10313e200] player-opts : start-on-prepared            = 1
[FFPlayer @ 0x10313e200] format-opts : ijkapplication               = 4330288320
[FFPlayer @ 0x10313e200] format-opts : ijkiomanager                 = 4330137200
[FFPlayer @ 0x10313e200] format-opts : user-agent                   = ijkplayer
[FFPlayer @ 0x10313e200] format-opts : auto_convert                 = 0
[FFPlayer @ 0x10313e200] format-opts : user_agent                   = Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B202 iOSDYD iOSDYD iOSDYD iOSDYD
[FFPlayer @ 0x10313e200] format-opts : timeout                      = 30000000
[FFPlayer @ 0x10313e200] format-opts : reconnect                    = 1
[FFPlayer @ 0x10313e200] format-opts : Referer                      = diyidan.net
[FFPlayer @ 0x10313e200] format-opts : safe                         = 0
===================
ijkmp_prepare_async()=0
[https @ 0x10220a220] Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'
2017-12-26 13:34:45.101192+0800 IJKMediaDemo[17339:5808417] invalidateRenderBuffer
Add dns cache hostname = musicapi.diyidan.net, ip = 106.75.65.101
[https @ 0x1029c8600] the user-agent option is deprecated, please use user_agent option
[https @ 0x10220a220] request: GET /video/6294360860123517729 HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=0-

Connection: close

Host: musicapi.diyidan.net

Icy-MetaData: 1

[AVIOContext @ 0x102247b30] Statistics: 0 bytes read, 0 seeks
https://musicapi.diyidan.net/video/6294360860123517729: Invalid data found when processing input
2017-12-26 13:34:45.428078+0800 IJKMediaDemo[17339:5808417] FFP_MSG_ERROR: 0
2017-12-26 13:34:45.428661+0800 IJKMediaDemo[17339:5808417] IJKMPMoviePlayBackStateDidChange 2: paused
2017-12-26 13:34:45.431355+0800 IJKMediaDemo[17339:5808417] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1

**Comment by moeyard** [comment]
不一定是https的问题,  这里测试好像重定向换端口就会有问题.

**Comment by shenmingyang** [comment]
能详细的说下么。

**Comment by shenmingyang** [comment]
解决了

**Comment by JRJian** [comment]
@shenmingyang 解决了能否发下方案？

**Comment by yjg2014** [comment]
@shenmingyang 请问如何解决的？
