### ISSUE TITLE
how can i build arm64

### ISSUE THREAD

**Issue by leonard0629** [Bilibili/ijkplayer#388]
I find the command "./compile-ijk.sh arm64" in compile-ijk.sh, but when i use this, i get a errorr:
MacBook-Pro:android leonard$ ./compile-ijk.sh arm64
profiler build: NO
Android NDK: ERROR:/Users/leonard/Documents/work/code/3rd/ijkplayer-android/android/ijkplayer/player-arm64/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /libijkffmpeg.so exists  or that its path is correct   
/Users/leonard/tools/android-ndk-r10e/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.

how i can build the arm64? i do all the steps in readme before and i get the correct .so except arm64.
i build it on macos

**Comment by bbcallen** [comment]
```
sh compile-ffmpeg arm64
```

**Comment by leonard0629** [comment]
yeah, i already done this. but i got the error message: 
MacBook-Pro:android leonard$ ./compile-ijk.sh arm64
profiler build: NO
Android NDK: ERROR:/Users/leonard/Documents/work/code/3rd/ijkplayer-android/android/ijkplayer/player-arm64/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file

Android NDK: Check that /libijkffmpeg.so exists or that its path is correct

/Users/leonard/tools/android-ndk-r10e/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting . Stop.

how can i solve this

**Comment by leonard0629** [comment]
i do what you told me and finally build the arm64 version successfully. thx

**Comment by jpxiong** [comment]
How did you solve the build problem ? I got the same error.

**Comment by jpxiong** [comment]
I had solve the build problem:
```
$ cd ijkplayer/android/contrib/
$ sh compile-ffmpeg.sh arm64
$ cd ..
$ sh compile-ijk.sh arm64
```

**Comment by aaronvargas** [comment]
in compile-ijk.sh do_ndk_build () 
   case "$PARAM_TARGET" in
        armv5|armv7a)
        ...
        x86|arm64)
            # This looks Suspect, why do both cd to x86 dir?
            cd ijkplayer/player-x86/src/main/jni

**Comment by bbcallen** [comment]
My fault

**Comment by fukemy** [comment]
not working for me, mac-os 64:

build on Darwin x86_64
ANDROID_NDK=/Users/thehe/Library/Android/sdk/ndk-bundle
NDKr10e(64-bit) detected
--------------------
# to continue to build ffmpeg, run script below,
sh compile-ffmpeg.sh 
# to continue to build ijkplayer, run script below,
sh compile-ijk.sh 
THG:contrib thehe$ cd ..
THG:android thehe$ ./compile-ijk.sh 
profiler build: NO
Android NDK: ERROR:/Users/thehe/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /libijkffmpeg.so exists  or that its path is correct   
/Users/thehe/Library/Android/sdk/ndk-bundle/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.

**Comment by loveq369** [comment]
> not working for me, mac-os 64:
> 
> ```
> build on Darwin x86_64
> ANDROID_NDK=/Users/thehe/Library/Android/sdk/ndk-bundle
> NDKr10e(64-bit) detected
> ```
> ```
> --------------------
> # to continue to build ffmpeg, run script below,
> sh compile-ffmpeg.sh 
> # to continue to build ijkplayer, run script below,
> sh compile-ijk.sh 
> THG:contrib thehe$ cd ..
> THG:android thehe$ ./compile-ijk.sh 
> profiler build: NO
> Android NDK: ERROR:/Users/thehe/ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file    
> Android NDK: Check that /libijkffmpeg.so exists  or that its path is correct   
> /Users/thehe/Library/Android/sdk/ndk-bundle/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
> ```

sb

**Comment by SUNILJAIN19** [comment]
Unable To build.Please help.
MT-MAC-7303:android mmt7703$ sh compile-ijk.sh arm64
profiler build: NO
Android NDK: ERROR:/Users/mmt7703/StudioProjects/ijkplayer-android/android/ijkplayer/ijkplayer-arm64/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /Users/mmt7703/StudioProjects/ijkplayer-android/android/contrib/build/ffmpeg-arm64/output/libijkffmpeg.so exists  or that its path is correct   
/Users/mmt7703/Library/Android/sdk/ndk-bundle/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.

**Comment by khyatiChitroda** [comment]
same issue I have, please help me,

profiler build: NO
Android NDK: ERROR:/home/khyati/ijkopenssl/ijkplayer/android/ijkplayer/ijkplayer-armv7a/src/main/jni/ffmpeg/Android.mk:ijkffmpeg: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /libijkffmpeg.so exists  or that its path is correct   
/home/khyati/Toolchain/android-ndk-r10e/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
/home/khyati/ijkopenssl/ijkplayer/android
