### ISSUE TITLE
ff_read (33): EXC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by SmallWeed** [Bilibili/ijkplayer#3886]
在 ijkplayer-0.8.4 运行本地视频，直接崩溃
![1514892815300](https://user-images.githubusercontent.com/11731944/34482580-db0d023e-eff3-11e7-8247-841a81bd5172.jpg)

**Comment by SmallWeed** [comment]
这是错误时因为，没有编译openssl ，config没有打开crypto

**Comment by zhangyuhan18** [comment]
请教一下，具体怎么解决呢

**Comment by SmallWeed** [comment]
> 请教一下，具体怎么解决呢

在配置文件打开 crypto
