### ISSUE TITLE
google play 上架因为OpenSSL问题被拒

### ISSUE THREAD

**Issue by Ianstark14** [Bilibili/ijkplayer#3888]
app内部使用ijkplayer,google play 上架反馈OpenSSL版本过低，查询之后发现是libijkffmpeg.so的OpenSSL版本为1.0.2d，低于谷歌要求的1.0.2f

**Comment by Android4MediaPlayer** [comment]
已经是用1.0.2h了

**Comment by Ianstark14** [comment]
最新的吗
