### ISSUE TITLE
hls playback keep-alive problem

### ISSUE THREAD

**Issue by masudo** [Bilibili/ijkplayer#389]
right know ffmpeg and ffplay make a new connection for getting new segments and updating m3u8 segments list, it makes streamplay back to stutter and not play smoothly, how can we fix the problem and tell ffmpeg to keep-alive the connection and make just one connection for fetching all segments and segments list?

below is the log of ffplay playback of a hls stream:

[http @ 0x7fd34a554ae0] request: GET /hls/tv3_lq34.ts HTTP/1.10/0   
User-Agent: Lavf/56.25.101
Accept: */*
Connection: close
Host: x.x.x.x
Icy-MetaData: 1

as you see it sends Connection: close in header instead of keep-alive and it close connection in this way the play suffers and stutters as the cost of making new http connection every 6 or 10 seconds is high! and when it have to update play list it should make two new connection every 6 seconds (as we defined, you can make it longer but it suffer anyway).

**Comment by bbcallen** [comment]
http://ffmpeg.org/ffmpeg-protocols.html#http
I don't think FFmpeg's HLS implement supports that.
