### ISSUE TITLE
【iOS】调用stop方法后，怎么重新播放

### ISSUE THREAD

**Issue by OCer** [Bilibili/ijkplayer#3892]
手动调用stop方法并不发送ijk停止的通知
手动调用stop方法后，调用prepareToPlay和play会崩溃
手动调用stop和shutdown方法后，调用prepareToPlay和play不会崩溃，但也没办法播放视频

我之所以用stop而不用pause是因为担心pause会继续缓存，从而浪费流量

**Comment by raymond1012** [comment]
不能，需要修改逻辑

**Comment by nicolasiJasica** [comment]
mark

**Comment by yscMichael** [comment]
我这边也发现这个问题了

**Comment by wushengdeluoye** [comment]
怎么解决的呢

**Comment by wanglianghd** [comment]
大佬怎么解决的呢？
