### ISSUE TITLE
android ijkplayer 相同码率，相同fps，增加分辨率视频为什么会卡顿

### ISSUE THREAD

**Issue by harlanc** [Bilibili/ijkplayer#3893]
如题，编码为hevc.4K不卡 ，5K就卡的不行

**Comment by harlanc** [comment]
把硬解选项打开了：
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-hevc", 1）；
发现4K的是media codec。
播放5K自己变成avcodec了

**Comment by harlanc** [comment]
error log
01-04 16:45:44.909 22340-22363/? D/J4A: J4ALoader: OK: 'android.media.MediaCodec$BufferInfo' loaded
01-04 16:45:44.909 22340-22363/? D/J4A: J4ALoader: OK: 'android.media.MediaCodec' loaded
01-04 16:45:56.555 22340-22469/? I/IjkMediaCodecInfo:  Unknown Profile Level 52 (4096,65536)
01-04 16:45:56.556 22340-22469/? I/IjkMediaCodecInfo:  Baseline Profile Level 52 (1,65536)
01-04 16:45:56.556 22340-22469/? D/IJKMEDIA: SDL_AMediaCodecJava_createByCodecName
01-04 16:45:56.610 22340-22469/? D/IJKMEDIA: SDL_AMediaCodecJava_init
01-04 16:45:56.610 22340-22469/? D/IJKMEDIA: SDL_AMediaCodec_increaseReference(): ref=1
01-04 16:45:56.610 22340-22469/? D/IJKMEDIA: SDL_AMediaCodecJava_configure_surface
01-04 16:45:56.612 22340-22484/? I/MediaCodec: [OMX.qcom.video.decoder.hevc] setting surface generation to 22876161
01-04 16:45:56.621 22340-22484/? E/MediaCodec: Codec reported err 0xfffffff4, actionCode 0, while in state 3
01-04 16:45:56.621 22340-22469/? E/MediaCodec: configure failed with err 0xfffffff4, resetting...
01-04 16:45:56.652 22340-22469/? W/System.err: android.media.MediaCodec$CodecException: Error 0xfffffff4
01-04 16:45:56.654 22340-22469/? W/System.err:     at android.media.MediaCodec.native_configure(Native Method)
01-04 16:45:56.654 22340-22469/? W/System.err:     at android.media.MediaCodec.configure(MediaCodec.java:1884)
01-04 16:45:56.654 22340-22469/? D/IJKMEDIA: SDL_AMediaCodec_decreaseReference(): ref=0
01-04 16:45:56.654 22340-22469/? I/IJKMEDIA: SDL_AMediaCodecJava_delete

**Comment by Android4MediaPlayer** [comment]
分辨率太高硬解码不支持了
MediaCodec: Codec reported err 0xfffffff4, actionCode 0, while in state 3
01-04 16:45:56.621 22340-22469/? E/MediaCodec: configure failed with err 0xfffffff4, resetting...
01-04 16:45:56.652 22340-22469/? W/System.err: android.media.MediaCodec$CodecException: Error 0xfffffff4

**Comment by Android4MediaPlayer** [comment]
@harlanc 硬解码不支持切换成软解码了

**Comment by harlanc** [comment]
thx @Android4MediaPlayer
