### ISSUE TITLE
使用了ijkhttphook，设置一个无效的播放地址不会调用播放失败的回调

### ISSUE THREAD

**Issue by finasty** [Bilibili/ijkplayer#3896]

**Comment by raymond1012** [comment]
need use ijkhttphook:http://xxx

**Comment by finasty** [comment]
http://cm14-ccm1-2.play.bokecc.com/flvs/ca/Qx8aH/umRX1yaLHR-20.mp4?t=1515128978&key=4D94F6A23AD076C61F6E3CD61D6FE885
这个地址是可以的，但是设置地址ijkhttphook:http://cm14-ccm1-2.play.bokecc.com/flvs/ca/Qx8aH/umRX1yaLHR-20.mp4?t=1515128978&key=4D94F6A23AD076C61F6E3CD61D6FE886  mOnErrorListener不会调用onError的回调

**Comment by raymond1012** [comment]
因为被hook了，无限重试

2018-01-05 11:18 GMT+08:00 finasty <notifications@github.com>:

**Comment by hzhzhen** [comment]
我的可以啊
