### ISSUE TITLE
android rtmp直播流 偶尔 黑屏只有声音

### ISSUE THREAD

**Issue by goingupbao** [Bilibili/ijkplayer#390]
如题 缓存完了没有画面，只有声音
对比了一下log
这是正常的
SDL_AMediaCodecJava_start
08-06 19:20:32.079: I/ACodec(12111): [OMX.qcom.video.decoder.avc] Now Loaded->Idle
08-06 19:20:32.079: I/ACodec(12111): [OMX.qcom.video.decoder.avc] configureOutputBuffersFromNativeWindow setBufferCount : 22, minUndequeuedBuffers : 4
08-06 19:20:32.079: I/ACodec(12111): [OMX.qcom.video.decoder.avc] Allocating 22 buffers from a native window of size 606208 on output port
08-06 19:20:32.169: I/IJKMEDIA(12111): VideoCodec: MediaCodec, OMX.qcom.video.decoder.avc
08-06 19:20:32.169: I/IJKMEDIA(12111): fps: 30.303030 (normal)
08-06 19:20:32.169: I/IJKMEDIA(12111): fps: 30.000000 (normal)
08-06 19:20:32.169: I/IJKMEDIA(12111): SDL_RunThread: [14005] ff_video_dec
08-06 19:20:32.169: I/ACodec(12111): [OMX.qcom.video.decoder.avc] Now Idle->Executing
08-06 19:20:32.169: W/IJKMEDIA(12111): ijkmp_get_msg: FFP_MSG_PREPARED
08-06 19:20:32.169: W/IJKMEDIA(12111): FFP_MSG_PREPARED:
08-06 19:20:32.169: W/IJKMEDIA(12111): FFP_MSG_VIDEO_SIZE_CHANGED: 776, 438
08-06 19:20:32.169: W/IJKMEDIA(12111): FFP_MSG_SAR_CHANGED: 0, 1
08-06 19:20:32.169: D/com.xxxxxx.Live.Widget.VideoView(12111): onPrepared
08-06 19:20:32.169: W/IJKMEDIA(12111): IjkMediaPlayer_start
08-06 19:20:32.169: W/IJKMEDIA(12111): ijkmp_start()
08-06 19:20:32.169: W/IJKMEDIA(12111): ijkmp_get_msg: FFP_REQ_START
08-06 19:20:32.169: D/IJKMEDIA(12111): ijkmp_get_msg: FFP_REQ_START: start on fly
08-06 19:20:32.169: W/IJKMEDIA(12111): ijkmp_start()=0
08-06 19:20:32.169: D/com.xxxxxx.Live.Widget.VideoView(12111): onVideoSizeChanged: (776x438)
08-06 19:20:32.169: I/Video_Change(12111): NW:1080 NH:607 VW:1080 VH:609
08-06 19:20:32.169: D/com.xxxxxx.Live.Widget.VideoView(12111): onVideoSizeChanged: (776x438)
08-06 19:20:32.169: I/IJKMEDIA(12111): SDL_RunThread: [14006] amediacodec_input_thread
08-06 19:20:32.179: I/ACodec(12111): [OMX.qcom.video.decoder.avc] Now Executing
08-06 19:20:32.189: I/ACodec(12111): [OMX.qcom.video.decoder.avc] Now handling output port settings change

如果触发了FFP_MSG_VIDEO_SIZE_CHANGED  onVideoSizeChanged 则画面正常

下面是不正常的日志
 : Audio: aac (LC), 48000 Hz, stereo, fltp, 131 kb/s
08-06 19:20:54.571: I/IJKMEDIA(12111): SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
08-06 19:20:54.571: I/IJKMEDIA(12111): SDL_Android_AudioTrack: ENCODING_PCM_16BIT
08-06 19:20:54.581: E/AudioTrack(12111): AudioTrack::set : Exit
08-06 19:20:54.581: I/IJKMEDIA(12111): SDL_Android_AudioTrack_new: init volume as 1.000000/(0.000000,1.000000)
08-06 19:20:54.581: I/IJKMEDIA(12111): AudioCodec: avcodec, aac
08-06 19:20:54.581: W/IJKMEDIA(12111): ijkmp_get_msg: FFP_MSG_PREPARED
08-06 19:20:54.581: W/IJKMEDIA(12111): FFP_MSG_PREPARED:
08-06 19:20:54.581: D/com.xxxxxx.Live.Widget.VideoView(12111): onPrepared
08-06 19:20:54.591: W/IJKMEDIA(12111): IjkMediaPlayer_start
08-06 19:20:54.591: W/IJKMEDIA(12111): ijkmp_start()
08-06 19:20:54.591: W/IJKMEDIA(12111): ijkmp_start()=0
08-06 19:20:54.591: W/IJKMEDIA(12111): ijkmp_get_msg: FFP_REQ_START
08-06 19:20:54.591: D/IJKMEDIA(12111): ijkmp_get_msg: FFP_REQ_START: start on fly
08-06 19:20:54.591: W/IJKMEDIA(12111): ijkmp_get_msg: FFP_REQ_START
08-06 19:20:54.591: D/IJKMEDIA(12111): ijkmp_get_msg: FFP_REQ_START: start on fly
08-06 19:20:54.601: I/IJKMEDIA(12111): SDL_RunThread: [14176] ff_audio_dec
08-06 19:20:54.601: I/IJKMEDIA(12111): SDL_RunThread: [14175] ff_aout_android
08-06 19:20:55.562: W/IJKMEDIA(12111): Stream discovered after head already parsed
08-06 19:21:10.977: D/HybiParser(12111): Creating frame for: 2 op: 1 err: -1
08-06 19:21:22.428: W/IJKMEDIA(12111): ijkmp_stop()
08-06 19:21:22.428: W/IJKMEDIA(12111): ijkmp_stop()=0
没有出发FFP_MSG_VIDEO_SIZE_CHANGED onVideoSizeChanged 则没有画面只有声音

**Comment by bbcallen** [comment]
Google "Stream discovered after head already parsed"

**Comment by zhanglehs** [comment]
the iOS version has the same problem

**Comment by zhanglehs** [comment]
i debugged my code, and found out that sometimes avformat_find_stream_info can't detect video stream (only detect audio stream), so there is no FFP_MSG_VIDEO_SIZE_CHANGED.
now the problem is why avformat_find_stream_info sometimes can't detect video stream, my probesize = 5000000, i think this is big enough.

**Comment by goingupbao** [comment]
播放RTMP 直播流的时候，会有关键帧，包含了VIDEO的相关信息，然而上传视频流的时候 关键帧是可设置的，具体可以看一下 OBS -> settings，没有关键帧 就无法播放视频流，如果关键帧间隔过长，就导致缓冲之后没有遇到关键帧，即使后来读到关键帧也无法播放

**Comment by Android4MediaPlayer** [comment]
check your rtmp server

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.

**Comment by RobinLW** [comment]
@zhanglehs try to set "analyzeduration" a big num. For example 10 seconds.

**Comment by RobinLW** [comment]
@goingupbao 直播推流的时候，编码设置除了关键帧还有哪些参数可能造成流打开解析失败啊
