### ISSUE TITLE
iOS - How can I change the selected audio stream while video is already playing?

### ISSUE THREAD

**Issue by awfulcode** [Bilibili/ijkplayer#391]
I found wanted_stream_spec in ffplay, but nothing that allows to choose a specific audio stream when there are more than 1. Is there anything already in there that does that or should I write my own code for that?

Thanks!

**Comment by bbcallen** [comment]
No, but you may find how it works in original ffplay.c

**Comment by bbcallen** [comment]
Supported with ijkmp_set_stream_selected();
