### ISSUE TITLE
问题咨询（ffmpeg版本问题）

### ISSUE THREAD

**Issue by DouglasLiu2016** [Bilibili/ijkplayer#3928]
请问ijkplayer内部的ffmpeg与https://github.com/FFmpeg/FFmpeg.git的ffmpeg有什么区别吗？

如果不一样，请问ijkplayer依赖的ffmpeg是基于正式的ffmpeg的哪个版本呢？

非常感谢！！

**Comment by raymond1012** [comment]
参考init-android.sh 或者init-ios.sh 中的ffmpeg
