### ISSUE TITLE
Immediate exit requested出现这个是为什么啊

### ISSUE THREAD

**Issue by Average77** [Bilibili/ijkplayer#3947]
E/IJKMEDIA: http://www.hlbrlyou.com/energy/u/cms/www/201801/22154413xq76.mp4: Immediate exit requested

**Comment by Average77** [comment]
@mdaslamHossin  you should used ijkplayer ，then release 。Don't premature release.
sorry，my English is poor.

**Comment by Average77** [comment]
After you have finished using ijkplayer

**Comment by Average77** [comment]
don't release when it is resume state @mdaslamHossin

**Comment by mdaslamHossin** [comment]
When i placed the release code? Currently added in onStop method .

**Comment by Average77** [comment]
onDestory() method @mdaslamHossin

**Comment by mdaslamHossin** [comment]
Not working yet.
