### ISSUE TITLE
请问为什么播放网络视频，没有缓冲中，但是视频播放起来很卡顿的样子

### ISSUE THREAD

**Issue by xiaoyaomeng** [Bilibili/ijkplayer#395]
最近做一个手机播放局域网视频的app
播放的时候有时候会很卡顿的样子，但是也没有停下来，缓冲。
请教一下，有解决的方法吗？

**Comment by Android4MediaPlayer** [comment]
切换硬解试试

**Comment by xiaoyaomeng** [comment]
请问ijkplayer如果切换成硬解？？刚接触这块，比较不清楚，谢谢！

**Comment by Android4MediaPlayer** [comment]
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
