### ISSUE TITLE
编译过程中遇到一个问题，很多人遇到但没有答案，求解答

### ISSUE THREAD

**Issue by xiaoyaomeng** [Bilibili/ijkplayer#396]
./compile-ffmpeg.sh all ： 

出现

In file included from libavcodec/x86/mpegvideoenc.c:83:0:
libavcodec/x86/mpegvideoenc_template.c: In function 'dct_quantize_ssse3':
libavcodec/x86/mpegvideoenc_template.c:151:9: error: 'asm' operand has impossible constraints
         __asm__ volatile(
         ^
libavcodec/x86/mpegvideoenc_template.c:186:9: error: 'asm' operand has impossible constraints
         __asm__ volatile(
         ^
make: *** [libavcodec/x86/mpegvideoenc.o] Error 1

**Comment by lionel0806** [comment]
Maybe you should install yasm, i am not sure, you can have a try.

**Comment by xiaoyaomeng** [comment]
oh, no , 我本身有装yasm， 所以跟这个可能并没有关系，我现在将sh中的x86去除了
