### ISSUE TITLE
播放网络音频不用start就开始播放

### ISSUE THREAD

**Issue by water92429** [Bilibili/ijkplayer#3962]
我使用如下方法：
mIMediaPlayer.setDataSource("http://fdfs.xmcdn.com/group26/M07/08/AB/wKgJWFpVsCKBehNNAEag_Um_4hg770.mp3");
mIMediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
mIMediaPlayer.prepareAsync();
初始化完就开始播放音频，为什么？

**Comment by OCer** [comment]
prepareAsync(); 调用了后就会播放  在这里之前你可以设置不自动播放
看这里  https://github.com/Bilibili/ijkplayer/issues/3961

**Comment by water92429** [comment]
java上没留接口吗？

**Comment by OCer** [comment]
也可以设置是否自动播放的吧

**Comment by water92429** [comment]
好的，谢谢，我再找找有没有接口！
