### ISSUE TITLE
播放rtmp直播流，播放无效链接时，没有错误信息返回吗？

### ISSUE THREAD

**Issue by zhangbl** [Bilibili/ijkplayer#398]
播放rtmp直播流，播放无效链接时，没有错误信息返回吗？

**Comment by garymabin** [comment]
Have you ever registered `OnErrorListener()`?

**Comment by zhangbl** [comment]
注册了，没错误信息返回，vlc能返回错误信息

**Comment by xiaoyaomeng** [comment]
我想请问下zhangbl另一个问题，你有办法加载在线视频，但是等到用户按了播放才开始播放吗？

**Comment by Android4MediaPlayer** [comment]
prepare之后不调start，点播放时调

**Comment by xiaoyaomeng** [comment]
@Android4MediaPlayer  你好，我播放的是在线视频，我将start去除掉了，依旧还是会自动播放

**Comment by Android4MediaPlayer** [comment]
你要设置下start-on-prepared这个option为0

**Comment by xiaoyaomeng** [comment]
@Android4MediaPlayer ijkMediaPlayer.setOption(IjkMediaPlayer.MEDIA_INFO_BUFFERING_START, "start_on_prepared", 0);   ??? 请问是这样吗？或者说有没有文档什么的可以给我一下？

**Comment by xiaoyaomeng** [comment]
@Android4MediaPlayer  另外再请教您一个问题：我现在手机连接着局域网里的一台设备，然后播放该设备上的在线视频，一秒钟大概1.5M/s，有时候视频会好像慢放一样非常卡顿，但是不会进入缓冲，感觉像是刷到SurfaceView上非常缓慢的感觉，这个请问你们遇到过吗？我改了#define MAX_QUEUE_SIZE (15 * 1024 * 1024)  改成 20 * 1024 * 1024也没有效果

**Comment by Android4MediaPlayer** [comment]
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "start_on_prepared", 0);

**Comment by xiaoyaomeng** [comment]
@Android4MediaPlayer  或者您是否可以给我提供下如何切换成硬解？？我试试？

**Comment by Android4MediaPlayer** [comment]
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);

**Comment by xiaoyaomeng** [comment]
@Android4MediaPlayer  改成硬解之后效果确实好很多，然而这样又另一个问题就是硬解，是不是只有部分机器可以支持？请问一下支持硬解的条件是什么？初次接触这些东西，希望指点。

**Comment by Android4MediaPlayer** [comment]
google

**Comment by xiaoyaomeng** [comment]
OK, thanks !
