### ISSUE TITLE
后台音乐无法播放

### ISSUE THREAD

**Issue by yinjining** [Bilibili/ijkplayer#3982]
后台有音乐播放，开启ijk视频播放，后台音乐被暂停。当ijk视频暂停或播放完成，后台音乐如何继续播放？而不是暂停状态。

**Comment by raymond1012** [comment]
起一个service来播放音乐

**Comment by yinjining** [comment]
@raymond1012 能详细点吗？代码小白，应该怎么修改代码呢？谢谢您了。

**Comment by yinjining** [comment]
@raymond1012 后台有音乐播放，是有其他播放器，其他音乐播放器再播放音乐，用ijk播放视频，后台音乐被打断暂停，当ijk视频播放完成后，后台音乐无法继续播放。

**Comment by zhanggao** [comment]
跟service无关，搜 requestAudioFocus。
