### ISSUE TITLE
ios切换播放url的时候崩溃

### ISSUE THREAD

**Issue by remantou** [Bilibili/ijkplayer#399]
我的切换流程不知道对不对 之前的没有问题 最新的崩
remove player的通知之后
[player shutdown]
然后用新的流地址初始化一个新的ffmovieplayer
然后就崩溃了
<img width="931" alt="2015-08-12 10 42 06" src="https://cloud.githubusercontent.com/assets/8045375/9215579/05b23cfa-40df-11e5-8758-c5e534b5fe14.png">

**Comment by bbcallen** [comment]
More stack info?

**Comment by remantou** [comment]
最后打印的日志：
SDL_Overlay(ffmpeg): overlay_free_l(0x1740b4340)
SDL_Overlay(ffmpeg): overlay_free_l(0x1782a1200)
SDL_Overlay(ffmpeg): overlay_free_l(0x1740aaec0)
ijkmp_shutdown_l()=void
ijkmp_dec_ref(): ref=0
ijkmp_shutdown_l()
ijkmp_shutdown_l()=void
aout_close_audio()

![Uploading 屏幕快照 2015-08-12 上午10.58.39.png…]()
![Uploading 屏幕快照 2015-08-12 上午10.58.52.png…]()

**Comment by remantou** [comment]
<img width="899" alt="2015-08-12 10 58 39" src="https://cloud.githubusercontent.com/assets/8045375/9217079/ba0696f4-40f5-11e5-8875-3c6c787eeec3.png">
<img width="870" alt="2015-08-12 10 58 52" src="https://cloud.githubusercontent.com/assets/8045375/9217083/c6664cfa-40f5-11e5-9bd7-01a56889f032.png">
最后的日志：
SDL_Overlay(ffmpeg): overlay_free_l(0x1740b4340)
SDL_Overlay(ffmpeg): overlay_free_l(0x1782a1200)
SDL_Overlay(ffmpeg): overlay_free_l(0x1740aaec0)
ijkmp_shutdown_l()=void
ijkmp_dec_ref(): ref=0
ijkmp_shutdown_l()
ijkmp_shutdown_l()=void
aout_close_audio()

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
