### ISSUE TITLE
求助！救助！播放m3u8直播流正常播放后，快进后无法播放? 

### ISSUE THREAD

**Issue by kulong51** [Bilibili/ijkplayer#3999]
log 提示
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
 I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
 I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
 I/IJKMEDIA: Hit DNS cache hostname = stream1.hnntv.cn
 I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
I/IJKMEDIA: Hit DNS cache hostname = stream1.hnntv.cn
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
 I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2

**Comment by raymond1012** [comment]
ffmpeg 的hls 仅对直播友好，不支持seek
