### ISSUE TITLE
ios切换播放url的时候崩溃

### ISSUE THREAD

**Issue by remantou** [Bilibili/ijkplayer#400]
我的切换流程不知道对不对 之前的没有问题 最新的崩
remove player的通知之后
[player shutdown]
然后用新的流地址初始化一个新的ffmovieplayer
然后就崩溃了
![Uploading 屏幕快照 2015-08-12 上午10.42.06.png…]()

**Comment by GrayLuo** [comment]
can't change url while playback state  is playing , prepareToPlay will set url . recreate a new player if you want to play another url.
