### ISSUE TITLE
about the touch event while playing video

### ISSUE THREAD

**Issue by leonard0629** [Bilibili/ijkplayer#401]
i found a problem when playing video. the first time i touched the view, nothing happened, and till the second time it went into the breakpoint at "onTouchEvent ". why this happened and how can i solve this? Would you give some advices? i'm using the android sample

**Comment by leonard0629** [comment]
anyone knows something about it?

**Comment by leonard0629** [comment]
i comment the code blew in hide&show method of MediaController
```
if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.ICE_CREAM_SANDWICH){
                mAnchor.setSystemUiVisibility(View.SYSTEM_UI_FLAG_VISIBLE);
            }
```

**Comment by gityan** [comment]
It works. Thx very much!
