### ISSUE TITLE
iOS options 参数设置

### ISSUE THREAD

**Issue by Will-ZJ** [Bilibili/ijkplayer#4015]
cpu 使用有点高，然后卡顿和花屏，绿屏，这些问题我想知道如何配置options 去调优？谢谢

**Comment by PengBoShi** [comment]
只是ijk并不会出现这个样子。估计是你把ijk集成到你的项目中出现的。ijk的参数并不能解决你的这个问题

**Comment by Will-ZJ** [comment]
@PengBoShi 哦，谢谢，那跟网速有关么？
