### ISSUE TITLE
Warning!! codec module is deprecated 

### ISSUE THREAD

**Issue by spaul13** [Bilibili/ijkplayer#4019]
**I am getting this kind of warnings showing that codec module is deprecated. Why this error is coming and how can I possibly fix this?**

_libavfilter/avfiltergraph.c: In function 'avfilter_graph_free':
libavfilter/avfiltergraph.c:132:5: warning: 'resample_lavr_opts' is deprecated (declared at libavfilter/avfilter.h:847) [-Wdeprecated-declarations]
     av_freep(&(*graph)->resample_lavr_opts);
     ^
libavformat/concatdec.c: In function 'detect_stream_specific':
libavformat/concatdec.c:208:9: warning: 'av_bitstream_filter_init' is deprecated (declared at ./libavcodec/avcodec.h:5929) [-Wdeprecated-declarations]
         if (!(bsf = av_bitstream_filter_init("h264_mp4toannexb"))) {
         ^
libavformat/concatdec.c: In function 'concat_read_close':
libavformat/concatdec.c:400:17: warning: 'av_bitstream_filter_close' is deprecated (declared at ./libavcodec/avcodec.h:5973) [-Wdeprecated-declarations]
                 av_bitstream_filter_close(cat->files[i].streams[j].bsf);
                 ^
libavformat/concatdec.c: In function 'filter_packet':
libavformat/concatdec.c:564:9: warning: 'av_bitstream_filter_filter' is deprecated (declared at ./libavcodec/avcodec.h:5961) [-Wdeprecated-declarations]
         ret = av_bitstream_filter_filter(bsf, cs->avctx, NULL,
         ^
libavformat/dump.c: In function 'dump_stream_format':
libavformat/dump.c:462:5: warning: 'codec' is deprecated (declared at libavformat/avformat.h:898) [-Wdeprecated-declarations]
     avctx->properties = st->codec->properties;
     ^
libavformat/dump.c:463:5: warning: 'codec' is deprecated (declared at libavformat/avformat.h:898) [-Wdeprecated-declarations]
     avctx->codec      = st->codec->codec;
     ^
libavformat/dump.c:464:5: warning: 'codec' is deprecated (declared at libavformat/avformat.h:898) [-Wdeprecated-declarations]
     avctx->qmin       = st->codec->qmin;
     ^
libavformat/dump.c:465:5: warning: 'codec' is deprecated (declared at libavformat/avformat.h:898) [-Wdeprecated-declarations]
     avctx->qmax       = st->codec->qmax;
     ^
libavformat/dump.c:466:5: warning: 'codec' is deprecated (declared at libavformat/avformat.h:898) [-Wdeprecated-declarations]
     avctx->coded_width  = st->codec->coded_width;
     ^
libavformat/dump.c:467:5: warning: 'codec' is deprecated (declared at libavformat/avformat.h:898) [-Wdeprecated-declarations]
     avctx->coded_height = st->codec->coded_height;
     ^
libavformat/dump.c:502:9: warning: 'codec' is deprecated (declared at libavformat/avformat.h:898) [-Wdeprecated-declarations]
         int tbc = st->codec->time_base.den && st->codec->time_base.num;
         ^
libavformat/dump.c:502:9: warning: 'codec' is deprecated (declared at libavformat/avformat.h:898) [-Wdeprecated-declarations]
libavformat/dump.c:514:13: warning: 'codec' is deprecated (declared at libavformat/avformat.h:898) [-Wdeprecated-declarations]
             print_fps(1 / av_q2d(st->codec->time_base), "tbc");
             ^
libavformat/movenc.c: In function 'ff_mov_write_packet':
libavformat/movenc.c:5157:1: warning: label 'end' defined but not used [-Wunused-label]
 end:
 ^
libavformat/tcp.c: In function 'tcp_getaddrinfo_request_free_buffer':
libavformat/tcp.c:127:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     TCPAddrinfoRequest *req = (TCPAddrinfoRequest *)opaque;
     ^
libavformat/utils.c: In function 'avformat_transfer_internal_stream_timing_info':
libavformat/utils.c:5429:5: warning: 'codec' is deprecated (declared at libavformat/avformat.h:898) [-Wdeprecated-declarations]
     const AVCodecContext *dec_ctx = ist->codec;
     ^
libavformat/utils.c:5430:5: warning: 'codec' is deprecated (declared at libavformat/avformat.h:898) [-Wdeprecated-declarations]
     AVCodecContext       *enc_ctx = ost->codec;
     ^
libavcodec/bitstream_filter.c: In function 'av_bitstream_filter_next':
libavcodec/bitstream_filter.c:39:5: warning: return discards 'const' qualifier from pointer target type
     return av_bsf_next(&opaque);
     ^
libavcodec/bitstream_filter.c: In function 'av_bitstream_filter_filter':
libavcodec/bitstream_filter.c:132:14: warning: assignment discards 'const' qualifier from pointer target type
     pkt.data = buf;
              ^
In file included from libavcodec/fft_fixed.c:21:0:
libavcodec/fft_template.c:467:6: warning: 'pass_big' defined but not used [-Wunused-function]
 PASS(pass_big)
      ^
libavcodec/fft_template.c:444:13: note: in definition of macro 'PASS'
 static void name(FFTComplex *z, const FFTSample *wre, unsigned int n)\
             ^
In file included from libavcodec/fft_float.c:21:0:
libavcodec/fft_template.c:467:6: warning: 'pass_big' defined but not used [-Wunused-function]
 PASS(pass_big)
      ^
libavcodec/fft_template.c:444:13: note: in definition of macro 'PASS'
 static void name(FFTComplex *z, const FFTSample *wre, unsigned int n)\
             ^
libavcodec/frame_thread_encoder.c: In function 'worker':
libavcodec/frame_thread_encoder.c:86:9: warning: 'avcodec_encode_video2' is deprecated (declared at libavcodec/avcodec.h:5407) [-Wdeprecated-declarations]
         ret = avcodec_encode_video2(avctx, pkt, frame, &got_packet);
         ^
libavcodec/frame_thread_encoder.c:92:13: warning: 'av_dup_packet' is deprecated (declared at libavcodec/avcodec.h:4526) [-Wdeprecated-declarations]
             int ret2 = av_dup_packet(pkt);
             ^
libavcodec/pngenc.c: In function 'png_write_row':
libavcodec/pngenc.c:277:25: warning: assignment discards 'const' qualifier from pointer target type
     s->zstream.next_in  = data;
                         ^
libavcodec/utils.c: In function 'avcodec_encode_audio2':
libavcodec/utils.c:1930:13: warning: 'av_dup_packet' is deprecated (declared at libavcodec/avcodec.h:4526) [-Wdeprecated-declarations]
             if (av_dup_packet(avpkt) < 0) {
             ^
libavcodec/utils.c: In function 'avcodec_encode_video2':
libavcodec/utils.c:2026:13: warning: 'av_dup_packet' is deprecated (declared at libavcodec/avcodec.h:4526) [-Wdeprecated-declarations]
             if (av_dup_packet(avpkt) < 0) {
             ^
libavcodec/utils.c: In function 'do_decode':
libavcodec/utils.c:2822:9: warning: 'avcodec_decode_video2' is deprecated (declared at libavcodec/utils.c:2227) [-Wdeprecated-declarations]
         ret = avcodec_decode_video2(avctx, avctx->internal->buffer_frame,
         ^
libavcodec/utils.c:2827:9: warning: 'avcodec_decode_audio4' is deprecated (declared at libavcodec/utils.c:2336) [-Wdeprecated-declarations]
         ret = avcodec_decode_audio4(avctx, avctx->internal->buffer_frame,
         ^
libavcodec/utils.c: In function 'do_encode':
libavcodec/utils.c:2979:9: warning: 'avcodec_encode_video2' is deprecated (declared at libavcodec/utils.c:1968) [-Wdeprecated-declarations]
         ret = avcodec_encode_video2(avctx, avctx->internal->buffer_pkt,
         ^
libavcodec/utils.c:2982:9: warning: 'avcodec_encode_audio2' is deprecated (declared at libavcodec/utils.c:1822) [-Wdeprecated-declarations]
         ret = avcodec_encode_audio2(avctx, avctx->internal->buffer_pkt,
         ^_

**Comment by raymond1012** [comment]
send patch to ffmpeg.org
