### ISSUE TITLE
IJK_GLES2_Renderer_create crash

### ISSUE THREAD

**Issue by iosnower** [Bilibili/ijkplayer#4021]
多次出现下面的崩溃，请大神看一下，下面是bugly捕获的堆栈信息：

SIGSEGV
SEGV_ACCERR

0 Dreamer-ios-client | IJK_GLES2_Renderer_create (renderer.c:182)
1 Dreamer-ios-client | IJK_GLES2_Renderer_create (renderer.c:182)
2 Dreamer-ios-client | -[IJKSDLGLView setupRenderer:] (IJKSDLGLView.m:313)
3 Dreamer-ios-client | -[IJKSDLGLView displayInternal:] (IJKSDLGLView.m:373)
4 Dreamer-ios-client | -[IJKSDLGLView display:] (IJKSDLGLView.m:363)
5 Dreamer-ios-client | vout_display_overlay (ijksdl_vout_ios_gles2.m:104)
6 Dreamer-ios-client | video_display2 (ff_ffplay.c:2182)
7 Dreamer-ios-client | video_refresh_thread (ff_ffplay.c:2712)
8 Dreamer-ios-client | SDL_RunThread (ijksdl_thread_ios.m:32)
9 libsystem_pthread.dylib | __pthread_body + 308
10 libsystem_pthread.dylib | __pthread_body

**Comment by raymond1012** [comment]
wait next version

**Comment by JosephWong2222** [comment]
@raymond1012 请问这个问题有修复版本吗？

**Comment by bill86006** [comment]
@raymond1012 Is there have any progress on this issue?
