### ISSUE TITLE
Question: What is the advantage of ijkplayer over exoplayer?

### ISSUE THREAD

**Issue by barhom** [Bilibili/ijkplayer#4032]
Hey,

Can somebody tell me what ijkplayer can do that exoplayer can not do?
So I know when to use ijkplayer and when to use exoplayer.

Thanks,

**Comment by methodus** [comment]
One main advantage: it is able to play RTSP, which exo can't do. Another thing: you can tweak ijkplayer with almost all ffmpeg options to get the best results from your stream or video. the ijkplayer api is easy to extend and to customize. Thats my opinion.

**Comment by mohit-sharma-87** [comment]
@methodus: Thanks for responding to this. I think you are already aware that Exo player [now supports RTSP](https://developer.android.com/guide/topics/media/exoplayer/rtsp) so would it be possible for you to add more light to the advantages of ijkplayer player?
