### ISSUE TITLE
Buffer Allocation in ijkplayer

### ISSUE THREAD

**Issue by spaul13** [Bilibili/ijkplayer#4035]
can anyone please tell me who is calling this function for allocating the buffer?
IjkFifoBuffer *ijk_av_fifo_alloc(unsigned int size);
static IjkFifoBuffer *fifo_alloc_common(void *buffer, size_t size);
IjkFifoBuffer *ijk_av_fifo_alloc_array(size_t nmemb, size_t size);

What's the value of size here? I have seen buffer is allocating as an array using calloc in ijkfifo.c. 
I just want to know from where its called and who is writing into the buffer and who is reading from the buffer?

**Comment by raymond1012** [comment]
ijkfifo will be discard
