### ISSUE TITLE
what calls J4ALoader to load while starting of ijkMediaPlayer

### ISSUE THREAD

**Issue by spaul13** [Bilibili/ijkplayer#4038]
Can anyone tell me what is calling J4ALoader, what makes Buffer and ByteBuffer load at the very start of ijkMediaPlayer?

02-21 12:46:28.830 5783-5802/? D/J4A: **J4ALoader: OK: 'java.nio.Buffer' loaded**
02-21 12:46:28.830 5783-5802/? D/J4A: **J4ALoader: OK: 'java.nio.ByteBuffer' loaded**
02-21 12:46:28.830 5783-5802/? D/J4A: J4ALoader: OK: 'java.util.ArrayList' loaded
02-21 12:46:28.832 5783-5802/? I/J4A: API-Level: 25
02-21 12:46:28.832 5783-5802/? D/J4A: J4ALoader: OK: 'android.media.AudioTrack' loaded
02-21 12:46:28.832 5783-5802/? D/J4A: J4ALoader: OK: 'android.media.MediaCodec$BufferInfo' loaded
02-21 12:46:28.832 5783-5802/? D/J4A: J4ALoader: OK: 'android.media.MediaCodec' loaded

**Comment by raymond1012** [comment]
see https://github.com/Bilibili/jni4android

**Comment by spaul13** [comment]
@raymond1012 , thanks for the reply.

For my case, I have seen J4ALoader is not getting loaded ( I am not getting this print statements). That's why my media codec is n't instantiated.

Can you tell me how to resolve this issue?
