### ISSUE TITLE
您好，SOS

### ISSUE THREAD

**Issue by Will-ZJ** [Bilibili/ijkplayer#4039]
iOS版不支持h265硬解吗？什么时候可以支持？？

**Comment by raymond1012** [comment]
update to 0.8.8 https://github.com/Bilibili/ijkplayer/commit/edfca47eca555636c69fde8d1f854088e2c1e5be

**Comment by Will-ZJ** [comment]
是不是需要参照你给的链接去修改.m文件？不会影响对h265的支持吧

**Comment by Will-ZJ** [comment]
我发现在iOS11的机子上cpu反而比低于11版本的机子更高？why？目前用的是k0.8.4?是不是iOS11版本的硬解需要另外设置（针对h264的解码）？
