### ISSUE TITLE
iOS  fatal error: 'armv7s/avconfig.h' file not found

### ISSUE THREAD

**Issue by KCastiglione** [Bilibili/ijkplayer#404]
I successfully compiled ffmpeg with latest HEAD version 094b9644f01913aa28ff96c225928bde7dae359b

         ./init-ios.sh
         cd ios
         ./compile-ffmpeg.sh all

I am trying to build IJKMediaPlayer.xcodeproj.

         xcodebuild -project 'IJKMediaPlayer.xcodeproj' -configuration 'Release' -sdk 'iphoneos8.4' clean build ARCHS='armv7 armv7s arm64' IPHONEOS_DEPLOYMENT_TARGET='6.0' TARGET_BUILD_DIR='/tmp/build-arm-all' BUILT_PRODUCTS_DIR='/tmp/build-arm-all'

        In file included from ../build/universal/include/libavutil/eval.h:29:
        In file included from ../build/universal/include/libavutil/avutil.h:296:
        In file included from ../build/universal/include/libavutil/common.h:44:
        ../build/universal/include/libavutil/avconfig.h:30:17: fatal error: 'armv7s/avconfig.h' file not found
        #       include "armv7s/avconfig.h"
                        ^
        

Please let me know how to fix this? This was working before.

**Comment by bbcallen** [comment]
Are you using armv7s architecture?
Run
```
./compile-ffmpeg.sh armv7s
```

BTW: Is't recommended to remove armv7s from your app's build.
