### ISSUE TITLE
rtmp compile error android

### ISSUE THREAD

**Issue by msdos2** [Bilibili/ijkplayer#405]
hello me you can explain how I can add on this project rtmp always gives me the same error. Thank you
ERROR: librtmp not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.

**Comment by bbcallen** [comment]
Build with librtmp is not supported by ijkplayer, yet.
