### ISSUE TITLE
Seek 时偶现电流声

### ISSUE THREAD

**Issue by xksds** [Bilibili/ijkplayer#4052]
新年好，B站的小伙伴们！

在播放音乐（m4a/aac格式）时，多次seek，会偶现电流声，概率不是很高，1/10差不多吧，如不复现可以多试几次。

dump decode前的AAC（AAC RAW --> ADTS ）数据，播放正常，无电流声。
dump decode出来的PCM数据，有电流声。
在FFMPEG的论坛上找到了相关文章（https://trac.ffmpeg.org/ticket/420）
对比了现在版本的代码，已经合并了。
也尝试了在Flush时清空其他decode cache的数据，依然不能解决。
不知道B站的小伙伴们有没有做AAC Decoder的，希望给予支持解决，谢谢。

我这边也会尝试解决，如问题解决，我会及时更新。

**Comment by Android4MediaPlayer** [comment]
用的ijk哪一个版本？有测试视频吗

**Comment by xksds** [comment]
===== versions =====
ijkplayer    : k0.8.4-2-ge1d04bd8
FFmpeg       : ff3.3--ijk0.8.0--20170829--001
libavutil    : 55.58.100
libavcodec   : 57.89.100
libavformat  : 57.71.100
libswscale   : 4.6.100
libswresample: 2.7.100

测试内容是m4a格式的AAC 音乐，Android/iOS都会复现。
PS1：我试了下你们的BILIBILI APP，Android，也会有此现象。
PS2：MAC上MPLayer在seek时也会偶现电流声，这个问题很可能时FFMPEG的BUG。

**Comment by Android4MediaPlayer** [comment]
更新到最新版试一下

**Comment by xksds** [comment]
![image](https://user-images.githubusercontent.com/6055000/36707745-a158d5f8-1baa-11e8-875e-35b44478f900.png)

**Comment by Android4MediaPlayer** [comment]
@xksds ？

**Comment by xksds** [comment]
@Android4MediaPlayer 
如上面截图所示，清空相关信息，重新init decoder，问题不再复现。
我感觉这种办法是很“**丑陋的**”，但是因为自身没有相关codec开发的经验，也没有更好的建议。
希望B站的小伙伴能给出完美的解决方案，谢谢。

**Comment by Android4MediaPlayer** [comment]
建议不用这么做，有更新0.8.8试一下吗？

**Comment by xksds** [comment]
@Android4MediaPlayer 
正在下载代码，今天公司网络很差，一直失败。
等更新好代码后我再做尝试。

**Comment by xksds** [comment]
@Android4MediaPlayer 
看了下 FFMPEG 的Git log （https://github.com/Bilibili/FFmpeg.git），最近并没有相关codec修改，感觉即使更新到最新也不一定能解决这个问题。

今天这网络太差了。。。

**Comment by xksds** [comment]
===== versions =====
ijkplayer    : k0.8.8
FFmpeg       : ff3.4--ijk0.8.7--20180103--001
libavutil    : 55.78.100
libavcodec   : 57.107.100
libavformat  : 57.83.100
libswscale   : 4.8.100
libswresample: 2.9.100
===== options =====
player-opts : video-pictq-size             = 3
player-opts : overlay-format               = fcc-_es2
player-opts : max-fps                      = 30
player-opts : framedrop                    = 0
player-opts : videotoolbox-max-frame-width = 960
player-opts : videotoolbox                 = 0
player-opts : start-on-prepared            = 1
format-opts : ijkapplication               = 140185246437408
format-opts : ijkiomanager                 = 140185246452192
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : timeout                      = 30000000
format-opts : reconnect                    = 1
format-opts : safe                         = 0
===================

AAC在seek时依然会偶现电流声，flush改成close和init这样比较干净，上面的截图会出现memory的少量增长。

![image](https://user-images.githubusercontent.com/6055000/36766318-4dbf17f6-1c70-11e8-91aa-5d1594d7e122.png)

**Comment by xksds** [comment]
@Android4MediaPlayer 
具体细节有机会再请假以前做Audio Codec的同事吧。
