### ISSUE TITLE
hi,bbcallen,能不能在底层添加改变视频播放速度的功能？

### ISSUE THREAD

**Issue by jaycee11** [Bilibili/ijkplayer#406]
如标题，Thanks

**Comment by bbcallen** [comment]
You are free to add what you want.

**Comment by Zard1096** [comment]
How to add the speed up or slow down?
I saw ffmpeg set -vf setpts for video and -af atempo for audio,and it must enable filter.
Where to set them with ijk?And could it set dynamically?

**Comment by cwq** [comment]
video: can use clock
audio: should use swr or other third-party libraries to transform audio data

**Comment by bbcallen** [comment]
Feature added
