### ISSUE TITLE
Android执行./compile-ffmpeg.sh all报错

### ISSUE THREAD

**Issue by sunkeding** [Bilibili/ijkplayer#4080]
myMacBook-Pro:contrib skd$ ./compile-ffmpeg.sh all
====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a arm64 x86 x86_64
FF_ACT_ARCHS = armv5 armv7a arm64 x86 x86_64

====================
[*] check env armv5
====================
FF_ARCH=armv5
FF_BUILD_OPT=

--------------------
[*] make NDK standalone toolchain
--------------------
build on Darwin x86_64
ANDROID_NDK=
You must define ANDROID_NDK before starting.
They must point to your NDK directories.

这个是什么意思啊，NDK环境我应该是配置了的呢

**Comment by raymond1012** [comment]
see README

**Comment by biezhihua** [comment]
目前这个库还不支持使用NDK16版本进行构建，哪怕你改了脚本也不行。

我自己写了个构建脚本，已经解决了这个问题，欢迎使用。

https://github.com/biezhihua/FFmpegBuildTool
