### ISSUE TITLE
ios8的iphone5上vtb失败 日志如下

### ISSUE THREAD

**Issue by remantou** [Bilibili/ijkplayer#410]
Error Error Domain=NSOSStatusErrorDomain Code=-12910 "The operation couldn’t be completed. (OSStatus error -12910.)"
CreateVTBSession - failed with status = (-12910)could not init video tool box decoder !!!vtb fail!!! switch to ffmpeg decode!!!! 
VideoCodec: avcodec, h264

这是什么原因啊

**Comment by cracj** [comment]
默认没打开硬解码的

**Comment by cracj** [comment]
你在IJKFFOptions.m里的optionsByDefault方法里加入[options setVideoToolBoxEnabled:YES];

**Comment by remantou** [comment]
就是打开了硬解 置为YES之后报的这个错误。

**Comment by cracj** [comment]
你的流是标准的流吗？

**Comment by cracj** [comment]
用软解能成功吗？

**Comment by remantou** [comment]
软解能成功

**Comment by cracj** [comment]
我的情况和你差不多，因为我的rtmp视频流没有pps和sps头，所以导致硬解失败，但可以软解
