### ISSUE TITLE
关于DNS缓存的问题

### ISSUE THREAD

**Issue by dlluotian** [Bilibili/ijkplayer#4103]
rtmp://XXXX.com:11937/base/a6a1bf2e1

rtmp://XXXX.com:11938/base/a6a1bf2e2

这两个地址域名相同，但是指向不同的ip，使用Ijk播放，先播放了其中一个，另外一个就无法播放了，指向了错误的ip。
现在的解决方式是修改了ffmg的源码，不使用dns缓存。就可以正常的播放。
如果java层能提供相关的开关最好了。

**Comment by raymond1012** [comment]
setoption

**Comment by JerryIsAgoodBoy** [comment]
@raymond1012  我查看了ijk的options，没有看到相关的选项，请教一下具体是哪个选项

**Comment by dlluotian** [comment]
@JerryIsAgoodBoy    ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_clear", 1);
