### ISSUE TITLE
使用cocoapods时候，如何集成ijkplayer到workspace里面

### ISSUE THREAD

**Issue by guitarkitten** [Bilibili/ijkplayer#411]
制作.a文件还是framwork文件？按照readme的步骤集成到workspace有很多问题。

**Comment by bbcallen** [comment]
Not support cocoapods, due to some public headers search path issue.

**Comment by guitarkitten** [comment]
so just create .a file, but the file is too big.

**Comment by bbcallen** [comment]
https://github.com/Bilibili/FFmpeg4ijkplayer-ios-bin
https://github.com/CocoaPods/CocoaPods/issues/1437

If you can fix it in ijkplayer or in cocoa pods, patch is welcome. (Not the workaround way)
