### ISSUE TITLE
0.88，配置module-default.sh之后，编译ffmpeg报错：linux/perf_event.h: No such file or directory

### ISSUE THREAD

**Issue by saisaixv** [Bilibili/ijkplayer#4118]
[*] compile ffmpeg
--------------------
In file included from ./libavutil/internal.h:42:0,
                 from ./libavutil/common.h:467,
                 from ./libavutil/avutil.h:296,
                 from ./libavutil/avassert.h:31,
                 from libavfilter/aeval.c:26:
./libavutil/timer.h:38:31: fatal error: linux/perf_event.h: No such file or directory
 # include <linux/perf_event.h>
                               ^
compilation terminated.
make: *** [libavfilter/aeval.o] Error 1

**Comment by weisterjie** [comment]
我也是这个问题   好尴尬

**Comment by blankfu** [comment]
@saisaixv   兄弟这个错误怎么解决的    我也是最新版本编译ffmpeg报这个错

**Comment by fly-jelly** [comment]
> 我也是这个问题 好尴尬

在config > module.sh 最后面添加 export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-linux-perf".我用的是ndk-android-14b
