### ISSUE TITLE
在nexus10(android 5.0.2)上MediaController会被底部虚拟按钮挡住

### ISSUE THREAD

**Issue by gnastnosaj** [Bilibili/ijkplayer#413]
全屏状态下，点击会先显示虚拟按钮，再点击一下才会出现MediaController但是被虚拟按钮遮住了一半。

**Comment by gnastnosaj** [comment]
请教怎么调整
mWindow.showAtLocation(mAnchor, Gravity.BOTTOM,
                        anchorRect.left, 0);

**Comment by garymabin** [comment]
you can enable immersive mode on API 19+ devices to hide navigation key.

**Comment by gnastnosaj** [comment]
thanks
