### ISSUE TITLE
"Protocol not found" when attempting to play RTMPS streams

### ISSUE THREAD

**Issue by ahopper-soltech** [Bilibili/ijkplayer#415]
Hello! I'm trying to play an rtmps stream, but I'm getting an "Protocol not found" error when I try to open the URL from within the Demo app (I also had to change the demo app to allow rtmps:// urls).

I tried setting the configuration to module-default (I saw that module-lite disables rtmp*), and I've also tried adding a line to module.sh to add --enable-protocols, but neither appears to have had any effect.

Am I missing a step? Debug logs below.

Thanks!
---------- Debug Logs from XCode ---------- 
av_version_info: n2.7-24-g58b28fc
ijkmp_set_format_callback(0x10295a590, 0x7fd4e3c02d10)
ijkmp_set_format_callback()=void
ijkmp_set_option_int(start-on-prepared, 1)
ijkmp_set_option_int()=void
2015-08-19 15:12:47.731 IJKMediaDemo[14034:18223936] OK setup GL
ijkmp_ios_set_view(glView=0x7fd4e3e171a0)
ijkmp_ios_set_view(glView=0x7fd4e3e171a0)=void
ijkmp_set_option(overlay-format, fcc-i420)
ijkmp_set_option()=void
ijkmp_set_option_int(skip_frame, 8)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_loop_filter, 48)
ijkmp_set_option_int()=void
ijkmp_set_option_int(timeout, 30000000)
ijkmp_set_option_int()=void
ijkmp_set_option_int(reconnect, 1)
ijkmp_set_option_int()=void
ijkmp_set_option(user-agent, ijkplayer)
ijkmp_set_option()=void
ijkmp_set_option_int(max-fps, 30)
ijkmp_set_option_int()=void
ijkmp_set_option_int(framedrop, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox-max-frame-width, 960)
ijkmp_set_option_int()=void
ijkmp_set_option_int(video-pictq-size, 3)
ijkmp_set_option_int()=void
ijkmp_set_data_source(url="rtmps://<my url>")
ijkmp_set_data_source(url="rtmps://<my url>")=0
ijkmp_set_option(safe, 0)
ijkmp_set_option()=void
ijkmp_prepare_async()
===== options =====
player-opts : start-on-prepared            = 1
player-opts : overlay-format               = fcc-i420
player-opts : max-fps                      = 30
player-opts : framedrop                    = 0
player-opts : videotoolbox-max-frame-width = 960
player-opts : video-pictq-size             = 3
format-opts : timeout                      = 30000000
format-opts : reconnect                    = 1
format-opts : user-agent                   = ijkplayer
format-opts : safe                         = 0
codec-opts  : skip_frame                   = 8
codec-opts  : skip_loop_filter             = 48
===================
ijkmp_prepare_async()=0
ijkmp_start()
ijkmp_start()=-3
remove 'timeout' option for rtmp.
rtmps://<my url>: Protocol not found
2015-08-19 15:12:47.747 IJKMediaDemo[14034:18223936] FFP_MSG_ERROR: 0
2015-08-19 15:12:47.747 IJKMediaDemo[14034:18223936] moviePlayBackStateDidChange 2: paused
2015-08-19 15:12:47.747 IJKMediaDemo[14034:18223936] playbackStateDidChange: MPMovieFinishReasonPlaybackError: 1
ijkmp_start()
ijkmp_start()=-3

**Comment by ahopper-soltech** [comment]
Note: ./configure --list-protocols shows rtmps, so it would appear that ffmpeg is reasonably happy...

**Comment by bbcallen** [comment]
See config.log
I guess it depends on openssl.

**Comment by Android4MediaPlayer** [comment]
plz add openssl

**Comment by ahopper-soltech** [comment]
Hm. If I set --enable-openssl, I get a compilation error stating openssl is not found. I have run init-ios-openssl.sh and compile-openssl.sh, but I'm still getting that error. Do I need to set any additional path information to have the ffmpeg compilation see the openssl libraries?

**Comment by ahopper-soltech** [comment]
Ha. I was following the steps for building ffmpeg, which includes "compile-ffmpeg.sh clean"
This kills the openssl output.

For any who come after me:
1. ./init-ios-openssl.sh
2. cd ios
3. ./compile-openssl.sh all
4. ./compile-ffmpeg.sh all
5. ./build/ffmpeg-x86_64/output/bin/ffprobe -protocols (you should see rtmps)

**Comment by ahopper-soltech** [comment]
I'm very close now. While the ffmpeg build now successfully completes with rtmps support, I can no longer compile the IJKMediaPlayer XCode project. Instead, I'm getting a bunch of linker errors for symbols like _BIO_clear_flags, _BIO_new, etc.It would appear that these are all OpenSSL functions. I have tried manually adding a reference to the universal libssl and libcrypto static libraries, but that appears to have no effect. Is there another way to link the OpenSSL libraries to this project?

**Comment by bbcallen** [comment]
How did you add references?
Try "Build Phases" -> "Link Binary with Libraries"

**Comment by ahopper-soltech** [comment]
Aha! I was using the IJKMediaDemo app, and it appears that I needed to add the references to the demo app project, not the IJKMediaPlayer project. It seems happy now. Thanks to everyone for their help!

**Comment by spaul13** [comment]
@bbcallen can you please tell me how can I possibly see when a frame is decoded whether its a I/P/B frame?
