### ISSUE TITLE
IJK_NDK_REL=""

### ISSUE THREAD

**Issue by dazhiyu** [Bilibili/ijkplayer#4156]
./compile-ffmpeg.sh all

====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a arm64 x86 x86_64
FF_ACT_ARCHS = armv5 armv7a arm64 x86 x86_64

====================
[*] check env armv5
====================
FF_ARCH=armv5
FF_BUILD_OPT=

--------------------
[*] make NDK standalone toolchain
--------------------
build on Darwin x86_64
ANDROID_NDK=/Users/lianyongke/Downlaods/android-ndk-r10e
IJK_NDK_REL=
You need the NDKr10e or later

ndk-r10e配置了，为什么还是编译不过去

**Comment by dazhiyu** [comment]
好吧，是我ndk地址配置错了。。。。

**Comment by piqiuqiuggl** [comment]
请问要怎么配置，我绝对路径也不好使
