### ISSUE TITLE
iOS Warnings when archiving

### ISSUE THREAD

**Issue by philtre** [Bilibili/ijkplayer#416]
I've included IJKMediaPlayer.xcodeproj as a subproject and managed to successfully build and archive my app in XCode 7 Beta 5. However, I get 70+ warnings when archiving, although it doesn't seem to affect any functionality. Is this something I should be worried about? Any idea on how to get rid of these warnings? They do not appear when I Build&Run, only when archiving.

    GenerateDSYMFile /Users/currentuser/Library/Developer/Xcode/DerivedData/VideoApp-eqpaduclbuzgdeclrwwlaonhztlg/Build/Intermediates/ArchiveIntermediates/VideoApp/BuildProductsPath/Release-iphoneos/VideoApp.app.dSYM /Users/currentuser/Library/Developer/Xcode/DerivedData/VideoApp-eqpaduclbuzgdeclrwwlaonhztlg/Build/Intermediates/ArchiveIntermediates/VideoApp/InstallationBuildProductsLocation/Applications/VideoApp.app/VideoApp
        cd /Users/currentuser/WORK/VideoApp/
        export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
        /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/currentuser/Library/Developer/Xcode/DerivedData/VideoApp-eqpaduclbuzgdeclrwwlaonhztlg/Build/Intermediates/ArchiveIntermediates/VideoApp/InstallationBuildProductsLocation/Applications/VideoApp.app/VideoApp -o /Users/currentuser/Library/Developer/Xcode/DerivedData/VideoApp-eqpaduclbuzgdeclrwwlaonhztlg/Build/Intermediates/ArchiveIntermediates/VideoApp/BuildProductsPath/Release-iphoneos/VideoApp.app.dSYM

    warning: (armv7)  could not find object file symbol for symbol _ff_fft_calc_vfp
    warning: (armv7)  could not find object file symbol for symbol _ff_fft16_vfp
    warning: (armv7)  could not find object file symbol for symbol _ff_h264_idct_add_neon
    warning: (armv7)  could not find object file symbol for symbol _ff_h264_idct_dc_add_neon
    warning: (armv7)  could not find object file symbol for symbol _ff_h264_idct_add16_neon
    warning: (armv7)  could not find object file symbol for symbol _ff_h264_idct_add16intra_neon
    warning: (armv7)  could not find object file symbol for symbol _ff_h264_idct_add8_neon
    warning: (armv7)  could not find object file symbol for symbol _ff_h264_idct8_add_neon
    warning: (armv7)  could not find object file symbol for symbol _ff_h264_idct8_dc_add_neon
    warning: (armv7)  could not find object file symbol for symbol _ff_h264_idct8_add4_neon
    warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels16_arm
    warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_arm
    warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_x2_arm
    warning: (armv7)  could not find object file symbol for symbol _ff_put_no_rnd_pixels8_x2_arm
    warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_y2_arm
    warning: (armv7)  could not find object file symbol for symbol _ff_put_no_rnd_pixels8_y2_arm
    warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_xy2_arm
    warning: (armv7)  could not find object file symbol for symbol _ff_put_no_rnd_pixels8_xy2_arm
    warning: (armv7)  could not find object file symbol for symbol _ff_avg_pixels16_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels16_x2_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels16_y2_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels16_x2_no_rnd_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels16_y2_no_rnd_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels16_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_x2_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_y2_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_x2_no_rnd_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_y2_no_rnd_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_avg_pixels8_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_add_pixels_clamped_arm
    warning: (armv7)  could not find object file symbol for symbol _ff_add_pixels_clamped_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_j_rev_dct_arm
    warning: (armv7)  could not find object file symbol for symbol _ff_imdct_half_neon
    warning: (armv7)  could not find object file symbol for symbol _ff_imdct_calc_neon
    warning: (armv7)  could not find object file symbol for symbol _ff_mdct_calc_neon
    warning: (armv7)  could not find object file symbol for symbol _ff_imdct_half_vfp
    warning: (armv7)  could not find object file symbol for symbol _ff_pix_abs16_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_pix_abs16_x2_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_pix_abs16_y2_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_pix_abs8_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_sse16_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_dct_unquantize_h263_inter_neon
    warning: (armv7)  could not find object file symbol for symbol _ff_dct_unquantize_h263_neon
    warning: (armv7)  could not find object file symbol for symbol _ff_dct_unquantize_h263_intra_neon
    warning: (armv7)  could not find object file symbol for symbol _ff_rdft_calc_neon
    warning: (armv7)  could not find object file symbol for symbol _ff_simple_idct_arm
    warning: (armv7)  could not find object file symbol for symbol __row_loop
    warning: (armv7)  could not find object file symbol for symbol __end_b_evaluation
    warning: (armv7)  could not find object file symbol for symbol __end_a_evaluation
    warning: (armv7)  could not find object file symbol for symbol __almost_empty_row
    warning: (armv7)  could not find object file symbol for symbol __end_row_loop
    warning: (armv7)  could not find object file symbol for symbol __col_loop
    warning: (armv7)  could not find object file symbol for symbol __end_bef_a_evaluation
    warning: (armv7)  could not find object file symbol for symbol _ff_simple_idct_armv5te
    warning: (armv7)  could not find object file symbol for symbol _ff_simple_idct_add_armv5te
    warning: (armv7)  could not find object file symbol for symbol _ff_simple_idct_put_armv5te
    warning: (armv7)  could not find object file symbol for symbol _ff_simple_idct_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_simple_idct_add_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_simple_idct_put_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_simple_idct_put_neon
    warning: (armv7)  could not find object file symbol for symbol _ff_simple_idct_add_neon
    warning: (armv7)  could not find object file symbol for symbol _ff_simple_idct_neon
    warning: (armv7)  could not find object file symbol for symbol _ff_startcode_find_candidate_armv6
    warning: (armv7)  could not find object file symbol for symbol _ff_prefetch_arm
    warning: (armv7)  could not find object file symbol for symbol _dct_unquantize_h263_intra_neon
    warning: (armv7)  could not find object file symbol for symbol _dct_unquantize_h263_inter_neon
    warning: (armv7)  could not find object file symbol for symbol _ff_vector_fmul_vfp
    warning: (armv7)  could not find object file symbol for symbol _ff_vector_fmul_window_vfp
    warning: (armv7)  could not find object file symbol for symbol _ff_vector_fmul_reverse_vfp
    warning: (armv7)  could not find object file symbol for symbol _ff_butterflies_float_vfp

**Comment by bbcallen** [comment]
I've no idea, for now.
I would wait for the stable version of Xcode.

**Comment by littledogboy** [comment]
这是没有导入动态类库的节奏吧

**Comment by linked67** [comment]
Have the same issue, a lot of warnings but the player don't seems to be affected

**Comment by livyathan** [comment]
I'm having a similar issue on Xcode v7.0.1 and SDK for iOS 9.0.

Initially, I was using an old version of the ijkplayer, from about 3 months ago, so when I saw all the warnings I decided to update everything again, but that didn't help.

I tested my app on an iPhone 4S with iOS 8.1.3 (CPU it's supposed to be armv7-a) and it works fine, even with all the warnings. Also tested on a iPhone 6 and iPad Air 2. I haven't uploaded the app to the store, so I'm not sure if this will cause troubles. Does anybody already tried to upload a update?


I'm using a custom version of the configuration file which supports only webm (vp6,vp8,vp9,opus), ogv (theora, vorbis), flac (just in case) and think also works with mkv. I don't know if it helps but here is my configuration file, it's based on the lite version, the only thing I did was to change the demuxers, parsers and decoders:

```
export COMMON_FF_CFG_FLAGS=

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-gpl"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-nonfree"

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-runtime-cpudetect"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-gray"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-swscale-alpha"

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-programs"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-ffmpeg"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-ffplay"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-ffprobe"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-ffserver"

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-doc"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-htmlpages"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-manpages"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-podpages"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-txtpages"

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-avdevice"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-avcodec"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-avformat"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-avutil"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-swresample"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-swscale"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-postproc"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-avfilter"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-avresample"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-network"

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-dxva2"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-vaapi"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-vda"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-vdpau"

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-encoders"

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-decoders"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=vp6"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=vp6a"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=vp6f"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=vp8"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=vp9"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=vorbis"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=flac"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=theora"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=zlib"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=vp7"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=opus"

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-hwaccels"

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-muxers"

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-demuxers"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=matroska"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=ogg"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=flac"

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-parsers"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-parser=vp8"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-parser=vorbis"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-parser=flac"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-parser=vp9"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-parser=opus"


export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-bsfs"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-bsf=mjpeg2jpeg"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-bsf=mjpeg2jpeg"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-bsf=mjpega_dump_header"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-bsf=mov2textsub"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-bsf=text2movsub"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-bsf=aac_adtstoasc"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-bsf=h264_mp4toannexb"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-bsf=mpeg4_unpack_bframes"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-bsf=mp3_header_decompress"

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocols"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-protocol=async"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-protocol=bluray"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-protocol=ffrtmpcrypt"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=ffrtmphttp"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-protocol=gopher"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-protocol=librtmp*"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-protocol=libssh"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-protocol=mmsh"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-protocol=mmst"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-protocol=rtmp*"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=rtmp"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=rtmpt"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-protocol=rtp"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-protocol=sctp"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-protocol=srtp"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-protocol=unix"

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-devices"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-filters"

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-iconv"
```



Here is the list of warnings:
```
warning: (armv7)  could not find object file symbol for symbol _ff_fft_calc_vfp
warning: (armv7)  could not find object file symbol for symbol _ff_fft16_vfp
warning: (armv7)  could not find object file symbol for symbol _ff_flac_lpc_16_arm
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels16_arm
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_arm
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_x2_arm
warning: (armv7)  could not find object file symbol for symbol _ff_put_no_rnd_pixels8_x2_arm
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_y2_arm
warning: (armv7)  could not find object file symbol for symbol _ff_put_no_rnd_pixels8_y2_arm
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_xy2_arm
warning: (armv7)  could not find object file symbol for symbol _ff_put_no_rnd_pixels8_xy2_arm
warning: (armv7)  could not find object file symbol for symbol _ff_avg_pixels16_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels16_x2_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels16_y2_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels16_x2_no_rnd_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels16_y2_no_rnd_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels16_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_x2_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_y2_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_x2_no_rnd_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_y2_no_rnd_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_avg_pixels8_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_imdct_half_neon
warning: (armv7)  could not find object file symbol for symbol _ff_imdct_calc_neon
warning: (armv7)  could not find object file symbol for symbol _ff_mdct_calc_neon
warning: (armv7)  could not find object file symbol for symbol _ff_imdct_half_vfp
warning: (armv7)  could not find object file symbol for symbol _ff_prefetch_arm
warning: (armv7)  could not find object file symbol for symbol _ff_decode_block_coeffs_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_vp8_luma_dc_wht_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_vp8_luma_dc_wht_dc_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_vp8_idct_add_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_vp8_idct_dc_add_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_vp8_idct_dc_add4uv_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_vp8_idct_dc_add4y_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_vp8_v_loop_filter16_simple_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_vp8_v_loop_filter16_inner_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_vp8_v_loop_filter8uv_inner_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_vp8_v_loop_filter16_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_vp8_v_loop_filter8uv_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_vp8_h_loop_filter16_simple_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_vp8_h_loop_filter16_inner_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_vp8_h_loop_filter8uv_inner_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_vp8_h_loop_filter16_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_vp8_h_loop_filter8uv_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_pixels16_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_pixels8_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_pixels4_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_epel16_h6_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_epel16_v6_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_epel8_h6_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_epel8_v6_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_epel8_h4_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_epel8_v4_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_epel4_h6_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_epel4_v6_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_epel4_h4_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_epel4_v4_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_bilin16_h_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_bilin16_v_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_bilin8_h_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_bilin8_v_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_bilin4_h_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_bilin4_v_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_epel16_h6v6_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_epel8_h6v6_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_epel8_h4v6_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_epel8_h6v4_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_epel8_h4v4_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_epel4_h6v6_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_epel4_h4v6_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_epel4_h6v4_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_epel4_h4v4_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_bilin16_hv_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_bilin8_hv_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_vp8_bilin4_hv_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_vector_fmul_vfp
warning: (armv7)  could not find object file symbol for symbol _ff_vector_fmul_window_vfp
warning: (armv7)  could not find object file symbol for symbol _ff_vector_fmul_reverse_vfp
warning: (armv7)  could not find object file symbol for symbol _ff_butterflies_float_vfp
```


Any ideas?

**Comment by Zard1096** [comment]
Probably ijkplayer version is not matching ffmpeg version.

**Comment by bbcallen** [comment]
No idea, yet.

**Comment by livyathan** [comment]
@Zard1096 could you be more specific, is there something I should check?

@bbcallen could you at least confirm that you can see the warnings too?

Xcode 6 didn't show any of this messages, they only appeared until I updated to Xcode 7, so maybe the FFMpeg needs some changes to remove this warnings. 

It appears there is an update for FFMpeg (v2.8.1), but the change log doesn't really mention anything about this. There is also a new version of iOS (v9.1) and a new version of Xcode (v7.1) just related today, it could help, or make it worst. I'll try to build again the library using the new Xcode later this week.

**Comment by bbcallen** [comment]
Yes, I can see the warnings since Xcode 7.0.

**Comment by nmodin** [comment]
Any word on this ? 

Just started getting them after a hiatus from coding. Xcode Version 7.1.1 (7B1005). Target iPhone 6 9.1

**Comment by oleynikd** [comment]
Anyone?

**Comment by bbcallen** [comment]
It's not on plan, since it doesn't really hurt anything, and I don't know how to fix it.
Any how, PR is welcome.

**Comment by livyathan** [comment]
I also think it's harmless, I have updated my app twice since my last post without problems. I even tested the video playback on an iPhone 4S, and I didn't found any problems.

Consider that I'm not using the default configuration files, so I cannot say something will not fail with certain file formats.

For now I still think this is a problem between FFMpeg and Xcode.

**Comment by Andrew-Khomenok** [comment]
As this is harmless, you can silence these warnings by setting Debug Information Format to DWARF in project's build settings for debug builds.

**Comment by troyzhao** [comment]
I guess these warnings means that the crash log can`t be parse to a symbol file。So I ignored them，呵呵哒

**Comment by troyzhao** [comment]
坐等更新

**Comment by JayGajjar** [comment]
@livyathan Have you uploaded app on app store ? Dose it got approved ?

**Comment by Andrew-Khomenok** [comment]
@JayGajjar I tried and it got approved.

**Comment by JayGajjar** [comment]
@Andrew-Khomenok Nice to hear that, Thank You

**Comment by Sparkle-Ds** [comment]
DWARF with dSYM file      Debug-DWARF    Release-DWARF with dSYM file

**Comment by Sparkle-Ds** [comment]
DWARF with dSYM file
Debug-DWARF
Release-DWARF with dSYM file
