### ISSUE TITLE
IJKSDLGLView: setupDisplay not ready

### ISSUE THREAD

**Issue by zcm9854** [Bilibili/ijkplayer#4162]
麻烦请教一下,播放本地视频成功,播放网络视频失败,应该如何修改
log:
av_version_info: ff3.3--ijk0.8.0--20170829--001
ijk_version_info: k0.8.4-2-ge1d04bd8
ijkmp_set_inject_opaque(0x604000209bd0)
ijkmp_set_inject_opaque()=void
ijkmp_set_ijkio_inject_opaque(0x604000209bd0)
ijkmp_set_ijkio_inject_opaque()=void
2018-04-09 20:21:09.529458+0800[23628:862361] OK setup GL
ijkmp_ios_set_view(glView=0x7ffaa5796ed0)
ijkmp_ios_set_view(glView=0x7ffaa5796ed0)=void
2018-04-09 20:21:09.531857+0800[23628:862361] invalidateRenderBuffer
2018-04-09 20:21:09.534097+0800[23628:873529] IJKSDLGLView: setupDisplay not ready
2018-04-09 20:21:09.547781+0800[23628:862361] invalidateRenderBuffer
2018-04-09 20:21:09.549925+0800[23628:873529] IJKSDLGLView: setupDisplay not ready

调用部分代码:
[IJKFFMoviePlayerController checkIfFFmpegVersionMatch:YES];
        IJKFFOptions *options = [IJKFFOptions optionsByDefault];
        
        self.mediaPlayer = [[IJKFFMoviePlayerController alloc] initWithContentURL:[NSURL URLWithString:_videoUrl] withOptions:options];
        self.mediaPlayer.view.autoresizingMask = UIViewAutoresizingFlexibleWidth|UIViewAutoresizingFlexibleHeight;
        self.mediaPlayer.view.frame = self.bounds;
        self.mediaPlayer.scalingMode = IJKMPMovieScalingModeAspectFit;
        self.mediaPlayer.shouldAutoplay = YES;
        [self addSubview:self.mediaPlayer.view];
        [self sendSubviewToBack:self.mediaPlayer.view];

视频url:http://m4.pptvyun.com/pvod/e11a0/ijblO6coKRX6a8NEQgg8LDZcqPY/eyJkbCI6MTUxNjYyNTM3NSwiZXMiOjYwNDgwMCwiaWQiOiIwYTJkbnEtWG82S2VvcTZMNEsyZG9hZmhvNkNjbTY2WXB3IiwidiI6IjEuMCJ9/0a2dnq-Xo6Keoq6L4K2doafho6Ccm66Ypw.mp4

**Comment by queli1990** [comment]
这是哪里设置不对呢？我也遇到同样的错误，求解

**Comment by ludashen** [comment]
+1

**Comment by Mandyhold** [comment]
请问解决了吗

**Comment by queli1990** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xiaodong Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月2日(星期一) 下午5:34
收件人:&nbsp;"bilibili/ijkplayer"<ijkplayer@noreply.github.com&gt;;
抄送:&nbsp;"ㄗs:水 卍"<457539780@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [bilibili/ijkplayer] IJKSDLGLView: setupDisplay not ready (#4162)




请问解决了吗

**Comment by Mandyhold** [comment]
怎么解决的？没看明白你的回复

**Comment by Mandyhold** [comment]
没看明白，你回复的什么意思？请问是怎么解决的？盼回



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "queli1990"<notifications@github.com&gt;; 
发送时间: 2020年3月2日(星期一) 下午5:36
收件人: "bilibili/ijkplayer"<ijkplayer@noreply.github.com&gt;; 
抄送: "张小东"<897596438@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [bilibili/ijkplayer] IJKSDLGLView: setupDisplay not ready (#4162)



------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"Xiaodong Zhang"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年3月2日(星期一) 下午5:34 
 收件人:&amp;nbsp;"bilibili/ijkplayer"<ijkplayer@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"ㄗs:水 卍"<457539780@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [bilibili/ijkplayer] IJKSDLGLView: setupDisplay not ready (#4162) 
 
 
 
 
 请问解决了吗

**Comment by 815065046** [comment]
怎么改呢？

**Comment by yxmysky** [comment]
请问怎么解决的呢？

**Comment by queli1990** [comment]
您好，您的邮件已收到，我会尽快查阅，谢谢！
