### ISSUE TITLE
k0.8.8版本 的 tcp fastopen选项

### ISSUE THREAD

**Issue by wbi1987** [Bilibili/ijkplayer#4163]
0.8.8版本里ffmpeg的tcp层有fastopen功能，打开后发现拉不到流，请问一下这个功能暂时无法使用还是其它地方需要配置什么吗？

**Comment by raymond1012** [comment]
需要云端配合，仅支持android 7.0 以上的部分机型

**Comment by lonmoon** [comment]
@raymond1012 请教下不支持iOS的原因是什么啊，从实现上来看，iOS应该是可以支持的吧
