### ISSUE TITLE
为啥quirk_reconfigure_with_new_codec总为真

### ISSUE THREAD

**Issue by Android4MediaPlayer** [Bilibili/ijkplayer#417]
// QUIRK: always recreate MediaCodec for reconfigure
        opaque->quirk_reconfigure_with_new_codec = true;
看到有这样的注释，@bbcallen，是出现什么问题吗？

**Comment by Android4MediaPlayer** [comment]
@bbcallen ??

**Comment by bbcallen** [comment]
This is an experimental option.
