### ISSUE TITLE
最新版ijkplayer android版用eclipse编译问题

### ISSUE THREAD

**Issue by playererer** [Bilibili/ijkplayer#419]
用eclipse将所有工程导入后，会提示如下错误：
styles.xml:7: error: Error: No resource found that matches the given name: attr 'preferenceTheme'.

看了说明需要导入preference-v7，我在android-SDK中的extras中没有找到，代码中会引用里面的东西。
import android.support.v7.preference.PreferenceFragmentCompat;

请问一下preference-v7在哪里？

**Comment by Android4MediaPlayer** [comment]
android: remove appcompat from git, drop support of eclipse

**Comment by bbcallen** [comment]
I think it's a google's mistake.
Hope it can be found in SDK 23.0.1

**Comment by linked67** [comment]
Same problem and i have update everything. Still no way to fix this ?

**Comment by bbcallen** [comment]
No, use Android Studio instead.
If you are using eclipse for your own project, you don't need to import sample module.
