### ISSUE TITLE
rtmp的流延迟很大，有没有什么方法设置减少延迟？

### ISSUE THREAD

**Issue by cracj** [Bilibili/ijkplayer#421]

**Comment by Android4MediaPlayer** [comment]
具体描述清楚点，是指实时性还是指别的？

**Comment by cracj** [comment]
实时性的，相对于源流有10秒以上的延迟

**Comment by lslxdx** [comment]
It's a long story. Maybe you could try as following:
1. enable infinite buffering
2. drop packets that are heavily delayed

**Comment by Android4MediaPlayer** [comment]
用librtmp库，不用ffmpeg自带的 #542

**Comment by jacky1234** [comment]
我怎么就不能使用rtmp协议呢？你用的什么so库啊
