### ISSUE TITLE
为什么我放so库到src/main/jinLibs后，一运行程序还是加载不到库

### ISSUE THREAD

**Issue by Yihaoer** [bilibili/ijkplayer#4213]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.pc.ijkplayertest-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.pc.ijkplayertest-2/lib/arm64, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]] couldn't find "libijkffmpeg.so"

**Comment by fakefacebook** [comment]
have you got solution for this issue?

**Comment by baishuai** [comment]
it is jniLibs, not jinLibs
