### ISSUE TITLE
在小米和魅族部分手机上面会出现播放时间不正确的现象，这个是什么原因呢，有解决方案么？

### ISSUE THREAD

**Issue by Mongolian** [Bilibili/ijkplayer#422]

**Comment by Android4MediaPlayer** [comment]
硬解还是软解？还是跟流有关系，请说明具体点

**Comment by Mongolian** [comment]
软解，跟流没有关系，同样的视频在不同手机上面拿到视频时间长度不一样。在魅族手机上面拿到的时间是一个很大的数字。

**Comment by Android4MediaPlayer** [comment]
请提供你的视频流

**Comment by Mongolian** [comment]
http://pl.youku.com/playlist/m3u8?ts=1440487880&keyframe=0&vid=XNjg4MDkxNDc2&type=3gphd&ep=dSaQGk2FUcYI5SPXgDsYZC%2B2cX8LXJZ0rEiB%2FKY5SMVQG%2BrQmzbWxg%3D%3D&sid=74404878800885133d584&token=2871&ctype=12&ev=1&oip=2035107507


是优酷的M3U8文件，统计时长出了问题

**Comment by Android4MediaPlayer** [comment]
能具体点机器吗 把出问题的机器列举上

**Comment by Mongolian** [comment]
小米手机M1 4.4.4 ,    OPPO R7/4.4.4/, 魅族MX4/4.4.2 目前在这四款手机上面发现的

**Comment by Android4MediaPlayer** [comment]
我测试了魅族MX4/4.4.2 ，没发现问题，总时长是74:46啊，没错吧

**Comment by Android4MediaPlayer** [comment]
@Mongolian 按道理跟软解没关系的，这个时长只跟协议有关的，你不是用最新的ffmpeg吗

**Comment by Mongolian** [comment]
我们用是ffmpeg2.4.6版本编译的，是个会是ffmpeg的bug 么

**Comment by Mongolian** [comment]
请问您使用的是哪个版本编译的呢

**Comment by Android4MediaPlayer** [comment]
最新版本的ffmpeg，时长是HLS协议层求的，你用最新的试一下吧

**Comment by bbcallen** [comment]
Possibly an int <-> long cast bug at java side

**Comment by Android4MediaPlayer** [comment]
bbcallen 这也可能的，请确认下你的类型使用

**Comment by Mongolian** [comment]
bug  getDuration() is native , java side not do anyting

**Comment by toumubaoqiong** [comment]
我也遇到类似的问题，不过问题是视频播放完成的时候，getCurrentPosition和getDuration的时间不一致，有一个视频相差近2秒
