### ISSUE TITLE
播放HTTP站点的MP4文件，文件太大会报错。

### ISSUE THREAD

**Issue by harlanc** [Bilibili/ijkplayer#4221]
文件太大会报下面的错误，3G和4G的文件都不行，2G可以。这个是什么原因导致的呢？？

05-03 16:36:31.358 15308-15358/tv.danmaku.ijk.media.example I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
05-03 16:36:31.358 15308-15358/tv.danmaku.ijk.media.example E/IJKMEDIA: Stream ends prematurely at 0, should be 3073219914
05-03 16:36:31.359 15308-15358/tv.danmaku.ijk.media.example D/IJKMEDIA: Statistics: 0 bytes read, 0 seeks
05-03 16:36:31.359 15308-15358/tv.danmaku.ijk.media.example E/IJKMEDIA: http://192.168.0.130:8080/mp4/merge.mp4: I/O error
05-03 16:36:31.359 15308-15358/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [15358]
05-03 16:36:31.359 15308-15356/tv.danmaku.ijk.media.example D/IJKMEDIA: FFP_MSG_ERROR: 0
05-03 16:36:31.408 15308-15308/tv.danmaku.ijk.media.example E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by harlanc** [comment]
解决了，这个不是IJK的问题，是HTTP server的问题

**Comment by aiven163** [comment]
这个问题是什么原因，我也遇到了，我们服务器直接给的地址，访问mp4文件，求教

**Comment by harlanc** [comment]
我用的是srs的HTTP server，换成python的http server就能播了
