### ISSUE TITLE
ffmpeg 使用第三方库libcurl.a，编译时报错undefined reference to **function

### ISSUE THREAD

**Issue by guoluming** [Bilibili/ijkplayer#4222]
大家有没遇到过，在FFmpeg中链接第三方.a库失败，报undefined reference to **function的错误呀，比如要使用curl，需要链接libcurl.a，放在/usr/local/lib后，在ijkplayer里的config加上export export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --extra-ldflags=-L/usr/local/lib"，不管用
![image](https://user-images.githubusercontent.com/7866118/39612336-0af2583a-4f91-11e8-9acd-ae8591643ae0.png)

**Comment by cocokale** [comment]
你好，请问你的问题解决了吗
