### ISSUE TITLE
how to get state : "MEDIA_INFO_VIDEO_RENDERING_START"?

### ISSUE THREAD

**Issue by pys200603027** [Bilibili/ijkplayer#423]
hi ! I simply use ijkplayer like this(but I never got "MEDIA_INFO_VIDEO_RENDERING_START"):

            ijkMediaPlayer = new IjkMediaPlayer();
				ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "overlay-format", IjkMediaPlayer.SDL_FCC_RV32);
				ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 12);

				ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "http-detect-range-support", 0);

				ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 48);
				ijkMediaPlayer.setMediaCodecEnabled(true);
				ijkMediaPlayer.setOpenSLESEnabled(true);
				
			       ijkMediaPlayer.setDataSource(mVideoPath);
				ijkMediaPlayer.setOnPreparedListener(preparedListener);
				ijkMediaPlayer.setOnInfoListener(infoListener);
				ijkMediaPlayer.setDisplay(holder);
				ijkMediaPlayer.setScreenOnWhilePlaying(true);
				ijkMediaPlayer.prepareAsync();

	OnPreparedListener preparedListener=new OnPreparedListener() {
		@Override
		public void onPrepared(IMediaPlayer mp) {
			mp.start();
		}
	};
	
	
	OnInfoListener infoListener=new OnInfoListener() {
		
		@Override
		public boolean onInfo(IMediaPlayer mp, int what, int extra) {
			Log.d(TAG, "[info] what:"+what);
			return false;
		}
	};

**Comment by Android4MediaPlayer** [comment]
please add MEDIA_INFO_VIDEO_RENDERING_START by yourself

**Comment by bbcallen** [comment]
Added: 5deaf7efba246721f1825d1fd011e714aa144c37

**Comment by niceteg** [comment]
Hello,

It is amazing what one can invent! You're gonna love it, I swear! Read more here <http://wunuresli.tacktrading.com/lnasxhiv>

My Best, teg@ukr.net

**Comment by niceteg** [comment]
Dear friend! 

There is something really surprising I  wanted  to show  you, just take a  look at it <http://ltytojotho.candlsolutions.com/lnugs>

Wishes, teg

**Comment by Android4MediaPlayer** [comment]
404

**Comment by niceteg** [comment]
Hello! 

I've found some fresh and cool stuff, don't miss it up! More info here <http://truthuquulto.naturesbesteggs.com/lntdn>

My best to you, teg

**Comment by niceteg** [comment]
Hey friend, 
I've just  heard  from  a  friend about that  amazing stuff, I'm so  excited, you've  got to take  a look <http://truth.rebarreo.com/lnfioac>
All the best, teg

**Comment by niceteg** [comment]
Greetings! 
Did you hear the latest news? You should definetely  read more info here <http://pleasure.curvyinthecity.com/lntsy>

Best regards, teg

**Comment by niceteg** [comment]
Hello, 

I've got  some good news for you, read more about it  here <http://kevin.wisevsc.com/lnddz/5>


All best, teg

**Comment by niceteg** [comment]
Yo! 


I've recently tried working as  a freelance journalist and wrote some interesting articles, check it out <http://antonia.sanfranciscowatersports.com/lnzh/93>

Best regards, teg

**Comment by niceteg** [comment]
Hello friend, 

I'm so happy to tell you about a  cool place I've been recently,you're gonna enjoy it,  just take  a look <http://erica.xelinkx.com/lnlvr/4>


Bests, teg
