### ISSUE TITLE
HLS video not playing smoothly. Here is my logcat

### ISSUE THREAD

**Issue by mdaslamHossin** [Bilibili/ijkplayer#4244]
05-13 11:03:50.396 20324-20543/com.footylight.android.gg D/IJKMEDIA: FFP_MSG_BUFFERING_START:
05-13 11:03:50.616 20324-20545/com.footylight.android.gg W/IJKMEDIA: skipping 1 segments ahead, expired from playlists
05-13 11:03:50.616 20324-20545/com.footylight.android.gg I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
05-13 11:03:50.617 20324-20545/com.footylight.android.gg I/IJKMEDIA: Hit DNS cache hostname = 185.93.0.129
05-13 11:03:50.617 20324-20545/com.footylight.android.gg I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
05-13 11:03:50.935 20324-20545/com.footylight.android.gg I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
05-13 11:03:51.253 20324-20545/com.footylight.android.gg I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
05-13 11:03:56.680 20324-20543/com.footylight.android.gg D/IJKMEDIA: FFP_MSG_BUFFERING_END:

**Comment by raymond1012** [comment]
net server  issue
