### ISSUE TITLE
如何加载自定义字幕/外挂字幕

### ISSUE THREAD

**Issue by hongyang51** [Bilibili/ijkplayer#4253]
难道只能在Java层根据时间解析写了?

**Comment by developerzjy** [comment]
@hongyang51 请问你字幕怎么解析的，有靠谱点的解析库可用吗

**Comment by hongyang51** [comment]
@developerzjy 没...

**Comment by hongyang51** [comment]
@zhuwei  那就自己解析吧 2014年作者就说的 java层解析或者c层精确解析
