### ISSUE TITLE
能否写一份简单的ijksdl的tutorial

### ISSUE THREAD

**Issue by LittleKey** [Bilibili/ijkplayer#427]
或者可以介绍一下ijksdl与SDL2.0使用上的区别吗？

**Comment by bbcallen** [comment]
Why?
ijksdl is not supposed to be public API of ijkplayer..

**Comment by LittleKey** [comment]
我想在视频加载时，在Textureview上绘制一些自己的动画或者图片，用surfaceview时我能用canvas做，但是如果用Textureview则不能（貌似是因为lockcanvas获取到的canvas不是硬件加速的，所以不能跟ijksdl共用一个anativewindow
所以想用ijksdl来绘制:) 希望能给一点指导thx

p.s: 因为需要截屏之类的功能，所以需要使用textureview

**Comment by bbcallen** [comment]
Use another SurfaceVIew or TextureView.

**Comment by LittleKey** [comment]
我的问题解决了。。thx  :)

**Comment by Android4MediaPlayer** [comment]
如何解决的，应说清楚～

**Comment by LittleKey** [comment]
之前在TextureView上调用lockCanvas来绘图会导致ijksdl那边不能lock anativewindow
现在把TextureView里传给ijkplayer的Surface给保存了一份 然后用Surface.lockCanvas就没问题了
@Android4MediaPlayer  :)

**Comment by garymabin** [comment]
According `Canvas Rendering` chapter [here](https://source.android.com/devices/graphics/architecture.html), direct call to lockCanvas will never use any GPU-render way. TextureView actually tries to use OpenGLES to render more efficiently, while use lockCanvas may break the rule.

**Comment by seu070507** [comment]
@LittleKey 请问你有没有遇到需要opengles 做一些滤镜效果的需求，你是如何处理的？
能否帮忙解答一下？
