### ISSUE TITLE
./compile-ffmpeg.sh all 报错

### ISSUE THREAD

**Issue by Zhangyanshen** [Bilibili/ijkplayer#4278]
执行./compile-ffmpeg.sh all报错，报错如下图：
<img width="570" alt="2018-05-26 1 22 29" src="https://user-images.githubusercontent.com/16679925/40572792-49e0e9b8-60e8-11e8-947d-a4cee053713b.png">

有人能帮忙解决一下吗？谢谢

**Comment by daveleenew** [comment]
两种方法
1.Xcode 降至 9.1
2.去掉这个架构

**Comment by Zhangyanshen** [comment]
@daveleenew 是去掉armv7吗？这个怎么去掉呢？

**Comment by daveleenew** [comment]
修改那个 module文件啊。

**Comment by fengdengyunmie** [comment]
在compile-ffmpeg.sh文件中把
FF_ALL_ARCHS_IOS8_SDK="armv7 armv7s arm64 i386 x86_64"中的armv7去掉修改过后的是
FF_ALL_ARCHS_IOS7_SDK="armv7s arm64 i386 x86_64"

**Comment by Zhangyanshen** [comment]
@daveleenew 好的，谢谢！

**Comment by Zhangyanshen** [comment]
@fengdengyunmie 谢谢，已经可以了！

**Comment by Norma1Coder** [comment]
@Zhangyanshen  请问你是怎么导入ijk到项目的，我通过删除armv7架构也是可以通过编译了，但是在打包合成静态库的时候真机模式就出问题了

**Comment by daveleenew** [comment]
@Zhangyanshen 不会啊。出现啥错误呢

**Comment by guanJiaPo** [comment]
iPhone6以上和模拟器都没问题, 在iPhone5上就报错了, 不支持armv7 , "ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

**Comment by daveleenew** [comment]
因为Xcode 最新版本是不支持armv7 编译的。两种解决方案:

1.xcode 降级到 9.1
2.ijkplayer删除 armv7

**Comment by magic3584** [comment]
@Destinyxl 我也遇到了这个问题，真机打包就会报错

**Comment by daveleenew** [comment]
这个问题不是说了解决的方案了吗？

删除不支持的架构就可以了撒

**Comment by magic3584** [comment]
iPhone 5 支持到 10 的啊，不能抛弃吧

**Comment by daveleenew** [comment]
那就建議你下載別人已經編譯好的庫 那麼就可以支持了
