### ISSUE TITLE
视频播放比例能否控制？(使用setAspectRatio无效)

### ISSUE THREAD

**Issue by SteveKin3** [bilibili/ijkplayer#4285]
部分终端底层播放比例是全屏拉伸的，一些1080*800的影院显示比例的影片会被拉伸全屏，导致画面变形，能否在应用层解决这个问题？

**Comment by wnpllrzodiac** [comment]
获取视频高宽，和播放设备高宽，根据尺寸自行计算比例。可以 wnpllr@gmail.com 咨询
