### ISSUE TITLE
android硬解码只有音频没有视频

### ISSUE THREAD

**Issue by zhouxiuwe** [Bilibili/ijkplayer#429]
软解能正常播放，切换成硬解码ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec",1)，只有音频没有视频

**Comment by Android4MediaPlayer** [comment]
机型及详细日志

**Comment by zhouxiuwe** [comment]
loadLibrary:225 Loading OMX library libOmxVideo.so.
08-28 13:21:36.860: I/omx_core(3443): Core library has 20 components
08-28 13:21:36.860: E/OMXMaster(3443): A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
08-28 13:21:36.860: W/ALooperRoster(3443): ALooper::handler_id ALooperRoster::registerHandler 10
08-28 13:21:36.860: I/AmSoftDec(3443): get mimetype : video/avc
08-28 13:21:36.860: I/AmFFmpegCodec(3443): CreateCodec for codecMime : video/avc
08-28 13:21:36.860: E/OMXNodeInstance(3443): OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
08-28 13:21:36.860: W/OMXNodeInstance(3443): OMX_GetExtensionIndex OMX.google.android.index.prepareForAdaptivePlayback failed
08-28 13:21:36.860: I/ALooperRoster(3443): ALooperRoster unregisterHandler handlerID=a
08-28 13:21:36.860: I/omx_core(3443): OMX_Deinit 96 gInitCount=0
08-28 13:21:36.870: I/IjkMediaCodecInfo(3443):  Baseline Profile Level 51 (1,32768)
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.vp8.decoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):     mime: video/x-vnd.on2.vp8
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.vp9.decoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):     mime: video/x-vnd.on2.vp9
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.rm.decoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):     mime: video/rm
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.wmv2.decoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):     mime: video/wmv2
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.wmv1.decoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):     mime: video/wmv1
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: AML.google.ac3.decoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):     mime: audio/ac3
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: AML.google.ec3.decoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):     mime: audio/eac3
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.mp2.decoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):     mime: audio/mpeg-L2
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.mp3.decoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):     mime: audio/mpeg
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: AML.google.dtshd.decoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):     mime: audio/dtshd
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.amrnb.encoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.amrwb.encoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.aac.encoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.flac.encoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.mpeg4.encoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.h263.encoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.amlogic.video.encoder.avc
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.h264.encoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.vp8.encoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: AACEncoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.raw.decoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):     mime: audio/raw
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.vp6.decoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):     mime: video/x-vnd.on2.vp6
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.vp6a.decoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):     mime: video/x-vnd.on2.vp6a
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.vp6f.decoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):     mime: video/x-vnd.on2.vp6f
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.h265.decoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):     mime: video/hevc
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):   found codec: OMX.google.wmv2.decoder
08-28 13:21:36.870: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443):     mime: video/wmv2
08-28 13:21:36.870: I/tv.danmaku.ijk.media.player.IjkMediaPlayer(3443): selected codec: OMX.amlogic.avc.decoder.awesome rank=800
08-28 13:21:36.870: D/IJKMEDIA(3443): SDL_AMediaCodecJava_createByCodecName
08-28 13:21:36.870: W/ALooperRoster(3443): ALooper::handler_id ALooperRoster::registerHandler 11
08-28 13:21:36.870: W/ALooperRoster(3443): ALooper::handler_id ALooperRoster::registerHandler 12
08-28 13:21:36.870: I/OMXClient(3443): Using client-side OMX mux.
08-28 13:21:36.870: D/OmxComponentManagerImpl(141): getEntryByName_2_num=3, componentName:OMX.amlogic.avc.decoder.awesome
08-28 13:21:36.880: D/OmxComponentManagerImpl(141): amstream_vbuf is free
08-28 13:21:36.880: D/OmxComponentManagerImpl(141): ret =0,*pEntry->mRoleNames=video_decoder.avc.awesome
08-28 13:21:36.880: D/OmxComponentManagerImpl(141): ionvide is free
08-28 13:21:36.880: D/OmxComponentManagerImpl(141): ready for creat omx decoder component
08-28 13:21:36.880: V/AmlogicVideoDecoderAwesome(141): media.omx.latency is not set used def=0.600000
08-28 13:21:36.880: E/OmxLogConf(141): Can not read property media.omx.log_levels, using 255
08-28 13:21:36.880: D/OmxComponentManagerImpl(141): IncreaseEntryNumByName pEntry->mNum=3, pEntry->mMaxNum:4,componentName:OMX.amlogic.avc.decoder.awesome
08-28 13:21:36.880: I/omx_core(141): OMX_getHandle_num=4
08-28 13:21:36.880: D/IJKMEDIA(3443): SDL_AMediaCodecJava_init
08-28 13:21:36.880: D/IJKMEDIA(3443): SDL_AMediaCodecJava_configure_surface
08-28 13:21:36.880: E/IJKMEDIA(3443): configure 0x1d300356 0x1d300362
08-28 13:21:36.880: D/OmxComponent(141): getExtensionIndex 1021 name="OMX.google.android.index.storeMetaDataInBuffers"
08-28 13:21:36.880: D/OmxVideoDecoder(141): setParameter 463 OMX_IndexAndroidStoreMetadataInBuffers
08-28 13:21:36.880: E/OMXNodeInstance(141): OMX_SetParameter() failed for StoreMetaDataInBuffers: 0x80001001
08-28 13:21:36.880: E/ACodec(3443): [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
08-28 13:21:36.890: V/OmxVideoDecoder(141): getParameter 261 nParamIndex=0x6000001
08-28 13:21:36.890: D/OmxVideoDecoder(141): setParameter nPortIndex 0 CompFmt 0x7 ColorFmt 0
08-28 13:21:36.890: V/OmxVideoDecoder(141): getParameter 261 nParamIndex=0x6000001
08-28 13:21:36.890: D/OmxVideoDecoder(141): setParameter nPortIndex 1 CompFmt 0 ColorFmt 0x15
08-28 13:21:36.890: V/OmxVideoDecoder(141): getParameter 261 nParamIndex=0x2000001
08-28 13:21:36.890: D/OmxVideoDecoder(141): setParameter nPortIndex 0 nFrameWidth 1280 nFrameHeight 720 nSliceHeight 16
08-28 13:21:36.890: V/OmxVideoDecoder(141): getParameter 261 nParamIndex=0x2000001
08-28 13:21:36.890: V/OmxVideoDecoder(141): mUseNativeBuffers 0
08-28 13:21:36.890: V/OmxVideoDecoder(141): port.mDef.nBufferSize 0
08-28 13:21:36.890: D/OmxVideoDecoder(141): setParameter nPortIndex 1 nFrameWidth 1280 nFrameHeight 720 nSliceHeight 720
08-28 13:21:36.890: V/OmxVideoDecoder(141): mUseNativeBuffers 0
08-28 13:21:36.890: V/OmxVideoDecoder(141): port.mDef.nBufferSize 1382400
08-28 13:21:36.890: V/OmxVideoDecoder(141): getParameter 261 nParamIndex=0x2000001
08-28 13:21:36.890: I/ACodec(3443): onConfigureComponent native-window finished OMX.amlogic.avc.decoder.awesome 
08-28 13:21:36.890: D/OmxComponent(141): getExtensionIndex 1021 name="OMX.google.android.index.enableAndroidNativeBuffers"
08-28 13:21:36.890: V/OmxVideoDecoder(141): setParameter 457 EnableNativeBuffers 1
08-28 13:21:36.890: V/OmxVideoDecoder(141): mUseNativeBuffers 1
08-28 13:21:36.890: D/AmlogicVideoDecoderAwesome(141): get native buffer info NV:w:1280,h:720..
08-28 13:21:36.890: V/OmxVideoDecoder(141): updatePort:portDef.format.video.nFrameWidth=1280,portDef.format.video.nFrameHeight=720
08-28 13:21:36.890: V/OmxVideoDecoder(141): port.mDef.nBufferSize 1382400
08-28 13:21:36.890: D/IJKMEDIA(3443): SDL_AMediaCodecJava_start
08-28 13:21:36.890: V/OmxVideoDecoder(141): getParameter 261 nParamIndex=0x2000001
08-28 13:21:36.890: V/OmxVideoDecoder(141): getParameter 261 nParamIndex=0x2000001
08-28 13:21:36.890: V/OmxVideoDecoder(141): mUseNativeBuffers 1
08-28 13:21:36.890: D/AmlogicVideoDecoderAwesome(141): get native buffer info NV:w:1280,h:720..
08-28 13:21:36.890: V/OmxVideoDecoder(141): updatePort:portDef.format.video.nFrameWidth=1280,portDef.format.video.nFrameHeight=720
08-28 13:21:36.890: V/OmxVideoDecoder(141): port.mDef.nBufferSize 1382400
08-28 13:21:36.890: D/OmxComponent(141): getExtensionIndex 1021 name="OMX.google.android.index.getAndroidNativeBufferUsage"
08-28 13:21:36.890: V/OmxVideoDecoder(141): getParameter 261 nParamIndex=0x7f000001
08-28 13:21:36.890: D/OmxVideoDecoder(141): setParameter nPortIndex 1 nFrameWidth 1280 nFrameHeight 720 nSliceHeight 720
08-28 13:21:36.890: V/OmxVideoDecoder(141): mUseNativeBuffers 1
08-28 13:21:36.890: D/AmlogicVideoDecoderAwesome(141): get native buffer info NV:w:1280,h:720..
08-28 13:21:36.890: V/OmxVideoDecoder(141): updatePort:portDef.format.video.nFrameWidth=1280,portDef.format.video.nFrameHeight=720
08-28 13:21:36.890: V/OmxVideoDecoder(141): port.mDef.nBufferSize 1382400
08-28 13:21:36.890: E/ion(138): ioctl c0144900 failed with code -1: Out of memory
08-28 13:21:36.890: E/[Gralloc-ERROR](138): int gralloc_alloc_buffer(alloc_device_t*, size_t, int, const native_handle_t**):119 Failed to ion_alloc from ion_client:20
08-28 13:21:36.890: W/GraphicBufferAllocator(138): alloc(1280, 720, 17, 20002900, ...) failed -1 (Operation not permitted)
08-28 13:21:36.890: E/(138): GraphicBufferAlloc::createGraphicBuffer(w=1280, h=720) failed (Operation not permitted), handle=0x0
08-28 13:21:36.890: E/BufferQueue(138): [SurfaceView] dequeueBuffer: SurfaceComposer::createGraphicBuffer failed
08-28 13:21:36.890: E/ACodec(3443): dequeueBuffer failed: Operation not permitted (1)
08-28 13:21:36.890: E/ACodec(3443): Failed to allocate buffers after transitioning to IDLE state (error 0xffffffff)
08-28 13:21:36.890: E/MediaCodec(3443): Codec reported an error. (omx error 0x80001001, internalError -1)
08-28 13:21:36.890: W/System.err(3443): java.lang.IllegalStateException: start failed
08-28 13:21:36.890: W/System.err(3443): 	at android.media.MediaCodec.start(Native Method)
08-28 13:21:36.890: W/System.err(3443): 	at dalvik.system.NativeStart.run(Native Method)
08-28 13:21:36.890: E/IJKMEDIA(3443): SDL_AMediaCodecJava_start: start failed
08-28 13:21:36.890: I/IJKMEDIA(3443): VideoCodec: MediaCodec, OMX.amlogic.avc.decoder.awesome
08-28 13:21:36.890: W/IJKMEDIA(3443): fps: 29.970030 (normal)
08-28 13:21:36.890: D/IJKMEDIA(3443): ijkmp_get_msg: FFP_MSG_PREPARED
08-28 13:21:36.890: D/IJKMEDIA(3443): FFP_MSG_PREPARED:
08-28 13:21:36.890: D/IJKMEDIA(3443): FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
08-28 13:21:36.890: D/IJKMEDIA(3443): FFP_MSG_SAR_CHANGED: 1, 1
08-28 13:21:36.890: D/tv.danmaku.ijk.media.widget.IjkVideoView(3443): onPrepared
08-28 13:21:36.890: D/VideoPlayerActivity(3443): ====onPrepared=====
08-28 13:21:36.900: D/VideoIjkPlayerActivity.showLiveLeftMenu(L:979)(3443): showLiveLeftMenu mPosition=0
08-28 13:21:36.900: D/IjkVideoView.setVideoScale(L:484)(3443): setVideoScale
08-28 13:21:36.900: D/ScreenSize(3443): coverScreen
08-28 13:21:36.910: D/VideoIjkPlayerActivity$6.onMediaPlayerCreated(L:3205)(3443): onMediaPlayerCreated--- mp=tv.danmaku.ijk.media.player.IjkMediaPlayer@43407000
08-28 13:21:36.910: D/MyMediaPlayer.<init>(L:31)(3443): MyMediaPlayer mp=tv.danmaku.ijk.media.player.IjkMediaPlayer@43407000
08-28 13:21:36.910: I/IJKMEDIA(3443): SDL_RunThread: [4184] ff_video_dec
08-28 13:21:36.910: W/System.err(3443): java.lang.IllegalStateException
08-28 13:21:36.910: W/System.err(3443): 	at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
08-28 13:21:36.910: W/System.err(3443): 	at dalvik.system.NativeStart.run(Native Method)
08-28 13:21:36.910: I/IJKMEDIA(3443): SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
08-28 13:21:36.910: W/System.err(3443): java.lang.IllegalStateException
08-28 13:21:36.910: W/System.err(3443): 	at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
08-28 13:21:36.910: W/System.err(3443): 	at dalvik.system.NativeStart.run(Native Method)
08-28 13:21:36.910: I/IJKMEDIA(3443): SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
08-28 13:21:36.910: I/IJKMEDIA(3443): SDL_RunThread: [4186] amediacodec_input_thread
08-28 13:21:36.920: D/tv.danmaku.ijk.media.widget.IjkVideoView(3443): onVideoSizeChanged: (1280x720)
08-28 13:21:36.920: D/tv.danmaku.ijk.media.widget.IjkVideoView(3443): onVideoSizeChanged: (1280x720)
08-28 13:21:36.940: D/ijkplayer(3443): ====surfaceChanged====
08-28 13:21:36.940: D/IJKMEDIA(3443): IjkMediaPlayer_setVideoSurface
08-28 13:21:36.940: D/IJKMEDIA(3443): ijkmp_set_android_surface(surface=0xb9a0001d)
08-28 13:21:36.940: D/IJKMEDIA(3443): ffpipeline_set_surface()
08-28 13:21:36.940: D/IJKMEDIA(3443): ijkmp_set_android_surface(surface=0xb9a0001d)=void
08-28 13:21:36.960: D/GvtvIME(710): onFinishInput.
08-28 13:21:36.960: D/GvtvIME(710): onStartInput  ccontentType: 0 Restarting:false

**Comment by Android4MediaPlayer** [comment]
08-28 13:21:36.890: E/(138): GraphicBufferAlloc::createGraphicBuffer(w=1280, h=720) failed (Operation not permitted), handle=0x0
08-28 13:21:36.890: E/BufferQueue(138): [SurfaceView] dequeueBuffer: SurfaceComposer::createGraphicBuffer failed
08-28 13:21:36.890: E/ACodec(3443): dequeueBuffer failed: Operation not permitted (1)
08-28 13:21:36.890: E/ACodec(3443): Failed to allocate buffers after transitioning to IDLE state (error 0xffffffff)
08-28 13:21:36.890: E/MediaCodec(3443): Codec reported an error. (omx error 0x80001001, internalError -1)

**Comment by bbcallen** [comment]
Seems device's bug.
Better use AndroidMediaPlayer on am logic.

**Comment by qazmoon** [comment]
不是自动软解吗？应该有软解的视频输出啊

**Comment by Android4MediaPlayer** [comment]
@bbcallen @qazmoon 只有在创建失败才会切换的
