### ISSUE TITLE
如何配置module.sh，能够支持常用的音频格式(包括无损)，同时屏蔽掉所有视频格式,，让so文件最小

### ISSUE THREAD

**Issue by rRemix** [Bilibili/ijkplayer#4291]

**Comment by rRemix** [comment]
@wnpllrzodiac 我配置出来的要么编译有问题，要么编译后有些格式如ape无法播放...请问能提供配置好的medule.sh吗？

**Comment by wnpllrzodiac** [comment]
有时间帮你看下，最近比较忙

**Comment by rRemix** [comment]
@wnpllrzodiac 非常感谢

**Comment by wnpllrzodiac** [comment]
[module_audio.sh.txt](https://github.com/Bilibili/ijkplayer/files/2132390/module_audio.sh.txt)

You can try build this version.
Only verify libffmepg.so and ijkplayer.so build done.
Not verify app play audio files.(Will do it later)
Now libffmpeg.so file size is about 1.x MB, can reduce smaller if some audio format NOT required.

**Comment by wnpllrzodiac** [comment]
```
Young And Beautiful.mp3
High歌_黄玲.wav
邓紫棋-泡沫.flac
陈慧娴-飘雪.ape
```
verified passed.

**Comment by wnpllrzodiac** [comment]
@rRemix 已更新状态

**Comment by rRemix** [comment]
@wnpllrzodiac 感谢感谢。

**Comment by rRemix** [comment]
@wnpllrzodiac 大佬.似乎m4a格式的歌曲播放不了。。能不能再麻烦看看，我自己尝试配置了下，怎么都播放不了m4a的。

**Comment by rRemix** [comment]
06-29 15:51:17.715 3735-3735/remix.myplayer D/IJKMEDIA: IjkMediaPlayer_getAudioSessionId
    ijkmp_android_get_audio_session_id()
    ijkmp_android_get_audio_session_id()=321
06-29 15:51:17.715 3735-3735/remix.myplayer D/IJKMEDIA: IjkMediaPlayer_getAudioSessionId
    ijkmp_android_get_audio_session_id()
    ijkmp_android_get_audio_session_id()=321
06-29 15:51:17.717 3735-3735/remix.myplayer D/IJKMEDIA: IjkMediaPlayer_reset
    IjkMediaPlayer_release
    ijkmp_set_android_surface(surface=0x0)
    ffpipeline_set_surface()
06-29 15:51:17.718 3735-3735/remix.myplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
    ijkmp_shutdown_l()
06-29 15:51:17.718 3735-4506/remix.myplayer D/IJKMEDIA: message_loop exit
06-29 15:51:17.718 3735-4506/remix.myplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4506]
06-29 15:51:17.718 3735-4507/remix.myplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4507]
06-29 15:51:17.724 3735-4508/remix.myplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4508]
06-29 15:51:17.725 3735-4511/remix.myplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4511]
06-29 15:51:17.735 3735-4510/remix.myplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4510]
06-29 15:51:17.737 3735-3735/remix.myplayer D/IJKMEDIA: ijkmp_shutdown_l()=void
    IjkMediaPlayer_native_setup
06-29 15:51:17.737 3735-3735/remix.myplayer I/IJKMEDIA: av_version_info: ff3.4--ijk0.8.7--20180103--001
    ijk_version_info: k0.8.8
06-29 15:51:17.738 3735-3735/remix.myplayer D/IJKMEDIA: ffpipeline_create_from_android()
    ijkmp_set_inject_opaque(0x2db2)
    ijkmp_set_inject_opaque()=void
    ijkmp_set_ijkio_inject_opaque(0x2db2)
    ijkmp_set_ijkio_inject_opaque()=void
    ijkmp_android_set_mediacodec_select_callback()
    ffpipeline_set_mediacodec_select_callback
    ijkmp_android_set_mediacodec_select_callback()=void
06-29 15:51:17.739 3735-3735/remix.myplayer D/IJKMEDIA: ijkmp_dec_ref(): ref=0
    ijkmp_shutdown_l()
    ijkmp_shutdown_l()=void
06-29 15:51:17.740 3735-3735/remix.myplayer D/IJKMEDIA: IjkMediaPlayer_setOptionLong
    IjkMediaPlayer_setDataSourceAndHeaders
06-29 15:51:17.740 3735-3735/remix.myplayer V/IJKMEDIA: setDataSource: path /storage/emulated/0/Music/Test/满汉全席音乐团队 - 樱花樱花想见你 [mqms2].m4a
06-29 15:51:17.740 3735-3735/remix.myplayer D/IJKMEDIA: ijkmp_set_data_source(url="/storage/emulated/0/Music/Test/满汉全席音乐团队 - 樱花樱花想见你 [mqms2].m4a")
    ijkmp_set_data_source(url="/storage/emulated/0/Music/Test/满汉全席音乐团队 - 樱花樱花想见你 [mqms2].m4a")=0
    IjkMediaPlayer_prepareAsync
    ijkmp_prepare_async()
06-29 15:51:17.740 3735-3735/remix.myplayer I/IJKMEDIA: ===== versions =====
    ijkplayer    : k0.8.8
    FFmpeg       : ff3.4--ijk0.8.7--20180103--001
    libavutil    : 55.78.100
06-29 15:51:17.740 3735-4539/remix.myplayer I/IJKMEDIA: SDL_RunThread: [4539] ff_msg_loop
06-29 15:51:17.740 3735-3735/remix.myplayer I/IJKMEDIA: libavcodec   : 57.107.100
    libavformat  : 57.83.100
06-29 15:51:17.740 3735-4539/remix.myplayer D/IJKMEDIA: message_loop
06-29 15:51:17.740 3735-3735/remix.myplayer I/IJKMEDIA: libswscale   : 4.8.100
    libswresample: 2.9.100
    ===== options =====
    player-opts : start-on-prepared            = 0
    format-opts : ijkapplication               = -719156592
    format-opts : ijkiomanager                 = -700730112
    ===================
06-29 15:51:17.741 3735-3735/remix.myplayer D/IJKMEDIA: ijkmp_prepare_async()=0
06-29 15:51:17.741 3735-4539/remix.myplayer D/IJKMEDIA: FFP_MSG_FLUSH:
06-29 15:51:17.741 3735-4540/remix.myplayer I/IJKMEDIA: SDL_RunThread: [4540] ff_vout
06-29 15:51:17.741 3735-4541/remix.myplayer I/IJKMEDIA: SDL_RunThread: [4541] ff_read
06-29 15:51:17.783 3735-4541/remix.myplayer E/IJKMEDIA: /storage/emulated/0/Music/Test/满汉全席音乐团队 - 樱花樱花想见你 [mqms2].m4a: Invalid data found when processing input
06-29 15:51:17.783 3735-4541/remix.myplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4541]
06-29 15:51:17.783 3735-4539/remix.myplayer D/IJKMEDIA: FFP_MSG_ERROR: 0
06-29 15:51:17.783 3735-3735/remix.myplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
06-29 15:51:17.783 3735-3735/remix.myplayer D/IJKMEDIA: IjkMediaPlayer_release
    ijkmp_set_android_surface(surface=0x0)
    ffpipeline_set_surface()
    ijkmp_set_android_surface(surface=0x0)=void
    ijkmp_shutdown_l()
06-29 15:51:17.783 3735-4539/remix.myplayer D/IJKMEDIA: message_loop exit
06-29 15:51:17.784 3735-4539/remix.myplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4539]
06-29 15:51:17.792 3735-4540/remix.myplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4540]
06-29 15:51:17.792 3735-3735/remix.myplayer D/IJKMEDIA: ijkmp_shutdown_l()=void
    ijkmp_dec_ref(): ref=0
    ijkmp_shutdown_l()
    ijkmp_shutdown_l()=void
06-29 15:51:17.793 3735-3735/remix.myplayer D/IJKMEDIA: IjkMediaPlayer_native_setup
06-29 15:51:17.793 3735-3735/remix.myplayer I/IJKMEDIA: av_version_info: ff3.4--ijk0.8.7--20180103--001
    ijk_version_info: k0.8.8
06-29 15:51:17.793 3735-3735/remix.myplayer D/IJKMEDIA: ffpipeline_create_from_android()
    ijkmp_set_inject_opaque(0x2db6)
    ijkmp_set_inject_opaque()=void
    ijkmp_set_ijkio_inject_opaque(0x2db6)
    ijkmp_set_ijkio_inject_opaque()=void
    ijkmp_android_set_mediacodec_select_callback()
    ffpipeline_set_mediacodec_select_callback
    ijkmp_android_set_mediacodec_select_callback()=void

**Comment by wnpllrzodiac** [comment]
should add
`export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=mp4"`

**Comment by wnpllrzodiac** [comment]
[module_audio.sh.txt](https://github.com/Bilibili/ijkplayer/files/2157417/module_audio.sh.txt)

**Comment by wnpllrzodiac** [comment]
`02朋友.m4a `
verified passed.

@rRemix

**Comment by rosickyxqc** [comment]
根据你配置文件，现在无法播放opus格式，请问如何处理？

**Comment by rosickyxqc** [comment]
> 根据你配置文件，现在无法播放opus格式，请问如何处理？

已解决。

**Comment by xilost** [comment]
@wnpllrzodiac 按照你的配置配了，WAV还是播放不了。
http://gddx.sc.chinaz.net/Files/DownLoad/sound1/201908/11811.wav 这个文件。

**Comment by wnpllrzodiac** [comment]
明天帮你看一下

**Comment by wnpllrzodiac** [comment]
Input #0, wav, from 'http://gddx.sc.chinaz.net/Files/DownLoad/sound1/201908/11811.wav':
  Duration: 00:00:10.43, bitrate: 705 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 22050 Hz, 2 channels, s16, 705 kb/s

**Comment by wnpllrzodiac** [comment]
我用我最后一次更新的配置，跑了下。你的wav正常播放的啊。
是一声鸟叫。

```
08-09 17:10:50.598: I/System(6073): core_booster, getBoosterConfig = false
08-09 17:10:56.288: I/IjkSDKPlayerActivity(6073): Java: screen 1080 x 1812
08-09 17:10:56.306: I/J4A(6073): API-Level: 23
08-09 17:10:56.468: I/IJKMEDIA(6073): av_version_info: ff3.4--ijk0.8.7--20180103--001
08-09 17:10:56.468: I/IJKMEDIA(6073): ijk_version_info: k0.8.8
08-09 17:10:56.473: I/IjkSDKPlayerActivity(6073): use normal config
08-09 17:10:56.474: I/IJKMEDIA(6073): ===== versions =====
08-09 17:10:56.474: I/IJKMEDIA(6073): ijkplayer    : k0.8.8
08-09 17:10:56.474: I/IJKMEDIA(6073): FFmpeg       : ff3.4--ijk0.8.7--20180103--001
08-09 17:10:56.474: I/IJKMEDIA(6073): libavutil    : 55.78.100
08-09 17:10:56.474: I/IJKMEDIA(6073): libavcodec   : 57.107.100
08-09 17:10:56.474: I/IJKMEDIA(6073): SDL_RunThread: [6128] ff_msg_loop
08-09 17:10:56.474: I/IJKMEDIA(6073): libavformat  : 57.83.100
08-09 17:10:56.474: I/IJKMEDIA(6073): libswscale   : 4.8.100
08-09 17:10:56.474: I/IJKMEDIA(6073): libswresample: 2.9.100
08-09 17:10:56.474: I/IJKMEDIA(6073): ===== options =====
08-09 17:10:56.474: I/IJKMEDIA(6073): player-opts : soundtouch                   = 1
08-09 17:10:56.474: I/IJKMEDIA(6073): player-opts : max_cached_duration          = 0
08-09 17:10:56.474: I/IJKMEDIA(6073): player-opts : infbuf                       = 0
08-09 17:10:56.474: I/IJKMEDIA(6073): player-opts : packet-buffering             = 1
08-09 17:10:56.474: I/IJKMEDIA(6073): format-opts : ijkapplication               = -1404681824
08-09 17:10:56.474: I/IJKMEDIA(6073): format-opts : ijkiomanager                 = -1404681752
08-09 17:10:56.474: I/IJKMEDIA(6073): codec-opts  : skip_frame                   = 0
08-09 17:10:56.474: I/IJKMEDIA(6073): codec-opts  : skip_loop_filter             = 0
08-09 17:10:56.474: I/IJKMEDIA(6073): ===================
08-09 17:10:56.476: I/IJKMEDIA(6073): SDL_RunThread: [6129] ff_vout
08-09 17:10:56.477: I/IjkSDKPlayerActivity(6073): surfaceChanged: fmt 4, 1794 x 1080
08-09 17:10:56.483: I/IJKMEDIA(6073): SDL_RunThread: [6130] ff_read
08-09 17:10:56.486: I/tv.danmaku.ijk.media.player.IjkMediaPlayer(6073): onNativeInvoke 1
08-09 17:10:56.518: I/tv.danmaku.ijk.media.player.IjkMediaPlayer(6073): onNativeInvoke 131073
08-09 17:10:56.664: I/tv.danmaku.ijk.media.player.IjkMediaPlayer(6073): onNativeInvoke 131074
08-09 17:10:56.664: I/IJKMEDIA(6073): Add dns cache hostname = gddx.sc.chinaz.net, ip = 183.2.247.192
08-09 17:10:56.753: I/tv.danmaku.ijk.media.player.IjkMediaPlayer(6073): onNativeInvoke 2
08-09 17:10:56.792: E/IJKMEDIA(6073): Option ijkiomanager not found.
08-09 17:10:56.808: I/IjkSDKPlayerActivity(6073): onInfo: 10005 0
08-09 17:10:57.218: I/IJKMEDIA(6073): max_frame_duration: 10.000
08-09 17:10:57.218: I/IJKMEDIA(6073): Input #0, wav, from 'http://gddx.sc.chinaz.net/Files/DownLoad/sound1/201908/11811.wav':
08-09 17:10:57.218: I/IJKMEDIA(6073):   Duration: 
08-09 17:10:57.218: I/IJKMEDIA(6073): 00:00:10.43
08-09 17:10:57.218: I/IJKMEDIA(6073): , bitrate: 
08-09 17:10:57.218: I/IJKMEDIA(6073): 705 kb/s
08-09 17:10:57.219: I/IJKMEDIA(6073):     Stream #0:0
08-09 17:10:57.219: I/IJKMEDIA(6073): : Audio: pcm_s16le ([1][0][0][0] / 0x0001), 22050 Hz, 2 channels, s16, 705 kb/s
08-09 17:10:57.219: I/IJKMEDIA(6073): SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
08-09 17:10:57.219: I/IJKMEDIA(6073): SDL_Android_AudioTrack: ENCODING_PCM_16BIT
08-09 17:10:57.227: I/IjkSDKPlayerActivity(6073): onInfo: 10006 0
08-09 17:10:57.237: I/IJKMEDIA(6073): SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(0.000000,1.000000)
08-09 17:10:57.238: I/IJKMEDIA(6073): audio_session_id = 622
08-09 17:10:57.239: I/IJKMEDIA(6073): SDL_RunThread: [6134] ff_aout_android
08-09 17:10:57.239: I/IJKMEDIA(6073): AudioCodec: avcodec, pcm_s16le
08-09 17:10:57.240: I/IJKMEDIA(6073): SDL_RunThread: [6135] ff_audio_dec
08-09 17:10:57.247: I/IjkSDKPlayerActivity(6073): onInfo: 10007 0
08-09 17:10:57.249: I/IjkSDKPlayerActivity(6073): onPrepared
08-09 17:10:57.256: I/AudioTrack-JNI(6073): audioTrack continuously zero data counter >= 10, send pause/stop state to pg, counter: 0
08-09 17:10:57.300: I/IjkSDKPlayerActivity(6073): onInfo: 10003 0
08-09 17:10:57.301: I/IjkSDKPlayerActivity(6073): onInfo: 10002 0
08-09 17:10:57.421: I/AudioTrack-JNI(6073): audioTrack send start state to pg
08-09 17:10:59.506: I/IjkSDKPlayerActivity(6073): surfaceChanged: fmt 4, 1080 x 1812
08-09 17:10:59.639: I/IJKMEDIA(6073): SDL_JNI_DetachThreadEnv: [6128]
08-09 17:10:59.644: I/IJKMEDIA(6073): SDL_JNI_DetachThreadEnv: [6129]
08-09 17:10:59.737: I/IJKMEDIA(6073): SDL_JNI_DetachThreadEnv: [6130]
08-09 17:10:59.737: I/IJKMEDIA(6073): SDL_JNI_DetachThreadEnv: [6135]
08-09 17:10:59.740: I/IJKMEDIA(6073): SDL_JNI_DetachThreadEnv: [6134]
08-09 17:11:32.770: I/IjkSDKPlayerActivity(6073): Java: screen 1080 x 1812
08-09 17:11:32.771: W/IJKMEDIA(6073): monstartup already called
08-09 17:11:32.939: I/IJKMEDIA(6073): av_version_info: ff3.4--ijk0.8.7--20180103--001
08-09 17:11:32.939: I/IJKMEDIA(6073): ijk_version_info: k0.8.8
08-09 17:11:32.943: I/IjkSDKPlayerActivity(6073): use normal config
08-09 17:11:32.943: I/IJKMEDIA(6073): ===== versions =====
08-09 17:11:32.943: I/IJKMEDIA(6073): ijkplayer    : k0.8.8
08-09 17:11:32.943: I/IJKMEDIA(6073): FFmpeg       : ff3.4--ijk0.8.7--20180103--001
08-09 17:11:32.943: I/IJKMEDIA(6073): libavutil    : 55.78.100
08-09 17:11:32.943: I/IJKMEDIA(6073): libavcodec   : 57.107.100
08-09 17:11:32.943: I/IJKMEDIA(6073): libavformat  : 57.83.100
08-09 17:11:32.943: I/IJKMEDIA(6073): libswscale   : 4.8.100
08-09 17:11:32.943: I/IJKMEDIA(6073): SDL_RunThread: [6322] ff_msg_loop
08-09 17:11:32.943: I/IJKMEDIA(6073): libswresample: 2.9.100
08-09 17:11:32.943: I/IJKMEDIA(6073): ===== options =====
08-09 17:11:32.943: I/IJKMEDIA(6073): player-opts : soundtouch                   = 1
08-09 17:11:32.943: I/IJKMEDIA(6073): player-opts : max_cached_duration          = 0
08-09 17:11:32.943: I/IJKMEDIA(6073): player-opts : infbuf                       = 0
08-09 17:11:32.943: I/IJKMEDIA(6073): player-opts : packet-buffering             = 1
08-09 17:11:32.943: I/IJKMEDIA(6073): format-opts : ijkapplication               = -1404720176
08-09 17:11:32.943: I/IJKMEDIA(6073): format-opts : ijkiomanager                 = -1403161592
08-09 17:11:32.943: I/IJKMEDIA(6073): codec-opts  : skip_frame                   = 0
08-09 17:11:32.943: I/IJKMEDIA(6073): codec-opts  : skip_loop_filter             = 0
08-09 17:11:32.943: I/IJKMEDIA(6073): ===================
08-09 17:11:32.946: I/IJKMEDIA(6073): SDL_RunThread: [6323] ff_vout
08-09 17:11:32.946: I/IjkSDKPlayerActivity(6073): surfaceChanged: fmt 4, 1794 x 1080
08-09 17:11:32.951: I/IJKMEDIA(6073): SDL_RunThread: [6324] ff_read
08-09 17:11:32.952: I/tv.danmaku.ijk.media.player.IjkMediaPlayer(6073): onNativeInvoke 1
08-09 17:11:32.952: I/IJKMEDIA(6073): Hit DNS cache hostname = gddx.sc.chinaz.net
08-09 17:11:32.952: I/tv.danmaku.ijk.media.player.IjkMediaPlayer(6073): onNativeInvoke 131073
08-09 17:11:33.954: I/tv.danmaku.ijk.media.player.IjkMediaPlayer(6073): onNativeInvoke 131074
08-09 17:11:34.006: I/tv.danmaku.ijk.media.player.IjkMediaPlayer(6073): onNativeInvoke 2
08-09 17:11:34.008: W/IjkSDKPlayerActivity(6073): http open too slow: 1054 msec
08-09 17:11:34.036: E/IJKMEDIA(6073): Option ijkiomanager not found.
08-09 17:11:34.068: I/IjkSDKPlayerActivity(6073): onInfo: 10005 0
08-09 17:11:34.259: I/IJKMEDIA(6073): max_frame_duration: 10.000
08-09 17:11:34.259: I/IJKMEDIA(6073): Input #0, wav, from 'http://gddx.sc.chinaz.net/Files/DownLoad/sound1/201908/11811.wav':
08-09 17:11:34.259: I/IJKMEDIA(6073):   Duration: 
08-09 17:11:34.259: I/IJKMEDIA(6073): 00:00:10.43
08-09 17:11:34.259: I/IJKMEDIA(6073): , bitrate: 
08-09 17:11:34.259: I/IJKMEDIA(6073): 705 kb/s
08-09 17:11:34.259: I/IJKMEDIA(6073):     Stream #0:0
08-09 17:11:34.259: I/IJKMEDIA(6073): : Audio: pcm_s16le ([1][0][0][0] / 0x0001), 22050 Hz, 2 channels, s16, 705 kb/s
08-09 17:11:34.260: I/IJKMEDIA(6073): SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
08-09 17:11:34.260: I/IJKMEDIA(6073): SDL_Android_AudioTrack: ENCODING_PCM_16BIT
08-09 17:11:34.269: I/IJKMEDIA(6073): SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(0.000000,1.000000)
08-09 17:11:34.270: I/IJKMEDIA(6073): audio_session_id = 636
08-09 17:11:34.270: I/IJKMEDIA(6073): AudioCodec: avcodec, pcm_s16le
08-09 17:11:34.270: I/IJKMEDIA(6073): SDL_RunThread: [6328] ff_aout_android
08-09 17:11:34.273: I/IJKMEDIA(6073): SDL_RunThread: [6329] ff_audio_dec
08-09 17:11:34.286: I/AudioTrack-JNI(6073): audioTrack continuously zero data counter >= 10, send pause/stop state to pg, counter: 0
08-09 17:11:34.299: I/IjkSDKPlayerActivity(6073): onInfo: 10006 0
08-09 17:11:34.302: I/IjkSDKPlayerActivity(6073): onInfo: 10007 0
08-09 17:11:34.305: I/IjkSDKPlayerActivity(6073): onPrepared
08-09 17:11:34.342: I/IjkSDKPlayerActivity(6073): onInfo: 10003 0
08-09 17:11:34.343: I/IjkSDKPlayerActivity(6073): onInfo: 10002 0
08-09 17:11:34.441: I/AudioTrack-JNI(6073): audioTrack send start state to pg
08-09 17:11:37.603: I/AudioTrack-JNI(6073): audioTrack continuously zero data counter >= 10, send pause/stop state to pg, counter: 0
08-09 17:11:43.196: I/IJKMEDIA(6073): SDL_JNI_DetachThreadEnv: [6322]
08-09 17:11:43.197: I/IJKMEDIA(6073): SDL_JNI_DetachThreadEnv: [6323]
08-09 17:11:43.251: I/IJKMEDIA(6073): SDL_JNI_DetachThreadEnv: [6324]
08-09 17:11:43.251: I/IJKMEDIA(6073): SDL_JNI_DetachThreadEnv: [6329]
08-09 17:11:43.253: I/IJKMEDIA(6073): SDL_JNI_DetachThreadEnv: [6328]
08-09 17:11:43.256: W/IJKMEDIA(6073): moncleanu already called

```

**Comment by helloAda** [comment]
> > 根据你配置文件，现在无法播放opus格式，请问如何处理？
> 
> 已解决。

您好！请问如何解决的 我也遇到这个问题。
