### ISSUE TITLE
Why I can't play this hls for aes128 url on ijkmediaPlayer  ?大神帮帮忙

### ISSUE THREAD

**Issue by hzhzhen** [Bilibili/ijkplayer#4299]
m3u8 address : http://hls.kaishuhezi.com/Act-HLS-Encryption/4037e5124cfe412bbdd24b0b315b9a07/20150911012749-1.m3u8?MtsHlsUriToken=xxx1111

standard  hls encryption

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="https://yhgtest.kaishustory.com/test/getKey.gg?MediaId=1894b879c1fa44df910d547c5a73188e&Ciphertext=YjlhYmQwM2UtMzMxMi00NTgzLWEzMTQtN2M4ZTAwMjk1ZWUyNWRlRUtyVTJOUmV2VkhXaHlSdlpvWlhReERSdWJ2eEZBQUFBQUFBQUFBREM0S1BQU3gydFN1Nm9uQ3BqRDB5dUlQZjIyakp5emR3eGg5dmZyZjhzcmxXZlZjR0pmVVN3&MtsHlsUriToken=xxx1111"
#EXTINF:9.914933,
20150911012749-1-00001.ts
#EXTINF:9.891689,
20150911012749-1-00002.ts
#EXTINF:9.914933,
20150911012749-1-00003.ts
#EXTINF:9.891689,
20150911012749-1-00004.ts
#EXTINF:9.891711,
20150911012749-1-00005.ts
#EXTINF:9.914922,
20150911012749-1-00006.ts
#EXTINF:9.891689,
20150911012749-1-00007.ts
#EXTINF:9.891711,
20150911012749-1-00008.ts
#EXTINF:9.914900,
20150911012749-1-00009.ts
#EXTINF:9.891711,
20150911012749-1-00010.ts
#EXTINF:9.891700,
20150911012749-1-00011.ts
#EXTINF:9.914922,
20150911012749-1-00012.ts
#EXTINF:9.891700,
20150911012749-1-00013.ts
#EXTINF:9.914922,
20150911012749-1-00014.ts
#EXTINF:9.891700,
20150911012749-1-00015.ts
#EXTINF:9.891700,
20150911012749-1-00016.ts
#EXTINF:9.914911,
20150911012749-1-00017.ts
#EXTINF:9.891711,
20150911012749-1-00018.ts
#EXTINF:9.891689,
20150911012749-1-00019.ts
#EXTINF:9.914922,
20150911012749-1-00020.ts
#EXTINF:9.891711,
20150911012749-1-00021.ts
#EXTINF:9.891700,
20150911012749-1-00022.ts
#EXTINF:9.914922,
20150911012749-1-00023.ts
#EXTINF:9.891689,
20150911012749-1-00024.ts
#EXTINF:9.891711,
20150911012749-1-00025.ts
#EXTINF:9.914911,
20150911012749-1-00026.ts
#EXTINF:9.891700,
20150911012749-1-00027.ts
#EXTINF:9.914933,
20150911012749-1-00028.ts
#EXTINF:9.891689,
20150911012749-1-00029.ts
#EXTINF:9.891700,
20150911012749-1-00030.ts
#EXTINF:9.914933,
20150911012749-1-00031.ts
#EXTINF:9.891700,
20150911012749-1-00032.ts
#EXTINF:9.891689,
20150911012749-1-00033.ts
#EXTINF:9.914933,
20150911012749-1-00034.ts
#EXTINF:9.891689,
20150911012749-1-00035.ts
#EXTINF:9.891711,
20150911012749-1-00036.ts
#EXTINF:9.914911,
20150911012749-1-00037.ts
#EXTINF:9.891711,
20150911012749-1-00038.ts
#EXTINF:9.891700,
20150911012749-1-00039.ts
#EXTINF:9.914911,
20150911012749-1-00040.ts
#EXTINF:9.891711,
20150911012749-1-00041.ts
#EXTINF:9.914922,
20150911012749-1-00042.ts
#EXTINF:9.891700,
20150911012749-1-00043.ts
#EXTINF:9.891689,
20150911012749-1-00044.ts
#EXTINF:9.914933,
20150911012749-1-00045.ts
#EXTINF:9.891689,
20150911012749-1-00046.ts
#EXTINF:9.891711,
20150911012749-1-00047.ts
#EXTINF:9.914911,
20150911012749-1-00048.ts
#EXTINF:9.891700,
20150911012749-1-00049.ts
#EXTINF:9.891711,
20150911012749-1-00050.ts
#EXTINF:9.914922,
20150911012749-1-00051.ts
#EXTINF:9.891700,
20150911012749-1-00052.ts
#EXTINF:9.891689,
20150911012749-1-00053.ts
#EXTINF:9.914922,
20150911012749-1-00054.ts
#EXTINF:9.891711,
20150911012749-1-00055.ts
#EXTINF:9.914911,
20150911012749-1-00056.ts
#EXTINF:9.891711,
20150911012749-1-00057.ts
#EXTINF:9.891700,
20150911012749-1-00058.ts
#EXTINF:9.914922,
20150911012749-1-00059.ts
#EXTINF:9.891700,
20150911012749-1-00060.ts
#EXTINF:9.891689,
20150911012749-1-00061.ts
#EXTINF:9.914933,
20150911012749-1-00062.ts
#EXTINF:9.891700,
20150911012749-1-00063.ts
#EXTINF:9.891700,
20150911012749-1-00064.ts
#EXTINF:9.914911,
20150911012749-1-00065.ts
#EXTINF:9.891700,
20150911012749-1-00066.ts
#EXTINF:9.891700,
20150911012749-1-00067.ts
#EXTINF:9.914933,
20150911012749-1-00068.ts
#EXTINF:9.891700,
20150911012749-1-00069.ts
#EXTINF:9.914922,
20150911012749-1-00070.ts
#EXTINF:9.891689,
20150911012749-1-00071.ts
#EXTINF:9.891700,
20150911012749-1-00072.ts
#EXTINF:9.914933,
20150911012749-1-00073.ts
#EXTINF:9.891700,
20150911012749-1-00074.ts
#EXTINF:9.891700,
20150911012749-1-00075.ts
#EXTINF:9.914922,
20150911012749-1-00076.ts
#EXTINF:9.891689,
20150911012749-1-00077.ts
#EXTINF:9.891711,
20150911012749-1-00078.ts
#EXTINF:9.914922,
20150911012749-1-00079.ts
#EXTINF:9.891689,
20150911012749-1-00080.ts
#EXTINF:9.891711,
20150911012749-1-00081.ts
#EXTINF:9.914922,
20150911012749-1-00082.ts
#EXTINF:9.891700,
20150911012749-1-00083.ts
#EXTINF:9.914911,
20150911012749-1-00084.ts
#EXTINF:9.891700,
20150911012749-1-00085.ts
#EXTINF:9.891700,
20150911012749-1-00086.ts
#EXTINF:9.914922,
20150911012749-1-00087.ts
#EXTINF:9.891700,
20150911012749-1-00088.ts
#EXTINF:5.410256,
20150911012749-1-00089.ts
#EXT-X-ENDLIST
I have complie openssl, crypto is enable .
ijk has  setting:
  mMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", "crypto,file,http,https,tcp,tls,udp");

but is not work

**Comment by hzhzhen** [comment]
06-12 11:26:52.443  4772  4772 I IJKMEDIA: ===== versions =====
06-12 11:26:52.443  4772  4772 I IJKMEDIA: ijkplayer    : k0.8.4
06-12 11:26:52.443  4772  4772 I IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170829--001
06-12 11:26:52.443  4772  4772 I IJKMEDIA: libavutil    : 55.58.100
06-12 11:26:52.443  4772  4772 I IJKMEDIA: libavcodec   : 57.89.100
06-12 11:26:52.443  4772  4772 I IJKMEDIA: libavformat  : 57.71.100
06-12 11:26:52.443  4772  4772 I IJKMEDIA: libswscale   : 4.6.100
06-12 11:26:52.443  4772  4772 I IJKMEDIA: libswresample: 2.7.100
06-12 11:26:52.443  4772  4772 I IJKMEDIA: ===== options =====
06-12 11:26:52.443  4772  4772 I IJKMEDIA: format-opts : ijkapplication               = 2137737168
06-12 11:26:52.443  4772  4772 I IJKMEDIA: format-opts : ijkiomanager                 = 2138032256
06-12 11:26:52.443  4772  4772 I IJKMEDIA: ===================
06-12 11:26:52.443  4772  5806 I IJKMEDIA: SDL_RunThread: [5806] ff_msg_loop
06-12 11:26:52.453  4772  5807 I IJKMEDIA: SDL_RunThread: [5807] ff_vout
06-12 11:26:52.453  4772  5808 I IJKMEDIA: SDL_RunThread: [5808] ff_read
06-12 11:26:52.453  4772  5808 I tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131075
06-12 11:26:52.453  4772  5808 I IJKMEDIA: ijkhttphook http://hls.kaishuhezi.com/Act-HLS-Encryption/4037e5124cfe412bbdd24b0b315b9a07/20150911012749-1.m3u8?MtsHlsUriToken=xxx1111 (remain)
06-12 11:26:52.453  4772  5808 I tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
06-12 11:26:52.453  4772  5808 I IJKMEDIA: Hit DNS cache hostname = hls.kaishuhezi.com
06-12 11:26:52.453  4772  5808 I tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
06-12 11:26:52.473  4772  5808 I tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
06-12 11:26:52.543  4772  5808 I tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
06-12 11:26:52.543  4772  5808 E IJKMEDIA: Unable to open key file https://yhgtest.kaishustory.com/test/getKey.gg?MediaId=1894b879c1fa44df910d547c5a73188e&Ciphertext=YjlhYmQwM2UtMzMxMi00NTgzLWEzMTQtN2M4ZTAwMjk1ZWUyNWRlRUtyVTJOUmV2VkhXaHlSdlpvWlhReERSdWJ2eEZBQUFBQUFBQUFBREM0S1BQU3gydFN1Nm9uQ3BqRDB5dUlQZjIyakp5emR3eGg5dmZyZjhzcmxXZlZjR0pmVVN3&MtsHlsUriToken=xxx1111
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.543  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 W IJKMEDIA: Failed to open segment of playlist 0
06-12 11:26:52.553  4772  5808 E IJKMEDIA: Error when loading first segment 'ijkhttphook:http://hls.kaishuhezi.com/Act-HLS-Encryption/4037e5124cfe412bbdd24b0b315b9a07/20150911012749-1-00001.ts'
06-12 11:26:52.553  4772  5808 E IJKMEDIA: ijkhttphook:http://hls.kaishuhezi.com/Act-HLS-Encryption/4037e5124cfe412bbdd24b0b315b9a07/20150911012749-1.m3u8?MtsHlsUriToken=xxx1111: Invalid data found when processing input
06-12 11:26:52.563  4772  5808 I IJKMEDIA: SDL_JNI_DetachThreadEnv: [5808]
06-12 11:26:52.573  4772  4772 I NEMO_UI : (1826854) - [IJKMusicPlayerService] - ijkService is start mMediaPlayer is null palyfalse
06-12 11:26:52.593  4772  4772 I NEMO_UI : (1826877) - [MusicPlayerUI] - ijkmMediaPlayer.getCurrentPosition duration::-1
06-12 11:26:52.603  4772  4772 E tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by hzhzhen** [comment]
I have resolve

**Comment by RoraxHan** [comment]
@hzhzhen  Hello! How did you solve the problem?
I can not play the m3u8.

**Comment by hzhzhen** [comment]
@RoraxHan No problem

**Comment by GJson** [comment]
@hzhzhen   Hello! How did you solve the problem?
