### ISSUE TITLE
播放加密的本地m3u8文件出现Invalid data found when processing input

### ISSUE THREAD

**Issue by chaoDream** [Bilibili/ijkplayer#4302]
具体就是前两个ts没问题可以相应，到第三个就会出现Invalid data found when processing input并且报IjkMediaPlayer: Error (-10000,0)这个错误！求解答！

 Statistics: 32200 bytes read, 0 seeks
06-14 10:01:07.935 7082-7214/com.wyc D/IJKMEDIA: opening http://fc.bjsteach.com/2017xfks/tlz/jssw/flash_k/60200/17xfks_jssw_tlz_60200_760x428_170kbps_m3u8_10-000.ts
06-14 10:01:07.936 7082-7214/com.wyc I/IJKMEDIA: Hit DNS cache hostname = fc.bjsteach.com
06-14 10:01:08.026 7082-7214/com.wyc D/IJKMEDIA: request: GET /2017xfks/tlz/jssw/flash_k/60200/17xfks_jssw_tlz_60200_760x428_170kbps_m3u8_10-000.ts HTTP/1.1
                                                                        User-Agent: Lavf/57.83.100
                                                                        Accept: */*
                                                                        Range: bytes=0-
                                                                        Connection: close
                                                                        Host: fc.bjsteach.com
                                                                        Icy-MetaData: 1
06-14 10:01:08.049 7082-7214/com.wyc V/IJKMEDIA: header='HTTP/1.1 206 Partial Content'
06-14 10:01:08.049 7082-7214/com.wyc V/IJKMEDIA: http_code=206
06-14 10:01:08.049 7082-7214/com.wyc V/IJKMEDIA: header='Server: Tengine'
06-14 10:01:08.049 7082-7214/com.wyc V/IJKMEDIA: header='Content-Type: video/mp2t'
06-14 10:01:08.049 7082-7214/com.wyc V/IJKMEDIA: header='Content-Length: 620784'
06-14 10:01:08.049 7082-7214/com.wyc V/IJKMEDIA: header='Connection: close'
06-14 10:01:08.049 7082-7214/com.wyc V/IJKMEDIA: header='Date: Thu, 17 May 2018 06:06:14 GMT'
06-14 10:01:08.049 7082-7214/com.wyc V/IJKMEDIA: header='Last-Modified: Tue, 20 Mar 2018 00:48:04 GMT'
06-14 10:01:08.049 7082-7214/com.wyc V/IJKMEDIA: header='ETag: "5ab05a44-978f0"'
06-14 10:01:08.049 7082-7214/com.wyc V/IJKMEDIA: header='Accept-Ranges: bytes'
06-14 10:01:08.049 7082-7214/com.wyc V/IJKMEDIA: header='Via: cache15.l2nu17-1[10,200-0,M], cache16.l2nu17-1[10,0], kunlun5.cn345[0,206-0,H], kunlun8.cn345[1,0]'
06-14 10:01:08.049 7082-7214/com.wyc V/IJKMEDIA: header='Age: 2404482'
06-14 10:01:08.049 7082-7214/com.wyc V/IJKMEDIA: header='X-Cache: HIT TCP_MEM_HIT dirn:10:536393724 mlen:-1'
06-14 10:01:08.049 7082-7214/com.wyc V/IJKMEDIA: header='X-Swift-SaveTime: Thu, 17 May 2018 06:06:14 GMT'
06-14 10:01:08.049 7082-7214/com.wyc V/IJKMEDIA: header='X-Swift-CacheTime: 23328000'
06-14 10:01:08.049 7082-7214/com.wyc V/IJKMEDIA: header='Content-Range: bytes 0-620783/620784'
06-14 10:01:08.049 7082-7214/com.wyc V/IJKMEDIA: header='Access-Control-Allow-Origin: *'
06-14 10:01:08.050 7082-7214/com.wyc V/IJKMEDIA: header='Timing-Allow-Origin: *'
06-14 10:01:08.050 7082-7214/com.wyc V/IJKMEDIA: header='EagleId: 1bdd1e0815289416561008142e'
06-14 10:01:08.050 7082-7214/com.wyc V/IJKMEDIA: header=''
06-14 10:01:08.053 7082-7214/com.wyc V/IJKMEDIA: Probing mp3 score:1 size:4096
06-14 10:01:08.054 7082-7214/com.wyc V/IJKMEDIA: Probing mp3 score:1 size:8192
06-14 10:01:08.070 7082-7214/com.wyc V/IJKMEDIA: Probing mp3 score:1 size:16384
06-14 10:01:08.867 7082-7214/com.wyc D/IJKMEDIA: opening http://fc.bjsteach.com/2017xfks/tlz/jssw/flash_k/60200/17xfks_jssw_tlz_60200_760x428_170kbps_m3u8_10-001.ts
06-14 10:01:08.868 7082-7214/com.wyc I/IJKMEDIA: Hit DNS cache hostname = fc.bjsteach.com
06-14 10:01:08.892 7082-7214/com.wyc D/IJKMEDIA: request: GET /2017xfks/tlz/jssw/flash_k/60200/17xfks_jssw_tlz_60200_760x428_170kbps_m3u8_10-001.ts HTTP/1.1
                                                                        User-Agent: Lavf/57.83.100
                                                                        Accept: */*
                                                                        Range: bytes=0-
                                                                        Connection: close
                                                                        Host: fc.bjsteach.com
                                                                        Icy-MetaData: 1
06-14 10:01:08.923 7082-7214/com.wyc V/IJKMEDIA: header='HTTP/1.1 206 Partial Content'
06-14 10:01:08.924 7082-7214/com.wyc V/IJKMEDIA: http_code=206
06-14 10:01:08.924 7082-7214/com.wyc V/IJKMEDIA: header='Server: Tengine'
06-14 10:01:08.924 7082-7214/com.wyc V/IJKMEDIA: header='Content-Type: video/mp2t'
06-14 10:01:08.924 7082-7214/com.wyc V/IJKMEDIA: header='Content-Length: 425072'
06-14 10:01:08.924 7082-7214/com.wyc V/IJKMEDIA: header='Connection: close'
06-14 10:01:08.924 7082-7214/com.wyc V/IJKMEDIA: header='Date: Tue, 15 May 2018 04:52:14 GMT'
06-14 10:01:08.924 7082-7214/com.wyc V/IJKMEDIA: header='Last-Modified: Tue, 20 Mar 2018 00:47:58 GMT'
06-14 10:01:08.924 7082-7214/com.wyc V/IJKMEDIA: header='ETag: "5ab05a3e-67c70"'
06-14 10:01:08.924 7082-7214/com.wyc V/IJKMEDIA: header='Accept-Ranges: bytes'
06-14 10:01:08.924 7082-7214/com.wyc V/IJKMEDIA: header='Via: cache17.l2nu17-1[0,200-0,H], cache43.l2nu17-1[25,0], kunlun6.cn345[0,206-0,H], kunlun6.cn345[6,0]'
06-14 10:01:08.924 7082-7214/com.wyc V/IJKMEDIA: header='Age: 2581722'
06-14 10:01:08.924 7082-7214/com.wyc V/IJKMEDIA: header='X-Cache: HIT TCP_HIT dirn:11:587113855 mlen:-1'
06-14 10:01:08.924 7082-7214/com.wyc V/IJKMEDIA: header='X-Swift-SaveTime: Wed, 16 May 2018 02:27:51 GMT'
06-14 10:01:08.924 7082-7214/com.wyc V/IJKMEDIA: header='X-Swift-CacheTime: 23328000'
06-14 10:01:08.924 7082-7214/com.wyc V/IJKMEDIA: header='Content-Range: bytes 0-425071/425072'
06-14 10:01:08.924 7082-7214/com.wyc V/IJKMEDIA: header='Access-Control-Allow-Origin: *'
06-14 10:01:08.924 7082-7214/com.wyc V/IJKMEDIA: header='Timing-Allow-Origin: *'
06-14 10:01:08.924 7082-7214/com.wyc V/IJKMEDIA: header='EagleId: 1bdd1e0615289416569672207e'
06-14 10:01:08.924 7082-7214/com.wyc V/IJKMEDIA: header=''
06-14 10:01:09.687 7082-7214/com.wyc D/IJKMEDIA: opening http://fc.bjsteach.com/2017xfks/tlz/jssw/flash_k/60200/17xfks_jssw_tlz_60200_760x428_170kbps_m3u8_10-002.ts
06-14 10:01:09.687 7082-7214/com.wyc I/IJKMEDIA: Hit DNS cache hostname = fc.bjsteach.com
06-14 10:01:09.721 7082-7214/com.wyc D/IJKMEDIA: request: GET /2017xfks/tlz/jssw/flash_k/60200/17xfks_jssw_tlz_60200_760x428_170kbps_m3u8_10-002.ts HTTP/1.1
                                                                        User-Agent: Lavf/57.83.100
                                                                        Accept: */*
                                                                        Range: bytes=0-
                                                                        Connection: close
                                                                        Host: fc.bjsteach.com
                                                                        Icy-MetaData: 1
06-14 10:01:09.761 7082-7214/com.wyc V/IJKMEDIA: header='HTTP/1.1 206 Partial Content'
06-14 10:01:09.761 7082-7214/com.wyc V/IJKMEDIA: http_code=206
06-14 10:01:09.761 7082-7214/com.wyc V/IJKMEDIA: header='Server: Tengine'
06-14 10:01:09.761 7082-7214/com.wyc V/IJKMEDIA: header='Content-Type: video/mp2t'
06-14 10:01:09.761 7082-7214/com.wyc V/IJKMEDIA: header='Content-Length: 421888'
06-14 10:01:09.761 7082-7214/com.wyc V/IJKMEDIA: header='Connection: close'
06-14 10:01:09.761 7082-7214/com.wyc V/IJKMEDIA: header='Date: Sat, 05 May 2018 01:17:09 GMT'
06-14 10:01:09.761 7082-7214/com.wyc V/IJKMEDIA: header='Last-Modified: Tue, 20 Mar 2018 00:48:04 GMT'
06-14 10:01:09.761 7082-7214/com.wyc V/IJKMEDIA: header='ETag: "5ab05a44-67000"'
06-14 10:01:09.761 7082-7214/com.wyc V/IJKMEDIA: header='Accept-Ranges: bytes'
06-14 10:01:09.761 7082-7214/com.wyc V/IJKMEDIA: header='Via: cache22.l2nu17-1[0,200-0,H], cache19.l2nu17-1[41,0], kunlun10.cn345[0,206-0,H], kunlun5.cn345[18,0]'
06-14 10:01:09.761 7082-7214/com.wyc V/IJKMEDIA: header='Age: 3458628'
06-14 10:01:09.761 7082-7214/com.wyc V/IJKMEDIA: header='X-Cache: HIT TCP_HIT dirn:6:81240087 mlen:-1'
06-14 10:01:09.761 7082-7214/com.wyc V/IJKMEDIA: header='X-Swift-SaveTime: Tue, 08 May 2018 08:27:21 GMT'
06-14 10:01:09.761 7082-7214/com.wyc V/IJKMEDIA: header='X-Swift-CacheTime: 23328000'
06-14 10:01:09.761 7082-7214/com.wyc V/IJKMEDIA: header='Content-Range: bytes 0-421887/421888'
06-14 10:01:09.761 7082-7214/com.wyc V/IJKMEDIA: header='Access-Control-Allow-Origin: *'
06-14 10:01:09.761 7082-7214/com.wyc V/IJKMEDIA: header='Timing-Allow-Origin: *'
06-14 10:01:09.761 7082-7214/com.wyc V/IJKMEDIA: header='EagleId: 1bdd1e0515289416577966087e'
06-14 10:01:09.761 7082-7214/com.wyc V/IJKMEDIA: header=''
06-14 10:01:09.811 7082-7214/com.wyc D/IJKMEDIA: Statistics: 1049746 bytes read, 0 seeks
06-14 10:01:09.815 7082-7214/com.wyc E/IJKMEDIA: hls+file:/storage/emulated/legacy/bluetooth/video-1.m3u8: Invalid data found when processing input
06-14 10:01:09.815 7082-7212/com.wyc D/IJKMEDIA: FFP_MSG_ERROR: 0
06-14 10:01:09.816 7082-7153/com.wyc E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
06-14 10:01:09.816 7082-7214/com.wyc I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [7214]
06-14 10:01:09.816 7082-7153/com.wyc D/IJKMEDIA: IjkMediaPlayer_release
06-14 10:01:09.816 7082-7153/com.wyc D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
06-14 10:01:09.816 7082-7153/com.wyc D/IJKMEDIA: ffpipeline_set_surface()
06-14 10:01:09.816 7082-7153/com.wyc D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
06-14 10:01:09.816 7082-7153/com.wyc D/IJKMEDIA: ijkmp_shutdown_l()
06-14 10:01:09.816 7082-7153/com.wyc D/IJKMEDIA: wait for read_tid
06-14 10:01:09.816 7082-7212/com.wyc D/IJKMEDIA: message_loop exit
06-14 10:01:09.816 7082-7212/com.wyc I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [7212]
06-14 10:01:09.817 7082-7153/com.wyc D/IJKMEDIA: wait for video_refresh_tid
06-14 10:01:09.826 7082-7213/com.wyc I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [7213]
06-14 10:01:09.826 7082-7153/com.wyc D/IJKMEDIA: ijkmp_shutdown_l()=void
06-14 10:01:09.826 7082-7153/com.wyc D/IJKMEDIA: ijkmp_dec_ref(): ref=0
06-14 10:01:09.826 7082-7153/com.wyc D/IJKMEDIA: ijkmp_shutdown_l()
06-14 10:01:09.826 7082-7153/com.wyc D/IJKMEDIA: ijkmp_shutdown_l()=void
06-14 10:01:09.827 7082-7153/com.wyc D/IJKMEDIA: IjkMediaPlayer_setVolume

**Comment by BruceLing** [comment]
遇到类似的问题，请问如何解决的？多谢！

**Comment by chaoDream** [comment]
> 遇到类似的问题，请问如何解决的？多谢！

就是播放的地址的title设置错了！没有转为本地地址！这是我这边遇到的！
