### ISSUE TITLE
video's total time is wrong

### ISSUE THREAD

**Issue by leonard0629** [Bilibili/ijkplayer#431]
when i seek to end, i find mp.getCurrentPosition is bigger then mp.getDuration, near 10 seconds, why this happen?

**Comment by sarahzuo** [comment]
There are the same issues like yours in my app. When play m3u8 type video, some video's duration is less about 10 seconds than real duration. I guess there are something wrong in m3u8 file, but I am not sure about that.

**Comment by Android4MediaPlayer** [comment]
plz give the url.

**Comment by Android4MediaPlayer** [comment]
@sarahzuo please give more message

**Comment by sarahzuo** [comment]
@Android4MediaPlayer

**Comment by sarahzuo** [comment]
@Android4MediaPlayer pls use these video urls: 1)  http://pl.youku.com/playlist/m3u8?vid=331284822&type=hd2&ts=1441769871&keyframe=0&ep=VyjMtm5wtr%2B2G1xOKHD6t4SkKmiOfA%2BAxOP6bjwvejEm7jIT73JIauU7oFBk9PMWPFYZZO8wSG584ICzP8t60w%3D%3D&sid=2441768311599123d8b0e&token=3781&ctype=20&ev=1&oip=3060450129&uc_param_str=xk 2) http://pl.youku.com/playlist/m3u8?vid=331362067&type=hd2&ts=1441770021&keyframe=0&ep=idIquXil%2BdTyPUsLFoSBkqiqPE3bZJHvx005N1JayUA%2B7qLP137%2FdSADQC3gUbTSPFYZZO8wSG584ICzP8t60w%3D%3D&sid=044177002117812231ed6&token=9545&ctype=20&ev=1&oip=2026301200&uc_param_str=xk 3) http://my.tv.sohu.com/ipad/o81237955_4652080281143_13340166.m3u8?plat=h5&playType=p2p&uid=1502011750050754&ver=1&prod=h5

**Comment by sarahzuo** [comment]
If the urls are not available any more, pls @ me.

**Comment by Android4MediaPlayer** [comment]
1) 12:52
2)  22:16
3) 34:19
@sarahzuo Is the every duration right?

**Comment by Android4MediaPlayer** [comment]
@sarahzuo ?

**Comment by sarahzuo** [comment]
The durations are:
1) 12:52
2) 22:16
3) 34:19, yes.
but, the issue is that videos finish until  at
1) 13:03
2) 22:26
3) 34:29
