### ISSUE TITLE
请问ijkplayer支持webm格式么？

### ISSUE THREAD

**Issue by ZHONGHuanGit** [Bilibili/ijkplayer#434]

**Comment by ZHONGHuanGit** [comment]
我根据ijkplayer里面的demo使用其它的player，但是没有办法播放web格式的视频，我看ijkplayer是封装了ffmpeg，以为其能够支持webm格式，所以想确认一下。

**Comment by Android4MediaPlayer** [comment]
格式是否支持跟ijk没关系，ffmpeg支持的话你可以打开选项重新编译ffmpeg，你有这样的文件或URL没？

**Comment by ctiao** [comment]
#154 #201 #198 #136 #362

**Comment by ZHONGHuanGit** [comment]
@ctiao  我并不了解你回答的几个issue的意思，我感觉和我想问的并不搭边，不过还是感谢

**Comment by ZHONGHuanGit** [comment]
@Android4MediaPlayer 你说这样的文件或URL是什么意思？是说播放的视频文件的URL么？所以你们也不清楚是否支持webm的格式么？在编译ffmpeg的时候是否有一些选项可以供选择支持webm格式？感谢你的回复。

**Comment by Android4MediaPlayer** [comment]
URL就是播放链接，本地文件也可以。webm格式是支持的，我看了demuxer列表

**Comment by ZHONGHuanGit** [comment]
@Android4MediaPlayer  我尝试了不同的playercontroller，但都无法播放，所以想请问是否有方法能够支持其播放，这个是webm格式的视频URL链接，http://7xkoif.com2.z0.glb.qiniucdn.com/short-XMTMwODgyMjAyOA==__flv__00-IcGetM4Asq.webm

**Comment by bbcallen** [comment]
in README
If you prefer more codec/format
```
cd config
rm module.sh
ln -s module-default.sh module.sh
cd android/contrib
# cd ios
sh compile-ffmpeg clean
```

**Comment by ZHONGHuanGit** [comment]
@bbcallen 谢谢你的提醒，我刚刚尝试了，虽然可以播放webm格式的视频了，但是播放开始会莫名弹出提示窗报错，结束就卡死。

**Comment by bbcallen** [comment]
Any log?

**Comment by TeeMoYan** [comment]
请问可以播放透明背景的webm视频吗？ 尝试播放时，背景依然是黑屏

**Comment by wying111** [comment]
@TeeMoYan 我也在弄这套方案，请问你有解决办法了吗？
