### ISSUE TITLE
Android Studio Import Project 'compileSdkVersion()'

### ISSUE THREAD

**Issue by cutler** [Bilibili/ijkplayer#435]
every thing is ok!

but when finally imoprt to Android Studio, print this error:
```
Error:(21, 0) Gradle DSL method not found: 'compileSdkVersion()'
Possible causes:
The project 'ijkplayer' may be using a version of Gradle that does not contain the method.
```

**My Build Enviroment:**
Android Studio:1.2.2
root build.gradle file:
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}
ext {
    compileSdkVersion "22"
    buildToolsVersion "22.0.1"
}
```

**Comment by bbcallen** [comment]
```
ext {
    compileSdkVersion = 22
    buildToolsVersion = "22.0.1"
}
```

**Comment by cutler** [comment]
i change `"22"`to`22`, print this error: 
```
Error:(22) A problem occurred evaluating root project 'ijkplayer'.
> Could not find method compileSdkVersion() for arguments [22] on root project 'ijkplayer'.
```

**Comment by bbcallen** [comment]
```
ext {
    compileSdkVersion = 22
    buildToolsVersion = "22.0.1"
}
```

**Comment by cutler** [comment]
thx very much.

**Comment by Rajes757** [comment]
same problem here,please help us

// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
allprojects {
    repositories {
        jcenter()
    }
}
task clean(type: Delete) {
    delete rootProject.buildDir
}

android {
    compileSdkVersion = 25
    buildToolsVersion = "25.0.2"
}
dependencies {
}

**Comment by MasterSami1985** [comment]
please need help 

 android studio ver 3.1.3
Could not find property 'SdkVersion' on com.android.build.gradle.AppExtension_Decorated@6c9efbf9.
Open File





apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'

android {
    implementation SdkVersion 23
    buildToolsVersion '27.0.3'

    defaultConfig {
        applicationId "com.example.android.miwok"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testimplementation 'junit:junit:4.12'
    implementation 'com.android.support:appcompat-v7:23.3.0'
    implementation 'com.android.support:support-v4:23.3.0'
    implementation 'com.android.support:design:23.3.0'
    implementation 'com.google.android.gms:play-services-auth:9.4.0'
}
