### ISSUE TITLE
关于同一个播放器实例切换url问题

### ISSUE THREAD

**Issue by Caij** [Bilibili/ijkplayer#4356]
看到issue里面建议重新创建对象，如果列表播放视频 一直销毁重建 是否会影响性能。 没办法考虑同一个player切换url吗？

**Comment by houtengzhi** [comment]
调用reset方法回到初始状态可以再次调用setDataSource
https://www.jianshu.com/p/590f60d34adf[https://www.jianshu.com/p/590f60d34adf](url)

**Comment by Caij** [comment]
谢谢
