### ISSUE TITLE
严重问题！！！！内存泄漏

### ISSUE THREAD

**Issue by maowentao0416** [Bilibili/ijkplayer#4366]
用的master分支中的样例视频：http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8
，通过Android profiler来观察内存|
播放--> 退出-->播放--> 退出-->播放--> 退出-->。。。。
发现native占用的内存一直在上涨

**Comment by yindalei00** [comment]
` if (mMediaPlayer != null) {
            mMediaPlayer.reset();
            mMediaPlayer.release();
            mMediaPlayer = null;
        }`

**Comment by brandy2015** [comment]
self.player?.shutdown()

**Comment by wzyzb** [comment]
> ` if (mMediaPlayer != null) { mMediaPlayer.reset(); mMediaPlayer.release(); mMediaPlayer = null; }`

这样可以解决？

**Comment by SXJCLZH** [comment]
请问有大佬解决的吗？

**Comment by iflove** [comment]
DirectByteBuffer 泄露，堆外内存泄露
