### ISSUE TITLE
IJKSDLGLView: setupDisplay not ready 已解决

### ISSUE THREAD

**Issue by DeliriousLee** [bilibili/ijkplayer#4367]
## 这个问题已解决，在issues里面备份一下解决方式。
项目集成使用了**IJKFrameWork.framework**，使用时，测试地址：香港卫视：<strong>rtmp://live.hkstv.hk.lxdns.com/live/hks</strong>可以播放**RTMP**，但是没有办法播放**RTSP**视频流。怀疑应该是编译的时候**Module.sh**那边没有很好的支持**RTSP**，故又重新把老的**Module.sh**删除，重新编辑生成**Module.sh**。然后编辑内容后重新编译<strong>./compile-ffmpeg.sh</strong>了。
`export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=rtp"`
`export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=sdp"`
`export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=rtp"`
`export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=tcp"`
`export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=rtsp"`
`export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=rtp"`
IJKPlayer编译各种坑。这几个教程还不错，参考这几个教程做出来的[https://www.jianshu.com/p/9743a68c2939](url)
[https://blog.csdn.net/qq372848728/article/details/62170288](url)

**Comment by 374601404** [comment]
That doesn't work!

**Comment by DeliriousLee** [comment]
> That doesn't work!

Maybe you can use mine ? which i have already compiled successfully.
https://pan.baidu.com/s/18h86bK43wPRQCwjaYm3CdQ      密码pwd：j3fh

**Comment by zj381652512** [comment]
使用最新版的0.88的IJKMediaFramework 在播放rtmp源时会连续2-3次下面的Log,从第一次打印下面log到开始播放通常要5-10s ,请问楼主打包IJKMediaFramework是解决这个问题吗

 invalidateRenderBuffer
 IJKSDLGLView: setupDisplay not ready

**Comment by koreadragon** [comment]
> > That doesn't work!
> 
> Maybe you can use mine ? which i have already compiled successfully. https://pan.baidu.com/s/18h86bK43wPRQCwjaYm3CdQ 密码pwd：j3fh



> > That doesn't work!
> 
> Maybe you can use mine ? which i have already compiled successfully. https://pan.baidu.com/s/18h86bK43wPRQCwjaYm3CdQ 密码pwd：j3fh

你好，能重新分享一次吗？链接失效了，或者发我邮箱，谢谢了！724584644@qq.com
