### ISSUE TITLE
how to generate jar package?

### ISSUE THREAD

**Issue by jboeyin** [Bilibili/ijkplayer#437]
I learned that the old version which was easily to build jar package and .so files via the following commands: 
##
./gradlew cleanFFmpeg buildJniLibs # generate on single shared library: libijkplayer.so
./gradlew jarRelease   #generate the ijkmediaplayer.jar 
I found out the new version just had remove the above mentioned commands, 
so how can I build the jar and .so files?

**Comment by bbcallen** [comment]
For .so files, ndk-build is enough.
For jar files, why you need it?
