### ISSUE TITLE
视频地址无法播放

### ISSUE THREAD

**Issue by Caij** [Bilibili/ijkplayer#4375]
已经开启了https

url： https://api.youku.com/videos/player/file?data=WcEl1o6uYdzBPRFl6TURZMU5nPT18MHwxfDEwMDUwfDEO0O0O

**Comment by Insofan** [comment]
@Caij  有解决方案么, 我有几个地址后缀不是 .mp4格式, 是 /mp4, 可以用 MP/AV播放, 但是无法使用IJK播放.

**Comment by Caij** [comment]
可以播放我都忘记怎么解决的 好像也没加什么参数  你确定你的开启https了吗？@Insofan

**Comment by Caij** [comment]
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_clear", 1);

**Comment by Insofan** [comment]
@Caij 上面的优酷地址可以播放是么, 我有的URL播放不了. 我http https都可以播放 但是后缀必须是.mp4的 如果后缀是 /mp4 无法播放

**Comment by Caij** [comment]
@Insofan 建议你用官方的demo试试能不能播   我已经解决了   开启https就行
