### ISSUE TITLE
how should I import ijkplayer library in react-native?

### ISSUE THREAD

**Issue by Kimzify** [bilibili/ijkplayer#4377]
I want to use ijkplayer for Android in my react-native app.I do the `things` that you said until:

```
git clone https://github.com/Bilibili/ijkplayer.git ijkplayer-android
cd ijkplayer-android
git checkout -B latest k0.8.8

./init-android.sh

cd android/contrib
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all

cd ..
./compile-ijk.sh all
```

and from:

```
Android Studio:
Open an existing Android Studio project
Select android/ijkplayer/ and import

```
I don't know how should I do and I can't import ijkplayer on my react-native app.

**Comment by LinusLiu724** [comment]
1、build the project  ijkplayer-android/android/ijkplayer, it can generate "ijkplayer-arm64"，"ijkplayer-armv7a" and "ijkplayer-java-release.arr".
2、copy "ijkplayer-arm64"，"ijkplayer-armv7a" and "ijkplayer-java-release.arr" to  your project's "libs" directory 
3、modify build.gradle 
      sourceSets { 
            main { 
                      jniLibs.srcDirs = ['libs'] 
            }
     }
     repositories {
              mavenCentral()
              flatDir {
                      dirs 'libs' //this way we can find the .aar file in libs folder
              }
      }

     api(name: 'ijkplayer-java-release', ext: 'aar')

**Comment by LinusLiu724** [comment]
你好，你的邮件已收到
