### ISSUE TITLE
工程中加入IJKMediaFramework.framework    编译后报错

### ISSUE THREAD

**Issue by zhifeng0825** [Bilibili/ijkplayer#441]
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_IJKFFMoviePlayerController", referenced from:
      objc-class-ref in RoomVideoViewController+Video.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by xclidongbo** [comment]
我的也是,有解决方法没
