### ISSUE TITLE
有谁添加过libssh(sftp)的支持吗

### ISSUE THREAD

**Issue by fengjing1213** [Bilibili/ijkplayer#4429]
想添加了对libssh的支持，但不知道该怎么配置，总是找不到编译好的libssh.a库

**Comment by cp110** [comment]
./init-ios-openssl.sh
cd ./ios
 ./compile-openssl.sh clean
./compile-openssl.sh all

**Comment by fengjing1213** [comment]
这个是支持https 不能播放的sftp吧

**Comment by fengjing1213** [comment]
@cp110 这个只是支持https吧 sftp需要依赖libssh包

**Comment by cp110** [comment]
操作完后，在ios/build/universal/lib目录下有libssh.a

**Comment by fengjing1213** [comment]
@cp110 android没有，好像要自己编译libssh.a包再添加

**Comment by fengjing1213** [comment]
弄好了，android端支持sftp，先编译libssh.a，编译时依赖ijk原有的openssl里libssl.a和libcrypto.a，还要依赖zlib库。编译好后放在do-compile-ffmpeg.sh中配置，跟openssl一样（我用的ubuntu，链接时被依赖库要放在后面）
