### ISSUE TITLE
集成Module在meizu note1 出现如下问题

### ISSUE THREAD

**Issue by HaoSilence** [Bilibili/ijkplayer#443]
设备：魅蓝NOTE 1
系统：Flyme 4.5.5A

编译ijkplayer-android项目后，把armv5,v7a,x86，java，sample部分文件导入到我自己的项目后，使用的时候出现了如下的问题，我不知道如何去修改。ijkplayer-android在此设备上运行正常，可以正常加载lib

09-07 17:34:33.763    8644-8644/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.testapp.dancing, PID: 8644
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.testapp.dancing-2/base.apk"],nativeLibraryDirectories=[/data/app/com.testapp.dancing-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"
at java.lang.Runtime.loadLibrary(Runtime.java:366)
            at java.lang.System.loadLibrary(System.java:988)
            at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:108)
            at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:119)

手头其它设备测试正常，没有出现此问题 ，MX4,Nexus 5

**Comment by Android4MediaPlayer** [comment]
arm64

**Comment by HaoSilence** [comment]
import Arm64 module and clean Project 
run with same Error

**Comment by bbcallen** [comment]
1. how do you write your gradle?

**Comment by HaoSilence** [comment]
compile project(':player-java')
    compile project(':player-armv7a')
    compile project(':player-x86')
    compile project(':player-armv5')

didnt compile arm64

**Comment by bbcallen** [comment]
So is the answer.

**Comment by HaoSilence** [comment]
I saw project ijkplayer also didnt compile arm64

**Comment by bbcallen** [comment]
Yes, I don't compile arm64 at all by default. Lib loader loads armv7a libs for my situation.

But if any arm64 lib exists in your project, lib loader will look up all libs under arm64,

**Comment by HaoSilence** [comment]
Thank you 

I just dont know why ijkplayer can play video on Meizu Note 1 without compile arm64 .
but my project cant play video

**Comment by bbcallen** [comment]
https://developer.android.com/ndk/guides/abis.html

**Comment by HaoSilence** [comment]
Thank you very much .

I modify .sh file and compile arm64 . 

it works . but I dont know why orginal project can play video .
