### ISSUE TITLE
avformat_write_header

### ISSUE THREAD

**Issue by hrdzkj** [Bilibili/ijkplayer#4435]
播放rtsp协议 视频格式H264; 音频格式pcm_alaw。avformat_write_header返回－22

int ffp_start_record(FFPlayer *ffp, const char *file_name)
{
    assert(ffp);
    AVDictionary *opt = NULL;
    int ret_code =99999;
    VideoState *is = ffp->is;
    
    ffp->m_ofmt_ctx = NULL; 
    ffp->m_ofmt = NULL;
    ffp->is_record = 0; 
    ffp->record_error = 0; 
    
    if (!file_name || !strlen(file_name)) { // 没有路径
        av_log(ffp, AV_LOG_ERROR, "filename is invalid");
        goto end;
    }
    
    if (!is || !is->ic|| is->paused || is->abort_request) { // 没有上下文，或者上下文已经停止
        av_log(ffp, AV_LOG_ERROR, "is,is->ic,is->paused is invalid");
        goto end;
    }
    
    if (ffp->is_record) { // 已经在录制
        av_log(ffp, AV_LOG_ERROR, "recording has started");
        goto end;
    }
    
    
    if ((avOutputFormat = av_guess_format(NULL, "mp4", "video/mp4")) == NULL) {
     av_log(ffp, AV_LOG_ERROR, "Could not guess output format\n", file_name);
     goto end;
    } 

    // 初始化一个用于输出的AVFormatContext结构体
    //avformat_alloc_output_context2(&ffp->m_ofmt_ctx, NULL, NULL, file_name);
    avformat_alloc_output_context2(&ffp->m_ofmt_ctx,av_guess_format("mp4", NULL, "video/mp4"), NULL, NULL);
    if (!ffp->m_ofmt_ctx) {
        av_log(ffp, AV_LOG_ERROR, "liuyi print,Could not create output context filename is %s\n", file_name);
        goto end;
    }
    ffp->m_ofmt = ffp->m_ofmt_ctx->oformat;
      
    
    for (int i = 0; i < is->ic->nb_streams; i++) {
        // 对照输入流创建输出流通道
        AVStream *in_stream = is->ic->streams[i];
        AVStream *out_stream = avformat_new_stream(ffp->m_ofmt_ctx, in_stream->codec->codec);
        if (!out_stream) {
            av_log(ffp, AV_LOG_ERROR, "liuyi print,Failed allocating output stream\n");
            goto end;
        }

        // 将输入视频/音频的参数拷贝至输出视频/音频的AVCodecContext结构体
        av_log(ffp, AV_LOG_DEBUG, "in_stream->codec；%@\n", in_stream->codec);
        if (avcodec_copy_context(out_stream->codec, in_stream->codec) < 0) {
            av_log(ffp, AV_LOG_ERROR, "Failed to copy context from input to output stream codec context\n");
            goto end;
        }
        
        out_stream->codec->codec_tag = 0;
        if (ffp->m_ofmt_ctx->oformat->flags & AVFMT_GLOBALHEADER) {
            out_stream->codec->flags |= CODEC_FLAG_GLOBAL_HEADER;
        }

        av_log(ffp, AV_LOG_ERROR, "liuyi: find encoder for codec_id=%s  \n",avcodec_get_name(out_stream->codec->codec_id));
    }

     av_dump_format(ffp->m_ofmt_ctx, 0, file_name, 1);
    
    // 打开输出文件
    if (!(ffp->m_ofmt->flags & AVFMT_NOFILE)) {
        ret_code = avio_open(&ffp->m_ofmt_ctx->pb, file_name, AVIO_FLAG_WRITE);
        if (ret_code < 0) {
            av_log(ffp, AV_LOG_ERROR, "liuyi print -->avio_open: Could not open output file '%s',ret_code=%d", file_name,ret_code);
            goto end;
        }
    }

    // 写视频文件头
    //av_dict_set(&options, "rtsp_transport", "tcp", 0);
    ret_code = avformat_write_header(ffp->m_ofmt_ctx, NULL);
    //ret_code = avformat_write_header(ffp->m_ofmt_ctx, &opt);
    //if ( ret_code< 0) {
       av_log(ffp, AV_LOG_ERROR, "liuyi print ---> avformat_write_header: Error occurred when opening output file resultCode=%d \n",ret_code);
       // goto end;
   // }

    ffp->is_record = 1;
    ffp->record_error = 0;
    pthread_mutex_init(&ffp->record_mutex, NULL);
    
    return 0;
end:
    ffp->record_error = 1;
    return -1;
}

**Comment by wnpllrzodiac** [comment]
pcm_alaw 和 h264 encode 确认开启编译了？（h264理论上是需要开启libx264的把）
QQ364953305

**Comment by hrdzkj** [comment]
@wnpllrzodiac ,我这样配置了，问题依然。
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=h264"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=h264"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=h264"

# 处理音频新增 （下面三个是自己添加的，原来的.sh没有这个配置）
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=pcm_alaw"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=pcm_ulaw"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=pcm_mulaw"

请问 如何开启开启libx264，如何pcm_alaw 和 h264 encode 确认开启？

**Comment by wnpllrzodiac** [comment]
下周二再看下吧，联系 QQ 364953305

**Comment by fengchuiyeluo** [comment]
你好，我也遇到返回-22的，请问你是怎么解决的呢

**Comment by wnpllrzodiac** [comment]
QQ 联系吧

**Comment by baiwulong** [comment]
你们解决了吗？-22，第一次接触视频，菜鸟求助

**Comment by wnpllrzodiac** [comment]
当然解决了，QQ联系吧

**Comment by baiwulong** [comment]
我也解决了，我的是因为搞mp4视频录制，但是音频流是pcm，mp4不支持pcm导致，然后我换成mov的初始化av
format context结构体可以了

**Comment by hrdzkj** [comment]
恭喜你呀。是的，每种封装格式都有一些规定的编码类型的。

**Comment by momoxiaoray** [comment]
@baiwulong 换成mov的初始化avformat context结构体，这个有没有修改记录，希望指点一下
