### ISSUE TITLE
How to set debugMode?

### ISSUE THREAD

**Issue by hwpo** [Bilibili/ijkplayer#445]
i want to see more logs, but i only got two lines:

09-08 16:26:33.694    8336-8399/tv.danmaku.ijk.media.sample E/IJKMEDIA﹕ Stream ends prematurely at 1091450, should be 4707275
09-08 16:26:33.837    8336-8399/tv.danmaku.ijk.media.sample E/IJKMEDIA﹕ av_read_frame error: fffffffb(�,�,�,�): unknown

i dont konw how to fixed it,
can you help me?

**Comment by Android4MediaPlayer** [comment]
ijkMediaPlayer.native_setLogLevel(IjkMediaPlayer.IJK_LOG_DEBUG);

**Comment by hwpo** [comment]
@Android4MediaPlayer 
THKS，
but i still can't resolve the problem：

Stream ends prematurely at 1091450, should be 4707275

any suggestion？

**Comment by Android4MediaPlayer** [comment]
give me the url,I try to see it

**Comment by hwpo** [comment]
http://c204.duotin.com/M03/01/F4/wKgB7FUX2bWAAmdWAEfTy5yUdXE359.mp3

**Comment by hwpo** [comment]
it works well on ios
but always be Interrupted on Android

**Comment by Android4MediaPlayer** [comment]
it works well on my android device.

**Comment by hwpo** [comment]
er。。。
打英文好累。。。魅族问题比较大，到4分钟左右一定会断，小米偶尔断，三星的偶尔断

**Comment by hwpo** [comment]
09-10 13:53:22.318    9580-9580/tv.danmaku.ijk.media.sample E/tv.danmaku.ijk.media.player.IjkMediaPlayer﹕ Buffer (23%) 277743/1176764
09-10 13:53:22.320    9580-9580/tv.danmaku.ijk.media.sample D/tv.danmaku.ijk.media.player.IjkMediaPlayer﹕ duration4296144060
09-10 13:53:22.871    9580-9720/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ audio cache=%2859 (142262/5000) (1048299/262144)
09-10 13:53:22.871    9580-9720/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ time cache=%2859 (142262/5000)
09-10 13:53:22.871    9580-9720/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ size cache=%402 (1048299/262144)
09-10 13:53:22.872    9580-9580/tv.danmaku.ijk.media.sample E/tv.danmaku.ijk.media.player.IjkMediaPlayer﹕ Buffer (23%) 278300/1176764
09-10 13:53:22.872    9580-9580/tv.danmaku.ijk.media.sample D/tv.danmaku.ijk.media.player.IjkMediaPlayer﹕ duration4296144060
09-10 13:53:23.436    9580-9720/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ audio cache=%2860 (142288/5000) (1048492/262144)
09-10 13:53:23.436    9580-9720/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ time cache=%2860 (142288/5000)
09-10 13:53:23.436    9580-9720/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ size cache=%402 (1048492/262144)
09-10 13:53:23.437    9580-9580/tv.danmaku.ijk.media.sample E/tv.danmaku.ijk.media.player.IjkMediaPlayer﹕ Buffer (23%) 278891/1176764
09-10 13:53:23.437    9580-9580/tv.danmaku.ijk.media.sample D/tv.danmaku.ijk.media.player.I
    --------- beginning of /dev/log/system
09-10 13:57:17.890    9580-9720/tv.danmaku.ijk.media.sample E/IJKMEDIA﹕ av_read_frame error: fffffffb(�,�,�,�): unknown

**Comment by hwpo** [comment]
I'll keep on doing it.
THKS anyway

**Comment by Android4MediaPlayer** [comment]
我用魅族3(M351) 测试也没有问题啊 网络问题吗

**Comment by Android4MediaPlayer** [comment]
@hwpo

**Comment by hwpo** [comment]
@Android4MediaPlayer 不是网络问题，用mx4每次播放到4分钟左右的时候一定会断掉，然后报错，小米2s也会断，但是时间不固定

**Comment by hwpo** [comment]
问题解决了，服务端主动断开了TCP连接，但是客户端没有去重连

http.c
read_ret = http_buf_read(h, buf, size);
    if (read_ret < 0 && s->reconnect && !h->is_streamed && s->filesize > 0 && s->off < s->filesize) {
        av_log(h, AV_LOG_ERROR, "Will reconnect at %"PRId64".\n", s->off);
        seek_ret = http_seek_internal(h, s->off, SEEK_SET, 1);
        if (seek_ret != s->off) {
            av_log(h, AV_LOG_ERROR, "Failed to reconnect at %"PRId64".\n", s->off);
            return read_ret;
        }

        read_ret = http_buf_read(h, buf, size);
    }
这段代码没有走，是因为没有设置reconnect，默认值为0，所以不会走这段代码。
设置方法如下：
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "reconnect", 1);

**Comment by Android4MediaPlayer** [comment]
这个我是设置了的

**Comment by Android4MediaPlayer** [comment]
所以不会～

**Comment by hwpo** [comment]
@Android4MediaPlayer demo里面没有设置。。。蛋疼了我一周。。。

**Comment by Android4MediaPlayer** [comment]
查到问题就好~ 可以关闭问题了

**Comment by zengyunpeng** [comment]
设置了,拔掉网线然后马上插上,视频还是不能续播
