### ISSUE TITLE
Android 最新版编译的库文件  视频播放可以，但是调用 seekTo 方法 就崩溃了

### ISSUE THREAD

**Issue by Mongolian** [Bilibili/ijkplayer#446]
请问这个是什么问题呢， 错误日志： Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 10483

**Comment by bbcallen** [comment]
Any log?

**Comment by Mongolian** [comment]
没有更多log 我看是调用native 的seekTo 方法就崩溃了，是不是我库编译的有问题 ，我编译好的库文件就三个libijkffmpeg.so,  libijkplayer.so , libijksdl.so 三个库文件。你有没有编译好的可以发我一个试试呢~ 我的联系方式403685209@qq.com 多谢

**Comment by bbcallen** [comment]
Which hash are you using?
I have fixed a crash in 24c5b430000cc304bbcd394f71ad714a2f15897b.
Can it fix your crash?
