### ISSUE TITLE
Fail to build ffmpeg and openssl on Android NDK r16-r18

### ISSUE THREAD

**Issue by karma-sun** [bilibili/ijkplayer#4468]
need to change build scripts to use clang instead of the deprecated gcc to compile

**Comment by biezhihua** [comment]
目前这个库还不支持使用NDK16版本进行构建，哪怕你改了脚本也不行。

我自己写了个构建脚本，已经解决了这个问题，欢迎使用。

https://github.com/biezhihua/FFmpegBuildTool

**Comment by karma-sun** [comment]
ijkplayer已废弃
