### ISSUE TITLE
crc.c crash

### ISSUE THREAD

**Issue by MingjunZou** [Bilibili/ijkplayer#447]
直播地址为http://112.74.192.59:9005/VMAwqQeaXp这个时崩溃在
    while (buffer < end)
        crc = ctx[((uint8_t) crc) ^ *buffer++] ^ (crc >> 8);
后台log为：
av_version_info: n2.7-29-g33056c9
ijkmp_set_format_callback(0x374e9, 0x16d9e6e0)
ijkmp_set_format_callback()=void
ijkmp_set_option_int(start-on-prepared, 1)
ijkmp_set_option_int()=void
2015-09-08 20:04:22.279 IJKMediaDemo[27367:60b] OK setup GL
ijkmp_ios_set_view(glView=0x16d9d920)
ijkmp_ios_set_view(glView=0x16d9d920)=void
ijkmp_set_option(overlay-format, fcc-i420)
ijkmp_set_option()=void
ijkmp_set_option_int(framedrop, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(max-fps, 30)
ijkmp_set_option_int()=void
ijkmp_set_option_int(video-pictq-size, 3)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox-max-frame-width, 960)
ijkmp_set_option_int()=void
ijkmp_set_option_int(auto_convert, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(timeout, 30000000)
ijkmp_set_option_int()=void
ijkmp_set_option(user-agent, ijkplayer)
ijkmp_set_option()=void
ijkmp_set_option_int(reconnect, 1)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_loop_filter, 48)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_frame, 8)
ijkmp_set_option_int()=void
ijkmp_set_option_int(analyzeduration, 2000000)
ijkmp_set_option_int()=void
ijkmp_set_option_int(probsize, 4096)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_loop_filter, 8)
ijkmp_set_option_int()=void
ijkmp_set_data_source(url="http://112.74.192.59:9005/VMAwqQeaXp")
ijkmp_set_data_source(url="http://112.74.192.59:9005/VMAwqQeaXp")=0
ijkmp_set_option(safe, 0)
ijkmp_set_option()=void
ijkmp_prepare_async()
===== options =====
player-opts : start-on-prepared            = 1
player-opts : overlay-format               = fcc-i420
player-opts : framedrop                    = 0
player-opts : max-fps                      = 30
player-opts : video-pictq-size             = 3
player-opts : videotoolbox-max-frame-width = 960
format-opts : auto_convert                 = 0
format-opts : timeout                      = 30000000
format-opts : user-agent                   = ijkplayer
format-opts : reconnect                    = 1
format-opts : analyzeduration              = 2000000
format-opts : probsize                     = 4096
format-opts : safe                         = 0
codec-opts  : skip_frame                   = 8
codec-opts  : skip_loop_filter             = 8
===================
ijkmp_prepare_async()=0
ijkmp_start()
ijkmp_start()=-3
request: GET /VMAwqQeaXp HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=0-

Connection: close

Host: 112.74.192.59:9005

Icy-MetaData: 1

Format mp3 probed with size=2048 and score=51
Skipping 0 bytes of junk at 0.
Option safe not found.
Before avformat_find_stream_info() pos: 0 bytes read:2880 seeks:0

**Comment by bbcallen** [comment]
Fixed in ffmpeg https://github.com/Bilibili/FFmpeg/commit/250af29be195be3239b4a92a22c0e8e106797da8
re-run init-android.sh or init-ios.sh and re-compile ffmpeg

**Comment by Android4MediaPlayer** [comment]
It is OK.

**Comment by Android4MediaPlayer** [comment]
@MingjunZou please close the item.

**Comment by MingjunZou** [comment]
ok, thanks
