### ISSUE TITLE
最近几个版本编译后sample程序都无法快进，多点2次就crash

### ISSUE THREAD

**Issue by ioryli** [Bilibili/ijkplayer#449]
主干最新版本， 和 最新的release版本都有这个问题。请问下 最近一个稳定版是哪一个呢？ 求推荐一个。

**Comment by ioryli** [comment]
解决了。。。回退到 k3.2.1是ok了的。 麻烦作者看下吧 ，这个在 k3.2.2以后都有这个问题

**Comment by bbcallen** [comment]
Any crash log?
