### ISSUE TITLE
Most easy sample to integrate ijkplayer android in a project ?

### ISSUE THREAD

**Issue by linked67** [Bilibili/ijkplayer#450]
Hi,

The sample is not working on eclipse and i have some hart time to see how this works on android.
I have follow the build steps and referenced the librarys.

Is there some small code to easy integrate ijkplayer into my app ?
Something like:

    // init player
    IjkMediaPlayer.loadLibrariesOnce(null);
    IjkMediaPlayer.native_profileBegin("libijkplayer.so");

    IjkMediaPlayer videoView1 = (IjkMediaPlayer) findViewById(R.idvideoview1);
    IjkMediaPlayer videoView2 = (IjkMediaPlayer) findViewById(R.id.videoview2);

Of course, this code don't work...
I just need a simple video view that display a stream, no pause/play or any other button.

**Comment by linked67** [comment]
I mean, does i need all the files that are in the sample (that does not work on eclipse with latest android SDK) or can i just use a simple view from a few lines of code ?

**Comment by bbcallen** [comment]
No, sample is only a sample. It only demonstrate how to use IjkMediaPlayer.

You can import player-* modules into eclipse without any dependence.
Or you can fetch eclipse sample from old version.

**Comment by linked67** [comment]
Thanks for your help but it's still not very clear. Even in older version, i see a VideoView.java class(widget) that is used in a XML file for easy use in activity, like this:

    mVideoView = (VideoView) findViewById(R.id.video_view);
    mVideoView.setMediaController(mMediaController);
    mVideoView.setMediaBufferingIndicator(mBufferingIndicator);
    mVideoView.setVideoPath(mVideoPath);
    mVideoView.requestFocus();
    mVideoView.start();

But if i try to copy this widget, i get lots of problem because it depend on MediaController or any other Class.

Can i import something to use just these few lines ?
I don't see any widget in ijkplayer-java i can import.

**Comment by linked67** [comment]
I just have found that the VideoView that was in the widget has been removed or moved to sample.
For the moment i have these folders:
ijkplayer-arm64
ijkplayer-armv5
ijkplayer-armv7a
ijkplayer-java
ijkplayer-sample (not working with v23)
ijkplayer-x86

None of them have a widget(VideoView) i can use in my activity xml.
What should i import to have a very basic player without any control ?
Or is it just no possible to do it in a few lines of code ?
