### ISSUE TITLE
慢动作视频播放越过

### ISSUE THREAD

**Issue by Break369** [Bilibili/ijkplayer#4503]
你好！在使用ijkplayer进行播放有慢动作的视频就会直接跳过慢动作的部分，应该如何处理？视频链接：http://alihk.peekaboocdn.com/hk/videos/hd/201804/537725362/d93538493d644a87834c435a7d2239cf1df5274dfd4211d5a50d3b56235dda3e.mp4

**Comment by Break369** [comment]
android

**Comment by 52yaoer** [comment]
mark下，持续关注。。。
