### ISSUE TITLE
添加编码器  HEVC

### ISSUE THREAD

**Issue by hrdzkj** [bilibili/ijkplayer#4505]
打开了export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-encoders"。 重新编译发现没有HEVC编码器。请问如何添加HEVC编码器。

**Comment by Koala2017** [comment]
解决了吗？分享下啊，我也需要支持hevc

**Comment by hrdzkj** [comment]
解决了，不是用添加hevc的方法，而是通过opengl渲染录像
