### ISSUE TITLE
avcodec_open2 返回-1

### ISSUE THREAD

**Issue by hrdzkj** [Bilibili/ijkplayer#4506]
代码如下：
            encoder= avcodec_find_encoder(AV_CODEC_ID_H263);          
            if (!encoder){
               av_log(ffp, AV_LOG_ERROR, "--->can not find video encoder %s\n",avcodec_name);
               continue;
            }

            enc_ctx->height = dec_ctx->height;
            enc_ctx->width = dec_ctx->width;
            enc_ctx->sample_aspect_ratio = dec_ctx->sample_aspect_ratio;       
            enc_ctx->pix_fmt = encoder->pix_fmts[0]; 
            enc_ctx->time_base = dec_ctx->time_base;
      
            ret =avcodec_open2(enc_ctx, encoder, NULL);
            if (ret < 0) {
               av_log(NULL, AV_LOG_ERROR, "-----> Cannot openvideo encoder for stream %d,%s\n",ret, av_err2str(ret));
               goto end;
            }

运行结果：
10-29 15:24:33.518 6758-6758/tv.danmaku.ijk.media.example E/IJKMEDIA: -----> Cannot openvideo encoder for stream -1,Operation not permitted

问题： 请问avcodec_open2 错误如何解决？

**Comment by Heber-xu** [comment]
@hrdzkj 你好，请问这个问题是怎么解决的？我也遇到了，不知道怎么解决。
