### ISSUE TITLE
IJK无法播放加密后的m3u8

### ISSUE THREAD

**Issue by yonghaocai** [Bilibili/ijkplayer#4524]
ijk无法播放带有加密key的m3u8视频。  
ffmpeg编译时支持了https 和 crypto
附log:
Opening 'https://laoshi.xueersi.com/AppIosCourse/getVideoKey/d76a536f55dce78b5de5bcca80529199' for reading
Hit DNS cache hostname = laoshi.xueersi.com
2018-11-12 13:25:33.843051+0800 m3u8IJKDemo[70545:808592] OK setup GL
2018-11-12 13:25:33.843950+0800 m3u8IJKDemo[70545:808592] IJKFFMoviePlayerController:applicationDidBecomeActive: 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0000.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0001.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0002.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0003.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0004.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0005.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0006.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0007.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0008.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0009.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0010.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0011.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0012.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0013.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0014.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0015.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0016.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0017.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0018.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0019.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0020.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0021.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0022.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0023.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0024.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0025.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0026.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0027.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0028.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0029.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0030.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0031.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0032.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0033.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0034.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0035.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0036.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0037.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0038.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0039.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0040.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0041.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0042.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0043.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0044.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0045.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0046.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0047.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0048.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0049.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0050.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0051.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0052.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0053.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0054.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0055.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0056.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0057.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0058.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0059.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0060.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0061.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0062.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0063.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0064.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0065.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0066.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0067.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0068.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0069.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0070.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0071.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0072.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0073.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0074.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0075.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0076.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0077.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0078.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0079.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0080.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0081.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0082.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0083.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0084.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0085.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0086.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0087.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0088.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0089.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0090.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0091.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0092.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0093.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0094.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0095.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0096.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0097.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0098.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0099.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0100.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0101.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0102.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0103.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0104.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0105.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0106.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0107.ts' for reading
Failed to open segment of playlist 0
Opening 'crypto+https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0108.ts' for reading
Failed to open segment of playlist 0
Error when loading first segment 'https://t1.xesv5.com/2014/05/a6d7ac50c400c06eb32a5c2a461da0d5/0000.ts'
https://laoshi.xueersi.com/AppIosCourse/getVideoPath/46358/167721: Invalid data found when processing input
2018-11-12 13:25:33.929580+0800 m3u8IJKDemo[70545:808592] FFP_MSG_ERROR: -1094995529
2018-11-12 13:25:33.930675+0800 m3u8IJKDemo[70545:808592] IJKMPMoviePlayBackStateDidChange 2: paused
2018-11-12 13:25:33.931075+0800 m3u8IJKDemo[70545:808592] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1

**Comment by yonghaocai** [comment]
@raymond1012

**Comment by kandynan** [comment]
add crypto protocol

**Comment by yonghaocai** [comment]
是的。是我编译的有问题。添加crypto protocol就能播放了。

**Comment by GJson** [comment]
@yonghaocai   怎么解决的？

**Comment by yonghaocai** [comment]
> @kandynan 怎么解决的呀

修改 ../config/module.sh ，注释 export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=crypto" 
支持crypto协议。
重新编译

**Comment by XiaoYiS** [comment]
@yong
https://github.com/bilibili/ijkplayer/issues/4524#issuecomment-456298762

注释？是把disable 改为enable吗

**Comment by yonghaocai** [comment]
是的。enable

**Comment by YYHNobug** [comment]
你好，你们是加密的整个m3u8文件，还是对每个ts进行的加密？我的场景是加密了没个ts，知道IJK怎么播放吗

**Comment by YYHNobug** [comment]
你好，我的场景是：iOS需要播放加密的m3u8文件，后台把每个ts地址进行加密，客户端进行解密后播放，请问IJK支持吗？现在解密每个ts已实现，该怎么播放？希望得到您的帮助。
已修改export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=crypto”，支持crypto协议

**Comment by yefangqingchen** [comment]
大哥，解决了吗，

**Comment by yonghaocai** [comment]
解决了。 看上面的。
修改 ../config/module.sh ，注释 export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=crypto"
支持crypto协议。
重新编译
