### ISSUE TITLE
Seek后 回退问题。

### ISSUE THREAD

**Issue by asawalker** [Bilibili/ijkplayer#453]
android端，播放m3u8视频， 当seek 到  某一切片内后，会   回退到目标切片的起始pos。

比如，m3u8文件中  有 10个切片，当前pos 是在 第2个切换，这个时候，我seek 到 第5个切片之内，第5个切片假如是  10:20——10：40，也就是说 当我seek 到 10:30的时候，回 回退到10:20的位置，也就是说 回退了 10s。

可知 此问题？

**Comment by Android4MediaPlayer** [comment]
revert "avformat/hls: disable seek within segment" commit for ffmpeg, and re-compiler ffmpeg.

**Comment by asawalker** [comment]
@Android4MediaPlayer  "ffmpeg disable seek within segment", are you sure? How to solve it?

**Comment by Android4MediaPlayer** [comment]
in ffmpeg Bilibili/FFmpeg@255dd66

**Comment by asawalker** [comment]
@Android4MediaPlayer 你的意思是 需要修改 ffmpeg的代码，然后 重新编译？ 是这个意思吗？谢谢了

**Comment by asawalker** [comment]
@Android4MediaPlayer  我看了 Bilibili/FFmpeg@255dd66 的patch，只是添加了一段代码 pls->seek_timestamp = AV_NOPTS_VALUE;
这个patch 是2014 年 上传的，但是 我是今天4月份 拉的代码编译的 还是有这个问题的，麻烦解释下。谢谢

**Comment by Android4MediaPlayer** [comment]
先要有range功能呀，看hls是否实现，bbc是在实现基础上关了

**Comment by bbcallen** [comment]
段内seek可能花屏，如果确实需要，请自己revert掉。

**Comment by asawalker** [comment]
@bbcallen 在线播放的时候，如果在已经缓存的片段内 去段内seek 会不会花屏？

**Comment by bbcallen** [comment]
Depending on how it was encoded and segmented.

**Comment by asawalker** [comment]
我看 你们B站的 拖动进度条，回退 会保持在5s以内。你们的视频格式 也是m3u8吗？我用咱们的播放器 播放m3u8的时候，如果 视频 是10分钟以内 并且 切片 比较大的情况下，看起来 进度条 会 回退很多。

**Comment by xiaoyaomeng** [comment]
public void onStopTrackingTouch(SeekBar bar) {
            if (!mInstantSeeking) {
                // mPlayer.seekTo((mDuration * bar.getProgress()) /
                // PROGRESS_MAX);
                mPlayer.seekTo((long)(mDuration * (bar.getProgress() * 1.0f / PROGRESS_MAX)));
            }

public void onProgressChanged(SeekBar bar, int progress,
                boolean fromuser) {
            if (!fromuser)
                return;

            // final long newposition = (mDuration * progress) / PROGRESS_MAX;
            final long newposition = (long)(mDuration * (progress * 1.0f / PROGRESS_MAX));

@asawalker 这样改一下
