### ISSUE TITLE
windows+msys+ndk编译不过，以前编译纯ffmpeg是可以的，问题多出在脚本上

### ISSUE THREAD

**Issue by sunbinjin** [Bilibili/ijkplayer#454]
我昨天开妈编译ijkplayer，发现新手要编译过它不容易，所以把一些遇到的问题给列出来，作者如果写得更好，大家可以更容易编译出来，而专注修改代码 ：）

1.readme里面可以专写一栏关于windows编译的一些注意事项
    如export ANDROID_NDK=/F/Android\ndk\android-ndk-r10c
    刚看有人看到ndk明明高版本，但还提示ndk版本不对，多是路径没写全，windows下不习惯从/开始写起
2.windows+msys+ndk-r10c编译错误

$ ./compile-ffmpeg.sh armv7a
====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a x86 arm64
FF_ACT_ARCHS = armv7a

====================
[*] check env armv7a
====================
build on MINGW32_NT-6.2 i686
ANDROID_SDK=/F/Android/sdk
ANDROID_NDK=/F/Android/ndk/android-ndk-r10c
NDKr10c detected

--------------------
[*] make NDK standalone toolchain
--------------------
which: nproc: unknown command
expr: warning: unportable BRE: `^\\([^\\-].*\\)$': using `^' as the first charac
ter
of the basic regular expression is not portable; it is being ignored
expr: warning: unportable BRE: `^\\(--[^=]*\\)=.*$': using `^' as the first char
acter
of the basic regular expression is not portable; it is being ignored
expr: warning: unportable BRE: `^--[^=]*=\\(.*\\)$': using `^' as the first char
acter
of the basic regular expression is not portable; it is being ignored
expr: warning: unportable BRE: `^\\([^\\-].*\\)$': using `^' as the first charac
ter
of the basic regular expression is not portable; it is being ignored
expr: warning: unportable BRE: `^\\(--[^=]*\\)=.*$': using `^' as the first char
acter
of the basic regular expression is not portable; it is being ignored
expr: warning: unportable BRE: `^--[^=]*=\\(.*\\)$': using `^' as the first char
acter
of the basic regular expression is not portable; it is being ignored
expr: warning: unportable BRE: `^\\([^\\-].*\\)$': using `^' as the first charac
ter
of the basic regular expression is not portable; it is being ignored
expr: warning: unportable BRE: `^\\(--[^=]*\\)=.*$': using `^' as the first char
acter
of the basic regular expression is not portable; it is being ignored
expr: warning: unportable BRE: `^--[^=]*=\\(.*\\)$': using `^' as the first char
acter
of the basic regular expression is not portable; it is being ignored
Copying prebuilt binaries...
Copying sysroot headers and libraries...
Copying c++ runtime headers and libraries...
Copying files to: /f/Android/Source/ijkplayer/android/contrib/build/ffmpeg-armv7
a/toolchain
Cleaning up...
Done.

--------------------
[*] check ffmpeg env
--------------------
/f/Android/Source/ijkplayer/android/contrib/../../config/module.sh: line 1: modu
le-lite.sh: command not found
建议：
1.nproc这个是干啥的，有办法解决么？
2.后面一堆 的像正则表达式的东东，可以用其它方法实现不？
3.module-lite.sh: command not found，能不能不要用linux里的文件连接，这东东在windows下没有，直接让module.sh去执行module-lite.sh就好了，这样如果想执行module-default.sh，直接改module.sh里的文本就好了，或者你在更上层提供一个参数也行，这样这套编译跨平台能力更强

等发现新问题再补充，暂时卡在这了……，装linux虚拟机还要时间 :)

**Comment by bbcallen** [comment]
windows build env is not under my maintain
