### ISSUE TITLE
[Android]The view was white and crashed later when i used TextureView to play stream

### ISSUE THREAD

**Issue by ioleon13** [Bilibili/ijkplayer#455]
使用最新支持textureview的版本，播放网络流媒体格式，有时候会出现屏幕一片白，声音播放正常，这个时候点击屏幕，出现crash，crash log如下：
E/AndroidRuntime(12917): FATAL EXCEPTION: main
E/AndroidRuntime(12917): Process: com.XXXX, PID: 12917
E/AndroidRuntime(12917): java.lang.IllegalStateException: eglMakeCurrent failed EGL_BAD_ALLOC
E/AndroidRuntime(12917): 	at android.view.HardwareRenderer$GlRenderer.createSurface(HardwareRenderer.java:1410)
E/AndroidRuntime(12917): 	at android.view.HardwareRenderer$GlRenderer.createEglSurface(HardwareRenderer.java:1292)
E/AndroidRuntime(12917): 	at android.view.HardwareRenderer$GlRenderer.initialize(HardwareRenderer.java:1106)
E/AndroidRuntime(12917): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2264)
E/AndroidRuntime(12917): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1314)
E/AndroidRuntime(12917): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6951)
E/AndroidRuntime(12917): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
E/AndroidRuntime(12917): 	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
E/AndroidRuntime(12917): 	at android.view.Choreographer.doFrame(Choreographer.java:560)
E/AndroidRuntime(12917): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
E/AndroidRuntime(12917): 	at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime(12917): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(12917): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(12917): 	at android.app.ActivityThread.main(ActivityThread.java:5332)
E/AndroidRuntime(12917): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(12917): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(12917): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
E/AndroidRuntime(12917): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
E/AndroidRuntime(12917): 	at dalvik.system.NativeStart.main(Native Method)

@bbcallen Tks

**Comment by bbcallen** [comment]
Device and System Information?
Is it crashed in sample or in your own app?

**Comment by Android4MediaPlayer** [comment]
yes,please give more infomation.

**Comment by ioleon13** [comment]
@bbcallen @Android4MediaPlayer 
Device info: huawei p8 Lite (ALE-TL00)  Android5.0
It crashed in my own app

**Comment by bbcallen** [comment]
Does it crash in sample?
There is nothing helpful related to ijkplayer in log

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
