### ISSUE TITLE
关于ffmpeg库的几个问题 ：）

### ISSUE THREAD

**Issue by sunbinjin** [Bilibili/ijkplayer#456]
1.作者把ffmpeg仓库取了一份300M，又复制出4份来对应不同的cpu，一定要这样做吗 ：）
我的意思直接用那一份编译4次生成不同的库也行吧？多复制了1个G空间不说，管理起来也麻烦呀

2.现在的init-android.sh默认取的是ijk-r0.2.4-dev，这个版本不知道对应ffmpeg哪个版本？为什么不取最新版本呢？手动取成ijk-r0.3.3-dev会怎么样 ：）

3.从这取的ffmpeg与从ffmpeg官网取的有何不同？作者是修改过很多东西吗？
我们应该是需要使用ijk相关版本或tag是吗？

**Comment by Android4MediaPlayer** [comment]
1.你可以修改脚本把不同cpu编译的.o存不同目录；
2.2.7版本，不同版本有修改的代码；
3.有做修改，有些地方有依赖，用ijk的就好

**Comment by bbcallen** [comment]
1. I need fast rebuild for debug.
2. There are tens of new commit in FFmpeg every day, I don't have time to test them every day.
3. Run "git log" in ffmpeg directory.

**Comment by sunbinjin** [comment]
谢谢，明白了，现在用0.3.3来工作

**Comment by Android4MediaPlayer** [comment]
问题应该解决了
