### ISSUE TITLE
android 使用YV12格式起播会闪一下绿屏

### ISSUE THREAD

**Issue by 18565773346** [Bilibili/ijkplayer#4561]
由于系统限制，播1080p只有yv12不卡，并且只能使用软解，开启硬解也会很卡，gpu太烂了

**Comment by qazmoon** [comment]
这是有问题还是没问题？

**Comment by 18565773346** [comment]
> 这是有问题还是没问题？

播放没问题，就是想去掉起播这个绿屏

**Comment by 18565773346** [comment]
@qazmoon  你有发现是什么导致闪绿屏吗，有解决办法没

**Comment by qazmoon** [comment]
diff --git a/ijkmedia/ijksdl/android/android_nativewindow.c b/ijkmedia/ijksdl/android/android_nativewindow.c
index b9fb3458..4fa4e617 100644
--- a/ijkmedia/ijksdl/android/android_nativewindow.c
+++ b/ijkmedia/ijksdl/android/android_nativewindow.c
@@ -263,6 +263,7 @@ int SDL_Android_NativeWindow_display_l(ANativeWindow *native_window, SDL_VoutOve
         return -1;
     }

+    voutDesc = native_window_get_desc(out_buffer.format);
     int render_ret = voutDesc->render(&out_buffer, overlay);
     if (render_ret < 0) {
         // TODO: 8 set all black
(END)

**Comment by 18565773346** [comment]
@qazmoon  问题解决了 谢谢  #4560
