### ISSUE TITLE
ios - buffer some CVImageBufferRef objects into queue after decoding callback

### ISSUE THREAD

**Issue by progamertr** [Bilibili/ijkplayer#457]
Hello Developer,

Thanks for your great project, this is a question, not an issue. If you help me, I am very appreciated.

After the videotoolbox decoding, as you know, the callback is called which is below

void VTDecoderCallback(void *decompressionOutputRefCon,
                       void *sourceFrameRefCon,
                       OSStatus status,
                       VTDecodeInfoFlags infoFlags,
                       CVImageBufferRef imageBuffer,
                       CMTime presentationTimeStamp,
                       CMTime presentationDuration)

I don't want to send the imageBuffer object directly to opelgl render, indeed I want to buffer some of them into my picture queue like in ffplay (in ffplay there is a static queue which has 4 frames in it)

How ever, I can not get the correct data pointer and size for kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange format type frame.

Could you please tell me how I can copy the data in imageBuffer object  to uint8 type data with memcpy

For example, with software decoding with ffmpeg for 420p format,

        fillFrameData(pFrame->data[0], vidFrame.pLuma.data, vidFrame.pLuma.size, pFrame->linesize[0],
                      _codecContext->width, _codecContext->height);
        fillFrameData(pFrame->data[1], vidFrame.pChromaB.data, vidFrame.pChromaB.size, pFrame->linesize[1],
                      _codecContext->width/2, _codecContext->height/2);
        fillFrameData(pFrame->data[2], vidFrame.pChromaR.data, vidFrame.pChromaR.size, pFrame->linesize[2],
                      _codecContext->width/2, _codecContext->height/2);

I can copy the image data to my vidFrame object by above way

Thanks,

- MG

kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/ios/IJKMediaPlayer/IJKMediaPlayer/ijkmedia/ijksdl/ios/ijksdl_vout_overlay_videotoolbox.m#L56

**Comment by tnadus** [comment]
bbcallen, you mean that using CVBufferRetain is the only way ?

**Comment by progamertr** [comment]
Also, I am calculating the queue size and so I need to get the size of imageBuffer object, how can I get this ?

**Comment by bbcallen** [comment]
If you mean size in bytes:
imageBufferSize = width_in_pixel * height_in_pixel * sizeof(byte) * bits_per_pixel (12 bits per pixel for NV12)

**Comment by progamertr** [comment]
Yes, that is what I exactly need, thank you.

Is there any way to get Y,U,V planes separately from imageBuffer in kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange format ?

**Comment by YangYuZhe** [comment]
Is it possible for me to get CVImageBufferRef by using this player?

**Comment by bbcallen** [comment]
You are free to modify what you want.
