### ISSUE TITLE
ijkplayer播放高清ts流，音视频同步问题。

### ISSUE THREAD

**Issue by huijiawanquba** [Bilibili/ijkplayer#4584]
大家好，我用的k0.8.8版本的ijkplayer播放高清ts流（局域网传输，不是网速问题），音视频同步稍差（音频慢一两秒，视频循环播放的时候延迟会累加），不知从哪优化，外面设置播放参数也无效。我用其它版本的也是这个问题，有优化过的麻烦告知一下，谢谢！

**Comment by Android4MediaPlayer** [comment]
enable mediacodec

**Comment by huijiawanquba** [comment]
请问是在哪设置的？我在Java层设置的有这些参数：

ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
                        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-auto-rotate", 1);
                        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-handle-resolution-change", 1);
                        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 1);
                        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "start-on-prepared", 0);
                        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "http-detect-range-support", 0);
                        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 48);

**Comment by huijiawanquba** [comment]
我昨天用多个版本的ffplay测试了一下视频源，发现视频源是不同步的，可以确定是视频源本身的问题，不是代码的问题。谢谢Android4MediaPlayer，感谢回复。

**Comment by Glumelin** [comment]
@huijiawanquba  请问下  ijkplayer播放ts流  需要设置什么参数吗？还是修改ff_play.c文件，能否告知如何修改

**Comment by Gouzhong1223** [comment]
您好,请问您的TS流就是188或者204字节一个包的那种TS传输流么
