### ISSUE TITLE
为何我在播放的时候锁不了屏幕

### ISSUE THREAD

**Issue by yanlj** [Bilibili/ijkplayer#459]
我把所有的idleTimerDisabled都设置了NO，但是播放的时候，屏幕会黑但是锁不了，暂停的时候就会锁屏，请问是什么原因呢

**Comment by Android4MediaPlayer** [comment]
锁屏调用暂停

**Comment by yanlj** [comment]
你好，能告诉我具体是那行代码锁屏调用的吗 ，我是ios的

**Comment by yanlj** [comment]
我把播放器里的所有 [UIApplication sharedApplication].idleTimerDisabled 设置都注释了  但是播放的时候就是不会锁屏，屏幕会变暗 不会锁

**Comment by bbcallen** [comment]
[IJKMediaModule sharedModule].appIdleTimerDisabled = YES

**Comment by yanlj** [comment]
并没有什么用，还是不能锁屏 我觉得是不是  ijkmp_start(_mediaPlayer);  这方法里面导致的不能锁屏

**Comment by yanlj** [comment]
发现debug的版本 锁不了屏幕  inhouse版可以锁屏
