### ISSUE TITLE
修改了module-lite.sh后so依然很大

### ISSUE THREAD

**Issue by a174232** [Bilibili/ijkplayer#4590]
替换了module-lite.sh，执行了以下命令
cd config
rm module.sh
ln -s module-lite.sh module.sh
cd android/contrib
sh compile-ffmpeg.sh clean
sh compile-ffmpeg.sh armv7a
编译出来的so依然很大

**Comment by YBill** [comment]
多大？你期望是多大？

**Comment by a174232** [comment]
GSYVideoPlayer这个里面也用到了这个libijkffmpeg才4M 目前我这边编译出来的接近15M

**Comment by YBill** [comment]
我用module-lite.sh编出来是4M多，module-default.sh编出来好像是12M，可能是你添加那些配置了

**Comment by aohanhongzhi** [comment]
编译后的文件怎么替换到原来工程啊？
https://github.com/Jzvd/JZVideo/issues/498
