### ISSUE TITLE
 Protocol not found

### ISSUE THREAD

**Issue by HappyGhostz** [bilibili/ijkplayer#4597]
error : IJKMEDIA: http://media-ali.wanmen.org/cd0a935c-d38d-4629-82d5-dde51b1d5dbd_mobile_low.m3u8?sign=21a4a3385730ccc316187d6d4ba36114&t=5c29c0e8&r=e02ff6123304538b427a164662f2b350: Protocol not found
error : tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

我用 exoplayer 播放这个url 提示的错误是没开启http重定向  当我使用exoplayer并 开启重定向后，exoplayer可以播放该条url。但当我转向 使用IjkMediaPlayer  这个播放该url时 会报Protocol not found 异常 ，我不知道该怎样处理了，能麻烦告知下解决方法吗  谢谢

**Comment by HappyGhostz** [comment]
该 url  会 http 重定向到 https    openssl 我也有编译   但是无法播放

**Comment by wnpllrzodiac** [comment]
明儿帮你看看

**Comment by wnpllrzodiac** [comment]
{"code":"40310910","msg":"authentication fails"}

**Comment by HappyGhostz** [comment]
谢谢

**Comment by HappyGhostz** [comment]
已解决

**Comment by uzaysan** [comment]
> solved

How did you solve? I'm facing same issue but i couldn't solve. Can you please explain?

**Comment by SHPDZY** [comment]
@HappyGhostz 怎么解决的，贴下代码，大佬

**Comment by HappyGhostz** [comment]
@SHPDZY  首先是保证编译的是正确的so 然后 我把缺少的protocol  添加到以下设置里就可以了  我的是一开始忘加rtmp了  加上以后就可以了  这个提示我是在logo中看到的
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", "rtmp,crypto,file,http,https,tcp,tls,udp");

**Comment by nicolasiJasica** [comment]
mark
