### ISSUE TITLE
Unexpected FFmpeg version

### ISSUE THREAD

**Issue by j364960953** [Bilibili/ijkplayer#462]
today , it is aleartview message 'Unexpected FFmpeg version', so, what I do?

**Comment by j364960953** [comment]
Xcode shows message on mac

**Comment by j364960953** [comment]
is 'rtsp:// ' support ?

**Comment by j364960953** [comment]
ijkmp_set_inject_opaque(0x7f9bb9f6ff90)
ijkmp_set_option_int(ijkinject-opaque, 140306816630672)
ijkmp_set_option_int()=void
ijkmp_set_inject_opaque()=void
ijkmp_set_option_int(start-on-prepared, 1)
ijkmp_set_option_int()=void
2015-09-14 14:03:40.415 IJKMediaDemo[25778:174173] OK setup GL
ijkmp_ios_set_view(glView=0x7f9bb9f66830)
ijkmp_ios_set_view(glView=0x7f9bb9f66830)=void
ijkmp_set_option(overlay-format, fcc-i420)
ijkmp_set_option()=void
ijkmp_set_option_int(skip_frame, 8)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_loop_filter, 48)
ijkmp_set_option_int()=void
ijkmp_set_option(user-agent, ijkplayer)
ijkmp_set_option()=void
ijkmp_set_option_int(auto_convert, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(timeout, 30000000)
ijkmp_set_option_int()=void
ijkmp_set_option_int(reconnect, 1)
ijkmp_set_option_int()=void
ijkmp_set_option_int(max-fps, 30)
ijkmp_set_option_int()=void
ijkmp_set_option_int(framedrop, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox-max-frame-width, 960)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(video-pictq-size, 3)
ijkmp_set_option_int()=void
ijkmp_set_data_source(url="rtsp://218.204.223.237:554/live/1/66251FC11353191F/e7ooqwcfbqjoo80j.sdp")
ijkmp_set_data_source(url="rtsp://218.204.223.237:554/live/1/66251FC11353191F/e7ooqwcfbqjoo80j.sdp")=0
ijkmp_set_option(safe, 0)
ijkmp_set_option()=void
ijkmp_prepare_async()
remove 'timeout' option for rtmp.
===== options =====
player-opts : start-on-prepared            = 1
player-opts : overlay-format               = fcc-i420
player-opts : max-fps                      = 30
player-opts : framedrop                    = 0
player-opts : videotoolbox-max-frame-width = 960
player-opts : videotoolbox                 = 0
player-opts : video-pictq-size             = 3
format-opts : ijkinject-opaque             = 140306816630672
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : safe                         = 0
format-opts : reconnect                    = 1
codec-opts  : skip_frame                   = 8
codec-opts  : skip_loop_filter             = 48
===================
ijkmp_prepare_async()=0
ijkmp_start()
ijkmp_start()=-3
remove 'timeout' option for rtmp.
rtsp://218.204.223.237:554/live/1/66251FC11353191F/e7ooqwcfbqjoo80j.sdp: Protocol not found
2015-09-14 14:03:40.427 IJKMediaDemo[25778:174173] FFP_MSG_ERROR: 0
2015-09-14 14:03:40.428 IJKMediaDemo[25778:174173] moviePlayBackStateDidChange 2: paused
2015-09-14 14:03:40.428 IJKMediaDemo[25778:174173] playbackStateDidChange: MPMovieFinishReasonPlaybackError: 1

hello, rtmp,m3u8 is live on,but rtsp is not

**Comment by bbcallen** [comment]
1. Clean and rebuild ffmpeg after checkout new ijkplayer source code.
2. No, modify module-lite.sh if you need it.

**Comment by j364960953** [comment]
thanks,i solved!

**Comment by tyhcyb** [comment]
How did you solve it?

**Comment by GCJ561** [comment]
help ？ about  'Unexpected FFmpeg version',
