### ISSUE TITLE
ijkplayer sdk pod support

### ISSUE THREAD

**Issue by maytrue** [Bilibili/ijkplayer#463]
How to set ijkplayer sdk with pod? So I can integrate ijkplayer sdk easily in my project?

**Comment by bbcallen** [comment]
Still waiting cocoapod to release 0.39 to fix some problems.

**Comment by KCastiglione** [comment]
cocoa pod 0.39 rc1 available now can be installed like this:

        gem install cocoapods --pre

**Comment by grandezot** [comment]
Still can't get pod install working, ijkplayer is not present on cocoapods and even the pod project in sources does not work. It still fails on pod install with:

[!] Unable to find a specification for `ijkplayer

**Comment by bbcallen** [comment]
No schedule, for now.
