### ISSUE TITLE
关于断网重连的问题

### ISSUE THREAD

**Issue by playervideo** [Bilibili/ijkplayer#464]
[options setTimeout:30 * 1000 * 1000];
请问一下这个timeout是指http重连的超时时间吗？如果断网了，开启重连，在这个超时时间内网络恢复的话，是不是可以重连成功？

**Comment by bbcallen** [comment]
https://www.ffmpeg.org/ffmpeg-protocols.html#http

**Comment by andyjmzheng** [comment]
@playervideo  http重连的超时时间。这个bug。你解决了吗？
