### ISSUE TITLE
编译时提示找不到 ijkversion.h

### ISSUE THREAD

**Issue by fankes** [bilibili/ijkplayer#4649]
编译时提示找不到 ijkversion.h 然后看了一下源码真的没有这个文件 但是在 ff_play.c这个文件里有引用

**Comment by CSsaan** [comment]
我也遇到了这个问题，发现是这个目录下的version.sh需要给权限：
chmod -R 777 version.sh
再次运行编译./compile-ijk.sh  xxx  即可。
