### ISSUE TITLE
请教~我想把x264编译到你们的ffmpeg中，但是失败了

### ISSUE THREAD

**Issue by JavanEu** [Bilibili/ijkplayer#465]
我参考了opengssl的编译方法。
但是x264虽然编译通过了，我们通过ffmpeg寻找x264的encoder的时候ffmpeg寻找失败。
不知道你的ln成so的方法我是否需要加入一些选项

**Comment by bbcallen** [comment]
Run command below to see if x264 symbol is linked
```
strings libijkffmpeg.so 
```

**Comment by JavanEu** [comment]
@bbcallen thks

**Comment by kingty** [comment]
@JavanEu 编译x264进去成功了吗？

**Comment by kingty** [comment]
@bbcallen 能请教一下怎么集成x264吗

**Comment by bbcallen** [comment]
@kingty Never used libx264.

**Comment by kingty** [comment]
@bbcallen we compiled the  ffmpeg and libx264 for compress the video when send a video ,is there any way to do it without it ?And I also want to replace the mediaplayer with ijkplayer.thks a lot for help.
