### ISSUE TITLE
[Android] NDK compile error

### ISSUE THREAD

**Issue by ioleon13** [Bilibili/ijkplayer#468]
Hi, @bbcallen 
When i git pull to the latest code, i got a compile error in $./compile-ijk.sh all, the error message as follows:
profiler build: NO
Android NDK: Could not find application project directory !
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.
/develop/adt-bundle-mac-x86_64-20131030/android-ndk-r10e/build/core/build-local.mk:143: *** Android NDK: Aborting    .  Stop.
/develop/02.code/github/ijkplayer-android/android
profiler build: NO
Android NDK: Could not find application project directory !
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.
/develop/adt-bundle-mac-x86_64-20131030/android-ndk-r10e/build/core/build-local.mk:143: *** Android NDK: Aborting    .  Stop.
/develop/02.code/github/ijkplayer-android/android
profiler build: NO
Android NDK: Could not find application project directory !
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.
/develop/adt-bundle-mac-x86_64-20131030/android-ndk-r10e/build/core/build-local.mk:143: *** Android NDK: Aborting    .  Stop.
/develop/02.code/github/ijkplayer-android/android
profiler build: NO
Android NDK: Could not find application project directory !
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.
/develop/adt-bundle-mac-x86_64-20131030/android-ndk-r10e/build/core/build-local.mk:143: *** Android NDK: Aborting    .  Stop.
/develop/02.code/github/ijkplayer-android/android

My Build Enviroment:
Mac OS X 10.10.3
Android NDK r10e

**Comment by bbcallen** [comment]
Fixed: 5469ffd614eedcff75fb8e349df6d36d7e609391
Thanks
