### ISSUE TITLE
使用ijkio协议不成功

### ISSUE THREAD

**Issue by passol1988** [bilibili/ijkplayer#4696]
搜索了相关的issue，不知道是哪一步操作失败了呢
1. 为url添加前缀 http://xxx.yyy.zzz/xx.m3u8 => ijkio:http://xxx.yyy.zzz/xx.m3u8 
   或者 rtmp://xxx.yyy.zzz/xx => ijkio:rtmp://xxx.yyy.zzz/xx
2. 设置option， `auto_save_map`,`parse_cache_map`,`cache_map_path`,`cache_file_path`
---
每次的结果总是 Operation not permitted

**Comment by passol1988** [comment]
部分调试成功

**Comment by luoxuuguang** [comment]
> 使用`ijkio:cache:ffio`部分调试成功

为什么我这边还是不成功呢-。-

**Comment by ZZZxwx** [comment]
怎么解决的？可以讲讲吗
