### ISSUE TITLE
iOS中，发现有很多都不能硬解码成功，请问H264视频流需要满足什么条件才能使硬解码成功

### ISSUE THREAD

**Issue by vicflight** [Bilibili/ijkplayer#471]

**Comment by bbcallen** [comment]
log, plz

**Comment by maytrue** [comment]
ios 8 以上

**Comment by Kestre1** [comment]
ijkmp_set_format_callback(0x1000ed8ac, 0x1701def00)
ijkmp_set_format_callback()=void
ijkmp_set_option_int(start-on-prepared, 1)
ijkmp_set_option_int()=void
2015-09-17 14:37:22.014 IJKMediaDemo[7804:2673589] OK setup GL
ijkmp_ios_set_view(glView=0x14d51c300)
ijkmp_ios_set_view(glView=0x14d51c300)=void
ijkmp_set_option(overlay-format, fcc-i420)
ijkmp_set_option()=void
ijkmp_set_option_int(skip_frame, 8)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_loop_filter, 48)
ijkmp_set_option_int()=void
ijkmp_set_option_int(timeout, 30000000)
ijkmp_set_option_int()=void
ijkmp_set_option_int(reconnect, 1)
ijkmp_set_option_int()=void
ijkmp_set_option(user-agent, ijkplayer)
ijkmp_set_option()=void
ijkmp_set_option_int(max-fps, 30)
ijkmp_set_option_int()=void
ijkmp_set_option_int(framedrop, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox-max-frame-width, 960)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox, 1)
ijkmp_set_option_int()=void
ijkmp_set_option_int(video-pictq-size, 3)
ijkmp_set_option_int()=void
ijkmp_set_data_source(url="rtp://192.168.2.122:5000")
ijkmp_set_data_source(url="rtp://192.168.2.122:5000")=0
ijkmp_set_option(safe, 0)
ijkmp_set_option()=void
ijkmp_prepare_async()
===== options =====
player-opts : start-on-prepared            = 1
player-opts : overlay-format               = fcc-i420
player-opts : max-fps                      = 30
player-opts : framedrop                    = 0
player-opts : videotoolbox-max-frame-width = 960
player-opts : videotoolbox                 = 1
player-opts : video-pictq-size             = 3
format-opts : timeout                      = 30000000
format-opts : reconnect                    = 1
format-opts : user-agent                   = ijkplayer
format-opts : safe                         = 0
codec-opts  : skip_frame                   = 8
codec-opts  : skip_loop_filter             = 48
===================
ijkmp_prepare_async()=0
ijkmp_start()
ijkmp_start()=-3
end receive buffer size reported is 65536
end receive buffer size reported is 65536
SDP:
v=0

c=IN IP4 192.168.2.122

m=application 5000 RTP/AVP 33


end receive buffer size reported is 65536
end receive buffer size reported is 65536
Option timeout not found.
stream=0 stream_type=0 pid=102 prog_reg_desc=
probing stream 0 pp:2500
probing stream 0 pp:2499
probing stream 0 pp:2498
probing stream 0 pp:2497
Probe with size=8356, packets=4 detected mp3 with score=1
probing stream 0 pp:2496
probing stream 0 pp:2495
probing stream 0 pp:2494
probing stream 0 pp:2493
non-existing PPS 0 referenced
non-existing PPS 0 referenced
decode_slice_header error
non-existing PPS 0 referenced
decode_slice_header error
no frame!
Invalid timestamps stream=0, pts=113017117, dts=113020120, size=1445
Current profile doesn't provide more RBSP data in PPS, skipping
invalid dts/pts combination 113062162
no picture 
Invalid timestamps stream=0, pts=113065165, dts=113068168, size=1813
Invalid timestamps stream=0, pts=113071171, dts=113074174, size=2181
Invalid timestamps stream=0, pts=113077177, dts=113080180, size=1813
Invalid timestamps stream=0, pts=113083183, dts=113086186, size=1629
Invalid timestamps stream=0, pts=113089189, dts=113092192, size=1997
Invalid timestamps stream=0, pts=113095195, dts=113098198, size=1997
probing stream 1 pp:2500
Probe with size=3850, packets=1 detected aac with score=25
probed stream 1
channel element 0.0 is not allocated
Invalid timestamps stream=0, pts=113101201, dts=113104204, size=1997
Invalid timestamps stream=0, pts=113107207, dts=113110210, size=1445
Invalid timestamps stream=0, pts=113113213, dts=113116216, size=1813
Invalid timestamps stream=0, pts=113119219, dts=113122222, size=2181
Invalid timestamps stream=0, pts=113125225, dts=113128228, size=1997
cannot set stream info, codec is open
cannot set stream info, codec is open
stream=2 stream_type=15 pid=103 prog_reg_desc=
All programs have pmt, headers found
Invalid timestamps stream=0, pts=113131231, dts=113134234, size=1937
All info found
max_frame_duration: 3600.000
Input #0, rtp, from 'rtp://192.168.2.122:5000':
  Duration: N/A, start: 1255.745744, bitrate: 41 kb/s
  Program 1 
    Stream #0:1, 24, 1/90000: Audio: aac, 22050 Hz, stereo, fltp, 41 kb/s
    Stream #0:0, 40, 1/90000: Video: h264 (Main), yuv420p(tv, bt709), 960x540, 0/1, 29.97 tbr, 90k tbn
    Stream #0:2, 0, 1/90000: Data: timed_id3 (ID3  / 0x20334449), 0/1
aout_open_audio()
AudioCodec: avcodec, aac
aout_pause_audio(0)
detected 2 logical cores
after scale width 960 height 540 
m_max_ref_frames 2 
fps: 29.970030 (normal)
Invalid timestamps stream=0, pts=113137237, dts=113140240, size=1997
Invalid timestamps stream=0, pts=113143243, dts=113146246, size=1813
2015-09-17 14:37:25.923 IJKMediaDemo[7804:2673589] FFP_MSG_VIDEO_DECODER_OPEN: true
ijkmp_get_msg: FFP_MSG_PREPARED
2015-09-17 14:37:25.923 IJKMediaDemo[7804:2673589] FFP_MSG_PREPARED:
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
2015-09-17 14:37:25.924 IJKMediaDemo[7804:2673589] mediaIsPreparedToPlayDidChange
flushed last keyframe pts 0 
2015-09-17 14:37:25.924 IJKMediaDemo[7804:2673589] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3
stereo with SCE
2015-09-17 14:37:25.924 IJKMediaDemo[7804:2673589] FFP_MSG_VIDEO_SIZE_CHANGED: 960, 540
2015-09-17 14:37:25.924 IJKMediaDemo[7804:2673589] FFP_MSG_SAR_CHANGED: 0, 1
2015-09-17 14:37:25.924 IJKMediaDemo[7804:2673589] moviePlayBackStateDidChange 1: playing
channel element 0.0 is not allocated
Invalid timestamps stream=0, pts=113149249, dts=113152252, size=2181
Invalid timestamps stream=0, pts=113155255, dts=113158258, size=1813
Invalid timestamps stream=0, pts=113161261, dts=113164264, size=2181
Invalid timestamps stream=0, pts=113167267, dts=113170270, size=1997
after scale width 960 height 540 
decode callback -12909 kVTVideoDecoderBadDataErr
2015-09-17 14:37:25.939 IJKMediaDemo[7804:2673732] seccuss:-12911
decodeFrame -12911 kVTVideoDecoderMalfunctionErr
ffp_toggle_buffering_l: start
aout_pause_audio(1)
RTP: missed 4282 packets
RTP: PT=21: bad cseq 841e expected=7364
RTP: missed 4283 packets
Continuity check failed for pid 258 expected 3 got 7
Continuity check failed for pid 257 expected 6 got 11
Continuity check failed for pid 258 expected 5 got 11
Invalid timestamps stream=0, pts=117791892, dts=117794895, size=525
Continuity check failed for pid 258 expected 12 got 14
Invalid timestamps stream=0, pts=117797898, dts=117800901, size=1629
Continuity check failed for pid 258 expected 7 got 11
unknown SEI type 160
unknown SEI type 81
SEI type 57 size 928 truncated at 920
Continuity check failed for pid 257 expected 13 got 15
Invalid timestamps stream=0, pts=117803904, dts=117806907, size=1997
Invalid timestamps stream=0, pts=117809910, dts=117812913, size=1813
Invalid timestamps stream=0, pts=117815916, dts=117818919, size=1629
PES packet size mismatch

**Comment by bbcallen** [comment]
Mostly caused by sps/pps stuffs.

**Comment by Kestre1** [comment]
同样的视频我通过http协议能够解码，通过rtp协议就出上面的问题。苹果的硬解码除了必须是h264编码、iOS8以上，还有其它的限制吗

**Comment by Android4MediaPlayer** [comment]
right sps/pps stuffs

**Comment by Kestre1** [comment]
我通过http协议，得到的是相同的sps/pps  能够解码，通过rtp协议却不能

**Comment by maytrue** [comment]
RTP协议不传输sps/pps，RTSP里SDP携带

**Comment by linjiansheng** [comment]
我也遇到，，关闭硬解码就正常播放

**Comment by yeshibuzhong** [comment]
请问 怎么开启硬解呢 ?  十分感谢
