### ISSUE TITLE
ijkplayer 如何隐藏了git的提交记录

### ISSUE THREAD

**Issue by solon-foot** [bilibili/ijkplayer#4722]
![TIM截图20190513104648](https://user-images.githubusercontent.com/11436948/57593088-79175200-756c-11e9-90e0-d88e542eb192.png)
如上图，我截图日期2019-5-13 10:46:48,然而代码中是没有提交记录的，那么他们的改动是指哪些东西呢，比较好奇

**Comment by TheLittleBoy** [comment]
pull requests 的时间可以对应上。

**Comment by solon-foot** [comment]
学习了
