### ISSUE TITLE
如何在交叉编译ffmpeg时添加libxml2支持

### ISSUE THREAD

**Issue by pkuzhd** [bilibili/ijkplayer#4734]
在编译参数中添加`--enable-libxml2`, 会出现

`ERROR: libxml-2.0 not found using pkg-config`

但是pkg-config是可以找到libxml-2.0信息的，而且非交叉编译是可以通过的

**Comment by JzwOnly** [comment]
@pkuzhd 大佬请问一下 该如何进行交叉编译呢  我在编译参数里添加 --enable-libsmbclient  编译时出现ERROR: libsmbclient not found

**Comment by pkuzhd** [comment]
> @pkuzhd 大佬请问一下 该如何进行交叉编译呢 我在编译参数里添加 --enable-libsmbclient 编译时出现ERROR: libsmbclient not found

时间比较久了，细节记得不太清了。

大致过程分两步：
1. 交叉编译libsmbclient
2. 让pkg-config知道你编译出来的库的路径

第二步我当时没有找到比较好的办法，我直接去改了使用pkg-config的相关shell语句

**Comment by JzwOnly** [comment]
@pkuzhd  大佬 我已经编译出libsmbclient.a 了  
但是第二步不太明白  应该把.a库放到哪里 或者改什么配置
编译还是error: libsmbclient not found

**Comment by pkuzhd** [comment]
> @pkuzhd 大佬 我已经编译出libsmbclient.a 了
> 但是第二步不太明白 应该把.a库放到哪里 或者改什么配置
> 编译还是error: libsmbclient not found

需要在添加--enable-libsmbclient的同时显式给出libsmbclient的位置。

我上次编译已经是一年前了，没有找到当时的虚拟机，没法给出具体的配置修改。

**Comment by chengzeyuan** [comment]
@JzwOnly 请问你是怎么编译出来libsmbclient.a文件的，我这边在ubuntu上编译，使用下面命令只得到了.so文件，没有任何.a文件生成
./configure --with-static-modules=ALL --nonshared-binary=smbtorture  
make

**Comment by yongjiaming** [comment]
请问 ERROR: libxml-2.0 not found using pkg-config 最后怎么解决的？

**Comment by pkuzhd** [comment]
需要自行编译不同平台的libxml2。你可以看下configure里关于--enable-libxml2的处理步骤，然后看看是哪个环节报的ERROR。

**Comment by pkuzhd** [comment]
> 请问 ERROR: libxml-2.0 not found using pkg-config 最后怎么解决的？

编译xml2之后设置一下PKG_CONFIG_PATH

**Comment by yongjiaming** [comment]
> > 请问 ERROR: libxml-2.0 not found using pkg-config 最后怎么解决的？
> 
> 编译xml2之后设置一下PKG_CONFIG_PATH

下载 tar 包后 make 编译会报错，目前我直接 brew install pkg-config 和 libxml2，按照提示设置了环境变量
```
export PATH="/opt/homebrew/opt/libxml2/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/libxml2/lib"
export CPPFLAGS="-I/opt/homebrew/opt/libxml2/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/libxml2/lib/pkgconfig"
```
 pkg-config libxml2 --cflags
```
-I/opt/homebrew/Cellar/libxml2/2.12.8/include/libxml2
```
看上去环境变量都配置好了，但是 ./compile-ffmpeg.sh all 后依然报 `ERROR: libxml-2.0 not found using pkg-config`，请问怎么解决呢？

**Comment by pkuzhd** [comment]
是这样的，你需要用的libxml2应该是针对你的手机平台（目标平台）的libxml2，通常是linux-arm，而你通过brew安装的libxml2是针对你本季平台的，看起来是针对mac的，是无法用于ffmpeg编译的。

建议下载libxml2的源码，编译出目标平台下的libxml2.
