### ISSUE TITLE
请问这个项目有一些文档不？我正在分析播放核心

### ISSUE THREAD

**Issue by sunbinjin** [Bilibili/ijkplayer#474]
我正在分析jni内核，简单的理解是：

整体解码内核使用了3个第三方库：
1.ffmpeg生成libijkffmpeg.so
2.sdl生成libijksdl.so
3.libyuv被静态链接进sdl中

作者的播放器库：
libijkplayer.so
基于ffplay，增加了不少东西，是Player级别的关键代码

作者自主功能主要在libijkplayer.so这块
因为我需要实现多文件无缝播放，所以我分析libijkplayer为主，但发现里面东西比我以前纯ffplay要多很多
但又不知道是为了解决什么问题的，所以麻烦问一下

    /* protocols */
    FF_REGISTER_PROTOCOL(async);
    IJK_REGISTER_PROTOCOL(ijkhttphook);
    IJK_REGISTER_PROTOCOL(ijkinject);
    IJK_REGISTER_PROTOCOL(ijklongurl);
    IJK_REGISTER_PROTOCOL(ijksegment);
    IJK_REGISTER_PROTOCOL(ijktcphook);

    /* demuxers */
    IJK_REGISTER_DEMUXER(ijklivehook);
1.以上增加的protocols 和demuxers 是为了解决什么特殊需求的？
2.里面大量用到的pipeline，pilenode，这些东西是为了做啥的？源ffplay没有这些东西 ：）
    pipe相关的设计思路是啥？
3.我猜想一般核心应该是不支持多文件无缝播放的，那在Java层创建多实例的话，不知道有问题不？
系统的MediaPlayer多实例没问题，但收到第一个文件的结束消息有延迟，虽说第二个播放早就prepare了，但还是导致第二个文件与第一个的接不上，有明显卡顿，所以只能用ffmpeg这种来解决问题。

问题比较多，作者不要介意哈

**Comment by bbcallen** [comment]
1. Experimental features.
2. Abstract interface for (decoder -> render), for switching it at runtime.
3. IjkPlayer does support multiple java instance, except that multiple hw decoders are depending on devices.

**Comment by qazmoon** [comment]
多文件是指不同codec的文件吗？目前多文件无缝播放不太可能，尤其是不同codec的切换。参考[426][1]
[1]:https://github.com/Bilibili/ijkplayer/issues/426

**Comment by cwq** [comment]
@sunbinjin 多文件无缝播放需要修改底层实现，软解的话可以有多个codec，在读取/解码和播放控制好codec的切换

**Comment by Android4MediaPlayer** [comment]
无缝播放在编码方面做成相同的，就可用concat了

**Comment by sunbinjin** [comment]
对，因为内容是可控的，所以多文件我们自己可以做成同样格式同样分辨率同样编码的文件 ：）

**Comment by sunbinjin** [comment]
@Android4MediaPlayer 请教比较简单的无缝播放在这个工程里怎么改合适？
我想到的Java层提前prepare下一个，在当前这个播放完的通知消息里开始播放下一个，但这样无缝效果不是很好，可能是第一个播放完消息有点晚。
另一种方法在jni里面改，复杂，比如第一个文件解码完成后开始解码第二个文件，但像sdl_audio_callback，Video显示线程这种代码，大量访问了VideoState结构，导致上下文不对……

**Comment by Android4MediaPlayer** [comment]
concat协议是最简单的

**Comment by sunbinjin** [comment]
@Android4MediaPlayer 看了下，concat有2种，1种是demuxer级，1种是protocol级 ,protocol 说是只能用于少数的几种，如mpeg，ts，我的mp4没戏？但demuxer能用于所有format
不知道demuxer级在ffplay里怎么应用？
另，我在windows下执行：
ffplay concat:1.mp4|2.mp4
结果ffplay并未连续播放2个文件，只播放了一个，而且还调用 系统关联播放器把所有文件都给打开了来播放，我有点对concat这个在ffplay上怀疑了
不知道你用concat是怎么用的？
麻烦你了 ：）

**Comment by Android4MediaPlayer** [comment]
不单单是本地文件，网络文件也是可以的，如下：
ffconcat version 1.0
file http://hot.vrs.sohu.com/ipad2457075_4648026007963_5668396.m3u8?plat=17&prod=app
duration 2935
file http://hot.vrs.sohu.com/ipad2457075_4648026007963_5668396.m3u8?plat=17&prod=app
duration 2935

**Comment by sunbinjin** [comment]
@Android4MediaPlayer 刚看了你提供的m3u8文件，里面写着虽说是mp4后缀，但把m3u8中的第一个URL下载下来，发现其实是一个几百K的ts文件，并非mp4的，里面的url中的mp4字样有点认人误解

另外，我手动生成如下文件：
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10, no desc
1.mp4
#EXTINF:10, no desc
2.mp4
#EXTINF:10, no desc
3.mp4
#EXTINF:10, no desc
4.mp4
#EXT-X-ENDLIST
这个ffplay是播放不了的，但如果把上面的mp4文件全换成ts，就可以播放
所以，mu38这种模式是用于hls的，好像对mp4支持不行……

还有更好的concat方法吗？

**Comment by Android4MediaPlayer** [comment]
网络流改成本地文件路径测试下

**Comment by Zard1096** [comment]
你生成的不是应该是m3u8而是根据

**Comment by sunbinjin** [comment]
@Android4MediaPlayer m3u8里写ts文件或ffplayer concat:1.ts|2.ts都是可以的
但只要把ts改成mp4都会不对，偏偏我的文件是mp4……

**Comment by sunbinjin** [comment]
@Zard1096 是不是打错字了，不好理解 ：）

**Comment by Zard1096** [comment]
你生成一个.ffconcat文件,里面的格式照着@Android4MediaPlayer 的写法，然后用ffplay去放这个文件

**Comment by Android4MediaPlayer** [comment]
@sunbinjin 原来你还没理解concat，这样你写一个test.ffconcat，假设你的MP4文件时长分别为A和B，那么里面的内容如下：
ffconcat version 1.0
file 1.mp4
duration A
file 2.mp4
duration B

**Comment by sunbinjin** [comment]
@Android4MediaPlayer 哦，明白了，以前没用过concat，刚好ffplay还有ffplay concat：1.mp4|2.mp4这种参数写法
我就以为是那个，没想到还有一种.ffconcat的写法
