### ISSUE TITLE
ff_ffmsg_queue.h中msg_queue_remove时死循环

### ISSUE THREAD

**Issue by zoudi1122** [Bilibili/ijkplayer#475]
```c
inline static void msg_queue_remove(MessageQueue *q, int what)
{
    AVMessage **p_msg, *msg, *last_msg = q->first_msg;
    SDL_LockMutex(q->mutex);

    if (!q->abort_request && q->first_msg) {
        p_msg = &q->first_msg;
        while (*p_msg) {
            msg = *p_msg;

            if (msg->what == what) {
                *p_msg = msg->next;
                p_msg = &msg->next;
#ifdef FFP_MERGE
                av_free(msg);
#else
                msg->next = q->recycle_msg;
                q->recycle_msg = msg;
#endif
            } else {
                last_msg = msg;
                p_msg = &msg->next;
            }
        }

        if (q->first_msg) {
            q->last_msg = last_msg;
        } else {
            q->last_msg = NULL;
        }
    }

    SDL_UnlockMutex(q->mutex);
}
```

这个函数的作用应该是把queue链中特定的消息移动到recycle链中吧？
但是逻辑好像跑不通的样子。
现在是在多次拖动进度条，也就是连续seek，有一定概率卡死。
在调试器里pause之后，发现主线程在msg_queue_remove里面死循环了。
链表里有两个FFP_REQ_SEEK消息，和另外一个消息（有时是SEEK_COMPLET有时是BUFFER_START等等）

**Comment by zoudi1122** [comment]
![f2710125-e53f-4b76-b7f3-1d7d68098642](https://cloud.githubusercontent.com/assets/13269687/9926953/b939f266-5d4c-11e5-9ad3-08094e2633c3.jpeg)

**Comment by zoudi1122** [comment]
```c
            if (msg->what == what) {
                *p_msg = msg->next;
                //p_msg = &msg->next;
#ifdef FFP_MERGE
                av_free(msg);
#else
                msg->next = q->recycle_msg;
                q->recycle_msg = msg;
#endif
            } else {
```

把p_msg = &msg->next;注释掉貌似就可以了
麻烦 @bbcallen 看看？我有没有理解错误

**Comment by LittleKey** [comment]
d493eeb1e61d9d5b221f0e0e2887408715db41b5

**Comment by bbcallen** [comment]
Try this blind fix: d493eeb1e61d9d5b221f0e0e2887408715db41b5

**Comment by zoudi1122** [comment]
使用了你这个fix不会出现卡死了，说明确实是竞争条件引起的。
但是对你这个函数的逻辑还是有疑问。
p_msg = &msg->next;
msg->next = q->recycle_msg;
这两句执行之后，相当于p_msg = q->recycle_msg;
那么之后的循环都走在recycle_msg这条链表上了。

**Comment by zoudi1122** [comment]
@bbcallen 
仍然有问题，还是会卡死，只是去掉竞争条件之后更难重现了而已。
我在循环里打个输出变量的断点，降低了执行效率，再去拖进度条，马上就重现了。在老机器上也比新机器上更容易出现。
麻烦你在仔细看一下这个函数吧。

**Comment by bbcallen** [comment]
Try this: a4957b95bee63ebb9372a121f4abc759c2213ec2

**Comment by sarahzuo** [comment]
@zoudi1122  请问卡死的时候是会出现什么样子？会使真机重启吗？还是app崩溃？还是卡在某一帧不动了？

**Comment by sarahzuo** [comment]
"Try this: a4957b9" 你用了这个版本之后问题解决了吗？

**Comment by Android4MediaPlayer** [comment]
@zoudi1122 现在是什么情况
