### ISSUE TITLE
安卓系统的ijkplayer，在seek的过程中，seek完后。画面会快速的跳动几帧画面。然后视频恢复正常

### ISSUE THREAD

**Issue by andyjmzheng** [Bilibili/ijkplayer#476]
安卓系统的ijkplayer，在seek的过程中，seek完后。画面会快速的跳动几帧画面。然后视频恢复正常。
我是一次seek 大概十分钟。seek完成后，画面会跳动几帧。跳动过程中类似快进的样子。

**Comment by andyjmzheng** [comment]
播放视频的地址如下:http://ssports.vod.smgbb.cn.cloudcdn.net/otv/vod/auto_bbf0913484a59baedb5d694236a45cc2.m3u8

**Comment by Android4MediaPlayer** [comment]
新英体育节目，这个是你的片源问题，要编码处理下

**Comment by andyjmzheng** [comment]
这个片源。我在vlc上测试。没有跳帧的问题呀？

**Comment by andyjmzheng** [comment]
需要片源在编码的时候如何处理？谢谢！

**Comment by Android4MediaPlayer** [comment]
VLC虽没有但是会有个等待时间的感觉的，你可以用系统播放器测试 发现可能画面都不会动了 是切片上时间戳方面检查下

**Comment by andyjmzheng** [comment]
好的。谢谢！

**Comment by andyjmzheng** [comment]
http://218.200.229.165:80/vod/video2/18/d54a67031d1a8ff31636e769fb66863d.m3u8 我用这个流测试了。没有跳帧的问题。那初步定位就是源的问题了。谢谢。
