### ISSUE TITLE
Ubuntu compile failed！

### ISSUE THREAD

**Issue by Balotelli-jy** [bilibili/ijkplayer#4767]
Description:I build the Ubuntu env to compile ijkplayer in my PC, compiled failed below:
/home/jiyi/code/ijkplayer/android/contrib/build/ffmpeg-armv7a/toolchain/bin//arm-linux-androideabi-gcc
arm-linux-androideabi-gcc is unable to create an executable file.
C compiler test failed.

my env:
ANDROID_NDK=/home/jiyi/code/ijkplayer/dev/android-ndk-r14b
ANDROID_HOME=/home/jiyi/code/ijkplayer/dev/android-sdk-linux

all of my tring:
1. use more ndk version like android-ndk-r10e, but no use;
2.chmod gcc Permission：chmod 777 /home/jiyi/code/ijkplayer/dev/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc, but no use;

Dose anyone solved problem like this? thank you.

**Comment by BruceLing** [comment]
reference：https://www.cnblogs.com/CentForever/p/7965920.html 
![image](https://user-images.githubusercontent.com/19875335/59564231-b93f8800-9076-11e9-8ee7-f3cbc975cdd4.png)

**Comment by Balotelli-jy** [comment]
> reference：https://www.cnblogs.com/CentForever/p/7965920.html
> ![image](https://user-images.githubusercontent.com/19875335/59564231-b93f8800-9076-11e9-8ee7-f3cbc975cdd4.png)

it's very nice of you!
