### ISSUE TITLE
播放M3U8时，报错

### ISSUE THREAD

**Issue by hwd920** [Bilibili/ijkplayer#477]
Android平台ijkplayer播放点播的M3U8时，报错，抓到的日志如下：
09-18 14:27:37.540: E/IJKMEDIA(29013): http://218.200.229.165:80/vod/video2/18/d54a67031d1a8ff31636e769fb66863d.m3u8
09-18 14:27:37.540: E/IJKMEDIA(29013): : End of file

vlc和Android的系统播放器播放这个地址是正常的，麻烦大侠看看，是什么问题呢？

**Comment by Android4MediaPlayer** [comment]
没有问题啊，是播放的一个43:28的视频，华数TV的log，片名为觉醒者

**Comment by hwd920** [comment]
嗯，感谢Android4MediaPlayer。我用demo测也是没有问题的，但是集成到自己的代码中去后，播放其它的M3U8是正常的，但是播放这个的时候就报错了。除了上面的错误信息，还有这个：
09-18 17:18:38.020: E/tv.danmaku.ijk.media.player.IjkMediaPlayer(25446): Error (-10000,0)
能解释下这个错误号代表什么意思么？

**Comment by hwd920** [comment]
找到问题了，是服务器返回数据的问题。服务器返回的实际地址是：
http://218.200.229.165:80/vod/video2/18/d54a67031d1a8ff31636e769fb66863d.m3u8\r\n，导致播放器播放不出来。谢谢！

**Comment by Android4MediaPlayer** [comment]
就是下载不到数据报错了，嗯，找到问题就好

**Comment by hwd920** [comment]
是的，正确的地址应该是http://218.200.229.165:80/vod/video2/18/d54a67031d1a8ff31636e769fb66863d.m3u8，服务器返回的是http://218.200.229.165:80/vod/video2/18/d54a67031d1a8ff31636e769fb66863d.m3u8\r\n，多了\r\n，服务器返回的地址是错的
