### ISSUE TITLE
升级ffmpeg到4.0

### ISSUE THREAD

**Issue by ddaajing** [bilibili/ijkplayer#4772]
尝试升级ffmpeg到4.0，所以修改了init-ios.sh里的：
IJK_FFMPEG_COMMIT=ff4.0--ijk0.8.25--20190618--001，然后编译ffmpeg，最后打开Xcode，编译IJKMediaPlayer项目时，报错

Undefined symbols for architecture x86_64:
  "_ff_ac3_parse_header", referenced from:
      _eac3_core_filter in libavcodec.a(eac3_core_bsf.o)
ld: symbol(s) not found for architecture x86_64

**Comment by BuildFaild** [comment]
我也遇到这个问题  请问是您解决了吗

**Comment by debugly** [comment]
需要修改 ffmpeg 编译配置：config/module-lite.sh

#export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-ffserver"
#export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-vda"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-bsf=eac3_core"

具体可参考：https://github.com/debugly/ijkplayer/blob/mac/config/module-lite.sh

**Comment by debugly** [comment]
> 我也遇到这个问题 请问是您解决了吗

需要修改 ffmpeg 编译配置：config/module-lite.sh

#export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-ffserver"
#export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-vda"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-bsf=eac3_core"

具体可参考：https://github.com/debugly/ijkplayer/blob/mac/config/module-lite.sh

**Comment by huyubao** [comment]
你编译成功了么？成功了能否把4.x版本的发给我一下

**Comment by ddaajing** [comment]
编译ffmpeg4不过时，正如debugly 所说，需要注释掉2行-disable-ffserver和--disable-vda，然后添加一行把eac3_cored配置disable掉--disable-bsf=eac3_core，然后clean掉，重新编译ffmpeg就好了

**Comment by BuildFaild** [comment]
> > 我也遇到这个问题 请问是您解决了吗
> 
> 需要修改 ffmpeg 编译配置：config/module-lite.sh
> 
> #export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-ffserver"
> #export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-vda"
> export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-bsf=eac3_core"
> 
> 具体可参考：https://github.com/debugly/ijkplayer/blob/mac/config/module-lite.sh

THX

**Comment by BuildFaild** [comment]
> 编译ffmpeg4不过时，正如debugly 所说，需要注释掉2行-disable-ffserver和--disable-vda，然后添加一行把eac3_cored配置disable掉--disable-bsf=eac3_core，然后clean掉，重新编译ffmpeg就好了

THX
