### ISSUE TITLE
升级ffmpeg ,编译android平台出的问题

### ISSUE THREAD

**Issue by KinaZhen** [bilibili/ijkplayer#4778]
报错 ：libavcodec/eac3_core_bsf.c:39: error: undefined reference to 'ff_ac3_parse_header'

init.android.sh  修改成   IJK_FFMPEG_COMMIT=ff4.0--ijk0.8.25--20190618--001
config/module-lite.sh  里面对应也做了修改

**Comment by wnpllrzodiac** [comment]
裁剪估计有问题吧。
4.x更新太多了。自己查下吧。

**Comment by KinaZhen** [comment]
只编译armv7a是可以正常编译-_-

**Comment by dueeeke** [comment]
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-bsf=eac3_core"

**Comment by ProFive** [comment]
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-bsf=eac3_core"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-parser=ac3"

**Comment by Equalzys** [comment]
> export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-bsf=eac3_core" export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-parser=ac3"

hello，All this has been done, but it has no effect；
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/17246251/157363122-e3579153-ea6c-42b5-b6ef-8f9542fe76d9.png">
