### ISSUE TITLE
修改ffmpeg源码的问题

### ISSUE THREAD

**Issue by ilsquare** [bilibili/ijkplayer#4779]
我在项目里修改extra里面的ffmpeg源码的之后,重新./init-ios.sh,编译出来的ffmpeg没有我加入的代码,请问如何才能修改ffmpeg之后生效

**Comment by befovy** [comment]
init 脚本会把ffmpeg checkout 到指定的git提交，你需要修改脚本

**Comment by xccwxc** [comment]
ios/ffmpeg--xxxx 在这个目录下改

**Comment by wnpllrzodiac** [comment]
comment out git checkout  ffmpeg branch的部分。
改ffmpeg比较麻烦，需要熟悉编译脚本

**Comment by Balotelli-jy** [comment]
ios没有编译过，安卓的版本是修改对应架构下面的FFmpeg代码就可以生效了，比如芯片平台是arm64版本，需要修改的对应FFmpeg源码为android\contrib\ffmpeg-arm64\下面的，iOS的可能也是这样，可以看下，但我认为应该不是修改extra下面的FFmpeg。
