### ISSUE TITLE
mediaplayer 重复调用setSurface会报 ANativeWindow_lock: failed -22

### ISSUE THREAD

**Issue by leown** [Bilibili/ijkplayer#478]
我的需求是 多个mediaplayer 切换播放视频，当第一个视频播放完毕后 setDisplay(null),然后调用setSurface,音频会继续播放，视频就停住了，我理解是并没有切换播放容器，我的播放容器是TextureView，或者有没有方案可以让surfaceView 放在listview中，滑动不黑屏的方法呢？不能设置为setZOrderOnTop 遮挡其他ui。 望回复，谢谢。

**Comment by bbcallen** [comment]
Try this: #426
I don't know if it works for you.
