### ISSUE TITLE
Ijkplayer 播放 dts 音频无声音 

### ISSUE THREAD

**Issue by mengziyu** [bilibili/ijkplayer#4782]
I/IJKMEDIA(19568): : Audio: dts, 48000 Hz, 6 channels
请问要做什么配置才能支持

**Comment by befovy** [comment]
6 chsnnels 音频，aout open 能成功吗？ 看看日志

**Comment by mengziyu** [comment]
添加配置重编就可以了
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=dca"
