### ISSUE TITLE
iOS - 点播编码为H265 1080p 60fps 画质帧率的视频怎么设置options 呢？

### ISSUE THREAD

**Issue by Sanchain** [bilibili/ijkplayer#4784]
请不吝赐教：
下面是我的option设置，但没有效果：
        [options setPlayerOptionIntValue:1 forKey:@"videotoolbox"]; // 硬解1 软解0
        [options setPlayerOptionIntValue:60 forKey:@"max-fps"]; // 丢弃fps大于max-fps的视频中的帧
        [options setPlayerOptionIntValue:10 forKey:@"framedrop"];
        [options setFormatOptionIntValue:1 forKey:@"dns_cache_clear"];
        [options setPlayerOptionIntValue:60 forKey:@"r"]; // 帧速率

上述设置的效果是音视频不同步，1分钟的视频只播了25秒，且画面播放速度加快，音频正常播放。
PS: H264 1080p 60fps 的视频能正常播放，且音视频同步；

请问是不是我忽略了哪个设置导致的呢？？ 合理解决方法可有偿回答，谢谢！！！！

**Comment by befovy** [comment]
@Sanchain  你可以提供一下日志，或者你的测试视频 url

**Comment by Sanchain** [comment]
> @Sanchain 你可以提供一下日志，或者你的测试视频 url

好的，这个是视频的下载地址，可以直接下载的；
https://wetransfer.com/downloads/844324945919318581bc0946ed2fea9b20190711052731/41c76af69c208372b9ead4f7a2ca335320190711052731/b1c84c

调试的日志：
[10:19:25:114000][BaseLocalAlbumVideoView.m 220] {播放的文件的名称: 2019_07_12_140240_00.MP4, uniquePath:/var/mobile/Containers/Data/Application/9DF41738-9F80-4EAE-A53B-1FD6BE5EAF79/Library/Caches/localVidio/2019_07_12_140240_00.MP4, filepPath:/var/mobile/Containers/Data/Application/9DF41738-9F80-4EAE-A53B-1FD6BE5EAF79/Library/Caches/localVidio, fileName:(null)}
ijkmp_set_inject_opaque(0x2817c3500)
ijkmp_set_inject_opaque()=void
ijkmp_set_ijkio_inject_opaque(0x2817c3500)
ijkmp_set_ijkio_inject_opaque()=void
2019-07-13 10:19:25.681735+0800 LinkDashCam[14259:4036203] OK setup GL
ijkmp_ios_set_view(glView=0x11ded58d0)
ijkmp_ios_set_view(glView=0x11ded58d0)=void
2019-07-13 10:19:25.685141+0800 LinkDashCam[14259:4036203] invalidateRenderBuffer
2019-07-13 10:19:25.685288+0800 LinkDashCam[14259:4036311] IJKSDLGLView: setupDisplay not ready
ijkmp_set_data_source(url="/var/containers/Bundle/Application/202DFE42-6E4C-412D-B62F-EA54195E7F9D/LinkDashCam.app/2019_07_09_215510_00.MP4")
ijkmp_set_data_source(url="/var/containers/Bundle/Application/202DFE42-6E4C-412D-B62F-EA54195E7F9D/LinkDashCam.app/2019_07_09_215510_00.MP4")=0
ijkmp_prepare_async()
ijkmp_prepare_async()=0
2019-07-13 10:19:25.700529+0800 LinkDashCam[14259:4036203] invalidateRenderBuffer
2019-07-13 10:19:25.700695+0800 LinkDashCam[14259:4036311] IJKSDLGLView: setupDisplay not ready
2019-07-13 10:19:25.713910+0800 LinkDashCam[14259:4036203] FFP_MSG_OPEN_INPUT:
2019-07-13 10:19:25.732861+0800 LinkDashCam[14259:4036203] FFP_MSG_FIND_STREAM_INFO:
aout_open_audio()
aout_pause_audio(0)
2019-07-13 10:19:25.856261+0800 LinkDashCam[14259:4036203] FFP_MSG_AUDIO_RENDERING_START:
2019-07-13 10:19:25.857282+0800 LinkDashCam[14259:4036203] FFP_MSG_VIDEO_DECODER_OPEN: false
2019-07-13 10:19:25.857764+0800 LinkDashCam[14259:4036203] FFP_MSG_COMPONENT_OPEN:
2019-07-13 10:19:25.857997+0800 LinkDashCam[14259:4036203] FFP_MSG_VIDEO_SIZE_CHANGED: 960, 540
2019-07-13 10:19:25.858081+0800 LinkDashCam[14259:4036203] FFP_MSG_SAR_CHANGED: 0, 1
ijkmp_get_msg: FFP_MSG_PREPARED
2019-07-13 10:19:25.858230+0800 LinkDashCam[14259:4036203] FFP_MSG_PREPARED:
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
2019-07-13 10:19:25.858342+0800 LinkDashCam[14259:4036203] fps in meta 60.000000
ijkmp_set_playback_rate(1.000000)
ijkmp_set_playback_rate()=void
ijkmp_set_playback_volume(1.000000)
ijkmp_set_playback_volume()=void
[10:19:25:858000][LDIJKPlayerView.m 519] {mediaIsPreparedToPlayDidChange
}
[10:19:25:859000][LDIJKPlayerView.m 455] {监听缓冲的方法 loadStateDidChange}
[10:19:25:859000][LDIJKPlayerView.m 459] {loadStateDidChange: IJKMPMovieLoadStatePlaythroughOK: 3
}
[10:19:25:860000][LDIJKPlayerView.m 546] {IJKMPMoviePlayBackStateDidChange 1: playing}
[10:19:25:862000][LDIJKPlayerView.m 865] {----当前的播放进度：0.000000s / 25.000000s, playableDuration:0.000000}
aout_pause_audio(1)
SDL_VoutFFmpeg_CreateOverlay(w=960, h=540, fmt=I420(0x30323449, dp=0x28003b7c0)
Video: first frame decoded
SDL_VoutFFmpeg_CreateOverlay(w=960, h=540, fmt=I420(0x30323449, dp=0x28003b7c0)
2019-07-13 10:19:25.872121+0800 LinkDashCam[14259:4036203] FFP_MSG_VIDEO_SIZE_CHANGED: 960, 540
2019-07-13 10:19:25.873645+0800 LinkDashCam[14259:4036203] FFP_MSG_VIDEO_DECODED_START:
2019-07-13 10:19:25.873715+0800 LinkDashCam[14259:4036203] FFP_MSG_VIDEO_SIZE_CHANGED: 960, 540
SDL_VoutFFmpeg_CreateOverlay(w=960, h=540, fmt=I420(0x30323449, dp=0x28003b7c0)
2019-07-13 10:19:25.877333+0800 LinkDashCam[14259:4036203] FFP_MSG_VIDEO_SIZE_CHANGED: 960, 540
2019-07-13 10:19:25.899801+0800 LinkDashCam[14259:4036203] FFP_MSG_BUFFERING_START:
[10:19:25:900000][LDIJKPlayerView.m 455] {监听缓冲的方法 loadStateDidChange}
[10:19:25:900000][LDIJKPlayerView.m 468] {loadStateDidChange: IJKMPMovieLoadStateStalled: 4
}
aout_pause_audio(0)
aout_close_audio()
aout_set_volume()
2019-07-13 10:19:25.940466+0800 LinkDashCam[14259:4036203] FFP_MSG_BUFFERING_END:
[GLES2] Version = OpenGL ES 2.0 Metal - 58.4
[GLES2] Vendor = Apple Inc.
[GLES2] Renderer = Apple A9 GPU
[GLES2] Extensions = GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_vertex_array_object GL_EXT_blend_minmax GL_EXT_color_buffer_half_float GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_draw_instanced GL_EXT_instanced_arrays GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_pvrtc_sRGB GL_EXT_read_format_bgra GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_texture_lod GL_EXT_shadow_samplers GL_EXT_sRGB GL_EXT_texture_filter_anisotropic GL_EXT_texture_rg GL_EXT_texture_storage GL_APPLE_clip_distance GL_APPLE_color_[10:19:25:941000][LDIJKPlayerView.m 455] {监听缓冲的方法 loadStateDidChange}
[10:19:25:941000][LDIJKPlayerView.m 459] {loadStateDidChange: IJKMPMovieLoadStatePlaythroughOK: 3
}
[10:19:25:941000][LDIJKPlayerView.m 546] {IJKMPMoviePlayBackStateDidChange 1: playing}
[10:19:25:942000][LDIJKPlayerView.m 865] {----当前的播放进度：0.000000s / 25.000000s, playableDuration:2.583000}
buffer_packed_float GL_APPLE_copy_texture_levels GL_APPLE_framebuffer_multisample GL_APPLE_rgb_422 GL_APPLE_sync GL_APPLE_texture_format_BGRA8888 GL_APPLE_texture_max_level GL_APPLE_texture_packed_float GL_IMG_read_format GL_IMG_texture_compression_pvrtc 
create render yuv420p
use render yuv420p
2019-07-13 10:19:25.944296+0800 LinkDashCam[14259:4036741] IJKSDLGLView: renderbufferStorage fromDrawable
IJK_GLES2_Renderer_TexCoords_cropRight
2019-07-13 10:19:25.949377+0800 LinkDashCam[14259:4036203] FFP_MSG_VIDEO_RENDERING_START:
avcodec/Audio: first frame decoded
2019-07-13 10:19:26.026022+0800 LinkDashCam[14259:4036203] FFP_MSG_AUDIO_DECODED_START:
[10:19:26:944000][LDIJKPlayerView.m 865] {----当前的播放进度：0.746000s / 25.000000s, playableDuration:24.740000}

请大神帮帮忙，谢谢你！！！

**Comment by befovy** [comment]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/51129600/61166577-821fa200-a562-11e9-848c-7a65d6d12a14.png">


你这个文件有两个 video track。 其中一个本身播放就慢。

```
  Duration: 00:00:25.00, start: 0.000000, bitrate: 26843 kb/s
    Stream #0:0(eng): Data: bin_data (gpmd / 0x646D7067), 2 kb/s (default)
    Metadata:
      creation_time   : 2019-07-09T21:55:10.000000Z
      handler_name    : ?gps
    Stream #0:1(eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 1920x1080, 8492 kb/s, 60 fps, 60 tbr, 120k tbn, 120k tbc (default)
    Metadata:
      creation_time   : 2019-07-09T21:55:10.000000Z
      handler_name    : ?Hisilicon VIDEO
    Stream #0:2(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      creation_time   : 2019-07-09T21:55:10.000000Z
      handler_name    : ?Hisilicon AUDIO
    Stream #0:3(eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709), 960x540, 1369 kb/s, 60 fps, 60 tbr, 120k tbn, 240k tbc (default)
    Metadata:
      creation_time   : 2019-07-09T21:55:10.000000Z
      handler_name    : ?Hisilicon VIDEO
```

**Comment by Sanchain** [comment]
> <img alt="image" width="456" src="https://user-images.githubusercontent.com/51129600/61166577-821fa200-a562-11e9-848c-7a65d6d12a14.png">
> 
> 你这个文件有两个 video track。 其中一个本身播放就慢。
> 
> ```
>   Duration: 00:00:25.00, start: 0.000000, bitrate: 26843 kb/s
>     Stream #0:0(eng): Data: bin_data (gpmd / 0x646D7067), 2 kb/s (default)
>     Metadata:
>       creation_time   : 2019-07-09T21:55:10.000000Z
>       handler_name    : ?gps
>     Stream #0:1(eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 1920x1080, 8492 kb/s, 60 fps, 60 tbr, 120k tbn, 120k tbc (default)
>     Metadata:
>       creation_time   : 2019-07-09T21:55:10.000000Z
>       handler_name    : ?Hisilicon VIDEO
>     Stream #0:2(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 125 kb/s (default)
>     Metadata:
>       creation_time   : 2019-07-09T21:55:10.000000Z
>       handler_name    : ?Hisilicon AUDIO
>     Stream #0:3(eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709), 960x540, 1369 kb/s, 60 fps, 60 tbr, 120k tbn, 240k tbc (default)
>     Metadata:
>       creation_time   : 2019-07-09T21:55:10.000000Z
>       handler_name    : ?Hisilicon VIDEO
> ```

是的，我刚用VLC验证了Track1 是正常播放的，Track2的播放效果就是我现在遇到的；我需要做什么设置让其播放Track1的呢？

**Comment by baishuai** [comment]
Stream #0:1(eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 1920x1080, 8492 kb/s, 60 fps, 60 tbr, 120k tbn, 120k tbc (default)

    Stream #0:3(eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709), 960x540, 1369 kb/s, 60 fps, 60 tbr, 120k tbn, 240k tbc (default)

这两个 track 最明显的区别就是 codec 不一样。
我看了下目前好像没有什么接口能够在启动播放器时设置选择 track。

你可以修改源代码，重新编译。
```
    int video_stream_count = 0;
    int h264_stream_count = 0;
    int first_h264_stream = -1;
    for (i = 0; i < ic->nb_streams; i++) {
        AVStream *st = ic->streams[i];
        enum AVMediaType type = st->codecpar->codec_type;
        st->discard = AVDISCARD_ALL;
        if (type >= 0 && ffp->wanted_stream_spec[type] && st_index[type] == -1)
            if (avformat_match_stream_specifier(ic, st, ffp->wanted_stream_spec[type]) > 0)
                st_index[type] = i;

        // choose first h264

        if (type == AVMEDIA_TYPE_VIDEO) {
            enum AVCodecID codec_id = st->codecpar->codec_id;
            video_stream_count++;
            if (codec_id == AV_CODEC_ID_H264) {
                h264_stream_count++;
                if (first_h264_stream < 0)
                    first_h264_stream = i;
            }
        }
    }
```

或者更直接的修改 
```
    if (!ffp->video_disable)
        st_index[AVMEDIA_TYPE_VIDEO] =
            av_find_best_stream(ic, AVMEDIA_TYPE_VIDEO,
                                st_index[AVMEDIA_TYPE_VIDEO], -1, NULL, 0);
```

**Comment by befovy** [comment]
@Sanchain 

    Stream #0:1(eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 1920x1080, 8492 kb/s, 60 fps, 60 tbr, 120k tbn, 120k tbc (default)

    Stream #0:3(eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709), 960x540, 1369 kb/s, 60 fps, 60 tbr, 120k tbn, 240k tbc (default)

这两个 track 最明显的区别就是 codec 不一样。
我看了下目前好像没有什么接口能够在启动播放器时设置选择 track。

你可以修改源代码，重新编译。
```
    int video_stream_count = 0;
    int h264_stream_count = 0;
    int first_h264_stream = -1;
    for (i = 0; i < ic->nb_streams; i++) {
        AVStream *st = ic->streams[i];
        enum AVMediaType type = st->codecpar->codec_type;
        st->discard = AVDISCARD_ALL;
        if (type >= 0 && ffp->wanted_stream_spec[type] && st_index[type] == -1)
            if (avformat_match_stream_specifier(ic, st, ffp->wanted_stream_spec[type]) > 0)
                st_index[type] = i;

        // choose first h264

        if (type == AVMEDIA_TYPE_VIDEO) {
            enum AVCodecID codec_id = st->codecpar->codec_id;
            video_stream_count++;
            if (codec_id == AV_CODEC_ID_H264) {
                h264_stream_count++;
                if (first_h264_stream < 0)
                    first_h264_stream = i;
            }
        }
    }
```

或者更直接的修改 
```
    if (!ffp->video_disable)
        st_index[AVMEDIA_TYPE_VIDEO] =
            av_find_best_stream(ic, AVMEDIA_TYPE_VIDEO,
                                st_index[AVMEDIA_TYPE_VIDEO], -1, NULL, 0);
```

**Comment by Sanchain** [comment]
> @Sanchain
> 
> ```
> Stream #0:1(eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 1920x1080, 8492 kb/s, 60 fps, 60 tbr, 120k tbn, 120k tbc (default)
> 
> Stream #0:3(eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709), 960x540, 1369 kb/s, 60 fps, 60 tbr, 120k tbn, 240k tbc (default)
> ```
> 
> 这两个 track 最明显的区别就是 codec 不一样。
> 我看了下目前好像没有什么接口能够在启动播放器时设置选择 track。
> 
> 你可以修改源代码，重新编译。
> 
> ```
>     int video_stream_count = 0;
>     int h264_stream_count = 0;
>     int first_h264_stream = -1;
>     for (i = 0; i < ic->nb_streams; i++) {
>         AVStream *st = ic->streams[i];
>         enum AVMediaType type = st->codecpar->codec_type;
>         st->discard = AVDISCARD_ALL;
>         if (type >= 0 && ffp->wanted_stream_spec[type] && st_index[type] == -1)
>             if (avformat_match_stream_specifier(ic, st, ffp->wanted_stream_spec[type]) > 0)
>                 st_index[type] = i;
> 
>         // choose first h264
> 
>         if (type == AVMEDIA_TYPE_VIDEO) {
>             enum AVCodecID codec_id = st->codecpar->codec_id;
>             video_stream_count++;
>             if (codec_id == AV_CODEC_ID_H264) {
>                 h264_stream_count++;
>                 if (first_h264_stream < 0)
>                     first_h264_stream = i;
>             }
>         }
>     }
> ```
> 
> 或者更直接的修改
> 
> ```
>     if (!ffp->video_disable)
>         st_index[AVMEDIA_TYPE_VIDEO] =
>             av_find_best_stream(ic, AVMEDIA_TYPE_VIDEO,
>                                 st_index[AVMEDIA_TYPE_VIDEO], -1, NULL, 0);
> ```

我在ff_ffplay.c 找到了上面的代码，但不清楚怎么修改；
有发现这一段：
    if (video_stream_count > 1 && st_index[AVMEDIA_TYPE_VIDEO] < 0) {
        st_index[AVMEDIA_TYPE_VIDEO] = first_h264_stream;
        av_log(NULL, AV_LOG_WARNING, "multiple video stream found, prefer first h264 stream: %d\n", first_h264_stream);
    }
这是优先播放H264的流？

**Comment by Sanchain** [comment]
> @Sanchain 你可以提供一下日志，或者你的测试视频 url

同事已解决，原因是视频编码时写入的帧率写错了，跟ijkplayer没有关系，是视频文件本身的问题；感谢您的帮助；

**Comment by befovy** [comment]
@Sanchain 我基于 ijkplayer 在开发一个 flutter 播放器插件，可以了解一下。

https://github.com/befovy/ijkplayer

https://github.com/befovy/fijkplayer


另外此问题解决了，请把此 issue 关闭吧


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by Sanchain** [comment]
> @Sanchain 我基于 ijkplayer 在开发一个 flutter 播放器插件，可以了解一下。
> 
> https://github.com/befovy/ijkplayer
> 
> https://github.com/befovy/fijkplayer
> 
> 另外此问题解决了，请把此 issue 关闭吧
> 
> :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

好的，flutter还没怎么看，先mark.
