### ISSUE TITLE
iOS中，通过rtsp协议输出相机的实时流，1080p的分辨率，软解码不清晰，硬解码报错BadDataErr

### ISSUE THREAD

**Issue by Kestre1** [Bilibili/ijkplayer#479]
请问数据是不正确，这个问题怎么解决

**Comment by Kestre1** [comment]
请问数据是不正确，这个问题怎么解决

**Comment by Android4MediaPlayer** [comment]
正确的sps,pps数据

**Comment by Kestre1** [comment]
怎么才是正确的，这个通过代码有办法解决么

**Comment by Kestre1** [comment]
这是我的sps/pps:00 00 00 01 00 00 00 01 67 64 00 28 AC 4D 80 F0 08 8F B4 00 00 00 01 68 EA 8E 2C

**Comment by lslxdx** [comment]
是不是没有设置fame max width:
ijkmp_ios_set_frame_max_width(_mediaPlayer, 1920);

**Comment by Kestre1** [comment]
没有你说的ijkmp_ios_set_frame_max_width这个方法啊

**Comment by YangYuZhe** [comment]
hi, I'm also faced with this issue,when I played tsp 1080P stream,it just black screen,have you solved it?
