### ISSUE TITLE
对于视频的方向不会跟随视频的拍摄来？是否需要配置？

### ISSUE THREAD

**Issue by fuminwen** [Bilibili/ijkplayer#480]
用手机拍摄一个竖屏的视频，在系统自带的播放器上播放，位置正常。但是在ijkplayer上播放，是变成横向的了；必现场景，是否有什么方法可以调整？

**Comment by bbcallen** [comment]
Use TextureView, see sample.

**Comment by BlueTopsky** [comment]
iOS里面没有TextureView，请问怎么解决这一问题啊，播放竖着拍摄的视频就会自动旋转了90度，播放横着拍摄的视频时是正常的

**Comment by Echo-Joker** [comment]
iOS里面没有TextureView，请问怎么解决这一问题啊，播放竖着拍摄的视频就会自动旋转了90度，播放横着拍摄的视频时是正常的

**Comment by zhuqingyuan** [comment]
TextureView切换视频比较慢是咋回事

**Comment by hanl001** [comment]
@fuminwen 这个问题最后怎么解决的呀
