### ISSUE TITLE
缩放模式是否支持类似Android ImageView centCrop

### ISSUE THREAD

**Issue by liouvilles** [bilibili/ijkplayer#4805]

**Comment by befovy** [comment]
AR_ASPECT_FILL_PARENT 应该满足你的需求

**Comment by liouvilles** [comment]
> AR_ASPECT_FILL_PARENT 应该满足你的需求

这个感觉类似于fitxy,拉伸了视频,没有剪裁

**Comment by befovy** [comment]
感觉？ 你没有自己试一下吗


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by liouvilles** [comment]
> 你没有自己试一下吗？ @liouvilles
> 
> AR_ASPECT_FILL_PARENT 和 AR_ASPECT_FIT_PARENT 都是保持原画面比例。
> 
> AR_ASPECT_FIT_PARENT 是保持比例扩大视频画面，
> 直至宽或高的某一个率先与View 的宽或高相等。
> 
> AR_ASPECT_FILL_PARENT 是保持比例扩大视频画面，在宽或高已经与view 的宽或高相等之后，继续扩大，直到另一边也与view 的大小相等。

**Comment by liouvilles** [comment]
用ijkplayer的example代码验证是对的,可能是因为我用的是一个封装了ijkplayer的开源项目,一直没有试出想要的效果.
多谢!

**Comment by befovy** [comment]
@liouvilles 你是不是忘了关掉这个issue了
