### ISSUE TITLE
cannot play hls after playing rtsp stream

### ISSUE THREAD

**Issue by andpark** [bilibili/ijkplayer#4810]
I've built ios framework with rtsp support

It plays hls and rtsp.
It plays rtsp after playing hls but It cannot play hls after playing rtsp.

If I don't play rtsp, It can play hls again and again. but when I play rtsp stream. It no longer plays hls until I restart the application.

I did some more investigation and I found this.
It fails to open input on "avformat_open_input" with error code "-1094995529".

for more information.
"avformat_open_input" does not open segment file url(ts file) after playing rtsp stream.
mp4 files something like "http://techslides.com/demos/sample-videos/small.mp4" opened normally.
(it opens and plays ts segment file before opening rtsp stream)

**Comment by befovy** [comment]
Which api did you call to play another stream after previous one?

**Comment by andpark** [comment]
first time playing m3u8 file.

> 2019-08-01 15:21:41.462746+0900 Runner[1915:436222] flutter: playing: http://xxx.xxx.xxx.xxx:xxxxx/V100/VMS_49101/summary_playlist?s=4xl04D9Z7yZXGJaM71TedScxh%2BddANW%2BSLQlFYvA4BOqfDwoG8iklp9QzTBzoHg5bYD5tD8QH6joMa%2Fq%2ByrIf16FLitNexN41u%2FsOGEpxx5v6an0OKVaZwas%2FmdtGQ6Ka5djvmDAZ7pnsvgUQNpCL6lyY1dBwBaTblvBifVZDbU%3D&t=96ada279.m3u8
> 2019-08-01 15:21:41.479508+0900 Runner[1915:436222] flutter: options = [IjkOption{category: IjkOptionCategory.format, key: fflags, value: fastseek}, IjkOption{category: IjkOptionCategory.codec, key: skip_loop_filter, value: 0}, IjkOption{category: IjkOptionCategory.codec, key: skip_frame, value: 0}, IjkOption{category: IjkOptionCategory.format, key: probesize, value: 5000000}, IjkOption{category: IjkOptionCategory.player, key: start-on-prepared, value: 1}, IjkOption{category: IjkOptionCategory.format, key: timeout, value: 10000}]
> 2019-08-01 15:21:41.524515+0900 Runner[1915:436168] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:41.524621+0900 Runner[1915:436168] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:41.551787+0900 Runner[1915:436217] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:41.552016+0900 Runner[1915:436217] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:41.552063+0900 Runner[1915:436217] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:41.552103+0900 Runner[1915:436217] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:41.552143+0900 Runner[1915:436217] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:41.552186+0900 Runner[1915:436217] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:41.552225+0900 Runner[1915:436217] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:41.565002+0900 Runner[1915:436217] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:41.565188+0900 Runner[1915:436217] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:41.565236+0900 Runner[1915:436217] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:41.565303+0900 Runner[1915:436217] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:41.565385+0900 Runner[1915:436217] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:41.565424+0900 Runner[1915:436217] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:41.565522+0900 Runner[1915:436217] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> ijkmediaplayer version : 347bdef4===== custom modules begin =====
> register demuxer : ijklivehook
> ===== custom modules end =====
> av_version_info: ff3.4--ijk0.8.7--20180103--001
> ijk_version_info: 347bdef4
> ijkmp_set_inject_opaque(0x2802d85e0)
> ijkmp_set_inject_opaque()=void
> ijkmp_set_ijkio_inject_opaque(0x2802d85e0)
> ijkmp_set_ijkio_inject_opaque()=void
> 2019-08-01 15:21:41.633581+0900 Runner[1915:436217] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:41.636049+0900 Runner[1915:436168] OK setup GL
> ijkmp_ios_set_view(glView=0x15fe06780)
> ijkmp_ios_set_view(glView=0x15fe06780)=void
> ijkmp_set_data_source(url="http://xxx.xxx.xxx.xxx:xxxxx/V100/VMS_49101/summary_playlist?s=4xl04D9Z7yZXGJaM71TedScxh%2BddANW%2BSLQlFYvA4BOqfDwoG8iklp9QzTBzoHg5bYD5tD8QH6joMa%2Fq%2ByrIf16FLitNexN41u%2FsOGEpxx5v6an0OKVaZwas%2FmdtGQ6Ka5djvmDAZ7pnsvgUQNpCL6lyY1dBwBaTblvBifVZDbU%3D&t=96ada279.m3u8")
> ijkmp_set_data_source(url="http://xxx.xxx.xxx.xxx:xxxxx/V100/VMS_49101/summary_playlist?s=4xl04D9Z7yZXGJaM71TedScxh%2BddANW%2BSLQlFYvA4BOqfDwoG8iklp9QzTBzoHg5bYD5tD8QH6joMa%2Fq%2ByrIf16FLitNexN41u%2FsOGEpxx5v6an0OKVaZwas%2FmdtGQ6Ka5djvmDAZ7pnsvgUQNpCL6lyY1dBwBaTblvBifVZDbU%3D&t=96ada279.m3u8")=0
> ijkmp_prepare_async()
> ijkmp_prepare_async()=0
> no reset timeout
> cur abort_request: 0
> opening input: http://xxx.xxx.xxx.xxx:xxxxx/V100/VMS_49101/summary_playlist?s=4xl04D9Z7yZXGJaM71TedScxh%2BddANW%2BSLQlFYvA4BOqfDwoG8iklp9QzTBzoHg5bYD5tD8QH6joMa%2Fq%2ByrIf16FLitNexN41u%2FsOGEpxx5v6an0OKVaZwas%2FmdtGQ6Ka5djvmDAZ7pnsvgUQNpCL6lyY1dBwBaTblvBifVZDbU%3D&t=96ada279.m3u8
> 2019-08-01 15:21:41.745510+0900 Runner[1915:436168] FFP_MSG_OPEN_INPUT:
> 2019-08-01 15:21:41.922699+0900 Runner[1915:436168] FFP_MSG_FIND_STREAM_INFO:
> 2019-08-01 15:21:41.923065+0900 Runner[1915:436168] FFP_MSG_VIDEO_DECODER_OPEN: false
> 2019-08-01 15:21:41.923169+0900 Runner[1915:436168] FFP_MSG_VIDEO_ROTATION_CHANGED:
> 2019-08-01 15:21:41.923186+0900 Runner[1915:436168] rotate arg1 = 0
> ijkmp_get_msg: FFP_MSG_PREPARED
> 2019-08-01 15:21:41.923505+0900 Runner[1915:436168] FFP_MSG_COMPONENT_OPEN:
> aout_pause_audio(1)
> 2019-08-01 15:21:41.923528+0900 Runner[1915:436168] FFP_MSG_VIDEO_SIZE_CHANGED: 1920, 1080
> 2019-08-01 15:21:41.923556+0900 Runner[1915:436168] FFP_MSG_SAR_CHANGED: 1, 1
> 2019-08-01 15:21:41.923571+0900 Runner[1915:436168] FFP_MSG_PREPARED:
> ijkmp_get_meta_l
> ijkmp_get_meta_l()=void
> ijkmp_set_playback_rate(1.000000)
> ijkmp_set_playback_rate()=void
> ijkmp_set_playback_volume(1.000000)
> ijkmp_set_playback_volume()=void
> 2019-08-01 15:21:41.923684+0900 Runner[1915:436168] load state change, state = 3
> 2019-08-01 15:21:41.923812+0900 Runner[1915:436168] FFP_MSG_BUFFERING_START:
> 2019-08-01 15:21:41.923830+0900 Runner[1915:436168] load state change, state = 4
> aout_pause_audio(0)
> 2019-08-01 15:21:41.985418+0900 Runner[1915:436168] FFP_MSG_BUFFERING_END:
> 2019-08-01 15:21:41.985469+0900 Runner[1915:436168] load state change, state = 3
> SDL_VoutFFmpeg_CreateOverlay(w=1920, h=1080, fmt=I420(0x30323449, dp=0x2815adb40)
> Video: first frame decoded
> 2019-08-01 15:21:42.003555+0900 Runner[1915:436168] FFP_MSG_VIDEO_SIZE_CHANGED: 1920, 1080
> 2019-08-01 15:21:42.003613+0900 Runner[1915:436168] FFP_MSG_VIDEO_DECODED_START:
> SDL_VoutFFmpeg_CreateOverlay(w=1920, h=1080, fmt=I420(0x30323449, dp=0x2815adb40)
> SDL_VoutFFmpeg_CreateOverlay(w=1920, h=1080, fmt=I420(0x30323449, dp=0x2815adb40)
> 2019-08-01 15:21:42.009669+0900 Runner[1915:436168] FFP_MSG_VIDEO_SIZE_CHANGED: 1920, 1080
> 2019-08-01 15:21:42.014613+0900 Runner[1915:436168] FFP_MSG_VIDEO_SIZE_CHANGED: 1920, 1080
> 2019-08-01 15:21:42.023196+0900 Runner[1915:436168] FFP_MSG_VIDEO_RENDERING_START:
> 2019-08-01 15:21:42.069857+0900 Runner[1915:436222] flutter: vod progress : 0.045 / 7.669
> 2019-08-01 15:21:42.147930+0900 Runner[1915:436222] flutter: vod progress : 0.122 / 7.669
> 2019-08-01 15:21:42.157655+0900 Runner[1915:436232] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:42.157773+0900 Runner[1915:436232] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:42.157936+0900 Runner[1915:436232] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:42.157966+0900 Runner[1915:436232] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:42.158296+0900 Runner[1915:436232] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:42.158375+0900 Runner[1915:436232] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:42.158497+0900 Runner[1915:436168] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:42.158624+0900 Runner[1915:436232] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:42.158794+0900 Runner[1915:436168] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:42.247907+0900 Runner[1915:436222] flutter: vod progress : 0.222 / 7.669
> 2019-08-01 15:21:42.266733+0900 Runner[1915:436234] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:21:42.347597+0900 Runner[1915:436222] flutter: vod progress : 0.323 / 7.669
> 2019-08-01 15:21:42.490898+0900 Runner[1915:436222] flutter: vod progress : 0.465 / 7.669
> 2019-08-01 15:21:42.547886+0900 Runner[1915:436222] flutter: vod progress : 0.523 / 7.669
> 2019-08-01 15:21:42.694470+0900 Runner[1915:436222] flutter: vod progress : 0.668 / 7.669
> 2019-08-01 15:21:42.746460+0900 Runner[1915:436222] flutter: vod progress : 0.721 / 7.669
> 2019-08-01 15:21:43.197818+0900 Runner[1915:436222] flutter: vod progress : 1.172 / 7.669
> ijkmp_pause()
> ijkmp_pause()=0
> ijkmp_get_msg: FFP_REQ_PAUSE
> aout_pause_audio(1)
> ijkmp_pause()
> ijkmp_pause()=0
> ijkmp_get_msg: FFP_REQ_PAUSE
> aout_pause_audio(1)
> ijkmp_stop()
> aout_pause_audio(1)
> ijkmp_stop()=0
> ijkmp_stop()
> aout_pause_audio(1)
> ijkmp_stop()=0
> ijkmp_shutdown_l()
> aout_pause_audio(1)
> aout_pause_audio(1)
> SDL_Overlay(ffmpeg): overlay_free_l(0x282be8310)
> SDL_Overlay(ffmpeg): overlay_free_l(0x282be8380)
> SDL_Overlay(ffmpeg): overlay_free_l(0x282be9dc0)
> ijkmp_shutdown_l()=void
> ijkmp_set_inject_opaque(0x0)
> ijkmp_set_inject_opaque()=void
> ijkmp_set_ijkio_inject_opaque(0x0)
> ijkmp_set_ijkio_inject_opaque()=void
> ijkmp_dec_ref(): ref=0
> ijkmp_shutdown_l()
> ijkmp_shutdown_l()=void
> aout_close_audio()
> 2019-08-01 15:22:06.442415+0900 Runner[1915:436217] 6.5.0 - [Firebase/InstanceID][I-IID003009] Failed to fetch default token Error Domain=com.firebase.iid Code=0 "(null)"


And, that m3u8 file looks like

> #EXTM3U
> #EXT-X-PLAYLIST-TYPE:VOD
> #EXT-X-TARGETDURATION:8
> #EXT-X-VERSION:3
> #EXT-X-MEDIA-SEQUENCE:0
> #EXT-X-ALLOW-CACHE:YES
> #EXTINF:7.669,
> http://xxx.xxx.xxx:xxxxx/V100/VMS_49103/summary_moviefile?s=4xl04D9Z7yZXGJaM71TedScxh%2BddANW%2BSLQlFYvA4BOqfDwoG8iklp9QzTBzoHg5bYD5tD8QH6joMa%2Fq%2ByrIf%2F79SsnDwaA4MwRQu9yfB3Ymln%2Fn%2FtclJWE9xd6IBMZrSIkjlpeWpbPaWfMF2i0SFA%3D%3D
> #EXT-X-ENDLIST
> 

It's ok to play other m3u8 files before playing rtsp stream.

And. this is the log when I play rtsp stream after playing m3u8 file.

> 2019-08-01 15:29:31.547881+0900 Runner[1915:436222] flutter: playing: rtsp://xxx.xxx.xxx.xxx:xxxx/gigaeyesmonitor/cam0000000187.stream
> 2019-08-01 15:29:31.548710+0900 Runner[1915:436222] flutter: playing: rtsp://xxx.xxx.xxx.xxx:xxxx/gigaeyesmonitor/cam0000000187.stream
> 2019-08-01 15:29:31.553106+0900 Runner[1915:436222] flutter: options = [IjkOption{category: IjkOptionCategory.format, key: fflags, value: fastseek}, IjkOption{category: IjkOptionCategory.codec, key: skip_loop_filter, value: 0}, IjkOption{category: IjkOptionCategory.codec, key: skip_frame, value: 0}, IjkOption{category: IjkOptionCategory.format, key: rtsp_transport, value: tcp}, IjkOption{category: IjkOptionCategory.format, key: probesize, value: 5000000}, IjkOption{category: IjkOptionCategory.player, key: start-on-prepared, value: 1}, IjkOption{category: IjkOptionCategory.format, key: timeout, value: 10000}]
> ijkmp_set_inject_opaque(0x2802dd060)
> ijkmp_set_inject_opaque()=void
> ijkmp_set_ijkio_inject_opaque(0x2802dd060)
> ijkmp_set_ijkio_inject_opaque()=void
> 2019-08-01 15:29:31.610380+0900 Runner[1915:436168] OK setup GL
> ijkmp_ios_set_view(glView=0x15fdabf60)
> ijkmp_ios_set_view(glView=0x15fdabf60)=void
> ijkmp_set_data_source(url="rtsp://xxx.xxx.xxx.xxx:xxxx/gigaeyesmonitor/cam0000000187.stream")
> ijkmp_set_data_source(url="rtsp://xxx.xxx.xxx.xxx:xxxx/gigaeyesmonitor/cam0000000187.stream")=0
> ijkmp_prepare_async()
> ijkmp_prepare_async()=0
> reset timeout
> cur abort_request: 0
> opening input: rtsp://xxx.xxx.xxx.xxx:xxxx/gigaeyesmonitor/cam0000000187.stream
> 2019-08-01 15:29:31.664682+0900 Runner[1915:437261] [si_destination_compare] send failed: Invalid argument
> 2019-08-01 15:29:31.664719+0900 Runner[1915:437261] [si_destination_compare] send failed: Undefined error: 0
> 2019-08-01 15:29:31.687531+0900 Runner[1915:436168] FFP_MSG_OPEN_INPUT:
> 2019-08-01 15:29:32.109788+0900 Runner[1915:437216] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:29:32.109859+0900 Runner[1915:437216] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:29:32.109979+0900 Runner[1915:437216] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:29:32.110007+0900 Runner[1915:437216] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:29:32.110324+0900 Runner[1915:437216] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:29:32.110384+0900 Runner[1915:437216] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:29:32.110444+0900 Runner[1915:436168] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:29:32.110548+0900 Runner[1915:437216] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:29:32.110782+0900 Runner[1915:436168] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:29:32.215611+0900 Runner[1915:437216] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:29:33.606520+0900 Runner[1915:436168] FFP_MSG_FIND_STREAM_INFO:
> 2019-08-01 15:29:33.606893+0900 Runner[1915:436168] FFP_MSG_VIDEO_DECODER_OPEN: false
> 2019-08-01 15:29:33.606920+0900 Runner[1915:436168] FFP_MSG_COMPONENT_OPEN:
> 2019-08-01 15:29:33.606935+0900 Runner[1915:436168] FFP_MSG_VIDEO_SIZE_CHANGED: 704, 480
> 2019-08-01 15:29:33.606954+0900 Runner[1915:436168] FFP_MSG_SAR_CHANGED: 40, 33
> ijkmp_get_msg: FFP_MSG_PREPARED
> 2019-08-01 15:29:33.607023+0900 Runner[1915:436168] FFP_MSG_PREPARED:
> ijkmp_get_meta_l
> ijkmp_get_meta_l()=void
> 2019-08-01 15:29:33.607076+0900 Runner[1915:436168] fps in meta 15.000000
> ijkmp_set_playback_rate(1.000000)
> ijkmp_set_playback_rate()=void
> ijkmp_set_playback_volume(1.000000)
> ijkmp_set_playback_volume()=void
> 2019-08-01 15:29:33.607188+0900 Runner[1915:436168] load state change, state = 3
> 2019-08-01 15:29:33.607952+0900 Runner[1915:436168] FFP_MSG_VIDEO_ROTATION_CHANGED:
> 2019-08-01 15:29:33.607984+0900 Runner[1915:436168] rotate arg1 = 0
> SDL_VoutFFmpeg_CreateOverlay(w=704, h=480, fmt=I420(0x30323449, dp=0x281500400)
> Video: first frame decoded
> 2019-08-01 15:29:33.622436+0900 Runner[1915:436168] FFP_MSG_VIDEO_SIZE_CHANGED: 704, 480
> SDL_VoutFFmpeg_CreateOverlay(w=704, h=480, fmt=I420(0x30323449, dp=0x281500400)
> 2019-08-01 15:29:33.623444+0900 Runner[1915:436168] FFP_MSG_VIDEO_DECODED_START:
> 2019-08-01 15:29:33.624328+0900 Runner[1915:436168] FFP_MSG_VIDEO_SIZE_CHANGED: 704, 480
> 2019-08-01 15:29:33.624369+0900 Runner[1915:436168] FFP_MSG_VIDEO_RENDERING_START:
> SDL_VoutFFmpeg_CreateOverlay(w=704, h=480, fmt=I420(0x30323449, dp=0x281500400)
> 2019-08-01 15:29:33.625397+0900 Runner[1915:436168] FFP_MSG_VIDEO_SIZE_CHANGED: 704, 480
> 2019-08-01 15:29:33.713540+0900 Runner[1915:436222] flutter: vod progress : 0.0 / 0.0
> 2019-08-01 15:29:33.850980+0900 Runner[1915:436222] flutter: vod progress : 0.0 / 0.0
> 2019-08-01 15:29:33.912893+0900 Runner[1915:436222] flutter: vod progress : 0.0 / 0.0
> 2019-08-01 15:29:34.013043+0900 Runner[1915:436222] flutter: vod progress : 0.0 / 0.0
> 2019-08-01 15:29:34.115775+0900 Runner[1915:436222] flutter: vod progress : 0.092 / 0.0
> 2019-08-01 15:29:34.215436+0900 Runner[1915:436222] flutter: vod progress : 0.189 / 0.0
> 2019-08-01 15:29:34.313760+0900 Runner[1915:436222] flutter: vod progress : 0.288 / 0.0
> 2019-08-01 15:29:34.412133+0900 Runner[1915:436222] flutter: vod progress : 0.387 / 0.0
> 2019-08-01 15:29:34.513012+0900 Runner[1915:436222] flutter: vod progress : 0.488 / 0.0
> 2019-08-01 15:29:34.616749+0900 Runner[1915:436222] flutter: vod progress : 0.592 / 0.0
> 2019-08-01 15:29:34.715685+0900 Runner[1915:436222] flutter: vod progress : 0.691 / 0.0
> 2019-08-01 15:29:34.813038+0900 Runner[1915:436222] flutter: vod progress : 0.787 / 0.0
> 2019-08-01 15:29:34.913213+0900 Runner[1915:436222] flutter: vod progress : 0.887 / 0.0
> 2019-08-01 15:29:35.013257+0900 Runner[1915:436222] flutter: vod progress : 0.988 / 0.0
> 2019-08-01 15:29:35.112802+0900 Runner[1915:436222] flutter: vod progress : 1.087 / 0.0
> 2019-08-01 15:29:35.211894+0900 Runner[1915:436222] flutter: vod progress : 1.186 / 0.0
> 2019-08-01 15:29:35.313772+0900 Runner[1915:436222] flutter: vod progress : 1.287 / 0.0
> 2019-08-01 15:29:35.414488+0900 Runner[1915:436222] flutter: vod progress : 1.389 / 0.0
> 2019-08-01 15:29:35.514974+0900 Runner[1915:436222] flutter: vod progress : 1.489 / 0.0
> 2019-08-01 15:29:35.677908+0900 Runner[1915:436222] flutter: vod progress : 1.653 / 0.0
> 2019-08-01 15:29:35.714966+0900 Runner[1915:436222] flutter: vod progress : 1.69 / 0.0
> 2019-08-01 15:29:35.813382+0900 Runner[1915:436222] flutter: vod progress : 1.789 / 0.0
> 2019-08-01 15:29:35.996046+0900 Runner[1915:436222] flutter: vod progress : 1.97 / 0.0
> 2019-08-01 15:29:36.025641+0900 Runner[1915:436222] flutter: vod progress : 2.0 / 0.0
> 2019-08-01 15:29:36.113771+0900 Runner[1915:436222] flutter: vod progress : 2.088 / 0.0
> ijkmp_pause()
> ijkmp_pause()=0
> ijkmp_get_msg: FFP_REQ_PAUSE
> aout_pause_audio(1)
> ijkmp_pause()
> ijkmp_pause()=0
> ijkmp_get_msg: FFP_REQ_PAUSE
> aout_pause_audio(1)
> ijkmp_stop()
> aout_pause_audio(1)
> ijkmp_stop()=0
> ijkmp_stop()
> aout_pause_audio(1)
> ijkmp_stop()=0
> ijkmp_shutdown_l()
> aout_pause_audio(1)
> aout_pause_audio(1)
> SDL_Overlay(ffmpeg): overlay_free_l(0x282bea220)
> SDL_Overlay(ffmpeg): overlay_free_l(0x282beabc0)
> SDL_Overlay(ffmpeg): overlay_free_l(0x282bed9d0)
> ijkmp_shutdown_l()=void
> ijkmp_set_inject_opaque(0x0)
> ijkmp_set_inject_opaque()=void
> ijkmp_set_ijkio_inject_opaque(0x0)
> ijkmp_set_ijkio_inject_opaque()=void
> ijkmp_dec_ref(): ref=0
> ijkmp_shutdown_l()
> ijkmp_shutdown_l()=void
> aout_close_audio()

It's ok to play rtsp stream. but when I go back to m3u8.

> 2019-08-01 15:34:28.059971+0900 Runner[1915:436222] flutter: playing: http://xxx.xxx.xxx.xxx:xxxxx/V100/VMS_49101/summary_playlist?s=JW0NxhFw5dH%2FB6PHl0hxC1BVjetuVQiN5ukTGIANn179Ekn7Z8apve2n7Rhv65dKBn1tgwr%2B9dGbj3LQTfeZhP75Fu6QwIJCiMzFNuZPiKyJY7UENfDkC9EgM4XxSESTs7fXCRsxjtFquLfdpiNG4R5YreMt3S0TV7df28rW3GQ%3D&t=49b6c3f6.m3u8
> 2019-08-01 15:34:28.061172+0900 Runner[1915:436222] flutter: options = [IjkOption{category: IjkOptionCategory.format, key: fflags, value: fastseek}, IjkOption{category: IjkOptionCategory.codec, key: skip_loop_filter, value: 0}, IjkOption{category: IjkOptionCategory.codec, key: skip_frame, value: 0}, IjkOption{category: IjkOptionCategory.format, key: probesize, value: 5000000}, IjkOption{category: IjkOptionCategory.player, key: start-on-prepared, value: 1}, IjkOption{category: IjkOptionCategory.format, key: timeout, value: 10000}]
> ijkmp_set_inject_opaque(0x2802d97b0)
> ijkmp_set_inject_opaque()=void
> ijkmp_set_ijkio_inject_opaque(0x2802d97b0)
> ijkmp_set_ijkio_inject_opaque()=void
> 2019-08-01 15:34:28.080791+0900 Runner[1915:436168] OK setup GL
> ijkmp_ios_set_view(glView=0x161a5a4a0)
> ijkmp_ios_set_view(glView=0x161a5a4a0)=void
> ijkmp_set_data_source(url="http://xxx.xxx.xxx.xxx:xxxxx/V100/VMS_49101/summary_playlist?s=JW0NxhFw5dH%2FB6PHl0hxC1BVjetuVQiN5ukTGIANn179Ekn7Z8apve2n7Rhv65dKBn1tgwr%2B9dGbj3LQTfeZhP75Fu6QwIJCiMzFNuZPiKyJY7UENfDkC9EgM4XxSESTs7fXCRsxjtFquLfdpiNG4R5YreMt3S0TV7df28rW3GQ%3D&t=49b6c3f6.m3u8")
> ijkmp_set_data_source(url="http://xxx.xxx.xxx.xxx:xxxxx/V100/VMS_49101/summary_playlist?s=JW0NxhFw5dH%2FB6PHl0hxC1BVjetuVQiN5ukTGIANn179Ekn7Z8apve2n7Rhv65dKBn1tgwr%2B9dGbj3LQTfeZhP75Fu6QwIJCiMzFNuZPiKyJY7UENfDkC9EgM4XxSESTs7fXCRsxjtFquLfdpiNG4R5YreMt3S0TV7df28rW3GQ%3D&t=49b6c3f6.m3u8")=0
> ijkmp_prepare_async()
> ijkmp_prepare_async()=0
> no reset timeout
> cur abort_request: 0
> opening input: http://xxx.xxx.xxx.xxx:xxxxx/V100/VMS_49101/summary_playlist?s=JW0NxhFw5dH%2FB6PHl0hxC1BVjetuVQiN5ukTGIANn179Ekn7Z8apve2n7Rhv65dKBn1tgwr%2B9dGbj3LQTfeZhP75Fu6QwIJCiMzFNuZPiKyJY7UENfDkC9EgM4XxSESTs7fXCRsxjtFquLfdpiNG4R5YreMt3S0TV7df28rW3GQ%3D&t=49b6c3f6.m3u8
> avformat_open_input error : -1094995529
> 2019-08-01 15:34:28.132320+0900 Runner[1915:436168] FFP_MSG_ERROR: 0
> 2019-08-01 15:34:28.640202+0900 Runner[1915:437162] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:34:28.640395+0900 Runner[1915:437162] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:34:28.640961+0900 Runner[1915:437162] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:34:28.641043+0900 Runner[1915:437162] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:34:28.642493+0900 Runner[1915:437162] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:34:28.642759+0900 Runner[1915:437162] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:34:28.642978+0900 Runner[1915:436168] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:34:28.643336+0900 Runner[1915:437162] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:34:28.643915+0900 Runner[1915:436168] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 2019-08-01 15:34:28.751458+0900 Runner[1915:437718] [MediaRemote] OutputDeviceUID is nil 스피커: (null)
> 



I added some more log to "ff_play.c" at the line number 3253

`
   ic = avformat_alloc_context();
    if (!ic) {
        av_log(NULL, AV_LOG_FATAL, "Could not allocate context.\n");
        MPTRACE("Could not allocate context.\n");
        ret = AVERROR(ENOMEM);
        goto fail;
    }
    ic->interrupt_callback.callback = decode_interrupt_cb;
    ic->interrupt_callback.opaque = is;
    if (!av_dict_get(ffp->format_opts, "scan_all_pmts", NULL, AV_DICT_MATCH_CASE)) {
        av_dict_set(&ffp->format_opts, "scan_all_pmts", "1", AV_DICT_DONT_OVERWRITE);
        scan_all_pmts_set = 1;
    }

    if (av_stristart(is->filename, "rtmp", NULL) ||
        av_stristart(is->filename, "rtsp", NULL)) {
        // There is total different meaning for 'timeout' option in rtmp
        av_log(ffp, AV_LOG_WARNING, "remove 'timeout' option for rtmp.\n");
        av_dict_set(&ffp->format_opts, "timeout", NULL, 0);
        MPTRACE("reset timeout\n");
    } else {
        MPTRACE("no reset timeout\n");
    }

    if (ffp->skip_calc_frame_rate) {
        av_dict_set_int(&ic->metadata, "skip-calc-frame-rate", ffp->skip_calc_frame_rate, 0);
        av_dict_set_int(&ffp->format_opts, "skip-calc-frame-rate", ffp->skip_calc_frame_rate, 0);
        MPTRACE("skip-calc-frame-rate\n");
    }

    if (ffp->iformat_name){
        is->iformat = av_find_input_format(ffp->iformat_name);
        MPTRACE("av_find_input_format: %s\n", ffp->iformat_name);
    }
    MPTRACE("cur abort_request: %d\n", is->abort_request);
    if(is->abort_request != 0) {
        MPTRACE("reset abort_request\n");
        is->abort_request = 0;
    }


    MPTRACE("opening input: %s\n", is->filename);

//    MPTRACE("reset opts\n");
//    AVDictionary *opts = 0;
//    av_dict_set(&opts, "rtsp_transport", "tcp", 0);
//    av_dict_set(&opts, "protocol_whitelist", "file,http,https,tcp,tls,crypto", 0);

    err = avformat_open_input(&ic, is->filename, is->iformat, &ffp->format_opts);
//    err = avformat_open_input(&ic, is->filename, NULL, &ffp->format_opts);
//    err = avformat_open_input(&ic, is->filename, NULL, &opts);
    if (err < 0) {
        MPTRACE("avformat_open_input error : %d\n", err);
        print_error(is->filename, err);
        ret = -1;
        goto fail;
    }
    ffp_notify_msg1(ffp, FFP_MSG_OPEN_INPUT);
`

Thank you for your attention.

**Comment by befovy** [comment]
Is the domain and port of m3u8 url same as rtsp url?  @andpark 

Maybe it likes https://github.com/bilibili/ijkplayer/issues/3990
or
https://github.com/bilibili/ijkplayer/issues/4510

**Comment by andpark** [comment]
@befovy Thank you so so so much.
I struggled with this problem for 3 days!

I used same Ip Address(not domain) but different port number.

The problem is gone after setting this option.
`ijkPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_clear", 1);`

Thank you!

**Comment by befovy** [comment]
@andpark I noticed that you use ijkplayer in flutter.
I'm also working on a flutter plugin for ijkplayer  https://github.com/befovy/fijkplayer  .
I will be very happy if you can give any advice.
