### ISSUE TITLE
ijkplayer Archive出错

### ISSUE THREAD

**Issue by Hytper** [bilibili/ijkplayer#4811]
自己的项目导入IJKMediaFramework.framework能真机运行，打ipa包就会报错。log如下:
Undefined symbols for architecture armv7:
  "_av_guess_frame_rate", referenced from:
      _QueuePicture in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _QueuePicture in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_avio_open_dyn_buf", referenced from:
      _vtbformat_init in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _decode_video_internal in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _vtbformat_init in IJKMediaFramework(IJKVideoToolBoxSync.o)
      _decode_video_internal in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_avio_close_dyn_buf", referenced from:
      _vtbformat_init in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _decode_video_internal in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _vtbformat_init in IJKMediaFramework(IJKVideoToolBoxSync.o)
      _decode_video_internal in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_av_packet_split_side_data", referenced from:
      _videotoolbox_async_decode_frame in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _videotoolbox_sync_decode_frame in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_av_packet_get_side_data", referenced from:
      _videotoolbox_async_decode_frame in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _videotoolbox_sync_decode_frame in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_avcodec_decode_video2", referenced from:
      _videotoolbox_async_decode_frame in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _videotoolbox_sync_decode_frame in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_ff_isom_write_avcc", referenced from:
      _vtbformat_init in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _vtbformat_init in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_avcodec_parameters_from_context", referenced from:
      _videotoolbox_async_decode_frame in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _videotoolbox_async_create in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _videotoolbox_sync_decode_frame in IJKMediaFramework(IJKVideoToolBoxSync.o)
      _videotoolbox_sync_create in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_av_copy_packet", referenced from:
      _videotoolbox_async_decode_frame in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _videotoolbox_sync_decode_frame in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_avcodec_parameters_free", referenced from:
      _videotoolbox_async_free in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _videotoolbox_sync_free in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_ffurl_closep", referenced from:
      _ijkurlhook_close in IJKMediaFramework(ijkurlhook.o)
      _ijkurlhook_reconnect in IJKMediaFramework(ijkurlhook.o)
  "_ffurl_write", referenced from:
      _ijkurlhook_write in IJKMediaFramework(ijkurlhook.o)
  "_ffurl_read", referenced from:
      _wrapped_url_read in IJKMediaFramework(ijkasync.o)
      _ijkurlhook_read in IJKMediaFramework(ijkurlhook.o)
      _ijklongurl_read in IJKMediaFramework(ijklongurl.o)
      _ijksegment_read in IJKMediaFramework(ijksegment.o)
      _ijkio_ffio_read in IJKMediaFramework(ijkioffio.o)
  "_av_fifo_space", referenced from:
      _async_buffer_task in IJKMediaFramework(ijkasync.o)
  "_ff_avc_parse_nal_units", referenced from:
      _decode_video_internal in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _decode_video_internal in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_av_application_on_async_read_speed", referenced from:
      _async_buffer_task in IJKMediaFramework(ijkasync.o)
  "_av_fifo_reset", referenced from:
      _async_buffer_task in IJKMediaFramework(ijkasync.o)
  "_av_fifo_alloc", referenced from:
      _async_open in IJKMediaFramework(ijkasync.o)
  "_ffurl_open_whitelist", referenced from:
      _async_open in IJKMediaFramework(ijkasync.o)
      _ijkurlhook_reconnect in IJKMediaFramework(ijkurlhook.o)
      _ijklongurl_open in IJKMediaFramework(ijklongurl.o)
      _ijksegment_open in IJKMediaFramework(ijksegment.o)
      _ijkio_ffio_open in IJKMediaFramework(ijkioffio.o)
  "_ffurl_size", referenced from:
      _async_open in IJKMediaFramework(ijkasync.o)
  "_ffurl_close", referenced from:
      _async_open in IJKMediaFramework(ijkasync.o)
      _async_close in IJKMediaFramework(ijkasync.o)
      _ijklongurl_close in IJKMediaFramework(ijklongurl.o)
      _ijksegment_close in IJKMediaFramework(ijksegment.o)
      _ijkio_ffio_close in IJKMediaFramework(ijkioffio.o)
  "_av_fifo_freep", referenced from:
      _async_open in IJKMediaFramework(ijkasync.o)
      _async_close in IJKMediaFramework(ijkasync.o)
  "_avcodec_parameters_copy", referenced from:
      _open_inner in IJKMediaFramework(ijklivehook.o)
  "_av_application_on_io_control", referenced from:
      _ijkurlhook_call_inject in IJKMediaFramework(ijklivehook.o)
      _ijkurlhook_call_inject in IJKMediaFramework(ijkurlhook.o)
      _ijksegment_open in IJKMediaFramework(ijksegment.o)
      _ijkio_urlhook_call_inject in IJKMediaFramework(ijkiourlhook.o)
  "_ff_check_interrupt", referenced from:
      _ijkurlhook_call_inject in IJKMediaFramework(ijklivehook.o)
      _async_seek in IJKMediaFramework(ijkasync.o)
      _async_check_interrupt in IJKMediaFramework(ijkasync.o)
      _async_buffer_task in IJKMediaFramework(ijkasync.o)
      _async_read_internal in IJKMediaFramework(ijkasync.o)
      _ijkurlhook_call_inject in IJKMediaFramework(ijkurlhook.o)
  "_ijkav_register_ijktcphook_protocol", referenced from:
      _ijkav_register_all in IJKMediaFramework(allformats.o)
  "_ijkav_register_ijkhttphook_protocol", referenced from:
      _ijkav_register_all in IJKMediaFramework(allformats.o)
  "_av_iformat_next", referenced from:
      _ijkav_register_all in IJKMediaFramework(allformats.o)
  "_ffurl_seek", referenced from:
      _async_buffer_task in IJKMediaFramework(ijkasync.o)
      _ijkurlhook_reconnect in IJKMediaFramework(ijkurlhook.o)
      _ijkhttphook_reseek_at in IJKMediaFramework(ijkurlhook.o)
      _ijklongurl_seek in IJKMediaFramework(ijklongurl.o)
      _ijksegment_seek in IJKMediaFramework(ijksegment.o)
      _ijkio_ffio_seek in IJKMediaFramework(ijkioffio.o)
  "_av_register_input_format", referenced from:
      _ijkav_register_all in IJKMediaFramework(allformats.o)
  "_av_strtod", referenced from:
      _get_rotation in IJKMediaFramework(ff_cmdutils.o)
  "_avcodec_parameters_alloc", referenced from:
      _videotoolbox_async_create in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _videotoolbox_sync_create in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_av_display_rotation_get", referenced from:
      _get_rotation in IJKMediaFramework(ff_cmdutils.o)
  "_avio_write", referenced from:
      _decode_video_internal in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _decode_video_internal in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_av_strerror", referenced from:
      _print_error in IJKMediaFramework(ff_cmdutils.o)
      _async_open in IJKMediaFramework(ijkasync.o)
      _async_close in IJKMediaFramework(ijkasync.o)
      _ijkio_cache_open in IJKMediaFramework(ijkiocache.o)
  "_av_frame_ref", referenced from:
      _func_fill_frame in IJKMediaFramework(ijksdl_vout_overlay_ffmpeg.o)
  "_av_buffer_alloc", referenced from:
      _func_fill_frame in IJKMediaFramework(ijksdl_vout_overlay_ffmpeg.o)
  "_sws_getCachedContext", referenced from:
      _func_fill_frame in IJKMediaFramework(ijksdl_vout_overlay_ffmpeg.o)
  "_av_buffer_unref", referenced from:
      _func_free_l in IJKMediaFramework(ijksdl_vout_overlay_ffmpeg.o)
  "_swr_alloc_set_opts", referenced from:
      _sdl_audio_callback in IJKMediaFramework(ff_ffplay.o)
  "_ijkav_register_ijksegment_protocol", referenced from:
      _ijkav_register_all in IJKMediaFramework(allformats.o)
  "_av_dict_copy", referenced from:
      _sdl_audio_callback in IJKMediaFramework(ff_ffplay.o)
      _ijklivehook_read_header in IJKMediaFramework(ijklivehook.o)
      _open_inner in IJKMediaFramework(ijklivehook.o)
      _ijkurlhook_init in IJKMediaFramework(ijkurlhook.o)
      _ijkurlhook_reconnect in IJKMediaFramework(ijkurlhook.o)
     (maybe you meant: _ijk_av_dict_copy)
  "_sws_scale", referenced from:
      _ffp_video_thread in IJKMediaFramework(ff_ffplay.o)
      _func_fill_frame in IJKMediaFramework(ijksdl_vout_overlay_ffmpeg.o)
  "_swr_set_compensation", referenced from:
      _sdl_audio_callback in IJKMediaFramework(ff_ffplay.o)
  "_swr_convert", referenced from:
      _sdl_audio_callback in IJKMediaFramework(ff_ffplay.o)
  "_av_fifo_drain", referenced from:
      _async_read_internal in IJKMediaFramework(ijkasync.o)
  "_av_asprintf", referenced from:
      _ffp_set_video_codec_info in IJKMediaFramework(ff_ffplay.o)
      _ffp_set_audio_codec_info in IJKMediaFramework(ff_ffplay.o)
      _ffp_set_subtitle_codec_info in IJKMediaFramework(ff_ffplay.o)
  "_swr_init", referenced from:
      _sdl_audio_callback in IJKMediaFramework(ff_ffplay.o)
  "_av_dict_set", referenced from:
      _ijkmeta_set_avformat_context_l in IJKMediaFramework(ijkmeta.o)
      _ffp_set_option in IJKMediaFramework(ff_ffplay.o)
      _ffp_prepare_async_l in IJKMediaFramework(ff_ffplay.o)
      _stream_component_open in IJKMediaFramework(ff_ffplay.o)
      _read_thread in IJKMediaFramework(ff_ffplay.o)
      _filter_codec_opts in IJKMediaFramework(ff_cmdutils.o)
      _ijklivehook_read_header in IJKMediaFramework(ijklivehook.o)
      ...
     (maybe you meant: _ijk_av_dict_set_int, _ijk_av_dict_set )
  "_av_read_frame", referenced from:
      _read_thread in IJKMediaFramework(ff_ffplay.o)
      _ijklivehook_read_packet in IJKMediaFramework(ijklivehook.o)
  "_avcodec_receive_frame", referenced from:
      _decoder_decode_frame in IJKMediaFramework(ff_ffplay.o)
  "_avcodec_decode_subtitle2", referenced from:
      _decoder_decode_frame in IJKMediaFramework(ff_ffplay.o)
  "_avcodec_flush_buffers", referenced from:
      _decoder_decode_frame in IJKMediaFramework(ff_ffplay.o)
      _videotoolbox_async_decode_frame in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _videotoolbox_sync_decode_frame in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_avformat_open_input", referenced from:
      _read_thread in IJKMediaFramework(ff_ffplay.o)
      _open_inner in IJKMediaFramework(ijklivehook.o)
  "_av_fifo_generic_write", referenced from:
      _async_buffer_task in IJKMediaFramework(ijkasync.o)
  "_avformat_find_stream_info", referenced from:
      _read_thread in IJKMediaFramework(ff_ffplay.o)
      _open_inner in IJKMediaFramework(ijklivehook.o)
  "_av_version_info", referenced from:
      +[IJKFFMoviePlayerController checkIfFFmpegVersionMatch:] in IJKMediaFramework(IJKFFMoviePlayerController.o)
      _ffp_create in IJKMediaFramework(ff_ffplay.o)
      _ffp_prepare_async_l in IJKMediaFramework(ff_ffplay.o)
  "_av_dump_format", referenced from:
      _read_thread in IJKMediaFramework(ff_ffplay.o)
  "_av_opt_find", referenced from:
      _filter_codec_opts in IJKMediaFramework(ff_cmdutils.o)
  "_av_packet_move_ref", referenced from:
      _decoder_decode_frame in IJKMediaFramework(ff_ffplay.o)
  "_avformat_match_stream_specifier", referenced from:
      _read_thread in IJKMediaFramework(ff_ffplay.o)
      _filter_codec_opts in IJKMediaFramework(ff_cmdutils.o)
  "_av_gettime", referenced from:
      _read_thread in IJKMediaFramework(ff_ffplay.o)
      _video_display2 in IJKMediaFramework(ff_ffplay.o)
  "_av_stream_get_side_data", referenced from:
      _get_rotation in IJKMediaFramework(ff_cmdutils.o)
  "_av_get_sample_fmt_name", referenced from:
      _sdl_audio_callback in IJKMediaFramework(ff_ffplay.o)
  "_av_log", referenced from:
      _ijkmp_get_msg in IJKMediaFramework(ijkplayer.o)
      _lockmgr in IJKMediaFramework(ff_ffplay.o)
      _ffp_create in IJKMediaFramework(ff_ffplay.o)
      _ffp_destroy in IJKMediaFramework(ff_ffplay.o)
      _stream_close in IJKMediaFramework(ff_ffplay.o)
      _ffp_get_opt_dict in IJKMediaFramework(ff_ffplay.o)
      _ffp_prepare_async_l in IJKMediaFramework(ff_ffplay.o)
      ...
  "_avio_feof", referenced from:
      _read_thread in IJKMediaFramework(ff_ffplay.o)
  "_avsubtitle_free", referenced from:
      _frame_queue_unref_item in IJKMediaFramework(ff_ffplay.o)
  "_avcodec_find_decoder", referenced from:
      _ijkmeta_set_avformat_context_l in IJKMediaFramework(ijkmeta.o)
      _stream_component_open in IJKMediaFramework(ff_ffplay.o)
      _filter_codec_opts in IJKMediaFramework(ff_cmdutils.o)
  "_av_log2", referenced from:
      _stream_component_open in IJKMediaFramework(ff_ffplay.o)
  "_avcodec_find_decoder_by_name", referenced from:
      _stream_component_open in IJKMediaFramework(ff_ffplay.o)
  "_av_codec_get_max_lowres", referenced from:
      _stream_component_open in IJKMediaFramework(ff_ffplay.o)
  "_av_rescale_q", referenced from:
      _decoder_decode_frame in IJKMediaFramework(ff_ffplay.o)
  "_av_codec_set_lowres", referenced from:
      _stream_component_open in IJKMediaFramework(ff_ffplay.o)
  "_avformat_version", referenced from:
      _ffp_prepare_async_l in IJKMediaFramework(ff_ffplay.o)
  "_avcodec_send_packet", referenced from:
      _decoder_decode_frame in IJKMediaFramework(ff_ffplay.o)
  "_av_get_channel_layout_nb_channels", referenced from:
      _stream_component_open in IJKMediaFramework(ff_ffplay.o)
      _sdl_audio_callback in IJKMediaFramework(ff_ffplay.o)
  "_av_log_set_level", referenced from:
      _ffp_global_set_log_level in IJKMediaFramework(ff_ffplay.o)
  "_av_samples_get_buffer_size", referenced from:
      _stream_component_open in IJKMediaFramework(ff_ffplay.o)
      _sdl_audio_callback in IJKMediaFramework(ff_ffplay.o)
  "_av_dict_free", referenced from:
      _ijkmeta_destroy in IJKMediaFramework(ijkmeta.o)
      _ijkmeta_reset in IJKMediaFramework(ijkmeta.o)
      _ffp_reset_internal in IJKMediaFramework(ff_ffplay.o)
      _stream_component_open in IJKMediaFramework(ff_ffplay.o)
      _read_thread in IJKMediaFramework(ff_ffplay.o)
      _sdl_audio_callback in IJKMediaFramework(ff_ffplay.o)
      _open_inner in IJKMediaFramework(ijklivehook.o)
      ...
     (maybe you meant: _ijk_av_dict_free)
  "_av_find_input_format", referenced from:
      _read_thread in IJKMediaFramework(ff_ffplay.o)
  "_av_guess_sample_aspect_ratio", referenced from:
      _ffp_video_thread in IJKMediaFramework(ff_ffplay.o)
  "_ijkav_register_ijklongurl_protocol", referenced from:
      _ijkav_register_all in IJKMediaFramework(allformats.o)
  "_av_image_fill_arrays", referenced from:
      _ffp_video_thread in IJKMediaFramework(ff_ffplay.o)
      _SDL_VoutFFmpeg_CreateOverlay in IJKMediaFramework(ijksdl_vout_overlay_ffmpeg.o)
      _func_fill_frame in IJKMediaFramework(ijksdl_vout_overlay_ffmpeg.o)
  "_av_malloc", referenced from:
      _ijkmp_change_state_l in IJKMediaFramework(ijkplayer.o)
      _ijkmp_prepare_async in IJKMediaFramework(ijkplayer.o)
      _ijkmp_start in IJKMediaFramework(ijkplayer.o)
      _ijkmp_pause in IJKMediaFramework(ijkplayer.o)
      _ijkmp_seek_to_l in IJKMediaFramework(ijkplayer.o)
      _ffp_seek_to_l in IJKMediaFramework(ff_ffplay.o)
      _queue_picture in IJKMediaFramework(ff_ffplay.o)
      ...
  "_avformat_seek_file", referenced from:
      _read_thread in IJKMediaFramework(ff_ffplay.o)
  "_sws_getContext", referenced from:
      _ffp_video_thread in IJKMediaFramework(ff_ffplay.o)
  "_ijkav_register_ijkio_protocol", referenced from:
      _ijkav_register_all in IJKMediaFramework(allformats.o)
  "_avcodec_alloc_context3", referenced from:
      _ffp_video_thread in IJKMediaFramework(ff_ffplay.o)
      _stream_component_open in IJKMediaFramework(ff_ffplay.o)
      _videotoolbox_async_decode_frame in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _videotoolbox_sync_decode_frame in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_av_fast_malloc", referenced from:
      _sdl_audio_callback in IJKMediaFramework(ff_ffplay.o)
  "_av_packet_unref", referenced from:
      _packet_queue_flush in IJKMediaFramework(ff_ffplay.o)
      _packet_queue_get_or_buffering in IJKMediaFramework(ff_ffplay.o)
      _packet_queue_put in IJKMediaFramework(ff_ffplay.o)
      _ffp_video_thread in IJKMediaFramework(ff_ffplay.o)
      _stream_component_close in IJKMediaFramework(ff_ffplay.o)
      _read_thread in IJKMediaFramework(ff_ffplay.o)
      _decoder_decode_frame in IJKMediaFramework(ff_ffplay.o)
      ...
  "_av_rescale", referenced from:
      _ffp_seek_to_l in IJKMediaFramework(ff_ffplay.o)
      _ffp_get_duration_l in IJKMediaFramework(ff_ffplay.o)
      _ffp_get_current_position_l in IJKMediaFramework(ff_ffplay.o)
      _ffp_check_buffering_l in IJKMediaFramework(ff_ffplay.o)
      _read_thread in IJKMediaFramework(ff_ffplay.o)
  "_av_reduce", referenced from:
      _ffp_video_thread in IJKMediaFramework(ff_ffplay.o)
  "_av_frame_unref", referenced from:
      _ffp_video_thread in IJKMediaFramework(ff_ffplay.o)
      _frame_queue_unref_item in IJKMediaFramework(ff_ffplay.o)
      _audio_thread in IJKMediaFramework(ff_ffplay.o)
      _func_free_l in IJKMediaFramework(ijksdl_vout_overlay_ffmpeg.o)
      _func_fill_frame in IJKMediaFramework(ijksdl_vout_overlay_ffmpeg.o)
      _videotoolbox_async_decode_frame in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _videotoolbox_sync_decode_frame in IJKMediaFramework(IJKVideoToolBoxSync.o)
      ...
  "_avio_find_protocol_name", referenced from:
      _ffp_prepare_async_l in IJKMediaFramework(ff_ffplay.o)
  "_swresample_version", referenced from:
      _ffp_prepare_async_l in IJKMediaFramework(ff_ffplay.o)
  "_av_packet_ref", referenced from:
      _read_thread in IJKMediaFramework(ff_ffplay.o)
  "_av_stristart", referenced from:
      _ffp_prepare_async_l in IJKMediaFramework(ff_ffplay.o)
      _read_thread in IJKMediaFramework(ff_ffplay.o)
      _ijklivehook_read_header in IJKMediaFramework(ijklivehook.o)
      _ijkhttphook_open in IJKMediaFramework(ijkurlhook.o)
  "_av_frame_free", referenced from:
      _ffp_video_thread in IJKMediaFramework(ff_ffplay.o)
      _frame_queue_destory in IJKMediaFramework(ff_ffplay.o)
      _audio_thread in IJKMediaFramework(ff_ffplay.o)
      _SDL_VoutFFmpeg_CreateOverlay in IJKMediaFramework(ijksdl_vout_overlay_ffmpeg.o)
      _func_free_l in IJKMediaFramework(ijksdl_vout_overlay_ffmpeg.o)
  "_av_opt_free", referenced from:
      _ffp_reset_internal in IJKMediaFramework(ff_ffplay.o)
  "_avcodec_version", referenced from:
      _ffp_prepare_async_l in IJKMediaFramework(ff_ffplay.o)
  "_avio_wb32", referenced from:
      _decode_video_internal in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _decode_video_internal in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_av_get_pix_fmt_name", referenced from:
      _ijkmeta_set_avformat_context_l in IJKMediaFramework(ijkmeta.o)
      _func_fill_frame in IJKMediaFramework(ijksdl_vout_overlay_ffmpeg.o)
  "_av_strdup", referenced from:
      _ffp_prepare_async_l in IJKMediaFramework(ff_ffplay.o)
  "_swr_free", referenced from:
      _stream_component_close in IJKMediaFramework(ff_ffplay.o)
      _sdl_audio_callback in IJKMediaFramework(ff_ffplay.o)
  "_avcodec_free_context", referenced from:
      _stream_close in IJKMediaFramework(ff_ffplay.o)
      _stream_component_close in IJKMediaFramework(ff_ffplay.o)
      _stream_component_open in IJKMediaFramework(ff_ffplay.o)
      _videotoolbox_async_decode_frame in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _videotoolbox_sync_decode_frame in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_swscale_version", referenced from:
      _ffp_prepare_async_l in IJKMediaFramework(ff_ffplay.o)
  "_avcodec_parameters_to_context", referenced from:
      _stream_component_open in IJKMediaFramework(ff_ffplay.o)
      _videotoolbox_async_decode_frame in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _videotoolbox_sync_decode_frame in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_av_opt_set_dict", referenced from:
      _ffp_prepare_async_l in IJKMediaFramework(ff_ffplay.o)
      _sdl_audio_callback in IJKMediaFramework(ff_ffplay.o)
  "_av_dict_set_int", referenced from:
      _ijkmeta_set_int64_l in IJKMediaFramework(ijkmeta.o)
      _ijkmeta_set_avformat_context_l in IJKMediaFramework(ijkmeta.o)
      _ffp_set_ijkio_inject_opaque in IJKMediaFramework(ff_ffplay.o)
      _ffp_set_option_int in IJKMediaFramework(ff_ffplay.o)
      _ffp_set_inject_opaque in IJKMediaFramework(ff_ffplay.o)
      _stream_component_open in IJKMediaFramework(ff_ffplay.o)
      _read_thread in IJKMediaFramework(ff_ffplay.o)
      ...
     (maybe you meant: _ijk_av_dict_set_int)
  "_avformat_close_input", referenced from:
      _stream_close in IJKMediaFramework(ff_ffplay.o)
      _read_thread in IJKMediaFramework(ff_ffplay.o)
      _ijklivehook_read_close in IJKMediaFramework(ijklivehook.o)
      _open_inner in IJKMediaFramework(ijklivehook.o)
  "_avcodec_encode_video2", referenced from:
      _ffp_video_thread in IJKMediaFramework(ff_ffplay.o)
  "_sws_freeContext", referenced from:
      _stream_close in IJKMediaFramework(ff_ffplay.o)
      _func_free_l in IJKMediaFramework(ijksdl_vout_overlay_ffmpeg.o)
  "_av_codec_get_pkt_timebase", referenced from:
      _decoder_decode_frame in IJKMediaFramework(ff_ffplay.o)
  "_av_freep", referenced from:
      _ffp_reset_internal in IJKMediaFramework(ff_ffplay.o)
      _ffp_destroy in IJKMediaFramework(ff_ffplay.o)
      _stream_close in IJKMediaFramework(ff_ffplay.o)
      _ffp_prepare_async_l in IJKMediaFramework(ff_ffplay.o)
      _packet_queue_destroy in IJKMediaFramework(ff_ffplay.o)
      _ffp_set_video_codec_info in IJKMediaFramework(ff_ffplay.o)
      _ffp_set_audio_codec_info in IJKMediaFramework(ff_ffplay.o)
      ...
     (maybe you meant: _ijk_av_freep)
  "_av_application_closep", referenced from:
      _ffp_reset_internal in IJKMediaFramework(ff_ffplay.o)
      _ffp_set_inject_opaque in IJKMediaFramework(ff_ffplay.o)
  "_av_log_set_callback", referenced from:
      _ffp_global_init in IJKMediaFramework(ff_ffplay.o)
      _ffp_global_set_log_report in IJKMediaFramework(ff_ffplay.o)
  "_av_usleep", referenced from:
      _queue_picture in IJKMediaFramework(ff_ffplay.o)
      _video_refresh_thread in IJKMediaFramework(ff_ffplay.o)
      _audio_thread in IJKMediaFramework(ff_ffplay.o)
      _sdl_audio_callback in IJKMediaFramework(ff_ffplay.o)
  "_av_free", referenced from:
      _ffp_destroy in IJKMediaFramework(ff_ffplay.o)
      _stream_close in IJKMediaFramework(ff_ffplay.o)
      _ffp_video_thread in IJKMediaFramework(ff_ffplay.o)
      _msg_obj_free_l in IJKMediaFramework(ff_ffplay.o)
      _vtbformat_init in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _decode_video_internal in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _vtbformat_init in IJKMediaFramework(IJKVideoToolBoxSync.o)
      ...
     (maybe you meant: _ijk_av_freep)
  "_avformat_alloc_context", referenced from:
      _read_thread in IJKMediaFramework(ff_ffplay.o)
      _open_inner in IJKMediaFramework(ijklivehook.o)
  "_ff_alloc_extradata", referenced from:
      _open_inner in IJKMediaFramework(ijklivehook.o)
  "_av_image_get_buffer_size", referenced from:
      _ffp_video_thread in IJKMediaFramework(ff_ffplay.o)
      _func_fill_frame in IJKMediaFramework(ijksdl_vout_overlay_ffmpeg.o)
  "_av_gettime_relative", referenced from:
      _ffp_prepare_async_l in IJKMediaFramework(ff_ffplay.o)
      _toggle_pause in IJKMediaFramework(ff_ffplay.o)
      _queue_picture in IJKMediaFramework(ff_ffplay.o)
      _video_refresh_thread in IJKMediaFramework(ff_ffplay.o)
      _read_thread in IJKMediaFramework(ff_ffplay.o)
      _get_clock in IJKMediaFramework(ff_ffplay.o)
      _sync_clock_to_slave in IJKMediaFramework(ff_ffplay.o)
      ...
  "_avcodec_register_all", referenced from:
      _ffp_global_init in IJKMediaFramework(ff_ffplay.o)
  "_av_opt_set_defaults", referenced from:
      _ffp_create in IJKMediaFramework(ff_ffplay.o)
  "_avformat_new_stream", referenced from:
      _open_inner in IJKMediaFramework(ijklivehook.o)
  "_avformat_network_init", referenced from:
      _ffp_global_init in IJKMediaFramework(ff_ffplay.o)
  "_av_opt_set_double", referenced from:
      _sdl_audio_callback in IJKMediaFramework(ff_ffplay.o)
  "_av_get_profile_name", referenced from:
      _ijkmeta_set_avformat_context_l in IJKMediaFramework(ijkmeta.o)
  "_av_log_get_level", referenced from:
      _ffp_log_callback_brief in IJKMediaFramework(ff_ffplay.o)
      _ffp_log_callback_report in IJKMediaFramework(ff_ffplay.o)
  "_av_frame_alloc", referenced from:
      _ffp_video_thread in IJKMediaFramework(ff_ffplay.o)
      _frame_queue_init in IJKMediaFramework(ff_ffplay.o)
      _audio_thread in IJKMediaFramework(ff_ffplay.o)
      _SDL_VoutFFmpeg_CreateOverlay in IJKMediaFramework(ijksdl_vout_overlay_ffmpeg.o)
      _videotoolbox_async_decode_frame in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _videotoolbox_sync_decode_frame in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_av_log_format_line", referenced from:
      _ffp_log_callback_report in IJKMediaFramework(ff_ffplay.o)
  "_av_default_item_name", referenced from:
      _ijklivehook_class in IJKMediaFramework(ijklivehook.o)
      _async_context_class in IJKMediaFramework(ijkasync.o)
      _ijktcphook_context_class in IJKMediaFramework(ijkurlhook.o)
      _ijkhttphook_context_class in IJKMediaFramework(ijkurlhook.o)
      _ijkio_context_class in IJKMediaFramework(ijkio.o)
      _ijklongurl_context_class in IJKMediaFramework(ijklongurl.o)
      _ijksegment_context_class in IJKMediaFramework(ijksegment.o)
.....等100个错误

**Comment by 278956952** [comment]
我现在flutter 打ios包出现了同样问题，请问如何解决，急

**Comment by Qu000** [comment]
同问怎么解决

**Comment by mdddj** [comment]
2022年了,这种有办法解决吗

**Comment by 11101b** [comment]
我也碰到这个问题了，请问解决了吗

**Comment by RainyLave** [comment]
どうしたの？
