### ISSUE TITLE
请问，如果AVFormatContext *s；s->streams[i]->codecpar 这个指针为空一般来说是啥原因？

### ISSUE THREAD

**Issue by BruceLing** [bilibili/ijkplayer#4819]
![image](https://user-images.githubusercontent.com/19875335/62822971-f24f3100-bbbd-11e9-867a-f7565ebb68c1.png)

**Comment by BruceLing** [comment]
01-01 08:03:37.604 E/IJKMEDIA( 4220): BruceLing setup_find_stream_info_opts s->streams[0] = 0xdcc77600,s->streams[0]->codecpar = 0x0

**Comment by BruceLing** [comment]
av_log(NULL, AV_LOG_DEBUG, "BruceLing setup_find_stream_info_opts s->streams[%d] = %p,s->streams[%d]->codecpar = %p\n",i,s->streams[i],i,s->streams[i]->codecpar);

发现崩溃点是这个函数，然后如此添加打印。。。

**Comment by liangzs** [comment]
检测一下头文件，不同版本用的config.h不一样。导致了这个问题
