### ISSUE TITLE
android studio 1.4RC1编译有错

### ISSUE THREAD

**Issue by qazmoon** [Bilibili/ijkplayer#482]
出现
Error:Could not find property 'GPG_PASSWORD' on com.jfrog.bintray.gradle.BintrayExtension_Decorated@142ad2cd.

**Comment by bbcallen** [comment]
Define this property as a workaround in your local properties
```
# xxx could be anything
GPG_KEYID=xxx
GPG_PASSWORD=xxx
```

BTW: What's your gradle's version ?

**Comment by bbcallen** [comment]
Ah, I can reproduce this problem.
fixed: c97c8c190481602bc89a922b2812f810b548131b
