### ISSUE TITLE
android2.3.6设备没有画面，渲染失败

### ISSUE THREAD

**Issue by Android4MediaPlayer** [Bilibili/ijkplayer#483]
09-22 11:36:28.877: D/IJKMEIDA(18595): ANativeWindow_setBuffersGeometry: w=480, h=270, f=(0x4) => w=640, h=360, f=RV32(0x32335652)
09-22 11:36:28.877: E/Surface(18595): invalid token (identity=473)
09-22 11:36:28.877: E/Surface(18595): invalid token (identity=473)
09-22 11:36:28.877: E/Surface(18595): dequeueBuffer failed (No such device)
09-22 11:36:28.877: E/IJKMEIDA(18595): SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -1

**Comment by bbcallen** [comment]
Which device?

**Comment by Android4MediaPlayer** [comment]
@bbcallen, vivo S1

**Comment by bbcallen** [comment]
Fixed: 1c86a856eb5e1c813ef2923eebebfdd05d8c62a2

**Comment by Android4MediaPlayer** [comment]
but https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijksdl/android/android_nativewindow.c#L265, render_ret = -1

**Comment by bbcallen** [comment]
In sample, or in your own project?

**Comment by Android4MediaPlayer** [comment]
sample, render_ret = -1,but the video picture is OK.

**Comment by Android4MediaPlayer** [comment]
@bbcallen  why?
