### ISSUE TITLE
怎么播放本地m3u8?

### ISSUE THREAD

**Issue by jianlin00000** [bilibili/ijkplayer#4839]
本地m3u8文件内容如下：
`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:42561
#EXT-X-TARGETDURATION:6
#EXTINF:4.000,
http://ts.lemmovie.com/70a96575-9bb3-418d-95e0-cb45b7d4840a/huNan-238060.ts
#EXTINF:4.000,
http://ts.lemmovie.com/70a96575-9bb3-418d-95e0-cb45b7d4840a/huNan-238061.ts
#EXTINF:4.000,
http://ts.lemmovie.com/70a96575-9bb3-418d-95e0-cb45b7d4840a/huNan-238062.ts
#EXTINF:4.000,
http://ts.lemmovie.com/70a96575-9bb3-418d-95e0-cb45b7d4840a/huNan-238063.ts
#EXTINF:4.000,
http://ts.lemmovie.com/70a96575-9bb3-418d-95e0-cb45b7d4840a/huNan-238064.ts
#EXTINF:4.000,
http://ts.lemmovie.com/70a96575-9bb3-418d-95e0-cb45b7d4840a/huNan-238065.ts
#EXTINF:4.000,
http://ts.lemmovie.com/70a96575-9bb3-418d-95e0-cb45b7d4840a/huNan-238066.ts
#EXTINF:4.000,
http://ts.lemmovie.com/70a96575-9bb3-418d-95e0-cb45b7d4840a/huNan-238067.ts
#EXTINF:4.000,
http://ts.lemmovie.com/70a96575-9bb3-418d-95e0-cb45b7d4840a/huNan-238068.ts
#EXTINF:4.000,
http://ts.lemmovie.com/70a96575-9bb3-418d-95e0-cb45b7d4840a/huNan-238069.ts
#EXTINF:4.000,
http://ts.lemmovie.com/70a96575-9bb3-418d-95e0-cb45b7d4840a/huNan-238070.ts
#EXTINF:4.000,
http://ts.lemmovie.com/70a96575-9bb3-418d-95e0-cb45b7d4840a/huNan-238071.ts
#EXTINF:4.000,
http://ts.lemmovie.com/70a96575-9bb3-418d-95e0-cb45b7d4840a/huNan-238072.ts
#EXT-X-ENDLIST`

播放过程中报了如下错误日志：
`2019-08-30 18:15:33.499 32213-32398/com.zoe.playdemo W/IJKMEDIA: Failed to open segment of playlist 0
2019-08-30 18:15:33.499 32213-32398/com.zoe.playdemo E/IJKMEDIA: Error when loading first segment 'http://ts.lemmovie.com/70a96575-9bb3-418d-95e0-cb45b7d4840a/huNan-229050.ts'
2019-08-30 18:15:33.517 32213-32398/com.zoe.playdemo E/IJKMEDIA: /storage/emulated/0/test.m3u8: Invalid data found when processing input`

代码中已经加了如下配置设置了白名单：
`setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", "file,http,https,tcp,tls,udp,hls");`
请问怎么样才能解决这个问题？是否像一些人说的要去改ffmpeg的源码重新编译，如果是要改哪里。麻烦告知一下，谢谢！

**Comment by jianlin00000** [comment]
已解决

**Comment by zmobs** [comment]
大佬，怎么解决的。

**Comment by Equalzys** [comment]
> 已解决

大佬，能详细说下怎么解决的吗？

**Comment by zhufengweihai** [comment]
大佬到底怎么解决的啊
