### ISSUE TITLE
How to detect black screen at play time?

### ISSUE THREAD

**Issue by seaguest** [bilibili/ijkplayer#4840]
Hello,

I am wondering is it possible to know if current player is black screen at play time?
because some old model mobiles do not support hard-decode and get black screen, I need to know this case and switch to soft-decode.

**Comment by befovy** [comment]
I think it's better and more easy to solve this problem by check if there're some hardware decode API calling fail or return error.

**Comment by seaguest** [comment]
@befovy 

There is no exception returned by ijkplayer at play time, it would be more reasonable to be done on ijkplayer's side, but I think this is kind of image decode exception, maybe ijkplayer is not aware of this.

It would a solution if there is any system api to know this issue.

**Comment by befovy** [comment]
@seaguest  If ijkplayer is not aware of this, you can fork and make your version.
I don't know any system api to detect black screen.
