### ISSUE TITLE
seekto 有情况下执行不准确

### ISSUE THREAD

**Issue by MoYuFly** [bilibili/ijkplayer#4844]
seekbar 拖动时IjkMediaPlayer.seekTo 执行不准确，会在拖动后回调几秒至几十秒，如果是手指点击进度条则不存在这个问题。与seekbar执行 onProgressChanged此方法多次调用IjkMediaPlayer.seekTo有关系？

**Comment by befovy** [comment]
你不妨把 seekTo 的调用，放在回调  `public void onStopTrackingTouch(SeekBar seekBar)` 中再试一试，并分享一下结果。

**Comment by MoYuFly** [comment]
> 你不妨把 seekTo 的调用，放在回调 `public void onStopTrackingTouch(SeekBar seekBar)` 中再试一试，并分享一下结果。

private boolean isFromUser=false;
    private int progress;
    private void initListener(){
        seekbar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener() {
            @Override
            public void onProgressChanged(SeekBar seekBar, int i, boolean b) {
                isFromUser=b;
                if (b){
                    progress=i;
                    tv_progress.setText(FormatHelper.formatDuration(i));
                }
                Logger.e("onProgressChanged", b+"");
            }

            @Override
            public void onStartTrackingTouch(SeekBar seekBar) {
                Logger.e("onStartTrackingTouch", "开始拽");
            }

            @Override
            public void onStopTrackingTouch(SeekBar seekBar) {
                Logger.e("onStopTrackingTouch", "停止拽");
                if (isFromUser){
                    TheApp.instance.musicBindr.changeProgress(progress);
                }
            }
        });
    }
已经尝试，这样可以准确跳转进度，但是在进度条拖拽期间，音频仍在按原有进度播放，音频这样处理还好，视频不知道如何。

**Comment by befovy** [comment]
seekBar  starttrack的时候调用 pause？


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by MoYuFly** [comment]
> seekBar starttrack的时候调用 pause？
> 
> :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

可行。谢谢。
