### ISSUE TITLE
iOS 报错symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by qingwu126** [bilibili/ijkplayer#4855]
Undefined symbols for architecture arm64:
  "_SSL_shutdown", referenced from:
      _tls_close in IJKMediaFramework(tls_openssl.o)
  "_SSL_CTX_free", referenced from:
      _tls_close in IJKMediaFramework(tls_openssl.o)
  "_SSL_write", referenced from:
      _tls_write in IJKMediaFramework(tls_openssl.o)
  "_CRYPTO_get_locking_callback", referenced from:
      _ff_openssl_init in IJKMediaFramework(tls_openssl.o)
      _ff_openssl_deinit in IJKMediaFramework(tls_openssl.o)
  "_SSL_read", referenced from:
      _tls_read in IJKMediaFramework(tls_openssl.o)
  "_SSL_CTX_use_certificate_chain_file", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_SSL_CTX_ctrl", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_SSL_CTX_use_PrivateKey_file", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_BIO_clear_flags", referenced from:
      _url_bio_bwrite in IJKMediaFramework(tls_openssl.o)
      _url_bio_bread in IJKMediaFramework(tls_openssl.o)
      _url_bio_ctrl in IJKMediaFramework(tls_openssl.o)
  "_SSLv23_server_method", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_SSL_CTX_set_verify", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_SSL_accept", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_SSL_set_bio", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_SSLv23_client_method", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_SSL_library_init", referenced from:
      _ff_openssl_init in IJKMediaFramework(tls_openssl.o)
  "_CRYPTO_num_locks", referenced from:
      _ff_openssl_init in IJKMediaFramework(tls_openssl.o)
      _ff_openssl_deinit in IJKMediaFramework(tls_openssl.o)
  "_SSL_CTX_load_verify_locations", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_ERR_get_error", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
      _print_tls_error in IJKMediaFramework(tls_openssl.o)
  "_SSL_new", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_ERR_error_string", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
      _print_tls_error in IJKMediaFramework(tls_openssl.o)
  "_BIO_new", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_SSL_connect", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_SSL_free", referenced from:
      _tls_close in IJKMediaFramework(tls_openssl.o)
  "_SSL_CTX_new", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_SSL_load_error_strings", referenced from:
      _ff_openssl_init in IJKMediaFramework(tls_openssl.o)
  "_SSL_ctrl", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_CRYPTO_set_locking_callback", referenced from:
      _ff_openssl_init in IJKMediaFramework(tls_openssl.o)
      _ff_openssl_deinit in IJKMediaFramework(tls_openssl.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by qingwu126** [comment]
![image](https://user-images.githubusercontent.com/10303151/64583823-0e184380-d3c5-11e9-9f37-8fce9042201d.png)
这个需要如何处理？求指教。

**Comment by anuranBarman** [comment]
How did you solve this?
