### ISSUE TITLE
播放完后出现Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1)错误

### ISSUE THREAD

**Issue by toumubaoqiong** [Bilibili/ijkplayer#486]
android系统中，播放完成某个视频后在oncompleteListener之前出现Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 14747，是那什么原因造成的？

**Comment by Android4MediaPlayer** [comment]
机型，硬解还是软解，详细log

**Comment by toumubaoqiong** [comment]
我对视频AVpacket做了AES加密，然后在ijkplayer中做了解密，我追踪视频播放完后到ff_ffplay.c中read_thread（）中的  if ((!is->paused || completed) &&
            (!is->audio_st || (is->auddec.finished == is->audioq.serial && frame_queue_nb_remaining(&is->sampq) == 0)) &&
            (!is->video_st || (is->viddec.finished == is->videoq.serial && frame_queue_nb_remaining(&is->pictq) == 0))) {}语句没有执行，引起内存泄露，下面是加密视频播放时我打印的相关数据
![image](https://cloud.githubusercontent.com/assets/8606981/10040776/3e81f87e-6211-11e5-8533-3d61e818a374.png)

这是正常视频播放时我打印的数据
![image](https://cloud.githubusercontent.com/assets/8606981/10040779/4569a4ca-6211-11e5-9fe9-19e517d52bfa.png)

，发现问题好像是视频播放完成了，队列里面还有帧，以至于这句话执行不到，销毁不了相关资源，导致内存泄露。
我的想法：是不是经过ffmpeg中AES对AVpacket加密之后视频帧增加，以至于视频播放完了，队列中还存在一些没用的视频帧，程序没有识别到，然后报错。有没有可能通过别的途径来判断视频是否播放完成？我尝试ffp_get_current_position_l（）/1000==ffp_get_duration_l()/1000;来识别还是有问题。

**Comment by toumubaoqiong** [comment]
@Android4MediaPlayer 
发现经过ffmpeg中的aes加密之后，视频在播放完之后，存放帧的队列并没有清空：
解决过程：
对于非aes加密的视频还是用队列是否为空判断视频是否结束，对于aes加密的视频通过比较时间来判断，
ffp_get_current_position_l（）/ 1000 == ffp_get_duration_l() / 1000；后来发现视频播放完成时视频的视频的ffp_get_current_position_l和 ffp_get_duration_l()相差几秒，当然我测了很多视频最大相差2秒，因此我对时间比较做了一个修改，ffp_get_current_position_l（）/ 1000 >= ffp_get_duration_l() / 1000 - 2;这样做的结果是视频播放结束后不会出现错误，但是正常的aes视频会提前2秒结束，但是总体来说影响不是很大，方法有点很笨，但是是我现在能想到的最好的办法。

**Comment by Android4MediaPlayer** [comment]
你可以加个自定义buffer IO 协议，这个模块做两件事：下载你的AES加密数据，解密数据。那么ffmpeg从你这个模块读到的数据也是不是AES加密的数据了
