### ISSUE TITLE
切换视频时出现第一个未销毁存在于后台播放声音但是第二个已经开始播放了

### ISSUE THREAD

**Issue by kaizhou123** [bilibili/ijkplayer#4868]
播电视剧的时候销毁第一集的播放器 再初始化播第二集  播第三集的时候就出现播放失败然后出现这个通知  然后我释放掉重新初始化播放器  然后重新初始化就能播放 但是会出现两个声音 并打印glview 什么什么的
case IJKMPMovieFinishReasonPlaybackError:
            NSLog(@"playbackStateDidChange: 播放出现错误: %d\n", reason);
            self.state = KZPlayerStateFailed;
            [self stop];
            [self initPlayerWithModel:_playModel];
            
            break;

  怎么找也找不到 每次切换都会打印销毁
- (void)stop {
    
    if (self.player) {
        [self.player stop];
        [self.player shutdown];
        [self.player.view removeFromSuperview];
        [self removeMovieNotificationObservers];
        [self.timer invalidate];
        self.timer = nil;
        self.player = nil;
    }

    NSLog(@"视频播放器----%@",self.player.view);
    
}

我是这样销毁的

**Comment by befovy** [comment]
先调用一下静音呗，销毁慢点也没关系了。 @kaizhou123

**Comment by kaizhou123** [comment]
@befovy  我试试看可以不可以,因为不知道什么原因导致我控制器也不释放了 所以就算dissmiss了控制器 到主界面还是会在后台播放声音 就很尴尬

**Comment by kaizhou123** [comment]
@befovy  还是不行不是静音的问题 我重新更新了一下问题描述  是播放失败然后我立马又重新初始化然后就可能会出现这样子

**Comment by befovy** [comment]
@kaizhou123 更新的描述让我更糊涂了。没理解

**Comment by kaizhou123** [comment]
@befovy  就是我播放一个视频的时候 IJKMPMovieFinishReasonPlaybackError 报这个错 然后我重新初始化再播放 然后就出现两个声音在哪里放

**Comment by kaizhou123** [comment]
@befovy   已经解决了  原来是因为我控制器一直没释放导致切换的时候会连续调用两次初始化  谢谢啦
