### ISSUE TITLE
android的系统，在播过过程中，视频一直显示缓存中。

### ISSUE THREAD

**Issue by andyjmzheng** [Bilibili/ijkplayer#487]
@bbcallen 安卓的手机，在播放http://ssports.vod.smgbb.cn.cloudcdn.net/otv/vod/auto_bbf0913484a59baedb5d694236a45cc2.m3u8流的过程中。显示缓存。显示缓存后就不能继续播放了。有遇到类似的bug吗？
各位大神。有遇到的麻烦指导下。谢谢！着急期盼。

**Comment by Android4MediaPlayer** [comment]
你用VLC等其他播放器播放是怎样的？

**Comment by andyjmzheng** [comment]
@Android4MediaPlayer 我觉得应该和流没有关系。我在用vlc测试下。看看是不是也有播放过程中缓冲停止的问题。
因为我用别的流播放的时候。ijkplayer也是会出现播放过程中缓存。
谢谢@Android4MediaPlayer

**Comment by Android4MediaPlayer** [comment]
@bbcallen 这个是一个小概率BUG，突然我想起了遇到过一次频繁SEEK会出现了一直会buffering，然后再SEEK到别的地方又会恢复 @andyjmzheng 当出现这种情况的时候 你SEEK下试一下会恢复么？

**Comment by andyjmzheng** [comment]
这个不是小概率bug。是我每次都毕现的bug。当出现了缓存后。seek 也不管用。退出播放器再进入也不管用。只能在后台杀死ijkplayer。再次进入才可以正常。但是继续播放一会。依然会出现缓存。然后停止播放。@Android4MediaPlayer ,@bbcallen

**Comment by andyjmzheng** [comment]
用vlc 测试
http://ssports.vod.smgbb.cn.cloudcdn.net/otv/vod/auto_bbf0913484a59baedb5d694236a45cc2.m3u8 流。不会出现缓存停止的问题。

**Comment by andyjmzheng** [comment]
出现了缓存中。视频停止播放后，logcat的打印都没有了。。

**Comment by Android4MediaPlayer** [comment]
不过我没有出现这种情况 我只遇到过一次SEEK出现的情况 这个应该是你自己的流 既然必现你可以跟后台服务器一起查下，看后台是断流了还是客户端没发请求了 确认下

**Comment by andyjmzheng** [comment]
好的。谢谢！@Android4MediaPlayer 我再用别的流测试下。

**Comment by andyjmzheng** [comment]
用此流测试。也是会毕现缓冲后，停止播放。再次seek也是没有继续播放。
http://218.200.229.165:80/vod/video2/18/d54a67031d1a8ff31636e769fb66863d.m3u8。我再查下代码吧。谢谢！@Android4MediaPlayer

**Comment by Android4MediaPlayer** [comment]
@andyjmzheng 你把user-agent设置为浏览器的测试下

**Comment by andyjmzheng** [comment]
@Android4MediaPlayer ，没有明白你说的 user-agent 怎么设置？能详细告诉下吗？我才接触hls。不是很明白这些。谢谢！

**Comment by andyjmzheng** [comment]
@Android4MediaPlayer 。想问下。你的ijkplayer.so 这个库对应的代码是那个版本的？我用git更新的版本是最新的吗？谢谢！依旧解决播放过程中缓存的问题。分析好像是死锁了。
在函数packet_queue_get函数中。卡在了SDL_CondWait 这里了。。后续就没有任何打印了。

**Comment by Android4MediaPlayer** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/android/ijkplayer/ijkplayer-java/src/main/java/tv/danmaku/ijk/media/player/IjkMediaPlayer.java#L650 ,API:setOption(int category, String name, String value)

**Comment by Android4MediaPlayer** [comment]
跟bbc一样我也是代码控，喜欢用最新的~~~ 你换几台机器测试下，看看这个问题的发生概率

**Comment by andyjmzheng** [comment]
基本是每台机器都毕现的。你自己现在的版本是商用的吗？可以加你的QQ吗？想和你了解点问题。谢谢！

**Comment by andyjmzheng** [comment]
基本是每台机器都毕现的。你自己现在的版本是商用的吗？可以加你的QQ吗？想和你了解点问题。谢谢
@Android4MediaPlayer

**Comment by andyjmzheng** [comment]
@Android4MediaPlayer @bbcallen  这么集成的人都没有遇到我类似的问题。莫非是我的上层应用有问题？我不是搞java的，所以也不是很懂android的东西。郁闷。。。

**Comment by Android4MediaPlayer** [comment]
@andyjmzheng github这么大平台 有问题可以提出来，你试一下换个user-agent试一下

**Comment by andyjmzheng** [comment]
@Android4MediaPlayer 怎么换user-agent？我不是很了解。谢谢！

**Comment by Android4MediaPlayer** [comment]
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "user-agent", "xxx");

**Comment by andyjmzheng** [comment]
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ IjkMediaPlayer_native_init
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ IjkMediaPlayer_native_setup
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample I/IJKMEDIA﹕ av_version_info: ff2.8--ijk0.3.3--dev0.3.3--rc1
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ffpipeline_create_from_android()
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_set_inject_opaque(0x1d2004c2)
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_set_option_int(ijkinject-opaque, 488637634)
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_set_option_int()=void
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_set_inject_opaque()=void
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_android_set_mediacodec_select_callback()
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ffpipeline_set_mediacodec_select_callback
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_android_set_mediacodec_select_callback()=void
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ IjkMediaPlayer_setOptionLong
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_set_option_int(overlay-format, 842225234)
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_set_option_int()=void
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ IjkMediaPlayer_setOptionLong
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_set_option_int(framedrop, 12)
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_set_option_int()=void
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ IjkMediaPlayer_setOptionLong
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_set_option_int(http-detect-range-support, 0)
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_set_option_int()=void
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample I/VideoView﹕ mUri.getPath:http://ssports.vod.smgbb.cn.cloudcdn.net/otv/vod/auto_bbf0913484a59baedb5d694236a45cc2.m3u8
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ IjkMediaPlayer_setOptionLong
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_set_option_int(skip_loop_filter, 48)
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_set_option_int()=void
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ IjkMediaPlayer_setOptionLong
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_set_option_int(get-av-frame-timeout, 3000000)
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_set_option_int()=void
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ IjkMediaPlayer_setOptionLong
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_set_option_int(mediacodec, 1)
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_set_option_int()=void
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ IjkMediaPlayer_setOptionLong
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_set_option_int(start-on-prepared, 1)
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_set_option_int()=void
09-24 11:06:26.599  21077-21077/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ IjkMediaPlayer_setDataSourceA

@Android4MediaPlayer  这个是现在代码的打印信息。
不是user-agent

**Comment by andyjmzheng** [comment]
09-24 11:34:43.539    1811-2017/tv.danmaku.ijk.media.sample I/IJKMEDIA﹕ SDL_RunThread: [2017] ff_msg_loop
09-24 11:34:43.539    1811-2017/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ message_loop
09-24 11:34:43.539    1811-1811/tv.danmaku.ijk.media.sample I/IJKMEDIA﹕ player-opts : overlay-format               = 842225234
09-24 11:34:43.539    1811-2017/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ FFP_MSG_FLUSH:
09-24 11:34:43.539    1811-1811/tv.danmaku.ijk.media.sample I/IJKMEDIA﹕ player-opts : framedrop                    = 12
09-24 11:34:43.539    1811-1811/tv.danmaku.ijk.media.sample I/IJKMEDIA﹕ player-opts : get-av-frame-timeout         = 3000000
09-24 11:34:43.539    1811-1811/tv.danmaku.ijk.media.sample I/IJKMEDIA﹕ player-opts : mediacodec                   = 1
09-24 11:34:43.539    1811-1811/tv.danmaku.ijk.media.sample I/IJKMEDIA﹕ player-opts : start-on-prepared            = 1
09-24 11:34:43.539    1811-1811/tv.danmaku.ijk.media.sample I/IJKMEDIA﹕ format-opts : ijkinject-opaque             = 488637634
09-24 11:34:43.539    1811-1811/tv.danmaku.ijk.media.sample I/IJKMEDIA﹕ format-opts : http-detect-range-support    = 0
09-24 11:34:43.539    1811-1811/tv.danmaku.ijk.media.sample I/IJKMEDIA﹕ codec-opts  : skip_loop_filter             = 48
09-24 11:34:43.539    1811-1811/tv.danmaku.ijk.media.sample I/IJKMEDIA﹕ ===================
09-24 11:34:43.549    1811-2021/tv.danmaku.ijk.media.sample I/IJKMEDIA﹕ SDL_RunThread: [2021] ff_vout
09-24 11:34:43.549    1811-2021/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ffpipenode_create_video_output_from_android_mediacodec()
09-24 11:34:43.549    1811-1811/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ ijkmp_prepare_async()=0
09-24 11:34:43.549    1811-2028/tv.danmaku.ijk.media.sample I/IJKMEDIA﹕ SDL_RunThread: [2028] ff_read
09-24 11:34:43.559    1811-2028/tv.danmaku.ijk.media.sample E/IJKMEDIA﹕ ffurl_connect
09-24 11:34:43.559    1811-2028/tv.danmaku.ijk.media.sample I/IJKMEDIA﹕ http_open http://ssports.vod.smgbb.cn.cloudcdn.net/otv/vod/auto_bbf0913484a59baedb5d694236a45cc2.m3u8
09-24 11:34:43.559    1811-2028/tv.danmaku.ijk.media.sample E/IJKMEDIA﹕ ffurl_connect
09-24 11:34:43.579    1811-2028/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ request: GET /otv/vod/auto_bbf0913484a59baedb5d694236a45cc2.m3u8 HTTP/1.1
    User-Agent: Lavf/56.40.101
    Accept: */*
    Range: bytes=0-
    Connection: close
    Host: ssports.vod.smgbb.cn.cloudcdn.net
    Icy-MetaData: 1
09-24 11:34:43.589    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='HTTP/1.1 200 OK'
09-24 11:34:43.589    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ http_code=200
09-24 11:34:43.589    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='Date: Thu, 24 Sep 2015 03:34:43 GMT'
09-24 11:34:43.589    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='Content-Length: 344'
09-24 11:34:43.589    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='Accept-Ranges: bytes'
09-24 11:34:43.589    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='Content-Type: application/octet-stream'
09-24 11:34:43.589    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='Last-Modified: Wed, 16 Sep 2015 10:39:58 GMT'
09-24 11:34:43.589    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0'
09-24 11:34:43.589    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='Connection: Close'
09-24 11:34:43.589    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='ETag: "55f946fe-158"'
09-24 11:34:43.589    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='Server: fastmirror 2015-05-14_2015-05-14'
09-24 11:34:43.589    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='Fw-Via: DISK HIT from CTL_HA_094_142.fcd, Configured MISS from CTL_HA_094_141.fcd, DISK HIT from 124.192.143.186'
09-24 11:34:43.589    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header=''
09-24 11:34:43.589    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ Probing hls,applehttp score:100 size:344
09-24 11:34:43.589    1811-2028/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ Format hls,applehttp probed with size=2048 and score=100
09-24 11:34:43.589    1811-2028/tv.danmaku.ijk.media.sample E/IJKMEDIA﹕ ffurl_connect
09-24 11:34:43.589    1811-2028/tv.danmaku.ijk.media.sample I/IJKMEDIA﹕ http_open http://ssports.vod.smgbb.cn.cloudcdn.net/otv/vod/600k/bbf0913484a59baedb5d694236a45cc2_600k_list.m3u8
09-24 11:34:43.589    1811-2028/tv.danmaku.ijk.media.sample E/IJKMEDIA﹕ ffurl_connect
09-24 11:34:43.599    1811-2028/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ request: GET /otv/vod/600k/bbf0913484a59baedb5d694236a45cc2_600k_list.m3u8 HTTP/1.1
    User-Agent: Lavf/56.40.101
    Accept: */*
    Connection: close
    Host: ssports.vod.smgbb.cn.cloudcdn.net
    Icy-MetaData: 1
09-24 11:34:43.609    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='HTTP/1.1 200 OK'
09-24 11:34:43.609    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ http_code=200
09-24 11:34:43.609    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='Date: Thu, 24 Sep 2015 03:34:43 GMT'
09-24 11:34:43.609    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='Content-Length: 45858'
09-24 11:34:43.609    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='Accept-Ranges: bytes'
09-24 11:34:43.609    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='Content-Type: application/octet-stream'
09-24 11:34:43.609    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='Last-Modified: Wed, 16 Sep 2015 10:12:35 GMT'
09-24 11:34:43.609    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0'
09-24 11:34:43.609    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='Connection: Close'
09-24 11:34:43.609    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='ETag: "55f94093-b322"'
09-24 11:34:43.609    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='Server: fastmirror 2015-05-14_2015-05-14'
09-24 11:34:43.609    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header='Fw-Via: DISK HIT from CTL_HA_094_142.fcd, DISK HIT from 124.192.143.186'
09-24 11:34:43.609    1811-2028/tv.danmaku.ijk.media.sample V/IJKMEDIA﹕ header=''
09-24 11:34:43.629    1811-2028/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ Statistics: 45858 bytes read, 0 seeks
09-24 11:34:43.629    1811-2028/tv.danmaku.ijk.media.sample E/IJKMEDIA﹕ ffurl_connect
09-24 11:34:43.629    1811-2028/tv.danmaku.ijk.media.sample I/IJKMEDIA﹕ http_open http://ssports.vod.smgbb.cn.cloudcdn.net/otv/vod/1200k/bbf0913484a59baedb5d694236a45cc2_1200k_list.m3u8
09-24 11:34:43.629    1811-2028/tv.danmaku.ijk.media.sample E/IJKMEDIA﹕ ffurl_connect
09-24 11:34:43.639    1811-2028/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ request: GET /otv/vod/1200k/bbf0913484a59baedb5d694236a45cc2_1200k_list.m3u8 HTTP/1.1
    User-Agent: Lavf/56.40.101
    Accept: */*
    Connection: close
    Host: ssports.vod.smgbb.cn.cloudcdn.net
    Icy-MetaData: 1
09-24 11:34:43.649    1811-1811/tv.danmaku.ijk.media.sample I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@42461820 time:174543932

@Android4MediaPlayer  这个应该本来就是user-agent吧？

**Comment by Android4MediaPlayer** [comment]
现在是默认的Lavf/56.40.101，换个Android浏览器的如Mozilla/5.0 (Linux; U; Android)
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "user-agent", "Mozilla/5.0 (Linux; U; Android)");

**Comment by andyjmzheng** [comment]
Lavf/56.40.101 和 Mozilla/5.0 (Linux; U; Android) 区别是什么呢？ @Android4MediaPlayer 
谢谢！
另外，我在代码中没有找到对Lavf/56.40.101 的设置。可能是我的java的代码和你的不一样的原因吧。
我想和你确认一个问题。你现在除了java的东西和github上的不一样。另外就是ffmpeg的库是用的2.7版本的。ijkplayer 和sdl的 都是和github上一样的最新版本？？
我现在想确定下是我的java的代码有问题还是底层的原因。

谢谢！希望回复。。。

**Comment by Android4MediaPlayer** [comment]
Lavf/56.40.101估计是ffmpeg里面的，我担心有服务器对UA有限制，先排除这个，都一样的啊，共同把这个开源项目做下去，希望能贡献点东西。

**Comment by andyjmzheng** [comment]
你那里用的是 Lavf/56.40.101  还是   Mozilla/5.0 (Linux; U; Android)？

**Comment by andyjmzheng** [comment]
ijkplayer这个开元的东西。视频效果还是很不错的。。我目前也是在调研这个东西。后续可能会用在我们的项目中。但是现在播放一段时间就缓存导致暂停。

**Comment by andyjmzheng** [comment]
@Android4MediaPlayer  Lavf/56.40.101估计是ffmpeg里面的，我担心有服务器对UA有限制，先排除这个。
 你说的服务器UA是什么？
我好和服务器的人联系。确认。
谢谢！

**Comment by andyjmzheng** [comment]
@Android4MediaPlayer  我问了下我们服务器的人。他说服务器的ua 是SSTBall/1 CFNetwork/711.5.6 Darwin/14.0.0 ？？？

**Comment by Android4MediaPlayer** [comment]
在ijkvideoview里加入这个代码，把服务器需要的ua设置下看看： ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "user_agent", "SSTBall/1 CFNetwork/711.5.6 Darwin/14.0.0");

**Comment by andyjmzheng** [comment]
我想问下。如果我的US是Lavf/56.40.101 服务器的US是SSTBall/1 CFNetwork/711.5.6 Darwin/14.0.0。这样会有什么冲突吗？会导致什么问题呢？麻烦指教下。谢谢！

**Comment by andyjmzheng** [comment]
我想问下。如果我的US是Lavf/56.40.101 服务器的US是SSTBall/1 CFNetwork/711.5.6 Darwin/14.0.0。这样会有什么冲突吗？会导致什么问题呢？麻烦指教下。谢谢！@Android4MediaPlayer

**Comment by Android4MediaPlayer** [comment]
有的用这个做防盗链 UA错了不给流了，或者隔断时间中断流

**Comment by andyjmzheng** [comment]
哦。点播也有防盗链一说吗？？

**Comment by andyjmzheng** [comment]
哦。点播也有防盗链一说吗？？ @Android4MediaPlayer

**Comment by Android4MediaPlayer** [comment]
这个问你服务器的同事就很清楚了

**Comment by andyjmzheng** [comment]
@Android4MediaPlayer 我问了我们服务器的同事。他和我说点播的视频没有防盗链。
奇怪了。。。还是没有找到问题的原因。。

**Comment by andyjmzheng** [comment]
@Android4MediaPlayer 我已经把user-agent设置成了Mozilla/5.0 (Linux; U; Android) 还是会出缓存暂停的问题。现在我想请教的问题是。我从git上拿下来的java部分的代码。怎么编译出来的apk。没有能播放视频的部分。是我编译的哪里有问题吗、？目前我是自己写了一个输入URL的页面。然后去播放的。。
麻烦回复下。谢谢！

**Comment by andyjmzheng** [comment]
cdn没有ua，都是透出的请求的。所以不会是ua导致这问题的。
是的，服务端没有ua
 以上是我们服务器的人给的回复。郁闷。他说没有ua
@Android4MediaPlayer
