### ISSUE TITLE
播放器seek问题，断网后在缓存范围内seek不起作用

### ISSUE THREAD

**Issue by playererer** [Bilibili/ijkplayer#488]
我用ijkplayer播http流的时候，播放器会有缓存，网络好的时候seek正常，但是网络断掉后，在缓存内seek，seek不起作用了，还是会回到seek之前的位置播放，请问一下这个问题该怎么解决？谢谢！

**Comment by playererer** [comment]
这个应该是IO层没有缓存，断网后seek获取不到数据，导致seek失败，IO层做缓存有知道怎么弄的吗？

**Comment by Android4MediaPlayer** [comment]
哗哩哗哩动画 SEEK是好的 @bbcallen  有啥不一样的改动？

**Comment by bbcallen** [comment]
Sometimes, we use android.media.MediaPlayer in bilibili.

**Comment by Android4MediaPlayer** [comment]
播放的时候会显示当前用什么播放器的，显示是ijkmedia

**Comment by Android4MediaPlayer** [comment]
@bbcallen
