### ISSUE TITLE
ios ijkplayer的demo无法播放加密的m3u8视频

### ISSUE THREAD

**Issue by spiritbuild** [bilibili/ijkplayer#4899]
播放的地址是这个:https://vod-hls.justeasy.cn/asset/ab18dcf05cd416c377a799d51c3f14f5/play_video/b5eba82f68904a6cadd2456e64ef7d94/index.m3u8?auth_info=FlmWqQWyqvcjp2lPy+5eaJIzZk+qwxI0bU/9en0FvGvaf0fky3wgwqsBeMqN+1sV4+6064KGKs/aPhhrayzWk2Et58ESPWOmVb1Fqmicc+4Gw7VBlQbsIhbMadgrw5lgJelgzOc+c56J+QysBIMxvA==.33653464333739356133343735656534

**Comment by spiritbuild** [comment]
xcode 日志是:
av_version_info: ff3.4--ijk0.8.7--20180103--001
ijk_version_info: 
ijkmp_set_inject_opaque(0x280c8cfa0)
ijkmp_set_inject_opaque()=void
ijkmp_set_ijkio_inject_opaque(0x280c8cfa0)
ijkmp_set_ijkio_inject_opaque()=void
2019-11-12 13:28:00.581636+0800 IJKMediaDemo[12545:3402374] OK setup GL
ijkmp_ios_set_view(glView=0x10921a6a0)
ijkmp_ios_set_view(glView=0x10921a6a0)=void
2019-11-12 13:28:00.585003+0800 IJKMediaDemo[12545:3402374] invalidateRenderBuffer
2019-11-12 13:28:00.585207+0800 IJKMediaDemo[12545:3403829] IJKSDLGLView: setupDisplay not ready
ijkmp_set_data_source(url="https://vod-hls.justeasy.cn/asset/ab18dcf05cd416c377a799d51c3f14f5/play_video/b5eba82f68904a6cadd2456e64ef7d94/index.m3u8?auth_info=FlmWqQWyqvcjp2lPy+5eaJIzZk+qwxI0bU/9en0FvGvaf0fky3wgwqsBeMqN+1sV4+6064KGKs/aPhhrayzWk2Et58ESPWOmVb1Fqmicc+4Gw7VBlQbsIhbMadgrw5lgJelgzOc+c56J+QysBIMxvA==.33653464333739356133343735656534")
ijkmp_set_data_source(url="https://vod-hls.justeasy.cn/asset/ab18dcf05cd416c377a799d51c3f14f5/play_video/b5eba82f68904a6cadd2456e64ef7d94/index.m3u8?auth_info=FlmWqQWyqvcjp2lPy+5eaJIzZk+qwxI0bU/9en0FvGvaf0fky3wgwqsBeMqN+1sV4+6064KGKs/aPhhrayzWk2Et58ESPWOmVb1Fqmicc+4Gw7VBlQbsIhbMadgrw5lgJelgzOc+c56J+QysBIMxvA==.33653464333739356133343735656534")=0
ijkmp_prepare_async()
===== versions =====
[FFPlayer @ 0x10a007c00] ijkplayer    : 
[FFPlayer @ 0x10a007c00] FFmpeg       : ff3.4--ijk0.8.7--20180103--001
[FFPlayer @ 0x10a007c00] libavutil    : 55.78.100
[FFPlayer @ 0x10a007c00] libavcodec   : 57.107.100
[FFPlayer @ 0x10a007c00] libavformat  : 57.83.100
[FFPlayer @ 0x10a007c00] libswscale   : 4.8.100
[FFPlayer @ 0x10a007c00] libswresample: 2.9.100
===== options =====
[FFPlayer @ 0x10a007c00] player-opts : video-pictq-size             = 3
[FFPlayer @ 0x10a007c00] player-opts : overlay-format               = fcc-_es2
[FFPlayer @ 0x10a007c00] player-opts : max-fps                      = 30
[FFPlayer @ 0x10a007c00] player-opts : framedrop                    = 0
[FFPlayer @ 0x10a007c00] player-opts : videotoolbox-max-frame-width = 960
[FFPlayer @ 0x10a007c00] player-opts : videotoolbox                 = 0
[FFPlayer @ 0x10a007c00] player-opts : start-on-prepared            = 1
[FFPlayer @ 0x10a007c00] format-opts : ijkapplication               = 4448117888
[FFPlayer @ 0x10a007c00] format-opts : ijkiomanager                 = 4448166368
[FFPlayer @ 0x10a007c00] format-opts : user-agent                   = ijkplayer
[FFPlayer @ 0x10a007c00] format-opts : auto_convert                 = 0
[FFPlayer @ 0x10a007c00] format-opts : timeout                      = 30000000
[FFPlayer @ 0x10a007c00] format-opts : reconnect                    = 1
[FFPlayer @ 0x10a007c00] format-opts : safe                         = 0
===================
ijkmp_prepare_async()=0
[NULL @ 0x106831000] Opening 'https://vod-hls.justeasy.cn/asset/ab18dcf05cd416c377a799d51c3f14f5/play_video/b5eba82f68904a6cadd2456e64ef7d94/index.m3u8?auth_info=FlmWqQWyqvcjp2lPy+5eaJIzZk+qwxI0bU/9en0FvGvaf0fky3wgwqsBeMqN+1sV4+6064KGKs/aPhhrayzWk2Et58ESPWOmVb1Fqmicc+4Gw7VBlQbsIhbMadgrw5lgJelgzOc+c56J+QysBIMxvA==.33653464333739356133343735656534' for reading
https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
https://vod-hls.justeasy.cn/asset/ab18dcf05cd416c377a799d51c3f14f5/play_video/b5eba82f68904a6cadd2456e64ef7d94/index.m3u8?auth_info=FlmWqQWyqvcjp2lPy+5eaJIzZk+qwxI0bU/9en0FvGvaf0fky3wgwqsBeMqN+1sV4+6064KGKs/aPhhrayzWk2Et58ESPWOmVb1Fqmicc+4Gw7VBlQbsIhbMadgrw5lgJelgzOc+c56J+QysBIMxvA==.33653464333739356133343735656534: Protocol not found
2019-11-12 13:28:00.600767+0800 IJKMediaDemo[12545:3402374] invalidateRenderBuffer
2019-11-12 13:28:00.600933+0800 IJKMediaDemo[12545:3403829] IJKSDLGLView: setupDisplay not ready
2019-11-12 13:28:00.616602+0800 IJKMediaDemo[12545:3402374] FFP_MSG_ERROR: 0
2019-11-12 13:28:00.616896+0800 IJKMediaDemo[12545:3402374] IJKMPMoviePlayBackStateDidChange 2: paused
2019-11-12 13:28:00.616940+0800 IJKMediaDemo[12545:3402374] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1

**Comment by spiritbuild** [comment]
xcode的日志是:
av_version_info: ff3.4--ijk0.8.7--20180103--001
ijk_version_info: 
ijkmp_set_inject_opaque(0x280c8cfa0)
ijkmp_set_inject_opaque()=void
ijkmp_set_ijkio_inject_opaque(0x280c8cfa0)
ijkmp_set_ijkio_inject_opaque()=void
2019-11-12 13:28:00.581636+0800 IJKMediaDemo[12545:3402374] OK setup GL
ijkmp_ios_set_view(glView=0x10921a6a0)
ijkmp_ios_set_view(glView=0x10921a6a0)=void
2019-11-12 13:28:00.585003+0800 IJKMediaDemo[12545:3402374] invalidateRenderBuffer
2019-11-12 13:28:00.585207+0800 IJKMediaDemo[12545:3403829] IJKSDLGLView: setupDisplay not ready
ijkmp_set_data_source(url="https://vod-hls.justeasy.cn/asset/ab18dcf05cd416c377a799d51c3f14f5/play_video/b5eba82f68904a6cadd2456e64ef7d94/index.m3u8?auth_info=FlmWqQWyqvcjp2lPy+5eaJIzZk+qwxI0bU/9en0FvGvaf0fky3wgwqsBeMqN+1sV4+6064KGKs/aPhhrayzWk2Et58ESPWOmVb1Fqmicc+4Gw7VBlQbsIhbMadgrw5lgJelgzOc+c56J+QysBIMxvA==.33653464333739356133343735656534")
ijkmp_set_data_source(url="https://vod-hls.justeasy.cn/asset/ab18dcf05cd416c377a799d51c3f14f5/play_video/b5eba82f68904a6cadd2456e64ef7d94/index.m3u8?auth_info=FlmWqQWyqvcjp2lPy+5eaJIzZk+qwxI0bU/9en0FvGvaf0fky3wgwqsBeMqN+1sV4+6064KGKs/aPhhrayzWk2Et58ESPWOmVb1Fqmicc+4Gw7VBlQbsIhbMadgrw5lgJelgzOc+c56J+QysBIMxvA==.33653464333739356133343735656534")=0
ijkmp_prepare_async()
===== versions =====
[FFPlayer @ 0x10a007c00] ijkplayer    : 
[FFPlayer @ 0x10a007c00] FFmpeg       : ff3.4--ijk0.8.7--20180103--001
[FFPlayer @ 0x10a007c00] libavutil    : 55.78.100
[FFPlayer @ 0x10a007c00] libavcodec   : 57.107.100
[FFPlayer @ 0x10a007c00] libavformat  : 57.83.100
[FFPlayer @ 0x10a007c00] libswscale   : 4.8.100
[FFPlayer @ 0x10a007c00] libswresample: 2.9.100
===== options =====
[FFPlayer @ 0x10a007c00] player-opts : video-pictq-size             = 3
[FFPlayer @ 0x10a007c00] player-opts : overlay-format               = fcc-_es2
[FFPlayer @ 0x10a007c00] player-opts : max-fps                      = 30
[FFPlayer @ 0x10a007c00] player-opts : framedrop                    = 0
[FFPlayer @ 0x10a007c00] player-opts : videotoolbox-max-frame-width = 960
[FFPlayer @ 0x10a007c00] player-opts : videotoolbox                 = 0
[FFPlayer @ 0x10a007c00] player-opts : start-on-prepared            = 1
[FFPlayer @ 0x10a007c00] format-opts : ijkapplication               = 4448117888
[FFPlayer @ 0x10a007c00] format-opts : ijkiomanager                 = 4448166368
[FFPlayer @ 0x10a007c00] format-opts : user-agent                   = ijkplayer
[FFPlayer @ 0x10a007c00] format-opts : auto_convert                 = 0
[FFPlayer @ 0x10a007c00] format-opts : timeout                      = 30000000
[FFPlayer @ 0x10a007c00] format-opts : reconnect                    = 1
[FFPlayer @ 0x10a007c00] format-opts : safe                         = 0
===================
ijkmp_prepare_async()=0
[NULL @ 0x106831000] Opening 'https://vod-hls.justeasy.cn/asset/ab18dcf05cd416c377a799d51c3f14f5/play_video/b5eba82f68904a6cadd2456e64ef7d94/index.m3u8?auth_info=FlmWqQWyqvcjp2lPy+5eaJIzZk+qwxI0bU/9en0FvGvaf0fky3wgwqsBeMqN+1sV4+6064KGKs/aPhhrayzWk2Et58ESPWOmVb1Fqmicc+4Gw7VBlQbsIhbMadgrw5lgJelgzOc+c56J+QysBIMxvA==.33653464333739356133343735656534' for reading
https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
https://vod-hls.justeasy.cn/asset/ab18dcf05cd416c377a799d51c3f14f5/play_video/b5eba82f68904a6cadd2456e64ef7d94/index.m3u8?auth_info=FlmWqQWyqvcjp2lPy+5eaJIzZk+qwxI0bU/9en0FvGvaf0fky3wgwqsBeMqN+1sV4+6064KGKs/aPhhrayzWk2Et58ESPWOmVb1Fqmicc+4Gw7VBlQbsIhbMadgrw5lgJelgzOc+c56J+QysBIMxvA==.33653464333739356133343735656534: Protocol not found
2019-11-12 13:28:00.600767+0800 IJKMediaDemo[12545:3402374] invalidateRenderBuffer
2019-11-12 13:28:00.600933+0800 IJKMediaDemo[12545:3403829] IJKSDLGLView: setupDisplay not ready
2019-11-12 13:28:00.616602+0800 IJKMediaDemo[12545:3402374] FFP_MSG_ERROR: 0
2019-11-12 13:28:00.616896+0800 IJKMediaDemo[12545:3402374] IJKMPMoviePlayBackStateDidChange 2: paused
2019-11-12 13:28:00.616940+0800 IJKMediaDemo[12545:3402374] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1

**Comment by chenzh2017** [comment]
https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
上面这个日志已经提示你了，不支持https，你需要执行以下init-android-openssl.sh，然后在android/contrib目录下执行下compile-openssl.sh

**Comment by chenzh2017** [comment]
sorry，说错了，我这边是安卓的，ios的应该也是类似

**Comment by spiritbuild** [comment]
> sorry，说错了，我这边是安卓的，ios的应该也是类似

ok,编译了OpenSSL 已解决了~
