### ISSUE TITLE
分段视频

### ISSUE THREAD

**Issue by asawalker** [Bilibili/ijkplayer#490]
ijkplayer 是否支持分段视频的播放？

**Comment by Android4MediaPlayer** [comment]
把concat协议编译进ffmpeg就可以了

**Comment by Android4MediaPlayer** [comment]
If you prefer more codec/format
cd config
rm module.sh
ln -s module-default.sh module.sh
cd android/contrib
# cd ios
sh compile-ffmpeg clean

**Comment by leown** [comment]
请问  concat协议是可以实现多个视频无缝切换播放吗？

**Comment by Android4MediaPlayer** [comment]
可以的，但是要求严格，编码需一样

**Comment by leown** [comment]
能大概说下 要如何实现么？

**Comment by Zard1096** [comment]
https://ffmpeg.org/ffmpeg-formats.html#Syntax
#211 #474 #289

**Comment by howhy** [comment]
http://youku.cdn11-okzy.com/share/571e646d4ea4d46a8fde33d07167efe5 这样的视频如何播放 错误E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
