### ISSUE TITLE
各位大佬，rtsp，在小米5手机上录屏闪退，求指点

### ISSUE THREAD

**Issue by Dreamskya** [bilibili/ijkplayer#4907]
各位大佬，请教下，在小米5手机上（高通骁龙820顶级处理器），进行rtsp播放，且录屏会出现闪退。测试中，发现预览有一些延迟，录屏就不会闪退，越流畅的画面，点击录屏功能，就闪退了。这是指小米5手机上的表现。在红米note4和荣耀10，小米8手机上测试，录屏没有异常。

A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc in tid 2275 (Thread-3)
11-14 09:18:43.285 2755-2755/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-14 09:18:43.285 2755-2755/? A/DEBUG: Build fingerprint: 'Xiaomi/gemini/gemini:8.0.0/OPR1.170623.032/V10.2.1.0.OAACNXM:user/release-keys'
11-14 09:18:43.285 2755-2755/? A/DEBUG: Revision: '0'
11-14 09:18:43.285 2755-2755/? A/DEBUG: ABI: 'arm64'
11-14 09:18:43.285 2755-2755/? A/DEBUG: pid: 2221, tid: 2275, name: Thread-3  >>> com.dream.ijk <<<
11-14 09:18:43.285 2755-2755/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc
11-14 09:18:43.285 2755-2755/? A/DEBUG: Cause: null pointer dereference
11-14 09:18:43.285 2755-2755/? A/DEBUG:     x0   00000071e59ece80  x1   000000000000000c  x2   0000000000000000  x3   0000000000000000
11-14 09:18:43.285 2755-2755/? A/DEBUG:     x4   00000071e59ece98  x5   0000000000000000  x6   6d2e6b0077656900  x7   80696577806b2e6d
11-14 09:18:43.285 2755-2755/? A/DEBUG:     x8   96988749beb03993  x9   96988749beb03993  x10  0000000000000001  x11  0000000000000000
11-14 09:18:43.285 2755-2755/? A/DEBUG:     x12  0000000000001f94  x13  00000000000077c0  x14  000000000000000d  x15  aaaaaaaaaaaaaaab
11-14 09:18:43.286 2755-2755/? A/DEBUG:     x16  00000071eb4dfc30  x17  0000007207504bb0  x18  00000071e580ca10  x19  00000071e59ece80
11-14 09:18:43.286 2755-2755/? A/DEBUG:     x20  0000000000000000  x21  00000071ea3143c8  x22  00000071eaaae000  x23  0000000000000000
11-14 09:18:43.286 2755-2755/? A/DEBUG:     x24  0000000000000000  x25  0000000000000000  x26  0000000000000008  x27  00000071eaaafba8
11-14 09:18:43.286 2755-2755/? A/DEBUG:     x28  0000000000000009  x29  00000071ea314290  x30  00000071eb3d6c90
11-14 09:18:43.286 2755-2755/? A/DEBUG:     sp   00000071ea314250  pc   00000071eb3d6cac  pstate 0000000020000000
11-14 09:18:43.287 2755-2755/? A/DEBUG: backtrace:
11-14 09:18:43.287 2755-2755/? A/DEBUG:     #00 pc 0000000000282cac  /data/app/com.dream.ijk-vU-O52J-6fbx7M1epJqZeQ==/lib/arm64/libijkffmpeg.so (av_buffer_ref+48)
11-14 09:18:43.287 2755-2755/? A/DEBUG:     #01 pc 0000000000282c8c  /data/app/com.dream.ijk-vU-O52J-6fbx7M1epJqZeQ==/lib/arm64/libijkffmpeg.so (av_buffer_ref+16)
11-14 09:18:44.424 2755-2755/? E/crash_dump64: cannot open libmiuindbg.so: No such file or directory
11-14 09:18:44.427 1080-1080/? E//system/bin/tombstoned: Tombstone written to: /data/tombstones//tombstone_02
11-14 09:18:44.471 623-623/? E/lowmemorykiller: Error writing /proc/2221/oom_score_adj; errno=22

**Comment by JzwOnly** [comment]
@Dreamskya 请问这个问题解决了吗 关于录屏的  av_buffer_ref崩溃
