### ISSUE TITLE
k0.8.8添加录屏功能部分手机出现异常

### ISSUE THREAD

**Issue by Dreamskya** [bilibili/ijkplayer#4913]
您好，作者，使用k0.8.8添加录屏功能，在小米5手机上会出现闪退，在K0.8.4版本上添加录屏功能，小米5手机上不会闪退。部分手机不适用，会出现以下异常。大佬，请指点下，修改方向。
录屏功能，参考这个博客：https://github.com/fengchuiyeluo/ijkplayer/commit/68eb8991b67b75c9ce8b79679784753cdfec4e02

录屏闪退异常信息：
ijk A/libc: Fatal signal 11 (SIGSEGV), code 0, fault addr 0x298e0000130c in tid 5068 (ff_read)
11-20 20:31:52.737 5175-5175/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-20 20:31:52.737 5175-5175/? A/DEBUG: Build fingerprint: 'Xiaomi/gemini/gemini:8.0.0/OPR1.170623.032/V10.2.1.0.OAACNXM:user/release-keys'
11-20 20:31:52.737 5175-5175/? A/DEBUG: Revision: '0'
11-20 20:31:52.737 5175-5175/? A/DEBUG: ABI: 'arm64'
11-20 20:31:52.737 5175-5175/? A/DEBUG: pid: 4876, tid: 5068, name: ff_read  >>> com.dream.ijk <<<
11-20 20:31:52.737 5175-5175/? A/DEBUG: signal 11 (SIGSEGV), code 0 (SI_USER), fault addr --------
11-20 20:31:52.737 5175-5175/? A/DEBUG:     x0   4190000041900000  x1   00000071f63562c0  x2   00000071e6441260  x3   0000000000000000
11-20 20:31:52.737 5175-5175/? A/DEBUG:     x4   0000000000000000  x5   0000000000003166  x6   000000000000007c  x7   0000000000000000
11-20 20:31:52.737 5175-5175/? A/DEBUG:     x8   96988749beb03993  x9   96988749beb03993  x10  0000000000000001  x11  0000000000000000
11-20 20:31:52.737 5175-5175/? A/DEBUG:     x12  0000000000000001  x13  0000000000000000  x14  00000000ffffffff  x15  00000000001ef0c0
11-20 20:31:52.737 5175-5175/? A/DEBUG:     x16  00000072075ad2c8  x17  000000720754f544  x18  00000000000001bf  x19  00000071e8ed5188
11-20 20:31:52.738 5175-5175/? A/DEBUG:     x20  0000000000000000  x21  00000071e85bc200  x22  00000071e8ed5228  x23  0000000000000000
11-20 20:31:52.738 5175-5175/? A/DEBUG:     x24  00000071e85bc200  x25  0000000000058534  x26  0000000000000001  x27  00000071e940eba8
11-20 20:31:52.738 5175-5175/? A/DEBUG:     x28  0000000000000001  x29  00000071e8ed5280  x30  00000071ea894a2c
11-20 20:31:52.738 5175-5175/? A/DEBUG:     sp   00000071e8ed5170  pc   00000071e6441260  pstate 0000000060000000
11-20 20:31:52.740 5175-5175/? A/DEBUG: backtrace:
11-20 20:31:52.741 5175-5175/? A/DEBUG:     #00 pc 0000000000041260  [anon:libc_malloc:00000071e6400000]
11-20 20:31:52.741 5175-5175/? A/DEBUG:     #01 pc 0000000000282a28  /data/app/com.dream.ijk-6wnf8OeiPxDj3ym2GePqug==/lib/arm64/libijkffmpeg.so

**Comment by JzwOnly** [comment]
@Dreamskya  请问录屏闪退的问题解决了吗  能看一下修改ijkplayer的ff_ffplay.c 源码吗
