### ISSUE TITLE
dns缓存key问题

### ISSUE THREAD

**Issue by mazejia** [bilibili/ijkplayer#4914]
dns缓存key如何改为域名加端口号呢？现在发现是只有域名当作key。

**Comment by befovy** [comment]
这部分内容在 ffmpeg 源码中，不在 ijkplayer 中。 @mazejia

**Comment by mazejia** [comment]
> 
> 
> 这部分内容在 ffmpeg 源码中，不在 ijkplayer 中。 @mazejia

好的。多谢。
