### ISSUE TITLE
音视频是单独分开的，这个怎么同时播放？

### ISSUE THREAD

**Issue by SteveKin3** [bilibili/ijkplayer#4926]
音频和视频是分开的两个文件/链接，exoplayer可以MergingMediaSource播放，ijkplayer怎么做？

**Comment by ChaoShengStash** [comment]
音视频分离，自己写demux呗

**Comment by ff-frida** [comment]
播放网络音频文件是https的时候，会播放失败。文件很大的时候，更容易失败。http的不会

**Comment by SteveKin3** [comment]
@ChaoShengStash  有偿指导一下？

**Comment by ChaoShengStash** [comment]
加QQ 1104244030

**Comment by mikedream89** [comment]
@SteveKin3 解决了吗, 怎么解决的

**Comment by CoolChimpanzee** [comment]
问题怎么样了楼主，能请教一下吗
