### ISSUE TITLE
设置了缓存。因为每次的url都不同实际是同一个文件，导致缓存文件被覆盖，这种有办法解决吗吗？？

### ISSUE THREAD

**Issue by lTBeL** [bilibili/ijkplayer#4927]

**Comment by befovy** [comment]
可以说一下你怎么设置缓存的吗？谢谢

**Comment by lTBeL** [comment]
> 可以说一下你怎么设置缓存的吗？谢谢

![mmexport1575630635034](https://user-images.githubusercontent.com/15243969/70318975-241a9080-185c-11ea-89cd-32098e1ed18a.jpg)
我的部分代码，在公交车上，你在问题里面搜一下选中的这个字符串，有别人的设置，我也是刚刚抄的。

**Comment by lTBeL** [comment]
@befovy

**Comment by befovy** [comment]
好的，谢谢 @lTBeL
