### ISSUE TITLE
为什么从github下载下来的java的代码编译好的apk没有设置url的页面。这样不能播放

### ISSUE THREAD

**Issue by andyjmzheng** [Bilibili/ijkplayer#493]
为什么从github下载下来的java的代码编译好的apk没有设置url的页面。这样不能播放？是本来就没有，还是我设置有问题？？麻烦告诉下。谢谢！@Android4MediaPlayer  @bbcallen 
谢谢！

**Comment by playererer** [comment]
原来是没有的，可以自己改下UI

**Comment by andyjmzheng** [comment]
我就是自己修改了UI后。ijkplayer.so和ffmpeg.so都没有修改。现在播放一段时间后就出现缓存。导致暂停。我查了底层的代码应该是没有问题的。想定位是哪里的问题。。你哪里有可以变异apk的代码吗？或者有可以测试的apk。我测试下？谢谢！@playererer

**Comment by andyjmzheng** [comment]
@playererer 原来没有、现在也没有吧？？

**Comment by bbcallen** [comment]
Feel free to implement your own UI.
