### ISSUE TITLE
请问修改哪个文件的参数能缩短出现画面的时间？

### ISSUE THREAD

**Issue by Long888** [Bilibili/ijkplayer#496]
我用Android原生的mediaplayer播放，出现画面的时间很短，一拿到流马上就能播放出画面，用ijkmediaplayer 使用mediacodec播放时就要多等几秒钟，这对于直播来说就很慢了。我是用http流播放的，自己在本地做了个httpproxy，将数据以流的形式推送给mediaplayer，然后播放。我是在Android4.4的电视盒上测试的，芯片是amlogic s805的。请问我要修改哪个文件的哪个参数才能缩短播放出画面的时间？一拿到流就能播。 还有就是有时候在退出的时候会出现一个错误：
09-25 18:22:33.388: A/libc(904): heap corruption detected by dlfree
09-25 18:22:33.388: A/libc(904): Fatal signal 6 (SIGABRT) at 0x00000388 (code=-6), thread 1258 (Thread-392)。

**Comment by bbcallen** [comment]
android.media.MediaPlayer is your best choice. 
amlogic's system supports enough format, you don't have to use ijkplayer on it.

**Comment by Long888** [comment]
我们的软件还需要适应其它的平台，所以必须用到ijkplayer,请问我该修改哪里才能满足需求？

**Comment by bbcallen** [comment]
```
IMediaPlayer mp = null;
if (isAmlogic())
    mp = new AndroidMediaPlayer();
else
    mp = new IjkMediaPlayer();
```

**Comment by Long888** [comment]
我现在就是这么做的，问题是还要适应其它平台，以后还要在手机上安装运行。有些手机自带的mediaplayer是不支持http流播放的,最终还得用到ijkplayer

**Comment by Android4MediaPlayer** [comment]
手机没有amlogic芯片的

**Comment by Long888** [comment]
其它平台也是一样的，是不是哪里有个buffersize可以调整，在mediaplayer接收到多少包后开始解码？

**Comment by lslxdx** [comment]
All of these constants affects the buffering speed:
VIDEO_PICTURE_QUEUE_SIZE_MIN
VIDEO_PICTURE_QUEUE_SIZE_MAX
VIDEO_PICTURE_QUEUE_SIZE_DEFAULT
SUBPICTURE_QUEUE_SIZE
SAMPLE_QUEUE_SIZE
FRAME_QUEUE_SIZE
DEFAULT_HIGH_WATER_MARK_IN_BYTES
DEFAULT_START_HIGH_WATER_MARK_IN_MS
DEFAULT_NEXT_HIGH_WATER_MARK_IN_MS
DEFAULT_MAX_HIGH_WATER_MARK_IN_MS
BUFFERING_CHECK_PER_BYTES
BUFFERING_CHECK_PER_MILLISECONDS

**Comment by Long888** [comment]
你说的这些参数我改了试过了，没什么效果。后来我在看log的时候发现了一行：max_analyze_duration 5000000 reached at 5013333 microseconds st:1  ，然后在网上查了一下，是ffmpeg里面的avformat_find_stream_info()这个函数里的max_analyze_duration值太大了，要改小一点。
