### ISSUE TITLE
电信移动网络播放问题

### ISSUE THREAD

**Issue by MisterAC** [bilibili/ijkplayer#4965]
用电信的移动网络，无法播放部分视频，但是在其他运营商以及WIFI下该视频也能播放
电信下一会能放一会不能，交替出现，切换成wifi播放后再切换回电信移动网络也能播放，错误提示
Connection to xxxx failed: No route to host
Hit dns cache but connect fail hostname = xxx, ip=

**Comment by huyanminggithub** [comment]
我也遇到了同样的问题。交替出现，一次能播放一次就播放不了

**Comment by panyancen** [comment]
videoOptionModel =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_clear", 1);
        list.add(videoOptionModel);
          GSYVideoManager.instance().setOptionModelList(list);

加上这段可以解决，具体可以查找相关文档解释，我刚刚解决，我在想原因

**Comment by zstartw** [comment]
wifi播放正常，移动网络就播放失败，我也出现了，手机是联通的网络

**Comment by panyancen** [comment]
> wifi播放正常，移动网络就播放失败，我也出现了，手机是联通的网络

内部实现加了dns缓存，需要把dns缓存关闭，因为视频链接做了cdn处理的

**Comment by pinguoooo** [comment]
我也遇到ijkplayer无法播放视频，用下面这句解决的
ijkMediaPlayer.setOption( IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_clear", 1);

**Comment by MisterAC** [comment]
as panyancen say

**Comment by pinguoooo** [comment]
原理一样的，嗯嗯
