### ISSUE TITLE
iOS - Can only play H.264 MP4?

### ISSUE THREAD

**Issue by clementyau** [Bilibili/ijkplayer#498]
With iOS and module-lite.sh, I was able to build the demo app. It plays H.264 MP4. However, none of the AVI / MPEG2 / H.264 MKV plays. This is with "Local Folder" files transferred via iTunes.

So ... which formats is it supposed to play? Thanks for your help.

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/config/module-lite.sh
