### ISSUE TITLE
some question about the new ijkplayer 

### ISSUE THREAD

**Issue by xiejinglan** [Bilibili/ijkplayer#499]
hello, i compiled the new ijkplayer in ubuntu. and the complile is success, but in the end, it's just has  (libijkffmpeg.so  libijkplayer.so libijksdl.so)  , it's doesn't see the (libijkutil.so libstlport_shared.so). i want to know am I right. thanks very much.

**Comment by bbcallen** [comment]
libijkutil.so has been merged into libijksdl.so
libstlport_shared.so is not necessary any more.
