### ISSUE TITLE
Some vidoe can't play

### ISSUE THREAD

**Issue by 51339938** [Bilibili/ijkplayer#50]
07-17 14:45:39.200: W/IJKMEDIA(22358): IjkMediaPlayer_native_setup
07-17 14:45:39.200: W/IJKMEDIA(22358): IjkMediaPlayer_setVideoSurface
07-17 14:45:39.200: W/IJKMEDIA(22358): ijkmp_set_android_surface(surface=0x36e0001d)
07-17 14:45:39.200: W/IJKMEDIA(22358): ijkmp_set_android_surface(surface=0x36e0001d)=void
07-17 14:45:39.200: W/IJKMEDIA(22358): IjkMediaPlayer_setDataSourceAndHeaders
07-17 14:45:39.200: W/IJKMEDIA(22358): ijkmp_set_data_source(url="/storage/sdcard0/Duopai/1.mp4")
07-17 14:45:39.200: W/IJKMEDIA(22358): ijkmp_set_data_source(url="/storage/sdcard0/1.mp4")=0
07-17 14:45:39.200: W/IJKMEDIA(22358): IjkMediaPlayer_prepareAsync
07-17 14:45:39.200: W/IJKMEDIA(22358): ijkmp_prepare_async()
07-17 14:45:39.200: W/IJKMEDIA(22358): message_loop
07-17 14:45:39.200: W/IJKMEDIA(22358): FFP_MSG_FLUSH:
07-17 14:45:39.215: W/IJKMEDIA(22358): ijkmp_prepare_async()=0
07-17 14:45:39.285: W/IJKMEDIA(22358): ijkmp_get_msg: FFP_MSG_PREPARED
07-17 14:45:39.285: W/IJKMEDIA(22358): FFP_MSG_PREPARED:
07-17 14:45:39.285: E/IJKMEDIA(22358): unknown FFP_MSG_xxx(700)
07-17 14:45:39.285: W/IJKMEDIA(22358): FFP_MSG_VIDEO_SIZE_CHANGED: 480, 480
07-17 14:45:39.285: W/IJKMEDIA(22358): FFP_MSG_SAR_CHANGED: 1, 1
07-17 14:45:39.290: W/IJKMEDIA(22358): FFP_MSG_BUFFERING_START:

when I am play this video,output log message have not "multiple edit list entries, a/v desync might occur, patch welcome",than it is will be down.

**Comment by chodison** [comment]
@51339938  能提供文件资源吗？还是播放网络链接？
