### ISSUE TITLE
m3u8文件中如果有多个分辨率的源，会自动根据网速切换么？

### ISSUE THREAD

**Issue by wudongyang** [Bilibili/ijkplayer#501]
1 m3u8文件中如果有多个分辨率的源，会自动根据网速切换么？
2 如果不能自动根据网速切换，能通过什么方式指定用哪一个么？

形如：
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=204800, RESOLUTION=240x180
/asp/hls/200.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=460800, RESOLUTION=480x360
/asp/hls/450.m3u8

**Comment by bbcallen** [comment]
1. Not for now.
2. No way for now.

**Comment by wudongyang** [comment]
ijkplayer 最终是调用 ffmpeg 解析 m3u8 格式吧？
通过修改 ffmpeg 理论上应该可以解决这个问题吧？
ijkplayer 现在调用的 ffmpeg 开源么？

**Comment by Android4MediaPlayer** [comment]
是的 这个主要在协议层实现 用的是ffmpeg开源里面的hls

**Comment by wuqi713** [comment]
能指定一个吗？
