### ISSUE TITLE
setVolume如何设置超过1

### ISSUE THREAD

**Issue by nbcallum** [bilibili/ijkplayer#5014]
需要做一个音量增益的效果，现在setVolume是[0~1]的范围，底层如何修改可以大于1呢，望指教下，谢谢了

**Comment by nbcallum** [comment]
参考了之前的issues 打开了avfilter 但是soundtouch就失效了  这两个是互斥的吗

**Comment by sishuixianghuo** [comment]
android 怎么打开 avfilter 设置增益
