### ISSUE TITLE
播放该TS地址无法播放，一直缓冲

### ISSUE THREAD

**Issue by 951AB159BA** [bilibili/ijkplayer#5029]
http://umeyecloudtest2.oss-cn-shenzhen.aliyuncs.com/hlstest/new_test2.ts

**Comment by 951AB159BA** [comment]
还有该m3u8地址也不行。估计是同一个问题。http://umeyecloudtest2.oss-cn-shenzhen.aliyuncs.com/hlstest/6.m3u8

**Comment by GetViewer** [comment]
怎么解决的
