### ISSUE TITLE
Invalid data found when processing WebM input

### ISSUE THREAD

**Issue by bluemix** [Bilibili/ijkplayer#503]
Hello, after building the player, and using an ARMv7A architecture, and explicitly wanted to play this WebM video, I get the following error:
```
09-28 22:36:51.481    3939-3961/tv.danmaku.ijk.media.sample E/IJKMEDIA﹕ http://video.webmfiles.org/big-buck-bunny_trailer.webm: Invalid data found when processing input
09-28 22:36:51.485    3939-3939/tv.danmaku.ijk.media.sample E/tv.danmaku.ijk.media.player.IjkMediaPlayer﹕ Error (-10000,0)
```

**Comment by Android4MediaPlayer** [comment]
in README
If you prefer more codec/format

cd config
rm module.sh
ln -s module-default.sh module.sh
cd android/contrib
# cd ios
sh compile-ffmpeg clean

**Comment by bluemix** [comment]
I have the ijkplayer in one folder and the ijk-player in another folder. Both of them are in the same folder:
+ Folder X
  - ijkplayer
  - ijkplayer-android

Even if I built with the default-module.sh, and changing little parameters there, I don't see any change in the configuration when it configures ffmpeg. So, I was explicitly adding parameters in the ```do-compile-ffmpeg.sh```.
So, I've built the player with the lite-module.sh and having the ```--enable-libvpx``` enabled from the ```do-compile-ffmpeg.sh```, and still getting this error:
```
10-05 08:18:10.515 21040-21079/tv.danmaku.ijk.media.sample E/IJKMEDIA: http://video.webmfiles.org/big-buck-bunny_trailer.webm: Invalid data found when processing input
10-05 08:18:10.519 21040-21040/tv.danmaku.ijk.media.sample E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
```

**Comment by bbcallen** [comment]
You should run "sh compile-ffmpeg.sh clean" after configure changed.
