### ISSUE TITLE
音频抢占问题

### ISSUE THREAD

**Issue by simplepeng** [bilibili/ijkplayer#5039]
例：网易云后台播放音乐，ijk开始播放视频，视频为无声音轨的视频，网易云播放的音乐就被暂停了
，释放掉ijk，网易云也不会重新播放音乐
同理：抖音播放视频退出后，网易云会继续播放音乐

请问下有什么解决办法吗，谢谢

**Comment by xuandu** [comment]
你可以在外边写一个监听，当关闭ijk操作的时候resume一下，应该是有这个恢复之前操作的；从你的描述看这个打断恢复应该不是网易做的，而是抖音做的；所以你也可以自外边写一下，

**Comment by simplepeng** [comment]
使用B站Android客户端测试，也是有同样的问题存在。
自己`AudioManager(context).abandonAudioFocus(null)`取消音频焦点也没用

**Comment by simplepeng** [comment]
```java
AudioManager am = (AudioManager) mAppContext.getSystemService(Context.AUDIO_SERVICE);
//        am.requestAudioFocus(null, AudioManager.STREAM_MUSIC, AudioManager.AUDIOFOCUS_GAIN);
        am.requestAudioFocus(null,
                AudioManager.AUDIOFOCUS_GAIN_TRANSIENT_MAY_DUCK,
                AudioManager.AUDIOFOCUS_GAIN_TRANSIENT);
```
将注释的代码，修改为其下的代码成功解决了这个问题

**Comment by MhuiHugh** [comment]
换七牛或者阿里云播放器，不开源但是免费。经测验可解决这个问题，音频焦点我试过不球行。20220301
https://developer.qiniu.com/pili/1210/the-android-client-sdk
https://help.aliyun.com/document_detail/125578.html
