### ISSUE TITLE
执行 ./compile-openssl.sh all 提示libcrypto.a找不到错误

### ISSUE THREAD

**Issue by kHRYSTAL** [bilibili/ijkplayer#5040]
![](https://ftp.bmp.ovh/imgs/2020/05/5f721a90860f2271.jpg)

系统环境: macOS Catalina 10.15.4
项目分支: k0.8.8

在执行./compile-openssl.sh all 时报出截图错误
是否需要关注该错误以及如何配置?

**Comment by kHRYSTAL** [comment]
`./config --prefix=/usr/local/ssl enable-shared`

**Comment by johnkx93** [comment]
请问这行是要放哪里呢？
