### ISSUE TITLE
本地代理，M3U8处理，ts 不从第一个开始播放

### ISSUE THREAD

**Issue by missu263** [bilibili/ijkplayer#5051]
求教一个问题：
【背景】：基于AndroidVideoCache实现本地代理对M3U8视频格式的缓存处理，就是本地会预下载第一个ts的文件，实现播放器（IJKPlayer）的秒开
【实现】：播放器设置的播放URL为 127.0.0.1/https://xxxx.m3u8，本地代理去请求https://xxxx.m3u8拿到playlist，这个时候会将playlist的每个ts片的地址也改为127.0.0.1/https://xxxx.ts，然后将这部分数据通过连接播放器的socket返回给播放器，后续本地代理会再收到127.0.0.1/https://xxxx.ts的请求
【碰到的问题】：上述实现过程还只是本地代理发送真正的请求，然后把网络流的数据通过播放器连接来的socket原封不动的返回。但是实际的播放过程中，发现播放器发起的ts请求，不是从第一个ts片开始请求播放（随机的）。这导致播放就乱了，而且最后播放器出现一直缓冲。
这里面会不会是因为播放器内部收到的http header不正确导致的啊，因为代理写入的response header为：
"HTTP/1.1 200 OK\n" + "Accept-Ranges: bytes\n"
                + format("Content-Length: %d\n", getContentLength(connection)) + "Connection: keep-alive\n"
                + format("Date: %s",gmtFormat.format(new Date()) + "\n")
                + format("Content-Type: %s\n", "application/octet-stream") + "\n"; // headers end

**Comment by as981242002** [comment]
你确定m3u8数据是正常的？

**Comment by missu263** [comment]
> 你确定m3u8数据是正常的？

正常的，已经找到问题了，发现是对ts进行全地址拼接后，没有更新response header 中的content-length导致的

**Comment by 812288976** [comment]
您好，基于AndroidVideoCache实现本地代理对M3U8视频格式的缓存处理，就是本地会预下载第一个ts的文件，实现播放器（IJKPlayer）的秒开 这个怎么实现的 有demo吗？
