### ISSUE TITLE
视频seek后必现几秒慢放

### ISSUE THREAD

**Issue by ilsquare** [bilibili/ijkplayer#5054]

**Comment by SenJiang** [comment]
I have problem  too  ,who resolve it !!!!

**Comment by kyriej** [comment]
have u solve it

**Comment by taojeff** [comment]
你有解决这个问题吗

**Comment by ilsquare** [comment]
> 你有解决这个问题吗

宏定义SDL_AUDIO_MAX_CALLBACKS_PER_SEC从30改成15

**Comment by taojeff** [comment]
> > 你有解决这个问题吗
> 
> 宏定义SDL_AUDIO_MAX_CALLBACKS_PER_SEC从30改成15

效果没有达到，我的状态是seek后感觉3-5秒进度都是播放倍速在0.5倍播放一样。不过还是挺感谢提供方案

**Comment by ilsquare** [comment]
> > > 你有解决这个问题吗
> > 
> > 
> > 宏定义SDL_AUDIO_MAX_CALLBACKS_PER_SEC从30改成15
> 
> 效果没有达到，我的状态是seek后感觉3-5秒进度都是播放倍速在0.5倍播放一样。不过还是挺感谢提供方案

是我搞错了，你可以试试吧SDL_IOS_AUDIO_MAX_CALLBACKS_PER_SEC从15改成30，音频的问题，回调太慢了

**Comment by taojeff** [comment]
> > > > 你有解决这个问题吗
> > > 
> > > 
> > > 宏定义SDL_AUDIO_MAX_CALLBACKS_PER_SEC从30改成15
> > 
> > 
> > 效果没有达到，我的状态是seek后感觉3-5秒进度都是播放倍速在0.5倍播放一样。不过还是挺感谢提供方案
> 
> 是我搞错了，你可以试试吧SDL_IOS_AUDIO_MAX_CALLBACKS_PER_SEC从15改成30，音频的问题，回调太慢了

@ilsquare 感觉好点了，现在快进后画面低倍数播放效果要比之前好多了。时间也在3秒内了。之前一直维持在5秒
