### ISSUE TITLE
Android IjkMediaPlayer播放RTSP视频流,一开始的时候会花屏,视频格式是H264

### ISSUE THREAD

**Issue by zengyunpeng** [bilibili/ijkplayer#5074]

**Comment by zengyunpeng** [comment]
这种问题有解决方案吗?需要修改C代码?

**Comment by Arikes** [comment]
可能的原因是服务端发送的数据量较大时，客户端缓冲区不足，导致数据丢失的问题，从而引起花屏现象。
I帧没到达收到了BP帧或者... 各种数据不完整导致。可以参考 https://www.cnblogs.com/dwdxdy/p/3240217.html

**Comment by zengyunpeng** [comment]
换成ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");我解决了这个问题

**Comment by pulapulapin** [comment]
> 换成ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");我解决了这个问题

设置这个属性对于客户端或者服务器有什么要求吗，我这边用live555发的流，ijkplayer设置了这个属性后 ffmpeg Server returned 400 Bad Request
