### ISSUE TITLE
IJKPlayer怎么监听视频播放完毕呢？

### ISSUE THREAD

**Issue by ZYF99** [bilibili/ijkplayer#5078]
如题，使用  IMediaPlayer.OnCompletionListener接口 无效

**Comment by ZYF99** [comment]
抱歉是我忘添加了，已经解决了！

**Comment by zerrojs** [comment]
发现只播放音乐是有OnCompletionListener回调的，播放一个视频没有这个回调。@ZYF99 遇到这个问题吗？

**Comment by ZYF99** [comment]
> 发现只播放音乐是有OnCompletionListener回调的，播放一个视频没有这个回调。@ZYF99 遇到这个问题吗？

你需要先写一个VideoPlayerListener implements IMediaPlayer.OnCompletionListener 
然后 mMediaPlayer.setOnCompletionListener(videoPlayerListener)
mMediaPlayer是一个IMediaPlayer 他的初始化这样做
        IjkMediaPlayer ijkMediaPlayer = new IjkMediaPlayer();
        IjkMediaPlayer.native_setLogLevel(IjkMediaPlayer.IJK_LOG_DEBUG);
        mMediaPlayer = ijkMediaPlayer;

**Comment by zerrojs** [comment]
ijk带的demo也是这样实现的，demo也没收到这个回调。但是如果只是播放一段音乐，是有这个回调的。很奇怪

**Comment by ZYF99** [comment]
> ijk带的demo也是这样实现的，demo也没收到这个回调。但是如果只是播放一段音乐，是有这个回调的。很奇怪

换个视频试试呢

**Comment by zerrojs** [comment]
换视频也是收不到这个回调。你的ijk版本是哪个呢？

**Comment by zerrojs** [comment]
重新下载ijk编译可以了，多谢🙏
