### ISSUE TITLE
Audio track selection feature

### ISSUE THREAD

**Issue by NikmanSergey** [Bilibili/ijkplayer#509]
@bbcallen,
Your library is awesome!
People asked this and I would be very happy to have this features as well:
- **Audio track selection**
- Subtitle track selection (sending subs text back to java to render there)
- Deinternlace

Please, tell will you going to implement this features in the future?
If you don't want to add them because of using additional resources, it can be implemented as selectable features at compile time.

The most important is Audio track selection.
You told that example by **Peterede** https://github.com/Bilibili/ijkplayer/issues/72 will not work with MediaCodec?
Could you, please, tell how this feature can be done when using MediaCodec mode?
Thanks again!

**Comment by NikmanSergey** [comment]
@bbcallen 
Please, can Audio track selection feature be on your recent plans?
If no, can you prompt how can I do this by myself. It sholud work with MediaCodec enabled.
Thanks!!!

**Comment by bbcallen** [comment]
No idea, never thought about it.

http://git.videolan.org/?p=ffmpeg.git;a=blob;f=ffplay.c;h=4a084b4480b949ba16b0ec3b878bf3306af8a8e8;hb=HEAD#l3191
This could be a start point.

**Comment by NikmanSergey** [comment]
@bbcallen 
I tried and this implementation seems working fine with and without MediaCodec.
However, this could take several seconds to sync video to new audio track. For the local files, following *mp.seekTo(mp.getCurrentPosition())* should be used.

Probably, you may want it add it officially.

ff_ffplay.c:
```
int ffp_get_audio_tracks_cnt(FFPlayer *ffp)
{
    assert(ffp);
    VideoState *is = ffp->is;
    int total = 0;
    if (!is)
        return EIJK_NULL_IS_PTR;

    AVFormatContext *ic = is->ic;
    int stream_index;
    AVStream *st;
    int codec_type = AVMEDIA_TYPE_AUDIO;

    for (stream_index = 0; stream_index < is->ic->nb_streams; stream_index++)
    {
        st = ic->streams[stream_index];
        if (st->codec->codec_type == codec_type) {
            /* check that parameters are OK */
            switch(codec_type) {
                case AVMEDIA_TYPE_AUDIO:
                    if (st->codec->sample_rate != 0 && st->codec->channels != 0)
                        total++;
                    break;
            }
        }
    }

    return total;
}

int ffp_select_audio_track(FFPlayer *ffp, int index)
{
    // Actually, make track cycling
    // index ignored
    assert(ffp);
    VideoState *is = ffp->is;
    if (!is)
	return EIJK_NULL_IS_PTR;

    AVFormatContext *ic = is->ic;
    int start_index, first_index = -1, stream_index;
    AVStream *st;
    int codec_type = AVMEDIA_TYPE_AUDIO;

    if (codec_type == AVMEDIA_TYPE_VIDEO)
        start_index = is->video_stream;
    else if (codec_type == AVMEDIA_TYPE_AUDIO)
        start_index = is->audio_stream;
    /*else
        start_index = is->subtitle_stream;
    if (start_index < (codec_type == AVMEDIA_TYPE_SUBTITLE ? -1 : 0))
        return;*/

    for (stream_index = 0; stream_index < is->ic->nb_streams; stream_index++)
    {
	st = ic->streams[stream_index];
        if (st->codec->codec_type == codec_type) {
	    /* check that parameters are OK */
            switch(codec_type) {
	        case AVMEDIA_TYPE_AUDIO:
                    if (st->codec->sample_rate != 0 && st->codec->channels != 0) {
                        if (first_index < 0)
                            first_index = stream_index;
                        if (stream_index > start_index)
                            goto the_end;
                    }
                    break;
            }
        }
    }

    stream_index = first_index;

the_end:
    stream_component_close(ffp, start_index);
    stream_component_open(ffp, stream_index);

    return 0;
} 
```

**Comment by bbcallen** [comment]
I'll take a look.

**Comment by bbcallen** [comment]
Try ijkmp_set_stream_selected()
