### ISSUE TITLE
./init-ios.sh ffmpeg从没有成功过

### ISSUE THREAD

**Issue by zp0605** [bilibili/ijkplayer#5091]
./init-ios.sh 下载不下来ffmpeg，脚本里面能否指定从国内镜像下载，github对国人下载很不友好

**Comment by scp1011** [comment]
我也失败过两次，一次好像是因为文件太大的限制，后来改了个什么东西就好了，具体看报了什么信息。另一次是因为下载太慢了，然后就自己手动用数据流量下载，再放到ffmpeg的目录里。

**Comment by qfkongyan** [comment]
打包下

**Comment by WangShunYang** [comment]
把对应的数据源切换到gitee 上的数据源就可以了


# IJK_FFMPEG_UPSTREAM=git://git.videolan.org/ffmpeg.git
IJK_FFMPEG_UPSTREAM=https://gitee.com/qtjdegit/FFmpeg.git
IJK_FFMPEG_FORK=https://gitee.com/qtjdegit/FFmpeg.git
IJK_FFMPEG_COMMIT=ff3.1--ijk0.6.0--20160715--001
IJK_FFMPEG_LOCAL_REPO=extra/ffmpeg

**Comment by zp0605** [comment]
多谢各位,后面自己找了个数据源：
IJK_FFMPEG_UPSTREAM=https://gitee.com/zp0605/FFmpeg_bilibili.git
IJK_FFMPEG_FORK=https://gitee.com/zp0605/FFmpeg_bilibili.git
IJK_FFMPEG_COMMIT=ff3.3--bw0.8.0--20180323--001
IJK_FFMPEG_LOCAL_REPO=extra/ffmpeg
