### ISSUE TITLE
ijkplayer on Android

### ISSUE THREAD

**Issue by taraspaliy** [Bilibili/ijkplayer#510]
I want to use the ijkplayer with Android app for playing aac/h264 files..
Does ijkplayer use FFmpeg for decoding h264? In case if ijkplayer uses FFmpeg - does it use native decoders or its own? 

Thanks for any info.

**Comment by xiejinglan** [comment]
it's always use the ffmpeg avcodec to decode your video files.

**Comment by taraspaliy** [comment]
Hi @xiejinglan 
Is it possible in this case to use ijkplayer for commercial app? I mean doesn't usage of FFmpeg decoders break the h264 patent rules?

**Comment by bbcallen** [comment]
http://ffmpeg.org/legal.html

**Comment by taraspaliy** [comment]
@bbcallen thanks for the answer.
But this legal notice doesn't answer the question. Is there any chance that you know about commercial apps, which used FFmpeg and in particular h264 decoder?

**Comment by bbcallen** [comment]
AFAIK, LGPLv2.1 license allows you to use the code in commercial app under LGPLv2.1, which is to say, you have to and only have to make ijkplayer and your modification on ijkplayer as open source code under LGPLv2.1 or later
But I am not a laywer, I can't answer the question about patent part.

**Comment by taraspaliy** [comment]
@bbcallen 
Thanks! so - there's no chance that library uses with for example MediaCodec native Android decoders?

**Comment by bbcallen** [comment]
You can enable it, but if error happens, ijkplayer would fall back to libavcodec.

**Comment by taraspaliy** [comment]
Great, thanks for the info
