### ISSUE TITLE
A problem with ijkplayer

### ISSUE THREAD

**Issue by xiejinglan** [Bilibili/ijkplayer#511]
i used ijkplaer to play video in android. but a problem with the progressBar. for example. the video duration is 30 second, when the play is complet, i called the function getCurrentPosition(), but it's always retrun the postion at 27 second.this problem is bothered me, and i don't know how to fix it, please help me to fix it , thanks a lot

**Comment by xiaoyaomeng** [comment]
我也遇到过这个问题

**Comment by xiejinglan** [comment]
@xiaoyaomeng 
so , how do you fix it? any solutions ?
