### ISSUE TITLE
ndk 21编不过

### ISSUE THREAD

**Issue by lyqaiym** [bilibili/ijkplayer#5118]
加了 
case "$IJK_NDK_REL" in
            11*|12*|13*|14*|21*)
以后
====================
[*] check archs
====================
FF_ALL_ARCHS = armv7a
FF_ACT_ARCHS = armv7a

====================
[*] check env armv7a
====================
FF_ARCH=armv7a
FF_BUILD_OPT=

--------------------
[*] make NDK standalone toolchain
--------------------
build on Linux x86_64
ANDROID_NDK=/home/lyq/develop/ndk/android-ndk-r21b
IJK_NDK_REL=21.1.6352462
NDKr21.1.6352462 detected
HOST_OS=linux
HOST_EXE=
HOST_ARCH=x86_64
HOST_TAG=linux-x86_64
HOST_NUM_CPUS=4
BUILD_NUM_CPUS=8
Auto-config: --arch=arm
ERROR: Failed to create toolchain

**Comment by Azson** [comment]
相同问题，lz怎么解决的呢

**Comment by chengshengru** [comment]
build on Darwin x86_64
ANDROID_NDK=/Android/sdk/ndk/21.0.6113669
IJK_NDK_REL=21.0.6113669
NDKr21.0.6113669 detected
HOST_OS=darwin
HOST_EXE=
HOST_ARCH=x86_64
HOST_TAG=darwin-x86_64
HOST_NUM_CPUS=8
BUILD_NUM_CPUS=16
Auto-config: --arch=arm
ERROR: Failed to create toolchain.


请问最后怎么解决的？

**Comment by kolyneh** [comment]
#3378
