### ISSUE TITLE
iOS 播放直播流视频会导致内存不断增加 然后闪退

### ISSUE THREAD

**Issue by lotawei** [bilibili/ijkplayer#5123]
use alloctions check app 
playing movie , 
av_malloc 每隔一段时间就会分配100mb左右内存
手机内存小的 放久就会收到内存警告导致闪退
播放紧紧使用 url来播放
 let options = IJKFFOptions.byDefault()
        options?.setFormatOptionIntValue(1024 * 16, forKey: "probsize")
        options?.setFormatOptionIntValue(50000, forKey: "analyzeduration")
        options?.setPlayerOptionIntValue(1, forKey: "videotoolbox")
        options?.setCodecOptionIntValue(Int64(IJK_AVDISCARD_DEFAULT.rawValue), forKey: "skip_loop_filter")
        options?.setCodecOptionIntValue(Int64(IJK_AVDISCARD_DEFAULT.rawValue), forKey: "skip_frame")
        options?.setPlayerOptionIntValue(5000, forKey: "max_cached_duration")
        options?.setPlayerOptionIntValue(0, forKey: "infbuf")
        options?.setPlayerOptionIntValue(0, forKey: "packet-buffering")
        options?.setPlayerOptionIntValue(3145728, forKey: "max-buffer-size")
这是相关设置不太清楚是否跟这个有关系

**Comment by dengjunlun** [comment]
请问这个问题解决了吗？我也遇到了这个问题

**Comment by lotawei** [comment]
可以检查下ijkoptional的设置可能跟开启硬件加速或者预缓存大小有关



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dengjunlun ***@***.***&gt;
发送时间: 2021年9月8日 11:51
收件人: bilibili/ijkplayer ***@***.***&gt;
抄送: lotawei ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[bilibili/ijkplayer] iOS 播放直播流视频会导致内存不断增加 然后闪退 (#5123)





 
请问这个问题解决了吗？我也遇到了这个问题

**Comment by lotawei** [comment]
具体情况可以根据Profile跑起来测试根据更改参数测试内存是否有暴涨的问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dengjunlun ***@***.***&gt;
发送时间: 2021年9月8日 11:51
收件人: bilibili/ijkplayer ***@***.***&gt;
抄送: lotawei ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[bilibili/ijkplayer] iOS 播放直播流视频会导致内存不断增加 然后闪退 (#5123)





 
请问这个问题解决了吗？我也遇到了这个问题

**Comment by iTwinkle** [comment]
options?.setPlayerOptionIntValue(0, forKey: "infbuf") 应该是设置了这个参数导致的
