### ISSUE TITLE
(反馈解决方案)1.视频时间多出1s 和2.SeekBar, 按了22s会回退到19s的问题

### ISSUE THREAD

**Issue by xiaoyaomeng** [Bilibili/ijkplayer#514]
都是修改MediaController.java

1. 视频时间多出1s
修改generateTime(long position) :

private static String generateTime(long position) {
        // int totalSeconds = (int)((position / 1000.0) + 0.5);
        // fix bug : add by jiangping.li
        int totalSeconds = (int)((position / 1000.0));
..........
}

2.SeekBar, 按了22s会回退到19s的问题

修改private OnSeekBarChangeListener mSeekListener中的两个地方：
//Modify begin by jiangping.li
// final long newposition = (mDuration * progress) / PROGRESS_MAX;
//===============div===============
final long newposition = (long)(mDuration * (progress * 1.0f / PROGRESS_MAX));
//Modify end by jiangping.li

//Modify begin by jiangping.li
// final long newposition = (mDuration * progress) / PROGRESS_MAX;
//===============div===============
 final long newposition = (long)(mDuration * (progress * 1.0f / PROGRESS_MAX));
//Modify end by jiangping.li

**Comment by xiaoyaomeng** [comment]
O(∩_∩)O 希望可以帮到遇到这个问题的人

**Comment by xiaoyaomeng** [comment]
3. 播放进度条会出现播放到一个值后，跳到起始位置的情况

private long setProgress() {
        if (mPlayer == null || mDragging)
            return 0;
        // fix bug: 18041 , int型溢出，导致变成了负数 modify by jiangping.li
        // int position = mPlayer.getCurrentPosition();
        // int duration = mPlayer.getDuration();
        long position = (long)mPlayer.getCurrentPosition();
        long duration = (long)mPlayer.getDuration();
        if (mProgress != null) {
            if (duration > 0) {
                // fix bug: 18041 , int型溢出，导致变成了负数 modify by jiangping.li
                // int pos = (PROGRESS_MAX * position / duration);
                int pos = Integer.parseInt((PROGRESS_MAX * position / duration)
                        + "");
                mProgress.setProgress(pos);
            }
            int percent = mPlayer.getBufferPercentage();
            mProgress.setSecondaryProgress(percent * PROGRESS_MAX);
        }

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
