### ISSUE TITLE
编译IOS版本的库很奇怪

### ISSUE THREAD

**Issue by semnyqu** [Bilibili/ijkplayer#515]
cd config
rm module.sh
ln -s module-default.sh module.sh
cd ../ios
sh compile-ffmpeg clean
当执行这个命令时发现出现以下错误：sh: compile-ffmpeg: No such file or directory
我再次确认了该路径下是有这个文件的

我直接忽视了这个文件，直接执行build ios下的命令
我直接已经下载好了源码（不是用　git　命令）
./init-ios.sh
执行这一步后发现根本没法搞了，每次下载到　11%左右直接　over了

**Comment by bbcallen** [comment]
Get a VPN or proxy
