### ISSUE TITLE
加载字幕时setOnTimedTextListener 

### ISSUE THREAD

**Issue by kyriej** [bilibili/ijkplayer#5167]

**Comment by kyriej** [comment]
加载字幕时setOnTimedTextListener 可以拿到回调的字幕文本，不过会报错
 Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 32661 (ff_subtitle_dec) 
是ass字幕，不知道是不是加载到特效字幕从而导致奔溃

**Comment by waqasyousafy** [comment]
Hi kyriej have you embed external subtitle in it ?
