### ISSUE TITLE
[QUESTION] Is it possible to provide your own data source?

### ISSUE THREAD

**Issue by stuckless** [Bilibili/ijkplayer#517]
Is it possible to provide a custom data source that is not a file, asset, or URL?  ie, I have a server that communicates chunks of video over tcpip, but it's not http, so we have to use raw sockets.  I'm wondering if i can read the data, and provide it as a custom data source.  The video data is valid data, ie, h264, etc.

**Comment by Android4MediaPlayer** [comment]
custom I/O

**Comment by stuckless** [comment]
Not sure if "custom I/O" was the answer, or a question.   I've looked at IMediaPlayer and setDataSource accepts a FileDescriptor or a Uri.   Unlike a URL, a Uri doesn't open an InputStream, but rather is consumed by something else.   The mediaplayer ultimately passes the datasource uri to a native _setDataSource method.  Is there a callback that can be used to fetch data from an alternate source?  ExoPlayer has an abstract concept of DataSource that has open(), readBytes(), and close() methods.  Using this I can create custom data sources pretty easily for ExoPlayer.  I'm just wondering if ijkplayer supports something similar, and I've missed it.

**Comment by bbcallen** [comment]
Search "AVIOContext Custom IO".
MediaDataSource is in plan, but not soon.

**Comment by stuckless** [comment]
Thanks @bbcallen, I see that while ffmpeg supports the concept, it would need to be exposed via the jni/java layer to utilize it in java.  Since C is not my strength, I'll leave that to the professionals ;)  Thanks for your help.  Great work on this this project, it is much appreciated.

If you want, you can close this "Issue" since it was just a question, and the question has been answered.  Or you can leave it open as as a reminder that supporting something like MediaDataSource, in the future, would be handy ;)

**Comment by bbcallen** [comment]
Have a look at
https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/ijkavformat/async.c
You could implement your own protocol as a FFmpeg module.

**Comment by stuckless** [comment]
Interestingly enough, the mplayer implementation on the desktop, uses a mplayer module to achieve this.  I'm more of a java guy than a c guy, so I was hoping for a bridge ;)  thx.
