### ISSUE TITLE
Library from jcenter not working on Android 6

### ISSUE THREAD

**Issue by mvasilchuk** [Bilibili/ijkplayer#518]
Hi.
I'm trying to use your media player in my project. But I found that libaries from jcenter not working on Android 6, because it can't load native libs.
What I do:

    dependencies {
        compile 'tv.danmaku.ijk.media:ijkplayer-java:0.4.1'
        compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.4.1'
    }

And when I try to use the player I get:

    java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.sample.testing-2/lib/x86/libijkffmpeg.so: has text relocations

I think this is because of a [new restriction in Android 6](https://developer.android.com/intl/ko/about/versions/marshmallow/android-6.0-changes.html#behavior-runtime).

**Comment by erwinshao** [comment]
I also encountered the same problem
04 22:04:09.129 E/AndroidRuntime( 1953): java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/tv.danmaku.ijk.media.demo-1/lib/arm/libijkffmpeg.so: has text relocations

**Comment by Android4MediaPlayer** [comment]
which devices?

**Comment by mvasilchuk** [comment]
I tested it on Android emulator from SDK (x86).

**Comment by Android4MediaPlayer** [comment]
try to remove x86 library

**Comment by mvasilchuk** [comment]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.sample.testing-1/base.apk"],nativeLibraryDirectories=[/data/app/com.sample.testing-1/lib/x86, /data/app/com.sample.testing-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libijkffmpeg.so"

**Comment by Android4MediaPlayer** [comment]
try to remove x86 folder

**Comment by mvasilchuk** [comment]
I tried to remove it. See the error test in my previous message.

**Comment by xiejinglan** [comment]
@mvasilchuk 
I think maybe you can try to download the source code and compile it.

**Comment by bbcallen** [comment]
This is an FFmpeg issue.
Submit a patch to FFmpeg, or wait for some FFmpeg developer to fix this issue.

**Comment by NoGirlFriendException** [comment]
是不是这个问题还没有解决。都是泪. we see it again.

**Comment by DanielXiao123** [comment]
咋解决啊，到底

**Comment by huangyuekai** [comment]
it will aroses just in emulator,but not in phone,
if emulator do not support ffmpeg.....?
