### ISSUE TITLE
Fatal error on elcapitan and lipo

### ISSUE THREAD

**Issue by linked67** [Bilibili/ijkplayer#519]
The default git clone compile fine but i have swap the lite config with the default and get this on the very end:

INSTALL	libavutil/xtea.h
INSTALL	libavutil/tea.h
INSTALL	libavutil/lzo.h
INSTALL	libavutil/avconfig.h
INSTALL	libavutil/ffversion.h
INSTALL	libavutil/libavutil.pc
lipo archs: armv7 arm64 i386 x86_64
Architectures in the fat file: /Users/leo/git/ijkplayer/ios/build/universal/lib/libavcodec.a are: armv7 i386 x86_64 arm64 
skip libavfilter.a of armv7
skip libavfilter.a of arm64
skip libavfilter.a of i386
skip libavfilter.a of x86_64
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: no input files specified
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo [input_file] ... [-arch <arch_type> input_file] ... [-info] [-detailed_info] [-output output_file] [-create] [-arch_blank <arch_type>] [-thin <arch_type>] [-remove <arch_type>] ... [-extract <arch_type>] ... [-extract_family <arch_type>] ... [-verify_arch <arch_type> ...] [-replace <arch_type> <file_name>] ...

**Comment by bbcallen** [comment]
Try "sh compile-ffmpeg.sh clean" after configure changed.

**Comment by linked67** [comment]
I have try this and a new git clone into a new folder without luck. I only have swap the configuration file light/defaut. With original it works, with swaped files, it crash. Maybe a elcapitan problem ?

**Comment by bbcallen** [comment]
Blind fixed: 8a577a5a0edaaafc607b2cb1bbf79e74095ccc37
Not tested.

**Comment by linked67** [comment]
It compile fine now but i have a black screen now, the log show it's playing, weird.
