### ISSUE TITLE
RTSP protocol not found on ios

### ISSUE THREAD

**Issue by linked67** [Bilibili/ijkplayer#520]
If i remember well last time i compiled, to enable rtsp i just had to enable rtp in the light config like this:

    export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=rtp"

I have try to clean build but it still complain about rtsp protocol not found.
Switching back to old compiled version works.

Any idea where to look ?

**Comment by bbcallen** [comment]
"./configure --list-demuxers", in ffmpeg directory.

**Comment by linked67** [comment]
I have this:
./configure --list-demuxers
aa			g722			mpc8
aac			g723_1			mpegps
ac3			g729			mpegts
act			gif			mpegtsraw
adf			gsm			mpegvideo
adp			gxf			mpjpeg
adx			h261			mpl2
aea			h263			mpsub
afc			h264			msnwc_tcp
aiff			hevc			mtv
amr			hls			mv
anm			hnm			mvi
apc			ico			mxf
ape			idcin			mxg
apng			idf			nc
aqtitle			iff			nistsphere
asf			ilbc			nsv
asf_o			image2			nut
ass			image2_alias_pix	nuv
ast			image2_brender_pix	ogg
au			image2pipe		oma
avi			image_bmp_pipe		paf
avisynth		image_dds_pipe		pcm_alaw
avr			image_dpx_pipe		pcm_f32be
avs			image_exr_pipe		pcm_f32le
bethsoftvid		image_j2k_pipe		pcm_f64be
bfi			image_jpeg_pipe		pcm_f64le
bfstm			image_jpegls_pipe	pcm_mulaw
bink			image_pictor_pipe	pcm_s16be
bintext			image_png_pipe		pcm_s16le
bit			image_qdraw_pipe	pcm_s24be
bmv			image_sgi_pipe		pcm_s24le
boa			image_sunrast_pipe	pcm_s32be
brstm			image_tiff_pipe		pcm_s32le
c93			image_webp_pipe		pcm_s8
caf			ingenient		pcm_u16be
cavsvideo		ipmovie			pcm_u16le
cdg			ircam			pcm_u24be
cdxl			iss			pcm_u24le
cine			iv8			pcm_u32be
concat			ivf			pcm_u32le
data			jacosub			pcm_u8
daud			jv			pjs
dfa			latm			pmp
dirac			libgme			pva
dnxhd			libmodplug		pvf
dsf			libnut			qcp
dsicin			libquvi			r3d
dss			live_flv		rawvideo
dts			lmlm4			realtext
dtshd			loas			redspark
dv			lrc			rl2
dvbsub			lvf			rm
dxa			lxf			roq
ea			m4v			rpl
ea_cdata		matroska		rsd
eac3			mgsts			rso
epaf			microdvd		rtp
ffm			mjpeg			rtsp
ffmetadata		mlp			sami
filmstrip		mlv			sap
flac			mm			sbg
flic			mmf			sdp
flv			mov			sdr2
fourxm			mp3			segafilm
frm			mpc			shorten
siff			tedcaptions		w64
sln			thp			wav
smacker			tiertexseq		wc3
smjpeg			tmv			webm_dash_manifest
smush			truehd			webvtt
sol			tta			wsaud
sox			tty			wsvqa
spdif			txd			wtv
srt			vc1			wv
stl			vc1t			xa
str			vivo			xbin
subviewer		vmd			xmv
subviewer1		vobsub			xwma
sup			voc			yop
swf			vplayer			yuv4mpegpipe
tak			vqf

**Comment by Android4MediaPlayer** [comment]
./configure --list-demuxers
aac			gif			mpegvideo
ac3			gsm			mpjpeg
act			gxf			mpl2
adf			h261			mpsub
adp			h263			msnwc_tcp
adx			h264			mtv
aea			hevc			mv
afc			hls			mvi
aiff			hnm			mxf
amr			ico			mxg
anm			idcin			nc
apc			idf			nistsphere
ape			iff			nsv
apng			ilbc			nut
aqtitle			image2			nuv
asf			image2_alias_pix	ogg
ass			image2_brender_pix	oma
ast			image2pipe		paf
au			image_bmp_pipe		pcm_alaw
avi			image_dpx_pipe		pcm_f32be
avisynth		image_exr_pipe		pcm_f32le
avr			image_j2k_pipe		pcm_f64be
avs			image_jpeg_pipe		pcm_f64le
bethsoftvid		image_jpegls_pipe	pcm_mulaw
bfi			image_pictor_pipe	pcm_s16be
bink			image_png_pipe		pcm_s16le
bintext			image_qdraw_pipe	pcm_s24be
bit			image_sgi_pipe		pcm_s24le
bmv			image_sunrast_pipe	pcm_s32be
boa			image_tiff_pipe		pcm_s32le
brstm			image_webp_pipe		pcm_s8
c93			ingenient		pcm_u16be
caf			ipmovie			pcm_u16le
cavsvideo		ircam			pcm_u24be
cdg			iss			pcm_u24le
cdxl			iv8			pcm_u32be
cine			ivf			pcm_u32le
concat			jacosub			pcm_u8
data			jv			pjs
daud			latm			pmp
dfa			libgme			pva
dirac			libmodplug		pvf
dnxhd			libnut			qcp
dsf			libquvi			r3d
dsicin			live_flv		rawvideo
dss			lmlm4			realtext
dts			loas			redspark
dtshd			lrc			rl2
dv			lvf			rm
dvbsub			lxf			roq
dxa			m4v			rpl
ea			matroska		rsd
ea_cdata		mgsts			rso
eac3			microdvd		rtp
epaf			mjpeg			rtsp
ffm			mlp			sami
ffmetadata		mlv			sap
filmstrip		mm			sbg
flac			mmf			sdp
flic			mov			sdr2
flv			mp3			segafilm
fourxm			mpc			shorten
frm			mpc8			siff
g722			mpegps			sln
g723_1			mpegts			smacker
g729			mpegtsraw		smjpeg
smush			tmv			wc3
sol			truehd			webm_dash_manifest
sox			tta			webvtt
spdif			tty			wsaud
srt			txd			wsvqa
stl			vc1			wtv
str			vc1t			wv
subviewer		vivo			xa
subviewer1		vmd			xbin
sup			vobsub			xmv
swf			voc			xwma
tak			vplayer			yop
tedcaptions		vqf			yuv4mpegpipe
thp			w64
tiertexseq		wav

**Comment by Android4MediaPlayer** [comment]
epaf microdvd   rtp
ffm mjpeg    rtsp

**Comment by linked67** [comment]
Yes rtp/rtsp is listed, then why did it complain it's a protocol not found ???

**Comment by bbcallen** [comment]
Because you didn't enable rtsp.

**Comment by linked67** [comment]
If the line below don't enable it, how then ?
   
    export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=rtp"

**Comment by bbcallen** [comment]
maybe 
```
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=rtsp"
```

**Comment by linked67** [comment]
Still protocol not found with both lines (your line and mine).
I just have to use the universal folder to take compiled changes, right ? It's to avoid a lot of copy paste.

**Comment by Zard1096** [comment]
If is iOS new version,try to remove ```FF_REGISTER_PROTOCOL(async)``` 
#495

**Comment by YangYuZhe** [comment]
IOS9_SDK, how to modify the compile-ffmpeg.sh?
here is the code:
FF_ALL_ARCHS_IOS9_SDK="armv7 armv7s arm64 i386 x86_64"

FF_ALL_ARCHS=$FF_ALL_ARCHS_IOS9_SDK


and Log:
FF_ALL_ARCHS = armv7 armv7s arm64 i386 x86_64
compile-ffmpeg.sh: line 144: cd: ffmpeg-armv7: No such file or directory
compile-ffmpeg.sh: line 144: cd: ffmpeg-armv7s: No such file or directory
compile-ffmpeg.sh: line 144: cd: ffmpeg-arm64: No such file or directory
compile-ffmpeg.sh: line 144: cd: ffmpeg-i386: No such file or directory
compile-ffmpeg.sh: line 144: cd: ffmpeg-x86_64: No such file or directory

**Comment by Zard1096** [comment]
Have you run init-ios.sh?

**Comment by YangYuZhe** [comment]
:( alright... I found I was totally wrong, now I will build it from start,thx

**Comment by YangYuZhe** [comment]
Also,Is it possible for me to get CVImageBufferRef by using this player?if is, and how?
