### ISSUE TITLE
android 11 播放崩溃

### ISSUE THREAD

**Issue by huohuoyoyo** [bilibili/ijkplayer#5202]
![image](https://user-images.githubusercontent.com/12482839/105956766-40f2d280-60b3-11eb-993b-9c296283b8a9.png)
![122](https://user-images.githubusercontent.com/12482839/105956944-7b5c6f80-60b3-11eb-9389-53bbc3958daa.png)

**Comment by raymond1012** [comment]
fixed

**Comment by MinTate** [comment]
> fixed
您好，看了一下最新的修改：https://github.com/bilibili/ijkplayer/commit/e99d640e5fe94c65132379307f92d7180bcde8e7，可否问一下，这样修改的原因是什么呢？

**Comment by MinTate** [comment]
您好，看了一下最新的修改：https://github.com/bilibili/ijkplayer/commit/e99d640e5fe94c65132379307f92d7180bcde8e7，可否问一下，这样修改的原因是什么呢？

**Comment by wp2463496** [comment]
![image](https://user-images.githubusercontent.com/13133220/144446667-a5668d0a-981f-4c92-84b5-9fcc45dacd59.png)
小米Android 11 报错闪退，请问有方案吗？
