### ISSUE TITLE
视频格式m3u8，ts音频格式AAC，播放时有画面没声音。日志：Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels, fltp): unspecified sample rate

### ISSUE THREAD

**Issue by isKotLin** [bilibili/ijkplayer#5208]
m3u8视频格式，ts音频AAC，播放时有画面没声音。日志：Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels, fltp): unspecified sample rate

**Comment by lingmoking** [comment]
你好，请问你是怎么解决这个问题的

**Comment by fjx-xxx** [comment]
你好，可以解答一下如何解决这个问题的吗，
