### ISSUE TITLE
iOS device restart when playing video

### ISSUE THREAD

**Issue by sarahzuo** [Bilibili/ijkplayer#521]
The issue confused me for few months, sometimes when playing video on iOS device (no finger touch, just put device on table and playing video) suddenly the device black screen and restart itself (not only crash the app, but the iPhone/iPad power off then power on), and I don’t know how to get any log in this situation, so I am not sure whether the issue caused by ijkPlayer.
At first I use the version k0.2.3, for avoiding the issue, I use the version k0.4.1, but the restart issue occurs more frequently.
Anybody have issue like mine?

**Comment by Zard1096** [comment]
Me too.
But not only for ijk,sometimes I debug my app include ijk then open like bilibili or youku watch video apps also can cause this crash.Probably due to ffmpeg confuse, I'm not sure yet.
@bbcallen

**Comment by sarahzuo** [comment]
@Zard1096  Do you know to get the log when iOS device restart or after restart in this situation?

**Comment by Zard1096** [comment]
I use iTools Pro,but failed in catching restart log.

**Comment by sarahzuo** [comment]
Before I forget to call [self.IJKFFMoviePlayerController shutdown] when I remove a IJKFFMoviePlayerController. I think it's maybe the  reason of restart issue (not very sure). 
@Zard1096  check whether you call "shutdown" when remove a IJKFFMoviePlayerController.

**Comment by bbcallen** [comment]
If you could reproduce this problem, maybe you could redirect logs to local file, to see what had happen.

**Comment by sarahzuo** [comment]
I use ipod touch 5 to run ijkplayer demo (k0.4.1) to play the the following video:
http://pl.youku.com/playlist/m3u8?ts=1443491023&keyframe=0&vid=XNjQzOTIzMDYw&type=hd2&sid=8443491023806201b57e9&token=2352&ctype=12&did=a8549bc94f573eb195fecf2cf612ce43&ev=1&oip=3673456916&ep=eiaQGU2EV84C5ivfjjwZZn7ncyIGXJZ0rH7P%2FrYbSsZQIa%2FQmz3UxQ%3D%3D

**Comment by sarahzuo** [comment]
Finaly! I found the reason－－CPU usage too high, and the high cpu usage is caused by option modify: I change ：options.skipLoopFilter  = IJK_AVDISCARD_DEFAULT;
    options.skipFrame       = IJK_AVDISCARD_DEFAULT;
