### ISSUE TITLE
编译时出现error: ijksoundtouch/ijksoundtouch_wrap.h: No such file or directory，导致编译失败

### ISSUE THREAD

**Issue by ZuoYiGeHeShang** [bilibili/ijkplayer#5219]
liunx_one@liunx-one-virtual-machine:~/ijkplayer-android/android$ ./compile-ijk.sh all
profiler build: NO

[armeabi] Compile thumb  : ijkplayer <= ff_ffplay.c
[armeabi] Compile thumb  : ijkplayer <= ijkmediadatasource.c
[armeabi] Compile thumb  : ijkplayer <= ijkio.c
[armeabi] Compile thumb  : ijkplayer <= ijkiomanager.c
[armeabi] Compile thumb  : ijkplayer <= ijkiocache.c
[armeabi] Compile thumb  : ijkplayer <= ijkioffio.c
[armeabi] Compile thumb  : ijkplayer <= ijkioandroidio.c
[armeabi] Compile thumb  : ijkplayer <= ijkioprotocol.c
[armeabi] Compile thumb  : ijkplayer <= ijkioapplication.c
/home/liunx_one/ijkplayer-android/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:78:46: fatal error: ijksoundtouch/ijksoundtouch_wrap.h: No such file or directory
 #include "ijksoundtouch/ijksoundtouch_wrap.h"

检查是jkplayer/ijkmedia/ijkplayer/ff_ffplay.c中引入了#include "ijksoundtouch/ijksoundtouch_wrap.h"，但是工程中没有这个文件。

**Comment by HelloPing** [comment]
怎么解决的?
