### ISSUE TITLE
怎么精简ffmpeg？

### ISSUE THREAD

**Issue by hwpo** [Bilibili/ijkplayer#522]
用ijkplayer替换了原生播放器以后，apk的大小增加了3、4M
我只用到其中的音频解码部分，如何精简ffmpeg？

**Comment by Android4MediaPlayer** [comment]
你可以精简ffmpeg那块，主要是ffmpeg库大小大些

**Comment by xiejinglan** [comment]
配置configure吧

**Comment by Android4MediaPlayer** [comment]
把所有不需要的都disable，把你需要的音频解码eanble即可

**Comment by hwpo** [comment]
@Android4MediaPlayer @xiejinglan 
谢谢指点，有些东西disable之后编译会有问题，我调试下，弄好了之后把configure发到这里
