### ISSUE TITLE
android 编译出错

### ISSUE THREAD

**Issue by asawalker** [Bilibili/ijkplayer#524]
root@iZ11nba7qlwZ:~/ijkplayer/ijkplayer/android# cd contrib/
root@iZ11nba7qlwZ:~/ijkplayer/ijkplayer/android/contrib# ./compile-ffmpeg.sh clean
====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a x86 arm64
FF_ACT_ARCHS = FF_ACT_ARCHS_64

/root/ijkplayer/ijkplayer/android/contrib
/root/ijkplayer/ijkplayer/android/contrib
/root/ijkplayer/ijkplayer/android/contrib
/root/ijkplayer/ijkplayer/android/contrib
root@iZ11nba7qlwZ:~/ijkplayer/ijkplayer/android/contrib# ./compile-ffmpeg.sh all
====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a x86 arm64
FF_ACT_ARCHS = armv5 armv7a x86 arm64

====================
[*] check env armv5
====================
build on Linux x86_64
ANDROID_SDK=/root/android_env/sdk/adt-bundle-linux-x86-20130917/sdk
ANDROID_NDK=/root/android_env/ndk/android-ndk-r9b
NDKr9b detected

--------------------
[*] make NDK standalone toolchain
--------------------
/root/android_env/ndk/android-ndk-r9b/build/tools/make-standalone-toolchain.sh: line 244: /root/android_env/ndk/android-ndk-r9b/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/bin/arm-linux-androideabi-gcc: No such file or directory
Copying prebuilt binaries...
Copying sysroot headers and libraries...
Copying libstdc++ headers and libraries...
Copying files to: /root/ijkplayer/ijkplayer/android/contrib/build/ffmpeg-armv5/toolchain
Cleaning up...
Done.

--------------------
[*] check ffmpeg env
--------------------

--------------------
[*] configurate ffmpeg
--------------------
/root/ijkplayer/ijkplayer/android/contrib/build/ffmpeg-armv5/toolchain/bin//arm-linux-androideabi-gcc
arm-linux-androideabi-gcc is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
root@iZ11nba7qlwZ:~/ijkplayer/ijkplayer/android/contrib# ^C
root@iZ11nba7qlwZ:~/ijkplayer/ijkplayer/android/contrib#

**Comment by bbcallen** [comment]
Try NDK r10e
