### ISSUE TITLE
iOS拖动播放崩溃,FF4.0,视频中含AVMEDIA_TYPE_DATA流，崩溃定位到avformat_seek_file

### ISSUE THREAD

**Issue by ai260697793** [Bilibili/ijkplayer#5251]
iOS拖动播放崩溃,FF4.0,视频中含AVMEDIA_TYPE_DATA流，崩溃定位到avformat_seek_file

**Comment by ai260697793** [comment]
> iOS拖动播放崩溃,FF4.0,视频中含AVMEDIA_TYPE_DATA流，崩溃定位到avformat_seek_file

换用最新的ff4.0--ijk0.8.8--20210426--001，无此问题

**Comment by lypoint** [comment]
> > iOS拖动播放崩溃,FF4.0,视频中含AVMEDIA_TYPE_DATA流，崩溃定位到avformat_seek_file
> 
> 换用最新的ff4.0--ijk0.8.8--20210426--001，无此问题

请问哪里有ff4.0--ijk0.8.8--20210426--001？

**Comment by taojeff** [comment]
> > iOS拖动播放崩溃,FF4.0,视频中含AVMEDIA_TYPE_DATA流，崩溃定位到avformat_seek_file
> 
> 换用最新的ff4.0--ijk0.8.8--20210426--001，无此问题
 为什么我切成4.0还是奔溃在那个地方

**Comment by ai260697793** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我是莫煌，您的邮件我已经收到，我会尽快查看并且回复您的。
