### ISSUE TITLE
怎么监控播放的流量

### ISSUE THREAD

**Issue by yanlj** [Bilibili/ijkplayer#527]
我想监控我直播中消耗的流量，应该怎么监控呢

**Comment by lslxdx** [comment]
ff_ffplay.c的read_thread函数中，packet_queue_put(&is->audioq, pkt);和packet_queue_put(&is->videoq, pkt);和av_free_packet(pkt);，可以大概算出来流量了

**Comment by linjiansheng** [comment]
@yanlj @bbcallen 
同这个https://github.com/Bilibili/ijkplayer/issues/620
如果通过这个 av_read_frame 计算流量，感觉不是十分准确

**Comment by Michael-Lfx** [comment]
I think you cannot just count those packets which are putted into video or audio queue. All the data gather by av_read_frame() and before the funcation call like probe and  data of internal buffer of av_read_frame()  should calculate too.
