### ISSUE TITLE
android ijkplayer problem

### ISSUE THREAD

**Issue by dieyidezui** [Bilibili/ijkplayer#528]
When using Ijkplayer, it seems that when I touch to pause video, the MediaController's pause button will not change its icon immediately.When it hides and shows again, it shows the right icon.The sample code's performance is same.But Android's native MediaPlayer works.
I research source code of MediaController and guess that when Ijkplayer's pause function and start function invoked, the isPlaying function will not change its value at once.
It really puzzled me.If my guess is right,it means that I have to drop MediaController or is there any solution to deal with it?

**Comment by bbcallen** [comment]
play/pause/seek request are scheduled asynchronized at low level.
So, it cannot be changed immediately, for now.
