### ISSUE TITLE
FFmpeg4.3什么时候可以支持呢

### ISSUE THREAD

**Issue by SivanLiu** [Bilibili/ijkplayer#5288]

**Comment by jeffzhou2000** [comment]
请参考https://github.com/zhouwg/kantv/tree/dev-baseon-latest-k0.8.8

这个分支在原始的ijkplayer 0.8.8上做了一些 bugfix与功能增强[https://github.com/zhouwg/kantv/blob/dev-baseon-latest-k0.8.8/NEWS.md](https://github.com/zhouwg/kantv/blob/dev-baseon-latest-k0.8.8/NEWS.md)，希望对开源社区有点用

**Comment by SivanLiu** [comment]
> 请参考https://github.com/zhouwg/kantv/tree/dev-baseon-latest-k0.8.8
> 
> 这个分支在原始的ijkplayer 0.8.8上做了一些 bugfix与功能增强https://github.com/zhouwg/kantv/blob/dev-baseon-latest-k0.8.8/NEWS.md，希望对开源社区有点用

谢谢，编译过了，能用，ffmpeg最新版本优化了不少东西

**Comment by zn123** [comment]
没有了

**Comment by trial** [comment]
> 请参考https://github.com/zhouwg/kantv/tree/dev-baseon-latest-k0.8.8
> 
> 这个分支在原始的ijkplayer 0.8.8上做了一些 bugfix与功能增强https://github.com/zhouwg/kantv/blob/dev-baseon-latest-k0.8.8/NEWS.md，希望对开源社区有点用

404了，请问还能重新分享一下吗

**Comment by Echo-Joker** [comment]
有没有编译好的ijk包ffmpeg的版本是4.3.1
