### ISSUE TITLE
退出时报错

### ISSUE THREAD

**Issue by Long888** [Bilibili/ijkplayer#529]
LOG:
10-10 17:46:11.378: I/ACodec(11241): video render this buffer -1209310304
10-10 17:46:11.378: I/ACodec(11241): video render this buffer -1209310304 ok
10-10 17:46:11.418: I/ACodec(11241): video render this buffer -1209358152
10-10 17:46:11.418: I/ACodec(11241): video render this buffer -1209358152 ok
10-10 17:46:11.428: D/IJKMEDIA(11241): ijkmp_stop()
10-10 17:46:11.428: D/IJKMEDIA(11241): ijkmp_stop()=0
10-10 17:46:11.428: D/IJKMEDIA(11241): IjkMediaPlayer_release
10-10 17:46:11.428: D/IJKMEDIA(11241): ijkmp_set_android_surface(surface=0x0)
10-10 17:46:11.428: D/IJKMEDIA(11241): ffpipeline_set_surface()
10-10 17:46:11.428: D/IJKMEDIA(11241): ijkmp_set_android_surface(surface=0x0)=void
10-10 17:46:11.428: D/IJKMEDIA(11241): ijkmp_shutdown_l()
10-10 17:46:11.428: D/IJKMEDIA(11241): wait for read_tid
10-10 17:46:11.428: D/IJKMEDIA(11241): message_loop exit
10-10 17:46:11.428: D/dalvikvm(11241): threadid=59: thread exiting, not yet detached (count=0)
10-10 17:46:11.428: I/IJKMEDIA(11241): MediaCodec: enqueue_thread_func: exit: 0
10-10 17:46:11.428: D/dalvikvm(11241): threadid=56: thread exiting, not yet detached (count=0)
10-10 17:46:11.518: D/dalvikvm(11241): threadid=54: thread exiting, not yet detached (count=0)
10-10 17:46:11.518: D/IJKMEDIA(11241): SDL_AMediaCodecJava_stop
10-10 17:46:11.808: I/IJKMEDIA(11241): MediaCodec: func_run_sync: exit: 0
10-10 17:46:11.808: D/dalvikvm(11241): threadid=55: thread exiting, not yet detached (count=0)
10-10 17:46:11.808: D/IJKMEDIA(11241): Statistics: 3181148 bytes read, 0 seeks
10-10 17:46:11.808: D/dalvikvm(11241): threadid=36: thread exiting, not yet detached (count=0)
10-10 17:46:11.808: D/IJKMEDIA(11241): wait for video_refresh_tid
10-10 17:46:11.808: W/System.err(11241): java.lang.IllegalStateException
10-10 17:46:11.808: W/System.err(11241): 	at android.media.MediaCodec.releaseOutputBuffer(Native Method)
10-10 17:46:11.808: W/System.err(11241): 	at tv.danmaku.ijk.media.player.IjkMediaPlayer._release(Native Method)
10-10 17:46:11.808: W/System.err(11241): 	at tv.danmaku.ijk.media.player.IjkMediaPlayer.release(IjkMediaPlayer.java:580)
10-10 17:46:11.808: W/System.err(11241): 	at tv.danmaku.ijk.media.widget.IjkVideoView.stopPlayback(IjkVideoView.java:268)
10-10 17:46:11.808: W/System.err(11241): 	at org.well.newlive.LivePlayerActivity.finishActivity(LivePlayerActivity.java:727)
10-10 17:46:11.808: W/System.err(11241): 	at org.well.newlive.LivePlayerActivity.onKeyUp(LivePlayerActivity.java:769)
10-10 17:46:11.808: W/System.err(11241): 	at android.view.KeyEvent.dispatch(KeyEvent.java:2894)
10-10 17:46:11.808: W/System.err(11241): 	at android.app.Activity.dispatchKeyEvent(Activity.java:2447)
10-10 17:46:11.808: W/System.err(11241): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1962)
10-10 17:46:11.808: W/System.err(11241): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3854)
10-10 17:46:11.808: W/System.err(11241): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3828)
10-10 17:46:11.808: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3401)
10-10 17:46:11.808: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3451)
10-10 17:46:11.808: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3420)
10-10 17:46:11.808: W/System.err(11241): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3527)
10-10 17:46:11.808: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3428)
10-10 17:46:11.808: W/System.err(11241): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3584)
10-10 17:46:11.808: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3401)
10-10 17:46:11.808: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3451)
10-10 17:46:11.808: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3420)
10-10 17:46:11.808: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3428)
10-10 17:46:11.818: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3401)
10-10 17:46:11.818: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3451)
10-10 17:46:11.818: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3420)
10-10 17:46:11.818: W/System.err(11241): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3560)
10-10 17:46:11.818: W/System.err(11241): 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3720)
10-10 17:46:11.818: W/System.err(11241): 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2013)
10-10 17:46:11.818: W/System.err(11241): 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1707)
10-10 17:46:11.818: W/System.err(11241): 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1698)
10-10 17:46:11.818: W/System.err(11241): 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:1990)
10-10 17:46:11.818: W/System.err(11241): 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
10-10 17:46:11.818: W/System.err(11241): 	at android.os.MessageQueue.nativePollOnce(Native Method)
10-10 17:46:11.818: W/System.err(11241): 	at android.os.MessageQueue.next(MessageQueue.java:138)
10-10 17:46:11.818: W/System.err(11241): 	at android.os.Looper.loop(Looper.java:123)
10-10 17:46:11.818: W/System.err(11241): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
10-10 17:46:11.818: W/System.err(11241): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-10 17:46:11.818: W/System.err(11241): 	at java.lang.reflect.Method.invoke(Method.java:515)
10-10 17:46:11.818: W/System.err(11241): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
10-10 17:46:11.818: W/System.err(11241): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
10-10 17:46:11.818: W/System.err(11241): 	at dalvik.system.NativeStart.main(Native Method)
10-10 17:46:11.818: E/IJKMEDIA(11241): SDL_AMediaCodecJava_releaseOutputBuffer: releaseOutputBuffer
10-10 17:46:11.818: E/IJKMEDIA(11241): SDL_Overlay(ffmpeg): overlay_free_l(0x70f9b2b0)
10-10 17:46:11.818: E/IJKMEDIA(11241): SDL_Overlay(ffmpeg): overlay_free_l(0x68d71540)
10-10 17:46:11.818: W/System.err(11241): java.lang.IllegalStateException
10-10 17:46:11.818: W/System.err(11241): 	at android.media.MediaCodec.releaseOutputBuffer(Native Method)
10-10 17:46:11.818: W/System.err(11241): 	at tv.danmaku.ijk.media.player.IjkMediaPlayer._release(Native Method)
10-10 17:46:11.818: W/System.err(11241): 	at tv.danmaku.ijk.media.player.IjkMediaPlayer.release(IjkMediaPlayer.java:580)
10-10 17:46:11.818: W/System.err(11241): 	at tv.danmaku.ijk.media.widget.IjkVideoView.stopPlayback(IjkVideoView.java:268)
10-10 17:46:11.818: W/System.err(11241): 	at org.well.newlive.LivePlayerActivity.finishActivity(LivePlayerActivity.java:727)
10-10 17:46:11.828: W/System.err(11241): 	at org.well.newlive.LivePlayerActivity.onKeyUp(LivePlayerActivity.java:769)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.KeyEvent.dispatch(KeyEvent.java:2894)
10-10 17:46:11.828: W/System.err(11241): 	at android.app.Activity.dispatchKeyEvent(Activity.java:2447)
10-10 17:46:11.828: W/System.err(11241): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1962)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3854)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3828)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3401)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3451)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3420)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3527)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3428)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3584)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3401)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3451)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3420)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3428)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3401)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3451)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3420)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3560)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3720)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2013)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1707)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1698)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:1990)
10-10 17:46:11.828: W/System.err(11241): 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
10-10 17:46:11.838: W/System.err(11241): 	at android.os.MessageQueue.nativePollOnce(Native Method)
10-10 17:46:11.838: W/System.err(11241): 	at android.os.MessageQueue.next(MessageQueue.java:138)
10-10 17:46:11.838: W/System.err(11241): 	at android.os.Looper.loop(Looper.java:123)
10-10 17:46:11.838: W/System.err(11241): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
10-10 17:46:11.838: W/System.err(11241): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-10 17:46:11.838: W/System.err(11241): 	at java.lang.reflect.Method.invoke(Method.java:515)
10-10 17:46:11.838: W/System.err(11241): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
10-10 17:46:11.838: W/System.err(11241): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
10-10 17:46:11.838: W/System.err(11241): 	at dalvik.system.NativeStart.main(Native Method)
10-10 17:46:11.838: E/IJKMEDIA(11241): SDL_AMediaCodecJava_releaseOutputBuffer: releaseOutputBuffer
10-10 17:46:11.838: E/IJKMEDIA(11241): SDL_Overlay(ffmpeg): overlay_free_l(0x69d11d20)
10-10 17:46:11.838: D/IJKMEDIA(11241): ijkmp_shutdown_l()=void
10-10 17:46:11.838: D/IJKMEDIA(11241): ijkmp_dec_ref(): ref=0
10-10 17:46:11.838: D/IJKMEDIA(11241): ijkmp_shutdown_l()
10-10 17:46:11.838: D/IJKMEDIA(11241): ijkmp_shutdown_l()=void
10-10 17:46:11.838: I/IJKMEDIA(11241): SDL_AMediaCodecJava_delete
10-10 17:46:11.868: D/IJKMEDIA(11241): IjkMediaPlayer_native_profileEnd
10-10 17:46:11.868: W/IJKMEDIA(11241): moncleanu already called
10-10 17:46:11.868: D/IJKMEDIA(11241): IjkMediaPlayer_native_profileEnd
10-10 17:46:11.868: W/IJKMEDIA(11241): moncleanu already called
10-10 17:46:11.898: A/libc(11241): invalid address or address of corrupt block 0x6a01a438 passed to dlfree
10-10 17:46:11.898: A/libc(11241): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 11814 (Thread-608)

code：
			if (videoView != null) {
				videoView .stopPlayback();
				videoView .release(true);
				videoView .stopBackgroundPlay();
				IjkMediaPlayer.native_profileEnd();
			}

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
