### ISSUE TITLE
Latest code from repository branch "master" on iOS gives code compilation errors

### ISSUE THREAD

**Issue by pantunes** [Bilibili/ijkplayer#530]
ERROR: No member name called "vfileter0"

if (ffp->vfilter0) {
        GROW_ARRAY(ffp->vfilters_list, ffp->nb_vfilters);
        ffp->vfilters_list[ffp->nb_vfilters - 1] = ffp->vfilter0;
}

If I run code from "latest" is all fine!

Is the "master" branch code not reliable?

Thank you

**Comment by bbcallen** [comment]
Nothing is reliable before 1.0.0 :)

**Comment by pantunes** [comment]
I'll do that, thank you!

**Comment by pantunes** [comment]
Worked good. Thank you very much and keep up the good work!
