### ISSUE TITLE
ijkplayer play rtmp stream reconnect

### ISSUE THREAD

**Issue by maytrue** [Bilibili/ijkplayer#531]
Does ijkplayer support reeconnect to rtmp server, when a encoder resume publishing to rtmp server(stop publishing first , and republish to rtmp server) ?

**Comment by bbcallen** [comment]
ijkplayer doesn't support, but I don't know if ffmpeg supports.

**Comment by linjiansheng** [comment]
ffplay support

**Comment by maytrue** [comment]
ffplay does not supports. When encoder resume publishing to rtmp server, ffplay does not reconnect to rtmp server and just stay still
