### ISSUE TITLE
iOS can't play rtsp

### ISSUE THREAD

**Issue by YangYuZhe** [Bilibili/ijkplayer#532]
The log is:
===================
ijkmp_prepare_async()=0
ijkmp_start()
ijkmp_start()=-3
[FFPlayer @ 0x7f8473f74bd0] remove 'timeout' option for rtmp.
rtsp://218.204.223.237:554/live/1/0547424F573B085C/gsfp90ef4k0a6iap.sdp: Protocol not found

and I have enabled rtp before build

**Comment by bbcallen** [comment]
#520

**Comment by YangYuZhe** [comment]
It seems that the man haven't make the issue sovled...never mind
maybe I should use module-default.sh instead of module-lite.sh?Or also I should manually add something to module-default.sh before compiling? 
very appreciate!

**Comment by YangYuZhe** [comment]
Still is protocol not found with enabled rtp&rtsp ,lite-module,remove FF_REGISTER_PROTOCOL(async),
could someone plz HELP me
