### ISSUE TITLE
IjkVideoView无法拿到videoAspectRatio

### ISSUE THREAD

**Issue by robin820224** [Bilibili/ijkplayer#534]
我正在使用0.4.1版本ijkplayer-sample中的IjkVideoView类，这个类里面并没有提供获取原始视频比例的getAspectRatio方法，请问如何才能拿到原始的视频比例？

**Comment by Leon1809** [comment]
Yeah, I also have this concern. As I know, Vitamio Video Player can get this parameter, the aspect ratio  of the video source, such as 16 : 9, 4 : 3. Can ijkPlayer get this parameter?
