### ISSUE TITLE
YUV数据转RGB

### ISSUE THREAD

**Issue by panzhi1** [Bilibili/ijkplayer#5347]
请教大佬们，Android MediaCodec 硬解码 或者 ffmpeg软解码出的yuv数据格式，多种多样（yuv444,yuv420,yuv410d等），在不同手机上的转换结果还不一样，请问有什么办法处理吗？看了下ijkplayer 的gles渲染的地方也只是处理了YUV420p的格式，其他好像没有找到相关代码。如果有知道，感谢告知下

**Comment by alaiyeshi** [comment]
用libyuv做转换

**Comment by panzhi1** [comment]
libyuv  速度有点慢   特别在视频帧分辨率大的时候

**Comment by panzhi1** [comment]
我目前直接采用通过opengl将yuv转成rgb的方式的方案，看起来还不错

**Comment by alaiyeshi** [comment]
> 分辨

这部分libyuv有两个改进方向，一个是汇编优化，一个是把计算改查表，可以都做。4K情况下应该还是可以接受的。另外走OpenGL 用顶点渲染的vertax 走vec4计算，这个也很快
