### ISSUE TITLE
iOS上播放4K视频卡顿

### ISSUE THREAD

**Issue by cowcomic** [Bilibili/ijkplayer#5355]
使用iPhone拍摄了不同分辨率，不同帧率的视频，测试结果
4K的视频无论什么帧率都会卡顿
60帧的视频无论什么分辨率都会花屏

但是，慢动作视频虽然帧率更高，但是没事儿，能正常播放

也搜了之前的issue，iOS这边没发现有效的方案
求助

====================

上面是用的一个第三方包的ijk测试的
这两天用官方demo测试了一下
60帧视频没有花屏，看来是那个第三方的ijk版本问题
但是4K的视频还是卡顿，看起来应该是CPU处理不过来了，始终满载
1080P的视频XR的CPU就基本满载，但还能顺畅播放

**Comment by sizhugongzi** [comment]
楼主解决了吗?

**Comment by sizhugongzi** [comment]
楼主解决了吗?

**Comment by cowcomic** [comment]
> 楼主解决了吗?

改硬解优先，好了
