### ISSUE TITLE
k0.3.2.1 偶发性卡死

### ISSUE THREAD

**Issue by Mongolian** [Bilibili/ijkplayer#537]
当我在播放一个视频
http://video.dispatch.tc.qq.com/49517406/z0018uy9hci.m1.mp4?type=mp4&vkey=0F809CADD96ECB986775D96F6A56BE1EA728228176AC8216EDF588DFE192D089F841B935CCCFBE96444F8EE8B460B9FD9344B840522EF5E9AB4A2CB8686A9B158C25DD451C2B26A53B9C1F413146F0FDDA811D1D09A70A95&platform=11&br=127&fmt=msd&sp=0

会经常行的走下面的LOG 就没有任何响应了，请问这个是不是源本身就有问题，能有解决的办法么。

10-12 19:33:31.876    8081-8081/ D/IJKMEDIA﹕ IjkMediaPlayer_prepareAsync
10-12 19:33:31.876    8081-8081/ I/IJKMEDIA﹕ player-opts : mediacodec                   = 0
10-12 19:33:31.876    8081-8081/ I/IJKMEDIA﹕ player-opts : opensles                     = 0
10-12 19:33:31.876    8081-8081/ I/IJKMEDIA﹕ player-opts : overlay-format               = 842225234
10-12 19:33:31.876    8081-8081/ I/IJKMEDIA﹕ player-opts : framedrop                    = 1
10-12 19:33:31.876    8081-8081/ I/IJKMEDIA﹕ player-opts : start-on-prepared            = 0

**Comment by Android4MediaPlayer** [comment]
http://video.dispatch.tc.qq.com/49517406/z0018uy9hci.m1.mp4?type=mp4&vkey=0F809CADD96ECB986775D96F6A56BE1EA728228176AC8216EDF588DFE192D089F841B935CCCFBE96444F8EE8B460B9FD9344B840522EF5E9AB4A2CB8686A9B158C25DD451C2B26A53B9C1F413146F0FDDA811D1D09A70A95&platform=11&br=127&fmt=msd&sp=0: Server returned 403 Forbidden (access denied)

**Comment by Mongolian** [comment]
这个地址是有时效性的，用这个地址试下呢


http://video.dispatch.tc.qq.com/85156564/z0168tdcnqq.mp4?type=mp4&vkey=5DBFB348BA8D22B6E8C022B990CF124252AE9D580CF77FBB896CB0BE31E1F15F8F3541A8C54A57E836D1CF7A482DD2AA696E672549EF00DD13097C7A6E64BB34DACC3C61F048DF41319E27095616A4A107E8DA6B1490AEE2&platform=11&br=126&fmt=mp4&sp=0

**Comment by Android4MediaPlayer** [comment]
不是卡死吧，是收不到服务器回应流过来倒遇到了
