### ISSUE TITLE
寻 IJKMediaFrameworkWithSSL.framework 可以升级ffmpeg 4.4 的高手

### ISSUE THREAD

**Issue by zencodex** [Bilibili/ijkplayer#5374]
RT，寻可以搞定 iOS版 升级为 ffmpeg 4.4 的牛人。

**Comment by ProFive** [comment]
@zencodex How to upgrade the FFmpeg 4.4?

**Comment by zencodex** [comment]
I have fixed my issues without upgrade, but I also hope somebody could do this, thanks. closed issue.

**Comment by ProFive** [comment]
libavutil/hlsdecryptor.c:42:10: fatal error: 'openssl/aes.h' file not found
