### ISSUE TITLE
播放m3u8的时候seekto会从下一个ts片段开始播

### ISSUE THREAD

**Issue by 865394064** [Bilibili/ijkplayer#5383]
播放m3u8的时候seekto到某一个时间点，会从下一个ts片段开始播，这会导致有时候seekto时间差距很大，比如我第一个ts片段有20s我seek到5s的位置，直接就从下一个ts片段21s开始播放了，这有办法解决吗大佬们

**Comment by Adonis-Song** [comment]
seek是seek的关键帧吧， 你要看看怎么不用seek到关键帧
