### ISSUE TITLE
这不是个问题，帮助大家，增加librtmp

### ISSUE THREAD

**Issue by lyqaiym** [Bilibili/ijkplayer#542]
http://blog.csdn.net/lyqaizhy/article/details/49077027
这个方法，只能连接静态库.a，却不能连接动态库.so
有知道怎么连接的说一下

**Comment by Android4MediaPlayer** [comment]
ffmpeg默认链接的就是第三方动态库啊

**Comment by Android4MediaPlayer** [comment]
@lyqaiym 使用rtmp有延迟吗

**Comment by lyqaiym** [comment]
这个就是配置了一下sh文件，增加librtmp。并不是增加第三方动态库这个功能。
延迟比较低
rtmp://live.hkstv.hk.lxdns.com/live/hks
香港这个，没设置属性3 4秒。

**Comment by andyjmzheng** [comment]
@lyqaiym  你好。增加librtmp 。我按照你的方式，怎么编译不过呀。总会报 NDK_PROJECT_PATH 这个变量具体是什么呢？

**Comment by lyqaiym** [comment]
没有jni/Application.mk这个文件吧？

**Comment by andyjmzheng** [comment]
@lyqaiym 有啊 还是没有编译通过。总报这样的错误。
Android NDK: Your APP_BUILD_SCRIPT points to an unknown file: ./jni/Android.mk    
/home/jmzheng/tools/android-ndk-r9d/build/core/add-application.mk:187: *** Android NDK: Aborting...    .  Stop.

**Comment by andyjmzheng** [comment]
编译rtmpdump 总报这样的错误。
有人知道原因吗？
Android NDK: Your APP_BUILD_SCRIPT points to an unknown file: ./jni/Android.mk    
/home/jmzheng/tools/android-ndk-r9d/build/core/add-application.mk:187: *** Android NDK: Aborting...    .  Stop.
