### ISSUE TITLE
[Android] How to play audio only stream

### ISSUE THREAD

**Issue by ioleon13** [Bilibili/ijkplayer#544]
When i play audio only stream using ijkplayer, it can not receive buffering end message, so it can not play the stream. Was there any options to set when play audio only stream?

@bbcallen 
@Android4MediaPlayer
Thks!

**Comment by Android4MediaPlayer** [comment]
Yes,you can call API which is ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "vn", 1) to disable video.
refer to https://github.com/Bilibili/ijkplayer/blob/master/android/ijkplayer/ijkplayer-java/src/main/java/tv/danmaku/ijk/media/player/IjkMediaPlayer.java#L724
sample: https://github.com/Bilibili/ijkplayer/blob/master/android/ijkplayer/ijkplayer-sample/src/main/java/tv/danmaku/ijk/media/sample/widget/media/IjkVideoView.java#L326

**Comment by ioleon13** [comment]
Thanks!
I set the option which is ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "start-on-prepared", 1) to fix this problem.

**Comment by bbcallen** [comment]
Why do you wait for "buffering end message"?
There is no guarantee that this message is always sent.

http://developer.android.com/reference/android/media/MediaPlayer.html
You should always setOnPreparedListener() and start player in callback,

**Comment by ioleon13** [comment]
Yes, i start player in the onPrepared callback, but when i play audio only stream, it was not played just buffering, the ijkplayer log as follows:
D/IJKMEDIA(26804): FFP_MSG_PREPARED:
I/IJKMEDIA(26804): SDL_RunThread: [28031] ff_audio_dec
D/IJKMEDIA(26804): ffp_toggle_buffering_l: start
D/IJKMEDIA(26804): FFP_MSG_BUFFERING_START:
D/IJKMEDIA(26804): IjkMediaPlayer_start
D/IJKMEDIA(26804): ijkmp_start()
D/IJKMEDIA(26804): ijkmp_start()=0
D/IJKMEDIA(26804): ijkmp_get_msg: FFP_REQ_START
D/IJKMEDIA(26804): ijkmp_get_msg: FFP_REQ_START: start on fly
D/IJKMEDIA(26804): IjkMediaPlayer_start
D/IJKMEDIA(26804): ijkmp_start()
D/IJKMEDIA(26804): ijkmp_start()=0
D/IJKMEDIA(26804): ijkmp_pause()
D/IJKMEDIA(26804): ijkmp_pause()=0
D/IJKMEDIA(26804): ijkmp_get_msg: FFP_REQ_PAUSE

when i set the "start-on-prepared" option to 1, it can play automatically

**Comment by Android4MediaPlayer** [comment]
OK.

**Comment by bbcallen** [comment]
Log says, you called pause yourself.
```
D/IJKMEDIA(26804): ijkmp_start()
D/IJKMEDIA(26804): ijkmp_start()=0
D/IJKMEDIA(26804): ijkmp_pause()
D/IJKMEDIA(26804): ijkmp_pause()=0
D/IJKMEDIA(26804): ijkmp_get_msg: FFP_REQ_PAUSE
```
