### ISSUE TITLE
setSurface not working when using AIDL

### ISSUE THREAD

**Issue by boybeak** [Bilibili/ijkplayer#5458]
I need pass Surface across process, from main process to player process. But the first 2 times works fine. if change surface 3 times, it not working.

**Comment by boybeak** [comment]
OK，I find the solution myself. 
```java
interface IPlayer {
    void setSurface(inout Surface surface);
}
```
replace the parameter's modifier from `in` to `inout`.

**Comment by zuilintan** [comment]
Why? Why does it work?
