### ISSUE TITLE
MPMovieLoadStateStalled resume

### ISSUE THREAD

**Issue by linked67** [Bilibili/ijkplayer#546]
Now that i have the latest master running, i see that the player stop when connection is bad.
A previous version from around this summer just wait in some way and resume when data come back a couple of seconds after (maybe 5 or 10s).

Now i have the delegate loadStateDidChange called with MPMovieLoadStateStalled state.
This is a internal change of the player since i have no code to manage resume. I was surprised that the same stream just wait and resume while on VLC a too long time get to the next stream but IJKPlayer was just waiting and resuming perfect.

Any idea on a settings or something else to easy resume in this case like previously ?

**Comment by bbcallen** [comment]
set "timeout" and "reconnect" to avformat.

**Comment by YangYuZhe** [comment]
why would iOS use android stuff? when I import "ijkplayer_internal.h" a warning appeared in ijksdl_codec_android_mediacodec.h that jin.h file not found

**Comment by linked67** [comment]
You mean these lines in IJKFFOption.m ?

    [options setFormatOptionIntValue:1                  forKey:@"reconnect"];
    [options setFormatOptionIntValue:30 * 1000 * 1000   forKey:@"timeout"];

They have the same value as my "old" compiledplayer but the fresh compiled player don't resume.

On a side not, why is here a 0, is hw acceleration disabled ?

    [options setPlayerOptionIntValue:0      forKey:@"videotoolbox"];

**Comment by linked67** [comment]
Any idea since all this time ?
