### ISSUE TITLE
after disable CONFIG_AVFILTER, cannot get managed_frame

### ISSUE THREAD

**Issue by wqmijkplayer** [Bilibili/ijkplayer#549]
Dear all
    I implement some hw decoder, and don't use mediacodec in ijkplayer itself
    I disabled CONFIG_AVFILTER in ff_ffplay_config.h file
    but following error msg displayed:
    "OOM in opaque_obtain_managed_frame_buffer"
   "Cannot initialize the conversion context"
     could shed me any light on this issue?

**Comment by Android4MediaPlayer** [comment]
welcome to share your code or patch

**Comment by wqmijkplayer** [comment]
感谢回复。
我程序的逻辑是这样，
1. 根据codec_id判断是否是支持的硬解码，由 is_hw_video_codec函数进行判断
2. 在stream_component_open函数中调用自己设计的函数hw_video_decoder_init进行解码初始化，
hw_video_decoder_init函数是进行对android的omxcodec初始化
3. 在decoder_decode_frame函数中调用自己设计的函数hw_decode_video_frame进行硬件解码，
hw_decode_video_frame使用omxcodec得到解码后的frame
4. 在stream_component_close对数据进行 清理
但是在关掉CONFIG_AVFILTER 后，硬解码的解码后的frame无法显示，提示错误信息是在queue_picture时，overlay->opaque->managed_frame这个变量都是非法的。我想知道managed_frame是从哪里进行设置的？
非常感谢

static int decoder_decode_frame(FFPlayer *ffp, Decoder *d, AVFrame *frame, AVSubtitle *sub) {
    int got_frame = 0;

    do {
        int ret = -1;

        if (d->queue->abort_request)
            return -1;

        if (!d->packet_pending || d->queue->serial != d->pkt_serial) {
            AVPacket pkt;
            do {
                if (d->queue->nb_packets == 0)
                    SDL_CondSignal(d->empty_queue_cond);
                if (packet_queue_get_or_buffering(ffp, d->queue, &pkt, &d->pkt_serial, &d->finished) < 0)
                    return -1;
                if (pkt.data == flush_pkt.data) {
                    avcodec_flush_buffers(d->avctx);
                    d->finished = 0;
                    d->next_pts = d->start_pts;
                    d->next_pts_tb = d->start_pts_tb;
                }
            } while (pkt.data == flush_pkt.data || d->queue->serial != d->pkt_serial);
            av_free_packet(&d->pkt);
            d->pkt_temp = d->pkt = pkt;
            d->packet_pending = 1;
        }

        switch (d->avctx->codec_type) {
            case AVMEDIA_TYPE_VIDEO: {
#ifdef FFP_SHOW_VDPS
                SDL_ProfilerBegin(&d->decode_profiler);
#endif
/*hw video codec ！！！！！！！！！！！！！！！！！！！！！！！*/
                if (is_hw_video_codec(d->avctx)) {
                    ret = hw_decode_video_frame(d->avctx, frame, &got_frame, &d->pkt_temp);
                }
                else {
                    ret = avcodec_decode_video2(d->avctx, frame, &got_frame, &d->pkt_temp);
                }
#ifdef FFP_SHOW_VDPS
                int64_t delta = SDL_ProfilerEnd(&d->decode_profiler);
                if (delta >= 30) {
                    av_log(ffp, AV_LOG_DEBUG,
                           "vdps[%d]: %"PRId64" ms/frame, vdps=%f, +%"PRId64"\n",
                           d->decode_profiler.total_counter,
                           d->decode_profiler.average_elapsed,
                           d->decode_profiler.sample_per_seconds,
                           delta);
                }
#endif
                if (got_frame) {
                    if (ffp->decoder_reorder_pts == -1) {
                        frame->pts = av_frame_get_best_effort_timestamp(frame);
                    } else if (ffp->decoder_reorder_pts) {
                        frame->pts = frame->pkt_pts;
                    } else {
                        frame->pts = frame->pkt_dts;
                    }
                }
                }
                break;
            case AVMEDIA_TYPE_AUDIO:
                ret = avcodec_decode_audio4(d->avctx, frame, &got_frame, &d->pkt_temp);
                if (got_frame) {
                    AVRational tb = (AVRational){1, frame->sample_rate};
                    if (frame->pts != AV_NOPTS_VALUE)
                        frame->pts = av_rescale_q(frame->pts, d->avctx->time_base, tb);
                    else if (frame->pkt_pts != AV_NOPTS_VALUE)
                        frame->pts = av_rescale_q(frame->pkt_pts, av_codec_get_pkt_timebase(d->avctx), tb);
                    else if (d->next_pts != AV_NOPTS_VALUE)
                        frame->pts = av_rescale_q(d->next_pts, d->next_pts_tb, tb);
                    if (frame->pts != AV_NOPTS_VALUE) {
                        d->next_pts = frame->pts + frame->nb_samples;
                        d->next_pts_tb = tb;
                    }
                }
                break;
            // FFP_MERGE: case AVMEDIA_TYPE_SUBTITLE:
            default:
                break;
        }

        if (ret < 0) {
            d->packet_pending = 0;
        } else {
            d->pkt_temp.dts =
            d->pkt_temp.pts = AV_NOPTS_VALUE;
            if (d->pkt_temp.data) {
                if (d->avctx->codec_type != AVMEDIA_TYPE_AUDIO)
                    ret = d->pkt_temp.size;
                d->pkt_temp.data += ret;
                d->pkt_temp.size -= ret;
                if (d->pkt_temp.size <= 0)
                    d->packet_pending = 0;
            } else {
                if (!got_frame) {
                    d->packet_pending = 0;
                    d->finished = d->pkt_serial;
                }
            }
        }
    } while (!got_frame && !d->finished);

    return got_frame;
}

/* open a given stream. Return 0 if OK */
static int stream_component_open(FFPlayer *ffp, int stream_index)
{
    VideoState *is = ffp->is;
    AVFormatContext *ic = is->ic;
    AVCodecContext *avctx;
    AVCodec *codec;
    const char *forced_codec_name = NULL;
    AVDictionary *opts;
    AVDictionaryEntry *t = NULL;
    int sample_rate, nb_channels;
    int64_t channel_layout;
    int ret = 0;
    int stream_lowres = ffp->lowres;

    if (stream_index < 0 || stream_index >= ic->nb_streams)
        return -1;
    avctx = ic->streams[stream_index]->codec;

    codec = avcodec_find_decoder(avctx->codec_id);

    switch (avctx->codec_type) {
        case AVMEDIA_TYPE_AUDIO   : is->last_audio_stream    = stream_index; forced_codec_name = ffp->audio_codec_name; break;
        // FFP_MERGE: case AVMEDIA_TYPE_SUBTITLE:
        case AVMEDIA_TYPE_VIDEO   : is->last_video_stream    = stream_index; forced_codec_name = ffp->video_codec_name; break;
        default: break;
    }
    if (forced_codec_name)
        codec = avcodec_find_decoder_by_name(forced_codec_name);
    if (!codec) {
        // FIXME: 9 report unknown codec id/name
        if (forced_codec_name) av_log(NULL, AV_LOG_WARNING,
                                      "No codec could be found with name '%s'\n", forced_codec_name);
        else                   av_log(NULL, AV_LOG_WARNING,
                                      "No codec could be found with id %d\n", avctx->codec_id);
        return -1;
    }

    avctx->codec_id = codec->id;
    if(stream_lowres > av_codec_get_max_lowres(codec)){
        av_log(avctx, AV_LOG_WARNING, "The maximum value for lowres supported by the decoder is %d\n",
                av_codec_get_max_lowres(codec));
        stream_lowres = av_codec_get_max_lowres(codec);
    }
    av_codec_set_lowres(avctx, stream_lowres);

    if(stream_lowres) avctx->flags |= CODEC_FLAG_EMU_EDGE;
    if (ffp->fast)    avctx->flags2 |= CODEC_FLAG2_FAST;
    if(codec->capabilities & CODEC_CAP_DR1)
        avctx->flags |= CODEC_FLAG_EMU_EDGE;

    opts = filter_codec_opts(ffp->codec_opts, avctx->codec_id, ic, ic->streams[stream_index], codec);
    if (!av_dict_get(opts, "threads", NULL, 0))
        av_dict_set(&opts, "threads", "auto", 0);
    if (stream_lowres)
        av_dict_set_int(&opts, "lowres", stream_lowres, 0);
    if (avctx->codec_type == AVMEDIA_TYPE_VIDEO || avctx->codec_type == AVMEDIA_TYPE_AUDIO)
        av_dict_set(&opts, "refcounted_frames", "1", 0);
    if ((ret = avcodec_open2(avctx, codec, &opts)) < 0) {
        goto fail;
    }
    if ((t = av_dict_get(opts, "", NULL, AV_DICT_IGNORE_SUFFIX))) {
        av_log(NULL, AV_LOG_ERROR, "Option %s not found.\n", t->key);
#ifdef FFP_MERGE
        ret =  AVERROR_OPTION_NOT_FOUND;
        goto fail;
#endif
    }

    is->eof = 0;
    ic->streams[stream_index]->discard = AVDISCARD_DEFAULT;
    switch (avctx->codec_type) {
    case AVMEDIA_TYPE_AUDIO:
#if CONFIG_AVFILTER
        {
            AVFilterLink *link;

            is->audio_filter_src.freq           = avctx->sample_rate;
            is->audio_filter_src.channels       = avctx->channels;
            is->audio_filter_src.channel_layout = get_valid_channel_layout(avctx->channel_layout, avctx->channels);
            is->audio_filter_src.fmt            = avctx->sample_fmt;
            if ((ret = configure_audio_filters(is, afilters, 0)) < 0)
                goto fail;
            link = is->out_audio_filter->inputs[0];
            sample_rate    = link->sample_rate;
            nb_channels    = link->channels;
            channel_layout = link->channel_layout;
        }
#else
        sample_rate    = avctx->sample_rate;
        nb_channels    = avctx->channels;
        channel_layout = avctx->channel_layout;
#endif

        /* prepare audio output */
        if ((ret = audio_open(ffp, channel_layout, nb_channels, sample_rate, &is->audio_tgt)) < 0)
            goto fail;
        ffp_set_audio_codec_info(ffp, AVCODEC_MODULE_NAME, avcodec_get_name(avctx->codec_id));
        is->audio_hw_buf_size = ret;
        is->audio_src = is->audio_tgt;
        is->audio_buf_size  = 0;
        is->audio_buf_index = 0;

        /* init averaging filter */
        is->audio_diff_avg_coef  = exp(log(0.01) / AUDIO_DIFF_AVG_NB);
        is->audio_diff_avg_count = 0;
        /* since we do not have a precise anough audio fifo fullness,
           we correct audio sync only if larger than this threshold */
        is->audio_diff_threshold = 2.0 * is->audio_hw_buf_size / is->audio_tgt.bytes_per_sec;

        is->audio_stream = stream_index;
        is->audio_st = ic->streams[stream_index];

        decoder_init(&is->auddec, avctx, &is->audioq, is->continue_read_thread);
        if ((is->ic->iformat->flags & (AVFMT_NOBINSEARCH | AVFMT_NOGENSEARCH | AVFMT_NO_BYTE_SEEK)) && !is->ic->iformat->read_seek) {
            is->auddec.start_pts = is->audio_st->start_time;
            is->auddec.start_pts_tb = is->audio_st->time_base;
        }
        decoder_start(&is->auddec, audio_thread, ffp, "ff_audio_dec");
        SDL_AoutPauseAudio(ffp->aout, 0);
        break;
    case AVMEDIA_TYPE_VIDEO:
        is->video_stream = stream_index;
        is->video_st = ic->streams[stream_index];

        decoder_init(&is->viddec, avctx, &is->videoq, is->continue_read_thread);
/*hw video codec ！！！！！！！！！！！！！！！！！！！！！！！*/
		if (is_hw_video_codec(d->avctx)) {
            int64_t duration;
            if (is->video_st->duration != AV_NOPTS_VALUE) {
                duration = is->video_st->duration * av_q2d(is->video_st->time_base)
                    * 1000000;
            } else {
                // default when no stream duration
                duration = ic->duration;
            }
            int ret = hw_video_decoder_init(avctx, duration, ffp->video_rotation);
            if (ret < 0) {
                goto fail;
            }
        }
        ffp->node_vdec = ffpipeline_open_video_decoder(ffp->pipeline, ffp);
        if (!ffp->node_vdec)
            goto fail;
        decoder_start(&is->viddec, video_thread, ffp, "ff_video_dec");
        is->queue_attachments_req = 1;

        if(is->video_st->avg_frame_rate.den && is->video_st->avg_frame_rate.num) {
            double fps = av_q2d(is->video_st->avg_frame_rate);
            SDL_ProfilerReset(&is->viddec.decode_profiler, fps + 0.5);
            if (fps > ffp->max_fps && fps < 130.0) {
                is->is_video_high_fps = 1;
                av_log(ffp, AV_LOG_WARNING, "fps: %lf (too high)\n", fps);
            } else {
                av_log(ffp, AV_LOG_WARNING, "fps: %lf (normal)\n", fps);
            }
        }
        if(is->video_st->r_frame_rate.den && is->video_st->r_frame_rate.num) {
            double tbr = av_q2d(is->video_st->r_frame_rate);
            if (tbr > ffp->max_fps && tbr < 130.0) {
                is->is_video_high_fps = 1;
                av_log(ffp, AV_LOG_WARNING, "fps: %lf (too high)\n", tbr);
            } else {
                av_log(ffp, AV_LOG_WARNING, "fps: %lf (normal)\n", tbr);
            }
        }

        if (is->is_video_high_fps) {
            avctx->skip_frame       = FFMAX(avctx->skip_frame, AVDISCARD_NONREF);
            avctx->skip_loop_filter = FFMAX(avctx->skip_loop_filter, AVDISCARD_NONREF);
            avctx->skip_idct        = FFMAX(avctx->skip_loop_filter, AVDISCARD_NONREF);
        }

        break;
    // FFP_MERGE: case AVMEDIA_TYPE_SUBTITLE:
    default:
        break;
    }
fail:
    av_dict_free(&opts);

    return ret;
}

static void stream_component_close(FFPlayer *ffp, int stream_index)
{
    VideoState *is = ffp->is;
    AVFormatContext *ic = is->ic;
    AVCodecContext *avctx;

    if (stream_index < 0 || stream_index >= ic->nb_streams)
        return;
    avctx = ic->streams[stream_index]->codec;

    switch (avctx->codec_type) {
    case AVMEDIA_TYPE_AUDIO:
        decoder_abort(&is->auddec, &is->sampq);
        SDL_AoutCloseAudio(ffp->aout);

        decoder_destroy(&is->auddec);
        swr_free(&is->swr_ctx);
        av_freep(&is->audio_buf1);
        is->audio_buf1_size = 0;
        is->audio_buf = NULL;

#ifdef FFP_MERGE
        if (is->rdft) {
            av_rdft_end(is->rdft);
            av_freep(&is->rdft_data);
            is->rdft = NULL;
            is->rdft_bits = 0;
        }
#endif
        break;
    case AVMEDIA_TYPE_VIDEO:
        decoder_abort(&is->viddec, &is->pictq);
        decoder_destroy(&is->viddec);
		if (is_hw_video_codec(avctx)) {
            hw_decoder_video_close(avctx); //added by pengkai@letv.com
        }
        break;
    // FFP_MERGE: case AVMEDIA_TYPE_SUBTITLE:
    default:
        break;
    }

    ic->streams[stream_index]->discard = AVDISCARD_ALL;
    avcodec_close(avctx);
    switch (avctx->codec_type) {
    case AVMEDIA_TYPE_AUDIO:
        is->audio_st = NULL;
        is->audio_stream = -1;
        break;
    case AVMEDIA_TYPE_VIDEO:
        is->video_st = NULL;
        is->video_stream = -1;
        break;
    // FFP_MERGE: case AVMEDIA_TYPE_SUBTITLE:
    default:
        break;
    }
}

bool is_hw_video_codec(AVCodecContext *avctx)
{
    bool supported = false;

    enum AVCodecID codec_id = avctx->codec_id;

    switch(codec_id) {
    case AV_CODEC_ID_H264:
    case AV_CODEC_ID_MPEG4:
    case AV_CODEC_ID_HEVC:
	    supported = true;
        break;
    default:
        supported = false;
        break;
    }

    return supported;
}

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/android/ijkplayer_android.c#L43
https://github.com/Bilibili/ijkplayer/tree/master/ijkmedia/ijkplayer/android/pipeline

Define your own pipeline and vout, to override original pipeline and vout.

**Comment by wqmijkplayer** [comment]
Thanks

**Comment by wqmijkplayer** [comment]
I enable CONFIG_AVFILTER, play video, display is ok
but play 4k  video is too slowly, so I disable CONFIG_AVFILTER
but disable CONFIG_AVFILTER, cannot display any video, and don't get managed_frame
only define my own pipeline and vout to fix this issue?

**Comment by bbcallen** [comment]
What you need to do, is not only "only".

HW decoders need to manage frames in different methods.
pipeline + vout define the interface between 'player area' and 'HW decoder & render area'.
So, you could create custom vout, create custom format frame (overlay) from your vout,
and render it onto screen in your custom way.

You don't have to follow pipeline + vout way, if you understand how it works.

**Comment by Android4MediaPlayer** [comment]
@wqmijkplayer  That's what bbcallen was said.
Define your own pipeline and vout and overlay from your vout.

**Comment by Android4MediaPlayer** [comment]
允许的话可以把你的代码pull到一个工程，有时间的话可以看看怎么集成。

**Comment by bbcallen** [comment]
BTW: manage_frame is used in FFmpegOverlay.
https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijksdl/ffmpeg/ijksdl_vout_overlay_ffmpeg.c

**Comment by wqmijkplayer** [comment]
Thanks
in ijksdl_vout_overlay_ffmpeg.c, SDL_VoutFFmpeg_CreateOverlay set managed_frame ok, managed_frame is set to overlay
but SDL_VoutFFmpeg_ConvertFrame cannot get managed_frame from overlay
(this overlay is from frame_queue_peek_writable)
I want to know why?
