### ISSUE TITLE
ijkmp_shutdown_l不能退出，发生死锁

### ISSUE THREAD

**Issue by benbochong** [Bilibili/ijkplayer#5498]
正常情况下，android环境下，切换播放源时调用 release会产生如下日志：
12-27 15:13:21.412 20614 20614 D IJKMEDIA: liblog: 224766- 3510- 0-ijkmp_stop()
12-27 15:13:21.412 20614 14352 D IJKMEDIA: liblog: 224767- 3511- 0-message_loop exit
12-27 15:13:21.412 20614 14352 I IJKMEDIA: liblog: 224768- 3512- 0-SDL_JNI_DetachThreadEnv: [14352]
12-27 15:13:21.413 20614 20614 D IJKMEDIA: liblog: 224769- 3513- 0-ijkmp_stop()=0
12-27 15:13:21.413 20614 20614 D IJKMEDIA: liblog: 224770- 3514- 0-IjkMediaPlayer_release
12-27 15:13:21.413 20614 20614 D IJKMEDIA: liblog: 224771- 3515- 0-ijkmp_set_android_surface(surface=0x0)
12-27 15:13:21.413 20614 20614 D IJKMEDIA: liblog: 224772- 3516- 0-ffpipeline_set_surface()
12-27 15:13:21.413 20614 20614 D IJKMEDIA: liblog: 224773- 3517- 0-ijkmp_set_android_surface(surface=0x0)=void
12-27 15:13:21.413 20614 20614 D IJKMEDIA: liblog: 224774- 3518- 0-ijkmp_shutdown_l()
12-27 15:13:21.420 20614 14353 I IJKMEDIA: liblog: 224775- 3519- 0-SDL_JNI_DetachThreadEnv: [14353]
12-27 15:13:21.421 20614 14354 I IJKMEDIA: liblog: 224776- 3520- 0-SDL_JNI_DetachThreadEnv: [14354]
12-27 15:13:21.422 20614 14358 I IJKMEDIA: liblog: 224777- 3521- 0-SDL_JNI_DetachThreadEnv: [14358]
12-27 15:13:21.439 20614 14357 I IJKMEDIA: liblog: 224780- 3524- 0-SDL_JNI_DetachThreadEnv: [14357]
12-27 15:13:21.445 20614 20614 D IJKMEDIA: liblog: 224781- 3525- 0-ijkmp_shutdown_l()=void
12-27 15:13:21.446 20614 20614 D IJKMEDIA: liblog: 224782- 3526- 0-ijkmp_dec_ref(): ref=0
12-27 15:13:21.446 20614 20614 D IJKMEDIA: liblog: 224783- 3527- 0-ijkmp_shutdown_l()
12-27 15:13:21.446 20614 20614 D IJKMEDIA: liblog: 224784- 3528- 0-ijkmp_shutdown_l()=void

即正常情况下ijkmp_shutdown_l()与ijkmp_shutdown_l()=void成对出现。
在频繁多次reset进行播放源切换后出现了日志仅有ijkmp_shutdown_l()而没有ijkmp_shutdown_l()=void的情况，即ijkmp_shutdown_l进入后一直不退出，app应用无响应。
日志如下：
12-27 15:13:39.544 20614 20614 D IJKMEDIA: liblog: 227208- 5452- 0-ijkmp_stop()
12-27 15:13:39.544 20614 14446 D IJKMEDIA: liblog: 227209- 5453- 0-message_loop exit
12-27 15:13:39.544 20614 14446 I IJKMEDIA: liblog: 227210- 5454- 0-SDL_JNI_DetachThreadEnv: [14446]
12-27 15:13:39.545 20614 20614 D IJKMEDIA: liblog: 227211- 5455- 0-ijkmp_stop()=0
12-27 15:13:39.545 20614 20614 D IJKMEDIA: liblog: 227212- 5456- 0-IjkMediaPlayer_release
12-27 15:13:39.545 20614 20614 D IJKMEDIA: liblog: 227213- 5457- 0-ijkmp_set_android_surface(surface=0x0)
12-27 15:13:39.545 20614 20614 D IJKMEDIA: liblog: 227214- 5458- 0-ffpipeline_set_surface()
12-27 15:13:39.545 20614 20614 D IJKMEDIA: liblog: 227215- 5459- 0-ijkmp_set_android_surface(surface=0x0)=void
12-27 15:13:39.545 20614 20614 D IJKMEDIA: liblog: 227216- 5460- 0-ijkmp_shutdown_l()
12-27 15:13:39.548 20614 14447 I IJKMEDIA: liblog: 227217- 5461- 0-SDL_JNI_DetachThreadEnv: [14447]

ijkmp_shutdown_l函数源码如下：
void ijkmp_shutdown_l(IjkMediaPlayer *mp)
{
    assert(mp);

    MPTRACE("ijkmp_shutdown_l()\n");
    if (mp->ffplayer) {
        ffp_stop_l(mp->ffplayer);
        ffp_wait_stop_l(mp->ffplayer);
    }
    MPTRACE("ijkmp_shutdown_l()=void\n");
}

其中ffp_stop_l存在死锁可能：
int ffp_stop_l(FFPlayer *ffp)
{
    assert(ffp);
    VideoState *is = ffp->is;
    if (is) {
        is->abort_request = 1;
        toggle_pause(ffp, 1);
    }

    msg_queue_abort(&ffp->msg_queue);
    if (ffp->enable_accurate_seek && is && is->accurate_seek_mutex
        && is->audio_accurate_seek_cond && is->video_accurate_seek_cond) {
        SDL_LockMutex(is->accurate_seek_mutex);
        is->audio_accurate_seek_req = 0;
        is->video_accurate_seek_req = 0;
        SDL_CondSignal(is->audio_accurate_seek_cond);
        SDL_CondSignal(is->video_accurate_seek_cond);
        SDL_UnlockMutex(is->accurate_seek_mutex);
    }
    return 0;
}

**Comment by benbochong** [comment]
已定位到 release 中会等待aout_thread_n线程结束，而该线程在调用android.media.AudioTrack.write死循环，死循环原因为android::ClientProxy::obtainBuffer获取不到可用buffer。
再往下的原因可能是audioflinger不能及时读取释放buffer，不能及时读取buffer的原因可能是audioflinger向audiohal写数据有错误。

**Comment by zzp1993315** [comment]
怎么解决这个问题的
