### ISSUE TITLE
如何播放视频流?

### ISSUE THREAD

**Issue by VincentSit** [Bilibili/ijkplayer#551]
平台：iOS。

首先感谢作者开源这个优秀的库。

我编译了可以运行，研究了几个小时源码，发现高层的封装都是接受 URL 参数，而我需要的是播放视频流，只有两个参数，一个是视频数据 buffer，另一个是 buffer size，拿到一帧渲染一帧。于是我往底层的代码研究，发现 `IJKSDLGLView` 有一个 `display:` 方法，接收一个 `SDL_VoutOverlay *` 作为参数，然而项目中有许多创建 SDL_VoutOverlay 的地方，本人不善于 C，许多代码无法参透，还请作者指教一二。谢谢！

**Comment by bbcallen** [comment]
No support in ijkplayer, yet.

**Comment by VincentSit** [comment]
多谢.
