### ISSUE TITLE
如何增加dts、dtshd、dts:X等格式支持？

### ISSUE THREAD

**Issue by AD-God** [Bilibili/ijkplayer#5521]
已经加了如下代码：
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mlp"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=truehd"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=dts"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=dtshd"

目前truehd格式已可支持，有声音。dts格式音频的还是没有声音

**Comment by liana101** [comment]
通过potplayer 查看音频解码

![image](https://user-images.githubusercontent.com/20311204/230311720-3557b8c6-1ec7-458f-9354-ce95d1abb8c5.png)
然后修改
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=dca"
