### ISSUE TITLE
哔哩哔哩网页版动态有错位

### ISSUE THREAD

**Issue by ghost** [Bilibili/ijkplayer#5529]
不知道该不该在这里说，但是这个bug已经存在好久了，主要是右上角的“投稿”总是莫名其妙的溜出框架外面。。。

**Comment by sansan-cc** [comment]
> 不知道该不该在这里说，但是这个bug已经存在好久了，主要是右上角的“投稿”总是莫名其妙的溜出框架外面。。。

哈哈哈直接找客服呗，App上应该有反馈渠道吧

**Comment by ghost** [comment]
> > 不知道该不该在这里说，但是这个bug已经存在好久了，主要是右上角的“投稿”总是莫名其妙的溜出框架外面。。。
> 
> 哈哈哈直接找客服呗，App上应该有反馈渠道吧

没找到反馈渠道😭🏊

**Comment by ghost** [comment]
> > 不知道该不该在这里说，但是这个bug已经存在好久了，主要是右上角的“投稿”总是莫名其妙的溜出框架外面。。。
> 
> 哈哈哈直接找客服呗，App上应该有反馈渠道吧

但是这个bug貌似上周末修好了，把图标弄的特别小，我真的会谢😶

**Comment by ghost** [comment]
> > > 不知道该不该在这里说，但是这个bug已经存在好久了，主要是右上角的“投稿”总是莫名其妙的溜出框架外面。。。
> > 
> > 
> > 哈哈哈直接找客服呗，App上应该有反馈渠道吧
> 
> 但是这个bug貌似上周末修好了，把图标弄的特别小，我真的会谢😶

👌
