### ISSUE TITLE
Call to undeclared function 'av_dict_get'; ISO C99 and later do not support implicit function declarations

### ISSUE THREAD

**Issue by LisonFan** [Bilibili/ijkplayer#5558]
![image](https://github.com/bilibili/ijkplayer/assets/9424775/7e7fccb0-4e36-476e-b8dd-37a19bb87c92)

**Comment by luffyjie** [comment]
#include "libavutil/dict.h"
手动引入头文件就行了

**Comment by kklwg** [comment]
good
