### ISSUE TITLE
Mac M3芯片 14.4.1 iOS SDK 17.4.1 执行  ./compile-ffmpeg.sh all armv7 和 arm64 分别都有报错 

### ISSUE THREAD

**Issue by liuqianteng** [Bilibili/ijkplayer#5593]
libavutil/dict.c:166:15: error: incompatible pointer to integer conversion initializing 'uintptr_t' (aka 'unsigned long') with an expression of type 'void *' [-Wint-conversion]
    uintptr_t ptr = NULL;
              ^     ~~~~
libavutil/dict.c:171:12: error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'uintptr_t' (aka 'unsigned long') [-Wint-conversion]
    return NULL;
           ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include/stddef.h:89:16: note: expanded from macro 'NULL'
#  define NULL ((void*)0)
               ^~~~~~~~~~
libavutil/dict.c:166:15: warning: unused variable 'ptr' [-Wunused-variable]
    uintptr_t ptr = NULL;
              ^
libavutil/dict.c:175:14: error: incompatible pointer to integer conversion initializing 'uintptr_t' (aka 'unsigned long') with an expression of type 'void *' [-Wint-conversion]
   uintptr_t ptr = NULL;
             ^     ~~~~
libavutil/dict.c:178:15: error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'uintptr_t' (aka 'unsigned long') [-Wint-conversion]
       return NULL;
              ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include/stddef.h:89:16: note: expanded from macro 'NULL'
#  define NULL ((void*)0)
               ^~~~~~~~~~
libavutil/dict.c:182:15: error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'uintptr_t' (aka 'unsigned long') [-Wint-conversion]
       return NULL;
              ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include/stddef.h:89:16: note: expanded from macro 'NULL'
#  define NULL ((void*)0)
               ^~~~~~~~~~
libavutil/dict.c:189:48: warning: format specifies type 'void *' but the argument has type 'uintptr_t' (aka 'unsigned long') [-Wformat]
    snprintf(valuestr, sizeof(valuestr), "%p", value);
                                          ~~   ^~~~~
                                          %lu
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.4.sdk/usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                                             ^~~~~~~~~~~
3 warnings and 5 errors generated.
make: *** [libavutil/dict.o] Error 1

uintptr_t ptr 不能赋值 NULL

**Comment by RATime360** [comment]
强制类型转换下，或者用旧的xcode编译

**Comment by jazzforlove** [comment]
请问怎么解决的

**Comment by liuqianteng** [comment]
用低版本系统编译

jazzforlove ***@***.***> 于2024年11月13日周三 21:24写道：

**Comment by LarryLee** [comment]
问题有解决方案么？

**Comment by taojeff** [comment]
> 强制类型转换下，或者用旧的xcode编译

可以问一下如何强制类型转换吗？

**Comment by taojeff** [comment]
@liuqianteng 你最终是用什么系统和对应的什么xcode进行解决的？

**Comment by liuqianteng** [comment]
强制转换没有用，我源代码都修改过。还是报错。
当时我自己有台旧电脑，老的XCode，我是用旧电脑，老版本的XCode编译的就ok了。
有问题的，我看bilibili也没有做适配。


其实.......
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bilibili/ijkplayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年1月15日(星期三) 下午3:36
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [bilibili/ijkplayer] Mac M3芯片 14.4.1 iOS SDK 17.4.1 执行  ./compile-ffmpeg.sh all armv7 和 arm64 分别都有报错  (Issue #5593)





  
强制类型转换下，或者用旧的xcode编译
  
可以问一下如何强制类型转换吗？

**Comment by taojeff** [comment]
> 强制转换没有用，我源代码都修改过。还是报错。 当时我自己有台旧电脑，老的XCode，我是用旧电脑，老版本的XCode编译的就ok了。 有问题的，我看bilibili也没有做适配。 其实....... ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "bilibili/ijkplayer" ***@***.***&gt;; 发送时间:&nbsp;2025年1月15日(星期三) 下午3:36 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [bilibili/ijkplayer] Mac M3芯片 14.4.1 iOS SDK 17.4.1 执行 ./compile-ffmpeg.sh all armv7 和 arm64 分别都有报错 (Issue #5593) 强制类型转换下，或者用旧的xcode编译 可以问一下如何强制类型转换吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

我现在M1电脑和xcode都升级到最新了版本了，不过还保留了一个15.4的xcode。不过我看issue里也有15.4xcode编译后有问题的

**Comment by liuqianteng** [comment]
那我要回去要看下，我之前编译的xcode是多少版本了。
我之前的电脑是intel芯片，不是apple M的芯片。
这个好像是M芯片才有问题。
我的现在新的电脑是M3的。


其实.......
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bilibili/ijkplayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年1月15日(星期三) 下午3:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bilibili/ijkplayer] Mac M3芯片 14.4.1 iOS SDK 17.4.1 执行  ./compile-ffmpeg.sh all armv7 和 arm64 分别都有报错  (Issue #5593)





  
强制转换没有用，我源代码都修改过。还是报错。 当时我自己有台旧电脑，老的XCode，我是用旧电脑，老版本的XCode编译的就ok了。 有问题的，我看bilibili也没有做适配。 其实....... @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "bilibili/ijkplayer" @.&gt;; 发送时间:&nbsp;2025年1月15日(星期三) 下午3:36 @.&gt;; @.&gt;;"State @.&gt;; 主题:&nbsp;Re: [bilibili/ijkplayer] Mac M3芯片 14.4.1 iOS SDK 17.4.1 执行 ./compile-ffmpeg.sh all armv7 和 arm64 分别都有报错 (Issue #5593) 强制类型转换下，或者用旧的xcode编译 可以问一下如何强制类型转换吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
我现在M1电脑和xcode都升级到最新了版本了，不过还保留了一个15.4的xcode。不过我看issue里也有15.4xcode编译后有问题的
