### ISSUE TITLE
16 KB Support for Android 15

### ISSUE THREAD

**Issue by smore-lore** [Bilibili/ijkplayer#5600]
Hi, Android 15 is introducing a 16 KB page size development mode and asking new apps to work in this mode, so that future devices can use 16 KB pages. You may want to ensure your SDK works in this mode, so that app developers using this software package don't have to update themselves. Thank you!

Read more at https://developer.android.com/16kb-page-size.

**Comment by CarGuo** [comment]
you can get ：
1、ijkplayer git diff patch with 16k page size ：https://github.com/CarGuo/GSYVideoPlayer/tree/master/16kpatch
2、android so library ：https://github.com/CarGuo/GSYVideoPlayer/tree/master/gsyVideoPlayer-armv64/src/main/jniLibs/arm64-v8a
3、article(only Chinese)  ：https://juejin.cn/post/7396306532671094793

**Comment by th1nk3r-ing** [comment]
ç

> you can get ： 1、ijkplayer git diff patch with 16k page size ：https://github.com/CarGuo/GSYVideoPlayer/tree/master/16kpatch 2、android so library ：https://github.com/CarGuo/GSYVideoPlayer/tree/master/gsyVideoPlayer-armv64/src/main/jniLibs/arm64-v8a 3、article(only Chinese) ：https://juejin.cn/post/7396306532671094793

兄弟, 有没有碰到 Android-15 在 `System.loadLobiray()` 卡主的情况. 感觉跟对齐还是有一定关系

**Comment by CarGuo** [comment]
@th1nk3r-ing  ld.bfd 的时候，遇到过 loadLobiray 时因为 cxx_global_var_init 出现 crash 的情况，换到 lld 正常

**Comment by th1nk3r-ing** [comment]
@CarGuo  我这边倒不是挂了, 是 jni call 卡主导致的 anr, 只在 Android-15 上概率性出现.
具体是 `JNIEnv->GetStaticMethodID("createByCodecName")` 方法调用获取 AMC 的静态创建方法, 一直没返回......

**Comment by CarGuo** [comment]
> you can get ： 1、ijkplayer git diff patch with 16k page size ：https://github.com/CarGuo/GSYVideoPlayer/tree/master/16kpatch 2、android so library ：https://github.com/CarGuo/GSYVideoPlayer/tree/master/gsyVideoPlayer-armv64/src/main/jniLibs/arm64-v8a 3、article(only Chinese) ：https://juejin.cn/post/7396306532671094793

if you don't want to update ndk, try this:
https://github.com/CarGuo/GSYVideoPlayer/tree/master/16kpatch/old

**Comment by peerless2012** [comment]
@CarGuo 感谢大佬踩坑分享，从文章来，找到根据地了。

**Comment by Hyyzt** [comment]
> [@CarGuo](https://github.com/CarGuo) 我这边倒不是挂了, 是 jni call 卡主导致的 anr, 只在 Android-15 上概率性出现. 具体是 `JNIEnv->GetStaticMethodID("createByCodecName")` 方法调用获取 AMC 的静态创建方法, 一直没返回......

大佬，这个问题有解决吗？同样是Android15上偶先的ANR

**Comment by thisdk** [comment]
> 大佬，这个问题有解决吗？同样是Android15上偶先的ANR

大佬，这个问题有解决吗？同样是Android15上偶先的ANR

```
07-03 14:48:00.242 28636 15165 W MIUIScout App: Enter APP_SCOUT_WARNING State
07-03 14:48:00.243 28636 15165 W MIUIScout App: (Current message: duration=2502ms seq=19679 late=41ms h=com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler w=0)
07-03 14:48:00.245 28636 15165 D AppScoutStateMachine: dump trace dirName = 2025-07-03-14-48-00-28636-APP_SCOUT_WARNING-cn.walmart.app
07-03 14:48:00.248 28636 18290 W MIUIScout App: Event:APP_SCOUT_WARNING Thread:main backtrace:
07-03 14:48:00.248 28636 18290 W MIUIScout App: at java.lang.Runtime.nativeLoad(Native Method)
07-03 14:48:00.248 28636 18290 W MIUIScout App: at java.lang.Runtime.loadLibrary0(Runtime.java:1086)
07-03 14:48:00.248 28636 18290 W MIUIScout App: at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
07-03 14:48:00.248 28636 18290 W MIUIScout App: at java.lang.System.loadLibrary(System.java:1765)
07-03 14:48:00.248 28636 18290 W MIUIScout App: at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:179)
07-03 14:48:00.248 28636 18290 W MIUIScout App: at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:191)
07-03 14:48:00.248 28636 18290 W MIUIScout App: at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:231)
07-03 14:48:00.248 28636 18290 W MIUIScout App: at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:227)
07-03 14:48:00.248 28636 18290 W MIUIScout App: at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:218)
07-03 14:48:00.248 28636 18290 W MIUIScout App: at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:60)
07-03 14:48:00.248 28636 18290 W MIUIScout App: at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:624)
07-03 14:48:00.248 28636 18290 W MIUIScout App: at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:39)
07-03 14:48:00.248 28636 18290 W MIUIScout App: at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:581)
```

**Comment by Hyyzt** [comment]
> > 大佬，这个问题有解决吗？同样是Android15上偶先的ANR
> 
> 大佬，这个问题有解决吗？同样是Android15上偶先的ANR
> 
> ```
> 07-03 14:48:00.242 28636 15165 W MIUIScout App: Enter APP_SCOUT_WARNING State
> 07-03 14:48:00.243 28636 15165 W MIUIScout App: (Current message: duration=2502ms seq=19679 late=41ms h=com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler w=0)
> 07-03 14:48:00.245 28636 15165 D AppScoutStateMachine: dump trace dirName = 2025-07-03-14-48-00-28636-APP_SCOUT_WARNING-cn.walmart.app
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: Event:APP_SCOUT_WARNING Thread:main backtrace:
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at java.lang.Runtime.nativeLoad(Native Method)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at java.lang.Runtime.loadLibrary0(Runtime.java:1086)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at java.lang.System.loadLibrary(System.java:1765)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:179)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:191)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:231)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:227)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:218)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:60)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:624)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:39)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:581)
> ```

没有解决，我们准备换播放器，切到腾讯云的播放器。
不过我可以提供一点其他的信息。我们有一共有两个项目，一个新项目，一个老项目，使用的都是Ijk的播放器，但是只有在老项目上偶现的出现这个ANR，新项目上没有这个问题。所以，我猜测有可能跟在loadLibrary的那一刻的cpu和内存的使用率有关。因为两个项目唯一的区别就是，启动的时候一个服务多，一个服务少。其他的并没有太多区别。但是老项目其他的服务很难动，成本太大，加上ijk已经不维护了，后续肯定还有其他的问题，所以我们准备切换播放器。

**Comment by th1nk3r-ing** [comment]
不用换. 我们之前排查的是多线程调用 AMC 接口导致的系统某部分死锁问题.
 具体你们可以排查下, loadLibrary 通过 jni load  AMC 的同时, 是不是还有其它 java 层的接口在调用 AMC, 有的话延后一下就行了. loadLibrary 成功之后就随便调用了.

**Comment by th1nk3r-ing** [comment]
> > 大佬，这个问题有解决吗？同样是Android15上偶先的ANR
> 
> 大佬，这个问题有解决吗？同样是Android15上偶先的ANR
> 
> ```
> 07-03 14:48:00.242 28636 15165 W MIUIScout App: Enter APP_SCOUT_WARNING State
> 07-03 14:48:00.243 28636 15165 W MIUIScout App: (Current message: duration=2502ms seq=19679 late=41ms h=com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler w=0)
> 07-03 14:48:00.245 28636 15165 D AppScoutStateMachine: dump trace dirName = 2025-07-03-14-48-00-28636-APP_SCOUT_WARNING-cn.walmart.app
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: Event:APP_SCOUT_WARNING Thread:main backtrace:
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at java.lang.Runtime.nativeLoad(Native Method)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at java.lang.Runtime.loadLibrary0(Runtime.java:1086)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at java.lang.System.loadLibrary(System.java:1765)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:179)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:191)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:231)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:227)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:218)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:60)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:624)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:39)
> 07-03 14:48:00.248 28636 18290 W MIUIScout App: at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:581)
> ```


不用换. 我们之前排查的是多线程调用 AMC 接口导致的系统某部分死锁问题.
具体你们可以排查下, loadLibrary 通过 jni load AMC 的同时(一点一点加打印, 看具体卡在哪个函数的 load), 是不是还有其它 java 层的接口在调用 AMC, 有的话延后一下就行了. loadLibrary 成功之后就随便调用了.

**Comment by Hyyzt** [comment]
> 不用换. 我们之前排查的是多线程调用 AMC 接口导致的系统某部分死锁问题. 具体你们可以排查下, loadLibrary 通过 jni load AMC 的同时(一点一点加打印, 看具体卡在哪个函数的 load), 是不是还有其它 java 层的接口在调用 AMC, 有的话延后一下就行了. loadLibrary 成功之后就随便调用了.

这就是我们老项目存在的问题了，之前的开发，已经把ijk的库编成so库了，我都不知道他编的哪个版本的，甚至有没有魔改都不知道，根本没办法debug,而且在初始化的时候，很多地方都在start,stop,播放器，很难把这些跟业务剥离开。

**Comment by Hyyzt** [comment]
> > 不用换. 我们之前排查的是多线程调用 AMC 接口导致的系统某部分死锁问题. 具体你们可以排查下, loadLibrary 通过 jni load AMC 的同时(一点一点加打印, 看具体卡在哪个函数的 load), 是不是还有其它 java 层的接口在调用 AMC, 有的话延后一下就行了. loadLibrary 成功之后就随便调用了.
> 
> 这就是我们老项目存在的问题了，之前的开发，已经把ijk的库编成so库了，我都不知道他编的哪个版本的，甚至有没有魔改都不知道，根本没办法debug

如果按照你的说法的话，是因为死锁导致的ANR，我之前有想过一个方案，在APP启动的时候直接初始化整个播放器的libc模块，这个时候肯定是单线程的，等到进入短视频页面，已经初始化完成了，就不会再次进入load的逻辑了，是否能解决这个问题?

**Comment by th1nk3r-ing** [comment]
> > > 不用换. 我们之前排查的是多线程调用 AMC 接口导致的系统某部分死锁问题. 具体你们可以排查下, loadLibrary 通过 jni load AMC 的同时(一点一点加打印, 看具体卡在哪个函数的 load), 是不是还有其它 java 层的接口在调用 AMC, 有的话延后一下就行了. loadLibrary 成功之后就随便调用了.
> > 
> > 
> > 这就是我们老项目存在的问题了，之前的开发，已经把ijk的库编成so库了，我都不知道他编的哪个版本的，甚至有没有魔改都不知道，根本没办法debug
> 
> 如果按照你的说法的话，是因为死锁导致的ANR，我之前有想过一个方案，在APP启动的时候直接初始化整个播放器的libc模块，这个时候肯定是单线程的，等到进入短视频页面，已经初始化完成了，就不会再次进入load的逻辑了，是否能解决这个问题?

so 改不了, 你把 LoadLibray 的 java 层加载提前不就行了. 保证 LoadLibrary 的时候不要哟别的地方在调 java 层 ＡＭＣ　就行

**Comment by thisdk** [comment]
> > > 大佬，这个问题有解决吗？同样是Android15上偶先的ANR
> > 
> > 
> > 大佬，这个问题有解决吗？同样是Android15上偶先的ANR
> > ```
> > 07-03 14:48:00.242 28636 15165 W MIUIScout App: Enter APP_SCOUT_WARNING State
> > 07-03 14:48:00.243 28636 15165 W MIUIScout App: (Current message: duration=2502ms seq=19679 late=41ms h=com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler w=0)
> > 07-03 14:48:00.245 28636 15165 D AppScoutStateMachine: dump trace dirName = 2025-07-03-14-48-00-28636-APP_SCOUT_WARNING-cn.walmart.app
> > 07-03 14:48:00.248 28636 18290 W MIUIScout App: Event:APP_SCOUT_WARNING Thread:main backtrace:
> > 07-03 14:48:00.248 28636 18290 W MIUIScout App: at java.lang.Runtime.nativeLoad(Native Method)
> > 07-03 14:48:00.248 28636 18290 W MIUIScout App: at java.lang.Runtime.loadLibrary0(Runtime.java:1086)
> > 07-03 14:48:00.248 28636 18290 W MIUIScout App: at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
> > 07-03 14:48:00.248 28636 18290 W MIUIScout App: at java.lang.System.loadLibrary(System.java:1765)
> > 07-03 14:48:00.248 28636 18290 W MIUIScout App: at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:179)
> > 07-03 14:48:00.248 28636 18290 W MIUIScout App: at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:191)
> > 07-03 14:48:00.248 28636 18290 W MIUIScout App: at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:231)
> > 07-03 14:48:00.248 28636 18290 W MIUIScout App: at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:227)
> > 07-03 14:48:00.248 28636 18290 W MIUIScout App: at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:218)
> > 07-03 14:48:00.248 28636 18290 W MIUIScout App: at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:60)
> > 07-03 14:48:00.248 28636 18290 W MIUIScout App: at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:624)
> > 07-03 14:48:00.248 28636 18290 W MIUIScout App: at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:39)
> > 07-03 14:48:00.248 28636 18290 W MIUIScout App: at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:581)
> > ```
> 
> 没有解决，我们准备换播放器，切到腾讯云的播放器。 不过我可以提供一点其他的信息。我们有一共有两个项目，一个新项目，一个老项目，使用的都是Ijk的播放器，但是只有在老项目上偶现的出现这个ANR，新项目上没有这个问题。所以，我猜测有可能跟在loadLibrary的那一刻的cpu和内存的使用率有关。因为两个项目唯一的区别就是，启动的时候一个服务多，一个服务少。其他的并没有太多区别。但是老项目其他的服务很难动，成本太大，加上ijk已经不维护了，后续肯定还有其他的问题，所以我们准备切换播放器。

感谢提供信息.我们这个项目确实也有很多服务.因为隐私政策原因.当授权后基本别的服务一窝蜂的初始化

**Comment by Hyyzt** [comment]
> > > > 不用换. 我们之前排查的是多线程调用 AMC 接口导致的系统某部分死锁问题. 具体你们可以排查下, loadLibrary 通过 jni load AMC 的同时(一点一点加打印, 看具体卡在哪个函数的 load), 是不是还有其它 java 层的接口在调用 AMC, 有的话延后一下就行了. loadLibrary 成功之后就随便调用了.
> > > 
> > > 
> > > 这就是我们老项目存在的问题了，之前的开发，已经把ijk的库编成so库了，我都不知道他编的哪个版本的，甚至有没有魔改都不知道，根本没办法debug
> > 
> > 
> > 如果按照你的说法的话，是因为死锁导致的ANR，我之前有想过一个方案，在APP启动的时候直接初始化整个播放器的libc模块，这个时候肯定是单线程的，等到进入短视频页面，已经初始化完成了，就不会再次进入load的逻辑了，是否能解决这个问题?
> 
> so 改不了, 你把 LoadLibray 的 java 层加载提前不就行了. 保证 LoadLibrary 的时候不要哟别的地方在调 java 层 ＡＭＣ　就行

我在application里面开线程直接load ijk的so库了，看看有没有用吧.
