### ISSUE TITLE
RTSP Protocol not found

### ISSUE THREAD

**Issue by ljllfdhz528** [Bilibili/ijkplayer#561]
av_version_info: ff2.8--ijk0.3.3--dev0.3.3--rc1
ijkmp_set_inject_opaque(0x145fc3540)
ijkmp_set_option_int(ijkinject-opaque, 5469123904)
ijkmp_set_option_int()=void
ijkmp_set_inject_opaque()=void
ijkmp_set_option_int(start-on-prepared, 1)
ijkmp_set_option_int()=void
2015-10-16 18:15:47.920 IJKMediaDemo[2978:1207335] OK setup GL
ijkmp_ios_set_view(glView=0x1470ecc90)
ijkmp_ios_set_view(glView=0x1470ecc90)=void
ijkmp_set_option(overlay-format, fcc-i420)
ijkmp_set_option()=void
ijkmp_set_option_int(skip_frame, 8)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_loop_filter, 48)
ijkmp_set_option_int()=void
ijkmp_set_option(user-agent, ijkplayer)
ijkmp_set_option()=void
ijkmp_set_option_int(auto_convert, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(timeout, 30000000)
ijkmp_set_option_int()=void
ijkmp_set_option_int(reconnect, 1)
ijkmp_set_option_int()=void
ijkmp_set_option_int(max-fps, 30)
ijkmp_set_option_int()=void
ijkmp_set_option_int(framedrop, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox-max-frame-width, 960)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(video-pictq-size, 3)
ijkmp_set_option_int()=void
ijkmp_set_data_source(url="rtsp://218.204.223.237:554/live/1/66251FC11353191F/e7ooqwcfbqjoo80j.sdp")
ijkmp_set_data_source(url="rtsp://218.204.223.237:554/live/1/66251FC11353191F/e7ooqwcfbqjoo80j.sdp")=0
ijkmp_set_option(safe, 0)
ijkmp_set_option()=void
ijkmp_prepare_async()
remove 'timeout' option for rtmp.
===== options =====
player-opts : start-on-prepared            = 1
player-opts : overlay-format               = fcc-i420
player-opts : max-fps                      = 30
player-opts : framedrop                    = 0
player-opts : videotoolbox-max-frame-width = 960
player-opts : videotoolbox                 = 0
player-opts : video-pictq-size             = 3
format-opts : ijkinject-opaque             = 5469123904
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : safe                         = 0
format-opts : reconnect                    = 1
codec-opts  : skip_frame                   = 8
codec-opts  : skip_loop_filter             = 48
===================
remove 'timeout' option for rtmp.
rtsp://218.204.223.237:554/live/1/66251FC11353191F/e7ooqwcfbqjoo80j.sdp: Protocol not found
ijkmp_prepare_async()=0
ijkmp_start()
ijkmp_start()=-3
2015-10-16 18:15:48.080 IJKMediaDemo[2978:1207335] FFP_MSG_ERROR: 0
2015-10-16 18:15:48.081 IJKMediaDemo[2978:1207335] moviePlayBackStateDidChange 2: paused
2015-10-16 18:15:48.082 IJKMediaDemo[2978:1207335] playbackStateDidChange: MPMovieFinishReasonPlaybackError: 1
av_version_info: ff2.8--ijk0.3.3--dev0.3.3--rc1
ijkmp_set_inject_opaque(0x145fc3340)
ijkmp_set_option_int(ijkinject-opaque, 5469123392)
ijkmp_set_option_int()=void
ijkmp_set_inject_opaque()=void
ijkmp_set_option_int(start-on-prepared, 1)
ijkmp_set_option_int()=void
2015-10-16 18:15:48.619 IJKMediaDemo[2978:1207335] OK setup GL
ijkmp_ios_set_view(glView=0x1470f8350)
ijkmp_ios_set_view(glView=0x1470f8350)=void
ijkmp_set_option(overlay-format, fcc-i420)
ijkmp_set_option()=void
ijkmp_set_option_int(skip_frame, 8)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_loop_filter, 48)
ijkmp_set_option_int()=void
ijkmp_set_option(user-agent, ijkplayer)
ijkmp_set_option()=void
ijkmp_set_option_int(auto_convert, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(timeout, 30000000)
ijkmp_set_option_int()=void
ijkmp_set_option_int(reconnect, 1)
ijkmp_set_option_int()=void
ijkmp_set_option_int(max-fps, 30)
ijkmp_set_option_int()=void
ijkmp_set_option_int(framedrop, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox-max-frame-width, 960)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(video-pictq-size, 3)
ijkmp_set_option_int()=void
2015-10-16 18:15:48.622 IJKMediaDemo[2978:1207335] Warning: Attempt to present <IJKVideoViewController: 0x1470b5700> on <IJKDemoInputURLViewController: 0x145f6cf20> whose view is not in the window hierarchy!

Please help me！！！

**Comment by ljllfdhz528** [comment]
PHONE IOS

**Comment by ljllfdhz528** [comment]
IOS

**Comment by Zard1096** [comment]
#520 #536

**Comment by hou3172568** [comment]
Hi,guys,you must modify module.sh,add some property for rtsp,like enable-demuxer=rtsp.

**Comment by oc2pcoj** [comment]
Hello! Where I can enable RTSP protocol? Where is module.sh location?
