### ISSUE TITLE
MediaCodec了个寂寞？

### ISSUE THREAD

**Issue by izxyz** [Bilibili/ijkplayer#5616]
安卓平台ijk的内存占用是原生MediaCodec的一百倍以上。
安卓平台ijk的CPU占用是原生MediaCodec的十倍以上。
注：只是使用的NDK文档中的AMediaCodec写法，并未做任何优化，播放一个8G30帧的视频。

**Comment by nideshouhei** [comment]
我也发现这个问题 同样的硬解  就特么 cpu 占用率还是贼高 电视上软解能 89% ijk 硬解百分之 65%cpu 占用  media3 exo 硬解百分之 20% cpu 占用 ，搞不懂为啥 不是都用的 mediaCodec 么，兄弟你要是有解跟我说下 我愁的一
