### ISSUE TITLE
H.264 UDP stream - playback problem

### ISSUE THREAD

**Issue by m-o** [Bilibili/ijkplayer#566]
Hi, I am creating application to play and stream video from DJI dron. I receive H.264, or also called MPEG-4 Part 10, Advanced Video Coding (MPEG-4 AVC) data through UDP. I feed the data to player, but the player does not start.

I use this way to play data form GoPro3 and GoPo4 ant it works. But with this format, the player does not start. Nothing happens on prepare, and I do not get an error also.

Do you have any experience with this type of encoding or DJI drons?
Thank you!

Edit: I found out, that i receive whole NAL units, starting with "0 0 0 1" and then data throught UDP. Can ijkplayer work with this format or is it a problem? Can the problem be in my data?

**Comment by bbcallen** [comment]
Any log?

**Comment by maytrue** [comment]
check if receive NAL type 7, 8, known as  pps and sps.
