### ISSUE TITLE
player crashed sometimes when hardware encoder is enabled

### ISSUE THREAD

**Issue by melody-rain** [Bilibili/ijkplayer#567]
This is due to invalid surface passed to MediaCodec. Only if we call setDisplay() inside onPrepared() during which the valid surface is created will the problem be solved. But actually setDisplay() can be called at anytime. There might be some problems inside reconfigure_codec_l().

Will you please debug that? thanks.

**Comment by bbcallen** [comment]
Which device did you tested on?
Could you provide some code based on sample project to reproduce this problem?

Actually, after both SurfaceView and TextureView are enabled in preference. You can switch surface/display by clicking 'render' button in TitleBar.

**Comment by melody-rain** [comment]
I think I you have solved the issue by the code below:
if (SDL_AMediaCodec_isConfigured(opaque->acodec)) {
        if (opaque->acodec) {
            if (SDL_AMediaCodec_isStarted(opaque->acodec)) {
                SDL_AMediaCodec_stop(opaque->acodec);
            }
            if (opaque->quirk_reconfigure_with_new_codec) {
                ALOGI("quirk: reconfigure with new codec");
                SDL_AMediaCodec_decreaseReferenceP(&opaque->acodec);
               
                //---> you did not call create_codec_l() in your previous code.
                opaque->acodec = create_codec_l(env, node);
                if (!opaque->acodec) {
                    ALOGE("%s:open_video_decoder: create_codec failed\n", __func__);
                    ret = -1;
                    goto fail;
                }
            }
        }

        assert(opaque->weak_vout);
    }

Therefore this is not a bug any more. Thanks.

**Comment by Android4MediaPlayer** [comment]
@melody-rain ？？
