### ISSUE TITLE
 seekto()到某一position，进度会从position后退几秒再播放

### ISSUE THREAD

**Issue by shench5612390** [Bilibili/ijkplayer#572]
ijkMediaPlayer seekTo()某一position，进度会从position后退几秒
seekTo()方法用过后，用getcurrentposition()方法获得position

log日志：

01-01 07:20:44.250: E/MyMediaController(17261): updatePausePlay
01-01 07:20:44.250: E/setProgress(17261): 8920
01-01 07:20:44.280: E/MyMediaController(17261): show
01-01 07:20:44.280: E/MyMediaController(17261): updatePausePlay
01-01 07:20:44.280: E/endGesture(17261): seekTo16315
01-01 07:20:44.280: E/setProgress(17261): 16315
01-01 07:20:44.330: E/onSeekComplete(17261): position=16315
01-01 07:20:44.510: E/setProgress(17261): 16315
01-01 07:20:44.580: E/setProgress(17261): 11282
01-01 07:20:44.670: E/setProgress(17261): 11373
01-01 07:20:44.740: E/setProgress(17261): 11442
01-01 07:20:44.800: E/setProgress(17261): 11500
01-01 07:20:44.880: E/setProgress(17261): 11577
01-01 07:20:44.950: E/setProgress(17261): 11646
01-01 07:20:45.010: E/setProgress(17261): 11711
01-01 07:20:45.030: E/setProgress(17261): 11733

个人猜测：
seekto（position）中position位置不是关键帧；后退几秒是为了找到关键帧开始播放。

不知道怎么解决这个问题。。。请问哪位懂这个？

**Comment by asawalker** [comment]
播放的视频格式是m3u8吗

**Comment by shench5612390** [comment]
不是，是播放已经下载好的视频，有mp4,avi,rmvb等等。

**Comment by jih488** [comment]
ffmpeg查找关键帧的函数可以配置向前向后搜索关键帧，如果是向后搜索，就会出现这种情况；向前搜索会出现进度条跳跃的情况。这个需要有处理。

**Comment by shench5612390** [comment]
不知道要怎么处理，能给个方案吗？

**Comment by jih488** [comment]
seek完成后，可以得到每一帧的时间，当帧的时间大于等于seek的目标时间时，再让进度条滑动。但是这种有个问题，就是有时进度条会停止一段时间。

**Comment by shench5612390** [comment]
我这样处理过，效果很不理想，就放弃了。。。貌似这个问题现在无解。。。多谢指点了

**Comment by mcmc2014** [comment]
请问现在解决了吗

**Comment by hu8373551** [comment]
現在 m3u8 seekto  的問題有解決麽, 發現點擊到組后一點位置的時候， 直接完成播放。

**Comment by ijustkeepmoving** [comment]
视频的SEEKTO是有问题，大部分拖动后，会回跳，甚至从头开始播放。

我提供一个解决方案：
播放视频是，拖动操作结束后，记录拖动位置startPosition，用以下代码重新实例化IJKPLAYER，即可以实现拖到后准确播放。
 mMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "seek-at-start", startPosition);
