### ISSUE TITLE
使用mediacodec时，播放器起播慢

### ISSUE THREAD

**Issue by wqmijkplayer** [Bilibili/ijkplayer#577]
播放器起播时，feed_input_buffer在处理flush_pkt时会申请opaque->acodec_mutex，但此时drain_output_buffer函数可能由于dequeueoutbuffer超时已经长时间lock住了opaque->acodec_mutex，
这样大概会多需要1秒的时间。
请问，这需要如何规避这个问题？

**Comment by bbcallen** [comment]
define AMC_OUTPUT_TIMEOUT_US as a smaller value (in milliseconds)

**Comment by wqmijkplayer** [comment]
for AMC_OUTPUT_TIMEOUT_US, do you know which value is proper?

**Comment by bbcallen** [comment]
Depending on you benchmark.

**Comment by wqmijkplayer** [comment]
Thanks
