### ISSUE TITLE
请问Android上ijkplayer的几个问题

### ISSUE THREAD

**Issue by xiaoyaomeng** [Bilibili/ijkplayer#580]
1.是否可以通过ijkplayer获取到视频文件的某一帧（我要做一个预显示）
2.ijkplayer播放视频前，需要等很久（VideoView整个都是黑的），请问这个有解决方案吗，或者我可以在哪里加个loading的框吗？

**Comment by xiejinglan** [comment]
you can do anything you want.

**Comment by xiaoyaomeng** [comment]
@xiejinglan but i don't know about ijkplayer api

**Comment by xiejinglan** [comment]
you can use class MediaMetadataRetriever and call the function getFrameAtTime() to get a bitmap

**Comment by bbcallen** [comment]
1. ijkplayer is supposed to be a MediaPlayer, but not a MediaMetadataRetriever, for now.
2. VideoView is a View, you can put anything you want above it.

**Comment by xiaoyaomeng** [comment]
@xiejinglan 我现在就是用MediaMetadataRetriever， getFrameAtTime()，用完也release()了，但服务器那边说我还在占用这个资源，所以我在想ijkplayer中是否有获取缩略图的api，可能没有这个问题

**Comment by bbcallen** [comment]
Not for now.
