### ISSUE TITLE
[ENHANCEMENT] Ability to FLUSH the player's buffer

### ISSUE THREAD

**Issue by stuckless** [Bilibili/ijkplayer#585]
To give some context, I'm looking to use ijkplayer as the media player engine for this open source project. (https://github.com/OpenSageTV/sagetv-miniclient)

SageTV performs the seek() operations on the server, so, from the client side when a seek() happens, I need to flush player, flush the cached bytes that I have, and then immediately start reading from the stream, since SageTV will have seeked and started to push data to the video player.

I don't see a way to tell the player to flush().  So, today, I'm basically doing a seek(0) on the player since generally seeking will force the player to flush.  This works, most times, but other times I get some odd behaviours.  (eg, sometimes when the new bytes start arriving, I get an audio loss, and ijkplayer complains about the time in the stream)

If I had a way to flush the player, then I could just simply flush it, and the cached bytes, and then it would start reading the new bytes which would contain the newly seeked data.

**Comment by bbcallen** [comment]
How did you do same thing with other players, e.g. android.media.MediaPlayer?

By search avformat_seek_file in ff_ffplay, you would find all flush things.
actually, nearly same as seek(0).

**Comment by stuckless** [comment]
I use a seek(0) in all cases.   The original media players for SageTV were natively written for specific hardware and didn't rely on ffmeg, mplayer, etc.  The desktop client (which I didn't write relied on mplayer, and it uses playa.seek(Long.MAX_VALUE), so maybe I change seek(0) to seek(Long.MAX_VALUE) and see what happens.   Seeking does flush, so maybe the seek() is a good work around for flushing the player.  thx.

**Comment by stuckless** [comment]
I've been playing with seekTo(Long.MAX_VALUE) as a means to flush the buffer, but, when the seek happens, because the stream thinks it's not seekable, then then ret has an error status

https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/ff_ffplay.c#L2650

So, in the error block, I do the buffer flushing...
```                if (is->video_stream >= 0) {
                    if (ffp->node_vdec) {
                        ffpipenode_flush(ffp->node_vdec);
                    }
                    packet_queue_flush(&is->videoq);
                    packet_queue_put(&is->videoq, &flush_pkt);
                }```

And this works better, but, there still must be some buffered data, because the video immediately starts playing the new data, but only for a frame or two, and then, starts playing the "old" data.

Interesting enough, if I seek twice in my app, ie, seeks once wait half second and then seek again, the buffers are completely cleared, and the video plays correctly.

I've also added
```
                    avformat_flush(is->ic);
                    avio_flush(is->ic->pb);
```
but still the same results.

I'm wondering if you know of other commands I can use the flush?  thanks.

**Comment by stuckless** [comment]
@bbcallen Just wondering if you have any thoughts on how I can completely flush the player?  thx.

**Comment by bbcallen** [comment]
No, I'm working on something else. And I don't know any method except you has listed above.

I would recreate a completely new player if I need a "completely flush".

**Comment by stuckless** [comment]
@bbcallen thanks.
