### ISSUE TITLE
Android 在缓冲视频前经常要卡10秒左右

### ISSUE THREAD

**Issue by lvtianhang** [Bilibili/ijkplayer#586]
10-26 11:18:46.351: D/IJKMEDIA(21569): ffpipenode_create_video_output_from_android_mediacodec()
10-26 11:18:46.351: I/IJKMEDIA(21569): SDL_RunThread: [21988] ff_msg_loop
10-26 11:18:46.351: D/IJKMEDIA(21569): message_loop
10-26 11:18:46.351: D/IJKMEDIA(21569): FFP_MSG_FLUSH:
10-26 11:18:56.495: D/IJKMEDIA(21569): request: GET /****.mp4 HTTP/1.1

不知道是什么原因造成的呢？这10秒都在请求什么呢？

**Comment by bbcallen** [comment]
Connect to server.

**Comment by lslxdx** [comment]
建议在调网络视频的时候，使用VLC和ijkplayer打开同一个视频对比一下，这样可以排除由于网络问题而导致的延时

**Comment by lvtianhang** [comment]
好的 谢谢 我会使用VLC也尝试一下
