### ISSUE TITLE
BUG：断网后播放器播放完之前下载好的缓存后就会报错 恢复网络也不会重新连接

### ISSUE THREAD

**Issue by chodison** [Bilibili/ijkplayer#587]

**Comment by bbcallen** [comment]
Not support, yet.

**Comment by chodison** [comment]
@bbcallen  Do you have a plan?

**Comment by bbcallen** [comment]
Not for now.

**Comment by SevenJustin** [comment]
@chodison  can you tell me something about how to use ijkplayer's cache http video stream to local file then play local video afterwards , thanks
