### ISSUE TITLE
ijkplayer ios 支持rtmp协议吗？

### ISSUE THREAD

**Issue by andyjmzheng** [Bilibili/ijkplayer#592]
请问我们的ijkplayer 是不是支持在ios上的rtmp协议？我在android上测试时支持的。

**Comment by bbcallen** [comment]
Maybe.

**Comment by chodison** [comment]
You should have a try.

**Comment by xuxiandi** [comment]
我认为应该是支持的。用的都是ffmpeg 。ffmpeg 里面带有rtmp 协议的支持。

**Comment by lslxdx** [comment]
支持，我们现在用的就是RTMP

**Comment by andyjmzheng** [comment]
@lslxdx  谢谢，。。。。我也已经用上了。。

**Comment by mandagod** [comment]
ffmpeg only support rtmp, but does no support rtmpt://, rtmpe://, rtmpte://, and rtmps://.
I think if ffmpeg depends on the librtmp, it all will ok.

**Comment by jacky1234** [comment]
@lslxdx，你好我怎么测试了就不支持rtmp呢？测试是支持hls的

**Comment by lslxdx** [comment]
你checkout到这个tag上试试：
commit 3289254bbbd24a5230816811d53b49ea78775996
Author: Zhang Rui <bbcallen@gmail.com>
Date:   Tue Mar 17 18:30:32 2015 +0800

    k0.2.3
