### ISSUE TITLE
Opening RTMP live stream

### ISSUE THREAD

**Issue by azizbekian** [Bilibili/ijkplayer#594]
I'm trying to open rtmp live stream (the rtmp streaming link is not broken).
But  mVideoView.setVideoPath(MY_RTMP_URI) won't open the stream. Instead, dialog gets popped off with "Unknown".

In logs:

D/MediaPlayer: Couldn't open file on client side, trying server side
E/: Failed to open file 'rtmp://MY_RTMP_URI/'. (No such file or directory)

What am I missing?

**Comment by aaxpers** [comment]
Issue resolved. 
Had to use mVideoView.setVideoURI(MY_RTMP_URI), instead of mVideoView.setVideoPath(MY_RTMP_URI).

The sample automatically treated my URI as String, that's why it tried to call setVideoPath.

**Comment by fatiao101** [comment]
@aaxpers 
I just add mVideoPath = "rtmp://live.hkstv.hk.lxdns.com/live/hks";
before mVideoView.start();
still , " E/: Failed to open file 'rtmp://live.hkstv.hk.lxdns.com/live/hks'. (No such file or directory)".

**Comment by aaxpers** [comment]
@fatiao101, not mVideoPath -> mVideoURI

**Comment by fatiao101** [comment]
@aaxpers 

mVideoUri = Uri.parse("rtmp://live.hkstv.hk.lxdns.com/live/hks");
mVideoView.setVideoURI(mVideoUri);
mVideoView.start();

it doesn't work.

**Comment by zaiyunduan** [comment]
@aaxpers 
I cannot understand "not mVideoPath -> mVideoURI".
More details? Thanks very much

**Comment by azizbekian** [comment]
@zaiyunduan 
Now I use IjkVideoView.setVideoURI() method and it opens stream normally.

**Comment by susuLee** [comment]
thanks ,it helps me.

**Comment by adteven** [comment]
mVideoView.setVideoURI(Uri.parse("rtmp://lssplay.aodianyun.com:1935/demo/game"));
mVideoView.start();
I changed the code like this ,but still can not play the rtmpStream, what am i missing

**Comment by azizbekian** [comment]
Your stream opened normally at my side. Look into the Logcat attentively.

**Comment by adteven** [comment]
Can you send me the project ？so i can check

**Comment by adteven** [comment]
when I use the url:
mVideoView.setVideoURI(Uri.parse("rtmp://lssplay.aodianyun.com:1935/demo/game"));
mVideoView.start();
the LogCat:
12-07 09:37:49.242 19856-19856/tv.danmaku.ijk.media.sample W/dalvikvm: Unable to resolve superclass of Ltv/danmaku/ijk/media/player/AndroidMediaPlayer$MediaDataSourceProxy; (163)
12-07 09:37:49.242 19856-19856/tv.danmaku.ijk.media.sample W/dalvikvm: Link of class 'Ltv/danmaku/ijk/media/player/AndroidMediaPlayer$MediaDataSourceProxy;' failed
12-07 09:37:49.242 19856-19856/tv.danmaku.ijk.media.sample D/dalvikvm: DexOpt: unable to opt direct call 0x51d5 at 0x05 in Ltv/danmaku/ijk/media/player/AndroidMediaPlayer;.setDataSource
12-07 09:37:49.252 19856-19856/tv.danmaku.ijk.media.sample E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
12-07 09:37:49.252 19856-19856/tv.danmaku.ijk.media.sample D/MediaPlayer: Couldn't open file on client side, trying server side
12-07 09:37:49.262 19856-19867/tv.danmaku.ijk.media.sample E/MediaPlayer: error (1, -2147483648)
12-07 09:37:49.352 19856-19856/tv.danmaku.ijk.media.sample E/MediaPlayer: Error (1,-2147483648)
12-07 09:37:49.352 19856-19856/tv.danmaku.ijk.media.sample D/IjkVideoView: Error: 1,-2147483648
12-07 09:37:49.362 19856-19856/tv.danmaku.ijk.media.sample I/AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
12-07 09:37:49.522 19856-19856/tv.danmaku.ijk.media.sample I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@424f48e8 time:41682163

**Comment by bbcallen** [comment]
You were using AndroidMediaPlayer, not IjkMediaPlayer.

**Comment by adteven** [comment]
so how to user the IjkMediaPlayer   I just user the sample to play

**Comment by adteven** [comment]
I have solved thank you
