### ISSUE TITLE
AndroidMediaPlayer和IjkMediaPlayer有什么区别？

### ISSUE THREAD

**Issue by niyingxunzong** [Bilibili/ijkplayer#596]

**Comment by bbcallen** [comment]
AndroidMediaPlayer is base on android.media.MediaPlayer,
IjkMediaPLayer is based on FFmpeg.

**Comment by yuxinLi** [comment]
借楼问一下大神：
       我目前用的是android.media.MediaPlayer ， 然后和ios 打开同一个在线文件 ， 发现android的显示很慢，问一下MediaPlayer 和 FFmpeg 分别是要下载多少帧才开始渲染的 ？
