### ISSUE TITLE
请教： 播放rtmp直播流，需要配置的参数

### ISSUE THREAD

**Issue by zhangxyfs** [Bilibili/ijkplayer#603]
android端的rtmp直播播放时候需要参数我如何配置？
或者类似下面这种配置的文档我在哪能够查看，谢谢。
 ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 0);

**Comment by bbcallen** [comment]
https://ffmpeg.org/ffmpeg-protocols.html#rtmp

For demuxer
```
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, <key>, <value>);
```

**Comment by zhangxyfs** [comment]
thanks~
