### ISSUE TITLE
ijkplayer 问题

### ISSUE THREAD

**Issue by andyjmzheng** [Bilibili/ijkplayer#604]
rtmp直播的时候。我把直播源断开20秒后。再次打开直播源。我们的ijkplayer 会一直打印消息FFP_MSG_COMPLETE.即使我增加了重试 从新调用函数setVideoPath，和start 函数。依然还是会打印
FFP_MSG_COMPLETE。不能继续播放。
遇到类似的情况后。我如何可以重试成功，可以继续播放？
@bbcallen

**Comment by bbcallen** [comment]
IjkVideoView is not intended to be reset for new URL.
Implement your own video view, and always create new player for url.
