### ISSUE TITLE
Android.mk:1: *** missing separator

### ISSUE THREAD

**Issue by henzaitianji** [Bilibili/ijkplayer#606]
android cywin编译最后一步
$ ./compile-ijk.sh all
profiler build: NO
/cygdrive/f/studiocode/ijkplayer-k0.4.1.1/android/ijkplayer/ijkplayer-armv5/src/main/jni/Android.mk:1: *** missing separator。 停止。
/cygdrive/f/studiocode/ijkplayer-k0.4.1.1/android
profiler build: NO
[armeabi-v7a] Install        : libijkffmpeg.so => libs/armeabi-v7a/libijkffmpeg.so
/cygdrive/f/studiocode/ijkplayer-k0.4.1.1/android
profiler build: NO
/cygdrive/f/studiocode/ijkplayer-k0.4.1.1/android/ijkplayer/ijkplayer-x86/src/main/jni/Android.mk:1: *** missing separator。 停止。
/cygdrive/f/studiocode/ijkplayer-k0.4.1.1/android
profiler build: NO
/cygdrive/f/studiocode/ijkplayer-k0.4.1.1/android/ijkplayer/ijkplayer-arm64/src/main/jni/Android.mk:1: *** missing separator。 停止。
/cygdrive/f/studiocode/ijkplayer-k0.4.1.1/android
怎么解决啊

**Comment by bbcallen** [comment]
Sorry, I don't have a windows PC, so I can't maintain build under cygwin.

**Comment by henzaitianji** [comment]
why not submit the so files with every version

**Comment by bbcallen** [comment]
Why should I?
It's too large to put into git repo.

**Comment by henzaitianji** [comment]
you can provide them with a download url like baidu cloud disk ,it is a open project ,Convenient to others is Convenient for yourself,thank,it is your freedom
