### ISSUE TITLE
How do I resume playing from a certain position?

### ISSUE THREAD

**Issue by awfulcode** [Bilibili/ijkplayer#607]
Hi guys,

I'm trying to store the position at which the player stopped playing and then get back to it once the user opens up the same file again. What's the proper way of doing that? I thought it would be the segmentresolver, so this is the code I tried in viewDidLoad:

```objc
    defaults = [NSUserDefaults standardUserDefaults];
    fileName = [self.url lastPathComponent];
    if ([defaults objectForKey:fileName]) {
        NSString *progressValue = [defaults objectForKey:fileName];
        [self.segmentResolver urlOfSegment:[progressValue doubleValue]];
        NSString *stringURL = [self.url path];
        self.player = [[IJKFFMoviePlayerController alloc] initWithContentURLString:stringURL withOptions:nil withSegmentResolver:self.segmentResolver];
    } else {
    
        self.player = [[IJKFFMoviePlayerController alloc] initWithContentURL:self.url withOptions:nil];
    }
```
And this is how I store the position in viewDidDisappear:

```objc
    NSString *playbackTime = [NSString stringWithFormat:@"%f",self.player.currentPlaybackTime];
    [defaults setObject:playbackTime forKey:fileName];
```

So this doesn't work at all. What's the proper way of doing it? I had tried forcing a seek after the video started playing, but that created all sorts of weird bugs as well.

Thanks!

**Comment by bbcallen** [comment]
SegmentResolver has nothing todo with this.
Please describe "all sorts of weird bugs"

**Comment by awfulcode** [comment]
It seems to be down to one problem. Was trying to seek before [self.player prepareToPlay].  Now, when I tell it to seek, I get an EXC_BAD_ACCESS in line 3301 of ffplay.c (    int64_t start_time = is->ic->start_time; )

This is how I'm trying to get it to resume playing at the same spot:

```objc
    NSString *playbackTime = [NSString stringWithFormat:@"%f",self.player.currentPlaybackTime];
    [defaults setObject:playbackTime forKey:fileName];
```

Also, I see there's a ffp_start_from_l method in ffplay.c, and an auto_resume property. Should I be using that instead? How would you approach this? I just want play to resume where it was stopped when the user reopens the file.

Thanks!

**Comment by awfulcode** [comment]
I think I figured it out. Put the resume code into <b>mediaIsPreparedToPlayDidChange</b> and turned autoplay on. It seems like this guarantees that we're not calling methods that aren't ready to run yet (which explains all the weird bugs I was getting – one of them was an AudioUnit IO thread blocking everything else).

If there's a more elegant solution than this, please let me know. Thanks!

**Comment by bbcallen** [comment]
I'm afraid it's the only way, for now.

**Comment by bbcallen** [comment]
Feel free to reopen if any more questions
