### ISSUE TITLE
iOS build #include "libavformat/avformat.h" file not found

### ISSUE THREAD

**Issue by lvtianhang** [Bilibili/ijkplayer#608]
iOS build
#include "libavformat/avformat.h"
"libavformat/avformat.h" file not found

**Comment by bbcallen** [comment]
Did you build ffmpeg first?

**Comment by lvtianhang** [comment]
yes

cd ios
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all

It has been performed

**Comment by bbcallen** [comment]
Any more information?
I can't reproduce this issue at my side.

**Comment by lvtianhang** [comment]
commendtools Version incorrect
Lead to compile error

Thanks！

**Comment by xclidongbo** [comment]
what?

**Comment by xclidongbo** [comment]
What's the answer?

**Comment by Assylkhan** [comment]
xclidongbo +

**Comment by Giggs123** [comment]
http://www.jianshu.com/p/1f06b27b3ac0
