### ISSUE TITLE
请教一个问题 ff_ffplay.c打开文件失败 permission denied

### ISSUE THREAD

**Issue by melody-rain** [Bilibili/ijkplayer#609]
Hi @bbcallen 请教个问题.比如我在彩信里添加视频然后想预览播放以下视频,然后跳到ijkplayer里播放这个视频.但是这时候传来的视频由于已经被拷贝到彩信的apk目录里,即/data/data/...里面,这时候ff_ffplay.c是没有权限读取这个视频的,报了permission denied.求教这种情况怎么解? 我看你通过ffmpeg的register注册了个pipe的protocol,我需要另外注册个什么新的protocol来解决这个问题吗? 谢谢~

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/android/ijkplayer/ijkplayer-java/src/main/java/tv/danmaku/ijk/media/player/IjkMediaPlayer.java#L399

**Comment by melody-rain** [comment]
@bbcallen 这个地方我调试时发现走到这里了.

    public void setDataSource(FileDescriptor fd)
            throws IOException, IllegalArgumentException, IllegalStateException {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.HONEYCOMB_MR1) {
            int native_fd = -1;
            try {
                Field f = fd.getClass().getDeclaredField("descriptor"); //NoSuchFieldException
                f.setAccessible(true);
                native_fd = f.getInt(fd); //IllegalAccessException
            } catch (NoSuchFieldException e) {
                throw new RuntimeException(e);
            } catch (IllegalAccessException e) {
                throw new RuntimeException(e);
            }
            _setDataSourceFd(native_fd);
        } else {
            ParcelFileDescriptor pfd = ParcelFileDescriptor.dup(fd);
            try {
                _setDataSourceFd(pfd.getFd());
            } finally {
                pfd.close();
            }
        }
    }

这个方法里不管走哪一条路径都会出现permission denied的问题.

**Comment by bbcallen** [comment]
Can you access this FileDescriptor directly from java side?

**Comment by melody-rain** [comment]
Hi @bbcallen 

It has access to fd. See the code below:

    public void setDataSource(FileDescriptor fd)
            throws IOException, IllegalArgumentException, IllegalStateException {
        FileInputStream file = new FileInputStream(fd);
        byte[] temp = new byte[20];
        file.read(temp, 0, 10);
        for(byte a : temp) {
            Log.e(TAG, "" + a);
        }
        ....
    }

It prints data read from fd and the printed values are correct.

**Comment by bbcallen** [comment]
Can you play it with android.media.MediaPlayer?

**Comment by melody-rain** [comment]
@bbcallen  yes Android's original MediaPlayer works well. That's what I am curious about. How can we give permission to ffmpeg to read the file with "fd"? 

Also "stream 0, offset 0x2c: partial file." is a problem. It happens only to mp4 or 3gp files. Other files can be played with "fd".

I play mp4 files from multimedia message, which means I use "fd" to setDataSource. Probably because of "stream 0, offset 0x2c: partial file." I cannot play the mp4 file, not because that permission is not given to the "fd".

**Comment by bbcallen** [comment]
Possibly because ffmpeg's pipe protocol doesn't support seek()

Have a look at ffmpeg/libavformat/file.c

**Comment by melody-rain** [comment]
@bbcallen yes I've checked that. Can we use any other protocol to use "fd"?

**Comment by bbcallen** [comment]
AFAIK, pipe protocol is the most easy way.

**Comment by bbcallen** [comment]
Feel free to reopen if any more questions
