### ISSUE TITLE
about play ac3 media 

### ISSUE THREAD

**Issue by ncnk** [Bilibili/ijkplayer#611]
if i want to support ac3 media ,did i only need to uncomment "export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-parser=ac3" in module-lite.sh?
Still need to modify other place？

**Comment by bbcallen** [comment]
run "./configure --help" in FFmpeg's directory.

**Comment by ncnk** [comment]
thanks for your answer, i solve this question by rebuilding FFmpeg use module-default.sh
