### ISSUE TITLE
libavformat/avformat.h file not found

### ISSUE THREAD

**Issue by gesw1219** [Bilibili/ijkplayer#612]
ios  build  libavformat/avformat.h file not found,

i just buid as

 git clone https://github.com/Bilibili/ijkplayer.git ijkplayer-ios
cd ijkplayer-ios
git checkout -B latest k0.4.2.4

./init-ios.sh

cd ios
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all

what should  i do before do these?
or after?

**Comment by bbcallen** [comment]
Can't reproduce, can you provide more information, such as build logs.

**Comment by shinrenpan** [comment]
Same issue here.
Xcode version 6.4 (6E35b)
Git version 2.3.2 (Apple Git-55)

Error log:
```
xcrun -sdk iphoneos clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
```

**Comment by bbcallen** [comment]
Use Xcode 7.x instead,
or remove "-fembed-bitcode" from ios/tools/do-compile-ffmpeg.sh

**Comment by shinrenpan** [comment]
Thanks @bbcallen

**Comment by xclidongbo** [comment]
What's the answer?

**Comment by Giggs123** [comment]
http://www.jianshu.com/p/1f06b27b3ac0
