### ISSUE TITLE
[bug report]有时会发生INFO_TRY_AGAIN_LATER导致视频不再有变化

### ISSUE THREAD

**Issue by qazmoon** [Bilibili/ijkplayer#613]
有时播放视频中会在函数drain_output_buffer_l里发生
(output_buffer_index == AMEDIACODEC__INFO_TRY_AGAIN_LATER) ，
结果导致视频画面不再有变化了。

**Comment by zyqing1** [comment]
我使用的时候也偶尔出现了这个问题，有解决方案了吗？

**Comment by qazmoon** [comment]
@zyqing1 暂时没有。你是播放H264时出现问题的么

**Comment by zyqing1** [comment]
@qazmoon 是的，是h264

**Comment by qazmoon** [comment]
发现有时SDL_AMediaCodec_dequeueOutputBuffer返回-1，紧跟着SDL_AMediaCodec_dequeueInputBuffer也返回-1，于是video画面断了。

**Comment by qazmoon** [comment]
@zyqing1  你解决这现象了吗？

**Comment by zyqing1** [comment]
@qazmoon 还没有

**Comment by chodison** [comment]
device detail information to the problom

**Comment by qazmoon** [comment]
@chodison  小米TV

**Comment by qazmoon** [comment]
本bug  同 https://github.com/Bilibili/ijkplayer/issues/613

**Comment by xiaoyaomeng** [comment]
@qazmoon 我的视频码流也是H264的

**Comment by qazmoon** [comment]
@zyqing1 用百度网盘把文件传过来

**Comment by zyqing1** [comment]
@qazmoon 我播放的在线ts流，而且发生概率的很低，这两天没遇到。

**Comment by xiaolei0808** [comment]
我遇到的一个视频画面卡住的问题是，播放过程中，在播放页上打开一个webview，关闭webview之后，很高的概率出现视频画面卡住，音频正常播放的情况。
