### ISSUE TITLE
SDL_AMediaCodecJava_getOutputBuffer和SDL_AMediaCodecJava_getInputBuffer空指针问题

### ISSUE THREAD

**Issue by wqmijkplayer** [Bilibili/ijkplayer#614]
SDL_AMediaCodecJava_getOutputBuffer和SDL_AMediaCodecJava_getInputBuffer在调用时，偶尔会出现空指针
例如：SDL_AMediaCodecJava_getOutputBuffer函数随时可能被调用，这时会取opaque->output_buffer_array数组元素的值。但是，当接收到AMEDIACODEC__INFO_OUTPUT_BUFFERS_CHANGED消息时，SDL_AMediaCodecJava_dequeueOutputBuffer函数会将opaque->output_buffer_array对象delete掉。
所以SDL_AMediaCodecJava_getOutputBuffer函数会调用到空指针。
请问，解决这个问题，是调用前加空指针判断，还是从流程上着手？

**Comment by bbcallen** [comment]
SDL_AMediaCodecJava_getOutputBuffer() will recreate it in getOutputBuffers();

**Comment by wqmijkplayer** [comment]
getOutputBuffers()的确会重建output_buffer_array数组，但是SDL_AMediaCodecJava_dequeueOutputBuffer函数可能会在重建后将output_buffer_array对象delete，毕竟SDL_AMediaCodecJava_dequeueOutputBuffer函数运行时间是随机的

**Comment by bbcallen** [comment]
SDL_AMediaCodecJava_dequeueOutputBuffer() and SDL_AMediaCodecJava_getOutputBuffer() are always run in same thread.

Actually, ijkplayer use direct-render mode of MediaCodec. It does't need to access output buffer at all. getOutputBuffer() is only used to ensure the buffer is valid.

**Comment by bbcallen** [comment]
Feel free to reopen if any more questions
