### ISSUE TITLE
从https://github.com/Bilibili/openssl下载的新openssl，为啥编译出错

### ISSUE THREAD

**Issue by lyqaiym** [Bilibili/ijkplayer#616]
找不到头文件啊
make[1]: Entering directory `/home/lyq/git/openssl-ijk/openssl-armv7a/crypto'
In file included from /usr/include/stdlib.h:24:0,
                 from include/internal/cryptlib.h:62,
                 from cryptlib.c:117:
/usr/include/features.h:374:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.

**Comment by bbcallen** [comment]
It's only a mirror of openssl official repository.
Check your own environment first.

**Comment by lyqaiym** [comment]
我复制了compile-openssl.sh和tools/do-compile-openssl.sh,编译init-android-openssl.sh来的可以，这个不行，我就是想问问，改哪里能编译成功，现在没有arm64的openssl

**Comment by lyqaiym** [comment]
我把你们的Configure复制过来，找到了一些问题，新的版本，头文件地址变了。
1626行
你们的是
open(IN,'<crypto/opensslv.h') || die "unable to read opensslv.h:$!\n";
新的是
open(IN,'<include/openssl/opensslv.h') || die "unable to read opensslv.h:$!\n";
1855行
你们的是
unlink("crypto/opensslconf.h.new") || die "unable to remove old crypto/opensslconf.h.new:$!\n" if -e "crypto/opensslconf.h.new";
open(OUT,'>crypto/opensslconf.h.new') || die "unable to create crypto/opensslconf.h.new:$!\n";
新的是
unlink("include/openssl/opensslconf.h.new") || die "unable to remove old include/openssl/opensslconf.h.new:$!\n" if -e "include/openssl/
opensslconf.h.new";
open(OUT,'>include/openssl/opensslconf.h.new') || die "unable to create include/openssl/opensslconf.h.new:$!\n";
1971行
你们的是
rename("crypto/opensslconf.h","crypto/opensslconf.h.bak") || die "unable to rename crypto/opensslconf.h\n" if -e "crypto/opensslconf.h";
rename("crypto/opensslconf.h.new","crypto/opensslconf.h") || die "unable to rename crypto/opensslconf.h.new\n";
新的是
rename("include/openssl/opensslconf.h","include/openssl/opensslconf.h.bak") || die "unable to rename include/openssl/opensslconf.h\n" if -e "include/openssl/opensslconf.h";
rename("include/openssl/opensslconf.h.new","include/openssl/opensslconf.h") || die "unable to rename include/openssl/opensslconf.h.new\n";
改了以后，找不到头文件的错误没有了，又有一个新错误
bn_lib.c: In function 'BN_free':
bn_lib.c:262:21: error: 'BN_FLG_FREE' undeclared (first use in this function)
         a->flags |= BN_FLG_FREE;
我把你们的741行的
my $bn	="crypto/bn/bn.h";
改成
my $bn	="include/openssl/bn.h";
还是不可以
希望你们更新下最新的openssl吧

**Comment by lyqaiym** [comment]
最后没办法，从https://www.openssl.org/source/下载openssl-1.0.2d.tar.gz稳定版就编过了，不是脚本问题，是这个工程问题啊
