### ISSUE TITLE
how to turn off the voice,i didn't find the voice adjust interface?

### ISSUE THREAD

**Issue by YAimport** [Bilibili/ijkplayer#619]
i think it should have a be silent property to help we do more various request?some body to  help me .

**Comment by bbcallen** [comment]
No individual volume setting, for now.

**Comment by YAimport** [comment]
for now ,if i want to silent ,what should i do ?

**Comment by bbcallen** [comment]
silent the system with volume related system API
Or set player option "an"="1" to disable audio.

**Comment by bbcallen** [comment]
Or you can try mp.setVolume(0, 0) which I haven't tested, yet.

**Comment by YAimport** [comment]
Thank you very much! I will try PlAN B.The player that i'm dealing with has two objects.One is set up on the ipad,and the other is set up on the external screen. Therefore, we need to mute one of them.It is better to mute that on the external screen.

**Comment by bbcallen** [comment]
I don't think you can control ijkplayer's volume individually from system's volume on iOS.

**Comment by YAimport** [comment]
mp.setVolume(0, 0),I don't find this method in ijkplayer public method?Now could i have other method to control mp volume? could you open this interfance to help me  ? thank you very much!

**Comment by bbcallen** [comment]
Use MPMusicPlayerController on iOS.

**Comment by YAimport** [comment]
But what i needed is playing video on ijkPlayer. Could you tell me  where the mp.setVolume(0, 0) or  player option "an"="1" i don't find it .

**Comment by bbcallen** [comment]
Use MPMusicPlayerController to adjust system volume.

**Comment by bbcallen** [comment]
Feel free to reopen if any more questions
