### ISSUE TITLE
rtsp无重连机制

### ISSUE THREAD

**Issue by haoshaolin** [Bilibili/ijkplayer#62]
请教个问题：ffmpeg中，rtsp的实现是不是没有重连机制。比如网络断开过会在恢复，是不是无法正常恢复播放？

**Comment by chodison** [comment]
这个需要你在IJK的播放逻辑里添加的，关闭再重新播放。

**Comment by CrazyPeter** [comment]
@haoshaolin 

我测试到，是检测到了播放状态的改变。
于是在检测方法那里添加了重新播放的代码。
测试过只添加play，但是还是无法重新开启，所以在开始前要停止原来的播放。
我估计是因为rtsp丢包，调起了链接状态的异常，本地关闭相关的接口，造成无法直接继续播放。

相关代码如下。
- (void)loadStateDidChange:(NSNotification*)notification{
 IJKMPMovieLoadState loadState = _player.loadState;
    if ((loadState & IJKMPMovieLoadStatePlaythroughOK) != 0) {
        NSLog(@"loadStateDidChange: IJKMPMovieLoadStatePlaythroughOK: %d\n", (int)loadState);
    } else if ((loadState & IJKMPMovieLoadStateStalled) != 0) {
        NSLog(@"loadStateDidChange: IJKMPMovieLoadStateStalled: %d\n", (int)loadState);
        [self.player stop];
        [self.player play];
        [self.mediaControl refreshMediaControl];
    } else {
        NSLog(@"loadStateDidChange: ???: %d\n", (int)loadState);
    }
}

**Comment by mistak** [comment]
你重新播放成功了吗？是怎么做到的？@CrazyPeter

**Comment by CrazyPeter** [comment]
@mistak 
如果我提到的方法不行，可以使用一个简单粗暴的方法，直接stop，然后nil掉对象再重新创建，相当于重连。ps：由于项目紧张，没有时间测试具体问题。

**Comment by mistak** [comment]
好吧，我也是这样做的。。。
