### ISSUE TITLE
能不能开个QQ群讨论把代码改的更好啊？

### ISSUE THREAD

**Issue by qazmoon** [Bilibili/ijkplayer#621]
能不能开个QQ群讨论把代码改的更好啊？

**Comment by bbcallen** [comment]
I've never seen and expected any serious technical discussion in any QQ group.

**Comment by Android4MediaPlayer** [comment]
@bbcallen beartchat

**Comment by linjiansheng** [comment]
@qazmoon 
我建了一个qq群，大家一起来讨论
qq群 : 490805051
