### ISSUE TITLE
请教多线程问题

### ISSUE THREAD

**Issue by wqmijkplayer** [Bilibili/ijkplayer#624]
在一个进程，启动了多个mediaplayer播放线程
1. 若使用ijkplayer软解流程会有什么问题吗？
2. 若使用mediacodec硬解，进程只加载了一份stagefright库进行解码，这样会有问题吗？
十分感谢

**Comment by bbcallen** [comment]
1. More cpu and memory usage.
2. Don't understand what do you mean about "load only one stagefright library".

**Comment by qazmoon** [comment]
@wqmijkplayer 启动多个播放线程，一般只能有一个线程可以使用mediacodec硬解，
其他线程必须软解

**Comment by wqmijkplayer** [comment]
@qazmoon 可以启动多个使用mediacodec硬解的线程吗？
因为用户使用硬解码场景实在太多

**Comment by qazmoon** [comment]
我所了解到的是绝大多数的硬解不支持多路同时解码，也就无法支持多线程的同时解码

**Comment by wqmijkplayer** [comment]
@bbcallen 谢谢回复
我没有说清楚
请问，Ijkplayer比android原生的stagefright优秀，主要优秀在什么地方？可否详细谈谈

**Comment by wqmijkplayer** [comment]
@qazmoon android的stagefright在一个进程里边启动多个mediaplayer线程进行播放，解码还是只是一路吗？
