### ISSUE TITLE
一些Android手机设备无法播放4K视频？

### ISSUE THREAD

**Issue by xiaoyaomeng** [Bilibili/ijkplayer#627]
APP需要播放4k视频，采用了ijkplayer的播放器，现在发现有一些设备无法播放4K视频，有声音没图像，这个是否有办法解决呢？

**Comment by xiaoyaomeng** [comment]
@bbcallen  发现不使用硬解，改为软解就有图像了，但是非常非常非常卡顿。
请问这种是设备问题，没办法避免的吗？

**Comment by qazmoon** [comment]
把流用百度网盘传上来

**Comment by qazmoon** [comment]
此问题同
https://github.com/Bilibili/ijkplayer/issues/605
https://github.com/Bilibili/ijkplayer/issues/613

**Comment by xiaoyaomeng** [comment]
@qazmoon 链接: http://pan.baidu.com/s/1hq6Rtg4 密码: jiis

**Comment by qazmoon** [comment]
@xiaoyaomeng 你的设备支持4k的硬解么

**Comment by xiaoyaomeng** [comment]
@qazmoon 这个也并不清楚，请问是否知道有什么方式可以判断设备是否支持硬解（API or Software）

**Comment by qazmoon** [comment]
设备型号

**Comment by xiaoyaomeng** [comment]
美图手机M4

**Comment by qazmoon** [comment]
@xiaoyaomeng 岂止4K，你的手机能支持8K

**Comment by xiaoyaomeng** [comment]
@qazmoon ？？？？？？
