### ISSUE TITLE
IjkMediaPlayer,surface is invalid after it call reset()

### ISSUE THREAD

**Issue by asawalker** [Bilibili/ijkplayer#630]
IjkMediaPlayer,surface is invalid after it call reset(), but AndroidMediaPlayer is ok.

**Comment by asawalker** [comment]
IjkMediaPlayer 调用 reset() 后，surface invalid，
使用场景：正在播放的时候，更换播放地址后，出现画面 停滞，但是有声音。经测试 发现，openVideo函数中调用了 release函数，release函数中调用了 reset函数， reset函数调用后，发现当前surface 无效。所以会出现这个问题。

**Comment by asawalker** [comment]
之前的版本 没有出现过此问题。

**Comment by asawalker** [comment]
播放器如果发生错误， 在mErrorListener中设置一个新的播放地址后，也是surface 也是无效的。这2个问题都是针对android版本的

**Comment by bbcallen** [comment]
Feel free to reopen if any more questions
