### ISSUE TITLE
在ijkplayer下编译rtmpdump 报错

### ISSUE THREAD

**Issue by andyjmzheng** [Bilibili/ijkplayer#631]
在ijkplayer 下编译rtmpdump 总报这样的错误。
有人知道原因吗？
Android NDK: Your APP_BUILD_SCRIPT points to an unknown file: ./jni/Android.mk    
/home/jmzheng/tools/android-ndk-r9d/build/core/add-application.mk:187: *** Android NDK: Aborting...    .  Stop.

**Comment by lyqaiym** [comment]
是不是你建的目录不对啊？

**Comment by bbcallen** [comment]
Has nothing to do with ijkplayer.
