### ISSUE TITLE
uses-sdk:minSdkVersion 14 cannot be smaller than version 21 declared in library 

### ISSUE THREAD

**Issue by cikichen** [Bilibili/ijkplayer#634]
```
	uses-sdk:minSdkVersion 14 cannot be smaller than version 21 declared in library [tv.danmaku.ijk.media:ijkplayer-arm64:0.4.2.4] 

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 21 declared in library [tv.danmaku.ijk.media:ijkplayer-arm64:0.4.2.4]  
/build/intermediates/exploded-aar/tv.danmaku.ijk.media/ijkplayer-arm64/0.4.2.4/AndroidManifest.xml
  	Suggestion: use tools:overrideLibrary="tv.danmaku.ijk.media.player_arm64" to force usage
```

**Comment by bbcallen** [comment]
So?

**Comment by quangtrung89** [comment]
How to import both arm7a and armv8a-64 inside one project?

    compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.4.2.4'
    compile 'tv.danmaku.ijk.media:ijkplayer-arm64:0.4.2.4'

I got same issue like cikichen.

**Comment by bbcallen** [comment]
set your app's minSdkVersion to 21

**Comment by quangtrung89** [comment]
But my app need to support from SDK 16.

**Comment by bbcallen** [comment]
Then, don't import any arm64 so.

**Comment by quangtrung89** [comment]
If not import arm64, devices has cpu arm v8 64 cannot play video.

**Comment by cikichen** [comment]
Yes, same to me.

**Comment by bbcallen** [comment]
arm64 device would find armv7a so files, if there are not any .so file (not only ijkplayer's) under your app's arm64-v8a directory.

FYI, my Nexus 9 works well with armv7a so files.

If you insist to import ijkplayer-arm64, you can extract the so file from aar or build it from source code, and put it into your arm64-v8a directory.

**Comment by quangtrung89** [comment]
I got error when tested with Huawei Honor 7
BUILD = BOARD=PLK-L01
BOOTLOADER=unknown
BRAND=HONOR
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=HWPLK

STACK_TRACE = java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.clubkicker-1/base.apk"],nativeLibraryDirectories=[/data/app/com.clubkicker-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:378)
	at java.lang.System.loadLibrary(System.java:998)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:98)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:106)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:147)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:143)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:135)

Thanks a lot for your guidance @bbcallen . I changed minSdkVersion = 9 inside android ijkplayer armv8a-64 bit and then rebuild the from source code. I got aar file. And then import it into my application. I works fine now.

**Comment by DanielXiao123** [comment]
@quangtrung89 你是怎么解决这个问题的，我得到了arr文件后，依赖了这个arr文件，仍然崩溃，
是不是我哪里操作不对啊？ava.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file 
"/data/data/cn.itools.small.reader/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-x86-0.5.1_45975cc25af64f30bfb49421dba2b4ff7b8b0503-classes.dex", dex file "/data/data/cn.itools.small.reader/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-java-0.5.1_8ee26e4e49649fe4912cb73903269a363bad0c65-classes.dex", dex file "/data/data/cn.itools.small.reader/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-armv7a-0.5.1_65538a37b2537bc2b1182a66847ae1fa0bb8cc09-classes.dex", dex file "/data/data/cn.itools.small.reader/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-armv5-0.5.1_8ef07bdd6ee34ca929ac2c9ec601a179c741dcdf-classes.dex", dex file "/data/data/cn.itools.small.reader/files/instant-run/dex/slice-support-annotations-23.3.0_f90064cb936da98caf5b5e70dc6c2b6b05db1922-classes.dex", dex file

**Comment by mrkentlng** [comment]
@quangtrung89 hi bro can i have your email! Im newbie android, i have problem when import this for android studio! Im compile it succesful but cant find ijkplayervideoview! Pls give me your email and i can learn from you! Thanks so much
