### ISSUE TITLE
使用过程中发现的bug

### ISSUE THREAD

**Issue by my519820363** [Bilibili/ijkplayer#635]
1：setVolume只有在setDataSource方法后调用才能生效，且会先按照原始值响一下再变化成设置的值。
2：setDataSource无需调用start方法，就会发出声音，但是不会有画面。
3：内存占用很高，没使用IjkPlayer前内存占用30-40M左右，使用后飙升至70-80M

**Comment by my519820363** [comment]
版本号 0.4.2.4

**Comment by bbcallen** [comment]
1: Bug
2: Can you provide some log? This should not happen before prepareAsync() being called.
3: Does it crash or be out of memory?
