### ISSUE TITLE
有没有自定义MediaController的实例代码参考下？

### ISSUE THREAD

**Issue by cikichen** [Bilibili/ijkplayer#641]
官方sample直接继承了系统的MediaController，想问下有没有完全自定义UI的ijkMediaController参考下，谢谢

**Comment by bbcallen** [comment]
No, I don't know how to customizing system MediaController.
There are too many private API usage inside MediaController.

Mostly, you need to rewrite the whole VideoView, that's why IjkVideoView is not part of ijkplayer API.
