### ISSUE TITLE
缓冲buffer大小

### ISSUE THREAD

**Issue by playererer** [Bilibili/ijkplayer#643]
请问一下下面两个宏有什么不同：

#define MAX_QUEUE_SIZE (15 * 1024 * 1024)
#define MIN_FRAMES 50000

第一个后面的值指的是什么？第二值应该是帧数，如果我想改缓冲buffer大小，应该改哪个值呢？

**Comment by scottguosk** [comment]
同问

**Comment by lyqaiym** [comment]
你们知道了吗？
