### ISSUE TITLE
About play next video

### ISSUE THREAD

**Issue by melody-rain** [Bilibili/ijkplayer#645]
Hi @bbcallen . I have a question about "playing next video" when using hardware codec. 
Once a video is completed we reset the current player and start to play the next video asynchronously. 

Between the time the ACodec is released completely and the time to start the next video, if ACodec is not released but the next video has been played, will it crash since ACodec is not recreated properly?

Thanks.

**Comment by bbcallen** [comment]
Depending on system.
In theory, ijkplayer will catch a java exception when create new MediaCodec instance, and fall back to ffmpeg/avcodec.
But in fact, some system doesn't handle this error properly, and could crashed or hang inside MediaCodec
