### ISSUE TITLE
java.lang.IllegalStateException when app call method _start 

### ISSUE THREAD

**Issue by Zo2m4bie** [Bilibili/ijkplayer#646]
Hi. I received java.lang.IllegalStateException when my app had tried to call method _start inside IjkMediaPlayer. And I see that _start can throw this exception. Can you explain when and whyI can receive this exception?

    Fatal Exception: java.lang.IllegalStateException: mpjni: start: null mp
            at tv.danmaku.ijk.media.player.IjkMediaPlayer._start(IjkMediaPlayer.java)
            at tv.danmaku.ijk.media.player.IjkMediaPlayer.start(IjkMediaPlayer.java:460)

**Comment by bbcallen** [comment]
I think you are the one, who should tell me when this happen and how to reproduce.
Usually, It means that mp has been released.

**Comment by bbcallen** [comment]
I think you are the one, who should tell me when this happen and how to reproduce.
Usually, It means that mp has been released.

**Comment by bbcallen** [comment]
Feel free to reopen if any more questions
