### ISSUE TITLE
不能解析MKV AVI等格式

### ISSUE THREAD

**Issue by yeshibuzhong** [Bilibili/ijkplayer#648]
如题,这个框架不可以解析MKV AVI格式的视频吗?   用的是软解.

**Comment by yeshibuzhong** [comment]
补充一下,我是搞的iOS端.

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/README.md#before-build

**Comment by yeshibuzhong** [comment]
OK 搞定了  多谢

**Comment by 317394245** [comment]
请教一下 mkv格式视频的解析是怎么处理的？遇到同样的问题
