### ISSUE TITLE
How to display videos in portrait orientation?

### ISSUE THREAD

**Issue by simonlinj** [Bilibili/ijkplayer#65]
The video was recorded in portrait orientation, but shows on the wrong orientation.. any ideas where should I start with for orientation correction? Thanks!

PS: tested on android devices

**Comment by almozavr** [comment]
@bbcallen is there a way to determine `rotation angle`? I see it in log but can't figure out how to get it from `IMediaPlayer`

**Comment by bbcallen** [comment]
There is a rotate_tag in ff_ffplay.c, you can expose it to application.

**Comment by pkadetiloye** [comment]
+1 
This library works well but I'm having the issue also with the orientation. Is there a quick fix I can do to make it work ?

Thanks,

**Comment by bbcallen** [comment]
No quick fix, yet.

**Comment by garymabin** [comment]
`3. use TextureView instead of SurfaceView, and call setTransform.setTransform(), (API-14+ only)`

I've tried with TextureView, when applied rotate matrix, the view just stays black either.

**Comment by pkadetiloye** [comment]
@garymabin: I changed SurfaceView to TextureView but now but getHolder() method is not available and shows an error.

See 
...
`getHolder().addCallback(mSHCallback);`

...
`getHolder().setFixedSize(mSurfaceWidth, mSurfaceHeight);`

Any way to resolve this ?

Thanks,

**Comment by garymabin** [comment]
@pkadetiloye  you can refer to this [gist](https://gist.github.com/garymabin/6654faf95f5e45fb88d4), It's a work but not throughly tested demo about replacing SurfaceView with TextureView. You can simply ignore the code around `setVideoLayout()` which is irrelevant.

**Comment by pkadetiloye** [comment]
Thanks, I already replaced it with TextureView but now am trying to setup the  transformation on the video but am not sure am doing right - not working.

Please see my sample code:

    
````
 public void setVideoLayout(int layout) {
        LayoutParams lp = getLayoutParams();
        Pair<Integer, Integer> res  = ScreenResolution.getResolution(mContext);
        int windowWidth = res.first.intValue(), windowHeight = res.second.intValue();
        float windowRatio = windowWidth / (float) windowHeight;
        int sarNum = mVideoSarNum;
        int sarDen = mVideoSarDen;
        if (videoHeight > 0 && videoWidth > 0) {
            float videoRatio = ((float) (videoWidth)) / videoHeight;
            if (sarNum > 0 && sarDen > 0)
                videoRatio = videoRatio * sarNum / sarDen;
            surfaceHeight = videoHeight;
            surfaceWidth = videoWidth;

            if (VIDEO_LAYOUT_ORIGIN == layout && surfaceWidth < windowWidth  && surfaceHeight < windowHeight) {
                lp.width = (int) (surfaceHeight * videoRatio);
                lp.height = surfaceHeight;
            } else if (layout == VIDEO_LAYOUT_ZOOM) {
                lp.width = windowRatio > videoRatio ? windowWidth : (int) (videoRatio * windowHeight);
                lp.height = windowRatio < videoRatio ? windowHeight : (int) (windowWidth / videoRatio);
            } else {
                boolean full = layout == VIDEO_LAYOUT_STRETCH;
                lp.width = (full || windowRatio < videoRatio) ? windowWidth  : (int) (videoRatio * windowHeight);
                lp.height = (full || windowRatio > videoRatio) ? windowHeight : (int) (windowWidth / videoRatio);
            }

//calculate transform matrix here

            float scaleX = 1.0f;
            float scaleY = 1.0f;

            float viewWidth = lp.width;
            float viewHeight = lp.height;
            if (videoWidth > viewWidth && videoHeight > viewHeight) {
                scaleX = videoWidth / viewWidth;
                scaleY = videoHeight / viewHeight;
            } else if (videoWidth < viewWidth && videoHeight < viewHeight) {
                scaleY = viewWidth / videoWidth;
                scaleX = viewHeight / videoHeight;
            } else if (viewWidth > videoWidth) {
                scaleY = (viewWidth / videoWidth) / (videoHeight / videoHeight);
            } else if (viewHeight > videoHeight) {
                scaleX = (viewHeight / videoHeight) / (viewWidth / videoWidth);
            }

            // Calculate pivot points, in our case crop from center
            int pivotPointX = (int)viewWidth / 2;
            int pivotPointY = (int)viewHeight / 2;

//apply transformation
            Matrix matrix = new Matrix();
            matrix.setScale(scaleX, scaleY, pivotPointX, pivotPointY);
            setTransform(matrix);

            setLayoutParams(lp);
            //getHolder().setFixedSize(surfaceWidth, surfaceHeight);
            DebugLog.dfmt(
                    TAG,
                    "VIDEO: %dx%dx%f[SAR:%d:%d], Surface: %dx%d, LP: %dx%d, Window: %dx%dx%f",
                    videoWidth, videoHeight, videoRatio, mVideoSarNum,
                    mVideoSarDen, surfaceWidth, surfaceHeight, lp.width,
                    lp.height, windowWidth, windowHeight, windowRatio);
        }
        mVideoLayout = layout;
    }
````

**Comment by garymabin** [comment]
@pkadetiloye TextureView works more like a View, the video shows correct even without the scale matrix.While as I answered above, when I tried to apply a rotate matrix, the video just turned black.

**Comment by pkadetiloye** [comment]
@garymabin I got rotation working, no black screen but my seekbar is not showing any more. I'm not sure why ?

I created a gist if you would like to check it out.

https://gist.github.com/pkadetiloye/6d8d2a668795c6c567cf

Thanks,

**Comment by pkadetiloye** [comment]
How can I get the seekbar to show on the TextureView ?

Seekbar doesn't show up when I `VideoView extends TextureView`

**Comment by garymabin** [comment]
@pkadetiloye Please check your code carefully, `currentState` and `targetState ` is useless and never changed, just remove them and use the origin `mCurrentState` and `mTargetState`

**Comment by pkadetiloye** [comment]
@garymabin It works fine now. Thank you!

:100:

**Comment by pkadetiloye** [comment]
I just pulled the latest code and it's much better now...but there is still an issue with the video orientation with TextureView. I recorded my video using the camera and try to view it but the portrait video captured is display in landscape and vice-versa. 

Any ideas why ?

Thanks,

**Comment by garymabin** [comment]
1.Is the video you recorded looks right with other videoplayers?
2.Have you configure the Camera's preview parameter about rotate before
recording(It should be configured to rotate 90 degree)?

2015-09-01 10:20 GMT+08:00 Philip K. Adetiloye <notifications@github.com>:

**Comment by pkadetiloye** [comment]
@garymabin it looks right when I play it using other player and on iOS but on the 
video player, the orientation is landscape.

I'm using the android intent to record my video.
```
Intent intent = new Intent(MediaStore.ACTION_VIDEO_CAPTURE);
		String MyVideoFilePath = "/sdcard/test/teest.mp4";
		File imageFile = new File(MyVideoFilePath);
		Uri imageFileUri = Uri.fromFile(imageFile);
		intent.putExtra(MediaStore.EXTRA_OUTPUT, imageFileUri);
		intent.putExtra(MediaStore.EXTRA_SCREEN_ORIENTATION, ActivityInfo.SCREEN_ORIENTATION_REVERSE_PORTRAIT);
		intent.putExtra("return-data", true);
		intent.putExtra(MediaStore.EXTRA_SIZE_LIMIT, 50 * 1048576L);
		startActivityForResult(intent, DataConstants.MIME_TYPE_VIDEO_CAPTURE);
```

**Comment by pkadetiloye** [comment]
I tried using ExifInterface to get the orientation but it always return 1
```
int rotate = 0;
		try {
			File imageFile = new File(sourcepath);
			ExifInterface exif = new ExifInterface(imageFile.getAbsolutePath());
			int orientation = exif.getAttributeInt(ExifInterface.TAG_ORIENTATION, -1);

			switch (orientation) {
				case ExifInterface.ORIENTATION_ROTATE_270:
					rotate = 270;
					break;
				case ExifInterface.ORIENTATION_ROTATE_180:
					rotate = 180;
					break;
				case ExifInterface.ORIENTATION_ROTATE_90:
					rotate = 90;
					break;
				default:
					// Do Nothing
					break;
                        }
		} catch (Exception e) {
			e.printStackTrace();
		}
```

Is there a way for the `VideoView` to detect the orientation and adjust it ?

**Comment by pkadetiloye** [comment]
I just recorded a video using the native camera and try to preview it with the player, still same issue with
the orientation.
It's probably the VideoView not displaying the orientation correctly.

**Comment by bbcallen** [comment]
partial supported: ed814911b41f0d65ae022b08e403b3a60cda7695

**Comment by MROU** [comment]
**method one：**
  <RelativeLayout
                android:id="@+id/video_layout"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                >
                <com.ruike.weijuxing.widget.media.IjkVideoView
                    android:id="@+id/video_view"
                    android:layout_width="match_parent"
                    android:layout_height="400dp"
                    android:layout_gravity="center">
                </com.ruike.weijuxing.widget.media.IjkVideoView>
            </RelativeLayout>

**method two：**
 RelativeLayout.LayoutParams lp=new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
      lp.width = screenWidth;
      lp.height =screenWidth;
     mVideoView.setLayoutParams(lp);

**Comment by harshal2711** [comment]
I read above solutions . Still didn't find a solution. I applied a surfaceview to player by **player.setDisplay(videoHolder);** .I didn't declare videoview anywhere. How can i perform rotation ?
TextureView is supported from api 14+ and causes issue of **black screen** and **control visiblilty** issue. I declare **android:screenOrientation="portrait"**  also and my video is playing proper in other 3rd party players with correct orientation. So it also made with proper **metadata**. Is there any proper solution ?

**Comment by AGuminskyi** [comment]
In the IJK Player u have the `IMediaPlayer.OnInfoListener`

Implement it and listen MEDIA_INFO_VIDEO_ROTATION_CHANGED

` override fun onInfo(mediaPlayer: IMediaPlayer, type: Int, value: Int): Boolean {
        when (type) {
            IMediaPlayer.MEDIA_INFO_VIDEO_ROTATION_CHANGED -> {
//                 (surfaceHolder as BonkSurfaceHolder).rotationDegree = value
                surfaceHolder.onVideoRotationChanged(value)
            }
        }
        return true
    }`
