### ISSUE TITLE
[iOS / Android] Pipefile playback.

### ISSUE THREAD

**Issue by a4tech** [Bilibili/ijkplayer#651]
Hello,

Can We try to add playback of mpeg2TS from PipeFile ?

I retrive data to a pipFile, ( test.ts ), I put NSURL to that file, but player can not make a playback for that.

**Comment by bbcallen** [comment]
Any log?
What do you mean with "PipeFile"?

**Comment by a4tech** [comment]
In iOS Player you can not play:

https://www.dropbox.com/s/g0b603knd8ro86b/tstTS3_fixed.ts?dl=0
https://www.dropbox.com/s/6x74wgpq2vsbnq4/tstTS3.ts?dl=0

This is TS from Sattelite which I save to file and try play by Your player on iOS. It does not detect codecs.

It is mpegts format.

Pipefile. I am making some kind of buffer - 32 MB where I am retriving data for the player which reads a pipefile and play the stream.

I get it by RTP 10022 port to a file and then read it by player.



I put the file inside the app document cache directory, the stream is slowmotion.... it does not play well

===== custom modules begin =====

register protocol: async

register protocol: ijkhttphook

register protocol: ijkinject

register protocol: ijklongurl

register protocol: ijksegment

register protocol: ijktcphook

register demuxer : ijklivehook

===== custom modules end =====

av_version_info: ff2.8--ijk0.4.1.1--dev0.3.3--rc4

ijkmp_set_inject_opaque(0x14c6bf2c0)

ijkmp_set_inject_opaque()=void

2015-11-16 08:54:11.662 IJKMediaDemo[5218:2724274] OK setup GL

ijkmp_ios_set_view(glView=0x14c6b8e40)

ijkmp_ios_set_view(glView=0x14c6b8e40)=void

ijkmp_set_data_source(url="/var/mobile/Containers/Bundle/Application/F635937A-11FD-4295-B0AB-54B9A1283872/IJKMediaDemo.app/test_TS.ts")

ijkmp_set_data_source(url="/var/mobile/Containers/Bundle/Application/F635937A-11FD-4295-B0AB-54B9A1283872/IJKMediaDemo.app/test_TS.ts")=0

ijkmp_prepare_async()

===== versions =====

FFmpeg       : ff2.8--ijk0.4.1.1--dev0.3.3--rc4

libavutil    : 54.31.100

libavcodec   : 56.60.100

libavformat  : 56.40.101

libswscale   : 3.1.101

libswresample: 1.2.101

===== options =====

player-opts : video-pictq-size             = 3

player-opts : overlay-format               = fcc-i420

player-opts : max-fps                      = 30

player-opts : framedrop                    = 0

player-opts : videotoolbox-max-frame-width = 960

player-opts : videotoolbox                 = 0

player-opts : start-on-prepared            = 1

format-opts : ijkinject-opaque             = 5577110208

format-opts : user-agent                   = ijkplayer

format-opts : auto_convert                 = 0

format-opts : timeout                      = 30000000

format-opts : reconnect                    = 1

format-opts : safe                         = 0

codec-opts  : skip_frame                   = 8

codec-opts  : skip_loop_filter             = 48

===================

ijkmp_prepare_async()=0

Format mpegts probed with size=2048 and score=100

Option ijkinject-opaque not found.

Before avformat_find_stream_info() pos: 0 bytes read:5046272 seeks:1

stream=0 stream_type=0 pid=c9 prog_reg_desc=

probing stream 0 pp:2500

Probe with size=16296, packets=1 detected ico with score=25

stream=1 stream_type=0 pid=ca prog_reg_desc=

probing stream 0 pp:2499

Probe with size=27840, packets=2 detected ico with score=25

probing stream 0 pp:2498

Probe with size=38128, packets=3 detected ico with score=25

probing stream 0 pp:2497

probing stream 1 pp:2500

Probe with size=2304, packets=1 detected mp3 with score=25

probed stream 1

probing stream 0 pp:2496

Probe with size=68888, packets=5 detected ico with score=25

probing stream 0 pp:2495

probing stream 0 pp:2494

Probe with size=131712, packets=7 detected ico with score=25

probing stream 0 pp:2493

probing stream 0 pp:2492

probing stream 0 pp:2491

probing stream 0 pp:2490

probing stream 0 pp:2489

probing stream 0 pp:2488

Probe with size=284016, packets=13 detected mpegvideo with score=51

probed stream 0

Invalid frame dimensions 0x0.

Invalid frame dimensions 0x0.

Invalid frame dimensions 0x0.

Invalid frame dimensions 0x0.

Invalid frame dimensions 0x0.

Invalid frame dimensions 0x0.

Invalid frame dimensions 0x0.

Invalid frame dimensions 0x0.

Invalid frame dimensions 0x0.

Invalid frame dimensions 0x0.

Invalid frame dimensions 0x0.

Continuity check failed for pid 201 expected 7 got 14

max_analyze_duration 5000000 reached at 5016000 microseconds st:1

PES packet size mismatch

After avformat_find_stream_info() pos: 0 bytes read:8573072 seeks:3 frames:339

max_frame_duration: 10.000

Input #0, mpegts, from '/var/mobile/Containers/Bundle/Application/F635937A-11FD-4295-B0AB-54B9A1283872/IJKMediaDemo.app/test_TS.ts':

  Duration: 00:00:36.30, start: 16715.335133, bitrate: 4165 kb/s

    Stream #0:0[0xc9], 128, 1/90000: Video: mpeg2video, 1 reference frame, yuv420p(tv, left), 720x576 [SAR 64:45 DAR 16:9], 1/50, max. 8000 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc

    Stream #0:1[0xca], 211, 1/90000: Audio: mp2, 48000 Hz, stereo, s16p, 192 kb/s

detected 2 logical cores

Setting 'sample_rate' to value '48000'

Setting 'sample_fmt' to value 's16p'

Setting 'channels' to value '2'

Setting 'time_base' to value '1/48000'

Setting 'channel_layout' to value '0x3'

tb:1/48000 samplefmt:s16p samplerate:48000 chlayout:0x3

auto-inserting filter 'auto-inserted resampler 0' between the filter 'ffplay_abuffer' and the filter 'ffplay_abuffersink'

query_formats: 2 queried, 0 merged, 3 already done, 0 delayed

Using s16p internally between filters

ch:2 chl:stereo fmt:s16p r:48000Hz -> ch:2 chl:stereo fmt:s16 r:48000Hz

aout_open_audio()

AudioCodec: avcodec, mp2

aout_pause_audio(0)

vtb fail!!! switch to ffmpeg decode!!!! 

VideoCodec: avcodec, mpeg2video

fps: 25.000000 (normal)

2015-11-16 08:54:11.870 IJKMediaDemo[5218:2724274] FFP_MSG_VIDEO_DECODER_OPEN: false

fps: 25.000000 (normal)

2015-11-16 08:54:11.871 IJKMediaDemo[5218:2724274] FFP_MSG_VIDEO_SIZE_CHANGED: 720, 576

2015-11-16 08:54:11.871 IJKMediaDemo[5218:2724274] FFP_MSG_SAR_CHANGED: 64, 45

ijkmp_get_msg: FFP_MSG_PREPARED

2015-11-16 08:54:11.871 IJKMediaDemo[5218:2724274] FFP_MSG_PREPARED:

ijkmp_get_meta_l

ijkmp_get_meta_l()=void

2015-11-16 08:54:11.871 IJKMediaDemo[5218:2724274] fps in meta 25.000000

2015-11-16 08:54:11.871 IJKMediaDemo[5218:2724274] mediaIsPreparedToPlayDidChange

2015-11-16 08:54:11.871 IJKMediaDemo[5218:2724274] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

2015-11-16 08:54:11.872 IJKMediaDemo[5218:2724274] moviePlayBackStateDidChange 1: playing

Audio frame changed from rate:48000 ch:2 fmt:s16p layout:stereo serial:-1 to rate:48000 ch:2 fmt:s16p layout:stereo serial:1

Setting 'sample_rate' to value '48000'

Setting 'sample_fmt' to value 's16p'

Setting 'channels' to value '2'

Setting 'time_base' to value '1/48000'

Setting 'channel_layout' to value '0x3'

tb:1/48000 samplefmt:s16p samplerate:48000 chlayout:0x3

auto-inserting filter 'auto-inserted resampler 0' between the filter 'ffplay_abuffer' and the filter 'ffplay_abuffersink'

query_formats: 2 queried, 0 merged, 3 already done, 0 delayed

Using s16p internally between filters

ch:2 chl:stereo fmt:s16p r:48000Hz -> ch:2 chl:stereo fmt:s16 r:48000Hz

Continuity check failed for pid 201 expected 7 got 14

Video frame changed from size:0x0 format:none serial:-1 to size:720x576 format:yuv420p serial:1

Setting 'video_size' to value '720x576'

Setting 'pix_fmt' to value '0'

Setting 'time_base' to value '1/90000'

Setting 'pixel_aspect' to value '64/45'

Setting 'frame_rate' to value '25/1'

w:720 h:576 pixfmt:yuv420p tb:1/90000 fr:25/1 sar:64/45 sws_param:

Setting 'out_w' to value 'floor(in_w/2)*2'

Setting 'out_h' to value 'floor(in_h/2)*2'

query_formats: 3 queried, 2 merged, 0 already done, 0 delayed

w:720 h:576 sar:64/45 -> w:720 h:576 sar:64/45

SDL_VoutFFmpeg_CreateOverlay(w=720, h=576, fmt=I420(0x30323449, dp=0x14c66f860)

Video: first frame decoded

2015-11-16 08:54:11.883 IJKMediaDemo[5218:2724274] FFP_MSG_VIDEO_SIZE_CHANGED: 720, 576

SDL_VoutFFmpeg_CreateOverlay(w=720, h=576, fmt=I420(0x30323449, dp=0x14c66f860)

2015-11-16 08:54:11.885 IJKMediaDemo[5218:2724274] FFP_MSG_VIDEO_SIZE_CHANGED: 720, 576

SDL_VoutFFmpeg_CreateOverlay(w=720, h=576, fmt=I420(0x30323449, dp=0x14c66f860)

2015-11-16 08:54:11.887 IJKMediaDemo[5218:2724274] FFP_MSG_VIDEO_SIZE_CHANGED: 720, 576

2015-11-16 08:54:11.892 IJKMediaDemo[5218:2724477] OK use I420 GL renderer

Continuity check failed for pid 201 expected 1 got 8

2015-11-16 08:54:11.900 IJKMediaDemo[5218:2724477] OK setup GL programm

2015-11-16 08:54:11.902 IJKMediaDemo[5218:2724477] OK setup GL framebuffer 1334:750

Continuity check failed for pid 201 expected 4 got 11

2015-11-16 08:54:11.906 IJKMediaDemo[5218:2724274] FFP_MSG_VIDEO_RENDERING_START:

Continuity check failed for pid 201 expected 10 got 1

Continuity check failed for pid 201 expected 12 got 2

Continuity check failed for pid 202 expected 8 got 9

PES packet size mismatch

Continuity check failed for pid 201 expected 14 got 5

Continuity check failed for pid 201 expected 14 got 5

avcodec/Audio: first frame decoded

2015-11-16 08:54:11.932 IJKMediaDemo[5218:2724274] FFP_MSG_AUDIO_RENDERING_START:

Continuity check failed for pid 201 expected 12 got 2

Continuity check failed for pid 202 expected 8 got 9

PES packet size mismatch

Continuity check failed for pid 201 expected 3 got 9

Continuity check failed for pid 202 expected 1 got 2

PES packet size mismatch

PES packet size mismatch

**Comment by bbcallen** [comment]
How do you confirm that player doesn't read beyond the end of file?

**Comment by a4tech** [comment]
I think in this case time is not important on TransportStream which is used to be live.
Files i have uploaded in the upper conversation, I did put link to files.

If You try to play them you can see that FPS is not good on them -> They are not playing smooth, there are hangs.

How can I help you more about ?

**Comment by bbcallen** [comment]
No idea. I'm not familiar with mpeg2video and mp2.
Try set
```
    [options setCodecOptionIntValue:IJK_AVDISCARD_DEFAULT    forKey:@"skip_loop_filter"];
    [options setCodecOptionIntValue:IJK_AVDISCARD_DEFAULT    forKey:@"skip_frame"];
```

**Comment by a4tech** [comment]
It helps and works with those TS files.

I am going to investigate now reading from RTMP and will try make some pull requests if I will fix anything.

Thanks
