### ISSUE TITLE
每次设置playback rate后，currentPlaybackTime都会重0开始，进度条回到起始位置

### ISSUE THREAD

**Issue by playervideo** [Bilibili/ijkplayer#652]
如题，在播放过程中设置playback rate，currentPlaybackTime都会重0开始，进度条回到起始位置！

**Comment by bbcallen** [comment]
It's an experimental feature, and I don't have plan to fix it recently.

**Comment by playervideo** [comment]
在播放过程中设置playback rate还会导致音视频不同步，@bbcallen 可不可以给些思路？
