### ISSUE TITLE
how to enable iOS video toolbox

### ISSUE THREAD

**Issue by tbago** [Bilibili/ijkplayer#654]
I want to enable videotoolbox for iOS version. I use the following code.

    IJKFFOptions *options = [IJKFFOptions optionsByDefault];
    [options setPlayerOptionIntValue:1 forKey:@"videotoolbox"];
    
    self.player = [[IJKFFMoviePlayerController alloc] initWithContentURL:self.url withOptions:options]; 

I use rtsp as input resource. The player work well when not set 'videotoolbox' option.

but when I enable videotoolbox,the console output as following:
===== custom modules begin =====
register protocol: async
register protocol: ijkhttphook
register protocol: ijkinject
register protocol: ijklongurl
register protocol: ijksegment
register protocol: ijktcphook
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff2.8--ijk0.4.1.1--dev0.3.3--rc4
ijkmp_set_inject_opaque(0x149011340)
ijkmp_set_inject_opaque()=void
2015-11-17 10:32:39.978 IJKMediaDemo[7340:3216048] OK setup GL
ijkmp_ios_set_view(glView=0x147db3930)
ijkmp_ios_set_view(glView=0x147db3930)=void
ijkmp_set_data_source(url="rtsp://192.168.73.254:8557/PSIA/Streaming/channels/2?videoCodecType=H.264")
ijkmp_set_data_source(url="rtsp://192.168.73.254:8557/PSIA/Streaming/channels/2?videoCodecType=H.264")=0
ijkmp_prepare_async()
remove 'timeout' option for rtmp.
===== versions =====
FFmpeg       : ff2.8--ijk0.4.1.1--dev0.3.3--rc4
libavutil    : 54.31.100
libavcodec   : 56.60.100
libavformat  : 56.40.101
libswscale   : 3.1.101
libswresample: 1.2.101
===== options =====
player-opts : video-pictq-size             = 3
player-opts : overlay-format               = fcc-i420
player-opts : max-fps                      = 30
player-opts : framedrop                    = 0
player-opts : videotoolbox-max-frame-width = 960
player-opts : videotoolbox                 = 1
player-opts : start-on-prepared            = 1
format-opts : ijkinject-opaque             = 5519774528
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : safe                         = 0
format-opts : reconnect                    = 1
codec-opts  : skip_frame                   = 8
codec-opts  : skip_loop_filter             = 48
===================
ijkmp_prepare_async()=0
remove 'timeout' option for rtmp.
SDP:
v=0

o=- 44385462 1 IN IP4 192.168.54.10

s=RTSP/RTP stream from IPNC

i=PSIA/Streaming/channels/2?videoCodecType=H.264

t=0 0

a=tool:LIVE555 Streaming Media v2012.10.24

a=type:broadcast

a=control:*

a=range:npt=0-

a=x-qt-text-nam:RTSP/RTP stream from IPNC

a=x-qt-text-inf:PSIA/Streaming/channels/2?videoCodecType=H.264

m=video 0 RTP/AVP 96

c=IN IP4 0.0.0.0

b=AS:12000

a=rtpmap:96 H264/90000

a=fmtp:96 packetization-mode=1;profile-level-id=640029;sprop-parameter-sets=Z2QAKa2EBUViuKxUdCAqKxXFYqOhAVFYrisVHQgKisVxWKjoQFRWK4rFR0ICorFcVio6ECSFITk8nyfk/k/J8nm5s00IEkKQnJ5Pk/J/J+T5PNzZprQFoe0qQAAAHgAABwgYEABVcAAYCC974XhEI1AAAAAB,aO48sA==

a=control:track1

Failed to parse interval end specification ''
video codec set to: h264
RTP Packetization Mode: 1
RTP Profile IDC: 64 Profile IOP: 0 Level: 29
Extradata set to 0x147f619a0 (size: 129)
end receive buffer size reported is 65536
end receive buffer size reported is 65536
hello state=0
Failed to parse interval end specification ''
Option ijkinject-opaque not found.
unknown SEI type 128
unknown SEI type 24
unknown SEI type 128
SEI type 24 size 64 truncated at 51
bytestream overread -4
bytestream overread -8
error while decoding MB 30 29, bytestream -8
concealing 64 DC, 64 AC, 64 MV errors in I frame
All info found
rfps: 29.250000 0.019494
rfps: 29.333333 0.015283
rfps: 29.416667 0.011585
rfps: 29.416667 0.011585
rfps: 29.500000 0.008402
rfps: 29.500000 0.008402
rfps: 29.583333 0.005732
rfps: 29.583333 0.005732
rfps: 29.666667 0.003577
rfps: 29.666667 0.003577
rfps: 29.750000 0.001935
rfps: 29.750000 0.001935
rfps: 29.833333 0.000808
rfps: 29.833333 0.000808
rfps: 29.916667 0.000194
rfps: 29.916667 0.000194
rfps: 30.000000 0.000095
rfps: 60.000000 0.000379
rfps: 120.000000 0.001516
rfps: 240.000000 0.006064
rfps: 29.970030 0.000071
rfps: 59.940060 0.000285
max_frame_duration: 10.000
Input #0, rtsp, from 'rtsp://192.168.73.254:8557/PSIA/Streaming/channels/2?videoCodecType=H.264':
  Metadata:
    title           : RTSP/RTP stream from IPNC
    comment         : PSIA/Streaming/channels/2?videoCodecType=H.264
  Duration: N/A, start: 0.200667, bitrate: N/A
    Stream #0:0, 28, 1/90000: Video: h264, 1 reference frame, yuvj420p(pc, left), 720x480, 1/60, 30 fps, 29.97 tbr, 90k tbn, 60 tbc
detected 2 logical cores
after scale width 720 height 480 
m_max_ref_frames 5 
fps: 30.000000 (normal)
fps: 29.970030 (normal)
ijkmp_get_msg: FFP_MSG_PREPARED
2015-11-17 10:32:40.225 IJKMediaDemo[7340:3216048] FFP_MSG_VIDEO_DECODER_OPEN: true
flushed last keyframe pts 0 
2015-11-17 10:32:40.225 IJKMediaDemo[7340:3216048] FFP_MSG_VIDEO_SIZE_CHANGED: 720, 480
2015-11-17 10:32:40.225 IJKMediaDemo[7340:3216048] FFP_MSG_SAR_CHANGED: 0, 1
2015-11-17 10:32:40.225 IJKMediaDemo[7340:3216048] FFP_MSG_PREPARED:
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
2015-11-17 10:32:40.225 IJKMediaDemo[7340:3216048] fps in meta 30.000000
2015-11-17 10:32:40.225 IJKMediaDemo[7340:3216048] mediaIsPreparedToPlayDidChange
2015-11-17 10:32:40.226 IJKMediaDemo[7340:3216048] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3
2015-11-17 10:32:40.226 IJKMediaDemo[7340:3216048] moviePlayBackStateDidChange 1: playing
after scale width 720 height 480 
decode callback -12909 kVTVideoDecoderBadDataErr
decode callback -12909 kVTVideoDecoderBadDataErr
decodeFrame -12911 kVTVideoDecoderMalfunctionErr
ffp_toggle_buffering_l: start
aout_pause_audio(1)
2015-11-17 10:32:40.251 IJKMediaDemo[7340:3216048] FFP_MSG_BUFFERING_START:
2015-11-17 10:32:40.251 IJKMediaDemo[7340:3216048] loadStateDidChange: MPMovieLoadStateStalled: 4

**Comment by tbago** [comment]
I use iPhone 6 plus with iOS version 9.1 for test.

**Comment by linjiansheng** [comment]
+1

**Comment by bbcallen** [comment]
Not familiar with rtsp.

**Comment by brulesLi** [comment]
哥子 你的能播放 rtp流吗

**Comment by brulesLi** [comment]
加我个 QQ1580651395  交流 一下

**Comment by Jaynn** [comment]
you can try [options setOptionIntValue:... forKey:@"..." ofCategory:...];
