### ISSUE TITLE
IOS9.0以及之后的版本是不是不能跑啊

### ISSUE THREAD

**Issue by huakucha** [Bilibili/ijkplayer#656]
IOS9.0以及之后的版本是不是不能跑啊 整个过程下来出现了IJKMediaFramework.framework不能用的情况

**Comment by huakucha** [comment]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_IJKFFOptions", referenced from:
      objc-class-ref in IJKMoviePlayerViewController.o
  "_OBJC_CLASS_$_IJKFFMoviePlayerController", referenced from:
      objc-class-ref in IJKMoviePlayerViewController.o
  "_IJKMoviePlayerLoadStateDidChangeNotification", referenced from:
      -[IJKVideoViewController installMovieNotificationObservers] in IJKMoviePlayerViewController.o
      -[IJKVideoViewController removeMovieNotificationObservers] in IJKMoviePlayerViewController.o
  "_IJKMoviePlayerPlaybackStateDidChangeNotification", referenced from:
      -[IJKVideoViewController installMovieNotificationObservers] in IJKMoviePlayerViewController.o
      -[IJKVideoViewController removeMovieNotificationObservers] in IJKMoviePlayerViewController.o
  "_IJKMoviePlayerPlaybackDidFinishNotification", referenced from:
      -[IJKVideoViewController installMovieNotificationObservers] in IJKMoviePlayerViewController.o
      -[IJKVideoViewController removeMovieNotificationObservers] in IJKMoviePlayerViewController.o
  "_IJKMediaPlaybackIsPreparedToPlayDidChangeNotification", referenced from:
      -[IJKVideoViewController installMovieNotificationObservers] in IJKMoviePlayerViewController.o
      -[IJKVideoViewController removeMovieNotificationObservers] in IJKMoviePlayerViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bbcallen** [comment]
Can't reproduce, please provide more information.

**Comment by huakucha** [comment]
sorry about that..as you can see the errors show up when i finish the steps of init ios.sh,now i don't kown how to figure it out，could you please send me a project has been compiled ,Thank you...

**Comment by bbcallen** [comment]
Did you run "compile-ffmpeg.sh all"?
Did you enable BITCODE if you are using Xcode 7.x ?

**Comment by huakucha** [comment]
i just want that demo ,because i don't know IJKMediaFramework.framework is good or not.YES BITCODE is enable...but the errors are same -_-!!!

**Comment by huakucha** [comment]
i did everything according to 'Build iOS'

**Comment by shingwasix** [comment]
You could execute the following command in Terminal to see if your IJKMediaFramework.framework support arm64.
`lipo -info {PATH_TO_YOUR_PROJECT}/IJKMediaFramework.framework/IJKMediaFramework`
