### ISSUE TITLE
IOS9.0以及之后的版本是不是不能跑啊

### ISSUE THREAD

**Issue by huakucha** [Bilibili/ijkplayer#657]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_IJKFFOptions", referenced from:
      objc-class-ref in IJKMoviePlayerViewController.o
  "_OBJC_CLASS_$_IJKFFMoviePlayerController", referenced from:
      objc-class-ref in IJKMoviePlayerViewController.o
  "_IJKMoviePlayerLoadStateDidChangeNotification", referenced from:
      -[IJKVideoViewController installMovieNotificationObservers] in IJKMoviePlayerViewController.o
      -[IJKVideoViewController removeMovieNotificationObservers] in IJKMoviePlayerViewController.o
  "_IJKMoviePlayerPlaybackStateDidChangeNotification", referenced from:
      -[IJKVideoViewController installMovieNotificationObservers] in IJKMoviePlayerViewController.o
      -[IJKVideoViewController removeMovieNotificationObservers] in IJKMoviePlayerViewController.o
  "_IJKMoviePlayerPlaybackDidFinishNotification", referenced from:
      -[IJKVideoViewController installMovieNotificationObservers] in IJKMoviePlayerViewController.o
      -[IJKVideoViewController removeMovieNotificationObservers] in IJKMoviePlayerViewController.o
  "_IJKMediaPlaybackIsPreparedToPlayDidChangeNotification", referenced from:
      -[IJKVideoViewController installMovieNotificationObservers] in IJKMoviePlayerViewController.o
      -[IJKVideoViewController removeMovieNotificationObservers] in IJKMoviePlayerViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bbcallen** [comment]
duplicated with #656
