### ISSUE TITLE
ijkmp_inc_ref和ijkmp_dec_ref_p内存泄露问题

### ISSUE THREAD

**Issue by wqmijkplayer** [Bilibili/ijkplayer#665]
@bbcallen @qazmoon
你们好！
请教一个问题
当只播放一个视频完毕，ijkmp_inc_ref和ijkmp_dec_ref_p对mp的引用计数并不匹配，播放视频完毕时，调用ijkmp_dec_ref_p时，mp的引用计数ref_count仍为2，导致mp不会被释放
从源代码可以看出，
ijkmp_create，jni_get_media_player，jni_set_media_player，ijkmp_prepare_async_l中mp的引用计数都会加1
jni_set_media_player，IjkMediaPlayer_release，IjkMediaPlayer_reset以及在调用fail时，mp引用计数计数减1
如何保证mp的引用计数在播放完毕为0呢？
感谢！

**Comment by bbcallen** [comment]
jni_set_media_player() call ijkmp_dec_ref_p(), too

**Comment by wqmijkplayer** [comment]
yes, jni_set_media_player() will call ijkmp_dec_ref_p()
but I don't know why jni_get_media_player and ijkmp_prepare_async_l function still call ijkmp_inc_ref()?

**Comment by bbcallen** [comment]
ijkmp_prepare_async_l() call ijkmp_inc_ref() for msg_loop()

**Comment by wqmijkplayer** [comment]
Thanks, this is my fault in my source code
