### ISSUE TITLE
java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in ".../libijksdl.so"

### ISSUE THREAD

**Issue by shenvsv** [Bilibili/ijkplayer#669]
java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in ".../libijksdl.so"
get this error on sdk version 22 while run pretty good on sdk version 23.

**Comment by bbcallen** [comment]
Plz provide more information.

**Comment by bo-bda** [comment]
I add flags to compile ffmpeg with mpeg codec. Then susseccfully complile x86 and armv7a lib, also then copy libs to jniLibs folder with there architecture and then i have the same error from load.library. 
The OSX El Capitan 10.11.1
NDK 10e

**Comment by bo-bda** [comment]
Also if you add projects ijkplayer-armv7a, ijkplayer-exo, ijkplayer-java, ijkplayer-x86 - all works with new codes, but when i add only *.so it can not load the library.

**Comment by bbcallen** [comment]
I don't think I can locate the problem with such limited information.

**Comment by bo-bda** [comment]
also why you need to include all project like x86 and armv7a if you need only the so files which you load in loadlibrary? as i understand you can get so which to the jniLibs/ (x86/armv7a) and paste there the file.

What kinf of inforamtion do you need?

**Comment by bbcallen** [comment]
1. What's the advantage in your way, and what's the disadvantage in current way?
2. I don't know. Mostly, when you find the information I need, you are almost near the solution.

**Comment by bo-bda** [comment]
What's the advantage in your way, and what's the disadvantage in current way?
1) You do not need to add all projects for the settings and build.gradle. You will have only the folders with libs incide your java ijkplaer project.

2) I don't know. Mostly, when you find the information I need, you are almost near the solution.
is there are any dependency of project with architecture of some files or only .so files?

**Comment by bbcallen** [comment]
2
No, they contain .so file only
