### ISSUE TITLE
iOS static library removed?

### ISSUE THREAD

**Issue by KCastiglione** [Bilibili/ijkplayer#671]
can you please add it back, why was it removed?

https://github.com/Bilibili/ijkplayer/commit/c00989176861756ea247688f6e4c6da462f83e5a

**Comment by bbcallen** [comment]
You can depend on target "IjkMediaFramework" instead.
#import <IJKMediaFramework/IJKMediaFramework.h>

**Comment by KCastiglione** [comment]
can we leave the static library like before for dependencies

**Comment by bbcallen** [comment]
Why? Does it broke anything?

**Comment by KCastiglione** [comment]
yes we were building static library and adding it to project, now we can't.


libIJKMediaPlayer.a
include/IJKMediaPlayer/
IJKAVMoviePlayerController.h  IJKFFOptions.h                IJKMediaModule.h              IJKMediaPlayer.h
IJKFFMoviePlayerController.h  IJKMPMoviePlayerController.h  IJKMediaPlayback.h

**Comment by bbcallen** [comment]
I think it could be switched to IjkMediaFramework smoothly.

**Comment by KCastiglione** [comment]
with static library , i can just add these files to the project and is very easy to maintain.
will be really great if we can continue maintaining static libraries. thank you very much for a great library.



      libIJKMediaPlayer.a
      include/IJKMediaPlayer/
      IJKAVMoviePlayerController.h IJKFFOptions.h IJKMediaModule.h IJKMediaPlayer.h
      IJKFFMoviePlayerController.h IJKMPMoviePlayerController.h IJKMediaPlayback.h

**Comment by bbcallen** [comment]
With framework, you just need to maintain only one Framework file which contains header file and library file.

And sorry, I can't maintain anything I don't use in my daily work.
