### ISSUE TITLE
Could it originally support to play h264+pcm raw data from memory on android by calling JAVA API without modifying the native ffmpeg code?

### ISSUE THREAD

**Issue by xie6723632** [Bilibili/ijkplayer#672]
If yes,how to use API and how to deal with AV sync?

**Comment by bbcallen** [comment]
Search IMediaDataSource in code.

**Comment by xie6723632** [comment]
I have tried to play a local file with suffix .h264 with ijkMediaPlayer selected,but it will cause the UNKNOWN tips from screen.It seems that it met some error in ffmpeg.
    In my opinion,ffmpeg can play file with .h264 suffix.So is h264 raw data file tested on ijkplayer or I should invoke other API in this case?
   Thanks very much for your help.

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer#before-build
If you prefer more codec/format
```
cd config
rm module.sh
ln -s module-default.sh module.sh
cd android/contrib
# cd ios
sh compile-ffmpeg clean
```

**Comment by zjgooddream** [comment]
how about on iOS , Could it originally support to play h264+ aac data from memory?
