### ISSUE TITLE
delay 4 frames on decoder buffer,how to decrease it ?

### ISSUE THREAD

**Issue by sentervip** [Bilibili/ijkplayer#673]
hi, thanks for your open code of ijkplayer. 
avcodec_decode_video2(pCodecCtx,pFrame,xxx),  pCodecCtx->delay=4, 
delay 4 frames on buffer of decoder ,how to decrease ?
THANKS!

**Comment by bbcallen** [comment]
No idea. Maybe search ffmpeg for codes where it is modified.

**Comment by sentervip** [comment]
Thanks bbcallen.
Who known it ? Please discuss it and  leave message,3Q!

**Comment by bo-bda** [comment]
as i know it is the buffering which Options set by default, if you put no buffering it will be easier.

**Comment by spaul13** [comment]
How many frames will decoder put in his buffer before reseting it?

who is calling the buffer to write in it?
