### ISSUE TITLE
请教如何关闭音频解码？

### ISSUE THREAD

**Issue by wqmijkplayer** [Bilibili/ijkplayer#674]
在一些android设备上，有的音频是Offload音频（解码在dsp中实现），比如aac格式
若再使用ffmpeg解码已是多余
请问如何关闭ffmpeg音频解码，直接将解码前的数据传给audiotrack？
多谢

**Comment by bbcallen** [comment]
No support, yet.

**Comment by wqmijkplayer** [comment]
若我要做件事，难度大吗？
有没有好入手的办法

**Comment by my519820363** [comment]
同求支持关闭音频解码的API

**Comment by wqmijkplayer** [comment]
api肯定没有，得自己做，不知道有没有什么简单处理办法
