### ISSUE TITLE
how to use this repo in iOS  project?

### ISSUE THREAD

**Issue by CheneyZJ** [Bilibili/ijkplayer#677]
Hi,I builded the iOS version as the guide and it ran well with the example provided.But,I am confused at how to integrated this SDK to my project .In the folder of "iOS", there are so many folders related with CPU architecture, do I need to copy all of the them to my project ?Another method I have tried:import IJKMediaFramework.framework and IJKMediaFramework.a in the build setting, however, I got the error ""IJKMediaFramework/IJKMediaFramework.h"file not found" when building the file of IJKMoviePlayerViewController.h. So, can someone give me a hand here?Thank u in advance

**Comment by zyi1992** [comment]
You can search the way to create a universe framework, then you can use the demo to create one for you project.

**Comment by zyi1992** [comment]
http://pan.baidu.com/s/1eQHLWT8  there is the framework i had build, hope this will be help

**Comment by CheneyZJ** [comment]
@zyi1992  I really appreciate ur help.It works very well. May i have a further request? Could u please tell me the way u generate the library for future use as this repo may upgrade?THX.

**Comment by bbcallen** [comment]
The example project is not only an example to show how to use API, but also an example to show how to integrate lib project.

**Comment by CheneyZJ** [comment]
@bbcallen Yes, u did point out the point.I have learnt extra things from using this project.

**Comment by zmsoft** [comment]
@zyi1992 Hi,Can you share the compiled framework again?Many thanks!

**Comment by zyi1992** [comment]
@zmsoft https://pan.baidu.com/s/1qYnmDPi  hope it usefull
