### ISSUE TITLE
最新版本ijkplayer，使用rtsp取流，android硬解码延时长问题

### ISSUE THREAD

**Issue by chenhangfeng** [Bilibili/ijkplayer#678]
ffmpeg库我已经优化，目前ios可以比较快的rtsp播放，但是android延时很大，一般要10s延时，请问除了ffmpeg，哪里还能优化？

**Comment by sayuokdgd** [comment]
ios延时问题怎么解决的啊？求分享。目前我这边使用rtmp流，在ios上延迟在7~8秒左右，请问该怎么优化啊？

**Comment by hou3172568** [comment]
@chenhangfeng 怎么优化？能说一下吗？

**Comment by bbcallen** [comment]
Not familiar with RSTP, but what you've done on iOS, should be OK on Android, too.

**Comment by chenhangfeng** [comment]
I am sorry! Android is not decoded by HW Before.now I select ijkMediaPlayer ,and  decode normal.I decoded the local H264 file,it is fasted!But H264 need low_level,I can't find a low_level H264 rtsp Stream from IPC.

**Comment by GavinYu** [comment]
@chenhangfeng ,请问一下ffmpeg怎么优化？谢谢了！

**Comment by polarbearmaster** [comment]
mark
