### ISSUE TITLE
preference-v7在使用安卓ijk时没找到找个包

### ISSUE THREAD

**Issue by adteven** [Bilibili/ijkplayer#680]
环境是mac10.11.1
用的是最新的sdk和jdk，编译完成之后，提示了好多perence相关的错误，有人遇到不

**Comment by xiaoyaomeng** [comment]
@adteven 这个是android的，你去下载6.0的android sdk

**Comment by bbcallen** [comment]
Use Android Studio, or ask google for preference-v7 in eclipse.

**Comment by fengfutong** [comment]
you shoule download android support repository with sdk manager. preference-v7 is in the support repository.
