### ISSUE TITLE
在ijkplayer-sample中添加rtmp源，播放失败

### ISSUE THREAD

**Issue by zaiyunduan** [Bilibili/ijkplayer#682]
1、在SampleMediaListFragment.java中添加
       mAdapter.addItem("rtmp://ams.studytv.cn/livepkgr/264","RTMP");
2、编译运行，点击该条目后，弹出“unknown”错误对话框。log如下。

谢谢

11-25 13:00:02.920 3438-3438/tv.danmaku.ijk.media.sample I/dalvikvm: Could not find method android.media.MediaDataSource.close, referenced from method tv.danmaku.ijk.media.player.AndroidMediaPlayer.releaseMediaDataSource
11-25 13:00:02.920 3438-3438/tv.danmaku.ijk.media.sample W/dalvikvm: VFY: unable to resolve virtual method 794: Landroid/media/MediaDataSource;.close ()V
11-25 13:00:02.920 3438-3438/tv.danmaku.ijk.media.sample D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
11-25 13:00:02.922 3438-3438/tv.danmaku.ijk.media.sample W/dalvikvm: Unable to resolve superclass of Ltv/danmaku/ijk/media/player/AndroidMediaPlayer$MediaDataSourceProxy; (163)
11-25 13:00:02.922 3438-3438/tv.danmaku.ijk.media.sample W/dalvikvm: Link of class 'Ltv/danmaku/ijk/media/player/AndroidMediaPlayer$MediaDataSourceProxy;' failed
11-25 13:00:02.922 3438-3438/tv.danmaku.ijk.media.sample E/dalvikvm: Could not find class 'tv.danmaku.ijk.media.player.AndroidMediaPlayer$MediaDataSourceProxy', referenced from method tv.danmaku.ijk.media.player.AndroidMediaPlayer.setDataSource
11-25 13:00:02.922 3438-3438/tv.danmaku.ijk.media.sample W/dalvikvm: VFY: unable to resolve new-instance 2652 (Ltv/danmaku/ijk/media/player/AndroidMediaPlayer$MediaDataSourceProxy;) in Ltv/danmaku/ijk/media/player/AndroidMediaPlayer;
11-25 13:00:02.922 3438-3438/tv.danmaku.ijk.media.sample D/dalvikvm: VFY: replacing opcode 0x22 at 0x0003
11-25 13:00:02.923 3438-3438/tv.danmaku.ijk.media.sample W/dalvikvm: Unable to resolve superclass of Ltv/danmaku/ijk/media/player/AndroidMediaPlayer$MediaDataSourceProxy; (163)
11-25 13:00:02.923 3438-3438/tv.danmaku.ijk.media.sample W/dalvikvm: Link of class 'Ltv/danmaku/ijk/media/player/AndroidMediaPlayer$MediaDataSourceProxy;' failed
11-25 13:00:02.923 3438-3438/tv.danmaku.ijk.media.sample D/dalvikvm: DexOpt: unable to opt direct call 0x51d5 at 0x05 in Ltv/danmaku/ijk/media/player/AndroidMediaPlayer;.setDataSource
11-25 13:00:02.927 3438-3451/tv.danmaku.ijk.media.sample E/MediaPlayer: error (1, -2147483648)
11-25 13:00:02.953 3438-3438/tv.danmaku.ijk.media.sample D/dalvikvm: GC_FOR_ALLOC freed 202K, 6% free 7530K/7928K, paused 11ms, total 12ms
11-25 13:00:02.995 3438-3438/tv.danmaku.ijk.media.sample E/MediaPlayer: Error (1,-2147483648)
11-25 13:00:02.995 3438-3438/tv.danmaku.ijk.media.sample D/IjkVideoView: Error: 1,-2147483648

**Comment by bbcallen** [comment]
You are using AndroidMediaPlayer, not IjkMediaPlayer.

**Comment by zaiyunduan** [comment]
thanks

**Comment by tiepvv** [comment]
Sorry, i don't understand. I have same quest, please help me example play rmtp://...

Thanks
TiepVV
