### ISSUE TITLE
Open rtmp live stream

### ISSUE THREAD

**Issue by jacky1234** [Bilibili/ijkplayer#683]
I tried to test the function of live stream. Here is the result,it support the protocol of hls,but not support protocol of rtmp.Here is my codes.

1.Put the test url.
 intent.putExtra(Intent.EXTRA_STREAM, Uri.parse("rtmp://7562.lssplay.aodianyun.com/yuepai/stream"));    //测试用
//intent.putExtra(Intent.EXTRA_STREAM,Uri.parse("http://7562.hlsplay.aodianyun.com/yuepai/stream.m3u8"));    //测试用

2.Gain the url of first step
 mVideoUri = intent.getParcelableExtra(Intent.EXTRA_STREAM);

3.test
mVideoView.setVideoURI(mVideoUri);

But it did not work.Why,did I missing something?

**Comment by bbcallen** [comment]
Log, please.
