### ISSUE TITLE
iOS 软解码出来视频画面质量差，怎么调优

### ISSUE THREAD

**Issue by linjiansheng** [Bilibili/ijkplayer#688]
同一个视频文件，用 android 手机 和 iphone 6 播放，都用软解码，对比视频画面，android 手机的画面，比iPhone 6的清晰好多，iPhone 6 的 CPU 占用 在 15% 左右。
请问是不是有参数可以设置？ @bbcallen 谢谢！

**Comment by bbcallen** [comment]
[options setCodecOptionIntValue:IJK_AVDISCARD_DEFAULT    forKey:@"skip_loop_filter"];
    [options setCodecOptionIntValue:IJK_AVDISCARD_DEFAULT    forKey:@"skip_frame"];

**Comment by linjiansheng** [comment]
Good！THX！

**Comment by allentsing** [comment]
@bbcallen 我按照你说的设置了，在iOS上没什么明显的变化啊，效果还是差（软解）

**Comment by DysaniazzZ** [comment]
@bbcallen Is there any difference between `skip_loop_filter` and `skip_frame` ? And should I use both of them on Android platform?
