### ISSUE TITLE
iOS play .ts stream seek error

### ISSUE THREAD

**Issue by zhang625152131** [Bilibili/ijkplayer#690]
When I started playing in the video within 10 seconds to drag the progress bar will appear this problem, but there will be audio, video footage is stuck, but the video playback 10 seconds after the drag the progress bar will not produce this problem.Can you help me?

log:

2015-11-27 14:02:47.350 GGDFPlayerDemo[223:31134] moviePlayBackStateDidChange 4: seeking
ijkmp_seek_to(2086977)
ijkmp_seek_to(2086977)=0
ijkmp_get_msg: FFP_REQ_SEEK
[FFPlayer @ 0x1839b600] stream_seek 2088377000(2086977) + 1400000, 
[FFPlayer @ 0x1839b600] ijkmp_get_msg: FFP_REQ_SEEK: seek to 2086977
[FFPlayer @ 0x1839b600] ffp_toggle_buffering_l: start
aout_pause_audio(1)
2015-11-27 14:02:47.407 GGDFPlayerDemo[223:31134] FFP_MSG_BUFFERING_START:
2015-11-27 14:02:47.407 GGDFPlayerDemo[223:31134] loadStateDidChange: MPMovieLoadStateStalled: 4
[http @ 0x1d498c50] request: GET /gongfuxiongmao2_143626076210507.ts HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=0-

Connection: close

Host: 10.167.20.56

Icy-MetaData: 1

[h264 @ 0x18b4da00] non-existing SPS 0 referenced in buffering period
[http @ 0x1d498c50] request: GET /gongfuxiongmao2_143626076210507.ts HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=1239647184-

Connection: close

Host: 10.167.20.56

Icy-MetaData: 1

[http @ 0x1d498c50] request: GET /gongfuxiongmao2_143626076210507.ts HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=1239645116-

Connection: close

Host: 10.167.20.56

Icy-MetaData: 1

[h264 @ 0x18b4da00] non-existing SPS 0 referenced in buffering period
[h264 @ 0x18b4da00] non-existing SPS 0 referenced in buffering period
[http @ 0x1d498c50] request: GET /gongfuxiongmao2_143626076210507.ts HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=1239645357-

Connection: close

Host: 10.167.20.56

Icy-MetaData: 1

[h264 @ 0x18b4da00] non-existing SPS 0 referenced in buffering period
[http @ 0x1d498c50] request: GET /gongfuxiongmao2_143626076210507.ts HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=1239646432-

Connection: close

Host: 10.167.20.56

Icy-MetaData: 1

[http @ 0x1d498c50] request: GET /gongfuxiongmao2_143626076210507.ts HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=477092300-

Connection: close

Host: 10.167.20.56

Icy-MetaData: 1

[h264 @ 0x18b4da00] non-existing SPS 0 referenced in buffering period
[http @ 0x1d498c50] request: GET /gongfuxiongmao2_143626076210507.ts HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=472030024-

Connection: close

Host: 10.167.20.56

Icy-MetaData: 1

[h264 @ 0x18b4da00] non-existing SPS 0 referenced in buffering period
[http @ 0x1d498c50] request: GET /gongfuxiongmao2_143626076210507.ts HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=472015736-

Connection: close

Host: 10.167.20.56

Icy-MetaData: 1

[h264 @ 0x18b4da00] non-existing SPS 0 referenced in buffering period
[http @ 0x1d498c50] request: GET /gongfuxiongmao2_143626076210507.ts HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=472019791-

Connection: close

Host: 10.167.20.56

Icy-MetaData: 1

[h264 @ 0x18b4da00] non-existing SPS 0 referenced in buffering period
[http @ 0x1d498c50] request: GET /gongfuxiongmao2_143626076210507.ts HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=472019872-

Connection: close

Host: 10.167.20.56

Icy-MetaData: 1

ijkmp_get_msg: FFP_MSG_SEEK_COMPLETE
2015-11-27 14:02:47.861 GGDFPlayerDemo[223:31134] FFP_MSG_SEEK_COMPLETE:
[h264 @ 0x18b4da00] non-existing SPS 0 referenced in buffering period
[FFPlayer @ 0x1839b600] ffp_toggle_buffering_l: end
aout_pause_audio(0)
flushed last keyframe pts 478800 
2015-11-27 14:02:48.435 GGDFPlayerDemo[223:31134] FFP_MSG_BUFFERING_END:
2015-11-27 14:02:48.438 GGDFPlayerDemo[223:31134] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3
2015-11-27 14:02:48.439 GGDFPlayerDemo[223:31134] moviePlayBackStateDidChange 1: playing
Audio frame changed from rate:44100 ch:2 fmt:fltp layout:stereo serial:1 to rate:44100 ch:2 fmt:fltp layout:stereo serial:2
after scale width 960 height 540 
[ffplay_abuffer @ 0x1d4f1530] Setting 'sample_rate' to value '44100'
[ffplay_abuffer @ 0x1d4f1530] Setting 'sample_fmt' to value 'fltp'
[ffplay_abuffer @ 0x1d4f1530] Setting 'channels' to value '2'
[ffplay_abuffer @ 0x1d4f1530] Setting 'time_base' to value '1/44100'
[ffplay_abuffer @ 0x1d4f1530] Setting 'channel_layout' to value '0x3'
[ffplay_abuffer @ 0x1d4f1530] tb:1/44100 samplefmt:fltp samplerate:44100 chlayout:0x3
[ffplay_abuffersink @ 0x17e9ca10] auto-inserting filter 'auto-inserted resampler 0' between the filter 'ffplay_abuffer' and the filter 'ffplay_abuffersink'
[AVFilterGraph @ 0x17ef43a0] query_formats: 2 queried, 0 merged, 3 already done, 0 delayed
[auto-inserted resampler 0 @ 0x17e9a1b0] [SWR @ 0x2f9e000] Using fltp internally between filters
[auto-inserted resampler 0 @ 0x17e9a1b0] ch:2 chl:stereo fmt:fltp r:44100Hz -> ch:2 chl:stereo fmt:s16 r:44100Hz
decode callback -12909 kVTVideoDecoderBadDataErr
decodeFrame -12911 kVTVideoDecoderMalfunctionErr

**Comment by bbcallen** [comment]
disable videotoolbox may fix this problem

**Comment by fukemy** [comment]
Hi. how to disable videotoolbox by config in ios? Thanks
