### ISSUE TITLE
how to display one picture called APIs of ijksdl ?

### ISSUE THREAD

**Issue by sentervip** [Bilibili/ijkplayer#691]
Hello,How to display one picture called apis of ijksdl ?
thanks !

try:
java get a surface and jni do this:
SDLVOUT VOUT;
    overlay =SDL_Vout_CreatOverlay(VOUT)
failed: overlay is NULL now;
    SDL_xxconvertFrame()
    ret =vout_display_overlay_l(VOUT,overlay)

**Comment by sentervip** [comment]
I wan't to add in IJK now.

**Comment by bbcallen** [comment]
Not understand what you want to do.
If you are on java side, why don't you display it with system API?

**Comment by sentervip** [comment]
Study with you code.
I want add new code which play the rtsp stream to the ijkplayer.
Pkt receive  and decoded  is ok ,but can't display with ijkSDL now. 
THanks bbcallen.

**Comment by qazmoon** [comment]
@sentervip 这烂英语，还是说中文吧

**Comment by Android4MediaPlayer** [comment]
java层去做吧

**Comment by bbcallen** [comment]
How do you know "decode is OK" while no picture?
