### ISSUE TITLE
Android RuntimeException

### ISSUE THREAD

**Issue by Asa-Walker** [Bilibili/ijkplayer#692]
java.util.concurrent.TimeoutException: tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize() timed out after 30 seconds

**Comment by Asa-Walker** [comment]
播放器实例 创建、销毁、创建、销毁，重复4、5遍后 报错

**Comment by Asa-Walker** [comment]
这个bug下个版本解决吗？

**Comment by xiaoyaomeng** [comment]
@Asa-Walker  我跟你遇到同样的问题，求教你怎么解决？

**Comment by Asa-Walker** [comment]
@xiaoyaomeng 作者已经打了patch
