### ISSUE TITLE
ios版本上，opessl编译成功后。在xcode上运行的时候报错。

### ISSUE THREAD

**Issue by andyjmzheng** [Bilibili/ijkplayer#693]
打印如下。
Ld /Users/guomiqi/Library/Developer/Xcode/DerivedData/IJKMediaDemo-ctengckjhpmocvgwurgolsoxixto/Build/Products/Debug-iphonesimulator/IJKMediaDemo.app/IJKMediaDemo normal x86_64
    cd /Users/guomiqi/Desktop/ijkplayer/ijkplayer-ios_test/ios/IJKMediaDemo
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.1.sdk -L/Users/guomiqi/Library/Developer/Xcode/DerivedData/IJKMediaDemo-ctengckjhpmocvgwurgolsoxixto/Build/Products/Debug-iphonesimulator -F/Users/guomiqi/Library/Developer/Xcode/DerivedData/IJKMediaDemo-ctengckjhpmocvgwurgolsoxixto/Build/Products/Debug-iphonesimulator -filelist /Users/guomiqi/Library/Developer/Xcode/DerivedData/IJKMediaDemo-ctengckjhpmocvgwurgolsoxixto/Build/Intermediates/IJKMediaDemo.build/Debug-iphonesimulator/IJKMediaDemo.build/Objects-normal/x86_64/IJKMediaDemo.LinkFileList -mios-simulator-version-min=7.0 -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -framework AudioToolbox -framework AVFoundation -framework CoreGraphics -framework CoreMedia -framework CoreVideo -lbz2 -lz /Users/guomiqi/Library/Developer/Xcode/DerivedData/IJKMediaDemo-ctengckjhpmocvgwurgolsoxixto/Build/Products/Debug-iphonesimulator/IJKMediaFramework.framework/IJKMediaFramework -framework MediaPlayer -framework MobileCoreServices -framework OpenGLES -framework QuartzCore -framework UIKit -framework VideoToolbox -Xlinker -dependency_info -Xlinker /Users/guomiqi/Library/Developer/Xcode/DerivedData/IJKMediaDemo-ctengckjhpmocvgwurgolsoxixto/Build/Intermediates/IJKMediaDemo.build/Debug-iphonesimulator/IJKMediaDemo.build/Objects-normal/x86_64/IJKMediaDemo_dependency_info.dat -o /Users/guomiqi/Library/Developer/Xcode/DerivedData/IJKMediaDemo-ctengckjhpmocvgwurgolsoxixto/Build/Products/Debug-iphonesimulator/IJKMediaDemo.app/IJKMediaDemo

Undefined symbols for architecture x86_64:
  "_BIO_clear_flags", referenced from:
      _url_bio_bwrite in IJKMediaFramework(tls_openssl.o)
      _url_bio_bread in IJKMediaFramework(tls_openssl.o)
      _url_bio_bputs in IJKMediaFramework(tls_openssl.o)
      _url_bio_ctrl in IJKMediaFramework(tls_openssl.o)
  "_BIO_new", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_CRYPTO_get_locking_callback", referenced from:
      _ff_openssl_init in IJKMediaFramework(tls_openssl.o)
      _ff_openssl_deinit in IJKMediaFramework(tls_openssl.o)
  "_CRYPTO_num_locks", referenced from:
      _ff_openssl_init in IJKMediaFramework(tls_openssl.o)
      _ff_openssl_deinit in IJKMediaFramework(tls_openssl.o)
  "_CRYPTO_set_locking_callback", referenced from:
      _ff_openssl_init in IJKMediaFramework(tls_openssl.o)
      _ff_openssl_deinit in IJKMediaFramework(tls_openssl.o)
  "_ERR_error_string", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
      _tls_read in IJKMediaFramework(tls_openssl.o)
      _tls_write in IJKMediaFramework(tls_openssl.o)
  "_ERR_get_error", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
      _tls_read in IJKMediaFramework(tls_openssl.o)
      _tls_write in IJKMediaFramework(tls_openssl.o)
  "_SSL_CTX_free", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
      _tls_close in IJKMediaFramework(tls_openssl.o)
  "_SSL_CTX_load_verify_locations", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_SSL_CTX_new", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_SSL_CTX_set_verify", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_SSL_CTX_use_PrivateKey_file", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_SSL_CTX_use_certificate_chain_file", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_SSL_accept", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_SSL_connect", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_SSL_ctrl", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_SSL_free", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
      _tls_close in IJKMediaFramework(tls_openssl.o)
  "_SSL_library_init", referenced from:
      _ff_openssl_init in IJKMediaFramework(tls_openssl.o)
  "_SSL_load_error_strings", referenced from:
      _ff_openssl_init in IJKMediaFramework(tls_openssl.o)
  "_SSL_new", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_SSL_read", referenced from:
      _tls_read in IJKMediaFramework(tls_openssl.o)
  "_SSL_set_bio", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_SSL_shutdown", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
      _tls_close in IJKMediaFramework(tls_openssl.o)
  "_SSL_write", referenced from:
      _tls_write in IJKMediaFramework(tls_openssl.o)
  "_TLSv1_client_method", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
  "_TLSv1_server_method", referenced from:
      _tls_open in IJKMediaFramework(tls_openssl.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation

@bbcallen

**Comment by bbcallen** [comment]
Did you add libssl.a to your project?

**Comment by andyjmzheng** [comment]
yes.already add libssl.a and libcrypto.a  @bbcallen

**Comment by andyjmzheng** [comment]
libstdc++.6.tdb
libbz2.tbd
libssl.a
libcrypto.a
libswscale.a
libavformat.a
libavcodec.a
libavfilter.a
libavutil.a
libswresample.a

我就是增加的这些.a文件。 链接后就会报上边的错误。 @bbcallen 
谢谢！

**Comment by andyjmzheng** [comment]
@bbcallen  我提的这个问题有人解决吗？谢谢！知道是什么原因吗？

**Comment by andyjmzheng** [comment]
@tasdg-yamamoto 
hello.do you have met the message above.
when i compile the openssl .after compiled the openssl,than i use it on iso
 with xcode.it reported many error.

**Comment by andyjmzheng** [comment]
@Android4MediaPlayer  你好。你遇到过我上边提到的问题吗？谢谢

**Comment by Android4MediaPlayer** [comment]
是库没链接上，我没弄ios

**Comment by andyjmzheng** [comment]
android 上我已经弄好了。就是在ios上怎么都不成功。ios是会编译出来好多个.a的文件。 @Android4MediaPlayer

**Comment by andyjmzheng** [comment]
知道ios上怎么链接吗？ @Android4MediaPlayer

**Comment by wanzhi** [comment]
android openssl 最后在 ./compile-ijk.sh armv7a 的时候报一大堆error: undefined reference to 'I422ToYUY2Row_NEON' 类似错误， @andyjmzheng ，请问你是编译过了吗？
