### ISSUE TITLE
How to add the player request header? 

### ISSUE THREAD

**Issue by zyi1992** [Bilibili/ijkplayer#697]
Is there any way to add http header for ijkplayer?

**Comment by qazmoon** [comment]
```c++
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "header_name", "header_string");
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "header_name", head_int);
```

**Comment by bbcallen** [comment]
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "headers", <headers>);

**Comment by zyi1992** [comment]
Thanks,that's work to me

**Comment by Blackquan** [comment]
hi, could you @qazmoon pls show more detail,
i dont know push that code to where
Thank you

**Comment by ndngiap** [comment]
@Blackquan You will find it in IjkVideoView class
