### ISSUE TITLE
播放本地M3U8视频，拉动进度条手机重启

### ISSUE THREAD

**Issue by kevin-zhujunyi** [Bilibili/ijkplayer#698]
[http @ 0x12b025e60] No trailing CRLF found in HTTP header.
[http @ 0x12b025e60] request: GET /396618/id33 HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Connection: close

Host: 127.0.0.1:12345

Icy-MetaData: 1

[NULL @ 0x126b88c00] unknown SEI type 37

**Comment by bbcallen** [comment]
Can you provide crash stack information?
