### ISSUE TITLE
MPEG-TS, MP4 stream seeking compability

### ISSUE THREAD

**Issue by don11995** [Bilibili/ijkplayer#699]
Hello! I tried your player and it is prety powerful and the most stable among all players that I tried on ffmpeg. But there is one critical issue in all players and in your's too - it does not support seeking in MPEG-TS, MP4 stream (your player can seek, but duration of the video is 0). By specification of MPEG-TS there is no way to positionnig within stream if stream not fully loaded, but I tested FFMpeg on iOS (not your's player) and FFMpeg is the only thing that can do positioning within MPEG-TS stream. Your player can seek, but I can not seek to needed millisecond while duration of the video is 0. I can only seek as offset to current position. On iOS FFMpeg returns duration as expected. The only difference that I saw in your's ffplay.c - while getting stream info You pass opts as parameters of the codec, while on iOS I pass NULL. Will your's player support this thing in future? Thanks a lot and sorry for my English.

**Comment by bbcallen** [comment]
What do you mean "On iOS FFMpeg returns duration as expected"?
Can you paste the log?

**Comment by don11995** [comment]
Ok, I found what is the problem - in iOS I get meta by parsing metadata from stream and then getting durationUS from it, in Android (in IjkMediaPlayer) I found the same thing:
```
mediaPlayer.getMediaInfo().mMeta
```
and it contains needed mDurationUS and the duration is correct, but if I call the next code:
```
mediaPlayer.getDuration()
```
it always returns 0.
I made the next wrapper for getDuration function:
```
    public long getDuration() {
        if (mediaPlayer ==null) return 0;
        //return mediaPlayer.getLength();
        return Math.max(mediaPlayer.getDuration(),mediaPlayer.getMediaInfo().mMeta.mDurationUS)/1000;
    }
```
And now it works fine, but I think this is the small bug. Because I have duration I can positioning now normally and your player do this perfectly. Only one question: how can I set less buffering time, because it about 5 seconds and it is too long?

**Comment by bbcallen** [comment]
Reduce DEFAULT_MAX_HIGH_WATER_MARK_IN_MS in ff_ffplay_def.h

**Comment by don11995** [comment]
There is no way to do this from Java code? I'm using gradle for now to import Your library.

**Comment by bbcallen** [comment]
No.
