### ISSUE TITLE
Player crashes on long loading and if connection lost.

### ISSUE THREAD

**Issue by don11995** [Bilibili/ijkplayer#700]
Sometimes your player crashes when video loading too long or if connection was lost or switched to other. This is like bug report=) I'm using it on Android devices with class IjkMediaPlayer.

**Comment by bbcallen** [comment]
Can you provide any crash stack information?

**Comment by don11995** [comment]
Sorry can't do this, because crash occurrs  in native code and it is loop there. I'll try to reproduce this and then write here how You can get this loop.
