### ISSUE TITLE
how can i get OnProgressUpdateListener method?

### ISSUE THREAD

**Issue by cikichen** [Bilibili/ijkplayer#701]

**Comment by bbcallen** [comment]
No idea what do you mean.

**Comment by cikichen** [comment]
是否能够提供进度更新的监听方法

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/android/ijkplayer/ijkplayer-java/src/main/java/tv/danmaku/ijk/media/player/IMediaPlayer.java#L146

**Comment by cikichen** [comment]
这是播放进度还是缓冲的？

**Comment by bbcallen** [comment]
I don't remember.
