### ISSUE TITLE
MediaCodec returning error -2147483648

### ISSUE THREAD

**Issue by NikmanSergey** [Bilibili/ijkplayer#702]
@bbcallen,
First of all, thanks a lot for the added *getTrakInfo* and *selectTrack*!!! It works great (if not set currently selected track - it will crash then).

However, in k0.4.4 version after several (~10-20) URLs playback it can't use MediaCodec anymore with this error logs on 2 different devices:

1 device:
```
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: selected codec: OMX.amlogic.avc.decoder.awesome rank=800
D/IJKMEDIA: SDL_AMediaCodecJava_createByCodecName
W/ALooperRoster: ALooper::handler_id ALooperRoster::registerHandler 86
W/ALooperRoster: ALooper::handler_id ALooperRoster::registerHandler 87
I/OMXClient: Using client-side OMX mux.
E/ACodec: Unable to instantiate decoder 'OMX.amlogic.avc.decoder.awesome'.
E/MediaCodec: Codec reported an error. (omx error 0x80001003, internalError -2147483648)
W/System.err: java.io.IOException: Failed to allocate component instance
W/System.err:     at android.media.MediaCodec.native_setup(Native Method)
W/System.err:     at android.media.MediaCodec.<init>(MediaCodec.java:210)
W/System.err:     at android.media.MediaCodec.createByCodecName(MediaCodec.java:204)
W/System.err:     at dalvik.system.NativeStart.run(Native Method)
W/System.err: java.io.IOException: Failed to allocate component instance
W/System.err:     at android.media.MediaCodec.native_setup(Native Method)
W/System.err:     at android.media.MediaCodec.<init>(MediaCodec.java:210)
W/System.err:     at android.media.MediaCodec.createByCodecName(MediaCodec.java:204)
W/System.err:     at dalvik.system.NativeStart.run(Native Method)
E/IJKMEDIA: reconfigure_codec_l:open_video_decoder: create_codec failed
I/IJKMEDIA: VideoCodec: avcodec, h264
```

2 device:
```
I/tv.danmaku.ijk.media.player.IjkMediaPlayer﹕ selected codec: OMX.qcom.video.decoder.avc rank=800
D/IJKMEDIA﹕ SDL_AMediaCodecJava_createByCodecName
I/OMXClient﹕ Using client-side OMX mux.
D/IJKMEDIA﹕ SDL_AMediaCodecJava_init
D/IJKMEDIA﹕ SDL_AMediaCodecJava_configure_surface
E/IJKMEDIA﹕ configure acodec:0x100ce6 format:0x200cfe: surface:0x200cf6
D/MediaCodec﹕ MediaCodec[kWhatConfigure]: video-output-protection: 00000000, audio-output-protection: 00000000
I/ACodec﹕ [OMX.qcom.video.decoder.avc] DRC Mode: Dynamic Buffer Mode
E/ACodec﹕ [OMX.qcom.video.decoder.avc] configureCodec returning error -2147483648
E/ACodec﹕ [OMX.qcom.video.decoder.avc] configureCodec returning error -2147483648
E/ACodec﹕ signalError(omxError 0x80001001, internalError -2147483648)
E/MediaCodec﹕ Codec reported err 0x80001001, actionCode 0, while in state 3
E/MediaCodec﹕ configure failed with err 0x80001001, resetting...
I/OMXClient﹕ Using client-side OMX mux.
W/System.err﹕ android.media.MediaCodec$CodecException: Error 0x80001001
W/System.err﹕ at android.media.MediaCodec.native_configure(Native Method)
W/System.err﹕ at android.media.MediaCodec.configure(MediaCodec.java:594)
E/IJKMEDIA﹕ reconfigure_codec_l:configure_surface: failed
I/IJKMEDIA﹕ SDL_AMediaCodecJava_delete
I/IJKMEDIA﹕ VideoCodec: avcodec, h264
```

Only hard app restart can return it to normal working.
I do not have this issure with k0.4.1.1 version.

Please, help!!!

**Comment by bbcallen** [comment]
Sounds something is leaked.
Were you testing in demo project, or in your own app?

**Comment by NikmanSergey** [comment]
@bbcallen 
Both.
I can get this issue steady with *ijkplayer-sample* app after start playing 20~30 FullHD videos.

**Comment by vladd49** [comment]
I've also got this issue after playing 1-2 videos on some devices. After making some investigation I noticed that SDL_AMediaCodec_decreaseReferenceP is called several times when video is being stopped.

When ref_count is > 0 SDL_AMediaCodec_delete is not called and OMX resources are not released. But you nullify *acodec in SDL_AMediaCodec_decreaseReferenceP in any case, thus preventing calling SDL_AMediaCodec_delete in the future.  

I've made the following fix in ijkmedia/ijksdl/android/ijksdl_codec_android_mediacodec.c:

```
int SDL_AMediaCodec_decreaseReference(SDL_AMediaCodec *acodec)
{
    if (!acodec)
        return -1;

    int ref_count = __sync_sub_and_fetch(&acodec->ref_count, 1);
    if (ref_count == 0) {
        AMCTRACE("%s(): ref=0\n", __func__);
        if (SDL_AMediaCodec_isStarted(acodec)) {
            SDL_AMediaCodec_stop(acodec);
        }
        SDL_AMediaCodec_delete(acodec);
    }
    return ref_count;
}

void SDL_AMediaCodec_decreaseReferenceP(SDL_AMediaCodec **acodec)
{
    if (!acodec)
        return;

    if ((SDL_AMediaCodec_decreaseReference(*acodec) == 0)) {
        *acodec = NULL;
    }
}
```

Also you need to change the returning type to int of SDL_AMediaCodec_decreaseReference in ijksdl_codec_android_mediacodec.h.

Everything seems to be working now. @bbcallen can you please confirm that this fix won't break anything?

**Comment by bbcallen** [comment]
You are very likely on the right direction, but that's not a right fix.
It's wrong to release ownership twice on same reference.

**Comment by vladd49** [comment]
What do you mean "to release ownership"? Is it done with SDL_AMediaCodec_delete? Only invoking this function fixes the problem. How it supposed to be called when ref_count is greater then 0?

**Comment by bbcallen** [comment]
I have pushed a blind-fix on branch
https://github.com/Bilibili/ijkplayer/commit/6608c0cfa150690e8db347022bfc00879303913c

I can't take any tests before next week, because no USB cable on my hand, 

Anyway, thanks for your pointing out, @vladd49

**Comment by NikmanSergey** [comment]
@bbcallen,
Looks like this commit do fixes this issue. Thanks!!!
