### ISSUE TITLE
the arg1 of MEDIA_BUFFERING_UPDATE is always less than duration

### ISSUE THREAD

**Issue by vincentssn** [Bilibili/ijkplayer#704]
hi, I use notifyOnBufferingUpdate(bufferPosition) to update the download progress, 
```
switch(msg.what){
       case MEDIA_BUFFERING_UPDATE:
                long bufferPosition = msg.arg1;
                Log.i("sky","============buffer: " + msg.arg1 + " 2:"+msg.arg2);
                if (bufferPosition < 0) {
                    bufferPosition = 0;
                }

                long percent = 0;
                long duration = player.getDuration();
                if (duration > 0) {
                    percent = bufferPosition * 100 / duration;
                }
                if (percent >= 100) {
                    percent = 100;
                }

                // DebugLog.efmt(TAG, "Buffer (%d%%) %d/%d",  percent, bufferPosition, duration);
                player.notifyOnBufferingUpdate((int)percent);
                return;
}
```

but I find the bufferPosition (also the msg.arg1) is always less than duration, which lead to the download progress is always less than 100%, Is it a bug? or is the bufferPosition is size but not duration? or when the bufferPosition equals to the duration, IjkMediaPlayer will send another Message?

**Comment by bbcallen** [comment]
There is no guarantee that MEDIA_BUFFERING_UPDATE returns all progress.
If you need it, just modify ffp_check_buffering_l() in ff_ffplay.c

**Comment by vincentssn** [comment]
@bbcallen   Thanks a lot. I have added a msg when av_read_frame()  return ret <0 in read_thread() to show the downloading buffering is completed.
