### ISSUE TITLE
最新版本开启硬解后, 视频方向错误, 被旋转了90度

### ISSUE THREAD

**Issue by lch2014a** [Bilibili/ijkplayer#707]
有什么方法可解吗?

**Comment by dourgulf** [comment]
视频方向应该要跟推流配合设置的，视频流本身貌似不带视频方向信息的。

**Comment by xiaoyaomeng** [comment]
@wqmijkplayer @bbcallen  hello, 二位大神，我发现在MTK6752的手机上，createPlayer(Settings.PV_PLAYER__IjkMediaPlayer) 然后设置为硬解码的话，也会90度倒置，软解不会（MTK6795上正常）。但是如果是Player采用：Settings.PV_PLAYER__AndroidMediaPlayer 的话不会有这种情况。 “wqmijkplayer” 认为是ijkplayer的问题，希望可不可以尽快帮忙解决下 项目比较赶。

**Comment by bbcallen** [comment]
Use TextureView instead of SurfaceView, in preference

**Comment by xiaoyaomeng** [comment]
@bbcallen  我用你的方案试了，的确可以了，谢谢哈~

**Comment by chq1314** [comment]
请问如何开启硬解

**Comment by chq1314** [comment]
How to open hardware decode function?

**Comment by BlueTopsky** [comment]
iOS里面没有TextureView，请问怎么解决这一问题啊，播放竖着拍摄的视频就会自动旋转了90度，播放横着拍摄的视频时是正常的

**Comment by menglijun** [comment]
请问楼主，视频方法错误那个解决了吗？
