### ISSUE TITLE
how to add a file cache for ijkplayer android?

### ISSUE THREAD

**Issue by lixiaoqi** [Bilibili/ijkplayer#713]
Hi, it seems that ijkplayer android doesn't cache the video in local file system and each time play a different video from network it has to download it first.

I'm interested to add a file cache to ijkplayer but I'm still a newbie to video player and ffmpeg.

Could anybody give me some thoughts about this.

thank you very much.

**Comment by bbcallen** [comment]
http://git.videolan.org/?p=ffmpeg.git;a=blob;f=libavformat/cache.c;h=d41161d4987ad514db19be7fbb91f0868f41a110;hb=HEAD

**Comment by lixiaoqi** [comment]
Thanks, and what is the difference between below sources?
https://github.com/Bilibili/FFmpeg
https://github.com/FFmpeg/FFmpeg
http://git.videolan.org/?p=ffmpeg.git;a=summary
