### ISSUE TITLE
crash when run demo

### ISSUE THREAD

**Issue by lixiaoqi** [Bilibili/ijkplayer#716]
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime: FATAL EXCEPTION: main
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime: java.lang.UnsatisfiedLinkError: Couldn't load ijksdl: findLibrary returned null
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime:     at java.lang.Runtime.loadLibrary(Runtime.java:365)
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime:     at java.lang.System.loadLibrary(System.java:535)
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime:     at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:144)
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime:     at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:156)
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime:     at tv.danmaku.ijk.media.sample.activities.VideoActivity.onCreate(VideoActivity.java:136)
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5008)
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime:     at android.app.ActivityThread.access$600(ActivityThread.java:130)
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99)
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137)
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4745)
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
12-08 12:26:05.030 1332-1332/tv.danmaku.ijk.media.sample E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

**Comment by lixiaoqi** [comment]
libLoader.loadLibrary("ijkffmpeg") success but libLoader.loadLibrary("ijksdl") failed

**Comment by bbcallen** [comment]
Did you run compile-ijkplayer successfully?

**Comment by lixiaoqi** [comment]
The problem is solved after download and build all over again.
Thanks.
