### ISSUE TITLE
Play in slow motion, and delayed longer and longer, how should solve?

### ISSUE THREAD

**Issue by mistak** [Bilibili/ijkplayer#717]
Reality has gone in 60 seconds, it only had less than 50 players, what reason is this?How to solve?

**Comment by mistak** [comment]
av_version_info: n2.7-30-g250af29
ijkmp_set_inject_opaque(0x7fadfad4c460)
ijkmp_set_option_int(ijkinject-opaque, 140385214317664)
ijkmp_set_option_int()=void
ijkmp_set_inject_opaque()=void
ijkmp_set_option_int(start-on-prepared, 1)
ijkmp_set_option_int()=void
2015-12-10 11:50:43.297 IJKMediaDemo[3081:933778] OK setup GL
ijkmp_ios_set_view(glView=0x7fadfad4dc20)
ijkmp_ios_set_view(glView=0x7fadfad4dc20)=void
ijkmp_set_option(overlay-format, fcc-i420)
ijkmp_set_option()=void
ijkmp_set_option_int(skip_frame, 8)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_loop_filter, 48)
ijkmp_set_option_int()=void
ijkmp_set_option(user-agent, ijkplayer)
ijkmp_set_option()=void
ijkmp_set_option_int(auto_convert, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(timeout, 30000000)
ijkmp_set_option_int()=void
ijkmp_set_option_int(reconnect, 1)
ijkmp_set_option_int()=void
ijkmp_set_option_int(max-fps, 30)
ijkmp_set_option_int()=void
ijkmp_set_option_int(framedrop, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox-max-frame-width, 960)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(video-pictq-size, 3)
ijkmp_set_option_int()=void
ijkmp_set_data_source(url="http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/prog_index.m3u8")
ijkmp_set_data_source(url="http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/prog_index.m3u8")=0
ijkmp_set_option(safe, 0)
ijkmp_set_option()=void
ijkmp_prepare_async()
===== options =====
player-opts : start-on-prepared            = 1
player-opts : overlay-format               = fcc-i420
player-opts : max-fps                      = 30
player-opts : framedrop                    = 0
player-opts : videotoolbox-max-frame-width = 960
player-opts : videotoolbox                 = 0
player-opts : video-pictq-size             = 3
format-opts : ijkinject-opaque             = 140385214317664
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : timeout                      = 30000000
format-opts : reconnect                    = 1
format-opts : safe                         = 0
codec-opts  : skip_frame                   = 8
codec-opts  : skip_loop_filter             = 48
===================
ijkmp_prepare_async()=0
ijkmp_start()
ijkmp_start()=-3
[http @ 0x7fadfad11030] request: GET /streaming/examples/bipbop_4x3/gear1/prog_index.m3u8 HTTP/1.1
User-Agent: ijkplayer
Accept: */*
Range: bytes=0-
Connection: close
Host: devimages.apple.com.edgekey.net
Icy-MetaData: 1


[hls,applehttp @ 0x7fadfb816600] Format hls,applehttp probed with size=2048 and score=100
[hls,applehttp @ 0x7fadfb816600] HLS request for url 'http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/fileSequence0.ts', offset 0, playlist 0
[http @ 0x7fadfad48ae0] request: GET /streaming/examples/bipbop_4x3/gear1/fileSequence0.ts HTTP/1.1
User-Agent: ijkplayer
Accept: */*
Connection: close
Host: devimages.apple.com.edgekey.net
Icy-MetaData: 1


Format mpegts probed with size=2048 and score=100
[mpegts @ 0x7fadfb801800] stream=0 stream_type=1b pid=101 prog_reg_desc=
[mpegts @ 0x7fadfb801800] stream=1 stream_type=f pid=102 prog_reg_desc=
[mpegts @ 0x7fadfb801800] Before avformat_find_stream_info() pos: 0 bytes read:22266 seeks:0
[h264 @ 0x7fadfb804800] Current profile doesn't provide more RBSP data in PPS, skipping
[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=903000, dts=906000, size=525
[h264 @ 0x7fadfb804800] Increasing reorder buffer to 1
[h264 @ 0x7fadfb804800] no picture 
[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=909000, dts=912000, size=525
[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=915000, dts=918000, size=525
[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=921000, dts=924000, size=525
[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=927000, dts=930150, size=525
[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=933150, dts=936150, size=525
[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=939150, dts=942150, size=525
[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=945150, dts=948150, size=341
[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=951150, dts=954150, size=525
[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=957150, dts=960150, size=525
[mpegts @ 0x7fadfb801800] All info found
[mpegts @ 0x7fadfb801800] rfps: 29.166667 0.019557
[mpegts @ 0x7fadfb801800] rfps: 29.250000 0.015337
[mpegts @ 0x7fadfb801800] rfps: 29.250000 0.015337
[mpegts @ 0x7fadfb801800] rfps: 29.333333 0.011634
[mpegts @ 0x7fadfb801800] rfps: 29.416667 0.008447
[mpegts @ 0x7fadfb801800] rfps: 29.500000 0.005778
[mpegts @ 0x7fadfb801800] rfps: 29.500000 0.005778
[mpegts @ 0x7fadfb801800] rfps: 29.583333 0.003626
[mpegts @ 0x7fadfb801800] rfps: 29.583333 0.003626
[mpegts @ 0x7fadfb801800] rfps: 29.666667 0.001991
[mpegts @ 0x7fadfb801800] rfps: 29.750000 0.000872
[mpegts @ 0x7fadfb801800] rfps: 29.750000 0.000872
[mpegts @ 0x7fadfb801800] rfps: 29.833333 0.000271
[mpegts @ 0x7fadfb801800] rfps: 29.833333 0.000271
[mpegts @ 0x7fadfb801800] rfps: 29.916667 0.000186
[mpegts @ 0x7fadfb801800] rfps: 29.916667 0.000186
[mpegts @ 0x7fadfb801800] rfps: 30.000000 0.000619
[mpegts @ 0x7fadfb801800] rfps: 60.000000 0.002475
[mpegts @ 0x7fadfb801800] rfps: 120.000000 0.009900
[mpegts @ 0x7fadfb801800] rfps: 29.970030 0.000404
[mpegts @ 0x7fadfb801800] rfps: 29.970030 0.000404
[mpegts @ 0x7fadfb801800] rfps: 59.940060 0.001615
[mpegts @ 0x7fadfb801800] rfps: 59.940060 0.001615
[mpegts @ 0x7fadfb801800] Setting avg frame rate based on r frame rate
[mpegts @ 0x7fadfb801800] After avformat_find_stream_info() pos: 24440 bytes read:25082 seeks:0 frames:36
Option safe not found.
[hls,applehttp @ 0x7fadfb816600] Before avformat_find_stream_info() pos: 6701 bytes read:6701 seeks:0
[h264 @ 0x7fadfb832400] no picture 
[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=903000, dts=906000, size=595
[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=909000, dts=912000, size=503
[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=915000, dts=918000, size=434
[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=921000, dts=924000, size=456
[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=927000, dts=930150, size=428
[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=933150, dts=936150, size=472
[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=939150, dts=942150, size=506
[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=945150, dts=948150, size=425
[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=951150, dts=954150, size=470
[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=957150, dts=960150, size=418
[hls,applehttp @ 0x7fadfb816600] All info found

hls,applehttp @ 0x7fadfb816600] Setting avg frame rate based on r frame rate

[hls,applehttp @ 0x7fadfb816600] After avformat_find_stream_info() pos: 6701 bytes read:6701 seeks:0 frames:36

[FFPlayer @ 0x7fadfad1c1b0] max_frame_duration: 10.000

Input #0, hls,applehttp, from 'http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/prog_index.m3u8':

  Duration: 00:30:00.00, start: 9.904222, bitrate: 0 kb/s

  Program 0 

    Metadata:

      variant_bitrate : 0

    Stream #0:0, 21, 1/90000: Video: h264 (Main), 2 reference frames ([27][0][0][0] / 0x001B), yuv420p(tv, smpte170m/smpte170m/bt709, topleft), 400x300 (400x304), 1/180000, 29.92 fps, 29.92 tbr, 90k tbn, 180k tbc

    Stream #0:1, 15, 1/90000: Audio: aac (LC) ([15][0][0][0] / 0x000F), 22050 Hz, stereo, fltp, 2 kb/s

aout_open_audio()

[FFPlayer @ 0x7fadfad1c1b0] AudioCodec: avcodec, aac

aout_pause_audio(0)

detected 4 logical cores

vtb fail!!! switch to ffmpeg decode!!!! 

[FFPlayer @ 0x7fadfad1c1b0] VideoCodec: avcodec, h264

[FFPlayer @ 0x7fadfad1c1b0] fps: 29.916667 (normal)

[FFPlayer @ 0x7fadfad1c1b0] fps: 29.916667 (normal)

ijkmp_get_msg: FFP_MSG_PREPARED

[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=963150, dts=966150, size=525

[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=963150, dts=966150, size=437

[mpegts @ 0x7fadfb801800] invalid dts/pts combination 969150

[NULL @ 0x7fadfb804800] Current profile doesn't provide more RBSP data in PPS, skipping

2015-12-10 11:50:47.326 IJKMediaDemo[3081:933778] FFP_MSG_VIDEO_DECODER_OPEN: false

[mpegts @ 0x7fadfb801800] invalid dts/pts combination 972150

[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=975150, dts=978150, size=525

[h264 @ 0x7fadfc062000] no picture 

[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=975150, dts=978150, size=427

[mpegts @ 0x7fadfb801800] Invalid timestamps stream=2015-12-10 11:50:47.327 IJKMediaDemo[3081:933778] FFP_MSG_VIDEO_SIZE_CHANGED: 400, 300

0, pts=981150, dts=984150, size=525

SDL_VoutFFmpeg_CreateOverlay(w=400, h=300, fmt=I420(0x30323449, dp=0x7fadfad27470)

[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=981150, dts=984150, size=462

avcodec/Video: first frame decoded

[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=987150, dts=990150, size=525

2015-12-10 11:50:47.341 IJKMediaDemo[3081:933778] FFP_MSG_SAR_CHANGED: 0, 1

[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=987150, dts=990150, size=434

[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=993150, dts=996150, size=525

[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=993150, dts=996150, size=444

[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=999150, dts=1002150, size=525

[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=999150, dts=1002150, size=456

[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=1005150, dts=1008150, size=341

[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=1005150, dts=1008150, size=450

[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=1011150, dts=1014150, size=525

2015-12-10 11:50:47.341 IJKMediaDemo[3081:933778] FFP_MSG_PREPARED:

ijkmp_get_meta_l

ijkmp_get_meta_l()=void

[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=1011150, dts=1014150, size=439

[m2015-12-10 11:50:47.341 IJKMediaDemo[3081:933778] fps in meta 29.916667

pegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=1017150, dts=1020150, size=341

SDL_VoutFFmpeg_CreateOverlay(w=400, h=300, fmt=I420(0x30323449, dp=0x7fadfad27470)

2015-12-10 11:50:47.341 IJKMediaDemo[3081:933778] mediaIsPreparedToPlayDidChange

[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=1017150, dts=1020150, size=413

[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=1023150, dts=1026150, size=525

2015-12-10 11:50:47.341 IJKMediaDemo[3081:933778] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3

[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=1023150, dts=1026150, size=422

[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=1029150, dts=1032150, size=525

[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=1029150, dts=1032150, size=479

[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=1035150, dts=1038150, size=341

[hls,applehttp @ 0x7fadfb816600] Inv2015-12-10 11:50:47.341 IJKMediaDemo[3081:933778] moviePlayBackStateDidChange 1: playing

alid timestamps stream=0, pts=1035150, dts=1038150, size=426

SDL_VoutFFmpeg_CreateOverlay(w=400, h=300, fmt=I420(0x30323449, dp=0x7fadfad27470)

[mpegts @ 0x7fadfb801800] invalid dts/pts combination 1041150

[NULL @ 0x7fadfb804800] Current profile doesn't provide more RBSP data in PPS, skipping

[mpegts @ 0x7fadfb801800] invalid dts/pts combination 1044150

[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=1047150, dts=1050150, size=525

[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=1047150, dts=1050150, size=428

[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=1053150, dts=1056150, size=525

[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=1053150, dts=1056150, size=440

2015-12-10 11:50:47.357 IJKMediaDemo[3081:933778] FFP_MSG_VIDEO_SIZE_CHANGED: 400, 300

[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=1059150, dts=1062150, size=525

2015-12-10 11:50:47.358 IJKMediaDemo[3081:933778] FFP_MSG_VIDEO_SIZE_CHANGED: 400, 300

[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=1059150, dts=1062150, size=477

[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=1065150, dts=1068150, size=341

[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=1065150, dts=1068150, size=440

[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=1071150, dts=1074150, size=341

2015-12-10 11:50:47.358 IJKMediaDemo[3081:933778] FFP_MSG_VIDEO_SIZE_CHANGED: 400, 300

[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=1071150, dts=1074150, size=454

[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=1077150, dts=1080300, size=341

[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=1077150, dts=1080300, size=437

[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=1083300, dts=1086300, size=341

2015-12-10 11:50:47.357 IJKMediaDemo[3081:937102] OK use I420 GL renderer

2015-12-10 11:50:47.360 IJKMediaDemo[3081:937102] OK setup GL programm

2015-12-10 11:50:47.360 IJKMediaDemo[3081:937102] OK setup GL framebuffer 1334:750

avcodec/Audio: first frame decoded

2015-12-10 11:50:47.396 IJKMediaDemo[3081:933778] FFP_MSG_AUDIO_RENDERING_START:

[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=1083300, dts=1086300, size=484

[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=1089300, dts=1092300, size=525

[NULL @ 0x7fadfb804800] Current profile doesn't provide more RBSP data in PPS, skipping
[mpegts @ 0x7fadfb801800] invalid dts/pts combination 3566700
[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=3569700, dts=3572700, size=525
[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=3569700, dts=3572700, size=425
[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=3575700, dts=3578700, size=525
[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=3575700, dts=3578700, size=438
[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=3581700, dts=3584700, size=525
[hls,applehttp @ 0x7fadfb816600] Invalid timestamps stream=0, pts=3581700, dts=3584700, size=469
[hls,applehttp @ 0x7fadfb816600] HLS request for url 'http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/fileSequence3.ts', offset 0, playlist 0
ijkmp_stop()
ijkmp_stop()=0
ijkmp_shutdown_l()
wait for read_tid
failed to open segment, retry...Failed to open segment of playlist 0
[hls,applehttp @ 0x7fadfb816600] HLS request for url 'http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/fileSequence4.ts', offset 0, playlist 0
[hls,applehttp @ 0x7fadfb816600] Failed to open segment of playlist 0
[hls,applehttp @ 0x7fadfb816600] HLS request for url 'http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/fileSequence5.ts', offset 0, playlist 0
[hls,applehttp @ 0x7fadfb816600] Failed to open segment of playlist 0
[hls,applehttp @ 0x7fadfb816600] HLS request for url 'http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/fileSequence6.ts', offset 0, playlist 0
[hls,applehttp @ 0x7fadfb816600] Failed to open segment of playlist 0
[hls,applehttp @ 0x7fadfb816600] HLS request for url 'http://devimages.apple.com.edgekey.net/streaming/examples/bi
[hls,applehttp @ 0x7fadfb816600] Failed to open segment of playlist 0
[mpegts @ 0x7fadfb801800] Invalid timestamps stream=0, pts=3587700, dts=3590700, size=485
aout_close_audio()
[AVIOContext @ 0x7fadfac6f0b0] Statistics: 6701 bytes read, 0 seeks
wait for video_refresh_tid
SDL_Overlay(ffmpeg): overlay_free_l(0x7fadfad59df0)
SDL_Overlay(ffmpeg): overlay_free_l(0x7fadfafed580)
SDL_Overlay(ffmpeg): overlay_free_l(0x7fadfae6a5f0)
ijkmp_shutdown_l()=void
ijkmp_dec_ref(): ref=0
ijkmp_shutdown_l()
ijkmp_shutdown_l()=void
aout_close_audio()

**Comment by mistak** [comment]
我截取了一部分控制台的信息，我觉得可能问题是vtb fail!!! switch to ffmpeg decode!!!!或者failed to open segment, retry...或者Failed to open segment of playlist 0？或者不是这三个问题导致？还有，请问我想要直播视频在卡顿之后不接着播放而是实时播放应该怎么做？求助。
I part of the information on the console, I think the problem is that VTB may fail!!!!!!The switch to ffmpeg decode!!!!!!!!!!Or failed to open the segment, retry...Or Failed to open the segment of the playlist 0?Or not these three questions?Also, I want to live video after caton then play but real-time playback should do?Ask for help.

**Comment by mistak** [comment]
@bbcallen

**Comment by bbcallen** [comment]
Were you testing on real device or simulator?

**Comment by mistak** [comment]
simulator,

**Comment by mistak** [comment]
我现在的问题是不知道去哪里调节视频帧数，解码
帧数出现错误。还有，我不知道去哪里清除缓冲？

**Comment by bbcallen** [comment]
search "skip_frame"

**Comment by mistak** [comment]
接触iOS不久，也不认识什么很厉害的人，虽然我还是有很多问题，但还是谢谢您的帮助，

**Comment by mistak** [comment]
@bbcallen

**Comment by mistak** [comment]
最后一个问题，。。怎么刷新视频，。。就是让视频从当前时刻播放。。
