### ISSUE TITLE
ijkplayer基于ffmpeg的，支持first seek功能吗？

### ISSUE THREAD

**Issue by mandagod** [Bilibili/ijkplayer#718]
如题，

谢谢！

**Comment by mandagod** [comment]
@bbcallen  ijkplayer based on the ffmpeg, Does it support first seek? the first seek number from Header of SetDataSource.

**Comment by mandagod** [comment]
@chundong, @ened, @devloe, @tewilove

**Comment by qazmoon** [comment]
什么叫first seek？头一次听说

**Comment by zzjjob** [comment]
Playback starts from the middle position？
like iOS system MediaPlayer initialPlaybackTime API ？

**Comment by RobinLW** [comment]
ijkplayer 可以设置开始时间的啊

**Comment by mandagod** [comment]
@qazmoon  比如说，用户看了一半退出了，下次再次进来的时候直接从上次的位置开始播放；

**Comment by mandagod** [comment]
@zzjjob  Yes, correct.

**Comment by mandagod** [comment]
@RobinLW  是类似seek，从头开始了，再seek?还是开始的时候直接从那个点开始下载并且播放？

**Comment by bbcallen** [comment]
You can implement it by you self based on
`start_time` field in struct FFPlayer in ff_ffplay.c

**Comment by RobinLW** [comment]
应该是完成了链接（完成了文件头解析之类），播放前，seek到某个时间

**Comment by mandagod** [comment]
@RobinLW  是这样的

**Comment by zzjjob** [comment]
After the open_input call  seek_frame immediate

**Comment by mandagod** [comment]
@zzjjob  Let me Try and test it.
