### ISSUE TITLE
Turn audio on/off (Android)

### ISSUE THREAD

**Issue by chrisjenx** [Bilibili/ijkplayer#720]
I was wondering how you enable/disable audio during streaming?

Using the `IjkMediaPlayer`, it will request audio focus regardless if I request it or not in java e.g. `am.requestAudioFocus(null, AudioManager.STREAM_MUSIC, AudioManager.AUDIOFOCUS_GAIN)`.

I know passing `an` will disable audio from ffmpeg. But ideally I would be nice to turn the audio stream on/off at a native level. 
As the only way I can release the audio focus is Restarting the stream with `an = 1`. Is there a way to do this without restarting the stream? (And without just muting the audio focus?)

**Comment by bbcallen** [comment]
No idea about audio focus, ijkplayer doesn't touch AudioManager in native at all.

If you want to disable audio decode/output once and for all, deselectTrack() is a workaround.
But there are some problems when you enable audio again by selectTrack();

If you only want to mute audio, setVolume(), getAudioSessionId() may help a little.
Mostly, AudioManager is enough for me.

**Comment by chrisjenx** [comment]
I think it might be android, even though you're not touching AudioManager natively, I think streaming audio on a native level automatically takes focus. (Or thats what it looks like).

I'll try the trackSelection stuff.

Thanks for your hard work, very much appreciated!

**Comment by chrisjenx** [comment]
OK, Just to update this, seems in 4.4 you can request audio focus correctly. It must of been a bug in the older version I was using. 

What is interesting is that audio seems to be playing too quickly on 4.4. tho.

**Comment by chrisjenx** [comment]
Closing, the fast audio might be an issue with genemotion, I'll try to replicate on another x86 device and raise a new issue if it still exists
