### ISSUE TITLE
Licence question

### ISSUE THREAD

**Issue by Zo2m4bie** [Bilibili/ijkplayer#721]
Hi. I want to ask some question about license. I saw in README that project based on ffmpeg which has LGPL license. But on ffmpeg site I have seen that it has some parts which has GPL license (https://www.ffmpeg.org/doxygen/2.6/md_LICENSE.html). I tried to find which files .sh file (do-compile-ffmpeg.sh) uses when compiles ffmpeg lib , but I couldn't. Can you help me with this? Do you have some of these files in lib?

Text from ffmpeg site:

     Specifically, the GPL parts of FFmpeg are:

     libpostproc
     optional x86 optimizations in the files
     libavcodec/x86/flac_dsp_gpl.asm
      libavcodec/x86/idct_mmx.c
     libutvideo encoding/decoding wrappers in libavcodec/libutvideo*.cpp
     the X11 grabber in libavdevice/x11grab.c
     the swresample test app in libswresample/swresample-test.c
     the texi2pod.pl tool
     the following filters in libavfilter:
     f_ebur128.c
    vf_blackframe.c
    vf_boxblur.c
    vf_colormatrix.c
    vf_cropdetect.c
    vf_delogo.c
    vf_eq.c
    vf_fspp.c
    vf_geq.c 
    vf_histeq.c
    vf_hqdn3d.c
    vf_interlace.c
    vf_kerndeint.c
    vf_mcdeint.c
    vf_mpdecimate.c
    vf_owdenoise.c
    vf_perspective.c
    vf_phase.c
    vf_pp.c
    vf_pp7.c
    vf_pullup.c
    vf_sab.c
    vf_smartblur.c
    vf_repeatfields.c
    vf_spp.c
    vf_stereo3d.c
    vf_super2xsai.c
    vf_tinterlace.c
    vf_uspp.c 
    vsrc_mptestsrc.c

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/config/module-lite.sh

**Comment by Zo2m4bie** [comment]
@bbcallen 
Yes, I saw config file. It contains this strings 

     export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-avcodec"
     export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-avformat"

Does it mean that lib compile all file from libavcodec and libavformat folders?

**Comment by bbcallen** [comment]
```
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-gpl"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-nonfree"
```
