### ISSUE TITLE
Android  0.4.4  ANR

### ISSUE THREAD

**Issue by Asa-Walker** [Bilibili/ijkplayer#722]
复现流程：在   设置播放地址之后，还没有prepared之前，finish activity 出现anr。
在官方demo中测试，同样出现了ANR，log 如下：

LOG:
12-10 15:07:16.756 789-882/? E/ActivityManager: ANR in tv.danmaku.ijk.media.sample (tv.danmaku.ijk.media.sample/.activities.SampleMediaActivity)
                                                Reason: keyDispatchingTimedOut
                                                Load: 10.49 / 10.23 / 9.97
                                                CPU usage from 6976ms to 1963ms ago:
                                                  90% 349/mediaserver: 0% user + 90% kernel / faults: 15 minor
                                                  4.5% 789/system_server: 3.7% user + 0.7% kernel / faults: 663 minor
                                                  3.3% 7814/tv.danmaku.ijk.media.sample: 2.5% user + 0.7% kernel / faults: 561 minor
                                                  2.1% 5112/RX_Thread: 0% user + 2.1% kernel
                                                  1.7% 5111/TX_Thread: 0% user + 1.7% kernel
                                                  1.5% 7532/logcat: 0% user + 1.5% kernel / faults: 8 minor
                                                  1.3% 476/adbd: 0% user + 1.3% kernel
                                                  1.1% 346/surfaceflinger: 0.1% user + 0.9% kernel / faults: 2 minor
                                                  1.2% 10161/logcat: 0.4% user + 0.8% kernel / faults: 8 minor
                                                  0.9% 2992/com.qihoo.daemon: 0.7% user + 0.1% kernel / faults: 123 minor
                                                  0.5% 6929/kworker/u:1: 0% user + 0.5% kernel
                                                  0.6% 9086/kworker/1:1: 0% user + 0.6% kernel
                                                  0.3% 6925/kworker/0:0: 0% user + 0.3% kernel
                                                  0.1% 107/irq/617-LCD_TE: 0% user + 0.1% kernel
                                                  0% 449/cnd: 0% user + 0% kernel
                                                  0.1% 513/mdss_fb0: 0% user + 0.1% kernel
                                                  0.1% 1104/com.android.systemui: 0% user + 0.1% kernel / faults: 5 minor
                                                  0% 3594/com.tencent.mobileqq: 0% user + 0% kernel / faults: 1 minor
                                                  0% 6926/kworker/0:2H: 0% user + 0% kernel
                                                  0.2% 32356/kworker/u:7: 0% user + 0.2% kernel
                                                52% TOTAL: 5% user + 46% kernel + 0.6% softirq
                                                CPU usage from 1742ms to 2262ms later with 99% awake:
                                                  98% 349/mediaserver: 0% user + 98% kernel
                                                    98% 9128/VideoDecCallBac: 0% user + 98% kernel
                                                  7.5% 789/system_server: 3.7% user + 3.7% kernel / faults: 12 minor
                                                    3.7% 882/ActivityManager: 1.8% user + 1.8% kernel
                                                    1.8% 1048/InputReader: 0% user + 1.8% kernel
                                                    1.8% 1303/Binder_8: 1.8% user + 0% kernel
                                                  3% 6414/kworker/u:4: 0% user + 3% kernel
                                                  1.2% 2/kthreadd: 0% user + 1.2% kernel
                                                  1.5% 6926/kworker/0:2H: 0% user + 1.5% kernel
                                                 +0% 9170/workqueue_trust: 0% user + 0% kernel
                                                37% TOTAL: 1.3% user + 36% kernel
12-10 15:07:16.756 449-449/? E/Parcel: Reading a NULL string not supported here.

**Comment by bbcallen** [comment]
Do you mind to paste the content of /data/anr/traces.txt

**Comment by zzjjob** [comment]
maybe block in the network，I have often encountered a similar situation

**Comment by jojoEcho** [comment]
请问一下，这个问题要怎么解决呢？是需要改JNI里面的东西么？

**Comment by Asa-Walker** [comment]
Anr 确实会出现，我的临时做法是把销毁播放器的代码，放在了线程中去做了

**Comment by bbcallen** [comment]
Try set a shorter timeout

**Comment by xiaoyaomeng** [comment]
@Asa-Walker  请问你这样做，如果退出之后 再进入播放呢，这样重复几次。

**Comment by jojoEcho** [comment]
@bbcallen  将timeout设为0，仍然是相同的情况

**Comment by xiaoyaomeng** [comment]
@Asa-Walker 请问你把哪段代码加到了线程中执行？？？这样可以吗？

**Comment by bbcallen** [comment]
Try this branch cab87a3ebd1672896dc8b79a796c0cbf48dd6c4f

**Comment by AricGuo** [comment]
@bbcallen "Try set a shorter timeout"   it's doesn't work.    i stop a IjkVideoView, timeout 1000ms,then start another;

**Comment by AricGuo** [comment]
`Executors.newSingleThreadExecutor().execute(new Runnable() {
           @Override
           public void run() {
               if (mIjkVideoView != null) {
                   try {
//                       mIjkVideoView.resume();
                       mIjkVideoView.stopPlayback();
                       mIjkVideoView.release(true);
                       mIjkVideoView.stopBackgroundPlay();
                   } catch (Exception e) {
                       e.printStackTrace();
                   }
               }
           }
       });`      


i try to do release in a new thread,but it cause a native crash。



`04-19 10:35:36.836 17132-18617/? E/CrashReport: SIGSEGV(SEGV_MAPERR)
                                                0x68
                                                #00    pc 0000d7f4    /data/app/com.chongdingdahui.app-2/lib/arm/libijkplayer.so [armeabi-v7a::8f5088d608075aca03694ee738b4f413]
                                                #01    pc 0000daff    /data/app/com.chongdingdahui.app-2/lib/arm/libijkplayer.so [armeabi-v7a::8f5088d608075aca03694ee738b4f413]
                                                #02    pc 0001134b    /data/app/com.chongdingdahui.app-2/lib/arm/libijkplayer.so (ffp_wait_stop_l+14) [armeabi-v7a::8f5088d608075aca03694ee738b4f413]
                                                #03    pc 00016095    /data/app/com.chongdingdahui.app-2/lib/arm/libijkplayer.so (ijkmp_shutdown_l+28) [armeabi-v7a::8f5088d608075aca03694ee738b4f413]
                                                #04    pc 000194bf    /data/app/com.chongdingdahui.app-2/lib/arm/libijkplayer.so [armeabi-v7a::8f5088d608075aca03694ee738b4f413]
                                                #05    pc 0102148f    /data/app/com.chongdingdahui.app-2/oat/arm/base.odex (oatexec+967823) [armeabi::0d03000000000000f36c0c0000000000]
                                                java:
                                                tv.danmaku.ijk.media.player.IjkMediaPlayer.release(IjkMediaPlayer.java:698)
                                                tv.danmaku.ijk.media.player.media.IjkVideoView.stopPlayback(IjkVideoView.java:277)
                                                com.chongdingdahui.app.dianbo.NormalVideoView$5.run(NormalVideoView.java:204)
                                                java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                java.lang.Thread.run(Thread.java:761)`
