### ISSUE TITLE
Enable/disable video filter "vf0" during playback

### ISSUE THREAD

**Issue by NikmanSergey** [Bilibili/ijkplayer#724]
Is there any posibilty to enable/disable video filter "vf0" during playback? Currently, it applies on preparing.

Also, is it necessary to enable all ffmpeg's filters? I've found that "aresample" filter must be included. But some videos still not showing without including all filters.

**Comment by bbcallen** [comment]
1. Yes, same as deselectTrack() + selectTrack()
2. What do you mean "enable all ffmpeg's filters"?

**Comment by NikmanSergey** [comment]
1) I use this code to activate deinterlacing:
```
mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "vf0", "yadif");
```
but this applies only when set it before playback, but not during playback.

2) I mean:
```
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-avfilter"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-filters"
```
this includes all available filters.

**Comment by bbcallen** [comment]
1. you'll need to implement so-called changeVideoFilters() in IjkMediaPlayer.java by yourself. 
2. isn't it now ?

**Comment by bbcallen** [comment]
BTW: ffp_set_playback_rate() could be an example.

**Comment by NikmanSergey** [comment]
@bbcallen,
Thanks!!!

Did it through *ffp_set_property_int64* by adding:
```
#define FFP_PROP_INT64_DEINT                              20100
```
```
void ffp_set_deint(FFPlayer *ffp, int64_t enable)
{
    if (!ffp)
        return;
 
    SDL_LockMutex(ffp->vf_mutex);
 
    if (ffp->vfilters_list)
        av_freep(&ffp->vfilters_list);
    ffp->nb_vfilters = 0;
    if (enable) {
        GROW_ARRAY(ffp->vfilters_list, ffp->nb_vfilters);
        ffp->vfilters_list[ffp->nb_vfilters - 1] = "yadif";
    }
 
    ffp->vf_changed = 1;
 
    SDL_UnlockMutex(ffp->vf_mutex);
}
```

**Comment by NikmanSergey** [comment]
As for second question, including all filters increases zipped library up to 2 mb. It's not a big problem. But is it really necessary to include all of them?
However, without adding all filters some videos not showing.

**Comment by bbcallen** [comment]
You are free to customize your own config-xxx.sh

**Comment by lijingchang** [comment]
I used his method and found picture come out slower, 3.8M ts stream.
can you fix it？
