### ISSUE TITLE
How to set the playback delay

### ISSUE THREAD

**Issue by adteven** [Bilibili/ijkplayer#725]
I use the IJKpayer for android  to play rtmp stream ,How to set the playback delay.
if I want to set 1s playbuffer time ,how to set the param,

**Comment by dourgulf** [comment]
+1 want to known.

**Comment by bbcallen** [comment]
I want to know, too.

**Comment by adteven** [comment]
@bbcallen 
我用之前的版本有这个接口调用，可以设置ffplay参数，
 ijkMediaPlayer.setAvFormatOption("analyzeduration","2000000"); ijkMediaPlayer.setAvFormatOption("fflags","nobuffer");
 ijkMediaPlayer.setAvFormatOption("probsize","4096");
新版的ijkplayer 用哪个接口设置ffplay参数

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/android/ijkplayer/ijkplayer-java/src/main/java/tv/danmaku/ijk/media/player/IjkMediaPlayer.java#L767

**Comment by adteven** [comment]
category 找个参数怎么写，其他两个我知道，比如"fflags","nobuffer"

**Comment by adteven** [comment]
@bbcallen 
打错字了，category 这个参数怎么设置，我没看到有这个参数的说明和使用例子，所以问下你，谢谢了

**Comment by adteven** [comment]
@bbcallen 
使用ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT,"fflags", "nobuffer");
播放黑屏，那边解决了吗

**Comment by ZhangyuTv** [comment]
there is an 'output_ts_offset' in 'Format Options' of libavformat. is it what you want?

**Comment by adteven** [comment]
@ZhangyuTv  
no ,the param is the encode param,I use it for decoding,

**Comment by adteven** [comment]
@bbcallen 
How to set up to play buffer size，

**Comment by iosnower** [comment]
请问这个问题，最后是怎么解决的？
