### ISSUE TITLE
Audio tracks language tags

### ISSUE THREAD

**Issue by NikmanSergey** [Bilibili/ijkplayer#726]
Adding audio tracks language tags to metadata could be a useful improvement?

**Comment by bbcallen** [comment]
I have no such video sample.

**Comment by NikmanSergey** [comment]
Here is the multi-language sample with 2 audio streams (en/de), and 2 subtitles streams (de/en):
http://wikisend.com/download/284920/hal.zip

Probably, getting language tag may look something like this:
```
AVDictionaryEntry *lang = av_dict_get(st->metadata, "language", NULL, 0);
// lang->value
```

**Comment by bbcallen** [comment]
Fixed: e7368611ded7b56753ebffc4d215a376b328163d

**Comment by NikmanSergey** [comment]
@bbcallen,
Works great!!!

**Comment by 24Lathiya** [comment]
@NikmanSergey @bbcallen Please let me know how to detect audio track and how to set.
Thanks
