### ISSUE TITLE
Android 开启mediacodec 花屏

### ISSUE THREAD

**Issue by xueleitt** [Bilibili/ijkplayer#727]
播放时按home，执行pause停止播放，然后再resume中执行start时候出现花屏，然后过几秒钟就好了，请问是什么原因导致的？

**Comment by xueleitt** [comment]
12-14 18:48:20.900 31243-31243/  D/IJKMEDIA: IjkMediaPlayer_start
12-14 18:48:20.900 31243-31243/  D/IJKMEDIA: ijkmp_start()
12-14 18:48:20.900 31243-31243/  D/IJKMEDIA: ijkmp_start()=0
12-14 18:48:20.900 31243-1579/  D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
12-14 18:48:20.900 31243-1579/  D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START: start on fly
12-14 18:48:20.910 31243-1580/  W/IJKMEDIA: voud_display_overlay_l: NULL native_window
12-14 18:48:20.920 31243-31243/  D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
12-14 18:48:20.920 31243-31243/  D/IJKMEDIA: ijkmp_set_android_surface(surface=0x1590001d)
12-14 18:48:20.920 31243-31243/  D/IJKMEDIA: ffpipeline_set_surface()
12-14 18:48:20.920 31243-31243/  D/IJKMEDIA: ijkmp_set_android_surface(surface=0x1590001d)=void
12-14 18:48:20.920 31243-31243/  D/IJKMEDIA: IjkMediaPlayer_start
12-14 18:48:20.920 31243-31243/  D/IJKMEDIA: ijkmp_start()
12-14 18:48:20.920 31243-1579/  D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
12-14 18:48:20.920 31243-1579/  D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START: start on fly
12-14 18:48:20.920 31243-31243/  D/IJKMEDIA: ijkmp_start()=0
12-14 18:48:20.920 31243-1609/  D/IJKMEDIA: ffpipeline_set_surface_need_reconfigure_l(0)
12-14 18:48:20.930 31243-1607/  I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: INFO_OUTPUT_FORMAT_CHANGED
12-14 18:48:20.930 31243-1607/  I/IJKMEDIA: AMEDIACODEC__INFO_OUTPUT_FORMAT_CHANGED
12-14 18:48:20.930 31243-1607/  D/IJKMEDIA: SDL_AMediaFormatJava_init
12-14 18:48:20.930 31243-1607/  I/IJKMEDIA: AMEDIACODEC__INFO_OUTPUT_FORMAT_CHANGED
                                                              width-height: (480 x 272)
                                                              color-format: (QCOM_FORMATYUV420PackedSemiPlanar32m: 0x7fa30c04)
                                                              stride:       (512)
                                                              slice-height: (288)
                                                              crop:         (0, 0, 479, 271)
12-14 18:48:20.930 31243-1609/  D/IJKMEDIA: SDL_AMediaCodecJava_stop
12-14 18:48:20.930 31243-1580/  W/IJKMEDIA: SDL_VoutAndroid_releaseBufferProxy_l: [2240] ???????? proxy 0: vout: 0 idx: -1 render: true
12-14 18:48:20.930 31243-1580/  W/IJKMEDIA: SDL_VoutAndroid_releaseBufferProxy_l: [2239] ???????? proxy 0: vout: 0 idx: -1 render: false
12-14 18:48:20.940 31243-1580/  W/IJKMEDIA: SDL_VoutAndroid_releaseBufferProxy_l: [2241] ???????? proxy 0: vout: 0 idx: -1 render: true
12-14 18:48:20.940 31243-1609/  I/IJKMEDIA: quirk: reconfigure with new codec
12-14 18:48:20.940 31243-1609/  I/IJKMEDIA: SDL_AMediaCodecJava_delete
12-14 18:48:20.950 31243-1609/  D/IJKMEDIA: SDL_AMediaCodecJava_createByCodecName
12-14 18:48:20.960 31243-1609/  D/IJKMEDIA: SDL_AMediaCodecJava_init
12-14 18:48:20.960 31243-1609/  D/IJKMEDIA: SDL_AMediaCodecJava_configure_surface
12-14 18:48:20.960 31243-1609/  E/IJKMEDIA: configure acodec:0x20a0060a format:0x1d2005f2: surface:0x1d60059e
12-14 18:48:20.970 31243-1609/  D/IJKMEDIA: SDL_AMediaCodecJava_start
12-14 18:48:20.980 31243-1609/  I/IJKMEDIA: reconfigure_codec_l:new acodec: 0x80958ec8
12-14 18:48:22.020 31243-1607/  I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: INFO_OUTPUT_FORMAT_CHANGED
12-14 18:48:22.020 31243-1607/  I/IJKMEDIA: AMEDIACODEC__INFO_OUTPUT_FORMAT_CHANGED
12-14 18:48:22.030 31243-1607/  D/IJKMEDIA: SDL_AMediaFormatJava_init
12-14 18:48:22.030 31243-1607/  I/IJKMEDIA: AMEDIACODEC__INFO_OUTPUT_FORMAT_CHANGED
                                                              width-height: (480 x 272)
                                                              color-format: (QCOM_FORMATYUV420PackedSemiPlanar32m: 0x7fa30c04)
                                                              stride:       (512)
                                                              slice-height: (288)
                                                              crop:         (0, 0, 479, 271)

**Comment by bbcallen** [comment]
Recreation of SurfaceView causes recreation of MediaCodec.

**Comment by xueleitt** [comment]
what does this mean? How to fix it ?

**Comment by Android4MediaPlayer** [comment]
@bbcallen check key frame?

**Comment by Android4MediaPlayer** [comment]
#825

**Comment by hljstardust** [comment]
how to resolve the problem?

**Comment by Somony** [comment]
> 播放时按home，执行pause停止播放，然后再resume中执行start时候出现花屏，然后过几秒钟就好了，请问是什么原因导致的？

@xueleitt 请问你这个问题是怎么解决的呢？我现在遇到了和你一样的问题，而且在花屏之后延迟还边变高了，想请教下有指导意见吗？
