### ISSUE TITLE
Desynchronizing audio and video if audio track changed

### ISSUE THREAD

**Issue by don11995** [Bilibili/ijkplayer#728]
Question is a title. How I can fix this? If I use seekTo after setTrackSelected synchronization s normal. Android/ IJKPlayer.

**Comment by bbcallen** [comment]
This is an experimental feature, I don't have plan for it, recently.
Force a seekTo() seems an only workaround for now.

**Comment by bbcallen** [comment]
Or reduce DEFAULT_MIN_FRAMES in ff_ffplay_def.h to reduce native buffer size.
