### ISSUE TITLE
缺少libijkplayer.so, libijksdl.so

### ISSUE THREAD

**Issue by vinceycy** [Bilibili/ijkplayer#730]
您好，我用k0.4.4.1 build完後發現在libijkffmpeg.so的資料夾下沒有libijkplayer.so, libijkdsl.so二個檔案的存在，是在build的時候缺少了什麼嗎？

**Comment by bbcallen** [comment]
What message did you get after run
```
sh compile-ijkplayer.sh all
```

**Comment by vinceycy** [comment]
sorry, 我少執行 compile-ijkplayer.sh all
