### ISSUE TITLE
IJKFFMoviePlayerController 的bufferingProgress 不准确

### ISSUE THREAD

**Issue by wanpiaoyi** [Bilibili/ijkplayer#731]
我用IJKFFMoviePlayerController 播放一段m3u8的视频，bufferingProgress值一直在变大，断网后bufferingProgress又不变了。怎么获取缓冲进度呢？

**Comment by wanpiaoyi** [comment]
播放m3u8视频，一旦碰到网络有问题的情况，直接导致播放器卡死，重新初始化也没有用，这个怎么解决呢？

**Comment by bbcallen** [comment]
No guarantee for precision of bufferingProgress
