### ISSUE TITLE
[Android] Video Framrate change

### ISSUE THREAD

**Issue by a4tech** [Bilibili/ijkplayer#735]
Hello,

I have an question, I have some mpegts file format which has issue: video and audio bitrate detected by the player are ~~12 fps - it means it is not smooth playback. Other are fine and plays well.

I tested by ffplay at PC and both plays well.

Can I force to set PES on them to get it arodun ~23 FPS ?

**Comment by bbcallen** [comment]
search skip_frame

**Comment by a4tech** [comment]
Hi,

I looked at it, and it only exist in ff_play.c

I found this:

https://trac.ffmpeg.org/wiki/How%20to%20speed%20up%20/%20slow%20down%20a%20video

but it does not helps me much.

Thanks for any tip.

**Comment by a4tech** [comment]
@bbcallen 

could you give me some tip how do You pass some arguments to ffmpeg ?

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/ios/IJKMediaPlayer/IJKMediaPlayer/IJKFFOptions.m#L51

**Comment by a4tech** [comment]
yes that's right for iOS, but possiable values for android are quite hard to find:

ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_frame", ????????);

**Comment by bbcallen** [comment]
https://ffmpeg.org/ffmpeg-codecs.html
