### ISSUE TITLE
duration calculate issue

### ISSUE THREAD

**Issue by RobinLW** [Bilibili/ijkplayer#736]
hi, why the video duration time substracted by the video start time. when i call the getduration api, the duration IJKPlayer returned is different from the duration that iphone mediaplayer showed for some m3u8 video.  I found that the starttime is not zero in this case. so, can i using the duration directly without substrating the starttime.

**Comment by bbcallen** [comment]
You are free to modify ff_ffplay.c to meet your needs.

**Comment by RobinLW** [comment]
thks. But why you substract the starttime from the duration, I'm a lot confused....

**Comment by bbcallen** [comment]
Long long ago, ffmpeg's m3u8 implement need this fix.
I don't remember when they fixed this issue.

**Comment by RobinLW** [comment]
ok, thks for your sharing!!!
