### ISSUE TITLE
为了精确定位hls哪一个资源有问题，我在手机建了一个本地服务，中转get请求

### ISSUE THREAD

**Issue by lyqaiym** [Bilibili/ijkplayer#742]
用的Apache的HttpServer，android原生的播放器可以正常播放，但是你们的这个，不请求key。
#EXT-X-KEY:METHOD=AES-128,URI="video.key"是这样的
在http.c中http_open方法，我打了log，他都没请求，应该是没有拼接
所以我试着改成全部路径，然后在http.c的http_open_cnx方法中
location_changed = http_open_cnx_internal(h, options);
s->http_code=0
location_changed=-541478725了。
其实还是没有请求。

**Comment by bbcallen** [comment]
Build openssl first.

**Comment by lyqaiym** [comment]
用openssl的，如果先把key保存下来，改成文件路径，就可以得到key了

**Comment by bbcallen** [comment]
I mean build ijkplayer with OpenSSL.

**Comment by lyqaiym** [comment]
是啊，我用的librtmp，--enable-openssl"

**Comment by lyqaiym** [comment]
在http的static int http_connect()方法中的
err = http_read_header(h, new_location);
产生错误了。
static int http_read_header()中的http_get_line
http_get_line的ch = http_getc(s);
static int http_getc()中
len = ffurl_read(s->hd, s->buffer, BUFFER_SIZE);
这个地方len=0所以出错了

**Comment by bbcallen** [comment]
Since you have digged so far, why don't you find out why key-url is not requested?
Actually, I don't have more knowledge than you about crypted HLS.

**Comment by lyqaiym** [comment]
我找到一个产生的地方，但还没有找到原因
hls.c的static int open_input(HLSContext *c, struct playlist *pls)
方法open_url改回原来的ffurl_open就行了。
