### ISSUE TITLE
YV12 error on some format

### ISSUE THREAD

**Issue by weyless** [Bilibili/ijkplayer#743]
I tried to play some video by YV12.
video 1 720x576 [SAR 16:15 DAR 4:3]  turned grey with some strange lines.
video 1 scaled to  720x540 [SAR 1:1 DAR 4:3]  same as video 1.
video 1 scaled to  1280x720 [SAR 1:1 DAR 16:9]  a flicker at the beginning then normal.
video 2 1280x720 [SAR 1:1 DAR 16:9]  a flicker at the beginning then normal.
video 2 scaled to 720x576 [SAR 64:45 DAR 16:9] crush.

so it seems that whether YV12 can be used partly depends on the pixel scale. how did it happen？
Do you have a plane to fix it or have some hits for me to try to fix it?

**Comment by bbcallen** [comment]
Android or iOS?

**Comment by weyless** [comment]
android ,multiple device.

**Comment by bbcallen** [comment]
Actually, YV12 is not a documented feature of Android.
It's not supported by all devices.

See header file in NDK
<android/native_window.h>
