### ISSUE TITLE
ijkplay如何加速播放

### ISSUE THREAD

**Issue by adteven** [Bilibili/ijkplayer#744]
请教下，如何让ijkplayer加速播放，FrameQueue pictq;就是把这个队里的数据尽快播放掉

**Comment by bbcallen** [comment]
frame_queue_next()

**Comment by martji** [comment]
Is there any useable APIs to set the parameter in IjkMediaPlayer?

**Comment by hiplayer** [comment]
感觉只有自己加接口，android原生没有这个接口。而且快进要考虑各种情况，什么网络播放，本地播放，有没有关键帧等问题。
