### ISSUE TITLE
Android scale mode

### ISSUE THREAD

**Issue by linked67** [Bilibili/ijkplayer#747]
Hi,

Is there a scale mode on android like on ios were we can use UIViewContentModeScaleAspectFit ?
I just have found a complex way where i must do the math myself when screen change.

**Comment by bbcallen** [comment]
You could copy the implement from MeasureHelper.java in sample project

**Comment by linked67** [comment]
Yes, if i copy the whole widget folder and tweak it a bit it works.
But the goal was to have a simple view with only video, no hud or control, just a video view.

For the moment i have a SurfaceView and I use mIjkMediaPlayer.setDisplay(surfaceView.getHolder());
It's very minimal and it work. If i add MeasureHelper.java, i probably have to add other widgets too, no ?

Or maybe you mean i can copy some math from MeasureHelper.java inside my Activity ?

**Comment by bbcallen** [comment]
You can copy some math from MeasureHelper.java into your Activity.
