### ISSUE TITLE
Help needed with ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, <key>, <value>);

### ISSUE THREAD

**Issue by msdos2** [Bilibili/ijkplayer#748]
Could you please explain me how to use setOption to accomplish what's done with IAvFormatOption?
I haven't been able to do it myself. I get an error:

ple I/IJKMEDIA: ===== options =====
09-15 10:59:43.856 1481-1481/tv.danmaku.ijk.media.sample I/IJKMEDIA: player-opts : mediacodec = 1
09-15 10:59:43.856 1481-1481/tv.danmaku.ijk.media.sample I/IJKMEDIA: player-opts : mediacodec-auto-rotate = 1
09-15 10:59:43.856 1481-1481/tv.danmaku.ijk.media.sample I/IJKMEDIA: player-opts : opensles = 0
09-15 10:59:43.856 1481-1481/tv.danmaku.ijk.media.sample I/IJKMEDIA: player-opts : overlay-format = 842225234
09-15 10:59:43.856 1481-1481/tv.danmaku.ijk.media.sample I/IJKMEDIA: player-opts : framedrop = 1
09-15 10:59:43.856 1481-1481/tv.danmaku.ijk.media.sample I/IJKMEDIA: player-opts : start-on-prepared = 0
09-15 10:59:43.856 1481-1481/tv.danmaku.ijk.media.sample I/IJKMEDIA: format-opts : ijkinject-opaque = 1049890

How should I instantiate ijkMediaPlayer to use setOption?

Thanks in advance,

**Comment by mandagod** [comment]
@msdos2 
Pls check the sample Demo of ijkplayer, In VideoView.java, when the type of MediaPlayer is ijkplayer, in CreatePlayer Function, will set the options.

**Comment by msdos2** [comment]
IjkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtmp_app", "privatestream");
        IjkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtmp_playpath", "sundance95?keys=FGpGnK9bwD-4tp_X5ZKWeA&keyt=1448254246");
        IjkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtmp_pageurl","http://privatestream.tv/js/jwplayer.flash.swf");
        //IjkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtmp_swfurl", "http://privatestream.tv/");
