### ISSUE TITLE
更新ijkplayer框架编译出错

### ISSUE THREAD

**Issue by ZHDeveloper** [Bilibili/ijkplayer#749]
项目中使用旧版本的ijk框架编译正常，但昨天更新ijkplayer框架时编译出错：
Undefined symbols for architecture x86_64:
  "_IJKMediaPlaybackIsPreparedToPlayDidChangeNotification", referenced from:
      -[MediaControl installMovieNotificationObservers] in MediaControl.o
      -[MediaControl removeMovieNotificationObservers] in MediaControl.o
  "_IJKMoviePlayerLoadStateDidChangeNotification", referenced from:
      -[MediaControl installMovieNotificationObservers] in MediaControl.o
      -[MediaControl removeMovieNotificationObservers] in MediaControl.o
  "_IJKMoviePlayerPlaybackDidFinishNotification", referenced from:
      -[MediaControl installMovieNotificationObservers] in MediaControl.o
      -[MediaControl removeMovieNotificationObservers] in MediaControl.o
  "_IJKMoviePlayerPlaybackStateDidChangeNotification", referenced from:
      -[MediaControl installMovieNotificationObservers] in MediaControl.o
      -[MediaControl removeMovieNotificationObservers] in MediaControl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

没有添加某个库文件吗？

**Comment by xiaoyaomeng** [comment]
@ZHDeveloper 可以参考下我写的编译教程博文，我前天刚按照原来的博文编过，是可以的http://blog.csdn.net/ljphhj/article/details/47421413
