### ISSUE TITLE
How should I import ijkplayer sdk for my ios project correctly?

### ISSUE THREAD

**Issue by aquaibm** [Bilibili/ijkplayer#750]
As the iOS guide told, I've compiled project successfully, now what exactly should I do as next step?
I've seen the following message but I don't quite get it, could it be more specific? A little help would be appreciated. 

 import ios/IJKMediaPlayer for MediaPlayer.framework-like interface (recommended)
 open ios/IJKMediaDemo/IJKMediaDemo.xcodeproj with Xcode

**Comment by bbcallen** [comment]
https://developer.apple.com/library/ios/technotes/iOSStaticLibraries/Introduction.html#//apple_ref/doc/uid/TP40012554-CH1-SW1

**Comment by mistak** [comment]
add ijkplayer 、build、ijkmedia、framework，
then add -fno-objc-arc for some files like IJKPlayerDemo 
build IJKplayer
