### ISSUE TITLE
skip_loop_filter和skip_frame

### ISSUE THREAD

**Issue by playererer** [Bilibili/ijkplayer#753]
/**
     * Skip loop filtering for selected frames.
     * - encoding: unused
     * - decoding: Set by user.
     */
    enum AVDiscard skip_loop_filter;

    /**
     * Skip decoding for selected frames.
     * - encoding: unused
     * - decoding: Set by user.
     */
    enum AVDiscard skip_frame;

请问一下这两个参数的具体含义，从注释里面没看明白，
**skip_loop_filter：48**  是指选中的48帧不进行环路滤波吗？这是怎么选的呢？
**skip_frame：8** 是指在解码性能不足的情况下跳过选中的8帧不解吗？还是其他的含义呢？

麻烦知道的帮忙解答一下，谢谢！

**Comment by weyless** [comment]
https://www.ffmpeg.org/ffplay-all.html 
(search skip_loop_filter)
https://www.ffmpeg.org/doxygen/trunk/group__lavc__decoding.html 
(search AVDISCARD)

**Comment by playererer** [comment]
非常感谢！

**Comment by DysaniazzZ** [comment]
As the [ffplay Document](https://www.ffmpeg.org/ffplay-all.html) says: `skip_frame` means skips decoding, and `skip_loop_filter` means skips frame loop filtering. And the value is below:

```
IJK_AVDISCARD_NONE = -16, discard nothing;
IJK_AVDISCARD_DEFAULT = 0, discard useless packets like 0 size packets in avi;
IJK_AVDISCARD_NONREF = 8, discard all non reference;
IJK_AVDISCARD_BIDIR = 16, discard all bidirectional frames;
IJK_AVDISCARD_NONKEY = 32, discard all frames except keyframes;
IJK_AVDISCARD_ALL = 48, discard all;
```
