### ISSUE TITLE
横竖屏切换的问题

### ISSUE THREAD

**Issue by dongchao** [Bilibili/ijkplayer#757]
你好，我在使用ijkPlayer时需要横竖屏切换，横屏时全屏播放，竖屏时半屏播放，通过setLayoutParams改变VideoView的大小，在红米Note2上面可以正常执行，在三星9300上面不起作用，视频还是原大小。请问如何处理？IMediaplayer可以设置分辨率吗？

**Comment by bbcallen** [comment]
override onMeasure()
