### ISSUE TITLE
av_read_frame error: fffffffb(\377,\377,\377,\373): unknown

### ISSUE THREAD

**Issue by zwy2937** [Bilibili/ijkplayer#758]
xcode console log this after play errored....what does this mean?how can i solve this problem

**Comment by bbcallen** [comment]
Nothing you can do, for now.
Just create a new player object an seek to last played position.

**Comment by zwy2937** [comment]
seek to last player position ? i have no idea to do .... :)

**Comment by Noiled** [comment]
@bbcallen that means restart the player ?

**Comment by sofifather** [comment]
create a new object was  very helpful solution.

**Comment by limbo0312** [comment]
暂停后，重新播放确实问题蛮多的
2016-08-30 15:34:27.055 IJKMediaDemo[12071:2318847] IJKMPMoviePlayBackStateDidChange 2: paused
[FFPlayer @ 0x7f90e5b99910] av_read_frame error: fffffffb(\377,\377,\377,\373): unknown
[FFPlayer @ 0x7f90e5b99910] av_read_frame error: fffffffb(\377,\377,\377,\373): unknown
[FFPlayer @ 0x7f90e5b99910] av_read_frame error: fffffffb(\377,\377,\377,\373): unknown
[FFPlayer @ 0x7f90e5b99910] av_read_frame error: fffffffb(\377,\377,\377,\373): unknown
[FFPlayer @ 0x7f90e5b99910] av_read_frame error: fffffffb(\377,\377,\377,\373): unknown
[FFPlayer @ 0x7f90e5b99910] av_read_frame error: fffffffb(\377,\377,\377,\373): unknown
[FFPlayer @ 0x7f90e5b99910] av_read_frame error: fffffffb(\377,\377,\377,\373): unknown
[FFPlayer @ 0x7f90e5b99910] av_read_frame error: fffffffb(\377,\377,\377,\373): unknown
[FFPlayer @ 0x7f90e5b99910] av_read_frame error: fffffffb(\377,\377,\377,\373): unknown
[FFPlayer @ 0x7f90e5b99910] av_read_frame error: fffffffb(\377,\377,\377,\373): unknown
[FFPlayer @ 0x7f90e5b99910] av_read_frame error: fffffffb(\377,\377,\377,\373): unknown
