### ISSUE TITLE
how to change URL when ijkplayer is playing RTMP video

### ISSUE THREAD

**Issue by zwy2937** [Bilibili/ijkplayer#759]
e...IJKFFMoviePlayerController is given a URL when init it ,but i want to change the URL after init ....how to do?

**Comment by bbcallen** [comment]
Create new player.

**Comment by zwy2937** [comment]
how to release the older player ? call  shutdown method  and let older player = nil ?

**Comment by bbcallen** [comment]
Yes

**Comment by zwy2937** [comment]
but after do this ,the memory use is still the same as before....

**Comment by bbcallen** [comment]
Did you shutdown the previous player, and remove player.view from parent view?

**Comment by zwy2937** [comment]
yeah .i do all this .first remove the preview of older player ,then shutdown and let it = nil ..

**Comment by zwy2937** [comment]
@property (atomic, retain) IJKFFMoviePlayerController *mediaPlayer;
this is the player 

[_mediaPlayer shutdown];
    [_mediaPlayer.view removeFromSuperview];
    if (_mediaPlayer != nil) {
        _mediaPlayer.tcpOpenDelegate = nil;
        _mediaPlayer = nil;
    }
and this is the action to release player ...after do this the memory use doesn't cut down

**Comment by shingwasix** [comment]
Are you using MRC mode?

**Comment by shingwasix** [comment]
If your project is using MRC mode,you should release the player like that
```
[_mediaPlayer  release];
_mediaPlayer = nil;
```
or
```
self.mediaPlayer = nil;
```
