### ISSUE TITLE
请问播放器有静音的接口，ios横竖屏切换

### ISSUE THREAD

**Issue by chenliming777** [Bilibili/ijkplayer#760]
1）请问播放器有静音的接口吗，我看到ff_play接口里面VideoState这个里面有muted，上层怎样调用啊
2）ios横竖屏切换contentMode设置为IJKMPMovieScalingModeAspectFit，然后从竖屏转横批会先缩小一下然后再旋转（强制旋转）

**Comment by bbcallen** [comment]
1. I haven't tested that field.
2. Not sure what do you want. Seems like a UI issue, no a player issue.

**Comment by chenliming777** [comment]
ok   very thanks

**Comment by wangrenzhu** [comment]
2.  We have same problem. Seems like SDL issue

**Comment by chenliming777** [comment]
我的这个问题  目前不设置IJKMPMovieScalingModeAspectFit   这设置frame来解决了，自己计算宽高比，但本质没有解决
