### ISSUE TITLE
前辈，我想打成一个apk，但是报错了

### ISSUE THREAD

**Issue by xiaoyuanandroid** [Bilibili/ijkplayer#762]
前辈您好，又来麻烦您了，我改了改UI，想打成一个apk，android的项目目录什么都没变，只是编译成so包了，但是我现在只有一混淆就报错，不混淆就没事，
 Process: tv.danmaku.ijk.media.sample, PID: 5431
    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app-lib/tv.danmaku.ijk.media.sample-2/libijksdl.so"
爆得这个错误。前辈，你们有没有什么混淆的代码啊！

**Comment by dazhiyu** [comment]
我现在也遇到这种情况，你是怎么解决的啊？
