### ISSUE TITLE
在sdk中找不到MediaDataSource

### ISSUE THREAD

**Issue by mcshengInworking** [Bilibili/ijkplayer#763]
import android.media.MediaDataSource;
提示出错

**Comment by bbcallen** [comment]
Upgrade your android SDK.

**Comment by mcshengInworking** [comment]
MediaDataSource在sdk api 23中才有，低版本的sdk，比如19，那应该怎样处理

**Comment by bbcallen** [comment]
Remove it.

**Comment by mcshengInworking** [comment]
thank you , i try

**Comment by xiangding1983** [comment]
@mcshengInworking 
你在19的版本怎么处理的？ 
我在22版本混淆报错：

Warning:u.aly.bt: can't find referenced method 'int checkSelfPermission(java.lang.String)' in library class android.content.Context
Error:Execution failed for task ':app:shrinkAll32ReleaseMultiDexComponents'.
