### ISSUE TITLE
播放器发生错误后，重新播放BUG

### ISSUE THREAD

**Issue by Asa-Walker** [Bilibili/ijkplayer#764]
设置播放URL后，开始播放，播放过程中，发生错误，播放器重新开始播放。
LOG：
12-22 19:15:19.144: D/IJKMEDIA(22325): IjkMediaPlayer_native_profileBegin
12-22 19:15:19.145: W/IJKMEDIA(22325): monstartup already called
12-22 19:15:19.145: D/IJKMEDIA(22325): IjkMediaPlayer_native_setLogLevel(5)
12-22 19:15:19.145: D/IJKMEDIA(22325): moncleanup
12-22 19:15:21.018: D/IJKMEDIA(22325): IjkMediaPlayer_native_setup
12-22 19:15:21.018: D/IJKMEDIA(22325): ffpipeline_create_from_android()
12-22 19:15:21.018: D/IJKMEDIA(22325): ijkmp_set_inject_opaque(0x20060a)
12-22 19:15:21.018: D/IJKMEDIA(22325): ijkmp_set_inject_opaque()=void
12-22 19:15:21.018: D/IJKMEDIA(22325): ijkmp_android_set_mediacodec_select_callback()
12-22 19:15:21.018: D/IJKMEDIA(22325): ffpipeline_set_mediacodec_select_callback
12-22 19:15:21.018: D/IJKMEDIA(22325): ijkmp_android_set_mediacodec_select_callback()=void
12-22 19:15:21.018: D/IJKMEDIA(22325): IjkMediaPlayer_setOptionLong
12-22 19:15:21.018: D/IJKMEDIA(22325): IjkMediaPlayer_setOptionLong
12-22 19:15:21.018: D/IJKMEDIA(22325): IjkMediaPlayer_setOptionLong
12-22 19:15:21.018: D/IJKMEDIA(22325): IjkMediaPlayer_setOptionLong
12-22 19:15:21.018: D/IJKMEDIA(22325): IjkMediaPlayer_setOptionLong
12-22 19:15:21.018: D/IJKMEDIA(22325): IjkMediaPlayer_setOptionLong
12-22 19:15:21.018: D/IJKMEDIA(22325): IjkMediaPlayer_setOptionLong
12-22 19:15:21.018: D/IJKMEDIA(22325): IjkMediaPlayer_setOptionLong
12-22 19:15:21.018: D/IJKMEDIA(22325): IjkMediaPlayer_setOptionLong
12-22 19:15:21.019: D/IJKMEDIA(22325): IjkMediaPlayer_setDataSourceAndHeaders
12-22 19:15:21.019: V/IJKMEDIA(22325): setDataSource: path http://bee.feixiong.tv/Public/ffconcat/2015/12/22/434680.concat
12-22 19:15:21.019: D/IJKMEDIA(22325): ijkmp_set_data_source(url="http://bee.feixiong.tv/Public/ffconcat/2015/12/22/434680.concat")
12-22 19:15:21.019: D/IJKMEDIA(22325): ijkmp_set_data_source(url="http://bee.feixiong.tv/Public/ffconcat/2015/12/22/434680.concat")=0
12-22 19:15:21.019: D/IJKMEDIA(22325): IjkMediaPlayer_setVideoSurface
12-22 19:15:21.019: D/IJKMEDIA(22325): ijkmp_set_android_surface(surface=0x7fe67c2fa8)
12-22 19:15:21.019: D/IJKMEDIA(22325): ffpipeline_set_surface()
12-22 19:15:21.019: D/IJKMEDIA(22325): ijkmp_set_android_surface(surface=0x7fe67c2fa8)=void
12-22 19:15:21.019: D/IJKMEDIA(22325): IjkMediaPlayer_prepareAsync
12-22 19:15:21.019: D/IJKMEDIA(22325): ijkmp_prepare_async()
12-22 19:15:21.019: I/IJKMEDIA(22325): SDL_RunThread: [23245] ff_msg_loop
12-22 19:15:21.019: D/IJKMEDIA(22325): message_loop
12-22 19:15:21.020: D/IJKMEDIA(22325): FFP_MSG_FLUSH:
12-22 19:15:21.022: D/IJKMEDIA(22325): ijkmp_prepare_async()=0
12-22 19:15:21.022: I/IJKMEDIA(22325): SDL_RunThread: [23247] ff_read
12-22 19:15:21.022: I/IJKMEDIA(22325): SDL_RunThread: [23246] ff_vout
12-22 19:15:21.336: E/IJKMEDIA(22325): Option ijkinject-opaque not found.
12-22 19:15:21.382: I/IJKMEDIA(22325): SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
12-22 19:15:21.382: I/IJKMEDIA(22325): SDL_Android_AudioTrack: ENCODING_PCM_16BIT
12-22 19:15:21.384: I/IJKMEDIA(22325): SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(1.000000,0.000000)
12-22 19:15:21.385: I/IJKMEDIA(22325): audio_session_id = 634
12-22 19:15:21.385: I/IJKMEDIA(22325): SDL_RunThread: [23259] ff_audio_dec
12-22 19:15:21.386: I/IJKMEDIA(22325): SDL_RunThread: [23258] ff_aout_android
12-22 19:15:21.392: W/IJKMEDIA(22325): fps: 25.000000 (normal)
12-22 19:15:21.392: W/IJKMEDIA(22325): fps: 25.000000 (normal)
12-22 19:15:21.392: I/IJKMEDIA(22325): SDL_RunThread: [23267] ff_video_dec
12-22 19:15:21.394: D/IJKMEDIA(22325): FFP_MSG_VIDEO_SIZE_CHANGED: 960, 720
12-22 19:15:21.394: D/IJKMEDIA(22325): FFP_MSG_SAR_CHANGED: 1, 1
12-22 19:15:21.394: D/IJKMEDIA(22325): ijkmp_get_msg: FFP_MSG_PREPARED
12-22 19:15:21.394: D/IJKMEDIA(22325): FFP_MSG_PREPARED:
12-22 19:15:21.498: D/IJKMEDIA(22325): IjkMediaPlayer_start
12-22 19:15:21.498: D/IJKMEDIA(22325): ijkmp_start()
12-22 19:15:21.498: D/IJKMEDIA(22325): ijkmp_start()=0
12-22 19:15:21.498: D/IJKMEDIA(22325): ijkmp_get_msg: FFP_REQ_START
12-22 19:15:21.499: D/IJKMEDIA(22325): IjkMediaPlayer_seekTo
12-22 19:15:21.499: D/IJKMEDIA(22325): ijkmp_seek_to(27108)
12-22 19:15:21.499: D/IJKMEDIA(22325): ijkmp_seek_to(27108)=0
12-22 19:15:21.499: D/IJKMEDIA(22325): ijkmp_get_msg: FFP_REQ_SEEK
12-22 19:15:21.592: D/IJKMEDIA(22325): ijkmp_get_msg: FFP_REQ_START
12-22 19:15:21.592: D/IJKMEDIA(22325): FFP_MSG_BUFFERING_START:
12-22 19:15:22.181: D/IJKMEDIA(22325): ijkmp_get_msg: FFP_MSG_SEEK_COMPLETE
12-22 19:15:22.182: D/IJKMEDIA(22325): FFP_MSG_SEEK_COMPLETE:
12-22 19:15:22.605: E/IJKMEDIA(22325): element type mismatch 1 != 0
12-22 19:15:22.616: E/IJKMEDIA(22325): element type mismatch 1 != 0
12-22 19:15:22.617: E/IJKMEDIA(22325): element type mismatch 1 != 0
12-22 19:15:23.632: D/IJKMEDIA(22325): SDL_VoutFFmpeg_CreateOverlay(w=960, h=720, fmt=RV32(0x32335652, dp=0x7f598ed930)
12-22 19:15:23.633: D/IJKMEDIA(22325): FFP_MSG_VIDEO_SIZE_CHANGED: 960, 720
12-22 19:15:23.637: D/IJKMEDIA(22325): Video: first frame decoded
12-22 19:15:23.638: D/IJKMEDIA(22325): SDL_VoutFFmpeg_CreateOverlay(w=960, h=720, fmt=RV32(0x32335652, dp=0x7f598ed930)
12-22 19:15:23.638: D/IJKMEDIA(22325): FFP_MSG_VIDEO_SIZE_CHANGED: 960, 720
12-22 19:15:23.648: D/IJKMEDIA(22325): SDL_VoutFFmpeg_CreateOverlay(w=960, h=720, fmt=RV32(0x32335652, dp=0x7f598ed930)
12-22 19:15:23.651: D/IJKMEDIA(22325): FFP_MSG_VIDEO_SIZE_CHANGED: 960, 720
12-22 19:15:24.229: D/IJKMEDIA(22325): FFP_MSG_BUFFERING_END:
12-22 19:15:24.236: D/IJKMEDIA(22325): avcodec/Audio: first frame decoded
12-22 19:15:24.236: D/IJKMEDIA(22325): FFP_MSG_AUDIO_RENDERING_START:
12-22 19:15:24.239: D/IJKMEDIA(22325): ANativeWindow_setBuffersGeometry: w=960, h=720, f=(0x4) => w=960, h=720, f=RV32(0x32335652)
12-22 19:15:24.245: D/IJKMEDIA(22325): FFP_MSG_VIDEO_RENDERING_START:
12-22 19:16:12.723: E/IJKMEDIA(22325): element type mismatch 1 != 0
12-22 19:19:07.367: E/IJKMEDIA(22325): element type mismatch 1 != 0
12-22 19:22:05.993: W/IJKMEDIA(22325): HTTP error 403 Forbidden
12-22 19:22:05.994: E/IJKMEDIA(22325): Impossible to open 'http://k.youku.com/player/getFlvPath/sid/645078171143720dce006_03/st/flv/fileid/0300010F0356788D0348A4055F8666380FAC08-2C9F-4E63-9DCE-7894559E9834?K=7108def75cc224cc282b0b64&hd=2&ts=180&r=/3sLngL0Q6CXymAIiF9JUfR5MDecwxp/gSVk/o8apWJ3KUkaGrqktKh7cO9ZZoqYN5iGQUM9dNrj6YzDV+fl4I/W/n4xRf3Uld5UKVC3gyJwtI4mHkDspyot4fn+kqNtVlkal2/4oLB5jVQdDQTk4Koiee/VjpMkQyKQmzXb5+8=&oip=3395594126&sid=645078171143720dce006&token=7758&did=ebb58103ea12d3269c9e1faeb9ea6731&ev=1&ctype=20&ep=MfdYWAqOiXZYbuBR3yPHWFThHMx89bXVFg9Km%2FOSKsV4G6HD296AzlyZ%2F8Di%2FRd1mnM%2FkBl5UgTPEqxO8HjHaXEetU7TerhecfJo2PNTtcl00yvDaMRAVRryMiswySO7'
12-22 19:22:05.994: W/IJKMEDIA(22325): open_next_file() failed (1)
12-22 19:22:06.012: W/IJKMEDIA(22325): HTTP error 403 Forbidden
12-22 19:22:06.012: E/IJKMEDIA(22325): Impossible to open 'http://k.youku.com/player/getFlvPath/sid/645078171143720dce006_03/st/flv/fileid/0300010F0356788D0348A4055F8666380FAC08-2C9F-4E63-9DCE-7894559E9834?K=7108def75cc224cc282b0b64&hd=2&ts=180&r=/3sLngL0Q6CXymAIiF9JUfR5MDecwxp/gSVk/o8apWJ3KUkaGrqktKh7cO9ZZoqYN5iGQUM9dNrj6YzDV+fl4I/W/n4xRf3Uld5UKVC3gyJwtI4mHkDspyot4fn+kqNtVlkal2/4oLB5jVQdDQTk4Koiee/VjpMkQyKQmzXb5+8=&oip=3395594126&sid=645078171143720dce006&token=7758&did=ebb58103ea12d3269c9e1faeb9ea6731&ev=1&ctype=20&ep=MfdYWAqOiXZYbuBR3yPHWFThHMx89bXVFg9Km%2FOSKsV4G6HD296AzlyZ%2F8Di%2FRd1mnM%2FkBl5UgTPEqxO8HjHaXEetU7TerhecfJo2PNTtcl00yvDaMRAVRryMiswySO7'
12-22 19:22:06.012: W/IJKMEDIA(22325): open_next_file() failed (2)
12-22 19:22:06.154: W/IJKMEDIA(22325): HTTP error 403 Forbidden
12-22 19:22:06.155: E/IJKMEDIA(22325): Impossible to open 'http://k.youku.com/player/getFlvPath/sid/645078171143720dce006_03/st/flv/fileid/0300010F0356788D0348A4055F8666380FAC08-2C9F-4E63-9DCE-7894559E9834?K=7108def75cc224cc282b0b64&hd=2&ts=180&r=/3sLngL0Q6CXymAIiF9JUfR5MDecwxp/gSVk/o8apWJ3KUkaGrqktKh7cO9ZZoqYN5iGQUM9dNrj6YzDV+fl4I/W/n4xRf3Uld5UKVC3gyJwtI4mHkDspyot4fn+kqNtVlkal2/4oLB5jVQdDQTk4Koiee/VjpMkQyKQmzXb5+8=&oip=3395594126&sid=645078171143720dce006&token=7758&did=ebb58103ea12d3269c9e1faeb9ea6731&ev=1&ctype=20&ep=MfdYWAqOiXZYbuBR3yPHWFThHMx89bXVFg9Km%2FOSKsV4G6HD296AzlyZ%2F8Di%2FRd1mnM%2FkBl5UgTPEqxO8HjHaXEetU7TerhecfJo2PNTtcl00yvDaMRAVRryMiswySO7'
12-22 19:22:06.155: W/IJKMEDIA(22325): open_next_file() failed (3)
12-22 19:22:06.175: W/IJKMEDIA(22325): HTTP error 403 Forbidden
12-22 19:22:06.175: E/IJKMEDIA(22325): Impossible to open 'http://k.youku.com/player/getFlvPath/sid/645078171143720dce006_03/st/flv/fileid/0300010F0356788D0348A4055F8666380FAC08-2C9F-4E63-9DCE-7894559E9834?K=7108def75cc224cc282b0b64&hd=2&ts=180&r=/3sLngL0Q6CXymAIiF9JUfR5MDecwxp/gSVk/o8apWJ3KUkaGrqktKh7cO9ZZoqYN5iGQUM9dNrj6YzDV+fl4I/W/n4xRf3Uld5UKVC3gyJwtI4mHkDspyot4fn+kqNtVlkal2/4oLB5jVQdDQTk4Koiee/VjpMkQyKQmzXb5+8=&oip=3395594126&sid=645078171143720dce006&token=7758&did=ebb58103ea12d3269c9e1faeb9ea6731&ev=1&ctype=20&ep=MfdYWAqOiXZYbuBR3yPHWFThHMx89bXVFg9Km%2FOSKsV4G6HD296AzlyZ%2F8Di%2FRd1mnM%2FkBl5UgTPEqxO8HjHaXEetU7TerhecfJo2PNTtcl00yvDaMRAVRryMiswySO7'
12-22 19:22:06.176: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:07.187: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:08.197: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:09.208: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:10.219: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:11.230: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:12.240: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:13.251: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:14.262: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:15.273: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:16.284: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:17.295: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:18.306: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:19.317: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:20.328: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:21.339: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:22.349: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:23.360: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:24.370: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:25.381: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:26.392: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:27.403: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:28.414: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:29.425: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:30.436: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:31.448: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:32.459: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:33.470: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:34.481: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:35.491: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:36.502: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:37.513: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:38.524: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:39.535: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:40.546: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:41.557: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:42.567: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:43.578: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:44.588: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:45.599: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:46.610: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:47.621: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:48.632: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:49.642: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:50.653: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:51.664: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:52.674: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:53.685: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:54.696: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:55.707: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:56.718: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:57.729: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:58.740: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:22:59.751: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:00.762: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:01.773: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:02.784: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:03.795: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:04.806: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:05.817: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:06.828: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:07.839: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:08.849: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:09.860: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:10.872: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:11.882: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:12.893: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:13.904: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:14.915: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:15.926: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:16.936: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:17.947: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:18.958: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:19.970: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:20.981: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:21.992: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:23.003: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:24.014: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:25.024: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:26.035: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:27.046: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:28.057: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:29.068: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:30.079: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:31.090: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:32.101: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:33.112: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:34.123: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:35.133: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:36.145: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:37.156: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:38.166: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:39.177: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:40.188: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:41.199: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:42.210: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:43.220: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:44.231: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:45.242: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:46.253: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:47.264: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:48.275: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:49.285: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:50.296: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:51.308: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:52.318: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:53.329: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:54.340: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:55.350: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:56.361: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:57.372: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:58.383: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:23:59.394: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:24:00.404: E/IJKMEDIA(22325): av_read_frame error: cccfcb08(�,�,�,): unknown
12-22 19:24:00.404: D/IJKMEDIA(22325): FFP_MSG_ERROR: 0
12-22 19:24:01.334: D/IJKMEDIA(22325): IjkMediaPlayer_reset
12-22 19:24:01.334: D/IJKMEDIA(22325): IjkMediaPlayer_release
12-22 19:24:01.334: D/IJKMEDIA(22325): ijkmp_set_android_surface(surface=0x0)

**Comment by bbcallen** [comment]
```
12-22 19:22:06.154: W/IJKMEDIA(22325): HTTP error 403 Forbidden
```

**Comment by Asa-Walker** [comment]
哦 谢谢 请求失败
