### ISSUE TITLE
[QUESTIONS] Custom IMediaDataSource and seeking

### ISSUE THREAD

**Issue by stuckless** [Bilibili/ijkplayer#765]
I'm calling player.seek() using a variety of media files and a custom IMediaDataSource.

When I call seek() for a .ts file being served up using the custom IMediaDataSource, the player drops the seek request and logs an error.  I realize that TS files are generally not seekable, but when the files is served up via an HTTP url, the player will seek it.  But when a custom datasource is used, I get a seek error.  I also manuall set the "seekable" format option to 1.

```
12-22 16:22:06.246 18753-19317/sagex.miniclient.android D/IJKMEDIA: IjkMediaPlayer_seekTo
12-22 16:22:06.246 18753-19317/sagex.miniclient.android D/IJKMEDIA: ijkmp_seek_to(42819)
12-22 16:22:06.246 18753-19317/sagex.miniclient.android D/IJKMEDIA: ijkmp_seek_to(42819)=0
12-22 16:22:06.246 18753-19924/sagex.miniclient.android D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_SEEK
12-22 16:22:06.246 18753-19926/sagex.miniclient.android E/IJKMEDIA: ijkmediadatasource:1050058: error while seeking
12-22 16:22:06.247 18753-19924/sagex.miniclient.android D/IJKMEDIA: FFP_MSG_BUFFERING_START:
12-22 16:22:06.247 18753-19924/sagex.miniclient.android D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_SEEK_COMPLETE
12-22 16:22:06.247 18753-19924/sagex.miniclient.android D/IJKMEDIA: FFP_MSG_SEEK_COMPLETE:
12-22 16:22:06.247 18753-19924/sagex.miniclient.android D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_SEEK_COMPLETE
12-22 16:22:06.247 18753-19924/sagex.miniclient.android D/IJKMEDIA: FFP_MSG_SEEK_COMPLETE:
12-22 16:22:06.247 18753-19924/sagex.miniclient.android D/IJKMEDIA: FFP_MSG_BUFFERING_END:
```

In MKV files, I get mixed results.   In some files the seek actually happens, but it takes some time for the video to catch up.  In other cases the seek happens, but, instead of seeking 30 seconds ahead, it will actually seek 3-4 minutes ahead (I can't really discern a pattern).

My assumption is that player.seekTo() accepts the time in milliseconds from the start of the file.

**Comment by bbcallen** [comment]
1. Seems I didn't handle "seekable" option in IMediaDataSource. What do you return from getSize()?
How readAt() is called when seek is requested?

2. Long time seek is not real seek, it just read straight forward to the target position.

**Comment by stuckless** [comment]
Thanks... In the event that I know the size, I return the size, otherwise I return -1.

So for #2, is that to mean that if I use a IMediaDataSource then I cannot have a real seek?

I know when a URL is used, then when a seek happens, it will open a new url with the range header set.  For TS files, I see it opening multiple times, since I think they approximate the time to bytes and then keeps opening requests until they get close enough.  For mp4/mkv, I think those files are seekable, so they only open a single request per seek (the files have a time to byte position map??)

**Comment by bbcallen** [comment]
If getSize() returns size > 0, IMediaDataSource would treat it as seekable.
Long time seek means, ijkplayer consider it's not seekable, so it falls back to long time read.

Have a look at "ijkmediadatasource.c", it doesn't need too much c-language knowedge.

I've got an assignment recently, so I can't spend to much time on ijkplayer until February.

**Comment by stuckless** [comment]
No worries, I'll take a peek at ijkmediadatasource.c and see what I can do... I started out in C... just been many years ;)  Good luck on your assignment, and Merry Christmas (or whatever you may be celebrating this holiday season ;) )

**Comment by stuckless** [comment]
Well, once again, your code is solid ;)  I found the issue after reading the ijkmediadatasource.c... I see you do a 0 length seek at the new position to see if it was valid (which makes sense).  In my datasource, if the len requested was <=0 I was returning -1.. so I changed it to <0 and the seeks are weeking as expected in all format that I'm testing.

Thanks again!!
