### ISSUE TITLE
硬解，onStop()里调用release会卡死。

### ISSUE THREAD

**Issue by xiaoyaomeng** [Bilibili/ijkplayer#772]
@bbcallen 之前反馈卡死的问题，最后我这边调试发现，只要是你设置了硬解码。ijkplayer-sample demo也会出现卡死的情况。

ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
然后在onStop里面调用stopPlayback()的时候在release的时候会卡死，然后会卡在Demo中选择视频列表那个界面。而软解的话视频出来的效果很不流畅，又没办法满足需求。希望提供的信息可以辅助到你们解决这个bug，项目比较赶，麻烦你们了。

public void stopPlayback() {
        if (mMediaPlayer != null) {
            mMediaPlayer.stop();
            mMediaPlayer.release();
            mMediaPlayer = null;
            if (mHudViewHolder != null)
                mHudViewHolder.setMediaPlayer(null);
            mCurrentState = STATE_IDLE;
            mTargetState = STATE_IDLE;
            AudioManager am = (AudioManager) mAppContext.getSystemService(Context.AUDIO_SERVICE);
            am.abandonAudioFocus(null);
        }
    }

**Comment by xiaoyaomeng** [comment]
@bbcallen 测试机型：MTK6795，MTK6752，还有Nexus5, Nexus6都会

**Comment by xiaoyaomeng** [comment]
@bbcallen 
我现在的解决方法是在：
/ijkplayer/ijkmedia/ijkplayer/android/pipeline/ffpipenode_android_mediacodec_vdec.c 

static int feed_input_buffer(JNIEnv *env, IJKFF_Pipenode *node, int64_t timeUs, int *enqueue_count)
方法里：加入一个非空判断。

帮忙看下这样解是否妥当哈

if (d->pkt_temp.data) {
        // reconfigure surface if surface changed
        // NULL surface cause no display
        if (ffpipeline_is_surface_need_reconfigure_l(pipeline)) {
            jobject new_surface = NULL;

            // request reconfigure before lock, or never get mutex
            ffpipeline_lock_surface(pipeline);
            ffpipeline_set_surface_need_reconfigure_l(pipeline, false);
            new_surface = ffpipeline_get_surface_as_global_ref_l(env, pipeline);
            ffpipeline_unlock_surface(pipeline);

//这里增加了一个NULL的判断，好像是new_surface为NULL引起的接下去的步骤，卡住.

	    ALOGI("%s: new surface = %d \n", __func__, (new_surface == NULL));
	    if(new_surface != NULL){
		    if (opaque->jsurface == new_surface ||
		        (opaque->jsurface && new_surface && (*env)->IsSameObject(env, new_surface, opaque->jsurface))) {
		        ALOGI("%s: same surface, reuse previous surface\n", __func__);
		        JJK_DeleteGlobalRef__p(env, &new_surface);
		    } else {
		        opaque->acodec_reconfigure_request = true;
		        SDL_LockMutex(opaque->acodec_mutex);
		        ret = reconfigure_codec_l(env, node, new_surface);
		        opaque->acodec_reconfigure_request = false;
		        SDL_CondSignal(opaque->acodec_cond);
		        SDL_UnlockMutex(opaque->acodec_mutex);

		        JJK_DeleteGlobalRef__p(env, &new_surface);

		        if (ret != 0) {
		            ALOGE("%s: reconfigure_codec failed\n", __func__);
		            ret = 0;
		            goto fail;
		        }

		        SDL_LockMutex(opaque->acodec_first_dequeue_output_mutex);
		        while (!q->abort_request &&
		            !opaque->acodec_reconfigure_request &&
		            !opaque->acodec_flush_request &&
		            opaque->acodec_first_dequeue_output_request) {
		            SDL_CondWaitTimeout(opaque->acodec_first_dequeue_output_cond, opaque->acodec_first_dequeue_output_mutex, 1000);
		        }
		        SDL_UnlockMutex(opaque->acodec_first_dequeue_output_mutex);

		        if (q->abort_request || opaque->acodec_reconfigure_request || opaque->acodec_flush_request) {
		            ret = 0;
		            goto fail;
		        }
		    }
	    }
        }

**Comment by Android4MediaPlayer** [comment]
which device？

**Comment by xiaoyaomeng** [comment]
@Android4MediaPlayer 任何设备，试过小米M4，Nexus 5，Nexus 6，美图V4。ijkplayer-sample都会出现。所以排除上层代码调用问题

**Comment by Android4MediaPlayer** [comment]
提问题不是说onstop里调release吗？这已经是应用流程调用了,试试别的地方看

**Comment by xiaoyaomeng** [comment]
@Android4MediaPlayer 对啊，虽然这是应用层面调用，但是实际上是调的是native层 _release()啊。

**Comment by xiaoyaomeng** [comment]
@Android4MediaPlayer @bbcallen 往下跟，就跟到那个new_surface == NULL的时候，就会出错，所以加了个非空判断，压测过了，没问题。但是就是怕会不会引入其他问题，所以提上来给你们看看。

**Comment by bbcallen** [comment]
Which version are you using now?

**Comment by xiaoyaomeng** [comment]
@bbcallen 


commit 2a50f476b85afdfa82f9b4db1cb309eaa0afbffe
Author: Zhang Rui <bbcallen@gmail.com>
Date:   Thu Dec 17 15:17:15 2015 +0800

    ijk-addr2line.sh

commit 4c126bf56c8937674bf69e0cd5fe3a15bf15c378
Author: Zhang Rui <bbcallen@gmail.com>
Date:   Thu Dec 17 11:53:59 2015 +0800

    android/MediaCodec: atomic increament of g_amediacodec_object_serial

commit 7491f77cd02c136a7bbb56211cb6a7411520e522
Author: Zhang Rui <bbcallen@gmail.com>
Date:   Wed Dec 16 21:05:33 2015 +0800

**Comment by xiaoyaomeng** [comment]
@bbcallen 

commit 77cb7a7c898674f004aa272aad87384e6ec6a95f
Author: Zhang Rui <bbcallen@gmail.com>
commit 77cb7a7c898674f004aa272aad87384e6ec6a95f
Author: Zhang Rui <bbcallen@gmail.com>
Date:   Thu Dec 17 17:36:24 2015 +0800

    android/sample: show av-cache

commit 2a50f476b85afdfa82f9b4db1cb309eaa0afbffe
Author: Zhang Rui <bbcallen@gmail.com>
Date:   Thu Dec 17 15:17:15 2015 +0800

**Comment by bbcallen** [comment]
Try latest code.
I have fixed something after that, not sure if it also fixed your issue.

**Comment by xiaoyaomeng** [comment]
@bbcallen 请问是否有针对改过此问题哈？？new_surface 为空的情况

**Comment by tonycore** [comment]
@xiaoyaomeng 同样遇到该问题，reconfigure_codec_l方法走进去后最终调用Mediecodec.release()会卡住，直到observer died.看了新版本里加了SDL_VoutAndroid_invalidateAllBuffers的处理，不知道是否能解决该问题

**Comment by xiaoyaomeng** [comment]
@tonycore 你那边是否测试过啦？
