### ISSUE TITLE
how to import the library in my project?

### ISSUE THREAD

**Issue by msdos2** [Bilibili/ijkplayer#777]
Can you tell me the steps to import in my project thanks

**Comment by bbcallen** [comment]
https://www.google.com/#newwindow=1&q=android+studio+import+library+project

**Comment by mistak** [comment]
iOS or andorid ?

**Comment by msdos2** [comment]
android

**Comment by mistak** [comment]
sorry, I don know,and do you know this？https://github.com/Bilibili/ijkplayer/issues/791
