### ISSUE TITLE
Could not find method jcenter() for arguments [] on repository container.

### ISSUE THREAD

**Issue by toumubaoqiong** [Bilibili/ijkplayer#782]
when I execute "gradle"  command occur error like this?
![image](https://cloud.githubusercontent.com/assets/8606981/12000245/869ceb9c-ab0d-11e5-8463-325cdf98e63e.png)
And, I don't use the follow content ,and I don't know how to use it?
![image](https://cloud.githubusercontent.com/assets/8606981/12000273/5372a53a-ab0e-11e5-8e5e-43d877dbe4f1.png)
so please help

**Comment by bbcallen** [comment]
https://www.google.com/#newwindow=1&q=%22could+not+find+method+jcenter%22

**Comment by toumubaoqiong** [comment]
thanks.
