### ISSUE TITLE
How can I rid of logs?

### ISSUE THREAD

**Issue by Zo2m4bie** [Bilibili/ijkplayer#784]
Hi, I see logs with data in my app, like:

     V/IJKMEDIA: setDataSource: path http://my_url
     D/IJKMEDIA: ijkmp_set_data_source(url=htttp://my_url)

How can I rid of this logs? I tried to use    
    
     nativeijkPlayernative_setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);

But it didn't help.

**Comment by bbcallen** [comment]
No API, yet.
You can redefine ALOG macros in ijksdl/ijksdl_log.h

**Comment by Zo2m4bie** [comment]
Ok, thank you.
