### ISSUE TITLE
http-detect-range-support这个选项是什么作用的？

### ISSUE THREAD

**Issue by mcshengInworking** [Bilibili/ijkplayer#786]
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "http-detect-range-support", 0);

http-detect-range-support在源码中找不到是什么作用，感觉没这个选项是没用的

**Comment by bbcallen** [comment]
You can remove it.

**Comment by mcshengInworking** [comment]
ok，thanks
