### ISSUE TITLE
RTSP protocol support

### ISSUE THREAD

**Issue by lexius** [Bilibili/ijkplayer#789]
Please add RTSP protocol support in light build.

**Comment by bbcallen** [comment]
It's up to you yourself to customize the build you need.

**Comment by addskya** [comment]
@lexius  You can add the Two lines in module-lite.sh
======
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=rtp"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=rtsp"

**Comment by jimneylee** [comment]
@addskya greate,  u save me,  thx
