### ISSUE TITLE
AMLogic AndroidMediaPlayer scale problem (off-topic)

### ISSUE THREAD

**Issue by NikmanSergey** [Bilibili/ijkplayer#790]
Hi! It is not IJKPlayer issue.
When playing 4:3 aspect ratio videos with AndroidMediaPlayer on AMLogic S812 devices *AR_ASPECT_FILL_PARENT* scale mode don't work properly. Video never clipped. SurfaceView object get Height larger than screen, but video is limited by screen height. So, it looks the same as AR_MATCH_PARENT.
However, IJKPlayer works fine.
I guess, MediaPlayer implementation in this devices makes video trimmed to screen size if it's larger. But I can't find the way to override this.
Other apps that uses native MediaPlayer also can't scale video larger that screen size on this devices.

Using TextureView scales videos fine, but video quality is not so fine (vivid and smooth) as when using SurfaceView.

The only app that can make it is Kodi. When using 'amcodec' in settings. But I think it uses specific codec rather then MediaPlayer implementation.
https://github.com/xbmc/xbmc/blob/138f8eb38e02bb20cbba9abe8894eb641fe5b355/xbmc/cores/VideoPlayer/DVDCodecs/Video/AMLCodec.cpp

**Comment by bbcallen** [comment]
No idea, I don't have any AMLogic devices.
But AndroidMediaPlayer's problem seems out of my reach.
