### ISSUE TITLE
[QUESTION]MPEG2 Hardware decoding on NVidia Shield TV

### ISSUE THREAD

**Issue by stuckless** [Bilibili/ijkplayer#793]
The NVidia Shield has hardware decoding for mpeg2, but I'm unsure if ijkplayer is actually using the hardware decoder.

is OnMediaCodecSelectListener only called if there is a hardware decoding support?  I see it called sometimes, but no always.  

Is there an easy way to tell if a hardware decoder is used, and if so, which decoder?  When I call player.getMediaInfo() and check mVideoDecoder and mVideoDecoder I get, avcodec, and mpeg2video respectively.  (other than telling me it's mpeg2video, I'm not sure what it's telling me :) )

**Comment by bbcallen** [comment]
Hardware decoding for mpeg2 is not supported in ijkplayer, because I rarely use it in my daily work, and don't know much about it. For now, only H264/AVC hw decoding is supported in ijkplayer.

'avcodec' means FFmpeg's decoder library, which is software decoder.

**Comment by stuckless** [comment]
@bbcallen Thanks for the reply.  So what would it take to get mpeg2 support in ijkplayer.  (I'm not a video developer).   My open source project (https://github.com/OpenSageTV/sagetv-miniclient) is an Android implementation of the SageTV client (SageTV is a PVR).  While I don't use MPEG2 myself, many users record TV using MPEG2 recorders :(

Eventually, I'd like to get hardware decoding working, where the device supports it, but I'm trying to understand what the scope of effort would be.

**Comment by bbcallen** [comment]
Hardware decoding is implemented in this file https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/android/pipeline/ffpipenode_android_mediacodec_vdec.c

It's more or less based on VideoLan's implement.
http://git.videolan.org/?p=vlc.git;a=blob;f=modules/codec/omxil/mediacodec.c;h=f7fcb5bef2499c8653e3eae8d3d28307e3c4564d;hb=HEAD

OnMediaCodecSelectListener is a filter to select workable OpenMAX decoder name.

**Comment by progamertr** [comment]
@bbcallen 
Does iOS have hardware decoding for mpeg2video with videotoolbox ?

**Comment by stuckless** [comment]
@bbcallen thanks.   It's interesting that the VLC implementation has mpeg2 "case" commented out.
http://git.videolan.org/?p=vlc.git;a=blob;f=modules/codec/omxil/mediacodec.c;h=f7fcb5bef2499c8653e3eae8d3d28307e3c4564d;hb=HEAD#l545
