### ISSUE TITLE
ijkplayer的解码模式选择怎么做的？

### ISSUE THREAD

**Issue by mandagod** [Bilibili/ijkplayer#796]
自动选择模式（根据机型和视频智能适配），这个是怎么做的？
bilili中有：
自动选择模式（根据机型和视频智能适配）
系统硬解优先
V3硬解优先
V2硬解优先
软件优先

**Comment by bbcallen** [comment]
Nothing to say.
It's not part of ijkplayer project.

**Comment by mandagod** [comment]
@bbcallen  有什么方法可以智能判断用硬解或者软解呢？上层java是否有这个接口？
