### ISSUE TITLE
IjkTrackInfo不能获取字幕类型(android),audio类型和video类型就可以获取

### ISSUE THREAD

**Issue by mcshengInworking** [Bilibili/ijkplayer#797]
IjkTrackInfo[] trackInfos = ijkMediaPlayer.getTrackInfo();
if (trackInfos != null) {
  for (int i = 0; i < trackInfos.length; i++) {
        Log.d("test",trackInfos[i].getInfoInline());                               
  }
}

**Comment by bbcallen** [comment]
Subtitle is not supported, for now.

**Comment by mcshengInworking** [comment]
那有什么办法可以获取到视频中的内嵌字幕个数吗？
