### ISSUE TITLE
can not play speex?

### ISSUE THREAD

**Issue by 283006884** [Bilibili/ijkplayer#798]
our iOS project use ijkplayer to play living videos. but some of the videos use speex for audio.at this situation , the videos we play have no sound .  how can I solve this problem? Thx!

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/README.md#before-build

**Comment by 283006884** [comment]
i tried this. but still no sound~~  how can i do now?thx

**Comment by bbcallen** [comment]
Maybe you need libspeex support

**Comment by 283006884** [comment]
thanks!

**Comment by congni** [comment]
我也遇到这个问题，你是怎么解决的
