### ISSUE TITLE
Custom datasource resets time to zero on resume playback

### ISSUE THREAD

**Issue by stuckless** [Bilibili/ijkplayer#799]
As you might recall, I have my own custom datasource for video playback, and it's working great, thanks to your help.

When I seek using the custom datasource it works perfect.

But, when stop, and then do a resume playback, it starts playing the video from the correct location (because I'm sending it the video from the correct location), but ijkplayer is ignoring the timestamp information in the media buffer, and resetting the timestamp back to 0.  The next result is that while the video resumes playback, at say, 2:15, the time code actually resets back to 0:00.   This is for a TS buffer.

In my application, when a "resume" happens, then server just starts sending the data to the client at the last known buffer position.  ie, the player doesn't tell the server that it needs to seek 2:15 because it doesn't know that, but instead the server knows where the user left off, and as such, the server simply pushes the media data to the client from that last resume position.

Is there a way to tell ijkplayer to either ignore it's own internal clock, or, to sync itself with the timecode in the media buffer.

Thanks

**Comment by bbcallen** [comment]
No, ijkplayer always adjust the start time to 0.

Maybe you need to modify ff_ffplay.c, save the internal pts/dts (calculated from PCR for TS) of AVPacket/AVFrame, and export it with ffp_get_property_int64().

**Comment by stuckless** [comment]
Thanks... I'll look into that.

**Comment by stuckless** [comment]
@bbcallen So, I did find a solution to my problem.  Basically, in my code, I just needed ```ff_ffplay.get_current_position_l``` to return the real position and not the adjusted position.  So after the ```pos``` is calculated, and before it adjusts it, I return the ```pos``` value.  This appears to work for my custom datasource.

So, I'm thinking that I'll add a player option ```"no-adjust-time"``` and check that in the ```get_current_position method``` to determine if it should adjust the time or not.

The question is do want this is your repo, or should I fork it and maintain it separately.  I'm ok either way.

**Comment by bbcallen** [comment]
it's your decision to create a pull request. :)
I can't tell whether it could be merged, until it has been reviewed.

**Comment by stuckless** [comment]
thx... I'll complete the change this weekend and submit a pull request.

Side question:  Is there a documented list of player options, format options, etc.  ie, a README somewhere that I should update if I add this option?  (I looked at one point, but did not see one)

**Comment by bbcallen** [comment]
Player's option could be find at
https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/ff_ffplay_options.h

FFmpeg's options could be find at
https://ffmpeg.org/documentation.html

No document for now.
PR is welcome, if you would like to. :)
