### ISSUE TITLE
怎样debug进去ffmpeg，有没有xcode的ffmpeg。

### ISSUE THREAD

**Issue by loveq369** [Bilibili/ijkplayer#80]

**Comment by change2hao** [comment]
@loveq369 你的头像好😎

**Comment by RobinLW** [comment]
@bbcallen 你好。我也想知道怎么在xcode里 debug ijk的 ffmpeg。能不能指点下～  谢谢啦！

**Comment by superPMonkey** [comment]
@RobinLW https://github.com/Akagi201/ffmpeg-xcode
