### ISSUE TITLE
拉动进度条，时间错位

### ISSUE THREAD

**Issue by kevin-zhujunyi** [Bilibili/ijkplayer#800]
ios最新版ijk，下载M3U8文件到手机，播放手机上的M3U8文件，拉动进度条，时间显示错误，报错No trailing CRLF found in HTTP header，不拉动进度条，时间正确显示，相同的方式下载，相同的视频，用MPMoviePlayerController播放拉动，没有问题，报错代码如下：
[hls,applehttp @ 0x15c969400] HLS request for url 'http://127.0.0.1:12345/444914/id98', offset 0, playlist 0
[http @ 0x160fdef50] No trailing CRLF found in HTTP header.
[http @ 0x160fdef50] request: GET /444914/id98 HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Connection: close

Host: 127.0.0.1:12345

Icy-MetaData: 1

[NULL @ 0x15d77f800] unknown SEI type 37

**Comment by kevin-zhujunyi** [comment]
[hls,applehttp @ 0x15c969400] HLS request for url 'http://127.0.0.1:12345/444914/id98', offset 0, playlist 0
[http @ 0x160fdef50] No trailing CRLF found in HTTP header.
[http @ 0x160fdef50] request: GET /444914/id98 HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Connection: close

Host: 127.0.0.1:12345

Icy-MetaData: 1






[NULL @ 0x15d77f800] unknown SEI type 37

**Comment by kevin-zhujunyi** [comment]
步骤：
1.下载地址如：http://pl.youku.com/playlist/m3u8?ts=1452134437&keyframe=0&vid=XODczMTg5NTYw&type=flv&r=/3sLngL0Q6CXymAIiF9JUfR5MDecwxp/gSVk/o8apWJ3KUkaGrqktKh7cO9ZZoqYN5iGQUM9dNrj6YzDV+fl4JyQ1lrgtQ+1OhDkk6zXTSsdyXhJ，下载M3U8文件至手机
2.生成手机地址：
#EXTM3U
#EXT-X-TARGETDURATION:12
#EXT-X-VERSION:2
#EXTINF:4,
http://127.0.0.1:12345/88925/id0
#EXTINF:6,
http://127.0.0.1:12345/88925/id1
#EXTINF:6,
http://127.0.0.1:12345/88925/id2
#EXTINF:12,
http://127.0.0.1:12345/88925/id3
#EXTINF:7,
http://127.0.0.1:12345/88925/id4
#EXTINF:12,
http://127.0.0.1:12345/88925/id5
#EXTINF:8,
http://127.0.0.1:12345/88925/id6
#EXTINF:11,
http://127.0.0.1:12345/88925/id7
#EXTINF:1,
http://127.0.0.1:12345/88925/id8
#EXT-X-ENDLIST
3.播放本机地址，调用didSliderTouchUpInside 方法后，mediaProgressSlider.value显示错误，报错代码如下：
[hls,applehttp @ 0x15c969400] HLS request for url 'http://127.0.0.1:12345/444914/id6', offset 0, playlist 0
[http @ 0x160fdef50] No trailing CRLF found in HTTP header.
[http @ 0x160fdef50] request: GET /444914/id98 HTTP/1.1
User-Agent: ijkplayer
Accept: /
Connection: close
Host: 127.0.0.1:12345
Icy-MetaData: 1
[NULL @ 0x15d77f800] unknown SEI type 37

**Comment by bbcallen** [comment]
What do you mean "时间显示错误"?

**Comment by kevin-zhujunyi** [comment]
例如：拉动进度条到04:50，调用didSliderTouchUpInside 方法后，mediaProgressSlider.value应该为04:50,实际显示的时间为00:04,个人认为是这样的，拉动到http://127.0.0.1:12345/88925/id4的第4秒，mediaProgressSlider.value的时间就显示第4秒，显示的是这一段落的第4秒，丢失了id1,id2,id3的时间

**Comment by bbcallen** [comment]
Can not reproduce with hls sample in demo,
Could you provide something I can debug with?

**Comment by kevin-zhujunyi** [comment]
demo已传邮箱，请查收
