### ISSUE TITLE
How to detect whether there are new frames arring during a livestream?

### ISSUE THREAD

**Issue by ProgrammerYuan** [Bilibili/ijkplayer#801]
RT.
I'd like to show some dialog or hint to tell users that there are something wrong with this liveshow.So I need to be able to detect whether there are more frames coming.Please help if you know how to achieve that.Thanks.

**Comment by ProgrammerYuan** [comment]
Okay, assume this specific occasion;
the publisher stops pushing frames to CDN and I want the Player to detect that and display a dialog that tells users that there's no more live video to play. how to do that?

**Comment by bbcallen** [comment]
I don't know any way to tell whether the publisher stops pushing or network is down.
