### ISSUE TITLE
ijkplayer android - how to call ffmpeg function in ndk C file?

### ISSUE THREAD

**Issue by lixiaoqi** [Bilibili/ijkplayer#802]
Hi, I'm using ijkplayer well and now I add some C files through ndk, and also want to call some functions declared in avcodec.h.
Is this possible, any suggestions? Thanks.

**Comment by bbcallen** [comment]
Yes, it's possible.

**Comment by lixiaoqi** [comment]
Hi @bbcallen ,one problem is that libijkffmpeg.so libijkplayer.so and libijksdl.so don't have any header files, could I use header files from ffmpeg directly?

**Comment by bbcallen** [comment]
After ffmpeg built successfully, header files can be found in directory android/contrib/build

**Comment by lixiaoqi** [comment]
thank you very much!
