### ISSUE TITLE
how to change url to player another video?(iOS)

### ISSUE THREAD

**Issue by 283006884** [Bilibili/ijkplayer#803]
Mr bbcallen:
In our playerViewController(using ijkPlayer in it),we have a tableView to show videos list, when I select a cell,I want to change url to play another video in the same viewController. I can't find the api to change url .   could you tell me the api please. our ijkplayer version is 0.4.3.12 (iOS).

 thank you very much!

**Comment by bbcallen** [comment]
Shutdown previous player, and create new player.

**Comment by 283006884** [comment]
thanks!
