### ISSUE TITLE
Can't compile latest version

### ISSUE THREAD

**Issue by weyless** [Bilibili/ijkplayer#805]
when I run ./compile-ffmpeg.sh all
I got this ,
i686-linux-android-gcc: error: libavfilter/x86/*.o: No such file or directory
I check to 894282b then ffmpeg compile is ok.

did I got anything wrong?

**Comment by bbcallen** [comment]
try 60b35846bfd3d2b4eebb2e6ce118492d4cf5ed99

**Comment by weyless** [comment]
Got new problem like this:
．．．．．．．．．
INSTALL	libavutil/ffversion.h
INSTALL	libavutil/libavutil.pc

--------------------
[*] link ffmpeg
--------------------

link compat/*.o
link libavcodec/*.o
link libavcodec/aarch64/*.o
link libavfilter/*.o
link libavformat/*.o
link libavutil/*.o
link libavutil/aarch64/*.o
link libswresample/*.o
link libswresample/aarch64/*.o
link libswscale/*.o
libavcodec/mpegvideo.o: In function `dct_init':
/home/tianyu/ijkplayer/android/contrib/ffmpeg-arm64/libavcodec/mpegvideo.c:305: undefined reference to `ff_mpv_common_init_neon'
collect2: error: ld returned 1 exit status

**Comment by bbcallen** [comment]
Try df2e5a25e979fa33c46f724ac92a780f6775cf83

**Comment by weyless** [comment]
This works ,thx.
