### ISSUE TITLE
Subtitles (feature request)

### ISSUE THREAD

**Issue by NikmanSergey** [Bilibili/ijkplayer#806]
Hi!
Subtitles support would be great feature for the project.
I mean not native renderer, but getting subtitles text as String and then draw it on Java side.
As it made in standard MediaPlayer implementation:
```
mediaPlayer.setOnTimedTextListener(MediaPlayer.OnTimedTextListener listener)
public void onTimedText(MediaPlayer mp, TimedText text)
```

**Comment by bbcallen** [comment]
Patch welcome
