### ISSUE TITLE
多ijkmediaplayer实例问题

### ISSUE THREAD

**Issue by wqmijkplayer** [Bilibili/ijkplayer#807]
@bbcallen 
请教一个问题
当在一个应用中新建两个ijkmediaplayer实例时，这两个实例都使用mediacodec硬解。
第一个ijkmediaplayer释放时，第二个ijkmediaplayer实例会在dequeueInputBuffer时超时，即使设置很大的AMC_INPUT_TIMEOUT_US也会超时
请问，ijkplayer不支持多实例吗？

**Comment by bbcallen** [comment]
Depending on device.

**Comment by wqmijkplayer** [comment]
我的设备是android 5.1平台
请问如何规避这个问题呢？

**Comment by bbcallen** [comment]
No, you can't,
As I said, it depending on device, not on system.

You should maintain some lock to assure there is only one HW ijkplayer instance.
