### ISSUE TITLE
RTP stream  latest demo can't playing

### ISSUE THREAD

**Issue by brulesLi** [Bilibili/ijkplayer#809]
this is report  
===== custom modules begin =====
register protocol: async
register protocol: ijkhttphook
register protocol: ijkinject
register protocol: ijklongurl
register protocol: ijksegment
register protocol: ijktcphook
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff2.8--ijk0.4.1.1--dev0.3.3--rc4
ijkmp_set_inject_opaque(0x17f4fbb0)
ijkmp_set_inject_opaque()=void
2016-01-07 18:20:44.749 IJKMediaDemo[3464:335305] OK setup GL
ijkmp_ios_set_view(glView=0x17e017e0)
ijkmp_ios_set_view(glView=0x17e017e0)=void
ijkmp_set_data_source(url="rtp://192.168.2.105:5000")
ijkmp_set_data_source(url="rtp://192.168.2.105:5000")=0
ijkmp_prepare_async()
===== versions =====
FFmpeg       : ff2.8--ijk0.4.1.1--dev0.3.3--rc4
libavutil    : 54.31.100
libavcodec   : 56.60.100
libavformat  : 56.40.101
libswscale   : 3.1.101
libswresample: 1.2.101
===== options =====
player-opts : videotoolbox-max-frame-width = 960
player-opts : overlay-format               = fcc-i420
player-opts : framedrop                    = 0
player-opts : max-fps                      = 30
player-opts : video-pictq-size             = 3
player-opts : videotoolbox                 = 0
player-opts : start-on-prepared            = 1
format-opts : ijkinject-opaque             = 401931184
format-opts : user-agent                   = ijkplayer
format-opts : http-tcp-hook                = ijktcphook
format-opts : auto_convert                 = 0
format-opts : timeout                      = 30000000
format-opts : reconnect                    = 1
format-opts : safe                         = 0
codec-opts  : skip_loop_filter             = 48
codec-opts  : skip_frame                   = 8
===================
ijkmp_prepare_async()=0
rtp://192.168.2.105:5000: Protocol not found
2016-01-07 18:20:44.796 IJKMediaDemo[3464:335305] FFP_MSG_ERROR: 0
2016-01-07 18:20:44.797 IJKMediaDemo[3464:335305] IJKMPMoviePlayBackStateDidChange 2: paused
2016-01-07 18:20:44.797 IJKMediaDemo[3464:335305] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackError: 1
ijkmp_start()
ijkmp_start()=-3
ijkmp_start()
ijkmp_start()=-3
ijkmp_start()
ijkmp_start()=-3
ijkmp_start()
ijkmp_start()=-3
ijkmp_start()
ijkmp_start()=-3
ijkmp_start()
ijkmp_start()=-3
ijkmp_start()
ijkmp_start()=-3
ijkmp_start()
ijkmp_start()=-3
ijkmp_start()
ijkmp_start()=-3
ijkmp_start()
ijkmp_start()=-3
ijkmp_start()
ijkmp_start()=-3
ijkmp_start()
ijkmp_start()=-3
ijkmp_start()
ijkmp_start()=-3

**Comment by bbcallen** [comment]
RTSP is not included by default
https://github.com/Bilibili/ijkplayer#before-build

**Comment by brulesLi** [comment]
是不是   
输入
# install homebrew, git, yasm
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install git
brew install yasm

# add these lines to your ~/.bash_profile or ~/.profile
# export ANDROID_SDK=<your sdk path>
# export ANDROID_NDK=<your ndk path>

# on Cygwin (unmaintained)
# install git, make, yasm
就行了
