### ISSUE TITLE
iPhone录制的视频转MP4以后播放不了

### ISSUE THREAD

**Issue by jb522185660** [Bilibili/ijkplayer#810]
iPhone录制的视频转MP4以后播放不了

**Comment by jb522185660** [comment]
这个地址：http://wx.img.6383.com/ImgServer/Down?id=e08d811a-f632-49e6-8537-105d48890b95

**Comment by jb522185660** [comment]
视频地址是这个：http://wx.img.6383.com/ImgServer/Down?id=e08d811a-f632-49e6-8537-105d48890b95，VLC可以播放

**Comment by jb522185660** [comment]
stream 0, offset 0x2c: partial file

**Comment by bbcallen** [comment]
Can not be played with ffplay on PC, too.
This should be a FFmpeg issue, better submit this file to FFmpeg's trac.
