### ISSUE TITLE
ijkmeta_create()  Memory leaks

### ISSUE THREAD

**Issue by monsterfx8278** [Bilibili/ijkplayer#813]
堆栈信息如下：
   0 libsystem_malloc.dylib malloc_zone_calloc
   1 libsystem_malloc.dylib calloc
   2 xxxx ijkmeta_create /Users/fuxin/Documents/work/APMultimediaLiveTemp/Sources/Video/live/IJKMediaPlayer/ijkmedia/ijkplayer/ijkmeta.c:41
   3 xxxx ijkmeta_set_avformat_context_l /Users/fuxin/Documents/work/APMultimediaLiveTemp/Sources/Video/live/IJKMediaPlayer/ijkmedia/ijkplayer/ijkmeta.c:201
   4 xxxx read_thread /Users/fuxin/Documents/work/APMultimediaLiveTemp/Sources/Video/live/IJKMediaPlayer/ijkmedia/ijkplayer/ff_ffplay.c:2571
   5 xxxx SDL_RunThread /Users/fuxin/Documents/work/APMultimediaLiveTemp/Sources/Video/live/IJKMediaPlayer/ijkmedia/ijksdl/ios/ijksdl_thread_ios.m:31
   6 libsystem_pthread.dylib _pthread_body
   7 libsystem_pthread.dylib _pthread_start
   8 libsystem_pthread.dylib thread_start

**Comment by monsterfx8278** [comment]
so,did you have fixed this bug?how to resolved?

**Comment by bbcallen** [comment]
No, I haven't confirmed this issue.

**Comment by bbcallen** [comment]
Fixed on master, thanks
