### ISSUE TITLE
[QUESTION] What is the role of ExoPlayer in IJKPlayer

### ISSUE THREAD

**Issue by stuckless** [Bilibili/ijkplayer#814]
I see there is an ExoPlayer portion that is optional.  I'm just trying to understand what the role of ExoPlayer would be in this project.

1. If using the ExoPlayer portion, is it using the ExoPlayer player, or the ijkplayer?
2. Is the ExoPlayer portion just there to mimic the ExoPlayer API, but still uses ijkplayer for playing, and nothing other than the API is used from ExoPlayer, etc?

I'm just wondering if could elaborate on how ExoPlayer and IJKPlayer co-exist in terms of DataSources, Extractors, TrackRenderers, etc.

For example, I could see it being beneficial to ExoPlayer, if there was an IJKExtractor that delegated the frame sample extractions to IJKPlayer that has a richer featureset in terms of parsing containers, etc.  For example MPEG2-PS is not supported by ExoPlayer, but it is by IJKPlayer.  But, ExoPlayer can play the MPEG2 stream using hardware decoding, if the decoder exists, whereas IJKPlayer will use a software decoder.

**Comment by bbcallen** [comment]
ExoMediaPlayer is only a pure java thin wrapper on ExoPlayer, and implement interface IMediaPlayer.
I can test ExoMediaPlayer and IjkMediaPlayer in same demo without change demo's code, and compare the results.
That's all. It has nothing to do with IjkMediaPlayer, and can be put into an individual repo. 

BTW: I have no plan to use ExoMediaPlayer in my own applications in the foreseeable future.

**Comment by stuckless** [comment]
Thanks.  I'm currently using both players, mainly because I need mpeg2 hardware decoding, and Exo provides that.  For everything else IJKPlayer has been working great.  Thanks for your efforts on this this project.
