### ISSUE TITLE
How to play next without closing view

### ISSUE THREAD

**Issue by desktopfreeware** [Bilibili/ijkplayer#817]
Hi , how do i play next video without closing IJKMoviePlayerViewController

For example , i have create button and when i click , i want to play next video like but not work

- (IBAction)playnextvideo:(UIBarButtonItem *)sender
{
    [self.player shutdown];
    [IJKFFMoviePlayerController setLogReport:NO];
    [IJKFFMoviePlayerController setLogLevel:k_IJK_LOG_INFO];
    [IJKFFMoviePlayerController checkIfFFmpegVersionMatch:YES];
    IJKFFOptions *options = [IJKFFOptions optionsByDefault];
    self.player = [[IJKFFMoviePlayerController alloc] initWithContentURL:@"mynextvideo.mp4" withOptions:options];
    self.player.view.autoresizingMask = UIViewAutoresizingFlexibleWidth|UIViewAutoresizingFlexibleHeight;
    self.player.view.frame = self.view.bounds;
    self.player.scalingMode = IJKMPMovieScalingModeAspectFit;
    self.player.shouldAutoplay = YES;
    self.mediaControl.frame = [UIScreen mainScreen].bounds;
    self.view.autoresizesSubviews = YES;
    [self.view addSubview:self.player.view];
    [self.view addSubview:self.mediaControl];
    self.mediaControl.delegatePlayer = self.player;
}

**Comment by bbcallen** [comment]
No, you can't. You should always create new player for new url.

**Comment by desktopfreeware** [comment]
Cheers mate
