### ISSUE TITLE
哇！斗鱼app也是用ijkplayer的啊

### ISSUE THREAD

**Issue by qazmoon** [Bilibili/ijkplayer#821]
打开lib\armeabi-v7a可以看到
libijkffmpeg.so
libijkplayer.so
libijksdl.so
libijkutil.so
liblc.so
libndkbitmap.so
libuffmpeg.so
libuplayer22.so
libuplayer23.so
libustagefright40.so
libustagefright43.so

**Comment by qazmoon** [comment]
libuplayer   libuffmpeg  libustagefright  用的是哪个开源的呢？

**Comment by Android4MediaPlayer** [comment]
是的，这个早知道了
