### ISSUE TITLE
ijkplayer lost sound when network very bad

### ISSUE THREAD

**Issue by maytrue** [Bilibili/ijkplayer#822]
Hi, 

When network become bad, ijkplayer will lost sound, but video stall and refresh.
Suppose you watch 100KB/s live stream, you can set network speed to 50KB/s, and ijkplayer will act above way.

**Comment by bbcallen** [comment]
You would receive buffering notification.

**Comment by maytrue** [comment]
I have not received MPMovieLoadStateStalled notify. I found "avcodec_decode_audio4" and IJKSDLAudioQueueOuptutCallback was called, but no sound play.

**Comment by bbcallen** [comment]
Any log?

**Comment by maytrue** [comment]
Here is  the log~
=================
2016-01-11 16:31:30.508 zbd[1536:384838] start!!
2016-01-11 16:31:30.525 zbd[1536:384838] <ZZBPlayerViewController.m : 298 : -[ZZBPlayerViewController initPlayer]>-: playUrlString = http://124.167.236.39//broadcast/7-271459237890-1452499037127-883249.flv
av_version_info: ff2.8--ijk0.3.3--dev0.3.3--rc1
ijkmp_set_inject_opaque(0x181ca9e0)
ijkmp_set_option_int(ijkinject-opaque, 404531680)
ijkmp_set_option_int()=void
ijkmp_set_inject_opaque()=void
ijkmp_set_option_int(start-on-prepared, 1)
ijkmp_set_option_int()=void
2016-01-11 16:31:30.550 zbd[1536:384838] OK setup GL
ijkmp_ios_set_view(glView=0x180b04e0)
ijkmp_ios_set_view(glView=0x180b04e0)=void
ijkmp_set_option(overlay-format, fcc-i420)
ijkmp_set_option()=void
ijkmp_set_option_int(framedrop, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(max-fps, 30)
ijkmp_set_option_int()=void
ijkmp_set_option_int(video-pictq-size, 3)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox, 1)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox-max-frame-width, 960)
ijkmp_set_option_int()=void
ijkmp_set_option(user-agent, ijkplayer)
ijkmp_set_option()=void
ijkmp_set_option_int(auto_convert, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(timeout, 30000000)
ijkmp_set_option_int()=void
ijkmp_set_option_int(reconnect, 1)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_loop_filter, 48)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_frame, 8)
ijkmp_set_option_int()=void
ijkmp_set_option_int(start-on-prepared, 1)
ijkmp_set_option_int()=void
ijkmp_set_data_source(url="http://124.167.236.39//broadcast/7-271459237890-1452499037127-883249.flv")
ijkmp_set_data_source(url="http://124.167.236.39//broadcast/7-271459237890-1452499037127-883249.flv")=0
ijkmp_set_option(safe, 0)
ijkmp_set_option()=void
ijkmp_prepare_async()
===== options =====
player-opts : videotoolbox-max-frame-width = 960
player-opts : overlay-format               = fcc-i420
player-opts : framedrop                    = 0
player-opts : max-fps                      = 30
player-opts : video-pictq-size             = 3
player-opts : videotoolbox                 = 1
player-opts : start-on-prepared            = 1
format-opts : ijkinject-opaque             = 404531680
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : timeout                      = 30000000
format-opts : reconnect                    = 1
format-opts : safe                         = 0
codec-opts  : skip_loop_filter             = 48
codec-opts  : skip_frame                   = 8
===================
ijkmp_prepare_async()=0
2016-01-11 16:31:30.617 zbd[1536:384838] by wifi
[http @ 0x181d3d40] request: GET //broadcast/7-271459237890-1452499037127-883249.flv HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=0-

Connection: close

Host: 124.167.236.39

Icy-MetaData: 1




[flv @ 0x16757c00] Format flv probed with size=2048 and score=100
Option safe not found.
[flv @ 0x16757c00] Before avformat_find_stream_info() pos: 13 bytes read:3994 seeks:0
[flv @ 0x16757c00] All info found
[flv @ 0x16757c00] rfps: 24.750000 0.015947
[flv @ 0x16757c00] rfps: 24.750000 0.015947
[flv @ 0x16757c00] rfps: 24.833333 0.007727
[flv @ 0x16757c00] rfps: 24.833333 0.007727
[flv @ 0x16757c00] rfps: 24.916667 0.002464
[flv @ 0x16757c00] rfps: 24.916667 0.002464
[flv @ 0x16757c00] rfps: 25.000000 0.000156
[flv @ 0x16757c00] rfps: 25.083333 0.000803
[flv @ 0x16757c00] rfps: 25.083333 0.000803
[flv @ 0x16757c00] rfps: 25.166667 0.004407
[flv @ 0x16757c00] rfps: 25.166667 0.004407
[flv @ 0x16757c00] rfps: 25.250000 0.010965
[flv @ 0x16757c00] rfps: 25.250000 0.010965
[flv @ 0x16757c00] rfps: 50.000000 0.000623
[flv @ 0x16757c00] Setting avg frame rate based on r frame rate
[flv @ 0x16757c00] After avformat_find_stream_info() pos: 93618 bytes read:98190 seeks:0 frames:109
[FFPlayer @ 0x181cadd0] max_frame_duration: 3600.000
Input #0, flv, from 'http://124.167.236.39//broadcast/7-271459237890-1452499037127-883249.flv':
  Metadata:
    encoder         : Lavf56.40.101
  Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
    Stream #0:0, 41, 1/1000: Video: h264, 1 reference frame, yuv420p(tv, smpte170m/bt709/bt709, left), 360x640 (368x640), 1/2000, 409 kb/s, 25 fps, 25 tbr, 1k tbn, 2k tbc
    Stream #0:1, 68, 1/1000: Audio: aac (LC), 44100 Hz, mono, fltp, 64 kb/s
aout_open_audio()
[FFPlayer @ 0x181cadd0] AudioCodec: avcodec, aac
aout_pause_audio(0)
init_videotoolbox - using avcC atom of size(30), ref_frames(1)after scale width 360 height 640 
m_max_ref_frames 1 
flushed last keyframe pts 0 
2016-01-11 16:31:33.234 zbd[1536:384838] FFP_MSG_VIDEO_DECODER_OPEN: true
[FFPlayer @ 0x181cadd0] fps: 25.000000 (normal)
[FFPlayer @ 0x181cadd0] fps: 25.000000 (normal)
ijkmp_get_msg: FFP_MSG_PREPARED
2016-01-11 16:31:33.238 zbd[1536:384838] FFP_MSG_VIDEO_SIZE_CHANGED: 360, 640
2016-01-11 16:31:33.239 zbd[1536:384838] FFP_MSG_SAR_CHANGED: 0, 1
2016-01-11 16:31:33.239 zbd[1536:384838] FFP_MSG_PREPARED:
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
2016-01-11 16:31:33.240 zbd[1536:384838] fps in meta 25.000000
2016-01-11 16:31:33.240 zbd[1536:384838] mediaIsPreparedToPlayDidChange
2016-01-11 16:31:33.241 zbd[1536:384838] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3
2016-01-11 16:31:33.241 zbd[1536:384838] <ZZBPlayerViewController.m : 758 : -[ZZBPlayerViewController moviePlayBackStateDidChange:]>-: moviePlayBackStateDidChange = 1
[SWR @ 0xb500000] Using fltp internally between filters
0.707107 
0.707107 
avcodec/Audio: first frame decoded
after scale width 360 height 640 
2016-01-11 16:31:33.242 zbd[1536:384838] moviePlayBackStateDidChange 1: playing
2016-01-11 16:31:33.259 zbd[1536:384838] FFP_MSG_AUDIO_RENDERING_START:

decodeFrame -12911 kVTVideoDecoderMalfunctionErr
decode callback -12909 kVTVideoDecoderBadDataErr
sample_info_recycle, multiple frames in same sample 0 / 1
SDL_VoutVideoToolBox_CreateOverlay(w=360, h=640, fmt=NV12(0x3231564e, dp=0x180b0390)
VideoToolbox: first frame decoded
2016-01-11 16:31:34.260 zbd[1536:384838] FFP_MSG_VIDEO_SIZE_CHANGED: 360, 640
2016-01-11 16:31:34.265 zbd[1536:386682] OK use NV12 GL renderer
2016-01-11 16:31:34.272 zbd[1536:386682] OK setup GL programm
2016-01-11 16:31:34.276 zbd[1536:386682] OK setup GL framebuffer 640:1136
2016-01-11 16:31:34.287 zbd[1536:384838] FFP_MSG_VIDEO_RENDERING_START:
SDL_VoutVideoToolBox_CreateOverlay(w=360, h=640, fmt=NV12(0x3231564e, dp=0x180b0390)
2016-01-11 16:31:34.373 zbd[1536:384838] FFP_MSG_VIDEO_SIZE_CHANGED: 360, 640
SDL_VoutVideoToolBox_CreateOverlay(w=360, h=640, fmt=NV12(0x3231564e, dp=0x180b0390)
2016-01-11 16:31:34.388 zbd[1536:384838] FFP_MSG_VIDEO_SIZE_CHANGED: 360, 640

**Comment by bbcallen** [comment]
```
$ ffplay "http://124.167.236.39//broadcast/7-271459237890-1452499037127-883249.flv"
http://124.167.236.39//broadcast/7-271459237890-1452499037127-883249.flv: End of file
```
Seems I can't access this URL.

**Comment by maytrue** [comment]
This is live stream.

You can download  http://wifi.liebao.cn/(it is windows version), and set speed limit. Suppose you watch 100KB/s live stream, you can set network speed to 50KB/s, ijkplayer will lost sound  when live stream is opened for a while(HTTP + FLV).

I trace the code and find the audio is sync with the video. But I think  video sync with audio is better, because audio bitrate is slow and audio can play well for bad network.

**Comment by bbcallen** [comment]
You can remove that line.

**Comment by bbcallen** [comment]
Do you have any log when it "lost sound"?

**Comment by maytrue** [comment]
I comment  "synchronize_audio", but not work.  I set k_IJK_LOG_DEBUG, above is full log. Should I change to k_IJK_LOG_VERBOSE?

**Comment by maytrue** [comment]
when setting k_IJK_LOG_VERBOSE, the log is the same.

**Comment by maytrue** [comment]
You can have a test according following step:
-  download http://wifi.liebao.cn/ (it is windows version), set speed limit 40KB/s
- open rtmp://live.hkstv.hk.lxdns.com/live/hks
After open URL for a while, you will find that sound lost.

**Comment by bbcallen** [comment]
I found out that your ijkplayer is a little old
can you find this line in ff_ffplay.c?
```
        av_log(ffp, AV_LOG_WARNING, "remove 'timeout' option for rtmp.\n");
```

**Comment by maytrue** [comment]
I have above code in ff_ffplay.c

**Comment by maytrue** [comment]
I am sorry because I modify following code to allow ijkplayer continue play when publisher muted( not send audio).

  if (q->is_buffer_indicator && !*finished && (pkt is video packet)
                ffp_toggle_buffering(ffp, 1);

I revert the code, and ijkplayer pause and play when network goes bad, it act in right way

**Comment by maytrue** [comment]
You can close issue now. I am very sorry and many thanks to you
