### ISSUE TITLE
播放过程中视频暂停

### ISSUE THREAD

**Issue by Asa-Walker** [Bilibili/ijkplayer#824]
01-11 18:58:46.407 20736-13511/com.fxtv.threebears W/IJKMEDIA: No trailing CRLF found in HTTP header.
01-11 18:58:57.367 20736-13511/com.fxtv.threebears W/IJKMEDIA: No trailing CRLF found in HTTP header.
01-11 18:59:16.907 20736-13511/com.fxtv.threebears W/IJKMEDIA: No trailing CRLF found in HTTP header.
01-11 18:59:24.457 20736-20736/com.fxtv.threebears D/fxtv_MediaController: onPause
01-11 18:59:24.457 20736-20736/com.fxtv.threebears D/IJKMEDIA: ijkmp_pause()
01-11 18:59:24.457 20736-20736/com.fxtv.threebears D/IJKMEDIA: ijkmp_pause()=0
01-11 18:59:24.457 20736-13503/com.fxtv.threebears D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_PAUSE

**Comment by Asa-Walker** [comment]
播放的视频格式 是M3u8

**Comment by bbcallen** [comment]
You called pause() there.

**Comment by Asa-Walker** [comment]
但是 我并没有手动暂停啊，好吧 我再检查下代码
