### ISSUE TITLE
How to play only audio or only video 

### ISSUE THREAD

**Issue by maytrue** [Bilibili/ijkplayer#827]
I want to init two player, one play audio stream and the other play video stream. Does ijkplayer support this feature?
According to https://github.com/Bilibili/ijkplayer/issues/822, when network goes bad, I want to ijkplayer play sound ok.

**Comment by bbcallen** [comment]
deselectTrack()

**Comment by maytrue** [comment]
When open live stream not file, and network is not good, we want audio stream can play smoothly.
