### ISSUE TITLE
Can ijkplayer play the video like "R.raw.test" in res/raw/ folder?

### ISSUE THREAD

**Issue by vincentssn** [Bilibili/ijkplayer#828]
hi，I was trying to play a raw video name welcome.mp4 in the res/raw/  of android app package. But ijkmedia give me such a hint: android.resource://com.qq.qcloud/2131099649: Protocol not found and stop the loading process. Can the ijkplayer play the raw video?

**Comment by bbcallen** [comment]
Have a look at
https://github.com/Bilibili/ijkplayer/blob/master/android/ijkplayer/ijkplayer-java/src/main/java/tv/danmaku/ijk/media/player/IjkMediaPlayer.java#L317
