### ISSUE TITLE
怎么减小播放前的缓冲时间和buffer

### ISSUE THREAD

**Issue by yyl7886908** [Bilibili/ijkplayer#83]
你好，ijkplayer怎么减小播放前的缓冲buffer，或者是减少缓冲时间。

**Comment by toumubaoqiong** [comment]
@yyl7886908 是把里面#define MAX_QUEUE_SIZE (15 * 1024 * 1024)
#define MIN_FRAMES 50000这两个值调大还是调小，我都试了下，感觉视频缓冲时间还是那么长，没什么变化？

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
