### ISSUE TITLE
When I play RTSP,always get notify about (ffp_toggle_buffering_l: start),then live stopped. 

### ISSUE THREAD

**Issue by CrazyPeter** [Bilibili/ijkplayer#830]
Hello,there.
When I play RTSP , always get notify about (ffp_toggle_buffering_l: start) , then live stopped. 
but wait for a long time,also cannot get "ffp_toggle_buffering_l: end"

```javascript
RTP: missed 2 packets
bytestream overread -29
error while decoding MB 24 18, bytestream -29
concealing 225 DC, 225 AC, 225 MV errors in P frame
Frame num gap 3 1
ffp_toggle_buffering_l: start
aout_pause_audio(1)
IJKMPMovieLoadStateBufferStarted
```

**Comment by CrazyPeter** [comment]
maybe just,
'''javascript
ffp_toggle_buffering_l: start
aout_pause_audio(1)
'''
 no other infomation

**Comment by bbcallen** [comment]
Sorry, I don't familiar with RTSP.

**Comment by CrazyPeter** [comment]
After all-day debug,I think it's not about whitch protocol,
 the functions about "buffer",seems have some problem.

**Comment by bbcallen** [comment]
Can you reproduce this problem with some other protocol/format?

**Comment by CrazyPeter** [comment]
no idea,actually.
I'm doing connecting to some WIFI_Devices(made in south china ಥ_ಥ).
Some Live Stream is HTTP,some is RTSP.
The sever is not stable enough,but VLC(PC) play well.
I need some custom feature in Player,so I used IJKPlyer(it's a good job).

I guess I need to overlook some buffer-check functions to keep the connect stable.

**Comment by bbcallen** [comment]
AFAIK, VLC has its own RTSP implement based on live555.

**Comment by CrazyPeter** [comment]
good news for me, thX!
