### ISSUE TITLE
Where is error code defined of ffp->error

### ISSUE THREAD

**Issue by lixiaoqi** [Bilibili/ijkplayer#832]
Hello, I get the error code -110 from these code in ff_ffplay.c
                    if (ffp->error) {
                        av_log(ffp, AV_LOG_INFO, "ffp_toggle_buffering: error: %d\n", ffp->error);
                        ffp_notify_msg1(ffp, FFP_MSG_ERROR);
                    }
I don't find out where the error code is defined, could you help me?

**Comment by bbcallen** [comment]
search in <errno.h>
