### ISSUE TITLE
ijkplayer android 编译问题

### ISSUE THREAD

**Issue by hailing0921** [Bilibili/ijkplayer#833]
请问大神，我今天刚下载的源码，为啥我按照github上的步骤编译完就只有一个ffmpeg,so呢？

**Comment by hailing0921** [comment]
profiler build: NO
[armeabi-v7a] Install        : libijkffmpeg.so => libs/armeabi-v7a/libijkffmpeg.so
/home/lc141319/zhl/ijkplayer/ijkplayer-master/android
以上是我执行./compile-ijk.sh armv7a打印出来的东西，只是把ffmpeg.so转移了位置

**Comment by hailing0921** [comment]
我转移到mac下编译出 libijkffmpeg.so、libijkplayer.so和libijksdl.so这三个so文件，是否正确了

**Comment by bbcallen** [comment]
libijkutil.so was merged into libijksdl.so

**Comment by hailing0921** [comment]
Thank you very much!
