### ISSUE TITLE
为什么Sample里面的进度条，往前拖动进度条后，还会往后退几秒

### ISSUE THREAD

**Issue by chq1314** [Bilibili/ijkplayer#834]
RT

**Comment by erwinshao** [comment]
seek只支持关键帧，出现这个情况就是原始的视频文件中i 帧比较少，播放器会在拖动的位置找最近的关键帧。

**Comment by chq1314** [comment]
@erwinshao 谢谢

**Comment by Catherine0728** [comment]
是这样么？但是我们ios中也是用的这个这个插件，但是播放相同的资源却是okay的！如果按照你说的这种情况，ios的也应该有同样的问题才是，你觉得呢@erwinshao

**Comment by gansidui** [comment]
这个问题似乎还没解决，播放一段时间后，将进度条拖动到开始位置（pos为0），进度条会直接从0跳到3秒的位置开始播放，播放m3u8时出现（MP4不会出现）

**Comment by eterrao** [comment]
My solution in the issue #313
