### ISSUE TITLE
循环播放视频会出现闪黑屏现象

### ISSUE THREAD

**Issue by androidMVP** [Bilibili/ijkplayer#835]
在android端，循环播放视频会出现闪黑屏的想象，log日志打印的信息是：
[SurfaceView] bindTextureImage: error binding external texture image 0x71: 0x501。
请问应该如何解决。

**Comment by androidMVP** [comment]
使用IjkVideoView循环播放尺寸比较大 的视频，会出现闪烁的想象，log日志不断打印[SurfaceView] bindTextureImage: error binding external texture image 0x71: 0x501。

**Comment by androidMVP** [comment]
我的现象就是这样，请问还需要提供什么信息吗？

**Comment by bbcallen** [comment]
https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html
