### ISSUE TITLE
怎样将ijkplayer android 直接集成到自己的项目中

### ISSUE THREAD

**Issue by JerryJson** [Bilibili/ijkplayer#836]
现在ijkplayer demo 是可以运行，但是libijkplayer.so文件太大了，如何减少文件体积将ijkplayer集成到自己的Android项目中，如何集成？

**Comment by JerryJson** [comment]
如果我要是在自己的项目中使用ijkplayer，那我该怎么进行..

**Comment by bbcallen** [comment]
Google "android studio import library project"

**Comment by JerryJson** [comment]
请问你们这个ijkplayer有中文的指导文档吗？

**Comment by bbcallen** [comment]
No

**Comment by JerryJson** [comment]
英文的指导文档呢？

**Comment by bbcallen** [comment]
No

**Comment by jinch888d** [comment]
使用IJKVideoView中的ijkMediaPlayer总是挂掉
