### ISSUE TITLE
怎么增加rtmp的读取数据的timeout

### ISSUE THREAD

**Issue by lyqaiym** [Bilibili/ijkplayer#837]
在ff_ffplay.c的read_thread和ffp_prepare_async_l方法中把av_dict_set(&ffp->format_opts, "timeout", NULL, 0);方法注释了。
用IjkMediaPlayer
设置setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", 300000);
或者setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", "300000");
无法播放了。
log如下:
E/IJKMEDIA(22547): Cannot open connection tcp://114.113.220.43:1937?listen&listen_timeout=300000000
E/IJKMEDIA(22547): rtmp://114.113.220.43:1937/live_bak/x_3_1648: Cannot assign requested address
E/tv.danmaku.ijk.media.player.IjkMediaPlayer(22547): Error (-10000,0)

**Comment by bbcallen** [comment]
https://ffmpeg.org/ffmpeg-protocols.html#toc-rtmp
There is different meaning for 'timeout' in rtmp.

**Comment by lyqaiym** [comment]
哦，所以我在url后面加了timeout=10，但也没啥用

**Comment by czh0405** [comment]
setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", 300000);设置这个timeout有什么意义？

**Comment by happy201993** [comment]
https://www.jianshu.com/p/e75e3f1fb6b0
试了下这个好像可以。
