### ISSUE TITLE
网络情况不好时，播放rtmp

### ISSUE THREAD

**Issue by czh0405** [Bilibili/ijkplayer#838]
请问，在网络情况不好的情况下，播放rtmp流，一直连接不上，在 onErrorLisenter里可以监听到超时信息吗？

**Comment by bbcallen** [comment]
I don't know. I don't use rtmp in my daily work.

**Comment by czh0405** [comment]
setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", 300000);
这个timeiout是设置连接超时的？

**Comment by bbcallen** [comment]
#837

**Comment by czh0405** [comment]
比如说我想把连接时间变短设置成10S，怎么设置呢，在哪里可以得到超时返回信息呢？

**Comment by WangShuo1143368701** [comment]
@czh0405 请问你解决了吗
