### ISSUE TITLE
视频开始播放接口

### ISSUE THREAD

**Issue by Asa-Walker** [Bilibili/ijkplayer#839]
我发现一个问题，就是上层无法准确知道 视频是不是开始播放了。我解释下：
给播放器设置一个url，prepared 之后，调用start函数开始播放视频，但是如果网络不好的时候，并不是调用了start() 后立刻就播放，而是缓冲一段时间后 才开始真正的播放。

我想问下，有没有视频开始真正的播放 的回调接口呢？

**Comment by bbcallen** [comment]
Please define "真正的播放"

**Comment by toss156** [comment]
可以监听第一个视频帧开始渲染的消息

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/search?utf8=✓&q=IJKMPMoviePlayerFirstVideoFrameRenderedNotification

**Comment by Asa-Walker** [comment]
Android端的，“真正的播放” 意思是：调用播放器的start()后，如果当前的网络不好，可能需要加载一段时间，加载完了才开始播放，如果当前的网络比较好，就有可能不需要加载视频 就可以播放了，我这边要做弹幕，视频start，弹幕引擎也要start。但是 视频start后，有可能需要加载，而弹幕引擎start后 不需要加载，所以 会造成一个时间差的bug。

**Comment by Asa-Walker** [comment]
就想问下 有没有 视频帧 开始运动的 回调函数？

**Comment by BelindaFly** [comment]
@bbcallen 
判断每次从后台进入前台时，通过重新初始化Player，来避免视频卡死。为了优化用户体验，想要在新的Player进行第一帧渲染时，才将上一个Player显示的最后一帧从视图的最前端移除，我想到监听IJKMPMoviePlayerFirstVideoFrameRenderedNotification通知，但是发现此通知在启动新的Player之后有时不能发送，但是看画面仍然正常渲染，why？？   

将断点在IJKFFMoviePlayerController中的postEvent: 方法中，有时不会走case FFP_MSG_VIDEO_RENDERING_START

case FFP_MSG_VIDEO_RENDERING_START: {
NSLog(@"FFP_MSG_VIDEO_RENDERING_START:\n");
_monitor.firstVideoFrameLatency = (int64_t)SDL_GetTickHR() - _monitor.prepareStartTick;
[[NSNotificationCenter defaultCenter] postNotificationName:IJKMPMoviePlayerFirstVideoFrameRenderedNotification object:self];
break;
}

**Comment by raymond1012** [comment]
not ijk issue
