### ISSUE TITLE
Invalid data found when processing input

### ISSUE THREAD

**Issue by brystel** [Bilibili/ijkplayer#84]
Hello,
When I'm trying to open this HLS stream: http://discovery-hls.live.numericable.tv/live/hls/discovery/ipad.m3u8

i got this error message:

10-10 14:02:26.902  12837-12874/tv.danmaku.ijk.media.demo W/IJKMEDIA﹕ HTTP error 404 Not Found
10-10 14:02:26.902  12837-12874/tv.danmaku.ijk.media.demo E/IJKMEDIA﹕ Unable to open key file http://80.236.2.153/live/hls/keys/cmp12_channel1_072214_060641920_3855.key
10-10 14:02:51.152  12837-12874/tv.danmaku.ijk.media.demo E/IJKMEDIA﹕ Error when loading first segment 'http://se-2.se.discovery-hls.live.numericable.tv/live/hls/discovery/ipadstream110discovery/segment_072214_060641920_1156705.ts'
10-10 14:02:51.152  12837-12874/tv.danmaku.ijk.media.demo E/IJKMEDIA﹕ http://discovery-hls.live.numericable.tv/live/hls/discovery/ipad.m3u8: Invalid data found when processing input
10-10 14:02:51.152  12837-12871/tv.danmaku.ijk.media.demo W/IJKMEDIA﹕ FFP_MSG_ERROR: 0
10-10 14:02:51.152  12837-12837/tv.danmaku.ijk.media.demo E/tv.danmaku.ijk.media.player.IjkMediaPlayer﹕ Error (-10000,0)
10-10 14:02:51.152  12837-12837/tv.danmaku.ijk.media.demo D/tv.danmaku.ijk.media.widget.VideoView﹕ Error: -10000, 0

Is there any possibility to solve that?
Thanks

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
