### ISSUE TITLE
安卓播放视频卡

### ISSUE THREAD

**Issue by hailing0921** [Bilibili/ijkplayer#841]
我编译后在三星手机上运行demo播放手机里面一个1920x1080的视频，声音到点结束了，可是视频还没播完，也就是说视频比正常要慢，怎么办

**Comment by bbcallen** [comment]
Use android.media.MediaPlayer, or enable MediaCodec decoder

**Comment by hailing0921** [comment]
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
这样就灰常滴顺畅啦，3q
