### ISSUE TITLE
Can I update FFmpeg from official repository?

### ISSUE THREAD

**Issue by don11995** [Bilibili/ijkplayer#843]
How can I update FFmpeg from official repository? I tried FFmpeg 2.8.5, FFmpeg compiled, but compile of the IJK throws errors such as "libavfilter/url.h" not found and others. Thanks.

**Comment by bbcallen** [comment]
cherry-pick these commits
https://github.com/Bilibili/FFmpeg/commits/ijk-r0.3.3-dev
