### ISSUE TITLE
ios播放视频有绿边

### ISSUE THREAD

**Issue by hailing0921** [Bilibili/ijkplayer#845]
我用ios播放手机里面的mov视频右边有很大一竖条的绿边，而且整个视频色彩怪异，用iphone5和6plus都试了，都有这个情况，是ios9.2，iphone4上是ios8也一样的情况，请问这个是什么问题呢？
（怎么不能上传图片啊啊啊啊）
===== custom modules begin =====
register protocol: async
register protocol: ijkhttphook
register protocol: ijkinject
register protocol: ijklongurl
register protocol: ijksegment
register protocol: ijktcphook
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff2.8--ijk0.4.1.1--dev0.3.3--rc4
ijkmp_set_inject_opaque(0x17e00130)
ijkmp_set_inject_opaque()=void
2016-01-18 11:41:34.347 IJKMediaDemo[1720:1183967] OK setup GL
ijkmp_ios_set_view(glView=0x17d31b70)
ijkmp_ios_set_view(glView=0x17d31b70)=void
ijkmp_set_data_source(url="/private/var/mobile/Containers/Data/Application/993981D7-626A-44D3-8C99-BF0ABAFF5446/tmp/trim.C5BA3596-67F6-4B33-8422-2175D96BE526.MOV")
ijkmp_set_data_source(url="/private/var/mobile/Containers/Data/Application/993981D7-626A-44D3-8C99-BF0ABAFF5446/tmp/trim.C5BA3596-67F6-4B33-8422-2175D96BE526.MOV")=0
ijkmp_prepare_async()
===== versions =====
FFmpeg       : ff2.8--ijk0.4.1.1--dev0.3.3--rc4
libavutil    : 54.31.100
libavcodec   : 56.60.100
libavformat  : 56.40.101
libswscale   : 3.1.101
libswresample: 1.2.101
===== options =====
player-opts : videotoolbox-max-frame-width = 960
player-opts : overlay-format               = fcc-i420
player-opts : framedrop                    = 0
player-opts : max-fps                      = 30
player-opts : video-pictq-size             = 3
player-opts : videotoolbox                 = 0
player-opts : start-on-prepared            = 1
format-opts : ijkinject-opaque             = 400556336
format-opts : user-agent                   = ijkplayer
format-opts : http-tcp-hook                = ijktcphook
format-opts : auto_convert                 = 0
format-opts : timeout                      = 30000000
format-opts : reconnect                    = 1
format-opts : safe                         = 0
codec-opts  : skip_loop_filter             = 48
codec-opts  : skip_frame                   = 8
===================
ijkmp_prepare_async()=0
Format mov,mp4,m4a,3gp,3g2,mj2 probed with size=2048 and score=100
ISO: File Type Major Brand: qt  
rfps: 29.750000 0.016006
rfps: 29.833333 0.002288
rfps: 29.916667 0.001017
rfps: 29.916667 0.001017
rfps: 30.000000 0.012192
rfps: 30.000000 0.012192
rfps: 29.970030 0.006740
rfps: 29.970030 0.006740
Option ijkinject-opaque not found.
Before avformat_find_stream_info() pos: 4325656 bytes read:73895 seeks:1
All info found
After avformat_find_stream_info() pos: 102345 bytes read:204967 seeks:2 frames:97
max_frame_duration: 10.000
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/private/var/mobile/Containers/Data/Application/993981D7-626A-44D3-8C99-BF0ABAFF5446/tmp/trim.C5BA3596-67F6-4B33-8422-2175D96BE526.MOV':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2016-01-18 03:41:29
  Duration: 00:00:07.79, start: 0.000000, bitrate: 4444 kb/s
    Stream #0:0(und), 96, 1/48000: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 156 kb/s (default)
    Metadata:
      creation_time   : 2016-01-18 03:41:29
      handler_name    : Core Media Data Handler
    Stream #0:1(und), 1, 1/90000: Video: h264, 2 reference frames (avc1 / 0x31637661), yuv420p(tv, smpte170m/smpte170m/bt709, left), 1280x720, 1/180000, 4369 kb/s, 29.91 fps, 29.92 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      rotate          : 90
      creation_time   : 2016-01-18 03:41:29
      handler_name    : Core Media Data Handler
      encoder         : H.264
    Side data:
      displaymatrix: rotation of -90.00 degrees
detected 2 logical cores
Setting 'sample_rate' to value '48000'
Setting 'sample_fmt' to value 'fltp'
Setting 'channels' to value '2'
Setting 'time_base' to value '1/48000'
Setting 'channel_layout' to value '0x3'
tb:1/48000 samplefmt:fltp samplerate:48000 chlayout:0x3
auto-inserting filter 'auto-inserted resampler 0' between the filter 'ffplay_abuffer' and the filter 'ffplay_abuffersink'
query_formats: 2 queried, 0 merged, 3 already done, 0 delayed
Using fltp internally between filters
ch:2 chl:stereo fmt:fltp r:48000Hz -> ch:2 chl:stereo fmt:s16 r:48000Hz
aout_open_audio()
AudioCodec: avcodec, aac
aout_pause_audio(0)
vtb fail!!! switch to ffmpeg decode!!!! 
VideoCodec: avcodec, h264
fps: 29.907174 (normal)
fps: 29.916667 (normal)
ijkmp_get_msg: FFP_MSG_PREPARED
Audio frame changed from rate:48000 ch:2 fmt:fltp layout:stereo serial:-1 to rate:48000 ch:2 fmt:fltp layout:stereo serial:1
2016-01-18 11:41:34.710 IJKMediaDemo[1720:1183967] FFP_MSG_VIDEO_DECODER_OPEN: false
2016-01-18 11:41:34.710 IJKMediaDemo[1720:1183967] FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
2016-01-18 11:41:34.711 IJKMediaDemo[1720:1183967] FFP_MSG_SAR_CHANGED: 0, 1
2016-01-18 11:41:34.711 IJKMediaDemo[1720:1183967] FFP_MSG_PREPARED:
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
2016-01-18 11:41:34.711 IJKMediaDemo[1720:1183967] fps in meta 29.907173
2016-01-18 11:41:34.712 IJKMediaDemo[1720:1183967] mediaIsPreparedToPlayDidChange
2016-01-18 11:41:34.712 IJKMediaDemo[1720:1183967] loadStateDidChange: IJKMPMovieLoadStatePlaythroughOK: 3
2016-01-18 11:41:34.712 IJKMediaDemo[1720:1183967] IJKMPMoviePlayBackStateDidChange 1: playing
Setting 'sample_rate' to value '48000'
Setting 'sample_fmt' to value 'fltp'
Setting 'channels' to value '2'
Setting 'time_base' to value '1/48000'
Setting 'channel_layout' to value '0x3'
tb:1/48000 samplefmt:fltp samplerate:48000 chlayout:0x3
auto-inserting filter 'auto-inserted resampler 0' between the filter 'ffplay_abuffer' and the filter 'ffplay_abuffersink'
query_formats: 2 queried, 0 merged, 3 already done, 0 delayed
Using fltp internally between filters
ch:2 chl:stereo fmt:fltp r:48000Hz -> ch:2 chl:stereo fmt:s16 r:48000Hz
Video frame changed from size:0x0 format:none serial:-1 to size:1280x720 format:yuv420p serial:1
Setting 'video_size' to value '1280x720'
Setting 'pix_fmt' to value '0'
Setting 'time_base' to value '1/90000'
Setting 'pixel_aspect' to value '0/1'
Setting 'frame_rate' to value '359/12'
w:1280 h:720 pixfmt:yuv420p tb:1/90000 fr:359/12 sar:0/1 sws_param:
Setting 'out_w' to value 'floor(in_w/2)*2'
Setting 'out_h' to value 'floor(in_h/2)*2'
Setting 'dir' to value 'clock'
query_formats: 4 queried, 3 merged, 0 already done, 0 delayed
w:1280 h:720 dir:1 -> w:720 h:1280 rotation:clockwise vflip:0
w:720 h:1280 sar:0/1 -> w:720 h:1280 sar:0/1
SDL_VoutFFmpeg_CreateOverlay(w=720, h=1280, fmt=I420(0x30323449, dp=0x17d05030)
Video: first frame decoded
2016-01-18 11:41:34.801 IJKMediaDemo[1720:1183967] FFP_MSG_VIDEO_SIZE_CHANGED: 720, 1280
2016-01-18 11:41:34.803 IJKMediaDemo[1720:1184354] OK use I420 GL renderer
2016-01-18 11:41:34.816 IJKMediaDemo[1720:1184354] OK setup GL programm
2016-01-18 11:41:34.825 IJKMediaDemo[1720:1184354] OK setup GL framebuffer 640:1136
2016-01-18 11:41:34.827 IJKMediaDemo[1720:1183967] FFP_MSG_VIDEO_SIZE_CHANGED: 720, 1280
SDL_VoutFFmpeg_CreateOverlay(w=720, h=1280, fmt=I420(0x30323449, dp=0x17d05030)
2016-01-18 11:41:34.840 IJKMediaDemo[1720:1183967] FFP_MSG_VIDEO_RENDERING_START:
avcodec/Audio: first frame decoded
2016-01-18 11:41:34.842 IJKMediaDemo[1720:1183967] FFP_MSG_AUDIO_RENDERING_START:
Increasing reorder buffer to 1
no picture 
SDL_VoutFFmpeg_CreateOverlay(w=720, h=1280, fmt=I420(0x30323449, dp=0x17d05030)
2016-01-18 11:41:34.854 IJKMediaDemo[1720:1183967] FFP_MSG_VIDEO_SIZE_CHANGED: 720, 1280
aout_pause_audio(1)
ffp_toggle_buffering: completed: OK
ijkmp_get_msg: FFP_MSG_COMPLETED
2016-01-18 11:41:43.042 IJKMediaDemo[1720:1183967] IJKMPMoviePlayBackStateDidChange 0: stoped
2016-01-18 11:41:43.042 IJKMediaDemo[1720:1183967] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackEnded: 0
2016-01-18 11:41:43.044 IJKMediaDemo[1720:1183967] IJKMPMoviePlayBackStateDidChange 0: stoped
ffp_toggle_buffering: eof

**Comment by bbcallen** [comment]
Can you provide such video sample?

**Comment by hailing0921** [comment]
这里好像没法上传文件，我怎么把视频给你呢？我在三个iphone上又试了下，竖着拍的视频播放就会有律条，横着拍的就没事

**Comment by hailing0921** [comment]
我从GitHub网站上直接下载了源码重新编译的没有绿边了，貌似用git指令拉下来的是0.4.1.1的，不过现在是没有绿边了，但是为什么我把CONFIG_AVFILTER改为1就不能播放了呢？

**Comment by bbcallen** [comment]
Sorry, I don't maintain ijkplayer with "CONFIG_AVFILTER=1". You have to dig it out by your self.

**Comment by jb522185660** [comment]
@hailing0921 我直接下载下来的怎么编译后没有framework
