### ISSUE TITLE
华为荣耀3C无法播放

### ISSUE THREAD

**Issue by androidMVP** [Bilibili/ijkplayer#847]
现象是：华为荣耀3C手机无法播放，屏幕呈现黑屏状态
视频源：http://pan.baidu.com/s/1hqYTEL2  密码：gevf
是否必现：必现
机型:华为荣耀3C
其他信息:使用mediacodec，软解，SDL_FCC_YV12类型

**Comment by androidMVP** [comment]
现象是：华为荣耀3C手机无法播放，屏幕呈现黑屏状态
视频源：http://pan.baidu.com/s/1hqYTEL2 密码：http://pan.baidu.com/s/1hqYTEL2
是否必现：必现
机型:华为荣耀3C
其他信息:使用mediacodec，软解，SDL_FCC_YV12类型

**Comment by bbcallen** [comment]
Resolution 720x4500 is too high for MediaCodec and NativeWindow.
You have to use swscale to scale it down, before render.

**Comment by androidMVP** [comment]
感谢你的回答。请问我应该如何使用ijkplayer对该视频进行压缩？

**Comment by bbcallen** [comment]
ijkplayer doesn't support that, for now.
