### ISSUE TITLE
播放直播视频时播放会中断

### ISSUE THREAD

**Issue by vincent-law** [Bilibili/ijkplayer#849]
D/IJKMEDIA: ffp_toggle_buffering_l: start
D/IjkVideoView: MEDIA_INFO_BUFFERING_START:
D/IjkVideoView: Error: -10000,0
E/IJKMEDIA: AVC: nal size 3877
E/IJKMEDIA: missing picture in access unit with size 1560
E/IJKMEDIA: av_read_frame error: ffffff98(�,�,�,�): unknown
 D/IJKMEDIA: ffp_toggle_buffering_l: end
E/IJKMEDIA: AVC: nal size 3877
E/IJKMEDIA: no frame!
D/IjkVideoView: MEDIA_INFO_BUFFERING_END:

**Comment by vincent-law** [comment]
播放flvoverhttp的一路直播流，大约5分钟后就中断了，显示“Unknown”对话框，log显示
I/IJKMEDIA: ffp_toggle_buffering: error: -104
D/IJKMEDIA: FFP_MSG_ERROR: 0
E/IJKMEDIA: av_read_frame error: ffffff98(�,�,�,�): unknown
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
D/IjkVideoView: Error: -10000,0

**Comment by vincent-law** [comment]
是否是缓存问题呢？

**Comment by ryanjunhung** [comment]
u can try modify "ff_ffplay.c"
==========================
static int packet_queue_get_or_buffering(FFPlayer *ffp, PacketQueue *q, AVPacket *pkt, int *serial, int *finished)
{
    assert(finished);
    while (1) {
        int new_packet = packet_queue_get(q, pkt, 0, serial);
        if (new_packet < 0)
            return -1;
        else if (new_packet == 0) {
            if (q->is_buffer_indicator && !*finished)
                ffp_toggle_buffering(ffp, 1);
            new_packet = packet_queue_get(q, pkt, 1, serial);
            if (new_packet < 0)
                return -1;
        }

        if (*finished == *serial) {
            av_free_packet(pkt);
            continue;
        }
        else
            break;
    }

    return 1;
}
============================================
TO ====>

static int packet_queue_get_or_buffering(FFPlayer *ffp, PacketQueue *q, AVPacket *pkt, int *serial, int finished)
{
    while (1) {
        int new_packet = packet_queue_get(q, pkt, 1, serial);
        if (new_packet < 0)
		{
			new_packet = packet_queue_get(q, pkt, 0, serial);
			if(new_packet < 0)
            	return -1;
		}
        else if (new_packet == 0) {
            if (!finished)
                ffp_toggle_buffering(ffp, 1);
            new_packet = packet_queue_get(q, pkt, 1, serial);
            if (new_packet < 0)
                return -1;
        }

        if (finished == *serial) {
            av_free_packet(pkt);
            continue;
        }
        else
            break;
    }

    return 1;
}

**Comment by vincent-law** [comment]
Thank you.It is very helpful to me.

**Comment by Coder-XL** [comment]
按照这个修改ff_ffplay.c文件但是还是不能播放rtsp协议流视频，还要设置什么？

**Comment by Coder-XL** [comment]
在module-lite.sh文件中也做了相应的支持
export COMMON_FF_CFG_FLAGS =" $ COMMON_FF_CFG_FLAGS --enable -protocol= rtp
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=rtsp
但是还是不行，还要怎么设置，若用module-default.sh，可以播放rtsp协议流视频，但是包太大。求大神！！！
