### ISSUE TITLE
ios:ijkplayer will stop other app background music playing once open ijkplayer before  

### ISSUE THREAD

**Issue by zyi1992** [Bilibili/ijkplayer#850]
I got a problem when use ijkplayer. Once i open the ijkplayer see a video and close the player then switch to a music app and playing without quit my app, then back to my app ,the music will stop. I guess the ijkplayer   have done  something event it was closed. So i user the leak to check it,I got this ,hope for you help.  
![qq20160119-0](https://cloud.githubusercontent.com/assets/12459874/12409275/94d5dec2-bea3-11e5-9ef4-6278a87d29d6.png)
![53ffb683-e3dd-4bc7-a12c-39653fd9ea0b](https://cloud.githubusercontent.com/assets/12459874/12409287/a6fd1296-bea3-11e5-94ff-ac83e5ee40d0.png)

**Comment by bbcallen** [comment]
Did you call shutdown, when you "close" player?

**Comment by zyi1992** [comment]
yes, i did

**Comment by zyi1992** [comment]
I did this in viewDidDisappear when close  player

**Comment by zyi1992** [comment]
![qq20160119-1](https://cloud.githubusercontent.com/assets/12459874/12410768/355e5b94-beb3-11e5-9c72-80a34e2ff6bc.png)

**Comment by bbcallen** [comment]
IJKAudioKit would obtain audio session active no matter whether there is a player instance.
Maybe you can remove all calls to [IJKAudioKit setupAudioSession] to disable this behavior.

**Comment by zyi1992** [comment]
This work to me , but i have a question ,why not remove the AVAudioSessionInterruptionNotification observer when  close player, Will it have any problem?

**Comment by bbcallen** [comment]
I've forgotten why

**Comment by zyi1992** [comment]
Ok,thanks！
