### ISSUE TITLE
ios播放视频旋转90度有绿边

### ISSUE THREAD

**Issue by hailing0921** [Bilibili/ijkplayer#854]
能不能帮忙看下ios为啥将视频旋转90度弄正了之后播放右边会有绿边啊？歪着播放实在是别扭啊，先谢啦

**Comment by hailing0921** [comment]
我把视频放到网上或者直接放到项目目录里面播放没有绿边，但是经过ios的Movie Picker压缩之后播放就有了绿边了

**Comment by hailing0921** [comment]
ios上打开filter让视频制动旋转成正方向的，播放时右边会有一个竖条的绿边，大神帮忙看下啊，实在是搞不定啦
视频是用iphone5竖着拍的，经过movie picker压缩后播放的
===== custom modules begin =====
register protocol: async
register protocol: ijkhttphook
register protocol: ijkinject
register protocol: ijklongurl
register protocol: ijksegment
register protocol: ijktcphook
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff2.8--ijk0.4.4.1--dev0.3.3--rc6
ijkmp_set_inject_opaque(0x16974840)
ijkmp_set_inject_opaque()=void
2016-01-23 15:14:36.955 IJKMediaDemo[3779:2154420] OK setup GL
ijkmp_ios_set_view(glView=0x15612e00)
ijkmp_ios_set_view(glView=0x15612e00)=void
ijkmp_set_data_source(url="/private/var/mobile/Containers/Data/Application/1E9C2C6B-E242-45B0-B323-782EE48F529A/tmp/trim.5A26D094-B992-4355-BEF9-6FB2B6D995AB.MOV")
ijkmp_set_data_source(url="/private/var/mobile/Containers/Data/Application/1E9C2C6B-E242-45B0-B323-782EE48F529A/tmp/trim.5A26D094-B992-4355-BEF9-6FB2B6D995AB.MOV")=0
ijkmp_prepare_async()
===== versions =====
FFmpeg       : ff2.8--ijk0.4.4.1--dev0.3.3--rc6
libavutil    : 54.31.100
libavcodec   : 56.60.100
libavformat  : 56.40.101
libswscale   : 3.1.101
libswresample: 1.2.101
===== options =====
player-opts : videotoolbox-max-frame-width = 960
player-opts : overlay-format               = fcc-i420
player-opts : framedrop                    = 1
player-opts : max-fps                      = 30
player-opts : video-pictq-size             = 3
player-opts : videotoolbox                 = 0
player-opts : start-on-prepared            = 1
format-opts : ijkinject-opaque             = 379013184
format-opts : user-agent                   = ijkplayer
format-opts : auto_convert                 = 0
format-opts : timeout                      = 30000000
format-opts : reconnect                    = 1
format-opts : safe                         = 0
codec-opts  : skip_loop_filter             = 48
codec-opts  : skip_frame                   = 8
===================
ijkmp_prepare_async()=0
Format mov,mp4,m4a,3gp,3g2,mj2 probed with size=2048 and score=100
ISO: File Type Major Brand: qt  
Option ijkinject-opaque not found.
Before avformat_find_stream_info() pos: 3520139 bytes read:70812 seeks:1
All info found
After avformat_find_stream_info() pos: 79256 bytes read:201884 seeks:2 frames:99
max_frame_duration: 10.000
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/private/var/mobile/Containers/Data/Application/1E9C2C6B-E242-45B0-B323-782EE48F529A/tmp/trim.5A26D094-B992-4355-BEF9-6FB2B6D995AB.MOV':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2016-01-23 07:14:32
  Duration: 00:00:06.75, start: 0.000000, bitrate: 4172 kb/s
    Stream #0:0(und), 98, 1/44100: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 63 kb/s (default)
    Metadata:
      creation_time   : 2016-01-23 07:14:32
      handler_name    : Core Media Data Handler
    Stream #0:1(und), 1, 1/600: Video: h264, 2 reference frames (avc1 / 0x31637661), yuv420p(tv, bt709, left), 1280x720, 1/1200, 4102 kb/s, 24 fps, 24 tbr, 600 tbn, 1200 tbc (default)
    Metadata:
      rotate          : 90
      creation_time   : 2016-01-23 07:14:32
      handler_name    : Core Media Data Handler
      encoder         : H.264
    Side data:
      displaymatrix: rotation of -90.00 degrees
detected 2 logical cores
Setting 'sample_rate' to value '44100'
Setting 'sample_fmt' to value 'fltp'
Setting 'channels' to value '1'
Setting 'time_base' to value '1/44100'
Setting 'channel_layout' to value '0x4'
tb:1/44100 samplefmt:fltp samplerate:44100 chlayout:0x4
auto-inserting filter 'auto-inserted resampler 0' between the filter 'ffplay_abuffer' and the filter 'ffplay_abuffersink'
query_formats: 2 queried, 0 merged, 3 already done, 0 delayed
Using fltp internally between filters
ch:1 chl:mono fmt:fltp r:44100Hz -> ch:1 chl:mono fmt:s16 r:44100Hz
aout_open_audio()
AudioCodec: avcodec, aac
aout_pause_audio(0)
vtb fail!!! switch to ffmpeg decode!!!! 
VideoCodec: avcodec, h264
fps: 24.000000 (normal)
fps: 24.000000 (normal)
ijkmp_get_msg: FFP_MSG_PREPARED
Audio frame changed from rate:44100 ch:1 fmt:fltp layout:mono serial:-1 to rate:44100 ch:1 fmt:fltp layout:mono serial:1
Setting 'sample_rate' to value '44100'
2016-01-23 15:14:37.438 IJKMediaDemo[3779:2154420] FFP_MSG_VIDEO_DECODER_OPEN: false
2016-01-23 15:14:37.439 IJKMediaDemo[3779:2154420] FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
2016-01-23 15:14:37.439 IJKMediaDemo[3779:2154420] FFP_MSG_SAR_CHANGED: 0, 1
2016-01-23 15:14:37.439 IJKMediaDemo[3779:2154420] FFP_MSG_PREPARED:
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
Setting 'sample_fmt' to value 'fltp'
Setting 'channels' to value '1'
Setting 'time_base' to value '1/44100'
Setting 'channel_layout' to value '0x4'
2016-01-23 15:14:37.440 IJKMediaDemo[3779:2154420] fps in meta 24.000000
tb:1/44100 samplefmt:fltp samplerate:44100 chlayout:0x4
auto-inserting filter 'auto-inserted resampler 0' between the filter 'ffplay_abuffer' and the filter 'ffplay_abuffersink'
query_formats: 2 queried, 0 merged, 3 already done, 0 delayed
Using fltp internally between filters
0.707107 
0.707107 
ch:1 chl:mono fmt:fltp r:44100Hz -> ch:2 chl:stereo fmt:s16 r:44100Hz
2016-01-23 15:14:37.442 IJKMediaDemo[3779:2154420] mediaIsPreparedToPlayDidChange
2016-01-23 15:14:37.442 IJKMediaDemo[3779:2154420] loadStateDidChange: IJKMPMovieLoadStatePlaythroughOK: 3
2016-01-23 15:14:37.443 IJKMediaDemo[3779:2154420] IJKMPMoviePlayBackStateDidChange 1: playing
Video frame changed from size:0x0 format:none serial:-1 to size:1280x720 format:yuv420p serial:1
Setting 'video_size' to value '1280x720'
Setting 'pix_fmt' to value '0'
Setting 'time_base' to value '1/600'
Setting 'pixel_aspect' to value '0/1'
Setting 'frame_rate' to value '24/1'
w:1280 h:720 pixfmt:yuv420p tb:1/600 fr:24/1 sar:0/1 sws_param:
Setting 'out_w' to value 'floor(in_w/2)*2'
Setting 'out_h' to value 'floor(in_h/2)*2'
Setting 'dir' to value 'clock'
query_formats: 4 queried, 3 merged, 0 already done, 0 delayed
w:1280 h:720 dir:1 -> w:720 h:1280 rotation:clockwise vflip:0
w:720 h:1280 sar:0/1 -> w:720 h:1280 sar:0/1
SDL_VoutFFmpeg_CreateOverlay(w=720, h=1280, fmt=I420(0x30323449, dp=0x1697a040)
Video: first frame decoded
2016-01-23 15:14:37.564 IJKMediaDemo[3779:2154420] FFP_MSG_VIDEO_SIZE_CHANGED: 720, 1280
avcodec/Audio: first frame decoded
2016-01-23 15:14:37.579 IJKMediaDemo[3779:2154682] OK use I420 GL renderer
2016-01-23 15:14:37.581 IJKMediaDemo[3779:2154420] FFP_MSG_AUDIO_RENDERING_START:
2016-01-23 15:14:37.593 IJKMediaDemo[3779:2154682] OK setup GL programm
2016-01-23 15:14:37.597 IJKMediaDemo[3779:2154682] OK setup GL framebuffer 1136:640
2016-01-23 15:14:37.598 IJKMediaDemo[3779:2154420] FFP_MSG_VIDEO_SIZE_CHANGED: 720, 1280
SDL_VoutFFmpeg_CreateOverlay(w=720, h=1280, fmt=I420(0x30323449, dp=0x1697a040)
2016-01-23 15:14:37.610 IJKMediaDemo[3779:2154420] FFP_MSG_VIDEO_RENDERING_START:
SDL_VoutFFmpeg_CreateOverlay(w=720, h=1280, fmt=I420(0x30323449, dp=0x1697a040)
2016-01-23 15:14:37.644 IJKMediaDemo[3779:2154420] FFP_MSG_VIDEO_SIZE_CHANGED: 720, 1280
Increasing reorder buffer to 1
no picture 
aout_pause_audio(1)
ffp_toggle_buffering: completed: OK
ijkmp_get_msg: FFP_MSG_COMPLETED
2016-01-23 15:14:44.675 IJKMediaDemo[3779:2154420] IJKMPMoviePlayBackStateDidChange 0: stoped
2016-01-23 15:14:44.676 IJKMediaDemo[3779:2154420] playbackStateDidChange: IJKMPMovieFinishReasonPlaybackEnded: 0
2016-01-23 15:14:44.676 IJKMediaDemo[3779:2154420] IJKMPMoviePlayBackStateDidChange 0: stoped
ffp_toggle_buffering: eof

**Comment by bbcallen** [comment]
For GLES, frame buffer width need to be 2^n.
But avfilter would trim that padding in frame buffer.

That's to say, you need to modify FFmpeg's code, to fix this issue.

**Comment by hailing0921** [comment]
Ok,3q

**Comment by jb522185660** [comment]
具体是怎么解决啊

**Comment by yeshibuzhong** [comment]
具体怎么解决的

**Comment by ceekay1991** [comment]
解决了吗？？？
