### ISSUE TITLE
怎么用mediacodec播放hevc视频？

### ISSUE THREAD

**Issue by Long888** [Bilibili/ijkplayer#855]
我在播放播放hevc视频的时候发现音视频不同步，后来查看日志发现没有调用mediacodec解码，是用的软解。芯片也是支持H265硬解码的，编译时我已经加上了和hevc相关的选项，代码里也设置相关的参数，但是就是不会调用mediacodec解码。

Code：
	IjkMediaPlayer ijkMediaPlayer = null;
			if (mUri != null) {
				ijkMediaPlayer = new IjkMediaPlayer();
				IjkMediaPlayer.native_setLogLevel(IjkMediaPlayer.IJK_LOG_INFO);

				if (mSettings.getUsingMediaCodec()) {
					ijkMediaPlayer
							.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER,
									"mediacodec", 1);
					ijkMediaPlayer.setOption(
							IjkMediaPlayer.OPT_CATEGORY_PLAYER,
							"mediacodec_all_videos", 1);
					ijkMediaPlayer.setOption(
							IjkMediaPlayer.OPT_CATEGORY_PLAYER,
							"mediacodec_hevc", 1);
					if (mSettings.getUsingMediaCodecAutoRotate()) {
						ijkMediaPlayer.setOption(
								IjkMediaPlayer.OPT_CATEGORY_PLAYER,
								"mediacodec-auto-rotate", 1);
					} else {
						ijkMediaPlayer.setOption(
								IjkMediaPlayer.OPT_CATEGORY_PLAYER,
								"mediacodec-auto-rotate", 0);
					}
				} else {
					ijkMediaPlayer
							.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER,
									"mediacodec", 0);
				}

				if (mSettings.getUsingOpenSLES()) {
					ijkMediaPlayer.setOption(
							IjkMediaPlayer.OPT_CATEGORY_PLAYER, "opensles", 1);
				} else {
					ijkMediaPlayer.setOption(
							IjkMediaPlayer.OPT_CATEGORY_PLAYER, "opensles", 0);
				}

				String pixelFormat = mSettings.getPixelFormat();
				if (TextUtils.isEmpty(pixelFormat)) {
					ijkMediaPlayer.setOption(
							IjkMediaPlayer.OPT_CATEGORY_PLAYER,
							"overlay-format", IjkMediaPlayer.SDL_FCC_RV32);
				} else {
					ijkMediaPlayer.setOption(
							IjkMediaPlayer.OPT_CATEGORY_PLAYER,
							"overlay-format", pixelFormat);
				}
				ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER,
						"framedrop", 1);
				ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER,
						"start-on-prepared", 0);

				// ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT,
				// "http-detect-range-support", 0);

				ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_CODEC,
						"skip_loop_filter", 48);

Log:

01-19 16:42:05.279: D/IJKMEDIA(28607): JJKLoader: OK: 'java.nio.ByteBuffer' loaded
01-19 16:42:05.279: D/IJKMEDIA(28607): JJKLoader: OK: 'java.util.ArrayList' loaded
01-19 16:42:05.279: D/IJKMEDIA(28607): JJKLoader: OK: 'android.os.Build$VERSION' loaded
01-19 16:42:05.279: D/IJKMEDIA(28607): JJKLoader: OK: 'android.os.Build' loaded
01-19 16:42:05.279: D/IJKMEDIA(28607): JJKLoader: OK: 'android.media.AudioTrack' loaded
01-19 16:42:05.279: I/IJKMEDIA(28607): API-Level: 19
01-19 16:42:05.279: D/IJKMEDIA(28607): JJKLoader: OK: 'android.media.MediaCodec$BufferInfo' loaded
01-19 16:42:05.329: D/IJKMEDIA(28607): JJKLoader: OK: 'android.media.MediaCodec' loaded
01-19 16:42:05.339: D/IJKMEDIA(28607): JJKLoader: OK: 'android.media.MediaFormat' loaded
01-19 16:42:05.339: D/IJKMEDIA(28607): JJKLoader: OK: 'android.os.Bundle' loaded
01-19 16:42:05.339: D/IJKMEDIA(28607): JJKLoader: OK: 'tv.danmaku.ijk.media.player.IjkMediaPlayer' loaded
01-19 16:42:05.339: D/IJKMEDIA(28607): JJKLoader: OK: 'tv.danmaku.ijk.media.player.misc.IMediaDataSource' loaded
01-19 16:42:05.369: D/IJKMEDIA(28607): IjkMediaPlayer_native_init
01-19 16:42:05.369: D/IJKMEDIA(28607): IjkMediaPlayer_native_setup
01-19 16:42:05.369: I/IJKMEDIA(28607): av_version_info: ff2.8--ijk0.4.1.1--dev0.3.3--rc4
01-19 16:42:05.369: D/IJKMEDIA(28607): ffpipeline_create_from_android()
01-19 16:42:05.369: D/IJKMEDIA(28607): ijkmp_set_inject_opaque(0x1d2002ba)
01-19 16:42:05.369: D/IJKMEDIA(28607): ijkmp_set_inject_opaque()=void
01-19 16:42:05.369: D/IJKMEDIA(28607): ijkmp_android_set_mediacodec_select_callback()
01-19 16:42:05.369: D/IJKMEDIA(28607): ffpipeline_set_mediacodec_select_callback
01-19 16:42:05.369: D/IJKMEDIA(28607): ijkmp_android_set_mediacodec_select_callback()=void
01-19 16:42:05.369: D/IJKMEDIA(28607): IjkMediaPlayer_native_setLogLevel(4)
01-19 16:42:05.369: D/IJKMEDIA(28607): moncleanup
01-19 16:42:05.369: D/IJKMEDIA(28607): IjkMediaPlayer_setOptionLong
01-19 16:42:05.369: D/IJKMEDIA(28607): IjkMediaPlayer_setOptionLong
01-19 16:42:05.369: D/IJKMEDIA(28607): IjkMediaPlayer_setOptionLong
01-19 16:42:05.369: D/IJKMEDIA(28607): IjkMediaPlayer_setOptionLong
01-19 16:42:05.369: D/IJKMEDIA(28607): IjkMediaPlayer_setOptionLong
01-19 16:42:05.369: D/IJKMEDIA(28607): IjkMediaPlayer_setOptionLong
01-19 16:42:05.369: D/IJKMEDIA(28607): IjkMediaPlayer_setOptionLong
01-19 16:42:05.369: D/IJKMEDIA(28607): IjkMediaPlayer_setOptionLong
01-19 16:42:05.369: D/IJKMEDIA(28607): IjkMediaPlayer_setOptionLong
01-19 16:42:05.369: D/IJKMEDIA(28607): IjkMediaPlayer_setDataSourceAndHeaders
01-19 16:42:05.369: V/IJKMEDIA(28607): setDataSource: path http://127.0.0.1:9104
01-19 16:42:05.369: D/IJKMEDIA(28607): ijkmp_set_data_source(url="http://127.0.0.1:9104")
01-19 16:42:05.369: D/IJKMEDIA(28607): ijkmp_set_data_source(url="http://127.0.0.1:9104")=0
01-19 16:42:05.369: D/IJKMEDIA(28607): IjkMediaPlayer_setVideoSurface
01-19 16:42:05.369: D/IJKMEDIA(28607): ijkmp_set_android_surface(surface=0x5cf0001d)
01-19 16:42:05.369: D/IJKMEDIA(28607): ffpipeline_set_surface()
01-19 16:42:05.369: D/IJKMEDIA(28607): ijkmp_set_android_surface(surface=0x5cf0001d)=void
01-19 16:42:05.369: D/IJKMEDIA(28607): IjkMediaPlayer_prepareAsync
01-19 16:42:05.369: D/IJKMEDIA(28607): ijkmp_prepare_async()
01-19 16:42:05.379: I/IJKMEDIA(28607): ===== versions =====
01-19 16:42:05.379: I/IJKMEDIA(28607): FFmpeg       : ff2.8--ijk0.4.1.1--dev0.3.3--rc4
01-19 16:42:05.379: I/IJKMEDIA(28607): libavutil    : 54.31.100
01-19 16:42:05.379: I/IJKMEDIA(28607): libavcodec   : 56.60.100
01-19 16:42:05.379: I/IJKMEDIA(28607): libavformat  : 56.40.101
01-19 16:42:05.379: I/IJKMEDIA(28607): libswscale   : 3.1.101
01-19 16:42:05.379: I/IJKMEDIA(28607): libswresample: 1.2.101
01-19 16:42:05.379: I/IJKMEDIA(28607): ===== options =====
01-19 16:42:05.379: I/IJKMEDIA(28607): player-opts : mediacodec                   = 1
01-19 16:42:05.379: I/IJKMEDIA(28607): player-opts : mediacodec_all_videos        = 1
01-19 16:42:05.379: I/IJKMEDIA(28607): player-opts : mediacodec_hevc              = 1
01-19 16:42:05.379: I/IJKMEDIA(28607): player-opts : mediacodec-auto-rotate       = 1
01-19 16:42:05.379: I/IJKMEDIA(28607): player-opts : opensles                     = 0
01-19 16:42:05.379: I/IJKMEDIA(28607): player-opts : overlay-format               = 842225234
01-19 16:42:05.379: I/IJKMEDIA(28607): player-opts : framedrop                    = 1
01-19 16:42:05.379: I/IJKMEDIA(28607): player-opts : start-on-prepared            = 0
01-19 16:42:05.379: I/IJKMEDIA(28607): format-opts : ijkinject-opaque             = 488637114
01-19 16:42:05.379: I/IJKMEDIA(28607): codec-opts  : skip_loop_filter             = 48
01-19 16:42:05.379: I/IJKMEDIA(28607): ===================
01-19 16:42:05.379: D/IJKMEDIA(28607): ijkmp_prepare_async()=0
01-19 16:42:05.379: I/IJKMEDIA(28607): SDL_RunThread: [28710] ff_msg_loop
01-19 16:42:05.379: D/IJKMEDIA(28607): message_loop
01-19 16:42:05.379: D/IJKMEDIA(28607): FFP_MSG_FLUSH:
01-19 16:42:05.379: I/IJKMEDIA(28607): SDL_RunThread: [28712] ff_read
01-19 16:42:05.379: I/IJKMEDIA(28607): SDL_RunThread: [28711] ff_vout
01-19 16:42:07.119: E/IJKMEDIA(28607): Option ijkinject-opaque not found.
01-19 16:42:07.399: I/IJKMEDIA(28607): max_frame_duration: 10.000
01-19 16:42:07.399: I/IJKMEDIA(28607): Input #0, mpegts, from 'http://127.0.0.1:9104':
01-19 16:42:07.409: I/IJKMEDIA(28607):   Duration: 
01-19 16:42:07.409: I/IJKMEDIA(28607): N/A
01-19 16:42:07.409: I/IJKMEDIA(28607): , start: 
01-19 16:42:07.409: I/IJKMEDIA(28607): 8649.526800
01-19 16:42:07.409: I/IJKMEDIA(28607): , bitrate: 
01-19 16:42:07.409: I/IJKMEDIA(28607): N/A
01-19 16:42:07.409: I/IJKMEDIA(28607):   Program 1 
01-19 16:42:07.409: I/IJKMEDIA(28607):     Metadata:
01-19 16:42:07.409: I/IJKMEDIA(28607):       service_name    : 
01-19 16:42:07.409: I/IJKMEDIA(28607): Service01
01-19 16:42:07.409: I/IJKMEDIA(28607):       service_provider: 
01-19 16:42:07.409: I/IJKMEDIA(28607): FFmpeg
01-19 16:42:07.409: I/IJKMEDIA(28607):     Stream #0:0
01-19 16:42:07.409: I/IJKMEDIA(28607): [0x100]
01-19 16:42:07.409: I/IJKMEDIA(28607): : Video: hevc (Main) ([36][0][0][0] / 0x0024), yuv420p(tv), 1280x720
01-19 16:42:07.409: I/IJKMEDIA(28607): , 
01-19 16:42:07.409: I/IJKMEDIA(28607): 60 tbr, 
01-19 16:42:07.409: I/IJKMEDIA(28607): 90k tbn, 
01-19 16:42:07.409: I/IJKMEDIA(28607): 90k tbc
01-19 16:42:07.409: I/IJKMEDIA(28607):     Stream #0:1
01-19 16:42:07.409: I/IJKMEDIA(28607): [0x101]
01-19 16:42:07.409: I/IJKMEDIA(28607): : Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 70 kb/s
01-19 16:42:07.429: I/IJKMEDIA(28607): SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
01-19 16:42:07.429: I/IJKMEDIA(28607): SDL_Android_AudioTrack: ENCODING_PCM_16BIT
01-19 16:42:07.449: I/IJKMEDIA(28607): SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(1.000000,0.000000)
01-19 16:42:07.449: I/IJKMEDIA(28607): audio_session_id = 69
01-19 16:42:07.449: I/IJKMEDIA(28607): AudioCodec: avcodec, aac
01-19 16:42:07.449: I/IJKMEDIA(28607): SDL_RunThread: [28724] ff_audio_dec
01-19 16:42:07.449: I/IJKMEDIA(28607): SDL_RunThread: [28723] ff_aout_android
01-19 16:42:07.449: D/IJKMEDIA(28607): ffpipenode_create_video_decoder_from_android_mediacodec()
01-19 16:42:07.449: I/IJKMEDIA(28607): API-Level: 19
01-19 16:42:07.449: E/IJKMEDIA(28607): ffpipenode_create_video_decoder_from_android_mediacodec: MediaCodec/HEVC is disabled. codec_id:1211250229 
01-19 16:42:07.449: I/IJKMEDIA(28607): VideoCodec: avcodec, hevc
01-19 16:42:07.449: W/IJKMEDIA(28607): fps: 60.000000 (too high)
01-19 16:42:07.449: D/IJKMEDIA(28607): FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
01-19 16:42:07.449: D/IJKMEDIA(28607): FFP_MSG_SAR_CHANGED: 0, 1
01-19 16:42:07.449: D/IJKMEDIA(28607): ijkmp_get_msg: FFP_MSG_PREPARED
01-19 16:42:07.449: D/IJKMEDIA(28607): FFP_MSG_PREPARED:
01-19 16:42:07.449: D/IJKMEDIA(28607): IjkMediaPlayer_start
01-19 16:42:07.449: D/IJKMEDIA(28607): ijkmp_start()
01-19 16:42:07.449: D/IJKMEDIA(28607): ijkmp_start()=0
01-19 16:42:07.449: D/IJKMEDIA(28607): IjkMediaPlayer_start
01-19 16:42:07.449: D/IJKMEDIA(28607): ijkmp_start()
01-19 16:42:07.449: D/IJKMEDIA(28607): ijkmp_start()=0
01-19 16:42:07.449: D/IJKMEDIA(28607): ijkmp_get_msg: FFP_REQ_START
01-19 16:42:07.449: I/IJKMEDIA(28607): SDL_RunThread: [28728] ff_video_dec
01-19 16:42:07.549: D/IJKMEDIA(28607): ijkmp_get_msg: FFP_REQ_START
01-19 16:42:07.779: D/IJKMEDIA(28607): SDL_VoutFFmpeg_CreateOverlay(w=1280, h=720, fmt=RV32(0x32335652, dp=0x66cea990)
01-19 16:42:07.779: D/IJKMEDIA(28607): FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
01-19 16:42:07.799: D/IJKMEDIA(28607): Video: first frame decoded
01-19 16:42:07.809: D/IJKMEDIA(28607): ANativeWindow_setBuffersGeometry: w=1280, h=720, f=(0x4) => w=1280, h=720, f=RV32(0x32335652)
01-19 16:42:07.839: D/IJKMEDIA(28607): FFP_MSG_VIDEO_RENDERING_START:
01-19 16:42:07.839: D/IJKMEDIA(28607): SDL_VoutFFmpeg_CreateOverlay(w=1280, h=720, fmt=RV32(0x32335652, dp=0x66cea990)
01-19 16:42:07.839: D/IJKMEDIA(28607): FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
01-19 16:42:07.839: D/IJKMEDIA(28607): avcodec/Audio: first frame decoded
01-19 16:42:07.849: D/IJKMEDIA(28607): FFP_MSG_AUDIO_RENDERING_START:
01-19 16:42:07.879: D/IJKMEDIA(28607): FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720
01-19 16:42:07.879: D/IJKMEDIA(28607): SDL_VoutFFmpeg_CreateOverlay(w=1280, h=720, fmt=RV32(0x32335652, dp=0x66cea990)

**Comment by bbcallen** [comment]
Sorry, I'm not familiar with HEVC.
That's to say I can't maintain HEVC related feature.
Maybe you could @chodison to see if he would help.

**Comment by Long888** [comment]
@chodison How to use mediacodec to play HEVC？

**Comment by Long888** [comment]
我已经搞定了

**Comment by andyjmzheng** [comment]
@Long888  如何搞定的？可以简单描述下吗？谢谢！

**Comment by chq1314** [comment]
@Long888 How to play hevc ?

**Comment by Long888** [comment]
把 ijkmedia/ijkplayer/android/pipeline/ffpipenode_android_mediacodec_vdec.c 这个文件里 case AV_CODEC_ID_HEVC: 下面的这几行代码去掉就可以了
   if (!ffp->mediacodec_hevc && !ffp->mediacodec_all_videos) {
            ALOGE("%s: MediaCodec/HEVC is disabled. codec_id:%d \n", __func__, opaque->avctx->codec_id);
            goto fail;
        }

**Comment by Long888** [comment]
不过还有bug，就是有些机型在播放HEVC视频时，从高分辨率切换到低分辨率的视频会出现有声音无画面的情况

**Comment by Long888** [comment]
@chodison 能把你的联系方式告诉我吗，我有几个问题想向你请教一下

**Comment by andyjmzheng** [comment]
@Long888  你有hevc码流的播放地址吗？你是自己搭建的播放环境吗？

**Comment by Long888** [comment]
自己搭建的测试环境

**Comment by andyjmzheng** [comment]
@Long888  那你是用ffmpeg 发hevc的流到服务器吗？是nginx的服务器吗？

**Comment by Long888** [comment]
不是，自己写的服务器

**Comment by andyjmzheng** [comment]
恩。

**Comment by Android4MediaPlayer** [comment]
目前有什么问题呢？

**Comment by andyjmzheng** [comment]
@Android4MediaPlayer 我现在想测试hevc的播放。我用的nginx的服务器。但是现在往nginx发hevc的流的时候。就发不过去。不知道nginx.conf怎么修改。网上没有找到相关的资料。所以不能测试hevc。

**Comment by Long888** [comment]
在amlogic 平台用ijklib 硬解HEVC时，过几个小时就会出现画面不动的情况。还有如果用exoplayer硬解H264，就不会不出画面，硬解HEVC反而是正常的，在其它平台测试都是正常的，这个问题你们能不能解决

**Comment by Android4MediaPlayer** [comment]
Any log？

**Comment by iTony** [comment]
ijkMediaPlayer.setOption(
                        IjkMediaPlayer.OPT_CATEGORY_PLAYER,
                        "mediacodec-hevc", 1);  // is "mediacodec-hevc", not "mediacodec_hevc"
