### ISSUE TITLE
关于ios硬解

### ISSUE THREAD

**Issue by hailing0921** [Bilibili/ijkplayer#856]
请问ios怎么用硬解并且自动旋转？
[options setPlayerOptionIntValue:1      forKey:@"mediacodec"];
    [options setPlayerOptionIntValue:1      forKey:@"mediacodec_auto_rotate"];
我用这两个没效果？不是这个么？

**Comment by bbcallen** [comment]
mediacodec is only valid on android.

**Comment by hailing0921** [comment]
我在ios上播放一个七秒左右的视频，实际播放时间大概有10秒了，怎么办

**Comment by yeshibuzhong** [comment]
同求ios硬解   怎么做
