### ISSUE TITLE
how to change the video quality?any suggestion?

### ISSUE THREAD

**Issue by muximus3** [Bilibili/ijkplayer#857]

**Comment by muximus3** [comment]
Is there any interface to change video quality ?

**Comment by bbcallen** [comment]
Video quality is determined when being encoded.
I don't think it can be changed by player.

**Comment by muximus3** [comment]
tks, so if i want to switch quality in app, which way would work, change the source url or  change the encoding mode?  how can i make it with ijkplayer Lib?

**Comment by bbcallen** [comment]
ijkplayer is only a playback library, it has nothing to do with encoding, for now.
