### ISSUE TITLE
not android6.0 , change play speed

### ISSUE THREAD

**Issue by iwakevin** [Bilibili/ijkplayer#859]

**Comment by martji** [comment]
Android 6.0 以下的版本能否支持加速播放，1.5X 2X 之类？

**Comment by bbcallen** [comment]
No.

**Comment by yangwuan55** [comment]
I have fix this problem(Including the problem of sound) at exoplayer.
Hope useful to you.[See here](https://github.com/yangwuan55/ExoPlayer)
