### ISSUE TITLE
Hi ，ijkplayer怎么将高分辨率的视频缩放。

### ISSUE THREAD

**Issue by yyl7886908** [Bilibili/ijkplayer#86]
Hi， 你好

ijkplayer怎么将高分辨率的视频缩放，例如视频的分辨率是1280x720 ，我想在500x600的空间来显示，不想让视频全屏，这个功能怎么做到。

我修改过videoview里面的一些高度和宽度，但是视频在播放的时候又恢复了

谢谢

**Comment by Catherine0728** [comment]
How to do it?now i have the same problem that needs to be solved!

**Comment by limeng10086** [comment]
@yyl7886908 请问您是怎么解决分辨率问题的，我的都是显示不全的问题

**Comment by fadaixiaohai** [comment]
我有点疑问，视频缩放你不按照比例来，不会变形吗

**Comment by Lscyzq** [comment]
I made it! I made a videoplayer named aliang-media. You can see the project on my profile.
