### ISSUE TITLE
发现在Mali 400 GPU上播放有严重的音画不同步的现象

### ISSUE THREAD

**Issue by renlong** [Bilibili/ijkplayer#860]
请问大家有遇到过同样的问题么？

**Comment by renlong** [comment]
我尝试了4款Mali 400 GPU的设备，小米盒子1、天猫魔盒1s、海美迪H7一代 、英菲克i7。使用时都出现了严重音画不同步的问题。
但尝试了Mali 450 GPU的盒子（如小米增强版）就表现的非常好。

@bbcallen 请问你需要更多什么样的信息呢？

**Comment by bbcallen** [comment]
Why don't you use android.media.MediaPlayer directly?
It should support nearly all formats on all these devices, and perform much better than ijkplayer.

**Comment by renlong** [comment]
@bbcallen  Yes. I know.
But i want to use some other way to play video. I like ijkpalyer, it play well on most of devices.
I just fount so problem on Mali 400 GPU, i don't know how to deal with it. so i ask for you help.
Could you have some plan to deal with this problem? or you need which kind of information?

**Comment by bbcallen** [comment]
No, I would use android.media.MediaPlayer on such devices (TV, TV box) even in my own application.
You can try enable MediaCodec, but I doubt if it would work well.

**Comment by renlong** [comment]
All right.
I will find some other way to deal with it.
Thanks for you help.

**Comment by sunzhilei** [comment]
你好，我也在用IJKPlayer做TV端的播放器，也遇到了一些兼容问题，是否有机会讨论一下？我的微信号sun_zhilei

**Comment by sunzhilei** [comment]
你好，我也在用IJKPlayer做TV端的播放器，也遇到了很多奇葩的问题，是否有机会讨论一下？
