### ISSUE TITLE
disable filters

### ISSUE THREAD

**Issue by kengabc** [Bilibili/ijkplayer#862]
I want to disable all the filters since I don't need any filter. as following:
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-filters"
but the video is preparing all the time after do that. Is there any way to disable parts of filters as to reduce the package size.

**Comment by bbcallen** [comment]
```
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-avfilter"
```

**Comment by kengabc** [comment]
After run ./compile-ffmpeg.sh armv7a
it causes error when disable avfilter 

arm-linux-androideabi-gcc: error: libavfilter/*.o: No such file or directory

any solution?

**Comment by bbcallen** [comment]
Modify the script, and remove all link to libavfilter/*.o
