### ISSUE TITLE
error compilation  libyuv.h

### ISSUE THREAD

**Issue by msdos2** [Bilibili/ijkplayer#863]
ijkplayer-armv7a/src/main/jni/ijkmedia/ijksdl/ffmpeg/abi_all/image_convert.c:25:20: fatal error: libyuv.h: No such file or directory
 #include "libyuv.h"
                    ^
compilation terminated.
make: *** [ijkplayer-android/android/ijkplayer/ijkplayer-armv7a/src/main/obj/local/armeabi-v7a/objs/ijksdl/ffmpeg/abi_all/image_convert.o] Error 1
/ijkplayer-android/android

**Comment by cani1see** [comment]
Build Android

cd ..
./compile-ijk.sh all  

[log.txt](https://github.com/Bilibili/ijkplayer/files/160072/log.txt)

**Comment by bbcallen** [comment]
Did you run ./init-android.sh successfully?

**Comment by cani1see** [comment]
@bbcallen  yes

**Comment by cani1see** [comment]
@bbcallen 
./compile-ffmpeg.sh all >compile-ffmpeg.log.txt 2>compile-ffmpeg-warning.log.txt

[compile-ffmpeg-warning.log.txt](https://github.com/Bilibili/ijkplayer/files/162425/compile-ffmpeg-warning.log.txt)
[compile-ffmpeg.log.txt](https://github.com/Bilibili/ijkplayer/files/162424/compile-ffmpeg.log.txt)

**Comment by bbcallen** [comment]
I would ask again.
Did you run ./init-android.sh SUCCESSFULLY?

**Comment by cani1see** [comment]
@bbcallen yes ./init-android.sh  init-android-libyuv.sh part:


== pull libyuv base ==
Fetching origin
/Users/canixsee/test/ijkplayer
== pull libyuv fork ==
Fetching origin
/Users/canixsee/test/ijkplayer
Already on 'ijk-r0.2.1-dev'
Your branch is up-to-date with 'origin/ijk-r0.2.1-dev'.
/Users/canixsee/test/ijkplayer

**Comment by bbcallen** [comment]
Try
```
cd /Users/canixsee/test/ijkplayer/ijkplayer/android/ijkplayer/ijkplayer-armv7a/src/main/jni/
rm ijkmedia
ln -s ../../../../../../ijkmedia
```

**Comment by cani1see** [comment]
@bbcallen that works
