### ISSUE TITLE
No Video Only Audio

### ISSUE THREAD

**Issue by raisam** [Bilibili/ijkplayer#864]
Hii I installed latest version in my app but my few users facing "only Audion No Video" Problem how to solve this any suggestion

Thanks in advance

**Comment by raisam** [comment]
what type of information you need sir???

**Comment by bbcallen** [comment]
Like this.
https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html

**Comment by raisam** [comment]
I just sent a mail to you on
dev.exoplayer@gmail.com

Please reply on my mail
raisam945@gmail.com

Thanks

**Comment by bbcallen** [comment]
dev.exoplayer@gmail.com belongs to exoplayer project, not ijkplayer project.

**Comment by raisam** [comment]
Then please reply to my mail or share your mail address

My email id is
Raisam945@gmail.com
