### ISSUE TITLE
播放rtmp，如何修改缓存buffer？

### ISSUE THREAD

**Issue by chq1314** [Bilibili/ijkplayer#865]
RT

**Comment by chq1314** [comment]
安卓端

**Comment by bbcallen** [comment]
Sorry, I'm not familiar with rtmp,
But you can search issues about "rtmp", "buffer", to see if there is anything may help.

**Comment by 307509256** [comment]
ijk的缓冲buffer是多少？

**Comment by bbcallen** [comment]
ijkplayer doesn't set this value, that's to say, it's the default value set by libavformat.

**Comment by 307509256** [comment]
但是jni应该是有缓冲区的设定的吧，rtmp协议层是ffmpeg去设定

**Comment by 307509256** [comment]
是否是这个：    ffp->max_high_water_mark_in_ms      = DEFAULT_MAX_HIGH_WATER_MARK_IN_MS;

**Comment by chq1314** [comment]
http://www.cutv.com/demo/live_test.swf 
这个flash是可以播放rtmp源的，里面有个buffer_time，感觉是起作用的
所以才想到是否手机端可以修改这个buffer_time
