### ISSUE TITLE
Android 播放过程中自动暂停

### ISSUE THREAD

**Issue by Asa-Walker** [Bilibili/ijkplayer#867]
如题

log：
01-22 16:00:06.333 10948-9061/com.fxtv.threebears W/IJKMEDIA: No trailing CRLF found in HTTP header.
01-22 16:00:06.333 10948-9061/com.fxtv.threebears W/IJKMEDIA: Failed to open segment of playlist 0
01-22 16:00:06.333 10948-9061/com.fxtv.threebears E/IJKMEDIA: missing picture in access unit with size 2208
01-22 16:01:42.253 10948-9086/com.fxtv.threebears E/IJKMEDIA: no frame!
01-22 16:01:43.343 10948-9059/com.fxtv.threebears D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_COMPLETED
01-22 16:01:43.343 10948-9059/com.fxtv.threebears D/IJKMEDIA: FFP_MSG_COMPLETED:
01-22 16:01

**Comment by bbcallen** [comment]
```
01-22 16:00:06333 10948-9061/comfxtvthreebears W/IJKMEDIA: Failed to open segment of playlist 0
```
