### ISSUE TITLE
why did the ijkplayer decoded video with lots of mosaic (Android armv5)

### ISSUE THREAD

**Issue by scientt** [Bilibili/ijkplayer#868]
Hello all:
    I compiled the ijkplayer and run it in Android cellphone,  but there is a lot of mosaic in the decoded rtmp video stream. I captured a picture, attached in this issue.
![mosaic](https://cloud.githubusercontent.com/assets/16849767/12529419/11056612-c1f0-11e5-85b1-f2ece1ba22a9.jpg)

    How can I adjust the parameters to erase the mosaic, to improve the quality of the decoded video? any suggestions?

**Comment by scientt** [comment]
by the way, this is the url of the video: http://s3.cn-north-1.amazonaws.com.cn/xvs/pub/FDXUPKRX/20160106/06/35/m3u8/aws-cn_north_1-5-fc2b82d4f6edc9e5.m3u8

**Comment by bbcallen** [comment]
Try set codec option skip-loopfilter = 0.
But I doubt if armv5 is fast enough for that.

**Comment by scientt** [comment]
It works!!  thanks a lot. @bbcallen
