### ISSUE TITLE
Is there any way to keep the rtmp decode latency always in less than 4 seconds?

### ISSUE THREAD

**Issue by scientt** [Bilibili/ijkplayer#869]
I added 2 options in  VideoView.openVideo()  function:

ijkMediaPlayer.setAvFormatOption("analyzeduration", "2000000");
ijkMediaPlayer.setAvFormatOption("probesize", "4096");

The decode latency is 3 seconds in the begining (without the options above, the latency is more than 5 seconds in begining), but after about 5 minutes the latency changed to 11 seconds. Unacceptable in my system.

How can I do to keep the latency always in less than 4 seconds (Discard frames in buffer?)  Any parameters related to this latency? Do I have to change the ffmpeg source code?

**Comment by bbcallen** [comment]
No parameters, for now.
But you can try librtmp.

**Comment by scientt** [comment]
Thank you four your reply. @bbcallen

**Comment by scientt** [comment]
Sorry , I have to start this issue again, @bbcallen Do you mean librtmp.c? I can find the librtmp.c in folder ijkplayer-k0.2.4/android/ffmpeg-armv5/libavformat, but this file is not involved in the compile scripts. (I analyzed the output information of compile-ffmpeg.sh armv5 and compile-ijk.sh armv5 nothing to do with librtmp.c :
CC	libavformat/rtmphttp.o
CC	libavformat/rtmppkt.o
CC	libavformat/rtmpproto.o)

**Comment by bbcallen** [comment]
Try google ffmpeg librtmp.
It's not included in ijkplayer, for now.

**Comment by scientt** [comment]
OK, thanks a lot.

**Comment by fukemy** [comment]
hello. 
@scientt  do you solve this? I dont know how to use librtmp.c? Can you provide some ways? Thanks a lo
