### ISSUE TITLE
关于SDL

### ISSUE THREAD

**Issue by yippeesoft** [Bilibili/ijkplayer#871]
感谢你的开源工作，只是不大明白SDL2已经支持android，好像采用的EGL，为什么还要做个LIBSDL采用mediaextractor?

**Comment by bbcallen** [comment]
I don't think SDL2 supports MediaCodec 0-copy rendering.

**Comment by yippeesoft** [comment]
是的。在SDL上增加了硬解和SURFACEVIEW。
只是我在电视MSTAR芯片上测试 MEDIAPLAY可以播，IJK用 extractor以及txtsurface surfacevie组合都不能播放。UNKNOW或者黑屏有声音。

用SDL2+FFMPEG用http://blog.csdn.net/ashqal/article/details/17640179 例子图像可以显示，暂时还未比对代码，不知道有什么区别。

**Comment by Android4MediaPlayer** [comment]
log?

**Comment by yippeesoft** [comment]
01-27 08:40:32.714: I/IJKMEDIA(4585): ===== versions =====
01-27 08:40:32.714: I/IJKMEDIA(4585): FFmpeg       : ff2.8--ijk0.4.1.1--dev0.3.3--rc4
01-27 08:40:32.714: I/IJKMEDIA(4585): libavutil    : 54.31.100
01-27 08:40:32.714: I/IJKMEDIA(4585): libavcodec   : 56.60.100
01-27 08:40:32.714: I/IJKMEDIA(4585): libavformat  : 56.40.101
01-27 08:40:32.714: I/IJKMEDIA(4585): libswscale   : 3.1.101
01-27 08:40:32.714: I/IJKMEDIA(4585): libswresample: 1.2.101
01-27 08:40:32.714: I/IJKMEDIA(4585): SDL_RunThread: [5502] ff_msg_loop
01-27 08:40:32.714: I/IJKMEDIA(4585): ===== options =====
01-27 08:40:32.714: D/IJKMEDIA(4585): message_loop
01-27 08:40:32.714: I/IJKMEDIA(4585): player-opts : mediacodec                   = 1
01-27 08:40:32.714: I/IJKMEDIA(4585): player-opts : mediacodec-auto-rotate       = 0
01-27 08:40:32.714: I/IJKMEDIA(4585): player-opts : opensles                     = 0
01-27 08:40:32.714: I/IJKMEDIA(4585): player-opts : overlay-format               = 842225234
01-27 08:40:32.714: I/IJKMEDIA(4585): player-opts : framedrop                    = 1
01-27 08:40:32.714: I/IJKMEDIA(4585): player-opts : start-on-prepared            = 0
01-27 08:40:32.714: I/IJKMEDIA(4585): format-opts : ijkinject-opaque             = 622855354
01-27 08:40:32.714: I/IJKMEDIA(4585): format-opts : http-detect-range-support    = 0
01-27 08:40:32.714: I/IJKMEDIA(4585): codec-opts  : skip_loop_filter             = 48
01-27 08:40:32.714: I/IJKMEDIA(4585): ===================
01-27 08:40:32.714: D/IJKMEDIA(4585): FFP_MSG_FLUSH:
01-27 08:40:32.719: I/IJKMEDIA(4585): SDL_RunThread: [5503] ff_vout
01-27 08:40:32.719: D/IJKMEDIA(4585): ijkmp_prepare_async()=0
01-27 08:40:32.719: I/IJKMEDIA(4585): SDL_RunThread: [5504] ff_read
01-27 08:40:32.809: D/IJKMEDIA(4585): Statistics: 1048576 bytes read, 0 seeks
01-27 08:40:32.809: E/IJKMEDIA(4585): /storage/sdcard0/mwwyt.mpg: Invalid data found when processing input
