### ISSUE TITLE
seems memory leak here

### ISSUE THREAD

**Issue by remantou** [Bilibili/ijkplayer#875]
<img width="1006" alt="2016-01-25 17 09 14" src="https://cloud.githubusercontent.com/assets/8045375/12546701/88e93c8e-c386-11e5-9564-3e4edd5146b4.png">
<img width="1011" alt="2016-01-25 17 11 27" src="https://cloud.githubusercontent.com/assets/8045375/12546728/b7297d3e-c386-11e5-88fa-bdc2e557bc69.png">

**Comment by bbcallen** [comment]
I can see this. But I don't know where it leaks, do you?
