### ISSUE TITLE
最新的ios版0.4.4.1，ios DEMO感觉播放器视频有点卡顿

### ISSUE THREAD

**Issue by zoujoe7750** [Bilibili/ijkplayer#877]
最近编译了最新版本的ijk ios版本，发现播放视频时虽然能够正常播放，但是有点小卡卡的感觉，不是很流畅。开始以为是模拟器的问题，后来安装到真机之后发现还是一个样子。

**Comment by zoujoe7750** [comment]
这种现象用语言很难描述，我录制了一个视频
原视频地址：http://krtv.qiniudn.com/150522nextapp
iphone6s录制视频：http://ac-fe4k124b.clouddn.com/b287cc24c095b62f.mov
用iphone网页浏览视频和用ijkdemo播放视频时，感觉ijk播放明显比较卡。

**Comment by bbcallen** [comment]
Try
```
    [self setOptionIntValue:IJK_AVDISCARD_DEFAULT forKey:@"skip_frame" ofCategory:kIJKFFOptionCategoryCodec];
    [self setOptionIntValue:IJK_AVDISCARD_DEFAULT forKey:@"skip_loop_filter" ofCategory:kIJKFFOptionCategoryCodec];
```

**Comment by zoujoe7750** [comment]
真机：可以完美解决，很流畅。
模拟器：貌似就更卡了。

 IJKFFOptions *options = [IJKFFOptions optionsByDefault];
 [options setOptionIntValue:IJK_AVDISCARD_DEFAULT forKey:@"skip_frame" ofCategory:kIJKFFOptionCategoryCodec];
 [options setOptionIntValue:IJK_AVDISCARD_DEFAULT forKey:@"skip_loop_filter" ofCategory:kIJKFFOptionCategoryCodec];

**Comment by nicolasiJasica** [comment]
m
