### ISSUE TITLE
does ijkplayer support api below 23?

### ISSUE THREAD

**Issue by lijingchang** [Bilibili/ijkplayer#879]

**Comment by bbcallen** [comment]
Why not?

**Comment by xiangding1983** [comment]
如果用22的时候，ijkpayer打包会报这个错：

Warning:u.aly.bt: can't find referenced method 'int checkSelfPermission(java.lang.String)' in library class android.content.Context
Error:Execution failed for task ':app:shrinkAll32ReleaseMultiDexComponents'.
> java.io.IOException: The output jar [K:\baidusync\qq\Max-Android\app\build\intermediates\multi-dex\all32\release\componentClasses.jar] must be specified after an input jar, or it will be empty.

**Comment by bbcallen** [comment]
I don't think u.aly.bt is a package name used in ijkplayer.
