### ISSUE TITLE
你好 我pod报错，怎么解决呢？

### ISSUE THREAD

**Issue by hhb19900618** [Bilibili/ijkplayer#880]
[!] Unable to find a specification for `ijkplayer (~> 0.3.2-rc.2)`

**Comment by bbcallen** [comment]
I haven't support pod, yet

**Comment by hhb19900618** [comment]
那怎么办呢？  请问您这个demo能否支持播放本地 m3u8视频文件吗？急于求助

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer#build-ios

**Comment by hhb19900618** [comment]
你说你这demo 支持本地m3u8文件的播放？
