### ISSUE TITLE
Can we decrease the rtmp latency by changing the play speed?

### ISSUE THREAD

**Issue by scientt** [Bilibili/ijkplayer#882]
Can we decrease the rtmp latency by changing the play speed?
For example: If the latency is more than 6 seconds, change the playspeed to 1.2 (or more faster) to consum the buffered frames faster, when the latency is decreased to 3 seconds, change the play speed back to 1.0?

**Comment by bbcallen** [comment]
I think it could work.

**Comment by scientt** [comment]
Thank you for your reply. @bbcallen 
So  how to change the play speed? I tried the set_clock_speed(...) in ff_ffplay.c
But the play speed not changed at all.

this is my code:

                playable_dur = ffp_get_playable_duration_l(ffp);
		current_pos = ffp_get_current_position_l(ffp);	
		if (playable_dur-current_pos >3000)
		{
			VideoState *is = ffp->is;		
			set_clock_speed(&is->audclk, 1.5);
		}

HOW  to change the PLAY SPEED?  thank you.

**Comment by bbcallen** [comment]
setPlaybackRate

**Comment by scientt** [comment]
Do we have this API? 
I can't find  string "setPlaybackRate" in the whole ijkplayer-k0.4.4.1 project.

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/search?utf8=✓&q=setPlaybackRate

**Comment by scientt** [comment]
OK,Thank you for your reply, I see the search result, the "setPlaybackRate" only included in IOS, but my program is running on ANDROID devices. 

Is there any way to change rtmp play speed in ANDROID?

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/search?utf8=✓&q=setSpeed&type=Code

**Comment by scientt** [comment]
OK，thank you.

**Comment by scientt** [comment]
Now I can decrease the latency by discard the video frame, and I just discard the Video frame in function get_video_frame()  like this:

static int get_video_frame(FFPlayer *ffp, AVFrame *frame)
{
    VideoState *is = ffp->is;
    int got_picture;

    if ((got_picture = decoder_decode_frame(ffp, &is->viddec, frame, NULL)) < 0)
        return -1;

	
	//Discard frame
	if (g_discard)
	{
		if (!frame->key_frame)
			return 0;
	}

I don't know how to  free the frame, Is there any memory leak?

**Comment by Android4MediaPlayer** [comment]
drop frame

**Comment by scientt** [comment]
av_frame_unref(frame); ?

**Comment by bbcallen** [comment]
yes

**Comment by scientt** [comment]
OK,thanks a lot.

**Comment by MarcSteven** [comment]
So for example if you want to change its speed to 1.5/2/3, how to make it happen?
@scientt  I cannot find the related api to make it happen
