### ISSUE TITLE
does ijkplayer support multiple player in one controller ?

### ISSUE THREAD

**Issue by zwy2937** [Bilibili/ijkplayer#883]
i mean i want to set four player in my controller,but it just one player did play the rtmp video; i am ios developer~how can i let all four player play different video~~~

**Comment by zwy2937** [comment]
and i want to konw how to just play video without sound~~~

**Comment by zwy2937** [comment]
ok ~ i mean i want to let four ijkplayer work in controller and play different video ~~~~but now it just one player work ,and the other three player doesn't play video~~~~~~~

**Comment by bbcallen** [comment]
I don't quite get your idea, Can you show your code?
