### ISSUE TITLE
看到最近的版本更新，加了show download speed，试了一下好像没有用？

### ISSUE THREAD

**Issue by toss156** [Bilibili/ijkplayer#885]
b308b892cf970fceac3a79a51ed7377229a7e28e 这个版本加了show download speed，有几个问题？
 1、这个是获取缓冲时的下载速度的实现吗？
 2、测试了一下在 hub 中一直显示的是 N/A ，要怎么用 ？

**Comment by bbcallen** [comment]
It only shows speed of async protocol.
You can copy this code into other protocols to generate the speed you need.

**Comment by Sunzznn** [comment]
请问你解决问题了吗？

**Comment by Sunzznn** [comment]
How to do？
