### ISSUE TITLE
How to resume the VideoTextureView which extends TextureView?

### ISSUE THREAD

**Issue by jpxiong** [Bilibili/ijkplayer#886]
I do the reconnecting operation in the `VideoView` when play streaming:
play streaming -> `onCompletion` invoked caused by poor network -> `VideoView#start` -> release current player -> create a new player

It works fine on `VideoView`, but not the `VideoTextureView` .

I found if i release the current player in `VideoTextureView`,  the `SurfaceTexture` will be released on some places. I don't think it's a right behavior: `VideoTextureView` owns the `SurfaceTexture`, but destroyed by player bottom layer.

PS: 
1. `VideoTextureView` is a `TextureView` type.
2. `VideoView` is a `SufraceView` type.

Any suggestions? Thanks.

**Comment by bbcallen** [comment]
Can not reproduce in demo, by click 'player' button to switch player.

**Comment by jpxiong** [comment]
How to reConnect in `VideoTextureView` ?

**Comment by bbcallen** [comment]
Take a look at IjkVideoView.java

**Comment by ykglove** [comment]
I solve the problem with call the method "setRenderView(renderView)" after  IjkVideoView.start();
