### ISSUE TITLE
关于音量

### ISSUE THREAD

**Issue by hailing0921** [Bilibili/ijkplayer#888]
我想调整视频播放的音量，把is->audio_volume = SDL_MIX_MAXVOLUME;改为is->audio_volume = SDL_MIX_MAXVOLUME/2;之后为什么没有声音了呢？ios上弄得，android没有试

**Comment by bbcallen** [comment]
http://stackoverflow.com/questions/10286744/how-to-change-device-volume-on-ios-not-music-volume

**Comment by hailing0921** [comment]
void SDL_MixAudio(Uint8*       dst,
                  const Uint8* src,
                  Uint32       len,
                  int          volume)
是不是因为你在这个函数里面什么也没做，所以就没有声音了？

**Comment by bbcallen** [comment]
It is not supported, yet.
