### ISSUE TITLE
ios 画面的质量，色彩上面有色差。原因分析

### ISSUE THREAD

**Issue by wanpiaoyi** [Bilibili/ijkplayer#889]
我在网上找来了一个http://recordcdn.quklive.com:80/broadcast/activity/6348/record.m3u8进行播放，与vlc进行对比，发现ios播放器的色彩渲染、清晰度上面都不如vlc，有比较大的差别，这会是什么原因呢？已经将
[options setCodecOptionIntValue:IJK_AVDISCARD_DEFAULT       forKey:@"skip_loop_filter"];
[options setCodecOptionIntValue:IJK_AVDISCARD_DEFAULT    forKey:@"skip_frame"];
设置了，也设置为硬编码了。
会不会是图像转化的时候，失了清晰度呢？

**Comment by toss156** [comment]
try ：
` [options setCodecOptionIntValue:IJK_AVDISCARD_NONREF forKey:@"skip_loop_filter"];`
` [options setCodecOptionIntValue:IJK_AVDISCARD_NONE forKey:@"skip_frame"];``
or
` [options setCodecOptionIntValue:IJK_AVDISCARD_NONE forKey:@"skip_loop_filter"];`
` [options setCodecOptionIntValue:IJK_AVDISCARD_NONE forKey:@"skip_frame"];``

**Comment by wanpiaoyi** [comment]
这里不能上传图片，我把图片传到了百度知道上了。画面截屏都是视频的最后一帧的图片。
http://zhidao.baidu.com/question/1577243158002309820.html

===== custom modules begin =====
register protocol: async
register protocol: ijkhttphook
register protocol: ijkinject
register protocol: ijklongurl
register protocol: ijksegment
register protocol: ijktcphook
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff2.8--ijk0.4.1.1--dev0.3.3--rc4
ijkmp_set_inject_opaque(0x14e807800)
ijkmp_set_inject_opaque()=void
2016-01-29 11:04:32.639 IJKMediaDemo[6131:1549915] OK setup GL
ijkmp_ios_set_view(glView=0x14e806f20)
ijkmp_ios_set_view(glView=0x14e806f20)=void
ijkmp_set_data_source(url="http://recordcdn.quklive.com:80/broadcast/activity/9454035195697933/record.m3u8")
ijkmp_set_data_source(url="http://recordcdn.quklive.com:80/broadcast/activity/9454035195697933/record.m3u8")=0
ijkmp_prepare_async()
===== versions =====
FFmpeg       : ff2.8--ijk0.4.1.1--dev0.3.3--rc4
libavutil    : 54.31.100
libavcodec   : 56.60.100
libavformat  : 56.40.101
libswscale   : 3.1.101
libswresample: 1.2.101
===== options =====
player-opts : video-pictq-size             = 3
player-opts : overlay-format               = fcc-i420
player-opts : max-fps                      = 30
player-opts : framedrop                    = 0
player-opts : videotoolbox-max-frame-width = 960
player-opts : videotoolbox                 = 1
player-opts : start-on-prepared            = 1
format-opts : ijkinject-opaque             = 5612009472
format-opts : probesize                    = 102400
format-opts : http-tcp-hook                = ijktcphook
format-opts : auto_convert                 = 0
format-opts : timeout                      = 30000000
format-opts : analyzeduration              = 300000
format-opts : headers                      = Referer:http://cloud.quklive.com


format-opts : user-agent                   = QuKanPlayer
format-opts : max_delay                    = 250
format-opts : reconnect                    = 1
format-opts : safe                         = 0
codec-opts  : skip_frame                   = 0
codec-opts  : skip_loop_filter             = 0
===================
ijkmp_prepare_async()=0
ijktcphook tcp://recordcdn.quklive.com:80 (remain)
request: GET /broadcast/activity/9454035195697933/record.m3u8 HTTP/1.1

User-Agent: QuKanPlayer

Accept: */*

Range: bytes=0-

Connection: close

Host: recordcdn.quklive.com:80

Icy-MetaData: 1

Referer:http://cloud.quklive.com




Format hls,applehttp probed with size=2048 and score=100
HLS request for url 'http://recordcdn.quklive.com/broadcast/activity/9454035195697933/20160129/104012_0.ts', offset 0, playlist 0
request: GET /broadcast/activity/9454035195697933/20160129/104012_0.ts HTTP/1.1

User-Agent: QuKanPlayer

Accept: */*

Connection: close

Host: recordcdn.quklive.com

Icy-MetaData: 1

Referer:http://cloud.quklive.com




Format mpegts probed with size=2048 and score=100
stream=0 stream_type=1b pid=100 prog_reg_desc=
stream=1 stream_type=f pid=101 prog_reg_desc=
Before avformat_find_stream_info() pos: 0 bytes read:9744 seeks:0
Increasing reorder buffer to 1
no picture 
All info found
rfps: 19.583333 0.016482
rfps: 19.583333 0.016482
rfps: 19.666667 0.010902
rfps: 19.666667 0.010902
rfps: 19.750000 0.006474
rfps: 19.750000 0.006474
rfps: 19.833333 0.003197
rfps: 19.833333 0.003197
rfps: 19.916667 0.001071
rfps: 19.916667 0.001071
rfps: 20.000000 0.000096
rfps: 20.083333 0.000272
rfps: 20.083333 0.000272
rfps: 20.166667 0.001600
rfps: 20.166667 0.001600
rfps: 20.250000 0.004079
rfps: 20.250000 0.004079
rfps: 20.333333 0.007709
rfps: 20.333333 0.007709
rfps: 20.416667 0.012490
rfps: 20.416667 0.012490
rfps: 20.500000 0.018422
rfps: 20.500000 0.018422
rfps: 40.000000 0.000384
rfps: 60.000000 0.000864
rfps: 80.000000 0.001536
rfps: 120.000000 0.003456
rfps: 240.000000 0.013824
rfps: 59.940060 0.002023
rfps: 59.940060 0.002023
After avformat_find_stream_info() pos: 186496 bytes read:186872 seeks:0 frames:36
Option safe not found.
Before avformat_find_stream_info() pos: 616 bytes read:616 seeks:0
no picture 
Probe buffer size limit of 102400 bytes reached
rfps: 19.000000 0.017547
rfps: 19.000000 0.017547
rfps: 19.083333 0.014818
rfps: 19.083333 0.014818
rfps: 19.166667 0.012320
rfps: 19.166667 0.012320
rfps: 19.250000 0.010053
rfps: 19.250000 0.010053
rfps: 19.333333 0.008017
rfps: 19.333333 0.008017
rfps: 19.416667 0.006212
rfps: 19.416667 0.006212
rfps: 19.500000 0.004638
rfps: 19.500000 0.004638
rfps: 19.583333 0.003294
rfps: 19.583333 0.003294
rfps: 19.666667 0.002181
rfps: 19.666667 0.002181
rfps: 19.750000 0.001300
rfps: 19.750000 0.001300
rfps: 19.833333 0.000649
rfps: 19.833333 0.000649
rfps: 19.916667 0.000229
rfps: 19.916667 0.000229
rfps: 20.000000 0.000040
rfps: 20.083333 0.000081
rfps: 20.083333 0.000081
rfps: 20.166667 0.000354
rfps: 20.166667 0.000354
rfps: 20.250000 0.000857
rfps: 20.250000 0.000857
rfps: 20.333333 0.001591
rfps: 20.333333 0.001591
rfps: 20.416667 0.002557
rfps: 20.416667 0.002557
rfps: 20.500000 0.003753
rfps: 20.500000 0.003753
rfps: 20.583333 0.005179
rfps: 20.583333 0.005179
rfps: 20.666667 0.006837
rfps: 20.666667 0.006837
rfps: 20.750000 0.008726
rfps: 20.750000 0.008726
rfps: 20.833333 0.010845
rfps: 20.833333 0.010845
rfps: 20.916667 0.013196
rfps: 20.916667 0.013196
rfps: 21.000000 0.015777
rfps: 21.000000 0.015777
rfps: 21.083333 0.018589
rfps: 21.083333 0.018589
rfps: 40.000000 0.000158
rfps: 60.000000 0.000356
rfps: 80.000000 0.000632
rfps: 120.000000 0.001422
rfps: 240.000000 0.005689
rfps: 59.940060 0.000574
rfps: 59.940060 0.000574
After avformat_find_stream_info() pos: 616 bytes read:616 seeks:0 frames:10
max_frame_duration: 10.000
Input #0, hls,applehttp, from 'http://recordcdn.quklive.com:80/broadcast/activity/9454035195697933/record.m3u8':
  Duration: 00:00:44.00, start: 0.200000, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0, 10, 1/90000: Video: h264, 2 reference frames ([27][0][0][0] / 0x001B), yuv420p(tv, smpte170m/bt709/bt709, center), 720x1280, 1/180000, 20 tbr, 90k tbn, 180k tbc
    Stream #0:1, 0, 1/90000: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, mono, fltp, 60 kb/s
detected 2 logical cores
Setting 'sample_rate' to value '44100'
Setting 'sample_fmt' to value 'fltp'
Setting 'channels' to value '1'
Setting 'time_base' to value '1/44100'
Setting 'channel_layout' to value '0x4'
tb:1/44100 samplefmt:fltp samplerate:44100 chlayout:0x4
auto-inserting filter 'auto-inserted resampler 0' between the filter 'ffplay_abuffer' and the filter 'ffplay_abuffersink'
query_formats: 2 queried, 0 merged, 3 already done, 0 delayed
Using fltp internally between filters
ch:1 chl:mono fmt:fltp r:44100Hz -> ch:1 chl:mono fmt:s16 r:44100Hz
aout_open_audio()
AudioCodec: avcodec, aac
aout_pause_audio(0)
after scale width 720 height 1280 
m_max_ref_frames 2 
fps: 20.000000 (normal)
2016-01-29 11:04:34.678 IJKMediaDemo[6131:1549915] FFP_MSG_VIDEO_DECODER_OPEN: true
2016-01-29 11:04:34.679 IJKMediaDemo[6131:1549915] FFP_MSG_VIDEO_SIZE_CHANGED: 720, 1280
ijkmp_get_msg: FFP_MSG_PREPARED
2016-01-29 11:04:34.681 IJKMediaDemo[6131:1549915] FFP_MSG_SAR_CHANGED: 0, 1
2016-01-29 11:04:34.681 IJKMediaDemo[6131:1549915] FFP_MSG_PREPARED:
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
2016-01-29 11:04:34.682 IJKMediaDemo[6131:1549915] mediaIsPreparedToPlayDidChange
flushed last keyframe pts 0 
2016-01-29 11:04:34.682 IJKMediaDemo[6131:1549915] loadStateDidChange: QKMPMovieLoadStatePlaythroughOK: 3
2016-01-29 11:04:34.682 IJKMediaDemo[6131:1549915] QKMPMoviePlaybackStateDidChange 1: playing
Audio frame changed from rate:44100 ch:1 fmt:fltp layout:mono serial:-1 to rate:44100 ch:1 fmt:fltp layout:mono serial:1
Setting 'sample_rate' to value '44100'
Setting 'sample_fmt' to value 'fltp'
Setting 'channels' to value '1'
Setting 'time_base' to value '1/44100'
Setting 'channel_layout' to value '0x4'
tb:1/44100 samplefmt:fltp samplerate:44100 chlayout:0x4
auto-inserting filter 'auto-inserted resampler 0' between the filter 'ffplay_abuffer' and the filter 'ffplay_abuffersink'
query_formats: 2 queried, 0 merged, 3 already done, 0 delayed
Using fltp internally between filters
0.707107 
0.707107 
ch:1 chl:mono fmt:fltp r:44100Hz -> ch:2 chl:stereo fmt:s16 r:44100Hz
after scale width 720 height 1280 
SDL_VoutVideoToolBox_CreateOverlay(w=720, h=1280, fmt=_VTB(0x4254565f, dp=0x14d5d7930)
Video: first frame decoded
2016-01-29 11:04:34.729 IJKMediaDemo[6131:1549915] FFP_MSG_VIDEO_SIZE_CHANGED: 720, 1280
2016-01-29 11:04:34.734 IJKMediaDemo[6131:1550110] OK use NV12 GL renderer
2016-01-29 11:04:34.736 IJKMediaDemo[6131:1549915] FFP_MSG_VIDEO_SIZE_CHANGED: 720, 1280
2016-01-29 11:04:34.757 IJKMediaDemo[6131:1550110] OK setup GL programm
2016-01-29 11:04:34.763 IJKMediaDemo[6131:1550110] OK setup GL framebuffer 1334:750
avcodec/Audio: first frame decoded
2016-01-29 11:04:34.765 IJKMediaDemo[6131:1549915] FFP_MSG_AUDIO_RENDERING_START:
SDL_VoutVideoToolBox_CreateOverlay(w=720, h=1280, fmt=_VTB(0x4254565f, dp=0x14d5d7930)
2016-01-29 11:04:34.776 IJKMediaDemo[6131:1549915] FFP_MSG_VIDEO_RENDERING_START:
SDL_VoutVideoToolBox_CreateOverlay(w=720, h=1280, fmt=_VTB(0x4254565f, dp=0x14d5d7930)
2016-01-29 11:04:34.783 IJKMediaDemo[6131:1549915] FFP_MSG_VIDEO_SIZE_CHANGED: 720, 1280
2016-01-29 11:04:36.120 IJKMediaDemo[6131:1549915] QKMPMoviePlaybackStateDidChange 4: seeking
ijkmp_seek_to(43170)
ijkmp_seek_to(43170)=0
ijkmp_get_msg: FFP_REQ_SEEK
stream_seek 43370000(43170) + 200000, 
ijkmp_get_msg: FFP_REQ_SEEK: seek to 43170
ffp_toggle_buffering_l: start
aout_pause_audio(1)
HLS request for url 'http://recordcdn.quklive.com/broadcast/activity/9454035195697933/20160129/104054_4.ts', offset 0, playlist 0
2016-01-29 11:04:36.161 IJKMediaDemo[6131:1549915] FFP_MSG_BUFFERING_START:
2016-01-29 11:04:36.162 IJKMediaDemo[6131:1549915] loadStateDidChange: QKMPMovieLoadStateStalled: 4
ijkmp_get_msg: FFP_MSG_SEEK_COMPLETE
2016-01-29 11:04:36.162 IJKMediaDemo[6131:1549915] FFP_MSG_SEEK_COMPLETE:
request: GET /broadcast/activity/9454035195697933/20160129/104054_4.ts HTTP/1.1

User-Agent: QuKanPlayer

Accept: */*

Connection: close

Host: recordcdn.quklive.com

Icy-MetaData: 1

Referer:http://cloud.quklive.com




2016-01-29 11:04:36.522 IJKMediaDemo[6131:1549915] FFP_MSG_BUFFERING_QUEUE_INFO:
ffp_toggle_buffering_l: end
aout_pause_audio(0)
flushed last keyframe pts 211320 
2016-01-29 11:04:36.739 IJKMediaDemo[6131:1549915] FFP_MSG_BUFFERING_END:
2016-01-29 11:04:36.740 IJKMediaDemo[6131:1549915] loadStateDidChange: QKMPMovieLoadStatePlaythroughOK: 3
2016-01-29 11:04:36.740 IJKMediaDemo[6131:1549915] QKMPMoviePlaybackStateDidChange 1: playing
after scale width 720 height 1280 
Audio frame changed from rate:44100 ch:1 fmt:fltp layout:mono serial:1 to rate:44100 ch:1 fmt:fltp layout:mono serial:2
Setting 'sample_rate' to value '44100'
Setting 'sample_fmt' to value 'fltp'
Setting 'channels' to value '1'
Setting 'time_base' to value '1/44100'
Setting 'channel_layout' to value '0x4'
tb:1/44100 samplefmt:fltp samplerate:44100 chlayout:0x4
auto-inserting filter 'auto-inserted resampler 0' between the filter 'ffplay_abuffer' and the filter 'ffplay_abuffersink'
query_formats: 2 queried, 0 merged, 3 already done, 0 delayed
Using fltp internally between filters
0.707107 
0.707107 
ch:1 chl:mono fmt:fltp r:44100Hz -> ch:2 chl:stereo fmt:s16 r:44100Hz
aout_pause_audio(1)
ffp_toggle_buffering: completed: OK
ijkmp_get_msg: FFP_MSG_COMPLETED
2016-01-29 11:04:38.810 IJKMediaDemo[6131:1549915] QKMPMoviePlaybackStateDidChange 0: stoped
2016-01-29 11:04:38.811 IJKMediaDemo[6131:1549915] playbackStateDidChange: QKMPMovieFinishReasonPlaybackEnded: 0
2016-01-29 11:04:38.811 IJKMediaDemo[6131:1549915] QKMPMoviePlaybackStateDidChange 0: stoped
ffp_toggle_buffering: eof

**Comment by wanpiaoyi** [comment]
我看了 编码设置的是fcc-i420，文档里的bpp=12，而FCC_RV32的bpp=24，这里出现了色差？

**Comment by bbcallen** [comment]
Sorry, I've no idea.
And I really can't see the difference in the images.

**Comment by wanpiaoyi** [comment]
在ios设置硬编码的时候 设置了kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange这个参数，编码出来的图片色彩上根源图略有色差，修改为kCVPixelFormatType_420YpCbCr8BiPlanarFullRange就没有色差了

**Comment by wanpiaoyi** [comment]
总算找到原因了

**Comment by beamlee** [comment]
请问要具体设置 IJKFFOptions的什么参数才能没有色差？
