### ISSUE TITLE
onsurfaceChange多次执行，且在未点击的情况下变换了width以及height的参数大小

### ISSUE THREAD

**Issue by Catherine0728** [Bilibili/ijkplayer#891]

**Comment by Catherine0728** [comment]
当两个视频进行切换时，在未操作大小的情况下，他的sizechange呗触动了，且大小还变成了屏幕的而分子一是。。。

**Comment by Catherine0728** [comment]
[http://192.168.0.139:8082/attachments/528/Screenshot_2015-11-20-14-23-47.png](url) like this
http://192.168.0.139:8082/attachments/529/Screenshot_2015-11-20-14-33-16.png
http://192.168.0.139:8082/attachments/784/14.jpeg
这是两个播放视频的Frgment，然后放在ViewPager中，然后播完了上一个视频，滑动viewpager进入下一个播放视频的Fragment的时候，就会存在这种现象，双击屏幕缩小surfaceview的时候，就回有上一篇的视频出现在当前页面，且我在监听surfaceview的变化事件的时候，发现他自己在我没有对屏幕做任何操作的时候，竟然也会触发     IRenderView.IRenderCallback mSHCallback = new IRenderView.IRenderCallback() {
         @Override
         public void onSurfaceChanged(@NonNull IRenderView.ISurfaceHolder holder, int format, int w, int h) {
             if (holder.getRenderView() != mRenderView) {
                 Log.e(TAG, "onSurfaceChanged: unmatched render callback\n");
                 return;
             }

             boolean isValidState = (mTargetState == STATE_PLAYING);
             boolean hasValidSize = !mRenderView.shouldWaitForResize() || (mVideoWidth == w && mVideoHeight == h);
             if (mMediaPlayer != null && isValidState && hasValidSize) {
这里的onSurfaceChanged。这个问题已经耽搁很久了！希望LZ看到能继续跟进，一起探讨。。。。谢谢

**Comment by bbcallen** [comment]
Can't open your png files.

**Comment by Catherine0728** [comment]
那要怎么给你效果图呢？我觉得效果图比我更能解释这些情况！方便其它沟通渠道？

**Comment by Catherine0728** [comment]
?

**Comment by Catherine0728** [comment]
http://www.cnblogs.com/Catherine-Brain/p/5210653.html这样吧，你要是不方便，我把这个问题放到这个网页上去了，您能方便看看么，数在下愚昧，真的很希望能得到解决。。。。。

**Comment by Catherine0728** [comment]
http://q.cnblogs.com/q/79939/

**Comment by bbcallen** [comment]
I don't understand your question at all.
Which problem is your real concern? onSurfaceChange()? Last image remains? Broken picture?

**Comment by Catherine0728** [comment]
我关心的是为什么出现了以上图片的那种情况，不是破碎的图片，是上一个视频的画面
场景是这样的，两个视频进行滑动切换，滑到第二个页面的时候，然后双击页面，页面变小的时候，出现了上一个页面的画面

**Comment by bbcallen** [comment]
Did you reuse same SurfaceView or same Player

**Comment by Catherine0728** [comment]
您是说重复使用对吧？目前是这样的，两个fragemnt用的是同一个布局，然后滑倒当前页面的时候，上一个页面并未销毁，所以，这个应该算重复使用吧！

**Comment by bbcallen** [comment]
That's why last frame remains there.

**Comment by Catherine0728** [comment]
可是我觉得这个跟控件一样吧，不是同一个页面，难道会用同一块内存下的东西？

**Comment by Catherine0728** [comment]
这里怎么才能不重复使用同一个SufaceView

**Comment by bbcallen** [comment]
new a new SurfaceView()

**Comment by Catherine0728** [comment]
还是同样的状况，所以我现在选择在页面创建videoview，然后不可见的时候移除，可见的时候再添加，这样就妥了。。。因为其他方法暂时真的没能解决这个问题，无论怎么样，还是谢谢
