### ISSUE TITLE
android, multicast udp have no audio!

### ISSUE THREAD

**Issue by karr1234** [Bilibili/ijkplayer#894]
This is my test ts file, i test the stream with a PC install VLC to stream UDP in a LAN, and use android box to play the stream with udp://224.0.0.1:1234.The ts file is:
http://58.99.32.133:8080/vlc_test/test_ts.ts

that have two problem:
(1)the video is fine, but audio is miss
(2)loading to long, every time to open the stream, take 5~10 sec. 

Help me to solve the problem.

**Comment by bbcallen** [comment]
If you can't play it well with VLC, why do you ask ijkplayer for help?

**Comment by karr1234** [comment]
sorry, the UDP stream is using the file from VLC, that is a streamer.
but, i play the UDP stream is using ijkplayer, that is not have audio.

===========================================================
不好意思，可能我沒表達好，碼流是透過vlc去送出udp。
再用ijkplayer去播放這個udp碼流，不過是沒有聲音，感謝您的回覆。

**Comment by bbcallen** [comment]
Any log?

**Comment by karr1234** [comment]
sorry, late to provide log. 
this is the print log as link.
[http://58.99.32.133:8080/logs/view_log.txt](logs_url)

**Comment by bbcallen** [comment]
```
01-01 13:26:11.570 5084-5142/tv.danmaku.ijk.media.sample I/IJKMEDIA: : Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, s16p, 192 kb/s
01-01 13:26:11.570 5084-5142/tv.danmaku.ijk.media.sample W/IJKMEDIA: No codec could be found with id 86016
```
mp2 codec is not included by default.
https://github.com/Bilibili/ijkplayer#before-build
