### ISSUE TITLE
播放rtmp流时，av_read_frame 读到pkt->duration 一直为0

### ISSUE THREAD

**Issue by linjiansheng** [Bilibili/ijkplayer#897]
ff_ffplay.c::read_thread 线程：
假设：
pkt1->pts = 1400
pkt2->pts = 2000
pkt3->pts = 2500
1, 播放点播视频如mp4是正确的（mp4 box 已存每个pkt的duration），av_read_frame读pkt2，pkt2->duration = pkt3->pts - pkt2->pts = 500
2，播放rtmp流，av_read_frame读到的每一个pkt->duration一直为0，这里是否需要处理一下？
我现在的做法是，记住上一个pkt的pts，如pkt2->duration = pkt2->pts - pkt1->pts

大家有遇到这个问题吗，怎么解决？这个影响videoq和audioq duration值

**Comment by linjiansheng** [comment]
对了，还遇到过一些rtmp流，av_read_frame读到的每一个pkt->duration一直为"帧率"
如video stream timebase为 {1, 1000}，视频帧率为25，pkt->duration 固定为 40，但是这个是不对的，用pkt3->pts - pkt2->pts 算出来的不一样。
加入代码：
```
        // calculate pkt duration, if play realtime stream
        if (is->realtime && pkt_ts != AV_NOPTS_VALUE) {
            if (pkt->stream_index == is->audio_stream) {
                if (audio_pre_pkt_pts > 0) {
                    pkt->duration = pkt_ts - audio_pre_pkt_pts;
                }
                audio_pre_pkt_pts = pkt_ts;
            } else if (pkt->stream_index == is->video_stream) {
                if (video_pre_pkt_pts > 0) {
                    pkt->duration = pkt_ts - video_pre_pkt_pts;
                }
                video_pre_pkt_pts = pkt_ts;
            }
        }
```

**Comment by bbcallen** [comment]
This should be a FFmpeg's issue.
