### ISSUE TITLE
[Android]为什么不支持多实例硬解？

### ISSUE THREAD

**Issue by wqmijkplayer** [Bilibili/ijkplayer#898]
@bbcallen 
你好，我记得你说过硬解不支持多实例。
在android上，硬解是通过mediacodec方式实现的。
从代码可以看见，不同的ijkplayer实例，mediacodec对象也不同。
按理说，是支持多实例的
不支持的原因在哪里呢？

**Comment by bbcallen** [comment]
I didn't say that.
