### ISSUE TITLE
video and audio doesn't capable in few second after player start

### ISSUE THREAD

**Issue by lijingchang** [Bilibili/ijkplayer#901]
log below:
Line 14017: D/IJKMEDIA(26070): Using s16p internally between filters
	Line 14019: I/IJKMEDIA(26070): ch:2 chl:stereo fmt:s16p r:48000Hz -> ch:2 chl:stereo fmt:s16 r:48000Hz
	Line 14021: D/IJKMEDIA(26070): avcodec/Audio: first frame decoded
	Line 14023: D/IJKMEDIA(26070): FFP_MSG_AUDIO_RENDERING_START:
	Line 14027: D/IJKMEDIA(26070): no picture 
	Line 14029: D/IJKMEDIA(26070): no picture 
	Line 14031: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14033: D/IJKMEDIA(26070): Video frame changed from size:0x0 format:none serial:-1 to size:720x576 format:yuv420p serial:1
	Line 14035: D/IJKMEDIA(26070): Setting 'video_size' to value '720x576'
	Line 14037: D/IJKMEDIA(26070): Setting 'pix_fmt' to value '0'
	Line 14039: D/IJKMEDIA(26070): Setting 'time_base' to value '1/90000'
	Line 14041: D/IJKMEDIA(26070): Setting 'pixel_aspect' to value '12/11'
	Line 14043: D/IJKMEDIA(26070): Setting 'frame_rate' to value '25/1'
	Line 14045: I/IJKMEDIA(26070): w:720 h:576 pixfmt:yuv420p tb:1/90000 fr:25/1 sar:12/11 sws_param:
	Line 14047: D/IJKMEDIA(26070): Setting 'out_w' to value 'floor(in_w/2)*2'
	Line 14049: D/IJKMEDIA(26070): Setting 'out_h' to value 'floor(in_h/2)*2'
	Line 14051: D/IJKMEDIA(26070): query_formats: 3 queried, 2 merged, 0 already done, 0 delayed
	Line 14053: I/IJKMEDIA(26070): w:720 h:576 sar:12/11 -> w:720 h:576 sar:12/11
	Line 14055: D/IJKMEDIA(26070): SDL_VoutFFmpeg_CreateOverlay(w=720, h=576, fmt=RV32(0x32335652, dp=0x5c211468)
	Line 14057: D/IJKMEDIA(26070): FFP_MSG_VIDEO_SIZE_CHANGED: 720, 576
	Line 14059: D/IJKMEDIA(26070): Video: first frame decoded
	Line 14061: D/IJKMEDIA(26070): SDL_VoutFFmpeg_CreateOverlay(w=720, h=576, fmt=RV32(0x32335652, dp=0x5c211468)
	Line 14063: D/IJKMEDIA(26070): FFP_MSG_VIDEO_SIZE_CHANGED: 720, 576
	Line 14065: D/IJKMEDIA(26070): ANativeWindow_setBuffersGeometry: w=720, h=576, f=(0x4) => w=720, h=576, f=RV32(0x32335652)
	Line 14067: D/IJKMEDIA(26070): FFP_MSG_VIDEO_RENDERING_START:
	Line 14069: I/tv.danmaku.ijk.media.player.IjkMediaPlayer(26070): Info: MEDIA_INFO_VIDEO_RENDERING_START
	Line 14073: D/IJKMEDIA(26070): FFP_MSG_VIDEO_SIZE_CHANGED: 720, 576
	Line 14075: D/IJKMEDIA(26070): SDL_VoutFFmpeg_CreateOverlay(w=720, h=576, fmt=RV32(0x32335652, dp=0x5c211468)
	Line 14077: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14103: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14107: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14133: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14135: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14137: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14163: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14165: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14167: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14193: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14195: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14221: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14223: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14225: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14253: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14255: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14285: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14287: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14313: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14315: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 14317: I/IJKMEDIA(26070): Current profile doesn't provide more RBSP data in PPS, skipping
	Line 19555: D/IJKMEDIA(30338): JJKLoader: OK: 'java.nio.ByteBuffer' loaded
	Line 19557: D/IJKMEDIA(30338): JJKLoader: OK: 'java.util.ArrayList' loaded
	Line 19559: D/IJKMEDIA(30338): JJKLoader: OK: 'android.os.Build$VERSION' loaded
	Line 19561: D/IJKMEDIA(30338): JJKLoader: OK: 'android.os.Build' loaded
	Line 19563: D/IJKMEDIA(30338): JJKLoader: OK: 'android.media.AudioTrack' loaded
	Line 19565: I/IJKMEDIA(30338): API-Level: 18
	Line 19567: D/IJKMEDIA(30338): JJKLoader: OK: 'android.media.MediaCodec$BufferInfo' loaded
	Line 19569: D/IJKMEDIA(30338): JJKLoader: OK: 'android.media.MediaCodec' loaded
	Line 19571: D/IJKMEDIA(30338): JJKLoader: OK: 'android.media.MediaFormat' loaded
	Line 19573: D/IJKMEDIA(30338): JJKLoader: OK: 'android.os.Bundle' loaded
	Line 19575: D/IJKMEDIA(30338): JJKLoader: OK: 'tv.danmaku.ijk.media.player.IjkMediaPlayer' loaded
	Line 19575: D/IJKMEDIA(30338): JJKLoader: OK: 'tv.danmaku.ijk.media.player.IjkMediaPlayer' loaded
	Line 19577: D/IJKMEDIA(30338): JJKLoader: OK: 'tv.danmaku.ijk.media.player.misc.IMediaDataSource' loaded
	Line 19583: D/IJKMEDIA(30338): IjkMediaPlayer_native_profileBegin
	Line 19583: D/IJKMEDIA(30338): IjkMediaPlayer_native_profileBegin
	Line 19587: D/IJKMEDIA(30338): monstartup: libijkplayer.so
	Line 19925: D/IJKMEDIA(30338): IjkMediaPlayer_native_init
	Line 19925: D/IJKMEDIA(30338): IjkMediaPlayer_native_init
	Line 19927: D/IJKMEDIA(30338): IjkMediaPlayer_native_setup
	Line 19927: D/IJKMEDIA(30338): IjkMediaPlayer_native_setup
	Line 19929: I/IJKMEDIA(30338): av_version_info: ff2.8--ijk0.4.1.1--dev0.3.3--rc4
	Line 19931: D/IJKMEDIA(30338): ffpipeline_create_from_android()
	Line 19933: D/IJKMEDIA(30338): ijkmp_set_inject_opaque(0x1d3002f2)
	Line 19935: D/IJKMEDIA(30338): ijkmp_set_inject_opaque()=void
	Line 19937: D/IJKMEDIA(30338): ijkmp_android_set_mediacodec_select_callback()
	Line 19939: D/IJKMEDIA(30338): ffpipeline_set_mediacodec_select_callback
	Line 19941: D/IJKMEDIA(30338): ijkmp_android_set_mediacodec_select_callback()=void
	Line 19943: D/IJKMEDIA(30338): IjkMediaPlayer_native_setLogLevel(3)
	Line 19943: D/IJKMEDIA(30338): IjkMediaPlayer_native_setLogLevel(3)
	Line 19945: D/IJKMEDIA(30338): moncleanup

**Comment by lijingchang** [comment]
audio first come out,and picture later. how can I make them appear same time?

**Comment by bbcallen** [comment]
Can you reproduce same problem with ffplay?

**Comment by lijingchang** [comment]
can ,can ,can .you can try this:
enable audio Using OpenSL ES and choose ijkmediaplayer in setting,then play.
audio first come out and pictrue later.
it isn't a big problem

**Comment by lijingchang** [comment]
can ,can ,can .you can try this:
enable audio Using OpenSL ES and choose ijkmediaplayer in setting,then play.
audio first come out and pictrue later.
it isn't a big problem

**Comment by lijingchang** [comment]
can ,can ,can .you can try this:
enable audio Using OpenSL ES and choose ijkmediaplayer in setting,then play.
audio first come out and pictrue later.
it isn't a big problem

**Comment by lijingchang** [comment]
can ,can ,can .you can try this:
enable audio Using OpenSL ES and choose ijk media player in setting,then play.
audio first come out and picture later.
it isn't a big problem

**Comment by lijingchang** [comment]
can ,can ,can .you can try this:
enable audio Using OpenSL ES and choose ijk media player in setting,then play.
audio first come out and picture later.
it isn't a big problem

**Comment by lijingchang** [comment]
can ,can ,can .you can try this:
enable audio Using Opens L ES and choose i j k media player in setting,then play.
audio first come out and picture later.
it isn't a big problem

**Comment by lijingchang** [comment]
can ,can ,can .you can try this:
enable audio Using Opens L ES and choose i j k media player in setting,then play.
audio first come out and picture later.
it isn't a big problem

**Comment by lijingchang** [comment]
can ,can ,can .you can try this:
enable audio Using Opens L ES and choose i j k media player in setting,then play.
audio first come out and picture later.
it isn't a big problem

**Comment by lijingchang** [comment]
can ,can ,can .you can try this:
enable audio Using OpensL ES and choose ijk media player in setting,then play.
audio first come out and picture later.
it isn't a big problem
