### ISSUE TITLE
read_thread代码问题

### ISSUE THREAD

**Issue by wqmijkplayer** [Bilibili/ijkplayer#902]
@bbcallen 
在ff-ffplay.c  read_thread函数最后部分，代码如下：
 fail:
    if (ic && !is->ic)
        avformat_close_input(&is->ic);

    if (!ffp->prepared || !is->abort_request) {
        ffp->last_error = last_error;
        ffp_notify_msg2(ffp, FFP_MSG_ERROR, last_error);
    }
    SDL_DestroyMutex(wait_mutex);
    return 0;
ic 和 is->ic不就是相同的一个指针吗？判断ic && !is->ic是否会导致永远不会走avformat_close_input(&is->ic);
谢谢

**Comment by bbcallen** [comment]
Fixed.
Thanks.

**Comment by Android4MediaPlayer** [comment]
@bbcallen 
    if (ic) {
        avformat_close_input(&ic);
        is->ic = NULL;
    }
