### ISSUE TITLE
Android 播放视频过程暂停后出错

### ISSUE THREAD

**Issue by zhousuqiang** [Bilibili/ijkplayer#903]
Android 播放视频过程暂停时间稍微长一点，然后点击播放正常播放到缓冲结尾时将出错。
URL(有时效性如需请留言我会再提供):http://play.g3proxy.lecloud.com/vod/v2/MTQyLzI0LzUvYmNsb3VkLzEyMTQxNi92ZXJfMDBfMjItMzIyNTgzNjI5LWF2Yy0yOTkzOTI0LWFhYy0xMjgwMDEtMzgzMzAwLTE1MDE3OTAzNi1mNjMwMzEzMGU1YjJiOWVmNTAwMGUyNmM1YzU4NTNlNi0xNDM2NDUxMjIxMjU2Lm1wNA==?b=3134&mmsid=32929728&tm=1454393179&key=fc68ae1ac65f632d6aa6f822c6a3c783&platid=2&splatid=206&playid=0&tss=no&vtype=52&cvid=507418364006&payff=0&pip=fd6cf9cc74de68e8a92af0458f981221&tag=mobile&sign=bcloud_121416&termid=2&pay=0&ostype=android&hwtype=un

Log信息如下：
02-02 13:59:18.650 18171-18171/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_pause()
02-02 13:59:18.650 18171-18171/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_pause()=0
02-02 13:59:18.650 18171-29849/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_PAUSE
02-02 13:59:37.010 18171-18177/tv.danmaku.ijk.media.sample D/TVM: Alloc from exist block failed.allocatedSize = 1128880, size = 56, idealSize= 1128888.
02-02 13:59:37.040 18171-18177/tv.danmaku.ijk.media.sample D/TVM: GC_TIME GC_ALLOC freed 531K, 20% free 5740K/7119K, objects(37938)
02-02 13:59:37.040 18171-18177/tv.danmaku.ijk.media.sample D/TVM: Sending VM heap info to DDM
02-02 14:00:41.440 18171-18171/tv.danmaku.ijk.media.sample D/TVM: Alloc from exist block failed.allocatedSize = 1109328, size = 12, idealSize= 1109328.
02-02 14:00:41.460 18171-18171/tv.danmaku.ijk.media.sample D/TVM: GC_TIME GC_ALLOC freed 524K, 20% free 5728K/7119K, objects(37712)
02-02 14:00:41.460 18171-18171/tv.danmaku.ijk.media.sample D/TVM: Sending VM heap info to DDM
02-02 14:00:55.180 18171-18171/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_start
02-02 14:00:55.180 18171-18171/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_start()
02-02 14:00:55.180 18171-29849/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
02-02 14:00:55.190 18171-18171/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_start()=0
02-02 14:00:55.190 18171-29849/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START: start on fly
02-02 14:00:56.250 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: Stream ends prematurely at 89641928, should be 150179036
02-02 14:00:56.250 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x557d5ad: partial file
02-02 14:00:56.250 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:00:57.260 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x557d720: partial file
02-02 14:00:57.260 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:00:58.270 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x557d895: partial file
02-02 14:00:58.270 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:00:59.290 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x557da6f: partial file
02-02 14:00:59.290 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:00.300 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x557dbe3: partial file
02-02 14:01:00.300 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:01.310 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x557dd48: partial file
02-02 14:01:01.310 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:02.320 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x557deb2: partial file
02-02 14:01:02.320 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:03.330 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x557e01c: partial file
02-02 14:01:03.330 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:04.340 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 0, offset 0x557e183: partial file
02-02 14:01:04.340 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:05.350 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 0, offset 0x5584d0f: partial file
02-02 14:01:05.350 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:06.360 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 0, offset 0x55868ce: partial file
02-02 14:01:06.360 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:07.370 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 0, offset 0x5587634: partial file
02-02 14:01:07.370 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:08.380 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x5588677: partial file
02-02 14:01:08.380 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:09.390 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x55887e2: partial file
02-02 14:01:09.390 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:10.400 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x558894e: partial file
02-02 14:01:10.400 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:11.410 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x5588ab7: partial file
02-02 14:01:11.410 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:12.420 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x5588c29: partial file
02-02 14:01:12.420 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:13.430 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x5588d95: partial file
02-02 14:01:13.430 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:14.440 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x5588f0c: partial file
02-02 14:01:14.440 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:15.450 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x558907a: partial file
02-02 14:01:15.450 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:16.460 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 0, offset 0x55891e3: partial file
02-02 14:01:16.460 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:17.470 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 0, offset 0x5596c9c: partial file
02-02 14:01:17.470 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:18.480 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 0, offset 0x5598cd7: partial file
02-02 14:01:18.480 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:19.500 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 0, offset 0x5599cc5: partial file
02-02 14:01:19.500 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:20.510 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x559ae70: partial file
02-02 14:01:20.510 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:21.480 18171-18171/tv.danmaku.ijk.media.sample D/TVM: Alloc from exist block failed.allocatedSize = 1096936, size = 24, idealSize= 1096928.
02-02 14:01:21.500 18171-18171/tv.danmaku.ijk.media.sample D/TVM: GC_TIME GC_ALLOC freed 460K, 19% free 5779K/7119K, objects(38685)
02-02 14:01:21.500 18171-18171/tv.danmaku.ijk.media.sample D/TVM: Sending VM heap info to DDM
02-02 14:01:21.520 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x559afda: partial file
02-02 14:01:21.520 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:22.530 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x559b14d: partial file
02-02 14:01:22.530 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:23.540 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x559b2c1: partial file
02-02 14:01:23.540 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:24.550 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x559b435: partial file
02-02 14:01:24.550 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:25.560 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x559b5c4: partial file
02-02 14:01:25.560 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:26.570 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x559b750: partial file
02-02 14:01:26.570 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:27.580 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x559b8b5: partial file
02-02 14:01:27.580 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:28.590 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 0, offset 0x559ba1b: partial file
02-02 14:01:28.590 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:29.600 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 0, offset 0x55a2dae: partial file
02-02 14:01:29.600 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:30.610 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 0, offset 0x55a4455: partial file
02-02 14:01:30.610 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:31.620 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x55a563f: partial file
02-02 14:01:31.620 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:32.630 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x55a57a2: partial file
02-02 14:01:32.630 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:33.640 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x55a590d: partial file
02-02 14:01:33.640 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:34.650 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x55a5a81: partial file
02-02 14:01:34.650 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:35.070 18171-29866/tv.danmaku.ijk.media.sample E/IJKMEDIA: AVC: nal size 3678
02-02 14:01:35.070 18171-29866/tv.danmaku.ijk.media.sample E/IJKMEDIA: AVC: nal size 3678
02-02 14:01:35.070 18171-29866/tv.danmaku.ijk.media.sample E/IJKMEDIA: no frame!
02-02 14:01:35.660 18171-29851/tv.danmaku.ijk.media.sample I/IJKMEDIA: ffp_toggle_buffering: error: -5
02-02 14:01:35.660 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x55a5bf4: partial file
02-02 14:01:35.660 18171-29851/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 14:01:35.660 18171-29849/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_ERROR: 0
02-02 14:01:35.660 18171-18171/tv.danmaku.ijk.media.sample E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
02-02 14:01:35.660 18171-18171/tv.danmaku.ijk.media.sample D/IjkVideoView: Error: -10000,0
02-02 14:01:35.660 18171-18171/tv.danmaku.ijk.media.sample I/zsq: onError...what: -10000 ,extra: 0
02-02 14:01:35.670 18171-18171/tv.danmaku.ijk.media.sample I/AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
02-02 14:01:35.680 18171-18171/tv.danmaku.ijk.media.sample D/ScrollView: ScrollView reload scrollMode = 0
02-02 14:01:36.670 18171-29851/tv.danmaku.ijk.media.sample I/IJKMEDIA: ffp_toggle_buffering: eof

**Comment by zhousuqiang** [comment]
补充一点暂停再播放时URL肯定是没有失效，因为我退出重新播放是可以加载正常播放的。

**Comment by bbcallen** [comment]
Sounds idle connection is disconnected by server.

**Comment by zhousuqiang** [comment]
请问会修改这种策略吗，可以不断开吗，不然用户中间暂停会还得重新加载视频。

补充：此过程中如果快进将不会出现提示错误。
02-02 15:08:39.060 1624-1624/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_start()=0
02-02 15:08:39.930 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: Stream ends prematurely at 30571416, should be 150179036
02-02 15:08:39.930 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 0, offset 0x1d2a424: partial file
02-02 15:08:39.930 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 15:08:40.940 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 0, offset 0x1d2bb06: partial file
02-02 15:08:40.940 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 15:08:41.950 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x1d34edd: partial file
02-02 15:08:41.950 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 15:08:42.960 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x1d35070: partial file
02-02 15:08:42.960 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 15:08:43.970 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x1d351f0: partial file
02-02 15:08:43.970 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 15:08:44.980 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x1d3534e: partial file
02-02 15:08:44.980 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 15:08:45.990 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x1d354a1: partial file
02-02 15:08:45.990 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 15:08:47.000 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x1d35614: partial file
02-02 15:08:47.000 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 15:08:48.010 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x1d35772: partial file
02-02 15:08:48.010 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 15:08:49.020 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: stream 1, offset 0x1d358e3: partial file
02-02 15:08:49.020 1624-1667/tv.danmaku.ijk.media.sample E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
02-02 15:08:49.250 1624-1624/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_seekTo
02-02 15:08:49.250 1624-1624/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_seek_to(54047)
02-02 15:08:49.250 1624-1624/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_seek_to(54047)=0
02-02 15:08:49.250 1624-1665/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_SEEK
02-02 15:08:49.250 1624-1665/tv.danmaku.ijk.media.sample D/IJKMEDIA: stream_seek 54047000(54047) + 0, 
02-02 15:08:49.250 1624-1665/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_SEEK: seek to 54047
02-02 15:08:50.030 1624-1667/tv.danmaku.ijk.media.sample D/IJKMEDIA: ffp_toggle_buffering_l: start
02-02 15:08:50.030 1624-1665/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_BUFFERING_START:
02-02 15:08:50.040 1624-1624/tv.danmaku.ijk.media.sample I/zsq: onInfo... what: 701 ,extra: 0
02-02 15:08:50.040 1624-1624/tv.danmaku.ijk.media.sample D/IjkVideoView: MEDIA_INFO_BUFFERING_START:
02-02 15:08:50.050 1624-1665/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_SEEK_COMPLETE
02-02 15:08:50.050 1624-1665/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_SEEK_COMPLETE:
02-02 15:08:50.110 1624-1677/tv.danmaku.ijk.media.sample D/IJKMEDIA: no picture 
02-02 15:08:50.110 1624-1678/tv.danmaku.ijk.media.sample D/IJKMEDIA: no picture 
02-02 15:08:50.130 1624-1624/tv.danmaku.ijk.media.sample D/SnakeProgressBar: initSquares width=48 height=48 mMaxSize=27
02-02 15:08:50.130 1624-1624/tv.danmaku.ijk.media.sample D/SnakeProgressBar: initSquares width=48 height=48 mMaxSize=27
02-02 15:08:50.580 1624-1667/tv.danmaku.ijk.media.sample D/IJKMEDIA: ffp_toggle_buffering_l: end
02-02 15:08:50.580 1624-1665/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_BUFFERING_END:

**Comment by zhousuqiang** [comment]
这个问题如何破呢？

**Comment by bbcallen** [comment]
Modify ffmpeg's http implement to reconnect after being closed by server.

**Comment by zhousuqiang** [comment]
请问会考虑修复这个问题吗

**Comment by bbcallen** [comment]
Nope, whether and how to retry/reconnect is app developers' decision, not mine.
Reconnect blindly is evil, especially on cell phone.

**Comment by zhousuqiang** [comment]
哦，谢谢您的回复，另外可否指点下具体如何修改吗？对ffmpeg研究太少了。

**Comment by bbcallen** [comment]
The simplest way is creating a new player after error occur.
