### ISSUE TITLE
display not correct for MTK CPU

### ISSUE THREAD

**Issue by maytrue** [Bilibili/ijkplayer#905]
Hi,

[Here is the display](http://78rfgs.com1.z0.glb.clouddn.com/IMG_20160203_150846.jpg)

My mobile phone info and ijkplayer setting: 
- Redmi Note2 
- ijkplayer with mediacodec

What is the possible reason, does color format really matters?

**Comment by bbcallen** [comment]
MediaCodec handles every thing, including color format.
I think there's nothing ijkplayer can do for this situation.

**Comment by maytrue** [comment]
I don't know the reason that cause above situation. 

As far as I know, It happens on MTK cpu android phone. It does not happen on Note4, Huawei Mate7 phones.

**Comment by Android4MediaPlayer** [comment]
@maytrue which android os version?

**Comment by maytrue** [comment]
Android 5.0.2

**Comment by leemeng0x61** [comment]
this about a mtk mediacodec bug

**Comment by linjiansheng** [comment]
MTK5507 play h264 high profile - -oz)()()
