### ISSUE TITLE
Why do you call the java API of MediaCodec rather than the C++ API

### ISSUE THREAD

**Issue by anITer** [Bilibili/ijkplayer#906]
In my opinion, every frame could be sent to the Java memory area and than sent back to the native memory area through JNI call in the way you using MediaCodec. As JNI call is really slow when passing mass of data, I'm really worried that my app could be dragged down by this.
Please do let me known the reason. Thanks a lot!

**Comment by bbcallen** [comment]
There is no native MediaCodec API until API-21

**Comment by anITer** [comment]
You sure? As I known, the real code beneath the Java API is actually the native code. So I think the native MediaCodec API come no later than the Java API.

**Comment by bbcallen** [comment]
1. Go ahead and prove me wrong.
2. Not until old devices disappear.

**Comment by anITer** [comment]
You could look into the source code of Android at "androidxref.com". There is a "MediaCodec.h" header file in libstagefright folder since API-16, and you can check it out here "http://androidxref.com/4.1.1/xref/frameworks/av/include/media/stagefright/MediaCodec.h".

**Comment by bbcallen** [comment]
I don't think this can be called as "API".

**Comment by anITer** [comment]
Maybe it's not a published API, but it is where the Java API really calls. I mean that every Java API call could be replaced by the functions in "MediaCodec.h".

**Comment by bbcallen** [comment]
I would suggest to take a benchmark with public NDK API in level 21, before introducing any private API usage. I don't think JNI-call could be the bottleneck. Of course, it could be faster, but not faster enough to match the burden of maintaining private API symbols, which is really a pain in the ass.

What do you mean by 'double-JNI-call'

**Comment by anITer** [comment]
What I mean by 'double-JNI-call' is that every frame could be sent to the Java memory area and than sent back to the native memory area through JNI call, 'cause the native cpp code is doing the real job.
Maybe you should have a look at the "android_media_MediaCodec.cpp", the JNI code between Java API and the native cpp code.

**Comment by bbcallen** [comment]
Yep, that's how it works.
My hands are tied without public NDK API.
