### ISSUE TITLE
Fatal signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by don11995** [Bilibili/ijkplayer#909]
In two of three times while seek in video I have an error "Fatal signal 11 (SIGSEGV) at 0x00000054 (code=1), thread 6077 (ff_vout)". It is the only meassage in logs. Sometimes it works normally, sometimes I get this error. Tested on Android 4.4.4.

**Comment by wanzhi** [comment]
I also encountered a similar mistake

A/libc: invalid address or address of corrupt block 0x5bf3c518 passed to dlfree
A/libc: Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 12954 (ff_read)

**Comment by Android4MediaPlayer** [comment]
give more infomation

**Comment by janedevelopex** [comment]
I built project with more codecs as in README and also this error happens. Seems like it happens randomly: sometimes after video stopping, sometimes after video starting. I have no idea what to do, i haven't changed the source code, open only samples. Please help.

**Comment by bbcallen** [comment]
Did it crashed in demo, or in your own app?

**Comment by wanzhi** [comment]
1, in the demo, I used to use master translation of the support https armv7a so, this appears to play random error of http or https when hls
2, in the demo, I use compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.5.0', http playback of hls, the random error
3, in the demo, I use compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.4.5.1', playing the http hls, not wrong

**Comment by janedevelopex** [comment]
@bbcallen in the demo app

**Comment by janedevelopex** [comment]
ff_read, ff_video_dec, ff_vout - in these functions fatal signal happens too. Even on 0.4.5.1 version.

**Comment by janedevelopex** [comment]
@bbcallen sorry, did you reproduce this bug? I updated to 0.5.1, built demo app "with more" codecs and when I start play samples, after it opening - app crashes.

**Comment by janedevelopex** [comment]
If I import lib with gradle - everything ok. But I need more codecs, such as mpeg2video and mp2.
