### ISSUE TITLE
how to free buffer/frames if memory too high (ios)

### ISSUE THREAD

**Issue by bigman0726** [Bilibili/ijkplayer#911]
Hi playing video on arm64 devices no problem , but on armv7 devices like iphone 4s hit didreceivedmemory warning and application quit sometimes 
      Is there any way to release frames/ buffer or something to release some memory in this case

Regards

**Comment by bbcallen** [comment]
No, there is no memory could be released.
But you can reduce memory usage by
```
[options setPlayerOptionIntValue:<size_in_bytes> forKey:@"max-buffer-size"]
```
