### ISSUE TITLE
Only you can save my day!

### ISSUE THREAD

**Issue by muximus3** [Bilibili/ijkplayer#913]
你好，由于项目需求，我实现的播放界面和bilibili的播放界面有类似的嵌套滑动（非全屏时），还有在播放时的手势操作，在播放器不是播放状态时，播放器会随着下面界面的上滑而收缩（CollapsingToolbarLayout），播放时播放界面不会收缩。
我的播放界面下面是一个recyclerview，播放时setNestedScrollingEnabled(false); 未播放时反之，但是我在测试中一直遇到一个bug，就时播放器播放时，如果对播放器进行手势操作（如声音亮度调节），然后滑动recylerview，播放器还是会收缩，但是第二次滑动就不会收缩了。
简单来说就是播放器在播放过程中（非全屏）进行手势操作后，第一次滑动recyclerview，播放器还是会收缩，然后抬起手指，第二次滑动recyclerview就不会了setNestedScrollingEnabled(false)好像在那次手势操作后没起作用。这个bug已经困扰我一段时间了，一直找不到原因，不知道你们在开发中有遇到这个问题吗？又有何解决建议呢，感激不尽。由于问题比较难以描述就用中文了。

**Comment by muximus3** [comment]
另外为了解决控件滑动和播放器手势的冲突，我在播放器播放状态时禁止播放器上层视图拦截事件，我之前一直针对这点测试，后来感觉好像并不是这个造成的

**Comment by bbcallen** [comment]
Sorry, I'm not good at UI development.

**Comment by muximus3** [comment]
tks for reply， i had solved this problem by adding a behavior to My CoordinatorLayout.
