### ISSUE TITLE
Does IJK support audio passthrough?

### ISSUE THREAD

**Issue by stuckless** [Bilibili/ijkplayer#914]
Do you know if IJK player supports audio passthrough (dts ac3), and if so, how is it enabled?

**Comment by bbcallen** [comment]
No, there is only PCM s16 output in ijkplayer for now.
Are there any devices and players support that?

**Comment by NikmanSergey** [comment]
There are number of Android TV boxes that do support Audio Passthrough mode. MediaPlayer class then send AC3/DTS audio directly through HDMI to be decoded on TV.
This would be great if IJK Player could have this option too.

**Comment by bbcallen** [comment]
How to tell if a device support it ?

**Comment by stuckless** [comment]
I just looked at ExoPlayer source, and, their audio track renderer appears to delegate to hardware decoder.
https://github.com/google/ExoPlayer/blob/267a870509bb85e2cff839ea162ae5b7c85933aa/library/src/main/java/com/google/android/exoplayer/MediaCodecAudioTrackRenderer.java

It checks, MediaCodeSelector for the "passthrough" codec, which results in "OMX.google.raw.decoder"

https://github.com/google/ExoPlayer/blob/f11c2e113f0a4df35461296905a3c3b461cab6a9/library/src/main/java/com/google/android/exoplayer/MediaCodecSelector.java

So, is it just a matter of delegating the audio decoding to hardware (like the video)?

If this is set like, "mediacodec-passthrough" option, then it could be left to the player implementation to turn it on/off.  If it's a matter of testing of the device supports audio passthrough, you'd iterate the list of codecs and check if the "raw" codec exists using MediaCodecList and/or check if you are using a phone/tablet (and turn if off).

On a phone/tablet passthrough is not needed (not does it have the decoders, I think).  But on a TV unit, it's appears that passthrough is nice feature to have.  I have the NVidia Shield TV and it does support passthrough (from testing using ExoPlayer -- and from feedback from my user community)

Keep in mind, I'm not a media developer, so, I have no idea what I'm talking about :)

**Comment by bbcallen** [comment]
1. AFAIK, decoders with prefix "OMX.google" is supposed to be software decoder, I have no idea if it's better than FFmpeg's own dts/ac3 decoder.

2. With MediaCodec, no matter HW (OMX.nvidia.*, OMX.qcom.*) or SW (OMX.google.*), I'm afraid it's still PCM s16 data (2 channels) received on the other side of HDMI. The only benefit is that it could be faster with HW decoder.

3. If you want to support more channels other than default stereo mode, such as, 5.1, 6.1, 7.1, You should modify AudioTracks wrappers, to send PCM in more channels.
http://developer.android.com/intl/zh-cn/reference/android/media/AudioTrack.html
```
android_audiotrack.c
ijksdl_aout_android_audiotrack.c
```
And audio_open() in ff_ffplay.c

4. For so called "passthrough", according to AudioTrack's document
http://developer.android.com/intl/zh-cn/reference/android/media/AudioFormat.html#ENCODING_PCM_FLOAT

For compressed audio, the encoding specifies the method of compression, for example ENCODING_AC3 and ENCODING_DTS. The compressed audio data is typically stored as bytes in a byte array or ByteBuffer. When a compressed audio encoding is specified for an AudioTrack, it creates a direct (non-mixed) track for output to an endpoint (such as HDMI) capable of decoding the compressed audio. For (most) other endpoints, which are not capable of decoding such compressed audio, you will need to decode the data first, typically by creating a MediaCodec. Alternatively, one may use MediaPlayer for playback of compressed audio files or streams.

That also need you to modify files mentioned in 3.

**Comment by stuckless** [comment]
@bbcallen Is this closed because Audio Passthrough is now working?  Or it's closed because the question is answered, and the answer is "no".  thx.

**Comment by bbcallen** [comment]
No, I just clean staled issues, and feature requests not on my plan.
But feel free to reopen it, if you need this issue to be open.

**Comment by stuckless** [comment]
np... I just wanted to clarify... I will likely take a stab at this using your notes above... Audio pass-through is a big issue for many of my users... I just need to find the time to do it :)  Thanks for all your work.

**Comment by stuckless** [comment]
Sadly no.  While I still use IJKPlayer, I did also include ExoPlayer in my application and ExoPlayer does support audio pass-through.
