### ISSUE TITLE
Send cookie in each query to server

### ISSUE THREAD

**Issue by Zo2m4bie** [Bilibili/ijkplayer#915]
Hi, in my project I have some kind of tokenization and I have to send token in cookie in every request which player sends to server. Can you help me and point where ijkplayer sends request(connects to serve) that I will take root into right place? Thank you

**Comment by bbcallen** [comment]
http://git.videolan.org/?p=ffmpeg.git;a=blob;f=libavformat/http.c;h=d1b91e23d6a1e5264c8f299b9214de6345e2b226;hb=HEAD

**Comment by Zo2m4bie** [comment]
@bbcallen 
Hi, I investigate more in my issues. As I understand this question is not connected to yuor lib, but maybe you will be able to help me. So I add test data in method [http_open](https://ffmpeg.org/doxygen/2.8/http_8c.html#a08d28a134863d46a635b4b144096c333) 

Added code:

`char data[] = {'t','e','s','t','=','r','2','d','2',';','p','a','t','h','=','/',';'};  `
`s->cookies = data;`

I looked into wireshark, my requests send with this cookie, but after first sending I receive:

`A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xa0c013e8 in tid 27629 (ff_read)`

Maybe you know something about it or faced with it, and can get me some advice. Thank you

**Comment by bbcallen** [comment]
I think cookies should be allocated on heap

**Comment by Zo2m4bie** [comment]
@bbcallen you were right, thank you

**Comment by Zo2m4bie** [comment]
Sorry to bother you one more time. But I cannot completely resolve my issue, maybe you can help me with it. Ok, so I found that we connect with server in two different places, when app calls prepareasync and when app calls start. I cannot fully connect methods but I found that 
[IjkMediaPlayer_prepareAsync ](https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/android/ijkplayer_jni.c#L211) some how calls
[read_thread](https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/ff_ffplay.c#L2380)  which calls
[err = avformat_open_input(&ic, is->filename, is->iformat, &ffp->format_opts);](https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/ff_ffplay.c#L2435)
 which calls
init_input(AVFormatContext *s, const char *filename,
                      AVDictionary **options) ([util.c ](https://ffmpeg.org/doxygen/trunk/libavformat_2utils_8c-source.html) line - 511)
which calls  avio_open2 (AVIOContext **s, const char *filename, int flags, const AVIOInterruptCB *int_cb, AVDictionary **options) (from libavformat.c )
which calls ffurl_open(&h, filename, flags, int_cb, options); 
which somehow calls http_open from http.c  but I cannot find how ffurl_open connects with http_open. 
And if I have understood correct I can send my cookie to http.c through AVDictionary **options, which I are able to add in read_thread method. Will it be correct if I do it?
And about start method, I cannot find where this method which loading data in buffer. I found mathod [decoder_decode_frame](https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/ff_ffplay.c#L369), but as far I understood it works independent from buffering. Also I want to implement there work with bittrate. Can you point me where buffering is?

**Comment by bbcallen** [comment]
These are questions about FFmpeg.
I think you can get better answers from FFmpeg ML, stackoverflow, blablabla...

**Comment by Zo2m4bie** [comment]
But read_thread it's your plauer method, and buffering as I understand implemented in your player to, that's why I ask you about this places

**Comment by bbcallen** [comment]
What I implement is only buffering notify, not buffering itself.

**Comment by Zo2m4bie** [comment]
I want to bother you one more time. I'm making some workaround with changing video streams for hlc and I added several files to ffmepg into libavformat package(in my case test.h and test.c). But when I try to compile ffmeg project (via your compile-ffmpeg.sh file) it throws errors with text "error: undefined reference to my_function" and "error: undefined reference to my_field". As far as I understand the problem is that this files weren't added to the project and when it compiles, compiler cannot find this methods/fields. So, can you say where I have to write these file's  names to compile ffmpeg correct?

**Comment by bbcallen** [comment]
Modify Makefile
