### ISSUE TITLE
Impossible to open the 'tcp' protocol for writing

### ISSUE THREAD

**Issue by wpfcool** [Bilibili/ijkplayer#918]
ijkmp_set_format_callback(0x1007c74bc, 0x1701d4af0)
ijkmp_set_format_callback()=void
2016-02-16 09:41:27.096 YC_AI[240:8235] OK setup GL
ijkmp_ios_set_view(glView=0x13ed03de0)
ijkmp_ios_set_view(glView=0x13ed03de0)=void
ijkmp_set_overlay_format(I420(0x30323449))
ijkmp_set_overlay_format()=void
2016-02-16 09:41:27.109 YC_AI[240:8235] ========================================
= FFmpeg options:
= skip_loop_filter: avdicard all;
= skipFrame:        avdiscard nonref
= frameBufferCount: 3
= maxFps:           30
= timeout:          -1
========================================
ijkmp_set_codec_option()
ijkmp_set_codec_option()=void
ijkmp_set_codec_option()
ijkmp_set_codec_option()=void
ijkmp_set_picture_queue_capicity(3)
ijkmp_set_picture_queue_capicity()=void
ijkmp_set_max_fp(30)
ijkmp_set_max_fp()=void
ijkmp_set_framedrop(0)
ijkmp_set_framedrop()=void
ijkmp_set_data_source(url="rtmp://pub.mfniu.com/tjapp/b5494806d2a7c3e9b07964f8180a73b1")
ijkmp_set_data_source(url="rtmp://pub.mfniu.com/tjapp/b5494806d2a7c3e9b07964f8180a73b1")=0
ijkmp_set_format_option(safe, 0)
ijkmp_set_format_option()=void
ijkmp_prepare_async()
ijkmp_prepare_async()=0
Impossible to open the 'tcp' protocol for writing
[rtmp @ 0x13eea6c60] Cannot open connection tcp://pub.mfniu.com:1935
rtmp://pub.mfniu.com/tjapp/b5494806d2a7c3e9b07964f8180a73b1: Input/output error

**Comment by bbcallen** [comment]
It works here.
Did you add network permission to AndroidManifest.xml?
