### ISSUE TITLE
Universal Framework but link failed with "Undefined symbols for arm64"

### ISSUE THREAD

**Issue by guitarkitten** [Bilibili/ijkplayer#919]
![2 h_ f2h8 9p8w4 s 0grh](https://cloud.githubusercontent.com/assets/1877053/13066097/d4946df2-d49d-11e5-9b95-284a9870048d.jpg)
![k o2alu75n0 klpnu _3n s](https://cloud.githubusercontent.com/assets/1877053/13066098/d693ba90-d49d-11e5-81b1-4c4201e44e03.jpg)

**Comment by bbcallen** [comment]
Did you add required system framework and library to your main project.
