### ISSUE TITLE
Change stream resolution / bitrate

### ISSUE THREAD

**Issue by brystel** [Bilibili/ijkplayer#92]
Hello,

I have to change HLS stream resolution and bitrate due to limited device performance.
Is there possibility to set a constant streaming resolution and bitrate? For example HD / SD resolutions and 70% quality? 

Is there also possiblity to change bitrate on fly? I means the buffer starts at low bitrate and when it's loaded bitrate raises.

Thank you

**Comment by vipulpurohit** [comment]
Hello,
I also need to change RTMP live stream resolution and bitrate on the fly.
I know it's not in plan for now but can you please give us some hint or path which I should follow to achieve this functionality?
I just need a correct path so I can try to implement it.

Thanks

**Comment by bbcallen** [comment]
Try flush avcodec between two streams.

**Comment by vipulpurohit** [comment]
I do not want to switch between two streams. In my case there will a single RTMP stream and what I need to do is change the resolution of the input stream on the fly and the updated resolution should be visible to user.
**E.g.**  I've a 1280x720 RTMP stream and now I need to convert this resolution to 640x360. So user should see the 640x360 resolution video, not the 1280x720.

Thanks for your reply.
Hoping for your reply.

**Comment by bbcallen** [comment]
No smooth switching, for now.

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
