### ISSUE TITLE
HelpBeginner-->MissingFile

### ISSUE THREAD

**Issue by GikkiAres** [Bilibili/ijkplayer#920]
I am a beginner,when I tried to run /ijkplayer-master/ios/IJKMediaPlayer/IJKMediaPlayer.xcodeproj directly,Xcode indicates me that  'libavformat/avformat.h' file not found,what should I do to solve this problem?

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer#build-ios

**Comment by GikkiAres** [comment]
@bbcallen Thank you for giving me the reference,I build according to it and I can run it now.

**Comment by xclidongbo** [comment]
What's the answer?

**Comment by GikkiAres** [comment]
![image](https://cloud.githubusercontent.com/assets/13636974/14015459/224efbac-f1f4-11e5-9839-c2b389685fb4.png)
Do as these steps,then you can run it.

**Comment by xclidongbo** [comment]
@GikkiAres   I do it step by step. but also error.
