### ISSUE TITLE
为什么设置"mediacodec_all_videos"或者"mediacodec_hevc"都不会调用mediacodec

### ISSUE THREAD

**Issue by Long888** [Bilibili/ijkplayer#922]
我在测试播放hevc时发现只有把IjkMediaPlayer.OPT_CATEGORY_PLAYER设置成“mediacodec”时才会调用mediacodec解码，设置"mediacodec_all_videos"或者"mediacodec_hevc"都是调用的软解，在代码执行到 case AV_CODEC_ID_HEVC:
        if (!ffp->mediacodec_hevc && !ffp->mediacodec_all_videos) {
            ALOGE("%s: MediaCodec/HEVC is disabled. codec_id:%d \n", __func__, opaque->avctx->codec_id);
            goto fail;
        }
发现ffp->mediacodec_hevc和!ffp->mediacodec_all_videos的值都是0，然后就会goto fail;

**Comment by Long888** [comment]
@bbcallen   ijkMediaPlayer.setOption(
					 IjkMediaPlayer.OPT_CATEGORY_PLAYER,
					 "mediacodec_all_videos", 1);
					 ijkMediaPlayer.setOption(
					 IjkMediaPlayer.OPT_CATEGORY_PLAYER,
					 "mediacodec_hevc", 1);
这个设置了没起作用

**Comment by bbcallen** [comment]
I think the option names are "mediacodec-all-videos", "mediacodec-hevc".

**Comment by OnClickListener2048** [comment]
mediacodec-all-videos
