### ISSUE TITLE
How can i use the cache?

### ISSUE THREAD

**Issue by mgoann** [Bilibili/ijkplayer#925]
i want to use cache file if it is exist, if it is not exist must to download from server side. like this uri:cache:/storage/emulated/0/ams-cache/1711_1455678396132_52620334.cf:http://8537.vod.myqcloud.com/8537_91618978d45911e5932aedda4a4b5f47.f30.mp4?sign=f21d9a3bf7241c54baccc4a1a4f570f4&t=56c5353c
if the file "1711_1455678396132_52620334.cf" is exist, use this file, if do not exist, use the url "http://8537.vod.myqcloud.com/8537_91618978d45911e5932aedda4a4b5f47.f30.mp4?sign=f21d9a3bf7241c54baccc4a1a4f570f4&t=56c5353c" download from server side and write to cache file "1711_1455678396132_52620334.cf" to make sure next play can use cache file "1711_1455678396132_52620334.cf"

how can i got this?
thx,please

**Comment by bbcallen** [comment]
No such support, yet

**Comment by aytunch** [comment]
@mgoann Could you ever find a solution for this?
