### ISSUE TITLE
ff_tempfile error, how can i custom this directory?

### ISSUE THREAD

**Issue by mgoann** [Bilibili/ijkplayer#926]
```
02-16 22:06:36.264 2025-2566/com.fengxing.ams.tvclient:vitamio E/IJKMEDIA: ff_tempfile: Cannot open temporary file /tmp/ffcache2ZE4sL
02-16 22:06:36.264 2025-2566/com.fengxing.ams.tvclient:vitamio E/IJKMEDIA: Failed to create tempfile
```
how can i define or change the temporary file path to ensure that no errors are reported.
thx, please

**Comment by bbcallen** [comment]
This seems a FFmpeg issue ?

**Comment by mgoann** [comment]
i think this is android system "temp" environment variable or parameter from java code to redesign the value. Can we work together to solve this problem？

**Comment by bbcallen** [comment]
Patch welcome, but it's very likely to be a FFmpeg patch.
