### ISSUE TITLE
build error: can't cd to android/contrib/ffmpeg-armv5

### ISSUE THREAD

**Issue by wujianbo** [Bilibili/ijkplayer#927]
build error: can't cd to android/contrib/ffmpeg-armv5,该怎么处理

**Comment by wujianbo** [comment]
自己解决
./tools/pull-repo-ref.sh:10:    git clone --dissociate --reference $REF_REPO $REMOTE_REPO $LOCAL_WORKSPACE

git版本太老导致，这个参数--dissociate需要在git最新版本上才支持

**Comment by StayZeal** [comment]
Ubuntu install latest git:
sudo add-apt-repository ppa:git-core/ppa
sudo apt-get update
sudo apt-get install git
