### ISSUE TITLE
Hello，使用Jcenter方式引入library库时找不到so文件是什么原因

### ISSUE THREAD

**Issue by jaycee88** [Bilibili/ijkplayer#931]
使用这种方式：compile 'tv.danmaku.ijk.media:ijkplayer-java:0.4.5.1'  导入library库找不到so文件

**Comment by bbcallen** [comment]
'tv.danmaku.ijk.media:ijkplayer-java:0.4.5.1' doesn't contain any so files.

**Comment by ChadCSong** [comment]
'tv.danmaku.ijk.media:ijkplayer-armv7a:0.4.5.1' contains so files.
ijkplayer-java was just java code.
