### ISSUE TITLE
Warning:u.aly.bt: can't find referenced method 'int checkSelfPermission(java.lang.String)' in library class android.content.Context

### ISSUE THREAD

**Issue by xiangding1983** [Bilibili/ijkplayer#932]
我的APP用了另一个工程库， 必须要用22来编译，如下:
    compileSdkVersion = 22
    buildToolsVersion = "22.0.1"

但ijkPlayer-java必须要 23才行，该怎么解决？ 
当ijkpayer用23的时候，在混淆时报以下错：
  
Warning:u.aly.bt: can't find referenced method 'int checkSelfPermission(java.lang.String)' in library class android.content.Context

**Comment by bbcallen** [comment]
You can import ijkplayer-java from source, and remove all 23 API referenced codes.

**Comment by xiangding1983** [comment]
thanks.
