### ISSUE TITLE
【ios】【need help】友盟上统计到崩溃，栈追溯后经过符号化后的信息如下

### ISSUE THREAD

**Issue by plumhly** [Bilibili/ijkplayer#933]
Application received signal SIGSEGV
(null)
((
	0   CoreFoundation                      0x0000000183425918  + 148
	1   libobjc.A.dylib                     0x0000000182a93f80 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000183425848  + 0
	3   GoodTime                         **UmengSignalHandler (in GoodTime) + 128**
	4   libsystem_platform.dylib            0x000000018308993c _sigtramp + 52
	5   GoodTime                         **hls_read_packet (in GoodTime) (hls.c:1714)**
	6   GoodTime                        **ff_read_packet (in GoodTime) (utils.c:682)**
	7   GoodTime                         **read_frame_internal (in GoodTime) (utils.c:1338)**
	8   GoodTime                         **av_read_frame (in GoodTime) (utils.c:1499)**
	9   GoodTime                          **read_thread (in GoodTime) (ff_ffplay.c:2775)**
	10  GoodTime                         **SDL_RunThread (in GoodTime) (ijksdl_thread_ios.m:31)**
	11  libsystem_pthread.dylib             0x000000018308fb28  + 156
	12  libsystem_pthread.dylib             0x000000018308fa8c  + 0
	13  libsystem_pthread.dylib             0x000000018308d028 thread_start + 4
)

dSYM UUID: ABCD897D-A175-3E4E-8A4D-B938E0EDC848
CPU Type: arm64
Slide Address: 0x0000000100000000
Binary Image: GoodTime
Base Address: 0x00000001000b0000

注：**UmengSignalHandler**是第三方捕捉奔溃的方法，不会引起崩溃。

**Comment by bbcallen** [comment]
Do you have any video sample to reproduce this problem?

**Comment by plumhly** [comment]
i dont know how to reproduce this problem

**Comment by plumhly** [comment]
Thanks for the reply. i dont know how to reproduce this problem, the tool catches the crash only provide this infomation,my Application has many this problem. is anyone   also encounter this problem?
