### ISSUE TITLE
what does “prepared” mean？

### ISSUE THREAD

**Issue by vincentssn** [Bilibili/ijkplayer#934]
（问题比较复杂，请允许我用中文来提问。。）
播放器preparing状态，做了什么事情标记着播放器切换到prepared状态？
遇到的问题是这样的，在线播放的需求里，在播放器已经prepared以后，我start()播放器，并且隐藏了视频封面，然而网络不好，弹出正在加载中，而此时视频显示还是黑屏，能够保证的是该视频第一帧不是黑屏。如果播放器的prepared状态意味着第一帧是已经缓冲到了本地，并且可以播放了的话，那么此时网络不好而缓冲的话，也会显示出第一帧的画面才对的。显示了黑屏是否表示“prepared状态并不意味着第一帧可以播放”？那么prepared区别于preparing是在于哪里？preparing是在准备哪些事情？
谢谢

**Comment by bbcallen** [comment]
You can listen the event "IJKMPMoviePlayerFirstVideoFrameRenderedNotification" for the first video frame.

**Comment by vincentssn** [comment]
@bbcallen  Does it exist in the android ijkplayer project? I can not search one.

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/master/android/ijkplayer/ijkplayer-java/src/main/java/tv/danmaku/ijk/media/player/IMediaPlayer.java

**Comment by vincentssn** [comment]
@bbcallen I try to catch msg 'MEDIA_INFO_VIDEO_RENDERING_START' , but it did not happen. Then, I try to search the sentence of sending info about this msg in C source but not found also. except for 'MEDIA_INFO_BUFFERING_START' and 'MEDIA_INFO_BUFFERING_START', other info sending sentences can also not found. Does these info sendings really implement in C?

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/search?utf8=✓&q=MEDIA_INFO_VIDEO_RENDERING_START
