### ISSUE TITLE
Android 播放视频有的设备声画不同步

### ISSUE THREAD

**Issue by zhousuqiang** [Bilibili/ijkplayer#936]
一开始播放就不同步，请帮助看下是什么原因呢，具体log如下：
02-19 15:34:25.428 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_native_profileBegin
02-19 15:34:25.428 7397-7397/tv.danmaku.ijk.media.sample W/IJKMEDIA: monstartup already called
02-19 15:34:25.472 7397-7399/tv.danmaku.ijk.media.sample D/dalvikvm: GC_CONCURRENT freed 544K, 23% free 4551K/5844K, paused 2ms+12ms, total 38ms
02-19 15:34:25.480 7397-7406/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_native_finalize
02-19 15:34:25.480 7397-7406/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_release
02-19 15:34:25.656 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_native_setup
02-19 15:34:25.656 7397-7397/tv.danmaku.ijk.media.sample I/IJKMEDIA: av_version_info: ff2.8--ijk0.4.1.1--dev0.3.3--rc4
02-19 15:34:25.656 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: ffpipeline_create_from_android()
02-19 15:34:25.656 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_inject_opaque(0x1d30027a)
02-19 15:34:25.656 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_inject_opaque()=void
02-19 15:34:25.656 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
02-19 15:34:25.656 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
02-19 15:34:25.656 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
02-19 15:34:25.656 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(3)
02-19 15:34:25.656 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: moncleanup
02-19 15:34:25.656 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
02-19 15:34:25.656 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
02-19 15:34:25.656 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
02-19 15:34:25.656 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
02-19 15:34:25.656 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
02-19 15:34:25.656 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
02-19 15:34:25.656 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
02-19 15:34:25.660 7397-7397/tv.danmaku.ijk.media.sample D/tv.danmaku.ijk.media.player.IjkMediaPlayer: Couldn't open file on client side, trying server side
02-19 15:34:25.660 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
02-19 15:34:25.660 7397-7397/tv.danmaku.ijk.media.sample V/IJKMEDIA: setDataSource: path http://gslb.otvcloud.com/otv/yfy/1/79/BF/00000001345/index.m3u8
02-19 15:34:25.660 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_data_source(url="http://gslb.otvcloud.com/otv/yfy/1/79/BF/00000001345/index.m3u8")
02-19 15:34:25.660 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_data_source(url="http://gslb.otvcloud.com/otv/yfy/1/79/BF/00000001345/index.m3u8")=0
02-19 15:34:25.660 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
02-19 15:34:25.660 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_android_surface(surface=0xeda0001d)
02-19 15:34:25.660 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: ffpipeline_set_surface()
02-19 15:34:25.660 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_android_surface(surface=0xeda0001d)=void
02-19 15:34:25.660 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_prepareAsync
02-19 15:34:25.660 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_prepare_async()
02-19 15:34:25.664 7397-7397/tv.danmaku.ijk.media.sample I/IJKMEDIA: ===== versions =====
02-19 15:34:25.664 7397-7397/tv.danmaku.ijk.media.sample I/IJKMEDIA: FFmpeg       : ff2.8--ijk0.4.1.1--dev0.3.3--rc4
02-19 15:34:25.664 7397-7397/tv.danmaku.ijk.media.sample I/IJKMEDIA: libavutil    : 54.31.100
02-19 15:34:25.664 7397-7397/tv.danmaku.ijk.media.sample I/IJKMEDIA: libavcodec   : 56.60.100
02-19 15:34:25.664 7397-7397/tv.danmaku.ijk.media.sample I/IJKMEDIA: libavformat  : 56.40.101
02-19 15:34:25.664 7397-7397/tv.danmaku.ijk.media.sample I/IJKMEDIA: libswscale   : 3.1.101
02-19 15:34:25.664 7397-7397/tv.danmaku.ijk.media.sample I/IJKMEDIA: libswresample: 1.2.101
02-19 15:34:25.664 7397-7397/tv.danmaku.ijk.media.sample I/IJKMEDIA: ===== options =====
02-19 15:34:25.664 7397-7397/tv.danmaku.ijk.media.sample I/IJKMEDIA: player-opts : mediacodec                   = 0
02-19 15:34:25.664 7397-7397/tv.danmaku.ijk.media.sample I/IJKMEDIA: player-opts : opensles                     = 0
02-19 15:34:25.664 7397-7397/tv.danmaku.ijk.media.sample I/IJKMEDIA: player-opts : overlay-format               = 842225234
02-19 15:34:25.664 7397-7397/tv.danmaku.ijk.media.sample I/IJKMEDIA: player-opts : framedrop                    = 1
02-19 15:34:25.664 7397-7397/tv.danmaku.ijk.media.sample I/IJKMEDIA: player-opts : start-on-prepared            = 0
02-19 15:34:25.664 7397-7397/tv.danmaku.ijk.media.sample I/IJKMEDIA: format-opts : ijkinject-opaque             = 489685626
02-19 15:34:25.664 7397-7397/tv.danmaku.ijk.media.sample I/IJKMEDIA: format-opts : http-detect-range-support    = 0
02-19 15:34:25.664 7397-7397/tv.danmaku.ijk.media.sample I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
02-19 15:34:25.664 7397-7397/tv.danmaku.ijk.media.sample I/IJKMEDIA: ===================
02-19 15:34:25.668 7397-13689/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_RunThread: [13689] ff_msg_loop
02-19 15:34:25.668 7397-13689/tv.danmaku.ijk.media.sample D/IJKMEDIA: message_loop
02-19 15:34:25.668 7397-13690/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_RunThread: [13690] ff_vout
02-19 15:34:25.672 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_prepare_async()=0
02-19 15:34:25.672 7397-13689/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_FLUSH:
02-19 15:34:25.672 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_RunThread: [13691] ff_read
02-19 15:34:25.736 7397-7397/tv.danmaku.ijk.media.sample D/dalvikvm: GC_FOR_ALLOC freed 1206K, 38% free 3670K/5844K, paused 22ms, total 22ms
02-19 15:34:25.760 7397-7399/tv.danmaku.ijk.media.sample D/dalvikvm: GC_CONCURRENT freed 157K, 34% free 3902K/5844K, paused 4ms+2ms, total 20ms
02-19 15:34:25.788 7397-7399/tv.danmaku.ijk.media.sample D/dalvikvm: GC_CONCURRENT freed 303K, 31% free 4073K/5844K, paused 2ms+2ms, total 17ms
02-19 15:34:25.812 7397-7397/tv.danmaku.ijk.media.sample D/dalvikvm: GC_FOR_ALLOC freed 303K, 30% free 4093K/5844K, paused 16ms, total 16ms
02-19 15:34:25.848 7397-7397/tv.danmaku.ijk.media.sample D/dalvikvm: GC_FOR_ALLOC freed 152K, 29% free 4178K/5844K, paused 26ms, total 26ms
02-19 15:34:25.880 7397-7397/tv.danmaku.ijk.media.sample D/dalvikvm: GC_FOR_ALLOC freed 151K, 28% free 4264K/5844K, paused 26ms, total 27ms
02-19 15:34:25.900 7397-7397/tv.danmaku.ijk.media.sample D/dalvikvm: GC_FOR_ALLOC freed <1K, 25% free 4416K/5844K, paused 20ms, total 20ms
02-19 15:34:25.900 7397-7397/tv.danmaku.ijk.media.sample I/dalvikvm-heap: Grow heap (frag case) to 4.598MB for 87280-byte allocation
02-19 15:34:25.924 7397-7406/tv.danmaku.ijk.media.sample D/dalvikvm: GC_FOR_ALLOC freed 0K, 25% free 4501K/5932K, paused 22ms, total 22ms
02-19 15:34:26.856 7397-13691/tv.danmaku.ijk.media.sample D/IJKMEDIA: Format hls,applehttp probed with size=2048 and score=100
02-19 15:34:26.988 7397-13691/tv.danmaku.ijk.media.sample D/IJKMEDIA: Statistics: 5263 bytes read, 0 seeks
02-19 15:34:26.988 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: HLS request for url 'http://42.159.236.213:80/otv/yfy/1/79/BF/00000001345/_d9710000_/2300/1345_23000.ts', offset 0, playlist 0
02-19 15:34:26.988 7397-13691/tv.danmaku.ijk.media.sample W/IJKMEDIA: No trailing CRLF found in HTTP header.
02-19 15:34:27.092 7397-13691/tv.danmaku.ijk.media.sample D/IJKMEDIA: Format mpegts probed with size=2048 and score=100
02-19 15:34:27.096 7397-13691/tv.danmaku.ijk.media.sample D/IJKMEDIA: stream=0 stream_type=1b pid=100 prog_reg_desc=
02-19 15:34:27.096 7397-13691/tv.danmaku.ijk.media.sample D/IJKMEDIA: stream=1 stream_type=f pid=101 prog_reg_desc=
02-19 15:34:27.096 7397-13691/tv.danmaku.ijk.media.sample D/IJKMEDIA: Before avformat_find_stream_info() pos: 0 bytes read:9747 seeks:0
02-19 15:34:27.176 7397-13691/tv.danmaku.ijk.media.sample D/IJKMEDIA: no picture 
02-19 15:34:27.316 7397-13691/tv.danmaku.ijk.media.sample D/IJKMEDIA: skip whole frame, skip left: 0
02-19 15:34:27.684 7397-13691/tv.danmaku.ijk.media.sample D/IJKMEDIA: All info found
02-19 15:34:27.688 7397-13691/tv.danmaku.ijk.media.sample D/IJKMEDIA: After avformat_find_stream_info() pos: 203228 bytes read:203607 seeks:0 frames:57
02-19 15:34:27.692 7397-13691/tv.danmaku.ijk.media.sample E/IJKMEDIA: Option ijkinject-opaque not found.
02-19 15:34:27.696 7397-13691/tv.danmaku.ijk.media.sample D/IJKMEDIA: Before avformat_find_stream_info() pos: 77 bytes read:77 seeks:0
02-19 15:34:27.728 7397-13691/tv.danmaku.ijk.media.sample D/IJKMEDIA: no picture 
02-19 15:34:27.768 7397-13691/tv.danmaku.ijk.media.sample D/IJKMEDIA: skip whole frame, skip left: 0
02-19 15:34:27.772 7397-13691/tv.danmaku.ijk.media.sample D/IJKMEDIA: All info found
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample D/IJKMEDIA: After avformat_find_stream_info() pos: 77 bytes read:77 seeks:0 frames:57
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: max_frame_duration: 10.000
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: Input #0, hls,applehttp, from 'http://gslb.otvcloud.com/otv/yfy/1/79/BF/00000001345/index.m3u8':
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA:   Duration: 
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: 00:25:00.00
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: , start: 
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: 1.458667
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: , bitrate: 
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: N/A
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA:   Program 0 
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA:     Metadata:
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA:       variant_bitrate : 
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: 2300000
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA:     Stream #0:0
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample D/IJKMEDIA: , 21, 1/90000
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: : Video: h264 (High), 4 reference frames ([27][0][0][0] / 0x001B), yuv420p(left), 1920x1080 (1920x1088) [SAR 1:1 DAR 16:9], 1/50
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: , 
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: 25 fps, 
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: 25 tbr, 
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: 90k tbn, 
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: 50 tbc
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA:     Metadata:
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA:       variant_bitrate : 
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: 2300000
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA:     Stream #0:1
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample D/IJKMEDIA: , 36, 1/90000
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: : Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 90 kb/s
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA:     Metadata:
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA:       variant_bitrate : 
02-19 15:34:27.788 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: 2300000
02-19 15:34:27.804 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
02-19 15:34:27.804 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_Android_AudioTrack: ENCODING_PCM_16BIT
02-19 15:34:27.816 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(1.000000,0.000000)
02-19 15:34:27.816 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: audio_session_id = 22
02-19 15:34:27.820 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: AudioCodec: avcodec, aac
02-19 15:34:27.820 7397-13729/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_RunThread: [13729] ff_audio_dec
02-19 15:34:27.832 7397-13691/tv.danmaku.ijk.media.sample I/IJKMEDIA: VideoCodec: avcodec, h264
02-19 15:34:27.832 7397-13691/tv.danmaku.ijk.media.sample W/IJKMEDIA: fps: 25.000000 (normal)
02-19 15:34:27.832 7397-13691/tv.danmaku.ijk.media.sample W/IJKMEDIA: fps: 25.000000 (normal)
02-19 15:34:27.832 7397-13689/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_VIDEO_SIZE_CHANGED: 1920, 1080
02-19 15:34:27.832 7397-13689/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_SAR_CHANGED: 1, 1
02-19 15:34:27.832 7397-13689/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_PREPARED
02-19 15:34:27.832 7397-13689/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_PREPARED:
02-19 15:34:27.832 7397-13728/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_RunThread: [13728] ff_aout_android
02-19 15:34:27.832 7397-13733/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_RunThread: [13733] ff_video_dec
02-19 15:34:27.832 7397-13689/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_VIDEO_ROTATION_CHANGED: 0
02-19 15:34:27.880 7397-7397/tv.danmaku.ijk.media.sample I/zsq: onPrepared...Duration: 25:00
02-19 15:34:27.880 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_start
02-19 15:34:27.880 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_start()
02-19 15:34:27.880 7397-13689/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
02-19 15:34:27.880 7397-7397/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_start()=0
02-19 15:34:27.880 7397-13689/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START: start on fly
02-19 15:34:27.892 7397-7397/tv.danmaku.ijk.media.sample I/zsq: onInfo... what: 10001 ,extra: 0
02-19 15:34:27.892 7397-7397/tv.danmaku.ijk.media.sample D/IjkVideoView: MEDIA_INFO_VIDEO_ROTATION_CHANGED: 0
                                                                         
                                                                         [ 02-19 15:34:27.896  7397: 7397 E/         ]
                                                                         SurfaceView doesn't support rotation (0)!
02-19 15:34:27.932 7397-13689/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
02-19 15:34:27.932 7397-13689/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START: start on fly
02-19 15:34:27.940 7397-13729/tv.danmaku.ijk.media.sample D/IJKMEDIA: skip whole frame, skip left: 0
02-19 15:34:27.972 7397-13730/tv.danmaku.ijk.media.sample D/IJKMEDIA: no picture 
02-19 15:34:27.996 7397-13731/tv.danmaku.ijk.media.sample D/IJKMEDIA: no picture 
02-19 15:34:28.208 7397-13733/tv.danmaku.ijk.media.sample D/IJKMEDIA: SDL_VoutFFmpeg_CreateOverlay(w=1920, h=1080, fmt=RV32(0x32335652, dp=0x5a6898b0)
02-19 15:34:28.208 7397-13689/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_VIDEO_SIZE_CHANGED: 1920, 1080
02-19 15:34:28.288 7397-13733/tv.danmaku.ijk.media.sample D/IJKMEDIA: Video: first frame decoded
02-19 15:34:28.296 7397-13690/tv.danmaku.ijk.media.sample D/IJKMEDIA: ANativeWindow_setBuffersGeometry: w=1920, h=1080, f=(0x4) => w=1920, h=1080, f=RV32(0x32335652)
02-19 15:34:28.312 7397-13689/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_VIDEO_SIZE_CHANGED: 1920, 1080
02-19 15:34:28.320 7397-13728/tv.danmaku.ijk.media.sample D/IJKMEDIA: Using fltp internally between filters
02-19 15:34:28.320 7397-13728/tv.danmaku.ijk.media.sample D/IJKMEDIA: avcodec/Audio: first frame decoded
02-19 15:34:28.320 7397-13689/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_AUDIO_RENDERING_START:
02-19 15:34:28.380 7397-7397/tv.danmaku.ijk.media.sample I/zsq: onInfo... what: 10002 ,extra: 0
02-19 15:34:28.380 7397-7397/tv.danmaku.ijk.media.sample D/IjkVideoView: MEDIA_INFO_AUDIO_RENDERING_START:
02-19 15:34:28.408 7397-13733/tv.danmaku.ijk.media.sample D/IJKMEDIA: SDL_VoutFFmpeg_CreateOverlay(w=1920, h=1080, fmt=RV32(0x32335652, dp=0x5a6898b0)
02-19 15:34:28.408 7397-13689/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_VIDEO_RENDERING_START:
02-19 15:34:28.504 7397-13689/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_VIDEO_SIZE_CHANGED: 1920, 1080
02-19 15:34:28.544 7397-7397/tv.danmaku.ijk.media.sample I/tv.danmaku.ijk.media.player.IjkMediaPlayer: Info: MEDIA_INFO_VIDEO_RENDERING_START
02-19 15:34:28.544 7397-7397/tv.danmaku.ijk.media.sample I/zsq: onInfo... what: 3 ,extra: 0
02-19 15:34:28.596 7397-7397/tv.danmaku.ijk.media.sample D/IjkVideoView: MEDIA_INFO_VIDEO_RENDERING_START:
02-19 15:34:28.640 7397-13733/tv.danmaku.ijk.media.sample D/IJKMEDIA: SDL_VoutFFmpeg_CreateOverlay(w=1920, h=1080, fmt=RV32(0x32335652, dp=0x5a6898b0)

**Comment by bbcallen** [comment]
1080p seems too high for your device.
