### ISSUE TITLE
Android 使用硬解码暂停偶发性报错

### ISSUE THREAD

**Issue by zhousuqiang** [Bilibili/ijkplayer#938]
02-19 17:43:33.508 7702-7702/tv.danmaku.ijk.media.sample E/MediaPlayer: error (-2147483648, 0)
02-19 17:43:33.708 7702-7702/tv.danmaku.ijk.media.sample E/MediaPlayer: Attempt to call getDuration without a valid mediaplayer
02-19 17:43:33.708 7702-7702/tv.danmaku.ijk.media.sample E/MediaPlayer: error (-38, 0)
02-19 17:43:33.712 7702-7702/tv.danmaku.ijk.media.sample E/MediaPlayer: Error (-2147483648,0)

**Comment by XiaoXunLu** [comment]
我也遇到了，播放网络视频的时候 偶尔视频流出现丢包的情况下 播放器就一直无法加载出视频
