### ISSUE TITLE
Audio crackling sound on Nexus 5

### ISSUE THREAD

**Issue by laminsk** [Bilibili/ijkplayer#941]
Hi 

I've been testing the player using local mp3 file on the device and randomly getting crackling pops (like having your mobile next to PC speaker!) during the playback. It's completely random and not seeing any error in logcat either. It's noticeable when you have the headphones on.  I'm testing the player purely for audio streaming only. I've tried using both (mediacodec and opensles)  and still no joy. Disable the video options doesnt help either. 
         
mMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER,"vn",1);
mMediaPlayer).setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER,"nodisp",1);

It also happens when streaming directly from web.  

http://thesixteendigital.com.s3.amazonaws.com/testfiles/Hallelujah.mp3

Is there any recommended settings for audio streaming only?

Thanks in advance.

**Comment by bbcallen** [comment]
Why don't you use android.media.MediaPlayer for mp3 files?

**Comment by laminsk** [comment]
Thanks for the reply. Main reason not using builtin media player is buffer control. Static pops are still randomly happening but less so if I don't specify mediacodec/opensles in IjkMediaPlayer.OPT_CATEGORY_PLAYER. Does it mean it's using ffmpeg to playback the audio? Should I disable these for audio playback only?

mMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER,"vn",1);
mMediaPlayer).setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER,"nodisp",1);

I'd be mainly using the player for rtsp/http audio streams, should there be any settings I should disable/enable for my use case.

Many Thanks.

**Comment by bbcallen** [comment]
opensles is audio output, not audio decoder. Default  audio output module is AudioTrack.
If you mean 'decode', ijkplayer always decode audio with ffmpeg.

You need these settings, only if you want to disable video track in stream.

Default settings are the most common settings. I don't know there are anything else you need to enable/disable. There are too many options in FFmpeg, you should always check FFmpeg's document or the implement, if you wang to disable/enable one.

**Comment by laminsk** [comment]
Thanks very much for reply. I'm completely new to FFmpeg & native programming in android and this project is a great learning source for me. I will dive further into FFmpeg documentation and see what I can do to improve the playback issue. One more question please if you don't mind. Any idea how to compile with latest FFmpeg 3.0 with ijkplayer  (perhaps new libavcodec might fix the issue)?  

If it's well beyond my knowledge, do you have any plan to upgrading the project to FFmpeg 3.0?

Many thanks.

**Comment by bbcallen** [comment]
I don't think crackling sound is related to decoder. Do you have same problem with AudioTrack?

There are some API changes in FFmpeg 3.0, I doubt if ijkplayer can upgrade smoothly.
I don't have any upgrade schedule in 2 or 3 weeks.

**Comment by laminsk** [comment]
Thanks for the reply. If I use exoplayer to test it, there's no problem. Please correct me if I'm wrong, but it seems, exoplayer also using AudioTrack. I'm just curious whether upgrading to FFmpeg 3.0 might fix the problem. I completely understand if you don't have time to upgrade to FFmpeg 3.0 for now but I'd be most grateful if you could spare some time in future. Thanks.

**Comment by Android4MediaPlayer** [comment]
Any log?

**Comment by bbcallen** [comment]
It's very unlikely that FFmpeg 3.0 could fix this.

**Comment by laminsk** [comment]
D/J4A: J4ALoader: OK: 'android.os.Build$VERSION' loaded
D/J4A: J4ALoader: OK: 'android.os.Build' loaded
D/J4A: J4ALoader: OK: 'java.nio.Buffer' loaded
D/J4A: J4ALoader: OK: 'java.nio.ByteBuffer' loaded
D/J4A: J4ALoader: OK: 'java.util.ArrayList' loaded
I/J4A: API-Level: 19
D/J4A: J4ALoader: OK: 'android.media.AudioTrack' loaded
J4ALoader: OK: 'android.media.MediaCodec$BufferInfo' loaded
J4ALoader: OK: 'android.media.MediaCodec' loaded
J4ALoader: OK: 'android.media.MediaFormat' loaded
J4ALoader: Ignore: 'android.media.PlaybackParams' need API 19
J4ALoader: OK: 'android.os.Bundle' loaded
J4ALoader: OK: 'tv.danmaku.ijk.media.player.misc.IMediaDataSource' loaded
J4ALoader: OK: 'tv.danmaku.ijk.media.player.IjkMediaPlayer' loaded
D/dalvikvm: Trying to load lib /data/app-lib/net.audiotest.ijktest-2/libijkplayer.so 0x42634d80
D/dalvikvm: Added shared lib /data/app-lib/net.audiotest.ijktest-2/libijkplayer.so 0x42634d80
D/IJKMEDIA: IjkMediaPlayer_native_init
D/IJKMEDIA: IjkMediaPlayer_native_setup
I/IJKMEDIA: av_version_info: ff2.8--ijk0.4.4.1--dev0.3.3--rc7
D/IJKMEDIA: ffpipeline_create_from_android()
D/IJKMEDIA: ijkmp_set_inject_opaque(0x1d20044e)
D/IJKMEDIA: ijkmp_set_inject_opaque()=void
D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
D/IJKMEDIA: IjkMediaPlayer_setOptionLong
D/IJKMEDIA: IjkMediaPlayer_setOptionLong
D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(3)
D/IJKMEDIA: moncleanup
D/IJKMEDIA: IjkMediaPlayer_setDataSourceCallback
V/IJKMEDIA: setDataSourceCallback: 488637526
D/IJKMEDIA: ijkmp_set_data_source(url="ijkmediadatasource:488637526")
D/IJKMEDIA: ijkmp_set_data_source(url="ijkmediadatasource:488637526")=0
D/IJKMEDIA: IjkMediaPlayer_prepareAsync
D/IJKMEDIA: ijkmp_prepare_async()
I/IJKMEDIA: ===== versions =====
net.audiotest.ijktest I/IJKMEDIA: SDL_RunThread: [4552] ff_msg_loop
I/IJKMEDIA: FFmpeg       : ff2.8--ijk0.4.4.1--dev0.3.3--rc7
I/IJKMEDIA: libavutil    : 54.31.100
I/IJKMEDIA: libavcodec   : 56.60.100
I/IJKMEDIA: libavformat  : 56.40.101
I/IJKMEDIA: libswscale   : 3.1.101
I/IJKMEDIA: libswresample: 1.2.101
I/IJKMEDIA: ===== options =====
I/IJKMEDIA: player-opts : vn                           = 1
I/IJKMEDIA: player-opts : nodisp                       = 1
I/IJKMEDIA: format-opts : ijkinject-opaque             = 488637518
I/IJKMEDIA: ===================
D/IJKMEDIA: message_loop
D/IJKMEDIA: FFP_MSG_FLUSH:
I/IJKMEDIA: SDL_RunThread: [4553] ff_vout
D/IJKMEDIA: ijkmp_prepare_async()=0
I/IJKMEDIA: SDL_RunThread: [4554] ff_read
D/dalvikvm: GC_FOR_ALLOC freed 201K, 2% free 17264K/17500K, paused 11ms, total 11ms

D/IJKMEDIA: Format mp3 probed with size=131072 and score=51
D/IJKMEDIA: id3v2 ver:3 flags:00 len:74361
D/IJKMEDIA: pad 576 876
I/IJKMEDIA: Skipping 0 bytes of junk at 75415.
E/IJKMEDIA: Option ijkinject-opaque not found.
D/IJKMEDIA: Before avformat_find_stream_info() pos: 75415 bytes read:132360 seeks:0
D/IJKMEDIA: demuxer injecting skip 1105 / discard 0
D/IJKMEDIA: skip 1105 / discard 0 samples due to side data
D/IJKMEDIA: skip 1105/1152 samples
I/IJKMEDIA: max_analyze_duration 5000000 reached at 5015510 microseconds st:0
W/IJKMEDIA: Could not find codec parameters for stream 1 (Video: mjpeg, 1 reference frame, none): unspecified size
                                                                Consider increasing the value for the 'analyzeduration' and 'probesize' options
D/IJKMEDIA: After avformat_find_stream_info() pos: 279191 bytes read:279240 seeks:0 frames:195
I/IJKMEDIA: max_frame_duration: 10.000
I/IJKMEDIA: Input #0, mp3, from 'ijkmediadatasource:488637526':
I/IJKMEDIA:   Metadata:
I/IJKMEDIA:     title           : 
I/IJKMEDIA: Hallelujah (Chorus)
I/IJKMEDIA:     artist          : 
I/IJKMEDIA: The Sixteen - Harry Christophers
I/IJKMEDIA:     album           : 
I/IJKMEDIA: Messiah
I/IJKMEDIA:     genre           : 
I/IJKMEDIA: Choral
I/IJKMEDIA:     composer        : 
I/IJKMEDIA: George Frideric Handel
I/IJKMEDIA:     track           : 
I/IJKMEDIA: 21/31
I/IJKMEDIA:     disc            : 
I/IJKMEDIA: 02/03
I/IJKMEDIA:     album_artist    : 
I/IJKMEDIA: The Sixteen - Harry Christophers
I/IJKMEDIA:     date            : 
I/IJKMEDIA: 2008
I/IJKMEDIA:   Duration: 
I/IJKMEDIA: 00:03:55.86
I/IJKMEDIA: , start: 
I/IJKMEDIA: 0.025056
I/IJKMEDIA: , bitrate: 
I/IJKMEDIA: 322 kb/s
I/IJKMEDIA:     Stream #0:0
D/IJKMEDIA: , 194, 1/14112000
I/IJKMEDIA: : Audio: mp3, 44100 Hz, stereo, s16p, 320 kb/s
I/IJKMEDIA:     Metadata:
I/IJKMEDIA:       encoder         : 
I/IJKMEDIA: LAME3.98r
I/IJKMEDIA:     Side data:
I/IJKMEDIA:       
I/IJKMEDIA: replaygain: 
I/IJKMEDIA: track gain - 
I/IJKMEDIA: -5.000000
I/IJKMEDIA: , 
I/IJKMEDIA: track peak - 
I/IJKMEDIA: unknown
I/IJKMEDIA: , 
I/IJKMEDIA: album gain - 
I/IJKMEDIA: unknown
I/IJKMEDIA: , 
I/IJKMEDIA: album peak - 
I/IJKMEDIA: unknown
I/IJKMEDIA: , 
I/IJKMEDIA:     Stream #0:1
D/IJKMEDIA: , 1, 1/90000
I/IJKMEDIA: : Video: mjpeg, 1 reference frame, none
I/IJKMEDIA: , 
I/IJKMEDIA: 90k tbr, 
I/IJKMEDIA: 90k tbn, 
I/IJKMEDIA: 90k tbc
I/IJKMEDIA:     Metadata:
I/IJKMEDIA:       comment         : 
I/IJKMEDIA: Cover (front)
I/IJKMEDIA: SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
I/IJKMEDIA: SDL_Android_AudioTrack: ENCODING_PCM_16BIT
I/IJKMEDIA: SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(1.000000,0.000000)
I/IJKMEDIA: audio_session_id = 556
I/IJKMEDIA: AudioCodec: avcodec, mp3
I/IJKMEDIA: SDL_RunThread: [4572] ff_audio_dec
D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_PREPARED
D/IJKMEDIA: FFP_MSG_PREPARED:
D/IJKMEDIA: ffp_toggle_buffering_l: start
D/IJKMEDIA: FFP_MSG_BUFFERING_START:
net.audiotest.ijktest D/IJKMEDIA: IjkMediaPlayer_start
net.audiotest.ijktest D/IJKMEDIA: ijkmp_start()
net.audiotest.ijktest D/IJKMEDIA: ijkmp_start()=0
D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START: start on fly
D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START: start on fly
D/IJKMEDIA: skip 1105 / discard 0 samples due to side data
D/IJKMEDIA: skip 1105/1152 samples
I/IJKMEDIA: SDL_RunThread: [4571] ff_aout_android
D/IJKMEDIA: ffp_toggle_buffering_l: end
D/IJKMEDIA: FFP_MSG_BUFFERING_END:
D/IJKMEDIA: Using s16p internally between filters
D/IJKMEDIA: avcodec/Audio: first frame decoded
D/IJKMEDIA: FFP_MSG_AUDIO_RENDERING_START:
D/IJKMEDIA: demuxer injecting skip 0 / discard 347

**Comment by laminsk** [comment]
Thanks for looking into this. Strange thing is the moment usb cable is disconnected from the device, the static pops are no longer there. I've tested with different cables & use alternative USB ports but the result is surprisingly the same. The noise comes back when usb cable is attached to the device. Any idea?

**Comment by bbcallen** [comment]
No idea at all.

**Comment by laminsk** [comment]
Thanks. On another topic, currently ffmpeg audio cache size can access from java but I'm wondering what's the best approach if I want to access the actual cache natively. Basically write the cache to disk without using custom datasource. What I'm trying to achieve is encrypt cache using openssl library. Any thoughts? 

Many thanks in advance.

**Comment by bbcallen** [comment]
Get familiar with FFmpeg first.

**Comment by laminsk** [comment]
Thanks. I think it will be very useful feature to have a java method like this "SavePlayerBuffer(file location, fileType)".

**Comment by bbcallen** [comment]
I agree.
Patch welcome.
