### ISSUE TITLE
Could I get decode data from player?

### ISSUE THREAD

**Issue by powpi2000** [Bilibili/ijkplayer#942]
Sorry , I just want to know that could i add function to get decode data for streamig?
If I got direction,I would like to add this function in ijkplaer
because I want to make thumbnail or save streaming data in local file

**Comment by bbcallen** [comment]
search avcodec_decode_video2

**Comment by powpi2000** [comment]
Thank for reply.
Could I use lib pipeline to get avpacket data ,so  that I can get streaming data.
Because I seen you write this lib for pipe data direct to android mediacodec or  ffmpeg codecs to decode data.
So I want to use this

**Comment by bbcallen** [comment]
It's not designed as public API.
But you are free to do what you want, to the source code.

**Comment by powpi2000** [comment]
Okay
but could you tell me,where is you send pipe data to android surface?
It's really thank you for reply
I hope I can help this project!!

**Comment by bbcallen** [comment]
Search SDL_AMediaCodecJava_releaseOutputBuffer

**Comment by powpi2000** [comment]
I search SDL_AMediaCodecJava_releaseOutputBuffer ,It seem to put android surface to C (ffplay generate scree), If I want to pull data back into android ,how should I do?
SDL_AMediaCodec_Opaque *opaque is dataframe?
what kind data type in android I can put AMediaCodec_Opaque in?

**Comment by bbcallen** [comment]
You have no access to the buffer if AMediaCodec is configured with a Surface.

**Comment by powpi2000** [comment]
Because I want get stream data to android So that I can do some job in android (like save record stream , take snapshot).
Please give more hint

**Comment by bbcallen** [comment]
Why don't you call FFmpeg directly?
