### ISSUE TITLE
断开WiFi,无法使用移动流量继续播放

### ISSUE THREAD

**Issue by yeshibuzhong** [Bilibili/ijkplayer#943]
是否有接口可以实现网络切换时影片继续播放的接口.

**Comment by bbcallen** [comment]
No such API, yet.

**Comment by jinyunfeng** [comment]
网络切换后不支持继续播放，是吗？

**Comment by yeshibuzhong** [comment]
不支持吧

**Comment by UC10D** [comment]
哥哥们现在是怎么处理的？

**Comment by yeshibuzhong** [comment]
我现在是重新创建一个播放器

**Comment by UC10D** [comment]
这样切换的过程，播放有影响吗？ 直接seekto？还是？

**Comment by yeshibuzhong** [comment]
我这边使用流量会有弹框,点击确定之后会移除播放器然后重新创建一个然后seekto

**Comment by UC10D** [comment]
reset 吗？

**Comment by UC10D** [comment]
播放连接流畅吗

**Comment by yeshibuzhong** [comment]
肯定会先出现黑屏,然后加载,不过你可以先截屏作为过渡动画

**Comment by UC10D** [comment]
能给个邮箱吗？好方便联系。。。

**Comment by yeshibuzhong** [comment]
83061601@qq.com

**Comment by dourgulf** [comment]
我的做法也是截屏重新创建播放器

**Comment by yeshibuzhong** [comment]
不过到现在我还有一个问题就是在弱网情况下点击播放视频,还没请求到视频数据就退出播放,这个时候如果网络突然变好,就是这个时候有可能会出现开始播放刚才的视频.  具体表现为在其他界面,但是视频有声音

**Comment by yeshibuzhong** [comment]
以上几位兄弟,  你们做视频播放应该也有做后台下载吧,能否留一下qq咱们谈论一下这个后台下载

**Comment by yeshibuzhong** [comment]
@dourgulf  @UC10D

**Comment by Chauvetok** [comment]
我切换网络后会重新创建播放器，但是发现切换4G时，视频会很卡，但是切换为wifi就很正常，手机网络都是正常的，有碰到这样的吗
