### ISSUE TITLE
ios端，开始播放的时候总是直接在播放状态了，而不是暂停等待播放状态，如何解决？....非常感谢~

### ISSUE THREAD

**Issue by DanielYQ** [Bilibili/ijkplayer#944]
问题同title,就是ios的demo在填写了url进入在线视频播放页面后，直接就开始播放,无法将初始状态调为等待播放界面....请问如何解决？...
 
Thank you very much!

**Comment by bbcallen** [comment]
search shouldAutoplay

**Comment by DanielYQ** [comment]
我把IJKVideoViewController.m中的self.player.shouldAutoplay设置为NO，可是初始的播放器界面是灰色的，没有视频，直到我点击了播放按钮才会出现视频...这是怎么回事啊。。
非常感谢！

**Comment by bbcallen** [comment]
duplicated with #945

**Comment by DanielYQ** [comment]
初始界面应该是视频播放的一个静态图像，可以看到视频的第一秒的截图，然后点击之后开始播放，现在是直接弹出一个灰色的空无一物的播放界面，没有任何图像。。。

**Comment by DanielYQ** [comment]
Thanks a lot..

**Comment by TomandWinnie** [comment]
> search shouldAutoplay

如果将shouldAutoplay设置NO,不调用play仅仅调用prepareToPlay还是会自动播放
