### ISSUE TITLE
I have a question with the ios demo...

### ISSUE THREAD

**Issue by DanielYQ** [Bilibili/ijkplayer#945]
I have a question with the ios demo...When i input the url of video ,the player will be playing in the next viewcontroller...But the common situation is that the player is pause,it will be playing until pressing the button of play.

How can i solve the problem?

Thank you very much~

**Comment by bbcallen** [comment]
search shouldAutoplay

**Comment by DanielYQ** [comment]
but after i set shouldAutoplay NO,the interface of player is grey until press the button of play...

**Comment by bbcallen** [comment]
Isn't that what you want?

**Comment by DanielYQ** [comment]
but the common situation is a static image of the video,not a grey image without anything...

**Comment by bbcallen** [comment]
ijkplayer doesn't guarantee that.
Maybe you can implement what you want with step_to_next_frame_l() in ff_ffplay.c

**Comment by DanielYQ** [comment]
oh oh,thank you~ I will have a try...

**Comment by TomandWinnie** [comment]
> oh oh,thank you~ I will have a try...

您好，关于您的这个问题具体是怎么解决的呢？
