### ISSUE TITLE
video seek problem

### ISSUE THREAD

**Issue by wuketidai** [Bilibili/ijkplayer#946]
The video can seek on AndroidMediaPlayer and ijkExoMediaPlayer, but it doesn't work on ijkMediaPlayer.

Is it encoding setting problem or player problem?

[newyear.mp4.zip](https://github.com/Bilibili/ijkplayer/files/140178/newyear.mp4.zip)

**Comment by bbcallen** [comment]
Cann't seek with ffplay, too.
Seems any FFmpeg issue.

**Comment by Android4MediaPlayer** [comment]
The video can seek.

**Comment by yuazhen** [comment]
FFmpeg cannot seek accurately with a "large I frame interval".
Maybe you can try a smaller GOP size in the encoding settings. This will decrease the I frame interval and increase the video bitrate.
