### ISSUE TITLE
Question about video quality on TV BOX.

### ISSUE THREAD

**Issue by sofifather** [Bilibili/ijkplayer#947]
Hi.added ijkplayer into my app.App plays live streaming video.But while stream is 720p quality have a problem with squares on playback screen.Is it builded ffmpeg on low characteristics or my device cannot render 720p stream normally?Sorry for bad english))))device characteristics: 
Output resolution	480i/p, 576i/p, 720p,1080i/p
System	SoC：Amlogic S805
	CPU：ARM Quad Cortex-A5 up to 1.5GHz(DVFS)  
	GPU：Quad-core Mali-450 up to 600MHz+ (DVFS)
	DRAM：DDDR3 1G
	Flash ：MLC 4G (Optional 8G )
Operation system	Android4.4
3D	Hardward 3D graphics acceleration 
Network	RJ45 Interface 10M/100M/1000M adaptive
	Build in Wi-Fi 2.4G 802.11b/g/n.
	Support most external 3G/4G USB dongle.
Video	"Decoder：
H.265, H.264 AVC/VC-1, WMV/VC-S, AVS, WebM, RMVB, HD MPEG 1/2/4, MJPEG, H.263, DivX 3/4/5/6, Xvid, RealVideo 8/9/10,VP6, VP8  up to 1080P. "
	"Format：
MKV, WMV, TS, M2TS, MOV, MP4, RM, RMVB, AVI, MPG, MPEG, DAT, VOB, FLV ,ISO"
Audio	"Decoder：
MPEG 1/2/2.5, Audio Layer 1/2/3, WMA Version 4, 4.1, 7, 8, 9,  WMA Pro, PCM, Vorbis, Flac, ALAC, APE, AAC-LC, AAC-HE, Real Audio . "
	
	"Format：
MP3, WMA, WAV, OGG, M4A, MP4, AAC, APE, FLAC, ALAC, MPEG, MP1, MP2, MPA, RM, DTS."
Subtitle formats	Support SMI, SRT, SSA, ASS,SUB, SUB+IDX, ISO Navigation      
Photo formats	Support HD JPEG/BMP/GIF/PNG/TIFF

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/search?q=skip-loop-filter&type=Issues&utf8=✓

BTW: I don't think Cortex-A5 is fast enough to playback 720p well with software decoder.

**Comment by sofifather** [comment]
Thanks for answer.I need to use hardware decoder?

**Comment by bbcallen** [comment]
I would prefer android.media.MediaPlayer on such devices.

**Comment by sofifather** [comment]
Ok.Thanks for answer.!!!
