### ISSUE TITLE
in iOS Simulator, video is out of sync with audio when IJKMediaDemo plays "Online Samples"

### ISSUE THREAD

**Issue by SterlingOnLoop** [Bilibili/ijkplayer#948]
To reproduce:

1. open the IJKMediaDemo project
2. run it in an iPhone 6 iOS 9.2 simulator
3. tap "Online Samples"
4. choose any option and wait for it to begin playing

The video plays at approximately half the speed of the audio.

To compare, run it on a real iPhone. Notice that you hear a low pitched tone when the video flashes the word "Bop!" and a high pitched tone when the video flashes the word "Bip!"

**Comment by bbcallen** [comment]
Actually, I don't run ijkplayer on simulator much, since it's much slower that real device.
