### ISSUE TITLE
Compile on Ubuntu with Errors

### ISSUE THREAD

**Issue by liuyuejinqiu** [Bilibili/ijkplayer#949]
tools/do-compile-ffmpeg.sh: 第 302 行: cd: /home/lifq/ijkplayer-android-master/android/contrib/ffmpeg-armv7a: 没有那个文件或目录

**Comment by liuyuejinqiu** [comment]
lifq@ubuntu:~$ cd ijkplayer-android-master
lifq@ubuntu:~/ijkplayer-android-master$ cd android
lifq@ubuntu:~/ijkplayer-android-master/android$ cd contrib
lifq@ubuntu:~/ijkplayer-android-master/android/contrib$ ./compile-ffmpeg.sh clean
====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a arm64 x86 x86_64
FF_ACT_ARCHS = FF_ACT_ARCHS_64

lifq@ubuntu:~/ijkplayer-android-master/android/contrib$ ./compile-ffmpeg.sh all
====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a arm64 x86 x86_64
FF_ACT_ARCHS = armv5 armv7a arm64 x86 x86_64

====================
[*] check env armv5
====================
build on Linux x86_64
ANDROID_SDK=/home/lifq/android-sdk-linux/
ANDROID_NDK=/home/lifq/android-ndk-r10e/
NDKr10e-rc4 (64-bit) detected

--------------------
[*] make NDK standalone toolchain
--------------------
Copying prebuilt binaries...
Copying sysroot headers and libraries...
Copying c++ runtime headers and libraries...
Copying files to: /home/lifq/ijkplayer-android-master/android/contrib/build/ffmpeg-armv5/toolchain
Cleaning up...
Done.

--------------------
[*] check ffmpeg env
--------------------

--------------------
[*] configurate ffmpeg
--------------------
tools/do-compile-ffmpeg.sh: 第 302 行: cd: /home/lifq/ijkplayer-android-master/android/contrib/ffmpeg-armv5: 没有那个文件或目录
lifq@ubuntu:~/ijkplayer-android-master/android/contrib$

**Comment by bbcallen** [comment]
Did you run "./init-android.sh"?

**Comment by liuyuejinqiu** [comment]
Yes, it can produce errors when I run it ,as follows:

tools/pull-repo-ref.sh: 第 11 行: cd: android/contrib/ffmpeg-armv5: 没有那个文件或目录
Counting objects: 19338, done.
Compressing objects: 100% (5214/5214), done.
Writing objects: 100% (19338/19338), done.
Total 19338 (delta 11953), reused 19338 (delta 11953)
./init-android.sh: 第 34 行: cd: android/contrib/ffmpeg-armv5: 没有那个文件或目录

**Comment by liuyuejinqiu** [comment]
How could this be？

**Comment by bbcallen** [comment]
There must be something wrong before that, please paste whole log from very beginning.

**Comment by liuyuejinqiu** [comment]
Thank you,the issue has  been resolved,It is a problem of Git command,as follows: 
 " error: unknown option `dissociate'  "

But,I have another question about the example of the player,What is the link between ijkplayer-exo and ijkplayer ?  When I use ijkplayer-exo or native exoplayer, what’s the differences between two?

**Comment by bbcallen** [comment]
ijkplayer-exo is a wrapper of exoplayer.
ijkplayer is a wrapper of ffplay.

**Comment by liuyuejinqiu** [comment]
Thank you!

**Comment by cqEguil** [comment]
@liuyuejinqiu How did you solve this problem?

**Comment by liuyuejinqiu** [comment]
@cqEguil Find the file "pull-repo-ref.sh"  in "~/ijkplayer-android/tools " 
  delete“--dissociate”
 git clone **--dissociate** --reference $REF_REPO $REMOTE_REPO $LOCAL_WORKSPACE

**Comment by cqEguil** [comment]
Oh, thanks! Actually I've already solved the problem by uprating my git client, the option 'dissociate' is supported by the new version!
