### ISSUE TITLE
视频延迟的问题，来求教了

### ISSUE THREAD

**Issue by xiaoyepadzhang** [Bilibili/ijkplayer#95]
你好bbcallen，我刚开始接触ijkplayer，在使用的过程中，发现在播放很多m3u8文件的时候，出现视频延迟的问题：
    音频很流畅。但是感觉视频每秒的帧数很低，但是很匀称像是在慢放的感觉，在demo例子中偶尔还会出现中间的buffering白圈飞快的闪烁的(可能是缓存不上来)。就导致了视频和音频的不同步，然后在翻阅历史issue时，看到了如下解决方法：
 #define DEFAULT_MAX_HIGH_WATER_MARK_IN_MS       (0)
 #define DEFAULT_NORMAL_HIGH_WATER_MARK_IN_MS    (0)
 #define DEFAULT_FAST_HIGH_WATER_MARK_IN_MS      (0)

尝试过之后发现，从效果上来看并没有太大区别。来问下有什么修改的空间吗，谢谢！

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
