### ISSUE TITLE
IOS --》 No codec could be found with id 86052

### ISSUE THREAD

**Issue by wpfcool** [Bilibili/ijkplayer#951]
播放rtmp时只有图像没有声音。报No codec could be found with id 86052 这个是什么问题！

**Comment by bbcallen** [comment]
It means the codec is not included in build.
https://github.com/Bilibili/ijkplayer#before-build

**Comment by wpfcool** [comment]
这个过程我操作了啊https://github.com/Bilibili/ijkplayer#before-build。
cd config
rm module.sh
ln -s module-default.sh module.sh
# cd ios
sh compile-ffmpeg clean

**Comment by bbcallen** [comment]
Then, you have to find out what codec it is, and add it to config.h manually.

**Comment by wpfcool** [comment]
不明白啊  config.h 这个文件是哪个，找了一遍没找到，能举个简单的例子吗 谢谢

**Comment by bbcallen** [comment]
Er, I mean module.sh

**Comment by Lohan-Ferreira** [comment]
Did you solve it or found what codec is referenced by 86052 ?

**Comment by wpfcool** [comment]
没找到编解码器
