### ISSUE TITLE
android 使用ffconcat，seek后进度混乱。

### ISSUE THREAD

**Issue by kkiluya** [Bilibili/ijkplayer#954]
你好作者，感谢提供了一个这么好用的库。

我使用ffconcat拼接测试的视频，在seek到除一个文件时长外的文件的时候，无法seek到正确的位置，基本上都是定位到下一个文件的开头处。
我在PC上用ffplay的时候，不会出现这样的问题。
在IOS上面也是使用同样的库，不会出现问题。

测试地址 ：video.iyotv.com/test/ff.ffconcat
播放的时候，点击大概7分钟的位置，进度条会跳到12：00处，但是实际上视频播放的是6：00位置的视频。点击19分钟位置，会调到36分钟的位置。

测试使用库自带的sample。

**Comment by bbcallen** [comment]
Same problem exists in iOS demo.
I would say this is very likely a FFmpeg issue.
Most because segments' timestamp are not start from 0.

**Comment by Android4MediaPlayer** [comment]
My tested result is OK.

**Comment by kkiluya** [comment]
@bbcallen 
thank you for your reply
but it could work well on windows.
any ideas?

the ios is use  "ijk-r0.2.1-dev" version  work well.

**Comment by bbcallen** [comment]
"ijk-r0.2.1-dev" depends on a different version of FFmpeg (n2.4)

**Comment by kkiluya** [comment]
this is a ffempg issue.
I replaced the ffmpeg concatdec.c whth older version

concatdec.c link:
https://github.com/FFmpeg/FFmpeg/blob/db64af639559c80668bf4fca2768fd8f7aeb43e9/libavformat/concatdec.c

this version concatdec  whitout inpoint and outpoint features

it work well now

**Comment by bbcallen** [comment]
Maybe you could find out what broken that, and submit a patch to FFmpeg.

**Comment by george5613** [comment]
In my version of .ffconcat file I found that the inpoint maybe cause the problem and it could be fix by set the inpoint to the "start_time" of your current segment video , which in my version I use ffprobe to get this duration. I think maybe it would help.
