### ISSUE TITLE
VTDecoderCallback crash

### ISSUE THREAD

**Issue by maytrue** [Bilibili/ijkplayer#955]
Hi, 

ijkplayer sometimes crash when VTDecoderCallback , and sourceFrameRefCon address = 0x1, and it crash only in ios 9.

**Comment by samirchen** [comment]
@maytrue I met the same problem: crash in VTDecoderCallback. Have you solved it?

**Comment by maytrue** [comment]
NO, I have not found any solution.

2016-05-24 10:14 GMT+08:00 Samir <notifications@github.com>:

**Comment by samirchen** [comment]
@bbcallen @maytrue 
I got some information about this crash:
Sometimes, VTDecoderCallback will get OSStatus with value -12911(kVTVideoDecoderMalfunctionErr), and it returned. And the next time VTDecoderCallback is called, the app crashed.

With these information, could you give some tips to fix it?

**Comment by cysgit** [comment]
@samirchen 
How to reproduce this crash to get that information?
We meet the same problem, but we cannot reproduce it.

**Comment by samirchen** [comment]
@cysgit 
Cannot reproduce. It is a random crash.

**Comment by Naituw** [comment]
Same issue here. I added some workaround then the crash gone:
1. Check `OSStatus status` before dereference `sourceFrameRefCon` (aka `sample_info`)
2. Explicit check value of `sourceFrameRefCon`, if it's `0x1`, treat it as NULL

**Comment by cdkr** [comment]
@Naituw could you please comment your code or make a PR?

**Comment by xinzhengzhang** [comment]
Try k0.7.4

**Comment by Singsmlie** [comment]
@samirchen i try this, it seems well, i will test online
![screen shot 2017-03-16 at 11 17 07 am](https://cloud.githubusercontent.com/assets/2203075/23980363/266d1a7a-0a3a-11e7-867c-34691ad5087f.png)

**Comment by ceekay1991** [comment]
tyr this
 if( !(sourceFrameRefCon >= (void *) ctx->sample_info_array && sourceFrameRefCon <= (void *) &(ctx->sample_info_array[VTB_MAX_DECODING_SAMPLES - 1])) ) {
            return;
        }
![83d051b3a9adbbf357ccf70b0ff53933](https://cloud.githubusercontent.com/assets/4811245/26767859/2d3e9924-49d6-11e7-97eb-f974212af375.png)

**Comment by bhltyou** [comment]
@ceekay1991  请问你的问题解决了吗

**Comment by ceekay1991** [comment]
@bhltyou 解决了

**Comment by bhltyou** [comment]
@ceekay1991 ce thanks
