### ISSUE TITLE
IJKVideoView player section MP4 file only sound no picture   HELP MAN

### ISSUE THREAD

**Issue by kang2nana** [Bilibili/ijkplayer#956]
IJK VideoView player section MP4 file only sound no picture, audio-only MP4 format is as follows:
【General】
Format: MPEG-4
Format profile: Base Media
Codec ID: isom (isom)
File size: 315 MiB
Duration: 31mn 59s
Overall bit rate mode: Variable
Overall bit rate: 1 374 Kbps
Encoded date: UTC 2015-07-09 07:10:19
Tagged date: UTC 2015-07-09 07:10:19
【Video】
Format: MPEG-4 Visual
Format profile: Simple @ L1
Format settings, BVOP: No
Format settings, QPel: No
Format settings, GMC: No warppoints
Format settings, Matrix: Default (H.263)
Codec ID: 20
Duration: 31mn 59s
Bit rate mode: Variable
Bit rate: 1 247 Kbps
Maximum bit rate: 6 455 Kbps
Width: 856 pixels
Height: 480 pixels
Display aspect ratio: 16: 9
Frame rate mode: Constant
Frame rate: 15.000 fps
Color space: YUV
Chroma subsampling: 4: 2: 0
Bit depth: 8 bits
Scan type: Progressive
Compression mode: Lossy
Bits / (Pixel * Frame): 0.202
Stream size: 285 MiB (91%)
Writing library: Lavc53.8.0
Encoded date: UTC 2015-07-09 07:10:19
Tagged date: UTC 2015-07-09 07:11:24
【Audio】
Format: AAC
Format / Info: Advanced Audio Codec
Format profile: LC
Codec ID: 40
Duration: 31mn 59s
Bit rate mode: Variable
Bit rate: 126 Kbps
Maximum bit rate: 171 Kbps
Channel (s): 2 channels
Channel positions: Front: L R
Sampling rate: 44.1 KHz
Frame rate: 43.066 fps (1024 spf)
Compression mode: Lossy
Stream size: 28.7 MiB (9%)
Encoded date: UTC 2015-07-09 07:11:22
Tagged date: UTC 2015-07-09 07:11:24

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer#before-build
Modify ffmpeg build config in module.h

**Comment by kang2nana** [comment]
Thank you for your reply, I'm going to try
