### ISSUE TITLE
Ubuntu编译，缺少libijkplayer.so, libijksdl.so

### ISSUE THREAD

**Issue by xiaonia** [Bilibili/ijkplayer#957]
您好，我在Ubuntu1404下编译了好多次，一直都缺少libijkplayer.so, libijksdl.so，不知道是什么问题？

**Comment by bbcallen** [comment]
I don't know, too.

**Comment by xiaonia** [comment]
我在编译ffmpeg的Android.mk末尾修改一下，就可以了，Thxs 
include $(call all-subdir-makefiles)

include ../../../../../../ijkmedia/Android.mk
