### ISSUE TITLE
MEDIA_INFO_BUFFERING_START，每次报出这个消息就会自动停止播放

### ISSUE THREAD

**Issue by xiaofeilong** [Bilibili/ijkplayer#958]
02-24 16:13:45.978    4032-7466/tv.danmaku.ijk.media.sample D/IJKMEDIA﹕ FFP_MSG_BUFFERING_START:
02-24 16:13:45.978    4032-4032/tv.danmaku.ijk.media.sample D/IjkVideoView﹕ MEDIA_INFO_BUFFERING_START:
每次报出这个消息就会自动停止播放

**Comment by bbcallen** [comment]
So?
