### ISSUE TITLE
Audio and video not sync

### ISSUE THREAD

**Issue by scientt** [Bilibili/ijkplayer#960]
I played this video use ijkplayer-k0.2.4 without any change:
http://record.suicam.com/mult/35686-mult-20160223212540.mp4

the video and audio not sync. why ?

**Comment by bbcallen** [comment]
Maybe 1080p is too high for your device to do software decode.

**Comment by scientt** [comment]
I changed ijkplayer to k0.2.3, play the same video file , the audio and video is sync.
Maybe the k0.2.4 really have something wrong.

**Comment by bbcallen** [comment]
1080p is too high, a little change can make that different.
Better use android.media.MediaPlayer or HW decoder instead.

**Comment by scientt** [comment]
OK, thank you for your reply.
