### ISSUE TITLE
Does ijkplayer support background play for ios?

### ISSUE THREAD

**Issue by maytrue** [Bilibili/ijkplayer#961]
I find ijkplayer android support background play, but I don't know whether it works for ios.

**Comment by bbcallen** [comment]
Yes.

**Comment by maytrue** [comment]
And which api? Thanks

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/fe0fb59d3d4c5dce9590111b18dc688167c01fba/ios/IJKMediaPlayer/IJKMediaPlayer/IJKFFMoviePlayerController.h#L84

**Comment by maytrue** [comment]
I call setPauseInBackground:NO, but audio stop playing when enter backgroud.

**Comment by bbcallen** [comment]
Then, take a breakpoint, see who paused audio.

**Comment by maytrue** [comment]
Need enable Background Modes, in info.plist

**Comment by fenglinxiu** [comment]
@maytrue It is right way.

**Comment by BelindaFly** [comment]
@maytrue @bbcallen @fenglinxiu  
I call setPauseInBackground:NO, and enable Background Modes-audio..., but it doesn't work. I use Xcode8.2.1 and iPhone 6 ios10.2.
Why???

**Comment by xinzhengzhang** [comment]
enable Audio permission in background modes setting for your app

**Comment by ProFive** [comment]
Sometimes background monitoring will automatically stop after more than ten minutes
Sometimes it will auto stop background monitoring for more than one hour
Happing both android & iOS 
I used IJK_FFMPEG_COMMIT=ff4.0--ijk0.8.8--20211030--926
