### ISSUE TITLE
隐藏视频

### ISSUE THREAD

**Issue by Catherine0728** [Bilibili/ijkplayer#962]
现在，我要在同一个布局里面点击一个按钮把正在播放的视频给隐藏掉，然后显示另外一个视频播放。。。可是我仔细看了，她是会执行隐藏的那个命令，但是当第二个视频出现的时候，被隐藏的那个视频消失的画面又出现的，但是只是一个缓存的画面，不可操作。。。

**Comment by Jiang00** [comment]
我也遇到了咋搞呀
