### ISSUE TITLE
error type reported by IMediaPlayer.OnErrorListener

### ISSUE THREAD

**Issue by kengabc** [Bilibili/ijkplayer#964]
Hi 

any document about the error type reported by IMediaPlayer.onErrorListener

**Comment by bbcallen** [comment]
No, there is not any meaningful error code, yet.

**Comment by kengabc** [comment]
ok, It seems that the onError(IMediaPlayer, what, extra) has only one type of -10000, any plan to upload the detail error type?

**Comment by bbcallen** [comment]
No, I can't get more error detail from FFmpeg.

**Comment by kengabc** [comment]
thx

**Comment by satyamub** [comment]
@kengabc @bbcallen did you people find anything regarding this??

**Comment by satyamub** [comment]
setonerrorlistener never get called!!
