### ISSUE TITLE
IJK player, the image is not so nice, it's pixelated

### ISSUE THREAD

**Issue by autostoper** [Bilibili/ijkplayer#966]
When I use IJK player, the image is not so nice, it's pixelated in some areas and not so sharp. test: s805, H3, Rk3128, S905, RK3229, RK 3128 

iJK player
![1321652713-ijk player](https://cloud.githubusercontent.com/assets/17535289/13382913/192f41ee-de80-11e5-829c-25a3c86f8414.jpg)

Internal android player
![105591662-internal](https://cloud.githubusercontent.com/assets/17535289/13382914/1fc3e5d2-de80-11e5-80bf-614945dc6114.jpg)

**Comment by bbcallen** [comment]
```
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 0);
```

**Comment by vladd49** [comment]
This seems to be amlogic and MediaCodec issue, not ijkplayer. The only way to solve it is to disable MediaCodec, but decoding speed will drop drop significantly. ExoPlayer with MediaCodec also has this issue on MediaCodec.

**Comment by linwea** [comment]
how to set the option let image best？
