### ISSUE TITLE
在低端android机器上，音视频不同步，怎么设置

### ISSUE THREAD

**Issue by lyqaiym** [Bilibili/ijkplayer#967]
android原生的是跳帧
setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 1);
setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "max-fps", 1);
这两种属性设置都没作用啊
setOption(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 0);
demo是48，给成0了，也没作用

**Comment by bbcallen** [comment]
I doubt if there is anything ijkplayer can do, if android.media.MediaPlayer can't play well.

**Comment by lyqaiym** [comment]
setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 50);
以后有作用了，但是不是像demo一样在构造方法以后，设置的，是在播放成功后设置的
ff_ffplay.c的
static int get_video_frame(FFPlayer *ffp, AVFrame *frame)
方法得到ffp->framedrop，在播放前一直获得是0，播放成功后，得到是设置的值。
