### ISSUE TITLE
How to use filters?

### ISSUE THREAD

**Issue by cqEguil** [Bilibili/ijkplayer#970]
I saw some code related to avfilter in jni level, but in the repository profile you mentioned that you're not planning to work on filters right now.

I'm in bad need of it at the moment, could you tell me how far you have gone on this and what else I should do to carry on the work? Thanks a lot!

**Comment by bbcallen** [comment]
Modify config/module.sh and rebuild FFmpeg, you'll get FFmpeg with libavfilter.

**Comment by cqEguil** [comment]
Thanks a lot. I can play 3d movies with the ffmpeg filter 'stereo3d' now, though the fps goes really low when using red blue mode... Is there any option I can change to improve it?

**Comment by bbcallen** [comment]
Do some profile to find out the bottleneck.

**Comment by cqEguil** [comment]
I'll dig it out, thanks.
