### ISSUE TITLE
Android 播放m3u8格式的视频，播放过程中会自动暂停。

### ISSUE THREAD

**Issue by var1993** [Bilibili/ijkplayer#971]
播放m3u8格式的视频时，播放过程中自动暂停，log如下：
03-01 11:56:18.668 8431-8632/? I/IJKMEDIA: HLS request for url 'http://114.80.180.235/697A94B37693B813AF1FBF66E7/030001100F56CB751CF8B204B921BFE8EE5F85-67D8-420C-7517-17F4DAEFC719.flv.ts?ts_start=126.58&ts_end=138.58&ts_seg_no=263&ts_keyframe=1', offset 0, playlist 0
03-01 11:56:18.668 8431-8632/? W/IJKMEDIA: No trailing CRLF found in HTTP header.
03-01 11:56:18.669 8431-8632/? W/IJKMEDIA: Failed to open segment of playlist 0
03-01 11:56:18.669 8431-8632/? I/IJKMEDIA: HLS request for url 'http://114.80.180.235/697A94B37693B813AF1FBF66E7/030001100F56CB751CF8B204B921BFE8EE5F85-67D8-420C-7517-17F4DAEFC719.flv.ts?ts_start=138.58&ts_end=145.1&ts_seg_no=264&ts_keyframe=1', offset 0, playlist 0
03-01 11:56:18.669 8431-8632/? W/IJKMEDIA: No trailing CRLF found in HTTP header.
03-01 11:56:18.670 8431-8632/? W/IJKMEDIA: Failed to open segment of playlist 0
03-01 11:56:20.570 8431-8659/? D/IJKMEDIA: Unknown NAL code: 0 (1424 bits)
03-01 11:56:26.570 8431-8659/? D/IJKMEDIA: unknown SEI type 37
03-01 11:56:26.570 8431-8659/? D/IJKMEDIA: Unknown NAL code: 0 (1424 bits)
03-01 11:56:32.575 8431-8659/? D/IJKMEDIA: Unknown NAL code: 0 (1424 bits)
03-01 11:56:38.575 8431-8659/? D/IJKMEDIA: unknown SEI type 37
03-01 11:56:38.575 8431-8659/? D/IJKMEDIA: Unknown NAL code: 0 (1424 bits)
03-01 11:56:44.576 8431-8659/? D/IJKMEDIA: Unknown NAL code: 0 (1424 bits)
03-01 11:56:50.577 8431-8659/? D/IJKMEDIA: unknown SEI type 37
03-01 11:56:50.577 8431-8659/? D/IJKMEDIA: Unknown NAL code: 0 (1424 bits)
03-01 11:56:56.579 8431-8659/? D/IJKMEDIA: Unknown NAL code: 0 (1424 bits)
03-01 11:57:00.792 8431-8659/? D/IJKMEDIA: bytestream overread -7
03-01 11:57:00.792 8431-8659/? E/IJKMEDIA: error while decoding MB 45 22, bytestream -7
03-01 11:57:00.792 8431-8659/? I/IJKMEDIA: concealing 1384 DC, 1384 AC, 1384 MV errors in P frame
03-01 11:57:02.125 8431-8632/? I/IJKMEDIA: ffp_toggle_buffering: completed: OK
03-01 11:57:02.125 8431-8630/? D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_COMPLETED
03-01 11:57:02.125 8431-8630/? D/IJKMEDIA: FFP_MSG_COMPLETED:
03-01 11:57:03.135 8431-8632/? I/IJKMEDIA: ffp_toggle_buffering: eof

**Comment by bbcallen** [comment]
```
03-01 11:56:18.670 8431-8632/? W/IJKMEDIA: Failed to open segment of playlist 0
```
That's all.

**Comment by var1993** [comment]
@bbcallen 
1、是优酷的一个视频地址，我用ios版本的ijkplayer和android版本的ijkplayer同时播放这一个地址，android版本的ijkplayer在播放过程中有概率会出现暂停，而iOS版本的ijkplayer不会出现暂停。

2、按道理来讲，视频源都是一样的，android版本的出现自动暂停，ios版本的也应该出现问题才对啊。

3、03-01 11:56:18.670 8431-8632/? W/IJKMEDIA: Failed to open segment of playlist 0 ，这条log信息，用ijkplayer播放优酷的任何视频都会出现此log。

4、
03-01 11:57:00.792 8431-8659/? D/IJKMEDIA: bytestream overread -7
03-01 11:57:00.792 8431-8659/? E/IJKMEDIA: error while decoding MB 45 22, bytestream -7
03-01 11:57:00.792 8431-8659/? I/IJKMEDIA: concealing 1384 DC, 1384 AC, 1384 MV errors in P frame
03-01 11:57:02.125 8431-8632/? I/IJKMEDIA: ffp_toggle_buffering: completed: OK
03-01 11:57:02.125 8431-8630/? D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_COMPLETED
03-01 11:57:02.125 8431-8630/? D/IJKMEDIA: FFP_MSG_COMPLETED:
03-01 11:57:03.135 8431-8632/? I/IJKMEDIA: ffp_toggle_buffering: oef
这段log中有说：concealing 1384 DC, 1384 AC, 1384 MV errors in P frame，P帧发生错误，是不是因为这个原因呢？

**Comment by bbcallen** [comment]
1. I don't know.
2. Did you test on exact same git revision?
4. I don't know.

**Comment by var1993** [comment]
@bbcallen 这跟 git 的版本有什么关系？

**Comment by bbcallen** [comment]
I mean git repo revision, not git client revision.

**Comment by nanguaSky** [comment]
@var1993 我出现的问题跟你一样，请问你解决了吗？
