### ISSUE TITLE
How can use rtmp play only audio without video?

### ISSUE THREAD

**Issue by kungercn** [Bilibili/ijkplayer#972]
I need a function: When I play rtmp url,I can change to play only audio and not play video!Thanks

**Comment by bbcallen** [comment]
setSurface(NULL)

**Comment by kungercn** [comment]
@bbcallen thanks!But I forget to say that I dont want to receive the video data.

**Comment by bbcallen** [comment]
You can't.

**Comment by kungercn** [comment]
Thank your repley.   May I said not clearly.  If I do what you said,do I waste my flow because of the video data?

**Comment by bbcallen** [comment]
Yes.

**Comment by kungercn** [comment]
Can I do that dont receive the video data to save my flow? @bbcallen

**Comment by bbcallen** [comment]
No.

**Comment by kungercn** [comment]
This is a blog about rtmp ,http://blog.csdn.net/defonds/article/details/17534903.  Can I send the NetStream command about receiveAudio? But I cant find the interface in your codes @bbcallen

**Comment by bbcallen** [comment]
No.
I'm not familiar with RTMP.
You are free to modify what you want.

**Comment by kungercn** [comment]
Thank all the same!  @bbcallen
