### ISSUE TITLE
android端播放过程中视频停播，MP4、m3u8都会出现。

### ISSUE THREAD

**Issue by jinyunfeng** [Bilibili/ijkplayer#974]
log如下
        3-01 17:02:00.358 8837-8837/? D/SizeAdaptiveLayout: com.android.internal.widget.SizeAdaptiveLayout{44add620 V.E..... ......ID 0,0-929,130 #7f0800bc app:id/adaptive}child view android.widget.FrameLayout{44b8bbd0 V.E..... ......ID 0,0-929,129 #10202d6 android:id/status_bar_latest_event_content} measured out of bounds at 129px clamped to 130px
03-01 17:02:00.368 8837-8837/? D/SizeAdaptiveLayout: com.android.internal.widget.SizeAdaptiveLayout{454ab9c0 V.E..... ......ID 0,0-929,130 #7f0800bc app:id/adaptive}child view android.widget.FrameLayout{454b0fa8 V.E..... ......ID 0,0-929,129 #10202d6 android:id/status_bar_latest_event_content} measured out of bounds at 129px clamped to 130px
03-01 17:02:01.208 960-9470/? D/Ulp_jni: Location CB invoked
03-01 17:02:01.378 4468-4468/? W/libc: pthread_create failed: couldn't allocate 1040384-byte stack: Out of memory
03-01 17:02:01.378 4468-4468/? E/dalvikvm: pthread_create (stack size 16384 bytes) failed: Try again
03-01 17:02:01.388 18744-19014/? E/IJKMEDIA: AVC: nal size 2163
03-01 17:02:01.388 18744-19014/? E/IJKMEDIA: AVC: nal size 2163
03-01 17:02:01.388 18744-19014/? E/IJKMEDIA: no frame!
03-01 17:02:01.448 4468-4468/? W/libc: pthread_create failed: couldn't allocate 1040384-byte stack: Out of memory
03-01 17:02:01.448 4468-4468/? E/dalvikvm: pthread_create (stack size 16384 bytes) failed: Try again
03-01 17:02:01.708 18744-18996/? I/IJKMEDIA: ffp_toggle_buffering: error: -104
03-01 17:02:01.708 18744-18994/? D/IJKMEDIA: FFP_MSG_ERROR: 0
03-01 17:02:01.708 18744-18996/? I/IJKMEDIA: ffp_toggle_buffering: eof
03-01 17:02:01.708 18744-18744/? E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
03-01 17:02:01.978 960-979/? I/PPPOEService: NetdCallbackReceiver onEvent 601601 limit alert globalAlert wlan0
03-01 17:02:02.048 960-8744/? D/ConnectivityServiceHSM: Actual State: DefaultConnectivityState, Current State: DefaultConnectivityState.processMessage what=112
03-01 17:02:02.078 224-790/? I/AudioFlinger: BUFFER TIMEOUT: remove(4097) from active list on thread 0xb3f6d008
03-01 17:02:02.988 4468-4468/? W/libc: pthread_create failed: couldn't allocate 1040384-byte stack: Out of memory
03-01 17:02:02.988 4468-4468/? E/dalvikvm: pthread_create (stack size 16384 bytes) failed: Try again
03-01 17:02:03.078 4468-4468/? W/libc: pthread_create failed: couldn't allocate 1040384-byte stack: Out of memory
03-01 17:02:03.078 4468-4468/? E/dalvikvm: pthread_create (stack size 16384 bytes) failed: Try again
03-01 17:02:04.118 232-232/? V/WLAN_PSA: NL MSG, len[048], NL type[0x11] WNI type[0x5050] len[028]
03-01 17:02:04.588 4468-4468/? W/libc: pthread_create failed: couldn't allocate 1040384-byte stack: Out of memory
03-01 17:02:04.588 4468-4468/? E/dalvikvm: pthread_create (stack size 16384 bytes) failed: Try again
03-01 17:02:04.608 224-790/? D/audio_hw_primary: out_standby: enter: stream (0xb80c8228) usecase(0: deep-buffer-playback)
03-01 17:02:04.678 4468-4468/? W/libc: pthread_create failed: couldn't allocate 1040384-byte stack: Out of memory
03-01 17:02:04.678 4468-4468/? E/dalvikvm: pthread_create (stack size 16384 bytes) failed: Try again
03-01 17:02:04.798 224-790/? I/listen_hal_loader: audio_extn_listen_update_stream_status(): uc_id 0 of type 0 for Event 2, with Raise=1
03-01 17:02:04.798 224-790/? V/listen_hw: listen_hw_notify_event: Enter
03-01 17:02:04.798 224-790/? V/listen_hw: handle_notify_event: Enter, event type = 2
03-01 17:02:04.798 224-790/? D/listen_hw: handle_notify_event: tx_active 0, rx_active 0
03-01 17:02:04.798 224-790/? V/listen_hw: handle_notify_event: Exit
03-01 17:02:04.798 224-790/? D/hardware_info: hw_info_append_hw_type : device_name = speaker
03-01 17:02:04.798 224-790/? I/listen_hal_loader: audio_extn_listen_update_device_status(): device 0x2 of type 0 for Event 0, with Raise=0
03-01 17:02:04.798 224-790/? V/EffectDiracSound: DiracSound_command() start, cmdCode=22
03-01 17:02:04.798 224-790/? V/EffectDiracSound: DiracSound_Command EFFECT_CMD_SET_AUDIO_STANDBY, current mode = 0
03-01 17:02:06.198 4468-4468/? W/libc: pthread_create failed: couldn't allocate 1040384-byte stack: Out of memory
03-01 17:02:06.198 4468-4468/? E/dalvikvm: pthread_create (stack size 16384 bytes) failed: Try again
03-01 17:02:06.308 4468-4468/? W/libc: pthread_create failed: couldn't allocate 1040384-byte stack: Out of memory
03-01 17:02:06.308 4468-4468/? E/dalvikvm: pthread_create (stack size 16384 bytes) failed: Try again
03-01 17:02:06.308 3943-3947/? D/dalvikvm: GC_CONCURRENT freed 1941K, 29% free 16157K/22492K, paused 2ms+3ms, total 39ms
03-01 17:02:07.878 8837-8837/? D/PhoneStatusBar: updateNotification pkg=com.qihoo.appstore;id=489348
03-01 17:02:07.888 4468-4468/? W/libc: pthread_create failed: couldn't allocate 1040384-byte stack: Out of memory
03-01 17:02:07.888 4468-4468/? E/dalvikvm: pthread_create (stack size 16384 bytes) failed: Try again
03-01 17:02:07.958 4468-4468/? W/libc: pthread_create failed: couldn't allocate 1040384-byte stack: Out of memory
03-01 17:02:07.958 4468-4468/? E/dalvikvm: pthread_create (stack size 16384 bytes) failed: Try again
03-01 17:02:07.958 8837-8837/? D/SizeAdaptiveLayout: com.android.internal.widget.SizeAdaptiveLayout{424c4420 V.E..... ......ID 0,0-929,130 #7f0800bc app:id/adaptive}child view android.widget.RelativeLayout{424e7ea8 V.E..... ......ID 0,0-929,128} measured out of bounds at 129px clamped to 130px
03-01 17:02:07.998 8837-8837/? D/PhoneStatusBar: updateNotification pkg=com.qihoo.appstore;id=489348
03-01 17:02:08.008 3989-3989/? W/ContextImpl: Implicit intents with startService are not safe: Intent { act=com.qihoo.notification.Stat } android.content.ContextWrapper.startService:494 com.qihoo.notification.NotificationReceiver.onReceive:-1 android.app.LoadedApk$ReceiverDispatcher$Args.run:761 
03-01 17:02:08.048 8837-8837/? D/SizeAdaptiveLayout: com.android.internal.widget.SizeAdaptiveLayout{424c4420 V.E..... ......ID 0,0-929,130 #7f0800bc app:id/adaptive}child view android.widget.RelativeLayout{424e7ea8 V.E..... ......ID 0,0-929,128} measured out of bounds at 129px clamped to 130px
03-01 17:02:08.068 4468-4468/? W/libc: pthread_create failed: couldn't allocate 1040384-byte stack: Out of memory
03-01 17:02:08.068 4468-4468/? E/dalvikvm: pthread_create (stack size 16384 bytes) failed: Try again
03-01 17:02:08.088 3943-3947/? D/dalvikvm: GC_CONCURRENT freed 1959K, 29% free 16157K/22492K, paused 2ms+3ms, total 38ms
03-01 17:02:08.118 3989-3993/? D/dalvikvm: GC_CONCURRENT freed 1916K, 35% free 14678K/22488K, paused 3ms+2ms, total 23ms
03-01 17:02:08.118 3989-3989/? D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 14ms
03-01 17:02:08.128 3989-3989/? W/ContextImpl: Implicit intents with startService are not safe: Intent { act=com.qihoo.notification.Stat } android.content.ContextWrapper.startService:494 com.qihoo.notification.NotificationReceiver.onReceive:-1 android.app.LoadedApk$ReceiverDispatcher$Args.run:761 
03-01 17:02:08.188 4468-4468/? W/libc: pthread_create failed: couldn't allocate 1040384-byte stack: Out of memory
03-01 17:02:08.188 4468-4468/? E/dalvikvm: pthread_create (stack size 16384 bytes) failed: Try again
03-01 17:02:09.128 232-232/? V/WLAN_PSA: NL MSG, len[048], NL type[0x11] WNI type[0x5050] len[028]
03-01 17:02:09.318 358-358/? D/mdb_debug: services.c:service_to_fd[L-285]: mdbd recive msg: tcp:3880
03-01 17:02:09.328 358-358/? D/mdb_debug: services.c:service_to_fd[L-285]: mdbd recive msg: shell:cat "/sys/class/power_supply/battery/capacity"
03-01 17:02:09.328 19302-19302/? E/mdb_debug: services.c:create_subprocess[L-196]: unable to open /proc/19302/oom_adj: 13, Permission denied
03-01 17:02:09.338 358-358/? E/mdb_debug: fdevent.c:fdevent_subproc_event_func[L-461]: subproc_fd 19 cleared from fd_table: 5, I/O error
03-01 17:02:09.348 358-358/? D/mdb_debug: services.c:service_to_fd[L-285]: mdbd recive msg: shell:df "/data"
03-01 17:02:09.348 19304-19304/? E/mdb_debug: services.c:create_subprocess[L-196]: unable to open /proc/19304/oom_adj: 13, Permission denied
03-01 17:02:09.378 358-358/? D/mdb_debug: services.c:service_to_fd[L-285]: mdbd recive msg: shell:df "/mnt/sdcard"
03-01 17:02:09.378 19307-19307/? E/mdb_debug: services.c:create_subprocess[L-196]: unable to open /proc/19307/oom_adj: 13, Permission denied
03-01 17:02:09.398 358-358/? E/mdb_debug: fdevent.c:fdevent_subproc_event_func[L-461]: subproc_fd 19 cleared from fd_table: 5, I/O error
03-01 17:02:09.408 358-358/? D/mdb_debug: services.c:service_to_fd[L-285]: mdbd recive msg: shell:getprop "ro.build.display.id"
03-01 17:02:09.408 19310-19310/? E/mdb_debug: services.c:create_subprocess[L-196]: unable to open /proc/19310/oom_adj: 13, Permission denied
03-01 17:02:09.528 4468-4468/? W/libc: pthread_create failed: couldn't allocate 1040384-byte stack: Out of memory
03-01 17:02:09.528 4468-4468/? E/dalvikvm: pthread_create (stack size 16384 bytes) failed: Try again
03-01 17:02:09.568 4468-4468/? W/libc: pthread_create failed: couldn't allocate 1040384-byte stack: Out of memory
03-01 17:02:09.568 4468-4468/? E/dalvikvm: pthread_create (stack size 16384 bytes) failed: Try again
03-01 17:02:10.338 358-358/? D/mdb_debug: services.c:service_to_fd[L-285]: mdbd recive msg: tcp:3880
03-01 17:02:10.338 358-358/? D/mdb_debug: services.c:service_to_fd[L-285]: mdbd recive msg: shell:cat "/sys/class/power_supply/battery/capacity"
03-01 17:02:10.348 19315-19315/? E/mdb_debug: services.c:create_subprocess[L-196]: unable to open /proc/19315/oom_adj: 13, Permission denied
03-01 17:02:10.358 358-358/? E/mdb_debug: fdevent.c:fdevent_subproc_event_func[L-461]: subproc_fd 19 cleared from fd_table: 5, I/O error
03-01 17:02:10.368 358-358/? D/mdb_debug: services.c:service_to_fd[L-285]: mdbd recive msg: shell:df "/data"
03-01 17:02:10.368 19317-19317/? E/mdb_debug: services.c:create_subprocess[L-196]: unable to open /proc/19317/oom_adj: 13, Permission denied
03-01 17:02:10.388 358-358/? D/mdb_debug: services.c:service_to_fd[L-285]: mdbd recive msg: shell:df "/mnt/sdcard"
03-01 17:02:10.388 19320-19320/? E/mdb_debug: services.c:create_subprocess[L-196]: unable to open /proc/19320/oom_adj: 13, Permission denied
03-01 17:02:10.408 358-358/? E/mdb_debug: fdevent.c:fdevent_subproc_event_func[L-461]: subproc_fd 19 cleared from fd_table: 5, I/O error
03-01 17:02:10.418 358-358/? D/mdb_debug: services.c:service_to_fd[L-285]: mdbd recive msg: shell:getprop "ro.build.display.id"
03-01 17:02:10.418 19323-19323/? E/mdb_debug: services.c:create_subprocess[L-196]: unable to open /proc/19323/oom_adj: 13, Permission denied
03-01 17:02:10.438 358-358/? E/mdb_debug: fdevent.c:fdevent_subproc_event_func[L-461]: subproc_fd 19 cleared from fd_table: 5, I/O error
03-01 17:02:11.168 4468-4468/? W/libc: pthread_create failed: couldn't allocate 1040384-byte stack: Out of memory
03-01 17:02:11.168 4468-4468/? E/dalvikvm: pthread_create (stack size 16384 bytes) failed: Try again
03-01 17:02:11.208 4468-4468/? W/libc: pthread_create failed: couldn't allocate 1040384-byte stack: Out of memory
03-01 17:02:11.208 4468-4468/? E/dalvikvm: pthread_create (stack size 16384 bytes) failed: Try again
03-01 17:02:11.208 960-9470/? D/Ulp_jni: Location CB invoked

这个问题出现在什么地方，怎么解决？

**Comment by bbcallen** [comment]
```
03-01 17:02:01.708 18744-18744/? E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
```

**Comment by jinyunfeng** [comment]
我看到了这句，当不知道为什么会出现这个报错

**Comment by Android4MediaPlayer** [comment]
OOM

**Comment by jinyunfeng** [comment]
oom有点抽象，能不能再具体一点

**Comment by bbcallen** [comment]
What's the matter with "OOM"?

**Comment by Android4MediaPlayer** [comment]
Out of memory

**Comment by q979713444** [comment]
我也遇到了，不知道是不是线程开多了就这样，楼主解决了么》求告知，多谢
