### ISSUE TITLE
百度统计捕获的异常

### ISSUE THREAD

**Issue by gawinghe** [Bilibili/ijkplayer#975]
decode_interrupt_cb (in ) (ff_ffplay.c:2395)
ff_poll_interrupt (in ) (network.c:152)
ff_listen_connect (in ) (network.c:258)
tcp_open (in ) (tcp.c:141)

**Comment by gawinghe** [comment]
Signal SIGSEGV was raised

**Comment by maorongsen** [comment]
同楼上，经常崩溃
0	AGVideoPro	decode_interrupt_cb	[ff_ffplay.c line 2351]
1	AGVideoPro	ff_check_interrupt	[avio.c line 603]
2	AGVideoPro	ff_poll_interrupt	[network.c line 152]
3	AGVideoPro	ff_listen_connect	[network.c line 258]
4	AGVideoPro	tcp_open	[tcp.c line 141]
5	AGVideoPro	ffurl_connect	[avio.c line 202]
6	AGVideoPro	ffurl_open	[avio.c line 303]
7	AGVideoPro	http_open_cnx	[http.c line 216]
8	AGVideoPro	http_open	[http.c line 498]
9	AGVideoPro	ffurl_connect	[avio.c line 198]
10	AGVideoPro	ffurl_open	[avio.c line 303]
11	AGVideoPro	avio_open2	[aviobuf.c line 920]
12	AGVideoPro	avformat_open_input	[utils.c line 355]
13	AGVideoPro	read_thread	[ff_ffplay.c line 2426]
14	AGVideoPro	SDL_RunThread	[ijksdl_thread_ios.m line 31]
15	libsystem_pthread.dylib
16	libsystem_pthread.dylib
17	libsystem_pthread.dylib

**Comment by bbcallen** [comment]
Which version are you using?
