### ISSUE TITLE
when run ./compile-ffmpeg.sh all，got error：Invalid platform name: android-21

### ISSUE THREAD

**Issue by haika** [Bilibili/ijkplayer#978]
Error detail is as below：
Invalid platform name: android-21
Please use --platform=<name> with one of: android-13 android-14 android-15 android-16 android-17 android-18 android-19 android-3 android-4 android-5 android-8 android-9

And I had isntalled android sdk platform: android-21

Someone knows the reason？
Thanks~

**Comment by cqEguil** [comment]
NDK version is too old, I guess.

**Comment by haika** [comment]
The NDK version is android-ndk-r9b

**Comment by cqEguil** [comment]
Compiling *.so file uses ndk, not sdk. Im using r10e, you can have a try.

**Comment by haika** [comment]
I think Im using ndk too. I just clone the project from github without any change.

**Comment by haika** [comment]
It's ok when I update ndk to version r10e, thanks @cqEguil
