### ISSUE TITLE
how to set the options of ijkplayer so i can play rtmp video without too much delay

### ISSUE THREAD

**Issue by zwy2937** [Bilibili/ijkplayer#979]
IJKFFOptions *options = [IJKFFOptions optionsByDefault];
    [options setFormatOptionValue:@"ijktcphook" forKey:@"http-tcp-hook"];
    [options setOptionIntValue:IJK_AVDISCARD_DEFAULT forKey:@"skip_frame" ofCategory:kIJKFFOptionCategoryCodec];
    [options setOptionIntValue:IJK_AVDISCARD_DEFAULT forKey:@"skip_loop_filter" ofCategory:kIJKFFOptionCategoryCodec];

i want to know what's the function of these code ,and i want to cut down the delay time when playing trmp video ~plz help me~~~thanks much

**Comment by bbcallen** [comment]
Sorry, I'm not quite familiar with RTMP.
