### ISSUE TITLE
VideoToolBox Hardware Decoding App Store rejected

### ISSUE THREAD

**Issue by jakehan** [Bilibili/ijkplayer#980]
Hi ,
VideoToolBox.framework is pubilic since iOS8,if i use this framework for accessing hardware decoder/encoder directly on iOS8+ and before iOS8 fall back to software decoding/encoding, wether or not my app can sandbox and update to app store??? have any idea???

**Comment by bbcallen** [comment]
I'm not a lawyer, you should ask Apple.

**Comment by jakehan** [comment]
i asked Apple several days ago and has not response yet. do you know any player app on App Store with videotoolbox hardware decoding/encoding? i googled for couple of weeks for this quesiton and has not anwser.

**Comment by jakehan** [comment]
@bbcallen  i asked Apple several days ago and has not response yet. do you know any player app on App Store with videotoolbox hardware decoding/encoding? i googled for couple of weeks for this quesiton and has not anwser.

**Comment by bbcallen** [comment]
No, I don't. They never tell me.
