### ISSUE TITLE
【Solved】bash error on Mac when building android -- caused by git 1.9, solved by upgrading git to 2.6

### ISSUE THREAD

**Issue by jubincn** [Bilibili/ijkplayer#982]
mac os version:  10.9.5

abstract：
error executing ./compile-ffmpeg.sh all 
tools/do-compile-ffmpeg.sh: line 302: cd: /Users/jubin/GetFun/source/ijkplayer-android/android/contrib/ffmpeg-armv5: No such file or directory

contrib git:(latest) ✗ ./compile-ffmpeg.sh all  
====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a arm64 x86 x86_64
FF_ACT_ARCHS = armv5 armv7a arm64 x86 x86_64

====================
[*] check env armv5
====================
build on Darwin x86_64
ANDROID_SDK=/Users/jubin/DevTool/adt-bundle-23.0.2/sdk
ANDROID_NDK=/Users/jubin/DevTool/android-ndk-r10e
NDKr10e (64-bit) detected

--------------------
[*] make NDK standalone toolchain
--------------------
Copying prebuilt binaries...
Copying sysroot headers and libraries...
Copying c++ runtime headers and libraries...
Copying files to: /Users/jubin/GetFun/source/ijkplayer-android/android/contrib/build/ffmpeg-armv5/toolchain
Cleaning up...
Done.

--------------------
[*] check ffmpeg env
--------------------

--------------------
[*] configurate ffmpeg
--------------------
tools/do-compile-ffmpeg.sh: line 302: cd: /Users/jubin/GetFun/source/ijkplayer-android/android/contrib/ffmpeg-armv5: No such file or directory

**Comment by bbcallen** [comment]
Update your git client

**Comment by jubincn** [comment]
@bbcallen 谢谢回复。不过没看懂啥意思。。。

**Comment by bbcallen** [comment]
brew install git

**Comment by jubincn** [comment]
@bbcallen My git is 1.9.3 and I upgraded to 2.6.3, will it work?

**Comment by bbcallen** [comment]
I don't know, you tell me.

**Comment by jubincn** [comment]
it works, thanks! @bbcallen  However, I installed git through dmg file instead of brew. I guess brew will be easier since I have to configure my git to newer one in MacOS 10.9.5
