### ISSUE TITLE
prepareAsync never callback

### ISSUE THREAD

**Issue by kengabc** [Bilibili/ijkplayer#988]
Hi, I try to play a video from network, after call the IJKMediaPlayer.prepareAsync(), the onPrepared never called. 

the log as follows:

ijkplayer_log IjkMediaPlayer_prepareAsync
ijkplayer_log ijkmp_prepare_async()
ijkplayer_log ===== versions =====
ijkplayer_log FFmpeg       : ff2.8--ijk0.4.1.1--dev0.3.3--rc4
ijkplayer_log FFP_MSG_FLUSH:
ijkplayer_log libavutil    : 54.31.100
ijkplayer_log libavcodec   : 56.60.100
ijkplayer_log libavformat  : 56.40.101
ijkplayer_log libswscale   : 3.1.101
ijkplayer_log libswresample: 1.2.101
ijkplayer_log ===== options =====
ijkplayer_log player-opts : loop                         = 1
ijkplayer_log format-opts : ijkinject-opaque             = 490735014
ijkplayer_log ===================
ijkplayer_log ijkmp_prepare_async()=0

**Comment by kengabc** [comment]
video play successfully will have following log:

ijkplayer_log IjkMediaPlayer_prepareAsync
ijkplayer_log ijkmp_prepare_async()
ijkplayer_log ===== versions =====
ijkplayer_log FFmpeg : ff2.8--ijk0.4.1.1--dev0.3.3--rc4
ijkplayer_log FFP_MSG_FLUSH:
ijkplayer_log libavutil : 54.31.100
ijkplayer_log libavcodec : 56.60.100
ijkplayer_log libavformat : 56.40.101
ijkplayer_log libswscale : 3.1.101
ijkplayer_log libswresample: 1.2.101
ijkplayer_log ===== options =====
ijkplayer_log player-opts : loop = 1
ijkplayer_log format-opts : ijkinject-opaque = 490735014
ijkplayer_log ===================
ijkplayer_log ijkmp_prepare_async()=0
**ijkplayer_log SDL_Android_AudioTrack: CHANNEL_OUT_STEREO 0 0 {"nt":4}
ijkplayer_log SDL_Android_AudioTrack: ENCODING_PCM_16BIT 0 0 {"nt":4}
ijkplayer_log SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(1.000000,0.000000) 0 0 {"nt":4}
ijkplayer_log audio_session_id = 40
ijkplayer_log AudioCodec: avcodec, aac
ijkplayer_log VideoCodec: avcodec, h264
ijkplayer_log fps: 15.000000 (normal)
ijkplayer_log fps: 15.000000 (normal)
ijkplayer_log FFP_MSG_VIDEO_SIZE_CHANGED: 640, 360
ijkplayer_log FFP_MSG_SAR_CHANGED: 1, 1
ijkplayer_log ijkmp_get_msg: FFP_MSG_PREPARED
ijkplayer_log FFP_MSG_PREPARED:**


as the bold log is missing

**Comment by bbcallen** [comment]
Any code?

**Comment by kengabc** [comment]
It seems hangs in 
 mp->msg_thread = SDL_CreateThreadEx(&mp->_msg_thread, ijkmp_msg_loop, mp, "ff_msg_loop");

**as in the Method of ijkmp_prepare_async_l(IjkMediaPlayer *mp) of ijkplayer.c:**

static int ijkmp_prepare_async_l(IjkMediaPlayer *mp)
{
    assert(mp);

    MPST_RET_IF_EQ(mp->mp_state, MP_STATE_IDLE);
    // MPST_RET_IF_EQ(mp->mp_state, MP_STATE_INITIALIZED);
    MPST_RET_IF_EQ(mp->mp_state, MP_STATE_ASYNC_PREPARING);
    MPST_RET_IF_EQ(mp->mp_state, MP_STATE_PREPARED);
    MPST_RET_IF_EQ(mp->mp_state, MP_STATE_STARTED);
    MPST_RET_IF_EQ(mp->mp_state, MP_STATE_PAUSED);
    MPST_RET_IF_EQ(mp->mp_state, MP_STATE_COMPLETED);
    // MPST_RET_IF_EQ(mp->mp_state, MP_STATE_STOPPED);
    MPST_RET_IF_EQ(mp->mp_state, MP_STATE_ERROR);
    MPST_RET_IF_EQ(mp->mp_state, MP_STATE_END);

    assert(mp->data_source);

    ijkmp_change_state_l(mp, MP_STATE_ASYNC_PREPARING);

    msg_queue_start(&mp->ffplayer->msg_queue);

    // released in msg_loop
    ijkmp_inc_ref(mp);
    mp->msg_thread = SDL_CreateThreadEx(&mp->_msg_thread, ijkmp_msg_loop, mp, "ff_msg_loop");
    // msg_thread is detached inside msg_loop
    // TODO: 9 release weak_thiz if pthread_create() failed;

    int retval = ffp_prepare_async_l(mp->ffplayer, mp->data_source);
    if (retval < 0) {
        ijkmp_change_state_l(mp, MP_STATE_ERROR);
        return retval;
    }

    return 0;
}
