### ISSUE TITLE
Do ijkplayer support playback h265 video?

### ISSUE THREAD

**Issue by StayZeal** [Bilibili/ijkplayer#993]
Encoding video by h265,but ijkplayer can only decode the audio .

**Comment by Android4MediaPlayer** [comment]
#595

**Comment by StayZeal** [comment]
Get it
If you prefer less codec/format for smaller binary size (include hevc function)
```
cd config
rm module.sh
ln -s module-lite-hevc.sh module.sh
cd android/contrib
# cd ios
sh compile-ffmpeg clean
```

**Comment by StayZeal** [comment]
I follow the steps ,but it does not work
```
cd config
rm module.sh
ln -s module-lite-hevc.sh module.sh
cd android/contrib
# cd ios
sh compile-ffmpeg clean
```

`03-08 16:23:45.348 974-974/tv.danmaku.ijk.media.sample E/Parcel: Reading a NULL string not supported here.
03-08 16:23:45.394 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_native_profileBegin
03-08 16:23:45.394 974-974/tv.danmaku.ijk.media.sample W/IJKMEDIA: monstartup already called
03-08 16:23:45.438 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_native_setup
03-08 16:23:45.438 974-974/tv.danmaku.ijk.media.sample I/IJKMEDIA: av_version_info: ff2.8--ijk0.4.4.1--dev0.3.3--rc7
03-08 16:23:45.438 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: ffpipeline_create_from_android()
03-08 16:23:45.438 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_inject_opaque(0x200bde)
03-08 16:23:45.438 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_inject_opaque()=void
03-08 16:23:45.438 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
03-08 16:23:45.438 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
03-08 16:23:45.438 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
03-08 16:23:45.438 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(3)
03-08 16:23:45.438 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: moncleanup
03-08 16:23:45.438 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-08 16:23:45.438 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-08 16:23:45.438 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-08 16:23:45.438 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-08 16:23:45.438 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-08 16:23:45.438 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-08 16:23:45.438 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-08 16:23:45.438 974-974/tv.danmaku.ijk.media.sample D/tv.danmaku.ijk.media.player.IjkMediaPlayer: Couldn't open file on client side, trying server side
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample V/IJKMEDIA: setDataSource: path /storage/emulated/legacy/265.mp4
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_data_source(url="/storage/emulated/legacy/265.mp4")
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_data_source(url="/storage/emulated/legacy/265.mp4")=0
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffe1f900)
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: ffpipeline_set_surface()
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffe1f900)=void
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_prepareAsync
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_prepare_async()
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample I/IJKMEDIA: ===== versions =====
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample I/IJKMEDIA: FFmpeg       : ff2.8--ijk0.4.4.1--dev0.3.3--rc7
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample I/IJKMEDIA: libavutil    : 54.31.100
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample I/IJKMEDIA: libavcodec   : 56.60.100
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample I/IJKMEDIA: libavformat  : 56.40.101
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample I/IJKMEDIA: libswscale   : 3.1.101
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample I/IJKMEDIA: libswresample: 1.2.101
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample I/IJKMEDIA: ===== options =====
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample I/IJKMEDIA: player-opts : mediacodec                   = 0
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample I/IJKMEDIA: player-opts : opensles                     = 0
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample I/IJKMEDIA: player-opts : overlay-format               = 842225234
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample I/IJKMEDIA: player-opts : framedrop                    = 1
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample I/IJKMEDIA: player-opts : start-on-prepared            = 0
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample I/IJKMEDIA: format-opts : ijkinject-opaque             = 2100190
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample I/IJKMEDIA: format-opts : http-detect-range-support    = 0
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
03-08 16:23:45.439 974-974/tv.danmaku.ijk.media.sample I/IJKMEDIA: ===================
03-08 16:23:45.439 974-4178/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_RunThread: [4178] ff_msg_loop
03-08 16:23:45.439 974-4178/tv.danmaku.ijk.media.sample D/IJKMEDIA: message_loop
03-08 16:23:45.440 974-4178/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_FLUSH:
03-08 16:23:45.441 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_prepare_async()=0
03-08 16:23:45.441 974-4186/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_RunThread: [4186] ff_vout
03-08 16:23:45.441 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_RunThread: [4187] ff_read
03-08 16:23:45.441 974-4187/tv.danmaku.ijk.media.sample D/IJKMEDIA: Format mov,mp4,m4a,3gp,3g2,mj2 probed with size=2048 and score=100
03-08 16:23:45.441 974-4187/tv.danmaku.ijk.media.sample D/IJKMEDIA: ISO: File Type Major Brand: isom
03-08 16:23:45.447 974-4187/tv.danmaku.ijk.media.sample E/IJKMEDIA: Option ijkinject-opaque not found.
03-08 16:23:45.447 974-4187/tv.danmaku.ijk.media.sample D/IJKMEDIA: Before avformat_find_stream_info() pos: 3542181 bytes read:127798 seeks:1
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample D/IJKMEDIA: All info found
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample D/IJKMEDIA: After avformat_find_stream_info() pos: 25867 bytes read:193334 seeks:2 frames:4
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: max_frame_duration: 10.000
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/legacy/265.mp4':
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA:   Metadata:
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA:     major_brand     : 
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: isom
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA:     minor_version   : 
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: 512
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA:     compatible_brands: 
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: isomiso2mp41
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA:     title           : 
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: mpeg4
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA:     encoder         : 
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: Lavf57.26.100
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA:     comment         : 
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: mpeg4
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA:   Duration: 
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: 00:02:10.36
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: , start: 
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: 0.000000
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: , bitrate: 
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: 217 kb/s
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA:     Stream #0:0
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: (und)
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample D/IJKMEDIA: , 3, 1/10240
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: : Video: hevc, 1 reference frame (hev1 / 0x31766568), none, 640x480 (0x0), 1/10240, 196 kb/s
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: , 
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: 20 fps, 
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: 20 tbr, 
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: 10240 tbn, 
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: 10240 tbc
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA:  (default)
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA:     Metadata:
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA:       handler_name    : 
03-08 16:23:45.451 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: VideoHandler
03-08 16:23:45.452 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA:     Stream #0:1
03-08 16:23:45.452 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: (und)
03-08 16:23:45.452 974-4187/tv.danmaku.ijk.media.sample D/IJKMEDIA: , 1, 1/8000
03-08 16:23:45.452 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: : Audio: aac (LC) (mp4a / 0x6134706D), 8000 Hz, mono, fltp, 17 kb/s
03-08 16:23:45.452 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA:  (default)
03-08 16:23:45.452 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA:     Metadata:
03-08 16:23:45.452 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA:       handler_name    : 
03-08 16:23:45.452 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: SoundHandler
03-08 16:23:45.455 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_Android_AudioTrack: CHANNEL_OUT_MONO
03-08 16:23:45.455 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_Android_AudioTrack: ENCODING_PCM_16BIT
03-08 16:23:45.459 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(1.000000,0.000000)
03-08 16:23:45.459 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: audio_session_id = 276
03-08 16:23:45.459 974-4187/tv.danmaku.ijk.media.sample I/IJKMEDIA: AudioCodec: avcodec, aac
03-08 16:23:45.460 974-4191/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_RunThread: [4191] ff_aout_android
03-08 16:23:45.460 974-4187/tv.danmaku.ijk.media.sample W/IJKMEDIA: No codec could be found with id 1211250229
03-08 16:23:45.460 974-4192/tv.danmaku.ijk.media.sample I/IJKMEDIA: SDL_RunThread: [4192] ff_audio_dec
03-08 16:23:45.460 974-4192/tv.danmaku.ijk.media.sample D/IJKMEDIA: ffp_toggle_buffering_l: start
03-08 16:23:45.460 974-4178/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_PREPARED
03-08 16:23:45.460 974-4178/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_PREPARED:
03-08 16:23:45.460 974-4178/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_BUFFERING_START:
03-08 16:23:45.469 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: IjkMediaPlayer_start
03-08 16:23:45.469 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_start()
03-08 16:23:45.470 974-974/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_start()=0
03-08 16:23:45.470 974-4178/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
03-08 16:23:45.470 974-974/tv.danmaku.ijk.media.sample D/IjkVideoView: MEDIA_INFO_BUFFERING_START:
03-08 16:23:45.470 974-4178/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START: start on fly
03-08 16:23:45.504 974-997/tv.danmaku.ijk.media.sample D/OpenGLRenderer: endAllActiveAnimators on 0xe14f8600 (ListView) with handle 0xe145f2d0
03-08 16:23:45.560 974-4178/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
03-08 16:23:45.560 974-4178/tv.danmaku.ijk.media.sample D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START: start on fly
03-08 16:23:45.573 974-4187/tv.danmaku.ijk.media.sample D/IJKMEDIA: ffp_toggle_buffering_l: end
03-08 16:23:45.573 974-4178/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_BUFFERING_END:
03-08 16:23:45.573 974-974/tv.danmaku.ijk.media.sample D/IjkVideoView: MEDIA_INFO_BUFFERING_END:
03-08 16:23:45.576 974-4191/tv.danmaku.ijk.media.sample D/IJKMEDIA: Using fltp internally between filters
03-08 16:23:45.576 974-4191/tv.danmaku.ijk.media.sample D/IJKMEDIA: avcodec/Audio: first frame decoded
03-08 16:23:45.578 974-4178/tv.danmaku.ijk.media.sample D/IJKMEDIA: FFP_MSG_AUDIO_RENDERING_START:
03-08 16:23:45.579 974-974/tv.danmaku.ijk.media.sample D/IjkVideoView: MEDIA_INFO_AUDIO_RENDERING_START:
`

**Comment by StayZeal** [comment]
BTW .
this option does not work

```
cd config
rm module.sh
ln -s module-default.sh module.sh
cd android/contrib
# cd ios
sh compile-ffmpeg clean

```

**Comment by Android4MediaPlayer** [comment]
cd config
rm module.sh
ln -s module-lite-hevc.sh module.sh
cd android/contrib
# cd ios
sh compile-ffmpeg clean

**Comment by StayZeal** [comment]
@Android4MediaPlayer  Do u really understand  my question ?

**Comment by StayZeal** [comment]
I forget excute ./compile-ijk.sh all....
