### ISSUE TITLE
can i modify the source code of the ijkplayer folder and recompile ？

### ISSUE THREAD

**Issue by conhow** [Bilibili/ijkplayer#997]
如果想修改ijkplayer 目录下的.c文件中获取yuv数据在SDL上显示，改为获取YUV数据使用openGL显示可行吗？

**Comment by bbcallen** [comment]
You are free to modify what you want under LGPL 2.1 license.

**Comment by conhow** [comment]
修改代码每次重新编译ijkplayer,是否有其他方式可以一边写代码，一边调试,怎么做？

**Comment by bbcallen** [comment]
Ask your IDE vendor.

**Comment by conhow** [comment]
使用Eclipse 修改代码，每次需要重新编译为so文件进行测试？是否可以使用jni方式？

**Comment by bbcallen** [comment]
What do you mean by "jni方式".

**Comment by conhow** [comment]
android c++ with the NDK

**Comment by bbcallen** [comment]
Isn't it now?

**Comment by conhow** [comment]
我还没有开始具体操作，只是看了下项目。

**Comment by conhow** [comment]
该项目可以使用NDK方式吧。

**Comment by conhow** [comment]
你们在编写ijkplayer 将其生成.so 。是在什么开发环境做的？

**Comment by bbcallen** [comment]
http://www.apple.com/shop/buy-mac/macbook-pro

**Comment by conhow** [comment]
你们是使用什么开发工具，编写ijkmedia播放器的？

**Comment by bbcallen** [comment]
xcode, android studio, sublime text, vim, notepad++

**Comment by conhow** [comment]
步骤：修改ijkmedia部分代码后，打包.so 。再在android studio 或xcode上运行测试？
