### ISSUE TITLE
new android demo build use module-lite.sh can not play rtsp and can support rtsp protocol, and the other format play sureface is vague. who can help me? please! 

### ISSUE THREAD

**Issue by dianyou1215** [Bilibili/ijkplayer#998]

**Comment by dianyou1215** [comment]
can not  support rtsp protocol

**Comment by bbcallen** [comment]
Did you try module-default.sh?

**Comment by dianyou1215** [comment]
@bbcallen I will try module-default.sh

**Comment by dianyou1215** [comment]
@bbcallen I use module-default.sh build the demo, can not support and play rtsp also, and some of m3u8 can not play.

**Comment by dianyou1215** [comment]
@bbcallen ijk好像支持rtmp吧？使用module-default.sh 编译的so也不行，而且播放视频的时候画面不清晰有马赛克类似的雪花，怎么解决啊？大神！

**Comment by dianyou1215** [comment]
@bbcallen video is source：rtsp://218.204.223.237:554/live/1/67A7572844E51A64/f68g2mj7wjua3la7.sdp

**Comment by bbcallen** [comment]
Same problem with ffplay on PC.
